### ISSUE TITLE
More flexible admin/mod/user permissions system

### ISSUE THREAD

**Issue by Amolith** [mastodon/mastodon#10070]
- [x] Looked for similar issues and found none

## Pitch

I would like greater control over the admin/mod permissions system. [Rocket.Chat](https://rocket.chat/) is a *very* extreme example of what I would like but it is similar.

![](https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fimgur.com%2FCzvmRSN.png&f=1)
*(image found on DuckDuckGo)*

I ran Rocket.Chat for a few weeks to try it out and the number of permissions was staggering so, while more would certainly be good, too many would also be . . . well . . . too many 😆

Columns of roles and rows of permissions with a simple checkbox system of granting them would be perfect.

## Motivation

I think admins would greatly benefit from a more flexible system that lets them determine what permissions users/mods/admins have by default and what different roles can do. For example, I would like to give mods the ability to add custom emojis, prevent admins from promoting other admins, things like that.

**Comment by test2a** [comment]
any updates on this?

**Comment by Sasha-Sorokin** [comment]
@test2a as you can see, no, there were no updates single May 1, 2019. Asking this won't help issue either, 👍 reaction to the issue, however, helps to prioritize it (no guarantees given it's going to be implemented, though). Contributions are welcomed.

**Comment by Gargron** [comment]
Fixed by #18641
