### ISSUE TITLE
Webpack failing with lots of 'Error: Cannot find module 'babel-plugin-syntax-dynamic-import' - Did you mean "@babel/syntax-dynamic-import"?"

### ISSUE THREAD

**Issue by egypturnash** [mastodon/mastodon#10092]
### Expected behaviour
When I do 'RAILS_ENV=production bundle exec rails assets:precompile', webpack does its thing. 

### Actual behaviour

Webpack starts to try to do its thing, then starts vomiting a bunch of errors like this:

    Error: Cannot find module 'babel-plugin-syntax-dynamic-import' from '/Users/egypt/Documents/code/dragonstyle/mastodon'
    - Did you mean "@babel/syntax-dynamic-import"?

### Steps to reproduce the problem

1. update your local dev installation to 2.7.2
2. do all the non-docker update steps
3. RAILS_ENV=production bundle exec rails assets:precompile
4. swear a lot (optional, I've been beating my head on this for a day and a half now.)

### Specifications

v2.7.2
SHA: f3eb99aec3c2cd596c0b32fde9eff3be4579b22a

Not a front-end issue but I'm on OSX 10.14.12.

[Full error log](https://github.com/tootsuite/mastodon/files/2887348/blarg.txt)

**Comment by egypturnash** [comment]
(also see [this thread on the Discourse](https://discourse.joinmastodon.org/t/cant-get-mastodon-to-work-locally/1560)  for someone having the same issue with 2.6.5)

**Comment by egypturnash** [comment]
So this is really some total bullshit but this made the error go away, and maybe it will help the next poor bastard banging her head against this one:

yarn upgrade-interactive --latest

choose to upgrade @babel/core to 7.3.3 and babel-loader to 8.0.5

rm yarn.lock
rm -rf node_modules
yarn install

Now 'RAILS_ENV=production bundle exec rails assets:precompile'' gets through everything that failed to find babel-plugin-syntax-dynamic-import. I guess doing this cleaned out *something* that just trying to clean yarn's cache and delete node_modules/yarn.lock didn't do.

It's still aborting with *other* complaints about not being able to find postcss-import, but 'yarn add postcss-import' fixed that, and unlocked a whole new set of problems that probably belong in another issue.

**Comment by saurabhbhatia** [comment]
In line with changes in webpacker 4.0+ for Rails 6 rc1, you might want to move your `.babelrc` to `babel.config.js` which looks like the following now :

```
module.exports = function(api) {
  var validEnv = ['development', 'test', 'production']
  var currentEnv = api.env()
  var isDevelopmentEnv = api.env('development')
  var isProductionEnv = api.env('production')
  var isTestEnv = api.env('test')

  if (!validEnv.includes(currentEnv)) {
    throw new Error(
      'Please specify a valid `NODE_ENV` or ' +
        '`BABEL_ENV` environment variables. Valid values are "development", ' +
        '"test", and "production". Instead, received: ' +
        JSON.stringify(currentEnv) +
        '.'
    )
  }

  return {
    presets: [
      isTestEnv && [
        require('@babel/preset-env').default,
        {
          targets: {
            node: 'current'
          }
        }
      ],
      (isProductionEnv || isDevelopmentEnv) && [
        require('@babel/preset-env').default,
        {
          forceAllTransforms: true,
          useBuiltIns: 'entry',
          modules: false,
          exclude: ['transform-typeof-symbol']
        }
      ]
    ].filter(Boolean),
    plugins: [
      require('babel-plugin-macros'),
      require('@babel/plugin-syntax-dynamic-import').default,
      isTestEnv && require('babel-plugin-dynamic-import-node'),
      require('@babel/plugin-transform-destructuring').default,
      [
        require('@babel/plugin-proposal-class-properties').default,
        {
          loose: true
        }
      ],
      [
        require('@babel/plugin-proposal-object-rest-spread').default,
        {
          useBuiltIns: true
        }
      ],
      [
        require('@babel/plugin-transform-runtime').default,
        {
          helpers: false,
          regenerator: true
        }
      ],
      [
        require('@babel/plugin-transform-regenerator').default,
        {
          async: false
        }
      ]
    ].filter(Boolean)
  }
}
```

Also move your `postcss.yml` to `postcss.config.js`

```
module.exports = {
    plugins: [
      require('postcss-import'),
      require('postcss-flexbugs-fixes'),
      require('postcss-preset-env')({
        autoprefixer: {
          flexbox: 'no-2009'
        },
        stage: 3
      })
    ]
  }
```

**Comment by dnellutla** [comment]
Any updates on this. I am having the issue...
