### ISSUE TITLE
Latest European directive on copyright

### ISSUE THREAD

**Issue by ogmkp** [mastodon/mastodon#10123]
The latest European Parliament text on copyright requires that any content be filtered and rejected before publication.
The host becomes responsible if content is published and penalties are provided.
Can you give us some details about the technical possibilities that Mastodon can offer us regarding pre-publication approval and possible ways of knowing if a content is copyrighted ?

Thank you.

**Comment by Gargron** [comment]
It is not possible.

**Comment by maxdrash** [comment]
This directive requires platforms of any size to perform content control during the publishing process and before content appears on the platform.
If the content (piece of text, image, part of a media) is copyrighted, the host must delete the content if it does not have a license.
The situation is the same for links to media, the host must remunerate the media in case of link sharing with a tax principle.
Every Mastodon host in Europe is concerned and is legally responsible in case of misconduct.

The final vote on this text as it stands is scheduled for mid-March.
https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:52016PC0593

What are the possible ways to comply with this directive?
If there are none, Mastodon's hosts in Europe will have to close.

**Comment by m4sk1n** [comment]
leave EU asap

**Comment by Gargron** [comment]
> What are the possible ways to comply with this directive?

There aren't any. Scanning all uploaded content for copyrighted content requires a license for a copyrighted content database, which is impossible for Mastodon operators to individually negotiate and afford.

IANAL, but if the directive passes, Mastodon will become illegal to host in the EU, except for private servers for friends & family. Germany for example considers any website aimed at a general audience (larger than friends & family) to be commercial regardless of profit motives.

Please do not let the directive pass!

**Comment by phoe** [comment]
@Gargron Do you plan on making any kind of protest action on mastodon.social related to the copyright directive proposal?

**Comment by trwnh** [comment]
IANAL either but it might be possible to argue that a Mastodon instance is a "communication service" and not an "online content sharing service", although that argument would depend on whether courts agree with you. You could also argue that the "best efforts" clause is inapplicable because it would be prohibitive to work with the so-called "rights-holders", but that's also a tenuous argument. By far the only 100% surefire way to avoid liability is to not pass the new articles.

**Comment by lukepighetti** [comment]
I don't understand how any website that publishes user content would be able to comply with this. In other words, 99% of the internet?

**Comment by coreyreichle** [comment]
The thing is, small sites aren't supposed to be able comply.  Only the larger corporations like Facebook and Google.

That was the same reason for the GDPR:  To ensure only certain groups can possibly comply.

**Comment by lukepighetti** [comment]
Does that mean that small sites are exempt or that they are forced to shut down?

**Comment by coreyreichle** [comment]
It doesn't mean they are exempt.  It means they cannot comply.

**Comment by lukepighetti** [comment]
Oh. I don't really engage in conspiracy theories. "Never attribute to malice that which is adequately explained by stupidity."

**Comment by jeroenpraat** [comment]
What I understand is that non-profits are not effected by this new law. Almost all Mastodon instances are non-profits and not even businesses, so I see no problem. But maybe this should be be proven in court first.

https://juliareda.eu/wp-content/uploads/2019/02/Art_13_unofficial.pdf says:

> ‘online content sharing service provider’ means a provider of an information society service whose main or one of the main purposes is to store and give the public access to a large amount of copyright protected works or other protected subject-matter uploaded by its users which it organises and promotes **for profit-making purposes**. Providers of services such as not-for profit online encyclopedias, not-for profit educational and scientific repositories, open source software developing and sharing platforms, electronic communication service providers as defined in Directive 2018/1972 establishing the European Communications Code, online marketplaces and business-to business cloud services and cloud services which allow users to upload content for their own use shall not be considered online content sharing service providers within the meaning of this Directive.

**Comment by mynameismonkey** [comment]
First of all, it's a Directive. Not a law. Mastodon is not illegal to host. A Directive directs the 28 member states to now draft their own law to meet the Directive, and come into compliance within two years.

Secondly, while there are no distinct, clear exemptions for non-commercial interpersonal sharing; as a EU-hosted, EU-specific instance I have no concerns whatsoever about this Directive. The Directive is aimed at extracting money from large corporations currently profiting from their unfettered use of shared, copyrighted material. No lawyer for any content rights holder is going to sue a Mastodon host for the money they don't have. Worst case would be a cease and desist/takedown notice. 

Whether or not any individual host/admin wants to fight those is up to each, but copyright existed before this Directive, will continue to exist for the foreseeable future, and imposes no (new) direct responsibility on non-commercial enterprise. 

If a Mastodon host found themselves sharing copyrighted works in numbers big enough to concern the rights holders (mention is made of 5 million unique users a month or 10 million Euros annual revenue as definitional thresholds) - and if that were the case there would likely be some kind of donation or fee or somesuch to sustain such an instance - I have no doubt this Directive (or more correctly the member state law adopted by the relevant country) would be brought to bear.

This is not a defense of the Directive, it is horrible legislation, but as an Internet dinosaur of the 90s I've seen the same arguments time and again, even the US tried to create a link tax at one point. At the end of the day, content creators want their content consumed, and if the hand holding the spoon (FB, BirdSite etc) is making money, they want some of it. 

That said, as there will be 28 or so countries creating law around this, we can simply find the most friendly one and host there.

Pending actual law being drafted and passed by an EU member state I would close this issue for now.

**Comment by nemobis** [comment]
> Pending actual law being drafted and passed

That has happened in the meanwhile in most countries, see [Comparative Report on the National Implementations of Article 17 of the Directive on Copyright in the Digital Single Market](https://communia-association.org/2022/12/01/comparative-report-on-the-national-implementations-of-article-17/) at Communia.

It remains far from clear what (if anything) a fediverse admin is supposed to be doing, so it makes sense to keep this report closed until there's a clear need for changes. If/when Mastodon gGmbH makes changes in Mastodon, these will not be guaranteed to be compatible with legal requirements in other countries, so I believe that anyone who desires to install upload filters in their fediverse instance should run a fork of Mastodon (or of Pleroma or [other ActivityPub application](https://fediverse.party)).
