### ISSUE TITLE
PWA is re-initialized every time it get on screen … (iOS 12.1.4)

### ISSUE THREAD

**Issue by fooness** [mastodon/mastodon#10154]
The PWA on iOS is re-initialized every time it’s selected from either the home screen or from the app switcher. Is this (still) a problem that iOS needs to fix, or is there anything, like service workers or states in local storage, that can be done to Mastodon to fix this?

**Comment by darkdragon-001** [comment]
Might be related to #24888

**Comment by trwnh** [comment]
i'm pretty sure this is an iOS thing, if it's still happening. (and if it is, please comment here so the issue can be reopened)
