### ISSUE TITLE
"drop" type filters don't work on CW text

### ISSUE THREAD

**Issue by CosineP** [mastodon/mastodon#10164]
### Expected behaviour

filter: meta: drop

CW: meta  
a post here

post doesn't show up (is filtered)

### Actual behaviour

filter: meta: drop

CW: meta  
a post here

post shows up in my timeline

Actually, doing more research now, this may apply to "hide" type filters as well. But only sometimes?

### Specifications

Mastodon 2.7.3

**Comment by ClearlyClaire** [comment]
I have not experienced this, and the filtering system has been largely revamped in #18058. Feel free to reopen if it still applies.
