### ISSUE TITLE
Remove twitter.activitypub.actor accounts from search

### ISSUE THREAD

**Issue by joenepraat** [mastodon/mastodon#10174]
twitter.activitypub.actor accounts show up when searching in Mastodon. This is very confusing for Mastodon users, cause it looks like people can interact with those accounts (that they can not). I even searched for someone and their twitter.activitypub.actor account showed up first in the list.

The only way I could come up with for now is to suspend twitter.activitypub.actor.

See also https://github.com/renatolond/mastodon-twitter-poster/issues/171

My suggestion is to blacklist twitter.activitypub.actor accounts, and other future *.activitypub.actor accounts that people can't interact with, from the search.

**Comment by trwnh** [comment]
I think the solution is to suspend the domain, yeah. Otherwise you're looking for a feature that hides an entire domain from just search... but not from anywhere else. Which leaves what, exactly?
