### ISSUE TITLE
Why "mobile" apps?

### ISSUE THREAD

**Issue by cutls** [mastodon/mastodon#10233]
Browse apps page on joinmastodon shows some desktop apps. It is no longer mobile apps page.
It should be "Apps", "Clients" or something.
![Screenshot_20190311-025029_Chrome](https://user-images.githubusercontent.com/17561618/54089089-810a1880-43a8-11e9-9beb-808c63f3913b.jpg)

**Comment by Gargron** [comment]
Most apps are mobile apps, I also think "apps" and "clients" would not be as obvious for visitors. The most common question is "Is there a mobile app" so having that in plain text is beneficial.

**Comment by cutls** [comment]
Thank you. I understood.
I doubt most of apps on the list are mobile. It's less than 60%, if we regard mobile apps as mobile only apps. Moreover, I think it ironical this text is shown only on desktop.
(In localization files of pt-BR, ja, id, sk, "mobile apps" are translated to "apps." Perhaps translators thought the list was not only for mobile.)
