### ISSUE TITLE
Remote reports still visible on (and accessible from) account page remote account

### ISSUE THREAD

**Issue by todoneunl** [mastodon/mastodon#10316]
### Expected behaviour

When someone sends a report from a remote instance to your instance, only the name of that instance is displayed to moderators, not the remote username.

The account page of that remote user shouldn't display the number of reports in the 'Made reports' box. It should always be 0, cause remote reports are always send with only the instance name.

### Actual behaviour

On the account page of that remote user the amount of reports are displayed in the  'Made reports' box. Moderators can click on it and it shows them the actual reports.

### Steps to reproduce the problem

You should know the remote user that did send your instance a report. Go to the account page of that particular user to see what I mean (as a mod of course).

### Specifications

Version 2.7.4

**Comment by BenLubar** [comment]
Remote reports are always sent by the contact address of the instance or the first non-banned user if one is not set.

#10457 is a possible way to solve this.

**Comment by todoneunl** [comment]
After a random check, I think this resolved.
