### ISSUE TITLE
Show multiple-choice poll percentages based on users, not votes

### ISSUE THREAD

**Issue by BenLubar** [mastodon/mastodon#10329]
Given a multiple choice poll, each user's response should only add 1 to the total that percentages are calculated from. The total should not increase by the number of items they selected.

**Comment by ThibG** [comment]
This one is actually tricky because we don't serialize that information (the number of unique voters) to ActivityPub :/

**Comment by mjankowski** [comment]
Last update here was ~5 years ago ... I believe this is still relevant to latest (4.3) version, but I'm not sure if this should be a wontfix, or if a change to serialize the needed information would be welcome?

**Comment by trwnh** [comment]
we have toot:votersCount now i think?
