### ISSUE TITLE
chewy:upgrade on older instance crash 

### ISSUE THREAD

**Issue by Dryusdan** [mastodon/mastodon#10336]
Hello :)

I encounter a problem with `RAILS_ENV=production bundle exec rake chewy:upgrade`

I have installed an Elasticsearch instance 2 years after my Mastodon instance and I follow the documentation.

Same problem when I use chewy:sync.

Elastic server is accessible (telnet try)
### Expected behaviour

No error ?

### Actual behaviour

When I tip this command: `RAILS_ENV=production bundle exec rake chewy:upgrade` I have a timeout : 

```
mastodon@mstdn-1:~/www$ RAILS_ENV=production bundle exec rake chewy:upgrade
Resetting StatusesIndex
  Imported StatusesIndex::Status in 6m 6s, stats: 
rake aborted!
Faraday::TimeoutError: Net::ReadTimeout with #<TCPSocket:(closed)>
```

### Steps to reproduce the problem

Have a Mastodon instance

### Specifications

I use Mastodon v2.7.4

Regards

**Comment by Maescool** [comment]
I'm having the same issue, is there any way to debug this? set timeout longer?

**Comment by Dryusdan** [comment]
I not install Elasticsearch because of this bug. :/

**Comment by Maescool** [comment]
This bug is still here for bin/tootctl search deploy
big long existing db's, can't seem to cleanly sync to elasticsearch without timing out.

**Comment by Maescool** [comment]
This seems to be resolved for me now.

**Comment by Dryusdan** [comment]
I can't try to test. No enought ressource and I closing soon my instance.
