### ISSUE TITLE
Profile link verification problem

### ISSUE THREAD

**Issue by ThomasLeister** [mastodon/mastodon#10361]
Hey Mastodon developers,

At the Anoxinon e.V. (Club about FOSS from Germany) we have an issue regarding the "Verified Profile Link" feature in Mastodon. Members of the club have a "rel=me" Link in the source code of the Home Page (https://anoxinon.de) so their membership can be proven if they put the club's Web address into their Mastodon profile (social.anoxinon.de)

Our problem can be summarized like that:

- social.anoxinon.de User tries to verify link to anoxinon.de: **Does NOT work!** :x: 
- social.anoxinon.de User tries to verify any other web site: Works! :heavy_check_mark: 
- Any other Mastodon users from other instances try to verify link to anoxinon.de: Works! :heavy_check_mark: 

In one sentence: **The problem only exists when using social.anoxinon.de instance and the anoxinon.de Homepage**. Any other combinations of Mastodon instance and home page do work. 

The only thing that our Mastodon instance and the home page do have in common, is their server location. They run on the same physical server, in the same private virtual subnet, but on entirely different KVM virtual machines. 

### 1

We used curl to retrieve the web site’s content from the server. Loigged into the user account that is used by the Mastodon instance and issued:

```
curl -4 https://anoxinon.de | grep rel=\"me\"
curl -6 https://anoxinon.de | grep rel=\"me\"
```

To check the content retrieved from the web server via IPv4 and v6 respectively. In both cases We retrieved the expected “rel=me” link lines in the source code. At the same time verification on other Mastodon instances did work here - so we’re sure that there was no mistake made while embedding the link snippet into the source code.

Our curl test proves that Mastodon should be able to retrieve the correct source code and make the verification succeed.

### 2

We checked the anoxinon.de 1 web server logs after we tried to verify a website on Mastodon. We could see a successful HTTP request coming from the Mastodon instance to the correct vHost and the correct page.

### 3

We checked the Mastodon logs. All we could see was:

```
[...] LinkCrawlWorker [...] INFO: start
[...] LinkCrawlWorker [...] INFO: done: 0.002 sec
```

### 4

- Several server and instance restarts
- Flushing Redis (not sure if this helps)

### 5

We set up another fresh Mastodon instance on the same physical servern (in another fresh VM) and faced the same issues. 

## What now?

From a basic "curl" perspective everything is fine. We get the correct source code from the correct server, data transmission works etc. It's only the Mastodon application which seems to do different things and fail when trying to verify the link.

In the [Mastodon forums a user suggested](https://discourse.joinmastodon.org/t/profile-link-verification-fails/1752)  that this problem exists because of security settings. We're not sure about that. 

We'd be very happy to find and resolve this issue. Any help is appreciated - we are really running out of ideas ... 

*We're using Mastodon 2.7.4 with Rails 2.6.0 on Debian Stretch*

**Comment by ThibG** [comment]
What does `anoxinon.de` resolve to from your Mastodon instance? My guess is that it resolves to the private address instead of the public one, which Mastodon will reject it to avoid confused deputy attacks (performing requests to services that shouldn't be available from the outside).

**Comment by ThomasLeister** [comment]
Hi @ThibG , thanks for your reply! Yes, anoxinon.de does resolve to the private adress. This is purpose to avoid NAT problems. If we use the public address instead, we end up in a NAT "Hair pinning problem" (?) which means we can't connect at all. For this reason the private address is used. In general it works well - only Mastodon seems to have a problem with it. 

Is there a chance to maybe avoid Mastodon's "protective" behavior?

**Comment by nightpool** [comment]
@ThibG 
>We checked the anoxinon.de 1 web server logs after we tried to verify a website on Mastodon. We could see a successful HTTP request coming from the Mastodon instance to the correct vHost and the correct page.

This seems to contradict the private address assumption?

**Comment by ThomasLeister** [comment]
> This seems to contradict the private address assumption?

Hmm yes, your're right :thinking:

**Comment by PhilRW** [comment]
I see the same behavior: When I disable internal IP address for my website, link verification works. It seems like Mastodon should trust DNS, no?

**Comment by schmittlauch** [comment]
I am stumbling over a similar issue, where the mastodon instance fails to verify a site hosted on the same server.
The difference is that the site cannot be locally retrieved via IPv4 (yes, I could try fixing my NAT setup) but loads fine via IPv6, having both an A and an AAAA record in DNS.
Mastodon though seems to try IPv4 resolution first and fails when this retrieval fails.

Could be worth opening a separate issue though.
