### ISSUE TITLE
[Feature Request] CSV import for lists and domain blocks

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#10408]
### Pitch and Motivations

Now since we can export lists and domain blocks (#9677), why can't we import them to another instance?

PS: Maybe a duplicate of #9268, #3716, #177, ...

**Comment by ThibG** [comment]
Domain blocks can already be imported, can't they? Lists can indeed not be imported, though…

**Comment by cd24** [comment]
+1 for importing lists

**Comment by ThisIsMissEm** [comment]
Looks like list importing landed in [4.2.0](https://github.com/mastodon/mastodon/blob/main/CHANGELOG.md#420---2023-09-21)

So I think this can be closed as "completed"
