### ISSUE TITLE
Change the sign in to reply link on conversations

### ISSUE THREAD

**Issue by jonaharagon** [mastodon/mastodon#10405]
### Expected behaviour

Clicking the "Sign in to participate in the conversation" link at the bottom of conversation pages should link to the same pop-up page as the reply icon buttons do (`https://{Instance URL}/interact/{Post ID}?type=reply`). That way people who wish to reply can do so from their own instance or the local one depending on their input.

### Actual behaviour

The button links to the instance's `/auth/sign_in` page, implying you need an account on that specific instance to reply.

### Steps to reproduce the problem

1. Open a post like https://mastodon.social/@Gargron/101826498787247000
2. Click "Sign in to participate in the conversation"

### Specifications

This is on the v2.7.4 release.

**Comment by vmstan** [comment]
Closed as the interaction models have changes many times since this was opened, especially in 4.2.
