### ISSUE TITLE
Notifications: Display all categories by default

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#10503]
### Pitch

The recent Notifications feature of splitting out mentions/favs/retoots/polls/follows etc is awesome but it's hidden behind clicks and nobody really notices it.

Please allow me to turn this feature on for all users new/old by default.

### Motivation

It's a cool feature and I want other people to enjoy it.

**Comment by Shleeble** [comment]
<img width="353" alt="image" src="https://user-images.githubusercontent.com/17537000/58147851-f3438700-7c8e-11e9-8caa-cfb849fa9715.png">

this thing is the best.
