### ISSUE TITLE
New landing page takes focus away from hero image

### ISSUE THREAD

**Issue by anampses** [mastodon/mastodon#10551]
Not sure if I'm alone on this, but I feel the design of the new landing page ruins the visual presentation of the hero image that previously helped to set apart each server. 

The new frontpage tucks away the unique image into a small cropped banner, and the Mastodon logo is now much larger and becomes the initial focal point at the top.

**Comment by ValiantNinja** [comment]
This is quite interesting as I had the issue of expecting this naturally when I was updating. It caught me off guard as I always expected to see an elephant on the front ;x --> #10438

**Comment by joycem137** [comment]
I think servers should have the ability to set the top banner on this as well as custom text.
