### ISSUE TITLE
Toot moderation toolbar hidden on mobile in 2.8.0

### ISSUE THREAD

**Issue by fwenzel** [mastodon/mastodon#10576]
After upgrading to 2.8.0, individual toot moderation (delete toot, mark sensitive, etc.) has vanished entirely. All I can do is warn/silence/suspend a user, but not delete a single toot anymore if it was violating policy.

### Expected behaviour

Screenshot from v2.7.4:
![Screenshot_20190413-142152_Chrome](https://user-images.githubusercontent.com/87232/56086936-fe94ce80-5e15-11e9-9e75-eebd544be76c.jpg)

I can delete / mark sensitive.

(ignore that the cat picture didn't load, probably unrelated)

### Actual behaviour

Screenshot from v2.8.0:
![Screenshot_20190413-142101_Chrome](https://user-images.githubusercontent.com/87232/56086944-110f0800-5e16-11e9-8d93-76ce35c9b6b3.jpg)

I cannot do anything to the toot itself.

### Steps to reproduce the problem

Navigate to any toot as a moderator / admin, choose "open this status in the moderation interface" in the dropdown menu.

### Specifications

Release v2.8.0

Chrome on Android.

**Comment by Gargron** [comment]
I cannot reproduce this! Have you run assets:precompile after upgrade?

**Comment by fwenzel** [comment]
I checked and I can confirm it even in a desktop browser, when switching to mobile-size view. It seems the moderation functions are disappearing when the page width gets small enough.

**Comment by fwenzel** [comment]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/87232/56089385-c0fc6980-5e46-11e9-9a59-e6e870c16d05.png">

**Comment by fwenzel** [comment]
I think it's this commit https://github.com/tootsuite/mastodon/commit/7130d6e51291b08df59f9580c7d6e1c1d97e7dad

**Comment by kedamaDQ** [comment]
I reproduced this issue in mobile mode.

Certainly, managing follows and followers is usually not urgent, but 'batch-table' style class is shared with the moderation interface, and report processing, force NSFW setting, and toot removal may be urgent. When such a situation occurs when there is only a small smartphone at hand, I think that it may be a trouble.

There is a workaround that rotate smartphone to landscape mode but... :thinking:

**Comment by fwenzel** [comment]
I agree, this is a pretty nasty bug that makes moderation on the phone very hard.
