### ISSUE TITLE
[Bug] Privacy Policy, service terms link the same page

### ISSUE THREAD

**Issue by marek-lach** [mastodon/mastodon#10595]
### Expected behaviour

The links to Privacy policy and Terms of Service should not be separate if they link to the same URL.

### Actual behaviour

In the RESOURCES section of the main instance homepage's footer, there are two separate links: 'Terms of Service' and 'Privacy Policy', but they both link to the same url: /terms

Since that is the case, the link to that page could be unified under one link, such as '_Terms of Service & Privacy_'.
<img width="180" alt="Screenshot 2019-04-17 at 18 45 45" src="https://user-images.githubusercontent.com/45913977/56306331-7169b680-6142-11e9-9e95-ea091822e1ac.png">

**Comment by Phroneris** [comment]
I feel opposite about the same issue;
The links to Privacy policy and Terms of Service should link to different URLs (and Mastodon should have each page) if they're written separately.

Note: Mine is similar to #8362.
