### ISSUE TITLE
Potential bug: 2FA errors after rotating secret keys

### ISSUE THREAD

**Issue by joyeusenoelle** [mastodon/mastodon#10607]
Recently I had cause to reinstall the Mastodon code base for my instance, but continue using the pre-existing database. As part of this, I regenerated the secret keys that are part of `.env.production`. An expected side effect of this was that existing users' 2FA was invalidated.

When I disabled 2FA through the web admin panel for any user who asked, as expected, they were able to log in. However, they were *not* able to re-establish 2FA on their account; trying to do so led to the oops.png error message.

In the Mastodon logs, TwoFactorAuthenticationsController was returning a status code 500 because of an OpenSSL CipherError. It did not explain what the error was.

I actually had not had 2FA on my account before, and was able to establish, remove, re-establish, etc. 2FA without any trouble through my Account Preferences page.

I finally found the solution in #7897. For some reason, after .env.production keys are changed, the "Disable 2FA" button on a user's account page in the admin panel (i.e. /admin/accounts/# rather than /settings/two_factor_authentication) only sets `users.otp_required_for_login` to `'f'`, and does not clear the following database columns for the selected user: `users.encrypted_otp_secret`, `users.encrypted_otp_secret_iv`, and `users.encrypted_otp_secret_salt`.

Disabling 2FA from /settings/two_factor_authentication - that is, user-side rather than admin-side - does not encounter this issue, which is why I couldn't duplicate it.

Manually clearing those columns resolved the issue. I believe the code does not expect to find existing secrets in the database, and throws an error when it encounters them.

I have not examined the code to discover where the flaw lies.

### Expected behaviour

After regenerating a server's secret keys, the "Disable 2FA" button at the /admin/accounts/# endpoint should fully remove 2FA information from the user's account, so that there is no collision when users attempt to re-establish 2FA.

### Actual behaviour

After regenerating a server's secret keys, the "Disable 2FA" button at the /admin/accounts/# endpoint only sets `users.otp_required_for_login` to `'f'`, and does not remove the encrypted OTP secrets, which causes a collision when users try to re-establish 2FA.

### Steps to reproduce the problem

As described above.

### Specifications

This occurs in v2.8.0.

**Comment by nightpool** [comment]
"collision" means something specific with regards to cryptography, so i tweaked the title a bit

**Comment by joyeusenoelle** [comment]
Good catch, thanks.

**Comment by panomaki** [comment]
I can confirm this but is still present in 4.1.9 and resetting the mentioned three database columns solves the problem.

**Comment by mjankowski** [comment]
The OTP mechanism here (for both storage and secrets) changed in 4.3 and I suspect resolved this as a side effect.

If this is reproducible on 4.3, please reopen with instructions for how to replicate.

Also thanks for being so thorough with original description!
