### ISSUE TITLE
Suggested instances when remote following on the web

### ISSUE THREAD

**Issue by RileyKyeden** [mastodon/mastodon#1062]
When you go to remote follow someone from the web, a list of already connected instances to choose from, in addition to a place to put your full name@instance, would be handy.

That way when I remote follow someone, I can just click the "mastodon.social" button. Or if you use local storage/cookies, it could just offer this as a default option after the first time.

This is my first time ever using Github so I may be doing this suggestion wrong. Let me know and I'll fix it. :3

* * * *

- [x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Shywim** [comment]
Local storage is only accessible from the current domain and cookies is either the same or would cause security issues anyway.

But I think it could be the job of some browser addon that you could configure which accounts you want to have a quick button for.

**Comment by Exagone313** [comment]
```javascript
/*
Copyright (c) 2017 Elouan Martinet

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
path = location.pathname.substr(1).split('/');
if(path.length === 3 && path[0] === 'users' && path[2] === 'remote_follow') {
	document.getElementById('new_remote_follow').addEventListener('submit', function() {
		sessionStorage.setItem('follower', document.getElementById('remote_follow_acct').value);
		return true;
	});
	if(sessionStorage.getItem('follower')) {
		document.getElementById('remote_follow_acct').value = sessionStorage.getItem('follower');
	}
}
```

**Comment by jeepfromoil** [comment]
Alternative solution: the input field could autocomplete to pick the right account, since it's possible to search users across the Fediverse from one instance.

**Comment by Shywim** [comment]
But then how is it different than browser's suggestions? I mean, Firefox
already give me my complete username suggestion when I click on the form on
any Mastodon instance since I first remote followed someone, maybe it
doesn't in Chrome.

**Comment by Exagone313** [comment]
See #898, should be closed. It's now stored on the session (via cookie) you get on the instance.

**Comment by luc122c** [comment]
For anyone looking for this feature, [FediAct](https://github.com/lartsch/FediAct) enables this behaviour as a browser addon. See https://mstdn.social/@feditips/109988772047097090 for info.

**Comment by trwnh** [comment]
> See https://github.com/mastodon/mastodon/pull/898, should be closed. It's now stored on the session (via cookie) you get on the instance.
