### ISSUE TITLE
Add account requests approval/reject to audit log

### ISSUE THREAD

**Issue by todoneunl** [mastodon/mastodon#10641]
Right now (v 2.8.0) when an account is requested, an approval or a rejection is not displayed in the audit log. Especially when having multiple moderators it's a must have to show this in the audit log.

**Comment by JamesABDL** [comment]
I think some display filtering is needed for the audit log, especially if approval/reject actions are added (which they should). Without the audit log wouldn't be as useful if we have hundreds of rejected spam accounts filling up the log.

**Comment by joyeusenoelle** [comment]
Implementing this would definitely require either a separate audit log or a filtering system on the log. Mastodon.social gets several hundred account requests each day, and including these in the audit log without any sort of filtering mechanism would make the log useless.

**Comment by jeroenpraat** [comment]
Filtering is indeed a good idea and not only for account requests. Another possibility is to make it an admin preference.

**Comment by todoneunl** [comment]
This is already added for a while.
