### ISSUE TITLE
Wanted: Public hashtag search page, with ~options~

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#10671]
### Pitch

I would love to see a public hashtag search page on instances. In addition to navigating to instance.url/tags/YourTagHere manually, I'm thinking something like:

* instance.url/tags - since /tags/YourTagHere is already a thing but /tags is an error page, curious people who go to /tags don't find anything. It could be something fun instead!
* It has a text box where you can type the hashtag you want to see. Maybe "this instance only" and "all posts known to this instance" options?
* It has AND and OR options. Want to see all toots containing `#poll` *and* `#gender`? You can do that!
* Brings up results from all public toots known to that instance, so it's like the federated timeline but more explorable.

If something very simple is needed to get the ball rolling, maybe:

1. Navigate to /tags, which is just a page with a textbox and a button that says "view hashtag".
2. When you type in a tag and click "view hashtag", it takes you to instance.url/tags/WhateverThePersonJustTypedIn

### Motivation

The [Twitter advanced search](https://twitter.com/search-advanced?lang=en-gb) page is good.

And public hashtag pages have the potential to draw people in to Mastodon, so maybe make them more user-friendly for non-members! People could use a /tags page to mooch around and explore Mastodon in a more freestyle way before joining.

**Comment by Cassolotl** [comment]
I still like this idea!

**Comment by CarwilB** [comment]
Please do this!

**Comment by Cassolotl** [comment]
This is probably met by `[instance]/explore/tags` now, so I will close the issue. :)
