### ISSUE TITLE
Provide Snap package

### ISSUE THREAD

**Issue by mhall119** [mastodon/mastodon#1068]
Provide a snap package through the Snap Store to easily install and update Mastodon. Snaps are like a light-weight docker that run natively on the host machine, get automatic updates when available, and run securely confined from the rest of the system.

https://snapcraft.io

* * * *

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by vielmetti** [comment]
Hi @mhall119 - have you built these sorts of things before (ie. that you are willing and able to help with this code to accomplish the task?)

**Comment by mhall119** [comment]
I have, I actually work for Canonical on Snap advocacy. It's Ruby that I don't know enough about. I've started on a package config for Mastodon here: https://github.com/mhall119/mastodon/commit/c0788ac776b3b085b146cbf5938c819e8f8d397c

It builds a snap with what appears to be all the necessary ruby and nodejs dependencies, but the call to ruby to run the service fails on a require for bundler/setup, which I don't see in the snap, even though the bundler module has been installed.

**Comment by mhall119** [comment]
You'll see that it's fairly similar to the Dockerfile (and simpler than the Vagrantfile), but I'm afraid I've reached the limit of my ability with this combination of languages and package managers. 

You can create a snap from that branch on Ubuntu 16.04 or newer, just run "snapcraft snap" inside the directory, then "snap install --dangerous mastodon_v1.0_amd64.snap" to install it.

**Comment by vielmetti** [comment]
PR filed, a tiny one https://github.com/mhall119/mastodon/pull/1

Can you paste in the error message you got when this started up and it didn't quite work? I have a sneaking suspicion there's a hidden development dependency that we can find.

Related: #1118

**Comment by vielmetti** [comment]
Also, are snaps designed to be cross-platform? I have an arm64 box that I'm working on, and the provided example hard-codes amd64 dependencies.

**Comment by mhall119** [comment]
Cross-platform, but not multi-arch. You would need different packages for arm64 and amd64. But we host a build service that can do them for you.

**Comment by dhelonious** [comment]
I have created an all-in-one snap package for Mastodon. You can find it here: https://github.com/dhelonious/mastodon-snap

At the moment the snap is only available via GitHub and for manual installation. I want to do some more testing (including arm64) before taking the next steps.

**Comment by renchap** [comment]
Closing this as we do not plan to provide an official snap package.
