### ISSUE TITLE
Closing an image causes timeline to jump back to top

### ISSUE THREAD

**Issue by fluffy-critter** [mastodon/mastodon#10688]
### Expected behaviour

Closing an image should not change my position on the timeline.

### Actual behaviour

Closing an image jumps my timeline back to the very top, losing my place where I was reading in backscroll.

### Steps to reproduce the problem

1. Scroll down on timeline
2. Open an image
3. Dismiss the image (either by clicking outside of it or by pressing Esc)

This only happens sometimes and it isn't clear what starts it happening, but once it does start to happen it keeps happening with close to 100% reproducibility until I close the browser tab and return to Mastodon.

Possibly a regression of (or the same thing as) #9954.

### Specifications

v2.8.0 on queer.party (but have been experiencing this for quite some time)

macOS 10.14, Safari 12.1

**Comment by ThibG** [comment]
Does the scrolling position reset in the rightmost timeline, or any timeline?
Do you know if it affects one kind of media but not another? (images, full-blown videos or “GIFV”)
When that happens, does it always jump to the very top, or some other position?

**Comment by fluffy-critter** [comment]
I only recall seeing it happen on the leftmost timeline but I also only generally see/interact with images there. It definitely happens to static images, but I don’t generally look at other media types either. 

I’ll keep these questions in mind next time it starts happening to me, and will try other interactions to narrow things down. There might also be something interesting printed to the developer console.

**Comment by fluffy-critter** [comment]
Oh and it always jumps to the very top.

**Comment by JamesABDL** [comment]
I'm finding the same thing on 2.8.2 using Safari (haven't tested in other browsers yet).

For me all columns (apart from Home or Notifications) jump back to the top when closing an image.

I can replicate this on mastodon.social as well.

**Comment by the-sillystring** [comment]
Jumps to top of all timelines for me as well on the latest stable Safari on iPad.

**Comment by fluffy-critter** [comment]
It's happening to me again on Safari. When I close a media attachment on *any* column, *all* columns jump back to the top. I'm not seeing anything interesting in the developer console. The jump-to-top behavior happens regardless of how I close the attachment (Esc or clicking the close button).

For example: https://youtu.be/pwJ-uneIJms

**Comment by ThibG** [comment]
Looking at the video it seems that not only the columns scroll back to the top, but there is something being reloaded… it definitely has to do with the `history.goBack` call that occurs when closing the modal… but I don't understand why it's not transparent how it should be

**Comment by JamesABDL** [comment]
Seeing this in simple layout as well. Several users have reported this bug to me now and it's very frustrating if you're a long way down in your feed.

**Comment by ThibG** [comment]
The simple layout bug is a specific one that should have been fixed very recently.

**Comment by JamesABDL** [comment]
@ThibG do we know which commit? Had a quick look but can't see it. My deployment is 47 commits behind tootsuite:master currently.

**Comment by Gargron** [comment]
50755a47b4f0999f8c49501ff4fa4c2ef676fa0e

**Comment by the-sillystring** [comment]
Nice.  This has been broken for about two years.  So glad to see a possible fix coming.

**Comment by the-sillystring** [comment]
Still broken for me on iOS for well over a year.  Sad face.

**Comment by ThibG** [comment]
I feared that would be the case, as this commit only fixes a recently-introduced bug…

**Comment by the-sillystring** [comment]
Unfortunately the issue still exists.

**Comment by ClearlyClaire** [comment]
Does this bug still occur? If so, could you please check the following:
- does it still occur if you press the history back button of the browser instead of closing the modal?
- in a browser console, what does `window.history.state.state` contain, when the modal is open? and when it is closed?
- could you disable any browser extension and try again?

**Comment by fluffy-critter** [comment]
I've switched from Safari to Firefox as my main browser, so I can't speak to whether this is still occurring on Safari. Hopefully someone else who's watching this bug still uses Safari and can provide that information.
