### ISSUE TITLE
When changing email address, clicking link in verification email just goes to "Something isn't quite right yet! Please review the error below"

### ISSUE THREAD

**Issue by oneonenine** [mastodon/mastodon#10691]
I'm trying to change my email address via the /auth/edit  URL. When I click "save changes", I get a verification email at the new address. But, when I click the link in that email, it takes me to a page that just says "Something isn't quite right yet! Please review the error below." It has a blank box for my email address. 

If I put the new address in that box and "RESEND CONFIRMATION EMAIL", the cycle repeats.

This occurs both if I click on the email link in an incognito browser, and in a browser where I have already logged into the Mastodon instance. In both cases, it fails to update my address.

I am therefore unable to change my email address on this Mastodon instance.

The server is using Mastodon version 2.8.0 .

![bug_1](https://user-images.githubusercontent.com/50261203/57176298-4900de00-6e0b-11e9-9be9-d33d20c43521.PNG)
![bug_2](https://user-images.githubusercontent.com/50261203/57176299-49997480-6e0b-11e9-9672-dd111cf92411.png)

**Comment by mgiagante** [comment]
@Gargron I'm completely knew to Mastodon's code, but I think there are few points of failure for this:

- The [`UserMailer#confirmation_instructions`](https://github.com/tootsuite/mastodon/blob/6d44f2441bf2aa14d11e481d9d2cfe82a74d81ed/app/mailers/user_mailer.rb#L11) method.
- The [`reconfirmation_instructions.text.erb`](https://github.com/tootsuite/mastodon/blob/6d44f2441bf2aa14d11e481d9d2cfe82a74d81ed/app/views/user_mailer/reconfirmation_instructions.text.erb#L7) template (and its Haml counterpart).

Please correct me if I'm wrong but I think the token is generated/handled by Devise, as is everything that happens later on.

Maybe it'd be good if @oneonenine could provide the url the "Verify Email Address" in the first screenshot takes to?

Hope it helps.

**Comment by oneonenine** [comment]
The url I got was just a simple https://instance.name/auth/confirmation?confirmation_token=JqMWzm9....

(where ... is more [A-Za-z0-9] characters)

Oddly, when I tried it today it _did_ work. One thing that's possibly different is that I didn't add anything to the "new password" field. I think I had a new password in there as well when I was trying to change my email last week.

**Comment by magarsangesh034-lab** [comment]
Bunty magar
