### ISSUE TITLE
First check, if email domain is valid, then if it is registered

### ISSUE THREAD

**Issue by clerie** [mastodon/mastodon#10694]
### Expected behaviour
When I try to register with a domain, which is not valid due to email whitelisting, but someone is still registered with it, it should be rejected for the domain reason first.

### Actual behaviour
The registration is rejected because the email address still exist.

### Steps to reproduce the problem
Try to self-register with a still registered email address, but non whitelisted domain.

### Specifications
Mastodon v2.8.1

**Comment by mjankowski** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
