### ISSUE TITLE
Changes to emoji handling to allow remote emoji

### ISSUE THREAD

**Issue by BenLubar** [mastodon/mastodon#10708]
### Pitch

Currently, emoji are recorded by shortcode and domain name. This means that a remote emoji will:

1. overwrite a local emoji with the same name
2. be added to a domain that doesn't own it

The domain name should, instead, be the domain of the emoji's `id` field, verifying that it matches the actual document before storing it in the database similar to how boosted posts aren't implicitly trusted.

Additionally, emoji are not able to be discovered via a search for the ActivityPub URL the way that posts and users can be discovered.

A third issue is that remote emoji and local emoji cannot be referenced in the same post if they have the same name, but this isn't really that big of a problem.

Test case: <https://ben.lubar.me/dump/emoji-test-68702b2a-cbdc-4d39-858e-f1b22fcc48a5/post.json> (search for `@testuser@ben.lubar.me` first if this returns no results in Mastodon)

### Motivation

This wouldn't immediately make any user-visible changes, but it would make room for future enhancements:

Using remote emoji would be most immediately useful in replies to posts from other domains with content warnings that contain emoji.

It would also allow centralized storage of an emoji library that is shared between multiple domains but none of those domains *own* the emoji library. In this example, I could use the entirety of Guild Wars 2's item list as an emoji source rather than having to upload thousands of PNGs to my instance before they were available.

**Comment by mjankowski** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.

Separately - I know there has been evolution in emoji handling since filing ... are there still valid desires left in here?
