### ISSUE TITLE
Keyboard shortcuts conflict

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon#10724]
### Expected behaviour

pressing <kbd>gr</kbd> should navigate to "Follow requests" without side effect

### Actual behaviour

<kbd>gr</kbd> navigates to "Follow requests" and last <kbd>r</kbd> performs "Reply"

### Steps to reproduce the problem

Press <kbd>gr</kbd> on Mastodon web UI

### Specifications

Mastodon version: 2.8.2
Browser: FF/Chrome on Linux

**Comment by ThibG** [comment]
The same occurs with <kbd>g f</kbd> and favorites, <kbd>g m</kbd> and mentions, <kbd>g b</kbd> and boosts… and so far I could not find a way to avoid that :/

**Comment by ThibG** [comment]
I guess we should use key combinations instead of sequences here
