### ISSUE TITLE
Hashtag identifier should follow standard

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon#10728]
### Expected behaviour

Hashtag identifiers are defined on UAX: https://www.unicode.org/reports/tr31/#hashtag_identifiers

    <Hashtag-Identifier> := <Start> <Continue>* (<Medial> <Continue>+)*
    Start := [#﹟＃]
        U+0023 NUMBER SIGN
        U+FE5F SMALL NUMBER SIGN
        U+FF03 FULLWIDTH NUMBER SIGN
        (These are # and its compatibility equivalents.)
    Medial is currently empty, but can be used for customization.
    Continue := XID_Continue, plus Emoji, Emoji_Component, and “_”, “-”, “+”, minus Start characters.
        Note the subtraction of # characters.
        This is expressed in set notation as:
        [\p{XID_Continue}\p{Extended_Pictographic}\p{Emoji_Component}[-+_]-[#﹟＃]]

So that should contain `#abc`, `#C++`, `#가나다`

### Actual behaviour

- `#abc` works fine
- `#C++` tagged as `#C`
- `#가나다` tagged correctly, But not on Frontend.
  - https://github.com/tootsuite/mastodon/blob/1bbe12254d450aadf343ea337287f5e4b6ce5e80/app/javascript/mastodon/features/compose/containers/warning_container.js#L8

**Comment by Gargron** [comment]
> The actual composition of allowable Unicode hashtag identifiers varies between vendors
