### ISSUE TITLE
Moderation API

### ISSUE THREAD

**Issue by Gargron** [mastodon/mastodon#10741]
In broad terms, the same things possible from the admin interface must become possible through an API with an additional OAuth scope.

**Comment by bclindner** [comment]
This should probably be closed. Looks like the GitHub project didn't do it for some reason. :man_shrugging:

**Comment by trwnh** [comment]
isn't this `/api/v1/admin`

**Comment by tofuwabohu** [comment]
I was about to open a Feature Request to make mod actions (activatinv users, resolve reports, etc) available via API so it can be done in apps. Is this about the same or is it a different thing?

**Comment by trwnh** [comment]
Duplicate of #2517
