### ISSUE TITLE
Use full screen width

### ISSUE THREAD

**Issue by Golutazem** [mastodon/mastodon#10750]
Currently on a desktop monitor, much screen space is wasted. This feature request is to change Mastodon to use the full screen width.
Here is code, which enables the resizing and limits the maximum size of the drawer.
```
div.drawer { max-width:40rem}
div.drawer ,
div.columns-area ,
	div.columns-area > div.column ,
	div.columns-area > div.search ,
	div.drawer 
	{ 
        flex-grow:1;
	}
```
The increased space better permits using a larger font.

**Comment by dnaf** [comment]
related: #5736, #8632, #9463

**Comment by Golutazem** [comment]
At the time of this issue was posted, the CSS included worked well.
Since then the code for the drawer has changed and the CSS no longer applies to that column.  I have not been able to identify how to make it apply again. If someone knows, the information would be welcome. I still think the patch should be applied. (after updating it)

**Comment by trwnh** [comment]
Closing in favor of #11413
