### ISSUE TITLE
Latest v2.8.2 broken with Chrome on Windows XP

### ISSUE THREAD

**Issue by anampses** [mastodon/mastodon#10764]
I have not tested it myself, but I have received reports from users on my instance that Mastodon will not display properly using Chrome browser on Windows XP. Before it is asked why they are still using XP, it is not really my place as admin to demand they use Firefox or a different OS instead. 

There was previously no issue with Mastodon and using Chrome on XP prior to v2.8.2, and I really hope this bug can be addressed.

**Comment by Shleeble** [comment]
lol

**Comment by mynameismonkey** [comment]
Chrome does not support Win XP. That's not a Mastodon thing, that's a Chrome thing. Even if it does manage to work, it is not secure. In your shoes I would counsel downloading an older version of Chrome (in this case version 49), or upgrading to an operating system that receives security updates. Security patches for XP ended in 2014.

**Comment by trwnh** [comment]
@mynameismonkey actually chrome 49 is the latest version available for xp. the problem is that this version (and xp in general) are just way too old.

with that said, if @anampses could identify the "prior to 2.8.2" version of mastodon that was running on their server, that would help in narrowing down which exact change uses unsupported css/js features.

**Comment by anampses** [comment]
I should have been more specific about the reports I received, my apologies. The last version that seemingly worked fine with Chrome 49 on XP was v2.7.4 

My two users still on XP tell me that using Firefox 52 does work, but Mastodon loads very slowly compared to when they had it working fine previously with Chrome before the upgrade in versions.

**Comment by no-boot-device** [comment]
Apparently [chromium](https://download-chromium.appspot.com/) still supports XP, according to word of mouth.
