### ISSUE TITLE
Remote status isn't indexed into ES well

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon#10760]
### Expected behaviour

As written at commit 3ebc0ad4d, Remote status that mentioned me is supposed to searchable by me.
```
    * Add full-text search for authorized statuses

    - Search API will return statuses that match the query
    - Only for logged in users
    - Only if you are author of the status,
    - Or you were mentioned in it
    - Or you favourited or reblogged it
    - Configuration over `ES_ENABLED`, `ES_HOST`, `ES_PORT`, `ES_PREFIX`
    - Run `rails chewy:deploy` to create & populate index

```

### Actual behaviour

Remote status is not index to ES server until local user fav/boost it

### Steps to reproduce the problem

1. From user A on server X, Mention user B on server Y with some random message
2. On user B's side, search that random message
3. That status is not searchable (Even if manually queried to ES server directly)
4. After some user on server Y fav or boost that status, it is searchable

### Specifications

On mastodon 2.8.2 stable release

**Comment by Kjwon15** [comment]
Additionally, unfav, unboost isn't update chewy record.
