### ISSUE TITLE
Video Quality Setting

### ISSUE THREAD

**Issue by MrTeeXD** [mastodon/mastodon#10772]
### Pitch

There is a problem when it comes to viewing videos posted on Mastodon, for example, a user's internet may not be as fast as today's internet speed, it would be great if there was a setting in the video preview to change the quality the video is being watched but instead Mastodon sticks to the raw quality of the posted video.

### Motivation

Most users with slow internet (like me) will greatly appreciate it if such option was implemented into Mastodon, I too would be greatfull for this setting.

**Comment by Gargron** [comment]
There are some blockers on this:

- CPU time of small Mastodon servers is scarce
- Disk storage of small Mastodon servers is scarce

Video quality settings require re-encoding the input video using ffmpeg into 3-4 different copies
