### ISSUE TITLE
Email stop working after last upgrade a couple weeks a go

### ISSUE THREAD

**Issue by r3k2** [mastodon/mastodon#10774]
I did not notice until 4-5 users started to complaint that they cant create accounts nor reset passwords.. I went in and check all settings and mail settings are ok, I went to mailgun and stop working around may 2nd but mailgun does not get any email after that.. so email is not getting sent from mastodon... anyways of where should I check see what lib or command I should rerun?

**Comment by ThibG** [comment]
Did you restart sidekiq after updating? Are there errors in sidekiq logs?

**Comment by ReK2Fernandez** [comment]
hello, hmm I believe I did since I restarted the server but will check for errors and get back

**Comment by ReK2Fernandez** [comment]
@ThibG sidekick is up and working... but not sure what to look for in there...

**Comment by ReK2Fernandez** [comment]
@ThibG I found on retries something called "mailer" that looks very suspicious obviosly with:
```
ActionView::Template::Error: Webpacker can't find media/images/mailer/icon_email.png in /home/mastodon/live/public/packs/manifest.json. Possible causes: 1. You want to set webpacker.yml value of compil...
```
wont show the whole thing...
rings a bell?

**Comment by ReK2Fernandez** [comment]
Similar issue but we are not running docker 
https://github.com/tootsuite/mastodon/issues/6295

**Comment by ThibG** [comment]
Sounds like you forgot to restart mastodon-sidekiq after upgrading. Does restarting it help?

**Comment by ReK2Fernandez** [comment]
@ThibG of course I did, many times and the whole server too at first

**Comment by ReK2Fernandez** [comment]
@ThibG for what the error says looks like is missing something more than something not restarting that I did many times all of the pieces...

**Comment by ThibG** [comment]
What does your `/home/mastodon/live/public/packs/manifest.json` look like?
That file is generated by running `bundle exec rails assets:precompile`, and read by the `mastodon-sidekiq` process at startup (this is why I suggested to restart it, as it may have operated on a stale `manifest.json` file). It should definitely include an entry for `media/images/mailer/icon_email.png`.

**Comment by ReK2Fernandez** [comment]
I been moving overseas, but this is still happening, will look more close in a couple days and report back

**Comment by ReK2Fernandez** [comment]
works if I manually copy logo_full.png  to :~/live/public/packs/media/images/mailer  ..... of course this is a hack since as soon I rebuild or update it will stop working..
