### ISSUE TITLE
improve the rss feeds to work as media rss

### ISSUE THREAD

**Issue by Dorifer** [mastodon/mastodon#10782]
### Pitch
I tried using the rss feed of a mastodon account (https://high.cat/@archillect.rss) as a media rss source for variety wallpaper changer. Variety claims this feed isnt a proper media rss feed (such as e.g. https://backend.deviantart.com/rss.xml?q=gallery%3Ajollyjack&type=deviation ).

Would it be possible to adapt the feeds of mastodon accounts to behave like this?

**Comment by Krinkle** [comment]
See also https://github.com/tootsuite/mastodon/issues/14538
