### ISSUE TITLE
Display back button when you can go back

### ISSUE THREAD

**Issue by ariasuni** [mastodon/mastodon#10811]
### Expected behaviour

Back button in last column is always and only displayed when you can go back in your browser, otherwise it is not displayed.

### Actual behaviour

Back button in last column:
- Is not displayed on Getting Started page, even when you can go back
- Is displayed on any other column, regardless of whether you can go back or not.

### Specifications

Mastodon 2.8.2

**Comment by mjankowski** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
