### ISSUE TITLE
Support TLS 1.3

### ISSUE THREAD

**Issue by SuperSandro2000** [mastodon/mastodon#10866]
### Pitch

Currently Mastodon can't connect to instances that only accept TLS 1.3.

### Motivation

In the future websites will move to TLS 1.3 only and Mastodon would break then. I think it is a good idea to go ahead and enable that feature early.

### Notes

Probably some ruby gem needs updating or that feature added.

**Comment by Gargron** [comment]
This is either up to Ruby's OpenSSL lib or the http.rb gem. We don't control this manually

**Comment by SuperSandro2000** [comment]
@stale get lost

**Comment by mkarg** [comment]
When will there be support for TLS 1.3? My EMail provider told me it does not support TLS 1.2 anymore.

**Comment by valtlai** [comment]
Does Mastodon support TLS v1.3 nowadays?

**Comment by mjankowski** [comment]
Should be supported on current version.
