### ISSUE TITLE
Direct Message tab seems to associate wrong users with post (seen on mastosoc)

### ISSUE THREAD

**Issue by lambadalambda** [mastodon/mastodon#10900]
### Expected behaviour

I should see the correct user being associated with a post

### Actual behaviour

![Screenshot_2019-05-30 Mastodon(1)](https://user-images.githubusercontent.com/27075834/58631311-7cd40400-82e2-11e9-9d54-3d83fe03d937.png)
![Screenshot_2019-05-30 Mastodon](https://user-images.githubusercontent.com/27075834/58631312-7cd40400-82e2-11e9-80e6-9b3de5f9c5b7.png)

The other user in the DM chain is associated with the post. It shows up correctly when I click on the post to open the thread.

### Specifications

Seen on mastodon.social.

**Comment by trwnh** [comment]
related #9190 / #10047

i agree it's still kinda confusing, but what's happening is that the conversation preview is using the following:

- the last post made in the thread
- the avatars of other users that are not you

so when the last post is by you, there's no clear indication of this. it's assumed to be implied by the mentions (e.g. `@lain hey` is your post targeted at `@lain`) but ultimately something like https://github.com/tootsuite/mastodon/issues/9190#issuecomment-462636191 would probably be better.

**Comment by lambadalambda** [comment]
Ah, no i understand. It became clear to me when I posted a DM with two other participants. Still, i find it very confusing, because the DM view looks exactly like a normal post otherwise.
