### ISSUE TITLE
Suggestion: Scroll left when tooting

### ISSUE THREAD

**Issue by JedBeom** [mastodon/mastodon#10914]
### Pitch

Sometimes I can't see what I'm writing on tooting area when the scroll is in the middle. What if you force the scroll to go to the left when typing no tooting area?

### Motivation

This feature will solve discomfort.

**Comment by mjankowski** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
