### ISSUE TITLE
Single panel : only four lists are displayed

### ISSUE THREAD

**Issue by husim0** [mastodon/mastodon#11109]
### Expected behaviour

All userlists should be listed in the single panel.

### Actual behaviour

Only the first four lists are displayed, alphabetically. Would be great to display all lists or have the possibility to have a dropdown button to display them all. Actually for some of my lists I have to go first to "Lists" and then select it.

![image](https://user-images.githubusercontent.com/50374438/59607950-9ebbec00-9114-11e9-8909-22021e205595.png)

### Steps to reproduce the problem

Create 5 five lists.

### Specifications

2.9.0

Firefox 60, GNU/Linux

**Comment by dariusk** [comment]
So the hook in the code that limits this to four lists is here:

https://github.com/tootsuite/mastodon/blob/master/app/javascript/mastodon/features/ui/components/list_panel.js#L16

It's a hard-coded value. It should either be a much bigger number (99 or something), or it should be configurable in the preferences pane.

**Comment by jayrope** [comment]
I sceond the request to leave the number of displayed lists to the user.

**Comment by mjankowski** [comment]
Last update here is ~4+ years old ... going to close this on the assumption that if it hasnt been addressed by now it isnt going to be (and general resistance to any inbound UI changes).
