### ISSUE TITLE
Mastodon is stripping off BBCode from Friendica posts incorrectly, also hashtag fail's

### ISSUE THREAD

**Issue by WNYmathGuy** [mastodon/mastodon#11115]
### Expected behavior

Interpret the [BBCode](https://social.outsourcedmath.com/help/BBCode) as modified HTML, or strip it off properly.

### Actual behavior

Whitespaces _that should remain_ after stripping off BBCode from Friendica Posts are instead removed which sometimes deactivates a hashtag or renders a link unclickable, and generally makes text harder to read depending on the complexity of the use of BBCode in the post.

### Steps to reproduce the problem

Post on a Friendica server account with BBCode markups, then view the post on a socially linked Mastodon account.

### Example

**Mastodon rendering:**
https://social.buffalomesh.net/web/statuses/102277565890775635 

**Friendica rendering:** 
https://social.outsourcedmath.com/display/9b1e8f93-125d-0559-5735-000328984393 

**BBCode source:**
`Woa. #America has been shitty to people for a really long time. Stole back the 40 acres and a mule, [i][b]AND[/b] paid former slave holders for the value of the formerly owned slaves![/i] We were a Trump-style country for a long freaking time.
[hr] [h4]Part 2 of "Eviction Crisis"[/h4][audio]https://www.podtrac.com/pts/redirect.mp3/audio.wnyc.org/otm/otm061419_cms943212_pod.mp3[/audio]
[attachment type='link' url='https://www.wnycstudios.org/story/on-the-media-40-acres' title='40 Acres | On the Media | WNYC Studios' image='https://media.wnyc.org/i/1860/1271/c/80/2019/06/40_acres_image.jpg']Part two of our series on eviction, and the human reality at the border amidst the latest Trumpian mendacity.[/attachment]
#Emancipation #Racism #Reparations #RedLining #HousingDiscrimination #FHA`

### Notes

I don't know how hashtags are handled elsewhere, but Friendica just wraps a URL anchor around them to search on the given server for that pattern.

BBCode is so finite and precisely patterned that it seems a mapping could be made on Mastodon that converts the markup to Mastodon render friendly instead of stripping it off.

**Comment by Gargron** [comment]
Source syntax usually does not matter. Federation transports messages as rendered HTML. We do not accept all HTML on our end, but links are accepted, so hashtags should not be affected. The Mastodon rendering link you posted is for logged-in users only so I cannot see what exactly you are referring to.

**Comment by WNYmathGuy** [comment]
Thanks @Gargron 
![Screenshot from 2019-06-21 22-09-25](https://user-images.githubusercontent.com/28640985/59958242-5af91780-9471-11e9-8b0b-958ced196c5c.png)
