### ISSUE TITLE
Single Column interface with all Timelines enabled

### ISSUE THREAD

**Issue by martinmuc** [mastodon/mastodon#11125]
Hi,
the single column interface is very nice and i am a big fan of it. But if i switch on e.g. local timeline, i dont see any news for hours, because of to few users on small instances locally and i am missing the federation timeline. If i switch to federation,  i will miss the other timelines. So i am now switching back and forth between all timelines, which is a little bit annoying anyhow.

How about a configuration checkbox on the topmost of the single column timeline, where i can enable/disable the 4 Timelines (home, local, federated and notifications), which i want to follow in one stream. So, i have all preferred timelines in one TL. Each toot can be marked e.g. on the upper right corner from which timeline is comes.

regards,
Martin

**Comment by Gargron** [comment]
You'll see local toots on the federated timeline

**Comment by martinmuc** [comment]
Thank you for your feedback. It wasn't clear for me, that the federated timeline is including the local timeline. Perhaps it should then better described, for people not so familiar with it. Regardless a user based configuration of what timelines are visible in the single column timeline isnt too bad, at all i think. Perhaps this can be reconsidered...
