### ISSUE TITLE
Hardcode a block of gab by default

### ISSUE THREAD

**Issue by Laurelai** [mastodon/mastodon#11129]
They are moving to use mastodon. Please hardcode a block on gab by default in such a way their servers cannot see ours.

**Comment by trwnh** [comment]
wouldn't a domain/IP block do this?

**Comment by Laurelai** [comment]
> wouldn't a domain/IP block do this?

Yes but shipping it out by default wll limit the harm they can do, gab has inspired mass shooters and murders.

**Comment by TheKinrar** [comment]
Instance admins can suspend gab themselves if they want too, Mastodon is only the software; it's up to the user as for how to use it.

**Comment by Laurelai** [comment]
Gab is different, you do not understand the type of threat they represent.

**Comment by TheKinrar** [comment]
I do understand your concern, that's not my point. What I'm saying is that hardcoding instance blocks is a restriction of the users' freedom while they use Mastodon, and, most importantly, that it means that Mastodon devs are now supposed to decide wether or not instances should be blocked by default in the future which might lead to other blocks, other restrictions of freedom.

I'm not saying Gab is good, nor I'm saying it's bad (well, in fact, I am, as they're blocked on my instance, but I'm not saying it here), I'm just saying it's not Mastodon's role to block them.

**Comment by Laurelai** [comment]
Im saying its everyones responsibility to combat the threat these people represent.

**Comment by TheKinrar** [comment]
Then encourage everyone to block them

**Comment by Laurelai** [comment]
I am. As seen by this issue being opened. Im taking all possible avenues.

**Comment by dascritch** [comment]
(reading this ticket, governments are preparing list of banned words to add in the source code, actively)

**Comment by Laurelai** [comment]
I opened a similar issue on glitch-social and florence. Both glitch and florence seem to be leaning in the direction of going for this idea. Ill probably approach pleroma and misskey too. And if you think blocking a known white supremacist terrorist group from the fedverse is the same as government censorship then you have lost the plot.

**Comment by TheKinrar** [comment]
not the same, but one allows discussion about the other in some way, at least

**Comment by aeris** [comment]
Please also blacklist any LGBT-related instances, because Saudi people consider them as illegal.
And any non communist political instances, because Chinese people consider them illegal too.

Welcome to the Fediverse Telescreen world…

**Comment by dascritch** [comment]
Dear @Laurelai , I understand your fears. But you must understand that you're opening a pandora box.

What could decide to add someone in this black list and what exempt it ?

Here, in France, government is discussing about a « Loi anti cyber haine » (« law against cyber-hate »), which is becoming a really dangerous open bag for any kind of censorship. Imagine what Iran, Saudi Arabia, China or United States can impose to the whole internet.

**Comment by farlistener** [comment]
@Laurelai I propose that if these instances are blocked by default, yours too, to balance the universe.
You want to harm open software, fine, you need to make a sacrifice.

I'm really against this idea ...

**Comment by nightpool** [comment]
I think @yipdw made a very good call by preemptively limiting the conversation on https://github.com/glitch-soc/mastodon/issues/1135#issuecomment-504005878 and I'll be doing the same here. Perdonallly, I think that client apps are the best place to add blocks for instances where the developers aren't comfortable with other people using their software. Hard-coded blocks in mastodon have several limitations client apps don't, and as ThibG has said, it's pretty difficult to achieve the level of isolation that we would desire from such a block (for statuses posted publicly, restricting public access is an unsolved problem).

that said, I think there's still value in this ticket and that we should consider it carefully before deciding one way or another. 

one thing I do want to say is that adding a hard coded block is in no way restricting anyone's freedom—nothing about adding a hard-coded block changes that Mastodon is free software that anyone can modify as they wish. comparisons to government censorship are completely inappropriate. the question is only about whether such a block is effective and appropriate for the mastodon project to recommend.

**Comment by nightpool** [comment]
Gab no longer federates.
