### ISSUE TITLE
Clicking in editor box (Web UI) to type a reply, results in focus going to top of parent post

### ISSUE THREAD

**Issue by imacdonald** [mastodon/mastodon#11132]
### Expected behaviour

- Clicking in editor box when replying to a post should keep the focus on the editor box

### Actual behaviour

- Clicking the editor box when replying to a post shifts the focus to the top of the parent post. If the parent post is long then the editor box vanishes below the visible screen.

### Steps to reproduce the problem

- Replying to a long parent post using the editor.

### Specifications

- Mastodon v2.9.0

- Firefox 60, Palemoon 28.0, Chromium 61.0.3163.100
- Debian 9.1

Video of the behaviour is inside the attached zipfile.

[mastodon-edit.zip](https://github.com/tootsuite/mastodon/files/3311294/mastodon-edit.zip)

**Comment by Cassolotl** [comment]
I have noticed this too and it is really annoying!
