### ISSUE TITLE
Improved transparency: let the user know when a whole instance or a user is blocked

### ISSUE THREAD

**Issue by schiessle** [mastodon/mastodon#11133]
I have a account on mastodon.social and I can't follow this account https://cmpwn.com/@sir

I don't know if I can't follow the user because mastodon.social blocks the whole cmpwn.com instance, because it blocks the specific user or if I can't follow the user because either https://cmpwn.com blocks mastodon.social or me specifically. Or maybe it is just a bug on one of the instances?

It would be great if I as a user could see somehow if there is any blocking involved, maybe in the form of a feedback when I press the "follow" button, so that I know what's going on. This also allows me to reach out to the admins if no blocking is involved to figure out what's the bug.

Maybe this could even be advanced so that the admin could add 1-2 sentences why a instance/user was blocked. This would help the users even more to understand what happens why and it would also help the admin when they review their blocking list to remember the reasons.

**Comment by vmstan** [comment]
Blocked instances are listed on `/about` page at the discretion of the administrator.
