### ISSUE TITLE
preview_url of toot's audio attachment that has artwork is 404

### ISSUE THREAD

**Issue by moko256** [mastodon/mastodon#11154]
### Expected behaviour
```preview_url``` contains thumbnail of audio artwork

### Actual behaviour
```preview_url``` contains url that return 404 like this: [small/91cea045debd1ae1.mp3](https://media-mstdn.maud.io/media_attachments/files/003/799/159/small/91cea045debd1ae1.mp3)

### Steps to reproduce the problem
1. Toot audio that has artwork
2. Get /api/v1/statuses and see media_attachments[0].preview_url

### Specifications
Original audio link is: [original/91cea045debd1ae1.mp3](https://media-mstdn.maud.io/media_attachments/files/003/799/159/original/91cea045debd1ae1.mp3)

At mstdn.maud.io (https://github.com/lindwurm/mastodon/commit/2d2de1be4a55698999249ef9a8d65d8980275a11) (Based on Mastodon v2.9.1 (aa9b37822bd39dff771844b7b1ac149e37788d34)) (I'm not admin)

**Comment by ykzts** [comment]
need
