### ISSUE TITLE
Sidekiq: Move LowPriorityDeliveryWorker to its own queue

### ISSUE THREAD

**Issue by joenepraat** [mastodon/mastodon#11175]
Right now ActivityPub::LowPriorityDeliveryWorker jobs are added to the regular queues. Therefore it's difficult for an administrator to estimate if there is a problem with the server. 

For example: Today I had a backlog queue of more than 2 million jobs, but I can send and receive messages without a serious problem. When there is really a problem, I can't see it, and I have to wait before one of my users tells me so.

So different queues (or any other visible way to see what's going on) for low priority jobs would be a welcome present for Mastodon admins.

Version running: 2.9.2

**Comment by nightpool** [comment]
I'm not sure I understand. The whole point of LowPriorityDeliveryWorkers is that they're added to the 'pull' queue instead of the 'push' queue? The pull queue is the lowest priority queue in mastodon.

**Comment by jeroenpraat** [comment]
@nightpool I don't know. There are also jobs in the pull queue that are processed almost immediately. I can send (push) and receive (pull) from/to remote servers.

**Comment by jeroenpraat** [comment]
@nightpool I understand from [this old PR](https://github.com/tootsuite/mastodon/pull/8345) that these are the queue descriptions:

- default: base functionality within the instance, highest-priority
- push: federation (mostly outwards), high priority
- mailers: used for mails (notifications, digest, …), low priority
- pull: lowest-priority tasks, mainly federation-related

So I understand that all those names are just poorly chosen and is very confusing. 

Still I like to find a solution for my original issue; to see if there are problems with the Mastodon server. I also think this related to #8342.

**Comment by jeroenpraat** [comment]
This is still relevant.

**Comment by ShadowJonathan** [comment]
@trwnh why did this get closed without comment?
