### ISSUE TITLE
Set up new instance with Terraform

### ISSUE THREAD

**Issue by vielmetti** [mastodon/mastodon#1118]
Terraform from Hashicorp is a system for provisioning new machines and maintaining infrastructure. 

It should be possible - maybe even easy - to put together a Terraform script that launches a new machine on your favorite provider, and then assembles together all of the code you need to get Mastodon started. Maybe it will only get you most of the way there, but it might well do the whole thing.

I'll share what I figure out about this here, and will use #terraform on Mastodon as a hashtag.

(Alternatively you might do this with Chef, Ansible, Puppet, or Salt "CAPS").

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by vielmetti** [comment]
See https://github.com/vielmetti/mastodon-terraform

**Comment by r7kamura** [comment]
Hi, I created https://github.com/r7kamura/mastodon-terraform to provide an easy way to set up Mastodon on AWS.
