### ISSUE TITLE
Users should be able to ignore instance silences

### ISSUE THREAD

**Issue by ealgase** [mastodon/mastodon#11218]
### Pitch

Allow users to unsilence remote instances or users that have been silenced by their instance.

### Motivation

Many instances silence other instances to prevent their users from being annoyed/harassed/seeing unmarked NSFW.  However, I'd like to be able to disable those protections, without needing to follow every user on those instances.

**Comment by rodti** [comment]
Could this be done via the 'Hidden domains' setting for the user?

**Comment by TemporaryUsername12481** [comment]
That might work, having the instance's silences be added to that list as "default hidden domains" or the like.

**Comment by trwnh** [comment]
Duplicate of #3890
