### ISSUE TITLE
Single column interface support for #tag searches

### ISSUE THREAD

**Issue by mariusor** [mastodon/mastodon#11238]
Hello, I love the new single column interface but I think it would be even better if it would support a method of adding custom tag searches as collections similarly to how you can add Lists. 

I think this feature is one of the last things to reach feature parity between the Advanced web interface and single column one.

**Comment by hirusi** [comment]
I am very much interested in this as well. The advance web interface is great, but as someone who wants to enjoy using Mastodon and not make it feel like "work", the following two factors do make it feel like "work":

- Scrolling horizontally when making a new search or wanting to open Messages (for example),
- having 24 toots (about 4 toots for each column, 4 columns) staring at me each time I open my homepage

I also do need every pinned hashtag updated to the minute. I'd just like if they stickied or a part of a list/collection that I could open at-will in the default/simple web interface.

A quick mockup:

![](https://i.imgur.com/TlTnt0A.png)

Doesn't need to have a title of "Pinned hashtags" -- it could go underneath navigation items like Lists, Profile Directory, and then the pinned hashtags.

**Comment by brunob** [comment]
This would really be useful, that's the only thing that keep me on multi column mode despite the fact that i find the single column one more readable :)

**Comment by mariusor** [comment]
I guess that with the feature of being able to follow a group of tags added in version 4.0, this feature request can be closed.
