### ISSUE TITLE
Plain hashtags in RSS / Atom feeds

### ISSUE THREAD

**Issue by raphaelbastide** [mastodon/mastodon#11239]
# Pitch

Currently, in RSS and Atom feeds, hashtags are split just like that `#<span>mastodon</span>` and it makes all attempt to filter the feed by hashtags more difficult.

### Motivation

I understand why hashtags need to be split with spans for the client interfaces of Mastodon, but I wonder if we can’t keep it as plain strings `#mastodon` in feeds to handle it more easily (string match with PHP or JS…). For example I suspect the service [IFTTT](https://ifttt.com/) not being able to detect the hashtag in the feeds for this reason.

Related issue:  https://github.com/tootsuite/documentation/issues/77

**Comment by nightpool** [comment]
if you're looking to do string matching on HTML content, you should convert
it to plain text first.
