### ISSUE TITLE
User names containing "-" from LDAP give 422

### ISSUE THREAD

**Issue by gerazo** [mastodon/mastodon#11277]
### Expected behaviour

User names containing hyphens ("-") are possible in connected systems using LDAP or other authentication. Mastodon should let all users (including those with hyphens in account name)  authenticated by LDAP in.

### Actual behaviour

If a user has "-" in the username and enters the password correctly, HTTP 422 error is returned. In case of incorrect password, the user is refused correctly.

### Steps to reproduce the problem

Try to login with any user coming from LDAP auth and having hyphen in the username. We could try it with a brand new user, so nobody could ever login with a username like this before.

### Specifications

v2.9.2

Probably related to:
Issue: https://github.com/tootsuite/mastodon/issues/9066
Issue: https://github.com/tootsuite/mastodon/issues/9309
PR: https://github.com/tootsuite/mastodon/pull/9345

**Comment by tigre-bleu** [comment]
Seems related to #6830

**Comment by gerazo** [comment]
Thanks @tigre-bleu According to what @Gargron said, there is a workaround by stripping or changing these problematic characters. But according to the bugs I've linked, hyphens were considered real bugs and those were fixed.
So my question is: Which way is the good way to go?
If the workaround is encouraged, where can I put such a regexp on usernames coming from other auth sources? (And would it really work also on auth? The user enters the real username and than gets an altered one also used for mentions?)

**Comment by tigre-bleu** [comment]
IMHO, the only solution is to separate authentification to LDAP using email, and username.

See the workflow I suggested in #6830: The user auths with LDAP using his email address and if it is the first time, he chooses a pseudo on the platform that shall respect the infamous regex that can't be changed.

Next logins he can either use is email to auth against LDAP, or use his pseudo. Mastodon then auths with LDAP by looking up for the email in its database.

If we don't want to bother too much, we could just allow to log via email and there is not the lookup functionnality to add.

**Comment by SuperSandro2000** [comment]
see #12021

Looks like you just need to set the ``LDAP_UID_CONVERSION_ENABLED=true`` env.

So this can be closed.

**Comment by gerazo** [comment]
Thanks for the information.
