### ISSUE TITLE
Instance choice

### ISSUE THREAD

**Issue by jelutz77** [mastodon/mastodon#11322]
Can we PLEASE get rid of the instance picking for interacting with posts of people on other servers? This is VERY annoying and will be a MAJOR obstacle to adoption for people used to simpler systems.

This could be accomplished with cookies and a drop-down on each post next to the action buttons instead of the annoying popup. The interface would look sort of like Facebook handles posting and liking as self or a page. This will make it MUCH simpler, especially for people with only one account.

You could use cookies, or at least a cookie for a subdomain for mastodon.social, for example. The cookie can just contain session information for all instances the user has logged into. Yes, this is a third-party cookie, but there could also be a better way.

**Comment by Gargron** [comment]
Well, no, no cookie can be shared between different servers, unless it belongs to a 3rd-party domain that all those servers load--say, setting a cookie on joinmastodon.org and having all servers load JavaScript from joinmastodon.org. However, I don't think that's a very good idea...
