### ISSUE TITLE
Advertisements

### ISSUE THREAD

**Issue by jelutz77** [mastodon/mastodon#11323]
Can you add an optional feature for advertisements? This will help instance admins who chose to use that feature finance their instance, making adoption easier.

**Comment by rodti** [comment]
Not personally keen on adverts, but you could create an account and in settings have all new users automatically follow that account. Then you can toot any server fundraisers or *gulp* adverts at them, and the users have an easy opt-out as they can unfollow that account at any time.

**Comment by kevinflo** [comment]
I run an instance that is pro ethical/untargeted duckduckgo style advertising ([Tinyfed.com](https://tinyfed.com)) and I feel very very strongly that this needs to be normalized in the fediverse. After all, ethical advertising supported RSS via podcasting and kept it from getting netflixtized all the way till 2019.

My quick-and-dirty solution was to create a "Sponsored" account and to set up all new accounts to auto-follow it. This also has the cool effect of making the whole advertising model opt-outable. Not perfect but good enough for now. 

Also my setup is really efficient, so I don't need to ad-fund it yet, but if the server sees an influx of users now everyone knows up-front exactly how the costs will be covered so it can stay healthy for everybody without compromising the instance's values (and maybe even so resources can be put back in to improve it).
