### ISSUE TITLE
Batch account management

### ISSUE THREAD

**Issue by fsnk** [mastodon/mastodon#11346]
### Pitch

It would be great to have the ability to perform sorting and batch operations on multiple accounts at the same time in the admin Accounts interface. (There are many available examples; most software that allows public user registration includes this kind of tool in administration and Mastodon already has this kind of interface for users to manage their following :) )

### Motivation

Allowing accounts created by automated registration to remain both artificially inflates user numbers and creates a potential security risk since these accounts are active and could be leveraged at any time. 

Right now account moderation requires manually scrolling through every page of the Accounts list (there is no sorting by e.g. activity or permissions available to reduce or reorder the list) and opening each individual account page and performing an administration function. This creates an unreasonable administration cleanup burden for e.g. situations with a high volume of bot spam registrations. (Ain't no one got time for that ;) )

Example: we still have multiple pages of this in our active accounts because there are no available cleanup tools for this kind of attack: 
![spamreg](https://user-images.githubusercontent.com/3524203/61439167-478e7e80-a941-11e9-8a10-c1d8cb28ae19.png)

**Comment by Floppy** [comment]
+1 on this, it's a problem we (mastodon.me.uk) have too with a large number of spam accounts that have never posted anything. One quick improvement might be to include the number of statuses in the account list, and make it sortable by that. That might at least give some indication of spam or dead accounts without the admin having to guess and click in to check.
