### ISSUE TITLE
Must run Mastodon docker setup twice

### ISSUE THREAD

**Issue by BNolet** [mastodon/mastodon#11368]
### Expected behaviour

setup should pull from supposedly saved .env.production from inside the container and use that info to populate db and compile assets. It does not, and db population

### Actual behaviour

![image](https://user-images.githubusercontent.com/10198484/61584887-998bfb80-ab1d-11e9-9539-1b038e96d753.png)

...

![image](https://user-images.githubusercontent.com/10198484/61584888-a3adfa00-ab1d-11e9-962d-ebbcf971edf2.png)

Setup fails after answering message in screenshot, ruby errors following: 

```
Running `RAILS_ENV=production rails db:setup` ...


rails aborted!
ArgumentError: `secret_key_base` for production environment must be a type of String`
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/application.rb:583:in `validate_secret_key_base'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/application.rb:432:in `secret_key_base'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/devise-4.6.2/lib/devise/secret_key_finder.rb:24:in `key_exists?'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/devise-4.6.2/lib/devise/secret_key_finder.rb:16:in `find'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/devise-4.6.2/lib/devise/rails.rb:37:in `block in <class:Engine>'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/opt/mastodon/config/environment.rb:5:in `<top (required)>'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/application.rb:337:in `require_environment!'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/command.rb:48:in `invoke'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create => db:load_config => environment
(See full trace by running task with --trace)
That failed! Perhaps your configuration is not right

```

### Steps to reproduce the problem

After setting up the environment  I ran `docker-compose run --rm web bundle exec rake mastodon:setup` using the pre-built images from the Docker Hub. I entered the required information, but didn't set up email. 

### Specifications

Using container image 2.9.2 for Mastodon, Ubuntu linux as the host. Docker version 18.09.8, build 0dd43dd87f. docker-compose version 1.24.1, build 4667896b

**Comment by BNolet** [comment]
From an inspection of the `.env.production` file located inside the container, it seems that the proper configuration *is* saved in the container, but it's not actually used. 

I tried to search through the scripts and whatnot, but couldn't turn up anything. Maybe someone much more familiar with the project can pinpoint the issue

**Comment by mfa777** [comment]
I just run `RAILS_ENV=production bundle rails  mastodon:setup` outside the docker to get one `.env.production` file, then to try to setup again inside docker.

Looks like mastodon didn't use docker image environment variable properly:

```
# Precompile assets
RUN cd ~ && \
	OTP_SECRET=precompile_placeholder SECRET_KEY_BASE=precompile_placeholder rails assets:precompile
```
The image has set SECRET_KEY_BASE already, but setup Processing didn't use this environment variable.

`ArgumentError: `secret_key_base` for production environment must be a type of String`
/opt/mastodon/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/application.rb:583:in `validate_secret_key_base'`

**Comment by BNolet** [comment]
But you shouldn't _have_ to run any of these things twice :/

I can see what you're saying here though with the envvar. However, this is for the compilation of assets? There's also a failure at the db population

**Comment by Rudraksh2003** [comment]
It looks like the issue is related to the `.env.production` file not being properly loaded or utilized within the Docker container, especially regarding the `SECRET_KEY_BASE` environment variable.

### Possible Solutions

1. **Ensure Correct `env_file` Configuration**:
   Verify your `docker-compose.yml` is correctly configured to reference the `.env.production` file:
   ```yaml
   services:
     web:
       env_file:
         - .env.production
   ```

2. **Mount `.env.production` Directly**:
   Try mounting the `.env.production` file directly from the host filesystem to ensure Docker uses it:
   ```yaml
   services:
     web:
       volumes:
         - ./.env.production:/path/to/container/.env.production
   ```

3. **Rebuild Docker Image**:
   Rebuild the Docker image without cache to ensure all changes are applied:
   ```bash
   docker-compose build --no-cache
   ```

4. **Manually Set Environment Variables for Precompilation**:
   If precompiling assets fails due to missing environment variables, set them manually:
   ```bash
   docker-compose run --rm web bash -c "OTP_SECRET=precompile_placeholder SECRET_KEY_BASE=precompile_placeholder rails assets:precompile"
   ```

5. **Verify Environment Variables Inside Container**:
   Run the following to ensure the necessary environment variables are loaded:
   ```bash
   docker-compose run --rm web env
   ```

6. **Check for Potential Docker Image Issues**:
   Consider using a different version of the Docker image or building from a `Dockerfile` for better control.

These steps should help resolve the environment variable loading issue during the Mastodon Docker setup.

**Comment by mjankowski** [comment]
This issue was originally filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please re-open this issue with updated logs/troubleshooting and we will take a look. Thank you.

Separately - if anyone tried the most recent suggestion here and had luck, thoughts on that welcome as well.
