### ISSUE TITLE
GUI issue: Toots not klickable to zoom in some modes

### ISSUE THREAD

**Issue by jacotec** [mastodon/mastodon#11361]
When a user is logged in and displays any timeline in the browser, or views a user's timeline, he can click on any place of a toot to get the full, zoomed view of the toot. As you can see, the mouse pointer changes to the "hand" icon to inicate I can click anywhere in this area to get the full view of the toot:

![image](https://user-images.githubusercontent.com/3321655/61532088-14bfb580-aa29-11e9-88a8-5dd6248f3de5.png)

In this mode the URL is like: mydomain.de/**web/accounts/4**

Viewing **the same account** / timeline in non-logged-in mode or with the URL:

mydomain.de/@username

(which has the same content as looking at ../web/accounts/4 in logged-in-mode), you need to **exactly klick on the timestamp of the message** (i.e. "10. Juli") to see the full toot in zoom mode with all comments. The remaining area of the toot is non-klickable:

![image](https://user-images.githubusercontent.com/3321655/61532395-fe662980-aa29-11e9-89fe-f2ed3a395d4c.png)

This is not only distracting to unknown / public users as they hardly can see how to expand the thread, it's also an inconsistent user experience as there is a different behavior for the same kind of display within the site.

Version: Mastodon 2.9.2
Browsers: Safari, Firefox, Chrome

**Comment by skeet70** [comment]
I was just checking out mastodon to possibly switch/use it and ran into this. I wouldn't have known to click the timestamp unless I'd found this issue.
