### ISSUE TITLE
PWA does not work on Firefox

### ISSUE THREAD

**Issue by Deuchnord** [mastodon/mastodon#11417]
On Android, the PWA seems to work perfectly on Chrome: after having logged in to your account, if you open the menu and tap _Add to Home screen_, the instance’s icon is added to the Home screen and opens the PWA correctly.

But on Firefox, when a PWA is available, there should be a small home icon that indicates a PWA is available (see screenshot below), which allows installing it. The option doesn’t seem to be available for Mastodon. Opening the menu > _Page_ and taping _Add Page Shortcut_ does not seem to have the same effect as on Chrome, because Firefox’s UI is displayed.

- Instance: hosted.social
- Version: 2.9.2

| Twitter URL bar on Firefox | Mastodon URL bar on Firefox |
| --- | --- |
| ![Screenshot](https://user-images.githubusercontent.com/7600265/61996341-89cb6480-b093-11e9-9b67-edcb00d0d03a.jpg) | ![Screenshot](https://user-images.githubusercontent.com/7600265/61996346-98198080-b093-11e9-8e67-9b68cecc8cf5.jpg)

**Comment by nightpool** [comment]
I don't believe Firefox on Android supports PWAs, although I'm happy to be
corrected. this sounds like a Firefox bug.

**Comment by Deuchnord** [comment]
It actually does supports PWA: https://hacks.mozilla.org/2017/10/progressive-web-apps-firefox-android/

I don't think the bug is on Firefox, because other websites providing PWAs work just perfectly. After a little test on a website of mine, it looks like Chrome displays websites in full screen when you add them to the home screen, even though they don't have any manifest file to define a PWA.

**Comment by danielbeutner** [comment]
I have the exact same issue the notifications are not working on Firefox for Android.

It works great in Chromium browser or Google Chrome.

Die further investigation it might be helpful that you may need to modify the notification settings on Android for the "Full screen control Firefox".

![Screenshot_20221116-125540.png](https://user-images.githubusercontent.com/531853/202175021-f2336cc9-c963-44f4-9d0a-2407b30b65f0.png)

It was set to "silent".
