### ISSUE TITLE
Hashtag / Hashtags won't work on toots with CW / content warning

### ISSUE THREAD

**Issue by KNTRO** [mastodon/mastodon#11443]
### Expected behaviour

I should be able to click on hashtagged words.

### Actual behaviour

Hashtags are not created/clickable.

### Steps to reproduce the problem

Just redact a toot with content warning and add hashtags to the toot. [Here's an example of the output toot](https://mastodon.social/@KNTRO/102524592320896636).

### Specifications

Mastodon Web v2.9.2.

**Comment by Cassolotl** [comment]
Hashtags in the CW field don't work, but if you put the hashtags under the CW, in the body of the toot, they work. CWs are intended to be plaintext. :)

**Comment by KNTRO** [comment]
The hashtags I used are in the body of the toot, like this:
[body of toot]
Blah blah blah, #hashtags are here
[CW content, clic to view]
[/body of toot]

**Comment by Cassolotl** [comment]
By "body of the toot" I mean the bigger text box. Here's a screenshot of what I mean:

![Screenshot 2019-07-30 at 17 03 51](https://user-images.githubusercontent.com/6607512/62145871-1cfed700-b2ec-11e9-855b-fe690fa7936b.png)

**Comment by Prog1563** [comment]
This would be a very nice feature to have

**Comment by dioraman** [comment]
Please fix this since it is counter-intuitive for newcomers that hashtags will not work in content warning.

**Comment by Vaguery** [comment]
Watching a large number of newcomers being told by the existing Mastodon community to "use CW as if it was a subject line" and also "use hashtags for findability".

If one cancels the other, this is a bug.

**Comment by trwnh** [comment]
Duplicate of #699
