### ISSUE TITLE
Polls are not updated to show as voted-in on clients other than the one that voted

### ISSUE THREAD

**Issue by OddBloke** [mastodon/mastodon#11523]
### Expected behaviour

I should have seen the post-vote information about the poll, instead of being presented with the vote options again.

### Actual behaviour

I was presented with the vote options, not the results. (A full refresh of the web interface addressed the issue.)

### Steps to reproduce the problem

1) Find a poll that you can vote on
2) Open the Mastodon web interface in two clients (in my case, it was Chrome on my desktop and Chrome-as-an-app on my phone)
3) Vote in the poll using one client
4) Observe the poll not being updated on the other

### Specifications

Mastodon 2.9.2 (with minor unrelated-to-polls changes); Chrome, Android and Ubuntu

**Comment by vmstan** [comment]
Resolved in newer versions.
