### ISSUE TITLE
Edit button, but only to add image descriptions

### ISSUE THREAD

**Issue by turtlebird** [mastodon/mastodon#11533]
### Pitch

Does what it says on the tin. A post hoc "add image description" button that allows you to edit a post only if there is an image with an empty image description

### Motivation

Image descriptions are a part of mastodon culture, to the point where many users will not boost a post without an image description. This would be of obvious utility to anyone who has forgotten to post an image description.

**Comment by trwnh** [comment]
this would more generally be handled by delete and redraft, but tangentially i think append-only editing might be an interesting approach more generally...

**Comment by turtlebird** [comment]
delete and redraft is a good feature if you realize right away, but it's frustrating to nuke a post that is already in circulation and redraft just to add an image description

**Comment by knuxify** [comment]
you can always reply to the post with an image description. it's not as intuitive but it works, sort of.

**Comment by Gargron** [comment]
Duplicate of #6829
