### ISSUE TITLE
Exclude home timeline from other timelines

### ISSUE THREAD

**Issue by clerie** [mastodon/mastodon#11530]
### Pitch

For many users the home timeline is their first place to start when checking out their Mastodon account. They've read all the posts. At some point their finished with this.
Now is the point to check out all the other timelines, i.e. the local or federated timeline. But it would really bad, if these timelines are full of posts they've already read.

For this I wish having an option in the timeline menu, to exclude all posts of my home timeline from the current one.

### Motivation

It helps users finding new posts and new other users, especially on instances with low incoming federated status frequencies.

**Comment by zuzak** [comment]
I would also like this feature. At the moment my federated timeline looks almost identical to my Home timeline, which is annoying. Being able to filter away non-home posts from the other timelines would be really useful to find the posts I've not yet read.
