### ISSUE TITLE
Not all hashtags are shown on a smaller screen < 1080p

### ISSUE THREAD

**Issue by akarshanbiswas** [mastodon/mastodon#11565]
Smaller screens like those on a laptop is unable to show all the trending hashtags.  

### Expected behaviour
It should show all the trending hashtags like on a bigger screen (like >=1080p)

### Actual behaviour
Only one hashtag is shown and rest are hidden.

### Steps to reproduce the problem

1. Open mastodon on a smaller screen (< 1080p)
2. Make sure more than two hashtags are trending
3. Observe the position of the hashtags.

### Specifications

2.9.3 + commit: https://github.com/tootsuite/mastodon/commit/26c229e6ed1dc3f0620937c9c000494385cb8c47

Browser: chrom{e,ium} , OS : Fedora 30

Screenshots:
On default zoom:

![Screenshot from 2019-08-14 22-51-47](https://user-images.githubusercontent.com/17230826/63041760-33a94e80-bee6-11e9-8a14-f3f1ff7630aa.png)

On zoomed out:

![Screenshot from 2019-08-14 22-52-01](https://user-images.githubusercontent.com/17230826/63041775-3c9a2000-bee6-11e9-92ea-80af02cbb512.png)

**Comment by Gargron** [comment]
This is intentional since they should not displace the more important navigation.

**Comment by akarshanbiswas** [comment]
@Gargron I wish the navigation panel could be scrollable atleast. :(

**Comment by akarshanbiswas** [comment]
I'm Sorry , I have to reopen this issue because it's a major problem. Shouldn't the UI adjust itself to different screens sizes and densities in the first place? The new menu "Profile directory" further hid the hastags and now not even a single hashtags is displayed. Can you please move hastags on the top right corner of the screen with a scrollable menu bar (home,notification,.....)?

@Gargron

**Comment by Maffsie** [comment]
Floating this issue up - a user on my instance literally didn't know that trending hashtags were a thing because their display resolution was such that a maximised Safari window didn't have the height needed for trending hashtags to be displayed. There should definitely be a better option than just yeeting it entirely from the things the user can see.

**Comment by Cassolotl** [comment]
![Screenshot 2020-07-27 at 11 15 16](https://user-images.githubusercontent.com/6607512/88532472-93680f00-cffc-11ea-9f59-bff4494e15b5.png)

I'm on an 11-inch MacBook Air, I have my dock at the bottom and I use the bookmarks bar. It's a normal laptop, not a particularly tiny one! I already have to scroll the Getting Started column anyway. Why *not* include the trending tags?
