### ISSUE TITLE
Using e-mail address with a period / full-stop affects messages

### ISSUE THREAD

**Issue by MxDozana** [mastodon/mastodon#11583]
I searched on the meta discussion and these issues, but there didn't seem to be a related bug report.

### Expected behaviour
I expected to sign up for a Mastodon server and be able to log in.

### Actual behaviour
I signed up to a Mastodon server with my e-mail address that includes a period / full-stop, ".", in it. I received the welcome and confirmation e-mail messages, but could not log in.
I requested a password reset, but only received the reset message when typing my address without the period / full-stop.
I can log on fine if I type my e-mail address without the period / full-stop in it.

### Specifications
I tried this today on eldritch.cafe, but I recall a similar or the same issue with scholar.social a few months ago.

**Comment by MxDozana** [comment]
This also affects the Tootle app for iOS, version 1.11.1

**Comment by Gargron** [comment]
Upstream Mastodon does not do anything with stops in e-mail addresses.. Those servers might have had some customization..?
