### ISSUE TITLE
Add a moderation option to mark all toots for an account 'sensitive'

### ISSUE THREAD

**Issue by raboof** [mastodon/mastodon#11581]
### Pitch

When a user toots sensitive images without marking them 'sensitive', and these are federated to an instance where marking such images with 'sensitive' is required, currently the only moderation option is to 'silence' the user there entirely.

It would be great to add a moderation option to mark all a users' toots as sensitive.

### Motivation

This would allow the material to be discovered and enjoyed by those who might like it, while avoiding shoving it into the faces of users who might not appreciate it.

Somewhat related to #8186 and #7066

**Comment by Cassolotl** [comment]
Nooo, this would be really useful!

**Comment by Cassolotl** [comment]
Thanks, bot. :D
