### ISSUE TITLE
Uploading animated gif results in corrupted colours

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#11599]
Currently when I upload my avatar, it gets resized and this causes some corruption of the colours:

Original:
![new-avatar](https://user-images.githubusercontent.com/42093217/63219927-8ff8c080-c1bb-11e9-8a15-593f37ac20eb.gif)

Static resized:
![bad-avatar](https://user-images.githubusercontent.com/42093217/63219937-bfa7c880-c1bb-11e9-958f-2aa57131bd29.png)

This is in v2.9.3.

It would be nice if instead of a poorly compressed gif, animated avatars could be uploaded as either mp4 or webm instead. This would reduce the burden of high speed animations on low end systems and also improve the quality of resized animated avatars.

**Comment by TheEssem** [comment]
The ImageMagick command used for processing profile picture uploads seems to be missing the `-coalesce` operator, which is necessary a lot of the time for proper GIF manipulation. However, this also increases the filesize significantly for many GIFs; this can be mitigated slightly with `-layers optimize` at the end, but it isn't a silver bullet and may just make it worse.

**Comment by kescherCode** [comment]
In general, when working with GIFs, I've found both ffmpeg and [Gifsicle](https://github.com/kohler/gifsicle) to be much better both in terms of filesize and... not corrupting the GIFs. I might replace GIF optimizations with either of these two in my fork.

**Comment by TheEssem** [comment]
I can personally vouch for libvips and the cgif encoder, they're incredibly performant and have plenty of options for optimization. Seems like moving away from Paperclip would allow for easier usage of vips, see #7414 and #20269.

**Comment by vmstan** [comment]
Possible that #30090 addresses this.
