### ISSUE TITLE
Upgrade notes for 2.9.0 do not mention new nodejs version requirement

### ISSUE THREAD

**Issue by progval** [mastodon/mastodon#11600]
### Expected behaviour

[Upgrade notes for version 2.9.0](https://github.com/tootsuite/mastodon/releases/tag/v2.9.0) should mention that #10805 increased the required Nodejs version to >=8.12.

### Actual behaviour

Without knowing this, I had to abort my instance upgrade in the middle, because of:

```
$ yarn install
yarn install v1.15.2
[1/6] Validating package.json...
error mastodon@: The engine "node" is incompatible with this module. Expected version ">=8.12 <12". Got "8.11.2"
```

**Comment by ProgVal** [comment]
This issue is not fixed.
