### ISSUE TITLE
Media is not getting deleted after deleting post

### ISSUE THREAD

**Issue by koyuawsmbrtn** [mastodon/mastodon#11637]
### Expected behaviour

Deleting a post should delete media

### Actual behaviour

Deleting a post didn't delete media on the server's hard drive

### Steps to reproduce the problem

Posting a post with media attached and deleting it afterwards

### Specifications

Version 2.9.3+

**Comment by Gargron** [comment]
Are you certain it's not just cached by nginx or cloudflare?

**Comment by koyuawsmbrtn** [comment]
> Are you certain it's not just cached by nginx or cloudflare?

Nothing is being cached, I cleared everything out and even run the media_cleanup_scheduler (or whatever its being called) task in Sidekiq.

**Comment by Gargron** [comment]
Wait, you're right, I forgot. Yes, media is not deleted when a post is deleted to support delete & redraft. Instead, the media becomes "unattached". Unattached media is cleared away after 1 day by the media cleanup scheduler.

**Comment by Gargron** [comment]
Related: #11638

**Comment by rgrunbla** [comment]
>Unattached media is cleared away after 1 day by the media cleanup scheduler.

Just adding some precision : Unattached media is cleared away *every 24h*, so they might be cleared away up to 2 days after their creation, not 1 day.
