### ISSUE TITLE
Gem::LoadError

### ISSUE THREAD

**Issue by voi159** [mastodon/mastodon#11684]
### Expected behaviour
Key Creation

### Actual behaviour
Gem::LoadError: You have already activated rake 12.3.2, but your Gemfile requires rake 12.3.3.

### Steps to reproduce the problem
1. git clone https://github.com/tootsuite/mastodon.git
2. cd mastodon
3. cp .env.production.sample .env.production
4. docker-compose build
5. docker-compose run --rm web rake secret

### Specifications
1. Last version Mastodon
2. Ubuntu 18.04 LTS

**Comment by lachesis** [comment]
Oh no, the exact same bug I'm facing, from over a year ago with no comments. :(

Is docker-compose still supported for this project?

**Comment by qawnaoya** [comment]
I have same case.

git clone --depth 1 -b v3.2.1 https://github.com/tootsuite/mastodon.git mastodon-3.2.1
cd mastodon-3.2.1
cp .env.production.sample .env.production
sudo docker-compose build
sudo docker-compose run --rm web rake secret

Ubuntu 18.04.5 LTS (Bionic Beaver)
