### ISSUE TITLE
Feature: More languages support and progress bar in OCR tool

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#11719]
### Pitch & Motivation

- `tesseract.js` supports [more than 100 languages](https://github.com/naptha/tesseract.js/blob/master/docs/tesseract_lang_list.md) and their combinations (eg: `eng+chi_tra` for English and Traditional Chinese).
- It's too slow to load language data and perform recognization.

**Comment by Gargron** [comment]
There is a progress bar in the OCR tool... That it is slow cannot be helped. Tesseract supporting multiple languages is great and all but there's no way for us to know which language to load before the recognition. Loading more languages would be even slower and require more bandwidth (a language file is > 10 MB). The English set will recognize most ASCII characters and that's the trade-off between accuracy and speed/bandwidth I've chosen.

**Comment by aka-rin** [comment]
@Gargron Sorry, maybe I should make it clear...

1. Since `tesseract.js` runs on client side, you can add a dropdown menu to let user choose the language before recognization. ASCII characters may be not enough since fediverse is not an English-speaking world. Other language training data can be loaded via CDN or media proxy.
2. The progress bar does not show the progress of downloading assets so it will stay at 0% while loading resources, which is a bit user-unfriendly. Although service worker will cache them, it is still confusing to users at the first time.

**Comment by bbaermann** [comment]
the tool is basically unusable for longer german text. this should be fixed. the userbase of mastodon is largely european and most of european languages have some kind of non-ascii characters.

**Comment by jubalfh** [comment]
please reconsider the design of the ocr feature; as it's user-driven, user is well able to specify the language of the image before starting the scanning process.

**Comment by hkolbeck** [comment]
Howdy, I'm working on a project around user alt text that's done some work around this, if that makes anything easier. To start with, here's some JS with the human readable name of every language supported by Tesseract: https://github.com/alt-text-org/my.alt-text.org/blob/main/src/tesseract.js#L27. I'm currently seeking help adding translations and non-latin keys, and there may be some by the time you read this.

There's code that turns that list into a live searchable dropdown, and then changes out the extraction language on selection. The training data is pulled from the Tesseract org, having to occasionally pull down 10M from a third party doesn't feel like a big issue.

For a preview of the project, check out https://alt-text-org.github.io/my.alt-text.org/, or if that doesn't work it might be moved to https://my.alt-text.org

**Comment by mjankowski** [comment]
Last relevant update here is pretty old ... going to close this one on the assumption that we are sort of stuck/content relying on the underlying library in terms of performance and accuracy and cannot really control much of the results from an app perspective.

Please reopen if this is still a large issue and/or you have other solutions/ideas that might improve things?

**Comment by hkolbeck** [comment]
@mjankowski A possible approach that I think would minimize load on the core devs here while allowing movement forward would be to pull the tesseract usage behind an interface, allowing the easier public exploration of other options. I realize that this may be far from simple depending on the current call paths, etc.

**Comment by mjankowski** [comment]
I think that would actually be pretty straightforward if someone wanted to do that. The surface area is pretty small and its usage is pretty limited to that one area. No idea if a wrapper like that would be reviewed/merged.

If anyone does do that, maybe accompany it with a description about how some hypothetical other wrapper lib could be plugged in instead and how that might improve things?
