### ISSUE TITLE
on success /share page should provide some feedback

### ISSUE THREAD

**Issue by simevo** [mastodon/mastodon#11751]
when a new toot is created with the `/share` page there is no feedback to the user:

![GIFrecord_2019-09-03_212202](https://user-images.githubusercontent.com/8254819/64202297-1a664300-ce91-11e9-83d6-cabfc16b0011.gif)

she has to open her own home feed to make sure the status has actually been published

on success the `/share` page should provide some feedback such as:
- "your toot xxx has been published" and a link to the status
- (better) straight redirect to the new status

**Comment by simevo** [comment]
On hitting the "Toot!" button, it does a `POST https://mastodon.social/api/v1/statuses` which returns:
```javascript
{
  "id": "104018243897147731",
  ...
}
```

this `id` is all we need to redirect the user to the new status: https://mastodon.social/web/statuses/104018243897147731

The form on `/share` is defined in `app/javascript/mastodon/features/compose/components/compose_form.js`. When the "Toot!" button is hit, control goes to `app/javascript/mastodon/actions/compose.js`.

I'd love to create a PR, sadly I'm not into React enough to know where to tweak it so that it redirects to https://mastodon.social/web/statuses/104018243897147731. Can I haz a hint ?

**Comment by simevo** [comment]
On second thought, what would be really cool is if this form could be customized with a webhook, as in: https://mastodon.social/share?text=sometext&callback=https%3A%2F%2Fexample.com%2Fwebhook

if the `callback` argument is supplied, on success Mastodon forwards the new status JSON to the supplied endpoint with `POST https://example.com/webhook`. If no `callback` argument is supplied, simply redirect to the new status.

**Comment by 1bubble1** [comment]
I also noticed this

**Comment by simevo** [comment]
almost there! the **Post published** toast added with [MR 25564](https://github.com/mastodon/mastodon/pull/25564) now also appears on the share page ... but clicking on the **OPEN** link has no effect here :crying_cat_face: 

(it works fine when the Publish button is clicked from the SPA)

**Comment by renchap** [comment]
This is fixed, the new 4.3 composer disables the button when you post.
