### ISSUE TITLE
Account content ratings

### ISSUE THREAD

**Issue by Gargron** [mastodon/mastodon#11794]

**Comment by tykayn** [comment]
what does it do, to achieve what goal ?
give a polled score on notes to get social credit like in China?

**Comment by jeroenpraat** [comment]
Besides I'm 99.9% sure it's unwanted by the community, there are also the following issues:

1. It will be used as a harassment tool. They tried this in the initial stadium of Hubzilla and it was immediately used to attack people. It was removed, I don't know if it ever came back in another form.

2. It creates a popularity contest. Something that is unwanted by the community from the beginning. Giving a little bit of acknowledgement or popularity with boosts, favorites and amount of followers is IMO the maximum.

3. Mainstream content will eventually prevail. Radical and controversial content will eventually bleed dead. Yes there is problematic content, but the current moderation system is good enough to handle that.

**Comment by RokeJulianLockhart** [comment]
By "Content ratings", are we referring to something like ESRB ratings, delimiting whether the acocunt's content is primarily child-friendly or not? If not, like the unhinged comments at https://github.com/mastodon/mastodon/issues/11794#issuecomment-549766459 and https://github.com/mastodon/mastodon/issues/11794#issuecomment-618555591, does https://github.com/mastodon/mastodon/issues/11794#issue-491189259 instead refer to a karma rating for the account, like Reddit provides?

I support both, but I'd like the clarification regardless. This is why issue reports should contain at least some information.

**Comment by mjankowski** [comment]
This is ~6 years old and ... without a clear description?

Going to close this on assumption that other since-developed moderation tooling may have quenched our thirst here, but please reopen with more detail if not!?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mastodon/mastodon/issues/11794#event-15442042208

@mjankowski, perhaps close as invalid instead?
