### ISSUE TITLE
Instance admins should be able to see all public toots

### ISSUE THREAD

**Issue by arteteco** [mastodon/mastodon#11807]
### Pitch

So, if a user blocks an instance admin, said admin won't be able to see the user posts. This can come as a problem when monitoring for violation of ToS and checking how things are is the main task of a mod or admin. 

I know it is possible to check the user profile from a browser session with no logins, but it's not imaginable to do that for every user.

If this feature is already present could you point it to me?

### Motivation

If you can't see harmful or problematic content you can't take measures, and you'll discover it only when it gets  reported.

Thanks!

**Comment by Gargron** [comment]
All public statuses are visible through the admin interface.

**Comment by arteteco** [comment]
Hi, thanks for your reply.

I know they are if you explicitly go look for them, but how often does a mod skim through all of the accounts in the admin interface just to check if everything is alright? You'll go to your admin interface once you know that something is wrong, you have a report or something. I'd like to be the one noticing it.

Now, I can see a few options: a duplicate of the local timeline in the mod interface but with all public posts displayed or, probably better, when a user is a mod or admin the local timeline is by default all shown. Or, also, remove the option to block local mods.

Just a few ideas, hope they make sense.
