### ISSUE TITLE
429 Throttled when deleting several toots

### ISSUE THREAD

**Issue by Sciss** [mastodon/mastodon#11842]
### Steps to reproduce the problem

This has been around for very long time, and occasionally when I clean up my old toots, deleting and unboosting them, it comes back and back again. When I start deleting old toots, it's only a matter of time (e.g. deleting more than five or so toots) until it becomes impossible to perform delete operations, as they only result in a '429 Throttled' pop-up. Refreshing the browser window doesn't fix this; also not logging out and back in.

### Specifications

Currently with v2.9.2 on octodon.social. I'm using the web interface on Firefox 60.9.0esr. (Don't ask why the attached video is suddenly speaking French; this was not before the screen recording, it just said 'Throttled').

![Screencast from 14-09-19 15_17_20](https://user-images.githubusercontent.com/131300/64908699-d5010b80-d703-11e9-905f-b392c8022323.gif)

**Comment by Gargron** [comment]
Status deletes are very expensive so there is a strict rate limit that is optimal for the network. Please delete at a slower rate or use an automated tool that respects the rate limit.

**Comment by Sciss** [comment]
I cannot automate this, because I want to select particular toots. Perhaps a fix would be to schedule the deletion at the next possible time interval, when I click 'delete'.
