### ISSUE TITLE
Grayscale PNGs become washed out

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#11844]
Original | Thumbnail
--- | ---
![original](https://files.mastodon.social/media_attachments/files/018/856/387/original/26d31c8fce7a835b.png) | ![thumb](https://files.mastodon.social/media_attachments/files/018/856/387/small/26d31c8fce7a835b.png)

### Specifications

mastodon.social

**Comment by trwnh** [comment]
Just reproduced on mastodon.social (3.0.0) but not on nulled.red (2.9.0)

**Comment by marrus-sh** [comment]
i have noticed colour changes as well and assumed that they were due to the colour space changing (if the colour space of the original image was not sRGB)—might be something to check

**Comment by Gargron** [comment]
Might be due to metadata being stripped?

**Comment by trwnh** [comment]
Not sure what metadata could cause this, but it just happened again with two screenshots from the same phone, both cropped by Google Photos app. One thunbnail is fine, one is washed out. https://mastodon.social/@trwnh/103022846981307851

Only difference I can see is that the one that got washed out got cropped closer and therefore includes only the background and text? So my hypothesis right now is that it might have something to do with the fact the image only contains gray tones? Maybe there's some grayscale conversion happening that should not be happening?

**Comment by trwnh** [comment]
Hm, I think it is the grayscale after all. I opened both images in GNU IMP and found out that they were 8-bit sRGB grayscale instead of 8-bit sRGB RGB. Presumably, Google Photos is doing some silent lossless conversion in an attempt to save space?

In any case, manually converting it back to RGB and uploading side by side, I observe the following:
- in the compose box, both image thumbnails are washed out
- after posting, the RGB thumbnail is correct while the grayscale one is washed out

**Comment by trwnh** [comment]
Manually did my own convert with the same options as Mastodon's media_attachment.rb, but added `-define png:format=png8`, which resulted in the second image here: https://mastodon.social/@trwnh/103023341293166601

I observed the same "incorrect in compose box, regenerated correctly after upload" behavior.
