### ISSUE TITLE
Support aliased properties & types from vocabularies in JSON-LD @context 

### ISSUE THREAD

**Issue by cjslep** [mastodon/mastodon#11966]
go-fed [just fixed a bug](https://github.com/go-fed/activity/issues/119) in its code-generated serialization. It aliases all non-ActivityStreams vocabularies in the JSON-LD context:

```
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    {
      "widsv": "https://w3id.org/security/v1"
    }
  ],
  "type": "Person",
  "widsv:publicKey": {
    "type": "widsv:PublicKey",
    "widsv:publicKeyPem": "test PEM value"
  }
}
```

I want to ensure Mastodon is able to handle these kinds of payloads properly when deserializing data for operations such as HTTP signatures.

**Comment by trwnh** [comment]
late response but this above example is technically invalid. you can define a term that aliases a *prefix*, but when providing an entire context document, you should just use it directly. so either

```json
{
  "@context": ["https://w3id.org/security/v1", "https://www.w3.org/ns/activitystreams"],
  "publicKey": ...
// ...
}
```

or

```json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    {
      "widsv": "https://w3id.org/security#"
    }
  ]
}
```

this allows for the translation from `publicKey` or `widsv:publicKey` to `https://w3id.org/security#publicKey`
