### ISSUE TITLE
Split Privacy Policy / ToS strings to separate files

### ISSUE THREAD

**Issue by brawaru** [mastodon/mastodon#12080]
### Pitch

Currently Privacy Policy is placed just like any other string in localization files. The idea is to split them into separate files in according format (`$LOCALE_FILE:terms:body_html` → `$PROJECT_DIR/config/locales/terms.$LOCALE.html`)

### Motivation

Doing this allows Crowdin translators to translate file sentence for sentence instead of the whole file. Translators also don't touch HTML and can see preview instead. This eases the process of translating and proofreading these documents.

![Example of online editor with HTML file](https://support.crowdin.com/assets/docs/list_colors.png)

### Implementation info

**Difficulty**: can be rather difficult to implement (?).

**Importance**: low, most translators avoid translating ToS due to not having legal skills.

**Things to consider**:

- :question: Needs check: Crowdin may return incomplete file instead of keeping original untranslated sentences if unavailable.
- :grey_exclamation: It is may needed to include translation notice at the top of the page linking to the original document.

### See also:

- #8362: idea about splitting Terms of Service, Code of Conduct, Privacy Policy to different pages

**Comment by Gargron** [comment]
I think neither should be translatable since CrowdIn translators cannot be expected to translated legal documents in a compliant way.

Neither is a translatable string anymore, so I am closing this.
