### ISSUE TITLE
Sending a notification to all users of an instance

### ISSUE THREAD

**Issue by wxcafe** [mastodon/mastodon#1209]
Hey! As an admin, it would be pretty nice to have a way of notifying all users on the instance
of impending maintenance or of an acknowledgement of an issue or something. Right now
what I've done is add in the site /about/more that people should follow an account that posts
stats about the server and sometimes announcements like these. But not every user does, and
it would be pretty nice to have a simple way to tell all local users directly.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by op3nus3r** [comment]
I agree,
it would be great to have a default channel to communicate to users when there is maintenance on the server or other admin messages.
This could be the Admin@Instance.tld account

The message would be displayed at the top of the notifications column and you would have to click (close) to confirm that you read correctly.

Perhaps through notifications, like this:

![notif](https://cloud.githubusercontent.com/assets/22491305/24876005/55ad5b8e-1e2a-11e7-84dd-6eac1706c502.png)

**Comment by thor-the-norseman** [comment]
We just founded the Norwegian Society for Free Social Media to run our instance, and would like to make various announcements to our users. Can we get some kind of highlighted, pinned notification, or bar at the top/bottom of the user interface, that can be un-highlight-pinned or dismissed by the user once they've seen it?

**Comment by thor-the-norseman** [comment]
This ticket, or tickets similar to it, has been created like 4 or 5 times now. I think it should have high priority.

**Comment by wxcafe** [comment]
when I tagged this, the priority labels weren't there yet. I'm tagging it that way

**Comment by sorin-davidoi** [comment]
For extra important announcements, we could allow admins to send the push notifications even to users who disabled them.

**Comment by wxcafe** [comment]
This is still up and it's still important
I'm noting here the various admin toots saying they'd like such a feature
https://octodon.social/@tcql/98963349613291690
https://octodon.social/@tcql/98963359161855791
https://dev.glitch.social/@MightyPork/98963387190380419
glicsoc even implemented a kind of local-only toots, and even if that doesn't fulfill the need in this issue it's still proof that it's wanted by a lot of people

I'm assiging @Gargron on this

**Comment by witcheslive** [comment]
I would extremely like this, I post frequently and with some notice whenever I have to do some changes that involve taking the server down and yet someone posts their surprise for it every time. It seems to give people anxiety like something is wrong or the server is going away, rational or not, and being able to do this would be immensely helpful.

**Comment by ClearlyClaire** [comment]
I think this is addressed by #12662
