### ISSUE TITLE
Local custom emoji don't seem to be rendering in toots

### ISSUE THREAD

**Issue by TrollDecker** [mastodon/mastodon#12136]
### Expected behaviour

Custom emoji shortcodes should be replaced by their respective emoji.

### Actual behaviour

Certain custom emoji shortcodes are not being properly replaced with their actual emoji, despite their presence and correct rendering in the emoji pickers and in the Custom Emoji control panel in Preferences.

Affected emoji that I've found so far have the shortcodes :blobeyes: and :blobhearteyes:

I've attempted another precompile (no warnings or errors there) and also delete and re-copy the offending emoji, to no avail.

### Steps to reproduce the problem

Posting a toot with a custom emoji. >.>

### Specifications

v3.0.0

Problem appears regardless of using a browser or a client app, so I suspect something is going wrong in the background.

**Comment by Gargron** [comment]
To my knowledge 3.0 did not touch custom emoji parsing or rendering code. They would not be affected by asset compilation either. Are you sure this is not related to object storage provider outage (e.g. Wasabi)?

**Comment by TrollDecker** [comment]
I'm certain, because I don't use an object storage provider.

**Comment by TrollDecker** [comment]
Thanks to some outside help, it turned out that something went a bit wonky with the `custom_emojis` table and I had to go through the following process:

https://monsterpit.net/@multiple_creatures/102945326604495384

Everything is hunky dory now, but I'm not sure what could have caused that over the course of the update process from v2.9.0 to v3.0.0, though.

**Comment by ThibG** [comment]
I have seen multiple reports of similar things (not specifically on v2.9.0 to v3.0.0 migrations though), so we're probably doing something wrong somewhere…
