### ISSUE TITLE
Possible bug in account migration

### ISSUE THREAD

**Issue by stevenroose** [mastodon/mastodon#12169]
So I migrated my account about 3 months ago from a large public instance (https://fosstodon.org/@stevenroose) to a smaller instance (https://x0f.org/@stevenroose). I noticed that many of my followers missed my account change, so I thought I might be able to use the new follower move procedure to try move the remainder over.

So once both instances upgraded to the new Mastodon version (remarkably fast), I tried. However, I can't seem to re-activate my Fosstodon account.

When I enter the account settings in Fosstodon, I get this screen:
![screenshot-2019-10-15-12-47-40](https://user-images.githubusercontent.com/853468/66828802-d8c5bf00-ef49-11e9-93b6-711eb3c9da54.png)
The `Cancel redirect` link is to this URL: https://fosstodon.org/settings/migration

Clicking it brings me here:
![screenshot-2019-10-15-12-48-55](https://user-images.githubusercontent.com/853468/66828869-fd219b80-ef49-11e9-9176-546834ddddf8.png)

Clicking that link brings me back to the first view, giving me the same message. So I can't seem to re-activate the account.

This might be on purpose, but in that case, it should give me an appropriate message.

**Comment by Gargron** [comment]
This is a bad UX problem. The first link is just a link, not an action. The actual action is the "Cancel redirect" you see in the 2nd screenshot. Sorry.

**Comment by stevenroose** [comment]
@Gargron What I'm saying is that when I click the "Cancel redirect" on the second screen, the same message stays on the first page. I can keep clicking "Cancel redirect" back and forth between the two pages. Even when I close or refresh the settings, the redirect stays active.

**Comment by MasterOfTheTiger** [comment]
I also experience this issue on quey.org.

**Comment by ThibG** [comment]
I can't reproduce this, and I don't understand how it could end up this way.
Can you verify that clicking that link actually issues a POST request with a `_method: delete` param?
