### ISSUE TITLE
Terms field too short

### ISSUE THREAD

**Issue by jelutz77** [mastodon/mastodon#12174]
I receive an error when saving TOS if it's more than 773 characters. This is not enough for a TOS document.

I paid for some legal assistance with my TOS, which resulted in a 12k document. Please increase the size to be much more than that! Anyone who is concerned enough about legal protections to have TOS written professionally will have a pretty long document here.

**Comment by jelutz77** [comment]
As an alternative, support for some sort of import, such as an HTML5 import would be good too, example below:
<link rel="import" href="/path/to/imports/stuff.html">

**Comment by NimaBoscarino** [comment]
What kind of error do you get when you save the TOS? Do you have a screenshot? On v3.0.1 I'm able to save the TOS even with 30k words (182k words).
