### ISSUE TITLE
Account quality filter for notifications

### ISSUE THREAD

**Issue by MirceaKitsune** [mastodon/mastodon#12181]
On platforms like Twitter, users are given ways to filter notifications from accounts that aren't verified. While Mastodon can't ask users to verify themselves with a phone number, it might be a good idea to allow filtering based on other simple criteria, permitting users to request some form of guarantee that an account is legitimate. This can include:

- Hide activity from accounts newer than X days.
- Hide activity from accounts with fewer than X posts.
- Hide activity from accounts with less than X followers.
- Hide activity from accounts that didn't set an avatar, banner, and bio.

I suggest this out of concern at the possibility of organized attacks, which Mastodon doesn't currently offer a lot of protection from: Nothing would stop a group of bad actors from making 1000 accounts on 10 instances and using them for the purpose of harassment. In such a scenario it could take hours or days until moderators everywhere would get to deal with every last one. Such a system would ensure that before an user can generate notifications, they meet basic criteria which make it likely they would have been caught if they were an attacker.

On the downside this could cause good users who are recently registered to have a harder time getting the attention of people who enable this feature. The thresholds should thus not be too high so an account can be considered proven after a few days. A good set of settings for the algorithm might be: Must be at least 7 days old, must have at least 100 posts (can include boosts but not favorites), must have at least 10 followers.

Although this would discourage the causal troll, it wouldn't stop a determined attacker from automating posts or having multiple accounts follow each other to reach the thresholds immediately. For this the system might need a deeper verification mechanism. For instance: Don't count followers who themselves didn't reach this criteria, while ignoring posts that are too frequent (if multiple posts were made in an interval of less than a minute, only one post is counted). Of course going this far can have negative performance implications.

**Comment by trwnh** [comment]
i'm worried that something like this would confuse "quality" with "activity".

**Comment by MirceaKitsune** [comment]
That is true. I'm basing this off a feature I used on Twitter which is a little different: You can filter notifications from accounts not verified by email or phone number (2FA). I stopped seeing the most extreme replies once I enabled that. But that's likely because banned users aren't able to get a new phone number in order to return and get new accounts verified... I'm not sure what the result would be here without that.

**Comment by Cassolotl** [comment]
I would be into this, because quite often I get follow requests from, for example, accounts with no posts and no avatar and no followers, who are already following 150+ people. They might well be new and excited about the fediverse, but I don't feel safe to accept them until I can see a bit more about them and know they're a real person. Being able to hide follow requests from those people would be cool, and I'll bet other similar things would be useful too - especially for people with a lot of followers.

**Comment by Cragsand** [comment]
Reviving this suggestion again after reading through these discussions:

- https://mastodon.social/@TechConnectify@mas.to/111433250593753736
- https://mastodon.social/@TechConnectify@mas.to/111428308397058438

Those who have a large amount of followings could really benefit from some sort filter that at the minimum sorts out posts that contain negative language and only shows them after clicking "Show more replies". How to implement this is rather tricky and bears careful consideration. To not overtly silence but also respect consent by having it available as an opt-in feature.

This is the similar feature described on the birdsite. https://help.twitter.com/en/managing-your-account/understanding-the-notifications-timeline 
![bild](https://github.com/mastodon/mastodon/assets/49168045/06e3d5ff-59e5-4d2a-ada2-9841fb26bec9)
![bild](https://github.com/mastodon/mastodon/assets/49168045/9a9f08af-f2c7-4680-966d-22e44958810f)

**Comment by ccoenen** [comment]
I would like to warn that processing some kind of "negative language keywords" automatically will mean that this is going to be limited to a select few blessed languages. Depending on the way this filter is applied it will also be trivial to circumvent if someone is trying to do harm intentionally.

**Comment by Cragsand** [comment]
> I would like to warn that processing some kind of "negative language keywords" automatically will mean that this is going to be limited to a select few blessed languages. Depending on the way this filter is applied it will also be trivial to circumvent if someone is trying to do harm intentionally.

This is true and does makes it difficult to implement. There's never going to be a perfect solution but the majority will not realize how it works, and how to counteract it, so already there there it saves some exposure to negativity.

One way I can imagine to counteract this could be by checking if words are interrupted with dots commas or random characters that are not in regular language and weight them as also being negative. If Mastodon has language translation built in it could weight it for coherency of using actual words. If a message contains the majority of gibberish it gets weighted as negative.

**Comment by shaunagm** [comment]
I just want to +1 this - I'm a pretty small account and even I get annoyed by the deluge of replies when something goes viral. I would hate to be in the position of some of my more popular friends & follows who have to deal with this constantly. 

I think it would be good to prioritize a bare bones version of this feature (maybe hide everything _except_ replies from people you've interacted with recently or follow) and then add other ways to customize it over time, so the feature is not held back by needing to figure out the details of the more complicated filters.
