### ISSUE TITLE
Sometimes Favourite notification status is null

### ISSUE THREAD

**Issue by nickiii** [mastodon/mastodon#12186]
Even though that by unfavouriting someone's post, it should disappear from the notifications, sometimes it just removes status from it.
Sometimes this happens on the first try, but for recreating it, I have to do it multiple times.

Steps to reproduce:
1. Post something from instance 1 (mastodon) to instance 2 (something)
2. Use curl to fav and unfav the post from instance 1 (Or you can just smash that like button like you want to hit rate limit)
3. Refresh notifications in instance 1

![Screenshot-2019-10-19T10:03:41](https://user-images.githubusercontent.com/32074788/67139204-4465a000-f25a-11e9-9081-0a3b56987b6e.png)
![Screenshot-2019-10-19T10:04:46](https://user-images.githubusercontent.com/32074788/67139205-44fe3680-f25a-11e9-9c0d-3c3e77263b79.png)

Even though it doesn't make any problems in the web frontend, it crashes tusky if you refresh notifications.
This was done in mastodon version 3.0.1

Don't mind this sentence, meow meow

**Comment by trwnh** [comment]
related #2865 #9234

**Comment by nickiii** [comment]
Yes, it seems it's duplicated, I couldn't find them trying to search for issues with null in it.
