### ISSUE TITLE
Avoid downloadable fonts

### ISSUE THREAD

**Issue by VikOlliver** [mastodon/mastodon#12182]
Use standard font characterss or downloaded icons rather than "Wingding"-like characters from downloaded fonts. Example: The "favourite" star.

Why? Because there is no current way in Firefox (or any other browser I'm aware of) to selectively block sites from downloading fonts. If a user blocks them all, downloadable font icons are completely illegible and meaningless.

There are two main reasons for wanting to do block downloadable fonts:

1. Accessibility. Idiot website designers tend to include illegible fonts that partially sighted people cannot read. Said user can't block them individually, and so blocks them all.

2. Font downloading and tracking is a potential privacy violation mechanism. Concerned users block them all.

There may be other constraints some users are under which cause them to block downloadable fonts, but these are the ones I have become aware of.

**Comment by lpar** [comment]
Suggestion: inline the symbols as SVG.
e.g. 
https://ikonate.com/
https://danklammer.com/bytesize-icons/

**Comment by ZoeBijl** [comment]
Related issues:

- https://github.com/tootsuite/mastodon/issues/1469
- https://github.com/tootsuite/mastodon/issues/7914

**Comment by vmstan** [comment]
I'm pretty sure this has been fixed long ago but I'm marking as closed by #27385
