### ISSUE TITLE
Alt-Text OCR Feature fails on highlighted text

### ISSUE THREAD

**Issue by jasikpark** [mastodon/mastodon#12196]
### Expected behaviour

The OCR for alt-text on desktop web mastodon should reliably detect and transcribe text from a screenshot.

### Actual behaviour

When transcribing the "Twitter" word highlighted in bright green, the OCR interpreted the green background as part of the characters, returning the wrong characters.

<img width="1131" alt="Screen Shot 2019-10-21 at 3 36 35 PM" src="https://user-images.githubusercontent.com/10626596/67241459-18dce400-f419-11e9-9488-543499b679e8.png">

### Steps to reproduce the problem

Take a screenshot of https://adrianroselli.com/2015/10/googles-amp-html.html#update12 and run the Mastodon image posting OCR for alt-text on it.

### Specifications

v3.0.0, 
https://mastodon.social

Not a front end issue. I am using Firefox 69.0.3 and macOS 10.14.6

**Comment by vmstan** [comment]
Confirmed as functional on latest version of Mastodon.

![CleanShot 2024-06-04 at 15 13 55@2x](https://github.com/mastodon/mastodon/assets/3002053/edc3f609-9191-40e1-b014-9272277255a1)
