### ISSUE TITLE
Initial loading of joined Hashtags in a column

### ISSUE THREAD

**Issue by bauernbua** [mastodon/mastodon#12197]
### Expected behaviour
In the advanced web interface I use a column where I added several Hashtags I am interested in. All OR joined Hashtags should be loaded when the site is loaded/reloaded.

### Actual behaviour
Only the first 4 Hashtags are shown when the site is loaded.

### Steps to reproduce the problem
1. Create a Column with one Hashtag.
2. Pin the Colum.
3. Enable "Include additional tags for this column".
4. Add 4+ Hashtags in the field "Any of these".
5. Check if posts of the 5th+ Hashtag are shown.

### Specifications
I found it after the upgrade to Version 3.0.1. It worked for me one one instance when it was running on 2.9.x.
If I add 8 Hashtags to one column and there is a new post from any of these 8 Hashtags in the lifefeed, the post is shown in the column. When I reload the page, these posts are gone and only the first 4 Hashtags are shown.

**Comment by ThibG** [comment]
This has been changed deliberately in #12091, presumably for performance reasons. It does that silently though, which is definitely confusing.
