### ISSUE TITLE
silenced domains are leaking into the federated public feed.

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#12226]
I noticed that switter.at and a few other previously silenced/suspended servers were showing up in federated public feed.

So I deleted and readded (switter.at for example) and then once the cache cleared - they were gone from the public feed

Regression?

**Comment by ThibG** [comment]
Silencing a domain works by:
1. Adding a record that, if present, auto-silences any newly-discovered account from that domain
2. Updating every known account from that domain to silence it (this is done after clearing media if you have asked for that)

So I guess there could have been an issue in running 2? I don't think there has been any regression though.

**Comment by Shleeble** [comment]
Is it worth having a scheduled task to regularly run silence jobs?

**Comment by ThibG** [comment]
I don't think so. They're long-running jobs, and if there ever was en error running them, it is somewhat likely to be reproduced every time. This seems to be a waste of resources.
