### ISSUE TITLE
trending hashtags not showing on a 1366x768 monitor

### ISSUE THREAD

**Issue by filippodb** [mastodon/mastodon#12228]
trending hashtags are showing wrongly, seems one of my user are  showing them at the bottom of a  1366x768 monitor, see screenshots below 
.
(he can see them only with a 40% zoom. )

it works fine on a 1280x1024 monitor.

### Specifications

mastodon version 3.01

Ubuntu (Firefox, Chromium e Midori) & Windows 10 (Internet Explorer, Edge, Firefox, Chrome)

**Comment by filippodb** [comment]
seems my browser is not working anymore on github, so can't upload or edit, thanks microsoft, here below links to screenshots:

https://cf.mastohost.com/v1/AUTH_91eb37814936490c95da7b85993cc2ff/mastodonuno/media_attachments/files/000/123/265/original/9ae54102c7abe0fe.png

https://cf.mastohost.com/v1/AUTH_91eb37814936490c95da7b85993cc2ff/mastodonuno/media_attachments/files/000/123/268/original/5d020e8f2a26a818.png

**Comment by filippodb** [comment]
yep, seems a design bug. 
also on mobile browser (safari) I've never been able to see the trending hashtags.

**Comment by MaciekBaron** [comment]
This isn't a design "bug", it's per design. The trending topics get explicitly hidden when there's not enough space for them there (i.e. it's explicitly done in CSS). I'm labelling this as a suggestion, the suggestion being that the trending topics should be still somehow visible, somewhere.

**Comment by akarshanbiswas** [comment]
Duplicate of https://github.com/tootsuite/mastodon/issues/11565
