### ISSUE TITLE
Hastag language in welcome message right after registration

### ISSUE THREAD

**Issue by skywinder** [mastodon/mastodon#12327]
1) It’s a minor improvement, but I think in first “welcome” email we don’t translate hastag name in order to make it consistant. What kind of translation tool are you using? Probably we have to fix only one field. I.e. now in russian it looks like has #приветсвие - so there is no posts with it at all, and I don’t know the name of the hastag to check globally posts from newcomers ( #greeting maybe?)

2) Another question, why it comes in Russian to me? My preferred languages in browsers is always English. 

​​![9DDF5970-EB8D-4B90-BA7D-FDDA62CE09F6](https://user-images.githubusercontent.com/3356474/68450467-291cfd80-0226-11ea-99e9-8e14030195ef.jpeg)

**Comment by ThibG** [comment]
1. Translation is managed on Crowdin: https://crowdin.com/project/mastodon
2. I think this may be the server's locale?

**Comment by skywinder** [comment]
@ThibG regarding to 2. - it's mastadon.social server
