### ISSUE TITLE
Thin images are not shown correctly.

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#12344]
### Expected behaviour

<img width="585" alt="image" src="https://user-images.githubusercontent.com/17537000/68573136-10b91700-04a2-11ea-85a5-002141d6ac16.png">

### Actual behaviour

<img width="586" alt="image" src="https://user-images.githubusercontent.com/17537000/68572896-840e5900-04a1-11ea-8560-91876754f035.png">

### Steps to reproduce the problem

Paste in a image. Post

### Specifications
3.0.1 on firefox

**Comment by Shleeble** [comment]
Visable on profile view https://aus.social/@shlee

**Comment by vmstan** [comment]
Is this still a problem after the changes to the way media is displayed in 4.2?

**Comment by mjankowski** [comment]
Closing on assumption that the last comment here implies that it IS fixed, but I havent verified -- can you reopen with current version/browser if still issue?
