### ISSUE TITLE
Customer Onboard in UX

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#12365]
### Pitch

When a new user connects... the welcome modal has some information about Mastodon.

I'd love to expand that modal to be a more interactive and onboard the new user..

upload avatar -> update bio -> enable MFA?

### Motivation

Far too many people have no avatar.

**Comment by harrybailey** [comment]
Still required? Add 'suggestion' label?

**Comment by vmstan** [comment]
Closed by #27829
