### ISSUE TITLE
Filtering the timeline when an account is added to a list

### ISSUE THREAD

**Issue by nspt-fr** [mastodon/mastodon#12366]
Messages from an account that has been added to a list also appears in the Timeline.

Could be implemented in third party app using the REST API

### Pitch

Creating lists is a handy functionnality to bring readability to the timeline, but messages from a listed account keep appearing in the timeline creating redundancy.

### Motivation

Would be helpful to everybody, to provide more readable timeline, and probably more efficient memory usage.

**Comment by zecamigo** [comment]
Yes second this.

This should be an opt-in feature though.

For clarity I think you mean being able filter out posts from a list from timeline.

This should be great to filter out bots and people who post a lot and being able to focus on slower posters.

**Comment by vmstan** [comment]
Fixed by #22048 in 4.2
