### ISSUE TITLE
Midnight theme

### ISSUE THREAD

**Issue by MainTomato** [mastodon/mastodon#12399]
### Pitch

A Mastodon "darker" theme for late night browsing

![Screenshot_2019-11-16 uwu social](https://user-images.githubusercontent.com/57838286/68996138-f0b49980-088d-11ea-81ee-f54294a7fab5.png)

### Motivation

Twitter has recently added a super dark theme, It would be cool to see on Mastodon

**Comment by nsuchy** [comment]
You should submit the CSS you made for this screenshot for this as a pull request. People might have minor change suggestions but this looks great so far.

**Comment by MainTomato** [comment]
> You should submit the CSS you made for this screenshot for this as a pull request. People might have minor change suggestions but this looks great so far.

I don't have a CSS file to give, It's just a mockup. I used dark reader to get this result with the light theme. The settings I used was +25 on contrast and +100 on grayscale. 

The only issue with this Is that It removes the colours on the icons and buttons, I would still like to keep colourful blue icons but with this dark background

**Comment by renchap** [comment]
Closing this as the new dark theme is darker than before.
