### ISSUE TITLE
Some posts are missing from misskey and mastodon

### ISSUE THREAD

**Issue by devporto** [mastodon/mastodon#12405]
## 💡 Summary

If we search for the tag misskey on mastodon we get one set of results while on misskey it's a different set of results. Shouldn't it be the same?

## 🙂 Expected Behavior

Same search results 

## ☹️ Actual Behavior

Here is misskey tag search on mastodon
![mastodon-misskey-tag-search-results](https://user-images.githubusercontent.com/48541161/69014769-db0da580-095b-11ea-8ad2-3731bb3c422a.jpg)

Here is misskey tag search on misskey
![misskey-misskey-tag-search-results](https://user-images.githubusercontent.com/48541161/69014767-d812b500-095b-11ea-9503-b964112e5f39.jpg)

## 📝 Steps to Reproduce

1. search tag misskey on mastodon
2. search tag misskey on misskey
3. compare both tag result

## 📌 Environment
Search on mobile and desktop using firefox and chrome

**Comment by trwnh** [comment]
hashtag search only works on posts that the local instance is aware of. there may be posts on one site that have not been delivered to the site.
