### ISSUE TITLE
Allow searching for multiple hashtags

### ISSUE THREAD

**Issue by ffffluffy** [mastodon/mastodon#12406]
### Pitch

My use case is as follow :
I sometime post the music I listen to, with a particular hashtag to identify my toots (fluffymusic), and a hashtag for the artist (rhapsodyOfFire for instance). I'd like to be able to do a search on both hashtags, linking them with a logical "and", as I want to filter the search to have less results.

However, people may also want to do the search with a logical "or". Best would be to have a default value, "and" or "or". Then users may be able to specify a particular one, to do searches like, `#videogame #videogameS` (with the default operator), `#rhapsody or #rhapsodyOfFire` (to have both results for both hashtags, `#tootradio and #metal or #rock` (order of priority matters, but I don't know which one would be best)...
These examples are just my thoughts and may not be the best choices at all.

### Motivation

I've written a particular use case, but I think it might be more useful than just for me. The current search engine has left some people dissatisfied, and while this wouldn't solve everything, it would still be more powerful. Moreover, I don't think this would take "too much work", as hashtag search already exists, but I may be wrong on this point.

### Edit

I've found that once the hashtag is made as a pinned column, it is possible to filter on several hashtags, which is great ! But it doesn't work on the searchbar, just when it's pinned.

**Comment by marmalodak** [comment]
Did you ever find a way to do this?
