### ISSUE TITLE
Indic language character count

### ISSUE THREAD

**Issue by Natkeeran** [mastodon/mastodon#12422]
The word தமிழ் has 3 Tamil alphabet characters in the Tamil language, but 5 unicode characters.  Many Tamil  characters are represented by more than 2, 3 or more unicode characters.  This reduces the number of alphabet characters that can be posted in mastodon by several folds.   So for instead of 500 character limit, these languages effectively have ~166 character limit.  

### Pitch

Count the real alphabet characters of a language when using characters limit as a limiting factor or feature.  

### Motivation

All indic and many other languages where one single characters is represented by multiple unicode characters will benefit from accurately counting the characters of those language.

**Comment by Gargron** [comment]
Testing on the server side, our code counts `தமிழ்` as 3 characters, not 5. Could you clarify if your bug report is based entirely on the web UI's character counter? Perhaps the bug is there.
