### ISSUE TITLE
Regression: Pinned hashtag feature does not work anymore with multiple hashtags

### ISSUE THREAD

**Issue by GerryT11** [mastodon/mastodon#12453]
### Bug description
The feature to pin hashtags and to include additional tags for this column worked nicely until some weeks ago, but then I noticed a severe regression of this feature. Since then, the frequency of new messages in the columns with multiple tags has substantially dropped. The regression is that the pinned hashtag search does not search additional tags correctly and omits a substantial number of toots.

### Expected behaviour
The pinned hashtag feature should show all toots that match any of the hashtags in the list.

### Actual behaviour
The pinned hashtag feature does not work anymore with multiple hashtags. It does not display all relevant toots.

### Steps to reproduce the problem
Here an example (see screenshot ![Mastodon-BugReport-PinnedSearches2](https://user-images.githubusercontent.com/58103727/69477650-117a7300-0de9-11ea-8fc8-be651a1cfe97.jpg):
- I have a column searching and displaying multiple hashtags related to "climate change", including the hashtag "klimawandel". The last toot is from 14 hours ago. You see it in the left column of the screenshot.
- In the right column of the screenshot, I just just searched the hashtag "klimawandel" and there were several toots much newer than in the pinned search. E.g. 13min, 4h, .... 

### Specifications
Since when: Since a Mastodon update some weeks ago. Before, it worked correctly. The bug is still present in v3.0.1
Reproducibility: Always. I noticed the bug in several pinned hashtag columns on mastodon.social and bonn.social

**Comment by Gargron** [comment]
You can combine at most 4 hashtags per mode (any/all/none) since v3.0.1 for performance reasons.

**Comment by GerryT11** [comment]
Thanks @Gargron for your quick answer. 

It's unfortunate that it was necessary to limit it to 4 search tags due to performance. It would be great to have more than 4 hashtags in the column. At the moment, I have over 20 tags (which doesn't work anymore, of course).

Thus, 2 questions to you:
//1: Will it be possible in future releases to increase the current limit of 4 search tags?

//2: In the web interface, the feature is described as "Include additional tags for this column", which is a bit misleading. Wouldn't it be better for now to change the wording to e.g. "Add max. 3 more tags for this column"?

**Comment by Cassolotl** [comment]
This is maybe where *option to follow hashtags #1096* would come in handy. It's the second most 👍ed issue on the open issue list. I have nine pinned hashtag search columns, all with more than one hashtag being monitored, because on a small instance I want to be able to see and boost things relevant to my interests and the federated timeline doesn't meet that need. I would much rather follow the hashtags and have them appear in my Home column because they take up so much space.\*

What's more, I had no idea that pinned hashtag search columns were limited to four hashtags - there was no indication in the UI that anything beyond the first four were ignored. So I've opened *No indication in web UI that hashtag search pinned columns only work for the first four hashtags #12458*!

------------

\* *Support groups #139* doesn't meet my needs, [because](https://github.com/tootsuite/mastodon/issues/139#issuecomment-370260564):

>when I used !groups on GNU Social, my main feeling was that they were pretty confusing. It required someone to set it up, and there could be three groups with the same name on three different instances all with different rules about who can join. If an admin made a group where members (followers and posters) had to be approved, and then the admin became inactive, the group just became stagnant forever.
>
>So it seemed to me like following a hashtag might be better, because there were no leaders and anyone could keep joining in without having to wait for permission.

**Comment by GerryT11** [comment]
I close this bug, because the pinned hashtag feature works as intended (Gargron pointed it out). 

However, there are two follow-up bugs:
#12458 to indicate to the user that there currently is a limitation of 4 hashtags
#12463 to increase the number of possible hashtags
#1096 is a related bug to add an option to follow hashtags

**Comment by unextro** [comment]
It's not just that only first 4 apply. In my case, posts with other hashtags (not among the first 4) show up in the search column but they disappear once I refresh the page and only the first 4 stay. It's still a bug.

**Comment by GerryT11** [comment]
After the comment by @unextro I reopen this bug again.

> It's not just that only first 4 apply. In my case, posts with other hashtags (not among the first 4) show up in the search column but they disappear once I refresh the page and only posts with the first 4 hashtags stay. It's still a bug.

**Comment by marrus-sh** [comment]
(The bug in this case is that Mastodon allows subscribing to more than 4 hashtags per column through websockets, but not fetching more than 4 hashtags per column on initial page load.)

**Comment by daprice** [comment]
Does the 4 hashtag limitation apply to the hashtag timeline API endpoint (`/api/v1/timelines/tag/:hashtag`) as well, or just the web ui? I can’t find any mention of it in the API docs.

**Comment by quicoto** [comment]
Couldn't we make the number of hashtags an environment variable? So the servers with more resources or single-user instances could make use of the higher number without impacting the performance of out of the box big instances (default set to 4)

**Comment by vmstan** [comment]
Closed as request for configuration has filed as #12463.
