### ISSUE TITLE
How to fix "slow query"?

### ISSUE THREAD

**Issue by dimlau** [mastodon/mastodon#12485]
It's all green on PgHero page, I don't know when. It displays this information:

1 slow query

Total Time | Average Time | Calls
-- | -- | --
0 min 0.3% | 24 ms | 109mastodon
SELECT n.nspname AS schema, c.relname AS relation, CASE WHEN c.relkind = $1 THEN $2 ELSE $3 END AS type, pg_table_size(c.oid) AS size_bytes FROM pg_class c LEFT JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname NOT IN ($4, $5) AND n.nspname !~ $6 AND c.relkind IN ($7, $8) ORDER BY pg_table_size(c.oid) DESC, 2 ASC /*pghero*/

**Comment by Gargron** [comment]
I do not think you should worry about this. That area of pgHero is not very useful in a general sense.
