### ISSUE TITLE
HTML 500 error when given account id above integer limit

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#12488]
DELETE with `account_ids[]=487623987434987263434343` caused a 500 error with HTML returned.

This probably happens with other methods too.

**Comment by mjankowski** [comment]
I believe this is a limit/cast for this now, such that large values alone should not trigger error.

I attempted to reproduce this local in some of the existing  spec coverage for api/v1/lists/:list_id/accounts (based on original title here), but could not. Going to close as stale on assumption that it was actually resolved by that casting ... but I do see the title changed here so if there are other reproducible cases please repoen with detail on recreating (not clear to me if this was API only or also elsewhere)
