### ISSUE TITLE
Add Github Sponsors

### ISSUE THREAD

**Issue by iGEL** [mastodon/mastodon#12482]
Even though I don't use Mastodon at the moment, I still support @Gargron with a small monthly contribution through Patreon, as I'd like to support open platforms. Obviously, I want my contribution, as small as it might be, to have the biggest possible effect, which brings me to [GitHub Sponsors](https://github.com/sponsors).

- GitHub Sponsors currently doesn't charge any fee
- GitHub matches all payments (so each contribution is paid out twice) in the first year
- It's integrated into GitHub, so if you have a GitHub account, it's very easy to use. No need to register on another site and if you have a payment method registered, it's even easier.

**Comment by fschrofner** [comment]
Seems like this was added, but for some reason @Gargron did not add any custom tier.
Is there a reason for that? 20$ per month seem to be a bit much to me.

**Comment by vmstan** [comment]
This has been implemented.
