### ISSUE TITLE
An icon for “Content warning”

### ISSUE THREAD

**Issue by nclm** [mastodon/mastodon#1249]
There’s one for adding a media, one for setting audience, but adding a content warning settle for “cw” which isn’t really clear, especially for users not on the English version of the interface.

Since we appear to be using FontAwesome, some possibilities:
* `exclamation-triangle` or `exclamation-circle`, though they may be interpreted as “there’s an issue with your status”, and are somewhat aggressive.
* `eye-slash`, if not already used somewhere else. It’s not a common use for that icon, but it makes sense in context? Alternative: `low-vision`, maybe even better except if it’s a real established symbol for low vision.
* `flag`? Could work, though may seem to refer to some kind of multi-language content feature (which is a suggestion for later). A triangle minesweeper flag would also be more fitting than the rectangle one.
* `hand-stop-o`?
* `user-secret` could be fun.
* `sticky-note` is a bit uninspired but straightforward.
* another I haven’t thought of.
* something custom yet to design.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by wxcafe** [comment]
I feel like CW/TW are clear for more people than an icon would be, and this is a pretty important thing for users to get. As a french speaker, Content/Trigger Warning are also the terms we use mostly (they're not translated). I don't know about other languages though, but I don't think it would be that much of an issue in many languages.

**Comment by nclm** [comment]
It isn't translated because the string is missing from the language files (see #1244), not on purpose. There's no reason not to translate it, since it would be pretty weird to keep two English words in the middle of a localised interface, and could frein newcomers. As soon as the translations are deployed, CW will get even more obscure.
I agree than nothing is better than text to convey an idea, and that the right words are better than any icon (and that was that interface a few months ago: words). But I'm not sure a two-letters unestablished abbreviation qualifies​ as proper text.

**Comment by wxcafe** [comment]
I guess an icon with the "Hide text behind warning" hovertext allows discoverability for the user, yeah

**Comment by SansPseudoFix** [comment]
> ``eye-slash``, if not already used somewhere else. It’s not a common use for that icon, but it makes sense in context? Alternative: ``low-vision``, maybe even better except if it’s a real established symbol for low vision.

I agree. This one makes sense 👍

**Comment by expenses** [comment]
I also think an icon as well as / instead of the `Show More` text could be useful, as it's not super clear why the content is hidden.

**Comment by nclm** [comment]
Indeed, if we have an icon at writing, this icon has to get in the “Show More” button too so everything is consistent. For new users having seen the icon pass in their timeline a few times, it would also make the discoverability and understanding of the feature easier, since they will recognise the icon in the writing box.

**Comment by Cassolotl** [comment]
At the moment there is an eye/slashed eye in use for the button formerly known as NSFW, which appears when media is uploaded, to hide the media only.

I think an icon for CW would have to very clearly show that it is hiding text, and NOT media. I honestly can't see a way to resolve this issue without causing more confusion.

This will be moot when #1010 is done ("CW should include the image, too") - which is currently marked high priority. I think this is probably the best solution.

**Comment by Sylvhem** [comment]
@nclm `low-vision` is a real established symbol for low vision. Both France's [Ministry of Culture](http://www.culturecommunication.gouv.fr/Thematiques/Developpement-culturel/Culture-et-handicap/Informations-pratiques/Pictogrammes/Pictogrammes) and [Superior Council of the Audiovisual](http://www.csa.fr/Television/Le-suivi-des-programmes/L-accessibilite-des-programmes/Pour-les-personnes-aveugles-ou-malvoyantes-l-audiodescription) use it. Besides, you can find plenty of examples on Internet.

I think `exclamation-triangle` is the icon which better convey the meaning of a trigger **warning**.

**Comment by detrout** [comment]
I was wondering if the display in the feed of protected text should show CW: <warning text> [SHOW MORE], as the inclusion of CW: in the toot might make it easier for new users to link the behavior of showing text behind a [SHOW MORE] button to the CW UI element under the toot text entry box.

(Was discussing this on mastodon and at least one other person thought it was a decent idea, and this looked like the most relevant issue.)

**Comment by xuv** [comment]
@nclm: We started to tackle [this issue in this fork of Font Awesome repo](https://github.com/ForkAwesome/Fork-Awesome/issues/27#issuecomment-367898561). It's a start. Let us know what you think.

**Comment by Cassolotl** [comment]
⚠️

**Comment by xuv** [comment]
@Cassolotl Yes. Indeed, that is the usual icon for "Warning". Now, I think there is a subtle difference with what would be meant by "Content Warning". 

It's also driven by the intention of adding an icon to Mastodon interface to replace the 'CW' here: <img width="86" alt="screen shot 2018-05-26 at 13 01 56" src="https://user-images.githubusercontent.com/192539/40578627-31007a4c-60e5-11e8-9407-cea87ca9e88d.png">

The function of the button is to hide the text of a message behind a "content warning" sign.

**Comment by Cassolotl** [comment]
It'd do for now, though, right? Until a better one can be created? Creating a new icon could take a very long time.

**Comment by detrout** [comment]
Just had an idea for a content warning icon. Human head outline surrounded by question and exclamation marks.

Don't know it expresses the right concept, but its another idea.

**Comment by rcrdlbl** [comment]
I have no idea if the mastodon project has access to font-awesome's pro icons; but if you do and you're not already using it elsewhere, `file-exclamation` ([This one](https://fontawesome.com/icons/file-exclamation?style=solid)) would work really well to show that it's text being hidden and not an image, like @Cassolotl mentioned.

**Comment by gabiturra** [comment]
Hey everyone, feel like I'm a bit late to the party, but since this is not fixed yet I sketched a symbol with this problem in mind... might be useful (??)

If you think this could work just reply and I'll make the adjustments necessary. As you can see, is not a 100% yet...

![eye-exclamation](https://user-images.githubusercontent.com/64840610/118886330-15f9ec00-b8f9-11eb-8bbe-66a19e85416d.png)

**Comment by harrybailey** [comment]
Who decides on the icon?
This is marked as 'fit for beginners' but that probably means it needs clarity on the requirements first.

**Comment by Cassolotl** [comment]
<img src="https://user-images.githubusercontent.com/64840610/118886330-15f9ec00-b8f9-11eb-8bbe-66a19e85416d.png" width="23"></img>

**Comment by lirontocker** [comment]
Seems like the level of detail is a bit too much for such a small size. I put a few additional examples in https://github.com/mastodon/mastodon/issues/20800, maybe something simple works best?

**Comment by James-Firth** [comment]
I think the `tag` or `tags` icons could work. [Font awesome link here](https://fontawesome.com/icons/tag?s=solid&f=classic)

I think using something indicative of a label/notice could also be useful in case #20117 (or a similar rename) comes into effect, since it would involve less changes to implement.
The tag or label I think is also applicable as many use the "CW" feature as a summary/subject line/spoiler/etc and not purely for trigger/content warnings

**Comment by Cassolotl** [comment]
> I think the tag or tags icons could work. [Font awesome link here](https://fontawesome.com/icons/tag?s=solid&f=classic). Emoji equivalent: 🏷

I'm not sure that would work; I'd interpret that like tags on Tumblr - so like, hashtags, or like folders in Gmail?

**Comment by Cassolotl** [comment]
These are my faves from [Font Awesome](https://fontawesome.com/search?p=2&o=r&c=alert):

<img width="839" alt="Screenshot 2022-11-24 at 22 39 13" src="https://user-images.githubusercontent.com/6607512/203871051-43b4bfb2-4b84-49d5-ba00-cd718a56b8fd.png">

<img width="147" alt="Screenshot 2022-11-24 at 22 40 23" src="https://user-images.githubusercontent.com/6607512/203871142-cda756ee-bb02-4406-9e3d-63f3f1876ddc.png">

<img width="150" alt="Screenshot 2022-11-24 at 22 41 08" src="https://user-images.githubusercontent.com/6607512/203871185-2da427fa-e877-48d9-8f94-2c78c2baf28b.png">

**Comment by James-Firth** [comment]
@Cassolotl That's a fair point of it being like tags. But I don't think I've ever seen a button for them before. I could see it either way, just trying to throw some non-"warning" ideas in the ring, like you did with the spoiler one!


I think the circle exclamation fits in nicely with the other icons on that bar.

I _like_ the spoiler icon but I'm hesitant here since that could be confused as a "post privacy" icon, thoughts?

**Comment by Cassolotl** [comment]
> I like the spoiler icon but I'm hesitant here since that could be confused as a "post privacy" icon, thoughts?

I think it's too hard for me to tell because I'm so used to Mastodon and the symbols. Maybe we need to ask some people who have never used Mastodon before, somehow?

**Comment by nclm** [comment]
> These are my faves from [Font Awesome](https://fontawesome.com/search?p=2&o=r&c=alert):

I like the idea of “message-exclamation”, a speech bubble with an exclamation mark. The ones that are just exclamation marks in circles or triangles could be interpreted as a UI notice displaying under your post while writing it because there’s something wrong with it. While the speech bubble is more clearly the action “I say: warning”.

**Comment by gunchleoc** [comment]
I looked at the Android apps, FediLab has an eye icon, Tusky has a squarish speech bubble with an exclamation point in it.
