### ISSUE TITLE
`yarn install` is executed twice when `assets: precompile` is executed

### ISSUE THREAD

**Issue by mayaeh** [mastodon/mastodon#12558]
After #12416, when `RAILS_ENV=production bundle exec rake assets: precompile` executed, `yarn install` seems to be executed twice.

![2019-12-05 21 13 05](https://user-images.githubusercontent.com/766076/70235475-5f5a8800-17a6-11ea-95a1-08b443efc76e.png)

I confirmed this only in the production environment.
Not yet confirmed in development and test environments.

### Specifications

Mastodon latest master and after 5605b828e5149bd3a5161eb8d536ad51094afe64

**Comment by mayaeh** [comment]
https://github.com/rails/webpacker/issues/2369

**Comment by ThibG** [comment]
Not sure why this is closed. That's a railties issue, but it's still there.

**Comment by mayaeh** [comment]
This problem seems to be fixed in webpacker v5.0.0 ( https://github.com/rails/webpacker/commit/cb8c07999c39be48afa4ebeb73160c2b5a5ee192 ) and v5.0.1 has been released.
[webpacker's CHANGELOG](https://github.com/rails/webpacker/blob/master/CHANGELOG.md)
