### ISSUE TITLE
share an panoramic capture -> Cropped

### ISSUE THREAD

**Issue by Moosh-be** [mastodon/mastodon#1255]
I've share an panoramic capture

![capture du 2017-04-08 13-13-14](https://cloud.githubusercontent.com/assets/388085/24828744/5ff27e70-1c64-11e7-92dc-a5c6ed206133.png)

Perhaps it's not a bug, but  it's not the result I attempt
https://mastodon.brussels/@Moosh/12279

The image "preview is  zommed/cropped" and not "resized
![screenshot-mastodon brussels 2017-04-08 14-02-32](https://cloud.githubusercontent.com/assets/388085/24828752/ac6cfb9a-1c64-11e7-8a50-f75dcb396aa7.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.  (but i've a bad english and perhaps miss the duplicate)

**Comment by trwnh** [comment]
images are now shown in their native aspect ratio if there is only one attachment
