### ISSUE TITLE
Reply counter stuck at 0 on direct posts

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#12588]
Instead of showing 1 or 1+, direct posts will always appear to have 0 replies even when there actually are replies.

**Comment by ThibG** [comment]
By design, DMs are not considered replies (as you may not want to leak the number of DM replies to the general public). I'm not sure why that isn't the case for followers-only toots too…

**Comment by trwnh** [comment]
I'm not sure why they would leak to the general public if they are not public. At most, you are only "leaking" to the participants, and only on the same instance.

**Comment by ThibG** [comment]
I was talking about the general case where you have a public toot, and private/direct replies.

We *could* make an exception for replies to things that already have a restricted visibility I guess, but then it's not super consistent.

**Comment by trwnh** [comment]
Oh, well I'd still expect the replies counter to not be too meaningful. It's a given that some replies might not be visible, e.g. if you block someone or someone has blocked you, or if there is a private/direct reply as you said. This is also mitigated by the fact that "1+" is used in the UI (even if not in the API).

I assume it would be too complicated to dynamically return a replies counter based on what the authorized user can see?
