### ISSUE TITLE
Bug: "Group boosts" not working (as expected?)

### ISSUE THREAD

**Issue by bannisdale** [mastodon/mastodon#12604]
### Expected behaviour

Boosts in timelines don't appear multiple times.

### Actual behaviour

Boosts in timelines don't appear multiple times.

### Steps to reproduce the problem

I have activated this option for quite some time now:

![grafik](https://user-images.githubusercontent.com/42511384/70720390-ffa73400-1cf3-11ea-9f0f-1f3199b8dcd5.png)

A few hours ago, I saw this boost:

![grafik](https://user-images.githubusercontent.com/42511384/70720409-09309c00-1cf4-11ea-8555-5adfef132724.png)

Then, I just saw this boost:

![grafik](https://user-images.githubusercontent.com/42511384/70720444-1baad580-1cf4-11ea-81b6-bd41b895b7e6.png)

### Specifications

* My instance is currently on v3.0.1
* Happened in Firefox 71.0

**Comment by LoVicente** [comment]
the setting works for recent boosts, seems to be a distance of 40 items in the timeline at the moment (https://github.com/ThibG/mastodon/blob/306f17553033134c2b537e8e0fb115b31a93e1af/app/lib/feed_manager.rb#L11)
you say these boosts were distanced by hours, so most likely enough items piled up to not count.

The point of the setting is to avoid multiple people boosting the same thing simultaneously from cluttering your home feed and making it unusable. It's not for only ever seeing a boost once.

**Comment by bannisdale** [comment]
Oh, wow. 40 items is ... Not much. :D I kinda expected this to keep me from seeing the same status several times a day due to multiple boosts.

I think this might need a little bit more clarity in the preferences then, especially since 40 items might go through within minutes.

Maybe there might even be an option to replace the 40 with a dynamic setting in the preferences with 40 being the default value? But I guess that's more a feature request then. :)

Thanks for the clarification so far.

**Comment by bannisdale** [comment]
I was just searching the repository for a similar issue when I realized that I created the issue three years ago and it's still not working as one could expect. :D

As #18693 is similar and has gathered more upvotes by now, I'm closing this one for tidiness. Still, would be great if this would finally be tackled.
