### ISSUE TITLE
International domain not working

### ISSUE THREAD

**Issue by perguth** [mastodon/mastodon#12635]
### Actual behaviour

https://photos.app.goo.gl/Mrs2y45KzrMU4Q8BA

### Steps to reproduce the problem

- Have a TLD that includes international characters. Try to follow someone on chaos.social.
- I run the TypeScript implementation.
- I tried it from http://温柔.移动

**Comment by ThibG** [comment]
oddly enough, I'm able to replicate it on mastodon.social and chaos.social, but not on my own instance…
I am not sure this is an issue with the domain being an international domain name, given the time it takes for the instances to reply, this sounds more like a connectivity issue.

**Comment by Perflyst** [comment]
Yes, there is a timeout `upstream timed out (110: Connection timed out) while reading response header from upstream`

port 80 on the servers IP is closed, only port 443 is opened, dunno if this could be an issue here
just FYI the server is not hosted somewhere in china, it is a server in germany

**Comment by perguth** [comment]
Is a unencrypted connection necessary for federation?

**Comment by ThibG** [comment]
> Is a unencrypted connection necessary for federation?

No, in theory, it should not be. From what I understand, every step should be making encrypted HTTP requests…

> upstream timed out (110: Connection timed out) while reading response header from upstream

what is the exact context of this error? (sorry, I'm not sure which instances you run, if any, and what logs those are from—I assume a reverse proxy)
