### ISSUE TITLE
Per device themes

### ISSUE THREAD

**Issue by lilydjwg** [mastodon/mastodon#12641]
### Pitch

A theme setting for users that doesn't sync across devices.

### Motivation

There are two kinds of themes: light and dark. Dark themes are good for LCD screens, especially at night, to ease my eyes a bit. But it's nearly unusable on an e-ink screen, which I have connected to my computer at home for reading to better protect my eyes. Just imagine a book that's made of black paper and has white text on it....

So I switch to light themes on my computer, only to find that it becomes light on my phone too. In my opinion themes should not be synced because they are often chosen depending on the environment and device.

It'll be even better if the theme can be changed programatically with client-side JavaScript so I can change it depending on which screen it is on, what time it is now (e-ink screens need a lot of light but LCDs hate sunshine), or I can even connect a light sensor to my raspberrypi and have the data control the theme.

**Comment by trwnh** [comment]
Related to #10851 -- i think certain preferences should be allowed to be overridden based on localStorage prefs

**Comment by YtvwlD** [comment]
Also somehow related: #10976 - you don't need to save the theme preference in localStorage if you just use the value provided by the system.

**Comment by renchap** [comment]
Closing this as there is now a new "automatic" theme that conforms to your system setting.
