### ISSUE TITLE
getting an Nginx page only after installation

### ISSUE THREAD

**Issue by Vibhigupta** [mastodon/mastodon#12665]
So i followed the guide and everything went smooth but when installing  last dependencies i got an error

> [DEPRECATED] The `--deployment` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set deployment 'true'`, and stop using this flag
> [DEPRECATED] The `--without` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set without 'development test'`, and stop using this flag
> 

other than this everything went smooth and fine but after setting it up 

visiting my domain it only show an nginx page. all services are ruuning it compiled without any issue but in end i get an nginx welcone page

**Comment by Vibhigupta** [comment]
Also tried the installing with yunohost same issue 

it encounter an error while installing ruby dependency (bundle installation)

**Comment by Gargron** [comment]
"[DEPRECATED]" is not an error. Which Nginx page does it show?

**Comment by vibhi19** [comment]
It show Welcome Nginx page here an example

![Matrix](https://cdn.deliciousbrains.com/content/uploads/2015/03/Image-1-Nginx.jpeg)

**Comment by vibhi19** [comment]
tried to install again Here is the issue i encountered, using ruby 2.6.4 as i was installing v3.0.0rc3 not the latest 

```
Traceback (most recent call last):
        2: from /home/mastodon/.rbenv/versions/2.6.4/bin/bundle:23:in `<main>'
        1: from /home/mastodon/.rbenv/versions/2.6.4/lib/ruby/site_ruby/2.6.0/rubygems.rb:294:in `activate_bin_path'
/home/mastodon/.rbenv/versions/2.6.4/lib/ruby/site_ruby/2.6.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by your /home/mastodon/live/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.3`


Using nilsimsa 1.1.2 from https://github.com/witgo/nilsimsa (at fd18488@fd18488)
/home/mastodon/.rbenv/versions/2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:165: warning: conflicting chdir during another chdir block
/home/mastodon/.rbenv/versions/2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:173: warning: conflicting chdir during another chdir block
```
