### ISSUE TITLE
Failure to db:migrate, when upgrading from v2.5.2 to v3.0.1

### ISSUE THREAD

**Issue by coyoteseattle** [mastodon/mastodon#12689]
Expected behavior:
When upgrading from old versions to current via git, db:migrate runs successfully.

Actual behavior: 
When upgrading from v2.5.2 to v3.0.1, db:migrate fails at 20181024224956 MigrateAccountConversations, due to column statuses.deleted_at not existing, as indicated in the attached log: [dbmigrate.log](https://github.com/tootsuite/mastodon/files/3999335/dbmigrate.log)
This appears to be approximately the same problem reported in #11952 .

Steps to reproduce: 
git checkout v2.5.2
<normal installation process>
git checkout v3,0.1
bundle install --deployment --without development test
yarn install --pure-lockfile
RAILS_ENV=production bundle exec rails db:migrate

Additional notes:
This can be worked around by first upgrading to v2.7.0, migrating the db, *then* upgrading to v3.0.1.

**Comment by ThibG** [comment]
It should be fixed by #12493
