### ISSUE TITLE
solved: /sidekiq cannot be displayed after updating to rails 5.2.4.1

### ISSUE THREAD

**Issue by mayaeh** [mastodon/mastodon#12698]
### Actual behaviour

An error page may be displayed when accessing /sidekiq after updating to rails 5.2.4.1.
At that time, the following error is output to the server log:

    NoMethodError (undefined method 'public_id' for #<String:0x00007f86d1decce0>):
    vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.4.1/lib/action_dispatch/middleware/session/cookie_store.rb:111:in 'write_session'

This seems to happen if you have a logged in session when running on rails 5.2.4, update to rails 5.2.4.1 and access with that session.

The problem was solved by clearing the web browser session and logging in again.

### Steps to reproduce the problem

1. Log in while running on rails 5.2.4.
2. Update to rails 5.2.4.1 without logout the session, restart and access again.
3. I got this error.

### Specifications

Mastodon master branch e0c2ecb1d3b04c7b7646a32c3a91cb5fd9112e90 or later

**Comment by ThomasLeister** [comment]
Thanks for mentioning your solution. I was having the same issue for months and finally got it working, again. :-)

**Comment by leahoswald** [comment]
Had the issue for months too and now it's working again :grinning:
