### ISSUE TITLE
"Copy stacktrace to clipboard" doesn't work

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#12710]
at least on iOS 12.4 with Chrome on mastodon.social: tapping the link to copy a stacktrace seems to do nothing except make the link flash. nothing is on the clipboard, so no "paste" option is given in a text field.

**Comment by mjankowski** [comment]
Still relevant on 4.3?

**Comment by trwnh** [comment]
i don't know how to trigger an intentional stack trace so i'm going to close this and reopen if it ever happens again
