### ISSUE TITLE
Post not searchable

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#12794]
### Expected behaviour

This post: https://blob.cat/notice/9qdxfG0lITJIwtLqZk

I should be able to paste the URL into the Mastodon search box and have it appear so that I can fave it, boost it, etc.

### Actual behaviour

![Screenshot 2020-01-07 at 12 22 47](https://user-images.githubusercontent.com/6607512/71895280-8b23b180-3148-11ea-884c-f61635ad6031.png)

### Steps to reproduce the problem

1. Paste https://blob.cat/notice/9qdxfG0lITJIwtLqZk into the Mastodon web UI search box and press enter.
2. "Searching toots by their content is not enabled on this Mastodon server."

### Specifications

queer.party, vanilla Mastodon v3.0.1

Latest version of Chrome on Mac 10.15.2.

**Comment by ThibG** [comment]
This is a bug in Pleroma, which returns an HTML document/a redirect whenever `text/html` is part of the accepted formats, even if it's far below `application/activity+json` which gets returned otherwise.

**Comment by Cassolotl** [comment]
Oop, okay, I'll see if I can work out how to report it over there. Thanks!

**Comment by Cassolotl** [comment]
Oh man they require me to register to report bugs. 😬 So, I will not be doing that. And I have no idea how to search out or even recognise the issue in their [issue list](https://git.pleroma.social/pleroma/pleroma/issues).

**Comment by ThibG** [comment]
Reopening, because I'm not sure asking for an HTML version still makes for a lot of sense.
Also, we could specify a low [quality value](https://developer.mozilla.org/en-US/docs/Glossary/quality_values) for `text/html`, but that doesn't solve anything regarding Pleroma not serving the JSON.

Reported the issue in the Pleroma bug tracker: https://git.pleroma.social/pleroma/pleroma/issues/1507

**Comment by Cassolotl** [comment]
I just tested it on queer.party with the URL in the first post, https://blob.cat/notice/9qdxfG0lITJIwtLqZk, and it seems to be working now!
