### ISSUE TITLE
tootctl domains purge: Incorrect success message

### ISSUE THREAD

**Issue by rixx** [mastodon/mastodon#12833]
# Expected behaviour

Running `tootctl domains purge <domain>` reports how many accounts were removed.

### Actual behaviour

Running `tootctl domains purge <domain>` reports how many account should have been removed.

We were seeing quite a bit of "could not obtain a connection from the pool within 5.000 seconds" during the run, but in the end the command reported that all the remote accounts had been removed. In truth, only about 10% of them were successfully deleted.

### Steps to reproduce the problem

Run the default `tootctl domains purge` which uses 5 concurrent connections by default, when you have less connections available for admin tasks (3 in our case).

### Specifications

Mastodon v3.0.1

**Comment by DevPGSV** [comment]
Today I had this problem. I ended up doing this:
`DB_POOL=20 RAILS_ENV=production bin/tootctl accounts cull --concurrency=19`

DB_POOL should be at least equal to concurrency plus 1.

When I used the default command, it tried to use 5 workers. Each worker requires 1 connection. The main process requires 1 connection. So the default command requires 6 connections.
With the configuration I have in my .env.production (i do not define DB_POOL, so its value by default equals MAX_THREADS, for me that is 5), I was only allowing 5 connections.

Reference: https://docs.joinmastodon.org/admin/config/#connections

**Comment by mjankowski** [comment]
Closing this on the assumption that this may have been resolved in newer Mastodon (or in underlying Rails connection managment) in the interim period.

If that's not the case and this is still an issue, please reopen with current logs/replication steps.
