### ISSUE TITLE
Deleted account email not detached(freed)

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon#12871]
### Expected behaviour

Deleting(self-suspending) account will remove email from that account. (plus IP address, etc.)

### Actual behaviour

IP, Email, Recent activity is not deleted as below:
![image](https://user-images.githubusercontent.com/5047683/72396577-78c8f980-3780-11ea-90d0-7d483d0248c7.png)
![image](https://user-images.githubusercontent.com/5047683/72396696-dd845400-3780-11ea-9e6c-2a5f6fe90db4.png)

### Steps to reproduce the problem

Someone want to start from new account
1. Delete their account by their self
2. Create new account(different username) with same email address
3. "already used" error shown

### Specifications

Mastodon v3.0.1

**Comment by ThibG** [comment]
I can't reproduce it. The deletion is supposed to occur in a worker (`Admin::SuspensionWorker`, in the `pull` queue, so the lowest-priority one) though, so maybe this didn't run by the time you reported the issue?

Could you check that the user record is still here? If it is, could you check whether `Admin::SuspensionWorker` is enqueued, or if it failed to execute for some reason?
