### ISSUE TITLE
Option for filters to work only if word is in CW

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#12913]
### Pitch

I'd like to be able to specify that a filter should only remove toots containing the term in the CW field.

### Motivation

For example, I might be happy to see a selfie un-CWed, but if there's a CW on it I'd rather it get filtered out. So I'd be like "filter: selfie. in CWs only? y." And then only posts with selfie in the CW field specifically would get filtered out.

**Edit:** Now that I think about it, I'm only posting this because blurry CWed-image thumbnails continue to be exhausting and space-wasting for me, and I would rather they were tucked under the CW like so: *Combine CW and Hide Media #6141*

**Comment by ThibG** [comment]
I'm sorry, I absolutely do not understand the use case :confused:

**Comment by Cassolotl** [comment]
Ahh, maybe it is only me who would want this. I'll ask around, maybe someone can help me clarify this.

**Comment by Cassolotl** [comment]
*Combine CW and Hide Media #6141* is done now, so I'm closing this. :)
