### ISSUE TITLE
Deactivate/suspend user account temporarily

### ISSUE THREAD

**Issue by rixx** [mastodon/mastodon#12941]
## Pitch

As an administrator and moderator, I'd like to suspend or deactivate user accounts temporarily. Currently, my only moderation options are a stern word or complete deletion/annihilation of the users' data. I'd like to be able to take more moderate actions, such as

- Deactivating an account for a set time (a day, a week, a month), which may serve as a way to deal with violent discourse.
- Deactivating an account indefinitely while an issue is being resolved
- Deactivating an account in preparation for account suspension/removal. This would allow the impacted user to still download or migrate their account, without allowing them to post.

### Motivation

I strongly dislike deleting a user's complete social media history – while it's sometimes warranted, sometimes it would be better to give a user the opportunity to migrate to a more suitable instance, or to give them some time to cool off when they have not been thinking straight in a discussion. The all-or-nothing moderation choices force us to be more combative than we need to be, and I'd like to see a more moderate option.

**Comment by ThibG** [comment]
You still have the option to disable login for a local account, which is *similar* to your need, although it doesn't signal anyone that the account is being investigated

**Comment by rixx** [comment]
Ah, see, I didn't know that you could disable accounts even without a report, because it's hidden behind the "warn" button (and disabling a user account is decidedly not intuitively a subtype of warning).

Since there is no explanation included in the warning interface, I don't know if disabling does the thing I want: Does it permit login, but prohibit actions? If so, it is what I want, except that I'd like to see a time-bound action for this, e.g auto-enable after a set amount of time.

**Comment by JamesABDL** [comment]
I think suspending just the login isn't enough in many cases, a deactivation should also hide posts, remove the user from search etc..

There should also be a way for users to deactivate their own account themselves.

**Comment by piegamesde** [comment]
@rixx Why was this closed?

**Comment by ClearlyClaire** [comment]
Presumably because starting from 3.3.0, suspensions are not immediately irreversible and only become irreversible after 30 days.

**Comment by rixx** [comment]
Exactly. Suspensions have become temporarily reversible, and while I was hoping for more (for example automated reactivation, so that moderators don't have to have calendar entries for temporary suspensions), I guess this is as good as we can hope for. No need to keep issues around in an overloaded project when they have been mostly, somewhat, resolved.
