### ISSUE TITLE
Sharing button not displayed in Android webview

### ISSUE THREAD

**Issue by koyuawsmbrtn** [mastodon/mastodon#13044]
### Expected behaviour

Sharing button should be displayed in Android webview

### Actual behaviour

No sharing button in Android webview

### Steps to reproduce the problem

Run Android Studio, create a new Webview app and load Mastodon into it

## Other notes

The sharing button gets displayed at random if you use the latest Chrome on Solus 4.1 KDE

![image](https://user-images.githubusercontent.com/40538332/73838123-3f315e80-4813-11ea-8818-3ecc9d2acfed.png)

### Specifications

Browser and OS: Android 7.1, Android WebView

Mastodon version: any

**Comment by ThibG** [comment]
I can't see what could cause share buttons to not show up on **public** toots when the share API is supported.

However, for some reason, it was only displayed for **public** toots and not **unlisted** toots. #13045 addresses that

**Comment by koyuawsmbrtn** [comment]
> I can't see what could cause share buttons to not show up on public toots when the share API is supported.

Apparently it's a Chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=765923 which Google is unwilling to fix and no developer on earth wants to tell me how I could implement WebShare support into my WebView app
