### ISSUE TITLE
Don't scroll the timelines (instance/global) when you're below the top

### ISSUE THREAD

**Issue by krainboltgreene** [mastodon/mastodon#1306]
I was reading a really big post on the instance timeline and suddenly my timeline starts moving up and down due to new toots coming in. That shouldn't happen.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
Even though this issue is older, I think can close it and forward people to *Don't scroll the timelines (instance/global) when you're below the top #1306* - it's the same issue but there's more discussion there.

**Comment by trwnh** [comment]
is this addressed by "slow mode"?

![image](https://user-images.githubusercontent.com/10606431/214928601-03e6d5d9-a5ee-4306-878f-1c404cdd7a5e.png)

> Hide timeline updates behind a click instead of automatically scrolling the feed

**Comment by mjankowski** [comment]
Going to close this on assumption that prior suggestion does resolve this (and that original issue is for an outdated version) ... but if not, can you reopen with current browser/server versions and images/logs if relevant?
