### ISSUE TITLE
Move bookmark from overflow menu next to favorite in home timeline

### ISSUE THREAD

**Issue by SuperSandro2000** [mastodon/mastodon#13085]
### Pitch

Move the bookmark option from the overflow menu right next to the favorite icon in the home timeline.

Right now the home timeline looks like 
![image](https://user-images.githubusercontent.com/7258858/74392880-bf098b00-4e08-11ea-81a3-3b4f69fbc90d.png)

and I want it to look like when you opened that toot 
![image](https://user-images.githubusercontent.com/7258858/74392902-cd57a700-4e08-11ea-9c6f-122696db039a.png)

### Motivation

When you open a toot it is right next to the favorite icon and it only makes sense to also put it there in the timeline. This would also promote the usage of bookmarks.

**Comment by ryliejamesthomas** [comment]
Can be closed. Fixed in version 4!
