### ISSUE TITLE
Throttled despite rate limit unmet

### ISSUE THREAD

**Issue by steffnay** [mastodon/mastodon#13098]
I’m getting throttled when calling the API despite the “x-ratelimit-remaining” header showing that I never drop below 150 requests remaining before the reset. Any idea of what’s going on here?

**Comment by ThibG** [comment]
there are multiple possible ratelimits that may apply based on the endpoint, maybe the x-ratelimit-remaining doesn't correspond to that actually being enforced
how did you get ratelimited?

**Comment by steffnay** [comment]
@ThibG I'm rate limited when retrieving statuses from timelines/public. Even when I only grab one page/sec I end up throttled, so I can't figure out what ratelimit I'm hitting.

**Comment by ThibG** [comment]
Paging requests are limited to 300 requests per 15 minutes, either per account if you're authenticated, or per IP address if you're not. That is in order to limit scraping of semi-public data on an instance.

**Comment by steffnay** [comment]
Got it, thank you! Is there a place where that's documented? Just out of curiosity.

**Comment by ThibG** [comment]
It's not really documented anywhere except in the configuration file: `config/initializers/rack_attack.rb`.
