### ISSUE TITLE
Bogus HTML markup validation in 3.1

### ISSUE THREAD

**Issue by fwenzel** [mastodon/mastodon#13171]
The new HTML validations for server descriptions etc seem to be bogus (?) flagging closing tags on `<p>`, `<strong>` and possibly other tags.

# Expected behaviour
Valid HTML is accepted.

### Actual behaviour
Valid HTML is flagged as invalid.

### Steps to reproduce the problem

<img width="821" alt="image" src="https://user-images.githubusercontent.com/87232/75616299-2a8b7200-5b04-11ea-9396-a84a1b61882a.png">

### Specifications

v3.1.2

**Comment by nightpool** [comment]
the server description is already contained inside of a <p> block already, so you can't add elements that aren't valid inside of a p block, like nesting a second p. the error message is pretty unclear though. the technical term for this is Phrasing content: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content

**Comment by fwenzel** [comment]
Thank you!

Since the extended description renders an entire page of content, I don't think it's useful to enforce this?
