### ISSUE TITLE
Add an API endpoint listing the instances an instance has blocked/silenced

### ISSUE THREAD

**Issue by pezcurrel** [mastodon/mastodon#13255]
### Pitch

I think mastodon is missing an API endpoint listing the instances an instance has blocked/silenced, exposing all the associated data for each blocked/silenced instance except the "private_comment" field.

### Motivation

The endpoint would allow clients to easily display "instance level" blocked/silenced instances to users, thus allowing more instance transparency, more thorough knowledge of an instance's "identity" for users, and their ability to check whether each block/silencing is actually "in policy" or not.
Moreover, the endpoint would allow the development of tools which could be useful, like a tool allowing different instances with similar policies to share a common blacklist.

**Comment by trwnh** [comment]
`GET /api/v1/instance/domain_blocks` has been added in #19345 and will be available in 4.0

**Comment by pezcurrel** [comment]
Should i close this issue now, or should i wait for the 4.0 release?

**Comment by trwnh** [comment]
i guess you could close it now?
