### ISSUE TITLE
After upgrading to 3.1.2, restarting mastodon-web.service is OK but server sends 500

### ISSUE THREAD

**Issue by bzg** [mastodon/mastodon#13270]
### Expected behaviour

- Follow 3.1.2 upgrade instructions from 3.0.1
- Restart all mastodon-* systemd processes
- Instance is working fine

### Actual behaviour

- Follow 3.1.2 upgrade instructions from 3.0.1
- Restart all mastodon-* systemd processes
- Instance is *NOT* working fine: 500 server error

### Steps to reproduce the problem

- Follow 3.1.2 upgrade instructions from 3.0.1
- Restart all mastodon-* systemd processes
- Instance is *NOT* working fine: 500 server error

So after `~$ git pull && git checkout v3.1.2` and upgrading normally, here is the error I get in `/var/log/nginx/error`:

`2020/03/17 11:13:20 [error] 6413#6413: *10504 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.254, server: _, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "mastodon.etalab.gouv.fr", referrer: "https://mastodon.etalab.gouv.fr/sw.js"`

**Comment by ThibG** [comment]
anything in mastodon-web's logs?

**Comment by bzg** [comment]
Thanks for the feedback, I'll check when the covid-19 communication crisis is a bit behind us.

**Comment by kkretsch** [comment]
Sane for me, but I found some SQL errors in the log. I think the documentation skipped the needed sql update script:

RAILS_ENV=production bundle exec rails db:migrate

After that and a restart of processes it worked for me.

**Comment by bzg** [comment]
Thanks for your help, I will try this.
