### ISSUE TITLE
Search in Bio and meta-fields.

### ISSUE THREAD

**Issue by berkes** [mastodon/mastodon#13272]
When searching for a keyword, and that keyword is mentioned in someone's public *bio*, or in one of the "meta fields" as key of value, the account should be returned as search result.

### Pitch

We can search for toots, and for usernames and even for keywords in the usernames@instance.tld strings. But we cannot search for the contents of the (public) bio or metadata fields.

Given Anne at example.com, a user with a public, listed Bio that says `Working at #foo, lover of Bar. Significant other of @bob@example.social`.  
Given Carol at example.com, a user with a account set to *not listed*, with bio `Working on #foo`.  
And given Bob at example.social followed by @anne@example.com with bio `Significant other of @anne@example.com`.

When any user on example.com searches for the term "example.social", currently already Bob shows up.

And when any user on example.com searches for the term "Bar" Anne should show up. 
And when a user searches for `#foo` any toot with hashtag `#foo` *as well as* Anne should show up. 
But when searching for `#foo` Carol should not show up.

### Motivation

This would benefit finding users. E.g. one could search for people advertising they are working on something, share a hobby, have the same interests and so on. 

This would allow new users to find interesting accounts to follow faster.

This would make the bio and meta-fields more usefull and a make accounts a more interesting unit: currently they are not searchable and only accounts are listed.

This might be an advanced feature, that is only available if an instance has chewy/Elasticsearch enabled.

I'm willing to develop this, but need to know whether this is wanted and how this would work in more detail before I can do so.

**Comment by CarwilB** [comment]
Please do this as soon as possible. As I've observed at https://github.com/mastodon/mastodon/issues/18128#issuecomment-1114026909

- The inability to search profiles is profoundly maddening. If the first word of my profile is "anthropologist" and I don't turn up on a search for "anthropologist" (honestly, preferrably also for "anthropology"), what in the world is my profile for?

**Comment by d3cline** [comment]
this is a very temporary fix, but if anyone finds this thread and just wants to do this now, you may use this python script. https://gist.github.com/d3cline/c31beed644f1da87c7c7f427fbca5419

**Comment by CarwilB** [comment]
So grateful for the work being done on this. 

However, despite mastodon.online being run on nightly builds and popping up a user interface cue that this feature is activated, it doesn't seem to actually find profiles. I've tried #Mastodon, #Rstats, #history as well as the example below and retrieve zero results each time. I can't be sure of others, but my "Suggest account to others" box is checked in preferences.

Search bar cue for searching profiles works…
<img width="298" alt="Screenshot 2023-07-01 at 7 14 02 AM" src="https://github.com/mastodon/mastodon/assets/54286746/e16a000e-6764-478c-b856-a66e54c7203c">

Zero results despite visible matching hashtag in my profile…
<img width="994" alt="Screenshot 2023-07-01 at 7 14 21 AM" src="https://github.com/mastodon/mastodon/assets/54286746/d0c16970-2e61-42fc-8da7-aa7be6b0f6ae">

**Comment by ClearlyClaire** [comment]
This hasn't been deployed on mastodon.online yet (which is using a nightly from a few days ago)

**Comment by CarwilB** [comment]
> This hasn't been deployed on mastodon.online yet (which is using a nightly from a few days ago)

@ClearlyClaire — Despite the mastodon.online's apparent update to the July 5 nightly, this lack of search results persists.

<img width="333" alt="Screenshot 2023-07-05 at 1 16 37 PM" src="https://github.com/mastodon/mastodon/assets/54286746/502975c6-f8fa-40e4-9454-1b3a03977d52">

**Comment by ClearlyClaire** [comment]
Ah, mastodon.online does not have Elasticsearch (the text search service) enabled if I remember correctly.
