### ISSUE TITLE
Scalingo setup: usability: form copy should provide link to S3 bucket region names → strings map 

### ISSUE THREAD

**Issue by aral** [mastodon/mastodon#1328]
<img width="551" alt="screen shot 2017-04-09 at 13 19 23" src="https://cloud.githubusercontent.com/assets/41798/24836549/8eb6ec78-1d27-11e7-96d4-3d1da0969f37.png">

The S3 Region input on the [Scalingo deployment form](https://my.scalingo.com/deploy?source=https://github.com/tootsuite/mastodon#master) does not specify the format that should be in. In the AWS interface, the region names are stated in human-friendly strings (e.g., "EU (Frankfurt)"). It is not trivial or logical to know that this maps to eu-central-1 (which is what I’m assuming the interface wants).

A link to a resource that maps the names to the identity strings would simplify this step.

Example copy:

`Amazon S3 region that the bucket is located in. e.g., eu-central-1 for EU (Frankfurt) <a href="http://docs.aws.amazon.com/general/latest/gr/rande.html">See full list of region identifiers.</a>`

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by matiaslagoevia** [comment]
Apologies for the delay, but I believe this should be closed. Thanks!
