### ISSUE TITLE
Support WebP images

### ISSUE THREAD

**Issue by raucao** [mastodon/mastodon#13315]
### Pitch

I just downloaded a `.webp` image from a website and was surprised when I wasn't able to share it in a Mastodon post.

### Motivation

I think this should be possible, because most users would expect any web content types to work out of the box.

### Considerations

As some browsers, especially older ones, may not support WebP directly, it may be necessary to transcode WebP images to another format, either directly at upload time, or when delivering the image.

**Comment by arethsu** [comment]
Support for WebP was added, but [then removed due to issues](https://github.com/tootsuite/mastodon/pull/11589). I'd love to see it fixed and added, but those issues would have to be ironed out. ^w^

**Comment by mstdn** [comment]
I would also love to see this happening

**Comment by kolgza** [comment]
[Related](https://github.com/LemmyNet/lemmy/issues/772)

**Comment by kolgza** [comment]
I really this issue were prioritized. I often use Mastodon on spotty connections, and so it takes a while for images to download. I would even go further and say that images and GIFs should automatically be converted to WebP.

**Comment by aelisya** [comment]
I really want to see it append to.

**Comment by trwnh** [comment]
i've observed pleroma instances using webp images in the wild now, and mastodon currently doesn't seem to even process them on the incoming side. it just says "not available" in the thumbnail.

**Comment by sindastra** [comment]
Since this issue was opened more than a year and a half ago, I would like to add that by now, all browsers (except IE, of course) do support WebP. [[source]](https://caniuse.com/webp)
