### ISSUE TITLE
After upgrading to 3.1.2 s3 file attachments no longer work

### ISSUE THREAD

**Issue by hulver** [mastodon/mastodon#13370]
s3 file attachments appear to be broken in 3.1.2 when using linode.com s3 compatible object storage. This was working fine in previous versions.

### Expected behaviour

Attaching media to a post should work

### Actual behaviour

A 500 error is returned when attempting to attach media to a post. Also, no media from other servers is displayed.

### Steps to reproduce the problem

Configure mastodon instance using linode.com object storage. The following environment variables are set in ,env.production.

```
S3_ENABLED=true
S3_BUCKET=(set to my bucket name)
AWS_ACCESS_KEY_ID=(set)
AWS_SECRET_ACCESS_KEY=(set)
S3_REGION=US
S3_PROTOCOL=https
S3_ENDPOINT=https://(my bucker name).us-east-1.linodeobjects.com/
S3_HOSTNAME=us-east-1.linodeobjects.com

```

```
web_1        | [f512b794-66e3-436d-8783-44767934ca03] [paperclip] Trying to link /tmp/RackMultipart20200331-15-dz93w2.jpg to /tmp/f8decba3946db4cc74454b470501cb2320200331-15-5lo256.jpg
web_1        | [f512b794-66e3-436d-8783-44767934ca03] Command :: file -b --mime '/tmp/f8decba3946db4cc74454b470501cb2320200331-15-5lo256.jpg'
web_1        | [f512b794-66e3-436d-8783-44767934ca03] [paperclip] Trying to link /tmp/f8decba3946db4cc74454b470501cb2320200331-15-5lo256.jpg to /tmp/778209daf14d6ff0739e613c24a46a8420200331-15-c79kcg.jpg
web_1        | [f512b794-66e3-436d-8783-44767934ca03] Command :: file -b --mime '/tmp/778209daf14d6ff0739e613c24a46a8420200331-15-c79kcg.jpg'
web_1        | [f512b794-66e3-436d-8783-44767934ca03] Command :: identify -format %m '/tmp/f8decba3946db4cc74454b470501cb2320200331-15-5lo256.jpg[0]'
web_1        | [f512b794-66e3-436d-8783-44767934ca03] Command :: convert '/tmp/f8decba3946db4cc74454b470501cb2320200331-15-5lo256.jpg[0]' -auto-orient -resize "1125x1456>" -quality 90 -strip +set modify-date +set create-date '/tmp/c4c52ace20e2cb10c8150e8fbe68b53320200331-15-1ibvl6l'
web_1        | [f512b794-66e3-436d-8783-44767934ca03] [paperclip] Trying to link /tmp/c4c52ace20e2cb10c8150e8fbe68b53320200331-15-1ibvl6l to /tmp/b59b80cd8693b48f07740542f1bddc9d20200331-15-136ai02
web_1        | [f512b794-66e3-436d-8783-44767934ca03] Command :: identify -format %m '/tmp/b59b80cd8693b48f07740542f1bddc9d20200331-15-136ai02[0]'
web_1        | [f512b794-66e3-436d-8783-44767934ca03] Command :: convert '/tmp/b59b80cd8693b48f07740542f1bddc9d20200331-15-136ai02[0]' -auto-orient -resize "352x455>" -quality 90 -strip +set modify-date +set create-date '/tmp/573dd7061f6b6765f121dfea0e53d01020200331-15-5epmdo'
web_1        | [f512b794-66e3-436d-8783-44767934ca03] Command :: convert '/tmp/573dd7061f6b6765f121dfea0e53d01020200331-15-5epmdo' RGB:-
web_1        | [f512b794-66e3-436d-8783-44767934ca03] [paperclip] Trying to link /tmp/573dd7061f6b6765f121dfea0e53d01020200331-15-5epmdo to /tmp/12e3018c660ec746fc2a96ded069373320200331-15-3uqztp
web_1        | [f512b794-66e3-436d-8783-44767934ca03] [paperclip] Trying to link /tmp/b59b80cd8693b48f07740542f1bddc9d20200331-15-136ai02 to /tmp/778209daf14d6ff0739e613c24a46a8420200331-15-7etip0.jpg
web_1        | [f512b794-66e3-436d-8783-44767934ca03] Command :: file -b --mime '/tmp/778209daf14d6ff0739e613c24a46a8420200331-15-7etip0.jpg'
web_1        | [f512b794-66e3-436d-8783-44767934ca03] [paperclip] saving media_attachments/files/000/734/311/original/9d8f5a6ff4da8ba4.jpg
web_1        | [f512b794-66e3-436d-8783-44767934ca03] method=POST path=/api/v1/media format=html controller=Api::V1::MediaController action=create status=500 error='Aws::S3::Errors::SignatureDoesNotMatch: ' duration=1071.41 view=0.00 db=3.55
web_1        | [f512b794-66e3-436d-8783-44767934ca03]
web_1        | [f512b794-66e3-436d-8783-44767934ca03] Aws::S3::Errors::SignatureDoesNotMatch ():
web_1        | [f512b794-66e3-436d-8783-44767934ca03]
web_1        | [f512b794-66e3-436d-8783-44767934ca03] app/controllers/api/v1/media_controller.rb:10:in `create'

```

### Specifications

Release 3.1.2

**Comment by Gargron** [comment]
I don't know why it was working before but can you try with `S3_OVERRIDE_PATH_STYLE=true`?

**Comment by hulver** [comment]
I've added that. No difference.

I'm now struggling to remember if it did actually work before. I did a conversion of local file storage to S3, so after I'd copied all the files onto S3, restarted, resynced and checked it all looked ok then. But I can't remember actually testing uploading something.

So it might not be a bug, but a configuration issue.

I know the keys are correct, I've double checked them against the settings for s3cmd which works fine. What else could it be?

**Comment by angristan** [comment]
@hulver what provider do you use?

**Comment by hulver** [comment]
Linode.com

**Comment by angristan** [comment]
It seems there is an issue with the `expect: 100-continue` header: https://www.linode.com/community/questions/19536/object-storage-upload-problem

**Comment by hulver** [comment]
`diff --git a/config/initializers/paperclip.rb b/config/initializers/paperclip.rb
index 8909678..03326ba 100644
--- a/config/initializers/paperclip.rb
+++ b/config/initializers/paperclip.rb
@@ -47,6 +47,7 @@ if ENV['S3_ENABLED'] == 'true'
       http_open_timeout: ENV.fetch('S3_OPEN_TIMEOUT'){ '5' }.to_i,
       http_read_timeout: 5,
       http_idle_timeout: 5,
+      http_continue_timeout: 0,
       retry_limit: 0,
     }
   )
`

Fixes my issue locally. No idea what effects this would have on other installations though. Thanks for the link @angristan 
No idea how to get this into the code base though.

**Comment by taicv** [comment]
We can't not attach media to the toot although media uploaded successfully to Wasabi.
The Toot! button still disable and it continue send request to /api/v1/media/[media_id] infinitely

https://imgur.com/a/avEvy6b

**Comment by SuperSandro2000** [comment]
![](https://i.imgur.com/IgrVsqK.gif)

**Comment by polkonic** [comment]
Same issue with  my Google Storage Bucket too...but amazon s3 works fine

**Comment by thorsummoner** [comment]
i found this thread while researching this issue: https://github.com/tootsuite/mastodon/issues/3676#issuecomment-873766178 (probably unrelated)

**Comment by mjankowski** [comment]
Still an issue on 4.3?
