### ISSUE TITLE
Upgrade notes for 3.1.3 do not mention new ruby version requirements

### ISSUE THREAD

**Issue by progval** [mastodon/mastodon#13399]
[Upgrade notes for version 3.1.3](https://github.com/tootsuite/mastodon/releases/tag/v3.1.3) should mention that #13287 increased the required Ruby version to >=2.5.0.

This is especially unexpected as 3.1.3 is a minor version number.

**Comment by angristan** [comment]
Apparently the new Sidekiq version also requires Redis > 4, and Debian 9 comes with Redis 3. Might be worth mentioning it!

(quickfix:)

```
apt install -t stretch-backports redis-server
```

**Comment by jplock** [comment]
I wasn't aware of the Redis >4 requirement either.  :(

**Comment by SuperSandro2000** [comment]
> The recommended Ruby version has been bumped to 2.6.6. You can upgrade, or you can continue using the old version by overwriting the .ruby-version file with e.g. 2.6.5 or 2.6.1 which were recommended previously

It mentions ruby but not redis.

**Comment by ProgVal** [comment]
@angristan @jplock The release notes were updated (see https://github.com/tootsuite/mastodon/issues/13404#issuecomment-610344675 )

@SuperSandro2000 This is the recommended version, not the minimum supported one

**Comment by ErikLentz** [comment]
> Apparently the new Sidekiq version also requires Redis > 4, and Debian 9 comes with Redis 3. Might be worth mentioning it!
> 
> (quickfix:)
> 
> ```
> apt install -t stretch-backports redis-server
> ```

Thanks for this. The Release Notes now mention Ubuntu, but not Debian, so I ignored it and now my feeds haven't changed in over 12 hours.
