### ISSUE TITLE
Hashtags "In the Trends" do not change

### ISSUE THREAD

**Issue by scroom** [mastodon/mastodon#13450]
### Expected behaviour

I would expect that the "In the Trends" section would always list current hashtags that are frequently used.

### Actual behaviour

Since the feature was introduced, the same hashtags are listed.

### Specifications

Actual I've updated my instance to version 3.1.3 but as described the feature never worked really.

**Comment by scroom** [comment]
I'm not the only one experiencing problems:

https://discourse.joinmastodon.org/t/trending-hashtags-broken/2523

Can I provide some more infos?

**Comment by koyuawsmbrtn** [comment]
Still an issue for me as well. Thought it was fixed, but only temporarily.

**Comment by Gargron** [comment]
Do you have a backlog of hashtags pending review? Because then it would be a different issue

**Comment by koyuawsmbrtn** [comment]
All hashtags queued for review are done. No hashtags appear in the review page for days now and the admin dashboard doesn't update as well. It's just...stuck.

**Comment by kstrauser** [comment]
I’m on 3.2.0 and having the same problem. I have no pending hashtags, and haven’t gotten the notification emails in weeks.

**Comment by koyuawsmbrtn** [comment]
I am slowly getting the feeling that @Gargron enjoys producing barely working software. It feels like we're back in the Pleroma alpha now.

**Comment by yakitama** [comment]
Sorry for the comment by DeepL translator.

My server is v3.2.0 and I have the same problem. When I was researching this issue, I noticed that the Scheduler::TrendingTagsScheduler, a recurring job in Sidekiq, was not running.
This is the output of `journalctl -u mastodon-sidekiq -g TrendingTagsScheduler -r`.

```
 9月 01 14:23:46 kokkoro bundle[1032199]: 2020-09-01T05:23:46.941Z pid=1032199 tid=ovxv5sxdr INFO: queueing Scheduler::TrendingTagsScheduler (trending_tags_scheduler)
 9月 01 14:18:46 kokkoro bundle[1032199]: 2020-09-01T05:18:46.942Z pid=1032199 tid=ovxv5sxdr INFO: queueing Scheduler::TrendingTagsScheduler (trending_tags_scheduler)
 9月 01 14:13:46 kokkoro bundle[1032199]: 2020-09-01T05:13:46.962Z pid=1032199 tid=ovxv5sydn INFO: queueing Scheduler::TrendingTagsScheduler (trending_tags_scheduler)
```

I see Sidekiq is pushing a task to the queue, but none of the threads are running this job.
The task is set as `lock: :until_executed`. I was wondering if there was some garbage left on Sidekiq from a job that had been executed in the past for this task.

On further investigation I noticed that there was a lot of stuff left in the Unique Digests section of the Sidekiq dashboard. I deleted all of these. Then the Scheduler::TrendingTagsScheduler starts to work.

```
 9月 01 14:28:47 kokkoro bundle[1032199]: 2020-09-01T05:28:47.094Z pid=1032199 tid=ovxtela0j class=Scheduler::TrendingTagsScheduler jid=368c9cb006a71673880d488d elapsed=0.16 INFO: done
 9月 01 14:28:46 kokkoro bundle[1032199]: 2020-09-01T05:28:46.934Z pid=1032199 tid=ovxtela0j class=Scheduler::TrendingTagsScheduler jid=368c9cb006a71673880d488d INFO: start
 9月 01 14:28:46 kokkoro bundle[1032199]: 2020-09-01T05:28:46.931Z pid=1032199 tid=ovxv5sydn INFO: queueing Scheduler::TrendingTagsScheduler (trending_tags_scheduler)
```

I'm not familiar with Mastodon or Ruby, so I don't know if this operation is correct. I hope my attempts will help to resolve this issue.

**Comment by koyuawsmbrtn** [comment]
> Sorry for the comment by DeepL translator.
> 
> My server is v3.2.0 and I have the same problem. When I was researching this issue, I noticed that the Scheduler::TrendingTagsScheduler, a recurring job in Sidekiq, was not running.
> This is the output of `journalctl -u mastodon-sidekiq -g TrendingTagsScheduler -r`.
> 
> ```
>  9月 01 14:23:46 kokkoro bundle[1032199]: 2020-09-01T05:23:46.941Z pid=1032199 tid=ovxv5sxdr INFO: queueing Scheduler::TrendingTagsScheduler (trending_tags_scheduler)
>  9月 01 14:18:46 kokkoro bundle[1032199]: 2020-09-01T05:18:46.942Z pid=1032199 tid=ovxv5sxdr INFO: queueing Scheduler::TrendingTagsScheduler (trending_tags_scheduler)
>  9月 01 14:13:46 kokkoro bundle[1032199]: 2020-09-01T05:13:46.962Z pid=1032199 tid=ovxv5sydn INFO: queueing Scheduler::TrendingTagsScheduler (trending_tags_scheduler)
> ```
> 
> I see Sidekiq is pushing a task to the queue, but none of the threads are running this job.
> The task is set as `lock: :until_executed`. I was wondering if there was some garbage left on Sidekiq from a job that had been executed in the past for this task.
> 
> On further investigation I noticed that there was a lot of stuff left in the Unique Digests section of the Sidekiq dashboard. I deleted all of these. Then the Scheduler::TrendingTagsScheduler starts to work.
> 
> ```
>  9月 01 14:28:47 kokkoro bundle[1032199]: 2020-09-01T05:28:47.094Z pid=1032199 tid=ovxtela0j class=Scheduler::TrendingTagsScheduler jid=368c9cb006a71673880d488d elapsed=0.16 INFO: done
>  9月 01 14:28:46 kokkoro bundle[1032199]: 2020-09-01T05:28:46.934Z pid=1032199 tid=ovxtela0j class=Scheduler::TrendingTagsScheduler jid=368c9cb006a71673880d488d INFO: start
>  9月 01 14:28:46 kokkoro bundle[1032199]: 2020-09-01T05:28:46.931Z pid=1032199 tid=ovxv5sydn INFO: queueing Scheduler::TrendingTagsScheduler (trending_tags_scheduler)
> ```
> 
> I'm not familiar with Mastodon or Ruby, so I don't know if this operation is correct. I hope my attempts will help to resolve this issue.

Can confirm this workaround worked, so looks like we identified the issue. Now we need people writing a patch for it.
![image](https://user-images.githubusercontent.com/40538332/91833539-21ac6200-ec47-11ea-8352-c261f0eab2fa.png)

**Comment by Retrodynen** [comment]
> On further investigation I noticed that there was a lot of stuff left in the Unique Digests section of the Sidekiq dashboard. I deleted all of these. Then the Scheduler::TrendingTagsScheduler starts to work.

Hi! We've had this issue for months, as @koyuawsmbrtn just confirmed while I was typing :wink: we now have trends working again after months. Just wanted to add a thanks to you.

**Comment by angristan** [comment]
related: https://github.com/tootsuite/mastodon/issues/13349

> FYI, I still have to delete unique digests all the time for trends to refresh, so I resorted to adding the crontab back

**Comment by Gargron** [comment]
With the whole separate scheduler queue in 3.3.0 we should be able to remove all the locks from scheduled jobs.
