### ISSUE TITLE
View Historical interactions with a user

### ISSUE THREAD

**Issue by lathomas64** [mastodon/mastodon#13474]
Would like to be able to easily search for interactions with my posts from a particular user. This would be helpful to evaluate whether or not to accept a follow request.

**Comment by mstdn** [comment]
I like that idea.. But how do you see it working?

**Comment by lathomas64** [comment]
Like UX wise or like codewise or what?
Pull a list of your notifications and filter by the id of the user to that user. Could be a button next to the follow request UX wise.

**Comment by mstdn** [comment]
UI indeed. Code-wise it would be doable I guess but only when ES is enabled.

**Comment by Gargron** [comment]
API-wise, the notifications endpoint supports an `account_id` param that will filter your notifications by who they're from.
