### ISSUE TITLE
Emoji Error with :it:

### ISSUE THREAD

**Issue by R4dio4ngel** [mastodon/mastodon#13578]
_This is similar to another issue reported that had to do with emoji rendering. However, it's a bit different._

:it: is appearing as a gender in emoji lists across various Mastadon instances and it cannot be changed via the custom emoji panel. I've searched for :it: via 'all', 'local' and 'remote' but it doesn't show up to change it.

**Comment by Tagadda** [comment]
Can you link a toot concerned by this issue ?

**Comment by R4dio4ngel** [comment]
@Tagadda Sure! Here's the main one that started the convo. 
![scrnli_4_29_2020_4-49-36 PM](https://user-images.githubusercontent.com/64558539/80650340-704bb480-8a39-11ea-9741-9cc38bafa82a.png)


- https://sunbeam.city/@chillgamesh/104082824159826436

**Comment by vmstan** [comment]
Closed as duplicate.
