### ISSUE TITLE
Unable to build docker image, "Value "mastodon" invalid for option gid (number expected)"

### ISSUE THREAD

**Issue by Casuallynoted** [mastodon/mastodon#13686]
I'm currently moving my Mastodon instance over to Docker, and I'm building using this guide:

https://www.howtoforge.com/how-to-install-mastodon-social-network-with-docker-on-ubuntu-1804/

Every time I run the first "sudo docker-compose build" command though, it ends with an error:

"Value "mastodon" invalid for option gid (number expected)

The command returned a non-zero code: 1"

Is there something I might be doing wrong? I've been using docker for a while, but this is my first time using docker-compose. I've checked while troubleshooting with another user and the Dockerfile is the same as the one in the repo.

Edit: This is the full error towards the end:

"Service 'web' failed to build: The command '/bin/sh -c apt update && echo "Etc/UTC" > /etc/localtime && ln -s /opt/jemalloc/lib/* /usr/lib/ && apt install -y whois wget && addgroup --gid $GID mastodon && useradd -m -u $UID -g $GID -d /opt/mastodon mastodon && echo "mastodon:head /dev/urandom | tr -dc A-Za-z0-9 | head -c 24 | mkpasswd -s -m sha-256" | chpasswd' returned a non-zero code: 1"

**Comment by SuperSandro2000** [comment]
This guide is not ideal as it guides you to install a mastodon instance of the master branch which you should only do if you know what you are doing. I suggest you to use the pre-build docker image from either Docker Hub or quay.

I build the Dockerfile from master without any issues so as of writing this can't be reproduced.

**Comment by Casuallynoted** [comment]
> 
> 
> This guide is not ideal as it guides you to install a mastodon instance of the master branch which you should only do if you know what you are doing. I suggest you to use the pre-build docker image from either Docker Hub or quay.
> 
> I build the Dockerfile from master without any issues so as of writing this can't be reproduced.

Initially, I tried doing it via the Docker Hub image, but it gives me this and then stops running when I try to run it:

![Screenshot_2020-05-09 Xanadu - Synology DiskStation](https://user-images.githubusercontent.com/6272557/81489084-8dedfa80-923f-11ea-8959-aee13b4ab31e.png)

**Comment by SuperSandro2000** [comment]
That happens if you run the docker image without any command supplied.

**Comment by Gargron** [comment]
GID must be a number. 991 by default.

The Dockerfile does not execute any command by default because the Docker image contains 3 separate things you must run. So you'll run 3 copies of the image, one with rails, one with sidekiq, and one with streaming. The docker-compose configuration takes care of all of that for you.
