### ISSUE TITLE
how to update the actor request. i just moved my acct to new position

### ISSUE THREAD

**Issue by dudochkin-victor** [mastodon/mastodon#13754]

**Comment by ThibG** [comment]
I am sorry, I don't understand your bug report.
What is “the actor request”?

By moving your account to a new position, do you mean you have used the account migration feature (see screenshot)?

![Account migration feature screenshot](https://user-images.githubusercontent.com/384364/82062146-f6b6f600-96c9-11ea-9a8a-3e40bd9dadd2.png)
