### ISSUE TITLE
White outline on black emojis rendered unevenly

### ISSUE THREAD

**Issue by leo60228** [mastodon/mastodon#13766]
### Expected behaviour
I would expect that the white outline (introduced by #8597) on a circular emoji like :8ball: is rendered as a circle.

### Actual behaviour
The shape is uneven.
Desktop Firefox (WebRender, AMD, Linux):
![image](https://user-images.githubusercontent.com/8355305/82099022-371b7180-96d4-11ea-9969-fce3faaaa797.png)
Unknown mobile browser (reported by another user):
![image](https://user-images.githubusercontent.com/8355305/82099046-4ac6d800-96d4-11ea-9fba-826382b5ddbc.png)

### Steps to reproduce the problem
Place the :8ball: emoji in a display name or message.

### Specifications

This occurs on multiple instances. I'm using the v3.1.2 tag, but I don't see any change to the relevant code since it was introduced.

I'm using Firefox 73.0 on Linux with WebRender enabled. I'm not sure what browser the other user is using.

**Comment by leo60228** [comment]
This filter works by making 4 copies of the image, making them solid white, and then moving them in different directions. You can get the same artifacts by doing this in an image editor:
![image](https://user-images.githubusercontent.com/8355305/82099876-66cb7900-96d6-11ea-8c6a-3878e79adb2b.png)
I can't find a way to outline SVGs in CSS that doesn't have this problem, though. The best option might be to just modify the SVGs themselves.

**Comment by leo60228** [comment]
This svg filter has no artifacting on my browser. Note that the more obvious `feMorphology` also creates artifacts (as it will never go outside the bounds of the input, unlike `feGaussianBlur`). https://codepen.io/snuggles08/pen/BaoqjZJ

**Comment by ThibG** [comment]
@leo60228 very interesting, thanks! The SVG filters seem to give a pretty good result. I'm worried about performances because of the Gaussian blur filter… but on a quick test, this doesn't seem worse than our existing 4-drop-shadow filter thing.

**Comment by leo60228** [comment]
The drop shadow trick does for Gaussian blurs, though they each have a radius of 0. I'm not sure if browsers optimize for this case.

**Comment by ThibG** [comment]
@leo60228 thanks. Started to experiment a bit in a PR (#13769), the changes seem pretty inconsistent across browsers. I'd say they are *mostly* good though.
