### ISSUE TITLE
Optimize restoration of scroll position

### ISSUE THREAD

**Issue by Pajn** [mastodon/mastodon#1379]
On mobile changing between the local and federated timeline is pretty slow. A big part of this comes from `react-router-scroll` and child modules as it causes a forced synchronous layout that takes over 100ms.
When switching between the timelines this is unnecessary as the scroll position isn't restored anyway.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Scroll position is restored when navigating using the "back" buttons. I do notice that unpleasant 100ms lag you mention, but I am not sure how this could actually be fixed? The scroll element needs to be there in case the user then navigates backward.

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
