### ISSUE TITLE
[legal] "No warranty" disclaimer for terms and privacy policy

### ISSUE THREAD

**Issue by dioraman** [mastodon/mastodon#14011]
### Expected behaviour

A "no warranty" **Disclaimer** paragraph stands at the top of the terms of service and privacy policy page since they are just placeholders. Instance admins change the page according to their own legal framework and translators safely provide a tentative translation.

### Actual behaviour

No disclaimer is provided and the page is just a placeholder. However, the current placeholder fits to mislead instance admins and translators:
- admins are induced to consider the page complying to their own legal framework -> admins may leave the placeholder as terms of service and privacy policy of their own instance;
- translators are induced to consider their translations to be complying to any relevant legal framework -> translators do not provide a tentative translation.

### Steps to reproduce the problem

Go to `$INSTANCEBASEURL`/terms. 

### Specifications

**Commit**: 5e6ec22
**Pull request**: #13826
**N.B.**: this is not a feature request. It's a compliance-level bug.

**Comment by nightpool** [comment]
@dioraman Mastodon's placeholder terms of service and privacy policy, like the rest of Mastodon, are provided without warranty, as covered in the AGPL:

 https://github.com/tootsuite/mastodon/blob/master/LICENSE#L589-L596

There's no reason for the terms of service or privacy policy to be called out explicitly here. Discourse, which provides a similar open-source forum app, has a similar approach, in that the default installation comes with a basic terms of service and privacy policy, and they do not explicitly disclaim it in the way you're suggesting. (In face, we adopted our current terms of service and privacy policy from theirs, as they adapted theirs from wordpress).

**Comment by mjankowski** [comment]
No updates here in ~4 years ... going to close on the assumption that the previous explanation (that the project license wrapper effectively already does this) resolves this.
