### ISSUE TITLE
When adding a toot the toot’s counter increased but new toot doesn’t appear until page being refreshed

### ISSUE THREAD

**Issue by bluescreen69** [mastodon/mastodon#14021]
### Expected behaviour

A toot is appear on user’s profile page and the counter increased

### Actual behaviour

The counter increased but a toot doesn’t appear

### Steps to reproduce the problem

1.	Open user profile page
2.	Submit a toot

### Specifications

Version: Mastodon Project v3.1.4

![NOhnVGkoOw](https://user-images.githubusercontent.com/60180427/84285783-8d01fe80-ab46-11ea-829f-bbf89ef0a40f.gif)

**Comment by resynth1943** [comment]
I have this issue too.

**Comment by bluescreen69** [comment]
Actually, there is a similar issue - when click delete a toot it's deleted from the user profile page, but the counter doesn't decrease.
See attachment:
![rmwV4fTFRf](https://user-images.githubusercontent.com/60180427/84423863-ce1e0f80-ac27-11ea-82d8-3654815249d3.gif)

**Comment by arielrodrigues** [comment]
I just reproduce both problems pointed by @bluescreen69. I will work on it at my weekend, right?

**Comment by vmstan** [comment]
Fixed with #14212
