### ISSUE TITLE
width of user images on follows/followers page inconsistent and usually too large

### ISSUE THREAD

**Issue by chaosmonk1** [mastodon/mastodon#14065]
### Expected behaviour

Images should be scaled width that is uniform and reasonable.

### Actual behaviour

The images are all different widths, and most are so wide that they leave little or zero room for the user's name.  See the image below.  Most user images are the size of OpenStreetMap's, which completely hides the username.  The rest are various widths less than that, ranging from reasonable (like Debian's) to still too large (like Whonix's which only leaves room for the first three characters of the username).

![follows_followers](https://user-images.githubusercontent.com/38551636/84847985-23cb3100-b007-11ea-9d62-1dfef942c601.png)

### Steps to reproduce the problem

Follow multiple users, go to the "Follows and followers" page.

### Specifications

* Mastodon 3.14 (self-hosted instance)
* Debian 10
* Ungoogled Chromium 81, Firefox 68ESR

**Comment by Gargron** [comment]
This isn't how it normally looks. Is the compiled CSS up to date?

**Comment by chaosmonk1** [comment]
@Gargron How would I check/ensure that?
