### ISSUE TITLE
can't remote follow mastodon.social users

### ISSUE THREAD

**Issue by chaosmonk1** [mastodon/mastodon#14066]
# Expected behaviour

After clicking "Follow" on a user's profile and entering myself@myinstance, I should be redirected to myinstance and prompted to follow the user.

### Actual behaviour

This works for most instances, but if the user I am trying to follow is on mastodon.social, after entering myself@myinstance I am taken to a page with the title "This page is not correct" and the text "We're sorry, but something went wrong on our end."  In order to follow the user, I have to search for them from my own instance.

### Steps to reproduce the problem

Try to remote follow a mastodon.social user. 

### Specifications

* 3.14 (self-hosted)

**Comment by ThibG** [comment]
Is the “This page is not correct” page from your domain or mastodon.social? If it's from your domain, can you check the logs? (`journalctl -u mastodon-web --follow`)

**Comment by chaosmonk1** [comment]
Hi, the "This page is not correct" page is from mastodon.social.  I don't make it back to my domain.

**Comment by ThibG** [comment]
Interesting… @Gargron could you have a look?

**Comment by kuba-orlik** [comment]
I have a similar issue - I can't remote follow users from https://en.osm.town

**Comment by ThibG** [comment]
@kuba-orlik I assume you mean you use a different instance than en.osm.town, and en.osm.town shows you “This page is not correct” when entering your handle in the “Enter your username@domain you want to act from” input after clicking a “Follow” link on en.osm.town, is that right? If that's not the case, could you describe the situation a bit more? (Which instances are involved, and at which step does it fail, do you ever see an error?)

**Comment by kuba-orlik** [comment]
Your description is correct. 

My instance is toot.kuba-orlik.name and it runs v3.1.2.

I'm visiting a users' profile, like this one: https://en.osm.town/@rory . Then I press "Follow" and a new window opens. I enter my handle (kuba@toot.kuba-orlik.name) and press "Proceed to follow". After clicking that button, I see a page saying "The page you are looking for isn't here." and a GIF of a frustrated mastodon inside the window:

![image](https://user-images.githubusercontent.com/2697916/86450460-1e5d2e80-bd09-11ea-890e-24ac3b7b9373.png)


Network manager reports a POST request to https://en.osm.town/users/rory that returns 404 error

**Comment by ThibG** [comment]
@kuba-orlik  hmm, oddly enough, if i do the same thing from that page, i get to a login page on your server… so it looks like it should work…?
can you provide a more complete log of the requests that have been performed?

**Comment by kuba-orlik** [comment]
I'm so dumb. After reading @ThibG's comment I realized that the issue on my side is caused by the [CleanLinks](https://github.com/Cimbali/CleanLinks) addon. Disabling the addon solved the issue. Thanks!
