### ISSUE TITLE
Unmute accounts automaticaly after some time

### ISSUE THREAD

**Issue by e1mo** [mastodon/mastodon#14100]
### Pitch

As with filters, it would be quite nice if account mutes could expire after some time. A REST API Endpoint parameter would be the least, a integration in to the UI also more ore less needed for people to actually use it. Possibly related to #13752 

### Motivation

There are numerous reasons to mute a person. E.g. a persons content is omnipresent but just not relevant to you. It could also be, that a person is having a mentally hard time and you just can't handle it. Other examples my be a person tooting about a topic you are just not interested in (e.g. a music competition), without proper usage of hashtags. In this case if have often felt the wish to just tune out a person for 24 hours or a couple of days. Myself, and others I know, often find myself forgetting to unmute a person manually for a couple of days or even weeks. This kinda sucks if you are interested in a persons toots but are a bit oblivious.

**Comment by ThibG** [comment]
See #13831

**Comment by sparr** [comment]
Should this be closed since #13831 was merged?

**Comment by ClearlyClaire** [comment]
I think so, yes!
