### ISSUE TITLE
Mastodon throws HTTP 400 with Honey extension enabled

### ISSUE THREAD

**Issue by koyuawsmbrtn** [mastodon/mastodon#14201]
### Expected behaviour

Mastodon should save the admin settings

### Actual behaviour

nginx gives a 400 error without any logs in Mastodon whatsoever

### Steps to reproduce the problem

Install Honey and hit the save button in the admin panel

### Specifications

Browser: Latest Firefox
Operating system: Windows and Linux (probably macOS as well)

**Comment by mjankowski** [comment]
Closing on assumption that this is resolved in newer versions. Can you re-open with current screenshots if still problem in 4.3?
