### ISSUE TITLE
When opening the context menu in the timeline, it flies away.

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#14266]
### Expected behaviour

Context menu should stay put while I select an option.

### Actual behaviour

Context menu flies up the page, preventing me from selecting an option.

### Steps to reproduce the problem

1. Click on the options button under a toot in either the federated or local timelines.
2. Wait for the timeline to update.
3. The context menu will fly up the page.

### Specifications

I'm using Fedora with Firefox 78.0.1 in the anticapitalist.party instance, although this issue happens on more than just this instance.

**Comment by Kellegram** [comment]
Ideally the top shouldn't update after scrolling, especially at this rate, IMO a better behaviour would be what is done on twitter, have a button informing the user there were new "toots" and upon clicking it, the user is taken to the top and the toots are loaded.

**Comment by Sasha-Sorokin** [comment]
It because the menu is absolutely positioned, the page continues to scroll as new posts appear, but the menu stays in the same place, therefore moves out of view. Annoying bug, but as far as I remember, all popups including dropdowns are placed using some library that does not allow to use fixed positioning. I wonder if we can fix this by bringing Popper.js, when bringing tooltips (as both libraries will probably share it) and in even farther future by using virtual scroll for timeline. For now, though, you can mitigate this bug by toggling on “Slow mode” in settings.

**Comment by ThibG** [comment]
@Sasha-Sorokin the library we use is https://react-bootstrap.github.io/react-overlays/api/Overlay, it does seem to use Popper.js, and we control the CSS, but the library's code seem to assume absolute positioning and just switching to “fixed” instead adds an offset.

Something we should probably do anyway is prevent TL auto-scrolling when a dropdown is open, the same way we do when moving the mouse over the TL. I will look into that.

**Comment by Sasha-Sorokin** [comment]
@ThibG I think we are running outdated version of `react-overlays`. Current is `3.2.0` (May 15, 2020), ours `0.9.1` (Oct 31, 2019). And there is no Popper.js in sight in [`0.9.1`'s `package.json`](https://github.com/react-bootstrap/react-overlays/blob/v0.9.1/package.json), as well as there were [no major changes](https://github.com/react-bootstrap/react-overlays/compare/v0.8.3...v0.9.1) from `v0.8.3` released back in Oct 24, 2017. Maybe it's worth trying to update it to actual version.

**Comment by ThibG** [comment]
@Sasha-Sorokin indeed, we're using a severely outdated version… I'm not sure newer versions allow us to use `position: fixed` though, and I tried using the latest version, but couldn't get it to work (see https://github.com/ThibG/mastodon/tree/features/react-overlays-3 if you want to have a look)

**Comment by Sasha-Sorokin** [comment]
@ThibG well, it should have broke, there surely were some breaking changes in these three majors. For me it places menu incorrectly, but if I replace `Overlay` with `Dropdown` it kinda shown menus in the right place, but it pops up as soon as component is mounted (ignoring `show` prop). I'll see what I can do, maybe it's worth rewriting the whole thing from scratch, for now we can kinda block this bug report for later, giving it's not that critical and can be mitigated by enabling “Slow mode”.

**Comment by ThibG** [comment]
@Sasha-Sorokin sure, I did try to account for the API changes (for the status dropdown at least, trying to get those to work first), but the injected style positions the element at `top: 0px` and `left: 0px` while also disabling pointer-events, and I'm not sure why that is (this seem to also occur in the demo, but then a new style is sent right away with correct placement etc., while in our case, the style props remain the same).

**Comment by afontenot** [comment]
Surprised that this issue hasn't received any comments in over 2 years. Just thought I'd mention that it's still occurring for me (and very annoying) on the local / federated timelines on mastodon.social. Instance version is 4.0.0rc1. Pretty difficult to do any kind of filtering on the fast timelines as a result.

**Comment by gregmcdougall** [comment]
i think this could be closed actually - one for the admins. i have discovered a profile setting under ANIMATIONS AND ACCESSIBILITY called Slow mode. checking this seems to enable the counter and prevent auto-scrolling. maybe should be on by default?

**Comment by Brawaru** [comment]
Not really, the issue is still there in slow mode if you scroll manually, so it makes sense that this is still open. I haven't had much success updating the overlays library, so if anyone wants to try it themselves, feel free to do so.

As for slow mode by default, there is a separate issue for that — #21049.

**Comment by sidp** [comment]
I am interested in working on this. I have verified that upgrading react-overlays (to the latest version, currently 5.2.1) will solve this issue. Quite a lot has changed in the library and adaptations are necessary, but it looks feasible to get this done.

**Comment by ClearlyClaire** [comment]
@sidp updating `react-overlays` seems worthwhile, especially if it fixes the issue at hand! I could not manage to get it working when I last tried though.

**Comment by Brawaru** [comment]
Yoo, thanks @sidp!
