### ISSUE TITLE
Mastodon constantly logs an AUTH error in the logs

### ISSUE THREAD

**Issue by csolisr** [mastodon/mastodon#14299]
When using Mastodon on a single-user setup, I noticed that the log files were constantly increasing in size. Upon checking the files, I noticed a common error constantly being logged and ballooning the storage size of the log files. I'm not completely sure about the source of the error, but I have the theory that it's related to Mastodon's workers' connection to Redis for cacheing - as I have a single-device configuration, I currently use Redis as a localhost-only service without a password configured, which might be the cause of the errors, but should be supported by both Mastodon and Redis.

### Expected behaviour

Mastodon should be able to run without constantly reporting a Node error in the logs.

### Actual behaviour

Mastodon constantly reports the following error in the Node logs, with the worker number being random each time:

````
info Starting worker 11458
info Worker 11458 now listening on 127.0.0.1:4000
ERR! ReplyError: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
info Worker 11458 exiting, bye bye
````

### Steps to reproduce the problem

- Start Mastodon (can upload redacted config files on request)
- Leave it running for a few minutes
- Check /var/log, notice the log file size ballooning

### Specifications

Stable version 3.1.3 running on Raspberry Pi 4 (DietPi OS), tested on Firefox for Linux and Windows.

**Comment by Gargron** [comment]
Make sure you don't have an empty `REDIS_PASSWORD=` in your `.env.production` file, if it's there just remove that line.
