### ISSUE TITLE
Safari push notifications

### ISSUE THREAD

**Issue by Sjors** [mastodon/mastodon#14352]
#3243 introduced  [Web Push Notifications](https://developers.google.com/web/fundamentals/engage-and-retain/push-notifications/web-push-protocol) which use a service worker. It's supported by [several browsers](https://caniuse.com/#feat=push-api) such as Chrome and it Just Works(tm).

Unfortunately Apple stubbornly (or in their great wisdom?) holds on to [their own standard](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html) in Safari.

Using it would require an instance administrator to sign up for an Apple, obtain a certificate, do some magic with it and then upload it. These steps should be easy to explain though.

I implemented Safari notifications in a project of my own, if someone needs an example:
* Rails 6 server side: mostly this [controller](https://github.com/Sjors/crush_curve/blob/master/app/controllers/subscriptions_controller.rb) and  [model](https://github.com/Sjors/crush_curve/blob/master/app/models/safari_subscription.rb) 
* ReactJS client side (apologies for hideous code): https://github.com/Sjors/crush_curve/blob/master/app/javascript/components/Settings.js 

In another project I have it side by side with Web Push Notifications and most functionality can be reused.

I supposed a 3rd party app using the REST API could do this, but - without being familiar with this codebase - it seems easier to build it side by side with the existing Web Push Notifications stuff.

Safari has better privacy by default than Chrome, which might make it worth supporting, especially if it's very little extra code.

**Comment by dariusk** [comment]
This is really cool. I wish Apple would stop holding this back :(

**Comment by gferreroferri** [comment]
Now that this is available in Safari, any plans to implement it in the near future?

**Comment by ThisIsMissEm** [comment]
I'd be inclined to suggest this won't be implemented any time soon, since it requires a credential generated by a registered apple developer account, where as the standard, which is implemented in other browsers, does not require such.

**Comment by dariusk** [comment]
It's like Apple picked the worst way to implement this

**Comment by jensimmons** [comment]
Safari announced support for standards-based Web Push two years ago at WWDC21. And shipped it in Safari 16.1.
https://webkit.org/blog/13399/webkit-features-in-safari-16-1/

You can read more at: https://webkit.org/blog/12945/meet-web-push/

The document you linked to above — "[their own standard](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html) in Safari" — is on a deprecated/archived website from years ago. 

This is Apple's documentation website, with up to date information about Push Notifications in Safari:
https://developer.apple.com/documentation/usernotifications/sending-web-push-notifications-in-web-apps-and-browsers

**Comment by jensimmons** [comment]
Also, Web Push shipped for web apps on iOS and iPadOS alongside Safari 16.4. 
https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/

**Comment by renchap** [comment]
Closing this as the web push notifications are now working in Safari, I just tested on the latest Safari macOS.
