### ISSUE TITLE
[Suggestion] add notice of audio CORS in 3.2.0 release note

### ISSUE THREAD

**Issue by highemerly** [mastodon/mastodon#14391]
By "Change design of audio players in web UI" of 3.2.0rc1, **audio file cannot be played in Web UI** if a server satisfies all of the following conditions:

- 3.2.0rc1 or 3.2.0rc2
- Media server has different domain from web server (e.g. files.mastodon.social from mastodon.social)
- The media server will not response "Access-Control-Allow-Origin" to GET request

The reason why audio file cannot be played is **CORS**. Until mastodon 3.1, all media files (image, video, and audio) will be fetched by `sec-fetch-mode: no-cors`. However, after mastodon 3.2, only audio file will be fetched by `sec-fetch-mode: cors`.

#### video in 3.2
<img width="413" alt="スクリーンショット 2020-07-25 20 18 21" src="https://user-images.githubusercontent.com/3039555/88455948-b7b8d400-ceb4-11ea-9ebc-5d9d36ebaa9b.png">

#### audio in 3.2
<img width="412" alt="スクリーンショット 2020-07-25 20 15 19" src="https://user-images.githubusercontent.com/3039555/88455953-c69f8680-ceb4-11ea-87a3-6a16e860dfe1.png">

Actually, I don't know the reason. (This specification is depend on web browser, or not??) However, by this update, some mastodon server will have the error about audio player, even though it is fine until 3.1.

I suggest to publish some notice for release note of 3.2.0, like:

**Notice:** If your media server has different domain (e.g. file.example.com or media.example.com) from web server, make sure that media server returns appropriate `Access-Control-Allow-Origin` attribute.

--- 

### Expected behaviour

`<img>`, `<video>`, and `<audio>` may be shown in Web UI

### Actual behaviour

`<img>` and `<video>` can be shown in Web UI, but `<audio>` cannot be. When audio file is got, CORS error of shortage "access-control-allow-origin" will be shown.

### Specifications

- Mastodon 3.2.0rc1
- Google Chrome 84.0.4147.89 64bit
- macOS Catalina 10.15.6

**Comment by Gargron** [comment]
Added to notes:

![grafik](https://user-images.githubusercontent.com/184731/88456941-ace54b80-ce82-11ea-86c9-3a5d217ba4d8.png)

**Comment by Gargron** [comment]
I'm actually not quire sure if methods/headers headers are necessary or if it will work correctly with just the origin one. Do you happen to know?

**Comment by highemerly** [comment]
Sounds good!

In my server, I set only 'Access-Control-Allow-Origin'. In my understanding, `Access-Control-Allow-Methods` and `Access-Control-Allow-Headers` are only used in pre-flight request. 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Request-Method

**Comment by nigini** [comment]
I am experiencing this in a v3.5.3 deployment. Could you clarify where the `Access-Control-Allow-Origin` should be added (as I cannot find any configuration related to serving  audio files specifically?) 

BTW: I assume we are talking about the `/etc/nginx/sites-available/mastodon` file, right?

**Comment by vmstan** [comment]
Closing as original request for documentation was met.
