### ISSUE TITLE
Ability to expose developer instance to 0.0.0.0

### ISSUE THREAD

**Issue by brawaru** [mastodon/mastodon#14472]
### Pitch

I wanted to work on #13545, but unfortunately, to test my changes I have to use Windows machine. It's kind of hard to get Mastodon running on Windows from my experience and I really don't want to duplicate my set up, so I have Virtual machine up and running, but I could not connect from it to my Mastodon developer instance, because it does not listen to connections outside the host machine (aka 127.0.0.1)

I've tried many ways to expose developer instance to the network with many weird hacks (like aliasing domains or redirecting requests in the browser), and while I've got some progress — like was able to load pages; things like CSS and websockets won't work because they are fetched from 127.0.0.1, which is not available in virtual machine, it's a different loopback interface.

Maybe I could somehow get it working, but I just don't understand Mastodon's setup, there are four processes binding on different ports, and they seem to be very interconnected. For webpack developer server, if you change pubilc address to address of the host on virtual machine, you won't be able to use your instance on your host or other devices, and it still won't work correctly on guest.

### Motivation

Painless ability to expose developer instance to the local network (not loopback interface) could be very useful to developers who want to tests on multiple targets. While I understand that this is related to the security (like you really don't want to do that on public networks), it should be allowed per developer's need via, say, environment variable like `MASTODON_DEV_HOST=0.0.0.0`.

Take me, I'm behind the NAT, so my server won't be visible to the public internet; people with routers can also relate — because most routers have internal firewall which does not forward ports by default.

**Comment by Gargron** [comment]
You can already do this, I think.

**Comment by Sasha-Sorokin** [comment]
@Gargron well, yes, but you have to edit config files and even if you manage to run it, CSP will block websockets, for example (from what I remember seeing in console).

**Comment by phocks** [comment]
I managed to get it going with an ssh port tunnel:

```bash
ssh -L 3000:localhost:3000 username@vm_ip_address
```

Then I could connect to http://127.0.0.1:3000 on my local Windows machine to the Ubuntu VM.

**Comment by mjankowski** [comment]
Closing on assumption that the last comment here resolves this ... if that's not the case (on current versions of things), please reopen.
