### ISSUE TITLE
[Feature request] Accept/reject follow request from profile

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#14483]
### Pitch

On someone's profile in the web UI, it would be cool if you could see that someone had sent you a follow request, and accept or reject it from their profile, so that you don't have to go back to `/web/follow_requests` to do it.

### Motivation

This is what it's currently like now. Both of these people kindly sent me follow requests so I could test on mobile and laptop, and there is no indication in their profile that they've requested to follow me, and nothing in profile menus.

Laptop (Mac, Chrome):

![Request 02](https://user-images.githubusercontent.com/6607512/89101931-83856c00-d3fc-11ea-9790-74dc89d4f172.png)

Mobile (Android):

![Request 01](https://user-images.githubusercontent.com/6607512/89101936-8da76a80-d3fc-11ea-823f-79c028506871.png)

I think it would benefit people who have locked accounts, because they wouldn't have to click/tap around as much to get to follow requests and accept them.

For example, when I get a follow request, I usually check out someone's profile before I accept. It would be cool if I could accept or reject from their profile, because it would reduce the chances that I accept/reject the wrong person from `/web/follow_requests` if I have several requests, and it would just same time and clicks and potential confusion.

**Comment by inga-lovinde** [comment]
Another benefit of this feature request: I can notice follow request, decide to act on it later, and then forget about it. Later, when I interact with that person, there is no indication in their profile that they sent me a follow request, and I will not know that they want to follow me (as I know for users who follow me)

**Comment by Cassolotl** [comment]
This feature has now been implemented. :) Thank you!
