### ISSUE TITLE
Empty column indicator has collapsed padding

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#14537]
`.timeline-hint` inside `.item-list` has proper padding, but inside `.empty-column-indicator` does not.

### Steps to reproduce
- Find a profile that follows accounts on your server but has 0 local followers (or vice-versa).
- Note that followers has collapsed padding due to `.empty-column-indicator` class.
- Note that removing the class causes padding to be correct.

**Comment by trwnh** [comment]
This is from the `contain: strict` rule as best as I can tell

**Comment by edent** [comment]
Just run in to this bug - here's a screenshot of what it looks like:
![Screenshot - you can't read the text.](https://user-images.githubusercontent.com/837136/202419481-7519813c-7079-4fb1-9be2-c1409564ba31.png)

Here's what it looks like if `contain:strict` is removed:
![now possible to read the text.](https://user-images.githubusercontent.com/837136/202419651-863db23b-5ee9-46c6-9293-71dfa72924de.png)

**Comment by mjankowski** [comment]
I can't replicate this on a local 4.3 install using either Chrome or Safari.

It might still make sense to remove that old CSS targeting super-old chrome versions, but I think this can resolve as stale.

That said, in the event I'm completely missing where to look here (or what conditions are needed) - can you reopen with more details on state of data/account, and also which server version and local browser versions produce the issue?
