### ISSUE TITLE
[Feature request] Option to replace filtered toots with placeholder that allows unhiding

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#14562]
### Pitch

@ThibG said [here](https://github.com/tootsuite/mastodon/issues/14519#issuecomment-670709393) that Glitch has:

> a setting to not hide filtered posts with a “Filtered” placeholder but dynamically add a CW with the matched words

### Motivation

It sounds great, I want it.

I remember back when the filters were first designed this option was intentionally omitted because people didn't want the option to unhide triggering content due to lack of impulse control. As a person with ADHD and very little impulse control I can understand that need, but I still want to be able to unhide filtered things sometimes. I want to know if my filters are working in a way that is good for me, and I like the idea of it functioning a bit like a CW that I impose.

For the latter, specifically people have been requesting for a while the ability to edit a post (as a mod or a user) to add a CW, and to be able to boost with a CW. Being able to filter in a way that adds a CW with the word you're filtering would fix this for a lot of people, **effectively allowing readers to add CWs to other people's posts.** Amazing!

**Comment by Cassolotl** [comment]
Related: *Option to expand filtered toots on click #8914*

**Comment by ObsidianWolf64** [comment]
[I commented on the other issue there but then realized this would probably be a better fit, oops.]

This would be absolutely wonderful. As it is, I can't even see what filter a post hit, much less what the post is if I decide it's worth opening.

Glitch does very nicely. It has a "(show why)" link next to the "Filtered" text; clicking that brings up a dialog that shows who wrote the post, what filter it hit, and lets you see the original post if you want.

This is totally optional, and I think it actually doesn't have it on by default, mimicking Mastodon's current behavior of "no option to view it at all".

!["Show Why"](https://user-images.githubusercontent.com/58482583/105638609-81e3b080-5e41-11eb-8e98-420d29a33eb6.png)
![Filter preview panel](https://user-images.githubusercontent.com/58482583/105638617-945dea00-5e41-11eb-847b-8b8754f62f9f.png)

**Comment by ClearlyClaire** [comment]
Implemented in #18058
