### ISSUE TITLE
Audio Thumbnails Don't Respect "Mark media as sensitive"

### ISSUE THREAD

**Issue by bcj** [mastodon/mastodon#14561]
### Expected behaviour

The media player doesn't display the album art for a track by default if "Mark media as sensitive" was selected.

### Actual behaviour

The artwork is always displayed, even when selected (and even when the post contains a CW)

### Steps to reproduce the problem

 * Upload an audio file with embedded album artwork (or manually add a thumbnail to a track without it)
 * Select "Mark media as sensitive"
 * Post
 * Find post in timeline, artwork is visible 

### Specifications

Server is running a fork of 3.2.0 (Hometown 1.0.5+3.2.0), so it's possible the fork is causing this problem.

This is using the light theme in Firefox 80.0b3, on macOS 10.15.6

**Comment by ThibG** [comment]
I can confirm this issue. This is something we overlooked.
