### ISSUE TITLE
Admin UI for accounts

### ISSUE THREAD

**Issue by Gargron** [mastodon/mastodon#146]
- [x] List local/remote accounts/users
- [x] Disable registrations
- [ ] Manually create user accounts
- [x] Reset an account's password
- [x] Toggle account silencing, NSFW marker

**Comment by triplefox** [comment]
Forcing NSFW will be a help with porn bots

**Comment by haniawni** [comment]
It'd be particularly useful for certain types of organizations to have member email addresses be unconstrained, but able to limit registrations, for example:
- require entering an invite code (ex. me and my friends, or members of a multiuniversity research organizing network)
- to require approval by an admin or by api, for semiclosed communities with an application process
- or up to a fixed total number of accounts

These suggestions would be particularly valuable for communities that are likely to be targeted by harassment, but which need registration open continuously for certain sorts of people.

**Comment by wxcafe** [comment]
The suggestions in the last comment should be added to the main post

**Comment by SherSpock** [comment]
> * [ ]  Manually create user accounts

Just curious, is the above still both missing and desired?

Checking out Mastodon for the first time and looking for something simple
