### ISSUE TITLE
[Feature Request] Converting toot ID between instances

### ISSUE THREAD

**Issue by molaeiali** [mastodon/mastodon#14601]
### Pitch

I think it would be great if we have an API to convert a URL form an instance to another, for example:
I want to reach here:

```https://hostux.social/web/statuses/99730308154753208```

from here:

```https://mastodon.social/@Mastodon/99730307203414093```

As you can see, They are same toots, but `hostux.social` is my instance and `mastodon.social` is the original instance, and the toot IDs are different.

The only possible way right now is to search `mastodon.social` URL inside `hostux.social` and get the toot and it's ID. 
The problems are:
1. It needs an access token.
2. It is not direct and requires more actions to load the other url.
3. The search page in web application is preventing default js functions so it cannot be automated to search and redirect to the toot.

### Motivation

Right now, toots shared in other places than mastodon instances are independent, so if I open my friends toot from `mastodon.social` which he is shared in telegram, it opens on `mastodon.social`, and I cannot interact with the toot (reply to it, favorite it, etc...)

It would be great to detect if I am logged in, in any other instance and redirect to that instance to see the toot automatically.

My solution to it was a firefox/chrome extension that get's your instance domain and check if you are logged in there, then redirects you, but I hit the wall of access token and search page not being automatizable etc. 

If only there where an API to convert these IDs for me, the extension just had to simply redirect me!

**Comment by SoniEx2** [comment]
> Motivation
> 
> Right now, toots shared in other places than mastodon instances are independent, so if I open my friends toot from `mastodon.social` which he is shared in telegram, it opens on `mastodon.social`, and I cannot interact with the toot (reply to it, favorite it, etc...)
> 
> It would be great to detect if I am logged in, in any other instance and redirect to that instance to see the toot automatically.
> 
> My solution to it was a firefox/chrome extension that get's your instance domain and check if you are logged in there, then redirects you, but I hit the wall of access token and search page not being automatizable etc.
> 
> If only there where an API to convert these IDs for me, the extension just had to simply redirect me!

we have protocol handlers but they have issues, see #14187 and such. (see also the referenced issues.)

**Comment by molaeiali** [comment]
I see, we also discussed the possible ways for doing this and each way has it's problems.

Although, I don't think having a public API to do these conversions harm anyone, and maybe opens the door for innovative solutions (like the extension I'm talking about)

If this API becomes a thing, I think browsers can do this although with minimum user interaction, the only thing needed is the domain of the user's instance (it can be stored automatically when user logs in, or managed by user)

**Comment by SoniEx2** [comment]
I think such an API would have to be built with protocol handlers in mind, even without actually registering them. an extension would then be able to use it, but more importantly if the system is already in place it can be used to apply pressure on browser vendors to support it. this would benefit not just mastodon and not just activitypub, but anything web-based and federated.

**Comment by nolanlawson** [comment]
Rather than an API, couldn't Mastodon do this automatically? If someone types this into their URL bar:

    https://hostux.social/web/statuses/99730308154753208

And they're not logged in to `hostux.social`, then why couldn't `hostux.social` just redirect to

    https://mastodon.social/@Mastodon/99730307203414093

...rather than the `hostux.social` login page?

This would be great for people who share toot URLs on their blogs/Twitter/etc. and just naïvely copy the URL from the URL bar. I think it would be easier to make this "just work" than to try to train everyone to click the "…" and then click "copy link," anyway.

**Comment by nightpool** [comment]
@nolanlawson I'm not sure I understand. When I click on https://hostux.social/web/statuses/99730308154753208 I *do* see a redirect to the mastodon.social url you posted. I think we implemented this in 2019? lmk if you're seeing something different though.

**Comment by nolanlawson** [comment]
@nightpool Looks like I was confused because it seems to work this way if you've logged out of a particular instance (i.e. the deeplink takes you to the login screen for `hostux.social` rather than the permalink at `mastodon.social`). It works fine if you've never logged in to the instance.
