### ISSUE TITLE
Lock account option description text is not the same in english and french

### ISSUE THREAD

**Issue by DegrangeM** [mastodon/mastodon#14603]
### Steps to reproduce the problem

Go to option and click on profile ([direct link](https://mastodon.etalab.gouv.fr/settings/profile)).
Look at the text under "Lock Account" / "Verrouiller le compte"

### Expected behaviour

The text should means the same things in english and french.

### Actual behaviour

English:
> Requires you to manually approve followers

French:
> Vous devrez approuver chaque abonné·e et vos statuts ne s’afficheront qu’à vos abonné·e·s
> Wich means : You must approve each followers and your post will only be shown to your follower

### Specifications
v3.1.4

**Comment by ThibG** [comment]
oof, that *is* misleading, the translation corresponds to a very old version of the string

I fixed it. Note that in the future, you can change it yourself via https://crowdin.com/translate/mastodon/

**Comment by vmstan** [comment]
Closed as fixed.
