### ISSUE TITLE
HTML Entities are still encoded in title of webpage preview

### ISSUE THREAD

**Issue by dlowe-net** [mastodon/mastodon#14602]
### Expected behaviour

HTML entities in the page title are displayed in their decoded state.

### Actual behaviour

Page titles in web previews are still encoded.

![image](https://user-images.githubusercontent.com/188363/90630861-c9f60b80-e1ef-11ea-8bd0-6aee939f19e8.png)

### Steps to reproduce the problem

Include a link in a toot to a page with an html entity.

### Specifications

Mastodon v3.2.0

Chrome Version 84.0.4147.125 (Official Build) (64-bit)
on Ubuntu 20

**Comment by MalloryA** [comment]
Both of the duplicate tickets suggested this was related to OpenGraph. The issue actually lies with oEmbed.

Across this and the two duplicates of this issue, three links were provided:

- https://ea.rna.nl/2020/03/04/gossip-trust-and-the-information-revolution/
- https://civic.io/2022/11/21/more-writing-less-words/
- https://terrytao.wordpress.com/career-advice/theres-more-to-mathematics-than-rigour-and-proofs/

Here are the oEmbed endpoints they each link to:

- https://public-api.wordpress.com/oembed/?format=json&url=https%3A%2F%2Fea.rna.nl%2F2020%2F03%2F04%2Fgossip-trust-and-the-information-revolution%2F&for=wpcom-auto-discovery
- https://public-api.wordpress.com/oembed/?format=json&url=https%3A%2F%2Fcivic.io%2F2022%2F11%2F21%2Fmore-writing-less-words%2F&for=wpcom-auto-discovery
- https://public-api.wordpress.com/oembed/?format=json&url=https%3A%2F%2Fterrytao.wordpress.com%2Fcareer-advice%2Ftheres-more-to-mathematics-than-rigour-and-proofs%2F&for=wpcom-auto-discovery

Here are two relevant lines from the first one:

```
"provider_name":"R&amp;A IT Strategy &amp; Architecture",
"title":"Gossip, Trust and the Information Revolution (&#8216;value&#8217; vs. &#8216;values&#8217;)",
```

Nowhere in [the oEmbed spec](https://oembed.com/) does it suggest that any text be interpreted as HTML. Here's what it says about text in general, and about the two fields in particular:

> All text must be UTF-8 encoded.

> provider_name (optional)
> The name of the resource provider.

> title (optional)
> A text title, describing the resource.

Per the specification, Mastodon is functioning correctly. It's WordPress that is behaving incorrectly here.

Somebody has already reported the bug to WordPress: https://core.trac.wordpress.org/ticket/57190
