### ISSUE TITLE
IP address matching in the Moderation > Accounts view

### ISSUE THREAD

**Issue by rodti** [mastodon/mastodon#14671]
### Pitch

One common 'red flag' for spam accounts is the creation of multiple accounts from the same IP address.

Enhance the existing functionality of the 'Most recent IP' column and 'IP' search box in the Accounts view by showing a flag alongside the user's IP when that IP address already exists in the database at the moment of registration.

This makes it very easy for admins/moderators to see 'at a glance' if that account might be one of numerous others created from that IP address.

### Motivation

Spam accounts are incredibly annoying and as well as degrading the user experience on an instance, creates additional work for administrators/moderators to police.

**Comment by rodti** [comment]
I think this suggestion might be superseded by [this](https://github.com/tootsuite/mastodon/issues/16043) one.

**Comment by vmstan** [comment]
Closing as superseded/duplicated.
