### ISSUE TITLE
Mastodon 3.2 major problem with new security mechanism and the token code

### ISSUE THREAD

**Issue by anampses** [mastodon/mastodon#14676]
Ever since updating my instance to 3.2, I have received 4 different reports from users telling me they are unable to regain access to their accounts after logging in from a new computer/new location after a long period of time. 3 of them tell me that the email with the security code never arrives to their inbox even after several attempts and double-checking their spam folder. The other user tells me that even though they received the token security code, it does not seem to work.

Whenever I had users message me with issues regarding two-factor authentication and they were locked out of their accounts, it was easy for me to simply disable 2FA for them to be able to log in again. However, with Mastodon 3.2's newest feature that sends this security code, there is no way for me to disable this or manually confirm it as the admin. The user is effectively locked out if they do not receive this email or the security code is invalid for some reason.

Please, I implore the Masto devs to look into adding some kind of setting in the admin panel to disable or opt out if this new feature, or at least the ability to allow for troubleshooting this login issue for users without resorting to changing their email address for another attempt at security verification.

**Comment by Gargron** [comment]
In my experience when a security code does not arrive it means the e-mail delivery service has blacklisted the e-mail address for one or another reason. For example, if a user reports an e-mail as spam, the delivery service is notified of this and prevents any further e-mails from being sent to that address. At least this is how it worked with Mailgun and SparkPost which I have used. In SparkPost you can remove an address from the "suppression list" in the UI, then e-mails get sent again.

People tend to re-use passwords between sites and get it leaked when another site has a breach. The amount of account hijackings on the fediverse has gone down to essentially zero since introducing this security measure. So I believe an opt-out of this feature would be intentionally weakening security. In reality, this feature simply highlights problems that have already existed -- the user has accidentally or intentionally reported a Mastodon e-mail as spam and isn't getting any new e-mails.

> The other user tells me that even though they received the token security code, it does not seem to work.

This is more suspicious of being a bug but I'd like more details on the circumstances of that code not working.

**Comment by Gargron** [comment]
Please let me know if you can check the 3 e-mail addresses for being on such a blacklist with your e-mail provider and if it's indeed the case for all of them.

**Comment by anampses** [comment]
I checked with the latest report I received Wednesday with an user not receiving the security code at their hotmail.com email address. I use Mailgun and queried the suppression list from its UI, but it says "no suppressions associated with your search." I checked the logs and it shows the email was successfully sent to the hotmail address despite being reported from the user that it was not received on their end.

Second most recent user reporting the same issue of not receiving the email with the security code token uses a "protonmail.com" address, another uses "outlook.com", and the third user uses "ezweb.ne.jp". It doesn't appear as though the 3 email addresses are on any blacklist... 

The fourth report regarding the code not working at all is a user with a "gmail.com" address. I'll try and see if I can find more information to provide you with this one.

I totally understand providing an opt-out of this feature would weaken security, but I still think at minimum there needs to be some way to resolve this from the admin panel. I plead you to consider some functionality to address this in the next update.

**Comment by chendo** [comment]
I'd also like an option to disable this feature for the time being as this is causing a lot of support issues for us.

**Comment by anampses** [comment]
Just in the last week I have gotten two more reports of the security code e-mail not reaching the user. The latest report is troubling... I have a user that did not receive the token security code to their outlook email address, so I changed it to another gmail address of theirs. They received the email to confirm the new gmail address change, but when attempting to login again it fails to deliver the security code to the same address.

Please push out an update ASAP to disable the security code, or at least some way to resolve for a particular user experiencing this problem. Like chendo, this is causing too much support issues on our end.

**Comment by Gargron** [comment]
If you want to disable this function right now without waiting for a new release, edit this line: https://github.com/tootsuite/mastodon/blob/master/app/models/user.rb#L175 to say `false`

**Comment by anampses** [comment]
Is this function available from the admin panel yet with the newest release? 

https://www.reddit.com/r/Mastodon/comments/k34lss/not_receiving_confirmation_instructions_on_reset/ge2vjib/

**Comment by anampses** [comment]
not sure if v3.3.0 undid the manual fix to edit the line as “false”, but I am suddenly getting reports again recently from users experiencing issues with the security token. One report today that they are not receiving the security code at all to their gmail, and another user that *did* receive it to their gmail, but the code appears to be completely invalid.

https://i.gyazo.com/e3b05bee81755613c1e0f6dfc60fca31.png

is there any way to completely disable this feature? I would really like another button next to the other tools for user moderation. Next to WARN, SENSITIVE, LIMIT, and SUSPEND, another option for CONFIRM. 

Without some confirm tool to bypass the security code, I am having trouble with helping users regain access that I know for sure is who they say they are.

**Comment by kushaldas** [comment]
I am having a similar issue with `3.3.0` release. The user is getting all other emails (say password reset email), but not the security token to login after a long time. Any temporary solution?

**Comment by Gargron** [comment]
suspicious_sign_in?

**Comment by kushaldas** [comment]
> suspicious_sign_in?

Thank you, I just now figured that and works.

**Comment by anampses** [comment]
> If you want to disable this function right now without waiting for a new release, edit this line: https://github.com/tootsuite/mastodon/blob/master/app/models/user.rb#L175 to say `false` (and restart the web process)

has the line for the newest Mastodon release changed in order to disable this function? I am receiving several reports again from users saying they are not getting the security code after updating to v3.4.0

**Comment by hecanjog** [comment]
In case anyone else is just trying to recover one account manually the security code is stored in plain text in `users.sign_in_token`.

**Comment by Gargron** [comment]
Since 771c9d4ba87a388dc306c58139d11bf510680c98 you can disable the mechanism for specific accounts
