### ISSUE TITLE
Import Job failed every Day

### ISSUE THREAD

**Issue by rhizoet** [mastodon/mastodon#14672]
### Expected behaviour

The Import Job should done without any Errors

### Actual behaviour

We get an Error like:

`Aug 27 07:26:26 hostname bundle[24300]: 2020-08-27T05:26:26.401Z pid=24300 tid=gt7thud68 WARN: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/chewy-5.1.0/lib/chewy/type/import.rb:88:in 'import!'`
`Aug 27 07:26:26 hostname bundle[24300]: /home/mastodon/live/lib/chewy/strategy/custom_sidekiq.rb:13:in 'perform'`
`Aug 27 07:26:26 hostname bundle[24300]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:196:in 'execute_job'`
`Aug 27 07:26:26 hostname bundle[24300]: 2020-08-27T05:26:26.393Z pid=24300 tid=orel4syso class=Chewy::Strategy::CustomSidekiq::Worker jid=ed77f4c96d8adec5aca8b308 elapsed=0.339 INFO: fail`
`Aug 27 07:26:26 hostname bundle[24300]: 2020-08-27T05:26:26.407Z pid=24300 tid=orel4syso WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"pull","class":"Chewy::Strategy::CustomSidekiq::Worker","args":["AccountsIndex::Account",[66433]],"jid":"ed77f4c96d8adec5aca8b308","created_at":1598505883.2972226,"enqueued_at":1598505986.033347,"error_message":"Import failed for 'AccountsIndex::Account' with:\n    Index errors:\n      '{\"type\"=>\"cluster_block_exception\", \"reason\"=>\"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];\"}'\n        on 1 documents: [\"66433\"]\n","error_class":"Chewy::ImportFailed","failed_at":1598505883.336423,"retry_count":1,"retried_at":1598505913.5159628},"jobstr":"{\"retry\":true,\"queue\":\"pull\",\"class\":\"Chewy::Strategy::CustomSidekiq::Worker\",\"args\":[\"AccountsIndex::Account\",[66433]],\"jid\":\"ed77f4c96d8adec5aca8b308\",\"created_at\":1598505883.2972226,\"enqueued_at\":1598505986.033347,\"error_message\":\"Import failed for 'AccountsIndex::Account' with:\\n    Index errors:\\n      '{\\\"type\\\"=>\\\"cluster_block_exception\\\", \\\"reason\\\"=>\\\"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];\\\"}'\\n        on 1 documents: [\\\"66433\\\"]\\n\",\"error_class\":\"Chewy::ImportFailed\",\"failed_at\":1598505883.336423,\"retry_count\":1,\"retried_at\":1598505913.5159628}"}`
`Aug 27 07:26:26 hostname bundle[24300]: 2020-08-27T05:26:26.407Z pid=24300 tid=orel4syso WARN: Chewy::ImportFailed: Import failed for 'AccountsIndex::Account' with:`
`Aug 27 07:26:26 hostname bundle[24300]:     Index errors:`
`Aug 27 07:26:26 hostname bundle[24300]:       '{"type"=>"cluster_block_exception", "reason"=>"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"}'`
`Aug 27 07:26:26 hostname bundle[24300]:         on 1 documents: ["66433"]`

### Steps to reproduce the problem

It's in the syslog and we don't know, if it's a "real" problem or a bug. 

### Specifications

Mastodon v3.2.0

Thanks in advance for your help.

**Comment by Gargron** [comment]
> FORBIDDEN/12/index read-only / allow delete (api)

Your ElasticSearch index is in read-only state. This can happen because of a crash or running out of disk space.

**Comment by sable-starflower** [comment]
This happened to me and running this command fixed it (after freeing up disk space):

```
curl -X PUT "localhost:9200/_all/_settings" -H 'Content-Type: application/json' -d'{ "index.blocks.read_only_allow_delete" : false } }'
```
