### ISSUE TITLE
Permission for moderators to create announcements

### ISSUE THREAD

**Issue by hmilles** [mastodon/mastodon#14685]
Currently, only admins can create announcements. There should be an option for moderators too.

I'm part of the admin team of my university's server, it would be really helpful if moderators (e.g. some student council members for this instance) could post announcements.
It would be generally useful for servers that don't wanna give admin rights to a that large group of people, but access to the feature would be helpful for them.

**Comment by vmstan** [comment]
User roles can now be granted this permission.
