### ISSUE TITLE
New Permission: "Sub-Administrator"

### ISSUE THREAD

**Issue by Phroneris** [mastodon/mastodon#14725]
### Pitch

A new user role, "**Sub-Administrator**", allows specified users to do everything that the administrator role we know can do from web UI such as modifying site settings, creating announcements, managing emojis and any moderation actions.
The only thing an owner (true administrator) does but the sub-admins *don't* is the core engineering like preparing requisite machine and source codes, installing and updating Mastodon, setting up and disclose one's instance.

![permission_diagram](https://user-images.githubusercontent.com/9891867/92136302-d496de80-ee46-11ea-8abc-35165ac82316.png)

### Motivation

- Currently, general users can't tell whether an "Admin" badge holder is the owner/originator of the server or just a staff to whom the owner assigned permission beyond moderators.
- Currently, when the owner wants to have some reliable users maintain settings/CSS/emojis/announcements, the only solution is to mass-produce administrators because existing moderator permission is not enough.
- Of cause the above tasks are NOT moderation, so it's not so suitable to add control of them to moderator features.
- It's my feeling though, the "Admin" shouldn't be able to be many but should be few (one or at most two, for the person oneself and kinda official announcement account) to show the server owner exclusively.
- This could solve some existing suggestions related to permission (e.g. #13077) inclusively.

### Notes

- The name can be something else :wink:
  - "**Vice-Administrator**", "**Web Contributor**", "**Core Staff**", "**Maintainer**", "**Secretary**", ...
  - Except "Manager". I think moderation is also a kind of management so this naming isn't enough exclusive.
- Another idea: Instead of that, sub-admins are allowed everything only within `Administration` menu just like moderators can work only within `Moderation`.
  ![menu_mod_admin](https://user-images.githubusercontent.com/9891867/92125513-14a39480-ee3a-11ea-8833-286eb4019fab.png)
  Then, they become parallel roles.
  - In this scenario, if the owner want to give full permission to a user, the account shall have two badges.
- *Another* idea: Instead of that, add a new highest user status "**Owner**" which can be given to only one or few account(s) and has full control.

**Comment by SuperSandro2000** [comment]
How about Owner, Administrator and Moderator? Those are common roles in other software, too.

**Comment by trwnh** [comment]
I don't think there's an implication that admins are also sysadmins... this would effectively be a visual flair only, right?

**Comment by Phroneris** [comment]
I suppose that the Owner > Admin > Mod idea has a disadvantage of exclusiveness of naming because the name "Administrator" seems like the top of roles for one who doesn't know there is an "Owner" role separately.
That's why my main idea is Admin > Sub > Mod style.

@SuperSandro2000
Thanks, I didn't consider whether multiple roles can be assigned to a single user visually and technically.
If the parallel roles are realized, I imagine the UI of permission assignment for each user could be like this:
![permission_parallel_ui](https://user-images.githubusercontent.com/9891867/92241311-fe104280-eef8-11ea-9cba-88246a680352.png)
... or a link to another page to set permissions (safer).
I agree on the point that things will be possibly confusing then.

@trwnh
"Sysadmin"!! It's a vocabulary I couldn't devise. Thanks.
In my main suggestion, the "Administrator" and "Sub-Administrator" are equal on the web UI except their badge displays.
So they differ only in appearance on the web, as you say, but I think that this semantic difference is necessary as long as Mastodon shows user permission on our profile pages.
("Semantic" is another vocabulary coming late to my brain)

**Comment by Phroneris** [comment]
@SuperSandro2000 Thanks for more knowledge.
Then let us return from a digression.
Naming is a secondary matter. UI is below it. Primary is the raison d'être for this feature.

> Why? Makes no sense.

The reason has been shown as a "Motivation" passage.
Additionally, to begin with, why does Mastodon have to show permission badges?
I assume that one of the purposes is to perform smoother communication related to moderation and server management.
And then,

> - Currently, general users can't tell whether an "Admin" badge holder is the owner/originator of the server or just a staff to whom the owner assigned permission beyond moderators.

I don't think the present circumstance is smooth enough.
THIS is confusing.

----

> I think that this semantic difference is necessary

My "necessary" might be overstatement, but this feature must be of worth.

**Comment by Phroneris** [comment]
In addition and addition, another reason for my suggestion is a respect for the owner/originator.

I live in [gensokyo.town](https://gensokyo.town) with an "Admin" badge but I'm not the owner of the server.
That's because:

> - Currently, when the owner wants to have some reliable users maintain settings/CSS/emojis/announcements, the only solution is to mass-produce administrators because existing moderator permission is not enough.

I feel mean for holding the same badge as the owner does despite I'm just a staff (I'm pretty sorry for selecting this inadequate English, "staff", but I couldn't find any better words else).
I wish that the owner would have a unique badge for respect for him/her.

**Comment by ryliejamesthomas** [comment]
I don't think these divisions account for situations where a person is paying someone to be the syadmin, like say people with Mastodon instances hosted on masto.host. They are still the owner they just don't manage the backend, and the sysadmin doesn't have an account on the instance.

And I agree with trwnh that 'I don't think there's an implication that admins are also sysadmins'.

**Comment by SuperSandro2000** [comment]
> I assume that one of the purposes is to perform smoother communication related to moderation and server management.

It won't get smoother if there are 4 or 5 or 6 roles which only have marginal differences and confuse people.

> Currently, general users can't tell whether an "Admin" badge holder is the owner/originator of the server or just a staff to whom the owner assigned permission beyond moderators.

Does that matter to an average user? No, it does not. We have a bio for such detailed information. 

> another reason for my suggestion is a respect for the owner/originator.

You should treat other people with respect no matter if they are the owner, admin, mod or just a regular user.

Why does it matter if a user has access to the backend? It doesn't. There is no reason for an end user to know and if the person wants to spread that info with the world we have a bio.

**Comment by Phroneris** [comment]
@ryliejamesthomas Ahhh I understand trwnh's first sentence now thanks to your comment.
I forgot the existence of Mastodon hosters and their clients.
Please regard my caption and illustration as things describing just the most basic use case.
I, either, don't think that Mastodon requires admins or sysadmins to be the other.
Then, the name of the top-level role must not be "Sysadmin" at least.

@SuperSandro2000
> You should treat other people with respect no matter if they are the owner, admin, mod or just a regular user.

Ignoratio elenchi aka straw person. Bye.

**Comment by Kjwon15** [comment]
How about add sysop badge for visual only on mastodon web ui and remain administrator as it for now

**Comment by Phroneris** [comment]
@Kjwon15 Thanks for a new vocabulary. Does your idea mean "Admin > Sysop > Mod" style?
IMAO sys-* names sound a little too technical like the sysadmin matter above, though...

**Comment by SuperSandro2000** [comment]
> "Admin > Sysop > Mod"

This is wrong. An admin on Mastodon does not need to have system access which means you have complete control over everything.

**Comment by Gargron** [comment]
Fixed by #18641
