### ISSUE TITLE
The contact e-mail in /about/more doesn't get abbreviated despite its overflow/text-overflow CSS properties

### ISSUE THREAD

**Issue by Phroneris** [mastodon/mastodon#14723]
![contact-widget_mail](https://user-images.githubusercontent.com/9891867/91998320-0724d680-ed76-11ea-8afa-651aff45bfbc.png)

When the screen is very narrow (but >415px) ...

### Expected behaviour

- The contact e-mail address is abbreviated as like `staff@mastod...`
- The /about/more page doesn't need horizontal scroll

### Actual behaviour

- The contact e-mail address is rendered fully
- The /about/more page have horizontal scroll to display it

### Steps to reproduce the problem

1. Go to https://mastodon.social/about/more on your PC
1. Drag the side edge of your browser and make it very narrow (but wider than 415px)
1. See "CONTACT:" field at the top right of the page

### Specifications

- OS: Windows 7 Professional 64-bit
- Browser: Chrome 84.0.4147.135
- Mastodon Server: mastodon.social, and many others of v3.2.0

### Notes

- On Chrome DevTools, I confirmed this `.contact-widget>a` element has `overflow: hidden;` and `text-overflow: ellipsis;` properties
- When the screen width is 415px or below, Mastodon switches to mobile display mode and then this issue doesn't occur

**Comment by ThibG** [comment]
`.contact-widget > a` has `display: inline-block` which causes this.
To solve this, I believe we could change it to `display: block` without causing another issue.

**Comment by Phroneris** [comment]
https://github.com/mastodon/mastodon/pull/18348#issuecomment-1308886498

> It seems that the v4 UI renewal gets rid of the root issue.
