### ISSUE TITLE
Scrolling down my timeline on Chromium-based browsers causes the page to error out

### ISSUE THREAD

**Issue by Mintww** [mastodon/mastodon#14731]
### Expected behaviour

It continues to work and to show me posts

### Actual behaviour

The page is replaced by a red on black screen stating "Due to a bug in our code or a browser compatibility issue, this page could not be displayed correctly.

Try refreshing the page. If that does not help, you may still be able to use Mastodon through a different browser or native app."

### Steps to reproduce the problem

Scroll down the home timeline on a browser such as Brave, Opera, etc.
While I am using an unofficial instance, I have seen this happen on multiple different 3.2.0 instances.

### Specifications

Mastodon v3.2.0, Brave Version 1.13.82 Chromium: 85.0.4183.83 (Official Build) (64-bit), Mac OS 10.14.6

### Stacktrace

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ls (https://fandom.ink/packs/js/common-39e9643818a17b71163e.js:2:1020531)
    at pu (https://fandom.ink/packs/js/common-39e9643818a17b71163e.js:2:1033720)
    at https://fandom.ink/packs/js/common-39e9643818a17b71163e.js:2:1054420
    at Ha (https://fandom.ink/packs/js/common-39e9643818a17b71163e.js:2:978886)
    at du (https://fandom.ink/packs/js/common-39e9643818a17b71163e.js:2:1031580)
    at Zs (https://fandom.ink/packs/js/common-39e9643818a17b71163e.js:2:1027734)
    at https://fandom.ink/packs/js/common-39e9643818a17b71163e.js:2:979177
    at https://fandom.ink/packs/js/common-39e9643818a17b71163e.js:2:1054420
    at Ha (https://fandom.ink/packs/js/common-39e9643818a17b71163e.js:2:978886)
    at Va (https://fandom.ink/packs/js/common-39e9643818a17b71163e.js:2:979122)

Ki (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5411:106)
Mi (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6363:21)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2816:9)
Jj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6204:2)
Kj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5895:4)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2851:16)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2816:9)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2846:6)

**Comment by ThibG** [comment]
Are you using extensions? Are you using automatic translation of the page?

**Comment by Mintww** [comment]
Oh oops, it's definitely the fault of a conflict with a userscript (linkify plus plus). Still, I haven't run into any other site, infinite scrolling or otherwise, that caused issues with it? There is, however, an issue open on their end, ( https://github.com/eight04/linkify-plus-plus/issues/30 )

Until it's fixed, on whichever end ends up fixing it, I can simply add excludes to the script on my end for all instances I have accounts on. Apologies for not checking more thoroughly.

**Comment by ThibG** [comment]
This happens because the extension messes with the page's DOM in ways which consume React. There is probably not much we can do on our end, but maybe there are ways to design the React part in ways that are more friendly to such extensions.
