### ISSUE TITLE
Some custom emoji not rendered in display name

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#14773]
Custom emoji are not rendered in certain Pleroma user display names.

Example: https://pl.snootbooping.date/users/pie

Expected behavior: custom emoji render properly

Actual behavior: only shortcodes are rendered

**Comment by Gargron** [comment]
Probably no spaces between colons. Mastodon doesn't support rendering shortcodes without spaces between them [because there was a preference for being able to share IPv6 addresses without issues](https://github.com/tootsuite/mastodon/issues/5044#issuecomment-331529570).

**Comment by trwnh** [comment]
gonna close this as inactionable i guess
