### ISSUE TITLE
Support Azure Storage for Files

### ISSUE THREAD

**Issue by paulirwin** [mastodon/mastodon#14810]
### Pitch

For Mastodon instances hosted in Azure, it would be convenient to support Azure Storage for file storage, equivalent to the existing S3 support. Ideally "Azure Storage" would be an option in the initial configuration wizard during setup as well, prompting you for the configuration values.

### Motivation

Mastodon users with instances in Azure would be able to keep all of their data together in one service.

### Additional Notes

* [Azure Storage Blob Client for Ruby](https://github.com/azure/azure-storage-ruby/tree/master/blob) (MIT licensed)
* Configuration environment variables: AZURE_STORAGE_ACCOUNT and AZURE_STORAGE_ACCESS_KEY

I suppose I'm posting this to gauge interest; I may also be able to help contribute towards implementing it. At a minimum, I can help be a tester of this functionality.

**Comment by rgroothuijsen** [comment]
Mastodon relies on Paperclip for handling storage, which by itself only supports S3. Third-party Azure storage drivers are available, though I have no experience with them.

**Comment by rickersilva** [comment]
Pauli, do you know any resource or step by step guide to start configuring an instance in Aziure?

**Comment by sylus** [comment]
I wonder if instead could use Azure Files (NFS) as a volume mount and would achieve roughly the same effect

**Comment by tomresing** [comment]
With the great twitter migration happening, this seems like a fix that could help increase the number of servers for the growing masses of people joining the fediverse everyday!

**Comment by tomresing** [comment]
> I decided to go on GCP, merely for costs. I’ll be hiring something around 100 dollars per month among instance, storage and db.

How did you solve the AWS dependency on GCP? I'm curious.

**Comment by nightpool** [comment]
Paperclip will support any storage backend with an S3 compatible API. Most providers (including Google Cloud) support this type of API natively. Personally, I use Digital Ocean, because they're cheap. For Azure specifically, it seems like it requires a third party program: https://devblogs.microsoft.com/cse/2016/05/22/access-azure-blob-storage-from-your-apps-using-s3-api/

**Comment by paulirwin** [comment]
@nightpool Paperclip is [deprecated since 2018](https://thoughtbot.com/blog/closing-the-trombone) and they recommend moving to ActiveStorage, which does appear to support Azure Storage (although I have no experience with using ActiveStorage yet). Perhaps moving to ActiveStorage instead could allow for native integration, and this issue could be reopened until then?

**Comment by tomresing** [comment]
I agree. Paperclip recommends moving. They even provide a detailed migration guide. https://github.com/thoughtbot/paperclip/blob/master/MIGRATING.md

**Comment by winsmith** [comment]
Just adding: I'm hosting a small instance on azure using the provided Helm charts and azure blob storage would be amazing!

**Comment by juju2143** [comment]
Paperclip also suggests using this actively maintained fork if you don't want to migrate just yet: https://github.com/kreeti/kt-paperclip

As for Azure storage, there's a third party provider that should work right there: https://github.com/supportify/paperclip-azure
