### ISSUE TITLE
Change confusing word choice for moderation actions ( suspend not meaning temporary in mastodon )

### ISSUE THREAD

**Issue by clarjon1** [mastodon/mastodon#14815]
# Improving wording for moderation actions

Currently, this is how the dropdown for taking actions appears: 
![image](https://user-images.githubusercontent.com/627845/93532460-1592f680-f90f-11ea-9a29-764800586e1a.png)
the last option, to terminate an account, can cause confusion despite its clarification because the word "Suspend" means a temporary action. This can result in an admin being unsure which part of the description is incorrect -- Suspend, meaning a temporary stop, or the rest of the description.

I propose changing the options to the following for better clarity:

```
Do Nothing
Suspend and Disable Login
Silence
Terminate and irreversibly delete account data
```

### Motivation

I think that all moderators and admins would benefit from having clear, accurate wording for the actions they are taking. This would prevent situations where a moderator, being told to "Just suspend the account until we talk to the user" from a staff member who forgot that in mastodon's current use case suspend means terminate and not to temporarily prevent login/posting, ends up completely removing a community member from their instance.

**Comment by Cassolotl** [comment]
I agree with this. To me (UK English), to "suspend" someone is to temporarily revoke their access to something, with the understanding that they'll return after a specified amount of time. If someone was never allowed back I'd call that a ban.

**Comment by ThibG** [comment]
Note that suspension is currently being reworked to actually be reversible, with according wording (this is already in `master` except for the federation part, meaning that if you suspend someone on your instance, it'll locally behave in a similar way as before, except you are able to undo the suspension, but remote instances will see no change to the account, which may lead other people think that no action has been taken).

**Comment by Nicedude-git** [comment]
"Suspend" is a twitter euphemism for "banning permanently", but in reality the meaning of suspensión implies something temporary in any language. According to Oxford:

Suspend: temporarily prevent from continuing or being in force or effect.

Please let's not replicate twitter's wordplay and torture of words in Mastodon.

**Comment by ThibG** [comment]
As I said in my previous comment, the current development version of Mastodon has changed the way suspension work to make them reversible. This would not necessarily imply this is a temporary measure, though, but it would be possible to use it as such (instead of the situation with current releases which is to wipe everything out immediately).

**Comment by Nicedude-git** [comment]
> As I said in my previous comment, the current development version of Mastodon has changed the way suspension work to make them reversible. This would not necessarily imply this is a temporary measure, though, but it would be possible to use it as such (instead of the situation with current releases which is to wipe everything out immediately).

Good. I only hope the difference between temporary and perrmanent is made clear using appropriate words.
