### ISSUE TITLE
mastodon-streaming won't start

### ISSUE THREAD

**Issue by 4nanook** [mastodon/mastodon#14866]
mastadon-streaming won't start, build of module node_modules/@clusterws/cws failed
### Expected behaviour
Expected it to start up and run.

### Actual behaviour
/usr/bin/node ./streaming
/misc/www/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:18
        throw err;
        ^

Error: Cannot find module '../dist/bindings/cws_linux_83'
Require stack:
- /misc/www/mastodon/live/node_modules/@clusterws/cws/dist/shared.js
- /misc/www/mastodon/live/node_modules/@clusterws/cws/dist/server.js
- /misc/www/mastodon/live/node_modules/@clusterws/cws/dist/client.js
- /misc/www/mastodon/live/node_modules/@clusterws/cws/dist/index.js
- /misc/www/mastodon/live/streaming/index.js check './node_modules/@clusterws/cws/build_log.txt' for post install build logs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /misc/www/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:14:16
    at Object.<anonymous> (/misc/www/mastodon/live/node_modules/@clusterws/cws/dist/shared.js:20:3)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/misc/www/mastodon/live/node_modules/@clusterws/cws/dist/shared.js',
    '/misc/www/mastodon/live/node_modules/@clusterws/cws/dist/server.js',
    '/misc/www/mastodon/live/node_modules/@clusterws/cws/dist/client.js',
    '/misc/www/mastodon/live/node_modules/@clusterws/cws/dist/index.js',
    '/misc/www/mastodon/live/streaming/index.js'
  ]
}

### Steps to reproduce the problem
Installed on Ubuntu 20.04 and tried to start all the services.  Everything but mastodon-streaming worked.

### Specifications

I followed these instructions: https://docs.joinmastodon.org/admin/install/ I do not know enough about github to know how to get the version of commit hash.

Backend issue with mastodon-streaming but I'm also using Ubuntu 20.04 and FIrefox 80.0.1

**Comment by 4nanook** [comment]
[build_log.txt](https://github.com/tootsuite/mastodon/files/5287861/build_log.txt)
I'm attaching the build log above so you can see what failed.

**Comment by 4nanook** [comment]
I was able to get it working by manually installing modules build log said were missing using npm.

**Comment by 4nanook** [comment]
Well it's back to broken in the same state.  I tried to create an admin account and it failed, so I re-installed.  When I first installed, I had some problems with https sites because it was not able to find my site certificate.  So I added environment so it could find them.  And now it's back to failing exactly the same way.

**Comment by mstdn** [comment]
I'm not sure but perhaps 20.04 makes things difficult? I have never these issues on 18.04. Are you using the correct version of npm? setup_12.x?

**Comment by 4nanook** [comment]
20.04 comes with npm --version
6.14.8


-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by 4nanook** [comment]
Ok, still no fix.

**Comment by ThibG** [comment]
> 20.04 comes with npm --version
> 6.14.8

This is rather curious, according to https://packages.ubuntu.com/focal/nodejs it should be nodejs 10.19.0 and according to the `build_log.txt` in your earlier indicates v14.12.0.

> I do not know enough about github to know how to get the version of commit hash.

What's the result of `git log --oneline -n 1`?

**Comment by nightpool** [comment]
the streaming server doesn't work with node 14 currently (npm version !=
node version). Please downgrade Node to v10 or v12.

**Comment by 4nanook** [comment]
Ok, now I remember why I have node v14 on this machine and that is because friendica when I installed it, the instructions said to delete the system nodejs and install from the website which is what I did.  Basically it involved installing a PPA that made the newer version available.

To answer the question about git log --online -n 1?
93dd413a4 (HEAD, tag: v3.2.0) Bump version to 3.2.0 (#14395)

I have existing people using friendica, so I don't want to break it by installing an earlier nodejs,   I also have a diaspora installed with this version and don't want to risk breaking it though it's not seeing much traffic yet.  Probably the easiest solution is to put
together another machine.

**Comment by Gargron** [comment]
You can use Mastodon's Docker image from Docker Hub

**Comment by 4nanook** [comment]
I am not familiar with docker but I am familiar with kvm/qemu virtual machines.

**Comment by mstdn** [comment]
So.. it's solved then?

**Comment by 4nanook** [comment]
More like on hold, either I'll wait untii 20.04 hits end of life and
you fix node 14 incompatabilities or I'll put together another machine.
Neither is going to happen instantly.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by SuperSandro2000** [comment]
You can get Node 12 for Ubuntu 20.04 here https://github.com/nodesource/distributions

**Comment by 4nanook** [comment]
As I previously stated, I have node 14 because that's what friendica
wanted, and I don't really want to dive into the complexities of docker,
so this while either wait until I set up another machine or mastodon brings
itself up to the modern world.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by 4nanook** [comment]
Since otherwise this will have to wait until I put a new server together, can anyone point me to instructions for installing Mastodon
using docker on Ubuntu 20.04 so I can work around the node version issue?  I am completely 100% unfamiliar with docker.

**Comment by ThisIsMissEm** [comment]
This can probably be closed given it's a Node.js 12 vs 14 issue, and Mastodon now requires Node.js >= 14
