### ISSUE TITLE
Visible warning for excessively out-of-date server

### ISSUE THREAD

**Issue by riking** [mastodon/mastodon#1487]
When an update has not been performed for 6 months (a safeguard against version checks failing and/or absent admins), a _user_-visible warning should be shown in the interface.

> :warning: The server software has not been updated in 6 months. Please ask your `[administrator](/about/more)` to update the software.

Of course, admin-visible warnings would be implemented for being 1 version behind, to give them time to check & update.

It's best to get this kind of code in early, _before_ security issues get found.

* * * *

#### Implementation Notes

```ruby
last_updated = Time.parse `git log HEAD -n1 --format=tformat:%cI`
# => 2017-04-07 23:16:46 -0400
last_commit = `git log HEAD -n1 --format=tformat:%H`.rstrip!
# => "541c538f9bbd00028b388468b2753b1136f3d5b3"
if last_updated < 6.months.ago
  ...
end
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
  Related: #1401, #409 
  Related: Notices from the admin in the Compose view (multi-column layout) or Getting Started (single-column layout) - this should appear in the same layout slot

**Comment by lutoma** [comment]
I don't think hard-coding `git log` is the best idea since Mastodon might also be installed other ways in the future (os package manager, non-git tarballs, …). I like the general idea though.

**Comment by expenses** [comment]
@lutoma

Agreed. The Masterdon instance should probably have the last updated timestamp stored somewhere.

**Comment by michaeljdeeb** [comment]
How are database migrations handled now? Does the script check for features/existing columns or a version stored somewhere? 

The [Releases API](https://developer.github.com/v3/repos/releases/#get-the-latest-release) could be used to find out the latest version, but there's very little metadata to do additional filtering for say, security releases, that should trigger a louder, more urgent upgrade warning. Unless something is affixed to `tag_name` or searched for in `body`.

**Comment by shleeable** [comment]
@vmstan please close.

**Comment by vmstan** [comment]
Mastodon 4.2 includes admin notification of critical updates.
