### ISSUE TITLE
Feature request: Short user info on hover

### ISSUE THREAD

**Issue by joenepraat** [mastodon/mastodon#14918]
### Pitch and motivation

I wanted to ask this for a while and everytime I forgot to ask. More and more I miss the very usable hover on username/avatar, like on most corporate social silo's. I really don't understand why Mastodon does not have this.

So please can the Mastodon devs add this? I suppose the bio and a follow button (and maybe followers/following count) would be enough. It makes sure you don't have to go everytime to a profile to see who this user is (and go back again). It also makes it much more quicker to follow someone.

Would be great new feature for the next Mastodon version.

Thanks in advance!

**Comment by mstdn** [comment]
Yes, yes, yes.

**Comment by mashirozx** [comment]
Great idea

**Comment by elenners** [comment]
Pleroma and Misskey both do this, so I imagine someone with the know-how may be able to port it over.

**Comment by Gargron** [comment]
I had a branch with tooltips and was planning to eventually add this. I need to check the state of that branch...

**Comment by realpixelcode** [comment]
I love thos preview tooltips! That's a use case just like on Wikipedia where you don't want to switch between different articles just to get some main information.

**Comment by koyuawsmbrtn** [comment]
Now with the redesigned profile cards can this feature be revisited?

**Comment by mashirozx** [comment]
2 years passed, has this branch been forgotten? https://github.com/mastodon/mastodon/tree/feature-rich-tooltips

**Comment by jesseskinner** [comment]
+1. Also, would this be the kind of thing a random newbie contributor could consider implementing and adding a pull request for, or would that be stepping on toes? Asking for a friend.

**Comment by Fordi** [comment]
+1

**Comment by koyuawsmbrtn** [comment]
> +1. Also, would this be the kind of thing a random newbie contributor could consider implementing and adding a pull request for, or would that be stepping on toes? Asking for a friend.

It'd be nice to contribute if you want to. Issues get closed faster if a Pull Request got merged.

**Comment by naught101** [comment]
Related - (extra) short bio field request: #21277

**Comment by robsonsobral** [comment]
How can we help, @Gargron ?

---

Some samples.

From Twitter:
![image](https://user-images.githubusercontent.com/931642/204100228-cfd903dd-64ff-4f53-972d-54059ecae330.png)

From Instagram:
![image](https://user-images.githubusercontent.com/931642/204100240-5adc1af1-19e1-46b3-9d57-7061fc662b4f.png)

From Github:
![image](https://user-images.githubusercontent.com/931642/204100251-6d57a018-b875-450f-ac5e-3e3e09bfe213.png)

**Comment by elenners** [comment]
> How can we help, @Gargron ?
> 
> Some samples.

![Screenshot 2022-11-26 110521](https://user-images.githubusercontent.com/63966511/204100462-28011287-81e3-4a66-9ae5-a9efeadeed25.png)
Misskey

**Comment by goliv04053** [comment]
How it's the development of this feature?

**Comment by robsonsobral** [comment]
I can finish the @Gargron implementation, but I'm not the right person to rebase a 3302 commits old branch.

**Comment by amydevs** [comment]
![image](https://user-images.githubusercontent.com/50583248/204111882-436ef612-0803-48e6-a2f8-74f2c009ac86.png)
i tried using the existing directory/account-card component and it seems to work pretty well. i'm just not really sure how to structure the code to implement these changes though, like should i just copy the account-card component into a new feature? or should i make it a global component? or should i make a separate similar component that calls dispatch(fetchRelationships()) as soon as the component is mounted? The last option seems the most straightforward, though i'm not sure making the account status hover a whole new feature in the project structure makes sense...

**Comment by robsonsobral** [comment]
Which changes, @amydevs ? What else need to be added? It looks enough for me.

**Comment by amydevs** [comment]
> Which changes, @amydevs ? What else need to be added? It looks enough for me.

1. how to structure the code so that the implementation isnt hacked-together like how it currently is
2. figuring out where to call dispatch(fetchRelationships()) to redux in the appropriate file
3. adding a delay before triggering the hover effect like so it doesn't popup right away on mouseover
4. animations that fade the card in and out
5. taking note of the X and Y positions of the mouse on hover and making the card appear just under that instead of aligned to the left side of the component

**Comment by eishiya** [comment]
If possible, I'd like to see the option to disable this feature in the appearance settings. While it's useful for many users, I found myself disliking it on Twitter because I'd hover by mistake much more often than I would on purpose, and the info box appearing unexpectedly was very distracting for me (I don't deal well with unexpected animation in general). I'd rather have to visit the user's profile to see this information than deal with that again.

If it's not possible to add such an option, then please give it an ID or some class that I can target with custom CSS to hide it, if it doesn't have one already.

**Comment by naught101** [comment]
@eishiya perhaps also a customisable hover delay time?

**Comment by joenepraat** [comment]
@ClearlyClaire @Gargron Unfortunately this popular feature request and IMO necessary feature, is still not implemented. It's even on the roadmap, although still under exploring (MAS-43 - On-hover information cards for users). 

**I like to hereby ask if it's possible to give this much requested feature a higher priority?**

**Comment by shaedrich** [comment]
> I suppose the bio and a follow button (and maybe followers/following count)

Additional to this, there could also be the user metadata fields (#27978) and/or the featured hashtags

**Comment by shleeable** [comment]
Elk does this

![image](https://github.com/mastodon/mastodon/assets/17537000/830a11dd-d4c2-4bb8-8280-7bc2b79f2aab)

**Comment by joenepraat** [comment]
🎉
