### ISSUE TITLE
Navigation links on simple interface not functional on Safari

### ISSUE THREAD

**Issue by alcapurrias** [mastodon/mastodon#14916]
See attached screenshot. The links above the pink line are not clickable and don't register as links when hovered over. Below the pink line the links are working as expected. 

Found on https://masto.beer running version 3.2.0. I am using Safari 14.0.1.

![Screen Shot 2020-10-03 at 8 07 48 PM](https://user-images.githubusercontent.com/63966511/95004762-46cd2100-05b5-11eb-9a1d-8b47d57a1234.jpg)

**Comment by dariusk** [comment]
I'm looking into this since it affects Hometown too. I'm having trouble reproducing this issue, can you tell me your browser and maybe your window resolution that causes this?

**Comment by elenners** [comment]
> I'm looking into this since it affects Hometown too. I'm having trouble reproducing this issue, can you tell me your browser and maybe your window resolution that causes this?

Hey Darius! Yes, it is Safari 14.0.1. I keep my screen maximized, the screen's resolution is 1680x1050. Here is a screenshot of the entire screen. 
![Screen Shot 2020-10-09 at 9 09 52 AM](https://user-images.githubusercontent.com/63966511/95593725-aa20de00-0a0f-11eb-929b-0f1dc94f6eb5.jpg)
