### ISSUE TITLE
Install Failure

### ISSUE THREAD

**Issue by 4nanook** [mastodon/mastodon#14941]
Trying to install on Ubuntu 20.04, have tried instructions from several sites but failure is same.
Have also tried with both Ruby 2.6.5 and 2.6.6 and get same failure.
### Expected behaviour
Expect it to work but it seems anything involving ruby or javascript rarely does.

Should have worked.
### Actual behaviour

```
bundle install -j$(getconf _NPROCESSORS_ONLN) --deployment --without development test
[DEPRECATED] The `--deployment` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set deployment 'true'`, and stop using this flag
[DEPRECATED] The `--without` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set without 'development test'`, and stop using this flag
Fetching gem metadata from https://rubygems.org/............
Using rake 13.0.1
Using concurrent-ruby 1.1.6
Using jsonapi-renderer 0.2.2
Using arel 9.0.0
Using mimemagic 0.3.5
Using erubi 1.9.0
Using mini_portile2 2.4.0
Using public_suffix 4.0.5
Using aws-eventstream 1.1.0
Using rack 2.2.3
Using aws-partitions 1.338.0
Using bcrypt 3.1.13
Using ffi 1.10.0
Using msgpack 1.3.3
Using browser 4.2.0
Using encryptor 3.0.0
Using bundler 2.1.4
Using multi_json 1.14.1
Using multipart-post 2.1.1
Using nio4r 2.5.2
Using elasticsearch-dsl 0.1.9
Using color_diff 0.1
Using connection_pool 2.2.3
Using orm_adapter 0.5.0
Using thread_safe 0.3.6
Using thor 0.20.3
Using builder 3.2.4
Using unf_ext 0.0.7.7
Using dotenv 2.7.5
Using e2mmap 0.1.0
Using ed25519 1.2.4
Using websocket-extensions 0.1.5
Using excon 0.75.0
Using method_source 1.0.0
Using mini_mime 1.0.2
Using formatador 0.2.5
Using mime-types-data 3.2020.0512
Using crass 1.0.6
Using raabro 1.3.1
Using http-form_data 2.3.0
Using oj 3.10.6
Using equatable 0.6.1
Using temple 0.8.2
Using hashie 4.1.0
Using hiredis 0.6.3
Using hkdf 0.3.0
Using htmlentities 4.3.4
Using http_accept_language 2.1.1
Using http_parser.rb 0.6.1 from https://github.com/tmm1/http_parser.rb (at 54b17ba@54b17ba)
Using chunky_png 1.3.11
Using rainbow 3.0.0
Using tilt 2.0.10
Using iso-639 0.3.5
Using minitest 5.14.1
Using json-canonicalization 0.2.0
Using link_header 0.0.8
Using jwt 2.2.1
Using kaminari-core 1.2.1
Using necromancer 0.5.1
Using net-ldap 0.16.2
Using nilsimsa 1.1.2 from https://github.com/witgo/nilsimsa (at fd18488@fd18488)
Using fast_blank 1.0.0
Using statsd-ruby 1.4.0
Using ox 2.13.2
Using parallel 1.19.2
Using parslet 2.0.0
Using tty-color 0.5.1
Using pg 1.2.3
Using jmespath 1.4.0
Using posix-spawn 0.3.13 from https://github.com/rtomayko/posix-spawn (at 58465d2@58465d2)
Using redis 4.2.1
Using private_address_check 0.5.0
Using rqrcode_core 0.1.2
Using rotp 2.1.2
Using semantic_range 2.3.0
Using thwait 0.1.0
Using stoplight 2.2.0
Using tty-cursor 0.7.1
Using fastimage 2.1.7
Using tty-screen 0.8.0
Using wisper 2.0.1
Using i18n 1.8.3
Using hamster 3.0.0
Using nokogiri 1.10.9
Using marcel 0.3.3
Using addressable 2.7.0
Using warden 1.2.8
Using sprockets 3.7.2
Using request_store 1.5.0
Using rack-attack 6.3.1
Using rack-cors 1.1.1
Using rack-proxy 0.6.5
Using aws-sigv4 1.2.1
Using blurhash 0.1.4
Using cld3 3.3.0
Using ffi-compiler 1.0.1
Using attr_encrypted 3.1.0
Using bootsnap 1.4.6
Using elasticsearch-api 7.8.0
Using streamio-ffmpeg 3.0.2
Using faraday 1.0.1
Using puma 4.3.5
Using tzinfo 1.2.7
Using unf 0.1.4
Using websocket-driver 0.7.2
Using mail 2.7.1
Using mime-types 3.3.1
Using omniauth 1.9.1
Using httplog 1.4.3
Using hamlit 2.11.0
Using webpush 0.3.8
Using pastel 0.7.4
Using mario-redis-lock 1.2.1
Using sidekiq 6.1.0
Using redis-store 1.9.0
Using redis-namespace 1.7.0
Using rqrcode 1.1.2
Using loofah 2.6.0
Using rdf 3.1.4
Using rack-test 1.1.0
Using ruby-saml 1.11.0
Using activesupport 5.2.4.3
Using rails-html-sanitizer 1.3.0
Using aws-sdk-core 3.103.0
Using elasticsearch-transport 7.8.0
Using css_parser 1.7.1
Using domain_name 0.5.20190701
Using et-orbi 1.2.4
Using fog-core 2.1.0
Using http-parser 1.2.1
Using json-ld 3.1.4
Using omniauth-cas 1.1.1
Using rdf-normalize 0.4.0
Using redis-rack 2.1.2
Using sidekiq-bulk 0.2.0
Fetching nokogumbo 2.0.2
Using sidekiq-unique-jobs 6.0.22
Using tty-reader 0.7.0
Using twitter-text 1.14.7
Using tzinfo-data 1.2020.1
Using nsa 0.2.7
Using omniauth-saml 1.10.2
Using premailer 1.11.1
Using pundit 2.1.0
Using redis-activesupport 5.2.0
Using simple-navigation 4.1.0
Using rails-dom-testing 2.0.3
Using globalid 0.4.2
Using activemodel 5.2.4.3
Using case_transform 0.2
Using aws-sdk-kms 1.36.0
Using elasticsearch 7.8.0
Using fog-json 1.2.0
Using fugit 1.3.6
Using http-cookie 1.0.3
Using json-ld-preloaded 3.1.3
Using actionview 5.2.4.3
Using activejob 5.2.4.3
Using activerecord 5.2.4.3
Using aws-sdk-s3 1.73.0
Using chewy 5.1.0
Using pkg-config 1.4.1
Using rufus-scheduler 3.6.0
Using tty-prompt 0.21.0
Using actionpack 5.2.4.3
Using kaminari-actionview 1.2.1
Using discard 1.2.0
Using kaminari-activerecord 1.2.1
Using makara 0.4.1
Using pghero 2.5.1
Using strong_migrations 0.6.8
Using actioncable 5.2.4.3
Using actionmailer 5.2.4.3
Using active_model_serializers 0.10.10
Using ipaddress 0.8.3
Using activestorage 5.2.4.3
Using sprockets-rails 3.2.1
Using charlock_holmes 0.7.7
Using redis-actionpack 5.2.0
Using sidekiq-scheduler 3.0.1
Using railties 5.2.4.3
Using premailer-rails 1.11.1
Using fog-openstack 0.3.10
Using redis-rails 5.0.2
Using responders 3.0.1
Using doorkeeper 5.4.0
Using dotenv-rails 2.7.5
Using hamlit-rails 0.2.3
Using rails 5.2.4.3
Using lograge 0.11.2
Using rails-i18n 5.1.3
Using webpacker 5.1.1
Using devise 4.7.2
Using health_check 4.0.0.pre from https://github.com/ianheggie/health_check (at 0b799ea@0b799ea)
Using simple_form 5.0.2
Using rails-settings-cached 0.6.6
Using devise-two-factor 3.1.0
Using http 4.4.1
Using ruby-progressbar 1.10.1
Using kaminari 1.2.1
Using goldfinger 2.1.1
Using idn-ruby 0.1.0
Using climate_control 0.2.0
Using cocaine 0.5.8
Using terrapin 0.6.0
Using av 0.9.0
Using paperclip 6.0.0
Using paperclip-av-transcoder 0.6.4
Installing nokogumbo 2.0.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /misc/www/mastodon/live/vendor/bundle/ruby/2.7.0/gems/nokogumbo-2.0.2/ext/nokogumbo
/usr/bin/ruby2.7 -I /usr/lib/ruby/2.7.0 -r ./siteconf20201005-414359-tozgyv.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.7
/usr/lib/ruby/2.7.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'nokogiri' (= 1.10.7) - did find: [nokogiri-1.10.9] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/misc/www/mastodon/live/vendor/bundle/ruby/2.7.0', execute `gem env` for more information
	from /usr/lib/ruby/2.7.0/rubygems/dependency.rb:323:in `to_spec'
	from /usr/lib/ruby/2.7.0/rubygems/specification.rb:988:in `find_by_name'
	from extconf.rb:10:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /misc/www/mastodon/live/vendor/bundle/ruby/2.7.0/gems/nokogumbo-2.0.2 for inspection.
Results logged to /misc/www/mastodon/live/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/nokogumbo-2.0.2/gem_make.out

An error occurred while installing nokogumbo (2.0.2), and Bundler cannot continue.
Make sure that `gem install nokogumbo -v '2.0.2' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  sanitize was resolved to 5.2.1, which depends on
    nokogumbo
mastodon@ftp:~/live$ more /misc/www/mastodon/live/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/nokogumbo-2.0.2/gem_make.out
current directory: /misc/www/mastodon/live/vendor/bundle/ruby/2.7.0/gems/nokogumbo-2.0.2/ext/nokogumbo
/usr/bin/ruby2.7 -I /usr/lib/ruby/2.7.0 -r ./siteconf20201005-414359-tozgyv.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.7
/usr/lib/ruby/2.7.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'nokogiri' (= 1.10.7) - did find: [nokogiri-1.10.9] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/misc/www/mastodon/live/vendor/bundle/ruby/2.7.0', execute `gem env` for more information
	from /usr/lib/ruby/2.7.0/rubygems/dependency.rb:323:in `to_spec'
	from /usr/lib/ruby/2.7.0/rubygems/specification.rb:988:in `find_by_name'
	from extconf.rb:10:in `<main>'

extconf failed, exit code 1
mastodon@ftp:~/live$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.2
  - RUBY VERSION: 2.7.0 (2019-12-25 patchlevel 0) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.7.0
  - USER INSTALLATION DIRECTORY: /misc/www/mastodon/.gem/ruby/2.7.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.7
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /misc/www/mastodon/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.7.0
     - /misc/www/mastodon/.gem/ruby/2.7.0
     - /usr/lib/ruby/gems/2.7.0
     - /usr/share/rubygems-integration/2.7.0
     - /usr/share/rubygems-integration/all
     - /usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin
```

### Steps to reproduce the problem
Try installing on Ubuntu 20.04 per instructions here:
https://computingforgeeks.com/install-mastodon-on-ubuntu-with-letsencrypt-ssl-certificate/

### Specifications

Current, not sure how to get this but what's on git as of 10/5/2020.

Ubuntu 20.04 never got to browser usage.

**Comment by 4nanook** [comment]
This is with node:
node --version
v10.19.0

I had previously tried under v14 you told me not compatible so now trying with old shit, still fails.

**Comment by ThibG** [comment]
This has nothing to do with node.js.

You may be missing some dependency, or maybe the `Gemfile.lock` has been modified somehow? (You could check this with `git diff v3.2.0 -- Gemfile.lock`)

What's in `/misc/www/mastodon/live/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/nokogumbo-2.0.2/gem_make.out`?

**Comment by 4nanook** [comment]
When I first installed and posted a bug report I was told node 14 wasn't compatible and indeed it did bitch about something that had been deprecated.  Anyway, I didn't modify the Gemfile.lock:
mastodon@ftp:~/live$ git diff v3.2.0 -- Gemfile.lock
mastodon@ftp:~/live$ 

     As you can see diff shows ZERO changes, no output.

     This is the contents of /misc/www/mastodon/live/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/nokogumbo-2.0.2/gem_make.out:

current directory: /misc/www/mastodon/live/vendor/bundle/ruby/2.7.0/gems/nokogumbo-2.0.2/ext/nokogumbo
/usr/bin/ruby2.7 -I /usr/lib/ruby/2.7.0 -r ./siteconf20201005-414359-tozgyv.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.7
/usr/lib/ruby/2.7.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'nokogiri' (= 1.10.7) - did find: [nokogiri-1.10.9] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/misc/www/mastodon/live/vendor/bundle/ruby/2.7.0', execute `gem env` for more information
	from /usr/lib/ruby/2.7.0/rubygems/dependency.rb:323:in `to_spec'
	from /usr/lib/ruby/2.7.0/rubygems/specification.rb:988:in `find_by_name'
	from extconf.rb:10:in `<main>'

extconf failed, exit code 1

**Comment by 4nanook** [comment]
I do not understand why some of the previous text was lined out.  It wasn't when I pasted it.

**Comment by ThibG** [comment]
Sorry, I meant to ask you the contents of `/misc/www/mastodon/live/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/nokogumbo-2.0.2/mkmf.log`

Your post appears like that because of the Markdown formatting. Please select command-line/file content snippets and use the “insert code” button in github's editor to make your posts easier to read.

**Comment by 4nanook** [comment]
There is no nokogumbo-2.0.2/mkmf.log file, there are only mkmf.log files for these extensions:

find . -name mkmf.log -print
./vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/nio4r-2.5.2/mkmf.log
./vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/nokogiri-1.10.9/mkmf.log
./vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/idn-ruby-0.1.0/mkmf.log
./vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/puma-4.3.5/mkmf.log
./vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/msgpack-1.3.3/mkmf.log
./vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/hiredis-0.6.3/mkmf.log
./vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/charlock_holmes-0.7.7/mkmf.log
./vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/unf_ext-0.0.7.7/mkmf.log
./vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/cld3-3.3.0/mkmf.log
./vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/ffi-1.10.0/mkmf.log
./vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/pg-1.2.3/mkmf.log
./vendor/bundle/ruby/2.7.0/bundler/gems/extensions/x86_64-linux/2.7.0/nilsimsa-fd184883048b/mkmf.log

**Comment by ThibG** [comment]
Alright… the only thing I'm seeing is the `Could not find 'nokogiri' (= 1.10.7) - did find: [nokogiri-1.10.9] (Gem::MissingSpecVersionError)` bit, but I have no idea why it would be looking for 1.10.7 since the `Gemfile.lock` only mentions `1.10.9`…

I currently don't have any better idea than the following: could you try again, after doing `rm -rf vendor/bundle`?

**Comment by 4nanook** [comment]
I've tried a good five times.  Not just removing vendor/bundle but everything from scratch.

**Comment by ThibG** [comment]
I assume `gem install nokogumbo -v '2.0.2' --source 'https://rubygems.org/'` fails with a similar error?

**Comment by 4nanook** [comment]
No oddly that succeeds, but if I go back and run the previous command it tries to build again even though it just installed manual ok, and fails.

**Comment by ThibG** [comment]
What was the output of `gem install nokogumbo -v '2.0.2' --source 'https://rubygems.org/'`?

What does running `grep -rF 1.10.7` in Mastodon's installation directory return?

**Comment by 4nanook** [comment]
> What was the output of gem install nokogumbo -v '2.0.2' --source 'https://rubygems.org/'?

mastodon@ftp:~/live$ gem install nokogumbo -v '2.0.2' --source 'https://rubygems.org/'
Building native extensions. This could take a while...
Successfully installed nokogumbo-2.0.2
Parsing documentation for nokogumbo-2.0.2
Done installing documentation for nokogumbo after 0 seconds
1 gem installed
mastodon@ftp:~/live$ 

> What does running grep -rF 1.10.7 in Mastodon's installation directory return?

mastodon@ftp:~/live$ grep -rF 1.10.7 
yarn.lock:selfsigned@^1.10.7:
yarn.lock:  version "1.10.7"
yarn.lock:  resolved "https://registry.yarnpkg.com/selfsigned/-/selfsigned-1.10.7.tgz#da5819fd049d5574f28e88a9bcc6dbc6e6f3906b"
yarn.lock:    selfsigned "^1.10.7"
vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/nokogumbo-2.0.2/gem_make.out:/usr/lib/ruby/2.7.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'nokogiri' (= 1.10.7) - did find: [nokogiri-1.10.9] (Gem::MissingSpecVersionError)
mastodon@ftp:~/live$ 

>

**Comment by ThibG** [comment]
I am sorry, I have truly no idea what's going on there :/

**Comment by 4nanook** [comment]
I think interpretive languages like Ruby, Javascript, Java, Python, hate me.  Always seem to run into random crapola like this.

**Comment by robtarr** [comment]
Could it be Ruby 2.7? I'm running 2.6.6 for mine, which is also what the Mastodon docs indicate to use. I wouldn't think 2.7 would break things, but I've seen stranger.

**Comment by 4nanook** [comment]
The only place it gives you an option to select a version, I selected
2.66, but 2.7 is the native version.  As far as I know nothing is using the
system version so I'm going to remove it and make another attempt installing
2.66 with rbenv, it may be that I'm losing or somehow messing up the path
during the build process and it's going to the system version.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by saper** [comment]
I'd get rid of 2.7.0 completely and try again.

**Comment by 4nanook** [comment]
Actually I got past the ruby issues by logging in as mastadon and working
from there, that way RBENV is always correct, however ran into some issues
with OPENSSL, 1.1.1h is missing an encryption it wants, so went back to 1.1.1g,
will try again.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by wilkis3** [comment]
Is this issue still relevant?

**Comment by 4nanook** [comment]
I tried another install lately, it blew up too but differently.
