### ISSUE TITLE
Rate limit on tootctl media remove-orphans

### ISSUE THREAD

**Issue by mashirozx** [mastodon/mastodon#14955]
### Pitch

I hope there to be an option in `tootctl media remove-orphans` to set the S3 API request rate.

### Motivation

Default is about 1000 per second I guess? It exceeds my S3 provider's rate limit, so it always failures in half way.

I hope to set the rate by my self.

**Comment by mashirozx** [comment]
Always failure with msg below because rate limit:

Error fetching list of files: Net::ReadTimeout with #<TCPSocket:(closed)>
If you want to continue from this point, add --start-after=accounts/avatars/000/005/476/original/dbd437bf08953f0f.jpeg to your command

Sad TAT

**Comment by Eriner** [comment]
This issue is still present as of v3.4.0.

**Comment by travnewmatic** [comment]
`S3_READ_TIMEOUT` should REALLY BE in the documentation
