### ISSUE TITLE
Too many boosts can prevent a timeline from seeing older posts ("show more" fails with boosts hidden on a column)

### ISSUE THREAD

**Issue by tyrosinase** [mastodon/mastodon#14957]
### Expected behaviour

Clicking "Show more" in the web client should display older posts.

### Actual behaviour

Timeline stalls when the requested batch of posts is 100% boosts and "show boosts" is turned off in that column. Apparently the batch request always uses the most recent *displayed* post, and can never get past the ridiculous chunk of boosts.

### Steps to reproduce the problem

Follow @vfrmedia@social.tchncs.de. Turn off "show boosts" in your home timeline. Wait for alex to boost an entirely unreasonable number of posts. Load the web client. Any more recent non-boost posts will appear, along with a "show more" button. If the boost cluster is larger than the client's request for older posts, you will never be able to see older posts. (Workaround: toggle "show boosts" so that the boosts are loaded, then turn it off so they're hidden again. Then hide boosts on alex's profile page so they don't end up in your timeline requests at all.)

### Suggested fix

"Show More" should use the timestamp of the oldest post in the last request, rather than the oldest _displayed_ post.

### Specifications

v3.2.0

**Comment by ironiridis** [comment]
Still an issue in v4.0.2, for what it's worth.

**Comment by ClearlyClaire** [comment]
> Apparently the batch request always uses the most recent _displayed_ post, and can never get past the ridiculous chunk of boosts.

Ah, indeed, that seems to be what is happening, and I completely missed that.

The button's behavior is defined here:
https://github.com/mastodon/mastodon/blob/6579e3af7d6eb2774eae3d16bb1c9b7772fb58ec/app/javascript/mastodon/components/status_list.jsx#L57-L59

But `this.props.statusIds` contains only the displayed posts, as they are filtered here:
https://github.com/mastodon/mastodon/blob/6579e3af7d6eb2774eae3d16bb1c9b7772fb58ec/app/javascript/mastodon/features/ui/containers/status_list_container.js#L39

> "Show More" should use the timestamp of the oldest post in the last request, rather than the oldest _displayed_ post.

I'm not sure this would be enough to completely eliminate the UX issues, as you could end up having multiple pages of filtered posts, thus making the “Show more” button appear to do nothing (but still making progress as you repeatedly press it), but it would help a great deal and fix the complete inability to get past a page of filtered posts.
