### ISSUE TITLE
Images attached to a public post will not load, remain blank instead

### ISSUE THREAD

**Issue by Currrupted** [mastodon/mastodon#14962]
### Expected behaviour

When adding any attachment, specifically images, to a new post with text, they should appear normally. Both for the user and other people seeing the post.

### Actual behaviour

The images are successfully attached to a new post, but are not loaded correctly. They turn into shapes with only one colour. Other users have confirmed that they cannot see the attachments either.

### Steps to reproduce the problem

1. Log into your own account on your Mastodon instance
2. Create a new post (Toot) via the sidebar to the left
3. Click on the attachment button and select multiple images
4. Wait for the images to (not) load
5. Publish the post ("Toot!")

### Specifications

Version: v3.2.0
Instance: https://todon.nl

Browser: Tor Browser 10.0 (based on Mozilla Firefox 78.3.0esr)
Operating System: Kubuntu 20.04 LTS (Kernel version: 5.4.0-48-generic)

**Comment by ThibG** [comment]
The issue is most probably a temporary issue specific to that instance. Does the issue still occur? Can you link to a post with attachments that do not show up? If the issue persists, is there anything about those specific pictures? Can you post them somewhere else so that we could have a look?
