### ISSUE TITLE
Mailers receiving Authentication error despite setup sending test email successfully

### ISSUE THREAD

**Issue by lambada** [mastodon/mastodon#15017]
I can only assume it might be because of my password having punctuation characters in it (e.g. `!@£$%`)

### Expected behaviour

ActionMailer should successfully send emails, e.g. a user welcome email

### Actual behaviour

Email is stuck in retry queue
```
Net::SMTPAuthenticationError: 535 5.7.3 Authentication unsuccessful [AM0PR07CA0026.eurprd07.prod.outlook.com]
```

### Steps to reproduce the problem
I _think_ it's likely password related soo likely....

Have an SMTP server where the password has special characters in it
Run the interactive setup script - `RAILS_ENV=production bundle exec rake mastodon:setup`
Choose to send the test email
Note you receive the email
Save the config
Register another user
Check the sidekiq queue

For a bit extra detail, here's my full smtp settings as stored in the config file generated
```
SMTP_SERVER=smtp.office365.com
SMTP_PORT=587
SMTP_LOGIN=user@domain.com
SMTP_PASSWORD=password!is@not£mine
SMTP_AUTH_METHOD=login
SMTP_OPENSSL_VERIFY_MODE=none
SMTP_FROM_ADDRESS=mastodon@domain.com
```

### Specifications
Latest stable: v3.2.1

**Comment by lambada** [comment]
I eventually managed to work around this by wrapping the SMTP_PASSWORD value in single quotes manually in the config file. Interestingly using `\` to escape the `!` in the password didn't work. I cannot test other symbols to see if they also cause a problem.

**Comment by ThibG** [comment]
The `dotenv-rails` gem we use to load environment variables doesn't quite match what a shell would do, so there might be some discrepancies and we wrote our own escaping code, which might contribute to explain the issue at hand here.

However, I don't seem to have any issue with a password like `password!is@not£mine` written as-is in the env file, so I'm unsure what the actual issue is.

**Comment by acheong08** [comment]
Quite a while later, this is still an issue. I had a '$' symbol in the password and it gave me SMTPAuthenticationError. Encapsulating with quotes fixed it

**Comment by dwehrmann** [comment]
That was the case for me, also. I had another symbol in the password, which was not a double or single quote, though. I think the general recommendation should be to put the password always in single quotes.

**Comment by ClearlyClaire** [comment]
This is annoying, `dotenv` parsing is a bit finnicky, and inconsistent with other ways of reading the env file, so there isn't, as far as I am aware, a way to escape the password such that it is safe in all situations.

Are you running Mastodon in docker? Which of these characters does your password use, if any? `'`, `"`, `$`, `#`, ` `?

**Comment by acheong08** [comment]
Just put the password in quotes and it has since been resolved for me.

**Comment by glenmo** [comment]
> This is annoying, `dotenv` parsing is a bit finnicky, and inconsistent with other ways of reading the env file, so there isn't, as far as I am aware, a way to escape the password such that it is safe in all situations.
> 
> Are you running Mastodon in docker? Which of these characters does your password use, if any? `'`, `"`, `$`, `#`, ` `?

Thanks for your reply. My SMTP password is only lettes and numbers (no special characters) and 16 characters long.

**Comment by glenmo** [comment]
> 

Thanks for the suggestion but that didn't work either. It's just weird that the setup confirmation email was sent OK but nothing subsequently. I get the following error:

> WARN: Net::SMTPFatalError: 550 relay access denied - please authenticate

**Comment by glenmo** [comment]
I've noticed this error in the sidekiq logs when restarting the service:

WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["/home/mastodon/live/lib/mastodon/redis_config.rb:38:in `<top (required)>'", "/home/mastodon/live/config/application.rb:53:in `require_relative'"]

Could this be related to the SMTP authentication failure problem?

**Comment by lambada** [comment]
> > This is annoying, `dotenv` parsing is a bit finnicky, and inconsistent with other ways of reading the env file, so there isn't, as far as I am aware, a way to escape the password such that it is safe in all situations.
> > Are you running Mastodon in docker? Which of these characters does your password use, if any? `'`, `"`, `$`, `#`, ` `?
> 
> Thanks for your reply. My SMTP password is only lettes and numbers (no special characters) and 16 characters long.

@glenmo it sounds like you’re experiencing a different problem to what I opened this issue for

**Comment by lambada** [comment]
> This is annoying, `dotenv` parsing is a bit finnicky, and inconsistent with other ways of reading the env file, so there isn't, as far as I am aware, a way to escape the password such that it is safe in all situations.
> 
> Are you running Mastodon in docker? Which of these characters does your password use, if any? `'`, `"`, `$`, `#`, ` `?

@ClearlyClaire My email password has an `!` and a `$` in it.

**Comment by glenmo** [comment]
> @glenmo it sounds like you’re experiencing a different problem to what I opened this issue for

@lambada oops... sorry... I just thought the title reflected my exact problem: setup sends email but thereafter nothing is sent via SMTP.

**Comment by lambada** [comment]
It does match the title, but in this case I narrowed it down to needing to escape the password. If that isn’t working in your case it suggests a different root cause
