### ISSUE TITLE
Replace "toot" with "content" in some strings

### ISSUE THREAD

**Issue by Porrumentzio** [mastodon/mastodon#15061]
### Pitch
When a user starts following another account, there is showed this message:
![image](https://user-images.githubusercontent.com/61913683/97543412-7c083b80-19c8-11eb-9435-1fb4682c23a0.png)

But that message is not correct, because not all account followed make toots, but videos, audios, blogs... so my proposal is to **replace `toot` with `content`** in such string(s)

### Motivation

As said, this message is erroneous, so it's logical to change it

**Comment by iomintz** [comment]
Within Mastodon's terminology a toot can take many forms and can contain multimedia, long-form writing, polls, etc. These are all properly called "toots" as far as I'm aware.

**Comment by Porrumentzio** [comment]
But it's a bit confusing using a word dedicated to the messages from a technology (Mastodon) to call any-any content, for example images, songs, links... from other technologies

**Comment by iomintz** [comment]
The [documentation](https://docs.joinmastodon.org/user/posting/) refers to all of these as "toots", rather than just "messages". Have you read otherwise somewhere?

**Comment by vmstan** [comment]
References to toots was removed from Mastodon 4.0
