### ISSUE TITLE
Domain block list export / import

### ISSUE THREAD

**Issue by argxentakato** [mastodon/mastodon#15095]
### Pitch

Domain Block Outputs the target domain in a specific format (CSV, JSON, etc.).

### Motivation

I think you need the function to export/import domain blocks list to share servers. 

This maybe protects the newly created server from dangerous servers (malicious or abandoned servers).

If we can get the domain block list from the REST API, we may be able to create a like "Fediverse credit list", and I think to make Fediverse will even safer.

**Comment by bixfrankonis** [comment]
I need this capability desperately.
