### ISSUE TITLE
Mastodon Gmail SMTP Error

### ISSUE THREAD

**Issue by erencantopdemir** [mastodon/mastodon#15103]
I have a gmail smtp problem.

i am seeing this error: EOFError: end of file reached

https://prnt.sc/vfj000

My settings:

SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_LOGIN=xxx@gmail.com
SMTP_DOMAIN=gmail.com
SMTP_PASSWORD=xxx
SMTP_AUTH_METHOD=none
SMTP_OPENSSL_VERIFY_MODE=none
SMTP_FROM_ADDRESS='XXX <xxx@gmail.com>'

i try it that combination:
SMTP_AUTH_METHOD=none, SMTP_AUTH_METHOD=plain
SMTP_OPENSSL_VERIFY_MODE=none, SMTP_OPENSSL_VERIFY_MODE=peer

Why got this error? Please help me.

**Comment by Gargron** [comment]
“EOFError: end of file reached” could mean that there is a mitm proxy that blocks traffic on the smtp port. Sometimes housing services have that on by default, check your settings.

**Comment by Gadgetoid** [comment]
For anyone else who - like me - ends up here - I had this same issue with Google's SMTP Relay service. I changed two settings at once on the Google side and it seems to work now:

1. I added my server's IPV6 address to the list of allowed IPs
2. I disabled "Require TLS encryption"

My email config:

```
SMTP_SERVER=smtp-relay.gmail.com
SMTP_PORT=587
SMTP_DOMAIN=mydomain.com
SMTP_LOGIN=
SMTP_PASSWORD=
SMTP_AUTH_METHOD=none
SMTP_OPENSSL_VERIFY_MODE=none
SMTP_ENABLE_STARTTLS=auto
SMTP_FROM_ADDRESS='Mastodon <mastodon@mydomain.com>'
```

**Comment by andresdegante** [comment]
I have the same problem, use bitmani in azure, anyone can help me?
