### ISSUE TITLE
Upgrade to 3.2.1

### ISSUE THREAD

**Issue by kdmiller45** [mastodon/mastodon#15143]
Currently using Mastodon 3.2.0 and noticed a newer version the instruction say:
Upgrade notes
Because this is a backport, it is not available with git pull. Use git fetch && git checkout v3.2.1

So as root I tried to run Use git fetch && git checkout v3.2.1
and got the following error:
fatal: not a git repository (or any of the parent directories): .git

so there must be more needed to be done then this simple command. please give more detail

**Comment by Gargron** [comment]
You have to be in the Mastodon directory to execute that. `cd /home/mastodon/live` or where you've installed it

**Comment by kdmiller45** [comment]
> You have to be in the Mastodon directory to execute that. `cd /home/mastodon/live` or where you've installed it

Yup was there
thanks for the attempt
