### ISSUE TITLE
Abnormal display of expression pack

### ISSUE THREAD

**Issue by ouyangqr** [mastodon/mastodon#15147]
![1605163157(1)](https://user-images.githubusercontent.com/42233480/98904650-fb335e80-24f4-11eb-9204-95ca63c6900b.png)

From this picture, we can see that the expression package is abnormal. When we use the expression pack in our speech, we will make the same error

**Comment by ThibG** [comment]
It looks like an issue with your setup, with the emoji assets not being loaded properly. Are there other assets not loading correctly? What browser are you using?
