### ISSUE TITLE
Toots are not displaying

### ISSUE THREAD

**Issue by raj3479** [mastodon/mastodon#15140]
![image](https://user-images.githubusercontent.com/2088134/98754759-5aa64700-23ed-11eb-9c8d-9d08dfa4f719.png)

Even though it's in public view, the toots are not displaying in the home page and looks like it's not working. Can you please let me know where to check for error?

Thanks

**Comment by ThibG** [comment]
The first thing I would check is the sidekiq logs: `journalctl -u mastodon-sidekiq`
