### ISSUE TITLE
Server does not decode percent-encoded '@'

### ISSUE THREAD

**Issue by pbx** [mastodon/mastodon#15153]
### Expected behaviour

Making a request of a Mastodon server with a URL containing percent-encoded "@" character (`%40`) should return the same response as a URL with a literal "@".

### Actual behaviour

The server returns a 404 if the "@" is percent-encoded.

### Steps to reproduce the problem

1. Confirm that you can view a user's profile page, e.g. [fosstodon.org/@pbx](https://fosstodon.org/@pbx)
2. Request that same URL with the `@` encoded per [RFC-3986](https://tools.ietf.org/html/rfc3986#section-2.1) as `%40`: [fosstodon.org/%40pbx](https://fosstodon.org/%40pbx)
3. Confirm the 404 response.

### Specifications

Reproduced on Mastodon v3.5.3 running at fosstodon.org.

Not a front-end issue, but seen in all browsers I've checked; most recent repro was on Firefox 106.0 (64-bit) on Linux.

Note that other percent-encoded characters in the URL are decoded without problem, e.g. [fosstodon.org/@dpast%65](https://fosstodon.org/@dpast%65)

**Comment by thijskh** [comment]
I ran into this when wanting to link to a toot from a Sharepoint page/comment. Sharepoint URL-encoded the @ making the only way to link to toots from Sharepoint to use an url shortener in between...

**Comment by noelk** [comment]
running v4.2.9 is looks like it is still an issue:
[https://social.bund.de/@bfdi](https://social.bund.de/@bfdi) works
[https://social.bund.de/%40bfdi](https://social.bund.de/%40bfdi) error

I didn't found the patch line in main and wrote a comment to the commit #23593
