### ISSUE TITLE
Mastodon fills up /tmp over time

### ISSUE THREAD

**Issue by ddevault** [mastodon/mastodon#1528]
A bunch of media files seem to accumulate there.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Fastidious** [comment]
As far as I know, `/tmp` is self-cleaning (at least, there is a daily cron for it on Ubuntu, which is what I use). Create a cronjob to delete files X days old? I don’t think this is a Mastodon problem, nor task.

**Comment by SirCmpwn** [comment]
/tmp is definitely not self cleaning. Cleaning up after yourself is 100% Mastodon's responsibility as a good citizen of Unix.

**Comment by SirCmpwn** [comment]
Some files in /tmp unrelated to Mastodon are meant to be there indefinitely, you know. Are you sure Ubuntu cleans it out periocially?

**Comment by expenses** [comment]
Supposedly, Ubuntu cleans `/tmp` on boot: http://serverfault.com/questions/377348/when-does-tmp-get-cleared

As for whether cleaning the directory is something Masterdon should do, I'm not sure. Whats the general policy with other services that use `/tmp`?

**Comment by SirCmpwn** [comment]
Everyone cleans up /tmp on boot, that's the point of tmpfs. It lives in RAM, not on disk. Like I said, the general policy is that everyone is expected to clean up /tmp files when they're done with them.

**Comment by mjankowski** [comment]
It might not solve the problem entirely, but there is a `mastodon:media:clear` rake task intended to be run regularly to clear up un-linked media files that have collected.

**Comment by Gargron** [comment]
@mjankowski That's something else though, that's on a different level to just /tmp

I don't know why /tmp wouldn't get cleaned up. There is not a line in Mastodon's own code that touches that directory, I think. It could be something Paperclip does/doesn't do..?

**Comment by mjankowski** [comment]
Yes, possibly paperclip-related - https://github.com/thoughtbot/paperclip/issues/1326 (and possibly a specific paperclip:sidekiq issue)

**Comment by docjkl** [comment]
as a workaround until this is fixed may i suggest an anti-packrat cronjob similar to: 

`@monthly /usr/bin/find /tmp -not -perm -u+x -type f -mtime +30 -delete`

**Comment by Gargron** [comment]
Maybe this is a fix? https://github.com/thoughtbot/paperclip/commit/90f9121a18df25bc3ef948356450ce19fbe1da83

We would need to upgrade Paperclip which currently fails: #8886
