### ISSUE TITLE
HTML sanitizer can change meaning of posts entirely

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#15311]
A private post in my home feed apparently contained a blockquote, which was stripped by the sanitizer and converted to a regular paragraph. This changed the meaning of the post entirely, since it was not apparent that one part was a quote and another part was not. It was pointed out that many of this user's other posts also contained blockquotes, and I fear that I may have misunderstood many of their posts due to there being no indication of this.

**Comment by Freeplayg** [comment]
I 100% agree with this. Mastodon not supporting basic markdown is a **major** issue when 90% of other Fedi platforms already support this stuff. This isn't something you can just choose to not add anymore. It's necessary.

**Comment by trwnh** [comment]
this issue isn't about markdown; it's about not mangling the HTML of incoming posts to the point that their meaning changes. i'm sure there's another issue for authoring markdown within mastodon, but it's not this one

**Comment by foreverxml** [comment]
Also commenting here to bring attention to this issue- Vanilla Mastodon ignores formatting currently and can change post meanings. I think authoring formatted posts should be implemented, but at least rendering other users’ formatter posts should be a given. But it's not.

**Comment by kvibber** [comment]
With more people joining the Fediverse and more projects that do allow minimal formatting (not just Misskey and its forks, but other projects like GoToSocial), it's becoming more important to avoid mangling the *actual meaning* of the post by stripping the html down as far as it is currently.

Even if vanilla Mastodon chooses not to support formatting when *creating* posts, it should preserve more formatting when sanitizing incoming posts.

At *minimum* blockquote and the strikethrough-related tags should be accepted for the reasons given by trwnh above (changing the meaning).

Additional basic formatting like bold, italic, maybe lists would certainly improve compatibility with other Fediverse software.

**Comment by renchap** [comment]
Closing this as it has been added in #23913 and will be in 4.2.0
