### ISSUE TITLE
[duplicate] Feature request: Option to disable notification counter in tab title

### ISSUE THREAD

**Issue by realpixelcode** [mastodon/mastodon#15313]
Please add an option to disable the new notifications counter in Mastodon's tab title since this may be annoying if you get particularly many notifications. I tried it but all the "Disable Notifications from this website", "Play sound" etc. options don't disable the counter itself, just the actual system's notifications.

For example:  "(5) Mastodon" -> just "Mastodon"

**Comment by weex** [comment]
Duplicate of https://github.com/mastodon/mastodon/issues/15313

**Comment by weex** [comment]
Duplicate of https://github.com/mastodon/mastodon/issues/13188

**Comment by realpixelcode** [comment]
@weex sorry

**Comment by weex** [comment]
@realpixelcode Don't be. I looked into this and it was fascinating how hard it was to trace. I just noted that it's a duplicate so both threads could gauge level of interest from the other. Thanks.
