### ISSUE TITLE
Link verification fails silently when page size exceeds 1MB

### ISSUE THREAD

**Issue by eloquence** [mastodon/mastodon#15316]
### Expected behaviour

Adding a link in the specified `rel="me"` format to a webpage, and then adding that webpage to a user profile, causes the link to be identified as verified.

### Actual behaviour

Link on https://securedrop.org/ is not recognized as "verified". Source code:

```
<a href="https://fosstodon.org/@securedrop" rel="me noopener nofollow" target="_blank">
<div class="footer-main__social-icon svg">
<img class="svg__svg" src="/static/images/mastodon.svg" type="image/svg+xml">
<img class="svg__fallback" src="/static/images/mastodon.png" alt="Mastodon Profile">
</div></a>
```

### Steps to reproduce the problem

1. Attempt to add https://securedrop.org/ to profile on https://fosstodon.org/@securedrop including by blanking and re-adding the profile.

### Specifications

Fosstodon is running 3.2.1. I also tried parsing this HTML excerpt locally using the code in https://github.com/tootsuite/mastodon/blob/master/app/services/verify_link_service.rb, and that seems to work fine, so I'm not sure if there's an issue with the HTML itself or not.

**Comment by ThibG** [comment]
This seems to occur because the page is too large for Mastodon. Mastodon will only load pages of up to 1MB (excluding any linked resource).

**Comment by eloquence** [comment]
@ThibG That sounds very plausible given the large inline SVG on the page (which compresses quite well, but still inflates the decompressed page size). Will test, thanks.

**Comment by eloquence** [comment]
The problem was indeed caused by the large page size. I would suggest showing an error message to the user in this case if at all possible, and have retitled the issue to that effect.

**Comment by xplosionmind** [comment]
I cannot figure out the reason why `rel='me'` verification fails on my website landing page, even though it is way smaller than 1MB (~110Kb), could you please help me figure it out?

- [tommi.space landing page](https://tommi.space)
- [tommi.space landing page source code](https://github.com/xplosionmind/tommi.space/blob/main/content/index.html)

**Comment by connyduck** [comment]
@xplosionmind The link to tommi.space on your profile is not clickable? Looks like you just put in `tommi.space` instead of `https://tommi.space/`

**Comment by xplosionmind** [comment]
Yep, you are right @connyduck. Thanks a lot, I did not realize it!

**Comment by maop** [comment]
> The problem was indeed caused by the large page size. I would suggest showing an error message to the user in this case if at all possible, and have retitled the issue to that effect.

Hello,
Please, a message error is really needed when this happens, one user on my instance had this problem and spent hours trying to figure it out.

**Comment by untitaker** [comment]
We at Sentry.io also ran into this problem.

Three ideas:

* Is there a concern with raising this limit to 10MB? There are far more memory-hungry tasks out there that also run more frequently.

* Would it be possible to not fail link verification but to instead truncate the page?

* Alternatively one could look into streaming HTML parsers like lol-html in Rust, but that doesn't seem worth the effort.

**Comment by chriszs** [comment]
We believe we just ran into this implementing verification at The Washington Post.

> Would it be possible to not fail link verification but to instead truncate the page?

This is also my question, and one I may submit a PR for. In my testing, Nokogiri parsing seems to succeed even when the page is truncated.

**Comment by freedmand** [comment]
+1 to truncating the page. In our case (I'm also at The Washington Post), we have large pages because NextJS injects the initial application state in the HTML. This always goes at the end of the page, so truncating wouldn't be losing any meaningful page content, i.e. where the rel="me" is located.

**Comment by ClearlyClaire** [comment]
Parsing truncated documents is an interesting idea, although I wonder if there are things we need to be careful about. For instance, it appears that if the document is truncated in the middle of the link's href, Nokogiri will happily parse that as a valid link, with the `href` set to everything it could read.

**Comment by chriszs** [comment]
@ClearlyClaire Ah, that's interesting! So for that case, I suppose we could test for `body.end_with?(link['href']).!` to prevent that specific issue (unless someone knows a cleverer way). We'd also have to look at the other uses of the client, I suppose, to see if there's anything that jumps out there.

**Comment by untitaker** [comment]
@ClearlyClaire if that is the case I believe nokogiri is in the wrong to behave this way as per HTML5 tokenization spec.

paste this into your browser:

```
data:text/html,<a href="http://google.com
```

and open devtools/inspector. you will see there is an empty body.

compare with:

```
data:text/html,<a href="http://google.com">
```

**Comment by untitaker** [comment]
I think nokogiri handles unclosed attributes just fine. From rails console:

```
[2] pry(main)> Nokogiri.HTML5("<a href=http://google.com>")
=> #(Document:0x11f6c {
  name = "document",
  children = [
    #(Element:0x11f80 {
      name = "html",
      children = [
        #(Element:0x11f94 { name = "head" }),
        #(Element:0x11fa8 {
          name = "body",
          children = [
            #(Element:0x11fbc {
              name = "a",
              attributes = [
                #(Attr:0x11fd0 { name = "href", value = "http://google.com" })]
              })]
          })]
      })]
  })
[3] pry(main)> Nokogiri.HTML5("<a href=http://google.com")
=> #(Document:0x11fe4 {
  name = "document",
  children = [
    #(Element:0x11ff8 {
      name = "html",
      children = [
        #(Element:0x1200c { name = "head" }),
        #(Element:0x12020 { name = "body" })]
      })]
  })
```

**Comment by chriszs** [comment]
@untitaker Correct that it parses unclosed attributes. In fact, it parses them so well it's difficult to detect and you might end up with a partial URL. I played around with different approaches to this, including telling Nokogiri to be stricter or inspecting errors, but landed on an `end_with` comparison. But I haven't solved the general case, just the verification specific one. You can see a demonstration of the issue and some unit tests for it in my PR here: #22703

**Comment by nightpool** [comment]
Another concern here is static hosts that charge for bandwidth e.g. S3. It would probably be pretty bad if someone could set up a bunch of accounts pointing to >10 gb s3 files they don't own and use it as a reflected DOS? That would be one potential benefit to our old method of detecting the Content Length early and then aborting as soon as possible. @chriszs with your updated code, do you know how S3 billing behaves? Do you get charged for the full file, or only the bytes downloaded? What about the old code?

**Comment by ClearlyClaire** [comment]
> I think nokogiri handles unclosed attributes just fine. From rails console:

Except we're using the HTML parser, not the HTML5 parser:

```
irb(main):001:0> Nokogiri::HTML('<a href="http://google.com')
=> 
#(Document:0x55ab4 {                          
  name = "document",                          
  children = [                                
    #(DTD:0x55ac8 { name = "html" }),       
    #(Element:0x55adc {                     
      name = "html",                        
      children = [ #(Element:0x55af0 { name = "body", children = [ #(Element:0x55b04 { name = "a", attributes = [ #(Attr:0x55b18 { name = "href", value = "http://google.com" })] })] })]
      })]                                   
  })   
```

**Comment by untitaker** [comment]
istm that switching to the HTML5 parser would fix this case and provide a parsing behavior that is much closer to how browsers do it. Not using HTML5-compliant parsing means that your parsing error recovery will always be specific to how nokogiri handles it because outside of WHATWG HTML5, error recovery is not part of any standard.

**Comment by untitaker** [comment]
I have opened https://github.com/mastodon/mastodon/pull/22879 which fixes the rubocop lints that flared up due to the files being touched, and moves to the nokogiri HTML5 parser instead of trying to detect that edgecase manually.
