### ISSUE TITLE
Upgrade from 3.1.3 to 3.2.2 broke whole mastodon

### ISSUE THREAD

**Issue by jakesullyneytiri** [mastodon/mastodon#15426]
Hi,

i was suggested to follow this guide https://docs.joinmastodon.org/admin/upgrading/ but that just breaks whole thing and now i'm stuck with broken profiles and toot feed throwing 500 errors.

also i ran build installers and yarn install or w.e it was and started the services that got page up on version 3.2.2 but errors appeared.

So how do i fix this now?

**Comment by jakesullyneytiri** [comment]
Update:

when i do following commands

# Migrate  
RAILS_ENV=production bundle exec rails assets:clobber 
RAILS_ENV=production bundle exec rails db:migrate 
RAILS_ENV=production bundle exec rails assets:precompile 
RAILS_ENV=production ~/live/bin/tootctl cache clear

i get this as result "rails aborted!
LoadError: cannot load such file -- tty-command"

**Comment by Gargron** [comment]
Remove the file `/home/mastodon/live/lib/tasks/digitalocean.rake`

**Comment by jakesullyneytiri** [comment]
Okay i will try again on another copy.

Also do i need to run yarn install and bundler install again for each upgrade?

**Comment by jakesullyneytiri** [comment]
Update: well this sems to work at last. Done a upgrade on test version 3.1.3 to 3.2.2 i removed rake file went to upgrading url and refollowed steps there, then did bundle install and yarn install and last the RAILS commands and that seems to have gotten whole upgrade passed through without a problem and without an error.

Maybe it's  good idea you guys add a notice information on upgrade page about "If you are on DigitalOcean remove following file /home/mastodon/live/lib/tasks/digitalocean.rake, before runing RAILS_ENV commands"

So other users who has it digitalocean won't be so confused and stuck on this problem like me.

**Comment by jakesullyneytiri** [comment]
next question when coming to the upgrading, is there a way to put site into a maintenance mode that will bring up a message notice on whole page until upgrade is done so when it is i can disable maintenance mode and users can login again or continue with their use?

Even a ready only mode would be good too if there is one, so they can ready toots but not post any or do changes at the moment?

**Comment by Gargron** [comment]
Upgrades are zero-downtime in most cases so such a page is not needed.

**Comment by jakesullyneytiri** [comment]
> Upgrades are zero-downtime in most cases so such a page is not needed.

I noticed that after, but wouldn't the database be affected while i do upgrade? Since whe ni do env cmds doesen't that change db and such and maybe causes errors temporarly when some one posts something?

**Comment by davidwolfpaw** [comment]
> Upgrades are zero-downtime in most cases so such a page is not needed.

That does mean not all cases. The ability to set a maintenance page would be helpful for this and other reasons.
