### ISSUE TITLE
Tumblr embeds not displaying

### ISSUE THREAD

**Issue by madprogramer** [mastodon/mastodon#15425]
For some reason Tumblr embeds don't seem to load properly, I'm not getting the image preview I'm expecting to on Mastodon.

### Expected behaviour

(Same embed on Twitter)

<img width="526" alt="image" src="https://user-images.githubusercontent.com/3719664/103106923-b3067080-464a-11eb-96bd-ae9aea0b9059.png">

### Actual behaviour

<img width="567" alt="image" src="https://user-images.githubusercontent.com/3719664/103106912-9b2eec80-464a-11eb-8376-0030a50e1851.png">

### Steps to reproduce the problem

Post a Tumblr toot (preferably with a shortened link)

### Specifications

Mastodon v3.3.0rc3

**Comment by madprogramer** [comment]
Bump!

**Comment by vmstan** [comment]
Tumblr link embeds are functional as of Mastodon 4.2
