### ISSUE TITLE
Mention Elasticsearch memory usage in install docs

### ISSUE THREAD

**Issue by melissaboiko** [mastodon/mastodon#15440]
My new-ish solo instance broke the VM’s 4GiB RAM cap, so I looked into it and these were the top 2 processes:

```
1438M RES  4792M VIRT elasticsearch
 325M RES  1371M VIRT sidekiq 
```

This is elasticsearch from debian stable (buster).

At this level of hogging I figure it’s worth a line in the install docs that enabling ES will bump up memory requirements dramatically…

**Comment by allilengyi** [comment]
I found this (apperently 4 year old version of mastodon docs) quite useful:
https://github.com/martindale/mastodon-docs/blob/master/Running-Mastodon/Elasticsearch-guide.md

<h4 dir="auto">Note: Are you worried about how much memory configuration
 need on your VPS? This list may be useful! In my opinion, It would be 
better to set it from 35% to 50% of the total memory.</h4>


Memory | Xms | Xmx
-- | -- | --
1GB | 256m | 256m
2GB | 512m | 512m
3GB | 1g | 1g
4GB | 2g | 2g

**Comment by vmstan** [comment]
Transferred to https://github.com/mastodon/documentation/issues/1337
