### ISSUE TITLE
Bugs display active users on the about page

### ISSUE THREAD

**Issue by oufmilo** [mastodon/mastodon#15474]
I have more active users than users
Do you have a solution to purge ?
[Active_users](https://imgur.com/V0dkn5r)

Thank you

**Comment by oufmilo** [comment]
I've test all tootctl  commands and nothing happens.
Anyone has a solution ?

**Comment by Gargron** [comment]
No solution, since these are historic counters and not a live counter. The thing is, you may not have as many users *anymore*, but you had that many active users in the time period that these stats are tracking. So it is technically correct even if it looks awkward next to a smaller user number.

**Comment by xakan** [comment]
Hi,

I encounter the same issue on my little instance, and I'm perfectly sure that no user account was deleted, but I have 10 active for 8  registered users.

Is it possible that the difference is caused by spam accounts we didn't allow to sign up ?

**Comment by oufmilo** [comment]
I don't understand why there is no problem in the admin panel ![Screenshot_20210109-214450_Firefox.png](https://user-images.githubusercontent.com/44617467/104109552-628c4580-52cf-11eb-8e76-1444969495a3.png)

It's not the same counter in the about page? 

Thanks for your answers @Gargron

**Comment by Gargron** [comment]
Dashboard has current week, frontpage has month

**Comment by Adnilson** [comment]
@Gargron I saw the code and it was a design decision. Can the name be changed in order to be more explicit?

**Comment by Gargron** [comment]
There is an asterisk next to "active" when you hover it says "Monthly Active Users (MAU)"
