### ISSUE TITLE
Keep GIF if converted video is bigger

### ISSUE THREAD

**Issue by sindastra** [mastodon/mastodon#15471]
### Pitch

The whole point of converting GIF to video is to save storage and bandwidth, I'm all for that.

However, in some cases the video output can be significantly bigger than the original GIF.

Therefore, I'd suggest adding a check to see if the video output is bigger, and keep the GIF if it is.

### Motivation

I just tooted an animated GIF that needs 485.5 KiB in size, which was converted to a video that now needs slightly over 1 MiB, which is more than double the original size, which defeats the point of conversion. Furthermore, the video output is lossy.

More storage, and lost information. Therefore, a simple check if the output is bigger, would make sense.

### Example GIF

![ConstellationGPS](https://user-images.githubusercontent.com/1236984/103397352-4f8fad80-4b38-11eb-8abb-54ca10f5700d.gif)

[Source](https://commons.wikimedia.org/wiki/File:ConstellationGPS.gif)

### Example video (as converted by Mastodon v3.3.0rc2)

Note that the video is now slightly over double the size, while also having lost some information.

https://user-images.githubusercontent.com/1236984/103397410-94b3df80-4b38-11eb-89f5-b25df83f9e90.mp4

[Source](https://mastodon.social/@sindastra/105473224572147558)

On a side-note, in the original toot, the color seems to be more accurate in the preview than when opening it.

**Comment by vmstan** [comment]
On Mastodon 4.3 with the most recent version of ffmpeg as the media processor, the resulting video file was only 25% larger than the original GIF, which is indeed still an increase but much improved over the original 2x increase.

The need to have animation processed as videos in timelines is driven by how they work on apps and mobile devices. Unfortunately that hasn't changed much in the 4 years since this was originally requested.

**Comment by sindastra** [comment]
@vmstan 

> in the 4 years since this was originally requested

Oh god. What happened to time...

**Comment by mjankowski** [comment]
Closing on assumption that the last few comments here indicate that while current performance is not ideal, it's a tradeoff we have to make and there's not more easy improvement to be had. Please re-open if there are specific other paths we could try.

**Comment by sindastra** [comment]
@vmstan Would you mind posting the original GIF and video output result for comparison? I'm curious as to what the current state is (not only in terms of size but also quality).

**Comment by vmstan** [comment]
It’s on https://vmst.io/@marshalus/112560147095470887 from a test post.
