### ISSUE TITLE
Extend feature of whether to crop images in non-expanded toots to include GIFs

### ISSUE THREAD

**Issue by tagener-noisu** [mastodon/mastodon#15497]
There's an option "Crop **images** in non-expanded toots to 16x9" that works only for images (as suggested in  #9916). It doesn't work for GIFs, they're always cropped to 16x9 whether this option is on or off.

### Pitch

Extend the feature to include GIFs.

### Motivation

Sometimes I create vertical gifs that look ugly if I don't expand them, maybe someone else would find this usefull too.

**Comment by vmstan** [comment]
This feature no longer exists.
