### ISSUE TITLE
Heroku build fail: cld3-3.4.1 requires ruby version < 3.1.0, >= 2.6.0, which is incompatible with the current version, ruby 2.5.0p0

### ISSUE THREAD

**Issue by haydenwalker980** [mastodon/mastodon#15512]
### Expected behaviour

Mastodon installs normally

### Actual behaviour

Got this error.  
![image](https://user-images.githubusercontent.com/37120379/103954280-b85ac500-50f8-11eb-9ba7-ebf9a3ce9401.png)

### Steps to reproduce the problem

I was attempting to install it. I used the button from Elements.

### Specifications

Branch master, latest version

It is not a front end issue

**Comment by echan00** [comment]
@haydenwalker980  did you have any luck on this?

**Comment by Gargron** [comment]
We don’t depend on cld3 anymore
