### ISSUE TITLE
Toot icon for bookmark, just like for boost / favorite

### ISSUE THREAD

**Issue by MirceaKitsune** [mastodon/mastodon#15522]
Mastodon recently introduced the ability to bookmark posts in addition to boosting and favoriting. As there's plenty of space on the bar below each toot, I see no reason why an icon wasn't added for this new action as well. The option currently resides under the "..." icon which opens a small menu, but to follow the existing trend and make it more accessible it could easily be placed to the right of the star icon.

Another advantage would be that, just as the boost icon turns blue when a post is boosted and the favorite icon turns yellow when a post is favorited, the bookmark icon would turn green when that toot is bookmarked so you can easily see it. Here's an edited screenshot showing precisely the suggested change... very clean and simple and leaves plenty of room.

![Screenshot_20210108_161155](https://user-images.githubusercontent.com/825418/104026832-2d98c980-51cf-11eb-8b5b-a09f063aa1fe.png)

**Comment by MirceaKitsune** [comment]
As an additional thought to this suggestion: I never really understood the point of having a bookmark feature, given that favoriting seems to do pretty much the same thing... if anything I'd have turned it into a follow feature instead, so that you can select a post on which to receive notifications for replies. But if this feature has been added in the end, it would make sense for it to look and work like its existing cousins boost and favorite.

**Comment by trwnh** [comment]
>I never really understood the point of having a bookmark feature, given that favoriting seems to do pretty much the same thing...

Bookmarking doesn't generate a notification.

**Comment by Dehelssey** [comment]
Favoriting is more like giving the OP a signal that you saw / like / support their toot 
Bookmarking is saving the toot far later

**Comment by MirceaKitsune** [comment]
@Dehelssey Sure. The icon could work in the same way still, completing the existing set. I imagine it would be more accessible this way to bookmark / unbookmark, as well as easier to see when you already bookmarked something (its icon is colored).

**Comment by Talkless** [comment]
+1 for bookmark button. No need to "spam" author with notifications as Favoriting does.

**Comment by ryliejamesthomas** [comment]
I've been using bookmarks a lot to save posts when I'm on my phone so I can look at them properly later in the web UI on desktop. But I'm finding it increasing annoying having to click on the '…' icon to unbookmark things in the bookmarks column.

**Comment by ryliejamesthomas** [comment]
Can be closed. Fixed in version 4!
