### ISSUE TITLE
Age of toots displayed incorrectly until page refreshed. 

### ISSUE THREAD

**Issue by DrewMcArthur** [mastodon/mastodon#15530]
### Expected behaviour

when viewing toots in any browser, the age should be displayed correctly even if the page has not refreshed recently.

e.g.  Page loads in browser, accurately displays age of a toot as 2h.  when i revisit the tab 5h later, the toot displays an age of 7h without requiring a refresh.

### Actual behaviour

Page loaded in browser, displayed a toot as 2h old. 5h later switch back to mastodon browser tab, toot's age is displayed as 2h old when the true difference from realtime to the time the post was created is 7h.  The inaccurate age is fixed when the page is reloaded.

### Steps to reproduce the problem

leave open a mastodon browser page long enough for the age of a displayed toot to go out of date.

### Specifications

`v3.3.0`

it is frontend, and safari but i think this is a cross-platform issue.  It's something i'd be happy to look into fixing for the app, as a small contribution.

**Comment by DrewMcArthur** [comment]
feel free to set me as the assignee :)

**Comment by vmstan** [comment]
Cannot duplicate with latest versions.
