### ISSUE TITLE
Profile Metadata Privacy Settings

### ISSUE THREAD

**Issue by trymeouteh** [mastodon/mastodon#15549]
Please add a setting to allow for your profile metadata to be visible to anyone, or to only your followers.

**Comment by vmstan** [comment]
Duplicate of https://github.com/mastodon/mastodon/issues/15548, https://github.com/mastodon/mastodon/issues/15549, https://github.com/mastodon/mastodon/issues/15550, https://github.com/mastodon/mastodon/issues/15551 and https://github.com/mastodon/mastodon/issues/15552
