### ISSUE TITLE
Tor & Onion Sites

### ISSUE THREAD

**Issue by trymeouteh** [mastodon/mastodon#15544]
Please allow for mastodon servers to work with Tor and allow you to connect or host an .onion mastodon instance. No need for the user that uses mastodon on a non-onion instance to be able to connect to an instance that is an onion instance.

**Comment by psjbeisler** [comment]
https://github.com/tootsuite/mastodon/issues/15501

**Comment by vmstan** [comment]
Close by https://github.com/mastodon/mastodon/pull/15560
