### ISSUE TITLE
Relaxing HTML sanitization for markup that reverses meaning

### ISSUE THREAD

**Issue by tateisu** [mastodon/mastodon#15554]
Mastodon does HTML sanitization when accepting remote posts.
However, removing the some markup reverses the meaning of the text.
Some markup should be acceptable such as :
- `<del>`
- `<s>`
- `<strike>`

### Motivation

Misskey has strike markup(Misskey flaverd markdown)
example: https://misskey.io/notes/8gytf5qwik
but when it is imported to Mastodon, it's markup is removed.

This is not a Misskey-specific issue. 
When assuming a federetable blog service, it is very troublesome that the meaning of the sentence changes significantly.

**Comment by trwnh** [comment]
#15311

**Comment by renchap** [comment]
Closing this as it has been implemented in #23913 ans will be released in 4.2.0
