### ISSUE TITLE
ARM64 docker image on Docker Hub

### ISSUE THREAD

**Issue by AaronDewes** [mastodon/mastodon#15598]
### Pitch

An arm64 image should be published on Docker Hub. I published it myself using GitHub actions (Example at https://github.com/AaronDewes2/mastodon)

### Motivation

ARM64 is used by the newer Apple Computers, and on the Raspberry Pi. I found this while trying to port mastodon to Umbrel, which runs on the Raspberry Pi.

**Comment by malicioustoker** [comment]
Ohhhh, is that why I was able to run Mastodon off the official docker image from my Mac mini with the M1 processor? :o

**Comment by AaronDewes** [comment]
> Mac mini with the M1 processor

AFAIK apple has a compatibility layer for amd64 apps

**Comment by AndrewKvalheim** [comment]
Looks like `linux/arm64` images are [published](https://hub.docker.com/r/tootsuite/mastodon/tags) as of `tootsuite/mastodon:v3.5.0`.

**Comment by technicalpickles** [comment]
Can this be closed now?
