### ISSUE TITLE
Restore alternate background color for direct messages

### ISSUE THREAD

**Issue by ClearlyClaire** [mastodon/mastodon#15593]
### Pitch

Before 3.3.0, Direct Messages had a different background color so they could be differentiated from non-DMs.

Since 3.3.0, DMs have been reintroduced in the home TL but the special background color has been removed. It should return.

### Motivation

While one can now differentiate a DM from a non-DM by looking at the recently-added privacy icon, this does not stand out as much as the background color change.

Furthermore, the new behavior may be anxiety-inducing to long-time users who were accustomed to the old behavior, as they could think they posted private information in a public toot (I have heard of this from several users).

**Comment by vmstan** [comment]
I *think* this can be closed as completed, as the background is different? @ClearlyClaire
