### ISSUE TITLE
Configuration button for "trending now"

### ISSUE THREAD

**Issue by alex-tee** [mastodon/mastodon#15617]
Add a configuration button ( :gear: ) on the top right of this screenshot to control the trending list. I'm not sure what options should be available but I at least want a "hide" option

![Screenshot from 2021-01-23 18-10-15](https://user-images.githubusercontent.com/3407655/105610232-83ac6600-5da6-11eb-9fc9-db0f25d71f6e.png)

### Motivation

I don't want to see the list of trending items, and some people might also want to customize the list it somehow

**Comment by Gargron** [comment]
You can disable it in preferences

**Comment by alex-tee** [comment]
ok thanks that did it. not sure if it would be a good idea to allow customization of the list (like time range) but if there would be any customizations I would expect a gear button somewhere in the screenshot above, along with the option to enable/disable it. feel free to close if you prefer to keep these kinds of things in the preferences
