### ISSUE TITLE
Drag and Drop link into compose box is not working on chrome based browsers

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon#15633]
### Expected behaviour

Link can be dropped into compose box

### Actual behaviour

Nothing happen

### Steps to reproduce the problem

1. Open mastodon web on chrome based browser
1. Drag and Drop a link(eg. toot's timestamp as permalink) onto a compose box
1. Nothing happens

Firefox is working, Chrome is not working

### Specifications

Mastodon v3.3.0
Ubuntu 20.04
Chrome Version 87.0.4280.141 (Official Build) (64-bit)
Brave Version 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)

**Comment by tribela** [comment]
Update:
It is working if compose form is not focused. Not working if focused.

**Comment by trwnh** [comment]
Tested working now, closing as stale

**Comment by benyamindsmith** [comment]
Hi this isn't working again.
