### ISSUE TITLE
Make published toots' privacy level visible in the UI

### ISSUE THREAD

**Issue by andrialexandrou** [mastodon/mastodon#1564]
So before I realized _that_ there were privacy settings, I think I posted some content to only local followers.

A friend has recently joined a new instance, and when viewing my profile from within his instance can only see 1 post, despite there being ~60. I would understand this discrepancy if _all_ my posts were for local only, but I know a lot of them were purposefully chosen Public. He is now able to see my new posts, but the discrepancy feels like a bug.

I am requesting this feature to troubleshoot the issue/behavior of federation myself, but also because I think it would be helpful to others. 

I do not know how in-depth a change it would be make the privacy setting editable after it has been posted ( I understand the implications, for instance, of not being able to delete/retract a toot once a separate instance has acquired it ), but thought I'd mention in case it could be done alongside this. 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mjankowski** [comment]
Is it accurate that your friend only sees (in his instance) the posts you made AFTER they started following you?

I believe that is expected behavior.

It might be interested to add an "when you follow someone, pull in X of their most recent posts" feature ... but that doesn't currently happen.

**Comment by andrialexandrou** [comment]
It was my estimation that that could be expected behavior, though if I chose many posts to be Public and he can only see one ( that I'd wager, if anything, would qualify as a DM to someone else ) -- not all of my public posts, not none of them ever -- seems to contradict expectation.

Even so, my request stands because it feels weird that I, as an author to a post, can't see what privacy setting I chose when creating something.

"Pull in recent posts" would be a neat feature @mjankowski, but is separate from this.

**Comment by Cassolotl** [comment]
We have privacy level indicators in the top-right corner of toots on dev.glitch.social and it's pretty great. :)

![screen shot 2018-02-26 at 22 20 41](https://user-images.githubusercontent.com/6607512/36698986-4fae592e-1b43-11e8-9d82-77807b20a981.png)
