### ISSUE TITLE
Integration: DeepSource

### ISSUE THREAD

**Issue by withshubh** [mastodon/mastodon#15688]
I ran DeepSource analysis on my fork of this repository and found some code quality issues. Have a look at the issues caught in this repository by DeepSource [here](https://deepsource.io/gh/withshubh/mastodon/issues/).

[DeepSource](https://deepsource.io/) is a code review automation tool that detects code quality issues and helps you to automatically fix some of them. You can use DeepSource to track test coverage, Detect problems in Dockerfiles, etc. in addition to detecting issues in code. 

The PR #15541 fixed some of the issues caught by DeepSource.

All the features of the DeepSource are mentioned [here](https://deepsource.io/features/).
I'd suggest you integrate DeepSource since it is free for Open Source projects forever.

Integrating DeepSource to continuously analyze your repository:
- Install DeepSource on your repository [here](https://deepsource.io/signup).
- Create `.deepsource.toml` configuration specific to this repo or use the configuration mentioned below which I used to run the analysis on the fork of this repo.
- Activate analysis [here](https://deepsource.io/gh/tootsuite/mastodon/).

```
version = 1

test_patterns = ["/app/javascript/mastodon/**/__tests__/**"]

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "jest"
  ]
```

**Comment by withshubh** [comment]
Update: PR #15541 merges the configuration file in this repository. You just need to signup and install DeepSource to continuously analyze the repo. :sparkling_heart:

**Comment by withshubh** [comment]
@Gargron :wave: Please have a look :eyes:

**Comment by Gargron** [comment]
I did it, I think

**Comment by withshubh** [comment]
> I did it, I think

Yes, you did. Thanks! 💖

I work at DeepSource so if you have any suggestions/feedback regarding our analyzer you can let me know. :sparkles:
