### ISSUE TITLE
KeyError: key not found: "OTP_SECRET"?

### ISSUE THREAD

**Issue by assignedgod** [mastodon/mastodon#15755]
Hi, I'm extremely new to all this, but I've been trying to migrate from digital ocean to my own machine, and while trying to run RAILS_ENV=production bundle exec rails assets:precompile to get all my assets together I get the following error message 
I am so so sorry if this is just a really simple problem, I'm quite new to all this

<details>
<summary>error log</summary>

```
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
rails aborted!
KeyError: key not found: "OTP_SECRET"
/home/mastodon/live/config/environments/production.rb:114:in `fetch'
/home/mastodon/live/config/environments/production.rb:114:in `block in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/railtie.rb:216:in `instance_eval'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/railtie.rb:216:in `configure'
/home/mastodon/live/config/environments/production.rb:1:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/engine.rb:608:in `block (2 levels) in <class:Engine>'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/engine.rb:607:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/engine.rb:607:in `block in <class:Engine>'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `instance_exec'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `run'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `call'
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each'
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `call'
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:60:in `run_initializers'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/application.rb:361:in `initialize!'
/home/mastodon/live/config/environment.rb:5:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/application.rb:337:in `require_environment!'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `invoke_prerequisites'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/command.rb:48:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/commands.rb:18:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => environment
```

</details>

**Comment by assignedgod** [comment]
So, I fixed this by writing a dummy value to production as already is done for development and test, but that led to a new problem 
mastodon@ubuntu:~/live$ RAILS_ENV=production bundle exec rails assets:precompile
rails aborted!
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit`
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/application.rb:585:in `validate_secret_key_base'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/application.rb:432:in `secret_key_base'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/devise-4.7.3/lib/devise/secret_key_finder.rb:24:in `key_exists?'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/devise-4.7.3/lib/devise/secret_key_finder.rb:16:in `find'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/devise-4.7.3/lib/devise/rails.rb:37:in `block in <class:Engine>'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `instance_exec'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `run'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/initializable.rb:60:in `run_initializers'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/application.rb:361:in `initialize!'
/home/mastodon/live/config/environment.rb:5:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/application.rb:337:in `require_environment!'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/command.rb:48:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/railties-5.2.4.4/lib/rails/commands.rb:18:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => environment
(See full trace by running task with --trace)
mastodon@ubuntu:~/live$ RAILS_ENV=production rails credentials:edit
Could not find nokogiri-1.10.10 in any of the sources
Run `bundle install` to install missing gems.
Or rather 2 problems, I cannot get Nokogiri to be shown despite having uninstalled and reinstalled a few times, any ideas?

**Comment by ClearlyClaire** [comment]
It seems like you have forgotten to copy your `.env.production` from your previous install.
As for nokogiri, have you run `bundle install`?

**Comment by assignedgod** [comment]
> 
> 
> It seems like you have forgotten to copy your `.env.production` from your previous install.
> As for nokogiri, have you run `bundle install`?

.env.production should be there, I copied the folder over and stuff, and I have run bundle install a few dozen times to try and get this to install, even trying to install it manually with gem install nokogiri, is it possible that I am missing something in my .env.production file and that being the issue?

**Comment by d0zingcat** [comment]
You could use `bundle exec rake mastodon:setup` to setup, and persistent the config file.
