### ISSUE TITLE
Add documentation for latest moderation options

### ISSUE THREAD

**Issue by leahoswald** [mastodon/mastodon#15772]
Currently there is not documentation about the latest moderation options. For example I can't find a word about the option "Limit" so I have no idea what they are actually doing. The more or less good moderation is one of the key features that makes mastodon more usable than twitter. But it looks like there is a lot of change and nobody thinks about documentation, this is really bad for instance administrators and mods. So please update the moderation docs.

![Screenshot2021-02-21_17-07-44](https://user-images.githubusercontent.com/1292551/108630921-b01bd680-7467-11eb-9100-7d39f0c0b3c1.png)

**Comment by ClearlyClaire** [comment]
For your information, “limit” is the new name for the “silence” functionality (means the user's actions don't generate notifications unless the user interacted with follows them, and the user's posts cannot have public visibility)

**Comment by Gargron** [comment]
It is suboptimal that you even need external documentation to be able to tell what the functions do. We should redesign the UI so that there are hints as to what each function does... Perhaps a radio button list with hints instead of dropdown on account action screen...

**Comment by ClearlyClaire** [comment]
What about something like this?
![image](https://user-images.githubusercontent.com/384364/108981754-572d8780-768d-11eb-8fa0-583527af4641.png)

**Comment by leahoswald** [comment]
Is fixed in a release since opening.
