### ISSUE TITLE
Please add gd locale

### ISSUE THREAD

**Issue by gunchleoc** [mastodon/mastodon#15826]
I'd like to start translating into gd on Crowdin. There's also a second language request in my topic: https://crowdin.com/project/mastodon/discussions/22

Locale: gd
Native name: Gàidhlig
English name: Scottish Gaelic

The other language requested is Afrikaans (af)

**Comment by 0-afflatus** [comment]
kw and bz would be good too. I guess I need to open a new ticket for that?

**Comment by gunchleoc** [comment]
Best and ask on Crowdin too. Are the projects active already? I'd be happy to help with the creating a branch & pull request. We'll need the native names of the languages.

**Comment by gunchleoc** [comment]
@0-afflatus Looks like kw is in but bz is not. Did you create a separate ticket? If so, this one could be closed.

**Comment by gunchleoc** [comment]
This has been done.
