### ISSUE TITLE
webp emoji support

### ISSUE THREAD

**Issue by FinecoFinit** [mastodon/mastodon#15846]
Less size, more resolution

**Comment by ClearlyClaire** [comment]
As far as I know, the reason for not supporting WebP attachments and emojis was because of iOS not supporting them. I think that has changed recently, so we may consider WebP support again.

**Comment by silverscat-3** [comment]
Great news, Apple has added support for Webp in Safari on iOS and macOS Big Sur and later.

https://caniuse.com/webp

The only thing that is no longer supported is Internet Explorer. (Who would want to use IE?)

So, I want to use webp to cope with Mastodon's unusually strict emoji capacity limit. webp compression efficiency is so great that it is more than enough to replace gif and png.

**Comment by tastytea** [comment]
Looks like this was addressed in <https://github.com/mastodon/mastodon/pull/18506>?

**Comment by nightpool** [comment]
Yes, resolved by #18506
