### ISSUE TITLE
Midnight is expressed as 24th hour instead of 0th hour

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#15855]
![image](https://user-images.githubusercontent.com/10606431/110281305-13e2eb00-7fa2-11eb-805e-55037fade608.png)

### Expected behaviour

Midnight should be 0:00, as is standard

### Actual behaviour

Midnight is 24:00, leading to confusion about date

**Comment by nightpool** [comment]
This is a bug in the JS standard: https://github.com/tc39/ecma402/pull/436 (although in practice it's mainly only a chrome bug)

**Comment by nightpool** [comment]
Fixed as of Chrome 124 https://issues.chromium.org/issues/42204487#comment8
