### ISSUE TITLE
Don't autofocus the compose form

### ISSUE THREAD

**Issue by raboof** [mastodon/mastodon#15862]
### Pitch

When opening a main page in a desktop browser, the cursor is automatically placed in the textarea of the compose form.

When using the keyboard for navigation (using a browser plugin like vimium or vim vixen, or just to hit 'space' to scroll down a page), you have remember to leave the field before using that.

### Motivation

Since you only visit the page to write a new post some of the time, I think it would be more natural to have nothing focused initially (and require the user to click or e.g. use 'tab' to focus the textarea)

**Comment by weex** [comment]
The pitch makes sense and certainly reading is more common than posting but I wonder if there's anyway to determine if its a net gain for users without an optional setting. Some UX research, even anecdotal experience might help gauge the value of this change.

**Comment by raboof** [comment]
> Some UX research, even anecdotal experience might help gauge the value of this change.

I got mostly positive reactions on the idea at https://merveilles.town/web/statuses/105854694617706696 , but I don't think anyone else but me has tried it.

Even more anecdotally, I still accidentally type 'f' and spaces into the textfield every now and then when using the default interface ;)

**Comment by raboof** [comment]
> Some UX research, even anecdotal experience might help gauge the value of this change.

It has been applied for a while to 17 instances, and at least nobody seems to have complained https://c4.social/@weex/107570727340573833

**Comment by paulpalinkas** [comment]
https://github.com/mastodon/mastodon/issues/19100
https://github.com/mastodon/mastodon/issues/11078

All of the bugs claiming the keyboard shortcuts don't work are expecting that the timeline be focused.  (There are many more duplicates of said bug.) 

I can't find another social media interface where initial keyboard focus is in a compose form.
