### ISSUE TITLE
[Feature Request] Indicate when image isn't full size

### ISSUE THREAD

**Issue by Mennaruuk** [mastodon/mastodon#15899]
There are images that I've come across where I thought that they were full size, until I coincidentally clicked on them and realized they were larger. Is there a way to make it easier to users that whatever image they're looking at isn't full size, and that they need to click on it to see the whole image?

[This is a perfect example](https://i.ibb.co/dm7tr0t/AAD324-CF-726-F-4-ED9-974-F-82-B80825-E30-E.jpg). One might think the meme ends at this picture. But when one clicks it, the meme is actually larger and continues.
![mastodon](https://user-images.githubusercontent.com/52135169/111078469-ea5b1f80-84cb-11eb-9d04-419b677d3f2b.jpg)

**Comment by vmstan** [comment]
@Mennaruuk I'm wondering how this may have changed for you with the way images are displayed in Mastodon 4.2?

**Comment by Mennaruuk** [comment]
Yes it's way better now. Images show in all their glory. Thank you!
