### ISSUE TITLE
[Feature Request] Improve defederation UX

### ISSUE THREAD

**Issue by inga-lovinde** [mastodon/mastodon#15890]
### Pitch

At the "New domain block" page in moderation UI, when moderator is going to suspend the instance, display some kind of warning that this will break the existing relationships between two instances, the number of these relationships, and some text clarifying the consequences of the block and listing some alternative options.

For example:

Current version:

![image](https://user-images.githubusercontent.com/52715130/111027343-f8d40900-83ef-11eb-970a-efd30c5e93f8.png)

Proposed version (draft):

![image](https://user-images.githubusercontent.com/52715130/111027729-64b77100-83f2-11eb-897b-a731ce657047.png)

There is a new block between "Domain" / "Severity" fields and "Private comment" field, containing the following text:

>  Note that there are 123 Mutual relations between [instance name] and mastodon.social, 456 Following relations from [instance name] to mastodon.social and 789 Followers relations from mastodon.social to [instance name]. Suspending mastodon.social will remove these relations.

> Suspending another instance is a big deal with a lot of far-reaching consequences for users of not only mastodon.social but [instance name] as well (such as rendering all mentions of users on mastodon.social useless, breaking the existing conversations with them, removing all bookmarks users of [instance name] might have had for posts on mastodon.social), and generally should only be done as a last resort. You might want to consider silencing mastodon.social or suspending specific users from mastodon.social instead. 

### Motivation

It seems that currently defederation is applied when other options would suffice, and that some moderators don't really know about far-reaching consequences that go with defederation.

This feature would provide them some useful context, and might help them to find some more appropriate moderation tools in some cases.

**Comment by ClearlyClaire** [comment]
I'm not too happy with how judgmental the second paragraph may sound, but reminding the admin about the number of existing relationships that would be severed might be a good idea, yeah.

**Comment by inga-lovinde** [comment]
> I'm not too happy with how judgmental the second paragraph may sound, but reminding the admin about the number of existing relationships that would be severed might be a good idea, yeah.

I'm not saying the text should be exactly like on screenshot.

The idea was to make it clear:
* How many relationships (and of what kinds) will be severed;
* What are the other implications;
* That there are alternative less-impactful options.

**Comment by joyeusenoelle** [comment]
Two thoughts:

1) At a minimum, the defederation UI should also display the total number of known accounts on the remote server (as the Federation UI does for instances that have already been limited): "This will affect at least `X` users on `example.com`...". In many cases this will be 0, either because my local instance has never interacted with a user from the remote instance before, or...

2) This is complicated by the fact that if, for instance, I am considering suspending `mastodon.example.com`, I can simply suspend `example.com` and Mastodon will block *all* subdomains of `example.com`. In this circumstance the proposed UI change will *necessarily* display "`0`" in every place where you've listed a number, because Mastodon can't possibly scan every possible subdomain of `example.com` to see if there are affected users. This could be remedied by combining the *known* subdomains of `example.com` - e.g. if Mastodon has seen 45 users on `mastodon.example.com` and 27 users on `pleroma.example.com`, and has only ever interacted with those two subdomains, it might say "This will affect at least 72 users on `example.com`...". But this may affect server performance if Mastodon has seen a large number of subdomains!

**Comment by inga-lovinde** [comment]
There is now a PR that will improve the situation documentation-wise https://github.com/mastodon/documentation/pull/1218 but I still think that it is worth it to explicitly mention the number of mutual relationships that will be severed by defederation / suspension.

Another related issue is #15891.

**Comment by digitalcircuit** [comment]
Is this closed by the merging of https://github.com/mastodon/mastodon/pull/25144 with that impact summary screen…?

**Comment by ClearlyClaire** [comment]
I think so, but I'll let @inga-lovinde judge whether that new confirmation screen is enough!

**Comment by inga-lovinde** [comment]
I totally missed that PR!
Thank you @ClearlyClaire , it looks much better now.

However, since you're asking...

1. I think that "subscriptions our users would lose" might be a better wording than "followers their users would lose"? Because when a moderator attempts to block another domain, they probably don't really worry or care about "their users"; my original idea was to highlight the impact it will have on one's own instance, not on the instance to be blocked.
2. It is not clear what "followers their users would lose" and "followers our users would lose" means; is this a number of users or a number of relationships? Suppose that local users A, B and C each are mutuals remote users X, Y and Z, all from the instance about to be blocked. Will the impact screen say that their and our users will lose 3 followers, or will it say 9 followers? I'd say that 9 more accurately reflects the degree of impact, but in any case it is not clear what exactly does the displayed number mean.
If a moderator sees 9, how should they interpret it? It can always mean "one of our users follows nine theirs", but can it mean "three of our users follow three theirs", or "nine of our users follow nine theirs"? The difference becomes more significant for large instances intensely federating with each other.
3. Unfortunately I cannot really understand what's going on in the code (I don't know Ruby), but it seems like the "Suspend" button is always active, even before "a possibly-slow-to-compute summary" was fetched from the server? Maybe it would make sense to block it (gray it out) while summary is loading.
4. Also the original idea was to additionally display the number of mutual relationships severed by defederation (implying that severing these relationships should warrant more caution than severing single-sided follow relationships). I understand that the confirmation page is already overloaded, but maybe this is the more important metric than "Accounts profiles this would delete" (which as I understand simply means "how many accounts from their instance did our instance ever encountered").
5. In your PR, there was a suggestion to mention limiting as the less destructive option. However, it was not implemented because the confirmation page is overloaded. However, maybe it would make sense to add a third button there? "Cancel" / "Limit" / "Suspend and remove". (Not sure about what wording would work there, though).

(Ideas above are mostly inspired by the recent events when the owner of mstdn.social (second largest instance on fedi by MAU) suspended mastodon.art because of the personal opinion, and undid the block 12 hours later, but of course the relationships were not restored automatically, threads will remain broken forever, and in order to manually restore relationships users would have to remember who exactly did they follow on mastodon.art and vice versa, which can be very difficult if they don't have recent enough backups of their following lists).

**Comment by ClearlyClaire** [comment]
> However, since you're asking...
> 
>     1. I think that "subscriptions our users would lose" might be a better wording than "followers their users would lose"? Because when a moderator attempts to block another domain, they probably don't really worry or care about "their users"; my original idea was to highlight the impact it will have on one's own instance, not on the instance to be blocked.

“Subscriptions our users would lose” sounds confusing: is that people they are following, or people they would be followed by? The current text has been workshoped quite a bit to avoid the confusion.

>     2. It is not clear what "followers their users would lose" and "followers our users would lose" means; is this a number of users or a number of relationships? Suppose that local users A, B and C each are mutuals remote users X, Y and Z, all from the instance about to be blocked. Will the impact screen say that their and our users will lose 3 followers, or will it say 9 followers? I'd say that 9 more accurately reflects the degree of impact, but in any case it is not clear what exactly does the displayed number mean.

It's the number of relationships.

>        If a moderator sees 9, how should they interpret it? It can always mean "one of our users follows nine theirs", but can it mean "three of our users follow three theirs", or "nine of our users follow nine theirs"? The difference becomes more significant for large instances intensely federating with each other.

I think we can't really display the full details of what is going on on a confirmation page.

>     3. Unfortunately I cannot really understand what's going on in the code (I don't know Ruby), but it seems like the "Suspend" button is always active, even before "a possibly-slow-to-compute summary" was fetched from the server? Maybe it would make sense to block it (gray it out) while summary is loading.

Being able to block before getting the summary is on purpose, because computing the summary can be *very* slow, and we don't want that to prevent an important moderation action.

>     4. Also the original idea was to additionally display the number of mutual relationships severed by defederation (implying that severing these relationships should warrant more caution than severing single-sided follow relationships). I understand that the confirmation page is already overloaded, but maybe this is the more important metric than "Accounts profiles this would delete" (which as I understand simply means "how many accounts from their instance did our instance ever encountered").

That is a good point, I'll think about it!

**Comment by inga-lovinde** [comment]
> “Subscriptions our users would lose” sounds confusing: is that people they are following, or people they would be followed by? The current text has been workshoped quite a bit to avoid the confusion.

I understand, and the current text is really clear, my only doubt about it is that it puts these to-be-severed relationships in the context of how it will harm "their" instance and "their" users, which is probably not really relevant to the one who is doing the block. So maybe it would be possible to reframe it somehow in the context of how it will harm "our" instance and "our" users.

> It's the number of relationships.

Great!

> I think we can't really display the full details of what is going on on a confirmation page.

I was worried that the number without an explanation might cause underestimation of impact, but now I see that this is not the case, so there is no pressing need to reword it :)

> Being able to block before getting the summary is on purpose, because computing the summary can be very slow, and we don't want that to prevent an important moderation action.

This makes me wonder, what does its performance depend on? Because if it depends on the number of relationships... then maybe the cases when computing the summary can be very slow are the exact same cases where extra caution around blocking is needed; while "our" instance would probably have close to none relationships with the proverbial nazi dot social, so hopefully computing the summary would be fast in this case and would not prevent an important moderation action?
(Again, this is based on mstdn.social / mastodon.art example... I'm just trying to think how this destructive thing could have been avoided.)

**Comment by ClearlyClaire** [comment]
> This makes me wonder, what does its performance depend on? Because if it depends on the number of relationships... then maybe the cases when computing the summary can be very slow are the exact same cases where extra caution around blocking is needed; while "our" instance would probably have close to none relationships with the proverbial nazi dot social, so hopefully computing the summary would be fast in this case and would not prevent an important moderation action?

It depends primarily on the number of known accounts on that domain, not the number of relationships. There have been servers flooding with countless accounts in the past, and it is imperative that this kind of scenario does not prevent the admins from blocking the domains in a timely fashion.

> (Again, this is based on mstdn.social / mastodon.art example... I'm just trying to think how this destructive thing could have been avoided.)

I think in this particular case, the summary would have been shown pretty quickly. And I'm not sure it would have made a difference.

**Comment by ThisIsMissEm** [comment]
Should this now be marked as complete, since there's been no action since Oct 2023, and no comments since Jun 2023?

**Comment by trwnh** [comment]
Fixed at least somewhat by #25144 -- please file a new issue for further specific improvements
