### ISSUE TITLE
Feature Request: "Approved" filter on hashtag moderation UI

### ISSUE THREAD

**Issue by Phroneris** [mastodon/mastodon#15947]
### Pitch

Currently, admin can browse hashtags filtering by review statuses as "all", "(not )reviewed", and "pending" on the hashtag moderation page.
How about adding "approved" filter there?
(And then "rejected" one must be also considerable...)

### Motivation

As time goes by, the amount of hashtags which rushed into that page gets larger and larger.
I would like to figure out which ones I and co-admins of my server have approved/rejected ever without resort to my distant memory.

**Comment by ThisIsMissEm** [comment]
This appears to now exist: `/admin/trends/tags?status=approved` in main. The change to add an approved filter was in https://github.com/mastodon/mastodon/pull/16917

@vmstan I think we can close this as completed?
