### ISSUE TITLE
Media Upload Enhancement

### ISSUE THREAD

**Issue by HolgerHuo** [mastodon/mastodon#16055]
Hi! 

It seems that when users upload a media, mastodon will first upload it directly to S3 storage (if configured) and redownload it then process it, and upload it again. It will be much better if we process the media once the file is uploaded to the server before it is uploaded to the S3 storage.

Also, the reuploading (to s3) could be slow sometimes and inconsistent with the progress bar on the UI. We may make it a background process and allow users to draft the status before the media is processed and then post it in the background by the server after the process completes.

### Motivation
The S3 storage will add another layer of latency when users upload large videos. And, the re-downloading process seems redundant and unnecessary.

Thanks for your developing&stay safe.

**Comment by Gargron** [comment]
Transformation happens in a different process and is not guaranteed to be on the same machine where the file was originally uploaded

**Comment by HolgerHuo** [comment]
I see that.
Sorry for my poor knowledge about the workers mechanism.

What about transforming in the background 🤔 Will it cause some conflicts?

**Comment by HolgerHuo** [comment]
BTW&Sorry again for my poor knowledge
> Transformation happens in a different process and is not guaranteed to be on the same machine where the file was originally uploaded
Are there any references that tell how to deploy mastodon sidekiq workers and puma instances to different machines? Is it only possible through docker?
And the two servers have a latency around 150ms. Will that have a impact on performance?
Thanks a lot!
