### ISSUE TITLE
Rename "follow" to "subscribe" (and corresponding nouns)

### ISSUE THREAD

**Issue by mc776** [mastodon/mastodon#16132]
### Pitch
Instead of "following" accounts, you "subscribe" to their posts which are then delivered to your tl.

### Motivation
As someone who's never used Twitter I've always found the "follow" language to be weird, like "these random strangers are now following you" and whatnot.

It's bothered me until this morning when it occurred to me that a person could also have a "following" of people, like a cult leader or something.

And now it bothers me even more.

I think "subscribing" to posts that people put up on the World Wide Web (or with a few subscriber-only side bits) is a bit more friendly and neutral.

(This is not intended to be suggested instead of any suggestion of allowing multiple levels of followers/subscribers, but in addition to that.)

EDIT: After posting this I was reminded that Tumblr uses the "follow" language and it doesn't bother me in the slightest. I'm not sure why my mind makes this distinction, but suspect it's got to do with Tumblr's moderation being a known element at all times, the relative notoriety of the shared posting culture (as opposed to the *very* different and often mutually unknown expectations between various fedi subcultures), and because, spam/marketing bots aside, I've only ever gotten follows from what appear to be people with similar interests who appear to genuinely want to see the kind of stuff I post or reblog.

**Comment by Muskworker** [comment]
> It's bothered me until this morning when it occurred to me that a person could also have a "following" of people, like a cult leader or something.

"Subscribe" has a similar problem — if I can claim I have a hundred subscribers, I feel that's as strong or even stronger a claim than claiming a hundred followers, especially to people unfamiliar with the platform who might think they are paying to join.  

If "follow" should be renamed, I would suggest "**watch**" and "**watchers**" as more neutral alternatives.  Claiming a hundred watchers is correctly a statement of your reach without implication of agreement.  

(It may also make more intuitive the anxiety people get for posting when there may potentially be a high number of people watching (see e.g. #1660) beyond what one might expect for "saying something in front of your followers/subscribers".)

**Comment by mc776** [comment]
I've thought about this on and off over the past 3 months since I posted this and I don't think there's anything conventionally used that's any meaningful improvement.

I'll close this issue.
