### ISSUE TITLE
Cannot connect to db in docker

### ISSUE THREAD

**Issue by SrAndromeda** [mastodon/mastodon#16135]
I was trying to deploy a mastodon instance for benchmarks bots development on a server i own (locally), it is running a VM with ubuntu bionic. I have read many tutorials online about doing it with docker or inside the VM itself, i am not very familiar with the db or ruby so i don´t want to touch anything, only deploy a stable version.

When i was following some instructions from [here](https://www.howtoforge.com/how-to-install-mastodon-social-network-with-docker-on-ubuntu-1804/) i run into an error with the conecction with de db, but i don´t know how to solve it, i look for some support online but no clue about what happends.

The error is:
![image](https://user-images.githubusercontent.com/40075928/116809720-bdc49b00-ab3f-11eb-866c-ff3bafa97f4e.png)

Also my docker-compose.yml is the same as in the repo, i don´t touch it only to remove the build order, because i am not touching any code. And my .env.production:
![image](https://user-images.githubusercontent.com/40075928/116809790-290e6d00-ab40-11eb-9bd8-f892311c716f.png)

I also tried writing "db" but it said couldn´t translate.

**Comment by Gargron** [comment]
DB_HOST has to be db

**Comment by SrAndromeda** [comment]
If you read the last sentence i said that if i write db on DB_HOST it says that cannot resolve host name

**Comment by Gargron** [comment]
I don’t know if something about Docker changed but docker-compose sets up the networking and that’s how you connect the containers, by their name in the docker-compose.yml file. localhost is wrong and won’t work because PostgreSQL is in another container.

**Comment by shleeable** [comment]
If you're using docker-compose, the hostname for the containers are the names
<img width="575" alt="image" src="https://user-images.githubusercontent.com/17537000/117804954-fc1e3080-b28a-11eb-824c-fa2f5effd76c.png">

so 
```
DB_HOST=db
REDIS_HOST=redis
etc
```

**Comment by SrAndromeda** [comment]
Here i post my .ev.production (obviusly i changed the name to upload it) and my docker-compose.yml.

[env_production.txt](https://github.com/tootsuite/mastodon/files/6508222/env_production.txt)

[docker-compose.txt](https://github.com/tootsuite/mastodon/files/6508226/docker-compose.txt)

Also de log that send me with the config said above
[log.txt](https://github.com/tootsuite/mastodon/files/6508291/log.txt)

I tried using the commit that are provided but im not understanding much of it

**Comment by FibreFoX** [comment]
@SrAndromeda 
> 
> Here i post my .ev.production (obviusly i changed the name to upload it) and my docker-compose.yml.
> 

you should never post files with your actual SECRETs 😨 or passwords, this is a public website

please change your passwords immediately

**Comment by FibreFoX** [comment]
Regarding the issue, I had problems today myself, because I tried to use Docker on a Windows machine, but the database never came up, due to permission-issues of the way how Docker for Desktop works on Windows.
