### ISSUE TITLE
Unable to easily view the larger avatar image

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#16224]
### Pitch
As mentioned in Discord, every few days, I click the avatar in Mastodon and it opens the profile when I've never ever wanted or expected this behavior. The mastodon avatar icon is much smaller than twitter as well which makes me MORE motivated to see a larger version of the avatar. which makes me more annoyed at the behavior.

### Motivation
Twitter works as I expect.
<img width="202" alt="image" src="https://user-images.githubusercontent.com/17537000/117907423-61b10200-b309-11eb-8c1b-5a7a319815d6.png">
Clicks avatar
<img width="795" alt="image" src="https://user-images.githubusercontent.com/17537000/117907453-6d042d80-b309-11eb-8c2d-92b08694abd8.png">

**Comment by mattcen** [comment]
@shleeable This has annoyed me for ages and I finally came to file a bug about it! Glad to see I'm not alone! :)
