### ISSUE TITLE
Show external urls a better view

### ISSUE THREAD

**Issue by AnonymousWebHacker** [mastodon/mastodon#16237]
When an example link (of a news item) is shared, it does not look aesthetically good compared to twitter.

Below I leave capture of differences.
![mastodon news](https://user-images.githubusercontent.com/43164089/118381323-20ab3d00-b5ea-11eb-9bc9-9c814f56fd3c.png)
![twitter news](https://user-images.githubusercontent.com/43164089/118381327-24d75a80-b5ea-11eb-987b-6b6c91445e87.png)
  
Could it be improved so that the link is complete like the one on twitter?

**Comment by AnonymousWebHacker** [comment]
This is the URL: https://actualidad.rt.com/actualidad/392209-cientificos-tiempo-evitar-asteroide-golpear-tierra

**Comment by weex** [comment]
Seems to be a design question. Authors know that adding images to their posts increases engagement and larger image display in Mastodon would honor that habit. (tested and og: tags seem to work fine)

**Comment by ChengduLittleA** [comment]
I second that. On mastodon web interface it just shows a small thumbnail and it's kinda meh compared to twitter, especially for me posting my artworks onto mastodon from my blog, would love a bigger `og:image` preview

**Comment by vmstan** [comment]
Closed by #26136
