### ISSUE TITLE
Docker-Compose Breaking upgrades

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#16250]
### Pitch
Docker-compose has not been upgraded in a long time. I'd love to upgrade from postgres 9.6 to 13.X, Redis to 6.0 to 6.X (that hardcode to 6.0 was a mistake), elasticsearch can be upgraded to 7.X.

There are also a number of other changes such as splitting the sidekiq queues into their own containers I would like to discuss.

### Motivation

Some of these changes will require migrating non-natively... so it will break

**Comment by AndrewKvalheim** [comment]
linking #16947, #19063
