### ISSUE TITLE
Preview card should cut preview picture if it’s too tall

### ISSUE THREAD

**Issue by ariasuni** [mastodon/mastodon#16310]
When generating a preview card, Mastodon generate a thumbnail with no height limit. If the picture for which a thumbnail is generated is very tall compared to its width, it results in a very tall thumbnail.

### Expected behaviour

[screenshot of a hand-modified page, with `max-height: 100px;`]
![image](https://user-images.githubusercontent.com/2446451/119386201-7d33e980-bcc7-11eb-8167-195db52eb6a3.png)

(it’s probably better to cut the picture to a better aspect ratio then generate a better quality thumbnail?)

### Actual behaviour

![image](https://user-images.githubusercontent.com/2446451/119385441-6b057b80-bcc6-11eb-8336-5613829b74dd.png)

Here the thumbnails is displayed as 100×1000px (while the thumbnail is really 40×400px, so it’s also really ugly).

See: https://mastodon.technology/@ariasuni/106291347454731440

### Steps to reproduce the problem

1. Put a link to a website with a very tall image in a public or unlisted post.
(for example: http://janinebd.fr/faire-faire-le-sale-boulot-sale-3-des-techniques-dautodefense-petty/)
2. Click on it, so that Mastodon generate the preview card.

### Specifications

Mastodon v3.3.0

**Comment by vmstan** [comment]
Preview card displays have been rewritten in 4.2, and using this provided link I can no longer duplicate this issue under the new configuration. Closing as fixed.
