### ISSUE TITLE
v3.4.1: warning: already initialized constant

### ISSUE THREAD

**Issue by hugogameiro** [mastodon/mastodon#16353]
When doing the upgrade to v3.4.1, running `RAILS_ENV=production bundle exec rails assets:precompile` or `RAILS_ENV=production bundle exec rails db:migrate` or in Docker `docker-compose run --rm web rails db:migrate` I am getting the following warnings:
```
/opt/ruby/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/opt/ruby/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/opt/ruby/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
```
This doesn't look like it breaks the upgrade and I see no issues on live v3.4.1.

**Comment by shleeable** [comment]
All docker installs will experience this error. So far, no idea if it's more than a warning. No side effects noticed yet.

**Comment by exstral** [comment]
Yes, I'm also seeing this over and over when running the local docker setup #16211 

Do we need to fix the bug in that gem or update it or whats the plan? :)

**Comment by ClearlyClaire** [comment]
https://github.com/ruby/net-imap/issues/16#issuecomment-803086765 seem to describe the issue accurately. Seems like most options available for now involve dropping support for Ruby 2.5, which I would like to avoid.

I am not aware of actual issues with this double-loading of net-protocol, though it's far from ideal and there could be issues I am unaware of.

**Comment by shleeable** [comment]
Death to Ruby 2.5!

**Comment by leadermontanus** [comment]
(For googleability):

If you try to follow fairly common instructions found on the web on how to set up Mastodon in Docker (e.g. https://www.alibabacloud.com/blog/how-to-install-mastodon-using-docker-on-alibaba-cloud-ecs_595049), this problem will "pollute" the secret strings generated with the "rake secrets" command. So `docker-compose run --rm mastodon_web bundle exec rake secret` will store something like this in the intermediate bash variable: 

*272abf59df29ef8e00e0ab204b12d4e09ebe9f743d5c7bb750b07b3549ba9f0e10a06120af758e08fdca84ff725f8b9abb958d9377e32822208d2bb5bdfed84**aas hereewas here** *  (The bold bit being the pollution)

The solution is to turn off warnings (as it says above, they are just warnings, not an error) by passing an env var to the Ruby commands being run inside the Docker image: `docker-compose run --rm -e RUBYOPT=-W0 mastodon_web bundle exec rake secret`

**Comment by ClearlyClaire** [comment]
Can someone affected by this try on current `main` branch? I believe with the recent update of the `nokogiri` gem and the `mini_portile2` gem (see https://github.com/flavorjones/mini_portile/commit/863da5eeb26e4c3b8f368be25f2fbc5f60a83a30), we aren't depending on the `net-protocol` gem anymore, and thus the definitions come the same place regardless of load order and ruby version.

**Comment by hugogameiro** [comment]
I can confirm that these warnings are no longer present in the current `main` branch. Thanks.
