### ISSUE TITLE
Settings page scrolling to top when a session is ended

### ISSUE THREAD

**Issue by bilfri** [mastodon/mastodon#16362]
How to reproduce:

- open a session on your phone
- open a session on your computer
- go to account -> account settings -> sessions
- press x on the oldest session
- observe that the pages scrolls to the top where it shows the 'the sessions was ended'-message
This is annoying when you want to close multiple sessions. Maybe the confirmation message could be shown where the ended session was before?

debug info: Firefox on Linux

that's it. thx for building this awesome app. <3

**Comment by ClearlyClaire** [comment]
In contrast with the WebUI, the settings interface is not a single-page application, so it doesn't “scroll to the top”, it merely loads a new page, and that is expected. I do not think there is any plan to make the settings interface a single-page app currently.

I guess another solution to your issue would be to have a way to manage sessions in bulk, with a checkbox besides sessions, for instance.

**Comment by bilfri** [comment]
Ah thx, for *clairifying* :smile:  Well it's just a suggestion - your option with the checkbox thing would work as well, I think.

**Comment by weex** [comment]
Another option is to include an anchor link when the page is loaded after form submission. For example: /auth/edit#sessions
