### ISSUE TITLE
Hashtag suggestions are pointlessly replacing CamelCase hashtags

### ISSUE THREAD

**Issue by FediVideos** [mastodon/mastodon#16449]
### Expected behaviour

When typing a hashtag in CamelCase, it should remain in CamelCase (as this is important for readability, especially for those using screen readers)

### Actual behaviour

If the CamelCase hashtag matches an existing hashtag, the auto-suggest feature is usually removing the CamelCase and making it all lower case

### Steps to reproduce the problem

1. Try to type a popular hashtag in CamelCase (for example DogsOfMastodon) 
2. Autosuggest box will appear, and will (probably) suggest the same tag but entirely lower case (dogsofmastodon)
3. When you press enter to get rid of the suggestion box, the hashtag has the CamelCase stripped out
...

This seems to be caused by suggestions being taken from whatever tags were first used on that instance. If an entirely lower case tag was used first, that is what ends up being suggested.

It would help a lot if the suggestion system simply did not replace a hashtag if the original text string and suggested text string is an exact match. This would (hopefully) leave the CamelCase as inputted by the user intact.

### Specifications

Mastodon v3.4.1
Firefox, Ubuntu

**Comment by mstdn** [comment]
This is the whole reason we are approving and editing hashtags by hand for the past year! It's a bunch of work but at least trending tags are getting much "prettier" and easier to read. 

Please automate this process :-)

**Comment by rkingett** [comment]
Yes! I wasted a lot of time editing hashtags before posting. If this were automated, that would make using the platform much better and less of a chore to output accessible content.

**Comment by algotruneman** [comment]
mstdn, does that mean the local server/instance is the primary (only?) repository for hashtag recommendations?

I wonder if a user-linked list could be given preference, allowing the recommendations to be first accessed from those a person has most often used. From that personal (cookie?) list, the suggestions could then cascade to the ones on the local server

**Comment by weex** [comment]
Workaround: Finish your tag with **space bar** instead of enter or tab (on 3.4.1)
