### ISSUE TITLE
Open Graph link previews are displayed widely different on public profile pages and in the timeline

### ISSUE THREAD

**Issue by phseiff** [mastodon/mastodon#16479]
### Expected behavior

They are displayed in the same way

### Actual behavior

They are displayed with a large image in the timeline and with a description text and with a cropped image on public profile pages

### Steps to reproduce the problem

I posted a link on mastodon.online to demonstrate the difference.

In the local timeline, it looks like this:

![image](https://user-images.githubusercontent.com/31518703/124907587-a34be980-dfe8-11eb-95b6-3f7383300570.png)
![image](https://user-images.githubusercontent.com/31518703/124907665-b959aa00-dfe8-11eb-93b6-d159122eb1bb.png)

On my public profile (the one you see when you right-clock a username and open it into a new tab), however, it looks like this:

![image](https://user-images.githubusercontent.com/31518703/124907825-e443fe00-dfe8-11eb-9580-696cdd526923.png)
![image](https://user-images.githubusercontent.com/31518703/124907886-f45bdd80-dfe8-11eb-9685-d8f4dc8bed7a.png)

I feel like this should either be unified reasonably, or depend on the `twitter:card` meta tag, if present (`summary` vs `summary_large_image`).

---

In case there is no interest in tackling this issue, I would appreciate if someone where to give me a small hint as to which parts of the code I'd have to read & modify to unify this in my own instance, because I wasn't able to locate the relevant code myself yet :smile: 

### Specifications

The screenshots I made to demonstrate this issue where taken on `mastodon.online`, which to my knowledge runs the newest version of mastodon (at the time of me writing this, at least).

I use Firefox on Ubuntu 18.04, though I heighly doubt this is relevant to this issue.

**Comment by davidmooreppf** [comment]
Just adding my thumbs-up for prioritizing this. New Mastodon users aren't going to understand why links don't have nice preview cards, as they do on commercial services like Twttr. 

Current behavior: Toots that include links from sites that have [Open Graph properties](https://docs.joinmastodon.org/entities/card/) are not displaying on the Mastodon.social or mastodon.xyz timelines with preview cards. 

Desired behavior: Toots with links should display with a preview card.

<img width="499" alt="Screen Shot 2022-10-30 at 11 56 14 AM" src="https://user-images.githubusercontent.com/116819/198891614-de66ba12-cc1a-4465-b3fe-8429a205e8b1.png">

<img width="569" alt="Screen Shot 2022-10-30 at 11 57 54 AM" src="https://user-images.githubusercontent.com/116819/198891606-71bab62b-2fd9-44ae-8a7e-ec6451918edb.png">

Thanks all! Open-source and libre software is wonderfully valuable and I realize resources are limited.

**Comment by j9t** [comment]
It seems these are two separate issues, no?

The first and original issue is about inconsistent or unexpected previews, the second one about some instances not supporting social markup at all? (Can reproduce: examples from [c.im](https://c.im/@frontenddogma/109286757390510971) vs. [mastodon.social](https://mastodon.social/@j9t/109287023290594264).)

@davidmooreppf, how about filing a separate issue, as that may be the bigger issue (at least on those instances)? Perhaps it’s relatively simple to fix, too, if it’s about running some update.

**Comment by davidmooreppf** [comment]
Happy to file another issue; it seems that this is the correct repo for the mastodon.social instance? 

Yes, it was the next day on mastodon.social that card previews appeared for two domains. No card preview appeared for a sample YouTube URL. Seems reasonable that new users would expect card previews for URLs with valid og tags to generate in real-time, before posting toot. 

<img width="572" alt="Screen Shot 2022-11-04 at 4 58 43 PM" src="https://user-images.githubusercontent.com/116819/200073868-866d8f06-a3e3-4788-ab04-0f642fd9cb93.png">

**Comment by ror3d** [comment]
This totally needs fixing, right now the links in many places emulate the "summary" card type from twitter, but use the opengraph information to populate the image, which has a large image and doesn't look good at all.
