### ISSUE TITLE
Web::PushNotificationWorker fail

### ISSUE THREAD

**Issue by OmmyZhang** [mastodon/mastodon#16497]
### Expected behaviour

push notification should work

### Actual behaviour

```
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT on https://fcm.googleapis.com/fcm/send/dfsauQP0pqc:APA91bGPDzMIWfzfZYGCId5-ULJnG-Zbb9eK_2NJBffkYsjaUpwmA7x_I2Y1U77sR...
```

### Steps to reproduce the problem

visit sidekiq when someone should have a new notification.

### Specifications

v3.4.1

**Comment by ClearlyClaire** [comment]
Do you happen to have a more complete backtrace?

**Comment by OmmyZhang** [comment]
Any suggestion on how to get a more complete backtrace? journalctl only show `WARN: Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT on ...` and it seems there's no push notification in development environment.

**Comment by ClearlyClaire** [comment]
aren't there a bunch of lines immediately surrounding this one?

**Comment by OmmyZhang** [comment]
```
<***> <***> bundle[767]: <***> pid=767 tid=28zi3 WARN: {"context":"Job raised exception","job":{"retry":5,"queue":"push","class":"Web::PushNotificationWorker","args":[2863,184787],"jid":"014cd29159d3caeddfcef58c","created_at":1626687531.7852788,"enqueued_at":1626687531.7854419},"jobstr":"{\"retry\":5,\"queue\":\"push\",\"class\":\"Web::PushNotificationWorker\",\"args\":[2863,184787],\"jid\":\"014cd29159d3caeddfcef58c\",\"created_at\":1626687531.7852788,\"enqueued_at\":1626687531.7854419}"}
<***> <***> bundle[767]: <***> pid=767 tid=28zi3 WARN: Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT on https://fcm.googleapis.com/fcm/send/<***>
```

Here're all related outputs I can find in jornalctl. Maybe it's just a warning so no more details? How can get more logs for failed sidekiq jobs?

**Comment by ClearlyClaire** [comment]
Hm, you could edit `app/workers/web/push_notification_worker.rb` to add `backtrace: true` to the `sidekiq_options` line, remove the `if ENV['BACKTRACE']` in `config/initializers/backtrace_silencers.rb` and increase `BACKTRACE_LIMIT` in `app/lib/sidekiq_error_handler.rb`, then restart `mastodon-sidekiq` and see if that error occurs again.

**Comment by OmmyZhang** [comment]
thanks

**Comment by ClearlyClaire** [comment]
oh, actually, those things are not why the backtrace is so short… it's line 62 of `app/lib/request.rb`, replace the whole line with `raise e`

**Comment by OmmyZhang** [comment]
> oh, actually, those things are not why the backtrace is so short… it's line 62 of `app/lib/request.rb`, replace the whole line with `raise e`

This seems not work for me. 

But I find the reason. It's not a problem of Mastodon but just my own fork. I modified `lib/mastodon/version.rb` , adding non-ascii characters in `suffix`. This problem disappears after I replace them with some English letters. （Although this didn't happen in lower version, it seems some thing changed）
