### ISSUE TITLE
Not work with translator in Edge

### ISSUE THREAD

**Issue by wsq003** [mastodon/mastodon#16509]
### Expected behaviour

should work

### Actual behaviour

not work

### Steps to reproduce the problem

1. Open latest Edge.
2. Open https://qoto.org/web/timelines/public
3. Right click on page choose Translate.
4. Scroll down.
5. Page not work and show error message.

### Specifications

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at gs (https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1103991)
    at wu (https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1117192)
    at t.unstable_runWithPriority (https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1137706)
    at Va (https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1062357)
    at _u (https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1115052)
    at su (https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1111206)
    at https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1062648
    at t.unstable_runWithPriority (https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1137706)
    at Va (https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1062357)
    at Ya (https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1062593)

Ki (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5411:106)
Mi (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6363:21)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2816:9)
Jj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6204:2)
Kj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5895:4)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2851:16)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2816:9)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2846:6)

**Comment by ClearlyClaire** [comment]
I invite you to try on an instance running 3.4.0 or 3.4.1, as qoto.org seem to be running a pretty outdated Mastodon version and #15611 has possibly fixed this issue.

**Comment by wsq003** [comment]
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.


Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at HTMLDivElement.removeChild (<anonymous>)
    at gs (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:1063734)
    at wu (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:1076935)
    at t.unstable_runWithPriority (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:1097449)
    at Qo (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:1022100)
    at _u (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:1074795)
    at su (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:1070949)
    at https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:1022391
    at t.unstable_runWithPriority (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:1097449)
    at Qo (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:1022100)


Ki (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5411:106)
Mi (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6363:21)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2816:9)
Jj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6204:2)
Kj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5895:4)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2851:16)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2816:9)

**Comment by wsq003** [comment]
Just tried mastodon.social which I believe should be the latest version. Same bug found.

**Comment by ClearlyClaire** [comment]
Yes, that's using the patches to mitigate for the Google Translate issues. Unfortunately, it seems those mitigations are not enough for Microsoft Translate on Edge. I can reproduce the issue. It will be difficult to track down but I will have a look.

**Comment by p37307** [comment]
This just occurred again while scrolling home when 'always translate German' is turned on. Please advise if I should do a new report. 

Latest official build for Windows 10
Microsoft Edge
Version 123.0.2420.53 (Official build) (64-bit)

Error report:
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
lc.onCommitFiberUnmount (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5136:122)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5222:6)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5263:6)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:61)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5263:6)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:61)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5258:6)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:61)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5258:6)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:61)

**Comment by ClearlyClaire** [comment]
Can you run the script from https://github.com/facebook/react/issues/11538#issuecomment-417504600 in the browser's console and:
1. check that it fixes the issue
2. report any “Cannot insert” or “Cannot remove” message from the browser's console?

**Comment by p37307** [comment]
> 2. report any “Cannot insert” or “Cannot remove” message from the browser's console?

@ClearlyClaire Neither of those and it hasn't happened again. Edge also updated from 123.0.2420.53 to 123.0.2420.65 from the time it happened by the time I tested.

**Comment by ClearlyClaire** [comment]
Alright! Let us know if that happens again!
