### ISSUE TITLE
Timeline Position/Sync API

### ISSUE THREAD

**Issue by mdrockwell** [mastodon/mastodon#16513]
### Pitch

It would be great if Mastodon had a built-in API that saves each user's timeline position. This would let Mastodon clients see what post the user was scrolled to last. This could be used as a cross-application timeline position sync system. So, no more scrolling past posts you've already seen when moving between applications or between devices.

### Motivation

This is a common feature among third-party iOS Twitter clients, which make it easy to jump between iPhone, iPad, and Mac without losing your place in the timeline.

Developers would benefit because they wouldn't need to build their own system for this and users would benefit because they could more gracefully transition between devices.

**Comment by Gargron** [comment]
See: https://docs.joinmastodon.org/methods/timelines/markers/
