### ISSUE TITLE
 Blocked host: <WEB_DOMAIN>

### ISSUE THREAD

**Issue by flosoft** [mastodon/mastodon#16521]
### Expected behaviour

It should load Mastodon.

### Actual behaviour

It throws an error, saying the host is blocked.

### Steps to reproduce the problem

Using an `.env.production` file with:
```
LOCAL_DOMAIN=domain.tld
WEB_DOMAIN=social.domain.tld
```

When trying to access Mastodon on social.domain.tld, the following error appears:

<img width="936" alt="Screenshot 2021-07-19 at 12 00 31" src="https://user-images.githubusercontent.com/602633/126142904-91e7a3b4-c3a4-49fc-878a-c19bcdc6c6f8.png">

### Specifications

I found this error in v3.4.1. v.3.3.0 was working fine with the exact same .env file.

I believe this is related to this PR: https://github.com/mastodon/mastodon/pull/16087

**Comment by nightpool** [comment]
"social.domain.tld" is not "social.florianjensen.com", which is the domain
you're trying to access. unless the snippet of .production.env you pasted
is incorrect?

**Comment by flosoft** [comment]
It would be the same. I just didn't edit the screenshot to omit the domain. So the real `.env.production` contains:
```
LOCAL_DOMAIN=florianjensen.com
WEB_DOMAIN=social.florianjensen.com
```

**Comment by nightpool** [comment]
What happens if you run `ENV["WEB_DOMAIN"]` in the rails console? What about `Rails.config.x.web_domain` and `Rails.config.hosts`?

**Comment by flosoft** [comment]
How can I get to the rails console in Docker?

**Comment by weex** [comment]
1. Get the container id from `docker ps`.
2. Connect to it with `docker exec -it b7a9f5eb6b85 sh` (replace b7a9f5eb6b85 with the id you get)
3. Then you can probably run the rails console with mastodon's `bin/rails`.

**Comment by flosoft** [comment]
```
$ rails console
Chewy console strategy is `urgent`
Loading production environment (Rails 5.2.4.4)
irb(main):001:0> ENV["WEB_DOMAIN"]
=> "social.florianjensen.com"
irb(main):002:0> Rails.config.x.web_domain
Traceback (most recent call last):
        1: from (irb):2
NoMethodError (undefined method `config' for Rails:Module)
Did you mean?  concerning
irb(main):003:0> Rails.config.hosts
Traceback (most recent call last):
        2: from (irb):2
        1: from (irb):3:in `rescue in irb_binding'
NoMethodError (undefined method `config' for Rails:Module)
Did you mean?  concerning
irb(main):004:0>
```

**Comment by nightpool** [comment]
Sorry, that should be Rails.configuration throughout

**Comment by flosoft** [comment]
So, this is weird. It didn't work when the docker-compose was running on MacOs, but I moved it to Linux and it all works.
```
irb(main):001:0> ENV["WEB_DOMAIN"]
=> "social.florianjensen.com"
irb(main):002:0> Rails.configuration.x.web_domain
=> "social.florianjensen.com"
irb(main):003:0> Rails.configuration.hosts
=> ["florianjensen.com", "social.florianjensen.com"]
```
