### ISSUE TITLE
Can't migrate account from one instance to another. 

### ISSUE THREAD

**Issue by ThatOneCalculator** [mastodon/mastodon#16564]
### Expected behaviour

My mastodon.lol account should have migrated to my voring.me account

### Actual behaviour

Get `is not an alias of this account` under the text field of my voring.me account, despite registering it as an alias.

### Steps to reproduce the problem

1. Add `thatonecalculator@mastodon.lol` as an account alias in my `voring.me` settings
2. Fill out `thatonecalculator@voring.me` and my password in the migration screen
3. Tap "MOVE FOLLOWERS"
4. Recieve error

### Specifications

voring.me is on 3.4.1, mastodon.lol is on 3.3.0. 
Firefox mobile on Android for the browser.

**Comment by ClearlyClaire** [comment]
There is a 24h-long cache that could potentially prevent `mastodon.lol` to be aware that your `voring.me` account points back to you. What happens if you retry now/in a few hours?

**Comment by ThatOneCalculator** [comment]
@ClearlyClaire just tried right now and still the same problem. :/

**Comment by ThatOneCalculator** [comment]
I should also add that I'm self hosting voring.me, hopefully I didn't mess up anything there .

**Comment by ClearlyClaire** [comment]
This is weird, `thatonecalculator@voring.me` does alias to `thatonecalculator@mastodon.lol`, so apart from the 24h-cache thing on `mastodon.lol`, moving from `mastodon.lol` to `voring.me` should work…

**Comment by ThatOneCalculator** [comment]
Seems it just needed time to work itself out, it now works ![](https://i.imgur.com/TKTay9a.jpg)
