### ISSUE TITLE
Reactivate account

### ISSUE THREAD

**Issue by AnonymousWebHacker** [mastodon/mastodon#16626]
### Pitch

A user of my instance for trying / wrong ..etc, gave him to delete his account, I get in the admission, as a suspended account.

I try later to register again and cannot. because your email is "supposedly in use".

Is there any way to release that email?

### Motivation

Reactivate account

**Comment by mthld** [comment]
> Is there any way to release that email?

Read the official documentation: https://docs.joinmastodon.org/admin/tootctl/#accounts, as mentioned from the *account* section:

```
RAILS_ENV=production bin/tootctl accounts create USERNAME --email EMAIL@MAIL.LOL --reattach
```

**Comment by AnonymousWebHacker** [comment]
@mthld  Thanks for your answer, I was seeing the link, but it can't solve the problem 

```
mastodon@mastodon:~/live$ RAILS_ENV=production bin/tootctl accounts create USERNAME --email whoami@azeroth.website --reattach --force
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
Failure/Error: email
    has already been taken

```

**Comment by ClearlyClaire** [comment]
> A user of my instance for trying / wrong ..etc, gave him to delete his account, I get in the admission, as a suspended account.

I don't understand if the account was deleted or suspended? Does the account still show up in the admin interface?
Note that suspending an account also bans their email address.

> it can't solve the problem
> 
> ```
> mastodon@mastodon:~/live$ RAILS_ENV=production bin/tootctl accounts create USERNAME --email whoami@azeroth.website --reattach --force
> /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
> /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
> /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
> /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
> /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
> /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
> Failure/Error: email
>     has already been taken
> ```

It seems you're using a *different* username than that of the account which is to be re-used. If you want to re-use the email address but with a different name, you can delete the old account with `tootctl accounts delete USERNAME`.

**Comment by AnonymousWebHacker** [comment]
### User data
Username: Skeep
mail: whoami@azeroth.website

### Deleting user
```
mastodon@mastodon:~/live$ RAILS_ENV=production bin/tootctl accounts delete Skeep
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
Deleting user with 0 statuses, this might take a while...
OK
```

Supposedly it was erased and everything ok. When I check the moderation, it keeps coming out, it never goes away.
I even try to register with his email and it goes out of use.
![Captura de pantalla de 2021-08-22 15-11-42](https://user-images.githubusercontent.com/43164089/130367279-d36f53b2-c084-42d9-88e6-57a5e3e64085.png)
![Captura de pantalla de 2021-08-22 15-11-15](https://user-images.githubusercontent.com/43164089/130367282-38b5b4cd-e18d-4ec1-8a3c-79939cef2f0e.png)
![Captura de pantalla de 2021-08-22 15-10-51](https://user-images.githubusercontent.com/43164089/130367283-f1f32473-0ff1-4049-872f-1aded8213bf4.png)

**Comment by ClearlyClaire** [comment]
Run, `User.where(email: 'whoami@azeroth.website')` in `RAILS_ENV=production bundle exec rails c`

**Comment by AnonymousWebHacker** [comment]
@ClearlyClaire 
```
mastodon@mastodon:~/live$ RAILS_ENV=production bundle exec rails c                                            
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
UserChewy console strategy is `urgent`
Loading production environment (Rails 6.1.3.2)
irb(main):001:0> User.where(email: 'whoami@azeroth.website')
=> #<ActiveRecord::Relation []>

```
The promt was left waiting as another command, I close it with exit, did not work

**Comment by ClearlyClaire** [comment]
Hm… alright, the email address has been blocked when you suspended it, then. Removing the block will be a bit annoying… open the Rails console (`RAILS_ENV=production bundle exec rails c`) and type the following:

```ruby
class EmailBlockFinder
  include EmailHelper
  def find(email)
    CanonicalEmailBlock.where(canonical_email_hash: email_to_canonical_email_hash(email))
  end
end
EmailBlockFinder.new.find('whoami@azeroth.website').map(&:reference_account)
EmailBlockFinder.new.find('whoami@azeroth.website').destroy_all
```

(please copy the output, it will help me debug things)

This should be enough, but I'm surprised at a few things here:
- I would have expected the error not to be “has already been taken” (but that is what the code does, it's a bit confusing)
- I would have expected `tootctl accounts delete Skeep` to also remove the email block, but it does not… maybe it'd need an extra option
- I would have expected an easy way to remove the email block… but there is none

**Comment by ClearlyClaire** [comment]
Oh, the root issue is #16498. I thought this would have been fixed in a release by now :grimacing:

**Comment by Flisk** [comment]
Please note that reactivating a user account in this fashion will cause issues when federating with some other ActivityPub implementations.

I reactivated an account on my Mastodon instance using `accounts create` with the `--reattach` flag as described above. The user was unable to interact with users on Pleroma instances that were aware of their account before the deletion. I had to contact the admins of those instances and ask them to manually re-enable the account in their instances, because Pleroma doesn't seem to allow for reactivation of deleted remote accounts.

Unfortunately I'm not ActivityPub-savvy enough to discern whether this kind of user reactivation violates the spec and shouldn't be done, or whether this is a bug in implementations that behave this way.

Another note: the follower/followed counts for the reactivated user were wrong and wouldn't update until I ran `tootctl cache recount accounts`.

**Comment by trwnh** [comment]
> Unfortunately I'm not ActivityPub-savvy enough to discern whether this kind of user reactivation violates the spec and shouldn't be done, or whether this is a bug in implementations that behave this way.

It's not a spec violation nor a "bug" per se, but it is an unhandled case. Likely what implementations would need to do is detect somehow that the user has been recreated and invalidate their old cache.

**Comment by vmstan** [comment]
Marked as fixed by https://github.com/mastodon/mastodon/pull/16644
