### ISSUE TITLE
Support .*webp

### ISSUE THREAD

**Issue by AnonymousWebHacker** [mastodon/mastodon#16624]
### Pitch

Mmastodon does not allow that type of file *webp

### Motivation

The telegram or whatsapp stikers are in * .webp and mastodon does not allow that type of file

**Comment by tribela** [comment]
Was added on #9879 and removed on #11589
I think it is OK to resupport webp now.

**Comment by AnonymousWebHacker** [comment]
I had not really dedicated myself to looking for any issuse related to this.

Thanks for the reference. :+1:

**Comment by sindastra** [comment]
This issue seems to be a duplicate of #13315

**Comment by Sushubh** [comment]
Not sure if I should file a bug report for this. But webp images do not seem to work with "Detect text from picture" functionality.
