### ISSUE TITLE
Could not find command "tootctl".

### ISSUE THREAD

**Issue by BedrockDigger** [mastodon/mastodon#16630]
### Expected behaviour

By running RAILS_ENV=production ./bin/tootctl tootctl accounts modify estel --disable-2fa, I expect mastodon would skip the extra security number verification via email and allow the account called "estel" login directly.

### Actual behaviour

tootctl returns "Could not find command 'tootctl'" and the security number verification is still required for the account "estel".

### Steps to reproduce the problem

1. Setup a mastodon instance without Docker following the official docs.
2. Add an admin account called `estel`.
2. Migrate the server to a new non-Docker instance following the official docs (using `pg_dump`, etc.).
4. Run `RAILS_ENV=production ./bin/tootctl tootctl accounts modify estel --disable-2fa`.
5. Full output:
``` shell
mastodon@VM-8-9-ubuntu:~/live$ RAILS_ENV=production ./bin/tootctl tootctl accounts modify estel --disable-2fa
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
Could not find command "tootctl".
```
**I noticed the "already initialized constant" error was already reported in #16353, but it seems that it isn't breaking anything.**

### Specifications

Release hash is d6486c969f4530444f7032c6893eaede2f4919e7, aka the official v3.4.1 tag.

**Comment by ClearlyClaire** [comment]
You repeated “tootctl” twice, type `./bin/tootctl accounts`, not `./bin/tootctl tootctl accounts`

**Comment by BedrockDigger** [comment]
> You repeated “tootctl” twice, type `./bin/tootctl accounts`, not `./bin/tootctl tootctl accounts`

Sorry, my bad 🙁
