### ISSUE TITLE
undefined symbol: EnsurePortalSnapshotExists when creating a toot

### ISSUE THREAD

**Issue by Sjors** [mastodon/mastodon#16631]
### Expected behaviour

It should have tooted

### Actual behaviour

The UI throws a cryptic "500" error, the server logs show an equally cryptic message

### Steps to reproduce the problem

Post a toot (reading toots still seems to work, as does starring other toots).

```
Aug 19 12:39:33 sjimmie bundle[1005172]: [a2318c82-5b86-4226-a442-e24eb80a45d0] method=POST path=/api/v1/statuses format=html controller=Api::V1::StatusesController action=create status=500 error='ActiveRecord::StatementInvalid: PG::UndefinedFile: ERROR:  could not load library "/usr/lib/postgresql/12/lib/plpgsql.so": /usr/lib/postgresql/12/lib/plpgsql.so: undefined symbol: EnsurePortalSnapshotExists
Aug 19 12:39:33 sjimmie bundle[1005172]: ' duration=54.68 view=0.00 db=12.93
Aug 19 12:39:33 sjimmie bundle[1005172]: [a2318c82-5b86-4226-a442-e24eb80a45d0]
Aug 19 12:39:33 sjimmie bundle[1005172]: [a2318c82-5b86-4226-a442-e24eb80a45d0] ActiveRecord::StatementInvalid (PG::UndefinedFile: ERROR:  could not load library "/usr/lib/postgresql/12/lib/plpgsql.so": /usr/lib/postgresql/12/lib/plpgsql.so: undefined symbol: EnsurePortalSnapshotExists
Aug 19 12:39:33 sjimmie bundle[1005172]: ):
Aug 19 12:39:33 sjimmie bundle[1005172]: [a2318c82-5b86-4226-a442-e24eb80a45d0]
Aug 19 12:39:33 sjimmie bundle[1005172]: [a2318c82-5b86-4226-a442-e24eb80a45d0] lib/mastodon/snowflake.rb:11:in `around_create'
Aug 19 12:39:33 sjimmie bundle[1005172]: [a2318c82-5b86-4226-a442-e24eb80a45d0] app/services/post_status_service.rb:66:in `block in process_status!'
Aug 19 12:39:33 sjimmie bundle[1005172]: [a2318c82-5b86-4226-a442-e24eb80a45d0] app/services/post_status_service.rb:65:in `process_status!'
Aug 19 12:39:33 sjimmie bundle[1005172]: [a2318c82-5b86-4226-a442-e24eb80a45d0] app/services/post_status_service.rb:38:in `call'
Aug 19 12:39:33 sjimmie bundle[1005172]: [a2318c82-5b86-4226-a442-e24eb80a45d0] app/controllers/api/v1/statuses_controller.rb:38:in `create'
Aug 19 12:39:33 sjimmie bundle[1005172]: [a2318c82-5b86-4226-a442-e24eb80a45d0] app/controllers/concerns/rate_limit_headers.rb:10:in `block in override_rate_limit_headers'
```

I only noticed this issue today. I was able to toot successfully on July 27th. I haven't touched my Mastodon installation in the time between that, but I have updated and rebooted the system several times. I did not touch Postgres settings (but perhaps an automatic update did).

This recent Postgres thread may be relevant: https://www.postgresql.org/message-id/CBED95D4-5072-4A16-9271-72AB73478817%40enterprisedb.com 

### Specifications

Mastodon v3.4.1 running on Ubuntu 20.04.2
Postgres 12.7
Ruby 2.7.2p137

**Comment by ClearlyClaire** [comment]
I am not quite sure the errors occurs on postgresql's server side or on the client library. In case this is the latter, it may be because system dependencies got updated but ruby modules still linked against older versions of those. To fix such an issue, I'd try `bundle install --force` then restart Mastodon services.

**Comment by mthld** [comment]
Got exactly the same error since upgrading to the latest 13.4 Postgres version.

Mastodon v3.4.0 running on Debian 10 Buster
Postgres v13.4 running on Alpine Linux 3.14.1
Ruby v2.7.2p137

**Comment by ClearlyClaire** [comment]
I'm not sure what could be causing this. It sounds like a mismatch between postgres libraries, maybe the system update went wrong, or the postgres server did not get restarted after upgrade?

**Comment by mthld** [comment]
> I'm not sure what could be causing this. It sounds like a mismatch between postgres libraries, maybe the system update went wrong, or the postgres server did not get restarted after upgrade?

The update went through seamlessly but I thought that the server was automatically restarted after the changes were applied. Obviously it wasn't, doing it manually fixed the issue. Thanks for your help! 💕

**Comment by Sjors** [comment]
Interestingly this error went away as randomly as it appeared. If it happens again I'll try the `bundle install --force` suggestion above.

**Comment by ClearlyClaire** [comment]
@Sjors I think all that was needed was to restart postgres. I'll close the issue but feel free to reopen it if it occurs again.

**Comment by vanbockryck** [comment]
I encountered the same issue.

There was a mismatch between the running postgresql server and a lib (lib-version was one point release further than running server) - probably due to a problem with a previous update/restart.

Restarting the server resolved the issue.
