### ISSUE TITLE
Streaming Service does not start | NodeJS | Debian Bullseye

### ISSUE THREAD

**Issue by LevelXStudiosorg** [mastodon/mastodon#16662]
### Expected behaviour

Mastodon Streaming is working

### Actual behaviour

mastodon-streaming Service does not start

### Steps to reproduce the problem

1. Upgrade Debian Buster(10) to Bullseye(11)
2. Restart the Mastodon Instance

### Specifications

Hello Mastodon developers,
Today we updated our system from Debian Buster to Bullseye. As you surely know, Python2.X support has been dropped as well. In the course of this, NodeJS version 12 was logically also removed from the system due to the missing package "python-minimal". During our research, we noticed that NodeJS cannot currently be installed on a Debian system. [See the following ticket: https://github.com/nodesource/distributions/issues/1254

On the one hand, we would like to ask here if you have a helpful tip for us on how to get our instance online again, and if or when support for a higher version of NodeJS might come, since even if the installation problem is solved, the dependencies on Python2 will probably continue to prevent NodeJS version12 from being installed and thus operation on Debian would no longer be possible.

With kind regards
Christopher from LevelXStudios
![Screenshot_1](https://user-images.githubusercontent.com/88385120/131106900-ecc53d8a-fe8b-4496-a04c-9659465e10ae.png)

**Comment by ClearlyClaire** [comment]
I don't think that should be considered a Mastodon bug if NodeJS provided packages do not install on a given distribution…

**Comment by nightpool** [comment]
I believe we support Node 14 as of earlier this month. From your screenshot, it doesn't look like your system has node installed at all. If you install Node 14 and Mastodon still doesn't work, please feel free to open a new issue.

**Comment by LevelXStudiosorg** [comment]
I am well aware that it is not a real bug. However, it may be a problem that could arise if you follow the installation routine from the documentation.

Even if the issue has been closed, I would like to add that a new package has already been released for NodeJS which could be installed without problems. The package is now called: nodejs_12.22.6-deb-1nodesource1_amd64.deb and can be installed under Bullseye without problems. With this, the "problem" has more or less been solved. I just wanted to add it for the sake of completeness and would like to ask you to close here again.
