### ISSUE TITLE
Toots are not clickable in public timeline view

### ISSUE THREAD

**Issue by Olf0** [mastodon/mastodon#16663]
### Expected behaviour
Toots are clickable in the public timeline view of a Mastodon account, opening that specific Toot with all its replies displayed below it.

### Actual behaviour
Nothing: Clicking on a Toot in the public timeline view of a Mastodon account is futile.

### Steps to reproduce the problem
1. Click on any regular text of a Toot in the public timeline view of a Mastodon account, e.g. at https://mastodon.social/@Gargron
2. In contrast to that, if one is logged in at Mastodon, and looks at own or somebody else's Toots in the tree column view, every Toot is clickable (as expected).
3. This is inconsistent, between the two Mastodon views (public and when logged in) and compared to Twitter (where every Tweet is clickable in any view).
4. As a workaround, one can click on the post date in the upper right corner of a Toot (in all views), which achieves the expected effect: That Toot is opened, and all its replies are displayed below it.
5. But as there is no hint indicating this workaround, many users assume, that this functionality is not present at Mastodon.

### Specifications
Mastodon server version 3.4.1

Irrelevant side note: Browser used for testing is Firefox 78.13.0esr

**Comment by kevintraver** [comment]
Is this still an issue? It appears to be fixed now.

**Comment by Olf0** [comment]
Thank you for addressing and checking this.  Triggered buy your message I also re-checked this issue on a recent Mastodon-Server release, and you are right: This issue was fixed meanwhile.
