### ISSUE TITLE
Cannot send mail anymore (SMTP, Mailgun)

### ISSUE THREAD

**Issue by mstdn** [mastodon/mastodon#16669]
### Expected behaviour

It worked a few days ago without changes.

### Actual behaviour

Mastodon is not sending anymore emails.

### Steps to reproduce the problem

Meow there,

Since the whole FiveM GTA issue thing mstdn.social is "stuck" on the main branch. As of 2 days ago the system cannot send anymore emails and I have zero clue why.. We have not updated in the past week nor made any changes, I get the following error with sidekiq-mailers in grep:

Aug 28 14:28:46 mstdn.social bundle[5195]: [ActiveJob] [ActionMailer::MailDeliveryJob] [e26cef58-cd00-441f-8f2f-7d6f1467ea0a] Delivered mail 612a2bfe96c85_144b3cd0c103482@mstdn.social (47.0ms)
Aug 28 14:28:46 mstdn.social bundle[5195]: [ActiveJob] [ActionMailer::MailDeliveryJob] [e26cef58-cd00-441f-8f2f-7d6f1467ea0a] Error performing ActionMailer::MailDeliveryJob (Job ID: e26cef58-cd00-441f-8f2f-7d6f1467ea0a) from Sidekiq(default) in 176.99ms: SocketError (getaddrinfo: Temporary failure in name resolution):
Aug 28 14:28:46 mstdn.social bundle[5195]: /home/mastodon/.rbenv/versions/2.7.4/lib/ruby/2.7.0/net/smtp.rb:539:in `initialize'
Aug 28 14:28:46 mstdn.social bundle[5195]: /home/mastodon/.rbenv/versions/2.7.4/lib/ruby/2.7.0/net/smtp.rb:539:in `open'
Aug 28 14:28:46 mstdn.social bundle[5195]: /home/mastodon/.rbenv/versions/2.7.4/lib/ruby/2.7.0/net/smtp.rb:539:in `tcp_socket'
Aug 28 14:28:46 mstdn.social bundle[5195]: /home/mastodon/.rbenv/versions/2.7.4/lib/ruby/2.7.0/net/smtp.rb:549:in `block in do_start'
Aug 28 14:28:46 mstdn.social bundle[5195]: /home/mastodon/.rbenv/versions/2.7.4/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
Aug 28 14:28:46 mstdn.social bundle[5195]: /home/mastodon/.rbenv/versions/2.7.4/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
Aug 28 14:28:46 mstdn.social bundle[5195]: /home/mastodon/.rbenv/versions/2.7.4/lib/ruby/2.7.0/net/smtp.rb:548:in `do_start'
Aug 28 14:28:46 mstdn.social bundle[5195]: /home/mastodon/.rbenv/versions/2.7.4/lib/ruby/2.7.0/net/smtp.rb:518:in `start'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.1.4/lib/action_mailer/base.rb:559:in `block in deliver_mail'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/notifications.rb:203:in `block in instrument'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/notifications.rb:203:in `instrument'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.1.4/lib/action_mailer/base.rb:557:in `deliver_mail'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.1.4/lib/action_mailer/message_delivery.rb:119:in `block in deliver_now'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.1.4/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.1.4/lib/action_mailer/message_delivery.rb:118:in `deliver_now'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/actionmailer-6.1.4/lib/action_mailer/mail_delivery_job.rb:23:in `perform'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.4/lib/active_job/execution.rb:48:in `block in perform_now'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/i18n-1.8.10/lib/i18n.rb:314:in `with_locale'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.4/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:126:in `instance_exec'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.4/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:126:in `instance_exec'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.4/lib/active_job/instrumentation.rb:21:in `block in instrument'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/notifications.rb:203:in `block in instrument'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/notifications.rb:203:in `instrument'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.4/lib/active_job/instrumentation.rb:31:in `instrument'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.4/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:126:in `instance_exec'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.4/lib/active_job/logging.rb:22:in `block in tag_logger'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/tagged_logging.rb:99:in `block in tagged'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/tagged_logging.rb:37:in `tagged'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/tagged_logging.rb:99:in `tagged'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.4/lib/active_job/logging.rb:22:in `tag_logger'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.4/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:126:in `instance_exec'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:137:in `run_callbacks'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.4/lib/active_job/execution.rb:47:in `perform_now'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.4/lib/active_job/execution.rb:25:in `block in execute'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.4/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/execution_wrapper.rb:88:in `wrap'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/reloader.rb:72:in `block in wrap'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/execution_wrapper.rb:84:in `wrap'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/reloader.rb:71:in `wrap'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.4/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:126:in `instance_exec'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/callbacks.rb:137:in `run_callbacks'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.4/lib/active_job/execution.rb:23:in `execute'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.4/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:196:in `execute_job'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-unique-jobs-7.1.5/lib/sidekiq_unique_jobs/middleware.rb:36:in `call'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/app/lib/sidekiq_error_handler.rb:7:in `call'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:143:in `invoke'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:163:in `block in process'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/job_retry.rb:112:in `local'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/rails.rb:14:in `block in call'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/execution_wrapper.rb:88:in `wrap'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/reloader.rb:72:in `block in wrap'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/execution_wrapper.rb:88:in `wrap'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4/lib/active_support/reloader.rb:71:in `wrap'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/rails.rb:13:in `call'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:257:in `stats'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/job_logger.rb:13:in `call'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/job_retry.rb:79:in `global'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/logger.rb:11:in `with'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/job_logger.rb:33:in `prepare'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:123:in `dispatch'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:162:in `process'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:78:in `process_one'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:68:in `run'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:43:in `watchdog'
Aug 28 14:28:46 mstdn.social bundle[5195]: /mnt/mstdn/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:52:in `block in safe_thread'
Aug 28 14:28:46 mstdn.social bundle[5195]: 2021-08-28T12:28:46.788Z pid=5195 tid=5emf class=ActionMailer::MailDeliveryJob jid=de19bb1a0c3950232e26254f elapsed=0.187 INFO: fail

LOG HERE: https://git.stuxhost.com/-/snippets/6

Does this indicate an issue with Mastodon smtp itself or..? 

Please help me and (mstdn.social) out with this issue <3

### Specifications

Our latest commits: 

https://git.stuxhost.com/mastodon/mstdn/-/commits/main

**Comment by mstdn** [comment]
This fixed the issue:
https://medium.com/@ahmadb/fixing-dns-issues-in-ubuntu-18-04-lts-bd4f9ca56620

**Comment by xvilo** [comment]
To add @mstdn; This was an issue on Mailguns' side. Someone at Mailgun had published a DS record without the zone being secure. So that was the case of you, and a lot of others, not being able to connect to them anymore!
