### ISSUE TITLE
duplicate key error while self-destruct

### ISSUE THREAD

**Issue by YJSoft** [mastodon/mastodon#16684]
### Expected behaviour

self-destruct command successfully ended

### Actual behaviour

duplicate key value violates unique constraint error occured

### Steps to reproduce the problem

1. Try to self-destruct instance

Error log from self-destruct run : [index_error.txt](https://github.com/mastodon/mastodon/files/7085219/index_error.txt)

duplicate key value violates unique constraint "index_canonical_email_blocks_on_canonical_email_hash"

### Specifications

Version 3.4.1

**Comment by ClearlyClaire** [comment]
This should be fixed in #16455

**Comment by YJSoft** [comment]
Ah, it's already fixed. I have searched for issues with keyword `index_canonical_email_blocks_on_canonical_email_hash`. but I found nothing.
