### ISSUE TITLE
Cannot add WebAuthn security keys with Firefox

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#16694]
### Expected behaviour

I can add my WebAuthn security keys successfully

### Actual behaviour

After putting in my PIN and tapping my finger to the security key, the page doesn't refresh, and nothing happens.

### Steps to reproduce the problem

1. Go to Settings > Account > Two-factor Auth
2. Make sure a TOTP Authenticator app is added to your account, so that Security keys becomes a valid option
3. Click Add
4. Enter your PIN and touch the security key

### Specifications

Windows 10, Firefox = doesn't work. Nothing happens.
Windows 10, Chrome = works fine. Page refreshes after touching security key and Mastodon registers it fine. I can login with it even in Firefox after this -- I just can't add any new security keys in Firefox.

**Comment by ClearlyClaire** [comment]
I am unable to reproduce the issue (Debian testing, Firefox 108.0, YubiKey 5 NFC)

**Comment by Bondarz** [comment]
> I am unable to reproduce the issue (Debian testing, Firefox 108.0, YubiKey 5 NFC)

In the meantime, it also works for me.
Firefox 108.0.1 Windows 10
Yubikey 5 NFC

**Comment by trwnh** [comment]
Hm, probably some bug in Firefox that got fixed?
