### ISSUE TITLE
IDN search not being processed

### ISSUE THREAD

**Issue by tigransimonyan** [mastodon/mastodon#16691]
### Expected behaviour

Find someone from another instance with a unicode domain

### Actual behaviour

Search not being processed

### Steps to reproduce the problem

1. write @tigran@անքուն.հայ in the search box
2. no result

### Specifications

macOS Catalina, Firefox 90.0.2, Mastodon v3.4.1

**Comment by ClearlyClaire** [comment]
Works whenever the account is already known to the instance. Initial discovery would be fixed by #16689

**Comment by tigransimonyan** [comment]
cool. thank you!
