### ISSUE TITLE
Can’t Login to mastodon iOS app, showing “Security verification failed. Are you blocking cookies?”

### ISSUE THREAD

**Issue by lessgoo00** [mastodon/mastodon#16770]
### Expected behaviour

I should’ve logged in to the mastodon iOS app

### Actual behaviour

Instead of logging in, I got this error (Security verification failed. Are you blocking cookies?) and couldn’t login no matter how many times I tried.

### Steps to reproduce the problem

1. Download mastodon iOS app
2. Open mastodon iOS app
3. Click on sign in
4. Choose your instance
5. Try singing in

### Specifications

OS: iPadOS 14.7.1

**Comment by Gargron** [comment]
Do you have cookies disabled in Safari settings?

**Comment by lessgoo00** [comment]
I was. It’s still showing the same thing even after I turned it off, however

**Comment by Gargron** [comment]
I don't know if it maybe requires restarting the app to take effect. At the very least you need to reload the login page within the Safari view.

**Comment by lessgoo00** [comment]
> I don't know if it maybe requires restarting the app to take effect. At the very least you need to reload the login page within the Safari view.

Thanks, that fixed it!
