### ISSUE TITLE
Big issues but unknow bug

### ISSUE THREAD

**Issue by solagg1** [mastodon/mastodon#16796]
### Expected behaviour

alway

### Actual behaviour

blank page and broken css

### Steps to reproduce the problem

please check the site is live https://solagg.com
<img width="2549" alt="Screen Shot 2021-09-29 at 8 17 33 PM" src="https://user-images.githubusercontent.com/91405435/135276506-da7e9be9-90fa-43cf-bbf7-440cb22195b2.png">

...
https://solagg.com/about

### Specifications

check it here
https://solagg.com/about

**Comment by solagg1** [comment]
<img width="2528" alt="Screen Shot 2021-09-29 at 9 10 12 PM" src="https://user-images.githubusercontent.com/91405435/135285567-30a2bcd7-a34a-4f02-bb4e-ddc5ae7d9fe2.png">
please check the red in debug

**Comment by Gargron** [comment]
1. This is not a bug, but user error (installation instructions were not followed correctly)
2. Troubleshooting questions are not answered in GitHub issues
3. The problem looks to already be resolved
3. Your server seems to be used for pushing a dubious cryptocurrency using spam messages and follows

Closing and locking thread.
