### ISSUE TITLE
Wrong user profile opened in WebUI, from boosted post

### ISSUE THREAD

**Issue by lindwurm** [mastodon/mastodon#16799]
### Expected behaviour

When click "Bob boosted" in timeline, open Bob's profile in WebUI

### Actual behaviour

When click "Bob boosted" in timeline, open Alice's profile (original post author) in WebUI

### Steps to reproduce the problem

<img width="415" alt="issue" src="https://user-images.githubusercontent.com/1874549/135462364-55531b3e-1bfd-40c0-9756-2cfba8cba9f9.png">

### Specifications

- found this bug when merge `mastodon:main` ( 24f9ea781850ee8d105aa3e396eaef8499bc5efc )
- another server (running 2b18f7a9436c29ff948b1c1fe9b777435d1b03c1 ) is not affected
- open link in external window/tab is okay (`href` is bob's profile url)

**Comment by hinaloe** [comment]
The profile (Alice) click and the reblog user (Bob) click both use the same `handleAccountClick`. However, the part that determines the clicked element seems to have been lost in #16171.

https://github.com/mastodon/mastodon/blob/9c9290768190d412e5b3d65502ee5d0d30596412/app/javascript/mastodon/components/status.js#L169
