### ISSUE TITLE
Mastodon blank page after logged on

### ISSUE THREAD

**Issue by solagg1** [mastodon/mastodon#16801]
### Expected behaviour

I got trouble with blank page after logged on 

### Actual behaviour

I got trouble with blank page after logged on but other link still can access to domain.com/settings

### Steps to reproduce the problem

I got trouble with blank page after logged on but other link still can access to domain.com/settings

### Specifications

I got trouble with blank page after logged on but other link still can access to domain.com/settings

**Comment by ClearlyClaire** [comment]
Closing for pretty much the same reasons as https://github.com/mastodon/mastodon/issues/16796#issuecomment-930748506
