### ISSUE TITLE
Line height not based on font size

### ISSUE THREAD

**Issue by Altreus** [mastodon/mastodon#1680]
I've increased the minimum font size in my browser, but masto's line-height is `20px` instead of the common `1.5em` or similar. That means that now all my fonts are squished up.

Minor change, but great for accessibility if it can be tweaked.

* * * *

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by expenses** [comment]
Which component are you referring to specifically? Can you take a screenshot?

**Comment by Altreus** [comment]
Anywhere really. If I set my minimum font size to 14pt the text reads fine, but if I increase it to 20pt the line-height doesn't adjust (because it's absolute) and therefore the lines of text get all cramped or get clipped by the bounding box.

![masto-nromal](https://cloud.githubusercontent.com/assets/74533/26053260/092c9620-3960-11e7-87bb-bb916e01e4ef.png)
![masto-squished](https://cloud.githubusercontent.com/assets/74533/26053261/093f8b5e-3960-11e7-8190-8e003e720a68.png)

**Comment by mjankowski** [comment]
Closing on assumption that this is resolved in newer versions. Can you re-open with current screenshots if still problem in 4.3?
