### ISSUE TITLE
Add clear indication for replies

### ISSUE THREAD

**Issue by Brawaru** [mastodon/mastodon#16824]
### Pitch

Unlike Twitter, Mastodon shows replies in feed as single post entities, whereas the first shows slice of context. That is very confusing, but sometimes you can distinguish replies from normal posts since they contain the **@​mentions**.

I understand that because Mastodon is not a centralised entity it will be harder to obtain slices in context, but there's a simple solution for now — showing a pre-text that the post below is a reply, the same way it's done for reposts.

![Screenshot of two Mastodon posts (from bottom to top): Admin posts ‘Are you insane?’; followed by ‘Admin replied in a thread’, Admin: ‘Yes.’](https://user-images.githubusercontent.com/10401817/136554590-8b218f65-599a-4abb-a00c-b0c5a2fa585f.png)

### Motivation

This issue is getting only more relevant since Smithereen has joined the fediverse family, and replies from there have no way to be distinguished whatsoever:

![Screenshot of reply by Gregory Klyushnikov (@grishka@friends.grishka.me) \[in Russian\] received by Mastodon from Smithereen: there's no indication or sings that this is a reply.](https://user-images.githubusercontent.com/10401817/136556101-46f499a5-c0d6-42f2-b5c0-7d013be3f7b6.png)

Getting at least such simple implementation would be really helpful, especially in such case.

**Comment by trwnh** [comment]
Done in 4.0 -- I think this issue can be closed? 
![image](https://user-images.githubusercontent.com/10606431/201582382-877b98fa-453f-4dfc-8447-20a75e06be23.png)

**Comment by Brawaru** [comment]
Indeed. Thanks for the reminder! 🚀
