### ISSUE TITLE
Outgoing emails from localhost are being marked as spam or not arriving

### ISSUE THREAD

**Issue by mossymossmoss** [mastodon/mastodon#16850]
### Expected behaviour

Outgoing notification emails (eg. verification) should  appear in user's inbox

### Actual behaviour

Outgoing notification emails only appear in user's spam and, in some cases, not at all.

### Steps to reproduce the problem

1. Set domain name record `A` to server IP. Set domain name record `TXT` to `v=spf1 ip4:[SEVER IP] -all`, replacing `[SERVER IP]` with actual server IP
2. Follow the steps to installation under https://docs.joinmastodon.org/admin/install/
3. When running the setup wizard, go with default mail settings but choose to have the instance send notification emails from localhost
4. Attempt to signup, see that verification email does not appear in inbox

### Specifications

Mastodon v3.4.1
Godaddy domain name
DigitalOcean hosting

**Comment by blackfireburn** [comment]
What email service are you sending to. It maybe a reputation issue if the domain is unknown or new to the service.

**Comment by mossymossmoss** [comment]
It appears that my domain has been placed on a blocklist, due to the fact that I am being hosted on DigitalOcean. This is not a problem with Mastodon, apologies
