### ISSUE TITLE
Add AVIF file support 

### ISSUE THREAD

**Issue by MyNameIsTroll** [mastodon/mastodon#16855]
### Pitch

The AVIF image format is now supported by most modern browsers like Chrome 85+, FIrefox 93+, Opera 71+ etc...  
Apparently only Safari does not currently support it.  :/

Android 12 adds a native support of AVIF, Microsoft adds the support to the update "19H1".
GIMP support :
https://www-gimp-org.translate.goog/news/2020/10/07/gimp-2-10-22-released/?_x_tr_sl=auto&_x_tr_tl=fr&_x_tr_hl=fr&_x_tr_pto=nui

Facebook ( AVIF images can be uploaded to facebook ):
https://www-reddit-com.translate.goog/r/AV1/comments/kohgbu/avif_images_can_be_uploaded_to_facebook/?_x_tr_sl=auto&_x_tr_tl=fr&_x_tr_hl=fr&_x_tr_pto=nui

Compare the gain:
https://jakearchibald.com/2020/avif-has-landed/

https://avif.io
![image](https://user-images.githubusercontent.com/31790025/137474367-da20a6a2-5a72-4361-98cb-55105b29cca1.png)
![image](https://user-images.githubusercontent.com/31790025/137474305-d5d67fbd-d702-4b95-9794-19c6c8f006b4.png)
![image](https://user-images.githubusercontent.com/31790025/137474262-4844bd5c-4ce7-4932-b7da-3d80f0ff49d4.png)
![image](https://user-images.githubusercontent.com/31790025/137474405-d6e3c095-30b3-4dae-84d6-5d34ad09a07c.png)

Sam Sneddon’s comment on the WebKit AVIF decoding support ticket :
https://bugs.webkit.org/show_bug.cgi?id=207750#c25

### Motivation

The gain in image weight is quite significant and could free up a lot of disk space for instances. Considering the performance and the growing support, it would be surprising if Apple did not implement it. 
It would be a good idea to start thinking about its implementation in Mastodon.

**Comment by BuyMyMojo** [comment]
AVIF support might still be slow but the actual video format that it is derived from, AV1, is supported enough for youtube to start serving video in the format, it could be beneficial for both bandwidth and video quality to support this format

![opera_PeA0aMWOjQ](https://user-images.githubusercontent.com/46948241/165739900-2626b08c-f34b-4363-8183-cea8384c9cf5.png)

**Comment by Morxemplum** [comment]
Good news. MacOS and iOS are supporting AVIF in macOS Ventura / iOS 16. Minus Edge, this means that all major browsers support AVIF. 
![image](https://user-images.githubusercontent.com/44561540/197704030-98bb2616-0947-4481-b7b8-11baa469e50a.png)

**Comment by txt-file** [comment]
I am very sad that HEIC is now supported while I still can't upload royalty-free AVIF files.

https://github.com/mastodon/mastodon/pull/19618

**Comment by Saiv46** [comment]
@txt-file You can close this issue

**Comment by txt-file** [comment]
@Saiv46 No I can not as I am not author of this issue. @MyNameIsTroll needs to close it. Or somebody from the @mastodon team.

**Comment by MaciekBaron** [comment]
Closing as resolved
