### ISSUE TITLE
Logging out of a single device logs me out from all other devices

### ISSUE THREAD

**Issue by vachan-maker** [mastodon/mastodon#16889]
### Expected behaviour

If I log out from a device, I should not be logged out from other devices.

### Actual behaviour

I was logged out from other devices (mobile)

### Steps to reproduce the problem

1. Log out from mastodon

### Specifications

Mastodon version: 3.4.1
Browser: Firefox 93

**Comment by ClearlyClaire** [comment]
Fixed in main and 3.4.2
