### ISSUE TITLE
Hashtag results number misleading

### ISSUE THREAD

**Issue by FediVideos** [mastodon/mastodon#16891]
### Expected behaviour

Searching for hashtags should display number of posts with that tag

### Actual behaviour

Searching for hashtags displays number of very recent posts with that tag

### Steps to reproduce the problem

1. Search for hashtag drupal on a major instance like mastodon.social
2. Results will be list of hashtags all containing word drupal, with 0 next to all of them
3. New users will assume this means 0 results for that hashtag and may not bother clicking on them
...

Posting this as a bug as just had a new user who searched for drupal on mastodon.social and thought there were no hits at all, because the number next to each tag said 0, so this is not expected behaviour.

Maybe it would be easiest and clearest to just have the graph, and no number at all? The graph is much better at conveying that it only shows recent trends. The number can be highly misleading.

### Specifications

Mastodon.social so it's the latest version, v3.4.1

![DrupalExample](https://user-images.githubusercontent.com/75383929/138598930-151f8d5c-8b7b-4549-8731-27bd54525940.png)

**Comment by naught101** [comment]
I think the issue of irrelevant tags showing up in the search is covered at #17494 

Not sure about the other issue.

**Comment by naught101** [comment]
Actually, I'm not sure that this is a bug so much as a translation issue. I think the problem is that the graph displays the number of tag uses in the last 7 days, but the text reports only the number of users using the tag in last 2 days. See the english text:

![image](https://user-images.githubusercontent.com/167164/204995838-d764b09f-b202-4e72-9ea7-b8ed039036b2.png)

**Comment by FediVideos** [comment]
Okay, this seems to have been fixed some time ago, well done developers! 👏  Apologies for not closing sooner.
