### ISSUE TITLE
Make welcome email fit for current follow recommendation feature

### ISSUE THREAD

**Issue by heguro** [mastodon/mastodon#16919]
### Pitch

Replace or remove this sentence in welcome email to fit current follow recommendation feature:
> You follow your server's admin(s) by default.

https://github.com/mastodon/mastodon/blob/884c60002e3a6f6ee3814d3f3634738bda607dc3/config/locales/en.yml#L1495
https://github.com/mastodon/mastodon/blob/884c60002e3a6f6ee3814d3f3634738bda607dc3/app/views/user_mailer/welcome.text.erb#L27
https://github.com/mastodon/mastodon/blob/884c60002e3a6f6ee3814d3f3634738bda607dc3/app/views/user_mailer/welcome.html.haml#L140

### Motivation

It is inconsistent with latest (>3.4.0.rc1) Mastodon, because this feature is removed in #15945.

**Comment by vmstan** [comment]
Closing as this is no longer in the welcome email.
