### ISSUE TITLE
WebAuthn keys cannot be setup without setting up TOTP first

### ISSUE THREAD

**Issue by Be-ing** [mastodon/mastodon#16916]
### Expected behaviour

server.domain/settings/two_factor_authentication_methods should allow adding WebAuthn security keys

### Actual behaviour

The option to add WebAuthn security keys is not shown until TOTP is enabled.

### Steps to reproduce the problem

1. In settings, go to Account > Two-factor Auth
2. See prompt to setup TOTP with no option to add FIDO2 WebAuthn keys
3. Setup TOTP
4. In settings, go to Account > Two-factor Auth.
5. Now an option appears to edit security keys

### Specifications

Mastodon 3.4.1

**Comment by trwnh** [comment]
Duplicate of #16693

**Comment by Be-ing** [comment]
Closing as duplicate of #16693
