### ISSUE TITLE
[Maintainability] Switch from Yarn to npm

### ISSUE THREAD

**Issue by brawaru** [mastodon/mastodon#16918]
### Pitch

Yarn used to be a beast when it came out, putting npm in shambles in terms of performance, especially when working with many dependencies. However, a lot of time has passed since then and npm has improved a lot. Even Yarn itself got upgraded to the second version which now has to be installed per-project, putting first version in maintenance mode, where it will no longer receive any major updates.

I believe it's worth switching Yarn for npm to at least slightly improve Mastodon maintainability and keep it on up-to-date stack.

### Motivation

- npm nowadays provides performance on pair or significantly better compared to Yarn. In my tests on Mastodon codebase it was able to beat Yarn by a margin of about 45 seconds or more (in all runs including no-cache and no-lockfile (and both)).

- Yarn has strange bugs. One that occurred to me a lot is when it would freeze telling ‘There appears to be trouble with your network connection. Retrying...’, while everything works just fine. It then will sit a long time doing nothing, until either exiting with error or continue as normal.

- It's another package to install (system-wide or through npm global packages) and additional lines in image files.

- It's not well maintained anymore, all focus is on the second version of Yarn which is a lot more confusing to use and has even more bugs. The documentation site for classic Yarn will now even barely open (confirmed with different browsers and even through a VPN).

- Yarn's utilities like `why` if one needs them can be replaced by separate packages like [`npm-why`](https://npm.im/npm-why). So it's not a major benefit.

- npm has `npm ci` command to use in continuous integrations to significantly improve installation time of packages, heavily utilising the lock file.

**Comment by shleeable** [comment]
https://github.com/mixmaxhq/deyarn

**Comment by vmstan** [comment]
This was evaluated by the team but decided to upgrade to Yarn 4 for the time being.

**Comment by brawaru** [comment]
I mean Yarn 4 is far far better than legacy Yarn, so that's still a great change! I'm curious though as to why pnpm did not work for Mastodon... Is there any explanation anywhere?

**Comment by vmstan** [comment]
@renchap did the work to port things to Yarn 3 (then 4), npm, and pnpm, and they were all tested, ultimately I think Yarn 4 won out due to ease of migrating existing deployment.
