### ISSUE TITLE
Can't login after updating from v3.4.1 to v3.4.2

### ISSUE THREAD

**Issue by Neustrashimy** [mastodon/mastodon#16944]
### Expected behaviour

Login to Mastodon with no error.

### Actual behaviour

Can't Login to Mastodon. Server returns HTTP/500 Internal Error.

### Steps to reproduce the problem

1. Updating Mastodon ftom  v3.4.1 to v3.4.2 (tag)

```bash
$ git fetch && git checkout v3.4.2
$ bundle install && yarn install
$ RAILS_ENV=production bundle exec rails db:migrate
$ RAILS_ENV=production bundle exec rails assets:clobber
$ RAILS_ENV=production bundle exec rails assets:precompile

(Restart Mastodon processes)
```
git fetch, git checkout and bundle install, yarn install were completes with no errors.
but, db:migrate, assets:clobber, assets:precompile shows some warnings. 
please refer: [db-migrate_and_assets.log](https://github.com/mastodon/mastodon/files/7489863/db-migrate_and_assets.log)

2. Reload browser (still login state, in this time, can post toots and upload images)
3. Logout Mastodon
4. Attempt to login Mastodon as Another user
3. Browser shows Mastodon's error page, Found HTTP/500 Error in Browser's developer console.

Error log in `journalctl -u mastodon-web` ,
please refer: [mastodon-web.log](https://github.com/mastodon/mastodon/files/7489866/mastodon-web.log)

### Specifications

- Linux fedora core 31 with 2GB RAM
- Non-docker
- PostgreSQL 11.8
- ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
- Mastodon v3.4.1 to v3.4.2 (tag release)

**Comment by Gargron** [comment]
Fixed in 3.4.3
