### ISSUE TITLE
Unknown primary key for table accounts in model Account.

### ISSUE THREAD

**Issue by tsia** [mastodon/mastodon#16950]
### Expected behaviour

no error message

### Actual behaviour

error message

### Steps to reproduce the problem

i updated mastodon to 4.3.4 via the usual ways (non-docker)
after that i also updated to debian 11 and postgresql 13. however even with postgresql 11 i have the same issue
after restarting all mastodon services i'm not able to log in again. i just get the 502 error page.
in the log files i can find this error:
```
Nov 06 18:31:49 mastodon bundle[11247]: [49ba63db-2493-432a-9d48-61b3144de5e6] method=GET path=/@tsia format=html controller=AccountsController action=show status=500 error='ActiveRecord::UnknownPrimaryKey: Unknown primary key for table accounts in model Account.' duration=209.63 view=0.00 db=140.72
Nov 06 18:31:49 mastodon bundle[11247]: [49ba63db-2493-432a-9d48-61b3144de5e6]
Nov 06 18:31:49 mastodon bundle[11247]: [49ba63db-2493-432a-9d48-61b3144de5e6] ActiveRecord::UnknownPrimaryKey (Unknown primary key for table accounts in model Account.):
Nov 06 18:31:49 mastodon bundle[11247]: [49ba63db-2493-432a-9d48-61b3144de5e6]
Nov 06 18:31:49 mastodon bundle[11247]: [49ba63db-2493-432a-9d48-61b3144de5e6] app/models/account.rb:123:in `user_pending?'
Nov 06 18:31:49 mastodon bundle[11247]: [49ba63db-2493-432a-9d48-61b3144de5e6] app/controllers/concerns/account_owned_concern.rb:28:in `check_account_approval'
Nov 06 18:31:49 mastodon bundle[11247]: [49ba63db-2493-432a-9d48-61b3144de5e6] app/controllers/concerns/localized.rb:16:in `block in set_locale'
Nov 06 18:31:49 mastodon bundle[11247]: [49ba63db-2493-432a-9d48-61b3144de5e6] app/controllers/concerns/localized.rb:15:in `set_locale'
```

i found these issues but nothing in there helped:
* #6043
* #9953

### Specifications

v4.3.4 (Tag)

**Comment by Gargron** [comment]
Do you still have all the data in the database? How did you upgrade PostgreSQL?

**Comment by tsia** [comment]
data in the database seems intact. i noticed the `users` table is empty but `conversations` for example is filled with about 3 million rows.

debian update installed postgres 13 while keeping postgres 11 running. i then did `pg_upgrade`, shut down mastodon and postgres 11 and then started postgres 13 and mastodon.

if i wasn't completely stupid the PG11 data was completely untouched but i get the same errors when i start the PG11 instance back up and try to start mastodon

**Comment by Gargron** [comment]
I don't know what went down there but the `users` table obviously shouldn't be empty. I would maybe think of restoring from a backup at this point. I think `pg_upgrade` might have done something wrong.

**Comment by tsia** [comment]
ok, i'll see what my backups have to offer. Thanks anyway!
