### ISSUE TITLE
Please push v3.4.3 to Docker Hub

### ISSUE THREAD

**Issue by ericlathrop** [mastodon/mastodon#16952]
### Expected behaviour

v3.4.3 should exist on https://hub.docker.com/r/tootsuite/mastodon/tags

### Actual behaviour

v3.4.1 is the last version to be published

### Steps to reproduce the problem

1. Try to install the lastest version from Docker Hub
2. See that latest version is v3.4.1, which is old

### Specifications

v3.4.3

**Comment by mthie** [comment]
Why is this still a manual process for such a large project?

**Comment by Gargron** [comment]
It wasn’t. Docker Hub changed their pricing plans and silently stopped automated builds that we had.

**Comment by steinhobelgruen** [comment]
So, the recommended solution/workaround is now to build our own docker images?

**Comment by unasuke** [comment]
How about to use GitHub Container Registry?

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by f0086** [comment]
Is there any update on this?
The PR #16973 is merged but does not work (only the ```edge``` tag is updated).

**Comment by unasuke** [comment]
Yes, that's right. Those pull requests (#16973 , #16980) affect future tags but existing tags are not. To fetch v3.4.2 and v3.4.3 images are required to build and push manually by who has push permission to hub.docker.com.

**Comment by f0086** [comment]
> To fetch v3.4.2 and v3.4.3 images are required to build and push manually by who has push permission to hub.docker.com.

Nobody here with push permissions?

**Comment by Gargron** [comment]
I have push permissions but don't have a Docker environment configured as I don't use Docker anymore. We're planning to release v3.4.4 within the next few days at which point the new image will be pushed to Docker Hub automatically.

**Comment by f0086** [comment]
This issue can be closed now, it resolved itself :)
