### ISSUE TITLE
Separate mentioning from toot context to something else, like likes, replies, etc.



### ISSUE THREAD

**Issue by d4f5409d** [mastodon/mastodon#16957]
Like on Twitter.  Just because we could keep a better track of the thread/toots without flooding the toot context with mentions.

**Comment by Gargron** [comment]
I did not like this change when Twitter did it. Mentions are a simple mechanic. Putting them away elsewhere will make it harder for people to keep track of who's getting pinged.

**Comment by d4f5409d** [comment]
No. It's the complete opposite. Now they are filled up in our toots, and if there are 10+ people mentioned, it's a complete mess. You could argue about it, but it is. This is why would it be better to make something like a dropdown menu for the mentions, containing all of the people, without any mess and with order. If somebody is curious about the toot, only checks toot (content). But, if somebody wants to check mentions, they just click on the menu. (The menu could contain 1-2 or 3 mentions without clicking on the dropdown.)
Please. Do us a favor. :)

**Comment by trwnh** [comment]
why mention 10+ people? there's a reason these kinds of things are called "hellthreads". the ui discouraging mentioning a ton of people is a feature imo.

with that said, other software might not include mentions in the `content` field, so a feature i *might* support is having a way to see a list of everyone addressed. but this shouldn't replace the existing mentions ux.

**Comment by d4f5409d** [comment]
Because it's a big thread/conversation?

**Comment by d4f5409d** [comment]
Mastodon won't compete with big players, if we let this platform go in the other direction.
