### ISSUE TITLE
PreviewCard for some sites is not displayed

### ISSUE THREAD

**Issue by abcang** [mastodon/mastodon#16955]
### Expected behaviour

PreviewCard will be displayed.

### Actual behaviour

PreviewCard is not displayed.

### Steps to reproduce the problem

1. Include `https://official.fanbox.cc/` in your post.
2. Check the ID of that post.
3. Open the LinkCrawlWorker job of the corresponding ID from the morgue page of the sidekiq administration ( `/sidekiq/morgue`).
4. You can see that the error `no implicit conversion of String into Integer` is displayed.

### Specifications

This is a test post.
https://testingmstdn.abcang.net/@abcang/107241694706037663

Main branch after #16938
![image](https://user-images.githubusercontent.com/4199439/140751253-cea1a530-71fa-4d73-8ffd-0e6d91a15a3f.png)

Mastodon v3.4.1:
![image](https://user-images.githubusercontent.com/4199439/140752094-3035d097-312f-49df-b443-25dae02140f2.png)

I checked the structured data and found that it is an array. Therefore, access to the structured data is failing.

**Comment by ClearlyClaire** [comment]
Assigned to avoid duplicate work as he is working on a PR that includes a fix for that issue
