### ISSUE TITLE
Reserve usernames on mastodon instance

### ISSUE THREAD

**Issue by wiligl** [mastodon/mastodon#16975]
### Pitch

I propose to define usernames with a regular expression, for example, "admin.*" to make them unavailable for regular users registering at the instance.

### Motivation

To minimize the risk of abuse.

**Comment by Gargron** [comment]
It's already a thing: https://github.com/mastodon/mastodon/blob/main/config/settings.yml#L55-L63

**Comment by wiligl** [comment]
Hej Gargron, well it's a start, I would like to reserve all user names based on a regular expression, ie all "admin.*" usernames, eg admin, admin1, admin2, ...  etc. Otherwise these similar names could be misused. Does this exist yet? If not, can someone please implement?
