### ISSUE TITLE
Federation with Lemmy

### ISSUE THREAD

**Issue by Nutomic** [mastodon/mastodon#16974]
### Pitch

Hi, i'm one of the maintainers of [Lemmy](https://join-lemmy.org/). At the moment I am making Activitypub federation work between Pleroma and Lemmy. As a side effect of that, federation between Mastodon and Lemmy is also starting to work. 

So far, Mastodon can already fetch users, posts and comments from Lemmy, and comments from Mastodon federate to Lemmy ([see here](https://ds9.lemmy.ml/post/1724/comment/2214)).

The problems I noticed so far are:

- Mastodon cant fetch a `Group` from Lemmy when inserting the url in the sarch. This is probably because it makes a webfinger request, which is completely unnecessary as it already has the url. The webfinger request it sends looks like `https://ds9.lemmy.ml/.well-known/webfinger?resource=acct:main@ds9.lemmy.ml`, which doesnt work because for group actors, Lemmy does webfinger under `resource=group:main@ds9.lemmy.ml` (so that it is possible to have a user and community with the same name).

- Comments and private messages from Lemmy fail to get delivered to Mastodon. For private messages, this is probably because we are using the [ChatMessage](https://docs.pleroma.social/backend/development/ap_extensions/#chatmessages) type from Pleroma. Not sure what the problem with comments is.

You can also join our [dev chat on Matrix](https://matrix.to/#/#lemmydev:matrix.org) to discuss this.

### Motivation

Users keep requesting this.

**Comment by ClearlyClaire** [comment]
>  Mastodon cant fetch a `Group` from Lemmy when inserting the url in the sarch. This is probably because it makes a webfinger request, which is completely unnecessary as it already has the url. The webfinger request it sends looks like `https://ds9.lemmy.ml/.well-known/webfinger?resource=acct:main@ds9.lemmy.ml`, which doesnt work because for group actors, Lemmy does webfinger under `resource=group:main@ds9.lemmy.ml` (so that it is possible to have a user and community with the same name).

Mastodon does require every actor it interacts with to have an `acct:` URI it can look up to. This is an unfortunate limitation of Mastodon stemming from UX expectations and (suboptimal) database design.

As for `acct:` VS `group:`, `acct:` is a registered URI scheme, while `acct:` is and is related to webfinger lookups: https://www.rfc-editor.org/rfc/rfc7565.html

> Comments and private messages from Lemmy fail to get delivered to Mastodon. For private messages, this is probably because we are using the [ChatMessage](https://docs.pleroma.social/backend/development/ap_extensions/#chatmessages) type from Pleroma. Not sure what the problem with comments is.

We do not support `ChatMessage`. As for comments, I can't think of any reason off the top of my head. Is there a comment I can fetch to investigate?

**Comment by Nutomic** [comment]
> As for comments, I can't think of any reason off the top of my head. Is there a comment I can fetch to investigate?

Fetching comments works just fine, you can try with `https://ds9.lemmy.ml/comment/2201`. Note, to view it in the browser you need to use [this link](https://ds9.lemmy.ml/post/1717/comment/2201). The problem is only with Create/Note activity. There is a similar problem with Pleroma which we are investigating, so the cause might be the same.

**Comment by Nutomic** [comment]
Update, the problem with comments not going from Lemmy to Pleroma turned out to be because it doesnt support `Announce/Create/Note` activities, only `Announce/Note`. I added a compatibility mode in Lemmy to also send out `Announce/Note`, which should fix the problem for Mastodon as well. 

We are going to release Lemmy 0.14 with this functionality in the next days. Later we can see about federation more actions between Mastodon and Lemmy.

**Comment by trwnh** [comment]
> it doesnt support Announce/Create/Note activities, only Announce/Note

Ah, things like this make me wonder how useful an Activity Grammar would be... `Announce/Note` is simpler and more idiomatic than `Announce/Create/Note`, for sure. If you think about it, what are you actually announcing? That the note exists, or that someone created it?

**Comment by Nutomic** [comment]
> If you think about it, what are you actually announcing? That the note exists, or that someone created it?

The latter. We dont only announce `Create/Note`, but also a lot of other actions, like `Update/Note`, `Delete`, `Vote`, or `Block`. So a special case for `Announce/Note` isnt consistent, but by sending that from Lemmy, Mastodon (and Pleroma) can at least federate in a limited way.

**Comment by Nutomic** [comment]
I fixed the webfinger problem now, as it was preventing Mastodon from verifying the HTTP signature of incoming `Announce/Page` and `Announce/Note` activities. Now Mastodon finally responds with status 202, but the page/note still dont show up in the timeline. Could you check if the json below looks correct? You can also test with your own instance by signing up on [ds9.lemmy.ml](https://ds9.lemmy.ml/) and making a comment tagging your Mastodon account (tagging doesnt work in posts).

```
{
	"@context": [
		"https://www.w3.org/ns/activitystreams",
		{
			"pt": "https://join-lemmy.org#",
			"sc": "http://schema.org#",
			"stickied": "as:stickied",
			"sensitive": "as:sensitive",
			"matrixUserId": {
				"type": "sc:Text",
				"id": "as:alsoKnownAs"
			},
			"comments_enabled": {
				"type": "sc:Boolean",
				"id": "pt:commentsEnabled"
			},
			"moderators": "as:moderators"
		},
		"https://w3id.org/security/v1"
	],
	"actor": "https://ds9.lemmy.ml/c/testcom",
	"to": [
		"https://www.w3.org/ns/activitystreams#Public"
	],
	"object": {
		"actor": "https://ds9.lemmy.ml/u/nutomic",
		"to": [
			"https://www.w3.org/ns/activitystreams#Public"
		],
		"object": {
			"type": "Note",
			"id": "https://ds9.lemmy.ml/comment/2242",
			"attributedTo": "https://ds9.lemmy.ml/u/nutomic",
			"to": [
				"https://www.w3.org/ns/activitystreams#Public"
			],
			"cc": [],
			"content": "<p>321</p>\n",
			"mediaType": "text/html",
			"source": {
				"content": "321",
				"mediaType": "text/markdown"
			},
			"inReplyTo": "https://mastodon.madrid/users/felix/statuses/107264371560406583",
			"published": "2021-11-12T23:19:09.507071+00:00"
		},
		"cc": [
			"https://ds9.lemmy.ml/c/testcom",
			"https://mastodon.madrid/users/felix"
		],
		"tag": [],
		"type": "Create",
		"id": "https://ds9.lemmy.ml/activities/create/2c28bb5b-0375-49fa-be5e-60cad29a18e9"
	},
	"cc": [
		"https://ds9.lemmy.ml/c/testcom/followers"
	],
	"type": "Announce",
	"id": "https://ds9.lemmy.ml/activities/announce/3991a2eb-60b7-4d3f-b698-18e9b2a22e9f",
}
```

**Comment by Gargron** [comment]
Hm, could it be that it’s an Announce of a Create of a Note? Whereas we usually deal with Announce of Note directly. That could be it.

**Comment by Nutomic** [comment]
Sorry I pasted the wrong activity, here is the `Announce/Note`:

```
{
	"@context": [
		"https://www.w3.org/ns/activitystreams",
		{
			"sensitive": "as:sensitive",
			"stickied": "as:stickied",
			"pt": "https://join-lemmy.org#",
			"comments_enabled": {
				"type": "sc:Boolean",
				"id": "pt:commentsEnabled"
			},
			"moderators": "as:moderators",
			"matrixUserId": {
				"type": "sc:Text",
				"id": "as:alsoKnownAs"
			},
			"sc": "http://schema.org#"
		},
		"https://w3id.org/security/v1"
	],
	"actor": "https://ds9.lemmy.ml/c/testcom",
	"to": [
		"https://ds9.lemmy.ml/c/testcom/followers"
	],
	"object": {
		"type": "Note",
		"id": "https://ds9.lemmy.ml/comment/2243",
		"attributedTo": "https://ds9.lemmy.ml/u/nutomic",
		"to": [
			"https://www.w3.org/ns/activitystreams#Public"
		],
		"cc": [],
		"content": "<p>test</p>\n",
		"mediaType": "text/html",
		"source": {
			"content": "test",
			"mediaType": "text/markdown"
		},
		"inReplyTo": "https://mastodon.madrid/users/felix/statuses/107264371560406583",
		"published": "2021-11-13T12:47:28.558443+00:00"
	},
	"cc": [
		"https://www.w3.org/ns/activitystreams#Public"
	],
	"type": "Announce",
	"id": "https://ds9.lemmy.ml/activities/announce/0c2f5b15-3fbf-481e-bc75-3c185ae80c1f",
	"published": "2021-11-10T13:38:17Z"
}
```

**Comment by kromonos** [comment]
Can I add https://github.com/LemmyNet/lemmy/issues/1910 to this topic?

**Comment by Nutomic** [comment]
We managed to make federation work now, which wasnt easy due to complete lack of documention.

[Lemmy PR](https://github.com/LemmyNet/lemmy/pull/1897)

[Release announcement](https://lemmy.ml/post/89740)

@kromonos Best open a separate issue.
