### ISSUE TITLE
Bug with expanding a post from an user’s media tab

### ISSUE THREAD

**Issue by anampses** [mastodon/mastodon#16971]
### Expected behaviour

When viewing the media tab of a user’s profile, clicking “Expand this post” will display the whole thread the post is from

### Actual behaviour

With the latest Mastodon update, clicking on “Expand this post” will instead return to the Home timeline

### Steps to reproduce the problem

1. View the media tab of a user eg: mastodon.social/web/accounts/######/media
2. Click on one of the user’s media thumbnail previews. 
3. Click on the lower right icon beneath the media with the arrow pointing out of the window to “Expand this post”
4. The post does indeed expand in the background, but trying to close out of the media window to view the expanded thread will instead force the feed to return to your Home timeline.
...

This bug has been replicated by several users of my instance since updating to the latest version of Mastodon, across different web browsers and occurs with both the “advanced web interface” and the single column interface.

### Specifications

Bug occurs with different browsers and has only been reported since updating to Mastodon v3.4.3

**Comment by ClearlyClaire** [comment]
This is because #16499 has been cherry-picked without also picking the follow-up fixes:
- #16516
- #16524

**Comment by ClearlyClaire** [comment]
Fixed in 3.4.4
