### ISSUE TITLE
Unable to log into my acount

### ISSUE THREAD

**Issue by Ecoologeek** [mastodon/mastodon#16977]
Hello,
when I whant to connect to https://mastodon.social/web/@vivis whith my mail xxx@free.fr, a message tell me to paste a code, but I never receave this code on my mailbox. Not in Spam folder also.
It's like this for months and I have no responces to my request by mail.
Can you help me please ?
Thanks
Elvis

**Comment by ClearlyClaire** [comment]
cc @Gargron

**Comment by tigransimonyan** [comment]
same problem with my admin profile

**Comment by ClearlyClaire** [comment]
@tigransimonyan which Mastodon version? is there anything in your `mastodon-sidekiq` logs?

**Comment by tigransimonyan** [comment]
mastodon v3.4.3. I didn't find any errors in the logs.
I can log in with my second admin account, but resetting the password for it doesn't work as well.

**Comment by tigransimonyan** [comment]
I want to downgrade version and try again. do I need to run `RAILS_ENV=production bundle exec rails db:migrate` after downgrading?

**Comment by ClearlyClaire** [comment]
No need to run database migrations when going back to v3.4.1 from v3.4.3. On the contrary, it's best not to.

Do you get other types of mails from your Mastodon instance? Have you checked your mailing setup?

**Comment by tigransimonyan** [comment]
I changed my mail server and started receiving emails. after that I reset user password and it started working.

**Comment by Ecoologeek** [comment]
OK my provider block the notifications because it contain words that are detected to be dangerous, and I don't have any access to tweak the spam filter. And nobody respond to my messages to mastodon.social sended from deferents mailbox. So I have no possibility to reactivate my account vivis. I'm tired to try so I quit.
Thank's for your responces here.

**Comment by Gargron** [comment]
@Ecoologeek I've disabled e-mail token authentication for you so you can try logging in now. But I can't imagine what words your mail provider could be blocking.

**Comment by Ecoologeek** [comment]
@Gargron You are my hero ! I didn't believe in it anymore. I have changed my associated mail  I think I will not have trouble now. THANK YOU !!

For information if nedeed, here is the undelivery message :
<XXX@free.fr>: host mx1.free.fr[212.27.48.7] said: 550 spam detected (in
reply to end of DATA command)
The original message content  "Tentative de connexion
Nous avons détecté une tentative de connexion à votre compte à partir d’une adresse IP non reconnue. Si c’est vous, veuillez entrer le code de sécurité ci-dessous sur la page de négociation de connexion :..."
