### ISSUE TITLE
Pasting a Mastodon user URL into compose editor should result in a proper Mastodon user handle reference instead

### ISSUE THREAD

**Issue by novoid** [mastodon/mastodon#16988]
### Pitch

When I copy a link from a user name handle, I would like to get a proper Mastodon user handle like `@user@instance.example` in the Mastodon toot compose text field and not `https://instance.example/@user`.

Maybe it is a viable solution to be "smart" and convert `https://instance.example/@user` URLs within the compose field to `@user@instance.example`. I'm far from being a fan of "smart features" like that but I currently can't think of any reason why I should need the URLs (and not the user handles) in a toot anyway.

### Motivation

Currently, when I see a toot somewhere and I do want to send a toot to that person (not a reply to the toot using the Reply button), I may think of copying the link associated with the user. To me, this is an obvious and intuitive way of addressing a specific user in a new, independent toot.

For that, I use the context menu on the user name shown somewhere in Mastodon which offers me the usual "Copy Link" feature of the browser. This copies something like `https://graz.social/@publicvoit` to the clipboard which is not visible to the user (except she's looking to the status bar before copying). When I paste this to my toot editor, it is not resulting in a proper user handle like `@publicvoit@graz.social` as I would expect. It results in an URL which can be tooted of course but misses the point the user intended most likely, causing different end results.

While the URL behind a user name is helpful for generic use in web browsers, it is not helpful for composing toots that mention other users.

**Comment by Gargron** [comment]
Posts have a "Mention @..." option in the dropdown if you don't want to reply to the specific post.

There is no way for the page to know the URL you are pasting is supposed to be someone's Mastodon profile (the @ in the URL path is not a Mastodon-specific thing, for example, Medium also has those)

**Comment by novoid** [comment]
Thanks @Gargron for answering!

The Mention-dropdown-feature may solve it for most use-cases, I agree.

It is not as intuitive as my workflow from above (using pre-Mastodon knowledge) and it might be hard to find for users, I'm afraid. Furthermore, when I "collect" various user handles to one single toot, it doesn't work any more. 

I agree that this is a nasty issue to solve (if solveable). Maybe a quick lookup on each paste to check if the url refers to a user on an instance? Although this might be considered a bad move probably ...

**Comment by Gargron** [comment]
You can definitely keep clicking "Mention @..." for different users and it will keep adding to the compose box. There's also the keyboard shortcut "m" to do this when you have a post focused.

**Comment by novoid** [comment]
> You can definitely keep clicking "Mention @..." for different users and it will keep adding to the compose box. There's also the keyboard shortcut "m" to do this when you have a post focused.

This is good news to me. So we do have a technical feature which allows mentioning multiple users, starting from independent toots. And thanks for the keyboard shortcut - very much appreciated.

If we settle for "there is a technical solution but people need to do things differently than their intuition would suggest", it will tend to a "won't fix", ignoring the mentioned non-working copy&paste-workflow.

The thing that worries me for the general case (not my personal situation) is that people might tend to use the described copy&paste workflow anyway because of previously learned knowledge how things are usually working on the Internet. Unfortunately, I don't have hard numbers here. This is based on my assumption on how people tend to work. You mileage may differ.

Just for fun, I've started a Mastodon poll in my bubble to find out if my way of thinking reflects other people's mind as well: https://graz.social/@publicvoit/107285616907905593 Maybe we can learn from this (probably small) set of results.

**Comment by nightpool** [comment]
Looks like of the 15 people who have responded to this poll, only one of them indicated that this was something they tried. I'm assuming that one person is you? I personally have not seen a single common user interface where copying and pasting someone's profile turns into an @ mention, so I'm not sure where people would be learning this copy paste workflow from. I think we can probably close this issue.

**Comment by novoid** [comment]
Hm, is it currently possible to vote in a poll that I've created myself? I'd say no.

Anyway, it was at least one person that could follow my rationale here.

However, the workflow I was thinking of seems to be somewhat unpopular, contrary to my initial assumption. So I'll close this for now. The voting ends in 13 hours but I don't think that the result will be flipped until then. 

Sorry for the noise.
