### ISSUE TITLE
Federated image from Lemmy

### ISSUE THREAD

**Issue by kromonos** [mastodon/mastodon#17003]
### Expected behaviour

Mastodon shows the link to the post on lemmy instead of the direct link to the image

### Actual behaviour

Mastodon shows the direct link to the image on lemmy

### Steps to reproduce the problem

1. Create a post on lemmy with an image instead of link
2. Take a look, what Mastodon receives

![](https://user-images.githubusercontent.com/1553902/142296163-3a93315f-16d0-4cd8-b728-b3931ab69a72.png)

### Specifications

Lemmy 0.14.1
Mastodon v3.4.3 and v3.4.2
Browser: Latest version of Firefox, Chrome, and Chromium

**Comment by mstdn** [comment]
I think this would be an "issue" with Lemmy rather than with Mastodon 😉

**Comment by kromonos** [comment]
> I think this would be an "issue" with Lemmy rather than with Mastodon wink

And the Lemmy says, that it's an issue with Mastodon ;)

**Comment by ClearlyClaire** [comment]
Do you have a link to such a post?

**Comment by ClearlyClaire** [comment]
For some reason, trying to get the ActivityStreams representation of https://fapsi.be/post/2989 leads to `NotFound`, so I cannot investigate further…

**Comment by kromonos** [comment]
Strange. I can open the Link without any problems:
![image](https://user-images.githubusercontent.com/1553902/142619643-8d04c150-b0e3-4501-bf63-6b0472b059e5.png)

Even in a private window:
![image](https://user-images.githubusercontent.com/1553902/142619805-166344ef-5fcc-4b91-aa46-b6b56e41c21f.png)

**Comment by ClearlyClaire** [comment]
Same, but that's the HTML representation. I can not fetch it in Mastodon nor manually inspect the ActivityStreams representation as querying https://fapsi.be/post/2989 with `Accept: application/activity+json` or `Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"` returns a 404.

In any case, the behavior you're describing suggests the object had a [`url`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-url) value pointing to the image, which I'm not sure is a proper use of the property since it's not really a representation of the *same* activity.

**Comment by kromonos** [comment]
hmm :thinking: Maybe [@dessaline](https://github.com/dessalines) could help out a bit?

**Comment by kromonos** [comment]
Ok, that's kinda funny. I took another post with an image upload, but that did it.
![Screenshot at 2021-11-19 13-55-30](https://user-images.githubusercontent.com/1553902/142626466-d73403c9-d1f3-4c8c-9eba-924aa2c0529f.png)

:thinking: where the heck is the difference?

**Comment by ClearlyClaire** [comment]
Alright, this one I can fetch and inspect. What happens is the activity type (`Page`) is not one “native” to Mastodon, so Mastodon only shows a summary, in this case comprised of:
- the name of the activity (“Drow”)
- a link to the `url` field of the activity, which in this case is the a link to the image and not the activity itself. As I said earlier, I believe it's a misuse of the `url` field as it's supposed to represent the activity itself. But at the same time, lemmy is centered around link sharing so it *kinds* of make sense.

In any case you can still see the article itself by clicking the permalink (where the timestamp is displayed).

**Comment by Nutomic** [comment]
@ClearlyClaire [The docs say](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-url) "Identifies one or more links to representations of the object". So maybe we are using it wrong. But not sure what the correct alternative would be, maybe like this?

```
{
    "type": "Page",
    "object": {
        "type": "Link",
        "href": "http://example.org/abc",
    },
    ...
}
```

**Comment by ClearlyClaire** [comment]
@Nutomic that's a good question. To be honest, that use of `url` seem consistent with the `Page` type, but that would imply that `Page` describes the page itself and would not have any additional content. Maybe `Article` would be more fit for this purpose. `object` is supposed to be used within `Relationship` and `Activity` objects, which neither `Page` nor `Article` are. Maybe `attachment`…

**Comment by dessalines** [comment]
If we ever want to switch to a multiple link model ( which would be necessary if we want to support things like extra pictures ), maybe attachment would be better.

**Comment by Nutomic** [comment]
FYI we are using `attachment` field for page links now. `url` field is still present for backwards compatibility, but will be removed in the next version.

https://join-lemmy.org/docs/en/federation/lemmy_protocol.html#post

**Comment by ClearlyClaire** [comment]
@Nutomic good to hear! While it might still be useful for Mastodon to expose the `uri` to the end-user, dropping `url` should fix the issue altogether.

**Comment by Nutomic** [comment]
I was wrong, the url field wont be removed in the next Lemmy major version, but the one after that (0.18). So maybe in half a year or later.

**Comment by paulo-roger** [comment]
@trwnh any reason for not implementing this?
