### ISSUE TITLE
Support latest HTTP Signature draft

### ISSUE THREAD

**Issue by Nutomic** [mastodon/mastodon#17004]
### Pitch

Mastodon currently only accepts incoming activities which are signed according to an older version of the [HTTP Signatures draft](https://tools.ietf.org/id/draft-cavage-http-signatures-12.html), which relies on the `Date` header. The latest standard version uses fields `(created)` and `(expires)` instead. It would be good if Mastodon could at least accept such signatures for receiving.

### Motivation

All projects would benefit, as they dont have to implement an old version of the standard in order to be compatible with Mastodon.

**Comment by nightpool** [comment]
We already support the `(created)` and `(expires)` pseudoheaders: https://github.com/mastodon/mastodon/blob/4ad7b81bc94561f11460f50c7b6f8f9772f356e5/app/controllers/concerns/signature_verification.rb#L157

**Comment by Nutomic** [comment]
Sorry you are right. Somehow there were problems before, apparently they were not caused by HTTP signatures because now the new ones are going through fine.
