### ISSUE TITLE
Update Notification in Admin Dashboard

### ISSUE THREAD

**Issue by Justinzobel** [mastodon/mastodon#17016]
### Pitch

I'd like to see an update notification in the admin dashboard.

It currently shows what version you're on. It would be great if it showed what the latest stable release is and if there has been an update that impacts security between your current version and the most recent.

For instance, self-hosted Gitlab has a section next to the current version showing "Update Available" in yellow if there is a new version. It will show in red if there is a security fix in any of the releases since the current version.

### Motivation

It allows administrators to know when their instance is in need of a security update which benefits both administrators and users alike. More secure software is a benefit to all involved.

It also benefits both administrators and users in ensuring they have the latest features and bug fixes for a smoother and more enjoyable experience.

**Comment by Justinzobel** [comment]
This could also be extended if desired to notify administrators if they are on an unsupported (end of life) version of PostgreSQL and point them to how to upgrade, etc.

**Comment by ClearlyClaire** [comment]
I'm not super comfortable with Mastodon calling home by default but maybe this could be an opt-in feature.

**Comment by Justinzobel** [comment]
That would be 100% acceptable and I understand the privacy concerns. Opt-in would be great.

**Comment by vmstan** [comment]
Closed by #26582
