### ISSUE TITLE
FrozenError: can't modify frozen String: "# Generated with mastodon... during Mastodon setup

### ISSUE THREAD

**Issue by Tuxicoman2** [mastodon/mastodon#17020]
### Expected behaviour

No error in the mastodon setup

### Actual behaviour

Error during the setup ;)

### Steps to reproduce the problem

I'm doing a fresh Mastodon install on Debian 11
I'm following the https://docs.joinmastodon.org/admin/install/ guide

I first faced #15751
then decided to reinstall ruby without using jemalloc (because https://github.com/mastodon/mastodon/issues/15751#issuecomment-873594463 seems the issue)

However during the setup step below I faced another error:
`RAILS_ENV=production bundle exec rake mastodon:setup`

Are you using Docker to run Mastodon? no
Do you want to send e-mails from localhost? No

then after successfully receiving the mail test:

```
This configuration will be written to .env.production
Save configuration? Yes
rake aborted!
FrozenError: can't modify frozen String: "# Generated with mastodon:setup on 2021-11-22 16:45:13 UTC\n\n"
/home/mastodon/live/lib/tasks/mastodon.rake:356:in `block (2 levels) in <top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/home/mastodon/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
/home/mastodon/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
Tasks: TOP => mastodon:setup
(See full trace by running task with --trace)
```

### Specifications

v 3.4.3
ruby 2.7.2
no jemalloc but I face the same issue with

**Comment by ClearlyClaire** [comment]
Fixed by #16976. Hopefully this will be in a new release soon.
