### ISSUE TITLE
Hashtag moderation interface regressions

### ISSUE THREAD

**Issue by ClearlyClaire** [mastodon/mastodon#17059]
#16917 revamped the administration interface for hashtags, but at least two features are lacking in the new design:
- quick access to the actual hashtag timeline to assess the posts using the hashtag
- accessing the admin page for a tag that is neither trending, pending nor rejected (which would be useful to disallow use or suggestions, or inspect stats of a hashtag that is not currently trending)

**Comment by Gargron** [comment]
I intend to embed some posts on the admin page itself, and to add a search component to the tags page for accessing specific non-trending hashtags (I don't think accessing any particular hashtag by finding it on the global alphabetic list or whatever has ever worked for anyone).

**Comment by lxjv** [comment]
@Gargron any updates on this?

**Comment by twilde** [comment]
Being unable to search for an perform administrative actions on a hashtag which is not currently trending is really problematic, any chance this can get prioritized?

**Comment by ThisIsMissEm** [comment]
We've resolved "accessing the admin page for a tag that is neither trending, pending nor rejected (which would be useful to disallow use or suggestions, or inspect stats of a hashtag that is not currently trending)" by #30880 and additionally via the potential changes in #31448.

Adding "quick access to the actual hashtag timeline to assess the posts using the hashtag" does absolutely make sense. I've opened a PR for this: #31533
