### ISSUE TITLE
Use Sonic instead of Elasticsearch

### ISSUE THREAD

**Issue by drequivalent** [mastodon/mastodon#17068]
### Pitch

https://github.com/valeriansaliou/sonic

Sonic is a lightweight search engine written in Rust that runs on a few megabytes of RAM.

### Motivation

Elasticsearch is entirely too expensive for what Mastodon uses it for. Mastodon is already taxing as it is.

**Comment by marek-lach** [comment]
This would be a good idea to adopt.

**Comment by ClearlyClaire** [comment]
Sonic is very far from being a drop-in replacement for Elasticsearch, and does not fit our use (recording who can search each post, etc.)
