### ISSUE TITLE
Mastodon online doesn't work at all. it tells there's an unexpected error

### ISSUE THREAD

**Issue by SelinaSebro** [mastodon/mastodon#17062]
### Steps to reproduce the problem

1. I tried to enter Mastodon.online (via Firefox). Content isn't loading.
2. I tried to refresh the page. The page just fell to pieces.
3. I tried to log out. It says it can't find the server.
4. I tried to enter via Edge. It says wrong logo and password though I copied them.
![зображення](https://user-images.githubusercontent.com/95098434/143616462-3a0593b2-98bf-4120-b12b-cd0f09672bf4.png)

...

### Expected behaviour

I should have seen some news and been able to post something

### Actual behaviour

Nothing works, nothing shows

### Specifications

I don't know what caused this. Mastodon is v3.4.3 now, it seems. Please help ASAP, my followers are waiting for giveaway :(

**Comment by ClearlyClaire** [comment]
Is there any error showing up in your browser's console?

**Comment by SelinaSebro** [comment]
![зображення](https://user-images.githubusercontent.com/95098434/143627477-33d8e2be-7330-4afb-894a-9301a22230b2.png)
Is that it?

**Comment by SelinaSebro** [comment]
I cleared all the cash and cookies, and now it just gives me a blank page saying can't find the server

**Comment by ClearlyClaire** [comment]
No, it wasn't that, but it's ok. Sounds like a connectivity issue between you and mastodon.online, and not a Mastodon bug. I don't think I can help you further, sorry.

**Comment by SelinaSebro** [comment]
THanks anyway for trying to help

**Comment by SelinaSebro** [comment]
Resolved. I had to change my DNS settings like [here](https://www.webnots.com/how-to-setup-google-public-dns/)
