### ISSUE TITLE
Server provided more than one HSTS header 

### ISSUE THREAD

**Issue by ztaylor100** [mastodon/mastodon#17083]
### Steps to reproduce the problem

1. Install Mastodon on Ubuntu Server 18.04 and set up according to official documentation.
2. Run curl -I https://mydomain.com/ | grep -i Strict
3. See two STS headers in the output.
strict-transport-security: max-age=63072000; includeSubDomains
strict-transport-security: max-age=31536000
...

### Expected behaviour

Only 1 STS header should be produced 

### Actual behaviour

2 STS headers are produced.

### Specifications

Mastodon3.4.4
Ruby2.7.2p137
PostgreSQL10.19
Redis4.0.9
Ubuntu 18.04 Server LTS

**Comment by mishfit** [comment]
As far as I can tell the reason this happens is that only the first declaration in the default nginx config is required (see the [config](https://github.com/mastodon/mastodon/blob/main/dist/nginx.conf#L55) for more detail).

**Comment by ztaylor100** [comment]
All of the declarations in the nginx config have the value "max-age=31536000".  The "max-age=63072000; includeSubDomains" has to be coming from somewhere else. Ruby on rails? I tried a text search to try and locate it with no luck. It is my understanding that only one program should be providing the HSTS header.

**Comment by mishfit** [comment]
That's really interesting, @ztaylor100...removing the extra declarations from my instance removed the complaint from ssllab.

**Comment by ztaylor100** [comment]
Yeah that IS interesting. I will give it a shot and report back.

**Comment by ClearlyClaire** [comment]
This does look like something Rails is adding by itself. Probably something I overlooked when switching to Rails 6.1.

**Comment by ztaylor100** [comment]
So, fortunately I have a Dev mirror of my production instance to test changes on. I removed EVERY header that references "strict-transport-security:*" from /home/mastodon/live/dist/nginx.conf, restarted both the nginx and mastodon-web services and finally rebooted the server only to find that both headers are still there. @ClearlyClaire 

`root@mastodon:~# curl -I https://mastodon.mydomain.com/ | grep -i Strict
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
strict-transport-security: max-age=63072000; includeSubDomains
strict-transport-security: max-age=31536000`

**Comment by ClearlyClaire** [comment]
Changing `/home/mastodon/live/dist/nginx.conf` will not change anything, it's just an example file. Change the file you installed somewhere in `/etc/nginx`.

**Comment by mishfit** [comment]
I changed the file that I originally copied from `dist`. This wouldn't fix anything for existing instances but it would prevent the issue for those that follow the instructions and copy from there anew.

```
$ curl -I https://backtothelan.social | grep -i strict
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
strict-transport-security: max-age=63072000; includeSubDomains
```
This is after having removed the headers from my configs at `/etc/nginx/sites-available/<xxx>`

**Comment by ztaylor100** [comment]
@mishfit Yep that did it ! @ClearlyClaire  DOH!  I guess it would be useful to edit the actual nginx.conf file that is being used. That would explain a lot actually! Thank you both for your help.

**Comment by ClearlyClaire** [comment]
Note that removing *every* header will live static files to not have HSTS headers as they are not served by Rails itself. Probably not much of an issue, but still.

The `nginx` example file should probably be updated to drop the HSTS headers on paths served by Rails and the other paths be updated to match Rails' defaults.

**Comment by ztaylor100** [comment]
Ok so can someone please provide an example of what that would look like or should I wait for an update that addresses this issue? I am a data center engineer trying to get this to a point where we can offer to host it in our cloud for customers and Mastodon is new to me so I don't really have an understanding of how updates/patches work with this project.

**Comment by ClearlyClaire** [comment]
I think something like this would do the trick, but I haven't tested it yet:
```patch
diff --git a/dist/nginx.conf b/dist/nginx.conf
index 27ca868ab..1de5ecdcb 100644
--- a/dist/nginx.conf
+++ b/dist/nginx.conf
@@ -52,21 +52,19 @@ server {
   gzip_http_version 1.1;
   gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
 
-  add_header Strict-Transport-Security "max-age=31536000" always;
-
   location / {
     try_files $uri @proxy;
   }
 
   location ~ ^/(emoji|packs|system/accounts/avatars|system/media_attachments/files) {
     add_header Cache-Control "public, max-age=31536000, immutable";
-    add_header Strict-Transport-Security "max-age=31536000" always;
+    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
     try_files $uri @proxy;
   }
 
   location /sw.js {
     add_header Cache-Control "public, max-age=0";
-    add_header Strict-Transport-Security "max-age=31536000" always;
+    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
     try_files $uri @proxy;
   }
 
@@ -90,7 +88,6 @@ server {
     proxy_cache_valid 410 24h;
     proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
     add_header X-Cached $upstream_cache_status;
-    add_header Strict-Transport-Security "max-age=31536000" always;
 
     tcp_nodelay on;
   }
```

**Comment by ztaylor100** [comment]
Just applied and tested and it's working for me.

**Comment by 0x3e4** [comment]
kudos to the solution and thanks for the thread! i had the same issue with my instance.

Specs:
Mastodon 3.4.4
Ruby 2.7.2p137
PostgreSQL 12.9
Redis 5.0.7
Ubuntu 20.04
