### ISSUE TITLE
After WebAuthn login always redirected to WebUI home, even if doing OAuth authorization

### ISSUE THREAD

**Issue by heguro** [mastodon/mastodon#17091]
### Steps to reproduce the problem

https://user-images.githubusercontent.com/65112898/144601295-6c2baa3a-2038-4f49-bdbc-b8a63dd2575a.mp4

1. Enable 2FA and security key in your account
2. Start authorization from some Mastodon client app
3. If you already signed in, click top right icon to sign out
4. Input emall address and password
5. Click "USE SECURITY KEY" button
6. Use security key

### Expected behaviour

Redirected back to OAuth authorization page

### Actual behaviour

Redirected to WebUI home

### Specifications

Confirmed with
* Mastodon v3.4.4 and main branch
* Safari with iOS 15.1, and Edge 96.0.1054.34 with Windows 11 22000.318

When logging in with other method than WebAuthn, this code is used to redirect:
https://github.com/mastodon/mastodon/blob/2e0d5753e350aacbfc20dac21942439e5a178fac/app/controllers/auth/sessions_controller.rb#L80-L88

But WebAuthn method uses different code:
https://github.com/mastodon/mastodon/blob/2e0d5753e350aacbfc20dac21942439e5a178fac/app/javascript/packs/two_factor_authentication.js#L30
https://github.com/mastodon/mastodon/blob/2e0d5753e350aacbfc20dac21942439e5a178fac/app/controllers/concerns/two_factor_authentication_concern.rb#L55-L60

This code always renders `{"redirect_path": "/"}`, and causes a issue.

Some app such as Amaroq reset session when starting authorization. In this case you cannot sign in to app with security key.

**Comment by ClearlyClaire** [comment]
Hi! Thanks for the detailed report! Unfortunately, I have yet to set up something to fully test this workflow, but your analysis seems spot on. Would you mind making a PR to fix this issue using the same logic as the default one in `SessionsController`?

**Comment by heguro** [comment]
Thanks for replying. I will try it in few days.
