### ISSUE TITLE
Project governance and transparency

### ISSUE THREAD

**Issue by progval** [mastodon/mastodon#17107]
### Pitch

Hi,

(Sorry if this isn't the right place, I couldn't find a better one.)

Since its creation, Mastodon's impact and user base are growing fast, as the best decentralized social network we have.

However, I feel that it is still managed like a hobby project, instead of the well-defined ownership and multi-stakeholder/decentralized leadership a project this important deserves.
I am aware [Mastodon gGmbH was created recently and you directed funding to it](https://blog.joinmastodon.org/2021/08/mastodon-now-a-non-profit-organisation/) and this is a step in the right direction, but as far as I am aware, it is still entirely owned by a single person and does not have public bylaws, so it does not fit the above point.

Therefore, I believe you should consider something like the following steps:

1. Getting more stakeholders in Mastodon gGmbH, so that no single person (or company) has >=50% of the voting power
2. Moving other Mastodon assets to it: trademark, joinmastodon.org, and possibly mastodon.social and/or mastodon.online
3. Publishing transparency reports at regular interval, such as accounting reports and roadmap

### Motivation

This would give Mastodon a more solid foundation, and help its users trust its goals are aligned with their interests.

Thank you

**Comment by felixtrade** [comment]
Are your points addressed in the [Annual Report 2021](https://github.com/mastodon/mastodon/files/7980272/2021_Mastodon_Annual_Report_3.pdf)?

**Comment by progval** [comment]
Most of them, yes! I was glad to see this earlier. Point 1 remains to be done, though.

**Comment by Gargron** [comment]
Half of point 1 is a wontfix, as I do not wish to give up more than 50% of the voting power, but there might be more stakeholders in the future. I think this issue can be closed now.

**Comment by progval** [comment]
Then most of it is moot if a single person still controls Mastodon and its ecosystem.

Thanks for the answer and addressing point 3, though
