### ISSUE TITLE
"TypeError: Cannot convert undefined or null to object" with docker compose

### ISSUE THREAD

**Issue by pedrolamarao** [mastodon/mastodon#17110]
### Steps to reproduce the problem

1. checkout stable-3.4
2. docker compose up

Eventually, output becomes an endless stream of:

```
mastodon-streaming-1  | TypeError: Cannot convert undefined or null to object
mastodon-streaming-1  |     at Function.assign (<anonymous>)
mastodon-streaming-1  |     at startWorker (/opt/mastodon/streaming/index.js:137:37)
mastodon-streaming-1  |     at throng (/opt/mastodon/node_modules/throng/lib/throng.js:25:12)
mastodon-streaming-1  |     at /opt/mastodon/streaming/index.js:1136:3
mastodon-streaming-1  |     at Server.<anonymous> (/opt/mastodon/streaming/index.js:1123:36)
mastodon-streaming-1  |     at Object.onceWrapper (events.js:420:28)
mastodon-streaming-1  |     at Server.emit (events.js:314:20)
mastodon-streaming-1  |     at emitCloseNT (net.js:1657:8)
mastodon-streaming-1  |     at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

### Expected behaviour

application starts without errors

### Actual behaviour

application generates endless errors

### Specifications

Built from source:

commit fd868f8ca0b13afdb3f6fb9a3be063ccec7e1349 (HEAD -> stable-3.4, tag: v3.4.4, origin/stable-3.4)
Author: Eugen Rochko <eugen@zeonfederated.com>
Date:   Fri Nov 26 01:27:08 2021 +0100

    Bump version to 3.4.4

Docker version:

Client:
 Cloud integration: v1.0.22
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.10
 Git commit:        dea9396
 Built:             Thu Nov 18 00:42:51 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:39 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by ClearlyClaire** [comment]
Hi! Did you manage to resolve your issue?

Looking at the traceback, it seems your `NODE_ENV` may be something else than `production` or `development`. Did you override it?

**Comment by oe1rfc** [comment]
Hi, I just encountered this, thanks on the hint regarding `NODE_ENV`, I was using `NODE_ENV=tests` as set in [.env.test](https://github.com/mastodon/mastodon/blob/main/.env.test).

**Comment by ThisIsMissEm** [comment]
We're also redone all this code in recent releases, as we've removed clustering from the streaming server; That said though, it does typically want a `NODE_ENV=production` or `NODE_ENV=development` (not that this really has that much effect on the code, other than changing which file `dotenv` attempts to load (`.env.production` or `.env`)
