### ISSUE TITLE
ActivityPub client-to-server Create Activity not working

### ISSUE THREAD

**Issue by johnspurlock** [mastodon/mastodon#17127]
### Steps to reproduce the problem

1. Obtain an oauth token on behalf of a known user
2. Fetch their account info via `/api/v1/accounts/verify_credentials`
3. Find out their AP outbox URL via an AP fetch call to the `url` from their account info (returning an AP Person)
4. POST a spec-standard AP reply comment as an authenticated user to the user's AP outbox URL as described in [Create Activity](https://www.w3.org/TR/activitypub/#create-activity-outbox) using the spec-standard for [Client to Server Interactions](https://www.w3.org/TR/activitypub/#client-to-server-interactions)

Does the AP outbox logic on the Mastodon backend implement this?  I'm not familiar with the codebase, but I don't see it in [outboxes_controller.rb](https://github.com/mastodon/mastodon/blob/49219508bc2e01fe724830ca31a7cfa7adba15cf/app/controllers/activitypub/outboxes_controller.rb)

I'm trying to create an AP client that is as server-agnostic as possible, and the Mastodon ActivityPub implementation seems great for reading, so I was surprised when I came across this snag for writing.

### Expected behaviour

Activity (Note) should have been created

### Actual behaviour

404 The page you are looking for isn't here

### Specifications

server version: 3.4.4

**Comment by nightpool** [comment]
Mastodon had not implemented the c2s protocol. see #10520
