### ISSUE TITLE
embedded statuses take on incorrect height when viewport is resized responsively

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#17136]
### Steps to reproduce the problem

1. embed multiple statuses in a web page
2. load that web page
3. resize that web page so that the iframes reflow

### Expected behaviour

the correct height is reset

### Actual behaviour

incorrect height is set

### Specifications

mastodon.social

![image](https://user-images.githubusercontent.com/10606431/146090846-2c0f6dbb-51c5-42c8-8596-b32eb145aba8.png)

reflowing back to original width makes the statuses look correct again

![image](https://user-images.githubusercontent.com/10606431/146090990-5117341c-b59f-48b9-b77d-4f18f2955567.png)

**Comment by mjankowski** [comment]
Still true for recent embed update in 4.3?
