### ISSUE TITLE
LibreTranslate support

### ISSUE THREAD

**Issue by PJ-Finlay** [mastodon/mastodon#17137]
### Pitch

Support detecting language and translating toots by connecting to a [LibreTranslate](https://libretranslate.com) instance.

### Motivation

Translating toots would make it easier for the user to read toots in languages that they do not speak.

**Comment by ClearlyClaire** [comment]
I can't vouch for the quality of the translations, but the API seems simple, and self-hosting is possible. Implementing an admin setting to use a LibreTranslate instance might be worth a try.

**Comment by Gargron** [comment]
Added in #19218
