### ISSUE TITLE
Embedding multiple posts will load only one post in all embeds

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#17135]
### Steps to reproduce the problem

1. Copy the embed links for multiple different statuses
2. Paste the iframes into a web page
3. Load that web page

### Expected behaviour

The different posts load in their respective frames

### Actual behaviour

Only one post will load in all frames

### Specifications

mastodon.social -- have some screenshots

![image](https://user-images.githubusercontent.com/10606431/146089264-01577e85-25fd-40c0-92ec-75a2af0fdf83.png)

![image](https://user-images.githubusercontent.com/10606431/146089224-d97dee58-40f7-4cac-96de-77986457ff0e.png)

**Comment by trwnh** [comment]
this seems to be some kind of caching bug, as removing the iframes and trying to load only one at a time still causes the first-loaded one to be shown instead.

**Comment by trwnh** [comment]
specifically in the javascript, as disabling javascript makes the correct posts show (although they are the wrong height, of course)

**Comment by miKa-pyon** [comment]
Hm it works for me, including embedded posts with media.
Works for me in Chromium, Falkon, Firefox and Vivaldi.

**Comment by ClearlyClaire** [comment]
Including the script multiple times may cause needless message-passing between the frames, but I fail to see anything that would cause this behavior, it only changes the frame's height…

**Comment by mjankowski** [comment]
Still true (to same degree) for recent embed update in 4.3?

**Comment by trwnh** [comment]
no longer reproducible
