### ISSUE TITLE
mastodon-web various error messages/ruby

### ISSUE THREAD

**Issue by DrSkyfaR** [mastodon/mastodon#17145]
### Steps to reproduce the problem

![Screenshot_1](https://user-images.githubusercontent.com/26686045/146668715-25f6a1ca-d8a2-48ed-bf01-238e7552cc6e.png)

```
Dez 19 09:31:49 s2.infra.levelxstudios.org bundle[54842]: /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
Dez 19 09:31:49 s2.infra.levelxstudios.org bundle[54842]: /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
Dez 19 09:31:49 s2.infra.levelxstudios.org bundle[54842]: /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
Dez 19 09:31:49 s2.infra.levelxstudios.org bundle[54842]: /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
Dez 19 09:31:49 s2.infra.levelxstudios.org bundle[54842]: /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
Dez 19 09:31:49 s2.infra.levelxstudios.org bundle[54842]: /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here

```

```
Dez 19 09:38:28 s2.infra.levelxstudios.org bundle[54901]: HINT:  Verwenden Sie den Befehl REFRESH MATERIALIZED VIEW.
Dez 19 09:38:28 s2.infra.levelxstudios.org bundle[54901]: ):
Dez 19 09:38:28 s2.infra.levelxstudios.org bundle[54901]: [05002f4e-5e2d-42b9-ad24-0e497d921a8a]
Dez 19 09:38:28 s2.infra.levelxstudios.org bundle[54901]: [05002f4e-5e2d-42b9-ad24-0e497d921a8a] app/controllers/admin/instances_controller.rb:59:in `set_instances'
Dez 19 09:38:28 s2.infra.levelxstudios.org bundle[54901]: [05002f4e-5e2d-42b9-ad24-0e497d921a8a] app/controllers/concerns/localized.rb:16:in `block in set_locale'
Dez 19 09:38:28 s2.infra.levelxstudios.org bundle[54901]: [05002f4e-5e2d-42b9-ad24-0e497d921a8a] app/controllers/concerns/localized.rb:15:in `set_locale'
Dez 19 09:38:28 s2.infra.levelxstudios.org bundle[54907]: [134826ad-a4e8-4fbc-b634-669229fb6363] method=GET path=/ format=*/* controller=HomeController action=index status=302 duration=1.12 view=0.00 db=0.00 lo>
Dez 19 09:38:28 s2.infra.levelxstudios.org bundle[54901]: [53fa8b0c-938c-4ad0-8729-6ebb94866141] method=GET path=/about format=*/* controller=AboutController action=show status=200 duration=52.56 view=23.14 db=>
```

I hope someone can help to fix this Problem.

### Expected behaviour

No error messages

### Actual behaviour

Error messages and non-functioning federation page in moderation

### Specifications

Latest Mastodon Version [https://github.com/mastodon/mastodon/releases/tag/v3.4.4] on a Debian Bullseye server

**Comment by ClearlyClaire** [comment]
The first set of warnings are a known issue with no known functional consequence.

The actual error in the second piece of log you are showing suggests you may not have run the migration scripts or there might have been an error when running them.

Have you installed 3.4.4 directly, or did you update from a previous version?

What happens if you run `RAILS_ENV=production bundle exec rails db:migrate`?

**Comment by DrSkyfaR** [comment]
Hello,
Thank you very much for your quick reply.
Regarding the first error output, I already thought something similar. 

Regarding your migration script question, the entire output of the command is as follows. 
`RAILS_ENV=production bundle exec rails db:migrate
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
Your database collation is susceptible to index corruption.
  (This warning does not indicate that index corruption has occurred and can be ignored)
  (To learn more, visit: https://docs.joinmastodon.org/admin/troubleshooting/index-corruption/)`
The instance has been updated over several versions but has not had any problems in this regard. 

Greetz Christopher

**Comment by ClearlyClaire** [comment]
Hm, there does not seem to be any actual error there. You most likely don't need to run `fix-duplicates` (but it's a good reminder that we need to update it).

Did you perhaps forget to restart `mastodon-web`?

**Comment by DrSkyfaR** [comment]
I have already restarted the service several times / all processes. If only because I had to fix the problem with Bullseye and jemalloc to get the instance to work on the new host system. If you need any information to help me better, please let me know. I'm happy to provide anything that can help debugging. I have never had any problems with Mastodon so far, this is the first time and I just don't understand the reason why this problem occurs.

**Comment by ClearlyClaire** [comment]
What happens if you do `Instance.refresh` in a Rails console (`RAILS_ENV=production bundle exec rails c`)?

**Comment by DrSkyfaR** [comment]
`RAILS_ENV=production bundle exec rails c
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
Chewy console strategy is `urgent`
Loading production environment (Rails 6.1.3.2)
irb(main):001:0> Instance.refresh
Traceback (most recent call last):
        2: from (irb):1
        1: from app/models/instance.rb:24:in `refresh'
ActiveRecord::StatementInvalid (PG::FeatureNotSupported: FEHLER:  CONCURRENTLY kann nicht verwendet werden, wenn die materialisierte Sicht nicht befüllt ist)
irb(main):002:0>
`

**Comment by ClearlyClaire** [comment]
```ruby
Scenic.database.refresh_materialized_view('instances', concurrently: false, cascade: false)
```

**Comment by DrSkyfaR** [comment]
```
irb(main):002:0> Scenic.database.refresh_materialized_view('instances', concurrently: false, cascade: false)
=> #<PG::Result:0x0000561fd2eac638 status=PGRES_COMMAND_OK ntuples=0 nfields=0 cmd_tuples=0>
```

**Comment by ClearlyClaire** [comment]
Is your issue solved, now?

**Comment by DrSkyfaR** [comment]
Oh yes, thank you very much. 
Could you perhaps explain to me in an easily understandable way what the problem was? What exactly was the problem behind it? I am always interested in knowing what the cause of a problem is.

**Comment by ClearlyClaire** [comment]
Basically, `instances` is a materialized view (that is, a database table storing the result of a SQL query), which is updated regularly. However, the updating code (`Instance.refresh`) works in such a way that it expects the materialized view to already be populated when updating it, which was not the case for you.

I am not sure why the materialized view was not populated for you, and I will investigate to see if I see a broken update path somewhere.

**Comment by DrSkyfaR** [comment]
Thank you very much for the help.
And thank you for explaining the problem. I would then close here. Good luck with the search? :D

**Comment by jplock** [comment]
I had this same issue on my instance which I had been running Mastodon for awhile.  I had to run https://github.com/mastodon/mastodon/issues/17145#issuecomment-998190956 to resolve the issue.

**Comment by JohnD28** [comment]
I hat the same issue after updating to 3.4.6n but running https://github.com/mastodon/mastodon/issues/17145#issuecomment-998190956 didn't solve the issue

**Comment by ClearlyClaire** [comment]
@jplock were you ever only using Mastodon releases or did you also use `main` at some point? Do you remember ever doing something weird regarding migrations?

@JohnD28 is the error you got actually the same? If not, what is it? If it is the same, what did running https://github.com/mastodon/mastodon/issues/17145#issuecomment-998190956 do?

**Comment by JohnD28** [comment]
@ClearlyClaire 

Yes, same error for all ruby command:
```
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
```

But if I do `Instance.refresh` I have this:

```
irb(main):005:0> Instance.refresh 
=> #<PG::Result:0x000055772af1eae0 status=PGRES_COMMAND_OK ntuples=0 nfields=0 cmd_tuples=0>
```
So `Scenic.database.refresh_materialized_view('instances', concurrently: false, cascade: false)` change nothing:

```
irb(main):006:0> Scenic.database.refresh_materialized_view('instances', concurrently: false, cascade: false)
=> #<PG::Result:0x00005577264a57c0 status=PGRES_COMMAND_OK ntuples=0 nfields=0 cmd_tuples=0>
```

**Comment by ClearlyClaire** [comment]
> @ClearlyClaire
> 
> Yes, same error for all ruby command:
> 
> ```
> /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
> /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
> /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
> /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
> /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
> /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
> ```

As stated in https://github.com/mastodon/mastodon/issues/17145#issuecomment-997901014 those are warnings and not errors, and you should not be concerned about them.

**Comment by zorun** [comment]
I had the same issue on mastodon 3.5.3, although it's possible that the problem appeared with an earlier version and I just didn't notice it. This is an old instance (created in 2017) that I upgrade regularly, and I never used `main`.

In any case, the "refresh_materialized_view" call in the console fixed the issue, thanks!

**Comment by Tuxicoman2** [comment]
https://github.com/mastodon/mastodon/issues/17145#issuecomment-998190956 solved the issue for me.
I had the same issue with mastodon 3.5.3

```
oct 29 20:22:35 darkstone bundle[1677]: [e5091706-8de5-4588-843c-db58769bf0a5]
oct 29 20:22:35 darkstone bundle[1677]: [e5091706-8de5-4588-843c-db58769bf0a5] ActiveRecord::StatementInvalid (PG::ObjectNotInPrerequisiteState: ERREUR:  la vue matérialisée « instances » n'a pas été peuplée
oct 29 20:22:35 darkstone bundle[1677]: HINT:  Utilisez la commande REFRESH MATERIALIZED VIEW.
oct 29 20:22:35 darkstone bundle[1677]: ):
oct 29 20:22:35 darkstone bundle[1677]: [e5091706-8de5-4588-843c-db58769bf0a5]
oct 29 20:22:35 darkstone bundle[1677]: [e5091706-8de5-4588-843c-db58769bf0a5] app/presenters/instance_presenter.rb:36:in `block in domain_count'
oct 29 20:22:35 darkstone bundle[1677]: [e5091706-8de5-4588-843c-db58769bf0a5] app/presenters/instance_presenter.rb:36:in `domain_count'
oct 29 20:22:35 darkstone bundle[1677]: [e5091706-8de5-4588-843c-db58769bf0a5] app/serializers/rest/instance_serializer.rb:49:in `stats'
oct 29 20:22:35 darkstone bundle[1677]: [e5091706-8de5-4588-843c-db58769bf0a5] app/controllers/concerns/cache_concern.rb:22:in `render_with_cache'
oct 29 20:22:35 darkstone bundle[1677]: [e5091706-8de5-4588-843c-db58769bf0a5] app/controllers/api/v1/instances_controller.rb:9:in `show'
oct 29 20:22:35 darkstone bundle[1677]: [e5091706-8de5-4588-843c-db58769bf0a5] app/controllers/concerns/localized.rb:11:in `set_locale'
oct 29 20:22:35 darkstone bundle[1677]: [e5091706-8de5-4588-843c-db58769bf0a5] lib/mastodon/rack_middleware.rb:9:in `call'
```

**Comment by kpfleming** [comment]
Same here... I've been running Mastodon for a while, upgrading and running migration scripts all along, but just had to run the command from #17145 to get the 'instances' tab working.

**Comment by Wurzelmann** [comment]
> ```ruby
> Scenic.database.refresh_materialized_view('instances', concurrently: false, cascade: false)
> ```

Oh wow, that finally fixed my problem with the instances view, thank you very much!

**Comment by Justinzobel** [comment]
> Scenic.database.refresh_materialized_view('instances', concurrently: false, cascade: false)

This also fixed my instances view too, thanks!

**Comment by leahoswald** [comment]
Same problem here after the upgrade to posgresql 15

**Comment by SchiWaGoA78** [comment]
hello.

i have the same issue with the view in mastodonafter the upgrade from postgrsql14 to 16.
where or how can i use the "Scenic.database.refresh_materialized_view('instances', concurrently: false, cascade: false)" ?

thx

**Comment by SchiWaGoA78** [comment]
> Try running `REFRESH MATERIALIZED VIEW instances` in PostgreSQL

Thank you so much, this worked instant. :)
