### ISSUE TITLE
Is there any Docker version of Vagrant provider for Apple Silicon Users

### ISSUE THREAD

**Issue by junkaiman** [mastodon/mastodon#17175]
### Pitch

Hi all,

I am asking whether there is any implementation for the Vagrant dev env using Docker as the provider since the Virtual Box is not compatible with Apple Silicon devices. It will help a lot if the original Vagrant settings for VirtualBox can be converted to Docker, or someone can come up with a Docker setting file optimized for development.

### Motivation

Since there will be more developers and admins using arm64 devices to deploy a dev env for Mastodon

**Comment by omz13** [comment]
Virtual Box now has [test builds](https://www.virtualbox.org/wiki/Testbuilds) that support arm64

**Comment by nileshtrivedi** [comment]
@omz13  That gave me hope, and I went to the length of setting up VMware Fusion on Apple M1 (which required registering on the Broadcom portal). But the [Vagrantfile](https://github.com/mastodon/mastodon/blob/main/Vagrantfile#L137) refers to the `ubuntu/focal64` box which does not work with the vmware provider.

Are there really no Mastodon developers using Apple silicon machines? 🤔

**Comment by c960657** [comment]
[.devcontainer/Dockerfile](https://github.com/mastodon/mastodon/blob/main/.devcontainer/Dockerfile) is optimized for development and works fine on Apple silicon. See [instructions in README.md](https://github.com/mastodon/mastodon?tab=readme-ov-file#docker).

**Comment by mjankowski** [comment]
Closing on assumption that the devcontainer (or native dev, which seems fine for me?) are good on Apple Silicon at this point.
