### ISSUE TITLE
from_elasticsearch return empty

### ISSUE THREAD

**Issue by adrianomic** [mastodon/mastodon#17177]
### Steps to reproduce the problem

I was running test.
But some ``from_elasticsearch`` method returns empty array.
Elasticsearch is running in localhost:9200

Exact test case is 
spec/services/search_service_spec.rb
```
        it 'includes the tag in the results' do
          query = '#tag'
          tag = Tag.new
          allow(Tag).to receive(:search_for).with('tag', 10, 0, exclude_unreviewed: nil).and_return([tag])

          results = subject.call(query, nil, 10)
          expect(Tag).to have_received(:search_for).with('tag', 10, 0, exclude_unreviewed: nil)
          expect(results).to eq empty_results.merge(hashtags: [tag])
        end
```

``results = subject.call(query, nil, 10)`` this one need to call ``TagSearchService::call`` method
``from_elasticsearch`` and ``from_database`` returns different result
``from_elasticsearch`` return empty array ``[]`` and ``from_database`` returns correct result.

Development tag is working well with elasticsearch.

Am I missing something in elasticsearch configuration or test configuration?

Look forward to your reply
Thank you

### Expected behaviour

Test should be passed

### Actual behaviour

Test failed

### Specifications

3.4.1

**Comment by ClearlyClaire** [comment]
As far as I know, Elasticsearch is not supposed to be used at all in the testsuite. Are you using `RAILS_ENV=test`? Have you edited `.env.test`? Do you have `ES_ENABLED`, `ES_HOST` etc. defined in your environment when launching the tests?

**Comment by adrianomic** [comment]
Adding ``ES_ENABLED=false`` to ``.env.test`` worked for me.
But modify .env.test is a must?

**Comment by adrianomic** [comment]
The problem is below test is failed if I don't add ``ES_ENABLED=false`` to ``.env.test``
```
  1) Profile I can change my account
     Failure/Error: first('.btn[type=submit]').click
     
     Faraday::ConnectionFailed:
       Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for "localhost" port 9200)  1) Profile I can change my account
     Failure/Error: first('.btn[type=submit]').click
     
     Faraday::ConnectionFailed:
       Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for "localhost" port 9200)
```

**Comment by ClearlyClaire** [comment]
> Adding `ES_ENABLED=false` to `.env.test` worked for me. But modify `.env.test` is a must?

No, on the contrary, you should not edit it. It's disabled by default. It looks like you have `ES_ENABLED=true` in your environment when you run rspec, which is causing the issue.

**Comment by adrianomic** [comment]
For development mode, we use ``.env`` file right?
For test, which file do we use? ``.env.test`` or ``.env`` ?

**Comment by adrianomic** [comment]
I see, I've used ``.env.development`` for development and ``.env`` for testing. All works

Thank you for your time and effort
