### ISSUE TITLE
Crowdin updates are not merged

### ISSUE THREAD

**Issue by tigransimonyan** [mastodon/mastodon#17192]
### Steps to reproduce the problem

Crowdin updates are not merged into main branch

https://github.com/mastodon/mastodon/pull/16858

### Expected behaviour

Get translation updates with new release.

### Actual behaviour

The new release did not contain translation updates.

### Specifications

mastodon v3.4.4

**Comment by Gargron** [comment]
There has not been a new release in a while. Backports do not count.

**Comment by comradekingu** [comment]
https://docs.weblate.org/en/latest/vcs.html?highlight=github#github-repositories  https://docs.weblate.org/en/latest/admin/continuous.html#automatically-receiving-changes-from-github
