### ISSUE TITLE
Giant profile pictures on Posts page

### ISSUE THREAD

**Issue by tarasis** [mastodon/mastodon#17219]
### Steps to reproduce the problem

1. go to https://social.tarasis.net/@tarasis
2. See that the profile images are very large and cover the toots below

Profile images on the timeline view when you log in are at the correct size and look normal. Its only the front page.

<img width="762" alt="Screenshot showing large images" src="https://user-images.githubusercontent.com/3006/147880619-f1bed974-bfc7-48e2-a125-4bc6fd172d0c.png">

Logged in view 

<img width="754" alt="Screenshot 2022-01-02 at 15 30 13" src="https://user-images.githubusercontent.com/3006/147880669-798f8914-ab6e-4e23-b7e6-81b9fde088a1.png">

### Expected behaviour

Images should be normal size

### Actual behaviour

The images are huge

### Specifications

Running mastodon latest (v3.4.4), migrated today from 3.1.3

**Comment by Gargron** [comment]
You missed the assets:precompile step, CSS is out of date.

**Comment by tarasis** [comment]
Hi Gargon, I had run the command earlier and again just now and still have the issue. (I apparently left out that I was using the docker image youse provide, apologies) 

```
[root@mc mastodon]# docker-compose run --rm web bundle exec rake assets:precompile
[+] Running 2/0
 ⠿ Container mastodon-db-1     Running                                                                                                                                       0.0s
 ⠿ Container mastodon-redis-1  Running                                                                                                                                       0.0s
/opt/ruby/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/opt/ruby/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/opt/ruby/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
yarn install v1.22.17
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
Done in 1.99s.
Everything's up-to-date. Nothing to do
```

(I will be updating to ruby 3 soon to get rid of that 2.7.0 warning)

**Comment by ClearlyClaire** [comment]
The `assets:precompile` step likely failed in an earlier attempt. Try doing `bundle exec rake assets:clobber` first.

However, I'm a bit surprised. Doesn't the docker image ship with a prebuilt version of the assets?
