### ISSUE TITLE
Unable to load Mastodon locally

### ISSUE THREAD

**Issue by markcellus** [mastodon/mastodon#17241]
### Steps to reproduce the problem

1. Run Mastodon locally using Vagrant instructions on README

### Expected behaviour

Local Mastodon is available at http://mastodon.local like the instructions say

### Actual behaviour

The local instance appears to be running fine, but navigating to http://mastodon.local in browser gives me blank page with no errors.

### Specifications

Latest commit on master used: d3db2eb7fb17e94ace3fc648153f14178e707830
Browser: Firefox 95.0.1
OS: Ubuntu 21.10

**Comment by ClearlyClaire** [comment]
Did you do `vagrant plugin install vagrant-hostsupdater`?

**Comment by markcellus** [comment]
Unfortunately no, since I didn't see that step on the README.

I tried it, it ran successfully. But now I can't run `vagrant up` anymore. It gives me this error:

```
It appears your machine doesn't support NFS, or there is not an
adapter to enable NFS on this machine for Vagrant. Please verify
that `nfsd` is installed on your machine, and try again. If you're
on Windows, NFS isn't supported. If the problem persists, please
contact Vagrant support.
```

I'm guessing that I need to install this missing package inside the vagrant instance?

**Comment by ClearlyClaire** [comment]
I think you need to install that on the host.

**Comment by markcellus** [comment]
Installed with `sudo apt install nfs-kernel-server` and it works now. Thanks!

**Comment by markcellus** [comment]
Someone should add the extra `vagrant plugin install vagrant-hostsupdater` and `sudo apt install nfs-kernel-server` step to the README or under a "Troubleshooting" section or something.
