### ISSUE TITLE
Blank page when logging in 

### ISSUE THREAD

**Issue by Gxnfvhg** [mastodon/mastodon#17261]
### Steps to reproduce the problem

1. Follow the installation instructions for Mastodon on Ubuntu 
2. Try to open your instance in your browser
3. Try to connect
...

### Expected behaviour

I should be able to connect since i followed every step to the letter

### Actual behaviour

I get a blank page, and the site overall doesn't display properly

### Specifications

I'm using the last version of Mastodon, I've seen another issue mentioning this but it's been locked as spam so i can't reply there, when i try to check  journalctl for more information i get lots of messages with inside the following error : controller=ApplicationController action=raise_not_found status=404, like dozens and dozens of lines saying this, i already tried reinstalling Mastodon since i first tried installing it on Debian but it didn't work and used 100% of the CPU. 
It seems like the person who had his thread locked for spam found a way to fix it but he didn't tell how, if nothing works i'll try reinstalling again. Here's a link to my instance = https://mastodon.urgelle.fr/

**Comment by Gxnfvhg** [comment]
To be sure, i tried reinstalling everything again but it didn't change anything. I get the same dozens of errors within mastodon web who can't seem to find the assets even though i can find them directly in their proper directory.

Errors like this : Jan 10 16:16:10 bundle[60119]: [07f03f25-f6f7-492d-9ff7-8a33ae0c5e10] method=GET path=/inert.css format=css controller=ApplicationController action=raise_not_found status=404 duration=8.99 view=1.34 db=1.20
Jan 10 16:16:11  bundle[60115]: [4b0dbe91-e4b3-48ce-ba4d-3492895d1b0d] method=GET path=/apple-touch-icon.png format=png controller=ApplicationController action=raise_not_found status=404 duration=13.43 view=2.76 db=3.79
Jan 10 16:16:11 bundle[60115]: [6b2e2ad0-d0e3-4848-89f8-405e91cc0e0a] method=GET path=/favicon.ico format=html controller=ApplicationController action=raise_not_found status=404 duration=13.35 view=2.95 db=5.70

**Comment by ClearlyClaire** [comment]
Either your reverse-proxy (most probably nginx) is misconfigured, or it doesn't have the necessary rights to your Mastodon install. Please check your reverse-proxy logs.

**Comment by Gxnfvhg** [comment]
It worked, thanks.
