### ISSUE TITLE
Mastodon segfaults while installing

### ISSUE THREAD

**Issue by Realitaetsverlust** [mastodon/mastodon#17283]
### Steps to reproduce the problem

- Setup fresh VPS
- follow the documentation under https://docs.joinmastodon.org/admin/install/
- execute `RAILS_ENV=production bundle exec rake mastodon:setup`

Segfault-log: https://pastebin.com/MfuCHGJM

At first, I suspected my machine was too low-specced. It was a 2CPUs 2GBs VPS with 40GB of storage. I upgraded it to 4CPUs and 8GBs of RAM, confident it would resolve the issue, but I still get the same error.

The only time I had to adapt the commands in the docs were during the main installation. The package `python-certbot-nginx`, which was python2. It didn't exist anymore, so I installed `python3-certbot-nginx`. 
Also, I ran into issues while installing yarn, I got something completely different at first, but got that worked out aswell after I added another repo.

If you need any kind of other details regarding my machine, just let me know, I'll provide all the infos I can.

### Expected behaviour

It should work

### Actual behaviour

It doesn't

### Specifications

I executed the command `git checkout $(git tag -l | grep -v 'rc[0-9]*$' | sort -V | tail -n 1)` as described in the documentation. The HEAD is currently detached at v3.4.4, which is fd868f8ca0b13afdb3f6fb9a3be063ccec7e1349

**Comment by ClearlyClaire** [comment]
Try something like `export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2` (check that it is indeed the path to libjemalloc on your system). See: https://github.com/mastodon/mastodon/issues/15751#issuecomment-873594463

**Comment by Realitaetsverlust** [comment]
Cheers @ClearlyClaire that worked.
