### ISSUE TITLE
Site empty, redirect to /about

### ISSUE THREAD

**Issue by NiceKype** [mastodon/mastodon#17298]
Hello,

i installed everything exactly in the order of the documentation but the tool wont work. It only appears a empty site and a auto redirect to /about. 

Logs: 
web service: https://pastebin.com/r130Hht4
streaming service: https://pastebin.com/HDQ0P2gk
sidekiq service: https://pastebin.com/8SJrpTpb

I dont have any clue anymore what can be the error and i really hope that anyone can help me.

Kind regards,
Timo // NiceKype

**Comment by Gargron** [comment]
Perhaps you forgot to assets:precompile or it didn’t run during setup for some reason?

**Comment by NiceKype** [comment]
It wasnt in the installation documentation so i didnt tried it. But i didnt looked at it in the troubleshooting, im sry ^^
I runned that command and now is there a error site, but it still redirect to /about and only shows that error site.

**Comment by NiceKype** [comment]
Oh im sry, i forgot to post that. I dont know why, but now it works. I changed nothing, but it works 😂😅
So issue is solved
