### ISSUE TITLE
All services (mastodon-web, streaming, sidekiq) show active, but errors on website

### ISSUE THREAD

**Issue by ThatOneCalculator** [mastodon/mastodon#17293]
### Steps to reproduce the problem

Unsure

### Expected behaviour

Mastodon instance work properly

### Actual behaviour

Shows the 500.html page

### Specifications

v3.4.4
Ubuntu 20.04
Ruby 2.7.2

**Comment by ThatOneCalculator** [comment]
Update: I was able to get the server up, but it can't seem to fetch any local posts and throws Error 500 a lot via a toast

**Comment by ClearlyClaire** [comment]
When getting a 500 error, please provide logs from `journalctl -u mastodon-web`

**Comment by ThatOneCalculator** [comment]
I fixed it, it was an issue with media attachments. After removing all media from my instance and fixing duplicates, it works again
