### ISSUE TITLE
`tootctl emoji import` only imports pngs, not gifs

### ISSUE THREAD

**Issue by ThatOneCalculator** [mastodon/mastodon#17303]
### Steps to reproduce the problem

1. Make a tar.gz with pngs
2. Run `RAILS_ENV=production bin/tootctl emoji import ./Amongus.tar.gz`

### Expected behaviour

All files in archive should import, including pngs a
![Screenshot_2022-01-16-09-24-33_2560x1440](https://user-images.githubusercontent.com/44733677/149712538-d23026bf-28f2-49d2-85aa-799b40d98fcf.png)
nd gifs

### Actual behaviour

Only pngs import

### Specifications

v.3.4.4

**Comment by ThatOneCalculator** [comment]
> The documentation is incorrect, Mastodon has never supported importing GIFs from the CLI, and I don't think it was ever intended to.
> 
> Might want to check whether uploading GIFs from the admin interface works, and if so, update the CLI tool for consistency, though.

Works from the admin interface fine. Either docs need to be updated or the CLI interface does. I've noticed a lot of false advertising in the docs tbh :/

**Comment by trwnh** [comment]
> I've noticed a lot of false advertising in the docs tbh :/

please point out anything incorrect so it can be fixed
