### ISSUE TITLE
Reduced OAUTH scope

### ISSUE THREAD

**Issue by f0x52** [mastodon/mastodon#17325]
### Pitch

It would be nice if Mastodon's OAUTH supported an even more reduced scope than `read`, similar to how Github has `(no scope) | Grants read-only access to public information (including user profile info, repository info, and gists)`. It should grant no other access to the account than what is already public, and could be used to confirm the user authenticating is who they say they are, but nothing more.

As not defining any scope currently defaults to `read`, behavior which might be used by existing clients, it might be good to give this reduced scope an explicit name, like `read:profile`, `identify` etc.

### Motivation

Has a similar usecase as #4800 for interconnecting with other apps, but is much simpler to implement.

Examples, taken from the [OAUTH Scope](https://oauth.net/2/scope/) list:
Github: `(no scope)` [link](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes)
Slack: `identify` [link](https://api.slack.com/scopes/identify)
Google: `profile`, `email`, `openid` [link](https://developers.google.com/identity/protocols/oauth2/scopes#google-sign-in)
Fitbit: `profile` [link](https://dev.fitbit.com/build/reference/web-api/developer-guide/application-design/#Scopes)

**Comment by ThisIsMissEm** [comment]
I'd be interested in working on this / implementing this.

**Comment by ThisIsMissEm** [comment]
I've introduced a `read:me` scope in #29087

**Comment by ThisIsMissEm** [comment]
This scope is now called `profile` and will be available in 4.3, you can detect it being available by making a `GET` request to `/.well-known/oauth-authorization-server` which returns support scopes by that Mastodon instance. This API is also a 4.3 API, so if it returns a 404, assume that the server does not support the `profile` scope and downgrade accordingly.

We originally had `read:me` but renamed to `profile` to use a more standard name, as it is a standard scope name in OIDC.

**Comment by mjankowski** [comment]
Closing as done by that linked PR ... do we need any doc changes/etc here as well?

**Comment by ThisIsMissEm** [comment]
@mjankowski documentation changes are already under way: https://github.com/mastodon/documentation/pull/1445
