### ISSUE TITLE
Is there a way to circumvent this issue?

### ISSUE THREAD

**Issue by LWFlouisa** [mastodon/mastodon#17346]
### Pitch

A method to appeal suspensions.

### Motivation

Recently I was attacked by members of CG, a hate campaign that targeted minorities in comics, in order to attempt to drive them out of the business. They ended up hijacking Eugene's report function, and ended up reporting me for transphobia despite being a trans person myself. That might not be what Eugene came out and said. But that's basically what it when the report got hijacked on there.

**Comment by ClearlyClaire** [comment]
There are already issues open for having a built-in appeal process, and plans to implement them.

As for your particular case, this issue tracker is not the place for appealing your suspension, use your server's contact information instead.
