### ISSUE TITLE
Private followers

### ISSUE THREAD

**Issue by Kreyren** [mastodon/mastodon#17340]
### Pitch

Provide ability to make the followers private

### Motivation

I am politically active and I don't want my followers known for the security and privacy of both sides.

relevant: https://freespeech.firedragonstudios.com/@kreyren/107659634917103308

**Comment by Gargron** [comment]
Use “Hide network” option in preferences

**Comment by Kreyren** [comment]
> Use “Hide network” option in preferences -- @Gargron (https://github.com/mastodon/mastodon/issues/17340#issuecomment-1018421185)

![2022-01-21_12-31](https://user-images.githubusercontent.com/11302521/150520031-d8b1de84-ef71-42d5-8352-e99fd44c7b61.png)

That is not sufficient as the follows are still visible

EDIT: I guess it works for the proposed motivation, thanks
