### ISSUE TITLE
"Unconfirmed" accounts should not be shown public

### ISSUE THREAD

**Issue by mstdn** [mastodon/mastodon#17382]
### Steps to reproduce the problem

1. Create new account but don't confirm email
2. Check public account link
3. It's accessible
...

Pitch
In the whole spam case from a few days ago we have opened up signups again with hCaptcha enabled. It immediately had effect since the bots started signing up again.

For now it seems the accounts are not getting activated so that's a big win!

However.. I did spot something unusual. When a new account has not been confirmed by email it does show up on the public account page(for the time it exists) and I'm not really getting that.

A new account should only be active when it's fully confirmed right?

Motivation
In this case I want to remove the possibility of a "botnet connection" with the publicly (temporary) created accounts. In the past mstdn.social but also mastodon.social has issues with a "malicious botnet actor" that was simply a default account. (I did had a IP in the bio but not sure if that matters).

### Expected behaviour

Not showing unconfirmed accounts

### Actual behaviour

Public accounts page for unconfirmed accounts

### Specifications

All branches

**Comment by Gargron** [comment]
I was pretty sure profiles were not public for unconfirmed accounts

**Comment by ClearlyClaire** [comment]
Profiles are not public for unapproved accounts but they are for unconfirmed accounts! Working on a fix.
