### ISSUE TITLE
PWA does not work with Bromite

### ISSUE THREAD

**Issue by adam-stambaugh** [mastodon/mastodon#17388]
### Steps to reproduce the problem

1. Log into a Mastodon instance from Bromite.
2. Add PWA as instructed
3. Open PWA shortcut.
...

Bromite works with PWAs from other sites. I've only ever had issues with Mastodon's PWA on it.

### Expected behaviour

PWA to display anything in its interface

### Actual behaviour

Completely blank interface

### Specifications

I've tried multiple instances, including mastodon.online, and all had the same issue.

**Comment by unascribed** [comment]
Same here.

This worked fine on my instance until I updated from 3.2.0 to 3.4.6.

Workaround: If you go into /settings then open the hamburger menu and choose "Back to Mastodon", the app loads. Doesn't work if loaded as a PWA, and I don't know *why* this works, but it does.

**Comment by csagan5** [comment]
Should be fixed in Bromite `98.0.4758.108`.

**Comment by nightpool** [comment]
Thanks @csagan5

**Comment by csagan5** [comment]
It will actually be fixed on next release due to a mishap, see [#1693.](https://github.com/bromite/bromite/issues/1693)
