### ISSUE TITLE
Use `media` extension to better describe media in RSS feed.

### ISSUE THREAD

**Issue by kevincox** [mastodon/mastodon#17392]
Right now multiple images on one post are represented as multiple top-level `<enclosure>` elements. Unfortunately what this means varies wildly between feeds as to be basically useless. In some cases it is meant to be multiple representations of the same image (different quality, formats...) whereas for some feeds (like mastodon's current feed) it represents multiple different images. [The specification](https://validator.w3.org/feed/docs/rss2.html#ltenclosuregtSubelementOfLtitemgt) doesn't even mention if multiple enclosures are allowed.

```xml
<rss version="2.0">
  <channel>
    <item>
      <enclosure url="{{image1.url}}" length="{{image1.size}}" type="{{image1.mime}}"/>
      <enclosure url="{{image2.url}}" length="{{image2.size}}" type="{{image2.mime}}"/>
    </item>
  </channel>
</rss>
```

In order to mitigate this and ensure a consistent experience across RSS clients I think the [mrss AKA media extension](https://www.rssboard.org/media-rss#media-group) should be used. This is a widely supported extension which has support for explicit grouping. The end result would look something like:

```xml
<rss version="2.0" xmlns:media="http://search.yahoo.com/mrss/">
  <channel>
    <item>
      <!-- Deprecated legacy elements to minimize change -->
      <enclosure url="{{image1.url}}" length="{{image1.size}}" type="{{image1.mime}}"/>
      <enclosure url="{{image2.url}}" length="{{image2.size}}" type="{{image2.mime}}"/>

      <!-- New more well defined structure -->
      <media:group>
        <media:content url="{{image1.url}}" fileSize="{{image1.size}}" type="{{image1.mime}}" isDefault="true" height="{{image1.height}}" width="{{image1.width}}" />
      </media:group>
      <media:group>
        <media:content url="{{image2.url}}" fileSize="{{image2.size}}" type="{{image2.mime}}" isDefault="true" height="{{image2.height}}" width="{{image2.width}}" />
      </media:group>
    </item>
  </channel>
</rss>
```

This also opens the door to other rich information such as [description](https://www.rssboard.org/media-rss#media-description).

**Comment by nightpool** [comment]
RSS feed representation has been very contentious and acrimonious in the past, and I wouldn't want to break the existing setup just because someone knew with a different requirement came along. Broadly, our RSS feeds are very basic and designed for the widest possible compatibility. The correct way for modern clients to access a machine readable representation of Mastodon posts is through our ActivityStreams JSON representation.

If there's a way to implement this without breaking backwards compatibility with the majority of common clients (MOST of which are designed for automated posting to some system or another, like Matrix, rather then being fully featured RSS clients), then we'd probably be okay with merging the PR, but please make sure to get consensus from the people who have contributed to the RSS implementation in the past, since none of the maintainers currently use it or have strong opinions on it.

**Comment by kevincox** [comment]
Right, I mean to point out that the `<enclosure>` elements can be kept for backwards compatibility. I agree that for mastodon-specific use case JSON makes the most sense, however the benefit of RSS is that it is an API that it broadly supported for a variety of use cases, so I wouldn't want to limit the RSS feed just because the JSON API is more accurate. It would be nice to support both.

Do you have anyone in mind that should be pulled into this discussion? Or should I just ping people who have authored or commented on RSS changes in the past?

**Comment by noellabo** [comment]
Once you've decided on a new RSS format, why not keep the old one and add an endpoint?

This is the PeerTube subscribe button, but it presents you with a choice.
![image](https://user-images.githubusercontent.com/28195220/151706030-a4cd3fde-8392-4e08-abe6-cee556302676.png)

**Comment by kevincox** [comment]
I would strongly advise against this. RSS is expected to be a generic feed, so how are users expected to chose from the various options? I think we should try to make a widely understood feed and just offer that one. Having multiple different feeds just creates confusion for users and difficulty maintaining them all.

**Comment by SuperSandro2000** [comment]
Why not keep the old endpoint for automated systems and only expose the new rss feeds to end users?

**Comment by kevincox** [comment]
I'm not sure what you mean because these feeds are only for automated systems. Do you mean to keep the old link as-is and update the frontend to send new subscribers to the new feed. (Basically new subscribers, new feed, old subscribers legacy feed)

If so my argument against that is that then old subscribers would never get an improved experience. They would need to be somehow informed to unsubscribe then resubscribe.

**Comment by SuperSandro2000** [comment]
> Do you mean to keep the old link as-is and update the frontend to send new subscribers to the new feed. (Basically new subscribers, new feed, old subscribers legacy feed)

yes

> If so my argument against that is that then old subscribers would never get an improved experience. They would need to be somehow informed to unsubscribe then resubscribe.

Then this can't easily be changed without breaking backwards compatibility. 

---

A real rssfeed reader shouldn't care about this change and should just continue to work but any bridge or mirror tool might have something custom cooked which could break.
