### ISSUE TITLE
Functionality: hide one specific post

### ISSUE THREAD

**Issue by Unazhang** [mastodon/mastodon#17397]
### Pitch

This feature is to hide some posts without having to block the user or filter some keywords.

### Motivation

I sometimes see triggering posts boosted multiple times by people I followed. It would be nice if I can hide this post without having to hide the person who posted it. The keyword filter doesn't apply in this scenario because it is this one specific post I don't what to see. Keyword filter kills other innocent posts which happen to have this keyword.

**Comment by ClearlyClaire** [comment]
This is already planned! Assigning myself to make that official.

**Comment by Unazhang** [comment]
> This is already planned! Assigning myself to make that official.

So glad to hear that!

**Comment by realpixelcode** [comment]
I'd love to have that feature too! For example, there was a photo of a spider that many people boosted. I didn't want to see it (you know, spiders...) but had no option to hide it entirely, since manually toggling the image's NSFW option doesn't persist between different Mastodon pages.

**Comment by ClearlyClaire** [comment]
Addressed by #18945
