### ISSUE TITLE
Docker hub latest points to v3.3.1 backport release instead of v3.4.5

### ISSUE THREAD

**Issue by oe1rfc** [mastodon/mastodon#17416]
### Steps to reproduce the problem

`docker-compose pull` will pull the image digest `3101710406ce`, which is actually `v3.3.1`, and not the latest release `v3.4.5`, which has no additional image tags apart from the version string.

Also see: https://hub.docker.com/r/tootsuite/mastodon/tags

This is probably because `v3.3.1` was pushed to dockerhub 2 minutes after `v3.4.5` and overwrote the `latest` tag. A backport release should not overwrite the `latest` image tag.

### Expected behaviour

v3.4.5 should be pulled

### Actual behaviour

v3.3.1 service release is pulled

### Specifications

This affects everyone running `docker-compose pull` on a docker-compose.yml file with `image: tootsuite/mastodon` image definition, as the supplied production docker-compose.yml also has.

**Comment by Gargron** [comment]
Fixed
