### ISSUE TITLE
Filter features - Show particular filter / Show filtered toot

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#17419]
### Pitch

![image](https://user-images.githubusercontent.com/17537000/151971326-b6072de0-2974-4cf0-91f3-5ab90477df0f.png)

I filter "wordle"...  I'd like to see two things. 

1) the "name" of the filter 
2) "show" to actually view the filtered toot

<img width="365" alt="image" src="https://user-images.githubusercontent.com/17537000/151972017-869e72ec-7b40-456d-8525-3dcf4ce4e63e.png">

### Motivation

This is mostly because sometimes I might want to dive into something I've filter out...

**Comment by ClearlyClaire** [comment]
This is planned.

**Comment by ClearlyClaire** [comment]
Implemented in #18058
