### ISSUE TITLE
visible polls

### ISSUE THREAD

**Issue by hacknorris-code** [mastodon/mastodon#17432]
### Pitch

would it be good to have a poll option to show existing votes before voting? like being able to see thru votes to see which is highest, etc using background color of a vote? before poll ends ofcourse. public.

### Motivation

maybe would be just useless, yea. but its neither in fb nor in tweeter so ... and sometimes would prevent situations like this : https://mastodon.social/@hacknorris/107733562927688041 (two different votes while requesting one thing from four)

**Comment by vmstan** [comment]
Functional added in Mastodon 4.2

![image](https://github.com/mastodon/mastodon/assets/3002053/87c0e499-c4db-42b9-a4c1-bef5450427ee)
