### ISSUE TITLE
TypeError (no implicit conversion of nil into Hash) for /users/(account)

### ISSUE THREAD

**Issue by zunda** [mastodon/mastodon#17437]
### Steps to reproduce the problem

1. Apply #17426
2. Send a GET request to `/users/(account)' with 'Accept: application/json' request header

### Expected behaviour

Responded with a JSON data for the account

### Actual behaviour

Responded with a 500 Internal Server Error

### Specifications

Puma records the error like

```
method=GET path=/users/zundan format=json controller=AccountsController action=show status=500 error='TypeError: no implicit conversion of nil into Hash' duration=20.80 view=0.00 db=2.88

TypeError (no implicit conversion of nil into Hash):

app/helpers/context_helper.rb:43:in `merge!'
app/helpers/context_helper.rb:43:in `block in serialized_context'
app/helpers/context_helper.rb:42:in `each'
app/helpers/context_helper.rb:42:in `each_with_object'
app/helpers/context_helper.rb:42:in `serialized_context'
app/lib/activitypub/adapter.rb:23:in `serializable_hash'
app/controllers/concerns/cache_concern.rb:22:in `render_with_cache'
app/controllers/accounts_controller.rb:52:in `block (2 levels) in show'
app/controllers/accounts_controller.rb:18:in `show'
```

This seems to be fixed with https://github.com/zunda/mastodon/commit/52edc1386a03cb3fe51c632cabdeab7f9b3cba15 but I'm not sure if this is the correct way to fix it.

**Comment by ClearlyClaire** [comment]
What version of Mastodon does it occur on? It seems like you may have applied the patch incorrectly.

**Comment by zunda** [comment]
I now understand the error is from me leaving the Keybase proof on my server with reverting #17045. Thanks for pointing that out!
https://mastodon.social/@Gargron/107736193127990402
