### ISSUE TITLE
Allow for editing individual server rules 

### ISSUE THREAD

**Issue by rscmbbng** [mastodon/mastodon#17441]
### Pitch

Allow server rules to be manually ordered and also individually edited.

### Motivation

When setting up server rules they are automatically ordered based moment of entry and can not be edited anymore.

Furthermore, they are numbered automatically which adds additional weight to the ordering (i.e. Rule Number 1 has more gravitas than the first rule in the list).

To edit either the sequence of the rules, or their content, they need to be deleted and submitted again in the correct order. This is an extremely tedious way of managing and editing the rules, especially if there are a couple.

**Comment by ClearlyClaire** [comment]
They can be edited! Just click on them and it'll let you. A pencil icon could make that more obvious.
Regarding ordering, I agree, especially since reordering-by-editing is not an option with the upcoming use of rules within reports.

**Comment by rscmbbng** [comment]
Oh I see they can indeed be edited! Thanks for pointing that out! Indeed making adding an icon or a button could help make that option more discoverable.

**Comment by FediVideos** [comment]
> They can be edited! Just click on them and it'll let you. A pencil icon could make that more obvious. Regarding ordering, I agree, especially since reordering-by-editing is not an option with the upcoming use of rules within reports.

I had zero idea this was possible! :open_mouth:  It would help a lot if this was made clearer, yes :+1: 

You've already got the "delete" link on each rule, maybe clearest solution would be to add an "edit" link next to the delete link?

**Comment by rhaamo** [comment]
just got that issue, edited first rule, saving it caused to be put on the bottom.

so I have a rule saying "first, " as the last item, very great...

**Comment by danorton** [comment]
I just put the rules into the about/more HTML. The <h2> headers show up in a column on the left.

**Comment by ClearlyClaire** [comment]
`/about/more` is discontinued in Mastodon 4.0, the custom extended information is still here, but the Table of Contents is gone, and the built-in rules are much more prominent now.

**Comment by danorton** [comment]
@ClearlyClaire ugh. Still with the broken rules editor? Another reason to wait to upgrade.

**Comment by danorton** [comment]
I see this in the release 4.0.0 notes: #20623

**Comment by danorton** [comment]
This issue, as titled, should probably be closed.

**Comment by ClearlyClaire** [comment]
There is still no obvious way to reorder them. Also, the fact that you can actually edit them is still difficult to discover.

**Comment by danorton** [comment]
The title is about "individual" server rules.

**Comment by danorton** [comment]
As a workaround to the ordering problem, the **priority** column in the tables database **rules** table looks easy to change...
