### ISSUE TITLE
Can't validate my account with keybase

### ISSUE THREAD

**Issue by stemy2** [mastodon/mastodon#17443]
### Steps to reproduce the problem

1. Create an account on keybase
2. Type `keybase prove mastodon.social [username]` in the console
3. Click on the URL provided (https://mastodon.social/settings/identity_proofs/new?provider=keybase&token=87caa3814feaaa4eb5a569b39b967b59210c10cd99207650bcf9f6a9c3727ff00f&provider_username=[keybase username]&username=[mastodon username]&user_agent=linux:5.9.0)

### Expected behaviour

Validation of my account

### Actual behaviour

The URL is broken and drive me to a 404 error

### Specifications

v3.4.6

**Comment by Gargron** [comment]
Keybase has been removed from Mastodon.

**Comment by stemy2** [comment]
Ah, OK. What was the reason ?

**Comment by Gargron** [comment]
See  #17045
