### ISSUE TITLE
Exaggerated participant count for a poll

### ISSUE THREAD

**Issue by vachan-maker** [mastodon/mastodon#17456]
### Steps to reproduce the problem

I don't know if this can be reproduced
1. Open https://mastodon.social/@akhilan/107746093840907287
2. Check how many people voted on the poll. You will see the number as 10, 842. But this many people did not vote on the poll. The number is way too large
![image](https://user-images.githubusercontent.com/65799568/152683706-e2397be9-786d-4a27-b220-4a1fecf4388d.png)

### Expected behaviour

Show the actual count of number of people who participated in the poll.

### Actual behaviour

Incorrect count being displayed.

### Specifications

Fosstodon.org mastodon version : 3.4.6
Mastodon.social version : 3.4.6

**Comment by Gargron** [comment]
As far as I’m aware the voting was conducted by a botnet through workers.dev subdomains, which has since been banned on mastodon.social.

**Comment by vachan-maker** [comment]
Oh interesting
@Gargron Should I close this issue then?
