### ISSUE TITLE
[LEGAL]: terms and privcy notice not displayed on small smartphone screens

### ISSUE THREAD

**Issue by rriemann** [mastodon/mastodon#17482]
### Steps to reproduce the problem

Dear community!

I prepare the use of Mastodon by some public sector bodies as we believe Mastodon has advantages with respect to data protection. During some preliminary checks, I discovered that the footer changes when moving from the desktop to the smartphone. The terms and privacy notice disappear. This is a legal issues in Germany and many other EU countries (possibly also other jurisdictions) that require to make this information easily accessible from any page on every device – also from smartphones.

I use as an example https://mastodon.social

## Desktop

![image](https://user-images.githubusercontent.com/111932/153038682-9340c42d-b6a4-48a9-8b56-af21f184dd51.png)

## Smartphone (Firefox Mobile and Chrome on Android)

![image](https://user-images.githubusercontent.com/111932/153039707-17a449d9-d5e1-4cd0-9bfa-02f57fc71581.png)

/cc @Gargron @alvar-freude 

### Expected behaviour

The terms and data protection links should be accessible on each page – also when opened on a smartphone

### Actual behaviour

On small screens, some links are not displayed – including the terms and data protection links

### Specifications

I have observed this issue with the most recent Mastodon version (v3.4.6).

**Comment by Gargron** [comment]
The links disappear at 415px width. I'll take a look.
