### ISSUE TITLE
postfix/postdrop warning: mail_queue_enter: create file maildrop: Permission denied

### ISSUE THREAD

**Issue by binarydad** [mastodon/mastodon#17489]
### Steps to reproduce the problem

I noticed these logs are happening non-stop when I view syslog or `journalctl -u mastodon-sidekiq`. After a while, I stop getting updates in my mastodon timeline. I would restart the mastodon-sidekiq service but the errors keep coming back. I feel this happened recently. 

![image](https://user-images.githubusercontent.com/1760607/153111432-2dad4cdd-2fe7-4768-9ab7-a9d7fe448451.png)

### Expected behaviour

I shouldn't get a million permission denied errors

### Actual behaviour

I'm getting a million permission denied errors

### Specifications

I am using Mastodon 3.4.6 installed via Yunohost (not sure if this is a YNH issue or mastodon, so this is posted in both places) on Debian 10.

**Comment by binarydad** [comment]
I tried this, and while it seems to have fix/stopped the "permission denied" errors, I'll wait to see if I'm still getting new posts showing on my feed. 

http://linuxhostingsupport.net/blog/postdrop-mail_queue_enter-create-file-maildrop-permission-denied

**Comment by Gargron** [comment]
Postfix/postdrop is not part of the Mastodon stack. Also, feed updates are not connected to e-mail delivery. If there is an issue there it needs to be investigated separately.

**Comment by binarydad** [comment]
Ok, thank you. I noticed that too when, while still getting the errors, my feed was updating. I just happened to notice prior to that, my feed was no longer refreshing. Maybe the errors were just a coincidence?

Either way, this is why I want to monitor it before closing this. If it happens again, I'll create a new issue.

**Comment by binarydad** [comment]
The issue came back this morning, randomly, at 9:57am EST, after resetting the permissions. It's flooding my syslog, writing:

```
Feb  9 09:57:46 yunohost bundle[534]: postdrop: warning: mail_queue_enter: create file maildrop/505592.14776: Permission denied
Feb  9 09:57:46 yunohost postfix/postdrop[14776]: warning: mail_queue_enter: create file maildrop/505592.14776: Permission denied
```

every 10 minutes. Before that time, nothing. Nothing seems to indicate something ran at that time in crontab. 

I'm stumped.

**Comment by binarydad** [comment]
I've re-installed postfix, I've confirmed permissions are correct for `/var/spool/` and `/var/spool/postfix/` (at least they appear correct). Not sure what else is happening - they keep coming back!

![image](https://user-images.githubusercontent.com/1760607/153258239-b5fc642f-3fad-455e-b90a-e8379d932562.png)

**Comment by binarydad** [comment]
Turns out the issue was a new permission/security setting for the sidekiq service, it seems. Here's my post regarding it on the YNH page. I'm not sure if this change was specific to YNH or was for Mastodon proper, but if anyone having this issue (especially on YNH), this should resolve it: https://github.com/YunoHost-Apps/mastodon_ynh/issues/305

**Comment by yalh76** [comment]
Sorry, yes it's YunoHost specific, you can close the issue here ^^

**Comment by jamesadney** [comment]
I ran into this issue on a pretty stock Ubuntu 24.04 install. It looks like it was caused by the systemd sandboxing for `mastodon-sidekiq`. The linked YunoHost solution just disables sandboxing, which isn't ideal (it looks like they later re-enabled sandboxing, but I don't see any reference to Postfix around that change).

I was able to fix by ([via](https://bbs.archlinux.org/viewtopic.php?pid=1968396#p1968396)):

1. Giving sidekiq permission to write to `/var/spool/postfix/maildrop`

   ```diff
   diff --git a/dist/mastodon-sidekiq.service b/dist/mastodon-sidekiq.service
   index 324cd5a398..b2cee97a14 100644
   --- a/dist/mastodon-sidekiq.service
   +++ b/dist/mastodon-sidekiq.service
   @@ -48,6 +48,8 @@ SystemCallFilter=@chown
    SystemCallFilter=pipe
    SystemCallFilter=pipe2
    ReadWritePaths=/home/mastodon/live
   +# Needed for sending mail with postfix
   +ReadWriteDirectories=/var/spool/postfix/maildrop
    
    [Install]
    WantedBy=multi-user.target
   ```

2. Adding `mastodon` to the `postdrop` group:

   ```sh
   usermod -aG postdrop mastodon
   ```
