### ISSUE TITLE
Streaming API error: ERR! SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by HolgerHuo** [mastodon/mastodon#17536]
### Steps to reproduce the problem

1. Start StreamingAPI
2. Check its logs

### Expected behaviour

no errors prompt

### Actual behaviour

mastodon-streaming throws ERR! SyntaxError: Unexpected end of JSON input

### Specifications

Mastodon v3.4.6
/streaming/index.js commit hash: [c5c46dd](https://github.com/mastodon/mastodon/commit/c5c46dd6ee7f54a25c08216d957af45e68a20131)

More information:
After a localhost subscription (`verb UUID Starting stream from timeline:public for 127.0.0.1`), mastodon-streaming process starts throwing `ERR! SyntaxError: Unexpected end of JSON input`.
Seems to be worker-related issue, as killing worker processes will restart the subscription and the error pauses when the worker process restarts.

**Comment by ClearlyClaire** [comment]
As far as I know, this is caused by incorrect requests to the streaming service, probably not caused by any legitimate Mastodon client.

**Comment by HolgerHuo** [comment]
That's true! There is a foreign server constantly connects to the streaming api, as shown in nginx log after restart streaming api.
`217.160.249.241 - - [14/Feb/2022:14:49:50 +0000] "GET /api/v1/streaming/?stream=public HTTP/1.1" 101 23605 "-" "-"`
This is quite annoying anyway. Thanks a lot!
