### ISSUE TITLE
ERR! SyntaxError: Unexpected end of JSON input every 10 seconds in syslog

### ISSUE THREAD

**Issue by binarydad** [mastodon/mastodon#17541]
### Steps to reproduce the problem

In the syslog, this is happening about every 10 seconds and seems to relate to the mastodon-streaming service. I suddenly started getting this a couple days ago and not sure what or why this is happening. 

Logs (note I restarted the service in the middle of these logs): https://paste.binarydad.com/?c48b04ffab49f342#2nCZH5p1gAMS5ueYJZwN4ub7UDHSRch8rdAZ4CmcYQZ3

### Expected behaviour

No failed log entries

### Actual behaviour

Getting log entries

### Specifications

I'm running node v12.22.10 on Debian 10 with YNH 4.3.6.2.

**Comment by HolgerHuo** [comment]
An external server is constantly scanning via the streaming API as in https://github.com/mastodon/mastodon/issues/17536
Seems to be generating contents from public timeline. Not sure if Mastodon allow unauthenticated access to streaming API or if it is a flaw.

**Comment by binarydad** [comment]
Got it. I modified `/streaming/index.js` on line 90 to add a check for the value of `json` before trying to parse. It at least reduces the errors. The issue was a blank string was being passed in and `JSON.parse` was failing. There is actually a null check right after this function, which makes it feel like this check should be part of the code in the first place.

![image](https://user-images.githubusercontent.com/1760607/153974480-c8a6eae7-8498-42c8-81a7-e4a816f6eace.png)

**Comment by HolgerHuo** [comment]
This is a solution. The one whoever scans the instance should modify its code anyway.

**Comment by shleeable** [comment]
Glad I'm not the only one having this problem. Big G said to ignore it, but let's see.

**Comment by ClearlyClaire** [comment]
Yes, this error can be safely ignored. However we should probably do something to reduce the noise, or at least make it more understandable.
