### ISSUE TITLE
Upgrade from version 3.4.5 to 3.4.6 fails

### ISSUE THREAD

**Issue by M-Stenzel** [mastodon/mastodon#17558]
### Steps to reproduce the problem

1. I installed from version 3.4.3 to version 3.4.4 to version 3.4.5 without any problems.
2. Use "git fetch && git checkout v3.4.6" to upgrade to latest version 
3. The procedure fails with:

remote: Enumerating objects: 1224, done.
remote: Counting objects: 100% (1191/1191), done.
remote: Compressing objects: 100% (580/580), done.
remote: Total 1224 (delta 808), reused 905 (delta 610), pack-reused 33
Receiving objects: 100% (1224/1224), 2.37 MiB | 18.63 MiB/s, done.
Resolving deltas: 100% (814/814), completed with 130 local objects.
From https://github.com/tootsuite/mastodon
 * [new branch]          dependabot/bundler/pg-1.3.2 -> origin/dependabot/bundler/pg-1.3.2
 + 437b08a6d...1ad2a8c1f feature-explore-web-ui -> origin/feature-explore-web-ui  (forced update)
   753080bc6..51a2e67cc  feature-trending-statuses -> origin/feature-trending-statuses
   97682af42..4d09f4cd9  l10n_main  -> origin/l10n_main
   564efd065..5f4b9e1bc  main       -> origin/main
error: Your local changes to the following files would be overwritten by checkout:
        config/environments/production.rb
Please commit your changes or stash them before you switch branches.
Aborting

### Expected behaviour

Upgrade to version 3.4.6 should work as expected

### Actual behaviour

The upgrade fails with the above shown error message

### Specifications

3.4.5

**Comment by ClearlyClaire** [comment]
As `git` is stating, you somehow modified `config/environments/production.rb`.
Use `git diff` to review the changes. If you want to discard them, you can do something like `git checkout -- config/environments/production.rb`.

**Comment by M-Stenzel** [comment]
> As `git` is stating, you somehow modified `config/environments/production.rb`. Use `git diff` to review the changes. If you want to discard them, you can do something like `git checkout -- config/environments/production.rb`.

Well, I temporarily removed the modified the production.rb and installed the latest version 3.5.1

Difference between 3.4.5 and 3.5.1 production.rb file (simple diff) shows this:

94c94,95
<   outgoing_mail_domain   = Mail::Address.new(outgoing_email_address).domain
---
>   outgoing_email_domain  = Mail::Address.new(outgoing_email_address).domain
> 
97,98c98
<     reply_to: ENV['SMTP_REPLY_TO'],
<     'Message-ID': -> { "<#{Mail.random_tag}@#{outgoing_mail_domain}>" },
---
>     message_id: -> { "<#{Mail.random_tag}@#{outgoing_email_domain}>" },
100a101,103
>   config.action_mailer.default_options[:reply_to]    = ENV['SMTP_REPLY_TO'] if ENV['SMTP_REPLY_TO'].present?
>   config.action_mailer.default_options[:return_path] = ENV['SMTP_RETURN_PATH'] if ENV['SMTP_RETURN_PATH'].present?
> 
108c111
<     :ca_file              => ENV['SMTP_CA_FILE'].presence,
---
>     :ca_file              => ENV['SMTP_CA_FILE'].presence || '/etc/ssl/certs/ca-certificates.crt',
110,112c113,115
<     :enable_starttls_auto => ENV['SMTP_ENABLE_STARTTLS_AUTO'] || true,
<     :tls                  => ENV['SMTP_TLS'].presence,
<     :ssl                  => ENV['SMTP_SSL'].presence,
---
>     :enable_starttls_auto => ENV['SMTP_ENABLE_STARTTLS_AUTO'] != 'false',
>     :tls                  => ENV['SMTP_TLS'].presence && ENV['SMTP_TLS'] == 'true',
>     :ssl                  => ENV['SMTP_SSL'].presence && ENV['SMTP_SSL'] == 'true',
121c124
<     'X-XSS-Protection'       => '1; mode=block',
---
>     'X-XSS-Protection'       => '0',
126,128d128
< 
<   config.hosts << "www.xy-space.de"
<

I guess it is safe to use the production.rb file that comes with version 3.5.1 and remove the older one?

Martin.
