### ISSUE TITLE
TL goes to the top answering toots with emojis

### ISSUE THREAD

**Issue by gaditano66** [mastodon/mastodon#17577]
### Steps to reproduce the problem

1. Simple interface
2. Read many toots
3. Answer a toot with some emoji
...

### Expected behaviour

It should stay in that position

### Actual behaviour

TL goes to the top and you lose where you were reading

### Specifications

When I have been reading the TL in the simple interface for a long time and I want to answer a toot with emojis, the TL usually goes up to the top. Can you fix this problem? Thanks

**Comment by ClearlyClaire** [comment]
I cannot reproduce this issue. Which version of Mastodon are you using? On which browser? How do you use the emoji? From the laughing face emoji in the corner of the textarea? Using autocompletion? In yet another way?

**Comment by gaditano66** [comment]
> I cannot reproduce this issue. Which version of Mastodon are you using? On which browser? How do you use the emoji? From the laughing face emoji in the corner of the textarea? Using autocompletion? In yet another way?

Hi ClearlyClaire.
It happens in chromium and firefox based browsers and not only in my last version 3.4.6, but also in the oldests versions. It doesn't happen always, but please read a lot of toots, for example 1h, 2h or more older and then click to answer some of these toots. If you click the emoji icon then the TL goes up, as I say: not always but it happens many times. It doesn't happen using Pinafore, for example. Recently using Firefox and Librewolf. Thank you.

**Comment by gaditano66** [comment]
> From the laughing face emoji in the corner of the textarea?

Yes, that's it.

**Comment by ClearlyClaire** [comment]
I have no idea why this is happening, but I can indeed reproduce it.

**Comment by gaditano66** [comment]
> I have no idea why this is happening, but I can indeed reproduce it on latest `main`.

Yes, even in the stable brach I used before. Now I'm using the latest main with masto.host
Well, thank you anyway. I'll use the advanced interface or Pinafore instead.

**Comment by ClearlyClaire** [comment]
Some observations:
- this happens no matter how far back you are in the TL
- it never happens the first time the picker is opened, but always happens on subsequent times

I am pretty sure this is linked to the autofocus, probably with the autofocus code triggering before the emoji picker is displayed/properly positioned. I am investigating how this can be fixed.

**Comment by gaditano66** [comment]
Thank you very much!
