### ISSUE TITLE
Web interface fails to load in GNOME Web 41.2, WebKitGTK 2.34.5

### ISSUE THREAD

**Issue by Marie-Joseph** [mastodon/mastodon#17581]
### Steps to reproduce the problem

1. Login to a Mastodon instance through GNOME Web
2. Attempt to load the main timeline

### Expected behaviour

the timeline should load

### Actual behaviour

the timeline does not load

### Specifications

Mastodon: v3.4.6 (and earlier, but not sure of the exact versions; probably all 3.4)
Browser: GNOME Web 41.2, WebKitGTK 2.34.5
OS: GuixSD GNU/Linux

Note that this issue happens with all pages requiring login. The only error in my browser console is "Your browser does not support Web Push Notifications."

**Comment by ClearlyClaire** [comment]
I am unable to reproduce the issue on Mastodon `main` using GNOME Web 41.3, WebkitGTK 2.34.5. I have not tested 3.4.6 yet, so it might have been something from back then that has been fixed since, but I can't think of anything.

**Comment by Marie-Joseph** [comment]
Turns out the problem was missing gst-plugins packages.

Good ol' GNU...
