### ISSUE TITLE
"Filter language" feature not working on public timelines

### ISSUE THREAD

**Issue by KNTRO** [mastodon/mastodon#17599]
### Steps to reproduce the problem

1. Go to [Preferences > Other](https://mastodon.social/settings/preferences/other).
2. Go to the _Public Timelines_ section, and check only one language or a few languages. Click on the _Save changes_ button.
3. Go back to [your Mastodon main page](https://mastodon.social/web/getting-started) and you will note that both the Local timeline and the Federated timeline will be displaying posts in all languages, and not just the selected language(s) in previous step.

### Expected behaviour

Should be working as in previous versions (v3.4.5 or earlier)

### Actual behaviour

Since version 3.4.6, the filter language is not woking and public timelines will be display posts in any language, despite user's choice

### Specifications

**OS**: Ubuntu 16.04 LTS
**Web browser**: Mozilla Firefox 91.6 ESR
**Mastodon Web**: v3.4.6

**Comment by KNTRO** [comment]
As far as I can tell, I think this bug has been fixed already. Closing this issue.

**Comment by ClearlyClaire** [comment]
I've seen another report of this and I think I know what's going on.

**Comment by ClearlyClaire** [comment]
Actually I can't reproduce it, sorry for the noise.
