### ISSUE TITLE
Mark Status/Account as HTTP 451 Not Available For Legal Reasons

### ISSUE THREAD

**Issue by elaine-jackson** [mastodon/mastodon#17591]
### Pitch

I would like a button in the moderation area to mark an entire account or status as HTTP Status 451 unavailable for legal reasons. This is particularly important with DMCA Requests where the account owner has a right to submit a counter notice.

We would still have to send out a delete actor to remove from other instances but could retain the account/status until they've submitted their counternotification and then reannounce it as if it were a new account/status.

### Motivation

This helps reflect when an account is removed for legal reasons vs individual moderation reasons.

**Comment by Gargron** [comment]
I wanted to add restoring for statuses deleted by mods in #17364 but we discovered there were issues un-deleting on remote servers. Either stuff would stay deleted everywhere except local, or you'd have to delay deleting anywhere else for many days which would make it a bit ineffective. For now we are investigating how this could be done.

**Comment by irlcatgirl** [comment]
> I wanted to add restoring for statuses deleted by mods in #17364 but we discovered there were issues un-deleting on remote servers. Either stuff would stay deleted everywhere except local, or you'd have to delay deleting anywhere else for many days which would make it a bit ineffective. For now we are investigating how this could be done.

I would vote for deleting remotely but keeping locally but hidden then it would be rebroadcast once undeleted. It's not perfect and you would lose remote likes/boosts. There's not a perfect solution without updating the ActivityPub RFCs.

**Comment by ClearlyClaire** [comment]
> > I wanted to add restoring for statuses deleted by mods in #17364 but we discovered there were issues un-deleting on remote servers. Either stuff would stay deleted everywhere except local, or you'd have to delay deleting anywhere else for many days which would make it a bit ineffective. For now we are investigating how this could be done.
> 
> I would vote for deleting remotely but keeping locally but hidden then it would be rebroadcast once undeleted. It's not perfect and you would lose remote likes/boosts. There's not a perfect solution without updating the ActivityPub RFCs.

Currently, Mastodon's implementation (and likely others) considers `Delete`s as irreversible, broadcasting the original activity again won't work. See #17553
