### ISSUE TITLE
videos and gifs don't work

### ISSUE THREAD

**Issue by harrma** [mastodon/mastodon#17613]
### Steps to reproduce the problem

1.find a video and clck play
2.it will remain black or bluerd with nsfw options set to uncensored in profile settings
3.and gifs don't do anything besides appear blurry or black and show a little image of a sun over a hill when clicked
...

### Expected behaviour

video or gif play

### Actual behaviour

nothing besides remaining black or bluerd

### Specifications

? it's in my browser in chrome windows 11. When should I expect a reply? (this is my first time using git hub)

**Comment by nemasu** [comment]
I noticed this just now.
I'm running my own instance, and the content was remote, but in my feed.
It was a gif that had a black screen with video controls, and when you press play, nothing happens.

**Comment by vmstan** [comment]
@harrma @nemasu I know this is an older issue, but have you been able to resolve this?
