### ISSUE TITLE
Internationalized domain names could be better formatted

### ISSUE THREAD

**Issue by Altonss** [mastodon/mastodon#17636]
### Steps to reproduce the problem

1. Visit https://mastodon.social/@RegierungBW

### Expected behaviour

The new account domain could have been displayed as bawü.social

### Actual behaviour

The account domain is displayed as xn--baw-joa.social

### Specifications

Mastodon: version 3.4.6
Browser: Mozilla Firefox 97.0
OS: Fedora 35

**Comment by Tritlo** [comment]
This should also be in the profile bar! I.e. My server is over at loðfíll.is, but user profiles are stated to be at xn--lofll-1sat.is!

**Comment by ClearlyClaire** [comment]
Hi! What do you mean by “profile bar”? Visiting your profile on your server seems to use the appropriate representation for the domain name.

**Comment by Tritlo** [comment]
That's because I'm running a fork implementing https://github.com/mastodon/mastodon/pull/21440 :)

**Comment by Tritlo** [comment]
See e.g. https://xn--y9a6bah4ck.xn--y9a3aq/@admin

**Comment by colinstu12** [comment]
@ClearlyClaire why does the /admin/accounts page show the raw IDN domain name yet when you click on a user from this page, then their domain name renders the special characters properly? Ideally this would display the correctly rendered one on both/all pages? 

Also querying on the /admin/accounts page does not work if you put in the special characters, it must be that raw xn-- IDN domain name. Any way to allow querying with both?
