### ISSUE TITLE
Reply under toot

### ISSUE THREAD

**Issue by Geobert** [mastodon/mastodon#1765]
Have the reply box open under the toot we are replying to. (like tweetdeck)

This will fix this as well: https://github.com/tootsuite/mastodon/issues/878
* * * *

- [ y] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by tomfhowe** [comment]
This might be helpful for not losing your place on mobile! I don't know how hard this would be to implement though.
