### ISSUE TITLE
Delete toots automatically: all toots or 1 week

### ISSUE THREAD

**Issue by gaditano66** [mastodon/mastodon#17658]
### Pitch

I think we need more options to delete toots automatically like these ones:

- Adding also 1 week to the option.
- Delete all toots, media, etc
Thanks

### Motivation

Sometimes we don't want toots for more than 1 week in our profiles. Or maybe we want to start again and delete all that we've done before.

**Comment by ClearlyClaire** [comment]
I guess we could add a “one week” option, but I do not understand your “Delete all toots, media, etc” suggestion: you just have to not select exceptions to the deletion policy?

**Comment by gaditano66** [comment]
> I guess we could add a “one week” option, but I do not understand your “Delete all toots, media, etc” suggestion: you just have to not select exceptions to the deletion policy?

Hello!
Thank you!

About "delete all toots, media, etc" I mean, not automatically, to delete in those moments inmediately all that you've done before and start again: make your account empty.

Thank you!

**Comment by ClearlyClaire** [comment]
Deleting all contents immediately is not possible, as explained in that tool's description.

**Comment by gaditano66** [comment]
> Deleting all contents immediately is not possible, as explained in that tool's description.

Oh, no problem then. Anyway, if we only have 1 week history we can delete all the content manually and it's not so hard.
Thanks
