### ISSUE TITLE
tootctl modify does not have a --skip-sign-in-token command

### ISSUE THREAD

**Issue by carlchenet** [mastodon/mastodon#17666]
### Steps to reproduce the problem

1. use 3.4.6 version
2. cd bin && RAILS_ENV=production ./tootctl account modify --help 
```
Usage:
  tootctl accounts modify USERNAME

Options:
  [--role=ROLE]                              
  [--email=EMAIL]                            
  [--confirm], [--no-confirm]                
  [--enable], [--no-enable]                  
  [--disable], [--no-disable]                
  [--disable-2fa], [--no-disable-2fa]        
  [--approve], [--no-approve]                
  [--reset-password], [--no-reset-password]
```
The official documentation mentions a --skip-sign-in-token option at https://docs.joinmastodon.org/admin/tootctl/
```
RAILS_ENV=production ./tootctl account modify --skip-sign-in-token admin
ERROR: "tootctl accounts modify" was called with arguments ["-skip-sign-in-token", "admin"]
Usage: "tootctl accounts modify USERNAME"
```

### Expected behaviour

--skip-sign-in-token should be available for the tootctl account modify command

### Actual behaviour

--skip-sign-in-token is not available for the tootctl account modify command

### Specifications

3.4.6

**Comment by Gargron** [comment]
It is available in main
