### ISSUE TITLE
Bump node-redis to v4 break streaming in WebUI?

### ISSUE THREAD

**Issue by lindwurm** [mastodon/mastodon#17660]
### Steps to reproduce the problem

Open any timeline in WebUI

### Expected behaviour

timeline streaming works correctly

### Actual behaviour

- some public posts are missing in local timeline.
- ~~console from Browser says `Unchecked runtime.lastError: The message port closed before a response was received.` every few minutes.~~

#### affected

- 50ab3f3dcb6b00109fa1462a5ca0228563abb99b (`main` when v3.4.6 released): reproduced
- a5c24d5c4d75f3f3144f69c8f60f542707a82584 (`main` in yesterday ): reproduced
- 8f6c67bfdeddd1c2c1085067e3dc549fb53f6ff4 (`main`): reproduced

#### not affected

- I've reverted these node-redis v4 related commits for my server, it works again:
  - bfe5ad5fee3e0ccc8ab480b311af1cf3c8fdcb2c
  - 777b248bd1a9f204427a99e7b2af7cb40435bc32
  - bc066d8936e2cfaa2dc275d9a5d4aefc0cbc1d86
  - 4d1eaf3e6e45a2141fd0e7d8deb2e4485485a177
  - 512bc9db7da6ac53d3d62ef5afcf4d49cec9e780

**Comment by Gargron** [comment]
Is this what you also experienced @mayaeh?

**Comment by mayaeh** [comment]
@Gargron @lindwurm I'm sorry I'm late to notice.
Not long ago I had a similar problem on my server.
But it hasn't happened in my environment since the update node-redis v4.0.3 and #17559 of Mastodon.

**Comment by mayaeh** [comment]
However, my server has few posts to LTL, so it may go unnoticed by me.

**Comment by lindwurm** [comment]
I forgot to apply these changes in my `nginx.conf` ...

- e03dc3956f8c7c20914775ca1aca19decf61b616
- a2afcac7d9d55860f62f2f27475cd5a059090505
- 48caeb9d659abd58ec7a9dc04f7365b35e314b74

I'll test it for a few hours

**Comment by lindwurm** [comment]
fixed by #17841
