### ISSUE TITLE
Can't edit media of scheduled post

### ISSUE THREAD

**Issue by connyduck** [mastodon/mastodon#17676]
### Steps to reproduce the problem

1. schedule a post with media attached
2. change the attachment description with /api/v1/media/:mediaId

### Expected behaviour

media description is changed, /api/v1/media/:mediaId returns 200

### Actual behaviour

/api/v1/media/:mediaId returns 404

### Specifications

v3.4.6, mastodon.social

**Comment by Gargron** [comment]
Is this a regression or it never worked?

**Comment by connyduck** [comment]
I have no idea to be honest. It has not been working for over a year though.
