### ISSUE TITLE
My pouets are falling with a 500 error since 3 weeks

### ISSUE THREAD

**Issue by PGaJK** [mastodon/mastodon#17695]
### Steps to reproduce the problem

1.[PG_JK @PG_JK@mastodon.top]
(https://mastodon.top/@PG_JK)
2.It (a 500 error ) appeared Suddenly in my Pouets with hashtags since 3 weeks, until then it worked perfectly.
I don't know why.
That's the reason why I send less messages, as you may know.
3.My Pouet is sent 
but my Pouet keeps appearing with the error 500 as if it had not been sent.
4.This is not a new instance ;
This new problem is on my working instance since my registration in January 2020.
5. Despite the "500 error", the mails are on my Timeline. 

5.Crossposting  between Mastodon and Twitter. isn't working. 
Crossposting isn't working from mastodon to twitter, neither from twitter to mastodon.

Thanks for your help, have a nice day.

### Expected behaviour

A Error 500 should not appear.

### Actual behaviour

A Error 500 appeared Suddenly in my Pouets with hashtags.

### Specifications

The browser is google chrome.

**Comment by ClearlyClaire** [comment]
I'm not sure I understand what's happening. Do you get errors when posting any toot or only toots with hashtags?
Or is it related to a hashtags column?

Ideally, when a 500 error occurs, we would need the server-side logs to understand what is going on, so if you can, try to get your server admin in the loop so we have logs to look at.

**Comment by PGaJK** [comment]
Thank you for your quick response.
It seems ;
A 500 error  appears Suddenly when I post only toots with hashtags.
I just discovered this point while writing to you ;
until now I've always written with hastags.
I don't know how to contact an admin on mastodon.top,
many thanks and best regards.

**Comment by Gargron** [comment]
I am sorry but we cannot help you with mastodon.top because it is not ours.
