### ISSUE TITLE
Word filters do not apply to hashtags

### ISSUE THREAD

**Issue by drone621** [mastodon/mastodon#17703]
### Steps to reproduce the problem

1. Filter a word, for example "test"
2. If the word appears in a hashtag, for example #test the toot will not be filtered.
3. This is despite the "Whole Word" option being unchecked, meaning that ideally #test should be treated the same as test.

### Expected behaviour

The toot with the filtered word as a tag should be filtered.

### Actual behaviour

The toot with the filtered word as a tag was still displayed.

### Specifications

This was encountered on mastodon.social. Version 3.4.6.

**Comment by artemmikhalitsin** [comment]
Hi @drone621, could you let me know in which context the post with the hashtag wasn't filtered (i.e. Home timeline, Profile, etc)?

**Comment by drone621** [comment]
Sorry for omitting that detail. The filter is set to filter every context except "Conversations". The posts escaped filtering in the Home and Federated timelines.

**Comment by drone621** [comment]
Sorry for the radio silence. "Drop instead of hide" is unchecked. I noticed this in the Mastodon web interface, but I haven't noticed it in a week. I looked for old toots, found them filtered as well and I'm starting to wonder if I had misconfigured the filter or if it took a few days to take effect. Apologies for the bad bug report and the waste of time.
