### ISSUE TITLE
joinmastodon.org is down

### ISSUE THREAD

**Issue by swannty** [mastodon/mastodon#17701]
### Steps to reproduce the problem

As of March 4, 2022 it is impossible to access the website docs.joinmastodon.org

(not sure this is the right place to report this problem)

### Expected behaviour

Website should be online

### Actual behaviour

Error 522 Connection timed out

### Specifications

Debian GNU/Linux 11 (bullseye)
Firefox 97.0.1

**Comment by ClearlyClaire** [comment]
Solved.
