### ISSUE TITLE
[feature] adding quote-toots to retoot function

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [mastodon/mastodon#17714]
so yes. now the only way to refer to other toot is to copy link of it. twitter have a feature to quote tweets, so content of tweet is visible. ithink thatvshuch feature could work good in mastodon cause its twitter-similar (also it'd help people to faster spread info and mastodon to get new users from twitter =] )

**Comment by ClearlyClaire** [comment]
This feature has been requested before, and explicitly refused for the reasons described in https://github.com/mastodon/mastodon/issues/309#issuecomment-469260847

**Comment by hacknorris-aka-penguin** [comment]
okay nvm
