### ISSUE TITLE
some environment cannot be displayed "Local timeline" and "Federated timeline"

### ISSUE THREAD

**Issue by mayaeh** [mastodon/mastodon#17756]
### Steps to reproduce the problem

1. Open Mastodon in an environment with a resolution similar to the landscape view of the iPad.
2. Ucheck "Enable advanced web interface" in the settings.
3. Back to Mastodon.

<img width="838" alt="2022-03-04 15 09 15" src="https://user-images.githubusercontent.com/766076/158044268-20fcc016-cc25-4e94-b0da-9e2351b2343e.png">
<img width="838" alt="2022-03-04 15 09 53" src="https://user-images.githubusercontent.com/766076/158044272-e56c22ef-08ed-4aac-acec-45c5aa130bce.png">

### Expected behaviour

LTL and FTL menu items appear in tab bars and menus

### Actual behaviour

Some environments, such as the iPad in landscape mode, do not display the menu items required to access the LTL or FTL in a single column layout.

### Specifications

* Mastodon main branch
* iPad landscape mode
* don't check "Enable advanced web interface"

**Comment by Gargron** [comment]
This is due to the `optional` class I added in tab bar mistakenly
