### ISSUE TITLE
Trending links not showing up

### ISSUE THREAD

**Issue by dadall** [mastodon/mastodon#17803]
### Steps to reproduce the problem

1. Connect to the admin panel
2. Allow links from 2 publishers
3. Wait 1h

### Expected behaviour

News colomn feeded with approved links

### Actual behaviour

News feed empty

### Specifications

Debian 11
PostgreSQL 13
Ruby 3.0.3
Redis 6.0.16

### Context 

I've users deleting their old toots and 10k sidekiq jobs queued. Can it explain something?

**Comment by Gargron** [comment]
Please allow user activity to accumulate, trends will not appear from old data.

**Comment by dadall** [comment]
It works now !

Thanks for this amazing release <3
