### ISSUE TITLE
weird character `Â·` in user profile's preview card

### ISSUE THREAD

**Issue by tusooa** [mastodon/mastodon#17816]
### Steps to reproduce the problem

1. Open https://t.tusooa.xyz/@tusooa
2. View its source
3. Find a meta tag with name=description
...

### Expected behaviour

There should be no weird character there

### Actual behaviour

`Â·` presents: `<meta content="XXX Posts, XX Following, XX Followers Â· ...." name="description">`

### Specifications

3.4.1

But also see https://mastodon.social/@Gargron , which is running `v3.5.0rc1`

**Comment by ClearlyClaire** [comment]
Looks like an encoding error introduced in #12078
