### ISSUE TITLE
Upgrade instructions to 3.5.0rc1 (from 3.4.6) seem incorrect - no git pull/fetch step

### ISSUE THREAD

**Issue by DalekDave** [mastodon/mastodon#17824]
### Steps to reproduce the problem

1. Follow upgrade instructions at https://github.com/mastodon/mastodon/releases/tag/v3.5.0rc1

2. There is no git pull/fetch step for the new source code

3. Follow all instructions for non-Docker scenario

4. All steps conclude successfully, including restart, and but Mastodon version number remains at 3.4.6 on the Mastodon instance's About page

5. Start upgrade process again, commencing with git fetch && git checkout -f v3.5.0rc1

   Seems to complete OK, with following message:
   
   Previous HEAD position was 93a6c143a Fix insufficient sanitization of report comments (#17430)
HEAD is now at 4bdce2c51 Bump version to 3.5.0rc1 (#17618)

6. Execute  bundle install

   I get the error message : rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
   
7. Bite fingers nervously and carefully do not restart Mastodon instance again before getting adivice/solution from developers

...

### Expected behaviour

Version on instance About page should incerment to 3.5.0rc1

### Actual behaviour

Version on instance's About page remains at 3.4.6

### Specifications

Previous HEAD position was 93a6c143a Fix insufficient sanitization of report comments (#17430)
HEAD is now at 4bdce2c51 Bump version to 3.5.0rc1 (#17618)

**Comment by benharri** [comment]
Might want to add a note in the changelog for updating ruby with rbenv

**Comment by bgman111111** [comment]
very dissaponted from @rf and from @gargron the c.e.o. from mastodon. who insult peoples and then block them. Include they flood website mastodon admins who dont think like @gargron. And i see from my experience from mastodon include @stux the worse peoples. im no more mastodon. deleted from my vps with pleasure we in france dont like mastodon

**Comment by shleeable** [comment]
It is true.. the `git fetch && git checkout v3.5.0rc1` is missing from the notes.

Hopefully you've got the problem sorted tho

**Comment by ClearlyClaire** [comment]
Yeah, as @benharri pointed out, the release notes are lacking instructions regarding updating Ruby with rbenv.

[Update the list of ruby versions available to `rbenv`](https://github.com/rbenv/rbenv#updating-the-list-of-available-ruby-versions) if needed, then build Ruby 3.0.3 with `RUBY_CONFIGURE_OPTS=--with-jemalloc rbenv install 3.0.3`.

I edited the release notes to add some more information about this as well as summarize dependencies.
