### ISSUE TITLE
Give a clearer explanation for error message (in this case: remote subscribe went wrong)

### ISSUE THREAD

**Issue by Fil** [mastodon/mastodon#1783]
Trying to remote follow alexis@social.notmyidea.org (ping @ametaireau) results in an indistinct error message
https://mamot.fr/authorize_follow?acct=alexis%40social.notmyidea.org

<img width="549" alt="capture d ecran 2017-04-14 a 11 25 21" src="https://cloud.githubusercontent.com/assets/7001/25048190/5c02179a-213b-11e7-9fb2-2f643a87bbd5.png">

cc: @vincib

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by JantsoP** [comment]
Looks like an issue with the social.notmyidea.org instance. Please contact the Instance admin. This is not an issue for github.

**Comment by yipdw** [comment]
This issue is about changing the error message to provide more details, not whether the error occurs.

**Comment by Fil** [comment]
I disagree. In the event that the remote server doesn't work as expected,
my instance SHOULD give me an explicit reason and to allow me to understand
what is failing. If only "the remote instance has a problem".

**Comment by mjankowski** [comment]
Can you go into more detail on the exact steps to reproduce the issue?

**Comment by Fil** [comment]
Go to https://social.notmyidea.org/@alexis, click "remote follow"
browser goes to https://social.notmyidea.org/users/alexis/remote_follow
type your masto login (fil@mamot.fr)
enjoy

**Comment by trwnh** [comment]
remote follow dialog was removed in 4.0 -- see #24842 for its successor
