### ISSUE TITLE
#16605 not merged

### ISSUE THREAD

**Issue by HolgerHuo** [mastodon/mastodon#17849]
### Steps to reproduce the problem

...

### Expected behaviour

...

### Actual behaviour

Pull Request  #16605 not merged into main branch or following releases. 

### Specifications

..

**Comment by HolgerHuo** [comment]
BTW, Mastodon docs haven't been reviewed for a while.
[https://github.com/mastodon/documentation/pulls](https://github.com/mastodon/documentation/pulls)

**Comment by Gargron** [comment]
It was merged into main on Aug 20, 2021

But we have not had a feature release since that time. 3.5.0rc1 is the first tag where your commit appears.

**Comment by HolgerHuo** [comment]
Oh. Sorry for my mistake. At first, i thought it should be released in minor versions(as a bug fix) and when my instance still couldn't handle this job natively, I checked this pull request, which, however, GitHub redirects to my fork of Mastodon by default(which I've neglected). As my fork of Mastodon follows stable releases, the fix wasn't included, sorry for the mistake.
