### ISSUE TITLE
When changing email address, confirmation mail does not include confirm link

### ISSUE THREAD

**Issue by CplPibald** [mastodon/mastodon#17868]
### Steps to reproduce the problem

Steps to reproduce:
1. go to /auth/edit
2. change your email address
3. enter your current password
4. Click "Save Changes"

Message displayed:

`You updated your account successfully, but we need to verify your new email address. Please check your email and follow the confirm link to confirm your new email address. Please check your spam folder if you didn't receive this email.`

Email that arrived:

````
The email address for your account is being changed to:

xyz@example.com

If you did not change your email, it is likely that someone has gained access to your account. Please change your password immediately or contact the server admin if you're locked out of your account.
````

### Expected behaviour

Email shows up with confirmation link to complete

### Actual behaviour

Email that arrives has no confirmation link or mention of confirmation at all.  Unable to complete email address change.

### Specifications

mastodon v3.4.6 on masto.host

**Comment by Gargron** [comment]
The e-mail you are quoting arrives at the *old* address, it is a notification and it is not supposed to contain a confirmation link. The new address receives the confirmation e-mail.
