### ISSUE TITLE
422 when approving pending account via admin API

### ISSUE THREAD

**Issue by JamesABDL** [mastodon/mastodon#17898]
### Steps to reproduce the problem

Send a POST to `/api/v1/admin/accounts/:id/approve` as detailed here: https://docs.joinmastodon.org/methods/admin/

```
[e18fc6c8-e58d-4524-9468-1315dc7a1efc] method=POST path=/api/v1/admin/accounts/10803970834686xxxx/approve format=*/* controller=Api::V1::Admin::AccountsController action=approve status=422 duration=4.71 view=1.32 db=0.59
```

### Expected behaviour

Should approve the account and return 200

### Actual behaviour

Returns 422 and no approval

### Specifications

This is a follow up from #17870, getting pending accounts is working again, but now we can't approve them.

Again this was working before in our little automated account approval script, but now getting stuck on this.

**Comment by ClearlyClaire** [comment]
The 422 reply should come with an error message, can you tell us what it is?

**Comment by Gargron** [comment]
What's the locale column of the user that returns this error?

**Comment by Gargron** [comment]
Well, looks like my guess was completely off. Not related to validation at all.

This error is due to the accidentally added CSRF requirement in #17204.

Of course, this information comes mere minutes *after* 3.5.0 is released.

**Comment by JamesABDL** [comment]
Any workaround for this currently?

**Comment by ClearlyClaire** [comment]
> This error is due to the accidentally added CSRF requirement in #17204.

Would there be any downside to removing the `protect_from_forgery with: :exception` occurrences that were added in that PR?

**Comment by ClearlyClaire** [comment]
@JamesABDL can you check that #17975 fixes it for you?

**Comment by JamesABDL** [comment]
@ClearlyClaire yes, fixed, thanks!
