### ISSUE TITLE
Russian UI not rounding stats in about/more

### ISSUE THREAD

**Issue by drequivalent** [mastodon/mastodon#17904]
### Steps to reproduce the problem

1. Open about/more page in Russian locale
2. Open about/more page in English locale
3. Compare

### Expected behaviour

English shows "123 K posts", while Russian shows "123 тыс. постов"

### Actual behaviour

English shows "123 K posts", while Russian shows "123 321 тыс. постов" which translates into "123 321 K posts".

### Specifications

![Снимок экрана от 2022-03-30 00-10-00](https://user-images.githubusercontent.com/1463277/160707510-46f5ef2f-153e-4bf7-ad5a-77f9b0b0afc5.png)
![Снимок экрана от 2022-03-30 00-09-53](https://user-images.githubusercontent.com/1463277/160707516-3122ddb5-6221-4569-8957-6684261abfed.png)

**Comment by Brawaru** [comment]
I had been able to trace this to the following commit:
https://github.com/mastodon/mastodon/commit/e2844b7e58e1ebdf666c5fecc97a75620da7bddf#diff-5f3fc5e3977d242572aa1d08551f5eb557de0ccaff30370838ee9df5386ea0daR17-R27

Basically in this commit precision was changed to 3 and what you see is the product of it. Russian uses comma as decimal separator and space as thousands separator. Thus if you divide 1,565 by 1,000 you get... 1.565 which in Russian with fraction precision of three would look like... `1,565`. The fix would be to use fraction precision of 1, but I am not sure how other languages agree on that, I think default Rails behaviour of per-language settings is preferable.

**Comment by ClearlyClaire** [comment]
I'm a bit confused, I understand from @drequivalent that the reported count is plain wrong, while I understand from the code and @Brawaru's post that it's “just” displayed in a weird and unusual way.

It seems that Rails' default for the screenshot would be “1,6 тыс” and “380,8 тыс”.

I guess reverting the referenced patch could be a good idea, but `rails-i18n` language definitions are incorrect for some languages, leading to weird and unexpected rounding. For instance, using 380842 posts would be rounded to “400 m”

**Comment by ClearlyClaire** [comment]
An issue with the code from https://github.com/mastodon/mastodon/commit/e2844b7e58e1ebdf666c5fecc97a75620da7bddf#diff-5f3fc5e3977d242572aa1d08551f5eb557de0ccaff30370838ee9df5386ea0daR17-R27 is that it overrides the precision level, but without overriding the fact that the precision is about the number of significant digits and not of fractional digits.

Therefore, I guess a fix would be to set `significant` to `true`, which in this case would lead to “1,57 тыс” and “381 тыс”. Not sure how much better that would be to a Russian speaker.

**Comment by Brawaru** [comment]
Hey, @ClearlyClaire. That is much much better, it's essentially the same as 1.57K and 381K in English, which is pretty close to a full number. The rounding issue with other languages feels like a bug, maybe it's worth reporting to Rails devs? In meanwhile maybe `friendly_number_to_human` helper can see which language is used and apply these options if Rails definitions are incorrect (instead of all languages)?

**Comment by ClearlyClaire** [comment]
> Hey, @ClearlyClaire. That is much much better, it's essentially the same as 1.57K and 381K in English, which is pretty close to a full number.

Alright, see #17929

> The rounding issue with other languages feels like a bug, maybe it's worth reporting to Rails devs? In meanwhile maybe `friendly_number_to_human` helper can see which language is used and apply these options if Rails definitions are incorrect (instead of all languages)?

Yes, as described in https://github.com/mastodon/mastodon/issues/16435#issuecomment-870719530 it's known, and it seems it has been fixed for newer versions of `rails-i18n`, which we should probably update.
