### ISSUE TITLE
Single quote character is corrupted in v.3.5.0 (regression)

### ISSUE THREAD

**Issue by bruceleerabbit** [mastodon/mastodon#17928]
### Steps to reproduce the problem

I’m simply posting a msg that contains straight single quotes.  I usually use a proper curved apostrophe (’), but sometimes I get lazy and use the straight single quote (') because it’s one keystroke.  Posts are submitted using a text-based client (not the stock Mastodon web client), but the server-side has just started doing something funky.

### Expected behaviour

a single quote should have remained as a single quote

### Actual behaviour

Straight single quotes are being replaced with an HTML encoding “`&#39;`”, which then appears as a literal `&#39;` when the API sends the msg to a plaintext based client.  This makes messages quite hard to read for non-GUI users.

Note that the status appears fine if it is rendered in a browser because `&#39;` has meaning to HTML browsers.  But it doesn’t belong in plaintext.

### Specifications

3.5.0
(no problem in past versions although I don't know exactly which past version was installed before the migration to 3.5.0)

**Comment by ClearlyClaire** [comment]
As far as I can tell, single straight quotes have always been escaped, but they were previously escaped as `&apos;` while they are now escaped as `&#39;`.

The behavior change is from #17828 which changed the function used for escaping HTML in toots to a significantly more efficient function (`ERB::Util.encode` instead of `HTMLEntities#encode`).

**Comment by ClearlyClaire** [comment]
I am inclined to close this issue as wontfix, considering status' contents are defined as HTML, and `&#39;` is a valid HTML encoding, so while there *is* a behavior change, that behavior change is correct.

Furthermore, the API can't make any guarantee about the encoding of remote posts, so remote posts could be using different HTML entities the plaintext client would have to handle too.
