### ISSUE TITLE
search engine failed

### ISSUE THREAD

**Issue by jiangshanghan** [mastodon/mastodon#17920]
### Steps to reproduce the problem

i was trying to search a post from another instance

### Expected behaviour

the aim postshoulb show on the search page

### Actual behaviour

the web page shows a tip: doesn't work

### Specifications

TypeError: t.get(...) is undefined

Q@https://slashine.onl/packs/js/features/explore-fb068da9adcd83f0fde2.chunk.js:1:4416
805/a.render@https://slashine.onl/packs/js/features/explore-fb068da9adcd83f0fde2.chunk.js:1:5774
Bi@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:1069030
qi@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:1068825
ks@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:1104439
vu@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:1095882
mu@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:1095805
su@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:1092835
$o/<@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:1044476
t.unstable_runWithPriority@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:1119534
Qo@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:1044185
$o@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:1044423
Yo@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:1044356
uu@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:1093126
notify@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:110758
notifyNestedSubs@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:111354
o@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:111188
v@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:341920
Lt/</</<@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:391755
Lt/</</<@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:391299
Lt/</</<@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:391052
p/</</<@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:342674
dispatch@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:390545
m/</<@https://slashine.onl/packs/js/common-a9f562a436aa80fe0012.js:2:233714

renderAccounts (webpack:///app/javascript/mastodon/features/explore/results.js:27:83)
ImmutableList (webpack:///app/javascript/mastodon/features/explore/results.js:75:49)
expirationTime (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:3769:14)
expirationTime (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:3757:16)
ng (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6003:19)
Mi (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5365:)
c.insertBefore (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5360:131)
Ii (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5132:)
Ie (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2110:44)
Wg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6970:9)
Ee (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2086:)
He (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2104:15)
He (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2098:44)
Ji (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5161:31)
batch(function (webpack:///node_modules/react-redux/es/utils/Subscription.js:15:6)
notifyNestedSubs (webpack:///node_modules/react-redux/es/utils/Subscription.js:85:14)
handleChangeWrapper (webpack:///node_modules/react-redux/es/utils/Subscription.js:90:19)
Error (webpack:///node_modules/redux/es/redux.js:289:21)
audio.pause (webpack:///app/javascript/mastodon/middleware/sounds.js:15:21)
action.type.match (webpack:///app/javascript/mastodon/middleware/errors.js:10:10)
action.type.match (webpack:///app/javascript/mastodon/middleware/loading_bar.js:18:29)
function (webpack:///node_modules/redux-thunk/es/index.js:10:11)
_dispatch (webpack:///node_modules/redux/es/redux.js:656:18)
dispatch(importFetchedAccounts (webpack:///app/javascript/mastodon/actions/search.js:57:48)

**Comment by Gargron** [comment]
I believe it may be a bug that has already been fixed in 3.5.0. Without version information in the report it's hard to tell.
