### ISSUE TITLE
Make it possible for admins to auto-approve posts and links on the Explore page

### ISSUE THREAD

**Issue by joenepraat** [mastodon/mastodon#17934]
### Pitch

Please make it possible to automatically approve trending posts and links on the Explore page. This is also possible for trending hashtags. Most of the well moderators servers have already non-problematic content trending, because of the organic network effect of their users. If there are problematic posts and links they can be removed later or reported by the users. I think it's up to  the admin to decide this. 

### Motivation

Most moderators don't have the time to approve posts and links as few per day or even daily. Therefore I predict that the Posts and News tab on the Explore pages will not be updated on many servers very often. This defies the use case of the Explore page.

**Comment by joenepraat** [comment]
I have an idea to make this easier (I think): Make the setting `Allow hashtags to trend without prior review` on the /admin/settings/edit page, also valid for trending posts and links. Actually this seems very logical to me.

**Comment by shleeable** [comment]
I support this. Less admin operational overhead, and people can report bad posts.

**Comment by tigransimonyan** [comment]
Is it possible to disable only email notifications?

**Comment by joenepraat** [comment]
> Is it possible to disable only email notifications?

This is off-topic, but yes go to .../settings/preferences/notifications and disable New trend requires review.

**Comment by mashirozx** [comment]
> > Is it possible to disable only email notifications?
> 
> This is off-topic, but yes go to .../settings/preferences/notifications and disable New trend requires review.

no, this doesn't work for me
