### ISSUE TITLE
Users keep getting asked for login code every day

### ISSUE THREAD

**Issue by verymilan** [mastodon/mastodon#17938]
### Steps to reproduce the problem

As far as i understand right now, some users log in to their Mastodon account at least once a day and after the recent update, they each time get asked for a login code because their last login was "a long time ago".

Personally, i was unable to reproduct this by simply logging off and on again. I was wondering if this could somehow be related to my other problem here: https://github.com/mastodon/mastodon/discussions/17932

**Edit:** [asking users](https://social.tchncs.de/@milan/108061985637324850) reveals that this likely is related to the user IP, since normal household ones change every 24h or so. Since my problem linked above (which also affects other instances), it can get even more annoying because when the queue is not properly processes, it is not only one more step but also much more time added to the login routine...

### Expected behaviour

Either wording should be different or the timeframe more relaxed

### Actual behaviour

Login code because they last login was "a long time ago".

### Specifications

v3.5.0, git

**Comment by MamaShip** [comment]
I had the same problem since v3.5.0 (asking user for email verification every day)

One user reported this issue and mentioned that he was using Incognito Window to visit Mastodon. And this didn't happen before.

**Comment by mfa777** [comment]
Same problem

**Comment by Gargron** [comment]
We are looking into this
