### ISSUE TITLE
`from:` search prefix 500s when the supplied account cannot be found

### ISSUE THREAD

**Issue by aescling** [mastodon/mastodon#17941]
### Steps to reproduce the problem

originally reported at https://github.com/glitch-soc/mastodon/issues/1730; Claire has confirmed the issue is with upstream.

1. I search for a post using from:, using an @; e.g., from:@aescling phone.
2. A toast reports that the seach 500s.

### Expected behaviour

Either the syntax should have been acceptable, or the backend should properly indicate that this is a syntax error.

### Actual behaviour

A toast appeared reporting a 500 error.

### Specifications

My instance is on https://github.com/kibicat/mastodon/commit/d0f03db93d83122cfaee46b0e12cff51b6b11702, which merges in https://github.com/glitch-soc/mastodon/commit/363773d0e9ffa9f4efc564603327f225193a2bf1, which merges 3.5.0 into glitch-soc.

The instance is running Elasticsearch 7.17.2 and Postgres 13.5-0+deb11u1.

**Comment by single-right-quote** [comment]
So it turns out the code will always 500 if it fails to find an account, which is Undesirable.

An interesting corner case I do not understand: when using `username@domain` syntax for a local account, the server will fail to find the local account, with the aforementioned Undesirable results.

**Comment by ClearlyClaire** [comment]
I see you have started working on a fix. Mind submitting it as a PR?

**Comment by single-right-quote** [comment]
> I see you have started working on a fix. Mind submitting it as a PR?

I&#x2019;ve been holding off as I&#x2019;m not sure the changes are fully satisfactory yet (and because I&#x2019;ve taken the liberty to make opinionated adjustments for GlitchCat specifically), but it&#x2019;s at least at a point that addresses the main issue, so might as well!

**Comment by mjankowski** [comment]
I believe the linked PR resolved this, but did not auto-close.

Please reopen if thats wrong and this still occurs on 4.3 release!
