### ISSUE TITLE
StatusesIndex: NoMethodError: undefined method `extract_status_plain_text' for StatusesIndex:Class

### ISSUE THREAD

**Issue by markusblogde** [mastodon/mastodon#17965]
### Steps to reproduce the problem

1. Upgraded Elasticsearch to 7.17.2
2. Upgraded Mastodon to 3.5.0
3. View sidekiq queue

### Expected behaviour

sidekiq queue should be processed

### Actual behaviour

queue filled up with index errors:

NoMethodError: undefined method `extract_status_plain_text' for StatusesIndex:Class

### Specifications

mastodon v3.5.0

**Comment by mfa777** [comment]
I got plenty of same error, it looks like going to be solved in next version: https://github.com/mastodon/mastodon/issues/17913

**Comment by ClearlyClaire** [comment]
Duplicate of #17913, fixed by #17912 (not released yet, to be included in 3.5.1)
