### ISSUE TITLE
Explore should optionally limit how many featured posts come from a single user simultaneously

### ISSUE THREAD

**Issue by FediVideos** [mastodon/mastodon#17972]
### Pitch

The Explore posts tab is really useful but sometimes it gets dominated by lots of posts simultaneously visible from the same user.

It would be nice if admins could limit how many of the posts in Explore come from a single user at the same time, so that Explore gives a more diverse selection of posts.

On one instance today I see five of the same user's posts featured in Explore simultaneously! This is too much.

### Motivation

Having a more diverse selection of featured posts would help promote a more diverse Fediverse. It would give more people a shot at being discovered.

(I say all this as someone who is often featured in Explore, I don't want to take more than my fair share of space, and I also want to discover more new people!)

**Comment by Gargron** [comment]
I was actually thinking the same!

**Comment by FediVideos** [comment]
There are no longer multiple posts from the same user, so I'll close the issue as it's now resolved! Thank you devs! :+1:
