### ISSUE TITLE
Moderation User Warning Emails Not Being Sent Due To ActionView::Template::Error

### ISSUE THREAD

**Issue by packetbiral** [mastodon/mastodon#17990]
### Steps to reproduce the problem

1. Suspend user and select warning preset 
2. "Notify the user per e-mail" is selected
3. Click Perform Action
...

### Expected behaviour

User should have been sent a warning email with the preset text

### Actual behaviour

UserMailer#warning job returns ActionView::Template::Error: undefined method `linkify' for #<ActionView::Base:0x00000003a2e038> Did you mean? link_to_if

### Specifications

Mastodon v3.5.0

**Comment by ClearlyClaire** [comment]
Fixed by #17983
