### ISSUE TITLE
tootctl accounts refresh failed because wrong remote url for avatars and headers.

### ISSUE THREAD

**Issue by buzhangjiuzhou** [mastodon/mastodon#18007]
### Steps to reproduce the problem

After deleted some medias carelessly , I want to refetch avatars and headers of remote users, so I use tootctl accounts refresh to do it.

And it returns 404 as follows:

/opt/mastodon/app/models/concerns/remotable.rb:25:in `block (2 levels) in remotable_attachment': https://mstdn.social/system/path/to/file returned code 404 (Mastodon::UnexpectedResponseError)
        from /opt/mastodon/app/lib/request.rb:75:in `perform'
        from /opt/mastodon/app/models/concerns/remotable.rb:24:in `block in remotable_attachment'
        from /opt/mastodon/lib/mastodon/accounts_cli.rb:366:in `refresh'
        from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
        from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
        from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from /opt/mastodon/bin/tootctl:8:in `<main>'

I tried use domain and it successed on most accounts while failed on some accounts.

And I opened the page on browser without error, during which I found out the error:

Some avatars and headers on mstdn.social with path like media.mstdn.social/path/to/file and my mastodon request mstdn.social/system/path/to/file

while some avatars and headers on mstdn.social with path like mstdn.social/system/path/to/file and my mastodon request media.mstdn.social/path/to/file

Maybe it is related to the instance, but it behaves well on web browsers. Mastodon should be able to handle this situation.

### Expected behaviour

It refreshes missing avatars and headers

### Actual behaviour

It returned 404 for some accounts.

### Specifications

mastodon 3.5.1 in docker.

**Comment by mfa777** [comment]
You can merge this PR [384275 to](https://github.com/mastodon/mastodon/pull/16414) to correct `remote_url` in database temporarily.
