### ISSUE TITLE
Websocket Connection Error & 500 error for image upload

### ISSUE THREAD

**Issue by alaksandarjesus** [mastodon/mastodon#18003]
### Steps to reproduce the problem

1.  Create an account with digital ocean
2. Install Mastodon from marketplace
3. Create aws bucket and give the credentials
4. Test the webpage console.log
...

### Expected behaviour

No errors in console and image should be uploaded

### Actual behaviour

Throwing errors

### Specifications

v3.1.3

![image](https://user-images.githubusercontent.com/4712552/162560252-53afac27-4319-4389-b1cb-eac73bea9f4a.png)

**Comment by ykzts** [comment]
v3.1.3 is no longer supported.
