### ISSUE TITLE
Can't create Account Alias for User Migration

### ISSUE THREAD

**Issue by halogeno** [mastodon/mastodon#18033]
### Steps to reproduce the problem

1. Log into Server1
2. click at Preferences
3. click at Account
4. click at Link "create an account alias"
5. You get the blue mastodon hitting the keyboard error...

I've tried it on four different mastodon server with the same result.

### Expected behaviour

It should create an account alias.

### Actual behaviour

The blue mastodon hitting the keyboard error appears.

### Specifications

on mastodon 3.5.1 and older versions

**Comment by shleeable** [comment]
This was fixed in main. https://github.com/mastodon/mastodon/pull/18004
It'll be out next stable.

**Comment by halogeno** [comment]
Thanks, I will wait.

**Comment by Lukas2112** [comment]
Will the update also make it possible to transfer the cancelled toots from the old profile to the new one, @shleeable ?

**Comment by shleeable** [comment]
> Will the update also make it possible to transfer the posted toots from the old profile to the new one, @shleeable ?

No. that isn't supported yet.

**Comment by ludwigprager** [comment]
Looks like I still have it in v3.5.3.
Or is this a recursion?

`ESC[34mweb_1        |ESC[0m [bca350b1-7462-4d3b-b1df-90bdf45fc2b4] method=GET path=/settings/aliases format=html controller=Settings::AliasesController action=index status=500 error='ActionView::Template::Error: undefined method `pretty_acct' for #<AccountAlias id: 1, account_id: 109304341366185691, acct: "uanews@botsin.space", uri: "https://botsin.space/users/uanews", created_at: "2022-11-08 07:12:14.447832000 +0000", updated_at: "2022-11-08 07:12:14.447832000 +0000">
`
Is there no workaround, pls?
