### ISSUE TITLE
Getting the context of a toot is very slow after migrating to PostgreSQL 14 / Mastodon v3.5.0

### ISSUE THREAD

**Issue by aldatsa** [mastodon/mastodon#18034]
### Steps to reproduce the problem

We followed the instructions to migrate the data to [PostgreSQL 14](https://github.com/mastodon/mastodon/pull/16947). We didn't notice any "ERROR: invalid input syntax for type \<something>" error, so we upgraded our instance to Mastodon 3.5.0.

Initially everything looked good, but then we noticed that getting the context of a toot is very slow. The API call (/api/v1/statuses/xxxxxxxxxxxxxxxxxxxxx/context) responds after 8-15 seconds. The response is correct and the ancestors and descendants of the toot are displayed correctly.

I tested it in mastodon.social and the API call needs less than a second to complete. There is something wrong in our instance. Any ideas on how to fix it?

Maybe a missing or unused index slows down the query? PgHero says that there are 33 unused indexes. Is it normal?

### Expected behaviour

The context of a toot should load quickly.

### Actual behaviour

The context of a toot is displayed after 8-15 seconds in our instance.

### Specifications
https://mastodon.eus
Mastodon v3.5.1 using Docker.
PostgreSQL 14 (postgres:14-alpine)

**Comment by Gargron** [comment]
I would try to run ANALYZE in psql.

**Comment by aldatsa** [comment]
I have just run ANALYZE in psql and now the context of the toots loads really fast! Thank you very much for your help @Gargron. I really appreciate it!
