### ISSUE TITLE
Revamp post filtering system

### ISSUE THREAD

**Issue by ClearlyClaire** [mastodon/mastodon#18035]
The user-defined post filtering features of Mastodon are long overdue for a redesign, and it is one of the goals of our NLnet application.

This issue is here to describe and track that redesign effort.

### Allow different actions for different filters

Currently, posts can either be completely hidden or replaced by a “(Filtered)” placeholder. These actions should be changed to the following:
- completely hide (as the current “Drop instead of hide” setting does)
- hide the post behind a “(Filtered)” placeholder, but allowing the user to see who posted it and why it was filtered, and let them decide whether they want to see the post or not

The rationale for these actions is that “(Filtered)” is not very useful to the end-user and can induce a fear of missing out. While allowing the user to see why something is filtered can let them review their filters and function similar to a recipient-set Content Warning covering topics that would generally not be considered worthy of a Content Warning.

### Have filters apply to a set of keywords instead of one

Currently, each filter matches one keyword. This makes it tedious to set the same scope, action and expiration date to each of them. A filter should apply to various keywords to make that easier and also allowing to show why a post was filtered without directly exposing the exact matching keyword.

Motivations (examples):
- listing individual presidential candidate names under a “elections” filter
- listing personally triggering keywords under a “trauma” filter
- regroup words with multiple variations or misspellings

### New filter types

Filtering posts based on their textual content is a good thing, but it should also be possible to filter individual posts and conversations.

## Technical changes

While full client support is preferable to handle real-time and retroactive changes to filters, it makes sense for the server to include filtering information directly within the API responses.

Indeed, this would make non-retroactive non-realtime filters easy to implement. It would also provide client programmers with a reference on how the client-side implementation should behave.

## Challenges

How to handle the migration, and especially how to handle clients using the old API is going to be challenging. There are also careful UX decisions to take care of.

**Comment by Lukas2112** [comment]
Would it also be possible to filter several hashtags under "Trash TV series and films"?

**Comment by ClearlyClaire** [comment]
I'm not sure a specific filter type for hashtags is needed, textual matching should match just as well, right?

**Comment by Lukas2112** [comment]
One more thought: With the revision of the contribution filter system, could one also create the possibility that filters (groups) in the filter overview can be temporarily deactivated by the user with one click?

@ClearlyClaire
