### ISSUE TITLE
auto-follow does not work (anymore?)

### ISSUE THREAD

**Issue by svoeth** [mastodon/mastodon#18042]
### Steps to reproduce the problem

mastodon provides admins with the ability to make new account follow specific local accounts or all local admins. But it doesn't work.
I tested an empty field, just accountnames, with an @ in front with domain, everything, but nobody follows automatically.
Other mastoadmins reported to me, that they used the feature sucessfully before but it doesn't work anymore. Seems to be a bug or am i missing a setting?!

Steps to reproduce:
1. add (or don't) add accounts to autofollow at admin/settings/edit (default is to follow all local admins if empty)
2. don't get automatically followed

### Expected behaviour

listed local accounts or admins get followed by new users

### Actual behaviour

nothing

### Specifications

Version: 3.5.1 (but also in previous versions back to 3.4.0)

**Comment by ClearlyClaire** [comment]
As the description shows, that feature has been changed to not provide auto-follow but instead list those accounts at the top of the follow recommendations (provided when onboarding, and available in the “Explore” tab).

![image](https://user-images.githubusercontent.com/384364/164221307-d32871fb-bae2-46b6-9eaa-a7c9c4c2ffc9.png)

**Comment by svoeth** [comment]
ok, thanks. At least the german translation is still wrong which led to the confusion.
