### ISSUE TITLE
Can't install using Docker

### ISSUE THREAD

**Issue by Odyssey346** [mastodon/mastodon#18056]
### Steps to reproduce the problem

1. Go on portainer
2. Create a new container, pull from "tootsuite/mastodon"
3. See that it errors out on "tini"
![image](https://user-images.githubusercontent.com/57069715/164007905-cd57339b-c9da-4f02-9f9e-2edac773eb14.png)

...

### Expected behaviour

It shouldve worked

### Actual behaviour

It doesn't

### Specifications

latest docker

**Comment by Gargron** [comment]
Please see how the container is used in docker-compose. There is no default command.
