### ISSUE TITLE
`tootctl accounts cull` is listing mastodon.social as not available

### ISSUE THREAD

**Issue by benoitjpnet** [mastodon/mastodon#18065]
### Steps to reproduce the problem

1. Run `tootctl accounts cull`

### Expected behaviour

Unavailable/dead instances show up, but not mastodon.social

### Actual behaviour

mastodon.social show up, but my server can well talk to it.

```
The following domains were not available during the check:
    mastodon.social
```
```
curl -s https://mastodon.social/api/v1/instance | jq .version
"3.5.1"
```

But it take some time though (Japan to Germany)... Is there some aggressive timeout in `accounts cull` code?
```
time curl -s https://mastodon.social/api/v1/instance | jq .version
"3.5.1"

real    0m7.709s
```

### Specifications

3.5.1

**Comment by benpro** [comment]
Probably this https://github.com/mastodon/mastodon/blob/39cdf61ab7be267a374c472c230b315971ead43c/app/lib/request.rb#L20

```
  # We enforce a 5s timeout on DNS resolving, 5s timeout on socket opening
  # and 5s timeout on the TLS handshake, meaning the worst case should take
  # about 15s in total
```

I did some tests, and it is looking good most of the time... But sometimes it goes over 15s or 45s... I guess the instance is a bit crowded and is answering too slow? Does not seems to be my connection.

```
time_total: 1.149415
time_namelookup: 0.028662 
time_connect: 0.308390 
time_appconnect: 0.891824 
time_pretransfer: 0.892101 
time_redirect: 0.000000 
time_starttransfer: 1.173575
```

I wonder if we can add some more logic to the cull code to avoid this situation.

**Comment by mjankowski** [comment]
Closing this on assumption that this may have been intermittent connectivity issue that worked itself out?

If you can repeat this reliably on current stable version, can you reopen with relevant steps/logs?
