### ISSUE TITLE
Linking with Google Storage does not work

### ISSUE THREAD

**Issue by xandervx** [mastodon/mastodon#18067]
### Steps to reproduce the problem

I set everything like in the official documentation guide.
All is working on this domain setest.xyz.
Except the Google Storage. When uploading it would return 500 right away into the UI.
Here's my setup of mastodon on Google Compute. 
![image](https://user-images.githubusercontent.com/10819474/164701905-45db85d9-45ab-4cfe-915a-6d98b7786932.png)

### Expected behaviour

I expect the file to be uploaded

### Actual behaviour

500 is returned

### Specifications

latest

**Comment by ykzts** [comment]
You must use `S3_SIGNATURE_VERSION=v4` in GCS.

**Comment by xandervx** [comment]
I am still getting 500...

**Comment by ykzts** [comment]
500 error alone is not enough information. Can you check the server error log?

**Comment by xandervx** [comment]
Apr 23 21:11:29 mastodon-ubuntu1804 bundle[21703]: [a8a52ba9-4ea5-4ffb-919f-eb00859cca92] [paperclip] Trying to link /tmp/2c576c0e8c461f7b02e79b0d898370d120220423-21745-1dlor3d to /tmp/d5ff7
Apr 23 21:11:29 mastodon-ubuntu1804 bundle[21703]: [a8a52ba9-4ea5-4ffb-919f-eb00859cca92] [paperclip] Trying to link /tmp/8f7bf713381f73cf91f18d5b9f33314a20220423-21745-1g0ifjn.jpg to /tmp/8
Apr 23 21:11:29 mastodon-ubuntu1804 bundle[21703]: [a8a52ba9-4ea5-4ffb-919f-eb00859cca92] Command :: file -b --mime '/tmp/8230982b804925bc73a5e6de8eb5c39b20220423-21745-15srqwg.jpg'
Apr 23 21:11:29 mastodon-ubuntu1804 bundle[21703]: [a8a52ba9-4ea5-4ffb-919f-eb00859cca92] [paperclip] saving media_attachments/files/108/183/439/874/319/941/original/387488199a5fb5ac.jpg
Apr 23 21:11:29 mastodon-ubuntu1804 bundle[21703]: [a8a52ba9-4ea5-4ffb-919f-eb00859cca92] method=POST path=/api/v2/media format=html controller=Api::V2::MediaController action=create status=
Apr 23 21:11:29 mastodon-ubuntu1804 bundle[21703]: [a8a52ba9-4ea5-4ffb-919f-eb00859cca92]
**Apr 23 21:11:29 mastodon-ubuntu1804 bundle[21703]: [a8a52ba9-4ea5-4ffb-919f-eb00859cca92] Aws::S3::Errors::AccessDenied (Access denied.):**
Apr 23 21:11:29 mastodon-ubuntu1804 bundle[21703]: [a8a52ba9-4ea5-4ffb-919f-eb00859cca92]
Apr 23 21:11:29 mastodon-ubuntu1804 bundle[21703]: [a8a52ba9-4ea5-4ffb-919f-eb00859cca92] lib/paperclip/attachment_extensions.rb:55:in `block in save'
Apr 23 21:11:29 mastodon-ubuntu1804 bundle[21703]: [a8a52ba9-4ea5-4ffb-919f-eb00859cca92] lib/paperclip/attachment_extensions.rb:61:in `save'
Apr 23 21:11:29 mastodon-ubuntu1804 bundle[21703]: [a8a52ba9-4ea5-4ffb-919f-eb00859cca92] app/controllers/api/v2/media_controller.rb:5:in `create'

**Comment by ykzts** [comment]
Can you  check that the same key can be used in aws cli to upload image lists and files? It looks like you don't have enough permissions.
