### ISSUE TITLE
Mastodon sidekiq crash with Too many open files

### ISSUE THREAD

**Issue by yingziwu** [mastodon/mastodon#18063]
### Steps to reproduce the problem

After upgrade Mastodon to v3.5.0, I found the sidekiq process of my instance crashes after running for a while (about 2-5 days).

Other instances that full-text search  is enabled have encountered similar problems, eg. m.cmx.im.

------------------------------------------

After running for a while, the sidekiq process with pull queue disappear from Sidekiq admin panel.

![image](https://user-images.githubusercontent.com/22741471/164582399-96f3d668-b1a8-4093-9003-8d5aa1de3d70.png)

Use systemd to view  the mastodon sidekiq service, the service still live but with many ``Too many open files`` errors.

```
# systemctl status mastodon-sidekiq.service
● mastodon-sidekiq.service - mastodon-sidekiq
     Loaded: loaded (/etc/systemd/system/mastodon-sidekiq.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-04-20 05:15:05 UTC; 1 day 20h ago
   Main PID: 811 (bundle)
      Tasks: 38 (limit: 18711)
     Memory: 600.6M
        CPU: 21h 34min 46.325s
     CGroup: /system.slice/mastodon-sidekiq.service
             └─811 sidekiq 6.4.1 live [11 of 25 busy]

Apr 22 02:11:32 git bundle[811]: 2022-04-22T02:11:32.921Z pid=811 tid=qnm3r class=Chewy::Strategy::Sidekiq::Worker jid=1072140b4852c65ac64c1065 elapsed=6.207 INFO: fail
Apr 22 02:11:32 git bundle[811]: 2022-04-22T02:11:32.921Z pid=811 tid=qnm3r WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"pull","class":"Chewy::Strategy::Sidekiq::Worker","args":["StatusesIndex",[1081731541370841>
Apr 22 02:11:32 git bundle[811]: 2022-04-22T02:11:32.924Z pid=811 tid=qnm3r WARN: Errno::EMFILE: Too many open files - Too many open files - socket(2) for "127.0.0.1" port 9200 (127.0.0.1:9200)
Apr 22 02:11:32 git bundle[811]: 2022-04-22T02:11:32.927Z pid=811 tid=qnm3r WARN: /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:623:in `rescue in create_socket'
Apr 22 02:11:32 git bundle[811]: /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:607:in `create_socket'
Apr 22 02:11:32 git bundle[811]: /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httplog-1.5.0/lib/httplog/adapters/httpclient.rb:60:in `create_socket'
Apr 22 02:11:32 git bundle[811]: 2022-04-22T02:11:32.931Z pid=811 tid=qnnaj class=PushUpdateWorker jid=5d12068aebf0111db48ab948 elapsed=14.192 INFO: done
Apr 22 02:11:32 git bundle[811]: 2022-04-22T02:11:31.228Z pid=811 tid=qnns3 class=LinkCrawlWorker jid=b684c8e64b16542830be3b49 elapsed=4.515 INFO: done
Apr 22 02:11:32 git bundle[811]: 2022-04-22T02:11:32.933Z pid=811 tid=qnnaj class=Chewy::Strategy::Sidekiq::Worker jid=6b241c8393b9ee981213e343 INFO: start
Apr 22 02:11:33 git bundle[811]: 2022-04-22T02:11:18.715Z pid=811 tid=qnk43 class=Chewy::Strategy::Sidekiq::Worker jid=85f1500992bfb59fa57ffe10 INFO: start
```

### Expected behaviour

Mastodon sikekiq process work well.

### Actual behaviour

Mastodon sikekiq process crashes after running for a while.

### Specifications

Software|Version
-- | --
Mastodon | 3.5.1~bgme
Ruby | 3.0.3p157
PostgreSQL | 13.5
Redis | 6.0.16

```
$ uname -a
Linux 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
```

**Comment by yingziwu** [comment]
@Gargron 
Mastodon v3.5.x  appears to have the connection leak.

```
# lsof -p 641091 | wc -l
454

# lsof -p 641091 | grep "9200" | wc -l
201
```

The Chewy don't close connection after completing the communication.

[9200-188.pcap.gz](https://github.com/mastodon/mastodon/files/8542570/9200-188.pcap.gz)

![image](https://user-images.githubusercontent.com/22741471/164756200-d4ab2e97-005d-4af9-bb5f-6c91ed282244.png)

**Comment by ClearlyClaire** [comment]
Which version of Elasticsearch are you using?

**Comment by yingziwu** [comment]
> Which version of Elasticsearch are you using?

Elasticsearch v7.17.2

**Comment by Letterus** [comment]
Until #27138 gets merged we applied following workaround to `.config/systemd/user/sidekiq.service`

```
[Service]
Restart=always
RuntimeMaxSec=7d
```
Reduce 7d if you run out of open files earlier.

**Comment by jdeluyck** [comment]
I will add my "me too" to this thread. I've had to restart Sidekiq with some regularity as the amount of open file descriptors to ElasticSearch just keeps increasing. My setup is about as stock as it would get, but i'm able to reproduce this issue easily - just letting Mastodon run.

As a temporary workaround I'm adding the restart in the systemd unit file, but it would be nice if the PR could get merged.
