### ISSUE TITLE
Irish/Gaeilge Translation

### ISSUE THREAD

**Issue by cathalgarvey** [mastodon/mastodon#18068]
### Pitch

The Mastodon software currently already has the ground-work in place for a Gaeilge translation, but there is no translation programme open on Crowdin for people to contribute towards. So, setting the language to "Gaeilge" currently does nothing.

If Irish/Gaeilge could be added to Crowdin, then we can begin making the translation available.

Thanks!

### Motivation

Irish speakers

**Comment by ykzts** [comment]
I added Irish (https://crowdin.com/project/mastodon/ga-IE).

**Comment by cathalgarvey** [comment]
Thank you! Táim buíoch díot! :)
