### ISSUE TITLE
Clarify that DMs can be read by instance owners

### ISSUE THREAD

**Issue by n0toose** [mastodon/mastodon#18079]
### Pitch

Users should be alerted them that their direct messages are, in fact, not private, and that the owners of the instances that all the participating parties are using could ***possibly, with extra effort***, read the content and take moderation-related actions.

I think that the current notice of `This post will only be sent to the mentioned users.` is a bit misleading. Can I make a PR for it?

https://github.com/mastodon/mastodon/blob/c3aef491d66aec743a3a53e934a494f653745b61/app/javascript/mastodon/features/compose/containers/warning_container.js#L51

### Motivation

Recent influx of users joining Mastodon, as a result of a potential acquisition deal involving Twitter, as well as skeptics sharing data privacy concerns surrounding the federated model of Mastodon.

**Comment by n0toose** [comment]
I seriously believe that applications aiming to achieve a better degree of privacy than existing solutions should be completely upfront about things like that, otherwise, continuing to portray yourself that way without being totally upfront and honest about this makes the end result no better than traditional social media, which also gives off a false sense of privacy despite the fact that your messages can be analyzed for ad-related purposes. Combined with the fact that Mastodon has a significantly higher number of people belonging in marginalized groups, I think that it is not unreasonable to think that changing the message that's being displayed right now (which is technically true, but misleading) should be considered as urgent.

As a result of the recent influx, there are now people on my Twitter timeline, as well as friends/connections of mine that brought up how much administrators are supposed to be trusted, while casting doubt on the entire model that Mastodon is built on top of as a result of the lack of awareness about this.

**Comment by n0toose** [comment]
Additional note: People seem to support the notion that, for instance, "companies have built-in mechanisms against it" (in reference to companies that have a track record of employees getting into trouble for abusing privileges), despite their entire moderation team being anonymous -- in direct contrast to what's very often not the case on Mastodon.

All I'm trying to demonstrate here is that being upfront about issues like this and the potential consequences, at least until some sort of Misskey-like encryption feature comes out, is the best way to have this taken more seriously under heavy scrutiny. Either way, I would be glad to try and improve the wording, as I have some small amount of experience in that and would love to contribute.

**Comment by nightpool** [comment]
This has been discussed to death in the past. See https://github.com/mastodon/mastodon/issues/7030 https://github.com/mastodon/mastodon/pull/7420 and https://github.com/mastodon/mastodon/pull/7546 for just a small handful of examples. The current compromise is to have a "learn more" link that leads to a Privacy Policy that explains explicitly that instance owners can read Direct Messages (when not using e2e encryption):

![](https://user-images.githubusercontent.com/184731/40270048-23aa47b4-5b87-11e8-81a9-5d6d143c433d.png)

**Comment by n0toose** [comment]
Excuse me for missing the memo, but if there are still reactions of people on the Internet that go like "Holy crap, I never knew this!", then that's absolutely not good enough. If there's something that I've also learned while working on my own projects, that is that nobody reads ToS'es, the argument that this is the fault of the user is one of the primary strategies of traditional social media networks. Saying one thing, and then explicitly negating it in a document that most people (average social media user:tm:) are not going to read, just leads to a (probably medium-to-small) percentage of people that would not know about this. Most instances that are not `mastodon.social` also forget or maybe deliberately do not include that message, and the message that is being shown right now is simply not 100% truthful. If reading messages in the first place is not easy and Mastodon, as a project, is trying to take away that "agency" from admins, unless if a report comes through by default, why should the admins of an instance have agency over informing the user about the privacy expectations of the project (as a whole)?

Hiding that because the "users do not need to know" and because "people not knowing about that is needed for moderation purposes" (Why?) is just straight up unethical, and I honestly believe that the contributors saying that "Twitter and Facebook don't do that either" as discussed in those issues is a ***very*** low bar to set. To me, that was essentially what made me start to think that these platforms are bad. I will also have to disagree with you, by the way. The original solution to the one of these issues you linked contained some sort of warning (see: https://github.com/mastodon/mastodon/pull/7420) that was ultimately removed later on in this pull request without additional discussion in the original issues. I don't think that the *current* compromise has been discussed to death, because the original point that was made was later amended. https://github.com/mastodon/mastodon/pull/7546

I get that there is some sort of simplification of the UI trying to happen here, but I think that the current compromise is unintentionally manipulative to a lot of people. I sometimes open up issues (or pull requests with minor UI improvements) like this and write long blocks of text to persuade people, not because I want to deliberately be annoying out of nowhere, but it's mostly because I am already seeing people take actual problems with it first-hand and trying to do my best to ring a warning bell over here.

<details>
<summary>Hidden example, as this block of text is way too long already.</summary>
(Example: https://nitter.net/atomicthumbs/status/1518669806777421824. The thread is largely misleading and a grievance against an entire model because of a bad experience as if everyone's not trustworthy, so we may as well just throw it out of the window, as well as a false expectation of a Mastodon account being the same thing as a Twitter account and that all instance admins conduct themselves in an immature behavior, while ignoring the possibility of instances gaining reputation for being high-quality. If there are bad people in "your sphere of things", why would you want to be there anyways when you can migrate? 

Keep in mind, I live in a student town, and many people in my circles are aware of Mastodon's existence (I even saw "Join Mastodon!" stickers next to the entrance of a bar here), and I have also heard similar arguments as the ones being made in that thread as I tried to annoyingly promote it to people yesterday.)
</details>

**Comment by ClearlyClaire** [comment]
> people not knowing about that is needed for moderation purposes

I'm really surprised by this statement and I don't think I have seen anyone make it.

Anyway, I do agree with @n0toose to some extent, the balance is kinda hard to strike, but I'm not completely satisfied with the current compromise. If current users are still surprised by this fact, then the current warning is not enough.

**Comment by tassoman** [comment]
I'm another user not aware before of this application's behaviour, but I don't want to start a "me too" waterfall. Just thumb up latest posts if you weren't aware about this by your instance privacy page. My questions are: 

- How e2e encryption can be enabled? 
- Encryption for PMs can be set on by default?

In my opinion the most effective way to stop personal messaging harassment is to block entirely the peer account.
Maybe you can flag accounts for "personal harassment" then display flagged accounts to administrators, after a custom number of events. 🤔

**Comment by n0toose** [comment]
> I'm really surprised by this statement and I don't think I have seen anyone make it.

I apologize for accidentally creating an imaginary strawman over here, because I most definitely misinterpreted something while I was shifting through the threads real quick. Thankfully didn't name names because of that, I hope that this won't undermine the case I'm trying to make here.

**Comment by ClearlyClaire** [comment]
> * How e2e encryption can be enabled?
> 
> * Encryption for PMs can be set on by default?

Unfortunately, there isn't any E2E encryption functionality implemented in Mastodon for the moment (we have already designed part of the protocol and implemented most of the server-side bits, but several challenges remain to implement the feature in clients). So for the time being, you have to rely on external tools for E2E encryption of any message in Mastodon, direct or otherwise.

> In my opinion the most effective way to stop personal messaging harassment is to block entirely the peer account.
> Maybe you can flag accounts for "personal harassment" then display flagged accounts to administrators, after a custom number of events. thinking

Yes, but reporting an user allows admins to prevent them from harassing other people. The protocol we have designed allows this (TL;DR: using a mechanism where a recipient can disclose a decrypted message to their server, while the server cannot learn anything more without someone decrypting it first for them).

**Comment by tassoman** [comment]
Sorry for misunderstanding, if I can get it well, the issue is about the undisclosed message the recipient decides to report to owners/moderators. Until now there's no automatic cryptography of messaging. So I imagine owners are able to read all flagged PM messages at all. 
If it's correct, I agree with @n0toose the issue must be much more clear informing users about this current behaviour of the software.

**Comment by ClearlyClaire** [comment]
System administrators can technically read any message known to their server with a little (very little) know-how. This issue is about the warning we display not being sufficient to clearly convey that.

End-to-end encryption would solve that by having only reported direct messages be readable by the system administrator or moderators, but that is not fully implemented yet.

**Comment by shleeable** [comment]
I've been scratching my head about the way to phrase this and generally came up with.. 

Admins can't see DMs in the app... if requires going out of my way to log into the DB and do extra work to find the toots (I never need to log into the DB), but there is no native out of the box way to see DMs in the webapp or from my phone.

Admins don't read DMs, and I'm hoping that soon enough that'll be encrypted and I won't be able too. 
Mastodon DMs should be considered "restricted messages" visible to people mentioned.

DMs are not that important when snapchat exists for sexts, and signal exists for crimes!

Real chat style DMs similar to Twitter/facebook is coming to the ecosystem soon and will be encrypted and secured from admins... but until then, you need to consider "DMs" in mastodon different than the normal style.

It's more of a direct toot, then a direct message.

and in fact, the [#mastodev](https://aus.social/tags/mastodev) team really should rename Direct Messages to "limited visibility" or "restricted" or "mentioned only" because people have mental associations with the word "direct"... and I get annoyed when I see a DM in my timeline and the back of chat style DMs..

![image](https://user-images.githubusercontent.com/17537000/165287196-65d6a63c-8675-44c1-88e9-08d5e171906b.png)

**Comment by n0toose** [comment]
> Admins don't read DMs, and I'm hoping that soon enough that'll be encrypted and I won't be able too.

> System administrators can technically read any message known to their server with a little (very little) know-how. This issue is about the warning we display not being sufficient to clearly convey that.

That's exactly what an admin who reads DMs would say! (Or an admin that is way too optimistic about peoples' intentions, there are already control panels that let you do that on Pleroma, not 100% sure about Mastodon.)

Sorry, but "please trust us, when we are not actively telling you about this" is super suspicious, if not, again, downright unacceptable, and justifying that by assuming what people are going to use your platform for is not good. People are going to your platform depending on whether you tell them, or insinuate to them, that something is fit for purpose. If you don't mention anything and everyone assumes something else, your platform *is* unintentionally misleading them.

In the example I linked earlier, at least 700 people got concerned enough to share that with all of their followers. And rightfully so.

> Mastodon DMs should be considered "restricted messages" visible to people mentioned.

The term you are using, as well as the message in the screenshot you included, do not make it clear in the way I spent a lot of time trying to describe.

### Recommendations

Responding to what you said about the way to phrase this:
- In your screenshot, to keep things short, I would use: "Visible for mentioned users and admins only". If that makes people skeptical of using that feature, **good**, they should be motivated to "use Snapchat or Signal" instead.

- In the source code I linked, I would write it so:

`This toot will only be visible to all the mentioned users and their instance admins. **Learn more**`, which may sufficiently convey that the same also applies to you. Easy to translate. However, slightly confusing.

`This toot will only be sent to all the mentioned users. Their and your instance owners can also read it. **Learn more**`.

`This toot will be visible to you, all the mentioned users and your instances' administrators. **Learn more**`. Super clear, gets the message across, you don't mix up `your/their` with the slash that makes translations confusing.

---

I think that this thread is getting excessively derailed with things like E2EE, I am only here to convince on the issue I initially brought up and ask for the "Go for it" so that I can file a pull request to fix it without causing a debate there and unnecessarily spending more time on this than I have to. [Please, let's avoid a bikeshed.org situation.](https://bikeshed.org/) :D

**Comment by n0toose** [comment]
In case any of you read responses per e-mail, I updated the last comment I just made multiple times because it's easy to misunderstand.

**Comment by ClearlyClaire** [comment]
Honestly, I'm not against just reverting #7546. Incidentally I've just been made aware that the French translation for that string still translates the version from before #7546, and that doesn't seem to have ever caused a major issue with any French user that I know of, so I think it is a reasonable warning.

**Comment by ClearlyClaire** [comment]
My only issue with `This toot will be visible to you, all the mentioned users and your instances' administrators. **Learn more**.` is that it may imply that being visible to the instances' administrators is the default/intended behavior and does not require active involvement from the administrators. This is a very slim distinction though. I think the following conveys the idea a bit closer to what we intend, and is also closer to the current French translation:
`This toot will only be sent to the mentioned users, and may also be accessed by the involved server's operators. **Learn more**`

**Comment by n0toose** [comment]
Sorry, left a comment without reading the entire thing first, on it.

**Comment by n0toose** [comment]
"involved" seems a bit ambiguous though, doesn't it?

**Comment by ClearlyClaire** [comment]
> "involved" seems a bit ambiguous though, doesn't it?

Yeah, that's what I'm not happy with in my current proposal :/
That being said I think that's cleared up in the “Learn more”

**Comment by n0toose** [comment]
To be honest, that seems like the best solution, especially considering that I argued about how urgent this is earlier and would rather not be *the* person complaining about what color the bikeshed is, as that would be quite ironic. Only one question: Wouldn't that also have to be "resolved for good" as soon as possible, considering that this translates to effort by translators? (again, I am assuming that this change was made because of the warning taking too much space.)

**Comment by n0toose** [comment]
I think that "scaring them away" is the most ethical option and that being upfront and honest about this is better PR-wise, considering that there's a lot of people mad and repelled from Mastodon as a whole because they do *not* know about it.

Maybe it's a good idea to emphasize things such as how these admins are very often eponymous, or even redirect people to the admin account as shown in the homepage. BUT LATER!

**Comment by spaceottercode** [comment]
While I appreciate seeing the following notice on toots designated as "Only people I mention":

"Posts on Mastodon are not end-to-end encypted. Do not share any dangerous information over Mastodon"

I'm not sure _dangerous_ is the best choice word. To demonstrate my discomfort with the word dangerous, replace the word information with messages (or even the word toots). Maybe I'm alone on this one. Should this bike shedding matter at all, sensitive, confidential, highly/critically sensitive, damaging, damning, are some words that come to mind. But a thesaurus would probably have better answers.

Again if you think, not a big deal, please disregard.

cheers

**Comment by n0toose** [comment]
Closing this issue, as it has been already resolved by https://github.com/mastodon/mastodon/pull/18146 and https://github.com/mastodon/mastodon/pull/18291.

**Comment by bigntallmike** [comment]
> Unfortunately, there isn't any E2E encryption functionality implemented in Mastodon for the moment (we have already designed part of the protocol and implemented most of the server-side bits, but several challenges remain to implement the feature in clients).
It occurs to me that the Signal protocol could be implemented with "low" effort instead of rolling a new one. My apologies if that's what's already happening.
