### ISSUE TITLE
can't access aliases page

### ISSUE THREAD

**Issue by LagSeeN** [mastodon/mastodon#18077]
### Steps to reproduce the problem

1. add new aliases in https://mastodon.social/settings/aliases
2. after add aliases message show We're sorry, but something went wrong on our end.

![image](https://i.imgur.com/Me9JGJo.png)

### Expected behaviour

aliases page can access

### Actual behaviour

aliases page can't access

### Specifications

OS : Windows 11
Browser : Chrome 100.0.4896.127

**Comment by Low012** [comment]
Duplicate of https://github.com/mastodon/mastodon/issues/18033?

**Comment by shleeable** [comment]
Indeed.

**Comment by LagSeeN** [comment]
> Duplicate of #18033?

thanks
