### ISSUE TITLE
Link verification should be done 'on display' rather than 'on modification'

### ISSUE THREAD

**Issue by mro** [mastodon/mastodon#18102]
### Steps to reproduce the problem

1. add verification <a rel="me" as described
2. modify and save you profile
3. rickroll by redirecting, e.g. via webserver config or <meta refresh

The visitor clicks a 'verified' url which goes somewhere completely different.

### Expected behaviour

Display 'verified' only for what you really verified just now or add a date.

### Actual behaviour

Verify on profile save and display the result on profile view regardless if still the case.

### Specifications

v3.5.1 as currently driving https://digitalcourage.social

**Comment by nightpool** [comment]
Verification is best effort, and there is unfortunately no way to solve
this problem fully.

For example, the kind of redirect you propose would still be possible if
verifying "on display"—just redirect every second request or similar. But
you don't even need to do that—even if the actual page you get is verified,
there's nothing preventing that page from redirecting you with JavaScript
once you get there. Fundamentally, to make sure the "display" matches the
verification, you would require browser level support to make sure the
viewed page still contains the rel=me tag when viewed by a user, as well as
making sure that page doesn't redirect you too early or anything.

Ultimately, you have to accept that verification is 1) best effort, and 2)
about a particular *URL*, not a particular page displayed by the browser.
Once you navigate to a verified URL, then it can do anything any other page
can do, including redirecting you to another page or navigating somewhere
else. But you still passed through the "verified" URL on the way, so in a
sense... that's fine?

**Comment by mro** [comment]
I gave it  second thought and all the verification shows is that the profile owner has some control over the linked target.

Which is fine I guess.

So thank you and close.
