### ISSUE TITLE
"503 Remote SSL cert could not be verified" when trying to fed with mastodon.social. Referred to #6449

### ISSUE THREAD

**Issue by danicotillas** [mastodon/mastodon#18119]
### Steps to reproduce the problem

1. I installed ActivityPub and NodeInfo on comunicacionabierta.net
2. I go to mastodon.social and look for @danicotillas@comunicacionabierta.net
3. I get "503 Remote SSL cert could not be verified" error

### Expected behaviour

I find my account @danicotillas@comunicacionabierta.net as a federated account.

### Actual behaviour

It gets error 503

### Specifications

I guess this is related with my server (Siteground) but maybe you got already a solution for this. I saw the ticket #6449 but I can't solve it as it is explained there.

THanks for all the help!

**Comment by ykzts** [comment]
Please contact mastodon.social, not Mastodon, for any problems with mastodon.social.
