### ISSUE TITLE
3.5.0 upgrade does not work

### ISSUE THREAD

**Issue by yawnbox** [mastodon/mastodon#18113]
### Steps to reproduce the problem

1. Followed the steps from https://github.com/mastodon/mastodon/releases (docker version)

### Expected behaviour

3.5.0 upgrade

### Actual behaviour

See Specifications

### Specifications

~/mastodon# docker-compose run --rm -e SKIP_POST_DEPLOYMENT_MIGRATIONS=true web rails db:migrate
Creating network "mastodon_internal_network" with the default driver
Creating network "mastodon_external_network" with the default driver
Creating mastodon_redis_1 ... done
Creating mastodon_db_1    ... done
rails aborted!
ActiveRecord::ConnectionNotEstablished: FATAL:  role "mastodon" does not exist
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_handling.rb:327:in `retrieve_connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_handling.rb:283:in `connection'
/opt/mastodon/lib/tasks/db.rake:21:in `block (2 levels) in <top (required)>'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5/lib/rails/command.rb:50:in `invoke'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5/lib/rails/commands.rb:18:in `<top (required)>'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/opt/mastodon/bin/rails:4:in `<main>'

Caused by:
PG::ConnectionBad: FATAL:  role "mastodon" does not exist
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/pg-1.3.4/lib/pg/connection.rb:637:in `async_connect_or_reset'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/pg-1.3.4/lib/pg/connection.rb:707:in `new'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/pg-1.3.4/lib/pg.rb:69:in `connect'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:78:in `new_client'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_handling.rb:327:in `retrieve_connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5/lib/active_record/connection_handling.rb:283:in `connection'
/opt/mastodon/lib/tasks/db.rake:21:in `block (2 levels) in <top (required)>'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5/lib/rails/command.rb:50:in `invoke'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5/lib/rails/commands.rb:18:in `<top (required)>'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/opt/mastodon/bin/rails:4:in `<main>'
Tasks: TOP => db:migrate => db:pre_migration_check
(See full trace by running task with --trace)

**Comment by shleeable** [comment]
Postgres was upgraded from 9.6 to 14. I've written a guide https://github.com/mastodon/mastodon/pull/16947

**Comment by yawnbox** [comment]
Yes, thank you. That had completed, i think? but the backup size was 1.5K.

~/mastodon# docker-compose logs db
Attaching to mastodon_db_1
db_1         | 
db_1         | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1         | 
db_1         | 2022-04-27 03:34:38.734 UTC [1] LOG:  starting PostgreSQL 14.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
db_1         | 2022-04-27 03:34:38.735 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1         | 2022-04-27 03:34:38.735 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1         | 2022-04-27 03:34:38.742 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1         | 2022-04-27 03:34:38.752 UTC [21] LOG:  database system was shut down at 2022-04-27 03:34:15 UTC
db_1         | 2022-04-27 03:34:38.760 UTC [1] LOG:  database system is ready to accept connections
db_1         | 2022-04-27 03:35:51.102 UTC [1] LOG:  received fast shutdown request
db_1         | 2022-04-27 03:35:51.105 UTC [1] LOG:  aborting any active transactions
db_1         | 2022-04-27 03:35:51.107 UTC [1] LOG:  background worker "logical replication launcher" (PID 27) exited with exit code 1
db_1         | 2022-04-27 03:35:51.108 UTC [22] LOG:  shutting down
db_1         | 2022-04-27 03:35:51.139 UTC [1] LOG:  database system is shut down

**Comment by yawnbox** [comment]
I apologize, but this is over my head. I do not understand why the deployment and updates of mastodon are so messy and complicated. Even email server open source software have scripts to take care of this complexity.

I did what you said, and now I have a 95 byte backup.

-rw-r--r--  1 root             root 1.5K Mar 30 18:05 9.6.backup
-rw-r--r--  1 root             root 1.5K Apr 26 20:33 9.6.backup.2
-rw-r--r--  1 root             root   95 Apr 28 17:42 9.6.backup.3

**Comment by albjeremias** [comment]
I did a very cool upgrade like this:

`$ docker run --rm --name postgres-upgrade-testing -e POSTGRES_PASSWORD=password -v "/mastodon/postgres_migration":/var/lib/postgresql/ tianon/postgres-upgrade:9.6-to-14 --link`

using: https://github.com/tianon/docker-postgres-upgrade
