### ISSUE TITLE
"New trends up for review" email has incorrect "View" link

### ISSUE THREAD

**Issue by cdzombak** [mastodon/mastodon#18129]
### Steps to reproduce the problem

1. Receive email with new trends up for review
2. Note the link at bottom is `View: https:/.../admin/trends/tags?pending_review=1`
3. Follow the link
4. Note the tags page is not filtered only to those pending review

### Expected behaviour

Link ends with `?status=pending_review`

### Actual behaviour

Link ends with `?pending_review=1`

### Specifications

Mastodon 3.5.0

**Comment by cdzombak** [comment]
It looks to me like this line just needs to change: https://github.com/mastodon/mastodon/blob/main/app/views/admin_mailer/_new_trending_tags.text.erb#L14

But I'm not sure what code that's calling and can't tell whether I can just change it to read `status: 'pending_review'` or not.

**Comment by cdzombak** [comment]
Sample of the complete email:

```
Chris Dzombak, 

The following items need a review before they can be displayed publicly: 

Trending hashtags 

- #reintroduction 
 Used 0 times today, compared to 7 yesterday • Current score 9.5 

Any of these candidates could surpass the #3 approved trending hashtag, which is currently #introduction with a score of 8.98. 

View: https://a2mi.social/admin/trends/tags?pending_review=1 
```

**Comment by ClearlyClaire** [comment]
> It looks to me like this line just needs to change: https://github.com/mastodon/mastodon/blob/main/app/views/admin_mailer/_new_trending_tags.text.erb#L14
> 
> But I'm not sure what code that's calling and can't tell whether I can just change it to read `status: 'pending_review'` or not.

You can, that would indeed be the way to fix it! Can you open a PR for that?

**Comment by cdzombak** [comment]
> You can, that would indeed be the way to fix it! Can you open a PR for that?

Sure thing - done in #18156. Thanks!
