### ISSUE TITLE
Trends are not displayed after upgrading to v3.5.1

### ISSUE THREAD

**Issue by Zagur** [mastodon/mastodon#18132]
### Steps to reproduce the problem

For user:

1. Log in

![imatge](https://user-images.githubusercontent.com/7691406/165541599-4f3d0058-75b7-445e-b5de-6e0872fdaf10.png)

For Admin User:
1. Log in and go Preferences > Trends

![imatge](https://user-images.githubusercontent.com/7691406/165541040-6be0a5ee-6fb3-479b-be7c-be465bb1b80a.png)

### Expected behaviour

The tags used for approval should be displayed.

### Actual behaviour

After upgrading to v3.5.0 the trend widget has disappeared even though I have enabled the "Trends" and "Allow hashtags to trend without prior review" options in Site Settings.  I also notice as an administrator, that several hours after the update the tags are not displayed for approval.

### Specifications

Debian 10
Mastodon: v3.5.1
Ruby: 3.0.3p157
PostgreSQL: 11.12
Redis: 5.0.3

**Comment by davidwolfpaw** [comment]
Seconding that myself and some other admins are reporting the same behavior

**Comment by Zagur** [comment]
> Seconding that myself and some other admins are reporting the same behavior

Solved by me.

Checking what could be wrong with my Mastodon installation, I noticed that the files for the SystemD services were very different from the current **v3.5.1** branch.

For example, the contents of **/etc/systemd/system/system/mastodon-web.service** I had was:

```[Unit]
Description=mastodon-web
After=network.target

[Service]
Type=simple
User=mastodon
WorkingDirectory=/home/mastodon/live
Environment="RAILS_ENV=production"
Environment="PORT=3000"
ExecStart=/home/mastodon/.rbenv/shims/bundle exec puma -C config/puma.rb
ExecReload=/bin/kill -SIGUSR1 $MAINPID
TimeoutSec=15
Restart=always

[Install]
WantedBy=multi-user.target
```

Instead, according to https://github.com/mastodon/mastodon/tree/main/dist I see that it should have this content:

```[Unit]
Description=mastodon-web
After=network.target

[Service]
Type=simple
User=mastodon
WorkingDirectory=/home/mastodon/live
Environment="RAILS_ENV=production"
Environment="PORT=3000"
Environment="LD_PRELOAD=libjemalloc.so"
ExecStart=/home/mastodon/.rbenv/shims/bundle exec puma -C config/puma.rb
ExecReload=/bin/kill -SIGUSR1 $MAINPID
TimeoutSec=15
Restart=always
# Proc filesystem
ProcSubset=pid
ProtectProc=invisible
# Capabilities
CapabilityBoundingSet=
# Security
NoNewPrivileges=true
# Sandboxing
ProtectSystem=strict
PrivateTmp=true
PrivateDevices=true
PrivateUsers=true
ProtectHostname=true
ProtectKernelLogs=true
ProtectKernelModules=true
ProtectKernelTunables=true
ProtectControlGroups=true
RestrictAddressFamilies=AF_INET
RestrictAddressFamilies=AF_INET6
RestrictAddressFamilies=AF_NETLINK
RestrictAddressFamilies=AF_UNIX
RestrictNamespaces=true
LockPersonality=true
RestrictRealtime=true
RestrictSUIDSGID=true
RemoveIPC=true
PrivateMounts=true
ProtectClock=true
# System Call Filtering
SystemCallArchitectures=native
SystemCallFilter=~@cpu-emulation @debug @keyring @ipc @mount @obsolete @privileged @setuid
SystemCallFilter=@chown
SystemCallFilter=pipe
SystemCallFilter=pipe2
ReadWritePaths=/home/mastodon/live

[Install]
WantedBy=multi-user.target
```

I think the main problem comes from the **/etc/systemd/system/mastodon-sidekiq.service** file. 

After making the change for the current one, it started to show tendencies to moderate:

![imatge](https://user-images.githubusercontent.com/7691406/166063081-a5b2f4a5-85a2-4784-99d4-8f9a003af20e.png)

and also appeared in the user's web interface after a few hours:

![imatge](https://user-images.githubusercontent.com/7691406/166063140-9c1bd662-36f5-4b22-9a43-5ade777f2999.png)

please @davidwolfpaw  check that you have it this way and that applying what I said solves the problem.

t3rr0rz0n3.

**Comment by ClearlyClaire** [comment]
It seems you have skipped the instructions in https://github.com/mastodon/mastodon/releases/tag/v3.3.0 about adding a `scheduler` queue to your sidekiq config.

If so, you should have had a warning in the admin dashboard.

**Comment by Zagur** [comment]
@ClearlyClaire 

Is rare. I upgraded from v3.4.4 to v3.4.6. Then from v3.4.6 to v3.5.0 and finally from v3.5.0 to v3.5.1. In v3.4.4, everything was working fine.

**Comment by mkody** [comment]
So I just saw there's an option in the Site settings under Administration to enable Trends publicly.
![image](https://user-images.githubusercontent.com/843787/169666203-9d66c33c-c5f3-4162-99a8-42e1a43920f4.png)

It was disable at first, and now that it's turned on everything is showing up again. 
But as far as I understand the option, shouldn't it display trends for authenticated users at least? If so, I think there's a bug there.

**Comment by Gargron** [comment]
Publicly, in that case, means "outside the admin UI". It turns the whole feature on and off. Sorry for the confusion. Personally I don't like that a core function of Mastodon even can be disabled.

**Comment by ClearlyClaire** [comment]
What is confusing is that the user interface is shown when it's explicitly disabled (and to some extent, the admin interface as well).
I personally don't consider trends to be a core feature of Mastodon and I am glad they can be disabled. It should just be made more explicit that they are disabled, instead of showing an empty interface.

**Comment by vmstan** [comment]
Closing as original issue was solved by adding scheduler queue.
