### ISSUE TITLE
OpenGraph - consider allowing robots to access media.

### ISSUE THREAD

**Issue by edent** [mastodon/mastodon#18134]
### Pitch

When posts are shared to other social networking services, the Open Graph tags successfully allow a preview of the content to be embedded. Unfortunately, media is not part of that preview.

Here's what [Twitter's card validator](https://cards-dev.twitter.com/validator) shows for one of my toots - 
![Screenshot 2022-04-27 at 16-33-27 Card Validator Twitter Developers](https://user-images.githubusercontent.com/837136/165557321-8cdd3b9e-c2d4-4b5d-a5ea-24a5a141bab7.png)

This is because https://files.mastodon.social/robots.txt blocks all robots from accessing media.

According to [Twitter's documentation](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started), their crawler can be allowed using `User-agent: Twitterbot`

Meta's Facebook has no problems grabbing the image - https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fmastodon.social%2Fweb%2F%40Edent%2F108204749089064567
![Screenshot from 2022-04-27 16-43-37](https://user-images.githubusercontent.com/837136/165558141-76773b27-cb28-4618-87b7-d34a28e0407a.png)

### Motivation

Allowing people to share their Mastodon posts on Twitter and other Social Networking Sites *might* encourage people to migrate. At the very least, it would let them see a preview of the content.

**Comment by ramonh** [comment]
Ooh, yes please, I'd love this!

**Comment by Gargron** [comment]
Okay, that was mastodon.social configuration, fixed

**Comment by edent** [comment]
Amazing! Works perfectly. Thanks ♥
https://twitter.com/edent/status/1519376631692992512
![Screenshot 2022-04-27 at 19-03-21 Terence Eden (@edent) _ Twitter](https://user-images.githubusercontent.com/837136/165590967-f1cac7fa-3eb4-4d02-8af6-bd5eb4c7baba.png)
