### ISSUE TITLE
I can't verify mastodon.social via keybase

### ISSUE THREAD

**Issue by YNedderhoff** [mastodon/mastodon#18130]
### Steps to reproduce the problem

I am trying to verify my mastodon.social account via keybase. If I click on the link provided by keybase (`https://mastodon.social/settings/identity_proofs/new?provider=keybase&token=<token>&provider_username=<provider_username>&username=<username>&user_agent=website`) I get a 404.
<img width="509" alt="Screenshot 2022-04-27 at 14 38 14" src="https://user-images.githubusercontent.com/8149019/165519678-325390fa-e6e7-4eb6-aa84-2f53ea86883e.png">

### Expected behaviour

I don't know exactly, as I haven't done this before.

### Actual behaviour

404 Error

### Specifications

I don't know. Current mastodon.social. 

https://mastodon.social/web/@ynedderhoff/108200620104152411

**Comment by Gaelan** [comment]
The Keybase integration was removed, as Keybase was acquired by Zoom and seems to be pretty much unmaintained at this point: https://github.com/mastodon/mastodon/pull/17045

**Comment by YNedderhoff** [comment]
Right. As it is still offered from the Keybase side I assumed it is supposed to work, and frankly I didn't realise how bad the state of Keybase was until now. Thanks!

**Comment by DaveWoodCom** [comment]
Perhaps adding a message on the endpoint stating Keybase integration was removed would be a good idea. Might save others from wasting time trying to find out why it's not working.
