### ISSUE TITLE
[feature] asking before tooting without description

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [mastodon/mastodon#18136]
### Pitch

a toggle in settings (enabled by default) to make a popup before tooting content without description...

### Motivation

why? just that "notifier" bots are only saying you didnt did it and redrafting (posting thing two times) i think is now-such-good. many people just foreget bout it (including me recently...)

**Comment by Cassolotl** [comment]
I think this is a duplicate of *Feature request: warn users of missing image description #7804*? If you think so too, close this issue and go to the older one to comment and/or add your 👍. :)

**Comment by ClearlyClaire** [comment]
Seems like a duplicate, yeah
