### ISSUE TITLE
I cannot upload anything.

### ISSUE THREAD

**Issue by Curly68** [mastodon/mastodon#18145]
### Steps to reproduce the problem

I was trying to send a song I've made to the public via Mastodon, but it doesn't upload at all. I follow all guidelines on the community I'm on like only 10 megabyte size uploads for now due to bandwitch issues, but even after that my uploads get rejected.

### Expected behaviour

The content should be uploaded without any problem

### Actual behaviour

On the desktop client, Mastodon's loading bar just gets stuck at 100% and nothing happens, while in mobile it gives me an error.

### Specifications

Version 3.5.1, both on Destkop and Mobile

**Comment by getimiskon** [comment]
As I can see, it's not an issue of the software itself, but of the instance you use. In the last few days there is an influx of new users and some instances already have problems.

**Comment by ClearlyClaire** [comment]
What Mastodon server are you using, and what is the error you get on mobile? On mobile, are you using the web interface, or a dedicated app?

**Comment by Curly68** [comment]
I'm on Mastodon.lol, a LGBT oriented server that is having a big increase in users following the announcement of Elon's plans of buying Twitter. I'm using the dedicated app for mobile

**Comment by ClearlyClaire** [comment]
Seems like it might just be your server struggling with load, thus taking a lot of time to process your uploads, or just failing: https://mastodon.lol/@nathan/108209924028702631

**Comment by Curly68** [comment]
Ah i see, that report was posted hours after i reported the issue here. The admin say a few hours later that he's going to invest on better servers btw and that the problem will be fixed soon. So I'll call this case closed for now
