### ISSUE TITLE
Creating apps through the API doesn't link them to the user

### ISSUE THREAD

**Issue by CamJohnson26** [mastodon/mastodon#18144]
### Steps to reproduce the problem

1. Create a new user
2. Use the token generated by the post -> accounts call as the authorization header
3. POST to /api/v1/apps with the body: 
```
{
    client_name: 'My Name',
    redirect_uris: 'urn:ietf:wg:oauth:2.0:oob',
    scopes: 'read write follow',
    website: 'https://...'
}
```
4. The request succeeds, and increments the id of the returned app: 
```
{
  id: '78',
  name: 'My Name',
  website: 'https://...',
  redirect_uri: 'urn:ietf:wg:oauth:2.0:oob',
  client_id: 'F_2Yx.....GIKQ',
  client_secret: '_tWH.......KWlHM',
  vapid_key: 'BFON.....R2gqD5zc='
}
```
5. Login as this user and navigate to Preferences > Development > Apps. 

Just to be extra careful, I also tried manually creating an app and using the resulting access token as the authorization header to verify that I was actually using the right user, still see the same behavior.

### Expected behaviour

The app appears in the UI for this user

### Actual behaviour

No app exists in the UI, but it does in the database

### Specifications

Currently using the latest version on DigitalOcean one click app deploy.
Browser: Brave, latest version
OS: Pop OS 21.04

**Comment by Gargron** [comment]
That API is public and not tied to users, so this is expected behaviour. It allows OAuth authentication schemes in a federated environment where manual app registration is not a possibility.
