### ISSUE TITLE
Featured hashtag editor replaces camel case by lower case

### ISSUE THREAD

**Issue by rfkat** [mastodon/mastodon#18184]
### Steps to reproduce the problem

1. Log in and start editing your profile
2. Try adding a camel-cased hashtag to your featured hashtags, e.g. #ArtOfHosting
3. See it added as #artofhosting

### Expected behaviour

See #ArtOfHosting added as a featured hashtag

### Actual behaviour

You get #artofhosting added

### Specifications

OS-independent, browser-independent.

**Comment by nevillepark** [comment]
Just noticed this as well. It's rather annoying and also undesirable for accessibility reasons.

**Comment by bixfrankonis** [comment]
Yeah, this needs fixing.

**Comment by Alex0007** [comment]
Still unfixed. Very frustrating

**Comment by smidgedy** [comment]
Hi,

A user on my instance who doesn't have a Github account has also raised this issue due to the accessibility problem previously mentioned (messes with screen reader), and also for cultural reasons - properly capitalising certain terms is a marker of respect for their culture, so this bug also contributes to structural racism that they experience.

I think it's important to fix, and to understand the reasons in their own words which are [here](https://aus.social/@KarenWyld/109285642652611760).

I'm unfamiliar with the codebase but it seems like a small thing to fix, I'll see if I'm able to raise a PR myself.

**Comment by stibinator** [comment]
This is important. It is ableist, and racist. CamelCase is important for accessibility, and capitalising words is culturally significant in some contexts—to use the word without capitals is racist and derogatory.

**Comment by smidgedy** [comment]
After some help from the user on my instance reporting the issue we found out more detail.

* If I feature a completely new hashtag that's never been used then Mastodon respects my word casing.
* If I feature an already existing hashtag, Mastodon uses the casing present in the existing hashtag. If other users have previously sent it in lowercase, mine will be forced to lowercase.
* If I feature a hashtag called "bandcampfridays" and there is already one called "BandcampFriday", then Mastodon displays my hashtag as "BandcampFridays".

Hopefully this helps properly diagnose the issue - the casing can matter and Mastodon is currently preventing users from improving the accessibility of existing hashtags.

**Comment by smidgedy** [comment]
A bit more understanding emerges - if you look at `db/schema.rb` the table storing hashtags looks like this:

```rb
create_table "tags", force: :cascade do |t|
    t.string "name", default: "", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.boolean "usable"
    t.boolean "trendable"
    t.boolean "listable"
    t.datetime "reviewed_at"
    t.datetime "requested_review_at"
    t.datetime "last_status_at"
    t.float "max_score"
    t.datetime "max_score_at"
    t.ssdftring "display_name"
    t.index "lower((name)::text) text_pattern_ops", name: "index_tags_on_name_lower_btree", unique: true
  end
  ```

The column "name" appears to store the text of the hashtag and is also used as a unique index to the table after lowercasing. What's happening then is that the first user to use any given hashtag would be locking in the capitalisation for all future usage.

Big caveat: I'm a casual ruby user and I've only started browsing through the Mastodon codebase tonight.

**Comment by smidgedy** [comment]
thank you pull request daddy @Gargron

**Comment by Alex0007** [comment]
Not related, but maybe it's worth merging various writings of same tags. Like `#RandomPic` and `#random_pic`
