### ISSUE TITLE
Outdated elasticsearch version in docker-compose.yml

### ISSUE THREAD

**Issue by petzsch** [mastodon/mastodon#18189]
### Steps to reproduce the problem

1. clone the repo
2. try to deploy with docker-compose
3. comment in the es: part of your docker-compose.yml

### Expected behaviour

I would expect recent versions of elasticsearch to be included in the default stack - at least for beginners this would reduce the risk of being hacked!

### Actual behaviour

elasticsearch is pinned at 7.10.2

### Specifications

current master (pulled beginning of the week)

Questions coming up: Is mastodon only compatible with 7.x es versions or is it safe to update to 8.1?

recent 7.x version would be [7.17](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/release-highlights.html)

Thanks again for the great platform.

**Comment by ClearlyClaire** [comment]
> Questions coming up: Is mastodon only compatible with 7.x es versions or is it safe to update to 8.1?

I might be wrong but I think we're only compatible with 7.x.

**Comment by ashleyhull-versent** [comment]
Thanks.
