### ISSUE TITLE
inconsistency in exclamation point for send button when replying vs when composing a new post

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#18191]
### Steps to reproduce the problem

1. note that it says "Toot!" when there is no reply
2. note that it says "Toot" when there is a reply

### Expected behaviour

they should both say the same thing, preferably "toot!" instead of "toot"

### Actual behaviour

they are different

### Specifications

mastodon.social

**Comment by Gargron** [comment]
Exclamation point when public, none when unlisted
