### ISSUE TITLE
Install process fails on Ubuntu 22.04 Jammy Jellyfish

### ISSUE THREAD

**Issue by tomprodehl** [mastodon/mastodon#18206]
### Steps to reproduce the problem

1. Trying to install a new instance of mastodon on Ubuntu Server 22.04 following instruction at https://docs.joinmastodon.org/admin/install/
2. Install of Ruby 3.0.4 fails due inability to process openssl.  Jammy installs libopenssl-dev for openssl v3 which 3.0.4 does not support
3. Choosing to install 3.1.2 does succeed but at the step "Installing the last dependencies
Now to install Ruby and JavaScript dependencies:"
bundle install -j$(getconf _NPROCESSORS_ONLN)
An error occurred while installing openssl (2.2.0), and Bundler cannot continue.
-- this results --
In Gemfile:
  webauthn was resolved to 3.0.0.alpha1, which depends on
    openssl

4. It seems that openssl of Jammy is not compatible with current sources.
5. 
...

### Expected behaviour

Installation should have had complete success

### Actual behaviour

Installation fails and I am left Mastodonless

### Specifications

Did not get to the step of installing mastodon, problem occurred when installing Ruby 3.0.4 in one case and when installing dependencies in another.

**Comment by shleeable** [comment]
This is a known issue. @ClearlyClaire has been working to resolve this with the upstream.

**Comment by ClearlyClaire** [comment]
Yes, unfortunately, the dependency we use for the WebAuthn (log-in through physical security tokens) is not compatible with OpenSSL 3.0 yet, and while I have submitted some patches to fix that, I have not heard back from the developers yet. Those dependencies seem to have become unmaintained, so we might need to fork them at some point…

**Comment by tomprodehl** [comment]
Registered this as an aid for other Jammy users wishing to install mastodon as I was.

**Comment by toeserve** [comment]
I ran into this problem as well. It seems like since webauthd developers are unresponsive, the best thing is to fork it so it can be patched, and if the developers wake up, they can pull them in.

**Comment by ClearlyClaire** [comment]
You may want to give https://github.com/mastodon/mastodon/pull/18449 a try, it installs fine and the tests run fine as well, although I haven't tried actually using it yet.

**Comment by ClearlyClaire** [comment]
I have now tested that PR, and it seems to work.

**Comment by rickersilva** [comment]
Sorry for this n00b question. it means I can upgrade my ruby from 2.7.2 to 3.1.2? I'm installing a new instance and wonder if I can go with latest ruby version before installing mastodon.

Thank you.
