### ISSUE TITLE
No option to send direct messages, add notes, or add to lists in main mastodon.social instance

### ISSUE THREAD

**Issue by audacenoire** [mastodon/mastodon#18217]
### Steps to reproduce the problem

1. Click on a user's username to go to their profile
2. Click on three dot menu next to their name

Until about yesterday I was able to click on the three dots menu next to someone's username on their profile, and I would see "Direct Message @username" and some other options. Now I only see options to mention, mute and block. 

I've only sent DMs to people in order to ask them if I could follow. 

I'm wondering if I've been banned or shadowbanned or if I otherwise did something wrong. 

This is only the case for the main mastodon.social instance. On my other instances things work as expected.

### Expected behaviour

"Direct message" "Add/remove from lists" "add note" options appear in drop down menu

### Actual behaviour

Only "Mute" "Block" and "Mention" items appear in drop down menu

### Specifications

Browser: Firefox

OS: Windows 11

**Comment by Gargron** [comment]
1. The direct message shortcut has been removed from Mastodon as we do not want posts to be confused with DMs
2. Add/remove from lists option is available only for profiles you are following (so just follow first)
3. Add note has never been a dropdown option, it's an input field that appears above the users' bio on their profile
