### ISSUE TITLE
ActiveRecord::ConnectionNotEstablished: FATAL:  role "mastodon" does not exist

### ISSUE THREAD

**Issue by solick** [mastodon/mastodon#18215]
### Steps to reproduce the problem

1. checkout either master or latest stable version
2. run docker-compose build
3.edit .env.production accordingly (changed DB_HOST variable to db, otherwise no connection to database)
4. run docker-compose build again5. 
5. run docker-compose run --rm web rails db:migrate

### Expected behaviour

datase migration

### Actual behaviour

error message, role "mastodon" does not exist

### Specifications

I tried either with current master or with version 3.5.1 both cause the same issue.

Running on a fresh Debian 11.

**Comment by ykzts** [comment]
Did you read the following statement in the upgrade guide in the release notes?

> The PostgreSQL container version in our docker-compose.yml configuration has been changed from 9.6 to 14 due to EOL (End-of-Life) of 9.6. Detailed instructions on how to migrate your data is [available here](https://github.com/mastodon/mastodon/pull/16947).

cite: https://github.com/mastodon/mastodon/releases/tag/v3.5.0

**Comment by shleeable** [comment]
Yeah. The Postgres version was updated in the stock docker-compose. I've written a guide that should work with your setup.

**Comment by solick** [comment]
> Yeah. The Postgres version was updated in the stock docker-compose. I've written a guide that should work with your setup.

Thanks, would you mind sharing the guide?

**Comment by solick** [comment]
I am not quite sure if I was clear enough: It is a fresh installation, not an update. I would expect a fresh install to work out of the box, no need to perform some manual database actions.

**Comment by ykzts** [comment]
@solick https://github.com/mastodon/mastodon/issues/18215#issuecomment-1114060368

**Comment by solick** [comment]
@ykzts but your comment is focused in upgrading from Postgres 9..6 which is not the case. I ran the vacuum command but still get the folioing error message:

`Attaching to mastodon_db_1
db_1         | 
db_1         | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1         | 
db_1         | 2022-05-01 11:19:21.748 UTC [1] LOG:  starting PostgreSQL 14.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
db_1         | 2022-05-01 11:19:21.755 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1         | 2022-05-01 11:19:21.755 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1         | 2022-05-01 11:19:21.759 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1         | 2022-05-01 11:19:21.769 UTC [21] LOG:  database system was shut down at 2022-05-01 07:47:00 UTC
db_1         | 2022-05-01 11:19:21.774 UTC [1] LOG:  database system is ready to accept connections
db_1         | 2022-05-01 11:19:36.454 UTC [28] FATAL:  role "mastodon" does not exist
db_1         | 2022-05-01 11:19:37.294 UTC [29] FATAL:  role "mastodon" does not exist
db_1         | 2022-05-01 11:19:48.819 UTC [30] FATAL:  role "mastodon" does not exist`

**Comment by ykzts** [comment]
Ah, I see. I misunderstood that you were upgrading from less than v3.5.0, since `db:migrate` is the command normally used for upgrades.

It is very likely that your configuration is incorrect. You need to set it up correctly using `rake mastodon:setup`.

**Comment by solick** [comment]
hmm ok I throw everything away and started from scratch:

1. git clone the repo
2. git checkout v3.5.0
3. cp .env.production.sample .env.production
4. docker-compose run --rm web bundle exec rake mastodon:setup

at the end I got the following error:

`Running `RAILS_ENV=production rails db:setup` ...


Database 'postgres' already exists
Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
Switching object-storage-safely from green to red because Redis::CannotConnectError Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
Done!`

**Comment by solick** [comment]
ok i made it work now. here are my steps which helped me out at the end:

1. git clone https://github.com/tootsuite/mastodon
2. cd mastodon/
3. git fetch
4. git checkout v3.5.0
5. cp .env.production.sample .env.production
6. docker-compose run --rm web bundle exec rake mastodon:setup
7. ATTENTION: You need to copy paste the config to .env.production
8. docker-compose build
9. docker-compose up -d
10. --> nginx config

After first startup it will take a while before you can reach the website
