### ISSUE TITLE
Search screen "posts" doesn't find posts, but clicking on hashtag does

### ISSUE THREAD

**Issue by CarwilB** [mastodon/mastodon#18218]
### Steps to reproduce the problem

1. When at https://mastodon.online/web/search, I entered a search for a hashtag "#bolivia." This returns a positive match for hashtags (see image below)
2. Clicking on "Posts" reveals no posts. 
3. Clicking on "#bolivia" under all reveals many posts.
...
<img width="581" alt="Search results / all shows 2 results for #bolivia" src="https://user-images.githubusercontent.com/54286746/166125108-f71f0f82-dc62-4308-8622-3427408715f3.png">
<img width="587" alt="Clicking through on #bolivia shows numerous posts" src="https://user-images.githubusercontent.com/54286746/166125111-18076e3f-dea0-4ce9-87f0-ef9da75c2c7a.png">
<img width="594" alt="Search results / posts shows 'Could not find anything for these search terms'" src="https://user-images.githubusercontent.com/54286746/166125117-b4bc0f6a-7dfe-46bc-a8a8-6675939c7d8a.png">

### Expected behaviour

It seems like Posts should show the same thing as I found in #3. And if it doesn't (for example because "Posts" only shows the hashtag in local posts, not federated ones), it should definitely explain how to find more.

### Actual behaviour

Search results / posts shows 'Could not find anything for these search terms'

### Specifications

[mastodon/mastodon](https://github.com/mastodon/mastodon) (v3.5.1). per mastodon.online webpage.

**Comment by ClearlyClaire** [comment]
The “Posts” tab is used for searching posts by their full URL or by contents (regardless of their hashtags), which is not available on all instances and only works for your posts and those you have interacted with.

I understand that this is confusing and at least some people would expect it to also include searchable posts using hahstags, though.

**Comment by CarwilB** [comment]
Okay, I've read your first sentence several times and still don't understand…

I think you're telling me it's possible that "searching posts … is not available on all instances." If so, the Posts tab needs to inform the user whether it is true.

Perhaps "search > posts" only looks at hashtags, or only looks at "your posts or those you have interacted with." If so, then I still am encountering this bug because I made a post that said among other things "[#photography](https://mastodon.online/tags/photography), [#translation](https://mastodon.online/tags/translation)" but it also does not appear under Search / posts when I look for "#translation."

**Comment by CarwilB** [comment]
More broadly, it seems essential to the user experience that "Search > Posts" do something. But based on this conversation I have no idea what it does. It clearly doesn't do the most intuitive thing, so somewhere on the screen there should be a clear explanation of what to expect there.

**Comment by ClearlyClaire** [comment]
> Okay, I've read your first sentence several times and still don't understand…
> 
> I think you're telling me it's possible that "searching posts … is not available on all instances." If so, the Posts tab needs to inform the user whether it is true.

“Posts” doesn't include search from hashtags but:
- results from full-text search, which needs to be enabled per-instance, and only searches in **your** posts and those you have favorited/bookmarked/boosted/where mentioned in
- any post you have access to when you search the exact post URL

**Comment by CarwilB** [comment]
My best guess is that search is disabled for this instance (maybe someone from mastodon.online can confirm). I experimented with non-hashtag search term, including those that appear in my own timeline: "Bolivia", "today", "deforestation" etc.

If search is disabled then "Could not find anything for these search terms" is **not** a useful error message. This message encourages the user to guess other search terms that might be in the timeline. 
<img width="897" alt="Screen Shot 2022-05-01 at 12 43 57 PM" src="https://user-images.githubusercontent.com/54286746/166157881-3c6f2e2c-4bb1-4e7d-81c2-b7378570b201.png">

Instead I would expect something like this…
- Full-text search is disabled for this instance. Only hashtags can be searched, by using the All tab above.

Further, if this is true then the "Posts" tab on instance.url/web/search should be visibly disabled to tell users that it doesn't do anything. 

If search is enabled, and nothing is found, there should also be an explanation, like this:
- Could not find anything for these search terms. This function only searches your posts and those you have interacted with.

**Comment by CarwilB** [comment]
Meta-comment… I'm a new user to Mastodon, familiar with open source software and participatory communities, and completely unable to step in and code in the languages used to make Mastodon. 

I see a lot of conversations that take the form of "Your UX appears to be broken" / "No, that's a clever design choice. Get used to it." 

Generally the people asking are, like me, really enthusiastic about getting new users onto Mastodon and trying to clear the way for their experience to be, at minimum, comprehensible. What I/we ask for in return is proactive efforts to improve the UX. I'm opening this issue precisely because I want the Mastodon user experience to be smoother; telling me to incorporate confusing information about Mastodon into my understanding of a search bar is (a) not solving the problem; (b) not going to scale well to the tens of thousands of users trying a feature like this for the first time.

**Comment by ClearlyClaire** [comment]
My comment was merely here to explain how the feature worked in its current state, not to disregard your criticism. If I thought that it was “a clever design choice”, I would have closed the issue.

But please understand that we are a very small team and have limited resource, so addressing UX issues can take a while. In the meantime, I thought explaining Mastodon's current behavior and how it differed from your expectation could help.

**Comment by DarckCrystale** [comment]
It may be a good idea to add an info message saying post search is disabled when it's the case

**Comment by Gargron** [comment]
I think a message like that is supposed to appear, and it not being there might be a bug…

**Comment by Gargron** [comment]
The safety-oriented search limitations (and the fact that ES is treated as optional) is definitely running afoul of user expectations a lot from what I’ve seen.

**Comment by CarwilB** [comment]
While I still think that having a Search > Posts tab when searching posts is disable is counter-intuitive, the current release of Mastodon does better at explaining what's going on by providing this error message:

> "Searching posts by their content is not enabled on this Mastodon server."

<img width="298" alt="UX screen capture showing a search for 'Carwil', a corresponding user profile, and the message 'Searching posts by their content is not enabled on this Mastodon server.' " src="https://user-images.githubusercontent.com/54286746/209479334-84d955cb-aec6-4efb-9d45-c2b242414b46.png">

Further questions re enabling search are underway in #21627, but I'm closing the issue I opened here.
