### ISSUE TITLE
Default "Browse profiles" to "From [this instance] only", or provide server configured default

### ISSUE THREAD

**Issue by brookmiles** [mastodon/mastodon#18223]
### Pitch

Default Browse Profiles page to "From [this instance] only" OR have this as a server configuration option

Additionally: remember a user's choice, currently it is reset to "From known fediverse" each time the page is opened

### Motivation

As a small new server attempting to build a community, I think discovery of other local profiles is top priority (this will of course vary between instances), especially as part of the new user onboarding process.

Currently if I invite a new user, and they are not logged in, they will see a profile directory populated by local accounts, perhaps some of which are already friends or people they recognize from the community.  However once a user is logged in, if they open the Profile Directory, they are initially presented with what could appear to be a mostly random assortment of unrelated users from the fediverse.

**Comment by janvlug** [comment]
Slightly related to this suggestion: It would be handy to have a URL that directly shows the "Browse profiles", "From [this instance] only". I sometimes want to show people the profiles of a specific instance.

**Comment by brookmiles** [comment]
The design of this feature has changed significantly since this issue was created, not really relevant anymore.
