### ISSUE TITLE
Upload profile picture cause EACCESS: permission denied

### ISSUE THREAD

**Issue by solick** [mastodon/mastodon#18229]
### Steps to reproduce the problem

1. fresh mastodon installation via docker
2.go to admin settings and chose profile
3.try to upload a profile cicture
...

the following error in the logs:

`web_1        | [cb17e1cb-7513-444d-961d-4b6b9e6da3bd] method=PUT path=/settings/profile format=html controller=Settings::ProfilesController action=update status=500 error='Errno::EACCES: Permission denied @ dir_s_mkdir - /opt/mastodon/public/system/accounts' duration=128.35 view=0.00 db=3.77
web_1        | [cb17e1cb-7513-444d-961d-4b6b9e6da3bd]   
web_1        | [cb17e1cb-7513-444d-961d-4b6b9e6da3bd] Errno::EACCES (Permission denied @ dir_s_mkdir - /opt/mastodon/public/system/accounts):`

### Expected behaviour

picture should be uploaded successfully

### Actual behaviour

Permission denied error

### Specifications

mastodon v3.5.0 on Debian 11 via Docker-compose

**Comment by solick** [comment]
hmm u set chmod 777 to public/sytem and all sub dir but seems not to be the best solutions right?

**Comment by Poldi1977** [comment]
I have the same problem. Did you create an extra user or do you start the Docker container as root?

**Comment by Poldi1977** [comment]
As a workaround `chmod o+w public/system` (without sub-directories) helped for me.

**Comment by Poldi1977** [comment]
This solved the problem for me::

```
sudo chown -R 70:70 ./postgres14
sudo chown -R 991:991 ./public
sudo chown -R 1000:1000 ./elascticsearch
```

**Comment by theBlackDragon** [comment]
This is caused by the issue described in #7116 (and linked issues) and also causes breakage when using Docker volumes. 

Apparently there were performance concerns in allowing configurablility here (see: #2680), but linuxserver.io is able to make this work without issues in any of the containers I've used from them, so maybe looking at what they're doing might be helpful.

**Comment by mjankowski** [comment]
Closing on assumption that this is a configuration issue (solved in comments here?) and not a bug ... but if there's a doc improvement we could make here, please open PR on docs repo (or reopen if I'm missing something...)

**Comment by qqjt** [comment]
> This solved the problem for me::
> 
> ```
> sudo chown -R 70:70 ./postgres14
> sudo chown -R 991:991 ./public
> sudo chown -R 1000:1000 ./elascticsearch
> ```

saved my ass. `elasticsearch` not `elascticsearch` by the way
