### ISSUE TITLE
new user cannot register (column "ips" does not exist)

### ISSUE THREAD

**Issue by solick** [mastodon/mastodon#18232]
### Steps to reproduce the problem

1.setup new instance in docker with version 3.5.1
2. try to register a new user
3.
...

`db_1         | 2022-05-01 14:46:19.949 UTC [57] ERROR:  column "ips" does not exist at character 105`

### Expected behaviour

user should be successfully registered

### Actual behaviour

an error is shown

### Specifications

Debian 11, mastodon 3.5.1 fresh Installation via docker-compose

**Comment by ClearlyClaire** [comment]
Was there any issue setting up the database?
Do database migrations (`bundle exec rails db:migrate`, with docker-compose, that would be `docker-compose run --rm -e web rails db:migrate`) succeed?
Can we have more context from the logs to the error?

**Comment by solick** [comment]
no there where no problems, the command is 'docker-compose run --rm web rails db:migrate' 

here are a longer part of the db logs:

`Attaching to mastodon_db_1
db_1         | 
db_1         | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1         | 
db_1         | 2022-05-01 14:31:05.734 UTC [1] LOG:  starting PostgreSQL 14.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
db_1         | 2022-05-01 14:31:05.735 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1         | 2022-05-01 14:31:05.735 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1         | 2022-05-01 14:31:05.738 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1         | 2022-05-01 14:31:05.744 UTC [21] LOG:  database system was shut down at 2022-05-01 13:59:38 UTC
db_1         | 2022-05-01 14:31:05.757 UTC [1] LOG:  database system is ready to accept connections
db_1         | 2022-05-01 14:32:58.044 UTC [56] ERROR:  column "ips" does not exist at character 105
db_1         | 2022-05-01 14:32:58.044 UTC [56] STATEMENT:  SELECT "email_domain_blocks".* FROM "email_domain_blocks" WHERE ("email_domain_blocks"."domain" = $1 OR ips && ARRAY['5.9.23.172','2a01:4f8:161:2a3::2','23.88.43.216','2a01:4f8:c17:284b::1']::inet[]) ORDER BY "email_domain_blocks"."id" ASC LIMIT $2
db_1         | 2022-05-01 14:33:56.473 UTC [56] ERROR:  column "ips" does not exist at character 105
db_1         | 2022-05-01 14:33:56.473 UTC [56] STATEMENT:  SELECT "email_domain_blocks".* FROM "email_domain_blocks" WHERE ("email_domain_blocks"."domain" = $1 OR ips && ARRAY['5.9.23.172','2a01:4f8:161:2a3::2','23.88.43.216','2a01:4f8:c17:284b::1']::inet[]) ORDER BY "email_domain_blocks"."id" ASC LIMIT $2
db_1         | 2022-05-01 14:46:19.949 UTC [57] ERROR:  column "ips" does not exist at character 105
db_1         | 2022-05-01 14:46:19.949 UTC [57] STATEMENT:  SELECT "email_domain_blocks".* FROM "email_domain_blocks" WHERE ("email_domain_blocks"."domain" = $1 OR ips && ARRAY['5.9.23.172','2a01:4f8:161:2a3::2','23.88.43.216','2a01:4f8:c17:284b::1']::inet[]) ORDER BY "email_domain_blocks"."id" ASC LIMIT $2
db_1         | 2022-05-01 16:13:15.393 UTC [1690] ERROR:  column "ips" does not exist at character 105
db_1         | 2022-05-01 16:13:15.393 UTC [1690] STATEMENT:  SELECT "email_domain_blocks".* FROM "email_domain_blocks" WHERE ("email_domain_blocks"."domain" = $1 OR ips && ARRAY['5.9.23.172','2a01:4f8:161:2a3::2','23.88.43.216','2a01:4f8:c17:284b::1']::inet[]) ORDER BY "email_domain_blocks"."id" ASC LIMIT $2
db_1         | 2022-05-01 16:14:24.770 UTC [1690] ERROR:  column "ips" does not exist at character 105
db_1         | 2022-05-01 16:14:24.770 UTC [1690] STATEMENT:  SELECT "email_domain_blocks".* FROM "email_domain_blocks" WHERE ("email_domain_blocks"."domain" = $1 OR ips && ARRAY['5.9.23.172','2a01:4f8:161:2a3::2','23.88.43.216','2a01:4f8:c17:284b::1']::inet[]) ORDER BY "email_domain_blocks"."id" ASC LIMIT $2
db_1         | 2022-05-01 16:15:25.376 UTC [1695] ERROR:  relation "pg_stat_statements" does not exist at character 15
db_1         | 2022-05-01 16:15:25.376 UTC [1695] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:15:33.508 UTC [1695] ERROR:  relation "pg_stat_statements" does not exist at character 15
db_1         | 2022-05-01 16:15:33.508 UTC [1695] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:15:33.602 UTC [857] ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
db_1         | 2022-05-01 16:15:33.602 UTC [857] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:15:40.427 UTC [1695] ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
db_1         | 2022-05-01 16:15:40.427 UTC [1695] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:15:45.202 UTC [1695] ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
db_1         | 2022-05-01 16:15:45.202 UTC [1695] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:15:48.401 UTC [1695] ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
db_1         | 2022-05-01 16:15:48.401 UTC [1695] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:15:50.585 UTC [857] ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
db_1         | 2022-05-01 16:15:50.585 UTC [857] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:15:52.978 UTC [1695] ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
db_1         | 2022-05-01 16:15:52.978 UTC [1695] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:16:19.467 UTC [1695] ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
db_1         | 2022-05-01 16:16:19.467 UTC [1695] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:16:19.472 UTC [1695] ERROR:  column "ips" does not exist at character 113
db_1         | 2022-05-01 16:16:19.472 UTC [1695] STATEMENT:  EXPLAIN SELECT "email_domain_blocks".* FROM "email_domain_blocks" WHERE ("email_domain_blocks"."domain" = $1 OR ips && ARRAY['5.9.23.172','2a01:4f8:161:2a3::2','23.88.43.216','2a01:4f8:c17:284b::1']::inet[]) ORDER BY "email_domain_blocks"."id" ASC LIMIT $2 /*pghero*/
db_1         | 2022-05-01 16:16:25.931 UTC [1695] ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
db_1         | 2022-05-01 16:16:25.931 UTC [1695] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:16:25.934 UTC [1695] ERROR:  column "ips" does not exist at character 121
db_1         | 2022-05-01 16:16:25.934 UTC [1695] STATEMENT:  EXPLAIN ANALYZE SELECT "email_domain_blocks".* FROM "email_domain_blocks" WHERE ("email_domain_blocks"."domain" = $1 OR ips && ARRAY['5.9.23.172','2a01:4f8:161:2a3::2','23.88.43.216','2a01:4f8:c17:284b::1']::inet[]) ORDER BY "email_domain_blocks"."id" ASC LIMIT $2 /*pghero*/
db_1         | 2022-05-01 16:16:27.636 UTC [1695] ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
db_1         | 2022-05-01 16:16:27.636 UTC [1695] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:16:27.640 UTC [1695] ERROR:  column "ips" does not exist at character 161
db_1         | 2022-05-01 16:16:27.640 UTC [1695] STATEMENT:  EXPLAIN (ANALYZE, COSTS, VERBOSE, BUFFERS, FORMAT JSON) SELECT "email_domain_blocks".* FROM "email_domain_blocks" WHERE ("email_domain_blocks"."domain" = $1 OR ips && ARRAY['5.9.23.172','2a01:4f8:161:2a3::2','23.88.43.216','2a01:4f8:c17:284b::1']::inet[]) ORDER BY "email_domain_blocks"."id" ASC LIMIT $2 /*pghero*/
db_1         | 2022-05-01 16:16:57.381 UTC [1688] ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
db_1         | 2022-05-01 16:16:57.381 UTC [1688] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:16:59.487 UTC [456] ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
db_1         | 2022-05-01 16:16:59.487 UTC [456] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:17:00.324 UTC [1688] ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
db_1         | 2022-05-01 16:17:00.324 UTC [1688] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:17:02.416 UTC [1688] ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
db_1         | 2022-05-01 16:17:02.416 UTC [1688] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:17:20.007 UTC [456] ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
db_1         | 2022-05-01 16:17:20.007 UTC [456] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:17:25.248 UTC [1688] ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
db_1         | 2022-05-01 16:17:25.248 UTC [1688] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:17:27.515 UTC [1688] ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
db_1         | 2022-05-01 16:17:27.515 UTC [1688] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:17:34.919 UTC [1688] ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
db_1         | 2022-05-01 16:17:34.919 UTC [1688] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:17:38.051 UTC [1688] ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
db_1         | 2022-05-01 16:17:38.051 UTC [1688] STATEMENT:  SELECT * FROM pg_stat_statements LIMIT 1 /*pghero*/
db_1         | 2022-05-01 16:19:55.765 UTC [1688] ERROR:  column "ips" does not exist at character 105
db_1         | 2022-05-01 16:19:55.765 UTC [1688] STATEMENT:  SELECT "email_domain_blocks".* FROM "email_domain_blocks" WHERE ("email_domain_blocks"."domain" = $1 OR ips && ARRAY['5.9.23.172','2a01:4f8:161:2a3::2','23.88.43.216','2a01:4f8:c17:284b::1']::inet[]) ORDER BY "email_domain_blocks"."id" ASC LIMIT $2
`

**Comment by ClearlyClaire** [comment]
Can you post the output of the following command? `docker-compose run --rm -e web rails db:version`

**Comment by solick** [comment]
the -e parameter is not working (no such service: rails). Without the following result:

'Current version: 20220429101850'

**Comment by ClearlyClaire** [comment]
> the -e parameter is not working (no such service: rails). Without the following result:

oops, sorry about that, you're right (edited the post so people don't get confused by that)

> `Current version: 20220429101850`

Ok, this is what I thought: you're somehow running 3.5.1 code on a database schema from the development version.
I'm not sure how you ended up like that, but you have two options:
- migrating back to the database schema from 3.5.1
- updating the code to the development version

**Comment by solick** [comment]
> Ok, this is what I thought: you're somehow running 3.5.1 code on a database schema from the development version. I'm not sure how you ended up like that, but you have two options:
i have no idea, I checked out from repo the version 3.5.0 and later updated to 3.5.1
> 
> * migrating back to the database schema from 3.5.1
that would be my preferred step. How would I do that?
> * updating the code to the development version

**Comment by ClearlyClaire** [comment]
I'm not too familiar with docker-compose, but you'd temporarily switch to the development version (tagged `edge` on DockerHub), then run `docker-compose run --rm web rails db:migrate VERSION=20220316233212`, then switch back to the `latest` tag.

**Comment by solick** [comment]
@ClearlyClaire thanks this worked. For everyone having the same problem:

git fetch & git checkout main
docker-compose build
docker-compose run --rm web rails db:migrate VERSION=20220316233212
git fetch & git checkout v3.5.1
docker-compose build
docker-compose up -d
