### ISSUE TITLE
rel="me" backlink is not recognized if there are other rel values too

### ISSUE THREAD

**Issue by Oblomov** [mastodon/mastodon#18233]
### Steps to reproduce the problem

1. add a link to a website to your Mastodon profile metadata
2. on the website, add a backlink to your Mastodon profile with `rel="me nofollow"` (for example)

### Expected behaviour

the Mastodon profile link should be confirmed and get the green checkmark

### Actual behaviour

the profile link remains unconfirmed

### Specifications

I first noticed that when trying to establish a cross-reference between my Mastodon profile on scholar.social (I m not sure which version of Mastodon is being run there) and my ORCID page. ORCID allows you to define social profiles, and it adds a `me` relationship, but the attribute also includes several other values (the full attribute value is `me nofollow noopener noreferrer`) and is thus not recognized. The user has no control on this, but regardless, as long as `me` is among the relationship values, Mastodon should still recognize the link.

**Comment by nightpool** [comment]
"nofollow" indicates that the rel link is not to be used for page ranking
calculations. it's generally used for untrusted links given by users. It
seems insecure for Mastodon to ignore that restriction, since it indicates
the webmaster doesn't trust the link in question not to be spammy.

**Comment by Oblomov** [comment]
Well, this is a bit problematic.

FWIW, I think that such an interpretation of the `nofollow` attribute is a bit too strict. The attribute has been used and abused for all sort of things, not just “potentially spammy because user-generated” links, and ultimately it remains directed at search, which is, I believe, a different use-case compared to the Mastodon case.

Moreover, while I can see some argument for theoretical potential for abuse, I don't think there's really much of a possibility for e.g. blogspam or wikispam to get the level of control that would allow a user to add a `rel=me` attribute, in addition to the `nofollow` added e.g. by the blog or wiki software (indeed, even on ORCID the `me` `rel` is added by the platform itself, not by the user). So I don't really think it would be particularly insecure for Mastodon to ignore such restriction.

OTOH, if there really are such safety concern, one possible solution could be to have some kind of control list for the domains where the restriction should or should not be ignored.

**Comment by apfelnutzer** [comment]
I experienced a similar issue - I linked my Thingiverse profile and put a backlink in the description but Thingiverse added a "nofollow" automatically as well and the backlink seems to be ignored. Why are such backlinks ignored?

**Comment by apfelnutzer** [comment]
I checked the backlink validation code on my own and it looked fine (for me). Re: Thingiverse I‘ve got the suspicion that the code is dynamically generated and thus not recognized correctly. I‘ll try to investigate this further.

**Comment by apfelnutzer** [comment]
… BTW: The validation function in question does not filter out „nofollow“ or any other additional keywords. It‘s just looking for „me“ in the `rel` attribute.

**Comment by apfelnutzer** [comment]
Hm. Looks like I'm right: when I save the page containing the backlink to my machine the backlink is not included. Instead there are a lot of javascript calls that probably generate additional html code - e.g. the link. So it's not visible to the validation function at all...

**Comment by Oblomov** [comment]
Oh, good spotting. I just checked with ORCID and it's exactly the same situation. I'm going to close this issue since the issue isn't what I thought it was, and it really can't be solved Mastodon-side safely (it would require rendering the page server-side, which is a huge resource hog and inherently unsafe).
