### ISSUE TITLE
Better RSS item title

### ISSUE THREAD

**Issue by manto89** [mastodon/mastodon#18256]
### Pitch

I'm using a minimal RSS Reader ([Miniflux](https://miniflux.app/)) that doesn't handle HTML in the RSS item title. 
As an example i will use this [RSS feed](https://mastodon.social/tags/infosec.rss), I had censored the actual text content and users.
The result is the annoying presence of tags in the titles of my feed, as below.
![infosec feed censored](https://user-images.githubusercontent.com/6862296/166267197-ee44b11d-028b-4d12-a608-2d7406268be4.png)

On top of that the current implementation of the RSS serializer takes the toot's text and truncates it after 30 characters (or at the first \n), but html tags and related properties are included in those 30 characters. As a result my RSS feed has many entries whose titles are completely useless since it doesn't show the toot's content (see the previous pic, first and last entry)

I'm proposing to render the title of each RSS item as plain text and to increase the truncation length to 128 characters.

I've tried to make some modifications in the /rss/serializer.rb and this is the result:
This toot 
![example toot not legible](https://user-images.githubusercontent.com/6862296/166268873-e1c47de6-2d52-4e01-b277-65760af7a4f8.png)
Became (along with some examples on my dev instance)
![example toot improved](https://user-images.githubusercontent.com/6862296/166267192-6ffe7bd6-f105-4f37-8c77-3bc05bf0ab3f.png)

I will attach the pull request with the proposed solution
Looking for reviews and further help (I'm a Ruby novice)

### Motivation

The current RSS implementation doesn't hint enough content in the titles and carries useless HTML in the title itself. Whoever uses RSS readers to read Mastodon feeds will be able to filter contents just by looking at the title

**Comment by afheisleycook** [comment]
good idea
