### ISSUE TITLE
3.5.1 new install on Ubuntu 22.04: no stylesheets, "permission denied" in nginx logs

### ISSUE THREAD

**Issue by jdkruzr** [mastodon/mastodon#18257]
### Steps to reproduce the problem

Hi,

I get a lot of this after completing my install:
```
2022/05/02 16:25:41 [crit] 76974#76974: *157 stat() "/home/mastodon/live/public/packs/media/images/preview-5df98290371ead9a70bc3cd4733bbfa7.jpg" failed (13: Permission denied)
```

The login page appears unformatted and no styles are loading. I have changed permissions on everything in /home/mastodon/live to 777 (although it all already belonged to mastodon:mastodon) and am still seeing these errors in nginx upon every attempt to get content. How do I troubleshoot this? Firewalls are off and there is no selinux.

Thanks!

### Expected behaviour

loaded front page normally

### Actual behaviour

no styles

### Specifications

3.5.1

**Comment by svoeth** [comment]
your files probably belong to the mastodon or any other user while your nginx server runs as www-data (or some other user).
Your webserver needs to be able to read the files inside live/public/

Call "chmod -R o+r public/" inside your mastodon folder (usually live). This should solve your problem. It adds reading rights to all users for all files in the folder and subfolders

**Comment by jdkruzr** [comment]
> your files probably belong to the user mastodon or any other user while your nginx server runs as www-data (or some other user). Your webserver needs to be able to read the files inside live/public/
> 
> Call `chmod -R o+r public/` inside your mastodon folder (usually live). This should solve your problem. It adds reading rights to all users for all files in the folder and subfolders

this didn't help, but adding mastodon to the www-data group and vice-versa did. I feel like this should probably be added to the instructions?

**Comment by SebastianBerlin** [comment]
> this didn't help, but adding mastodon to the www-data group and vice-versa did. I feel like this should probably be added to the instructions?

@jdkruzr, what do you mean by vice-versa? I have the same issue with a fresh ubuntu 22 installation and mastodon 4.0.2 – and `chmod -R o+r public/` doesn't work either.

I already added mastodon to the `www-data` group via `usermod -a -G www-data mastodon` but what else?

I have really no idea, why it's that odd, and where the problem is. Thx!

**Comment by theawes0megamer** [comment]
@SebastianBerlin I did the same. Did you ever fix this?
