### ISSUE TITLE
Hover Pop-Up for basic profile information

### ISSUE THREAD

**Issue by btjprojects** [mastodon/mastodon#18252]
### Pitch

One of the things I really miss from the birdsite (ok Twitter) is the hover pop-up you get of a user's profile information so you can see their bio and basic stats without having to click into the full profile.

### Motivation

Anyone new to the platform and looking for users to follow, etc.

**Comment by ryliejamesthomas** [comment]
This's a good suggestion, but there's already an issue for it: https://github.com/mastodon/mastodon/issues/14918

**Comment by btjprojects** [comment]
Thanks I've liked that issue and I'll close this one.
