### ISSUE TITLE
Suspension of local account (at least) doesn't delete the data after 1 month

### ISSUE THREAD

**Issue by todoneunl** [mastodon/mastodon#18258]
### Steps to reproduce the problem

1. Normally when you suspend an account, the account can be fully restored during 1 month and after that the data will be deleted.
2. This doesn't seem to happen
3. See screenshot.
...
![image](https://user-images.githubusercontent.com/41594439/166275085-8c99518c-551a-4a23-b3f7-d56a1d18dffb.png)

It's also possible that this is an old bug and older data hasn't been removed after that. 

### Expected behaviour

Data of (local) suspended account will be deleted after 1 month

### Actual behaviour

Data of (local) suspended account isn't deleted after 1 month.

### Specifications

Mastodon 3.5.1

**Comment by ClearlyClaire** [comment]
Do you have a sidekiq job processing the `scheduler` queue? Do you have failed jobs about `AccountDeletionWorker`?

**Comment by joenepraat** [comment]
scheduler queue: yes
AccountDeletionWorker: If I click through the pages of the failed jobs, I don't find that. Unfortunately I see no option to search in Sidekiq.

There are also a few remote accounts with failed data deletion, mostly part of a server suspension, but maybe that's another issue.

I know this issue  is vague, so let's keep it open, and I will keep en eye on it. I will manually delete the data of this one.

**Comment by ClearlyClaire** [comment]
You could check the logs in `journalctl -u mastodon-sidekiq`.

Can you open a Rails console (`RAILS_ENV=production bundle exec rails c`) and try the following things? (please report the output)
```ruby
AccountDeletionRequest.where('created_at <= ?', AccountDeletionRequest::DELAY_TO_DELETION.ago).reorder(nil).find_each do |deletion_request|
  puts "Deletion request from #{deletion_request.created_at.to_s}"
  DeleteAccountService.new.call(deletion_request.account, reserve_username: true, reserve_email: true)
end
```

**Comment by joenepraat** [comment]
```
Chewy console strategy is `urgent`
Loading production environment (Rails 6.1.5)
irb(main):001:1* AccountDeletionRequest.where('created_at <= ?', AccountDeletionRequest::DELAY_TO_DELETION.ago).re
order(nil).find_each do |deletion_request|
irb(main):002:1*   puts "Deletion request from #{deletion_request.created_at.to_s}"
irb(main):003:1*   DeleteAccountService.new.call(deletion_request.account, reserve_username: true, reserve_email: 
true)
irb(main):004:0> end
Deletion request from 2021-01-03 19:26:00 UTC
[paperclip] deleting /home/mastodon/live/public/system/cache/accounts/avatars/000/000/424/original/41db3988d2a7dd9
d.jpg
[paperclip] deleting /home/mastodon/live/public/system/cache/accounts/headers/000/000/424/original/2921bd23ffb6a27
e.jpg
```

And than a lot of Elasticsearch warnings, alternated with lines like this:

```
Deletion request from 2021-01-23 17:49:54 UTC
[paperclip] deleting /home/mastodon/live/public/system/cache/accounts/avatars/000/002/000/original/51e4fa2360f9539
3.jpg
```

**Comment by ClearlyClaire** [comment]
ok, seems like there is no error when processing account deletions, and the particular account you listed should now be properly deleted.

This means that for some reason, that code did not run. So either the `UserCleanupScheduler` did not run at all, or it failed before executing this block of code.

What does `Scheduler::UserCleanupScheduler.perform_inline` do in a Rails console?

Have you modified `config/sidekiq.yml` in any way?

Can you double-check that there is a sidekiq process handling the `scheduler` queue?

**Comment by todoneunl** [comment]
Old issue. Doesn't seem to happen anymore as far as I can see,
