### ISSUE TITLE
Reflect default setting on P2P sharing on instance about page

### ISSUE THREAD

**Issue by rriemann** [mastodon/mastodon#18251]
### Pitch

The about page of the instance tube.social.network.europa.eu (EU Tube) operates on P2P opt-in mode: If users want to employ P2P, they must become active and opt-in. Otherwise it is disabled by default.

Can we please also reflect the opt-in/opt-out mode here? I suggest the current two values in case that P2P is activated:

P2P enabled by default (opt-out mode): :heavy_check_mark: (active unless disabled by the user)

P2P disabled by default (opt-in mode): :heavy_check_mark:  (inactive unless activated by the user)

Current design:

![image](https://user-images.githubusercontent.com/111932/166250509-a891f739-a6c3-434c-b4b2-fbcd9d10422a.png)

### Motivation

The about page of opt-in instances may be read as if P2P were activated by default and as such the visitor's IP address shared with other members of the P2P network. GDPR mandates to be transparent about the processing of personal data. Hence, I suggest to change the wording slightly to avoid confusion.

**Comment by ClearlyClaire** [comment]
I assume you want to report that to https://github.com/Chocobozzz/PeerTube, not Mastodon

**Comment by rriemann** [comment]
argh! Please delete this one!
