### ISSUE TITLE
Can't see the login page or the home page on a fresh install - Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by rohtua** [mastodon/mastodon#18263]
### Steps to reproduce the problem

I've setup a fresh install of Mastodon on my Ubuntu 20.04 server. It all appears to be working correctly after following the installation instructions below:

https://docs.joinmastodon.org/admin/install/

I had no errors during the setup and the systemd services are all up and running however when I navigate to the home page it's just a blank page (upon navigating to it initially it's blank, refreshing the page then loads the error screen with the elephant). I can't see the login screen or the homepage after logging in. I can however see other pages on the site which appear to be normal (no need to refresh they just load when navigated to). For example if I go to example.com/about then I can see the about page and login from there (although succesfully logging in takes me to the blank front page). Once logged in I can go to the settings pages and they all work and I can view user pages (e.g. example.com/@user). The formatting all appears to be correct.

Looking online I've seen suggestions that it could be permissions issues (I've tried setting permissions on the entire 'live' directory to 777), ownership issues (again I've tried changing the ownership to www-data no luck). 

I've also seen suggestions that it could be missing stylesheets but both the assets folder and the packs folder are there and the pages I can see do appear to be formatted correctly with nothing missing.

Another suggestion I've seen and tried is to change the version of yarn from stable to latest but again it doesn't seem to have had an effect. 

I've tried disabling the firewall on the serverand also on the off chance I disabled the firewall on my router to see if there was any interferance there but no luck on either count.

Finally I've removed the entire live folder and the database and started from scratch but I've had exactly the same result. 

I'm at a bit of a loss as to what I can try next, I don't know whether it's something I've not configured or a bug in the current version. Any help/suggestions would be greatly appreciated. 

### Expected behaviour

The login/homepage should appear

### Actual behaviour

Just seeing a blank page 

### Specifications

The server is running Ubuntu 20.04 LTS. 

For testing I have used both the latest versions of Firefox and Edge on a Windows 11 machine and also tried with Firefox and Chrome on Android. I see the same behaviour on all browsers.

**Comment by ClearlyClaire** [comment]
Is there anything in the `mastodon-web` logs? (`journalctl -u mastodon-web`)

**Comment by rohtua** [comment]
> 

Hi it does show 404 errors in the log which I believe has been linked to missing stylesheets in the past which doesn't seem to be my issue. I've included the log as an attachment because for some reason the editor was just formatting it as a continuous block of text rather than in lines. 

I've been having a look at some other mastodon sites and what I've noticed is that when navigating to the site e.g. mastodon.social I'm automatically redirected to mastodon.social/about

With my site if I go to example.com/about then the page loads but logging in then redirects me to example.com/home which is a blank screen. Whereas logging into mastodon.social redirects to mastodon.social/web/start which again if I login then navigate to that address for my site it works. I'm thinking there's a redirection issue somewhere but I don't know where. The nginx config I've used is the one generated during setup and the only change is the server name. I've also included my nginx config attached.

[mastodon_web_log.txt](https://github.com/mastodon/mastodon/files/8611776/mastodon_web_log.txt)

[mastodon.txt](https://github.com/mastodon/mastodon/files/8611794/mastodon.txt)

**Comment by ClearlyClaire** [comment]
The blank page is served by nginx's cache, and it seems like it's not actually a blank page, but RocketChat's landing page (not loading properly because the assets cannot be found). My guess is that nginx's cache is shared across your subdomains and the cache for RocketChat is served instead of Mastodon's landing page.
