### ISSUE TITLE
Allow for "simple" backlinks

### ISSUE THREAD

**Issue by apfelnutzer** [mastodon/mastodon#18290]
### Pitch

I tried to add a backlink containing the `rel="me"` attribute into my Thingiverse profile to have a confirmed link in my Mastodon profile. Unfortunately (probably due to security/code injection reasons), Thingiverse obviously strips down this link to a simple link without the `rel` attribute. Wouldn't it be sufficient to look for such "simple" backlinks?

### Motivation

Simple backlinks could be integrated easier into other platforms, so that the verification can be used more broadly - not just for your own website.

**Comment by ClearlyClaire** [comment]
Hi! Unfortunately, such a change would make it easy for people to claim pages they do not own. For example, when you boost or publicly mention someone on Mastodon, your public page will link to them, so someone mentioned/boosted could simply claim to be you and have link verification working.

**Comment by apfelnutzer** [comment]
Hm, I see - that's a pity :-/. Thanks for your quick response though!
