### ISSUE TITLE
Add support for TLS 1.3 on rel="me" check

### ISSUE THREAD

**Issue by BirdInFire** [mastodon/mastodon#18313]
### Pitch

Actually for user who use a modern config of nginx/apache/traefik/..., (who only allow TLS 1.3) the rel="me" check fail (since it seem the script / bot who do the check seem to not support it).

### Motivation

I think the people who are in advance in security (by removing older security first mustn't be "punished" it's because they are in advance on other they can found (like i found) potential problem for when TLS 1.2 will retire (probably after the appearance of TLS 1.4 or a critical vulnerability not fixable via server/client update).

**Comment by ClearlyClaire** [comment]
Mastodon itself performs the link verification, and it should support TLSv1.3. I think you reached an incorrect conclusion and your issue is because of something else.

**Comment by BirdInFire** [comment]
> Mastodon itself performs the link verification, and it should support TLSv1.3. I think you reached an incorrect conclusion and your issue is because of something else.

no, i can confirme that it was the activation of TLS 1.2 and cipher of tls 1.2 who have solved the problem, i have tried EVERYTHING removing robots.txt, header security, firewall all failed, active tls 1.2 WAS the solution who have fixed my problem.

**Comment by BirdInFire** [comment]
> Mastodon itself performs the link verification, and it should support TLSv1.3. I think you reached an incorrect conclusion and your issue is because of something else.

no, i can confirme that it was the activation of TLS 1.2 and cipher of tls 1.2 who have solved the problem, i have tried EVERYTHING removing robots.txt, header security, firewall all failed, active tls 1.2 WAS the solution who have fixed my problem.

**Comment by ClearlyClaire** [comment]
Can you share the URL you were trying to check as well as the Mastodon server you were trying to check from? I have confirmed TLSv1.3 to work on latest Mastodon on a reasonably recent system.

**Comment by BirdInFire** [comment]
i have dont it onto the main server (mastodon . social), on a server fedora 35, last nginx, the only change to my config (to make it work was to pass from TLS1.3 settings: 
`#ssl_protocols TLSv1.3;`
`#ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384;`
To TLS 1.3 & 1.2
`ssl_protocols TLSv1.2 TLSv1.3;`
`ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;`
And reload nginx.

**Comment by BirdInFire** [comment]
> Can you share the URL you were trying to check as well as the Mastodon server you were trying to check from? I have confirmed TLSv1.3 to work on latest Mastodon on a reasonably recent system.

Note my certificate (on this server) is an ECC one, so maybe the combination TLS 1.3 only + ECC certificate for HTTPS ?

**Comment by ClearlyClaire** [comment]
> `#ssl_protocols TLSv1.3;`
> `#ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384;`

I have just confirmed that these settings alone do not prevent Mastodon from accessing pages.

> Note my certificate (on this server) is an ECC one, so maybe the combination TLS 1.3 only + ECC certificate for HTTPS ?

I doubt it, but possibly! It would be easier to debug if you could provide the URL that is causing issues (with the server configuration that is causing issues).

**Comment by BirdInFire** [comment]
> > `#ssl_protocols TLSv1.3;`
> > `#ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384;`
> 
> I have just confirmed that these settings alone do not prevent Mastodon from accessing pages.
> 
> > Note my certificate (on this server) is an ECC one, so maybe the combination TLS 1.3 only + ECC certificate for HTTPS ?
> 
> I doubt it, but possibly! It would be easier to debug if you could provide the URL that is causing issues (with the server configuration that is causing issues).

Actually i will not disclose this domain, because i do everyday a check list before connecting to anything related to this domain to maintain the domain (and all services associated) totally disconnected from me, and publish this domain on an account who have tied to my real name (PGP key etc), it will destroy all the organisation process i have done, so maybe add a tag "cannot replicate" and let it open for some month (to see if someone replicate it later ?).

**Comment by BirdInFire** [comment]
> Alright, then I can't help much more. Just to shed light on how the verification is performed, if that can help you understand what else could have gone wrong:
> 
> * the verification is triggered whenever the profile changes, there is no other trigger for the verification
> * it is processed in a low-priority background worker, meaning that there might be a delay between the profile change and the check; the delay depends on how busy the server is
> * the worker performs an HTTP GET on each profile field that contains exactly a link, and gives up if the page returned is over 1MB in size or takes more than 5 seconds to connect or 10 seconds to reply; if this results in a HTTP 200 status code, with a `a` and `link` tag with `rel="me"` attributes (no other value) and linking back exactly to your profile (case-sensitive comparison, for now), the link is considered verified

Will try in an hour or two to relaunch the old settings remove the url and add it again, if it work will say and close.

**Comment by BirdInFire** [comment]
So i have tried again
Step 1 : remove the url from the profile,
Step 2 : redo the settings : 
#ssl_protocols TLSv1.3;
#ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384;
Step 3 : restart nginx
Step 4 : push the url again, and grey.

redo step 1 & 4 : 3 times.

Reactivate TLS1.2 (on step 2)
Instant green on Step 4.

**Comment by unclearParadigm** [comment]
Same experience around TLS1.3 for me. A site to test it would be: [blog.rtrace.io](https://blog.rtrace.io). The rel=me href is in the footer, yet the verification does not work. In general it seems that at least [mastodon.social](https://mastodon.social) instance does not support TLSv1.3. Also had troubles federating with Fediverse services that only support TLSv1.3.

**Comment by ClearlyClaire** [comment]
I can't reproduce this, but I guess it could be an issue with the OpenSSL version or certificate installed on mastodon.social

**Comment by unclearParadigm** [comment]
Yes. I assume, it might be an outdated(?) version of OpenSSL on this particular instance (no offense to Eugen there). I'm going to give it a try with a different masto-instance just to verify it's not the fault of Mastodon (the codebase), but rather the configuration of above mentioned instance. Thanks @ClearlyClaire for helping

**Comment by BirdInFire** [comment]
> Yes. I assume, it might be an outdated(?) version of OpenSSL on this particular instance (no offense to Eugen there). I'm going to give it a try with a different masto-instance just to verify it's not the fault of Mastodon (the codebase), but rather the configuration of above mentioned instance. Thanks @ClearlyClaire for helping

it's seem @ClearlyClaire must be right, when i try (with some manual config) to reach mastodon.social (with tls 1.3 only) it fail. must be mastodon.social fault, anyone who can reach Eugen ? (have tried to ask him in DM when opening this but not had answer since).
