### ISSUE TITLE
[ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: 192.168.2.170

### ISSUE THREAD

**Issue by RJGhugo** [mastodon/mastodon#18333]
### Steps to reproduce the problem

[8] Puma starting in cluster mode...
[8] * Puma version: 5.6.4 (ruby 3.0.3-p157) ("Birdie's Version")
[8] *  Min threads: 5
[8] *  Max threads: 5
[8] *  Environment: production
[8] *   Master PID: 8
[8] *      Workers: 2
[8] *     Restarts: (✔) hot (✖) phased
[8] * Preloading application
[8] * Listening on http://0.0.0.0:3000
[8] Use Ctrl-C to stop
[8] - Worker 0 (PID: 11) booted in 0.02s, phase: 0
[8] - Worker 1 (PID: 14) booted in 0.01s, phase: 0
[ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: 192.168.2.170

### Expected behaviour

get my mastodon site

### Actual behaviour

blank website

### Specifications

Nginx Proxy on 192.168.2.5
proxy_pass http://192.168.2.170:3000;

k3s service listen on 192.168.2.170:3000
NODE_ENV=production
RAILS_ENV=production
TRUSTED_PROXY_IP=192.168.2.170

**Comment by ClearlyClaire** [comment]
Hi! Mastodon expects to be given the proper `Host` header, please look at the provided nginx configuration file (`dist/nginx.conf`) for an example.

Also, are you getting a blank page, or an error page? In the latter case, I'm curious to know if #17143 would have helped you to identify and fix the issue on your own.

**Comment by RJGhugo** [comment]
### dist/nginx.conf
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

upstream backend {
    server 192.168.2.170:3000 fail_timeout=0;
}

upstream streaming {
    server 192.168.2.169:4000 fail_timeout=0;
}

proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=CACHE:10m inactive=7d max_size=1g;

server {
  listen 80;
  listen [::]:80;
  server_name mastodon-server.example.com;

  keepalive_timeout    70;
  sendfile             on;
  client_max_body_size 80m;

  root /home/mastodon/live/public;

  gzip on;
  gzip_disable "msie6";
  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;
  gzip_buffers 16 8k;
  gzip_http_version 1.1;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml image/x-icon;

  add_header Strict-Transport-Security "max-age=31536000" always;

  location / {
    try_files $uri @proxy;
  }

  location ~ ^/(emoji|packs|system/accounts/avatars|system/media_attachments/files) {
    add_header Cache-Control "public, max-age=31536000, immutable";
    add_header Strict-Transport-Security "max-age=31536000" always;
    try_files $uri @proxy;
  }

  location /sw.js {
    add_header Cache-Control "public, max-age=0";
    add_header Strict-Transport-Security "max-age=31536000" always;
    try_files $uri @proxy;
  }

  location @proxy {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Proxy "";
    proxy_pass_header Server;

    proxy_pass http://backend;
    proxy_buffering on;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    proxy_cache CACHE;
    proxy_cache_valid 200 7d;
    proxy_cache_valid 410 24h;
    proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
    add_header X-Cached $upstream_cache_status;
    add_header Strict-Transport-Security "max-age=31536000" always;

    tcp_nodelay on;
  }

  location /api/v1/streaming {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Proxy "";

    proxy_pass http://streaming;
    proxy_buffering off;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    tcp_nodelay on;
  }

  error_page 500 501 502 503 504 /500.html;
}

### Activate

sudo nginx -t

sudo systemctl restart nginx.service

sudo certbot --nginx

### re-migrate

bundle exec rails db:migrate

https://neilzone.co.uk/2021/10/migrating-mastodon-to-a-raspberry-pi-4
https://github.com/mastodon/mastodon/issues/15696

### Thanks
Thanks for the quick hint.
