### ISSUE TITLE
Rails error during setup

### ISSUE THREAD

**Issue by JamesM92** [mastodon/mastodon#18342]
### Steps to reproduce the problem

1. download docker compose, and env.production files 
2. in docker compose comment out the build lines.
3. in terminal run the command :
4. docker-compose run --rm web bundle exec rake mastodon:setup
5. all other database containers were turned off for testing. so they shouldnt cause issue
6. the following is the output during the setup.
...
```
root@OpenMediaVult:/var/lib/docker/volumes/portainer_data/_data/compose/131# docker-compose run --rm web bundle exec rake mastodon:setup
Creating volume "131_public" with local driver
Creating 131_db_1    ... done
Creating 131_redis_1 ... done
Creating 131_web_run ... done
Your instance is identified by its domain name. Changing it afterward will break things.
Domain name: penguinarmy.club

Single user mode disables registrations and redirects the landing page to your public profile.
Do you want to enable single user mode? No

Are you using Docker to run Mastodon? Yes

PostgreSQL host: db
PostgreSQL port: 5432
Name of PostgreSQL database: postgres
Name of PostgreSQL user: postgres
Password of PostgreSQL user:
Database configuration works! 🎆

Redis host: redis
Redis port: 6379
Redis password:
Redis configuration works! 🎆

Do you want to store uploaded files on the cloud? No

Do you want to send e-mails from localhost? No
SMTP server: smtp.mailgun.org
SMTP port: 587
SMTP username:
SMTP password:
SMTP authentication: plain
SMTP OpenSSL verify mode: none
E-mail address to send e-mails "from": Mastodon <notifications@penguinarmy.club>
Send a test e-mail with this configuration right now? no

This configuration will be written to .env.production
Save configuration? Yes
Below is your configuration, save it to an .env.production file outside Docker:

# Generated with mastodon:setup on 2022-05-06 17:59:31 UTC

# Some variables in this file will be interpreted differently whether you are
# using docker-compose or not.

LOCAL_DOMAIN=penguinarmy.club
SINGLE_USER_MODE=false
SECRET_KEY_BASE=6771cd4fdb45339dda4be926637733b1886b4340a7a9d4b4c8c4a2904562d79f29a83e71ca48e021ab4983adea129aef299a74c7ccfc0786952471fb5265f65c
OTP_SECRET=ecc699ffea87a4374321dd3040706d844dc82628b3318f39cc26bd0f1e50e29814f04c13b5fa585daac5b2e577fccc5515f00e332c261268eabafafdd114ecad
VAPID_PRIVATE_KEY=dt43mspg1JgOjEH2R1CmPuUi4KwZP9PYTWemmWRS3Xc=
VAPID_PUBLIC_KEY=BEb-mvTjeMzkSlTc-lfGKh5S6TVv9qhr6pW0PqVBxiqdBbUrjapOdNzYBCMw2_VI_hgT1Rr_jW6hisrMMit4W0A=
DB_HOST=db
DB_PORT=5432
DB_NAME=postgres
DB_USER=postgres
DB_PASS=postgres
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=
SMTP_SERVER=smtp.mailgun.org
SMTP_PORT=587
SMTP_LOGIN=
SMTP_PASSWORD=
SMTP_AUTH_METHOD=plain
SMTP_OPENSSL_VERIFY_MODE=none
SMTP_FROM_ADDRESS=Mastodon <notifications@penguinarmy.club>

It is also saved within this container so you can proceed with this wizard.

Now that configuration is saved, the database schema must be loaded.
If the database already exists, this will erase its contents.
Prepare the database now? Yes
Running `RAILS_ENV=production rails db:setup` ...


Database 'postgres' already exists
Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
Switching object-storage-safely from green to red because Redis::CannotConnectError Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
Done!

All done! You can now power on the Mastodon server 🐘

Do you want to create an admin user straight away? Yes
Username: admin
E-mail: admin@penguinarmy.club
Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
Switching object-storage-safely from green to red because Redis::CannotConnectError Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
You can login with the password: dbd19caeba5aa8b2a6d6bd3a11ad913c
You can change your password once you login.
root@OpenMediaVult:/var/lib/docker/volumes/portainer_data/_data/compose/131#

```

### Expected behaviour

for setup to complete without errors

### Actual behaviour

errors during rail deployment , nothing shows up when accessing port

### Specifications

default settings for docker compose.

**Comment by ClearlyClaire** [comment]
Hi, the database containers should be up when running the script, this includes the `redis` container.

**Comment by JamesM92** [comment]
Isn't the script starting and running the containers when you start it? Or is that something I'm supposed to do manually before starting the script?

From the output it looks like it's creating the redis container at the beginning of the script

**Comment by ClearlyClaire** [comment]
The script runs *inside* a container, so starting and running the containers is not something it does nor something it can do.

The containers are created because you ran `docker-compose`, but I don't know `docker-compose` enough to know whether it is supposed to start the other containers when ran with these options.

**Comment by timaschew** [comment]
I got same error, but the issue was that the .env.production file was not overwritten with the one which I've manually edited from the sample.

The redis variables are almost same, the correct config has this line (even if the password is empty!): `REDIS_PASSWORD=`

**Comment by timaschew** [comment]
But I still can't acccess the web (via curl): In the docker-compose logs I see

```
 web_1        | [ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: localhost
 ```
 
 And it doesn't matter if I try to access other variants like `curl 127.0.0.1:3000` or `curl 0.0.0.0:3000`.

**Comment by JamesM92** [comment]
Even adding 
REDIS_PASSWORD= to the env file i still get the same error as above

**Comment by ClearlyClaire** [comment]
I think this might be because of #18160

**Comment by JamesM92** [comment]
> Oh, wait, I did not notice that the script managed to reach redis and postgres at first but failed later. I will investigate more.
> 
> > As a side note the env.production files never updates even though the script keeps saying that it is going to update it , it never does.
> 
> It should be printing “Below is your configuration, save it to an .env.production file outside Docker:” which is pretty self-explanatory

ok, i thought it said it was saving it to the env file, not that it was recommending i copy it. I must have misread it.

**Comment by ClearlyClaire** [comment]
> So what do i do to resolve it?

I'm trying to figure it out, but one thing you can do, I think, to work around the issue, is to put the following in your `.env.production` (outside docker):

```
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=
```
