### ISSUE TITLE
Blocking instances by users

### ISSUE THREAD

**Issue by gaditano66** [mastodon/mastodon#18345]
### Pitch

I would like to see the addition of the possibility for users of any instance to be able to block instances themselves, not just mute them.

### Motivation

I think it could reduce work for moderators and give more freedom to the fediverse.

**Comment by ClearlyClaire** [comment]
I am not sure what you mean. A user blocking a domain severs all follow relationships with their accounts, prevents any new one, and, when `AUTHORIZED_FETCH` is enabled, prevents these servers from fetching the user's public posts.

**Comment by gaditano66** [comment]
> I am not sure what you mean. A user blocking a domain severs all follow relationships with their accounts, prevents any new one, and, when `AUTHORIZED_FETCH` is enabled, prevents these servers from fetching the user's public posts.

I mean that now a user can only "mute" an instance but if he wants to block, for example, a nazi instance, he cannot. The user now always depends on the admin and if he does not want that instance to be related to his account, he does not need to wait for the moderator or admin.

**Comment by ClearlyClaire** [comment]
“If he does not want that instance to be related to his account”?

**Comment by gaditano66** [comment]
> “If he does not want that instance to be related to his account”?

He/she doesn't want people from that instance to read/follow/interact with his/her account.
I mean: what an admin does now blocking an instance, but made by all users, not only muting them.
So, it's fast and not waiting moderators/admin to do something.

**Comment by gaditano66** [comment]
An user now has the possibility to mute an entire instance. Why not blocking it?

**Comment by tribela** [comment]
User can block each servers. Mute is what is not implement yet

**Comment by gaditano66** [comment]
> User can block each servers. Mute is what is not implement yet
Oh, I thought it was the opposite, thank you!
I change to English language and I see it now (I use the Spanish language, sorry)

**Comment by FediVideos** [comment]
Have been testing out user level domain blocks between two servers both running authorized fetch (social.chinwag.org and social.growyourown.services). The blocks came from the same account, AT fedithing AT chinwag.org, and were directed at an account and domain on social.growyourown.services.

The domain block just isn't behaving the same way as account blocks. The account block removes all accounts from being visible and prevents any kind of interaction. The domain block doesn't do this, it is showing posts and allows interaction.

Have attached screenshots as viewed from the blocked domain, the first is from an account block while the second is from a domain block (both user-level, not anything admin-based).

User-level domain blocking seems to be behaving like a mute, while user-level account blocking is a proper block. Perhaps this issue needs to be re-opened?

![AccountBlockTest](https://github.com/mastodon/mastodon/assets/75383929/2aebb79b-a924-4665-b2ce-c2bea513ed4c)

![DomainBlockTest](https://github.com/mastodon/mastodon/assets/75383929/8bb09598-7430-48d8-b373-ffa5f8dc6fad)

**Comment by ClearlyClaire** [comment]
The domain block feature available to users do not let the remote server know that a block has happened (there are multiple reasons for this: there is no protocol to convey this at the moment, and when blocking a whole server, you generally don't want them to receive a protocol message that makes them aware of the block)

The new domain block modal better conveys what you can expect from the feature:
![image](https://github.com/mastodon/mastodon/assets/384364/c80eea03-aa68-4f72-8174-a843540eec76)

**Comment by ClearlyClaire** [comment]
> So user-level domain block _is_ a slightly different feature to user-level account block? Is there a particular reason why they differ?

Yes, as written above, the reasons are the following:
- there is currently nothing in the protocol to represent that
- when blocking a specific person, you generally trust the server but not the person; when blocking a domain, you generally don't trust the server, and thus may not want it to know about the block at all (which it needs to know to behave the same way as user blocks)

**Comment by jonpincus** [comment]
Thanks @FediVideos and @ClearlyClaire for the clarifications.

Does the user-level domain block the same as an instance-level domain block in this way?

**Comment by skybrian** [comment]
The new dialog seems pretty clear. I'm not sure those assumptions work for some servers, though. If someone wants to block Threads, does it need to be a secret?

It seems like there is a difference between "ghosting" and blocking, and it's conceptually orthogonal to whether it's a user or a server. it's not necessarily true that you always want to block users and ghost servers. Possibly, you might want to block all the users on a server, or ghost a specific user.

Although it's essential for ghosting, it seems kind of bad if the follow button appears enabled but doesn't work. Won't that increase confusion and the perception that Mastodon is buggy and/or difficult to use?
