### ISSUE TITLE
In a muted conversation, admin still sends notifications to the rest v. 3.5.2 masto.host

### ISSUE THREAD

**Issue by gaditano66** [mastodon/mastodon#18349]
### Steps to reproduce the problem

1. Open a thread with some users, posting 
2. Admin is in that thread, posting or not 
3. Some user mutes the conversation
4. When admin in the same instance posts in this thread, the user in the same instance who muted the conversation in the thread still receives the posts from his/her admin
...

### Expected behaviour

All posts should be muted

### Actual behaviour

Notifications from admin are received

### Specifications

All notifications when you mute a thread should be muted but admin toots will be received.

**Comment by Gargron** [comment]
Notifications from staff cannot be muted since #9152

**Comment by gaditano66** [comment]
> Notifications from staff cannot be muted since #9152

Oh sorry. Then close this thread.
Thank you!
