### ISSUE TITLE
Images not available after upgrading to 3.5.2, also could not attach image when posting toots

### ISSUE THREAD

**Issue by fweng322** [mastodon/mastodon#18401]
### Steps to reproduce the problem

1. Upgrading to 3.5.2
2. Images became "Not available", but can be clicked and will show in a new window
3. Attaching images in a toot would be hang there and could not post
...

Instance: https://social.slat.org/

### Expected behaviour

Images can be shown and attached in a toot

### Actual behaviour

Images not available in home/local/federated timeline

### Specifications

1. tag 3.5.2
2. Running on Debian Buster 
3. Browser is Firefox 91.9.0esr but same on Chrome 101.0

**Comment by fweng322** [comment]
Tried running `RAILS_ENV=production ./bin/tootctl cache clear` but of no use

**Comment by ClearlyClaire** [comment]
Hi! What was the last functional version you updated from?
Do you have a large sidekiq backlog? (See https://social.slat.org/sidekiq/queues)
Is there any error in sidekiq's logs? (See `journalctl -u mastodon-sidekiq`)

**Comment by fweng322** [comment]
Thanks for replying.

1. Last functional version is 3.4.x (I forget which)
2. Looks like no backlog in sidekiq... 0 in the queues, 4 scheduled, 1 busy, 12,138,090 processed, 927,963 failed.
3. I have 1.5GB log for mastodon-sidekiq since Apr. 29, even only today (May 12) I have around 148MB text log.  Is it too much?  But filtering out "ERROR" only I got 74,405 entries, all "Too many open files"
`xfw: 5月 12 13:04:53 social bundle[411625]: 2022-05-12T05:04:53.732Z pid=411625 tid=rh4x ERROR: heartbeat: Too many open files @ rb_sysopen - /proc/411625/status`

I have no idea how to go on.

**Comment by ClearlyClaire** [comment]
It sounds like #18063. Are you using Elasticsearch?

**Comment by fweng322** [comment]
> It sounds like #18063. Are you using Elasticsearch?

Yes.  In the dashboard a message said,

"Incompatible Elasticsearch version: Elasticsearch 6.8.23 is running while 7.x is required "

**Comment by ClearlyClaire** [comment]
Ok, then I don't know if that would fix the “Too many open files” issue, but you need to update Elasticsearch, or disable it

**Comment by fweng322** [comment]
Thanks, I'll observe it for more time.
