### ISSUE TITLE
Prevent import of wrong csv file

### ISSUE THREAD

**Issue by septem9er** [mastodon/mastodon#18418]
### Pitch

In the data import menu of mastodon, a feature to prevent accidentally uploading the wrong type of list for the selected import type.

Some ideas of how to do that:
1. Make the list identifiable on export and check that on import. Some lists, like the following list, already has headings in the csv. If you do this for all of the lists and on import check that the heading isn't wrong, you could prevent this. Backwards compatibility shouldn't be a problem either if you just check that the heading isn't wrong if there is one. If a user wants to import a different kind of list for some reason, he could simply change the heading in the csv file.
2. Show a warning when you lose followers when importing a blacklist, as this is probably most relevant, because it cannot easily be undone.

### Motivation

As I wanted to import bothe my blocking list and my following list from my old account in the new one, I accidentally selected the csv of my following list as blocking list. Therefore I lost a lot of my followers.

As users typically will import multiple lists at a given time, it's not unlikely to accidentally click on the wrong one.

**Comment by ClearlyClaire** [comment]
I think https://github.com/mastodon/mastodon/pull/21054 addresses it by:
- splitting imports between destructive and non-destructive types
- try to detect the type of import based on file name and CSV headers, and display a warning if something is amiss
