### ISSUE TITLE
Add "Show boosts" option on the account profile page

### ISSUE THREAD

**Issue by OmmyZhang** [mastodon/mastodon#18413]
### Pitch

Add a "Show boosts" switch button on the account profile page, so people can choose only to see original posts or posts including reblogging.

Here is a demo:
![](https://user-images.githubusercontent.com/17777309/168445748-68ab469f-86d1-4445-87c8-28c6f77af629.png)
(maybe the button should be smaller)

Adding a `collapseButton` may make things too complex, so I simply add a `Toggle` in `Header`.

I will try to open a PR if this is acceptable.

### Motivation

I have seen so many people in my community say that they want to see one's original posts, especially when dealing with follow requests. Therefore, this option will be very useful.

**Comment by ryliejamesthomas** [comment]
Yeah, was just thinking the other day how useful this'd be.

My idea was to exclude boosts from the 'Posts and replies' tab, but yours is probably better.

**Comment by OmmyZhang** [comment]
> My idea was to exclude boosts from the 'Posts and replies' tab

This seems also a good idea, and makes things much simpler.

**Comment by trwnh** [comment]
> Reblogs are already excluded from the "posts and replies" tab...

Wait, really? Do there's no way to view posts, boosts, and replies all at once?

**Comment by ryliejamesthomas** [comment]
I'm looking at that tab right now and seeing boosts

**Comment by Gargron** [comment]
Then I misremembered

**Comment by trwnh** [comment]
It might be better to have a quick filter bar on the profiles just like there is on the notifications? I think that it could make sense to have toggles for original posts, boosts, and replies so that people can, for example, view only original posts (not replies or boosts)

**Comment by hexagontruth** [comment]
> ### Pitch
> Add a "Show boosts" switch button on the account profile page, so people can choose only to see original posts or posts including reblogging.
> 
> Here is a demo: ![](https://user-images.githubusercontent.com/17777309/168445748-68ab469f-86d1-4445-87c8-28c6f77af629.png) (maybe the button should be smaller)
> 
> Adding a `collapseButton` may make things too complex, so I simply add a `Toggle` in `Header`.
> 
> I will try to open a PR if this is acceptable.

Do you have a public-facing commit for this hypothetical PR @OmmyZhang? I would like to incorporate it into my instance if nothing like this is going to be a mainline feature anytime soon.

**Comment by OmmyZhang** [comment]
@hexagontruth Hi, you can find it in pr #24267 now, if you are still interested.

**Comment by trwnh** [comment]
Closing in favor of #10011
