### ISSUE TITLE
Display friendlier error when a user is not found on a server

### ISSUE THREAD

**Issue by bvanrijn** [mastodon/mastodon#1842]
Now, when you search for a nonexistent user on some server, for instance `@example@mastodon.cloud`, you get an error:

> 422 Remote account could not be resolved

Nothing wrong with that per se, but in my opinion a better message would be

> Oops! Couldn't find that user there.

What do you think?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by thomaskuntzz** [comment]
Yep, agree!

**Comment by trwnh** [comment]
i think this issue can be closed now? search just says "0 results" instead of throwing any error at all
