### ISSUE TITLE
RSS feed entry header

### ISSUE THREAD

**Issue by snan** [mastodon/mastodon#18446]
### Steps to reproduce the problem

I was looking at the RSS feed for a user on mastodon.social

### Expected behaviour

To  see entry headers derived from the body, or from the CW if there was one

### Actual behaviour

Entry headers contain dates

### Specifications

This was on mastodon.social middle of May 2022.

**Comment by Gargron** [comment]
This is not a bug. I changed it intentionally. This is closer to how a blog feed would look like if blog posts had no titles. On the other hand, post bodies are now rendered fully and all media attachments are included, so you don't need to visit the website to see everything. I've tested the new feed format in Inoreader and Feedly and I think it is a real improvement.

**Comment by snan** [comment]
The problem is that I need to click on every post instead of at a glance selecting the ones that seem the most interesting.
