### ISSUE TITLE
Increase custom emoji file size limit

### ISSUE THREAD

**Issue by tastytea** [mastodon/mastodon#18452]
### Pitch

Mastodon displays the shortcode instead of the image for WebP and GIF emojis (verified with the web client on mastodon.social). Please show the images instead.

I do get why you would want to limit formats, compatibility with old platforms and so on. But I see no reason not to show them when they are received.

Test post with GIF and WebP image: <https://very.tastytea.de/notes/90elbge0z2>  
Related: #15846

### Motivation

I'm using Misskey, and some of the emojis I send are WebPs or GIFs. My friends are sad because they can't see them. :crying_cat_face:

**Comment by trwnh** [comment]
gif is allowed, i'm pretty sure? it's just there's a limit of 50kb and that gif you used in the example is 67.6kb

**Comment by trwnh** [comment]
with that said, however, i think the limits could be feasibly increased... discord, for example, allows up to 256kb

**Comment by tastytea** [comment]
WebP support was [merged today](https://github.com/mastodon/mastodon/pull/18506#event-6694552344). I'm changing the title since custom emojis other than the supported `image/png`, `image/gif` and `image/webp` don't seem to be common, so the only issue remaining is the file size limit.

**Comment by Saiv46** [comment]
BTW I think 50kb size limit is too large. When I open built-in emoji selector - I'll need to wait 3-5 minutes for all emojis to load, and that's on desktop via decent internet connection.

I made random 128x128 image and stored it as:
- PNG - 32.4 kb
- WebP (lossless) - 34.8 kb
- WebP (slight loss) - 24.4 kb
- GIF - 22.1 kb

And that's worst-case scenario, when just you can't compress much. Actual emojis can be smaller with proper encoding, then they don't since you can't exceed 50kb on 128x128 image.

**Comment by tastytea** [comment]
The 3-5 minutes seem to be an issue with your instance? 100 50 KiB emojis are 5 MiB, that shouldn't take longer than a few seconds with a decent internet connection. Furthermore, custom emojis on Mastodon (at least on mastodon.social) are supposed to be cached in your browser for up to 1 year.¹

Most emojis in use today are indeed smaller than 50 KiB. But keep in mind that not all emojis are 128x128 px, some are quite complex (which makes them less compressable) and a few are animated. Can you get <https://very.tastytea.de/files/6ad9dd16-2d9d-4637-9c0c-a6b479306573> below 50 KiB without sacrificing quality?

I don't think increasing the limit will cause everyone to use bigger emojis just because they can. Most of the emojis i see seem to be around 20-30 KiB. The only emojis over 50 KiB are animated, very complex or bigger than 256 px. All of those are pretty uncommon. Increasing the limit will however allow Mastodon users to see all of the emojis that are send from non-Mastodon instances.

¹ `curl -I https://files.mastodon.social/custom_emojis/images/000/003/676/static/77c4094eacccac9e.png`

**Comment by trwnh** [comment]
i think there's an argument to be made in either direction here... perhaps the 256x256 animation you linked should be resized, as doubtless it will be displayed much smaller than that. i don't think there's any guidance for a "max emoji dimensions" per se, but discord specifies 108x108 and i assume this is the maximum size at which it will be displayed.

**Comment by tastytea** [comment]
> i think there's an argument to be made in either direction here... perhaps the 256x256 animation you linked should be resized^, as doubtless it will be displayed much smaller than that. i don't think there's any guidance for a "max emoji dimensions" per se, but discord specifies 108x108 and i assume this is the maximum size at which it will be displayed.

Misskey displays emojis at up to 4 times the normal size (`$[x4 :blobcat:]`), which is 214 px high in this case (seems to depend on the font size). It is possible to increase that even more but that's more a hack than a supported feature.

Then there is the issue of “high DPI” displays, which often are used together with scaling. So you need to have images that are 2x the intended size.

> i also wanted to respond to this bit specifically:
> 
> > 5 MiB, that shouldn't take longer than a few seconds with a decent internet connection
> 
> not everyone has a "decent" internet connection, and 5mb would take 2.5 - 5 minutes to download over a 2g mobile connection. 

I was answering to @Saiv46, who has a decent internet connection. Slow connections are frustating to use with custom emojis as it is, i don't think a few big emojis are gonna change that perceptibly. Unless *all* emojis get bigger all of a sudden, but i don't think that's likely.

> regardless, however, one should strive to optimize their media as much as possible, and using the same gif from above as an example, we can obtain a 58.62% improvement in file size, which is fairly significant.

I agree and i do optimize file size where possible (that's why i asked for WebP support). However, in this case it is not possible without sacrificing quality. I was able to get it down to 60 KiB with WebP.

> 
> it may also be a worthwhile compromise to accept incoming custom emoji within larger limits, but then process them for caching locally at a much smaller size. mastodon, for example, displays emoji at 20px, which is a far cry from the 256x256 that your remote gif is arriving at. even avatars, which are given more visual prominence than emoji, are displayed at 48px.

Sounds good to me. Some people on Mastodon use 3rd party CSS to increase emoji size, i think to 32 px. Keeping “high DPI” in mind, maybe resizing to 64 px is reasonable?

**Comment by tastytea** [comment]
> the source is a gif and resizing the gif to 128x128 still looks suitable to me -- is there a problem with the quality of what i posted? to my eyes, it looks fine, with no perceptible quality loss.

It's totally fine for Mastodon, but too small for Misskey. I can't resize the original file because it is quite likely that it is posted with a 80-120px, or even >200 px height.

Original: <img src="https://very.tastytea.de/files/6ad9dd16-2d9d-4637-9c0c-a6b479306573" height="256">
Resized: <img src="https://user-images.githubusercontent.com/10606431/170981642-80cf7006-50d6-41ef-badd-daec51050a00.gif" height="256">

**Comment by Saiv46** [comment]
> The 3-5 minutes seem to be an issue with your instance? 100 50 KiB emojis are 5 MiB, that shouldn't take longer than a few seconds with a decent internet connection.

You forgot to say that *single* 5 MiB file can be downloaded in few seconds, not 100 small files concurrently.

> Most emojis in use today are indeed smaller than 50 KiB. But keep in mind that not all emojis are 128x128 px, some are quite complex (which makes them less compressable) and a few are animated.

Mastodon never ever need emoji larger than 128x128 px (and that's 4x), and animated emojis can fit into 50kb or less.

> I don't think increasing the limit will cause everyone to use bigger emojis just because they can.

That's literally happening with games, when internet and hard drives become decent enough so you need to download >50 GB of textures in absurd quality.

> Increasing the limit will however allow Mastodon users to see all of the emojis that are send from non-Mastodon instances.

Emojis are not supposed to be that large. I think it's be more feasible to use image attachments or implement stickers.

Maybe Misskey need to restrain a bit? It's so fucking ugly (except project website) so only my weeb friend registered on instance with that, and then he dropped it in favor of centralized social networks.
