### ISSUE TITLE
Undo Announce activity is not sent when unboosting posts from unfollowed remote accounts

### ISSUE THREAD

**Issue by MitarashiDango** [mastodon/mastodon#18471]
### Steps to reproduce the problem

1. Boost posts on remote accounts that don't follow you.
2. Remove boost.
...

### Expected behaviour

Undo Announce activity sent to remote server.

### Actual behaviour

Undo Announce activity is not sent．

### Specifications

Reproducible version: v3.5.2

### Note
The process of sending an Undo Announce was probably introduced with the following commit.
https://github.com/mastodon/mastodon/pull/7959

However, the relevant part has been rewritten with the following commit. (However, looking at his implementation of StatusReachFinder at the time, it seems to be working fine at the time of this commit.)
https://github.com/mastodon/mastodon/commit/e7e099d1a06700d14fa10258f5509fc5c52738c8

https://github.com/mastodon/mastodon/blob/e7e099d1a06700d14fa10258f5509fc5c52738c8/app/lib/status_reach_finder.rb

In the latest version, the following conditional branch processing is introduced in StatusReachFinder, and it seems that the URL of Inbox is not returned in the case of posting.
https://github.com/mastodon/mastodon/blob/54bb659ad14fda8d3427752d2c99716420997d6e/app/lib/status_reach_finder.rb#L22

**Comment by nightpool** [comment]
Thanks, this appears to be a regression from https://github.com/mastodon/mastodon/pull/16051 (not any of the other issues linked)
