### ISSUE TITLE
Allow adding non followed users to lists

### ISSUE THREAD

**Issue by amelandri** [mastodon/mastodon#18485]
### Pitch

Currently lists can contain only users that you follow: they are like filters of your main timeline.

Users should be allowed to add non followed accounts to list

### Motivation

Being able to add non followed account to lists would allow users to keep the main timeline clean and organize contents in a better way.

For example, a user could have his main timeline used only for important contacts while having news, gaming and technology accounts relegated to their specific list.

**Comment by trwnh** [comment]
Duplicate of #6982
