### ISSUE TITLE
Omniauth login doesn't redirect to the previous page after successful login

### ISSUE THREAD

**Issue by connyduck** [mastodon/mastodon#18481]
### Steps to reproduce the problem

1. open any client app
2. log into an instance with SAML that has it enabled

### Expected behaviour

I am logged into the app

### Actual behaviour

The app shows a Webview with the Webapp. I am not actually logged into the app.

<img src="https://user-images.githubusercontent.com/10157047/169703950-0e1864e0-793a-46ac-b17f-10c66b7c0925.png" width="250">

(screenshot from Mastodon for Android)

### Specifications

Mastodon v3.5.2, Tusky/Fedilab/Mastodon app

It seems Mastodon just shows the webapp instead of redirecting to the url specified by the client app when starting the OAuth process

**Comment by Steffo99** [comment]
More in detail, I think the original "destination" URL is forgotten while performing a Omniauth login, and that all Omniauth logins automatically redirect to the home page.

For example, visiting the following URL while logged out:
```
https://mastodon.example/oauth/authorize?client_id=REDACTED&redirect_uri=WHATEVER&response_type=code&scope=read
```
I'm redirected to:
```
https://mastodon.example/auth/sign_in
```
Then, after performing a Omniauth login, instead of going back to the original URL, I'm redirected to:
```
https://mastodon.example
```

**Comment by Steffo99** [comment]
I suspect (but I'm not sure, since I've never used Rails before) that the problematic line of code is the following:

https://github.com/mastodon/mastodon/blob/54bb659ad14fda8d3427752d2c99716420997d6e/app/controllers/auth/omniauth_callbacks_controller.rb#L20

**Comment by Steffo99** [comment]
Specifically, by using `sign_in_and_redirect`, the user is redirected to the "after sign-in page":

https://github.com/heartcombo/devise/blob/8593801130f2df94a50863b5db535c272b00efe1/lib/devise/controllers/helpers.rb#L240

Which supports redirecting to a stored location:

https://github.com/heartcombo/devise/blob/8593801130f2df94a50863b5db535c272b00efe1/lib/devise/controllers/helpers.rb#L216

So perhaps the location is never stored anywhere...?

**Comment by Steffo99** [comment]
Here's what I think is the source of the problem!

https://github.com/mastodon/mastodon/blob/54bb659ad14fda8d3427752d2c99716420997d6e/app/controllers/auth/omniauth_callbacks_controller.rb#L33-L39

**Comment by Steffo99** [comment]
Nope, the fix didn't work. I'm not sure what else to try, I've been messing around with Omniauth all night, and I haven't been able to figure out anything else.

**Comment by Steffo99** [comment]
If needed, I can provide an example SAML configuration to debug with.

**Comment by decentral1se** [comment]
FYI OpenID Connect also affected https://github.com/tuskyapp/Tusky/issues/2462#issuecomment-1147224672

**Comment by rscmbbng** [comment]
Can confirm the above!

**Comment by Steffo99** [comment]
I'd rename this to "Omniauth login doesn't redirect to the previous page after successful login".

**Comment by puyoxyz** [comment]
Also experiencing this, on Mastodon iOS app with OpenID Connect:

https://user-images.githubusercontent.com/15311104/188260307-d2d8c27c-596f-4ebe-b751-a2119676cc3a.MOV

(commenting to show a video because that might explain it clearer if anyone doesn't understand)

**Comment by rscmbbng** [comment]
Thanks for sharing the video @puyoxyzkee! The behaviour is identical on both Tusky and Fedilab.

**Comment by AustinFoss** [comment]
Hey! I was searching around with information on how to use Mastodon with OIDC and it took me a while to even find out about Omniauth because the docs still reference OAuth only, and seemingly with instructions to just act as the provider.

Glad I found this discussion and I'm not the only one looking at setting up mastodon as a client. I haven't even installed the server yet because I wanted to confirm this functionality was available first. 

Where can I find the redirect uri that I should use when registering the mastodon client with my provider?

**Comment by CSDUMMI** [comment]
After researching this issue, we found that this issue might relate to an overwrite of the redirect location stored by `store_location_for(:user)`.

Currently, when trying to authorize a third-party app, such a pinafore.social on an instance using SSO, the following occures:

1. Pinafore opens `/oauth/authorize?client_id=XXX&redirect_uri="https://pinafore.social/settings/instances/add
"&response_type=code&scope=read write follow push`
2. Mastodon returns a redirect to `/auth/sign_in` and sets a session cookie.
3. User clicks on the SSO option to log in. 
4. `POST /auth/auth/saml` responds with a redirect to the SAML IDP.
5. User authenticates to SSO.
6. SSO redirects to Mastodon.
7. `POST /auth/auth/saml/callback` redirects to `/`
8. User finds themselves on the homepage.

**Comment by CSDUMMI** [comment]
What I believe happens:

Between step 1 and 2, `store_location_for(:user, 'https://pinafore.social/settings/instances/add')` is called.
Then upon step 3, `store_location_for(:user, '/auth/sign_in')` overwriting the previous value. 

Then upon step 6, `stored_location_for(:user)` is called and return `/auth/sign_in`, which is filtered out and the user is returned to `/`.

The problem that causes this bug, at least according to my theory, is thus that `store_location_for` is called upon every redirect and that it overwrites the previous value.

**Comment by CSDUMMI** [comment]
The reason why I believe that store_location_for is called upon every redirect, is because of this function in devise: [`redirect`](https://github.com/heartcombo/devise/blob/main/lib/devise/failure_app.rb#L77)

**Comment by CSDUMMI** [comment]
A possible bug fix could be to replace `store_location_for` by a stack, that is pushed to on any call to `store_location_for` and pops an element for every call of `stored_location_for`.

**Comment by CSDUMMI** [comment]
I have experimented with this approach and can now tell you, that implementing a stack does not work.

**Comment by CSDUMMI** [comment]
I suspect that this is because session data is removed once a user has logged in.

**Comment by CSDUMMI** [comment]
I have added logging of `store_location_for` and `stored_location_for` functions. 

Here are the logs I collected during signing in via SSO.

```
bundle[35633]: [Store Location] Storing location for user(https://mastodon/)[a5ec7849-138a-4e2b-aa5e-f5d16816de99] method=GET path=/ format=html controller=HomeController action=index status=200 duration=255.24 view=232.27
bundle[35633]: [Store Location] Reading stored location: user[Store Location] No locations storedRedirecting after sign in to nil[c5fb69e7-d6f8-49e2-8411-fde45b9f4fb6] method=POST path=/auth/auth/saml/callback format=html controller=Auth::OmniauthCallbacksController action=saml status=302 duration=182.26 view=0.00 db=47.83 location=https://mastodon/
bundle[35633]: [Store Location] Storing location for user(https://mastodon/)[67ed8a50-ea83-416f-a6b3-733807828877] method=GET path=/ format=html controller=HomeController action=index status=200 duration=145.40 view=98.08 db=33.45
bundle[35633]: [Store Location] Storing location for user(https://mastodon/)[cd9ed176-7b1b-4f91-a17a-baf478b7036c] method=GET path=/ format=*/* controller=HomeController action=index status=200 duration=66.00 view=46.16 db=6.01
```

As you can see, the location `/` is stored before starting the login process, but after returining back to the page from SSO, the session is empty.

**Comment by CSDUMMI** [comment]
```
bundle[35633]: [Store Location] Storing location for user(https://mastodon/oauth/authorize?client_id=U8ZPX1457l2tHebviRsx19VHuSgXVE5x_uXW9Wg4W4g&redirect_uri=https%3A%2F%2Fpinafore.social%2Fsettings%2Finstances%2Fadd&response_type=code&scope=read%20write%20follow%20push)[33fa4e02-0890-46e2-9fce-481973132eac] method=GET path=/oauth/authorize format=html controller=Oauth::AuthorizationsController action=new status=302 duration=3.83 view=0.00 db=0.00 location=https://mastodon/auth/sign_in
bundle[35626]: [Store Location] Reading stored location: user[Store Location] No locations storedRedirecting after sign in to nil[14bd6625-0bf6-4c29-bf2f-6663adc7d07c] method=POST path=/auth/auth/saml/callback format=html controller=Auth::OmniauthCallbacksController action=saml status=302 duration=108.55 view=0.00 db=28.58 location=https://mastodon/
bundle[35626]: [Store Location] Storing location for user(https://mastodon/)[4db7d264-d7c6-43d9-88e4-d479baa75a8d] method=GET path=/ format=html controller=HomeController action=index status=200 duration=127.06 view=97.09 db=19.70
bundle[35633]: [Store Location] Storing location for user(https://mastodon/)[0e08490e-d889-482d-932d-ff6414d0495f] method=GET path=/ format=*/* controller=HomeController action=index status=200 duration=74.79 view=52.08 db=8.14
```

I tried using pinafore.social to log in to the instance. But I get a very similar log.

**Comment by CSDUMMI** [comment]
Ok. I believe the cause of this issue might be: [``expire_data_after_sign_in!`](https://gitlab.com/CSDUMMI/devise/-/blob/main/lib/devise/controllers/sign_in_out.rb#L108).

This function removes all keys in the session after the login that start with `devise`

**Comment by CSDUMMI** [comment]
Although the location stored is called `user_return_to`.

**Comment by CSDUMMI** [comment]
I have found a hacky solution to this issue.

When you run this [fork of Mastodon](https://gitlab.com/babka_net/mastodon-babka) on the `redirect_to_idp` branch, you'll be redirected after a login to the site you previously visited.

I'll not be creating a PR for this solution yet, because I deem it too hacky.

Essentially what I do is this:
1. In my fork of [`gitlab-omniauth-openid-connect`](https://gitlab.com/CSDUMMI/gitlab-omniauth-openid-connect/-/blob/master/lib/omniauth/strategies/openid_connect.rb) I append the value currently stored in `session[:user_return_to]` as the value of a query parameter called `referrer` to the redirect uri passed to the SSO IdP.
2. In the Mastodon forks  omniauth callback controller this `referrer` parameter is taken and loaded into the stored location again.

This system works. I've tested it on my testing server, but I still believe that it is a hacky solution.

**Comment by CSDUMMI** [comment]
This branch also still contains a lot of extraneous logging that needs to be removed prior to any release.

**Comment by CSDUMMI** [comment]
Is this issue still valid on the current main branch? I fail to reproduce the issue now.

**Comment by Steffo99** [comment]
I shut down the instance I was using OAuth on, so I currently have no way to check. :(

**Comment by shamiv** [comment]
> Is this issue still valid on the current main branch? I fail to reproduce the issue now.

I am not sure, but the problem you discuss might be connected to what is discussed in this thread: https://social.edu.nl/@MishaVelthuis/109998529907767480

**Comment by CSDUMMI** [comment]
I've been able to reproduce this bug again. I'm working on a fix. It's difficult and I'm unsure whether I'll be able to solve it a) nicely and b) entirely in Mastodon. But if I'm unable to make a nice fix inside of Mastodon, I think I know a dirty fix inside of Mastodon and I'll create a PR for this within about 1-2 weeks.

**Comment by CSDUMMI** [comment]
Ok. It didn't take 2 weeks.

**Comment by CSDUMMI** [comment]
Can this issue be closed?
