### ISSUE TITLE
Get rid of filtered_languages?

### ISSUE THREAD

**Issue by marrus-sh** [mastodon/mastodon#18522]
### Pitch

After https://github.com/mastodon/mastodon/pull/7823 it doesn’t appear that the `filtered_languages` column in the user table is doing anything. Is there a reason it is still here? Can it be removed? It has been four years 🙂.

### Motivation

It makes the codebase more confusing to have both `filtered_languages` and `chosen_languages` in the user model when only one of those is actually used.

**Comment by ClearlyClaire** [comment]
That indeed sounds like an oversight
