### ISSUE TITLE
Docker Deployment on DockerHub

### ISSUE THREAD

**Issue by patchint** [mastodon/mastodon#18532]
On our Mastodon instance we use Watchtower to automatize updates for Docker containers.

We got a downgrade of our Mastodon instance v3.5.2 -> v3.4.8

We make this issue for all people getting this bug just by the fault of developpers who are pushing the wrong version on the latest tag.

Change the tag latest to v3.5.2 to get the last versions available on DockerHub for all containers are using the tootsuite/mastodon image.

**Comment by Gargron** [comment]
I don't know what watchtower is but I think updating to the `latest` tag automatically is considered an anti-pattern.

The `latest` tag is set to the latest stable version pushed. Today we released two: 3.4.8 and 3.5.3, in this order.

When 3.5.3 finished building, it became `latest`.

**Comment by theo546** [comment]
Hey, is there any way to get a "stable" branch with only the latest stable (ex: 3.5.3) version being pushed on it and a "back ports" branch with the old stable version with backported fixes (ex: 3.4.8)?
