### ISSUE TITLE
Add lang tag to timeline posts for screen readers

### ISSUE THREAD

**Issue by gunchleoc** [mastodon/mastodon#18542]
### Pitch

Now that we can select the language per post, it would be good to have an HTML lag tag per post too.

I am attaching a screenshot from the inspected HTML with the 2 rows highlighted where I think it should probably go, to have it on the post's text as well as the media alt labels

![mastodon_no_language_code_label](https://user-images.githubusercontent.com/4095570/170778133-ac22560c-6fc2-4624-b563-4b5fd4f90cfc.png)

### Motivation

Help people with multilingual timelines who depend on screen readers

**Comment by tribela** [comment]
Related: #12124, #10930
