### ISSUE TITLE
Use ISO-639-conforming language codes for per-toot-language interface

### ISSUE THREAD

**Issue by Wuzzy2** [mastodon/mastodon#18549]
### Pitch

(This is a follow-up of #17073.)

Currently, the recently-added per-toot language UI uses non-standard language codes. It's in all-capes. However, ISO-639, *the* standard for language codes uses lower-case. For example, it shows "EN" for English although "en" would be correct.

I'm not sure which standard is used for the language codes currently shown in the UI, but if I would guess, it's literally ISO-639, but converted to upper-case for some reason.

### Motivation

Conforming to ISO-639 just makes sense to me. If uppercase was chosen because "it looks better", that's a poor argument IMHO. The ISO standard is case-sensitive. Also note that there is another popular ISO standard for country codes, and it is in upper case, so this is definitely a source of confusion.

Just sticking to ISO-639 and not do some arbitrary modifications to it reduces confusion.

**Comment by Wuzzy2** [comment]
Since that was closed as completed, may I ask which commit(s) contain(s) this change?

**Comment by nightpool** [comment]
The idea that "Upper case means country code and lower case means language code" appears to be a complete invention with no basis in actual usage or specification text. The drop-down uses the full native names of the languages, there is no confusion here between language code and country code.

**Comment by Wuzzy2** [comment]
So apparently, ISO *recommends* to use lower-case but they also say these codes are case-insensitive.

https://www.loc.gov/standards/iso639-2/faq.html#21

So I guess whether to choose lower or upper case is a matter of taste then, I guess?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mastodon/mastodon/issues/18549#issuecomment-1140871368

@mro, a reason *to* adhere to the recommendation is that it makes variants (like `eng-GBR-oxendict-fonipa` for Oxford Dictionary-standard English in IPA format) possible. Otherwise, `GBR` could be a variant of `eng`. When you have both `eng-GBR-fonipa` and `eng-fonipa`, this becomes a problem.
