### ISSUE TITLE
Right column menu contents and way to access it

### ISSUE THREAD

**Issue by nclm** [mastodon/mastodon#1856]
This is a follow-up of #262 and #641.

The former was the bug leading to the creation of the current navigation menu as the initial state of the right column. However, the piece to go back to it (either with a X button or by designing it as an unfoldable menu) wasn’t implemented. The only element in the current interface offering this feature is the asterisk icon, located at the other end of the screen. The latter issue, unimplemented, answered this by reorganising the navigation options between the left column icons and the right column menu.

Here’s a new mock-up that resolves the situation **with a minimum number of changes**. It’s probably not optimal and soon enough a overhaul of the consistency of the interface could be a welcome move. But for now:

_Update: better option in a message below!_

**Screen 1**
* All links opening in the right column have been moved/confined to the right column menu. All links opening externally have been moved/confined to the left column icons.
* Unrelated: also contains versions of #1829 and #1249.

![ui1-a](https://cloud.githubusercontent.com/assets/923008/25064584/555ef71a-21fd-11e7-81e0-fb8bd7acea1a.png)

**Screen 2**
* When something is opened (here the local timeline) in the right column, the asterisk icon stays in the title bar. It allows the user to go back to the menu (i.e. the “Getting started screen”, or a possible new name depending of #1850).

![ui1-b](https://cloud.githubusercontent.com/assets/923008/25064583/555e191c-21fd-11e7-9da5-590f059968e5.png)

**Comment by nclm** [comment]
Much simpler solution, based on the menu version of my #262 sketch, which reuses the drop-down menu element already in use for contextual settings in other columns, and ends the confusion about “Getting started” being at the same time the menu and the content behind it (see #1850).

“Getting started” is now the content, the navigation list is now an independent menu. It is simply opened by default when “Getting started” is loaded at log-in, but it can be opened and closed in any situation.

![ui2-all](https://cloud.githubusercontent.com/assets/923008/25065151/fdc5d1ce-2209-11e7-84c9-2166538611c9.png)

(**Left to right:** “Getting started” with menu opened by default, local timeline with menu closed, local timeline with menu opened)

**Comment by nclm** [comment]
Remaining questions:
* What icon for the menu? A standard hamburger or list (as here) icon, or something more memorable to say “That’s where you should look for navigating this column”, evaluate its discoverability.
* Define more precisely “opened by default when ‘Getting started’ is loaded at log-in”, think of cases in which the menu has to be opened by default at loading.
* Improve the content of the “Getting started” screen for it to be helpful, but that’s another bug.

**Comment by elioqoshi** [comment]
Really like UX solutions proposed here! I see the screens show the columns as full width for the whole screen. I would think that this might be a good solution, as right now, 1/5th of the width is unused on the right.
