### ISSUE TITLE
3.5.x Update Instructions Missing Incremental Steps

### ISSUE THREAD

**Issue by fnufu** [mastodon/mastodon#18564]
### Steps to reproduce the problem

1. Try to update to 3.5.3 from 3.5.1 version while missing out 3.5.2 following the instructions given in 3.5.3 ONLY

### Expected behaviour

Sufficient Update Instructions in every minor Update OR note to read and follow every incremental update note OR fix update process to handle these steps by executing scripts

### Actual behaviour

Update failed because of missed db migration steps due to insufficient documentation of the incremental character of updates

### Specifications

3.4.x documentation mentions "If you are upgrading directly from an earlier release, please carefully read the upgrade notes for the skipped releases as well, as they often require extra steps such as database migrations or dependency updates."
3.5.x documentation no longer has this note

**Comment by ClearlyClaire** [comment]
Thanks for pointing that out, I re-added that text to the various release notes on the 3.5 branch.
