### ISSUE TITLE
EMAIL_DOMAIN_WHITELIST not effective when changing email

### ISSUE THREAD

**Issue by dorianim** [mastodon/mastodon#18620]
### Steps to reproduce the problem

1. Set the env variable EMAIL_DOMAIN_WHITELIST
2. Register as a user with a whitelisted domain
3. Change the email address of the user to a domain which is not whitelisted

### Expected behaviour

An error should be thrown, indicating that the domain is not allowed

### Actual behaviour

The user is allowed to change their email address to a domain which is not whitelisted

### Specifications

Version 3.5.3

**Comment by ClearlyClaire** [comment]
This is by design, see #10683

**Comment by dorianim** [comment]
I think it should at least be possible to enable that check. My use case is this:
We are running a server for our university and are only allowing @our-university.edu. Like this, we know who everybody is in case they post something illegal. When they are able to change their email, we don't know who they are anymore. 
Besides that, one person can register multiple accounts like that, and we don't want that either.

So I would appreciate a switch or environment variable to enable this behavior :)

**Comment by ClearlyClaire** [comment]
I agree. #18642 should handle that.
