### ISSUE TITLE
401 dereferencing AP replies collection with `replies?only_other_accounts=true&page=true` params

### ISSUE THREAD

**Issue by tsmethurst** [mastodon/mastodon#18638]
### Steps to reproduce the problem

From GoToSocial, my instance sends an http-signed request to (for example) `https://eldritch.cafe/users/AgathaSorceress/statuses/108459012240329285/replies?only_other_accounts=true&page=true`. This is an Unlisted post, and no block exists in either direction between the servers or the user doing the dereferencing, so my server should be able to obtain a Collection of replies. However, instead I get a 401 unauthorized error. The same is true in reverse; Mastodon instances dereferencing GoToSocial replies collections with params in the URL also receive a 401 unauthorized in response.

The reason for this is that Mastodon does not take account of URL query parameters in signing strings, wheres GoToSocial and some other AP implementations do. According to the HTTP Signature spec (or at least one of the linked RFCs in the spec), implementations should take account of URL query parameters by including them in outgoing signatures, and parsing them on incoming ones. (see https://datatracker.ietf.org/doc/html/draft-cavage-http-signatures-12#section-2.3 and especially https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.3). For better or worse, other AP implementations which use HTTP Signatures followed Mastodon's lead on this, and so the issue will be prevalent on other softwares as well.

### Expected behaviour

The query should return an ActivityPub Collection of URIs.

### Actual behaviour

401 unauthorized

### Specifications

GtS -> Mastodon issues happen exclusively with secure mode mastodon instances, which makes sense since they're the only ones that care about http signatures. Mastodon -> GtS issues happen regardless of Mastodon's secure mode setting, since GtS enforces authorized fetch always.

**Comment by tsmethurst** [comment]
Oh! I'm sorry, i didn't see you were already working on it: https://github.com/mastodon/mastodon/pull/18474

**Comment by renchap** [comment]
Fixed by #28476
