### ISSUE TITLE
https://ostatus.org/ is a Gambling Site

### ISSUE THREAD

**Issue by fireindark707** [mastodon/mastodon#18661]
### Steps to reproduce the problem

1. https://ostatus.org/ is in the head of all activitypub requests.

### Expected behaviour

Remove it

### Actual behaviour

Keep it in the header

### Specifications

3.5.2

**Comment by Gargron** [comment]
It’s a fake, inline namespace for compatibility with pre-2017 content. What’s on the domain is of no consequence to the code.
