### ISSUE TITLE
Accessing certain user pages returns a 500 error

### ISSUE THREAD

**Issue by Reticulmz** [mastodon/mastodon#18673]
### Steps to reproduce the problem

1. Access the user page of the user experiencing the problem
2. Receive HTTP 500 error

### Expected behaviour

User page displays correctly and can refer to the toot

### Actual behaviour

HTTP 500 error returned

### Specifications

stable-v3.5.0

**Comment by Reticulmz** [comment]
# Further information
#### Accessing https://sumanko.ml/@reticulmz spits out this error
`bundle[29128]: [de1d05ad-0751-4dc9-8dcb-ab0d34ee0ba3] method=GET path=/@reticulmz format=html controller=AccountsController action=show status=500 error='ActionView::Template::Error: undefined method video?' for nil:NilClass' duration=304.16 view=0.00 db=5.17
`

**Comment by ClearlyClaire** [comment]
Hi! I believe this was fixed by #18211, so you should update to v3.5.3. Are you using “tooot” by any chance?

**Comment by Reticulmz** [comment]
Thank you for your answer
I'm using subwaytooter.
I'll upgrade to v3.5.3.

**Comment by Reticulmz** [comment]
I updated to 3.5.3 and it fixed it, thank you!
