### ISSUE TITLE
embed piped videos

### ISSUE THREAD

**Issue by lucamp** [mastodon/mastodon#18701]
### Pitch

please embed [piped](https://piped.kavin.rocks/) videos so they can be played inside the timeline without having to open the link in another tab

### Motivation

Piped is a YouTube privacy oriented frontend that do not track users

[Piped Github](https://github.com/TeamPiped/Piped)
[Piped instance](https://piped.kavin.rocks/)

**Comment by realpixelcode** [comment]
You could use the [LibRedirect](https://github.com/libredirect/libredirect) browser addon for that. It loads embedded videos from Invidious.

**Comment by Gargron** [comment]
Mastodon embeds anything via the OEmbed standard. A website simply needs to have an OEmbed endpoint.
