### ISSUE TITLE
Report interface actions: duplicate actions

### ISSUE THREAD

**Issue by rixx** [mastodon/mastodon#18718]
### Steps to reproduce the problem

The report interface has a "quick actions" style list of actions to take against the reported user. It would be great if those action buttons indicated if they were useless. In particular, the **"Limit"** action is offered even when the user is already limited.

Additionally, even after pressing the button, there is no reaction to indicate what is going on: are limited users getting an additional notification? Did just nothing happen (while the moderator expected to take a siginificant action)?

### Expected behaviour

Don't show the button / show it greyed out indicating that the user is already limited.

### Actual behaviour

Button is available and gives no feedback after pressing it that anything is amiss.

### Specifications

v3.5.3

**Comment by uzorjchibuzor** [comment]
@rixx can I take this?

**Comment by rixx** [comment]
I only reported the bug, I don't know how issue assignments work in this project. I'd assume that you can just work on it and open a PR!

**Comment by uzorjchibuzor** [comment]
I guess I'd do that.

**Comment by ThisIsMissEm** [comment]
Are you meaning something like this?

<img width="869" alt="Screenshot 2024-09-05 at 03 55 10" src="https://github.com/user-attachments/assets/579d3590-50ce-490d-8b58-ebb73f015342">

**Comment by ThisIsMissEm** [comment]
Alternatively, we could hide it entirely.

(Though, I'm currently toying with an idea to do away with the quick-actions in favour of a dialog based flow, where you click "take action" and it pops up a modal on the page that's some sort of combination between custom and the predefined actions, so there's no page navigation involved — though this would need javascript, so would need to be done with progressive enhancement)
