### ISSUE TITLE
Integrate Libre Translate

### ISSUE THREAD

**Issue by raven9nine** [mastodon/mastodon#18738]
### Pitch

Integrate Libre Translate - a free, open source, self hosted language translation tool. https://libretranslate.com

### Motivation

If Libre Translate were integrated, when Mastodon users post in their own language, users from other countries could read their post translated into their languages. This could be automatic or by the use of a translate button on the gui.

**Comment by nemobis** [comment]
Does https://blog.mozilla.org/en/mozilla/local-translation-add-on-project-bergamot/ reduce the need for this?

**Comment by Gargron** [comment]
Added in #19218
