### ISSUE TITLE
Elasticsearch reponding with code 500 (class_cast_exception)

### ISSUE THREAD

**Issue by hllizi** [mastodon/mastodon#18747]
### Steps to reproduce the problem

1. get elasticsearch running and mastodon, too. (The actuall instance has been in use for some time without elasticsearch.)
2. use `tootctl search deploy` to set up elasticsearch.

### Expected behaviour

Indices Should be set up

### Actual behaviour

The enterprise fails with the error message: " __raise_transport_error': [500] {"error":{"root_cause":[{"type":"class_cast_exception","reason":"java.lang.Boolean cannot be cast to java.util.Map"}],"type":"class_cast_exception","reason":"java.lang.Boolean cannot be cast to java.util.Map"},"status":500} (Elasticsearch::Transport::Transport::Errors::InternalServerError)"

### Specifications

This should be fbcbf7898f000d9d1a21d52e8a8d3ed4602aa7db, i.e. v3.5.3

---

I am attaching the stack trace of tootctl. This appears a bit uninformative and gives me no idea about where the boolean value came from that was tried to cast to a Map. I found no instructions however on how to increase the verbosity of the output. If there is any means to do so, I'll be happy to produce more detailed data.

trace:

```
<mastodon-installation-path>/lib/ruby/gems/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/base.rb:218:in `__raise_transport_error': [500] {"error":{"root_cause":[{"type":"class_cast_exception","reason":"java.lang.Boolean cannot be cast to java.util.Map"}],"type":"class_cast_exception","reason":"java.lang.Boolean cannot be cast to java.util.Map"},"status":500} (Elasticsearch::Transport::Transport::Errors::InternalServerError)
	from <mastodon-installation-path>/lib/ruby/gems/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/base.rb:347:in `perform_request'
	from <mastodon-installation-path>/lib/ruby/gems/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
	from <mastodon-installation-path>/lib/ruby/gems/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/client.rb:192:in `perform_request'
	from <mastodon-installation-path>/lib/ruby/gems/3.0.0/gems/elasticsearch-api-7.13.3/lib/elasticsearch/api/namespace/common.rb:38:in `perform_request'
	from <mastodon-installation-path>/lib/ruby/gems/3.0.0/gems/elasticsearch-api-7.13.3/lib/elasticsearch/api/actions/indices/create.rb:48:in `create'
	from <mastodon-installation-path>/lib/ruby/gems/3.0.0/gems/chewy-7.2.4/lib/chewy/index/actions.rb:62:in `create!'
	from <mastodon-installation-path>/lib/ruby/gems/3.0.0/gems/chewy-7.2.4/lib/chewy/index/actions.rb:34:in `create'
	from <mastodon-installation-path>/lib/ruby/gems/3.0.0/gems/chewy-7.2.4/lib/chewy/index/actions.rb:116:in `purge'
	from /nix/store/3d01b0wlrc78i9sf46q9qbyxjzq7kzhg-mastodon-3.5.3/lib/mastodon/search_cli.rb:62:in `block in deploy'
	from /nix/store/3d01b0wlrc78i9sf46q9qbyxjzq7kzhg-mastodon-3.5.3/lib/mastodon/search_cli.rb:60:in `each'
	from /nix/store/3d01b0wlrc78i9sf46q9qbyxjzq7kzhg-mastodon-3.5.3/lib/mastodon/search_cli.rb:60:in `deploy'
	from <mastodon-installation-path>/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from <mastodon-installation-path>/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from <mastodon-installation-path>/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from <mastodon-installation-path>/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from <mastodon-installation-path>/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from <mastodon-installation-path>/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from <mastodon-installation-path>/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from <mastodon-installation-path>/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from <mastodon-installation-path>/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /etc/profiles/per-user/mastodon/bin/tootctl:8:in `<main>'
```

I'm on nixos btw. So if it helps I can provide my mastodon and elasticsearch modules.

**Comment by hllizi** [comment]
I'm on nixos btw. If it helps I can provide my mastodon and elasticsearch modules.

**Comment by ChvckN0rri5** [comment]
Same here. 

Commenting to follow. Logs are about the same.

**Comment by f0x52** [comment]
same here, makes setting up elasticsearch impossible

**Comment by f0x52** [comment]
Mastodon apparently only works with Elasticsearch 7, this should definitely be noted on https://docs.joinmastodon.org/admin/optional/elasticsearch/

**Comment by hllizi** [comment]
Great! Thanks a lot, that was it!

**Comment by hllizi** [comment]
Closed with solution: elasticsearch 7 required.

**Comment by TonyHoyle** [comment]
This is still an error on the mastodon docs.  

https://mastodon.gitbook.io/mastodon/admin/optional/elasticsearch explicitly installs elasticsearch 6.x which fails.

**Comment by progval** [comment]
@TonyHoyle The official guide (at https://docs.joinmastodon.org/admin/elasticsearch/) installs Elasticsearch 7.x
