### ISSUE TITLE
OCR fails to load and Tesseract errors in console

### ISSUE THREAD

**Issue by joenepraat** [mastodon/mastodon#18750]
### Steps to reproduce the problem

1. Upload an image with some text in the web-ui
2. Click 'Detect text from picture'
3. The text 'Preparing OCR' keeps showing 
4. In the browser console the following error message keeps showing:

`RuntimeError: abort(CompileError: call to WebAssembly.instantiate() blocked by CSP). Build with -s ASSERTIONS=1 for more info.            tesseract-core.wasm-e4db7f953ac7bcf9f67bd39031e42241.js:1:8515`

### Expected behaviour

Text should be detected

### Actual behaviour

Nothing happens and errors in browser console

### Specifications

Tested on three different Mastodon servers (incl. mastodon.social, all v3.5.3), on desktop (Linux Ubuntu 22.04 - latest Firefox, Chomium and Gnome Web) and on mobile (Android 11 - latest Firefox - via home wifi and mobile data).

**Comment by joenepraat** [comment]
Gnome Web had some extra errors. Maybe helpful.

![afbeelding](https://user-images.githubusercontent.com/41594439/176733985-57397e66-dbc7-4a83-a321-0b0c714d9b67.png)

**Comment by joenepraat** [comment]
Chromium's console output

![afbeelding](https://user-images.githubusercontent.com/41594439/176734919-a07ea6cc-91a6-4056-8b29-1f685a7d0f70.png)

**Comment by prplecake** [comment]
This seems relevant: https://connect.mozilla.org/t5/discussions/new-csp-enhancements-in-firefox-102/td-p/8816

**Comment by kleinesfilmroellchen** [comment]
This also happens with Chrome 104, see #19107
