### ISSUE TITLE
Appeals: Provide list and backlinks

### ISSUE THREAD

**Issue by rixx** [mastodon/mastodon#18761]
### Pitch

Currently, appeals are very hard to find for moderators – we have to keep track of the email notifications, or else there is no way to find the appeals page for an admin action again. 

I'd like to see two features here:

- Provide a list of appeals (with filters for pending/resolved), similar to the list of reports.
- On reports with an associated appeal, provide a link to this appeal. The appeal already contains a link to the "associated report" in the sidebar, and having the same connection in reverse would be helpful.

### Motivation

Emails with appeal notifications can get lost, and are also not the best way to keep track of open appeals when matters drag on for various reasons. Having an easy way in the UI to see a list of open appeals would help moderators make sure that nothing falls through the cracks.

**Comment by rixx** [comment]
Update: As of v4.0, there is a list of appeals. However, it's not accessible via the usual moderation interface, it's hidden on the admin dashboard.

**Comment by ThisIsMissEm** [comment]
Okay, this should be relatively easy to fix, it's another one like #26199 — so we'd just need to add a navigation item in Moderation for Appeals: `/admin/disputes/appeals`

**Comment by ThisIsMissEm** [comment]
Have opened this to address the missing navigation link: https://github.com/mastodon/mastodon/pull/31071

**Comment by ThisIsMissEm** [comment]
Fixing the report side of this issue will be more complicated, since we need to figure out "where" to include the link to the appeal

**Comment by ThisIsMissEm** [comment]
@ClearlyClaire this should perhaps be re-opened as there were two parts:
1) adding the missing navigation link
2) some sort of change to the reports to include information about the appeal

I think point 2 is probably harder to address, but still likely worth addressing.

**Comment by ThisIsMissEm** [comment]
Have opened https://github.com/mastodon/mastodon/issues/31461 for getting some form of "backlink" to the Appeal in the Report UI.
