### ISSUE TITLE
Uploading more than one video in a single toot fails with "Cannot attach a video to a post that already contains images"

### ISSUE THREAD

**Issue by vschweitzer** [mastodon/mastodon#18807]
### Steps to reproduce the problem

1. Log in to mastodon.social.
2. Create a new toot.
3. Attach >1 video files to that toot (in this case, two or more 10 second long MP4 videos, containing hevc/h265 video and AC3 audio).
4. Click "Publish!"
5. A popup will prompt "422 Cannot attach a video to a post that already contains images".

### Expected behaviour

As all attached files are videos, this error message should not appear.

### Actual behaviour

Publishing the toot fails with the aforementioned error message.

### Specifications

 - This issue has been encountered on mastodon.social on 2022-07-13 and has not yet been tested on any other instance.
 - The issue has occurred in both the API and web interface.
- All files with which this issue was reproduced were below 8MiB in size. 
- The issue has been reproduced with both h264 and h265 video.

Probes for the two files with which this issue appeared are as follows:
**File 1:**
```
Duration: 00:00:10.43, start: 0.000000, bitrate: 1781 kb/s
    Stream #0:0(und): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 1329 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 23.98 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1(side), fltp, 448 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Side data:
      audio service type: main
```

**File 2:**
```
Duration: 00:00:10.43, start: 10.427000, bitrate: 1327 kb/s
    Stream #0:0(und): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 875 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 23.98 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1(side), fltp, 448 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Side data:
      audio service type: main
```
I have left out metadata for these files, but can provide it and the files themselves if necessary.

**Comment by vschweitzer** [comment]
Stripping the audio stream off of all files "fixes" the issue. With audio, only one file at a time can be uploaded, without, multiple files are possible at once.

**Comment by Gargron** [comment]
You can only attach one video. You can attach multiple GIFs. Soundless videos count as GIFs.
