### ISSUE TITLE
Cannot find user role with that name

### ISSUE THREAD

**Issue by halmikami** [mastodon/mastodon#18813]
### Steps to reproduce the problem

1. su - mastodon
2. cd live
3. Type  RAILS_ENV=production bin/tootctl account modify username --role admin
4. Cannot find user role with that name

username is already exists

Another command works
eg) 
RAILS_ENV=production bundle exec bin/tootctl accounts create aaaa --email aaa@gmail.com
OK
New password: 9915dbb949afe8511bd05f538d14f251

### Expected behaviour

OK 

### Actual behaviour

Cannot find user role with that name

### Specifications

v3.5.3

**Comment by kellya** [comment]
I am here because I followed [the documentation](https://docs.joinmastodon.org/admin/setup/) and got the same error.  Specifying "Admin" works as expected.  It seems the documentation needs to specify "Admin"

**Comment by djdonnerwolke** [comment]
i had the same problem and it helped me. Thanks a lot!

**Comment by iferca** [comment]
I'm running `(HEAD detached at v4.0.0rc3)` and I'm getting this error with both lower and capital case role names. Any hint?

**Comment by TeeSee64** [comment]
same problem. after update to V4.0.2 i can login but I lost my admin rights. 

docker-compose run --rm web bin/tootctl accounts modify <username> --role Admin
does not work . error: Cannot find user role with that name

**Comment by fzorb** [comment]
> same problem. after update to V4.0.2 i can login but I lost my admin rights.
> 
> docker-compose run --rm web bin/tootctl accounts modify (my username) --role Admin does not work . error: Cannot find user role with that name

I get this too.

**Comment by jared252016** [comment]
Same issue, I was able to fix it by running: 

```
docker-compose run --rm web bundle exec rake db:seed
```

Then re-running the command to set the role.
