### ISSUE TITLE
Field for web admin and server maintainers

### ISSUE THREAD

**Issue by sjehuda** [mastodon/mastodon#18811]
### Pitch

The emali message below is missing an email address of owners or administrators
```
New email address

===

The email address for your account is being changed to:

email@address.info

If you did not change your email, it is likely that someone has gained access to your account. Please change your password immediately or contact the server admin if you're locked out of your account.

---

Mastodon hosted on mastodon.social
Change e-mail preferences: https://mastodon.social/settings/preferences
```

I ask myself...
Who's the server admin???
I see who's the administrator on the main mastodon page, but why is it not attached to the above message?
This is an exceptional case.

### Motivation

Assusming the scenario above actually occurs, I think it's best for user to have webadmin email attached to this urgent message, instead of looking up for it while being anxious.

**Email address for instance issues or problems is necessary to set on mastodon setup.**

**Comment by nemobis** [comment]
I don't understand this report. Are you saying that from the text of the email it's not clear enough that the message comes from the system itself, rather than from some random person?

**Comment by sjehuda** [comment]
> Are you saying that from the text of the email it's not clear enough that the message comes from the system itself, rather than from some random person?

No.

> Assusming the scenario above actually occurs, I think it's best for user to have webadmin email attached to this urgent message, instead of looking up for it while being anxious.

I think that this could be urgent to contact the admin(s) ASAP, so it would be good to have their email address (or a dedicate email address for urgent scenarios) in the email message itself.

I, for instance, want that email address to be available on a click, rather than looking up for the admin(s) when I might be under pressure.

**Comment by nemobis** [comment]
Il 21/10/22 09:59, Schimon Jehuda ha scritto:
> have their email address (or a dedicate email address for urgent scenarios) in the email message itself.
> 
> I, for instance, want that email address to be available on a click,

In short you'd like that string "contact the server admin" to be a link 
to the /about/more page, which contains the contact email?

**Comment by sjehuda** [comment]
On Fri, 21 Oct 2022 00:19:18 -0700
nemobis ***@***.***> wrote:

> Il 21/10/22 09:59, Schimon Jehuda ha scritto:
> > have their email address (or a dedicate email address for urgent
> > scenarios) in the email message itself.
> > 
> > I, for instance, want that email address to be available on a
> > click,  
> 
> In short you'd like that string "contact the server admin" to be a
> link to the /about/more page, which contains the contact email?
> 
> 

I want to see an administrator/moderator email address *in* the email
message, particularly in email messages concerning suspicious
behaviours.

**Comment by rixx** [comment]
Couldn't you just … reply to the email, instead?

**Comment by rixx** [comment]
Couldn't you just reply to the email instead? I feel like that's what email headers are there for.

**Comment by sjehuda** [comment]
On Tue, 30 Jan 2024 23:33:11 -0800
Tobias Kunze ***@***.***> wrote:

> Couldn't you just reply to the email instead? I feel like that's what
> email headers are there for.
> 

I suppose so.

I got emails from ***@***.***
Would ***@***.*** receive messages if sent?
Or perhaps write an email address to reply to in the message body.

Shall we close this ticket?

**Comment by sjehuda** [comment]
I wrote: notifications - at- mastodon.social

**Comment by rixx** [comment]
> Shall we close this ticket?

I'd say so. Providing contact details and making sure their email addresses work is what server admins should do; no software solution will fix that :)

**Comment by sjehuda** [comment]
Closing. Thank you @rixx
