### ISSUE TITLE
Custom CSS does not seem to work properly.

### ISSUE THREAD

**Issue by SurplusXoyo** [mastodon/mastodon#18820]
### Steps to reproduce the problem

The "" symbol in Custom CSS does not seem to be parsed correctly, thus becoming `&quot;` causing custom styles to fail.

This problem does not occur with the Latest version, but once you update to the edge version, the above error occurs.

### Expected behaviour

font-family:"Inter","Noto Serif SC","Noto Serif TC",sans-serif;

### Actual behaviour

font-family:`&quot;`

### Specifications

I only found this problem in the most recent version of edge, I'm not a professional program coder and after checking some files I took the liberty of thinking it was a bug in mastodon.

**Comment by tribela** [comment]
Fixed by #18824
