### ISSUE TITLE
Hashtag breaks in middle of word for "Hindi" language

### ISSUE THREAD

**Issue by ArshadSiddiqui** [mastodon/mastodon#18846]
### Steps to reproduce the problem

1. Open mastodon.social in web browser.
2. Create a post with content "#ग़लती"
3. Publish the post.
4. Open the created post.
...
<img width="742" alt="Screenshot 2022-07-19 at 7 55 20 PM" src="https://user-images.githubusercontent.com/11211568/179781896-f8e0a5c6-028a-412d-a24a-969d706c64f4.png">

### Expected behaviour

Hashtag should encompass all letters of the word

### Actual behaviour

Hashtag breaks in middle of the word (only first few letters are included in hashtag and rest of letter are not included)

### Specifications

Mastodon version: v3.5.3
Website: https://mastodon.social
Browser: Chrome, Firefox, Safari
OS: MacOS, Android

**Comment by ClearlyClaire** [comment]
This appears to be a regression from #18795, specifically those lines: https://github.com/mastodon/mastodon/pull/18795/files#diff-175888239adc2b81ed2e4e82f0ee0663be0677f376e1aa1d9151baa69596e546L27-R28
