### ISSUE TITLE
h-feed h-entry support

### ISSUE THREAD

**Issue by sjehuda** [mastodon/mastodon#18845]
### Pitch

h-feed is a simple, open format for publishing a stream or feed of h-entry posts, like complete posts on a home page or archive pages, or summaries or other brief lists of posts. h-feed is one of several open microformat draft standards suitable for embedding data in HTML.

https://microformats.org/wiki/h-feed
https://microformats.org/wiki/h-entry

### Motivation

Standard (better) retrival of information

I know Mastodon already provides RSS, feeds, yet this h-feed idea is worthwhile, especially when users who are not aware of the rss feed add to their news application a URL of profile, page or tag.

This actually can work for any page, and there's no need to program code specificaly for making an RSS feed for.

**Every page is subjected to be used for feed aggregation by end-user.**

P.S. Even the developer of feedparser python module is planning to support this https://github.com/kurtmckee/feedparser/issues/309#issuecomment-1184461650

**Comment by nightpool** [comment]
Mastodon already provides microformats markup

**Comment by sjehuda** [comment]
Thanks.
Please refer me to the code.
