### ISSUE TITLE
Backup Followers via API

### ISSUE THREAD

**Issue by RJGhugo** [mastodon/mastodon#18860]
### Pitch

I use the [Account API](https://docs.joinmastodon.org/methods/accounts/) to make the **backup** of my following accounts.

The default limit is 40.

### Motivation

For backing up followers I do not want to find out, in advance, how many following accounts I have to backup.

curl "https://mastodon.example.com/api/v1/accounts/"$id"/following?limit=100" -H "Authorization: Bearer "${bearer[$i]}"" > "$backup_pfad""/""${konto[$i]}"".following"

**Comment by Gargron** [comment]
Use Import and Export -> CSV to download a list of your followed accounts or paginate through the API.
