### ISSUE TITLE
Active user counts should not count banned users

### ISSUE THREAD

**Issue by austinhuang0131** [mastodon/mastodon#18861]
### Pitch

Active user counts (monthly/MAU on the landing page, or weekly in `/api/v1/instance/activity`) should not count banned users.

### Motivation

Spam registrations (particularly from SEO companies) massively inflate (current) MAU count which misleads new users

**Comment by Gargron** [comment]
The MAU is kept in a HyperLogLog data structure to provide a unique count. It cannot be decremented.
