### ISSUE TITLE
Alternative moderation notification channels (discord, Slack, etc)

### ISSUE THREAD

**Issue by offbyone** [mastodon/mastodon#18879]
### Pitch

I would like to have Mastodon deliver moderation request notifications to channels other than email. At minimum, I should be able to link my Mastodon instance to a discord channel (public or private) or a Slack channel (same characteristics) but ideally it could be integrated into any public event bus that would then render the moderation request for eventual notification and possibly resolution.

This is related to, but not quite the same as #15324, which aims to surface moderation _decisions_; in this case, I want moderation _requests_ to be distributed to a moderator interface other than email. I refer to it because I suspect that the plumbing would end up being similar.

### Motivation

Mainly... I want the ability to have moderation requests surfaced into an interface suitable for discussion of the request without having to refer to emails. I want a notification to come when a request arrives, _and_ to have that notification automatically updated when the request is handled, so that there's a clear view of the actions taken on a moderation _team_, without the need to drill into the moderation interface to confirm.

**Comment by Gargron** [comment]
You can connect it to whatever service you want through webhooks.

**Comment by offbyone** [comment]
#8890?

That would work fine, sure

**Comment by ThisIsMissEm** [comment]
@offbyone so this can be closed as completed then?

**Comment by offbyone** [comment]
Yup!
