### ISSUE TITLE
.gay domains are not regex'd correctly

### ISSUE THREAD

**Issue by AverytheFurry** [mastodon/mastodon#18890]
### Steps to reproduce the problem

1. Post a link to a .gay domain (https://example.gay/)
2. Post a link to a .com domain (https://example.com/)
3. Observe that the .gay domain is not properly converted to link format.

### Expected behaviour

I expect the domain to be shortened (hiding https:// and /) and clickable (clicking redirects to the link)

### Actual behaviour

This did not happen

### Specifications

Mastodon v3.0.1
https://github.com/witcheslive/mastodon (Instance)
Artix Linux (client)

**Comment by Gargron** [comment]
3.0.1 is 2 years old at this point. I can make no guarantee about it. If the issue occurs in the latest version, feel free to reopen

**Comment by viasux** [comment]
> 3.0.1 is 2 years old at this point. I can make no guarantee about it. If the issue occurs in the latest version, feel free to reopen

LOL didn't realize that! I'll ask the instance admins why the server is on a 2 year old version xd
