### ISSUE TITLE
Admin group has no permission to PG Hero and Sidekiq page

### ISSUE THREAD

**Issue by mashirozx** [mastodon/mastodon#18904]
### Steps to reproduce the problem

1. visit these pages with admin user

### Expected behaviour

see the page or can add devops permission for role Admin 

### Actual behaviour

The page you are looking for isn't here.

### Specifications

76ff45230630c32dd01fd45c89557e092a81b27f

**Comment by Gargron** [comment]
You need the Owner role for that
