### ISSUE TITLE
Max pined post limited

### ISSUE THREAD

**Issue by clovfr** [mastodon/mastodon#18938]
### Steps to reproduce the problem

1. Pin note
2. Pin note
3. Delete Pined note (without unpining it)
4. Pin note: Error 422

### Expected behaviour

Infinite quantity of Notes can be pined

### Actual behaviour

Pining post is limited and Thumbstones apparently still use a slot

### Specifications

Linux/5.18.14-1-MANJARO, Firefox/103.0, WebUI extended

**Comment by ClearlyClaire** [comment]
Deleting a post happens in multiple steps:
1. marking the post as deleted/inaccessible, this prevents directly accessing it but does not remove associated data, or send the deletion message around
2. the deletion message is sent around and the associated data is deleted
3. the post itself is deleted. In most cases, this happens at the same time as 2

In most cases, all of the three steps are performed in quick succession, although only the first step is guaranteed to be performed by the time the API call returns. Currently, removing pinned posts occurs in step 3, which may be further postponed if the post has been reported. I think we should handle removing the pinned post information in step 2 or possibly in step 1 as it should be a cheap operation.
