### ISSUE TITLE
 Mastodon can't just choose to not show markdown anymore.

### ISSUE THREAD

**Issue by Freeplayg** [mastodon/mastodon#18958]
### Pitch

**At least** showing markdown from other instances.

**TO CLARIFY: Currently, Mastodon strips away any markdown used from other servers and fediverse platforms. This is an issue.**

Example post with markdown: https://i.calckey.cloud/notes/991jrz6bm2
![image](https://user-images.githubusercontent.com/40742947/213543835-9a471185-9a81-4e82-b2bb-7a5cdab91c22.png)

That same post when viewed from Mastodon: https://mastodon.coffee/@freeplay@i.calckey.cloud/109553057990730094
![image](https://user-images.githubusercontent.com/40742947/213543989-fac3cd1d-ed4c-4a69-9421-31edc30b5bf9.png)

### Motivation

Mastodon is the biggest Fediverse platform. And with 99% of other Fediverse platforms (including Mastodon's derivatives/forks) already supporting basic markdown, so much information gets lost. Bold, italics, etc. have so much meaning and can dramatically change how a sentence is read.

Not even blockquotes are visible on Mastodon, it's all just plain text. How am I supposed to know that it's a quote? You can't.

I love this platform, and don't want these disconnects between them. It doesn't matter if you just don't like it. You can't just choose to not add it anymore.

**Comment by arittner** [comment]
I agree and technically it's possible, because the message content is already HTML. Links, hashtags, and emoticons are rendered as HTML, managed by Mastodon.

**Comment by Cassolotl** [comment]
I said this when it came around years ago, but yeah, I absolutely agree. If they don't want to add the ability to *use* markdown in Mastodon posts, fair enough - but at least show incoming posts correctly, come on!!

**Comment by trwnh** [comment]
Duplicate of #15311 and #15554

**Comment by dwbit** [comment]
Not sure if there is a better issue to add this feedback to, but just finished setting up a PeerTube and noticed that markdown from VIdeo/channel bio is not supported when searching/viewing accounts in Mastodon, which gives it a spammy appearance.

**Comment by foreverxml** [comment]
Not showing incoming posts correctly, is, like, a *very* big issue. I think Mastodon needs to gather itself and implement formatting rendering *at the minimum*.

**Comment by shleeable** [comment]
I'm going to release the stats from a small survey of instance admins, but 70% of them want rich text... so I think this argument is kind of over.

Regardless of simply adding it for compatibility reasons with other AP software.

**Comment by mashirozx** [comment]
Try markdown here! https://littlefo.rest

**Comment by tsmethurst** [comment]
IIRC proper display of a larger range of html elements on incoming posts is already implemented in Glitch, so presumably this could be pulled/adapted relatively easily from there :thinking:

**Comment by Hund** [comment]
If we see support for this, it would be a good idea to add an option to disable it as well. It should cause any drama for the people who doesn't like Markdown. Not that I understand why anyone wouldn't like it.

**Comment by Reedyn** [comment]
> If we see support for this, it would be a good idea to add an option to disable it as well. It should cause any drama for the people who doesn't like Markdown. Not that I understand why anyone wouldn't like it.

having an option to disable posting via markdown would be a good idea, but as someone posted previously in this issue mastodon should always display formatting when there is formatting and that shouldn't be possible to disable.

**Comment by shleeable** [comment]
Depends if you think Mastodon should follow the https://misskey.io/mfm-cheat-sheet style?

or something similar to slack
![image](https://user-images.githubusercontent.com/17537000/185286437-3f3c31ab-f734-4316-b3dd-4d369e29621b.png)

**Comment by xxxserxxx** [comment]
It's worth at least discussing a watered-down version of Markdown, such a [Gemtext](https://gemini.circumlunar.space/docs/gemtext.gmi). Supporting a subset designed to be programmatically trivial to parse and render has advantages for broad adoption: it makes it easier for implementers, and keeps clients fast and light.

**Comment by Sly-Little-Fox** [comment]
Actually, not adding Markdown is just stupid. The only thing needed to do is to find a good markdown => html renderer. Gemtext, which xxxserxxx suggested, seems fine as we don't need full Markdown. I think something like Discord's Markdown subset will be fine.

**Comment by tastytea** [comment]
See also: `https://github.com/mastodon/mastodon/pull/10787` and the pull request linked within.

Looks like the main hindrance for this feature is rude people polluting the pull requests. Anyone opening a pull request for Markdown/Rich text support can expect a shitshow. Would you wanna put up with that?

**Comment by Freeplayg** [comment]
I've realized that one of the great things about Fediverse is that you can also follow blogs, which are **even more likely to have blockquotes, bolding, etc.** And you usually can't see that when viewing from Mastodon...

**Comment by robsonsobral** [comment]
Gemtext, MissKey and every syntax else aside, I think the best to do is:

- allow a subset of Markdown only;
- respect CommonMark Specification.

Anything other than that could charge a huge price in the future.

Lists and paragraphs on Markdown are so intuitive that my clients/users think it's a "default thing". Others features are easy to learn and... Being clear, I've no idea how Brazilians non-tech learned that `~~` means `<del>`, but I've seen it from time to time!

**Comment by eishiya** [comment]
Thirding(?) the suggestion to let users set whether their posts should be parsed as MD or not. A lot text emotes like \*_\* and \~\*e-glitter\*\~ and things like \*doing actions with asterisks\* also use the same symbols as MD and escaping them is annoying and easy to forget. I use Discord and that has forced Markdown, and I'm tired of some of my posts consisting of 20% backslashes, and frequently requiring editing xP I'm also tired of seeing posts using \*actions\* made by people who don't know/care that they can escape their asterisks and avoid their \*actions\* blending with surrounding text.

If Mastodon manages posts in HTML though, I worry about MD play along with Editing posts. Would the HTML be converted back to MD for editing? Or did I misunderstand that part?

**Comment by robsonsobral** [comment]
As a first move, I would, parse MD on front-end. Then, we could change things further.

I admit I don't care about old posts being escaped, but I think it could enabled on new ones only to save you from the evil backslashes.

**Comment by robsonsobral** [comment]
> If Mastodon manages posts in HTML though, I worry about MD play along with Editing posts. Would the HTML be converted back to MD for editing? Or did I misunderstand that part?

I don't think user submitted data should be converted on saving, besides trim strings. The parsing should happens **after** data retrieval from database. Do you ever wanted to fight Microsoft Word for guessing what you're trying to do? Always better to respect the data. Trim, sanitize and save it. Nothing more.

---

I have seen a lot of people talking against text formatting on microblogging in here, and I understand their fear. What is a stream of thoughts can be trasnformed into somethign unreadable. Centuries ago, there was a social network called Orkut and god forbid humankind for what the colors, splashes and whistles have made to each others eyes.

However, design, calligraphy and formatting carry meaning. To say "__something__" isn't the same as "something":

> I've watched mother!

And:

> I've watched **mother!**

(Great [movie](https://www.themoviedb.org/movie/381283-mother) by the way!)

To write foreign words, sarcasm and titles in italics or bold; to signalize something is a quote, etc would improve the communication.

So, please, let's have it but in small doses.

**Comment by turtlegarden** [comment]
yes, as others have said, imo it would be good to parse basic markdown, e.g. links, bold, italic, code, codeblocks, headings, quotes, along with others like `<small>`, `<sup>`, `<sub>`. (less needed the further through the list)

**Comment by robsonsobral** [comment]
I don't even think we should have headings and small print for short texts. Links, superscript and subscript **could** be future improvements. **Could**. It all depends.

Let's start simple, please.

**Comment by jasonbyrne** [comment]
+++ Can we please have some basic formatting with Markdown? Especially code blocks IMO

**Comment by Sly-Little-Fox** [comment]
imo glitch-soc's implementation is the best

**Comment by Fordi** [comment]
* codeblock: which variant?  Four leading spaces, or triple backtick?  If leading spaces, do we support language highlighting?  Does "codeblock" include inline single-backtick? 

Examples:

        Four leading spaces

    ```
    Triple backtick
    ```

    ```markdown
    # Triple backtick
    
    * Now with language highlighting
    ```
    
    `inline`

```

**Comment by xxxserxxx** [comment]
There are better options than Markdown; Org-mode, for example, stays true to the origins of lightweight markup, which started as plain ASCII email conventions that mimicked what typewriters output. It's quite a full standard, though, and arguably overkill for a 500-character microblogging platform.

I argue for a minimal, well-defined subset that conveys the markup even without rendering. It would satisfy many objectives: less load on clients (they can choose to not render), more diversity in target platforms (it doesn't lock out console viewers), and better accessibility (@fordi).

Markdown is the dominant markup, although it has a strong allegience to the web and HTML, which makes it less than ideal for (e.g.) terminal clients. CommanMark includes [HTML Blocks](https://spec.commonmark.org/0.30/#html-block) in the spec, so choosing CommonMark would essentially bind Mastodon to the web.

Many markup languages value disambiguity over consiceness. It's common to choose double-characters for markup so the renderer has no (well, less) doubt as to whether the characters are markup or verbatim; this works against a microblog where every character counts against a character budget. Again, Org-mode or Textile opt for single-character markup, and would be better choices to build on.

The world may not need [yet another lightweight markup language](https://en.wikipedia.org/wiki/Lightweight_markup_language), but the existing ones are weighted to a specific render case (wiki, web pages) or attempt to be full featured (tables, todo checkboxes, block renderers) -- the latter case is probably the bigger issue -- so defining a new subset of some existing spec that minimizes markup might be a good path forward. Pick Org-mode or Textile, or Slack or Jira's markup and then whittle it down to the minimum set of supported markup.

The choice of base markup is important, but not as important as picking *something* and documenting it as the "official" markup.  IMHO.

**Comment by jasonbyrne** [comment]
@Fordi  @xxxserxxx 

I'd advocate for Markdown--or at least a subset of Markdown--because it is pretty concise, easy to read even when it's not parsed and formatted, and it is very well known. 

You can do use backticks on Medium blog or Slack messages, for example. It's very common and, therefore, will be very intuitive for many people (at least the target audience).

Both inline and codeblocks are necessary, in my opinion.

**Comment by jasonbyrne** [comment]
I'd think any code highlighting would be optionally added by the client. But, in order to support that, you would want the ability to add the language after the triple ```

**Comment by pauljacobson** [comment]
Another reason to support rich text formatting is to better support and prepare for federation with services that already use rich text formatting. One good example is Tumblr that is looking into adding ActivityPub support.

If/when that happens (whether it is Tumblr or other services), if Mastodon doesn't support at least common Markdown, Mastodon users will have a markedly (pun only partially intended) poorer experience compared to users on other services that do support rich text format.

A current example is [Micro.blog](https://micro.blog/) that supports Markdown and also supports ActivityPub.

**Comment by xxxserxxx** [comment]
> @Fordi @xxxserxxx
> 
> I'd advocate for Markdown--or at least a subset of Markdown--because it is pretty concise, easy to read even when it's not parsed and formatted, and it is very well known.

The author of [djot](https://github.com/jgm/djot) -- @jgm, the author of Pandoc -- provides a number of reasons based on his experience with adding commonmark support to Pandoc, on why you might want to **not** use Markdown:

- It's not parseable in linear time, requiring backtracking
- It's complex, with (e.g.) 17 special case rules for a parser to correctly interpret emphasis
- It's tightly coupled to HTML output

The [Rationale](https://github.com/jgm/djot#rationale) section explains this and more.

Since djot is based on CommonMark, it (or a subset) might be a good choice. If the decision to choose Markdown is based on an appeal-to-authority (it's popular because github is), then appealing the authority of @jgm -- who has far more experience with more markup languages than most people -- should carry some weight.

**Comment by Freeplayg** [comment]
I think my goal currently with this issue is just trying to get markdown to show from _other_ servers. And if people want to use markdown, they can use Fediverse software.

I just want it to be compatible with the rest of other Fediverse software, especially for things like, as I said before, blogs, articles, and other things that may have markdown

**Comment by tastytea** [comment]
> * It's complex, with (e.g.) 17 special case rules for a parser to correctly interpret emphasis

There are libraries for that.

> * It's tightly coupled to HTML output

Rich text is usually (always?) sent as HTML in the Fediverse, so that's not an issue.

> I think my goal currently with this issue is just trying to get markdown to show from _other_ servers. And if people want to use markdown themselves, they can use other Fediverse software.

Since incoming messages are formatted as HTML, it doesn't need Markdown support. A few changes in the “sanitizer” should be enough.

**Comment by Sly-Little-Fox** [comment]
> I think my goal currently with this issue is just trying to get markdown to show from _other_ servers. And if people want to use markdown themselves, they can use other Fediverse software.
> 
> I just want it to be compatible with the rest of other Fediverse software, especially for things like, as I said before, blogs, articles, and other things that may have markdown

Well, Glitch already implements that, we just need to convince them into PR'ing Markdown support into upstream...

**Comment by Freeplayg** [comment]
Updated issue to clarify & add an example

**Comment by woozalia** [comment]
In case it hasn't been noted: this is especially a problem with lists (<li> tag), which are (last I checked) rendered as a single long paragraph, no line-breaks. I have to take steps, when in Markdown mode, to avoid having my hand-numbered lists turned into ordered lists (<ol>), which vanilla Mastodon then strips down to an unnumbered paragraph blob.

**Comment by dertuxmalwieder** [comment]
> There are better options than Markdown; Org-mode, for example, stays true to the origins of lightweight markup

I support to have org-mode as another option. Markdown *does* have its quirks.

**Comment by McPringle** [comment]
Never heard of [org-mode](https://en.wikipedia.org/wiki/Org-mode) before. I would definitely go with Markdown, because MD is widely used and the syntax is known by many people. Of course, I would not support all MD features. I would use a subset only, e.g. bold/italic/lists/links.

**Comment by mcepl** [comment]
For better or worse (I would prefer [reStructuredText](https://en.wikipedia.org/wiki/ReStructuredText) myself) Markdown is not the dominant and “normal” markdown format especially for the casual notes, so that’s probably what we need to have.

**Comment by Shinigami92** [comment]
In the meantime of waiting for official support, you can start using https://elk.zone
We have Markdown support already but we are not fully feature complete with mastodon yet (v0.3.1) right now ^^

**Comment by dertuxmalwieder** [comment]
> I would definitely go with Markdown

There’s no reason for “either-or”. Why not both? :)

**Comment by dertuxmalwieder** [comment]
> Markdown is now the dominant and “normal” markdown format especially for the casual notes

A self-fulfilling prophecy - people use Markdown because that’s what software vendors provide. It could be a good idea to provide options.

**Comment by McPringle** [comment]
> It could be a good idea to provide options.

In my opinion multiple options would add unnecessary complexity, both in implementation / support by clients and in usability. It should be kept simple and easy. We can like it or not, Markdown is very wide spread and known by so many people, that it should be considered "standard".

If someone has used tools like Wikipedia, GitHub, Notion, Twitter (!), etc. before and comes to Mastodon, he would naturally try MD syntax to format messages. I see this every day in my timeline, when there are posts scrolling by using * and ** etc.

**Comment by dertuxmalwieder** [comment]
> If someone has used tools like Wikipedia, GitHub, Notion, Twitter (!), etc. before and comes to Mastodon, he would naturally try MD syntax to format messages.

If someone has used GNU Emacs for too long, org-mode is a natural choice as well. ;-) "Trying MD" is not as easy as it sounds, as there is a wide variety of "almost compatible" Markdown standards which support different features. Which Markdown dialect would you want to use and why?

(It might even be a good idea to add a formatting toolbar to prevent ambiguities; but then again, org-mode would work.)

**Comment by tastytea** [comment]
> > If someone has used tools like Wikipedia, GitHub, Notion, Twitter (!), etc. before and comes to Mastodon, he would naturally try MD syntax to format messages.

Perhaps more relevant, all the other Fediverse software that supports rich text, including Mastodon forks, use Markdown (some also allow HTML and/or bbcode).

> "Trying MD" is not as easy as it sounds, as there is a wide variety of "almost compatible" Markdown standards which support different features. Which Markdown dialect would you want to use and why?

To my knowledge, there is no Markdown dialect that do the basics like `*emphasized*`, `**strong**`, \`code\`, `* lists` and `> quotes` differently. Some support `~~strikethrough~~`, some do not. There are slight differences in how newlines are treated and how to force a newline. Most differences are with the more advanced features, that are probably not relevant to Mastodon.

Markdown has a [de-facto spec](https://spec.commonmark.org/0.30/) now that most people use.

**Comment by arittner** [comment]
I understand these religious-seeming discussions about the best markup language for formatting and surely there is the best in the world for every purpose.

But honestly, we're talking about Mastodon with 500 character message limit.

What do we need? Bold, italic, underlined, and maybe strikethrough. In addition, ordered and unordered lists. And with lists, I'm not sure if they need multiple levels. Oh yes headlines are maybe useful (but not more than 2 levels?!). And with headlines and orded lists we go into the complicated area. (headlines and hashtags, in Plume it's solved with a space between the hash and the headline Text; markdown ordered lists are numbers and maybe a user don't like formatting in this case). 

I don't think with this set of formatting we need to discuss whether another markup language is better than Markdown, nor whether there are too many parsing problems with Markdown.

Rather, it would make sense to enforce the feature at all with a simple suggestion. Do not already discuss a golden castle in the air, which is then never implemented under many other important features, because of too much complexity.

Look, even quoted boosts are now considered by @Gargron not impossible. So let's not make it completely impossible with unnecessarily complex requirements.

**Comment by mcepl** [comment]
> A self-fulfilling prophecy - people use Markdown because that’s what software vendors provide. It could be a good idea to provide options.

You may not like it, but that’s how the world works. You may like `bazaar`, Mercurial, `svn` or something more weird (`fossil SCM`, `darcs`?), but the universe spoke and the answer is `git`, whether you like it or not. The same goes for many other parts of the software universe, it has tendency to settle on monopoly unless some serious reason applies.

**Comment by dertuxmalwieder** [comment]
The universe has no power to decide which technical solutions *I* prefer to use. (Indeed, I use several of those you named.) Neither does the fact that GitHub uses a version of Markdown necessarily make Mastodon have to use Markdown as well. Different platforms require different solutions. BBCode was already mentioned, and, as Mastodon is more like a web forum than like a collection of READMEs, it would be a logical choice as well.

I never suggested to use Org **instead** of Markdown. There is no harm in having both though.

**Comment by jubalfh** [comment]
@dertuxmalwieder are you volunteering to maintain the org mode support in mastodon for the next five years? because there is more than one reasonably well-maintained markdown processor for ruby, and there are existing mastodon forks that support markdown messages.

**Comment by dertuxmalwieder** [comment]
Forks of this repository are not relevant within the scope of this issue tracker. How many processors do you need?

**Comment by McPringle** [comment]
> Forks of this repository are not relevant within the scope of this issue tracker.

Generally yes, but in the case of this issue I have a different opinion. We are talking about formatted messages and should always keep in mind that Mastodon is only *one* client in the *Fediverse*. There are many more clients out there. And all clients that I know that support formatting of messages (e.g. PeerTube), they all support Markdown. Some support a subset of HTML, too. None supports bbcode, org-mode, etc.

You may not like it, but since a few years Markdown is a *de-facto-standard* for formatting text messages. Therefore, in my opinion we should use the most widely supported option. If we go with bbcode or org-mode or something else, I'm pretty sure this will not be supported by (most) of the other clients which will make reading messages for their users unnecessary ugly. And if a Mastodon user receives a MD formatted message, it won't be nice either. Exchanging formatted messages will be a mess. Users will complain and it will be very hard for them to understand the reason.

Please, everyone in this thread (including myself), think about the users and usability. Mastodon isn't a technical experiment anymore. We should not tackle this issue from a technical perspective or personal preferences.

Maybe having a vote on Mastodon could be a solution to pick the formatting option?

**Comment by arittner** [comment]
> Generally yes, but in the case of this issue I have a different opinion. We are talking about formatted messages and should always keep in mind that Mastodon is only one client in the Fediverse.

Maybe here is something unclear.

A Markdown syntax is only needed to parse the format wishes. The instance is able to change the format to HTML and all services in Fediverse are able to show it or filter it out. Also Mastodon filters HTML and shows most of a message in plain text.

So mastodon should parse the formatting options and should not filter anymore all HTML elements.

**Comment by dertuxmalwieder** [comment]
> Some people may not like it, but since a few years Markdown is a _de-facto-standard_ for formatting text messages.

It is *one* (number of) de-facto standards for formatting *a subset of* text messages.

> Maybe having a vote on Mastodon could be a solution to pick the formatting option?

I think the misunderstanding here is that you consider “options” and “the only option” equal. It was not my intention to only have *one* supported formatting option.

**Comment by Sly-Little-Fox** [comment]
> The universe has no power to decide which technical solutions _I_ prefer to use. (Indeed, I use(d) several of those you named.) Neither does the fact that GitHub uses a version of Markdown necessarily make Mastodon have to use Markdown as well. Different platforms require different solutions. BBCode was already mentioned, and, as Mastodon is more like a web forum than like a collection of READMEs, it would be a logical choice as well.
> 
> I never suggested to use Org **instead** of Markdown. There is no harm in having both though. Mastodon is a technical project, and “popularity” is not always the most important decision aspect in those.

BBCode is long, Markdown is shorter. Mastodon is for microblogging. Also, *there is already a fork of Mastodon which already implements everything*

**Comment by McPringle** [comment]
> I think the misunderstanding here is that you consider “options” and “the only option” equal. It was not my intention to only have _one_ supported formatting option.

Nope, I do not misunderstood it. In my opinion it does not make sense to implement multiple solutions for the same problem if the power of developers is limited. I would not stop you from contributing Org support. I would highly appreciate it. But in case the core team of Mastodon developers has to implement it, they should use the most easy solution known to a huge group of people with wide-spread support by other Fediverse clients.

We can't just demand everything that would be possible. Well, we can, but that doesn't make sense. For each demand, we should consider what makes sense in the respective context and also take into account the severely limited resources in terms of developer capacity in order to increase the likelihood of implementation. Mastodon is not Google. It can't throw dozens of developers at a project.

**Comment by TimothyRichardGreen** [comment]
Should this be split into two separate discussions? People are talking over each other.

1. Mastodon should stop stripping HTML on messages from other parts of the Fediverse. It should sanitize (otherwise it would allow XSS attacks), and perhaps simplify (stripping out colours or fonts, and embedded CSS or javascript, probably), but at least some formatting should be allowed through.
2. Mastodon should allow formatting itself, probably using a subset of CommonMark.

Those are two separate conversations, and having both at once is causing confusion. (For what it's worth, I'd vote yes on both of them.)

**Comment by dertuxmalwieder** [comment]
Good idea, actually. :-)

**Comment by spaceottercode** [comment]
Would be nice to have some level of support for the display and drafting of Markdown/commonmark. And should be possible to do incrementally. I mean to say, with display being addressed first, and only tackling a subset. But I think with time people will eventually want to replicate what they see. Eventually drafting facilities could help testing too. I just it's something we get to see/use on the official web interface too as opposed to 3rd party client apps only. 🤞

**Comment by ThatOneCalculator** [comment]
What about MFM? It's a Fediverse standard that already implements most markdown items, and is used on Misskey, Calckey, Akkoma, and more.

**Comment by VyrCossont** [comment]
> What about MFM? It's a markdown format that's already popular on the Fediverse and implements most markdown items, and is used on Misskey, Calckey, Akkoma, and more.

Why implement something with no spec, no Ruby implementation, and no user base outside of Misskey? The easiest option would be to merge Glitch's rendering implementation, since that's pretty well tested and widely deployed already.

**Comment by cam-rod** [comment]
> Why implement something with no spec, no Ruby implementation, and no user base outside of Misskey? The easiest option would be to merge Glitch's rendering implementation, since that's pretty well tested and widely deployed already.

It looks like Glitch uses Redcarpet, which isn't compatible with CommonMark (see vmg/redcarpet#429) and seems to be in maintenance mode. It might make sense to use something based on CommonMark (or flavours of it).

But using other components from Glitch would be great.

**Comment by McPringle** [comment]
> can mastodon just add old html tags like `<blink>` or `<marquee>` like i did on my site?

Hopefully not! 😱

**Comment by cam-rod** [comment]
Seeing that rich text support was added in #23913, this covers the core parts of Markdown:

- Bold, italics, strikethrough
- Ordered and unordered lists
- Blockquotes, inline code, and fenced code blocks
- Headers (formatted as bold text in separate paragraphs)

It basically fixes the original point of this issue. As for posting with Markdown, I've opened #23981 to continue that discussion.

**Comment by lime360** [comment]
> > can mastodon just add old html tags like `<blink>` or `<marquee>` like i did on my site?
> 
> Hopefully not! 😱

why not?
