### ISSUE TITLE
Presence of accentuation in hashtags

### ISSUE THREAD

**Issue by retiolus** [mastodon/mastodon#18962]
### Pitch

I don't know if this is a feature request or a bug, but it would be nice if hashtags could be considered equal when the word in it has an accent or not.

Example: #catala and #català are currently considered two different hashtags, it would be nice if Mastodon didn't differentiate between these two.

### Motivation

This is not the case with English, but many languages have accented words, so Mastodon's differentiation between, for example, #catala and #català often makes it very difficult to find content.

**Comment by Gargron** [comment]
Fixed in #18795
