### ISSUE TITLE
Email confirmation 

### ISSUE THREAD

**Issue by romainjak** [mastodon/mastodon#18968]
### Steps to reproduce the problem

1. Want to go in Mastodon network
2. selecting mastodon.social server 
3. Waiting for email confirmation

But nothing is coming after more than 6 hours
...

### Expected behaviour

Receiving the email confirmation 

### Actual behaviour

Not receiving email confirmation 

### Specifications

Mastodon app on Android phone

**Comment by living8bit** [comment]
I have the same issue on 'mastodon.social'.  Tried with a 'protonmail.com' address a while back, and today tried with my own server so I could monitor email logs.  Thought it may be firewall but need to know IPs of 'mastodon.social' email _sender_ to check.

**Comment by Gargron** [comment]
I am sorry you're having issues, but it's not an issue for this repository, which is for the software.
