### ISSUE TITLE
Add authorized fetch option into Mastodon admin graphical interface

### ISSUE THREAD

**Issue by FediVideos** [mastodon/mastodon#18971]
### Pitch

As far as I can tell, there is no way to switch on the "authorized fetch" option in the Mastodon admin graphical interface.

It would be nice if there was an "authorized fetch" option that people could toggle on and off, like any other Masto setting.

Akkoma (the recent Pleroma fork) has such a setting, maybe Masto could have something similar?

![akkoma](https://user-images.githubusercontent.com/75383929/184557707-3ca81d57-280f-41af-82de-1c8cc05a5670.png)

### Motivation

Having this option in the graphical interface would make it a lot easier for admins to switch this mode on, especially on managed hosting instances.

At the moment, managed hosting instances have to manually contact the hosting company to make changes to the mode. This is really cumbersome if people want to experiment with having this on or off, especially considering the competing safety and compatibility issues pulling admins in different directions.

**Comment by nightpool** [comment]
Generally, it is the responsibility of managed hosting providers to allow admins to configure instance options that are determined when the user installs the instance, including environment variables. The addition of UI elements to the admin interface is for non-technical options that may be configured by any user and don't impact the technical functionality of the instance, or are more complicated then environment variables easily support (like image uploads). If your hosting provider doesn't allow you to easily change Mastodon configuration variables, then you either need to ask them to implement that or find another hosting provider.
