### ISSUE TITLE
Remote user's avatar/header deletion is not affected

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon#18974]
### Steps to reproduce the problem

1. Delete user profile or header image from remote
2. Check that user on local
3. Even force update profile from admin interface
...

### Expected behaviour

Empty remote user's account or header 

### Actual behaviour

Not deleted

### Specifications

Mastodon v3.5.3

**Comment by ClearlyClaire** [comment]
Fixed by #18973?

**Comment by tribela** [comment]
> Fixed by #18973?

Jes. Fixed
