### ISSUE TITLE
How to edit published post

### ISSUE THREAD

**Issue by Ygarr** [mastodon/mastodon#18995]
### Steps to reproduce the problem

1. create and publish
2. then try edit

### Expected behaviour

edit interface

### Actual behaviour

no shortcut to do this

### Specifications

Is it possible at all?
Need to convey information more accurate

**Comment by shleeable** [comment]
Editing posts is apparently going to be enabled in the next release.

There hasn't been much communication about it.

**Comment by ClearlyClaire** [comment]
There is currently no interface to edit posts. This is on purpose as to give servers time to catch up with the protocol changes. Furthermore, we still have to improve the edition interface, but this is planned!

**Comment by forenta** [comment]
> Editing posts is apparently going to be enabled in the next release.
> 
> There hasn't been much communication about it.

It has been announced for 3.5, what happend afterwards? Anyway, as long as we're waiting for this, you can use your Mastodon-account with [Soapbox FE](https://fe.soapbox.pub/) which supports the edit of toots.

**Comment by Gargron** [comment]
The API has been released in 3.5, the web app enables it in the imminent 4.0.

**Comment by forenta** [comment]
Thank you!
