### ISSUE TITLE
sidekiq: [FATAL] failed to allocate memory

### ISSUE THREAD

**Issue by HolgerHuo** [mastodon/mastodon#19010]
### Steps to reproduce the problem

1. spin up sidekiq processes with default and push queue

### Expected behaviour

sidekiq runs without crashing

### Actual behaviour

sidekiq crashed 3 times in 9 days

### Specifications

Mastodon 3.5.3 stable

I've set up mastodon sidekiq with 3 different processes with each of them runs default+push(128 threads) mailers+pull(128 threads) and scheduler(64 threads). The system normally runs under 10 Gigs of memory (30G total with no swap enabled). However, the one sidekiq process running default and push crashes frequently(the process normally runs with 1G of ram). There was some failed jobs like nxdomain when processing remote statuses and there was quite a few `Error storing media attachment: execution expired` (But this did not show up in retries or dead list when i look them up around 10 hours after sidekiq crashed, so im not sure if this error is related to the problem.)

So in my assumption, this sidekiq process eats at least another 20 gigs of memory before crashing and it didnt seem reasonable. Or should i specify the amount of memory allocated to sidekiq somewhere? Also, another thing to mention is that all other processes run without being affected at all.

**Comment by HolgerHuo** [comment]
I've added 8G swap (on NVMe storage) to my server and reduced each sidekiq process to 64 threads but this error persist.
Sidekiq log outputs nothing other than [FATAL]: failed to allocate memory.

It is very least likely that I've run out of memory, so are there any ways I can further investigate it?
Or should out-of-memory be the case, won't it be some internal memory leak?

**Comment by Gargron** [comment]
It could be ffmpeg/imagemagick that runs out of memory, and maybe it is due to an explicit limitation of how much memory they are allowed to use. I don't think Mastodon sets such limitations but they may be controlled by environment variables, system settings or jail processes.

**Comment by thegcat** [comment]
We also noticed rising memory consumption over time on the sidekiq side, though we haven't instrumented it in any way. Maybe adding something like https://github.com/klaxit/sidekiq-worker-killer would be enough for people to be able to configure sidekiq better for themselves?

**Comment by HolgerHuo** [comment]
> We also noticed rising memory consumption over time on the sidekiq side, though we haven't instrumented it in any way. Maybe adding something like https://github.com/klaxit/sidekiq-worker-killer would be enough for people to be able to configure sidekiq better for themselves?

We've instrumented our server and found that there are 10-20Gigs free mem at the time of crash, ruling out the possibility of OOM. We suspect that there are some compatibility issues with RHEL9 (we've tried both w/ or w/o jemalloc, and they produced same outcomes). The only clue to follow is that in some cases, sidekiq is crashed with a segment fault from blurhash gem. However, there don't seem to be other ppl reporting this issue, so ihni whether it is the real cause.

**Comment by vmstan** [comment]
Hi @HolgerHuo is this still an issue for you?

**Comment by HolgerHuo** [comment]
> Hi @HolgerHuo is this still an issue for you?

@vmstan Hi! I just checked and found all sidekiq queues running healthily for more than a month, and I think this issue no longer persists. Maybe an updated dependency fixed the issue. 

I didn't keep an eye on how it was resolved as although it keeps crashing, it didn't cause much trouble. Do you have the same issue?

Sorry for not having responded yesterday. Happy new year :-)
