### ISSUE TITLE
Redis is under high load when a domain block is created with reject_media.

### ISSUE THREAD

**Issue by abcang** [mastodon/mastodon#19060]
### Steps to reproduce the problem

1. Open `/admin/domain_blocks/new`
2. Check the "Reject media files" checkbox.
3. Create domain block

### Expected behaviour

CPU usage in redis is normal.

### Actual behaviour

CPU usage of redis becomes very high.

### Specifications

This is probably due to the use of `Rails.cache.delete_matched` since v3.2.0.
https://github.com/mastodon/mastodon/commit/89f40b6c3ec525b09d02f21e9b45276084167d8d

`Rails.cache.delete_matched` is not fast because it searches practically all keys and deletes the matched ones. And this is very time consuming and increases redis CPU usage because it repeats for the number of toots affected by the domain block. Also, the cache is deleted together at the end of the process, but if the time it takes to delete media is longer than the expiration date of the cache, the cache deletion process is not very useful.

Therefore, I believe the cache deletion process should be improved. The cache expiration time is a few tens of minutes and the cache hit rate seems to be low when deleting all of them, so I think it is a good idea to stop deleting the cache on a dare. If you are concerned about the cache, I think it is better to explicitly delete it with `Rails.cache.delete` instead of `Rails.cache.delete_matched`.

**Comment by ClearlyClaire** [comment]
The `delete_matched` call has been here since v2.3.0rc3: https://github.com/mastodon/mastodon/commit/64db9ed5f6c8ff826104b3294956416d08d7a135#diff-139f4fe1ac2db8106baae28695925cc0566b917a4b66f075f5086b9ea2cc9e0dR28

This indeed seems especially expensive… and looking into it I'm not even sure it matches *any* key. Wouldn't the key just be `statuses/#{id}` and not `statuses/#{id}-something`?

**Comment by abcang** [comment]
If you want to clear the cache by `cache_collection`, it would be better to use ActiveRecord cache keys like `Rails.cache.delete(status)` or `Rails.cache.delete(status.cache_key)`. If you want to clear the cache by `render_with_cache`, you may need to calculate the cache key.
