### ISSUE TITLE
minor sidekiq error

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#19077]
### Steps to reproduce the problem

class=ActivityPub::DeliveryWorker jid=3686a053636fb167d5bc17e5 WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["/opt/mastodon/app/lib/redis_configuration.rb:20:in `pool_size'", "/opt/mastodon/app/lib/redis_configuration.rb:15:in `pool'"]

### Expected behaviour

no error

### Actual behaviour

error

### Specifications

Main

**Comment by splacat** [comment]
Same warn here

**Comment by fuomag9** [comment]
Same warn here, still present
