### ISSUE TITLE
Disambiguate Emoji flags section

### ISSUE THREAD

**Issue by tdelmas** [mastodon/mastodon#1908]
In the flags section, some emoji need disambiguation:
For example:
🇨🇵 Clipperton Island - http://emojipedia.org/flag-for-clipperton-island/
🇫🇷 France - http://emojipedia.org/flag-for-france/
Display, depending of your font, the same Blue-White-red flag, or, "CP"/"FR".
And sadly, the CP version is often misused in the place of the french one.

Maybe a sorting of the flags could fix that, like sub-sections by continent?

https://apps.timwhitlock.info/emoji/tables/iso3166

**Comment by clement-analogue** [comment]
I don't know if it's related, but we have an issue with Tusky where the French flag is displayed as `C P` https://github.com/Vavassor/Tusky/issues/473

**Comment by nightpool** [comment]
this is an upstream issue w/ emoji-data

**Comment by mjankowski** [comment]
Closing on assumption (From last comment) that this is in upstream lib and out of our control.
