### ISSUE TITLE
Role tags missing from webui standard/advanced

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#19096]
### Steps to reproduce the problem

shown in public (3.5 public)
![image](https://user-images.githubusercontent.com/17537000/187341234-6b4ac259-e178-4645-9db7-6946abd4e56f.png)

missing in standard (4.0)
![image](https://user-images.githubusercontent.com/17537000/187341270-96c31d4c-59c0-40cf-bec5-3c507cad7bab.png)

missing in advanced(4.0)
![image](https://user-images.githubusercontent.com/17537000/187341307-9cf9f437-0ce7-4abc-98e5-74f1521928ed.png)

### Expected behaviour

Role tag on all views

### Actual behaviour

Role tag onto in the bad view

### Specifications

main

**Comment by vmstan** [comment]
Closed by #26281 and #25649
