### ISSUE TITLE
Automatic text extraction from images not possible on Chrome 104

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [mastodon/mastodon#19107]
### Steps to reproduce the problem

1. Through the web interface, upload an image for a toot.
2. Open the image focus & description editing window.
3. Click on "auto-detect text from image"

### Expected behaviour

OCR should happen normally.

### Actual behaviour

Interface freezes, OCR doesn't happen. The in-page window can and must be closed, after which it is possible to open it again and/or interact with the page normally.

### Specifications

The browser in use is Chrome 104.0.5112.102 on Windows 10 21H2. My instance's Mastodon version is 3.5.3.

## Further information:

A simple look into the developer tools gives a clear indication of why this happens:

![image](https://user-images.githubusercontent.com/28656157/188023125-6b228f88-429a-4918-ad08-3ee408c91b47.png)

From a quick web search, it appears that this can and must be changed by the website itself.

**Comment by ClearlyClaire** [comment]
This might be a duplicate of #18750

**Comment by kleinesfilmroellchen** [comment]
Yep it is; couldn't find it by searching.
