### ISSUE TITLE
nginxのservers設定ファイルを追加。

### ISSUE THREAD

**Issue by pooza** [mastodon/mastodon#19136]

**Comment by nightpool** [comment]
Configuration files for nginx can be found in the `dist` folder, as [mentioned in our official installation guide](https://docs.joinmastodon.org/admin/install/#:~:text=exit-,Setting%20up%20nginx,-Copy%20the%20configuration)

**Comment by pooza** [comment]
My apologies.
I accidentally registered an issue that should be in my fork repository.
