### ISSUE TITLE
Accessing Mastodon first after launching Vivaldi Browser opens in single-column UI

### ISSUE THREAD

**Issue by mimikun** [mastodon/mastodon#19186]
### Steps to reproduce the problem

1. Install Vivaldi Browser & setup
2. Enable advanced web interface
![Pasted image 20220918090149](https://user-images.githubusercontent.com/13450321/190880215-5ea105ce-3e18-4c8f-80be-05c5f178b0b7.png)
4. Close tab
5. Aceess Mastodon again
![Pasted image 20220918085956](https://user-images.githubusercontent.com/13450321/190880222-b5c46ddd-e956-4852-8651-03bb2fc52bcd.png)

### Expected behaviour

First access: Advanced UI

### Actual behaviour

First access: Single Column UI

### Specifications

- Mastodon: v3.5.3
- Browser: Vivaldi
- OS: Windows 10

**Comment by MitarashiDango** [comment]
This issue has been reproduced in the following versions.
- Vivaldi (5.4.2722.3)

However, it did not reproduce in the following versions.
- Vivaldi (5.4.2704.3)

I was able to reproduce the issue with the pattern below.
- Launch a new browser and directly enter the URL to access the page.
- Access by directly entering the URL in the URL bar of the tab that opens the web page of another domain.

When I checked the difference in behavior between the version that caused the problem and the version that didn't, I found a difference in the value returned by `window.innerWidth`.
The above properties are referenced below.

ref. https://github.com/mastodon/mastodon/blob/c55219efa811b3c6347774bec1b174d325e5f300/app/javascript/mastodon/is_mobile.js#L9

Vivaldi (5.4.2722.3)
- 0

Vivaldi (5.4.2704.3)
- browser inner width (example: 1280)

**Comment by lindwurm** [comment]
We've tested Vivaldi snapshot but;

- [5.4.2718.3](https://vivaldi.com/blog/desktop/always-secure-and-media-fixes-vivaldi-browser-snapshot-2718-3/) (2022.06.27) is ok
- [5.4.2733.3](https://vivaldi.com/blog/desktop/chromium-bump-and-accent-from-page-vivaldi-browser-snapshot-2722-3/)  (2022.06.30, bump Chromium version) is affected

I've submitted bug report to Vivaldi (and provided demo account from my instance, for testing purpose).

**Comment by Gargron** [comment]
window.innerWidth returning 0 sounds like a privacy protection measure.

**Comment by dstengele** [comment]
I am also running into this problem with 5.5.2805.42. Interestingly, this only seems to happen, when navigating to Mastodon in an existing tab. When opening e.g. a bookmark to Mastodon in a new tab, the advanced UI is correctly loaded instead.

**Comment by mimikun** [comment]
I updated to Mastodon v4.0.2 and this issue has been resolved.
Thanks!
Close this issue.
