### ISSUE TITLE
Saving a new filter from settings results in a 500 error

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#19187]
### Steps to reproduce the problem

1. Go to /filters
2. Create a new filter
3. Add a title, context, and keyword (FilterTest, home, FilterTest)
4. Click save

### Expected behaviour

You are taken back to the filter list

### Actual behaviour

500 error "We're sorry, but something went wrong on our end"

### Specifications

mastodon.social

**Comment by ClearlyClaire** [comment]
Probably a duplicate of #18742, I'm not sure how up to date mastodon.social is.

**Comment by trwnh** [comment]
Updated my dev instance and I'm not seeing it anymore, so probably!
