### ISSUE TITLE
API: instance_media_attachments measure returns empty values

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#19215]
### Steps to reproduce the problem

POST /api/v1/admin/measures with instance_media_attachments, then check value in each item of the data array

### Expected behaviour

at least show 0 bytes

### Actual behaviour

"" (empty string)

### Specifications

latest commits

**Comment by mjankowski** [comment]
These should be coalesced to zero as of https://github.com/mastodon/mastodon/pull/29415
