### ISSUE TITLE
[Solved] FF Bug upon loading /web/home

### ISSUE THREAD

**Issue by jayrope** [mastodon/mastodon#19228]
### Steps to reproduce the problem

1. Log in.

2. Error displays about a second after showing /web/home correctly, then showing error window instead as displayed in screenshot below. Reloading /web/home does not solve the problem. Bug is ultimate.

![Screen Shot 2022-09-24 at 10 21 05](https://user-images.githubusercontent.com/18708813/192088345-5d5d4d7d-fc81-42ad-8042-de959f0cb736.jpg)

3. Note: Quickly jumping to /settings/profile shows correct page without error. 

### Expected behaviour

Normal display of /web/home

### Actual behaviour

Showing ultimate error as in attached screenshot

### Specifications

Mastodon 3.5.3 on https://mastodon.online.

Firefox 78 on MacO 10.9.

**Stacktrace:**

TypeError: Intl.DisplayNames is not a constructor

render@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:263572
Bi@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1069864
qi@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1069659
ks@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1105273
bl@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1096716
ml@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1096639
sl@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1093669
Yo/<@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1045310
t.unstable_runWithPriority@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1120366
Vo@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1045019
Yo@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1045257
Xo@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1045190
ll@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1093960
notify@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:95612
notifyNestedSubs@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:96208
o@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:96042
b@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:337225
zt/</</</<@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:384311
zt/</</<@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:384006
zt/</</</<@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:383789
p/</</<@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:337979
dispatch@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:383321
S/</<@https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:143326

render (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:263572)
Bi (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1069864)
qi (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1069659)
ks (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1105273)
bl (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1096716)
ml (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1096639)
sl (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1093669)
Yo/< (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1045310)
t.unstable_runWithPriority (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1120366)
Vo (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1045019)
Yo (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1045257)
Xo (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1045190)
ll (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:1093960)
notify (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:95612)
notifyNestedSubs (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:96208)
o (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:96042)
b (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:337225)
zt/</</</< (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:384311)
zt/</</< (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:384006)
zt/</</</< (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:383789)
p/</</< (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:337979)
dispatch (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:383321)
S/</< (https://cdn.mastodon.online/packs/js/common-88e72cdd6b2414f7873f.js:2:143326)

**Comment by kescherCode** [comment]
https://endoflife.date/firefox

ESR support ended 10 months ago for your Firefox version.
I suspect you're not even running that, but rather a very, very outdated version of Firefox from **2 years ago**. This means the browser is considered dead. macOS Mavericks (10.9) itself stopped receiving support from Apple in **2016**, which is why Mozilla stopped supporting that version in Firefox 79. 

https://github.com/mastodon/mastodon/blob/7165e89362167eea79f3ab0d0251d56b300dd150/.browserslistrc#L4

**Comment by jayrope** [comment]
@KescherCode. However, yesterday it worked, and for the last two years. There is no obvious reason, why it shouldn't now. I can use a profile on another server running 3.5.2 without any problems. 
3.5.3 sems to get updated a lot without any obvious version jump.

Don't take it personal, but forcing users into having to buy new hardware for new operating systems through such procedures is - mildly put - contraproductive (, i tend to call this typical coder behaviour _technocratic_). 
I'd like to remind, that the majority of net users worldwide, epecially in developping countries, lack the funds for always running newest hardware and OS versions. This type of policy leads to many of us having to jump ship from an otherwise pretty clever social media idea, which for many is the only hope to circumvent corporate media. Please keep that in mind. Thank you.

**Comment by FediVideos** [comment]
Getting this same message on mastodon.online on latest version of Firefox when looking at hamburger menu (https://mastodon.online/web/getting-started) on web version of mastodon.online. Menu is visible when window is small enough to trigger mobile mode.

No idea if this is related, but think mastodon.online is testing new landing page, this seems to have broken something as it was working yesterday.

**Comment by jayrope** [comment]
> Getting this same message on mastodon.online on latest version of Firefox when looking at hamburger menu (https://mastodon.online/web/getting-started) on web version of mastodon.online. Menu is visible when window is small enough to trigger mobile mode.
> 
> No idea if this is related, but think mastodon.online is testing new landing page, this seems to have broken something as it was working yesterday.

Does it work today? Here i can access everything since today again. Problm solved. Whoever was part of this solution: Thanks a lot!
