### ISSUE TITLE
Ruby processes crash in blurhash gem when processing media attachments due to jemalloc

### ISSUE THREAD

**Issue by kescherCode** [mastodon/mastodon#19235]
### Steps to reproduce the problem

1. Run a Mastodon instance as described in "Installing from source"
2. Monitor `journalctl -u mastodon-sidekiq -f` for segmentation faults
3. `/opt/mastodon/live/vendor/bundle/ruby/3.0.0/gems/blurhash-0.1.6/lib/blurhash.rb:10: [BUG] Segmentation fault at 0x00007f565be8e000`, followed by lots of call stack information and a sidekiq crash.

### Expected behaviour

No segmentation faults

### Actual behaviour

Segmentation fault in the blurhash gem, specifically when the FFI function blurHashForPixels is called.

### Specifications

I have been investigating this bug for a while now, so this has been occuring at least since 3.5.2, and occurs up until the latest commit (3e0999cd1139d638332d62129dbf0b37263802fd)

This bug is remedied by not compiling Ruby with jemalloc and also not preloading jemalloc for mastodon-sidekiq. Doing either will eventually cause this segmentation fault a few times during a day. However, this remedy is not desirable due to what's mentioned in #7257 (in fact, my sidekiq has swollen up to 2.5 GiB RSS, but that doesn't matter for now).

This segmentation fault occurs consistently **only** in the `blurhash` gem, but I am not sure the gem itself is faulty, but rather, it may be some sort of weird interaction with Ruby when jemalloc is loaded. That's why I am reporting it here, not at the `blurhash` gem itself.

The crash memory address in step 3 is interesting. It always differs, but it is either at the border between a rw memory region and a non-rw memory region (In this case, look where `7f565be8e000` is):

```
7f565be27000-7f565be40000 ---p 00000000 00:00 0
7f565be40000-7f565be45000 rw-p 00000000 00:00 0
7f565be45000-7f565be64000 ---p 00000000 00:00 0
7f565be64000-7f565be8e000 rw-p 00000000 00:00 0
7f565be8e000-7f565be92000 ---p 00000000 00:00 0
7f565be92000-7f565be93000 rw-p 00000000 00:00 0
7f565be93000-7f565be9d000 ---p 00000000 00:00 0
7f565be9d000-7f565bea0000 rw-p 00000000 00:00 0
7f565bea0000-7f565bea8000 ---p 00000000 00:00 0
```

or it is sometimes outside the memory allocated to the process entirely.

Here's a dump by https://is-a.cat/@ar: https://gist.github.com/7b0585cc1ef9de33efce07f9ab9ed0bc

**Comment by kescherCode** [comment]
(jemalloc version 5.3.0, btw)

**Comment by kescherCode** [comment]
Update: This exact same bug happens with mastodon-web too now. Exact same crash at :blurHashForPixels in the blurhash gem.

I still blame jemalloc. This does *not* happen with other allocators, such as mimalloc (which does consume more memory than jemalloc, however). I can safely rule out a bug in the blurhash gem and I blame jemalloc.

**Comment by delroth** [comment]
> I still blame jemalloc.

What makes you think it's a bug in jemalloc and not a bug made apparent by a different memory allocation strategy? IMO the most likely hypothesis would be that with other allocators the same bug just reads arbitrary memory contents instead of crashing...

(Can reproduce btw, also on a runtime that links with jemalloc.)

**Comment by kescherCode** [comment]
> What makes you think it's a bug in jemalloc and not a bug made apparent by a different memory allocation strategy?

@delroth you know what: Good point. I kind of just went with the assumption that since jemalloc was the only allocator I've seen exhibit this behaviour. Still, I have yet to see any other crash or funky memory access, but if you can find one, that'd be very helpful.

**Comment by delroth** [comment]
Crash reproduced with scudo, but unfortunately no additional debug info -- I wonder if that's because the Ruby SEGV handler is eating it. Crash log attached so you can confirm there's no trace of jemalloc in there.
[crashlog.txt](https://github.com/mastodon/mastodon/files/9967322/crashlog.txt)

**Comment by Gargron** [comment]
I would welcome any performance improvements or fixes for blurhash generation. I'm aware it might not be the most efficient procedure (e.g. I have to pipe binary output from imagemagick into the Ruby process so that the blurhash library can do its thing based on pixel data).

**Comment by delroth** [comment]
I reproduced the crash under strace and as far as I can tell it happens while processing the following image: [crasher.png](https://user-images.githubusercontent.com/202798/201267875-de974c8f-a2c4-461f-b1d9-d0a292707578.png). The irony of this specific image being a repro is not lost on me.

Interestingly, imagemagick claims:
```
$ identify crasher.png
crasher.png PNG 400x400 400x400+0+0 8-bit sRGB 5c 376B 0.000u 0:00.000
$ convert crasher.png RGB:- | wc -c
240000
```

But 240000 is definitely not 400x400x3, which is what Mastodon would be expecting.

**Comment by delroth** [comment]
```
$ convert -depth 8 crasher.png RGB:- | wc -c
480000
```

Not sure why imagemagick decides to output 4 bit RGB instead but apparently that's what's happening. I suspect adding -depth 8 is safe in all cases and better matches the expectations of the blurhash code. I'll send a PR.
