### ISSUE TITLE
Restore preference to aggregate reblogs in home/list feeds

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#19293]
### Pitch

There should be a preference for whether to display all reblogs or not in your own feeds.

### Motivation

#18112 removed this preference, nominally for performance reasons, but if the performance impact is not noticeable (as Claire suggests it might not be), then this change only serves to make Mastodon less convenient to use for people who would rather see all times a status is reblogged. The act of reblogging a status carries semantic meaning and context, and collapsing all reblogs into a single entry can remove information, similar to a hypothetical situation where notifications were grouped. Given that this is truly a matter of preference (and a not-insignificant number of users do have preferences that differ from the default), it would make sense to restore the setting that controls this preference.

**Comment by noellabo** [comment]
The change to always enable aggregate reblogs doesn't get much attention now, but it will be a feature that users will complain about after v3.6 is released. This feature should be kept.
