### ISSUE TITLE
Live Streaming

### ISSUE THREAD

**Issue by amjiddader** [mastodon/mastodon#19309]
### Pitch

Hi,
Firstly thanks for Mastodon I have been using since long especially left Facebook after Facebook–Cambridge Analytica thing.

With time Mastodon will be better and bigger but i am missing some very useful features and please consider.

LIVE STREAMING: Mostly community i.e Instagram, Twitter Facebook have Live Streaming where users/creators go live with audience and is very impressive and useful.

I want to see Live Streaming in Mastodon with support for RTMP/CAMERA and also available on Smartphone Apps.

### Motivation

It will be useful for content creators, gamers and social influencers and help them to instantly share with others.

**Comment by Gargron** [comment]
I think that livestreaming is out of focus for a microblogging platform.

**Comment by amjiddader** [comment]
> I think that livestreaming is out of focus for a microblogging platform.

🤔 Create a poll and ask if someone else thinks my way.

Text Post is to say something.
Photos is to show something.

Live Is when someone has to say+show something.
from College basketball to live concerts and i m personally intrested in livestream because of GAMMING & Entertainment.

Lot of people nowadays are switching to Facebook live with CODM or other games. It will be nice if they can do same thing on Mastodon.

It was just a suggestion, you should create a poll..

Regards

**Comment by ryliejamesthomas** [comment]
@amjiddader You might want to look at Peertube if you're interesting in live streaming on the Fediverse.

**Comment by amjiddader** [comment]
Thanks mate . It was suggestion 
and Peertube is not Fediverse.
