### ISSUE TITLE
Allow API clients to detect availability of translation feature

### ISSUE THREAD

**Issue by connyduck** [mastodon/mastodon#19328]
### Pitch

Add some kind of parameter to /api/v1/instance or a new feature detection endpoint that allows clients to know whether the [new translation feature](https://github.com/mastodon/mastodon/pull/19218) is available.

Advertising instance features generally makes sense, not only for this feature. Please consider this also for new features that not all Mastodon versions support.

### Motivation

Apps can adapt their interface to not show the translation feature if it is not available without actually using it. This improves UX and performance.

**Comment by nyancrimew** [comment]
This is especially important in this case since the feature being available not only depends on version, but also whether or not admins have actually supplied api keys for a translation api, so it's generally not available on all instances.
