### ISSUE TITLE
crash after switching between WiFi networks with longer delay in between

### ISSUE THREAD

**Issue by pabloski80** [mastodon/mastodon#19323]
### Steps to reproduce the problem

1. Attached to one wifi
2. Mastodon working nicely
3.go out of range
4.attach to another WiFi after some 1h or so
5.crash on page reload
...

### Expected behaviour

page should load and display normally

### Actual behaviour

crash with error message that mastodon app crashed

### Specifications

Fennel v 103 9n android 5.0.1 on Samsung galaxy S4

Not sure where to drop a stack trace,  so dumping it below.

ReferenceError: MathJax is not defined

I</n._renderMathJax@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:243999
I</n.componentDidMount@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:244134
cs@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1092882
wu@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1110571
t.unstable_runWithPriority@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1129891
Va@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1054542
_u@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1107239
su@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1103391
Ya/<@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1054833
t.unstable_runWithPriority@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1129891
Va@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1054542
Ya@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1054780
Xa@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1054713
uu@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1103483
notify@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:99781
c</t.notifyNestedSubs@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:100416
c</t.handleChangeWrapper@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:100484
g@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:418118
Pt/</</<@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:389615
Pt/</</<@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:389159
Pt/</</</<@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:388912
a/</</<@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:336815
dispatch@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:420289
x/</<@https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:139986

**Comment by Gargron** [comment]
Hi, upstream Mastodon does not include MathJax. Judging by the stacktrace, the error is connected to a custom modification on qoto.org, so unfortunately I cannot help.
