### ISSUE TITLE
Allow to remove old timeline data of federated users unconditionally (GDPR compliance)

### ISSUE THREAD

**Issue by rriemann** [mastodon/mastodon#19347]
### Pitch

Dear all,

currently, administrators can remove cached federated user data with "tootctl statuses remove".

I proposes to add a new option "--force" that removes status data of federated users even if there has been some interaction with local users (subscriptions, likes, messages).

This would allow to run the the command twice to wipe out other user timeline data at the latest after e.g. 150 days:

    tootctl statuses remove --days=100
    tootctl statuses remove --force --days=150

Documentation: https://docs.joinmastodon.org/admin/tootctl/#statuses

### Motivation

To avoid that instances run by the public sector gather and store user data without any retention period, it would be necessary to offer tools to delete old data systematically. Data retention periods are required by the GDPR. So any change would also benefit the private sector.

This work could qualify for funding under the Next Generation Internet project of the European Commission 🇪🇺 .

Check the following funding line: https://nlnet.nl/entrust/

**Comment by Gargron** [comment]
Already done it #19232

**Comment by rriemann** [comment]
Sorry @Gargron , it is indeed a duplicate of myself 🤦‍♂️  https://github.com/mastodon/mastodon/discussions/18763

**Comment by nemobis** [comment]
The subject is about "timeline data", but isn't the cached username/handle and avatar for remote users also a case of "storing] user data without any retention period"? Apart from suspending a server and running `tootctl accounts cull` for deleted users, I couldn't find a way to delete the images and metadata of old users not associated to any local post/event.

**Comment by nemobis** [comment]
Ah that's https://github.com/mastodon/mastodon/issues/9567 , I'm told.
