### ISSUE TITLE
Cancelling a follow request says "unfollow" instead of "cancel"

### ISSUE THREAD

**Issue by mxamber** [mastodon/mastodon#19361]
### Steps to reproduce the problem

1. enable unfollow confirmation dialog
2. follow request someone
3. withdraw the request before it is approved

### Expected behaviour

The dialog should say something along the lines of "Are you sure you want to cancel your follow request?"

### Actual behaviour

The button says "unfollow" as if your request had already been approved and you were about to unfollow.

### Specifications

Mastodon 3.5.3 (reproduced on mastodon.art)

**Comment by navaneethkp36** [comment]
hi @mxamber I would like to contribute to this
