### ISSUE TITLE
Account migration relies on stale cache

### ISSUE THREAD

**Issue by nemobis** [mastodon/mastodon#19366]
### Steps to reproduce the problem

1. Set up a new account on some instance
2. Look at that account while logged in on your previous instance
3. Link the old account as an alias from the new account
4. Visit `/settings/migration` on the old account and attempt to confirm migration

### Expected behaviour

Migration should work

### Actual behaviour

Migration fails

### Detailed description

The alias check on the "old" instance uses stale cached data. The migration page should be changed to refresh/delete the cache about the "new" account.

For some reports see e.g. https://fosstodon.org/@krinkle/109178992694841477

A workaround is apparently to search the new account again from the old account, which can refresh the cache.

I'm not sure how difficult it is to clear the cache before performing the check. Can we just add something like `Rails.cache.delete_matched("relationship:#{account_id}:*")` somewhere around `app/views/settings/migrations/show.html.haml`?

### Specifications

Mastodon 3.5.3 on both sides

**Comment by nemobis** [comment]
Sort of related issue (which could provide an easier workaround) is https://github.com/mastodon/mastodon/issues/14023#issuecomment-689026176

**Comment by Gargron** [comment]
Related: #18429

**Comment by nemobis** [comment]
If you're admin on the instance the account is being moved from, another workaround is to go to /admin/accounts/ , find the remote account and click "Refresh profile".

**Comment by k3rn3l3rr0r** [comment]
Can confirm this behaviour on v4.0.0rc2

**Comment by mjankowski** [comment]
I think fixed by https://github.com/mastodon/mastodon/pull/18429 - but please comment/reopen if still occurring on a 4.3 install.
