### ISSUE TITLE
Cant setup admin - ERROR: relation "tags" does not exist

### ISSUE THREAD

**Issue by NiceKype** [mastodon/mastodon#19381]
### Steps to reproduce the problem

1. Every step of the installaton (no problems)
2. Setup process
3. Abort on Admin Setup

### Expected behaviour

Setup should go further to setup an admin

### Actual behaviour

Setup rake aborted with the error relation tags does not exist

### Detailed description

I got threw any step of the installation docs and everything worked fine.
But if i get to the installation, still anythins works fine, but at the admin setup section it aborts the setup and i get this error:
ERROR: relation "tags" does not exist.
In the logs i got this: https://img.nicekype.de/j7KPE0wu.png

So i tried to manually setup an admin but with that command in your docs i get this error:
su: bin/toolctl: No such file or directory

And if i want to start that howl thing without an admin, it gives me the first error in the logs.
The systems are active but i get an error in the web and the site does not load. 
See here the console: https://img.nicekype.de/LBKkbNfg.png
And here the browser error: https://img.nicekype.de/5NkfII0g.png

I really need help with that. 

### Specifications

Latest mastodon
Ubuntu 18.04

**Comment by Gargron** [comment]
Is it connected to the right database, and has the database been setup? The rails mastodon:setup task does it for you but if you do the setup your own way you must run rails db:setup yourself. Otherwise I don’t know, the tags table can’t be missing unless the database is corrupted.

**Comment by NiceKype** [comment]
Oh i tried the setup again to check this and i got some errors in the db setup.
- Database mastodon already exists
- PG::InsufficientPrivilege: ERROR:    permission denies for schema public

The first one is correct, i setup the database because the user need to have permissions for that, so i created a db and grant the user all permissions for the db but the tool can write in that database thats already exists or not?
I dont know what the second one means.

**Comment by NiceKype** [comment]
And i grant all permissions to the db, to the db in the schema public and granted usage of the schema public. Still have this error.
The grant commands in postgressql: https://img.nicekype.de/7fnKSMdG.png
The error thats still there: https://img.nicekype.de/mnoEDLwe.png

**Comment by NiceKype** [comment]
No solution for that? :/

**Comment by NiceKype** [comment]
push

**Comment by NiceKype** [comment]
push :/
