### ISSUE TITLE
Implement security for Elasticsearch

### ISSUE THREAD

**Issue by gunchleoc** [mastodon/mastodon#19402]
### Pitch

Support authenticating with elasticsearch using Transport Layer Security (TLS).

We also don't seem to have the ability to define a username and password.

### Motivation

In future versions, elasticsearch will start with security enabled by default, see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-minimal-setup.html

See also https://github.com/mastodon/documentation/issues/962

**Comment by tribela** [comment]
Username and Password is supported on #16890

**Comment by ElanHasson** [comment]
TLS works when you set `ES_HOST` to `https://….`

**Comment by plinss** [comment]
> TLS works when you set `ES_HOST` to `https://….`

I can confirm this works, however the URL can't contain the port, just scheme and hostname (it appears that the port is simply appended to the URL, e.g. `https://elastic.example.com:9200/` becomes `https://elastic.example.com:9200/:9200/...` and results an error.

Can I suggest that `ES_HOST` and `ES_PORT` be deprecated and replaced with `ES_URL` that simply takes a fully formed URL as-is? (it can default to http if no scheme is present, but should not default the port to 9200, so someone can run ES on port 80 or 443 without having to specify the port in the URL)

**Comment by vmstan** [comment]
I was also able to get this working after using @plinss suggestion of being specific about port 443.

**Comment by ElanHasson** [comment]
This is my configuration.


<html>
<body>


ES_ENABLED | true
-- | --
ES_HOST | https://my.instance.host.tld
ES_PASS | somethingsafe
ES_PORT | 9200
ES_USER | elastic


</body>
</html>

**Comment by gunchleoc** [comment]
Username and password is now documented on https://docs.joinmastodon.org/admin/elasticsearch/ so I'm closing this issue.
