### ISSUE TITLE
Follow a poll without voting in it

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#19416]
### Pitch

There should be an option (in the ... menu or something) on poll posts for "give me a notification when this poll ends", which can be selected without voting in the poll.

### Motivation

On mastodon dot social, if I create a poll and it later ends, I get a notification telling me. I think also if I voted in a poll I get a notification on end, I don't remember.

Sometimes there is a poll that is of interest, but which I personally cannot or should not vote in. For example, [this poll](https://weirder.earth/@cadxdr/109207542174583224) asking people with non-anglophone names about preferred pronunciation etiquette from anglophone speakers. I have a anglophone name so it would be inappropriate for me to select any option.

Sometimes people offer a "see results" option in a poll to capture people the poll is not directed at, but this uses up a poll option and makes the results harder to read. The linked poll didn't have such an option.

When a poll is over, everyone can see the options. But it's hard to remember to go back and check a poll 24 hours later or whatever.

Since Mastodon already has a "notify on poll completion" mechanism, the solution is obvious and possibly easy to implement. Just make it possible to hook into the "notify on poll completion" feature that's already there on demand. I don't know what software components would have to change to make this possible.

**Comment by ClearlyClaire** [comment]
> When a poll is over, everyone can see the options. But it's hard to remember to go back and check a poll 24 hours later or whatever.

The workaround I use in this case is to bookmark the poll.

> I don't know what software components would have to change to make this possible.

So far, it's tied to authorship of the poll or having an existing vote. `PollExpirationNotifyWorker` is queued at most once per poll, runs on the poll's expiration, and does most of the work (notify local poll author and voters, as well as update remote servers with the poll results).

`LocalNotificationWorker` is then queued once per local participant to deliver the notification through `NotifyService`.

On the client side, `renderPoll` in `app/javascript/mastodon/features/notifications/components/notification.js` displays the notification (selecting the appropriate text depending on whether the poll is authored by the recipient of the notification).

There is also another code path (triggered from `NotifyService`) for Web Push notifications

**Comment by Cassolotl** [comment]
Maybe a duplicate of *[Feature request] Option to be notified of poll results for polls you haven't voted in #11092* (June 2019)?

**Comment by mcclure** [comment]
Agreed, closing as duplicate

**Comment by Cassolotl** [comment]
Cool. :) Add a 👍 or a comment over there to make sure your vote is heard!
