### ISSUE TITLE
Vagrant Dev VM version doesn't support rsvg required to compile branding

### ISSUE THREAD

**Issue by cortices** [mastodon/mastodon#19410]
### Steps to reproduce the problem

1. Wanted to compile branding SVGs
2. Updated my vagrant VM according to the Vagrantfile
3. SSHed into VM
4. apt installed rsvg
5. Tried to use rails branding:generate
...

### Expected behaviour

The branding images should correctly generate.

### Actual behaviour

Shell errors were thrown about lack of support for "stylesheet" option

### Detailed description

Basically, the most recent supported version of `librsvg2-bin` on bionic (the version still shipped as vagrant vm) is too old to support the stylesheet arguments passed by mastodon's built-in branding tasks. This seems pretty clearly an oversight as the vagrant VM setup is recommended for development tasks.

librsvg v2.5+ (with stylesheet arg) is available on Jammy.

Also worth noting that librsvg2-bin isn't installed on the vagrant VM by default so originally, it causes a command not found error from rails.
I suggest the Vagrantfile could do with some TLC to bring it up to Jammy and include librsvg2-bin in the packages so it's possible to work with branding SVGs in it.

### Specifications

Mastodon edge from glitch-soc fork, but Vagrantfile is the same.

**Comment by techhead** [comment]
Pull request #22075 updates Ubuntu to 20.04 (Focal Fossa), NodeJS to v16, and adds additional system dependencies listed in the documentation as well. https://docs.joinmastodon.org/admin/install/#system-packages

This *may* resolve this issue also.

**Comment by mjankowski** [comment]
Closing on assumption that linked PR did solve this original issue.

That said, if the vagrantfile still has OTHER issues and/or is otherwise out of sync with rest of dev env, please open new issues/PRs/etc.
