### ISSUE TITLE
PostgreSQL error when running tootctl status remove on large database

### ISSUE THREAD

**Issue by hugogameiro** [mastodon/mastodon#19435]
### Steps to reproduce the problem

run `tootctl status remove` on large database

### Expected behaviour

Finish status remove

### Actual behaviour

Fails

### Detailed description

Attempting to run `tootctl status remove` on a large database fails on the '[Creating temporary database indices...](https://github.com/mastodon/mastodon/blob/main/lib/mastodon/statuses_cli.rb#L53)' step with the following message:
`ERROR: index row requires 322280 bytes, maximum size is 8191 (PG::ProgramLimitExceeded)`

From the information I could find this 8191 limit in PostgreSQL cannot be altered.

### Specifications

Mastodon 3.5.3

**Comment by Gargron** [comment]
It seems like it’s trying to index a specific value that is abnormally long…

**Comment by hugogameiro** [comment]
@Gargron Thank you so much, you put me on the right track. After reading your comment, the error message made much more sense.

The problem was caused by some custom third party software that had federated a base64 encoded png image `data:image/png;base64` and obviously it was a gigantic string on a field that expected a `remote_url`. It makes perfect sense that PostgreSQL did not accept a string so long on a index.

In case someone runs into this thread and is having the same problem, doing a simple sql query `select id, char_length(remote_url) as strsize from media_attachments order by strsize desc limit 10;` makes the problematic row pretty clear to identify.
