### ISSUE TITLE
Deleted user/account via preferences and via tootctl but unable to re-register using the same username - get 'account has already been taken' error.

### ISSUE THREAD

**Issue by jsailo** [mastodon/mastodon#19439]
### Steps to reproduce the problem

1. User registers and verifies account, say **username**.
2. User goes to preferences i.e. `/auth/edit` and clicks `settings/delete` and deletes account.
3. User tries to register with same account name. 
4. User gets Account `has already been taken` error.
...

I also used tootctl to delete the account using the following command and I get an Ok output (pic below).
`RAILS_ENV=production ./bin/tootctl accounts delete username`

User is still unable to register with `username`.

![image](https://user-images.githubusercontent.com/35369823/197601604-feca131e-5313-48c0-8fe4-ef9ef774ad7d.png)

### Expected behaviour

Account should have been deleted from the database with no trace left

### Actual behaviour

Account still exists

### Specifications

Mastodon v3.5.3
Firefox 106

**Comment by ClearlyClaire** [comment]
This is by design to avoid impersonation of previous users. You can create a new account with the same username by using `--reattach`.
