### ISSUE TITLE
Don't remove extra images or videos from other instances

### ISSUE THREAD

**Issue by Freeplayg** [mastodon/mastodon#19454]
### Pitch

Allow posts that have more than 4 images or more than one video to be shown. 

Someone suggested for the the fourth square to include a sub-grid (with a max of 4), with an overlay showing the amount of more images there are. And then users can see the rest by scrolling through the image popup.

My idea would be to have the images scroll horizontally. Something like this, but with an arrow button to scroll
![image](https://user-images.githubusercontent.com/40742947/197808635-bab335af-fafe-4683-956b-3e95a78ed1c0.png)

### Motivation

For example, Pixelfed, Calckey, and other Fediverse platforms allow users to add more than 4 images. But people on Mastodon will only see the first 4.

Example post! 
Original: https://plasmatrap.com/notes/9liahxqyd6u3cl85
From Mastodon: https://mastodon.online/@freeplay@plasmatrap.com/111331293932045363

**Comment by Sly-Little-Fox** [comment]
Maybe PR this into glitch-soc? Mastodon isn't gonna add that any time soon :(

**Comment by spaceottercode** [comment]
some people have suggested the last thumbnail in the 4-thumbnail display contain the text "+1" for 5 images, "+2" for 6 images, & so forth. People have suggested the 4th thumbnail be blurred when said text is overlayed. Clicking on the 4th thumbnail displays the 4th image as usual, giving viewers the opportunity to swipe to see the remaining images as consistently done with the first 3 images. While not as visually appealing as OPs idea, it might be easier to implement, it is backwards compatible, said presentation is commonly used and familiarity. But in the end, any approach is a good one. This is just something I've seen people w/o accounts here, bring up.

**Comment by Freeplayg** [comment]
Anything works, I just don't want images from other fedi software to be cut off.

**Comment by april83c** [comment]
> Maybe request this into glitch-soc? Mastodon isn't gonna add that any time soon :(

except this isn't one of those kinda quality of life/tweak things, this is a big problem. mastodon is just cutting off images and telling the user there's only 4

this is like if whenever there was a "show more" link on a long text post, instead of telling you there's more and letting you see more it just ended the post there and didn't indicate to you in any way that there's any more to it

this is more of a bug than a feature request

**Comment by Freeplayg** [comment]
Not sure if I can change the label on this D:

**Comment by wakest** [comment]
why are issues like these getting no response? this seems like quite an important issue, and one thats quite easy to solve with simply a "read more" or "show more immages" button after the first 4 are shown

**Comment by JacksonChen666** [comment]
> why are issues like these getting no response?

Because people are either busy or working on another issue.

**Comment by Freeplayg** [comment]
This also includes videos (w/ audio) being capped to only one.

**Comment by vmstan** [comment]
Duplicative (somewhat) of #14336
