### ISSUE TITLE
Domain block from user is not affected on hashtag following

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon#19469]
### Steps to reproduce the problem

1. Follow a hashtag
2. Block a domain (as a user)
3. Post using the hashtag from blocked domain
...

### Expected behaviour

Posts from blocked domain not appear on home timeline

### Actual behaviour

Posts from blocked domain appear on home timeline

### Specifications

Mastodon 3ad0a2ae3dcd36e4a9e0be5f72273f9c30df7548

**Comment by VyrCossont** [comment]
Was this actually fixed, and are there any caveats that users should be aware of? I'm still seeing posts from domains I've blocked in hashtags I follow. Example (mastodon.social, running 4.0.2, a few minutes ago):

<img width="661" alt="image" src="https://user-images.githubusercontent.com/26195552/203840098-641cbd8c-4701-47f7-9996-f0b51489b157.png">
