### ISSUE TITLE
Error while reviewing trending posts

### ISSUE THREAD

**Issue by Tslmuun** [mastodon/mastodon#19495]
### Steps to reproduce the problem

1.open https://example.com/admin/trends/statuses
2.Select trending post
3.Click  allow post
4.An error page appeared

### Expected behaviour

Allow posts to trend and appear on the explore page

### Actual behaviour

trends not working

### Detailed description

Oct 28 12:42:16 host bundle[2818076]:  method=POST path=/admin/trends/statuses/batch format=html controller=Admin::T>
Oct 28 12:42:16 host bundle[2818076]: 
Oct 28 12:42:16 host bundle[2818076]:  NoMethodError (undefined method `review?' for #<StatusPolicy:0x00007fe6b29067>
Oct 28 12:42:16 host bundle[2818076]: 
Oct 28 12:42:16 host bundle[2818076]:  app/controllers/concerns/authorization.rb:13:in `authorize'
Oct 28 12:42:16 host bundle[2818076]:  app/models/trends/status_batch.rb:33:in `block in approve!'
Oct 28 12:42:16 host bundle[2818076]:  app/models/trends/status_batch.rb:33:in `approve!'
Oct 28 12:42:16 host bundle[2818076]:  app/models/trends/status_batch.rb:12:in `save'
Oct 28 12:42:16 host bundle[2818076]:  app/controllers/admin/trends/statuses_controller.rb:16:in `batch'
Oct 28 12:42:16 host bundle[2818076]:  app/controllers/concerns/localized.rb:11:in `set_locale'
Oct 28 12:42:16 host bundle[2818076]:  lib/mastodon/rack_middleware.rb:9:in `call'

### Specifications

commit: https://github.com/mastodon/mastodon/commit/3e18e05330ac8c1101845db650d7cd62b0fa8260
ruby:3.0.4

**Comment by Gargron** [comment]
This should be fixed by #19490

**Comment by Tslmuun** [comment]
> 这应该由[#19490 修复](https://github.com/mastodon/mastodon/pull/19490)


Ok, thank you.
