### ISSUE TITLE
Numbers next to hashtag search results are incorrectly saying zero

### ISSUE THREAD

**Issue by FediVideos** [mastodon/mastodon#19498]
### Steps to reproduce the problem

1. On Mastodon.online search for hashtag Gardens
2. Hashtag results say zero for Gardens
3. Clicking on the tag shows there are actually loads of results for Gardens
...

### Expected behaviour

The number shouldn't say zero if there are posts with that tag

### Actual behaviour

The number says zero even if there are loads of posts with that tag

### Detailed description

I realise that the number is supposed to describe posts in last two days, but that is already displayed in context underneath the tag.

Why is there a much more prominent number in bright white without context off to the right? It would be much better if this larger number was removed completely.

Most tags will have 0 in last two days, so this white number is misleading people into thinking there are no results for most hashtag searches, even when there are loads of results.

I'm posting this as have seen new people misled by this, it is putting people off using the hashtag search even though that's the main system of discovery on Mastodon.

![tag example](https://user-images.githubusercontent.com/75383929/198600281-610c13d8-18ab-4441-a2b6-c34f9039849e.png)

![tag example 2](https://user-images.githubusercontent.com/75383929/198600347-29361c24-0c9c-4be7-9a9b-0f0b12c65a7a.png)

### Specifications

Mastodon 3.5.3 on mastodon.online

**Comment by FediVideos** [comment]
Just had more new users claiming hashtag search broken, they think 0 means no results. Just deleting the big white numbers would make Masto so much easier to use :)

**Comment by FediVideos** [comment]
Even more new users complaining to me today about there being no results in hashtag searches. When I tell them to click through, then there are results.

Just removing the large white number on the right would help Mastodon a lot! No need for any other changes.

**Comment by Peregrine997** [comment]
I have a similar (maybe the same?) issue.  Example follows.  (I hope the images load.) 
Starting here...
<img width="292" alt="image" src="https://user-images.githubusercontent.com/118069025/201484705-de68c336-d7a9-43b4-91ca-63018d30da85.png">
Input "#Ukraine"
Search yields 0 results: 
<img width="295" alt="image" src="https://user-images.githubusercontent.com/118069025/201484771-6d0d150d-a817-42ec-9a25-c17ef93d6d17.png">

Thank you

**Comment by FediVideos** [comment]
Okay, brilliant! This issue seems to have been resolved, the large white numbers are gone! :tada:  Thank you to devs for fixing! :pray: 

Issue closed!
