### ISSUE TITLE
Toot fails to send if sending toot exactly 500 characters long (character limit)

### ISSUE THREAD

**Issue by limdingwen** [mastodon/mastodon#19492]
### Steps to reproduce the problem

1. Create toot exactly 500 characters long on iOS app and mastodon.social. 
2. Send it. 

### Expected behaviour

The toot sends. 

### Actual behaviour

I get a pop up saying the toot failed to send and to check my internet connection (with options Discard and Retry). Retry does not work and I had to Discard. 

### Detailed description

A toot of 499 characters sends. I am using the iOS app’s character counter (sending at 0 characters left as shown in the UI) so I’m not too sure if it’s actually 500 characters. 

### Specifications

Mastodon.social (v3.5.3?)
iOS Mastodon app (v1.4.5) (144)

**Comment by Gargron** [comment]
If the text includes unicode or emoji I suspect the iOS app might incorrectly report the number of characters...

**Comment by limdingwen** [comment]
The text that was causing the bug was this: https://hastebin.skyra.pw/hutewejini.txt

However, it seems like it works now, not sure what changed. Thank you though!
