### ISSUE TITLE
Link preview cards removes URL fragment (everything after #) from links

### ISSUE THREAD

**Issue by forteller** [mastodon/mastodon#19538]
### Steps to reproduce the problem

1. Post a toot with a URL containing a #, like https://cryptpad.fr/pad/#/2/pad/view/VbowAnzGBYRRL9axpkOxVXdJArhe8Y0QCVu2zPLR2-E/

### Expected behaviour

Clicking on the automatic link preview card attached to the toot should send you to the exact URL you added to the toot

### Actual behaviour

The link preview card strips the #, and everything after it

### Detailed description

Most of the time this stripping of the # and everything after it might only change where on a page people clicking a link gets sent to. That's bad enough in itself. But some times, like with my example above, stripping this information totally changes where you're linked to. Clicking the URL sends you to the correct content, while clicking on the preveiw card sends you to something completely different. This is a problem.

I tried searching to see if this was already reported, my apologies if I just didn't find it.

Thanks for your hard and very important work!

### Specifications

Mastodon 3.5.3

**Comment by ClearlyClaire** [comment]
As explained in #19573, this is because we store the preview card for the “normalized” or “canonical” link for the resource posted, which does not contain the hash part. I think we should eventually rework this to link to the exact posted link no matter what the “normalized” or “canonical” link for the resource is, but that would require some database changes.

Basically, I think we want to store the link target in `preview_cards_statuses` whenever it is different from the “canonical” one.

**Comment by ineffyble** [comment]
I could see a scenario where we add the anchor back in to the normalised/canonical link, as opposed to forcing the card to the original URL. I can see some drawbacks with making the link go exactly as posted (e.g. if someone copies something from a tweet and the input url was t.co, ideally it's the destination that gets shared).

**Comment by FediVideos** [comment]
This is a real pain for me because I post links every day that depend on anchor links. People get confused about why the preview link is different to the actual link.

Would rather switch previews off than have this continue?

**Comment by forteller** [comment]
Every link to any TechCrunch article has a "preview card" that links to somewhere on consent.yahoo.com instead. Like 
https://consent.yahoo.com/v2/collectConsent?sessionId=3_cc-session_100c4264-7f15-4fff-875c-aea7606268a6 – which is a 404.

This is getting problematic. Really hope somone will focus on this! (and I'm really sorry I can't code and help out)

![image](https://user-images.githubusercontent.com/343561/208257389-eb7156bf-dd79-4168-a8e0-26c05642aa93.png)

**Comment by ineffyble** [comment]
Oof, TechCrunch is _broken as heck_ then.

**Comment by ineffyble** [comment]
@forteller That looks to be some temporary glitch. If I view that status from a remote instance, the preview card has correct URL. Mastodon.social looks to have cached the problem.

**Comment by AndrewKvalheim** [comment]
My reading of the situation is that for affected links the reality is there’s currently no preview available. When no preview is available, Mastodon should show no preview.

**Comment by Mart-Bogdan** [comment]
I've just encountered this bug.

Example post: https://octodon.social/@faho/109977432384095741
