### ISSUE TITLE
Improve contents of the footer

### ISSUE THREAD

**Issue by nclm** [mastodon/mastodon#19548]
So I was thinking about the links and text that appears in the footer of the left-side column:

> [Get the app](https://joinmastodon.org/apps) · [About](https://mastodon.social/about) · [About Mastodon](https://joinmastodon.org/) · [Documentation](https://docs.joinmastodon.org/) · [Privacy Policy](https://mastodon.social/privacy-policy) · [Hotkeys](https://mastodon.social/keyboard-shortcuts) · [Directory](https://mastodon.social/directory) · [Invite people](https://mastodon.social/invites) · [Account settings](https://mastodon.social/auth/edit) · [Logout](https://mastodon.social/auth/sign_out)
> 
> Mastodon is free, open source software. You can view the source code, contribute or report issues at [mastodon/mastodon](https://github.com/mastodon/mastodon) (v4.0.0rc1).

There are a few things about it that I think could be improved:
- The text is very technical: “open source software”, “view the source code”, the link to Github shown as “mastodon/mastodon”, the version number “v4.0.0rc1”. Most of that is not relevant for most people, especially not always visible on every page.
- It mixes links that have to do with the instance with links that have to do with Mastodon in general. The most confusing being “About · About Mastodon”: it should at least be “About this instance · About Mastodon” or better “About InstanceName ⋅ About Mastodon”.
- There are so many links that it leads to link blindness. Some of them are already in other, more logical places, such as “Account settings” and “Log out”.

Here’s a first pass trying to solve some of that:

> [InstanceName](https://mastodon.social/about) is part of [Mastodon](https://joinmastodon.org/), a decentralised social network that puts people first.
>
> InstanceName: [About](https://mastodon.social/about) · [Invite people](https://mastodon.social/invites) · [Profiles directory](https://mastodon.social/directory) · [Privacy policy](https://mastodon.social/privacy-policy) 
>
> Mastodon: [About](https://joinmastodon.org/) ⋅ [Get the app](https://joinmastodon.org/apps) · [How to use](https://docs.joinmastodon.org/) · [Keyboard shortcuts](https://mastodon.social/keyboard-shortcuts) · [Get help and suggest features](https://github.com/mastodon/mastodon/discussions) ⋅ [Report technical issues](https://github.com/mastodon/mastodon/issues)

Now that’s not perfect, but some things it does:
- Talk about Mastodon as a social network, not as software. That’s how people experience it. Of course it is software but every other network is too. The exact sentence “a decentralised social network that puts people first” is made up quickly, it can be anything else, as long as it is short and clear and not technical.
- Reminds of the relationship between your instance in particular and the general network. Not everyone gets that in the beginning, especially if you have been recommended an instance directly and didn’t get through joinmastodon.org.
- Separates the links that are instance-specific with the ones that are not. That’s optional, it adds clarity in some respects but also complexity in others. 
- Makes some links more clear and less technical. “Directory” becomes “Profiles directory” (it could even be “Discover people” or “Find people to follow”). “Documentation” (a developer or administrative term) becomes “How to use”. “Hotkeys” becomes “Keyboard shortcuts” (how most people would call them I think).
- Gives a better form to the link to Github than the weird “mastodon/mastodon” and does not take regular users to the depository landing page, which is incomprehensible with all its files and commits to someone who doesn’t work with software. Instead, it’s turned into two links, “Get help and suggest features” that goes to Discussions (copied from joinmastodon.org), and “Report technical issues” that goes to Issues (the “technical” is added so it cannot be confused with a place to report issues one might have with another user or similar), both of which are more friendly and more understandable landing pages.
- Removes the version number. It’s useful information, but it might have a better place, maybe in the settings. But if it is necessary for people to suggest features and report issues, then it could be added back.

I hope this makes sense! The exact sentences, links and link labels can be talked about to reach something very relevant, but I do believe that a direction like this could improve the footer section :)

**Comment by Gargron** [comment]
Being able to view/download the source code is a requirement of the AGPLv3 license Mastodon is distributed under, so I consider that bit essential to the footer, but otherwise, I'm trying your suggestions out...

**Comment by nclm** [comment]
Fair enough, good points, what about something like this:

> [InstanceName](https://mastodon.social/about) is part of [Mastodon](https://joinmastodon.org/), a social media app that puts people first and connects you to a global social network.
>
>  [Get the app](https://joinmastodon.org/apps) · [How to use](https://docs.joinmastodon.org/) · [Keyboard shortcuts](https://mastodon.social/keyboard-shortcuts) · [Invite people](https://mastodon.social/invites) · [Profiles directory](https://mastodon.social/directory) · [Get help and suggest features](https://github.com/mastodon/mastodon/discussions) ⋅ [Report technical issues](https://github.com/mastodon/mastodon/issues) · [Source code](https://github.com/mastodon/mastodon) · [Privacy policy](https://mastodon.social/privacy-policy)

Using “app” as a very user-friendly synonym for “piece of software”. And adding a “Source code” link to respect the license.

By the way, if InstanceName is “Mastodon”, then it should show the installation domain (maybe capitalised). “Mastodon.social is part of Mastodon”.
