### ISSUE TITLE
More than 3 trends in desktop browser view

### ISSUE THREAD

**Issue by B0ngripper** [mastodon/mastodon#19545]
### Pitch

It would be great, if more than 3 trends can be shown in desktop browser view.

### Motivation

The user base is getting bigger by the minute and already now i have the feeling that 3 trends in not enough to keep track of "hot" topics. At least 5 or even 10 would be a huge improvment.

**Comment by Gargron** [comment]
You can see more by navigating to "Explore". Do you think that's not sufficient?

**Comment by Cassolotl** [comment]
I don't see any trends in that column at all because my 13.3-inch laptop screen is not tall enough, and this has been an issue since the feature was created.

*Not all hashtags are shown on a smaller screen < 1080p #11565*

**Comment by Gargron** [comment]
My hands are a bit tied when it comes to that, surely it would not be preferable to have one part of the screen always scroll? If there were fewer links in the navigation panel we would have a bit more space to play with...

**Comment by Gargron** [comment]
Favourites and bookmarks could be united as tabs under a "Saved posts" screen, and local and federated timelines could be moved as tabs to the "Explore" screen, that would make the navigation a lot shorter, but I fear the community might not appreciate it.

**Comment by Cassolotl** [comment]
>My hands are a bit tied when it comes to that, surely it would not be preferable to have one part of the screen always scroll? If there were fewer links in the navigation panel we would have a bit more space to play with...

On my 13.3 inch laptop screen the Getting Started/Navigation panel already has to scroll, so I'm like, why split the panel's scroll at all? Why not just put 5 trending hashtags at the bottom of the panel for everyone and have the entire column scroll if you want to scroll down to view them?

**Comment by Gargron** [comment]
I thought the issue was about the default UI, not the advanced one.

**Comment by B0ngripper** [comment]
> You can see more by navigating to "Explore". Do you think that's not sufficient?
In the meantime, that is enough. I have learnt some new search features in the last couple of days. Thanks!
