### ISSUE TITLE
Mastodon Android - App crashes when attempting to view followers

### ISSUE THREAD

**Issue by vaelfonia** [mastodon/mastodon#19559]
### Steps to reproduce the problem

1. Launch Mastodon for Android.
2. Go to profile.
3. Attempt to check followers.

### Expected behaviour

Should have been able to view the list of followers.

### Actual behaviour

App crashed, sent back to launcher.

### Detailed description

I'd like to note that this issue doesn't exist for me when checking who I follow - just who is following me. This is all I know.

### Specifications

Mastodon for Android 1.1.3 (Play Store)
Android 13.0 (October 2022 patch - build number TP1A.221005.003)
Google Pixel 6a

**Comment by ClearlyClaire** [comment]
Issues with the official Android app should be reported here, thanks: https://github.com/mastodon/mastodon-android/issues thanks
