### ISSUE TITLE
High Contrast mode is not

### ISSUE THREAD

**Issue by cgay** [mastodon/mastodon#19564]
### Steps to reproduce the problem

1. Turn on High Contrast theme in settings
2. Turn on the advanced UI (but maybe not necessary)
3. Start to reply to a toot
4. Be unable to read the toot you're trying to reply to because of extremely low contrast "highlights".

### Expected behaviour

I should be able to read the toot I'm replying to.

### Actual behaviour

I can't read the toot I'm replying to.

### Detailed description

The Dark theme is actually higher contrast than the High Contrast theme in this regard.

<img width="342" alt="Screen Shot 2022-10-30 at 5 36 29 PM" src="https://user-images.githubusercontent.com/491829/198904089-d620551b-3553-4382-a49b-57e87e016255.png">

It is literally impossible for me to read the purple text in the above image. I have pretty decently functioning eyeballs for a 58-year-old human being.

### Specifications

* Mastodon web client that was current as of 30-Oct-2022. (The version info is not displayed anywhere obvious that I can see.)
* Chrome Version 106.0.5249.119 (Official Build) (arm64)

**Comment by Gargron** [comment]
I think this is a regression from recent stylesheet changes. Definitely not intended...

**Comment by cgay** [comment]
I did it again, I submitted a bug and sounded cranky but didn't really mean to have it come across that way. Sorry about that and thanks for all you do to make Mastodon a great place to hang out! Contrast issues are kind of my pet peeve I guess.
