### ISSUE TITLE
Can't cancel a follow request on a private account

### ISSUE THREAD

**Issue by interglossa** [mastodon/mastodon#19569]
### Steps to reproduce the problem

Follow a private account on another mastodon server. Then navigate to the private account profile and click "Withdrawal follow request". Nothing happens. -

This was  using the web interface. This was reported in 2017 (#785) but was attributed to accounts which went public after the follow request was issued. This account was private before and after. #785 was marked as "closed" but the bug is still there .

### Expected behaviour

It should have removed the follow request.

### Actual behaviour

It did not remove the follow request.

### Detailed description

See above. Issue friend request on mastodon.social, user on social.coop

### Specifications

Mastodon 4.0.0rc1
Browser chrome, Android and chromeOS same behavior

**Comment by ClearlyClaire** [comment]
I am unable to reproduce this issue. Did any error pop up when clicking “Withdraw request”? Does this still occur? This may be quite involved in mobile browsers, but if possible, can you check if there is any error in your browser's console?

**Comment by thekingrat** [comment]
I followed a public account on another server which was having issues. That server has resolved its issues.  Account is still public. Am unable to withdraw follow request and unable to send a new follow request.  Following from account is on mastodon.social, running 4.0RC1. Following to account is on a 3.5.3 server.

**Comment by ClearlyClaire** [comment]
> I followed a public account on another server which was having issues. That server has resolved its issues. Account is still public. Am unable to withdraw follow request and unable to send a new follow request. Following from account is on mastodon.social, running 4.0RC1. Following to account is on a 3.5.3 server.

Same questions: what happens when clicking “Withdraw request”? does an error message pop up at the bottom of the screen after a while? If you know how to access your browser's console, is there any error on it?

**Comment by ClearlyClaire** [comment]
Nevermind, I have identified the issue and will fix it shortly.
