### ISSUE TITLE
Logged in to my instance but cannot interact with another instance using the Copy button in the 'On a different server' area

### ISSUE THREAD

**Issue by jsailo** [mastodon/mastodon#19576]
### Steps to reproduce the problem

1. I open e.g. https://mastodon.social/@Gargron/109256990373721673, click **Boost**. 
2. Click the **Copy** button in the **On a different server** area. 
3. I go to my instance where I'm logged in and paste the copied URL on the web browser address bar.
4. I'm Redirected back to the URL in step 1 i.e. https://mastodon.social/@Gargron/109256990373721673

### Expected behaviour

Pop-up window should appear that asks me to input my server/instance username so I can to interact with the post (on another instance/server)

### Actual behaviour

Redirected back to the URL or the URL is opened with no option to interact with the Toot/post

### Detailed description

I'm following the _correct_ steps. If I'm not, I think it's a usability/User flow issue.

https://user-images.githubusercontent.com/35369823/198955919-60d3bd3e-6d40-4adc-ae7c-8e948ce27469.mp4

### Specifications

- PostgreSQL 9.5+
- Redis 4+
- Ruby 2.6+
- Node.js 14+
- Firefox 160.0.2

Uploading mastodon_cannot_reboost_edit.mp4…

**Comment by ClearlyClaire** [comment]
The “search bar of your favourite app or the web interface” would be the “Search” bar above the compose box and your name in the web interface, not the browser's address bar:
![image](https://user-images.githubusercontent.com/384364/198966412-b2da460f-a967-4d1b-89e4-6bfb106891a0.png)

The placeholder text has very recently been updated to “Search or paste URL”, but I'm not sure what else could be done to make it clearer:
![image](https://user-images.githubusercontent.com/384364/198966585-6fff425a-4369-4052-a3fc-13f62e9f0a93.png)

**Comment by jsailo** [comment]
Thanks @ClearlyClaire. That works. 

May I suggest:
- Adding a small file gif animation of what you mentioned above? (PIC 1)
OR
- A **See how** hyperlink just after the 'where you are signed in' text? (PIC 2)

You guys are experts so it's up to you. The current flow is quite confusing to be honest.

PIC 1

![image](https://user-images.githubusercontent.com/35369823/198968178-d118fb08-155d-485b-9ad9-7326af5dc525.png)

PIC 2

![image](https://user-images.githubusercontent.com/35369823/198969476-015d9885-5ad8-4f28-b5f9-223b0ccfa98e.png)

**Comment by Gargron** [comment]
The GIF is an interesting idea! That would be very visual.

**Comment by vmstan** [comment]
Closing as the interaction model has been redesigned for 4.2.
