### ISSUE TITLE
Bad UI: "Bell" icon only on server.name/web/@account, not on server.name/@account

### ISSUE THREAD

**Issue by wklaebe** [mastodon/mastodon#19587]
### Steps to reproduce the problem

1. desire to follow an account
2. browse to their server.name/@account, possibly via clicking link in toot
3. see "Follow" button, but not "notify me" button (the one with the bell icon)
4. edit URL, insert 'web/' -> server.name/web/@account
5. see "Follow" button *and* "notify me" button

### Expected behaviour

the "notify me" button should be present on the first page too

### Actual behaviour

the "notify me" button was not present on the first page

### Detailed description

There seem to be two slightly different account pages, server.name/@account and server.name/web/@account - the first one does not have the "notify me" button, the second does. I don't currently see a reason for that to be a design choice.

### Specifications

Mastodon v3.5.3 on https://chaos.social/
Firefox 106.0.2

**Comment by mcfly** [comment]
thanks for opening that @wklaebe

**Comment by Gargron** [comment]
The distinction between UIs is no longer present in the main branch and upcoming 4.0

**Comment by trwnh** [comment]
can this issue be closed, then?

**Comment by wklaebe** [comment]
"My" instance (chaos.social) is still on 3.5.5, so I cannot really tell yet if it's resolved. I'll close as soon as I can confirm.

**Comment by wklaebe** [comment]
Now they updated to 4.0.2.
- https://chaos.social/web/@account gives me a "404" Mastodon image in the rightmost column
- https://chaos.social/@account has a "bell" icon
