### ISSUE TITLE
twitter cross verification

### ISSUE THREAD

**Issue by AlanBell** [mastodon/mastodon#19584]
### Pitch

link verification in the profile is great for blogs and sites where you can put a rel=me link, but it would be good to cross verify to twitter in a low friction way.

expand services/verify_link_service.rb so that if a twitter handle is present, such as @sometwitteruser it will check twitter to see if the current name for that handle is set to @[user@mastodon.instance](mailto:user@mastodon.instance) so to verify a twitter handle you change the twitter display name to reference your mastodon name. As with the other verification this would only happen on save, so you could change it back on twitter afterwards if you wanted to.

### Motivation

when migrating from the bird site it can be useful to have a verified link to a twitter profile to assert that the person controlling this mastodon profile has control over that twitter profile.

**Comment by yurukov** [comment]
Easier change and more secure would be to skip the rel check on the Twitter domain if the link is in the profile description. This way you would need to add your link in the bio on twitter to have it verified.

**Comment by AlanBell** [comment]
I think the problem with that is that twitter hides the actual link behind their link shortener, so we either follow that and check it matches, or do some dubious parsing of what it serves up. This is the kind of thing it would be:
`<a dir="ltr" href="https://t.co/nyMbxY0g5G" rel="noopener noreferrer nofollow" target="_blank" role="link" class="css-4rbku5 css-18t94o4 css-901oao css-16my406 r-1cvl2hr r-1loqt21 r-poiln3 r-bcqeeo r-qvutc0"><span aria-hidden="true" class="css-901oao css-16my406 r-poiln3 r-hiw28u r-qvk6io r-bcqeeo r-qvutc0">https://</span>mastodon.green/web/@alanbell</a>`

**Comment by yurukov** [comment]
That is true. We can follow the redirects to verify or make assumptions about how twitter has operated so far and get the link text instead. One can't do markdown, so getting the same link as what would be redirected from the shortner is guaranteed (currently).

Risks would be:
- Elon pulls out a blunt and bans all mastodon-related links - highly likely
- they allow markdown in bio - unlikely

**Comment by AlanBell** [comment]
The website field on the twitter profile appears to be identified with data-testid=UserUrl so a selector for it would be something like
`$('a[data-testid="UserUrl"]').text`
which I think would be fractionally more robust than looking for links in the bio.

**Comment by Michael-Brooks** [comment]
You could do something similar to Keybase where it verifies you with a tweet that contains a specific key. It does something similar for HN and Reddit too. Here's my HN profile as an example https://news.ycombinator.com/user?id=michaelbrooks

**Comment by AlanBell** [comment]
I think that might be adding a bit too much complexity and an appearance of more security than there actually is. It is also going to be a lot easier for someone up to no good to persuade an account to tweet a thing than it is to change something on their profile - particularly bot accounts.

**Comment by AlanBell** [comment]
Digging a bit further into the way twitter serves up public profile data this is going to be somewhat more challenging than expected. The page is constructed after loading, using data about the profile from the graphql api based on a request that requires a x-guest-token and authorization: Bearer token in the headers.

**Comment by yurukov** [comment]
> Digging a bit further into the way twitter serves up public profile data this is going to be somewhat more challenging than expected...

Yep, noticed that too. We may do an api call, but then each instance needs to register as a twitter service which won't happen. So no-go.

**Comment by AlanBell** [comment]
yeah, I can't see a remotely sane way to do it, so I think people will have to rely on eyeballs 1.0 Click the link on the mastodon profile and look for a link back on their twitter profile.

**Comment by NicolaeNMV** [comment]
That's an interesting idea. You could just use oauth for this ?
