### ISSUE TITLE
Invalid admin log translated message for re-sending e-mail confirmation letter

### ISSUE THREAD

**Issue by skobkin** [mastodon/mastodon#19593]
### Steps to reproduce the problem

1. Find user with not yet confirmed e-mail
2. Re-send confirmation mail from their profile
3. Check audit log (in English at least)

![invalid translation](https://user-images.githubusercontent.com/967576/199055583-6e3e9b86-a0e5-41d0-915f-3dd14c6d2e51.png)

### Expected behaviour

Something like "Re-sent confirmation message"

### Actual behaviour

"%admin% confirmed e-mail address of user"

### Specifications

Mastodon 3.5.3
https://github.com/mastodon/mastodon/blob/main/config/locales/en.yml#L232

**Comment by ClearlyClaire** [comment]
Addressing it in #19674. It will only fix new entries, though. Old entries are incorrectly stored and cannot be fixed.
