### ISSUE TITLE
IP rules lost on upgrade to v4.0.0.rc1

### ISSUE THREAD

**Issue by rodti** [mastodon/mastodon#19608]
### Steps to reproduce the problem

1. Upgrade from v3.5.3 to v4.0.0rc1 (commit https://github.com/mastodon/mastodon/commit/2d9a85db6efe0c9ccfda1420551ce3d6025bc27e)
2. Logged in as admin, go to Preferences > Moderation > IP Rules
3. All previously defined IP rules have vanished, none are shown

### Expected behaviour

IP rules preserved from before upgrade

### Actual behaviour

IP rules lost

### Detailed description

There were around 20+ IP rules defined on the server before the upgrade, a mix of IPv4 and IPv6, different subnets, different comment. All have disappeared after upgrade.

### Specifications

Mastodon v4.0.0rc1
Node 3.0.4

**Comment by rgarver** [comment]
If you had duplicates it appears that #19456 could have removed all of them.

**Comment by ClearlyClaire** [comment]
Is it possible that they would all have normally expired?

**Comment by rodti** [comment]
> Is it possible that they would all have normally expired?

I had them set for either 1 or 3 years, all were set within the last year.

What's amusing is that I went to that page after upgrading to v4.0.0rc1 with the plan of copying all IP rules to a text file and removing most or all of them. We have a lot of new subscribers so I thought I'd 'open the floodgates' and start building a new set of IP rules, but Mastodon was one step ahead of me!

**Comment by ClearlyClaire** [comment]
That's surprising… my only lead so far is indeed #19456 removing duplicates, but it should keep one of each anyway. I don't understand yet what else could have happened.

**Comment by rodti** [comment]
> That's surprising… my only lead so far is indeed #19456 removing duplicates, but it should keep one of each anyway. I don't understand yet what else could have happened.

Thinking out loud here, but is it possible they're still there but not being displayed? I'm also having issues with viewing the audit logs (https://github.com/mastodon/mastodon/issues/19609#issuecomment-1298620557) and wonder if there are maybe some similar problems with accessing parts of the Moderator submenus.

**Comment by rgarver** [comment]
@ClearlyClaire you are right it should leave the "last" record for each IP address (missed the `...` vs `..` in the PR).

**Comment by ClearlyClaire** [comment]
> > That's surprising… my only lead so far is indeed #19456 removing duplicates, but it should keep one of each anyway. I don't understand yet what else could have happened.
> 
> Thinking out loud here, but is it possible they're still there but not being displayed?

I don't think so. If you want to be sure, I guess try `IpBlock.unscoped.all` in a Rails console (`RAILS_ENV=production bundle exec rails c`)

> I'm also having issues with viewing the audit logs ([#19609 (comment)](https://github.com/mastodon/mastodon/issues/19609#issuecomment-1298620557)) and wonder if there are maybe some similar problems with accessing parts of the Moderator submenus.

No, this shouldn't be related.

**Comment by rodti** [comment]
> > Thinking out loud here, but is it possible they're still there but not being displayed?
> 
> I don't think so. If you want to be sure, I guess try `IpBlock.unscoped.all` in a Rails console (`RAILS_ENV=production bundle exec rails c`)

No output returned from that command.

If I add in a new IP rule as a test, it is returned by that command in the console.

Very strange. At the end of the day I was going to recreate my rules anyway, but worrying that the data was lost on upgrade.
