### ISSUE TITLE
One-time event during server load: Single post duplicated many times in notifications

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#19615]
### Steps to reproduce the problem

On 2022-Oct-30, during the heavy server load event following the Twitter acquisition, I saw an unusual one-time event that seems to indicate a bug in the Mastodon server or web-client code.

I was logged into mastodon.social. At the time I had (not on purpose) two browser tabs pointing at mastodon.social. Another user on mastodon.social replied to a post of mine with [this reply](https://mastodon.social/@danielcassidy/109258386155107084).

Over the next hour, I saw a continuous thing in **both** browser tabs where every minute or two a new copy of this same post would appear in my notifications stream. Each new copy would show a unique timestamp corresponding to the moment it appeared in the Notifications stream:

![Duplicate notification](https://user-images.githubusercontent.com/277318/199135178-33cc73c1-57ee-46ff-a746-430a186040d2.png)

Throughout the event in **both** browser tabs an additional copy of the post remained at the very top of the notifications tab, floating above newer notifications, with the timestamp corresponding to the original true post:

![Weird "pinned" notification](https://user-images.githubusercontent.com/277318/199135187-f4b3045f-90da-4a24-8022-06c15be05088.png)

I am not sure if the two browser tabs received the same number of duplicate notifications but there were many of them. When I scrolled down after this had been going on for a while, I counted at least eight dupes, as well as in at least two places weird post-sized gaps between duplicates that only appeared when I scrolled down (THIS SPECIFIC SYMPTOM MAY NOT HAVE BEEN CAUSED BY MASTODON, see "Specifications")

![Gaps](https://user-images.githubusercontent.com/277318/199135458-1ebaf931-6500-4b75-a36d-2f1f5a19b933.png)

I asked Daniel Cassidy after the event and he said he did *not* delete and re-post, or use any edit feature.

I checked on the Mastodon discord. Claire and Eugen suggested I check whether the links on the duplicates all had the same ID. They did, all of them. Claire also suggested I check the Javascript console, which showed only:

> (1000x) The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate as value and it is preloaded intentionally.
> 608 log entries are not shown.

and 3 "issues":

> (1x, message icon) Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
> (2x, error icon) Content Security Policy blocks inline execution of scripts and stylesheets

Claire said this JS console output indicated "No websocket errors".

After about 20 minutes I happened to click from the "All" to the "Mentions" subtab in one browser tab, and at the end of the hour I did the same to the other tab. The instant I clicked from "All" to "Mentions" and back, the duplicates all disappeared and the unusual behavior halted immediately.

I have never seen this before, and there appears to be no way to reproduce it on purpose.

This is obviously not high priority but may be worth investigating after the load decreases.

### Expected behaviour

Posts appear in linear order of receipt

### Actual behaviour

As described

### Specifications

This was with Chrome 106.0.5249.119 (Official Build) (64-bit) (cohort: Stable) 9f2101830b56fd2ea1408287f6c74e253ebcb7c6-refs/branch-heads/5249@{#797} on Windows 10. I was running UBlock Origin, as well as the Stylus plugin with [this Mastodon-targeting CSS userstyle](https://userstyles.world/style/7065/compact-er-mastodon), but that could not have caused the post duplication (it possibly **could** have caused the blank spaces observed between some of the dupe posts, that would be hard to say). I use the multi-column "advanced mode".

**Comment by ClearlyClaire** [comment]
Thanks for the detailed report! There are multiple issues at play here, and I will try to break them down.

## Client receiving duplicate notifications

For some reason, the client is receiving duplicate notifications. To be honest, I have no idea how this could occur, as `LocalNotificationWorker` checks for existing notifications before issuing a new one.

## Client showing duplicate notifications

Incoming notifications are processed client-side in `app/javascript/mastodon/reducers/notifications.js` in either `normalizeNotification` (when receiving the notification through the streaming server) or `expandNormalizedNotifications` (when polling or expanding notifications).

Neither of these functions ensures there can be no duplicate (although if the notifications are received in-order and without duplicates, there can be no duplicate).

## Client showing weird gaps

This is a direct consequence of the client displaying duplicate notifications. Without getting into details, this is our code for unloading out-of-view content not handling duplicate contents well. This is not really an issue with this piece of the code, but really the notification list itself breaking the `ScrollableList` and React expectations of not having duplicate items.

**Comment by ClearlyClaire** [comment]
Actually there is one thing I am unsure about and that could matter quite significantly: did the client receive the same notification multiple times, or multiple notifications about the same activity? Neither is supposed to occur, but the involved code paths and possible fixes could be quite different depending on which it is.

(This is merely me posting to keep track of both possibilities, not a request for you to provide more information, as it would not be easy to figure out with the affected tabs still open, and probably impossible once they have been closed).

**Comment by ClearlyClaire** [comment]
Investigating a bit more, the fact that refreshing the page clears the duplicate notifications suggests that the issue is not several notification objects for the same activity, but the front-end processing the same notification object multiple times. I believe the “weird gap” issue also confirms this.

My theories are:
- either the client does receive multiple copies of the notification object, although I don't understand how it is possible (can a single client receive multiple copies of a single Redis publication on the same subscription?)
- either it is the client polling for notifications and messing up because notifications were previously received out-of-order, but I think it requires the Websocket or EventSource connection to have failed, which I see no indication of in the original report

Whatever the root issue is, it's something that probably should be handled on the client, and I will try to address that (that code is notoriously messy because of the need to account for “disconnection gaps”).

**Comment by mcclure** [comment]
Claire, what if anything does the "floating copy" in the second screenshot tell you about likely causes? IE it was not just that this one notification kept appearing, but there was also the "special" copy of the notification that did not get refreshed/recreated but just happened to constantly get sorted above all other notifications.

**Comment by ClearlyClaire** [comment]
Needs a lot of testing and careful review, but I think I addressed the issue in #19693.
