### ISSUE TITLE
Loading a "trending news" link should load posts including that link instead of the article itself

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#19620]
### Pitch

When viewing the list of trending links, try to click on a component for a trending news link.

- Current behavior: It loads the article externally
- Proposed behavior: It loads posts that link to the article

### Motivation

- A significant number of articles are paywalled and can't be read
- The comments that people are making are more interesting and relevant than the article itself
- Presenting articles without context of public opinion is not very useful
  - It is possible to make an article trend entirely by people being overwhelmingly or entirely critical of its contents
  - Linking to an article is not an endorsement of the article

**Comment by Gargron** [comment]
I do agree…

**Comment by ClearlyClaire** [comment]
I am not sure about that. Wouldn't that kind of conflict the “no full-text search” stance of the project? Sure, it's still not full-text search, but using a hashtag is far more intentional than posting a link is.

**Comment by trwnh** [comment]
Yeah, it's a bit of a challenege because there isn't really a way to communicate to users that posting a link may make their post visible in a discovery feature specific to links. The only way forward I can think of (that doesn't involve removing the news tab) is to somehow tie to it to existing privacy hints such as whether the post is unlisted or whether the user has enabled "suggest account to others".

**Comment by kolgza** [comment]
I can see people are talking about an article, but I can't see what they're saying. This is really frustrating!
![image](https://user-images.githubusercontent.com/46303203/201490569-440e8209-48de-462e-add7-0be68f7bb00f.png)

**Comment by simevo** [comment]
I also agree, see this 3-years old proposal: **shared urls as "soft hashtags"** #12285

**Comment by lirontocker** [comment]
I put together some wireframes for this in a duplicate thread, I'll close the duplicate and add the wireframes here:

![202869036-01ebea20-b0aa-4e0e-bd77-64931e5320b5](https://user-images.githubusercontent.com/7912787/202893473-f8bd1510-07ff-45ba-bb4b-0454080a236c.png)
![202869039-9f465545-d33c-4873-b222-2969fd367bed](https://user-images.githubusercontent.com/7912787/202893477-3a082752-feab-4c4f-bdb6-e1ca23ad1e2a.png)

**Comment by simevo** [comment]
@lirontocker many thanks for taking the initiative to propose a UI for this very important feature.

BTW in the 2nd mock-up I'd like to see the **threads** that people start about the link.

Can someone who is knowledgeable in the Mastodon code-base point to us the views, API endpoints and front-end code that would need to be touched to implement this?

**Comment by lirontocker** [comment]
> BTW in the 2nd mock-up I'd like to see the **threads** that people start about the link.

The current behavior is that if you click on a post (for example, one of the above), you see the thread originating from that post. I agree that this isn't ideal, I would also prefer to see an embedded design, but that is a design issue across the board and not strictly related to this topic/ticket. So I'd separate this discussion probably.

**Comment by simevo** [comment]
In the 1st screenshot what you see are not posts, they are **external links**. ATM if you hover on on one you see the external link preview (example: `https://variety.com/2022/digital/news/cbs-news-pauses-twitter-posting-1235437572/`), and if you click on it you leave Mastodon.

The same link can be independently shared by different people i.e. `https://mastodon.social/@jayrosen_nyu/109371753702111164` and `https://mastodon.social/@paolog/109375897310020865`. These "initial shares" could each seed an independent thread and could even be on separate instances, in different languages etc. They may not see each other at all, currently there is no search mechanism to match them.

My proposal isto show a list of these "seeding" shares so that people can join the existing threads rather than starting a new one.

**Comment by lirontocker** [comment]
I think that is what I tried to illustrate with the wireframes above. To change the behavior of the links in the first screenshot to lead to a single (not yet existing) "news item" page which works a bit like a single-hashtag page, with one difference that the news item is highlighted at the top.

**Comment by RustoMCSpit** [comment]
> 

'The comments that people are making are more interesting and relevant than the article itself'

lmfao
