### ISSUE TITLE
Public profile page is not rendered while AUTHORIZED_FETCH mode is on

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon#19623]
### Steps to reproduce the problem

1. Upgrade to v4.0.0rc1
2. enable AUTHORIZED_FETCH mode
3. Go to some user page (eg: domain.tld/@admin)
4. The API request is failing with 401 unauthorized
...

### Expected behaviour

Render Public profile without problem

### Actual behaviour

401 error occured

### Specifications

Mastodon v4.0.0rc1 with AUTHORIZED_FETCH mode on

**Comment by trwnh** [comment]
worth noting that other implementations like pleroma behave exactly like this and do not render public views of profiles when authorized fetch is required.

**Comment by kescherCode** [comment]
In my opinion, this is too much of a difference between the now removed haml-based Web UI and the React-based one.

It does somewhat make sense for AUTHORIZED_FETCH to behave this way, but there should be an additional setting for instance owners that want to use AUTHORIZED_FETCH to have only public posts (not even unlisted ones) displayed in timelines, ideally only of local users, and that want public and unlisted posts of only local users to remain publicly linkable. This would be an improvement in compliance with AUTHORIZED_FETCH, while still allowing proper outside linking.

**Comment by kescherCode** [comment]
It may also be worth noting that some forks of Pleroma/Akkoma have a way to only show local users on timelines as well on AUTHORIZED_FETCH enabled instances, even going as far as to make any remote users unlinkable, too.

**Comment by tribela** [comment]
> and that want public and unlisted posts of only local users to remain publicly linkable. This would be an improvement in compliance with AUTHORIZED_FETCH, while still allowing proper outside linking.

Yes. public permalink should be remained even if AUTHORIZED_FETCH is enabled
