### ISSUE TITLE
/settings/profile hides header image preview at mobile widths

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#19643]
### Steps to reproduce the problem

Go to /settings/profile on a mobile device

### Expected behaviour

The preview card shows both header and avatar

### Actual behaviour

The header part is not shown

### Specifications

mastodon.social
Firefox for Android 108

**Comment by ClearlyClaire** [comment]
This is a CSS rule that applies to this card and this card only, so I don't know what the original rationale was.

**Comment by mjankowski** [comment]
Still an issue?

I see both avatar and header images/previews on this page on mobile.

**Comment by ClearlyClaire** [comment]
Pretty sure this is fixed.
