### ISSUE TITLE
scheduler::IndexingScheduler Errors filling up Dead Jobs in Sidekiq

### ISSUE THREAD

**Issue by KuJoe** [mastodon/mastodon#19646]
### Steps to reproduce the problem

1. Install Elasticsearch
2. Uninstall Elasticsearch (edit .env.production, apt remove elasticsearch, reboot server)

### Expected behaviour

The Dead Jobs log in Sidekiq should not be getting spammed by scheduler::IndexingScheduler

### Actual behaviour

scheduler::IndexingScheduler creates an error every 5 minutes

### Detailed description

scheduler::IndexingScheduler creates the following error every 5 minutes in the Dead Jobs list in Sidekiq:

Faraday::ConnectionFailed: Connection refused - Connection refused - connect(2) for "localhost" port 9200 (localhost:9200)

### Specifications

Mastodon 3.5.3

**Comment by ClearlyClaire** [comment]
Have you removed the ElasticSearch configuration from your `.env.production` and restarted Mastodon processes?

**Comment by KuJoe** [comment]
I commented the lines out, I'll try deleting them.

**Comment by KuJoe** [comment]
> Have you removed the ElasticSearch configuration from your `.env.production` and restarted Mastodon processes?

Deleting them and restarting the processes didn't fix anything, still getting the error every 5 minutes.

**Comment by Gargron** [comment]
Strange, this shouldn't be happening. I'll look into it

**Comment by ClearlyClaire** [comment]
Most likely, the jobs were already queued

**Comment by Gargron** [comment]
Correct, but the jobs are probably missing a check to give up once ElasticSearch is disabled
