### ISSUE TITLE
Promoting to Mastodon official app decreses user experience

### ISSUE THREAD

**Issue by SJang1** [mastodon/mastodon#19654]
### Pitch

After updating to 4.0.0rc1, on Safari at the top of the iPhone, now promotes Mastodon official application decreasing user experience.

- It(the mastodon app) does not have the federated timeline that webpage has.
- It uses hight a lot that so timeline is shortner
- There is lots of 3rd party apps, but it only promotes one of the app (official app)

- on the #16599 it says about PWAs, but it also appears on PWAs when scrolling up.

### Motivation

We should delete the promote of Mastodon official iOS app on the Safari.

**Comment by Gargron** [comment]
If you close the banner it never shows it again. It is not like those annoying Reddit banners that are rendered by the webpage and show up every time.
