### ISSUE TITLE
SAML nor OpenID_Connect display_name seem to be respected

### ISSUE THREAD

**Issue by samip5** [mastodon/mastodon#19666]
### Steps to reproduce the problem

1. Install Mastadon like you normally would
2. Add SAML or OpenID Connect variables to env, with an DISPLAY_NAME variable
3. Notice that the login page shows just openid_connect or saml rather than what was the variable set to.

### Expected behaviour

It should have been set to the attribute value

### Actual behaviour

It was using openid_connect or saml respectfully

### Detailed description

Despite https://github.com/mastodon/mastodon/pull/18568 being merged, it would need a new release to fix this or manually changing those.

### Specifications

Mastadon v3.5.3
Firefox 106.0.1 on Gentoo linux

**Comment by obsidiangroup** [comment]
Can also confirm on a new 3.5.3 install with OIDC configured and working properly that login button only displays "Or log in with OPENID_CONNECT".

Tried using Chrome on Windows, Android, and Ubuntu, Edge on Windows and Android, and Firefox on Windows, Android, and Ubuntu.

**Comment by ClearlyClaire** [comment]
As noted in the opening post, #18568 addresses the issue.
