### ISSUE TITLE
Followed documentation exactly, getting MIME and 404 errors on public folder and no CSS

### ISSUE THREAD

**Issue by fullStackRacc** [mastodon/mastodon#19683]
### Steps to reproduce the problem

I followed the documentation on https://docs.joinmastodon.org/admin/install/ to create an instance 

I've tried on 3 different VPSes, 2 of them with 8 GBs of RAM, and it did the same thing every time 

I am getting this every time I attempt to load Mastodon:
![image](https://user-images.githubusercontent.com/106115808/199617416-095e5692-2151-43af-b51d-8f7a29394dee.png)

I am very confused and tired and stressed and just want to figure out what's going on

### Expected behaviour

I expected the server to work

### Actual behaviour

The server did not work

### Specifications

Mastodon 3.5.3
Node 16.18.0
Ruby 3.0.3

**Comment by Gargron** [comment]
CSS and JS are compiled using webpack through the `rails assets:precompile` command (it should be executed by `mastodon:setup`). 8GB should be more than enough RAM for Webpack, so I'm not sure what could've gone wrong--try running the command again.

**Comment by fullStackRacc** [comment]
had to do assets:clobber first so it would recompile, but it's doing exactly the same thing still. I attempted to log in after I made this ticket, so right now it's just a white screen with those errors.
