### ISSUE TITLE
UI: Fuzzy display of notifications

### ISSUE THREAD

**Issue by Izorkin** [mastodon/mastodon#19699]
### Steps to reproduce the problem

1. Set light theme
2. Wait for notification

### Expected behaviour

Notifications are clearly displayed

### Actual behaviour

Fuzzy display of notifications

### Detailed description

Have to strain your eyesight or get close to the screen to see the number of notifications.

![vivaldi_2022-11-03_19-52-26](https://user-images.githubusercontent.com/26877687/199786842-b776c895-240d-4147-9316-7f88d52ed51a.png)

### Specifications

Mastodon rev https://github.com/mastodon/mastodon/commit/8f073818568b78b4adb858feb928b0da237d066a
Ruby 3.0.4
Nodejs 18.9.1

Vivaldi 5.5.2805.38 (Chrome/106.0.0.0)

**Comment by Izorkin** [comment]
@Gargron thanks, now it is better.
Can also fix the colors in the logo?
![vivaldi_2022-11-04_20-51-19](https://user-images.githubusercontent.com/26877687/200043118-db8bfa07-6c60-4020-964e-0584d9a4152f.png)

**Comment by Phroneris** [comment]
> @Gargron thanks, now it is better. Can also fix the colors in the logo? ![vivaldi_2022-11-04_20-51-19](https://user-images.githubusercontent.com/26877687/200043118-db8bfa07-6c60-4020-964e-0584d9a4152f.png)

The same opinion as mine!
I feel the purple elephant is too dark for background of black "mastodon" text.
This new logo for light theme seems like almost "■astodon" at least when it's small in size.

But you should create a separate issue for that.
