### ISSUE TITLE
Toots, follows, boosts etc from mastodon.social never reach my instance but show up on mastodon.social itself

### ISSUE THREAD

**Issue by mmeier86** [mastodon/mastodon#19710]
### Steps to reproduce the problem

1.In the Mastodon Web UI for my instance, go to a profile on mastodon.social and hit "Follow"
2. The "Follow" button has now turned into the "Unfollow" button
3. Look at my own follows in the Web UI: The new account does not show up after minutes, hours or days
4. Open the remote profile again in my instance's Web UI: The "Unfollow" button has turned into the "Cancel Follow Request" button
5. Go to the profile on mastodon.social. I appear in the "Followers" list
6. Open my remote profile on mastodon.social: The mastodon.social profile I tried to follow appears under "Following"
...

It works similarly with e.g. somebody on mastodon.social mentioning me:
1. Answer to a thread of a user on mastodon.social
2. When the mastodon.social user answers me in the thread, nothing happens on my instance - the answer never shows up in my notifications
3. When copying the URL of the answer mentioning me into the search bar in my instance's web UI, the notification for the answer suddenly shows up

### Expected behaviour

Following should have worked, and toots should reach my instance without me manually copying them.

### Actual behaviour

Following works on the mastodon.social side, but toots from people I follow never reach my instance

### Detailed description

I've got a problem in particular with mastodon.social. I'm self-hosting a mastodon instance only used by myself. I can, without problem, interact with users from other instances, e.g. fosstodon, via following, boosts, toots etc.

My instance/profile can be found [here](https://social.mei-home.net/web/@mmeier).

One more clarification: While the examples below will be from the last couple of days, I have never been able to follow mastodon.social accounts since I started my instance in August this year, I just realized it only in the last couple of days, because there never was any error message anywhere when following accounts. So I'm reasonably sure that my problem is not due to the high load on mastodon.social in the past few days.

### Following Example

Alright, let's start with following an account on mastodon.social. To get an overview of the problem, have a look at [my following tab on my own instance](https://social.mei-home.net/users/mmeier/following). Note that there's not a single mastodon.social account in there, but 38 accounts from other instances.

Then, look at my (remote? Not sure about terminology here) profile on [mastodon.social](https://mastodon.social/@mmeier@social.mei-home.net/following) and note that mastodon.social seems to think that I'm following a couple of accounts there, but my own instance seems to not know that.

Now let's take [one of my friends](https://mastodon.social/@n_develop) as an example. At the time of writing this bug, I'm following him. I also appear in his "Followers" list. On my instance, I get the "pending request" icon:

![grafik](https://user-images.githubusercontent.com/7581774/199842266-945ed15b-5166-47c8-835e-39843ec701dd.png)

![grafik](https://user-images.githubusercontent.com/7581774/199842354-57312c5f-d13d-419b-a9c7-4697ad92a368.png)

When I hit the "Cancel follow request" button, it faithfully turns back into the "Follow" button and, looking at his profile on mastodon.social, I disappear from his followers list, so on mastodon.social's side, everything seems to be working. If I hit "Follow" again, the button tuns into the "Unfollow" button and I appear in his "Followers" list on his mastodon.social profile again. But on my instance, nothing happens, and after a short while, the "Unfollow" button turns into "Cancel follow request" again.

And exactly the same happens for every single account on mastodon.social I thought I follow - but don't actually follow.

### Toots/mentions

Following does not seem to be the only problem for me. I also don't get notifications when somebody mentions me from mastodon.social. 

Take [this post](https://mastodon.social/@n_develop/109281589540033454) from the same account as above as an example. It explicitly mentions me. I never got a notification. 45 minutes after the post was made, I happened to see it while trying to figure out the "Following" problem. I then copied the post's URL into the search bar in my instance's web UI - and then I heard the ping and the mention showed up in my notifications. So now I'm a bit embarrassed that people on mastodon.social might have been trying to talk to me, and on their side it simply looked like I never bothered to answer. :-/

### One last request

Is there some corner where Mastodon admins meet for self-help? I'm at least half convinced that this is entirely my problem, but I had no idea where to post a couple of general questions.

### Specifications

Mastodon 3.5.3 in the official Docker image.
Self-hosted on a residential connection with regular reconnects around 5 AM UTC.

### Edit1

Hm, it seems that this is not restricted to mastodon.social. I've just tried following a user from mastodon.cloud, and I finally got an error message in my logs:

```
"2022-11-03T23:11:29.756Z pid=7 tid=2olmz WARN: {\"context\":\"Job raised exception\",\"job\":{\"retry\":16,\"queue\":\"push\",\"dead\":false,\"args\":[\"{\\\"@context\\\":\\\"https://www.w3.org/ns/activitystreams\\\",\\\"id\\\":\\\"https://social.mei-home.net/40b61e88-a0bf-4e08-99ad-f49b401d39da\\\",\\\"type\\\":\\\"Follow\\\",\\\"actor\\\":\\\"https://social.mei-home.net/users/mmeier\\\",\\\"object\\\":\\\"https://mastodon.cloud/users/schmichael\\\"}\",108760698623705507,\"https://mastodon.cloud/users/schmichael/inbox\"],\"class\":\"ActivityPub::DeliveryWorker\",\"jid\":\"cb6a96331e0131d0372c1fe1\",\"created_at\":1667516982.6811194,\"enqueued_at\":1667517089.6205862,\"error_message\":\"https://mastodon.cloud/users/schmichael/inbox returned code 401\",\"error_class\":\"Mastodon::UnexpectedResponseError\",\"failed_at\":1667516982.8487608,\"retry_count\":2,\"retried_at\":1667517030.9029238},\"jobstr\":\"{\\\"retry\\\":16,\\\"queue\\\":\\\"push\\\",\\\"dead\\\":false,\\\"args\\\":[\\\"{\\\\\\\"@context\\\\\\\":\\\\\\\"https://www.w3.org/ns/activitystreams\\\\\\\",\\\\\\\"id\\\\\\\":\\\\\\\"https://social.mei-home.net/40b61e88-a0bf-4e08-99ad-f49b401d39da\\\\\\\",\\\\\\\"type\\\\\\\":\\\\\\\"Follow\\\\\\\",\\\\\\\"actor\\\\\\\":\\\\\\\"https://social.mei-home.net/users/mmeier\\\\\\\",\\\\\\\"object\\\\\\\":\\\\\\\"https://mastodon.cloud/users/schmichael\\\\\\\"}\\\",108760698623705507,\\\"https://mastodon.cloud/users/schmichael/inbox\\\"],\\\"class\\\":\\\"ActivityPub::DeliveryWorker\\\",\\\"jid\\\":\\\"cb6a96331e0131d0372c1fe1\\\",\\\"created_at\\\":1667516982.6811194,\\\"enqueued_at\\\":1667517089.6205862,\\\"error_message\\\":\\\"https://mastodon.cloud/users/schmichael/inbox returned code 401\\\",\\\"error_class\\\":\\\"Mastodon::UnexpectedResponseError\\\",\\\"failed_at\\\":1667516982.8487608,\\\"retry_count\\\":2,\\\"retried_at\\\":1667517030.9029238}\"}"
```
This is even weirder - why would the inbox push return 401?

**Comment by mmeier86** [comment]
One short update: I've tried to enable debug logs in the hopes that an error might show up there, but also didn't see anything relevant.

**Comment by mmeier86** [comment]
Another update: Following people on mastodon.social now works. It must have started sometime today around 13:55 UTC. But I have no idea why that would be. I'm 100% sure I did not change anything since I did the last tests yesterday.

I will tentatively leave the issue open in the hopes that somebody might figure out the root cause.

**Comment by wbob** [comment]
I had issues following "locked" users on mastodon.online from a smaller instance the last few days when demand was high.

The follow request didn't seem to go through. Canceling and reapplying somehow ended up in the local instance thinking I follow, while the remote didn't list me anymore, and no new items were delivered by the remote to the local instance.

Unfollowing and request to follow again seemed to have solved it.

I speculate the follow-request-cancellation took effect after the follow-ack of the remote user.

**Comment by nyura123** [comment]
@mmeier86 I encountered 401 when POSTing to an inbox when my sidekiq was misconfigured. The LOCAL_DOMAIN setting was missing so it was generating the wrong keyId in Signature header (`request.rb` `signature`), causing the receiving server to reject with 401 when trying to verify the signature (it couldn't fetch the public key because of the wrong keyId). Not sure if it's at all related to your 401 but just wanted to give this bit of info.

**Comment by solick** [comment]
@nyura123 you made my day. After adding the webfinger config to my nginy reverse proxy I now receive all the messages which has been missing!

`location /.well-known/webfinger {
  return 301 https://mastodon.example.com$request_uri;
}`

**Comment by blackdiamont** [comment]
I have the same problem with my new instance (manual installation). I've checked the config (everything is correct) and even tried @solick solution but no luck :/

nginx log:
`"POST /inbox HTTP/1.1" 401 150 "-" "http.rb/5.1.0 (Mastodon/4.0.2; +https://mastodon.social/)"
"POST /inbox HTTP/1.1" 401 152 "-" "http.rb/5.0.4 (Mastodon/3.5.5; +https://mastodon.matrix.org/)"
`
mastodon-web log:
`method=POST path=/users/blackdiamont/inbox format=html controller=ActivityPub::InboxesController action=create status=401 duration=187.93 view=0.50 db=7.88 key=https://mastodon.matrix.org/users/matrix#main-key`

**Comment by nyura123** [comment]
@blackdiamont not sure if it's the same issue, might be worth opening a new one? fwiw I can't see `blackdiamont` user on either mastodon.social or mastodon.matrix.org (https://mastodon.social/@blackdiamont, https://mastodon.matrix.org/@blackdiamont)

**Comment by drboone** [comment]
I seem to have almost exactly the same problem as the OP.  LOCAL_DOMAIN was never broken in my setup, though I did end up having to add an ALTERNATE_DOMAIN.  The /.well-known item described above does not seem to have made any difference.

**Comment by blackdiamont** [comment]
@nyura123 It is the same problem. I'm listed as follower -> https://mastodon.social/@blackdiamont@mastodon.mystic-welten.de for https://mastodon.social/@computerbase but its on "withdraw follow request" if I check the profile.
Same with matrix etc

**Comment by nyura123** [comment]
@blackdiamont I'm new to Mastodon myself so could be wrong but from your logs, it looks like the 401s are being generated by your server. Since you're listed as a follower on mastodon.social, it means it processed your Follow request ok, but maybe your server rejected/did not process the Accept Follow message. And it's probably rejecting incoming posts too (the `action=create` shown in your log). 

In my case it was the opposite, the 401 was generated by the remote server in response to my (badly formed) Follow request

**Comment by mmeier86** [comment]
@blackdiamont I'm afraid I also can't help you. The behaviour you describe is exactly the same I was seeing. But for mastodon.social, it just magically solved itself after a couple of days. Suddenly, I could just start following people on mastodon.social. The second problem I described, where I get 401 errors from some remote servers when trying to follow people there, is still present though.

**Comment by blackdiamont** [comment]
@mmeier86 Thanks for your reply. I've noticed that messages starts appearing on the Federated tab. Maybe it's just a network problem because many peeps joining mastodon from twitter?
The people I've started following still shows cancel but maybe it will fix itself after a while too.

Just guesses but who knows :)

**Comment by drboone** [comment]
This problem seems to me like it is probably related to PKI.  Based on other issues and discussions I've read, I think that if the domain name setup changes, these keys break.  The LOCAL_DOMAIN of my instance hasn't changed, but my instance is behind an haproxy, so there's a chance there's another way to break this.  Is there anyone who can explain how the PKI bits work, and/or help me walk through settings and database records at that level?  @ClearlyClaire @Gargron ?

**Comment by Foritus** [comment]
This is broken for me too. I suspect almost certainly because I'm behind an nginx reverse proxy, but I have no useful logs to go from at all. I can see the web server rejecting federation-related traffic, e.g.

```
Nov 20 21:48:53 mastodon bundle[2169]: [1300b456cf5b53eb0a046518cd4ea430] method=POST path=/inbox format=html controller=ActivityPub::InboxesController action=create status=202 duration=19.00 view=0.00 db=2.31 key=https://masto.ai/users/inpt#main-key
```

Is there any way to log out more details to see why it's rejecting the requests?

**Comment by drboone** [comment]
I think you should be able to put `RAILS_LOG_LEVEL=debug` into your environment file to raise the log level.

**Comment by Foritus** [comment]
Thanks for the tip :)

Unfortunately, nothing obviously stands out. e.g. for this request with trace id 0363ca61a3f94871744e991d70c448a0 I can see some DB queries that all look normal and then it suddenly 401's 🤔 

> Nov 20 22:00:21 mastodon bundle[2430]: [0363ca61a3f94871744e991d70c448a0]   Account Load (7.8ms)  SELECT "accounts"."id", "accounts"."username", "accounts"."domain", "accounts"."private_key", "accounts"."public_key", "accounts"."created_at", "accounts"."updated_at", "accounts"."note", "accounts"."display_name", "accounts"."uri", "accounts"."url", "accounts"."avatar_file_name", "accounts"."avatar_content_type", "accounts"."avatar_file_size", "accounts"."avatar_updated_at", "accounts"."header_file_name", "accounts"."header_content_type", "accounts"."header_file_size", "accounts"."header_updated_at", "accounts"."avatar_remote_url", "accounts"."locked", "accounts"."header_remote_url", "accounts"."last_webfingered_at", "accounts"."inbox_url", "accounts"."outbox_url", "accounts"."shared_inbox_url", "accounts"."followers_url", "accounts"."protocol", "accounts"."memorial", "accounts"."moved_to_account_id", "accounts"."featured_collection_url", "accounts"."fields", "accounts"."actor_type", "accounts"."discoverable", "accounts"."also_known_as", "accounts"."silenced_at", "accounts"."suspended_at", "accounts"."hide_collections", "accounts"."avatar_storage_schema_version", "accounts"."header_storage_schema_version", "accounts"."devices_url", "accounts"."suspension_origin", "accounts"."sensitized_at", "accounts"."trendable", "accounts"."reviewed_at", "accounts"."requested_review_at" FROM "accounts" WHERE LOWER("accounts"."username") != '' AND LOWER("accounts"."username") = 'dusepo' AND LOWER("accounts"."domain") IS NULL ORDER BY "accounts"."id" ASC LIMIT $1  [["LIMIT", 1]]

>Nov 20 22:00:21 mastodon bundle[2430]: [0363ca61a3f94871744e991d70c448a0]   User Load (2.2ms)  SELECT "users"."id", "users"."email", "users"."created_at", "users"."updated_at", "users"."encrypted_password", "users"."reset_password_token", "users"."reset_password_sent_at", "users"."sign_in_count", "users"."current_sign_in_at", "users"."last_sign_in_at", "users"."admin", "users"."confirmation_token", "users"."confirmed_at", "users"."confirmation_sent_at", "users"."unconfirmed_email", "users"."locale", "users"."encrypted_otp_secret", "users"."encrypted_otp_secret_iv", "users"."encrypted_otp_secret_salt", "users"."consumed_timestep", "users"."otp_required_for_login", "users"."last_emailed_at", "users"."otp_backup_codes", "users"."account_id", "users"."disabled", "users"."moderator", "users"."invite_id", "users"."chosen_languages", "users"."created_by_application_id", "users"."approved", "users"."sign_in_token", "users"."sign_in_token_sent_at", "users"."webauthn_id", "users"."sign_up_ip", "users"."role_id" FROM "users" WHERE "users"."account_id" = $1 LIMIT $2  [["account_id", 109377973941609422], ["LI
MIT", 1]]

>Nov 20 22:00:21 mastodon bundle[2430]: [0363ca61a3f94871744e991d70c448a0]   DomainBlock Load (2.5ms)  SELECT "domain_blocks".* FROM "domain_blocks" WHERE "domain_blocks"."domain" IN ($1, $2, $3) ORDER BY char_length(domain) desc LIMIT $4  [["domain", "mastodon.thomaspreece.net"], ["domain", "thomaspreece.net"], ["domain", "net"], ["LIMIT", 1]]
>Nov 20 22:00:21 mastodon bundle[2430]: [0363ca61a3f94871744e991d70c448a0]   Account Load (4.9ms)  SELECT "accounts"."id", "accounts"."username", "accounts"."domain", "accounts"."private_key", "accounts"."public_key", "accounts"."created_at", "accounts"."updated_at", "accounts"."note", "accounts"."display_name", "accounts"."uri", "accounts"."url", "accounts"."avatar_file_name", "accounts"."avatar_content_type", "accounts"."avatar_file_size", "accounts"."avatar_updated_at", "accounts"."header_file_name", "accounts"."header_content_type", "accounts"."header_file_size", "accounts"."header_updated_at", "accounts"."avatar_remote_url", "accounts"."locked", "accounts"."header_remote_url", "accounts"."last_webfingered_at", "accounts"."inbox_url", "accounts"."outbox_url", "accounts"."shared_inbox_url", "accounts"."followers_url", "accounts"."protocol", "accounts"."memorial", "accounts"."moved_to_account_id", "accounts"."featured_collection_url", "accounts"."fields", "accounts"."actor_type", "accounts"."discoverable", "accounts"."also_known_as", "accounts"."silenced_at", "accounts"."suspended_at", "accounts"."hide_collections", "accounts"."avatar_storage_schema_version", "accounts"."header_storage_schema_version", "accounts"."devices_url", "accounts"."suspension_origin", "accounts"."sensitized_at", "accounts"."trendable", "accounts"."reviewed_at", "accounts"."requested_review_at" FROM "accounts" WHERE "accounts"."uri" = $1 LIMIT $2  [["uri", "https://mastodon.thomaspreece.net/users/thomas"], ["LIMIT", 1]]

>Nov 20 22:00:21 mastodon bundle[2430]: [0363ca61a3f94871744e991d70c448a0]   CACHE DomainBlock Load (0.1ms)  SELECT "domain_blocks".* FROM "domain_blocks" WHERE "domain_blocks"."domain" IN ($1, $2, $3) ORDER BY char_length(domain) desc LIMIT $4  [["domain", "mastodon.thomaspreece.net"], ["domain", "thomaspreece.net"], ["domain", "net"], ["LIMIT", 1]]

>Nov 20 22:00:21 mastodon bundle[2430]: [0363ca61a3f94871744e991d70c448a0]   Account Load (3.2ms)  SELECT "accounts"."id", "accounts"."username", "accounts"."domain", "accounts"."private_key", "accounts"."public_key", "accounts"."created_at", "accounts"."updated_at", "accounts"."note", "accounts"."display_name", "accounts"."uri", "accounts"."url", "accounts"."avatar_file_name", "accounts"."avatar_content_type", "accounts"."avatar_file_size", "accounts"."avatar_updated_at", "accounts"."header_file_name", "accounts"."header_content_type", "accounts"."header_file_size", "accounts"."header_updated_at", "accounts"."avatar_remote_url", "accounts"."locked", "accounts"."header_remote_url", "accounts"."last_webfingered_at", "accounts"."inbox_url", "accounts"."outbox_url", "accounts"."shared_inbox_url", "accounts"."followers_url", "accounts"."protocol", "accounts"."memorial", "accounts"."moved_to_account_id", "accounts"."featured_collection_url", "accounts"."fields", "accounts"."actor_type", "accounts"."discoverable", "accounts"."also_known_as", "accounts"."silenced_at", "accounts"."suspended_at", "accounts"."hide_collections", "accounts"."avatar_storage_schema_version", "accounts"."header_storage_schema_version", "accounts"."devices_url", "accounts"."suspension_origin", "accounts"."sensitized_at", "accounts"."trendable", "accounts"."reviewed_at", "accounts"."requested_review_at" FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2  [["id", -99], ["LIMIT", 1]]

>Nov 20 22:00:21 mastodon bundle[2430]: [0363ca61a3f94871744e991d70c448a0] [httplog] GET https://mastodon.thomaspreece.net/users/thomas completed with status code 200 in 0.419193 seconds

>Nov 20 22:00:21 mastodon bundle[2430]: [0363ca61a3f94871744e991d70c448a0]   CACHE DomainBlock Load (0.0ms)  SELECT "domain_blocks".* FROM "domain_blocks" WHERE "domain_blocks"."domain" IN ($1, $2, $3) ORDER BY char_length(domain) desc LIMIT $4  [["domain", "mastodon.thomaspreece.net"], ["domain", "thomaspreece.net"], ["domain", "net"], ["LIMIT", 1]]

>Nov 20 22:00:21 mastodon bundle[2430]: [0363ca61a3f94871744e991d70c448a0]   Account Load (2.5ms)  SELECT "accounts"."id", "accounts"."username", "accounts"."domain", "accounts"."private_key", "accounts"."public_key", "accounts"."created_at", "accounts"."updated_at", "accounts"."note", "accounts"."display_name", "accounts"."uri", "accounts"."url", "accounts"."avatar_file_name", "accounts"."avatar_content_type", "accounts"."avatar_file_size", "accounts"."avatar_updated_at", "accounts"."header_file_name", "accounts"."header_content_type", "accounts"."header_file_size", "accounts"."header_updated_at", "accounts"."avatar_remote_url", "accounts"."locked", "accounts"."header_remote_url", "accounts"."last_webfingered_at", "accounts"."inbox_url", "accounts"."outbox_url", "accounts"."shared_inbox_url", "accounts"."followers_url", "accounts"."protocol", "accounts"."memorial", "accounts"."moved_to_account_id", "accounts"."featured_collection_url", "accounts"."fields", "accounts"."actor_type", "accounts"."discoverable", "accounts"."also_known_as", "accounts"."silenced_at", "accounts"."suspended_at", "accounts"."hide_collections", "accounts"."avatar_storage_schema_version", "accounts"."header_storage_schema_version", "accounts"."devices_url", "accounts"."suspension_origin", "accounts"."sensitized_at", "accounts"."trendable", "accounts"."reviewed_at", "accounts"."requested_review_at" FROM "accounts" WHERE "accounts"."domain" IS NOT NULL AND "accounts"."uri" = $1 LIMIT $2  [["uri", "https://mastodon.thomaspreece.net/users/thomas"], ["LIMIT", 1]]

>Nov 20 22:00:21 mastodon bundle[2430]: [0363ca61a3f94871744e991d70c448a0] method=POST path=/users/dusepo/inbox format=html controller=ActivityPub::InboxesController action=create status=401 duration=515.17 view=0.57 db=23.23 key=https://mastodon.thomaspreece.net/users/thomas#main-key

**Comment by Foritus** [comment]
Ok I think I solved my particular case. It was due to an intermediate reverse proxy sending requests on one of my ALTERNATE_DOMAINs, which seems to break some kind of host validation in the federation. In my nginx reverse proxy I added these:

in `location @proxy`:
```
    proxy_set_header Host "MY_LOCAL_DOMAIN"; # Override the host that is sent to ensure it matches the domain expected by federation
```
and the same inside `location ^~ /api/v1/streaming {`, and suddenly everything started working. The error logging around this failure mode is still pretty awful, so this was more old-man-psychic-debugging rather than science though 🙂

**Comment by drboone** [comment]
Does seem to have helped mine too.  Many thanks!

**Comment by 100terres** [comment]
I add a really similar issue!

I'm running the server on `mastodon.fedi.100terres.com` (`WEB_DOMAIN` env), but the network domain I'm using is `100terres.com` (`LOCAL_DOMAIN` env). I wasn't able to follow anyone on other instances.

The redirection suggestion from @solick was the right one :tada: 

> `location /.well-known/webfinger { return 301 https://mastodon.example.com$request_uri; }`

I'm hosting my personal website on `100terres.com` and that's why I couldn't have my instance there. I used `mastodon.fedi.100terres.com` instead.

I guest the issue was that when I'm was trying to follow people on other instances, there was a verification step being made by the instances to verify that the request was legitimate. From what I understand to do this verification step they are using the `/.well-known/webfinger` URI using the `LOCAL_DOMAIN` to do it. `100terres.com/.well-known/webfinger` doesn't respond the right thing when the other instances do their verifications. That's why they are returning a 401 authorization error.

To solve this, I did what @solick suggested and I redirected all traffics hitting `100terres.com/.well-known/webfinger?resource=acct:*` and redirected it to `https://mastodon.fedi.100terres.com/.well-known/webfinger?resource=acct:*` which return the expected payload. I'm using cloudflare so I was able to quickly create a page rules to do the rediection, but you can do this in NGNIX, traefik, etc. Once I tested that the rediction was working, I restarted all the failed jobs in sidekiq and it worked!

Thank you again @solick!

---

@Gargron I'm not 100% sure that this was the issue I faced, because I didn't dig into the codebase and do not know enough about the webfinger spec, but if that was the issue I think the documentation regarding [Webfinger](https://docs.joinmastodon.org/spec/webfinger/) (or somewhere else) should mentioned that when the `WEB_DOMAIN` env isn't the same as `LOCAL_DOMAIN` we should redirect request from `LOCAL_DOMAIN/.well-known/webfinger` to `WEB_DOMAIN/.well-known/webfinger`. _(Sorry if it's already there and I missed it.)_

**Comment by blackdiamont** [comment]
> Ok I think I solved my particular case. It was due to an intermediate reverse proxy sending requests on one of my ALTERNATE_DOMAINs, which seems to break some kind of host validation in the federation. In my nginx reverse proxy I added these:
> 
> in `location @proxy`:
> 
> ```
>     proxy_set_header Host "MY_LOCAL_DOMAIN"; # Override the host that is sent to ensure it matches the domain expected by federation
> ```
> 
> and the same inside `location ^~ /api/v1/streaming {`, and suddenly everything started working. The error logging around this failure mode is still pretty awful, so this was more old-man-psychic-debugging rather than science though slightly_smiling_face

That worked for me! I'm using apache as reverse proxy and added the header to the config.
Now following works! And I don't see any 401 anymore :)
Thank you so much!

**Comment by solick** [comment]
@100terres glad my solution works for you too.

**Comment by nightpool** [comment]
Hi all, glad the issue here seems to be resolved. The original issue seems to have just been standard federation lag due to mastodon.social being overloaded, and any follow-up posts should be directed to the Discussions Q&A forum for troubleshooting. Thanks!

**Comment by drboone** [comment]
Some of the issues reported by posters to this issue were _not_ "standard federation lag", but rather issues with proxies, or with nginx configuration around the /.well-known url space.
