### ISSUE TITLE
Feature Request: Allow using only U2F/security keys instead of forcing to use TOTP to use U2F

### ISSUE THREAD

**Issue by miicat** [mastodon/mastodon#19722]
### Pitch

The security is only as strong as weakest link. In this case you are forced to use TOTP, which is not as secure as U2F.

[Birdsite](https://twitter.com), [Cloudflare](https://cloudflare.com), [SimpleLogin](https://simplelogin.io), [PyPI](https://pypi.org) and [BitWarden](https://bitwarden.com) has implemented it this way for example

## Features/changes:

* Allow adding just the security keys/make TOTP optional
* If there is some places that won't work with just security keys enabled, show a warning before enabling just the keys

Not really related to this issue, but it would be nice to support Fido2 resident credentials (or WebAuthn, which I think supports that) :D

### Motivation

Currently it doesn't really matter if you add security keys or not. As the attacker can use the weakest 2FA method (TOTP)

**Comment by ClearlyClaire** [comment]
Duplicate of #16693 as far as I can tell (feel free to reopen if you disagree).
