### ISSUE TITLE
[Query] nginx 404 when POSTing to remote /f/inbox

### ISSUE THREAD

**Issue by evoLucidity** [mastodon/mastodon#19736]
### Steps to reproduce the problem

1. Observe nginx access logs for mastodon instance 
2. See expected 200/202 codes for most interactions inc. POST to `/inbox` of remote servers
3. See 404 code when POST attempted to `/f/inbox` of remote server
...

### Expected behaviour

Should attempt be successful?

### Actual behaviour

404 code returned

### Detailed description

````
10.0.0.254 - - [04/Nov/2022:14:26:26 +0000] "POST /receive/public HTTP/1.1" 202 5 "-" "DiasporaFederation/0.2.8"
10.0.0.254 - - [04/Nov/2022:14:26:28 +0000] "POST /receive/public HTTP/1.1" 202 5 "-" "DiasporaFederation/0.2.8"
10.0.0.254 - - [04/Nov/2022:14:26:30 +0000] "POST /inbox HTTP/1.1" 202 31 "-" "http.rb/5.1.0 (Mastodon/4.0.0rc1; +https://mstdn.social/)"
10.0.0.254 - - [04/Nov/2022:14:26:31 +0000] "POST /f/inbox HTTP/1.1" 404 1989 "-" "http.rb/5.0.4 (Mastodon/3.5.3; +https://photog.social/)"
10.0.0.254 - - [04/Nov/2022:14:26:31 +0000] "POST /f/inbox HTTP/1.1" 404 1989 "-" "http.rb/5.0.4 (Mastodon/3.5.3; +https://sueden.social/)"
10.0.0.254 - - [04/Nov/2022:14:26:35 +0000] "POST /receive/public HTTP/1.1" 202 5 "-" "DiasporaFederation/0.2.8"
````

### Specifications

Mastodon v3.5.3

**Comment by ClearlyClaire** [comment]
`/f/inbox` is typically not an endpoint that Mastodon would use/serve. Neither is `/receive/public`.

Are you really running Mastodon? If so, were you previously running some other fediverse software on the same domain name? Or are you running some other fediverse software alongside it?

**Comment by evoLucidity** [comment]
Apologies. More haste, less speed needed. Please see entries from log that are actually relevant to query!

````
10.0.0.254 - - [04/Nov/2022:14:51:12 +0000] "POST /f/inbox HTTP/1.1" 404 1989 "-" "http.rb/5.1.0 (Mastodon/3.5.3+glitch; +https://social.dev-wiki.de/)"
10.0.0.254 - - [04/Nov/2022:14:51:35 +0000] "POST /inbox HTTP/1.1" 202 31 "-" "http.rb/5.0.4 (Mastodon/3.5.3; +https://awscommunity.social/)"
10.0.0.254 - - [04/Nov/2022:14:51:53 +0000] "POST /inbox HTTP/1.1" 202 31 "-" "http.rb/5.1.0 (Mastodon/3.5.3+glitch; +https://eldritch.cafe/)"
10.0.0.254 - - [04/Nov/2022:14:52:08 +0000] "POST /inbox HTTP/1.1" 202 31 "-" "http.rb/5.0.4 (Mastodon/3.5.3; +https://mastodon.me.uk/)"
10.0.0.254 - - [04/Nov/2022:14:52:30 +0000] "POST /f/inbox HTTP/1.1" 404 1989 "-" "http.rb/5.0.4 (Mastodon/3.5.3; +https://awscommunity.social/)"
10.0.0.254 - - [04/Nov/2022:14:52:35 +0000] "POST /inbox HTTP/1.1" 202 31 "-" "http.rb/5.0.4 (Mastodon/3.5.3; +https://mastodon.me.uk/)"
````

**Comment by evoLucidity** [comment]
If it's relevant, I'm also running latest versions of Diaspora, Friendica, Pixelfed and Peertube.

**Comment by ClearlyClaire** [comment]
> If it's relevant, I'm also running latest versions of Diaspora, Friendica, Pixelfed and Peertube.

Are the logs you are showing from Diaspora, Friendica, Pixelfed or Peertube? It looks like you may have an error in your nginx config and mixing up services, Mastodon should never expose a `/f/inbox` endpoint, so remote services should not try to use it.

**Comment by evoLucidity** [comment]
I'll make Mastodon use it's own nginx access log to make sure. I'll report back shortly.

**Comment by evoLucidity** [comment]
It's actually coming from my Pixelfed instance! Sorry, I'll go ask them.
Thanks for helping! :-)
