### ISSUE TITLE
Notifications and replies take at least 12 minutes in showing up

### ISSUE THREAD

**Issue by monbrielle** [mastodon/mastodon#19745]
### Steps to reproduce the problem

Someone replied to me for example 12 minutes ago and Im just getting his/her reply which slows down the conversation a lot considering the other person is waiting for it right away. Is it a bug or this is how Mastodon works?

### Expected behaviour

Replies showing right away

### Actual behaviour

Taking 12 minutes

### Specifications

![image](https://user-images.githubusercontent.com/11840819/200028303-b73e74b6-6bce-4540-afa0-716a17262c29.png)

**Comment by Gargron** [comment]
Please do not report operational issues with specific servers to this repository.
