### ISSUE TITLE
With a user on an instance running 3.5.3 can't follow a user running v4.0.0rc1 using web

### ISSUE THREAD

**Issue by mcfly** [mastodon/mastodon#19749]
### Steps to reproduce the problem

0. On web version of a 3.5.3 instance (chaos.social)
1. Go to account of user on https://mastodon.social/@Gargron
2. click on follow
3. follow eugen window opens
4. click on "copy to clipboard" 
5. gets back to https://mastodon.social/@Gargron
...

This is reproducable on all users that are on servers running 4.0rc1

Following users that are on a server running 3.5.3 work fine

### Expected behaviour

5. Possibility to follow user

### Actual behaviour

can't follow, gets back to @gargon's page

### Specifications

web version on Mastodon 4.0rc1

Myself running on 3.5.3 with firefox 106.0.3

**Comment by ClearlyClaire** [comment]
I am not sure I understand your report. “Copy to clipboard” copies the account's URL to you clipboard. You are not supposed to paste it in your browser's address bar, but in your Mastodon client's (including the web client) search bar.

**Comment by mcfly** [comment]
Yeah, i am looking for the facepalm emoticon. This can be closed. 

Maybe its worth updating the wording there but yes. you are right and i am stoopid. 

Sorry for this one.

**Comment by davidvasandani** [comment]
fwiw I got caught by this as well.

**Comment by ClearlyClaire** [comment]
> Yeah, i am looking for the facepalm emoticon. This can be closed.
> 
> Maybe its worth updating the wording there but yes. you are right and i am stoopid.
> 
> Sorry for this one.

No worries, you aren't the first one to fall into that one, so we definitely need to do something around that.
