### ISSUE TITLE
yarn install and assets:precompile fail on emoji-mart in v3.5.3

### ISSUE THREAD

**Issue by chronos-tachyon** [mastodon/mastodon#19755]
### Steps to reproduce the problem

1. Install Mastodon from source by following https://docs.joinmastodon.org/admin/install/

### Expected behaviour

Mastodon is installed correctly, without needing to manually modify package.json using "yarn add"

### Actual behaviour

Mastodon installation fails at the "yarn install" step

### Detailed description

The installation fails with `emoji-mart@npm:emoji-mart-lazyload: Registry failed to return tag "emoji-mart-lazyload"`

I successfully worked around the issue by running:

> `yarn add emoji-mart@npm:emoji-mart-lazyload@^3.0.1-j`

Omitting the version spec for `emoji-mart-lazyload` makes yarn very confused.

### Specifications

* Mastodon v3.5.3
* ruby `3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [aarch64-linux]`
* node v14.21.1
* yarn 3.2.4
* npm 6.14.17
* Ubuntu 22.04.1 LTS

**Comment by kmeisthax** [comment]
I had essentially the same bug. The only difference was that Yarn said there were no candidates rather than the error you got. Your workaround worked just the same.
