### ISSUE TITLE
Mobile view: No search bar - Cannot search for users

### ISSUE THREAD

**Issue by math-GH** [mastodon/mastodon#19768]
### Steps to reproduce the problem

Use case: As a user I want to follow a person. I know her username.

1. Open mastodon.social on your mobile phone
2. search for the search bar
3. cannot find the search bar
4. so I cannot follow her

### Expected behaviour

a icon to open the search bar

### Actual behaviour

no search bar

### Detailed description

Table view:
![grafik](https://user-images.githubusercontent.com/1645099/200114790-a8d7f6ee-7ad1-4acb-9108-ed52fb041c84.png)

Mobile view:
![grafik](https://user-images.githubusercontent.com/1645099/200114843-220226b0-20db-4341-9b1b-1c20bf5c0c77.png)

Normal view with search bar:
![grafik](https://user-images.githubusercontent.com/1645099/200114942-cd369421-47b3-4714-ad2f-8ce8ca7e2412.png)

### Specifications

Mastodon on mastodon.social (4.0.0RC1)

**Comment by connyduck** [comment]
You can search in the "# Explore" (Entdecken) view. Took me a while to find that as well. Very confusing, this should be changed.

**Comment by ionpro** [comment]
I believe the Search bar visible in the #Explore view is only visible when the viewport is under 630px wide, but the left-hand column is only visible when the viewport is over 896px wide. In between those two, I don't see any easy way to Search. This is particularly problematic as the default viewport with of an ipad is in this range.

Viewport at 896px wide
896px: <img src="https://www.uniqueish.com/github/mastodon_bug_19768/Viewport896px.png">

In between, the web interface does not appear to have a Search bar. 
894px: <img src="https://www.uniqueish.com/github/mastodon_bug_19768/Viewport894px.png">
631px: <img src="https://www.uniqueish.com/github/mastodon_bug_19768/Viewport631px.png">

There is some oddness at 895px wide as well, where the left column disappears but the Search option does not appear in the nav.
895px: <img src="https://www.uniqueish.com/github/mastodon_bug_19768/Viewport895px.png">

The Search box appears in the single-column UI at 630px where "#Explore" was before:
630px: <img src="https://www.uniqueish.com/github/mastodon_bug_19768/Viewport630px.png">

I'm guessing this is a CSS media query issue, but I'm not sure where to poke to find the CSS in this case. Perhaps I'm missing a third location for the search box at these widths; if so, please point me to them, thanks!

**Comment by dsalt** [comment]
Similar situation now (4.0.2). It would make sense to me for the search box, or an icon for it, to be in the top area, left of the “publish” button – and, for that matter, for the hashtag list to be shown unless the rightmost column is collapsed.

(Desktop browser, but normally kept to ~1000px wide for reasons including convenient tiling with other windows and too-wide text columns on various sites.)

**Comment by Takiro** [comment]
For the Mobile web view, I think it would already help a lot, if the icon for the Explore tab would be a magnifying glass instead of a hashtag, also makes more sense from a semantic point.

**Comment by frabcus** [comment]
A poor workaround I just did when I hit this problem - editing the URL to /search as the path takes to a search page with a visible search box. I'm on mastodon.social

**Comment by math-GH** [comment]
The search button is available now in Mastodon 4.2
