### ISSUE TITLE
Hide followers count not working

### ISSUE THREAD

**Issue by njmulsqb** [mastodon/mastodon#19763]
### Steps to reproduce the problem

1. Open Settings --> Preferences --> Others
2. Check "Hide followers count"
3. Save changes
...
After saving changes, the check box will be unchecked itself and settings will be reverted.

### Expected behaviour

Followers count should be hidden

### Actual behaviour

Followers count not hiding even by enabling in settings.

### Detailed description

I checked 
![image](https://user-images.githubusercontent.com/47940898/200108026-c88cda3d-26bb-44b5-8be7-c05a32120e85.png)
the checkbox and clicked on save changes but it reverted on itself and I cant hide my followers.

The server is @infosec.exchange

### Specifications

Firefox
Windows 11

**Comment by trwnh** [comment]
This is not part of mainline Mastodon -- it appears to be a change in infosec.exchange's fork of Mastodon. (Arguably, mainline Mastodon should have a way to hide the counts, but that's out of scope of this issue.)

**Comment by ClearlyClaire** [comment]
This is a glitch-soc bug! I'll have a look.
