### ISSUE TITLE
Feedback on List imports

### ISSUE THREAD

**Issue by rscmbbng** [mastodon/mastodon#19770]
### Pitch

Currently there is no feedback when using the import functionality. Upon uploading for example a list of followers you are only greeted with: "Your data was successfully uploaded and will be processed in due time."

Upon completion it would be good to receive a notification which tells me that based on my import I am now following x, y and z.

Right now it seems to succeed or fail silently.

### Motivation

The current TwitterMigration has made people generate or share lists of people to follow. Tools like https://fedifinder.glitch.me similarly are based on the importing of lists of followers. The lack of feedback from the interface however does not help for people to know whether their actions succeeded or not.

**Comment by ClearlyClaire** [comment]
Hi! Imports feedback is something I have wanted to do for a while but never got around to. Whether it is running, how many items successfully imported, if there were any errors, and so on.

It'll require a bit of work and I'm not sure when we'll be able to take care of it, though.

**Comment by dangpzanco** [comment]
Also, without the feedback, the user is more likely to submit duplicate import lists. If high demand is a problem to the server, this might slow things down even further.

**Comment by trwnh** [comment]
Fixed by #21054 i think. if not, comment here so the issue can be reopened
