### ISSUE TITLE
Follow a person from a toot

### ISSUE THREAD

**Issue by brendanjones** [mastodon/mastodon#19802]
### Pitch

Following someone takes too many steps. I'd like to be able to follow anyone directly from any of my timelines, without ever leaving the toot.

Solution: 
- add `Follow [username]` to the ellipsis menu on a toot.
- Upon following the person, display some kind of confirmation to the user. That could be a confirmation message somewhere in the UI, and/or adding info to the followed person's toot like suggested on https://github.com/mastodon/mastodon/issues/15403.

<img width="1175" alt="Screen Shot 2022-11-05 at 21 47 03" src="https://user-images.githubusercontent.com/16049594/200140832-17541528-60e8-4059-ac2b-56e84b89597e.png">

I feel like someone must have requested this already but I can't find it ...

### Motivation

Following someone now takes too many steps. My proposal means a follow is max two clicks away, and you never have to leave the toot you're looking at.

**Comment by trwnh** [comment]
A lot of users have important information in their bio that should be read before following. Arguably, having a dedicated follow button straight from the status would encourage a lack of courtesy.

**Comment by brendanjones** [comment]
What kind of info? I mean maybe you already know who the person is, or you've seen a number of their toots and you know you like their content. What would be discourteous about following them then? It's not like adding this option removes the ability to go look at their profile, you'd still be able to do that if you don't know who they are.

I loathe to say "but on Twitter ...", but I guess I've gotten used to having the person's profile info on the sidebar, or on hover of their name.

<img width="1151" alt="Screen Shot 2022-11-05 at 22 19 16" src="https://user-images.githubusercontent.com/16049594/200141781-4a277ec0-6029-43ad-a714-42f2e233b57c.png">

**Comment by brendanjones** [comment]
Oh hey, Github does it also!
<img width="475" alt="Screen Shot 2022-11-05 at 22 22 37" src="https://user-images.githubusercontent.com/16049594/200141882-b4167ca1-3676-4f93-948e-61600b3a6c25.png">

**Comment by trwnh** [comment]
See #14918 for that

**Comment by trwnh** [comment]
>What kind of info?

Essentially, the cultural standards on the fediverse are different. We don't have "private accounts" in the same way as Twitter, but we do have "manually approve followers". Many users enable this feature to have some control over who follows them, as they don't want just anybody to be able to see their followers-only posts. Typically, users will have some extra information in their bio or pinned posts describing some criteria for sending a follow request -- often something like "please interact before following", or "DM me with an introduction first", or other such requests.

**Comment by Cassolotl** [comment]
I asked for this way back in 2019:

*On the toot menu in public timelines, "follow" should be an option alongside block, mute, etc. #10919*

I put "public timelines" in the title, but yeah, basically anywhere you can see a post from someone you don't follow, you should be able to follow them very easily.

**Comment by jebarjonet** [comment]
Following someone immediately from a great toot they did sounds convenient most of the time. If it is not specifically restricted by settings or user preferences of the author, why hide it ?

If courtesy is a primary criteria, readers should probably not be able to send a private message from that same menu ? It sounds more invasive than following to me.

Maybe people validating following requests should have a different button then ? Like "Read profile" instead of "Follow". It is all about helping the reader keep in touch with an author they like in the end.

**Comment by brendanjones** [comment]
> I asked for this way back in 2019:
> 
> _On the toot menu in public timelines, "follow" should be an option alongside block, mute, etc. #10919_
> 
> I put "public timelines" in the title, but yeah, basically anywhere you can see a post from someone you don't follow, you should be able to follow them very easily.

Oh bother, I didn't find that one in search. This is duplicate then. I'll close.
