### ISSUE TITLE
Follow a hashtag & filter on hashtags

### ISSUE THREAD

**Issue by brendanjones** [mastodon/mastodon#19800]
### Pitch

Hashtags are wonderful and useful. I'd like more ways of using them, in order to discover content in which I'm interested.

Problems with the current timeline view of a hashtag ( `https://[intance]/web/tags/[hashtag]` ):
1. It's temporary. It's not one of your selectable timelines, you have to navigate to it anew every time
2. Takes too many clicks to get to.
3. For pinned hashtag views, that functionality is only available in advanced view.

Current ways of getting to a hashtag timeline:
- Select search box > Search '#[hastag]' > select hashtag
- Select search box > Search '[hashtag]' > select hashtag
- Happen to see a post in your feed with the hashtag in it > click on the hashtag

Ideas
- Allow filtering your timeline(s) with hashtags. Only see toots in the timeline containing the selected hashtags.
- Allow following hashtags on your home timeline - see toots from people you don't follow that contain the hashtag.
- Allow following hashtags in lists - see toots from people you don't follow that contain the hashtag.
-- The difference in lists being that you don't necessarily have to follow anyone in the list, so you could have a list that's just showing content from one hashtag.
-- Limiting it to a list also wouldn't flood your home timeline with federated content.
-- It'd be nice to be able to set boundaries for following hashtags in lists, i.e. "from people I'm following", "from this server", "from the federation".
-- You could add a button to a hashtag timeline view labelled "Save as list", to save any hashtag as a list. e.g. if you did it on `https://[instance]/web/tags/climate` then you'd create a list labelled #climate, following that hashtag.

This is a lot of requests, it could easily be split up into smaller pieces of work.

### Motivation

These features are especially useful to new users without many follows to populate their timeline, but also useful to experienced users looking to refine the content they see.

/edit: Of course I only found these _after_ making this issue. Somewhat duplicate, but different implementations:
- https://github.com/mastodon/mastodon/issues/7692
- https://github.com/mastodon/mastodon/issues/11091
- https://github.com/mastodon/mastodon/issues/18239

**Comment by brendanjones** [comment]
I'd also love the same functions as above but using geotags instead of hashtags. Needs https://github.com/mastodon/mastodon/issues/281

**Comment by ClearlyClaire** [comment]
You can already follow hashtags in the development version, although that is quite barebones.

As for “saving” a hashtag column, if you enable advanced mode, you can do that by pinning them (and optionally add other hashtags)!

**Comment by brendanjones** [comment]
I'm going to close this because you can now follow hashtags in the home feed, and the other suggestions have specific issues already.
