### ISSUE TITLE
Web Push notifications broken on OpenSSL 3.x

### ISSUE THREAD

**Issue by packetbiral** [mastodon/mastodon#19810]
### Steps to reproduce the problem

1. Turn on web push notifications in web UI
2. Send a test notification
3. Check Sidekiq for errors from Web::PushNotificationWorker workers with - OpenSSL::PKey::PKeyError: pkeys are immutable on OpenSSL 3.0

### Expected behaviour

Should have gotten a web push notification

### Actual behaviour

Error message - OpenSSL::PKey::PKeyError: pkeys are immutable on OpenSSL 3.0

### Detailed description

As far as I am aware this issue started happening when I upgraded my server to Ubuntu 22.04 LTS which runs OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022).

### Specifications

Mastodon v3.5.3
Ubuntu 22.04.1 LTS
Ruby version 3.0.3

**Comment by ClearlyClaire** [comment]
Fixed by #18449
