### ISSUE TITLE
Feat: respond to toots with emoji

### ISSUE THREAD

**Issue by djayatillake** [mastodon/mastodon#19839]
### Pitch

I couldn't see this in the issues.

It would be good to be able to react to toots with emojis where this stays on the toot. Like with Slack and LinkedIn.

### Motivation

Everyone as it allows for differentiated non verbal reaction from favourite which I believe is supposed to be used like a bookmark.

**Comment by Cassolotl** [comment]
Duplicate of *arbitrary emojis as reactions #4106*, maybe? :) If so, close this issue and add a comment and a 👍 over there.
