### ISSUE TITLE
column custom_filters.irreversible does not exist

### ISSUE THREAD

**Issue by gregology** [mastodon/mastodon#19848]
### Steps to reproduce the problem

I noticed the feed no longer updating and there were a high number of failed tasks in Sidekiq. The `FeedInsertWorker` jobs were failing with
```
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR: column custom_filters.irreversible does not exist LINE 1: ...ers" WHERE "custom_filters"."account_id" = $1 AND "custom_fi... ...
```

### Expected behaviour

The feed should update

### Actual behaviour

The feed is not updating

### Detailed description

The `FeedInsertWorker` jobs are failing with

`ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR: column custom_filters.irreversible does not exist`

which is preventing the feed from updating. I have run all migrations.

`docker-compose run --rm web rails db:migrate`

### Specifications

Mastodon - 3.5.3
Ruby - 3.0.3p157
PostgreSQL - 14.5
Redis - 7.0.5
Host - clar.ke

**Comment by grahhnt** [comment]
I am getting this same error and it also is preventing my feed from updating.

**Comment by Gargron** [comment]
Your description says 3.5.3 but did you update to the main branch or another recent version? The column is removed in the recent code, but depended on by 3.5.3 code. If you already upgraded your database to a more recent version, you should run the code from that version.

**Comment by gregology** [comment]
I ended up doing a fresh install and the issue didn't occur the second time. I likely did something weird in my docker setup.

I imported my follows and my followers propagated over a few hours from the other servers.

Cheers Team!
