### ISSUE TITLE
Support Chrome Incognito Mode

### ISSUE THREAD

**Issue by alsutton** [mastodon/mastodon#19840]
### Pitch

Currently Incognito mode causes rendering issues for profile pages (see https://fosstodon.org/@cketti/109293360502946982). Some vistors to the site don't want to be tracked, and so browse much of the web in incognito mode.

### Motivation

Supporting a wider range of users, including those who live in regions, or work for companies, where their internet usage is tracked, and visiting the profiles of potential people could have serious repercussions.

**Comment by shyim** [comment]
That seems fixed already with the latest RC. Picked a random profile on mastodon.social it works: https://mastodon.social/@Gargron

**Comment by ineffyble** [comment]
@alsutton reading the replies in that thread, it sounds like you found the underlying issue. Can this be closed?

**Comment by alsutton** [comment]
Definately.

For those facing a similar symptom, the issue was that the `nginx` process did not have access rights to the `live/public` directory in the mastodon install. This problem was create by me when I locked down the permissions on the mastodon install directory to make sure others couldn't read the credentials stored in `.env.production`.
