### ISSUE TITLE
Email "doesn't appear to exist"

### ISSUE THREAD

**Issue by cbmtrx** [mastodon/mastodon#19845]
### Steps to reproduce the problem

1. Enter email address. 
2. Sign up form won't accept non-standard domain.

### Expected behaviour

Recognize the email as a valid email

### Actual behaviour

Rejected

### Detailed description

Using a .space domain (yes, this is real) the form returns an error. I'd guess that it would have a problem with other non-standard domains. 

### Specifications

Website and app. Instance does not seem to matter. 

Can't join if I can't sign up.

**Comment by TonyRogers** [comment]
Same with our .name domain.

**Comment by cbmtrx** [comment]
SOLVED. Domain name was recently transferred and I had not actually checked that the new DNS settings were working.

**Comment by Tech-Goddess** [comment]
I have users that can't sign up with emails from yahoo.de and gmx.net

**Comment by TonyRogers** [comment]
It seems to be a server specific problem. I'm up and running on mas.to
