### ISSUE TITLE
Error yarn.lock (3.5.3 -> 4.0.0rc1)

### ISSUE THREAD

**Issue by TonAmSi** [mastodon/mastodon#19868]
### Steps to reproduce the problem

I tried the update today to 4.0.0rc1.
My version at the moment is 3.5.3; Ruby 3.0.3

My installation was aborted several times with the error message:
```
mastodon@localhost:~/live$ git fetch && git checkout v4.0.0rc1
remote: Enumerating objects: 2630, done.
remote: Counting objects: 100% (1815/1815), done.
remote: Compressing objects: 100% (190/190), done.
remote: Total 2630 (delta 1683), reused 1740 (delta 1625), pack-reused 815
Receiving objects: 100% (2630/2630), 3.14 MiB | 21.42 MiB/s, done.
Resolving deltas: 100% (2040/2040), completed with 302 local objects.
From https://github.com/tootsuite/mastodon
 + 816466a4b...f6e94eb13 l10n_main  -> origin/l10n_main  (forced update)
   0f5e6dd02..5187e4e75  main       -> origin/main
 * [new tag]             v4.0.0rc2  -> v4.0.0rc2
 * [new tag]             v4.0.0rc1  -> v4.0.0rc1
error: Your local changes to the following files would be overwritten by checkout:
	yarn.lock
Please commit your changes or stash them before you switch branches.
Aborting
```

What's going wrong here?
can't see the forest for the trees...

### Expected behaviour

-

### Actual behaviour

-

### Specifications

Ubuntu 20.04
Mastodon 3.5.3
Ruby 3.0.3
Yarn 1.22.19
npm 8.19.2
node v16.18.1

**Comment by ClearlyClaire** [comment]
You have local changes to `yarn.lock`, this could happen if you have manually updated some dependencies for instance.

Revert the changes by doing `git checkout -- yarn.lock` before trying again.

**Comment by TonAmSi** [comment]
Thanx! This ist the solution!
And now - it works!
