### ISSUE TITLE
Streaming API diverges from documentation in 4.0.0rc1

### ISSUE THREAD

**Issue by rpetti** [mastodon/mastodon#19872]
### Steps to reproduce the problem

Accessing Mastodon via the Sengi client. The client opens websocket on `/api/v1/streaming` as per the API [documentation](https://docs.joinmastodon.org/methods/timelines/streaming/).

### Expected behaviour

Socket should open

### Actual behaviour

Server sends 301 redirect to `/api/v1/streaming/`

### Detailed description

Clients depend on the APIs being stable, but it seems that it has diverged from the [documentation](https://docs.joinmastodon.org/methods/timelines/streaming/) in v4.0.0rc1. Specifically, `/api/v1/streaming` is now erroneously redirecting to `/api/v1/streaming/` which is not correct according to the docs. Nodejs websocket libraries, for example, typically do not handle 30x redirects, and this causes those clients to break.

As an aside, the redirected URL `/api/v1/streaming/` is also currently failing on mastodon.social with a 502 error, though that may just be a service issue.

### Specifications

mastodon.social (v4.0.0rc1)
Sengi v1.1.5

**Comment by Gargron** [comment]
I wonder if this is caused by nginx config changes in #19438

**Comment by rpetti** [comment]
> I wonder if this is caused by nginx config changes in #19438

That would be my guess. Unfortunately I can't seem to get a docker-compose development environment working to test a fix...
