### ISSUE TITLE
Add ability to follow hashtags

### ISSUE THREAD

**Issue by maryball2** [mastodon/mastodon#19873]
### Pitch

This would function similarly to the way Tumblr had this feature years ago. In addition to users you could follow different hashtags and posts with that hashtag would come up on your homepage.

### Motivation

I feel like this would be a user-friendly way to interact with more people without needing to constantly search the same hashtags everyday. Right now when I logon I just instantly go to the search bar and type in the same tags I always search when instead those could just show up on my homepage.

**Comment by ClearlyClaire** [comment]
Implemented in #18809, this will be part of 4.0!
