### ISSUE TITLE
tootctl accounts modify username --role Admin says "OK", but user still not Admin

### ISSUE THREAD

**Issue by BarryLevinson** [mastodon/mastodon#19876]
### Steps to reproduce the problem

1. run `RAILS_ENV=production bin/tootctl accounts modify some_username --role Admin`
2.returns `OK`
3.but the user is still just a user, doesn't show up as Admin
...

### Expected behaviour

the user should be an admin

### Actual behaviour

seems like nothting changes from the command

### Specifications

Using the Digital Ocean Mastodon droplet
( https://marketplace.digitalocean.com/apps/mastodon )
Software Included
Package
Version
License
Mastodon
[3.1.3](https://github.com/tootsuite/mastodon/releases)
[AGPLv3](https://github.com/tootsuite/mastodon/blob/master/LICENSE)
Nginx
[1.14.0](https://packages.ubuntu.com/bionic/nginx)
[Custom](http://nginx.org/LICENSE)
Postgres
[10](https://packages.ubuntu.com/bionic/postgresql)
[Postgres SQL](https://opensource.org/licenses/postgresql)
Certbot
[0.27.0](https://packages.ubuntu.com/bionic/certbot)
[Apache 2](https://github.com/certbot/certbot/blob/master/LICENSE.txt)
Redis
[4.0.9](https://packages.ubuntu.com/bionic/redis-server)
[BSD-3-Clause](https://github.com/antirez/redis/blob/unstable/COPYING)

**Comment by ClearlyClaire** [comment]
Try with lowercase `admin`. This will change in Mastodon 4.0, sorry for the confusion!

**Comment by BarryLevinson** [comment]
That worked!  Thanks @ClearlyClaire !
