### ISSUE TITLE
Translation with DeepL 503 Service Unavailable 

### ISSUE THREAD

**Issue by retiolus** [mastodon/mastodon#19887]
### Steps to reproduce the problem

After setting up DeepL token and Plan in `.env.production` as:
DEEPL_API_KEY=here my token
DEEPL_PLAN=free

### Expected behaviour

Translation should work

### Actual behaviour

get 503 Service Unavailable 

### Specifications

Mastodon v4.0.0rc2

**Comment by retiolus** [comment]
As my GUI is in Catalan and DeepL does not support this language, there is an error. If the translation option is DeepL and the interface language is Catalan, then Spanish should be used for translation.

I am sure there are other cases where such standards could be applied.

**Comment by vmstan** [comment]
Closing as the request to address this is covered in #22169 and the workaround would be to use Libretranslate which does have support for Catalan as a translation engine.
