### ISSUE TITLE
Make lists shareable

### ISSUE THREAD

**Issue by Julibrarian** [mastodon/mastodon#19882]
### Pitch

I like to curate lists of accounts around particular professions or interests (journalists, historians, etc.). I'm in the process of making one that I think would be helpful to others, but there is no way to share it (that I know of). Is it possible to make lists shareable? Thanks for considering it!

### Motivation

I think it would help users get around the problem of not being able to see a feed of toots from special-interests instances that they are interested in, but not qualified to join, or don't want to join multiple ones.

**Comment by FediVideos** [comment]
Been hearing a LOT of people via my FediTips account asking about shareable lists, it comes up again and again.

I am wondering if this could be somehow done through the Import section which currently allows sharing of follows lists as csv files?

The current Lists section isn't really doing what new users expect it to do, maybe that could be renamed as "filtered timeline" or something?

Anyway, whatever you decide is appropriate, just wanted to let you know there is a lot of demand for shareable lists!

**Comment by innosflew** [comment]
Yeah, it would be really nice we could easily share lists and follow other people's lists just like on Twitter. I think this would come pretty useful for everyone. For example now a lot of academics are coming over from Twitter and having a hard time finding and connecting with other academics. If people were able to share their lists, someone could make a list of academics that people could use for finding and following other academics.
