### ISSUE TITLE
Secure mode breaks profile pages on Mastodon 4.0.0 rc1

### ISSUE THREAD

**Issue by kaniini** [mastodon/mastodon#19894]
### Steps to reproduce the problem

I upgraded to Mastodon 4.0.0 rc1, and now my profile pages are broken because I run with `AUTHORIZED_FETCH=true`.

### Expected behaviour

Profile pages should work

### Actual behaviour

Profile pages have "unauthorized" errors.

### Specifications

Mastodon 4.0.0rc1

**Comment by ClearlyClaire** [comment]
Did you upgrade before #19803 hit main? Because this should address it.

**Comment by kaniini** [comment]
Yes, pulling that patch in fixes it.
