### ISSUE TITLE
The rest of following hashtags (list followings, unfollow and add notice in timeline)

### ISSUE THREAD

**Issue by koyuawsmbrtn** [mastodon/mastodon#19895]
### Pitch

I encountered some UX issues with the new follow hashtag feature in Mastodon 4.0. Below is a checklist with things I'd like to see.

- [x] Ability to list all following hashtags and unfollow them from there
- [ ] Having a small text above posts that come from the hashtag follow feature, something like Diaspora has e.g. "This post is viewed to you since you follow #cats"

### Motivation

This would improve the follow hashtag UX

**Comment by Cassolotl** [comment]
YES thank you, I have been thinking both of those things!!

**Comment by trwnh** [comment]
The first one has an API but no UI

The second one is a bit harder, there's no way to know yet. Perhaps for 4.1?

**Comment by koyuawsmbrtn** [comment]
Yes, that would be nice for 4.1

**Comment by innosflew** [comment]
Yeah, it would be awesome if this was in 4.1

**Comment by scottjenson** [comment]
This is especially confusing as my home feed is following a hashtag and, as far as I can tell, it's impossible to turn off. Everything I do implies I SHOULDN'T be following it (not pinned, not on profile) but it still shows up. I've resorted to creating a FILTER to remove it from my home feed which is frustrating.

**Comment by aallan** [comment]
These would both be really nice (and fairly unobtrusive) helpful additions to the UI.

**Comment by ClearlyClaire** [comment]
> This is especially confusing as my home feed is following a hashtag and, as far as I can tell, it's impossible to turn off. Everything I do implies I SHOULDN'T be following it (not pinned, not on profile) but it still shows up. I've resorted to creating a FILTER to remove it from my home feed which is frustrating.

Following a hashtag is a separate action from having something pinned or on your profile: visit the hashtag timeline and notice the icon button on the right. Click it to unsubscribe from the hashtag (it won't retroactively remove posts from your timeline, though).

![image](https://user-images.githubusercontent.com/384364/200535307-e1adb028-e2fc-4c90-b29f-81d9f8889509.png)

**Comment by Cassolotl** [comment]
I think part of why I found it difficult to find that unfollow icon is because the icon is a person-shape and that means profile, but a hashtag isn't a person.

**Comment by borsboom** [comment]
Another that would be nice is the ability to add hashtags to lists (I follow a few different types of communities and having all their hashtags jumbled up together in my feed isn't ideal).

**Comment by placoderm** [comment]
> visit the hashtag timeline

Part of the issue is that when something shows up in your home feed, as stated above, you don't know exactly why you are seeing it. So you don't know which, of possibly very many, hashtags are the one you are following. So then you have to go to the time line of each one to see which one you are subscribed to.

**Comment by FediVideos** [comment]
Agree with both these.

One request though, could you rename this issue to mention both these points? I had trouble finding if these had been mentioned before!

**Comment by Diapolo** [comment]
I'm also missing that feature and would love to See it e.g. in 4.1 :-). Keep up the great work!

**Comment by ladyteruki** [comment]
A small text or an icon would work for me, either way. Way too often I think "why is this person appearing on my timeline ?!".
But also I think as it is, it can even be detrimental to users ; in some cases I'll be assuming that I already follow the person, when I don't.

**Comment by cooperaj** [comment]
> But also I think as it is, it can even be detrimental to users ; in some cases I'll be assuming that I already follow the person, when I don't.

This is a great point. I'd love to have an easy way to know that I should probably follow the author of this great post.

**Comment by FediVideos** [comment]
Have had about ten zillion people asking for a list of followed tags over on FediTips. This would be a really popular feature to add, it's by far the most asked question about followed hashtags.

**Comment by jsoref** [comment]
- [ ] The follow hashtag art should be changed from 👤➕ to something else

https://mstdn.social/@feditips/109355263904445831
![screenshot from post with hashtag and arrow pointing to 👤➕](https://media.mstdn.social/media_attachments/files/109/355/234/586/487/992/original/12f3173d2d53dbbc.png)

**Comment by Lonsfor** [comment]
> Have had about ten zillion people asking for a list of followed tags over on FediTips. This would be a really popular feature to add, it's by far the most asked question about followed hashtags.

honestly it baffles me that list didn't came out with following. just following 2 or 3 hashtags can make the home timeline go overboard.

**Comment by ropery** [comment]
Please also add support for export & import of followed hashtags.

**Comment by placoderm** [comment]
@trwnh Can you point me to any documentation on that API? I wonder if it would be possible to make a browser extension or a script that would add this to the interface until it gets officially supported.

**Comment by atomicwrites** [comment]
@FediVideos FediLab has a list of followed tags now, not sure how.

**Comment by atomicwrites** [comment]
I would also like to ask for the ability to filter stuff from followed hashtags on the home feed just like we can currently hide boosts and replies. After following a few tags they bury the people I've followed.

**Comment by bitbonk** [comment]
> @trwnh Can you point me to any documentation on that API? I wonder if it would be possible to make a browser extension or a script that would add this to the interface until it gets officially supported.

https://docs.joinmastodon.org/methods/followed_tags/

**Comment by bgrinter** [comment]
This would be incredibly helpful - spent 20min looking for the option myself!

**Comment by koyuawsmbrtn** [comment]
Okay, this ticket blew up. Anyone want to write some code?

**Comment by CEbbinghaus** [comment]
> Okay, this ticket blew up. Anyone want to write some code?

I would if I could the bloody dev container to work 😒

**Comment by stephan75** [comment]
What about displaying hashtags that are followed in a different colour than the other hashtags that are not followed?

**Comment by placoderm** [comment]
> What about displaying hashtags that are followed in a different colour than the other hashtags that are not followed?

Perhaps you should create a new issue for that?

If you want to experience what it's like to have your followed tags in a different colour, you can do this manually using the Stylus plugin. Just add this to the custom css:

```
.hashtag[href$="/News"], .hashtag[href$="/news"]
{
  color:green!important
}
```

Having tried this for about a week *I can 100% say that it is hugely beneficial.* So beneficial that I go through the hassle of adding a new item in the custom css every time I follow a new tag. Specifically it helps with the "Why the heck is this showing up in my feed?" issue.

**Comment by scottjenson** [comment]
I'm happy to help with an UI design for the dialog/page that will display them.

**Comment by koyuawsmbrtn** [comment]
> > Okay, this ticket blew up. Anyone want to write some code?
> 
> I would if I could the bloody dev container to work 😒

I prefer setting up a dev environment according to the documentation

**Comment by laurence-b** [comment]
If you need to split this ticket in 2 or 3, but as an MVP, a list of hashtags I currently follow. I have NO IDEA what they are and trying to second-guess them from what I see in my HOME feed.

**Comment by placoderm** [comment]
> trying to second-guess them from what I see in my HOME feed.

The only way I know of is to click on the hashtag and then look at the icon to see if it has an x or a +.

**Comment by cmonster42** [comment]
Yes please. I followed a lot in my first few days and now I regret it. But trying to find what I did follow is painful. Please please please

**Comment by connorshea** [comment]
Listing of followed tags will be handled by #21773 once it's merged (if you have the iOS app, you can actually see the list right now in that).

Unfollow already exists, and the notice on the timeline has two separate issues: #21484 #19528

**Comment by naught101** [comment]
My mockup from #22444 

![image](https://user-images.githubusercontent.com/167164/208305245-1ae0de96-5d15-46d9-9f76-629793c47955.png)

**Comment by placoderm** [comment]
> My mockup from

This looks good, but I wonder if it would start to get intrusive. I follow mainly hastags and not people. And I follow several related hashtags (as I'm guessing others do too). So this would quickly become a long list. And it would be at the top of almost every post on my feed.

**Comment by naught101** [comment]
I have been thinking that all the "boosted by" text, and this, could be a bit smaller and have a little less padding, and perhaps a lower contrast colour to fade them into the background a bit. 

But I think only about 10% of my timeline comes from boosts, and I would definitely appreciate the information displayed.

Perhaps an even more compact option might be to just display the icon in the upper right of the toot, and have the longer info display in a mouse-over?

**Comment by Rayrob** [comment]
> The second one is a bit harder, there's no way to know yet. Perhaps for 4.1?
If it's currently not possible to state the specific hashtag(s), is it any easier to indicate that the post came from the hashtag following process as an interim improvement that could be built on later?
This would at least be enough info to prompt me to check if I'm following the poster if they seem interesting.

**Comment by James-Firth** [comment]
I'd also like this feature, it's one reason why most of my time on Mastodon is via Ivory on iOS (they use bubbles/chips to indicate the hashtag that makes a post appear in your feed)

I too have had the "why the heck is this in my feed?" Issue on desktop after following a few hashtags.

**Comment by Angular-Angel** [comment]
Also! Ability to add hashtags to lists.

**Comment by naught101** [comment]
I dunno if this should be a separate feature, or part of this one, but a version of the Firehose that's limited to tags I follow would be really nice

**Comment by Cassolotl** [comment]
Now that 1 of 2 parts of this feature request have been completed, the rest is a duplicate of *Show mention of the followed hashtag #19528* (October 2022) and this one can be closed, I reckon?

**Comment by koyuawsmbrtn** [comment]
Looks like it, I'll close it now
