### ISSUE TITLE
Link / Site Previews

### ISSUE THREAD

**Issue by sflorg** [mastodon/mastodon#19898]
### Steps to reproduce the problem

1.Post a link from a website. No Preview is attached anymore

### Expected behavior

A Preview 

### Actual behavior

Just text

### Detailed description

Attached is what it looked like and what we get now.
Without such there is no titles to articles. This is detrimental to accounts like ours.
![2022-11-06_134959](https://user-images.githubusercontent.com/60510691/200191977-b34dc18a-3866-4cae-9f68-6cc7342724cd.png)
![2022-11-06_135028](https://user-images.githubusercontent.com/60510691/200191980-f6dbc48b-c815-415d-8613-78ad18a890ef.png)

### Specifications

v4.0.0rc1

**Comment by DanaEpp** [comment]
Similarly, the IOS app doesn't render them at all. [https://github.com/mastodon/mastodon-ios/issues/518](https://github.com/mastodon/mastodon-ios/issues/518)

**Comment by nichu42** [comment]
This is still present in v4.0.2.
Is it a bug, or was it changed deliberately? If the latter, it would be great to have the possibility to opt-in to link previews.

**Comment by llagerlof** [comment]
It happens to me too.

**Comment by vmstan** [comment]
I'm closing this as an stale issue because Mastodon does indeed have functional link previews, but if there are specific issues with link previews on a site please open a new issue.
