### ISSUE TITLE
How long does the update take? (3.5.3 -> 4.0.0.rc1)

### ISSUE THREAD

**Issue by TonAmSi** [mastodon/mastodon#19892]
### Steps to reproduce the problem

I started the update an hour ago from 3.5.3 -> 4.0.0.rc1
Status:
`mastodon@localhost:~/live$ RAILS_ENV=production bundle exec rails assets:precompile
yarn install v1.22.19
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
[4/6] Linking dependencies...
warning Workspaces can only be enabled in private projects.
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 12.15s.
Compiling...
Compiled all packs in /home/mastodon/live/public/packs`

How long does the update usually take?

### Expected behaviour

-

### Actual behaviour

Frozen?

### Specifications

Mastadon 3.5.3
Ruby 3.0.4

**Comment by TonAmSi** [comment]
Now - it works! Thanx!

**Comment by dozjul** [comment]
@TonAmSi is there a bug, or do you might want to close this issue (if it works now)?
