### ISSUE TITLE
migrating account (within instance) leads to "ghost followers" 

### ISSUE THREAD

**Issue by simonheb** [mastodon/mastodon#19900]
### Steps to reproduce the problem

1. set up two accounts on the same instance:  @oldaccount and @newaccount. @oldaccount has some followers from the same instance. 
2. make @newaccount "private", i.e., that people need to request to be allowed to follow
3. migrate @oldaccount to @newaccount: (1) first create an alias from @newaccount, then log into @oldaccount and migrate
4. make @newaccount public. I.e., allow to follow without request.

### Expected behavior

@newaccount should have the followers of @oldaccount. for the ones from the same instance this should be quick. Of course followers might not be transferred immediately. But once they show up in the list of followers, they should be counted.

### Actual behavior

@newaccount shows the incorrect follower count

### Detailed description

@newaccount shows a very low number of followers on the profile page. but when I click on the followers, I see a large number of followers listed (most of which are from the same instance). So it seems the followers are migrated correctly, but not counted on my profile?

### Specifications

Mastodon 3.5.3
Instance econtwitter.com @simon@econtwitter.com 

### Suggestions

- Warn before transfer if the new account is private
- Warn before transfer that transfers take time
- Auto-send follow requests when followers are transferred to a protected account.

**Comment by ClearlyClaire** [comment]
Good catch! What happens is that we rewrite local follows to local users internally as efficiently as possible, but that does not go through our usual follow/unfollow logic, and does not update the counters.

**Comment by simonheb** [comment]
Oh ok. So should I expect that the counts will be updated at some later point?

**Comment by ClearlyClaire** [comment]
Unfortunately not—at least not with an admin's intervention.

But I'll try to fix the underlying cause relatively soon.

**Comment by simonheb** [comment]
Interesting. Just out of curiosity (so it's ok if you don't have the time to answer):
Does that mean the "counts" are stored separately and never fully updated? Are they only incremented/decremented when a new follower appears/leaves?

**Comment by ClearlyClaire** [comment]
> Interesting. Just out of curiosity (so it's ok if you don't have the time to answer): Does that mean the "counts" are stored separately and never fully updated? Are they only incremented/decremented when a new follower appears/leaves?

Indeed, they are stored separately and only incremented/decremented when a new follower appears/leave.

They can be re-computed from an admin command-line tool, though (`tootctl cache recount accounts`).

> And because I did not understand from your reply: Is that issue unrelated to the fact that @newaccount was requiring follow requests at the point when the migration was initiated or is that part of the problem?

It is not related to `@newaccount` requiring approval for follow requests.
