### ISSUE TITLE
Pressing the change language button makes the timeline reset to the top

### ISSUE THREAD

**Issue by konomikitten** [mastodon/mastodon#19915]
### Steps to reproduce the problem

1. Scroll your timeline down
2. Press the change language button

### Expected behaviour

Change language button should open without effecting the page

### Actual behaviour

The change language button makes the timeline jump to the top

### Specifications

Mastodon v4.0.0rc1 (mastodon.online)

Firefox 106.0.5

**Comment by ClearlyClaire** [comment]
I'm confused, what “Change language” button are you referring to?

**Comment by konomikitten** [comment]
> I'm confused, what “Change language” button are you referring to?

![Change language](https://user-images.githubusercontent.com/12713710/200279408-37ee85d5-6044-425b-be7f-dfefd3d21276.png)

**Comment by ClearlyClaire** [comment]
Oh I see, thanks! I can reproduce the issue in single-column mode. I think this may be because the language search input is given the focus before it's properly positioned. I will try to fix that later.
