### ISSUE TITLE
Option to add Content Warning with a boost

### ISSUE THREAD

**Issue by debbiegoldsmith** [mastodon/mastodon#19927]
### Pitch

Lots of people (especially new arrivals) are not great about using CWs. It would be handy to be able to add a content warning when boosting a post that the originator didn't think needed a CW, or didn't think about it period. Some of these posts have great content and would be interesting to share except for the lack of a CW.

### Motivation

Aside from the obvious acceleration of sharing (otherwise) good content, it's possible that people who are bad about CWs seeing their own posts boosted with a CW might help educate them about using a CW in the first place. Just telling people to use a CW doesn't seem to be working that well.

**Comment by Cassolotl** [comment]
This might be a duplicate of *Add content warning on a boost #13291*? (If so, please close this issue and add your comment and/or 👍 over there!)

**Comment by debbiegoldsmith** [comment]
Yes, it's a dupe. I tried doing a search but didn't find that one. Dupe of https://github.com/mastodon/mastodon/issues/13291
