### ISSUE TITLE
Official app doesn't offer "Unlisted" privacy level

### ISSUE THREAD

**Issue by debbiegoldsmith** [mastodon/mastodon#19925]
### Steps to reproduce the problem

1. Create a new post using the official iOS app
2. Try to set the privacy level to "Unlisted"

### Expected behaviour

"Unlisted" should be an option

### Actual behaviour

Only options are "Mentioned, Followers, Public"

### Detailed description

I can set a post to Unlisted on the web site and via various third-party apps, but not via the official iOS app

### Specifications

Official app version 1.4.5 (144)

**Comment by Rexogamer** [comment]
Should this be moved to [the iOS app's repo](https://github.com/mastodon/mastodon-ios)?

**Comment by borgr** [comment]
Same in android 
![Uploading Screenshot_2022-11-07-05-59-45-74_98181b3e65f153deb38599aee3aee7e4.jpg…]()

**Comment by ClearlyClaire** [comment]
I believe this is a deliberate decision from @Gargron and the UX designers hired for the app in order to reduce apparent complexity for users, although I personally disagree with this decision, given how useful the distinction between public and unlisted posts can be with regards to public timelines and trending features.

**Comment by Ferdi265** [comment]
I concur wirh @ClearlyClaire that unlisted posts can be useful. In fact, the instance I use (graz.social) has rules that longer threads should have replies marked as unlisted, and with the current Mastodon app I cannot comply with those rules.

**Comment by Moelf** [comment]
It definitely feel more confusing for web and official app to have different list of options

**Comment by trwnh** [comment]
- https://github.com/mastodon/mastodon-android/issues/37
- https://github.com/mastodon/mastodon-ios/issues/250
