### ISSUE TITLE
Matodon won't start after Ubuntu upgrade.

### ISSUE THREAD

**Issue by mycloudmatrix** [mastodon/mastodon#19934]
### Steps to reproduce the problem

1. Ran 'do-release-upgrade' from Ubuntu 18.04 to 20.04 LTS.
2. mastodon-web won't start.
3. Ran sudo journalctl -u mastodon-web

### Expected behaviour

Expected Mastodon to restart.

### Actual behaviour

Mastodon failed to start.

### Detailed description

# sudo journalctl -u mastodon-web
`/home/mastodon/.rbenv/versions/2.6.6/bin/ruby: error while loading shared libraries: libjemalloc.so.1: cannot open shared object file: No such file or directory`

### Specifications

Ubuntu 20.04 LTS

**Comment by ClearlyClaire** [comment]
It seems that libjemalloc is not installed anymore, or at least not the version you compiled Ruby against.

Check that `libjemalloc-dev` is still installed, and rebuild Ruby. I'd also advise to move to a more recent Ruby version in the process. (As a reminder, the install guide is here: https://docs.joinmastodon.org/admin/install/)

**Comment by LolYangccool** [comment]
Same bug here... Not solved at this moment.

**Comment by LolYangccool** [comment]
On Ubuntu 18.04 Mastodon have a bug with images upload.
I have upgraded to 20.04 and then 22.04 and Mastodon don’t start after that.
Both Ubuntu 20.04 and 22.04 are affected.
No solution at this time, my Mastodon server is down for now.
Please help me.

**Comment by ClearlyClaire** [comment]
As always, check the logs for errors (`journalctl -u mastodon-web`, `journalctl -u mastodon-sidekiq`).

I suspect the issue you are having is that you have not rebuilt the Ruby gems for the updated system libraries. If that is indeed the case, `bundle install --force` should do the trick.

**Comment by LolYangccool** [comment]
When I run this command I got this error :
`mastodon@mastodon:~/.rbenv$ bundle install --force
[DEPRECATED] The `--force` option has been renamed to `--redownload`
Could not locate Gemfile`

**Comment by ClearlyClaire** [comment]
don't do that in `~/.rbenv` but in `~/live`

**Comment by LolYangccool** [comment]
Ok, thank you, but I got this error :
`mastodon@mastodon:~/live$ bundle install --force
/home/mastodon/.rbenv/versions/3.0.6/bin/ruby: error while loading shared libraries: libjemalloc.so.1: cannot open shared object file: No such file or directory`

**Comment by ClearlyClaire** [comment]
Check that `libjemalloc-dev` is still installed, and rebuild Ruby according to the docs

**Comment by LolYangccool** [comment]
`libjemalloc-dev` is installed.
I have rebuild Ruby and make `bundle install --force` in /home/mastodon/live but the problem still the same.

**Comment by ClearlyClaire** [comment]
How have you rebuilt Ruby? When you say “the problem is still the same”, it's `bundle install --force` failing with the same error, or Mastodon not working?

**Comment by LolYangccool** [comment]
Ok, I miss reboot my server, after a reboot, Mastodon apparently works on Ubuntu 22.04.
Need to try image upload but it seems to works.
Thanks you very much !
