### ISSUE TITLE
Open posts and profiles in your own instance even when opening a new page

### ISSUE THREAD

**Issue by innosflew** [mastodon/mastodon#19967]
### Pitch

Usually when you normally click on a post it opens it within your own instance even if it's from an other instance. What I mean by this is that I'm from mstdn.social and when I click on Eugen's latest post from mastodon.social it's going to open it in  "https://mstdn.social/@Gargron@mastodon.social/109301198014267634" instead of "https://mastodon.social/@Gargron/109300967725833789".

But when I want to open the post in a new window by clicking on the time stamp with the middle mouse button or by right-click with "open link in new window" it's not going to open it in my own instance mstdn.social. It's going open it in mastodon.social.

Same goes if want to open their profile in a new window.

Would it be possible to add the option within the preferences to change every link on every post so they will going to open in your own instance?
![Links to opening a post](https://i.imgur.com/GESx820.png)

### Motivation

It's much easier to navigate posts within your own instance. You can also immediately interact with posts and users within your own instance and follow users with a single click. However when you go onto other instances you have to go through multiple steps before you can interact with posts and users there which makes it clunky and off-putting.

**Comment by afontenot** [comment]
Agree on all cases except "copy link to post" should probably copy a link to the canonical version of the post. The idea is presumably to get something you can share with others.

**Comment by innosflew** [comment]
> Agree on all cases except "copy link to post" should probably copy a link to the canonical version of the post. The idea is presumably to get something you can share with others.

We could have both if they were to add a new option alongside that called "copy link to original post" or something.

**Comment by trwnh** [comment]
#19652 is possibly related or a duplicate

**Comment by innosflew** [comment]
It seems this has been implemented in [v4.0.0](https://github.com/mastodon/mastodon/releases/tag/v4.0.0).

**Comment by SamStephens** [comment]
Yeah, it was implemented via issue https://github.com/mastodon/mastodon/issues/19652 (as @trwnh said, this is a duplicate of that), pull request https://github.com/mastodon/mastodon/pull/20540.
