### ISSUE TITLE
Reorder multiple images before submission

### ISSUE THREAD

**Issue by inabap** [mastodon/mastodon#19964]
### Pitch

I want to be able to reorder uploaded images before submission.

### Motivation

The order of images are important in some cases;

e.g.)
- Explain the steps of a process.
- Photos of a course meal in the order in which they appeared.
- Multiple travel photos according to a timeline.
- Upload MANGA.
etc...

With the current version, if I upload multiple images at once, the order will be randomized. Therefore, I'm necessary to upload them one by one in order. This is not very user-friendly and should be improved.

![SS 2022-11-07 16 57 33](https://user-images.githubusercontent.com/6042647/200256208-63ae0d10-605c-4def-9c41-2d4326d9a3d1.png)
![SS 2022-11-07 16 58 24](https://user-images.githubusercontent.com/6042647/200256232-4ea417af-816f-4485-b8a0-c571e7433506.png)

**Comment by saschanaz** [comment]
Dupe of #9635?

**Comment by inabap** [comment]
Oh, Sorry, this was a duplication of [#9635](https://github.com/mastodon/mastodon/issues/9635).
It is frustrating that the same problems have not been solved for the past four years.

However, this is a duplication of [#9635](https://github.com/mastodon/mastodon/issues/9635) So I'm going to close this issue for now.
Thanks for letting me know!
