### ISSUE TITLE
Mastodon Issues

### ISSUE THREAD

**Issue by C3n7ral051nt4g3ncy** [mastodon/mastodon#20005]
### Steps to reproduce the problem

Hi there, 

Good to see that Mastodon is becoming more popular, well done team!
I have a couple of issues/questions to address:

## Impersonating
People don't yet understand that Mastodon has instances, they share their username saying "*Hey guys, I am now on Mastodon, this is my username* `@bobtherabbit`, *see you there*".
<br>
As the same username can be created across all the instances, what has been done to limit impersonating a user. For example taking the same username, putting the same website, an email that looks like the one of the user, the same photo. This would be perfect for scammers.

- How are users verified?
- If the user is on various instances, could something be done to know it's the same user? 
- Having the same public key on each instance would be great, it could also work the other way around  and to know its the same user, even if the user has a different username on another instance.
- What other measures have you implemented to limit impersonation?

## API (v2)

The API is supposed to pull a user from every instance.
But for example, searching for a known user on https://mastodon.online brings no results, but his profile can be accessed via browser. 
- Why is this?
- Is there some instances that the API doesn't cover?

Thanks 

### Expected behaviour

API should have returned the correct result

### Actual behaviour

didn't find user that exists 

### Specifications

Mastodon api (v2)

**Comment by ClearlyClaire** [comment]
> How are users verified?

There is no verification of users, but there is verification of external links, that is, you can add a link to another profile of yours in your profile fields, and it will be verified (instructions are available in the profile settings).

> If the user is on various instances, could something be done to know it's the same user?

You can create aliases. From your account settings, you can also link to your other profiles in your account profiles. Though there are regressions about that since the recent logged-out interface redesign.

> * Having the same public key on each instance would be great, it could also work the other way around  and to know its the same user, even if the user has a different username on another instance.

We unfortunately can't do that under our current security model. The keys are held by the server and the private key cannot be disclosed by the user.

**Comment by Raptor85** [comment]
the problem is @bobtherabbit isn't a mastodon username, it's only PART of one, that's like setting up an email on example.com like bobtherabbit@example.com and saying "hey guys, I have a new email address, it's bobtherabbit!  There's nothing that stops someone from registering this on outlook, protonmail, etc.   People need to get into the habit like with email or even blizzard/discord posting FULL usernames (@bobtherabbit@example.com), not just the short version, as those cannot be duplicated

**Comment by mgrider** [comment]
I don't see a bug here.

> But for example, searching for a known user on https://mastodon.online/ brings no results, but his profile can be accessed via browser.

I tested search just now, on mastodon.online, and search does return the user.

**Comment by C3n7ral051nt4g3ncy** [comment]
- @ClearlyClaire: Many thanks for the quick response. So you mean the owner of a domain name can verify his profile and confirm ownership of the domain with a TXT record to put in the DNS records?

- @Raptor85: Great points there! thank you

- @mgrider: I can't post the username on open source, I can confirm I found the profile on mastodon.online, but the api is not returning any results, the profile is set to not discoverable, but the api should still bring back a result. Is there a way I can send you the username without having it on open source?

As soon as the api issue is solved, I will close this issue and `mark as completed`.

**Comment by Raptor85** [comment]
@C3n7ral051nt4g3ncy on the profile page there's a block about how to verify ownership of domains, it's just adding a tag to the site index.

`You can verify yourself as the owner of the links in your profile metadata. For that, the linked website must contain a link back to your Mastodon profile. The link back must have a rel="me" attribute. The text content of the link does not matter. `

**Comment by ClearlyClaire** [comment]
> * @ClearlyClaire: Many thanks for the quick response. So you mean the owner of a domain name can verify his profile and confirm ownership of the domain with a DNS TXT record ?

You can currently verify pages, not domains. The page you link to needs to link back to you with `rel="me"`

> The API is supposed to pull a user from every instance. But for example, searching for a known user on https://mastodon.online brings no results, but his profile can be accessed via browser.

There is no global search, the server will reply with what it knows about. If it has not encountered the account, it will not return it in search results. However, it is possible to resolve an account or post by pasting its address in the search bar, although that only works if you are logged in, and will not work if the remote server is too slow to reply.

**Comment by C3n7ral051nt4g3ncy** [comment]
@ClearlyClaire:

- If I understand correctly, seeing `me` in the .json means the user verified his link?
- See screenshot below:

<img src="https://user-images.githubusercontent.com/104733166/200557561-ee4a5b95-853f-4f88-80e0-55a5bffe1f85.png">

**Comment by C3n7ral051nt4g3ncy** [comment]
@ClearlyClaire I like this link verification feature , it would be a great way to identify possible scammers.
