### ISSUE TITLE
Mastodon 4.0.0-RC2 - Is there a way to roll back git fetch?

### ISSUE THREAD

**Issue by hackdefendr** [mastodon/mastodon#20011]
### Note: This is not a Mastodon bug

1. Ubuntu 20.04 (OpenSSL 1.1.1f) and 22.04 (OpenSSL 3.0)
2. Attempts to install Ruby 3.0.4 fail due to OpenSSL library issues that I suspect came in the most recent vulnerability patch.
3. Attempts to use Ruby 3.0.3 fail with similar OpenSSL library issues
4. Can a `git stash && git fetch` be reversed if that is all that was done in the `live` folder?
...

### Expected behaviour

When attempts to continue using Ruby 3.0.3 are used I expect I should still be able to upgrade Mastodon

### Actual behaviour

Compiler crashes every time on the openssl-3.0 extension build

### Detailed description

Again, this is not a Mastodon bug, but this issue is stopping me (possibly others) from upgrading.

I attempted to upgrade/install Ruby 3.0.4 per the release notes. It failed with a terrible [log dump](https://gist.github.com/hackdefendr/0843d822fbfbecdc777b007bbe82aea8). So I edited the .ruby-version file and changed it to 3.0.3 in hopes of being able to at least still upgrade Mastodon to v4.0.0-RC2 since Ruby 3.0.3 was working still. 

Basically any gem with an openssl dependency won't upgrade. I see the same or very similar crash log.

Presently, I would just like to go back to v3.5.3 if at all possible. Can `git stash` be unstashed?

### Specifications

Ubuntu 22.04.1
Mastodon 4.0.0 (RC2)
Ruby 3.0.3
NodeJS v16.18.1

**Comment by hackdefendr** [comment]
Thank-you Claire, I will definitely try.  I haven't done anything in the live folder beyond the stash and fetch. No migrations. Crossing fingers!

**Comment by hackdefendr** [comment]
Well it ultimately did work!!  

I had to do a bit of dancing and /usr/lib/x86_64-linux-gnu/libidn.so.11 became /usr/lib/x86_64-linux-gnu/libidn.so.12 so I had to find the proper version and copy it where Sidekiq could find it. With all that done my Mastodon host is back online at v3.5.3, not sure if I can ever upgrade to v4 without a full system rebuild.

Thank-you very much Claire.

**Comment by ClearlyClaire** [comment]
Good to hear that it ended up working! If I were you, I'd investigate into building Ruby and Ruby gems with OpenSSL 1.1 though, so you can keep up with other dependency updates.

**Comment by hackdefendr** [comment]
For anyone that see's this later, how to install Ruby 3.0.4 on Ubuntu 22.04+

https://askubuntu.com/questions/1399788/ruby-installation-build-failed-ubuntu-20-04-using-ruby-build-20220324
