### ISSUE TITLE
Lost email address

### ISSUE THREAD

**Issue by biocoopenvexin** [mastodon/mastodon#20024]
### Steps to reproduce the problem

1.
2.
3.
...

### Expected behaviour

Get an email from your screen name

### Actual behaviour

No solution

### Detailed description

Hi, I don't remember which email I used to register on mastodon.social and I can't find any message on my different accounts. Is there any way to retreive an email from a Screen name ? At least it could trigger an email to that inbox ?

### Specifications

mastodon.social

**Comment by biocoopenvexin** [comment]
Sorry it should really have been a suggestion.

**Comment by nightpool** [comment]
This repo is for tracking issues with the Mastodon software, if you need help with a specific server or troubleshooting, please use Discord or another channel. We do not currently have a way to trigger "forgot password" without knowing the email address of the account, for security reasons. I suggest you get in touch with your server's admin directly.
