### ISSUE TITLE
Translation with Locally-hosted LibreTranslate Impossible Due To `Mastodon::PrivateNetworkAddressError`

### ISSUE THREAD

**Issue by isosphere** [mastodon/mastodon#20029]
### Steps to reproduce the problem

1. Install LibreTranslate on the same machine as a Mastodon instance
2. Configure the above to listen on the loopback address
3. Set `LIBRE_TRANSLATE_ENDPOINT` appropriately, referencing the loopback address and port
4. Restart `mastodon-web`
5. Attempt to translate something

### Expected behaviour

Translation

### Actual behaviour

`error: "Mastodon::PrivateNetworkAddressError"`

### Detailed description

The translation feature was merged in #19218 

The feature appears to use (I am new to this repo) the `Request` object to perform requests, as shown here:
https://github.com/mastodon/mastodon/blob/3114c826a7a6b2b10bff722c59cca57abe7f819f/app/lib/translation_service/libre_translate.rb#L30

https://github.com/mastodon/mastodon/blob/3114c826a7a6b2b10bff722c59cca57abe7f819f/app/lib/translation_service/deepl.rb#L31

The `Request` object is not allowed to pull data from private network addresses:

https://github.com/mastodon/mastodon/blob/8cf7006d4efbcfdd4a4ab688db1bcc73a2915a47/app/lib/request.rb#L261-L265

As it raises `PrivateNetworkAddressError` for endpoints that are private. The loopback address is private, so it is not possible to host a translation engine locally.

This is a pain for small instance owners like myself that would like to support translation without paying for the hosted service or adding an additional machine just for this purpose. I'd also like to avoid exposing the endpoint to the Internet.

I suppose I could make the service listen globally, use the public address in `LIBRE_TRANSLATE_ENDPOINT`, and configure a firewall rule that blocks all access to the appropriate port except from the server itself, but that's a pretty strange configuration to maintain and it's bad practice to have services listen outside loopback if they are internal.

### Specifications

Mastodon v4.0.0rc1
LibreTranslate 1.3.0
Linux 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64

**Comment by isosphere** [comment]
If this were my project, having the very limited understanding of it that I do, I would add a flag parameter to `Request` that would allow us to override this behaviour for hand-picked circumstances like this one.

**Comment by ClearlyClaire** [comment]
Oh, interesting oversight. This is not an entirely satisfying solution, but until the issue is fixed, you can work around the issue by using `ALLOWED_PRIVATE_ADDRESSES`

**Comment by isosphere** [comment]
> Oh, interesting oversight. This is not an entirely satisfying solution, but until the issue is fixed, you can work around the issue by using `ALLOWED_PRIVATE_ADDRESSES`

I like this solution far better than the one I mentioned (listening globally), thank you!

I set `ALLOWED_PRIVATE_ADDRESSES` to "127.0.0.1" and restarted `mastodon-web`, and now I have a different error message (503 Service Unavailable) which I will consider progress on my end! I'll consider that irrelevant to this issue.

**Comment by ineffyble** [comment]
This occurs if you're using Docker and running LibreTranslate in a Docker container, since Docker containers use a private network range. Would definitely be nice for security if the code was adjusted to avoid needing to set this.
