### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by Arthegor** [mastodon/mastodon#20026]
### Pitch

Hello,

First of all I wanted to thank all the people who allowed the development of mastodon as well as the fediverse

The French translation no respect French linguistic usage. Indeed, our ministery have highly discouraged using Inclusive Speech in actual form (ref: Annex A) because it's a big problem for general comprehension, dyslexic ( Annex B), autistic, people using text to speech or braille system (Annex C) and for foreign people tying to learn French language.

Being myself suffering from an autism spectrum disorder and evolving in autistic aid associations, many are those who complain about this writing which excludes them because of the very great effort it generates to decode it. 

All this to come to my question : how can we remedy this problem? Personally I am ready with the help with friend who can read this writing to propose an alternative translation in order to be able to allow the millions of French-speaking people suffering from the constraints mentioned above to be able to use mastodon. 

Sincerely,

Annex:

A: https://www.education.gouv.fr/bo/21/Hebdo18/MENB2114203C.htm
B: https://www.ffdys.com/actualites/ecriture-inclusive-et-dyslexie-lavis-de-la-ffdys.htm
C: https://aveuglesdefrance.org/app/uploads/2021/03/CP_Non-au-melange-des-genres_Ecriture-inclusive_Aveugles-de-France.pdf

### Motivation

This functionality would benefit the millions of people with disabilities in France and in French-speaking countries.

**Comment by ClearlyClaire** [comment]
This is an editorial decision by the project that we are not revisiting.

**Comment by Arthegor** [comment]
I'm quite surprised and sad by this answer. In French, the official rules indicate that the neutral gender already exists (example: "un abonné" is neutral)

But it's your decision and I respect it even if I don't agree with it. We are going to think within our community if it is better to fork the project, which seems to me counterproductive for a social network, link to an existing fork (I heard a project called gab had forked mastodon, maybe they will have made changes translation) or go to another platform that is more inclusive for us (if you have any recommendations for me, I would gladly share them with our community.)
