### ISSUE TITLE
Password confirmation screen causes Safari to create a new, non-working password

### ISSUE THREAD

**Issue by daprice** [mastodon/mastodon#20067]
### Steps to reproduce the problem

1. While logged in to Mastodon, go to Preferences > Account > Two Factor Auth
2. Click "Set Up”

Alternatively, perform any other action that requires password confirmation.

### Expected behaviour

If I have my password saved in Safari, it should prompt to autofill it

### Actual behaviour

Safari automatically creates a *new* password, fills it in the field, and prompts to overwrite my real saved password with it

### Detailed description

When Mastodon prompts for confirmation of my existing password, Safari automatically attempts to create a *new* password. If a user simply goes along with all the prompts, it ends up overwriting their saved *real* password with the newly created, non-working one, and they lose access to their Mastodon account.

Based on the [Safari documentation](https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element) it appears the field needs `autocomplete="current-password"` to tell the browser what it wants. Without that attribute, a password field by itself on a page is assumed to be password *creation* field rather than a login/confirmation field.

### Specifications

I’ve seen this on Mastodon 3.5.3 and 4.0.0rc1

Safari 16.1 (18614.2.9.1.12), MacOS Ventura 13.0, also iOS/iPadOS 16.1

**Comment by ClearlyClaire** [comment]
I think this is addressed by  #20071. If you are able to test or review it, I'd be glad if you did.
