### ISSUE TITLE
Donation unlock coffee cup icon

### ISSUE THREAD

**Issue by BirdInFire** [mastodon/mastodon#20075]
### Pitch

With the 8$ a month of musk i had an idea to help funding our server.
Why not proposing in mastodon a coffee cup logo behind his name for anyone that actually do a donation with something like username@server to make the process automatics.
But unlike twitter make it a one time payment of any amount (min 2$ (0.5 for mastodon dev funding, and 1.5 for de server)).

### Motivation

Help funding mastodon dev & pay for the server because if we take the number of active user that Eugen pushed on explore : 
1,028,362 and we take into account that 10% will donate if it's 2 buks 1 time payment.
take 10% so 102.836.

it will make a minimum of 25.709$ for the development and 77.127$ for the different server who host the network.
And the people get this coffee cup icon on their name to show they at least once supported financially the network.

Since it's a coffee cup logo it does not imply any verification just say, hey guys i support mastodon.

**Comment by MoritzKa** [comment]
I think that makes a lot of sense. Lack of funding is what keeps development at a slower pace compared to centralized platforms.
Do you run your own mastodon instance or do you know an instance that might be willing to create a showcase? Happy to help.
