### ISSUE TITLE
4.0.0rc2: public profile displays "No one follows this user yet." when social graph is hidden

### ISSUE THREAD

**Issue by abochmann** [mastodon/mastodon#20070]
### Steps to reproduce the problem

1. activate "Hide your social graph" in the profile settings
2. log out of the instance and go to your profile page
3. the profile page shows a count of Following and Followers, with the text "No one follows this user yet." below

### Expected behaviour

Old public profile text: "This information is not available"

### Actual behaviour

Current text: "No one follows this user yet."

### Detailed description

When the social graph is hidden, text on the public profile page and the Following / Follower count are inconsistent.

Current public profile page example:
![image](https://user-images.githubusercontent.com/9380844/200419292-0470e676-b888-4765-94ea-4e9d71657fa8.png)

Mastodon 3.5.3 profile page example:
![image](https://user-images.githubusercontent.com/9380844/200419339-ef9cae87-e5be-44b1-a858-26e50f5ec411.png)

### Specifications

Mastodon 4.0.0rc2

**Comment by abishekmuthian** [comment]
Hiding social graph setting doesn't seem to function anymore, I could still see my social graph from a private window.

Is it disabled to address this bug?
