### ISSUE TITLE
Error with OAuth on just one instance „Client authentication failed due to unknown client“

### ISSUE THREAD

**Issue by tibor** [mastodon/mastodon#20081]
### Steps to reproduce the problem

I developed an app for Mastodon. With multiple instances, there are no problems. But with mstdn.social/oauth/authorize, I only get an error message.

1. use whotofollow.tibor.net
2. log in via mstdn.social
3. error message: „Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.“
...

### Expected behaviour

Code should be generated

### Actual behaviour

Client authentication failed due to unknown client

### Specifications

Mastodon 4.0.0

**Comment by tibor** [comment]
The problem occurs with all my apps and it also occurs on eay.social and legal.social. On most instances, everything works fine.

**Comment by tibor** [comment]
I created another app for this purpose on mstdn.social. Now everything works fine with the above instances, but the error message occurs on mastodon.social. I suspect there is some problem with the API between different instances or versions of mastodon.

**Comment by joshdick** [comment]
I'm seeing this same issue when https://micro.blog attempts to authenticate to https://indieweb.social to enable crossposting integration: https://micro.blog/help/13884458

**Comment by joshdick** [comment]
> I'm seeing this same issue when https://micro.blog attempts to authenticate to https://indieweb.social (Mastodon v3.5.3 as of this writing) to enable crossposting integration: https://micro.blog/help/13884458

Update for this report: 

I decided to try again, and the issue self-resolved/I was able to successfully enable micro.blog crossposting to the same aforementioned Mastodon instance.

No idea what, if anything, changed; the Mastodon instance was not upgraded in the interim.

**Comment by tibor** [comment]
Figured it out myself: Seems like you need to create an app automatically via the API before you send the user to the login page

**Comment by huckabarry** [comment]
> Figured it out myself: Seems like you need to create an app automatically via the API before you send the user to the login page

Would you mind helping me understand this a little better? 

I created an instance of my own bit want to cross post to it from Micro.blog. Any time I try to log in, I get the same error above. 

It doesn't happen when I log in to large instances, but whenever I log in to my own, I get the error: 

"Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."
