### ISSUE TITLE
Might be a good idea to limit number of followers to like 10K or 20K

### ISSUE THREAD

**Issue by perfors** [mastodon/mastodon#20089]
### Pitch

I think it would be a great idea to limit the number of followers for anybody that uses Mastodon so that there are no HUGE accounts. I realise this is a pretty strong suggestion but I have strong reasons for it, explained below. In a nutshell, I think  that having people with very large follower counts not only goes against the “quality of experience, not reach” ethos embodied in Mastodon, but has really bad consequences for the integrity of the information system itself. This is not something you all have probably had to think about before -- at least not at this scale -- but with the latest influx of people it is becoming very relevant as an issue.

### Motivation

I'm one of the many refugees from the recent TwitterMigration, so please take all of this in that light. I'm aware it is super tacky to come in somewhere new and immediately suggest changes so if you have already considered this stuff deeply or just want to ignore me then that is fine. This goes pretty against character for me to stick my head up like this. However, I think this is important and there is a chance you haven't thought about it deeply yet, so it's worth saying something.

Background is: I'm an academic who studies cognitive science, cognition, and specifically misinformation and information systems. So I've thought a lot about how the affordances of different platforms interact with our cognition to influence the information system and the subjective experience. I've also thought a lot about the factors that made twitter so pathological and am trying to anticipate to what extent they might have a similar effect on Mastodon as more people come. Many of them are factors that you all have given a great deal of time and consideration to.

A huge factor that you might not have, though, is the fact that very soon, without explicit actions to stop this, we're going to have more and more people with vastly more followers than the median person -- people with 50K or 100K or especially 1M+ followers.

Why is this bad?

Fundamentally, nobody should have power that is many orders of magnitude (say, 100x or more) larger than a “median” person. That is where many of the pathologies in our world come from, whether you’re talking about income or followers. None of us are 1K or 1M times as smart or thoughtful or knowledgeable than the median; thus, that person having that much power is a distortion of the underlying “value” of their thoughts.

To the extent that an efficient information system should be one in which the “power” or “reach” of an idea is proportional to its value, this sort of mismatch really corrupts the system — it means that the most valuable (by whatever metric) ideas aren’t favoured, but instead the ones that originated from people with many followers.

If somebody who would otherwise have 100K followers and is limited to 10K has a valuable thought, then it will still get high reach because a lot of people will boost it — but a follower limit would prevent *all* of their thoughts getting that kind of reach.

You might ask, what is the harm in them having more reach? Besides being a distortion of the system, so it no longer rewards info proportionately to its value, the fact is that people are limited — very limited — in our time and attention capacity. The more high-follower-count people there are, the more the conversation shapes around them. This is part of where twitter’s “character of the day” came from, and why it just felt like a firehose of shit — because all of our conversations were shaped *far more than they should have been* by people with large follower counts — even if we didn’t follow them, they had such reach that they affected what everyone else was saying. Even with CWs and no quote-retweets, instead of it being a calm space oriented around conversations, it will become more and more like a twitter-esque  endless parade of news, even for people who don't follow those accounts.

I would also suggest that having a lot of followers creates other, hidden problems. People are not cognitively equipped to handle the kind of scale that that many followers creates. Say that 0.01% of people are totally irrational and cruel, and a further 0.001% of those will bother to comment accordingly. If you have fewer than 10K followers, then you’ll get one awful comment for every toot — they suck when they happen but your modal experience is still pretty good. If you have 1M followers, then every toot will be accompanied by 100 awful comments. 

That’s awful for many reasons. It means high-follower-account people won’t read the comments, thus defeating the purpose of this as a multi-way communication. Either that or they will fixate on them (because this is another thing people do, remember and dwell on the negative stuff far more than the positive stuff). I suspect that this dynamic is part of what drives polarisation - you get a few negative comments from members of Group X or about Y thing, begin to think X people are mean or Y is silly, dig down about it, post slightly more extreme about it, get more negative comments, hate them more, etc., until before you know it you’re a full-on radical against X or Y. Or, you get the negative comments and just leave or never talk about X or Y again, which also isn’t good.

Even if you’re not the person with lots of followers, if you follow somebody like this and read any of the comments they get, you are affected by the same dynamic. 

Finally, and importantly, having nobody with large numbers of followers means there are many fewer and less tempting targets for trolls or bots. On twitter -- and on Mastodon soon, as they come because so many people are here -- trolls can get a lot of leverage if they can either convince a high-follower person to believe in their cause — or even if they can’t, that person is a great way for them to identify a bunch of other like-minded targets. And replying to that person’s toots is a great way to ensure that their messages are read by a lot of people. Limiting numbers of followers would give trolls and bots way less of an attack surface. Not to mention, I can't imagine trying to be a poor individual who owns and instance or server, and needing to monitor these massive accounts.

I don't think having people distributed across different servers or not-allowing quote retweets or any of the other very nice features of Mastodon changes this fundamental dynamic, which is basically driven by math and human cognition.

For these reasons I am making a (fairly radical, I realise) suggestion that it would be good to limit people’s total followers to like 10K or 20K or at most 50K. People can accept who they want as followers and thus tune it that way (so if there is someone they want to be a follower they can make someone else unfollow and put the new person in the spot). And of course non-followers could still read all their toots and boosts and so forth. And they could even create multiple accounts, but each would be limited (thus it would be super hard to get to like 1M people even spread across multiple, because then they'd have to juggle dozens or hundreds of accounts and nobody is going to bother to do that). Basically, getting around this would require so much extra effort as to vastly mitigate these issues. I know it might make existing “big names” not want to jump to Mastodon, but I’m not sure I or we want them all anyway.

If you're thinking "why don't we wait and see how it goes", well, perhaps that is better than nothing, but it is way easier to stop people from getting something than to take away something they already have. There will be much less pushback if such limits are instituted before a bunch of famous and loud people have that many followers. Also, if the quality of the Mastodon experience goes down in the ways I predict it will be hard to know how to trace it to this issue so I'm not sure what kind of data would be convincing that it's worth trying to do this. 

Like I said, I’m totally conscious that I’m a complete newbie coming in and saying my idea of what Mastodon should be so of course YMMV and I could be completely wrong. Or you have already thought about this and discarded my potential solution, or have a much better potential solution. All of these would be great and if that's the case my apologies for saying something. I just thought that  this is important enough — and Mastodon is growing fast enough — that I wanted to put the idea out there. 

Thank you for creating such an awesome thing. I really hope we newcomers don't screw it all up.

**Comment by perfors** [comment]
I'll add that it might be sensible to allow certain exceptions to this ban (e.g., admin of servers, or reputable organisations that can be proven as such) but that opens up a can of worms as to how to set those boundaries. And even those, I would suggest, should have limits (just maybe higher ones), because the underlying dynamics and effects on conversation are similar whether driven by people or organisations.

**Comment by trwnh** [comment]
This is a really tricky subject -- the problems you bring up are very real, and they aren't even the *only* problems. At the same time, there's no clear solution.

I think the more fundamental issue is that the concept of "following" is inherently tied to audiences and therefore lends itself to the outsized influence and attention inherent to socially scaling beyond a certain point.

Speaking purely in theoretical terms, I think we could draw a distinction between "talking with friends" vs. "publishing a post". The former is a conversation, while the latter is broadcasting. These are different modes of communication. But I'm not sure how to cleanly separate them. Simply putting a cap on max followers doesn't really do anything meaningful to differentiate the two.

There's also a lot of uncertain behavior that would occur if we did this -- what happens if you want to follow someone who has maxed out their followers? Do we convert that to a follow request? How do you advertise to remote followers that you are at capacity? And so on.

**Comment by perfors** [comment]
Thanks so much for engaging with this! You're right that the problems are a lot more apparent than the solution. I am relieved you agree at least that there is a problem.

The distinction between talking with friends and publishing a post is an interesting and important one, but I think it falls down once we're talking about these huge accounts. Once you have 100K followers I don't think it's possible to engage in real conversation; there are just too many replies and not enough time or capacity. (I have never had such a large account but on twitter I had a few things go viral and that was the subjective experience -- it was overwhelming and I couldn't engage to the level I wanted. And that was with much less response than these large accounts would get with every single toot). So at best these accounts would read and respond to only a few replies, but more often everything would be a post without interaction.

So I guess the question for the community is to what extent we (or you, I feel like I'm too new to have much right to an opinion) want accounts that are devoted to just posting... and not only that, posting with an outsize impact and power relative to the accounts that actually engage and talk with each other.

As for what my proposed solution would look like -- again, I defer to smarter people than me, but I was loosely envisioning one of two options. (Probably there are better ideas out there!)

1. After the max followers is reached, subsequent people get put in a queue (similar to how people who have made a follower request that hasn't yet been answered are in a queue). The person with the account can shape their follower list by dropping followers and replacing them with people from the queue, but it can't go over the max. Upside: this is transparent and gives the account holder the control. Downside: liable to be frustrating and feels kind of elitist as it means a lot of people will never be able to follow accounts they want.

2. An account can have however many followers they want, but only MaxNumber ever see any one toot. So, if I have 100K followers and 10K is the limit, then 10K of those followers will see my toot. This subset could be randomly sampled from the followers for each toot, or perhaps randomly sampled weighted by engagement (so followers who the account has engaged with get priority proportional to the amount of engagement). Advantage of this is it is simpler and it doesn't create tiers of followers. Disadvantage is it's less transparent. I'd weakly favour this option if I had to choose.

As you can see I don't have all the answers! Mainly I wanted to start the conversation because the effects of lots of unchecked, high-follower accounts will, I think, be bad. Thanks again for engaging.

**Comment by bt90** [comment]
Please don't tell me or others who we are allowed to follow. That's not how the fediverse works. Your "solution" to these existing technical problems is throwing the baby out with the bathwater.

**Comment by petrokoriakin1** [comment]
As an industry, we already have PEP (politically exposed person) concept for decades. Banking domain is super-conscious about that. Maybe it would be just enough to add one more checkbox on profile edit screen like we have for bots already? Smh like 

[ ] Self-declared as PEP

I have no idea how it will be used from UX perspective and what value chains will be affected. But this seems to be a good battle-proof direction for evolution.

**Comment by akmsmith** [comment]
Baking a hard limit into the network seems problematic, if people want to engage with celebrities, journalists, politicians then you're pushing them towards corporate networks (Facebook, Twitter etc). The German government has set up an instance and I can imagine in time that the Chancellor and other leaders might want their own individual accounts which they may use a team of paid people to moderate and engage with users on. They wouldn't just have 10k followers but millions of followers.

Far better to allow admins to set the limit on their own server so if they want their instance to feel like their front room then they can.

**Comment by xz-dev** [comment]
> 

But I think that let admins have the power he shouldn't have.

**Comment by xz-dev** [comment]
> Baking a hard limit into the network seems problematic, if people want to engage with celebrities, journalists, politicians then you're pushing them towards corporate networks (Facebook, Twitter etc). The German government has set up an instance and I can imagine in time that the Chancellor and other leaders might want their own individual accounts which they may use a team of paid people to moderate and engage with users on. They wouldn't just have 10k followers but millions of followers.
> 
> Far better to allow admins to set the limit on their own server so if they want their instance to feel like their front room then they can.

But I think that let admins have the power he shouldn't have.

**Comment by bt90** [comment]
> Far better to allow admins to set the limit on their own server so if they want their instance to feel like their front room then they can.

Which side are we actually talking about? If you do not agree with the pope tooting from your instance because it cannot handle the load, then ask him to leave. Anything else would resemble a softblock of that user.

I'm not sure if there is a difference at all for followers?

**Comment by akmsmith** [comment]
It would be interesting to get the perspective of an admin on some of the instances where the big users have moved in from Twitter, one of them chose the instance he did simply because he liked the name and the admin he did is now stuck with a $50 a month bill, there isn't much they can do about that.

**Comment by trwnh** [comment]
Having a limit on total followers might make sense for admins who wish to limit total capacity, sure, but it will lead to some confusing UX around remote follows, where you send a Follow to a non-locked account and it turns into a follow request because you never get the Accept back

**Comment by perfors** [comment]
Thanks everyone for all the engagement. Seems like there is not much appetite for this so, fair enough. I suppose we'll see what happens.

Good point about what might be possible to implement. I admit I'm fuzzy on this. I guess I thought that if it's possible to implement other Mastodon-wide standards (like no quote-tweets) it would be possible to do this. But I don't know the codebase so I'll defer to your expertise.

Thinking about it further, and based on some of these comments, this might be a _little_ less of a problem than I was worried about simply because a lot of servers won't have the resources to handle huge accounts. The moderation challenges and money they would cost would be a lot, so those huge folks might end up either self-funding or tending to congregate onto servers run by corporations. Another issue, but easier to mass block them.

Anyway, all good. Was worth opening the conversation.

**Comment by trwnh** [comment]
> By design there is no central authority that could impose a limit on how many followers someone has.

Actually, there is a central authority in this case -- it's the server hosting your profile. The ActivityPub spec requires that for every Follow you send out, you MUST wait for an Accept Follow to be received back. This is done even if your account doesn't require any manual approval -- in such cases, the Accept is sent out automatically as soon as the Follow is processed.

Implementing a feature like this would actually be surprisingly doable -- you just don't send that Accept Follow out, in effect converting their follow into a follow request.

**Comment by brendanjones** [comment]
I’ll just note: there is a setting to combine boosts in your feed, meaning that no matter how many times people boost a post it’ll still only appear once in your feed. Turning that setting on surely solves a large part of the described problem? Yes with many followers come many boosts meaning more people see a post, but setting an arbitrary limit on followers seems heavy handed.

**Comment by trwnh** [comment]
I forgot that there is a MAX_FOLLOWS variable set to 7500, and a MAX_FOLLOW_RATIO of 1.1; perhaps a similar thing could be done like MAX_FOLLOWERS? The only missing part of this is the auto-convert-to-follow-request functionality.

**Comment by simon-brooke** [comment]
> I guess I thought that if it's possible to implement other Mastodon-wide standards (like no quote-tweets) it would be possible to do this. But I don't know the codebase so I'll defer to your expertise.

It isn't possible to implement Fediverse-wide standards like no quote-posts. Vanilla Mastodon instances don't allow quote-posts because Eugen Rochko (@Gargron), as principal author, chooses not to implement it; but other ActivityPub implementations do allow it. 

Things can be excluded from *parts* of the Fediverse by defederation – for example, most servers don't allow child porn or hate speach; but that's a political/social decision not a technical one. Similarly, you could have a group of instances which implemented a follower limit and defederated from all instances which didn't implement the follower limit, and that would work. But making a change to one server implementation doesn't impose that change across the Fediverse, because

1. the Fediverse is heterogenous by design: not all servers are the same, and, for basic stability and security reasons, nor should they be (although Mastodon is currently dominant);
2.  Admins are perfectly free to fork Mastodon and implement their own changes (see for example [Glitch edition](https://glitch-soc.github.io/docs/)).

Open source is inherently not like closed source. There are no single points of technical control.

> Anyway, all good. Was worth opening the conversation.

Indeed.
