### ISSUE TITLE
Web Home feed updates show content from 3-6 hours ago.

### ISSUE THREAD

**Issue by jxyzn** [mastodon/mastodon#20090]
### Steps to reproduce the problem

1. Turn off Home boosts and replies.
2. Reload the web interface to get fresh posts. My account, following ~300, this usually, shows posts from within the last 45 minutes at the top.
3. Wait for updates to appear in the Home feed. My account, this usually takes 2-5 minutes.
4. Observe the age of the newly appearing posts. I usually see 2-3 new posts appear with timestamps from 4+ hours ago.

### Expected behaviour

Items appear in reverse chronological order, and only new items appear.

### Actual behaviour

Older items from hours ago are inserted at the top of the feed.

### Detailed description

This appears in both the basic and advanced views. The older items are often items that I have definitely seen before.

In this screenshot, you can see two 4h old items appearing *above* 26m and 1h old items: 
![image](https://user-images.githubusercontent.com/245082/200470884-12107d1b-ab36-4735-811b-08da26b4bd47.png)

### Specifications

This is observed on mastadon.social running 4.0.0rc1

**Comment by ClearlyClaire** [comment]
This is not a software bug, but a load issue with mastodon.social in particular. The server resources were scaled up in the meantime and the issue should be resolved.
