### ISSUE TITLE
Confirmation emails never received

### ISSUE THREAD

**Issue by Maude-Mayhem** [mastodon/mastodon#20125]
### Steps to reproduce the problem

1. Sign up
2. Send the confirmation email
3. dont get the email, request it be resent
...

Still nothing.

### Expected behaviour

The email should be received within 15 minutes

### Actual behaviour

I have received nothing

### Detailed description

I have tried to sign up to Mastodon with two different emails an hour ago. i still have yet to receive any of the verification emails. I have checked in my spam boxes. they are not there. i have changed the address but still nothing. I apologize if this is an error on my end. the email for this account came through relatively well too.

### Specifications

Mastodon Android app

Opera

**Comment by aerger** [comment]
Any chance you're using a + in your email address?

**Comment by ClearlyClaire** [comment]
This may be an issue with the specific Mastodon server you are attempting to register to. It may be overloaded or have other issues.

You could share which server it is you tried to register to so that we can try to investigate the issue with them, or if you are ok with using another server, you could try that too.

**Comment by ClearlyClaire** [comment]
> mastodonapp.uk

This server seems to currently be struggling with load: https://mastodonapp.uk/@wild1145/109308376951724487 https://status.atlas-media.co.uk/incidents/42

**Comment by Sadcjp** [comment]
So, do I just wait or is there something I can do ?

**Comment by ClearlyClaire** [comment]
> So, do I just wait or is there something I can do ?

Just waiting should be good! But if you can't wait, you can try another server.

**Comment by Sadcjp** [comment]
I can be patient and thanks for responding

**Comment by Maude-Mayhem** [comment]
No. This is the email i registered with on the server.

And the other one is ***@***.***

**Comment by Sadcjp** [comment]
Email finally received and verified....HOWEVER....the app now will not load on Safari but does load on Firefox....?????

**Comment by moo** [comment]
Check your junk mail! 

My confirmation email was delivered to my spam/junk folder. 
This was using gmail, and happened both in browser and using the ios Mail app. 

Maybe there's a way to whitelist these emails?

**Comment by Sadcjp** [comment]
I've managed to get passed that stage but can't log in using Safari on my MacBook. The webpage is just blank but I cannot in using Firefox !!!!!

I much prefer Safari and want to use Safari to log in.....

**Comment by OMR7** [comment]
Please guys, i have problem setting up my server and its killing me, everything is working properly and im recieving confirmation email but the confirmation email is not opening, when i open the confirmation email it sends me to a website and it says this site cannot be reach, im sure that the server is working properly, just when i try to open a new account and want to recieve a confirmation email it says like that, please help

**Comment by ClearlyClaire** [comment]
> So, I have now attempted to create/apply for accounts on 5 servers, of which 1 has successfully managed to send me a confirmation mail. The one that managed to do this was instant and I also got an instant email confirmation when I later set up MFA for my authentication.
> 
> These are pretty bad statistics. I am not sure if all 4 of them are using the same email service, and if that is the culprit, or what.

Mastodon itself behaves like a mail client and relies on a locally-configured MTA, so the issue would either be specific to the MTA used by those servers, or maybe Spamgourmet flagging Mastodon mails as spam? There is not much we can do without more information from either the specific servers involved or Spamgourmet, depending on where the issue lies.

@OMR7 your issue seem to be completely different, and lacking some important information: is the website you're sent to your server or something else? would you mind sharing it?

**Comment by Sadcjp** [comment]
I just gave up trying to work it all out and never got anywhere with Mastodon as they make something simple really idiotically complicated


-----Original Message-----
From: Claire ***@***.***>
To: mastodon/mastodon ***@***.***>
CC: Sadcjp ***@***.***>; Comment ***@***.***>
Sent: Tue, 9 May 2023 10:53
Subject: Re: [mastodon/mastodon] Confirmation emails never received (Issue #20125)


So, I have now attempted to create/apply for accounts on 5 servers, of which 1 has successfully managed to send me a confirmation mail. The one that managed to do this was instant and I also got an instant email confirmation when I later set up MFA for my authentication.These are pretty bad statistics. I am not sure if all 4 of them are using the same email service, and if that is the culprit, or what.
Mastodon itself behaves like a mail client and relies on a locally-configured MTA, so the issue would either be specific to the MTA used by those servers, or maybe Spamgourmet flagging Mastodon mails as spam? There is not much we can do without more information from either the specific servers involved or Spamgourmet, depending on where the issue ***@***.*** your issue seem to be completely different, and lacking some important information: is the website you're sent to your server or something else? would you mind sharing it?—

**Comment by kennb** [comment]
Given up after many attempts to create an account.  Never received a confirmation.  I suspect it's because my email address is a redirected by my domain host rather than a physical email address but I am not prepared to use my physical email address.

**Comment by cjshaker** [comment]
Running into the same problem with mastadon.radio. It's been several hours, and I've received NO confirmation email to either of the two email addresses I used in an attempt to open an account. I've wasted enough time on this today.

Mastadon appears to be a Balkanized world that doesn't work?

Meanwhile, X (twitter) continues to work.

**Comment by MadokVaur** [comment]
Maybe Mastodon.radio?

With an "o"?

Does that help in any way?

https://fedidb.org/network/instance/mastodon.radio

**Comment by vmstan** [comment]
> Running into the same problem with mastadon.radio. It's been several hours, and I've received NO confirmation email to either of the two email addresses I used in an attempt to open an account. I've wasted enough time on this today.
> 
> 
> 
> Mastadon appears to be a Balkanized world that doesn't work?
> 
> 
> 
> Meanwhile, X (twitter) continues to work.

Since Mastodon isn't a centralized service you'll need to contact the administrators the .radio instance and find out why their email notifications aren't working.
