### ISSUE TITLE
See list of followed hashtags

### ISSUE THREAD

**Issue by Paarsec** [mastodon/mastodon#20132]
### Pitch

Hi, I was wondering if there was a way to see a list of the # we follow to manage them, or if there are plans to implement one. Thank you very much!

### Motivation

I think everyone could benefit from this to manage their followed interests.

**Comment by CEbbinghaus** [comment]
Indeed this would be an amazing addition. It can be hard to know which hashtags you follow. Also providing the option to unfollow that hashtag from right on the list page will be valuable for people trying to purge some clutter

**Comment by trwnh** [comment]
#19895

**Comment by ladyteruki** [comment]
YES, thank you !

**Comment by spikebike** [comment]
In the meantime this repo has a listfollows command.  https://github.com/HalCanary/mastodoner.git  Once that's installed then run: ./listfollows -tags

**Comment by ronilaukkarinen** [comment]
Just thought about this, it's getting asked more and more. So my +1 to this feature.

**Comment by neffscape** [comment]
This is necessary. I'm following too many hashtag and my home timeline is now filled with garbage. I cannot tell from the posts which tag is causing the issue. A list of followed hashtag is much needed and could be easily added in settings (in the same page you can see the list of the followed people).

**Comment by connorshea** [comment]
This will be fixed by #21773.

**Comment by placoderm** [comment]
> This will be fixed by #21773.

Thank you so much for your work on this! For those of us who aren't involved in Mastodon development, are you able to give any idea of when this would be included in an official version? I know it's up to individual instance admins to upgrade.

**Comment by connorshea** [comment]
@placoderm I can't speak for the maintainers (I'm just a random contributor 😄), but assuming it gets merged in the next few days, probably v4.0.4 or v4.0.5? As for _when_ those would release, I'm not sure. That part is up to the maintainers. I'd assume 4.0.4 would come out in the next week, maybe two. And then v4.0.5 a few weeks after that.

But again, just speculation. There's no official release cadence as far as I'm aware. And that's all assuming my change gets merged at all :)

**Comment by kefir-** [comment]
Should there be a separate issue for export/import of hashtag follows? That's relevant for migration. An export might be an even simpler way to add at least some minimal functionality, and it's necessary regardless.

**Comment by connorshea** [comment]
> Should there be a separate issue for export/import of hashtag follows? That's relevant for migration. An export might be an even simpler way to add at least some minimal functionality, and it's necessary regardless.

I believe that this PR covers that feature? #21841

**Comment by Hacklet** [comment]
I agree. I am seeing so many people ask for this - Also it's something that users need to be able to export, because a carefully curated hashtag set can take a lot of time and effort to build.

**Comment by davidmegginson** [comment]
Boost!

**Comment by mstahl302** [comment]
This should be visible on the "Follows and Followers" settings page, just like all other followers. 
![image](https://user-images.githubusercontent.com/3792004/209164584-52b194b2-4476-4881-81e9-dc90466e77bd.png)

**Comment by davidmegginson** [comment]
It is, apparently, already available via that API, but that's not a practical solution for most users (especially not setting up OAuth2).

**Comment by adriencater** [comment]
> This should be visible on the "Follows and Followers" settings page, just like all other followers.
> ![image](https://user-images.githubusercontent.com/3792004/209164584-52b194b2-4476-4881-81e9-dc90466e77bd.png)

For UI, this is the right place to put it, this is where I looked for it intuitively first.

For UX, this feature is necessary from the moment the ability to follow tags is added, otherwise there's no undo.

**Comment by placoderm** [comment]
> otherwise there's no undo.

Well, if you just click on a hashtag in a post, you can unfollow the same way you followed. So there is an undo, it's just not very useful.

I'm guessing that the devs wanted to get hashtag following out quickly and (rightly) figured that listing the follows could come later.

**Comment by RockstarRaccoon** [comment]
> This should be visible on the "Follows and Followers" settings page, just like all other followers. ![image](https://user-images.githubusercontent.com/3792004/209164584-52b194b2-4476-4881-81e9-dc90466e77bd.png)

This is also where I look for it before I looked up how to do it on Google, which is what led me to this thread.  It's definitely worth adding for people who follow a few hashtags, don't remember which ones, then realize our feed is full of stuff we don't actually want.  (I followed a some hashtags for sociology reasons on my professional account that ended up being way more politically charging than I thought they would be)

**Comment by connorshea** [comment]
This has been resolved by #21773 :)

**Comment by James-Firth** [comment]
@Paarsec can this issue be closed now? I believe the linked PR covers it (see comment above mine)

**Comment by davidmegginson** [comment]
Yes, it's been working on the Mastodon instance I use (mstdn.ca) for a couple of months now.
