### ISSUE TITLE
"Unfortunately, there was an error looking up the remote account" from Peertube

### ISSUE THREAD

**Issue by alejandrocobo** [mastodon/mastodon#20141]
### Steps to reproduce the problem

1. Install Peertube and Mastodon in the same server
2. Set /etc/hosts file so both Peertube and Mastodon domains point to the server's local IP
3. Try to comment a Peertube video from your local Mastodon account

### Expected behaviour

Mastodon should respect `/etc/hosts` in order to be able to communicate with other ActitityPub local instances when "NAT loopback/Local loopback" is not available.

### Actual behaviour

Mastodon bypasses `/etc/hosts`

### Detailed description

I have a Peertube and a Mastodon instance in the same server. Since the router doesn't allow me to access to the server using the public IP, I have to set the local server IP in my /etc/hosts file.

Both instances work fine when interoperate with ActivityPub sites outside my LAN. But when I try to comment a video in the Peertube instance using my Mastodon instance's user, I get this error:

`Unfortunately, there was an error looking up the remote account`

I know comments from other  Mastodon instances work.

There is other (I think related) issue. If I put a link of a video from my Peertube instance in my Mastodon, it only appears the link. If I see the post from another Mastodon instance, I see a thumbnail from the video.

I used the default nginx configuration file only modifying certs and domain names.

Thanks.

EDIT: More details in [here](https://github.com/mastodon/mastodon/discussions/20312).

### Specifications

Mastodon 3.5.3.
Peertube 4.3.0.

**Comment by ClearlyClaire** [comment]
This sounds like a configuration issue on your end, but there is something I am confused about. What is your peertube domain name?

**Comment by alejandrocobo** [comment]
> This sounds like a configuration issue on your end, but there is something I am confused about. What is your peertube domain name?

Probably is a issue on my end but it makes no sense to me. The Peertube domain is video.hardlimit.com

**Comment by ClearlyClaire** [comment]
I honestly have no idea what's going on. The only thing is on Mastodon's side, you need to allow local addresses to be able to query them, using `ALLOWED_PRIVATE_ADDRESSES` https://docs.joinmastodon.org/admin/config/#allowed-private-addresses, but that wouldn't explain anything trying to resolve `peertube@social.hardlimit.com`

**Comment by alejandrocobo** [comment]
@ClearlyClaire adding the local IP and the loopback IP to `ALLOWED_PRIVATE_ADDRESSES` didn't solve the problem.

I've fixed the first post because I made a mistake. The error message appears only when I try to follow my Mastodon instance, which probably makes no sense. 

When I get the `Unfortunately, there was an error looking up the remote account` message or when I add a video link to Masdoton and the thumbnail don't appear, there are no errors related with social.hardlimit.com in Peertube's log.

**Comment by alejandrocobo** [comment]
I've opened a new issue into Peertube's Github with extra details, in case some that would help you to figure out: https://github.com/Chocobozzz/PeerTube/issues/5398

**Comment by alejandrocobo** [comment]
Solved. The solution is in GitHub's "Discussions" section: https://github.com/mastodon/mastodon/discussions/20312

I don't know if bypassing `hosts` file is an expected behavior.

**Comment by ClearlyClaire** [comment]
Mastodon resolves hostnames by using `Resolv::DNS#getaddresses` which indeed does not uses `/etc/hosts`. Maybe there's something to change here.

Can you edit your issue to reflect that the problem is Mastodon not respecting `/etc/hosts`?

**Comment by strk** [comment]
@alejandrocobo could you also update the issue title to give more detail about the specific problem ? I came here as having trouble looking up remote accounts on really remote servers (no /etc/hosts involved)
