### ISSUE TITLE
Grouping likes together in notifications

### ISSUE THREAD

**Issue by eloydegen** [mastodon/mastodon#20146]
### Pitch

Excuse me if this a duplicate, but using the search function I could not find an issue like this.

When a lot of users like a certain toot, every single like generates a new notification. It would be nice if they are grouped together when multiple likes occur, especially with viral posts.

### Motivation

Any user who posts a toot that has 2 or more likes.

**Comment by ClearlyClaire** [comment]
This is indeed a duplicate of #1483!
