### ISSUE TITLE
Risk of false website verification in the fediverse

### ISSUE THREAD

**Issue by eloydegen** [mastodon/mastodon#20159]
### Pitch

The documentation [here](https://docs.joinmastodon.org/user/profile/) states:

> [...] Mastodon can cross-reference the links you put on your profile to prove that you are the real owner of those links. In case one of those links is your personal homepage that is known and trusted, it can serve as the next-best-thing to identity verification.

This is a nice feature, but there is still a risk of impersonation: any Mastodon instance administrator could put a verified tick for any user with any website, if they want to. But we could at least try to detect those violations. When interacting with a different instance, it could try to redo the verification and report a violation in the logging to the admin. A scanning tool or browser extension could also be implemented, but that could probably best be done in a separate project. I'd like to hear any feedback!

### Motivation

It would prevent having the trust in the website verification feature be reduced

**Comment by afontenot** [comment]
> When interacting with a different instance, it could try to redo the verification

This already exists, instances do their own verification. You only have to trust your instance owner / admin, not the instance of the user that's claiming verification. 

> When interacting with a different instance, it could try to redo the verification and report a violation in the logging to the admin.

I think (someone correct me if I'm wrong) that the activitypub protocol doesn't notify server B that server A claims that user X has such and such verified account. So there's no reliably way (at present) to detect false claims. Introducing this *might* be a bad idea, as sometimes verification fails for reasons that have to do with a particular server. Maybe it's overloaded, maybe it's further away (in physical space) from the user's website's server and so it took too long to connect.

**Comment by eloydegen** [comment]
> This already exists, instances do their own verification. You only have to trust your instance owner / admin, not the instance of the user that's claiming verification.

After reading some source code, I think you are right indeed. 

> Introducing this might be a bad idea, as sometimes verification fails for reasons that have to do with a particular server. Maybe it's overloaded, maybe it's further away (in physical space) from the user's website's server and so it took too long to connect.

Agreed.
