### ISSUE TITLE
Linked GIFs should show as if attached

### ISSUE THREAD

**Issue by timhosey** [mastodon/mastodon#20178]
### Pitch

Whenever I link a GIF in a post (say, from Giphy or a similar site) it shows the link but no preview or version of the GIF inline. My expectation would be a similar behavior to have the link previews generate for websites, but if it's a GIF file it'd be viewable right from the timeline.

Discord does something similar when a link to a GIF is posted - it renders in the chat as if attached.

### Motivation

Since attachments are limited to 2 MB, it might be worthwhile to allow attachment of GIFs from third-party sites via a direct link. GIFs are also a super popular method of response amongst users, and with non-technical users it might be harder for them to download and attach from these third party sites (not to mention space/bandwidth savings on the server side).

**Comment by afontenot** [comment]
Looks like this is probably supposed to be working but isn't. Maybe you have an example of this not working? Could be an instance specific problem.

![masto_example](https://user-images.githubusercontent.com/3870410/200696081-78cc630d-3410-47d4-8482-0bc901cdb13f.png)

The gif is playing in the above screenshot; you do have to click a play button to activate external embeds. This helps Mastodon respect your privacy, as no data is sent to the external server until you click play.

**Comment by timhosey** [comment]
Thanks for the reply! Strangely enough, it's working now. It definitely was not before. This can be closed, then.

**Comment by CEbbinghaus** [comment]
> The gif is playing in the above screenshot; you do have to click a play button to activate external embeds. This helps Mastodon respect your privacy, as no data is sent to the external server until you click play.

Is there an option to disable this behavior? I like my gifs playing automatically even if it means sending off another HTTP request

**Comment by afontenot** [comment]
@CEbbinghaus there's an issue request for this you should probably give it a thumbs up if you'd like to see it implemented https://github.com/mastodon/mastodon/issues/14349
