### ISSUE TITLE
Text on hastag moderation screen on mobile is overlapping

### ISSUE THREAD

**Issue by Justinzobel** [mastodon/mastodon#20193]
### Steps to reproduce the problem

Login as admin user
Open hashtag moderation screen

### Expected behaviour

Text should be legible

### Actual behaviour

Text is overlapping

### Detailed description

Text on hastag moderation screen on mobile is overlapping

### Specifications

Mastodon 3.5.3
Node 16.18.0
Ruby 3.0.3

Firefox Mobile 106.1.0

**Comment by ThisIsMissEm** [comment]
Are you referring to the Trends > Trending Hashtags screen? Because there's a new Moderation > Hashtags screen, though, I think both may have issues on mobile.

**Comment by Justinzobel** [comment]
I honestly couldn't tell you, this was nearly 2 years ago and I can barely remember 2 weeks ago. I'm going to close this as I should have provided a screenshot to show the issue.
