### ISSUE TITLE
Official app doesn’t show verified links

### ISSUE THREAD

**Issue by jaredzimmerman** [mastodon/mastodon#20219]
### Steps to reproduce the problem

1. Add url to profile structured field 
2. See verified mark on site utilizing rel=me on web client 

### Expected behaviour

URL shows as verified in iOS app

### Actual behaviour

URL shows as verified in web client but not iOS app

### Specifications

iOS 1.4.5 144

**Comment by FediVideos** [comment]
The official apps have their own sections on here, would be best to raise issues about them there:

iOS
https://github.com/mastodon/mastodon-ios

Android
https://github.com/mastodon/mastodon-android
