### ISSUE TITLE
mastodon-streaming could not start after upgrade to HEAD (at the moment)

### ISSUE THREAD

**Issue by gemelen** [mastodon/mastodon#20218]
### Steps to reproduce the problem

1. Made a fresh installation of a Mastodon of a version 3.5.3, found an issue with some instances (mastodon.social data fetches failed)
2. Made an upgrade to 6ba52306f9d2611a06326445230b54c156c37e53 (all upgrade steps executed and succeeded) to obtain fix from #20108 
3. `web` and `sidekiq` services are running, while `streaming` doesn't come up after a restart due to an error
```
Nov 09 07:07:37 yeti systemd[1]: Started mastodon-streaming.
Nov 09 07:07:37 yeti node[72551]: /home/mastodon/live/node_modules/jsdom/lib/jsdom/browser/parser/html.js:170
Nov 09 07:07:37 yeti node[72551]:     after._pushedOnStackOfOpenElements?.();
Nov 09 07:07:37 yeti node[72551]:                                        ^
Nov 09 07:07:37 yeti node[72551]: SyntaxError: Unexpected token '.'
Nov 09 07:07:37 yeti node[72551]:     at wrapSafe (internal/modules/cjs/loader.js:915:16)
Nov 09 07:07:37 yeti node[72551]:     at Module._compile (internal/modules/cjs/loader.js:963:27)
Nov 09 07:07:37 yeti node[72551]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Nov 09 07:07:37 yeti node[72551]:     at Module.load (internal/modules/cjs/loader.js:863:32)
Nov 09 07:07:37 yeti node[72551]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
Nov 09 07:07:37 yeti node[72551]:     at Module.require (internal/modules/cjs/loader.js:887:19)
Nov 09 07:07:37 yeti node[72551]:     at require (internal/modules/cjs/helpers.js:74:18)
Nov 09 07:07:37 yeti node[72551]:     at Object.<anonymous> (/home/mastodon/live/node_modules/jsdom/lib/jsdom/browser/parser/index.js:4:20)
Nov 09 07:07:37 yeti node[72551]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
Nov 09 07:07:37 yeti node[72551]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Nov 09 07:07:37 yeti systemd[1]: mastodon-streaming.service: Main process exited, code=exited, status=1/FAILURE
```
4. Tried to upgrade Node from 16.18.1 to 18.12.1 and `jsdom` specifically to `20.0.2`, as separate steps, with no luck

### Expected behaviour

`streaming` service launches successfully after upgrade

### Actual behaviour

`streaming` service could not be launched

### Specifications

Mastodon as of [6ba52306f9d2611a06326445230b54c156c37e53](https://github.com/mastodon/mastodon/commit/6ba52306f9d2611a06326445230b54c156c37e53)
Ruby 3.0.4
Node 16.18.1 (and 18.12.1)
Running on a `PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"` in a BHYVE vm.

**Comment by ineffyble** [comment]
Interesting, that syntax error *should* only occur in Node.js versions older than Node 14...

**Comment by gemelen** [comment]
Aha, so it should be some older version of Node jumped in. I'll check PATH in an environment, thanks for an idea.

**Comment by gemelen** [comment]
[This](https://github.com/mastodon/mastodon/blob/main/dist/mastodon-streaming.service#L12) systemd unit has a hardcoded path that not 100% points to the right version, that's the culprit.

**Comment by ineffyble** [comment]
Managing Node versions/installations is always a pain. Not sure there's a nicer option for the systemd config, wonder if there's some docs somewhere that could note this though.
