### ISSUE TITLE
AWS Application LoadBalancer healthchecks are failing

### ISSUE THREAD

**Issue by bruecktech** [mastodon/mastodon#20238]
### Steps to reproduce the problem

1. Deploy Mastodon as an ECS task behind the ALB
2. Look at the logs

### Expected behaviour

ALB healthchecks should succeed

### Actual behaviour

ALB healtchecks fail

### Detailed description

In the logs I can find this message. The IP address is the ALB instance trying to execute the health check.

```
[ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: 10.0.5.23
```
It seems Rails is blocking certain hosts in production and I've tried to disable this by building my own Docker image that clears the allowed hosts, but none of my tries was successful.

```
FROM tootsuite/mastodon:4.0.0rc2

RUN echo $' \n\
Rails.application.configure do \n\
  config.hosts.clear \n\
end' >> /opt/mastodon/config/environments/production.rb
```

Please advise how to disable this host authorization check for Mastodon or alternatively how to add the private IP range of the VPC

### Specifications

Mastodon 4.0.0rc2

**Comment by bruecktech** [comment]
I was able to use `/health` as health check path now and this works. Not sure if this is documented somewhere, at least I didn't find anything. Would be great to add this to the docs.

**Comment by matthewford** [comment]
It's probably rate-limited. Adding the health check URL to the docs is a good idea.

**Comment by bruecktech** [comment]
> It's probably rate-limited.

It's related to this [feature](https://www.fngtps.com/2019/rails6-blocked-host/) in Rails. None of the requests went through, so it's a hard block, no rate limit.
`/health` is explicitly excluded [here](https://github.com/mastodon/mastodon/blob/main/config/initializers/1_hosts.rb#L34)

**Comment by ClearlyClaire** [comment]
Yeah, `/health` needs to be used for this. I'm closing, but arguably a documentation issue could be open to make that clearer.

**Comment by vmstan** [comment]
I'm trying to implement something similar with Digital Ocean load balancer health checks, and am confused about `/health`

If I'm on the local machine I can `curl http://127.0.0.1/health` and get an OK but that isn't accessible to the load balancer as a check. Is there something I need to add to the nginx config?

**Comment by ClearlyClaire** [comment]
No, you should be able to just hit `https://your-domain/health`

**Comment by vmstan** [comment]
Thanks @ClearlyClaire I eventually just tried that from the DO load balancer and it worked.
