### ISSUE TITLE
Indexes are not updating in ElasticSearch

### ISSUE THREAD

**Issue by CygnixProto** [mastodon/mastodon#20230]
### Steps to reproduce the problem

1. New instance of Mastodon 3.5.3 + ElasticSearch 8.5.0 (3 Node Cluster)
2. Run tootctl search deploy
3. Wait for new posts with hashtags
4. Wait for Sidekiq index job to run
...

### Expected behaviour

ElasticSearch indexes should update with the latest hashtags etc

### Actual behaviour

No updates are performed

### Detailed description

Deploying the indexes for the first time is successful and running the job again subsequently brings them up to date however I would expect that this is supposed to be done by the sidekiq task

The task appears to run, however it completes incredibly fast with no obvious result 
```
2022-11-09T10:00:13.920Z pid=7 tid=6g0f class=Scheduler::IndexingScheduler jid=8c3ce70353524df31236be49 INFO: start
2022-11-09T10:00:13.922Z pid=7 tid=6g0f class=Scheduler::IndexingScheduler jid=8c3ce70353524df31236be49 elapsed=0.003 INFO: done
```
I've attached kibana to my ES cluster to double check and can confirm at the time of writing there has been no new data added to the tags index for 12 hours and hashtags have definitely been posted to my timeline

ES_ENABLED=true as well as the ES_HOST, ES_PORT, ES_USER and ES_PASS are set in all pods that run a mastodon service (web, streaming, sidekiq)

ES cluster parameters:
```
ingest.geoip.downloader.enabled: false
node.attr.attr_name: attr_value
node.store.allow_mmap: false
ES_JAVA_OPTS: '-Xms512m -Xmx512m'
```
Please let me know if you need further information

### Specifications

Mastodon 3.5.3 - Docker image and deployed on k8s
ElasticSearch 8.5.0 - 3 node HA cluster deployed with the ECK operator

**Comment by CygnixProto** [comment]
I may be way off base here and please forgive me if I misinterpreted the code (Ruby/Rails isn't really my jam), but digging into this further it seems as if tags/accounts/statuses to be processed are not even hitting redis.

I tested this by pausing sidekiq, bookmarking some posts and seeing what happens. My crude understanding is that [app/models/bookmark.rb:16](https://github.com/mastodon/mastodon/blob/fbcbf7898f000d9d1a21d52e8a8d3ed4602aa7db/app/models/bookmark.rb#L16) should drop an entry into the chewy:queue:statuses set in redis which would then get processed by the job.

However after doing this all the sets are still empty

```
127.0.0.1:6379> smembers chewy:queue:accounts
(empty array)
127.0.0.1:6379> smembers chewy:queue:tags
(empty array)
127.0.0.1:6379> smembers chewy:queue:statuses
(empty array)
```

**Comment by matthewford** [comment]
Did you restart after setting ES_ENABLED=true

**Comment by CygnixProto** [comment]
ES_ENABLED=true has been set since the deployment began and the pods have been restarted/redeployed multiple times. 

I've noticed Chewy doesn't explicitly state that it supports 8.x for ES, so I have redeployed ES as 7.17.7 and restarted all the pods again.

No noticeable difference I'm afraid.

**Comment by CygnixProto** [comment]
Updated to Mastodon 4.0.2 and the issue still persists to a degree
- Accounts index updates sporadically
- Status index seems to be updating, hard to quantify as there's no time field
- Tags index does not update at all.

**Comment by TheAlienKnight** [comment]
Came here looking to see if the issue I was trying to debug on my instance was somewhere in the issues pages, and it is. I am having this _exact_ issue(s). So far, I have yet to be able to see exactly what is causing the issues either- but I am also not super familiar with Ruby. If I find something out in my hunt for why I'll be sure to update it here.

**Comment by gunchleoc** [comment]
I can confirm that the tags index won't update in Mastodon 4.0.2.

Switching off ElasticSearch will enable hashtag search for new hashtags, switching it back on will break it.

Running `live/bin/tootctl search deploy --only tags` will add the missing hashtags to ElasticSearch

**Comment by TheAlienKnight** [comment]
> I can confirm that the tags index won't update in Mastodon 4.0.2.
> 
> Switching off ElasticSearch will enable hashtag search for new hashtags, switching it back on will break it.
> 
> Running `live/bin/tootctl search deploy --only tags` will add the missing hashtags to ElasticSearch

Thank you, I can confirm that this does work as a temporary solution. For now I will setup a cronjob to periodically refresh these tags. I am still not entirely sure why this happens, but I look forward to seeing the cause.

![image](https://user-images.githubusercontent.com/88284489/205681352-3861b285-534c-4417-afbf-e2895431807f.png)

**Comment by allilengyi** [comment]
I can confirm, too. I am on a fresh install of Mastodon 4.0.2. Elastic search is 7.17. This is especially sad, since elastic search should give more features instead of less. 
> Updated to Mastodon 4.0.2 and the issue still persists to a degree
> 
>     * Accounts index updates sporadically
> 
>     * Status index seems to be updating, hard to quantify as there's no time field
> 
>     * Tags index does not update at all.

**Comment by isosphere** [comment]
> Also experiencing this. For now, I’ve settled on logging into the Mastodon container and firing off an index rebuild manually. When I get a chance I’ll get a cron trigger going for that and post it here as a workaround for others.

Here's my crontab line:
```
@daily RAILS_ENV=production /home/mastodon/live/bin/tootctl search deploy --only tags
```

**Comment by seano-vs** [comment]
Coming here to say I have this exact issue as well, I had a user come to me and say that my instance wasn't keeping up with search updates. I found this thread, and surely enough creating a `tootctl search deploy` cronjob is bandaiding it.

**Comment by smiba** [comment]
Same issue with the tags, and I feel like it sometimes struggles as well with other information. But the tags I can absolutely reproduce

**Comment by Gargron** [comment]
The issue with tags is real but I haven't been able to find the root of the problem yet.

**Comment by vmstan** [comment]
@CygnixProto can you verify if this issue persists in newer (4.2.x versions of Mastodon as search received an extensive amount of work)
