### ISSUE TITLE
Can we add the Scots language

### ISSUE THREAD

**Issue by SS64** [mastodon/mastodon#20249]
### Pitch

The 'Scots' language which is ISO 639-2 (SCO) is not available in the list of languages when posting within Mastodon.
It does have 'Scots Gaelic', but thats a completely different language.
See https://dsl.ac.uk/ for details

### Motivation

So that Scots speakers and Gaelic speakers don't have to see each other's posts. Also to reduce confusion due to the significant difference between these languages (they have almost no words in common).

**Comment by AlistairDavidson** [comment]
Seconding this. It's uncomfortable, when writing in Scots, to have it labelled as English. Also it is an official language in Northern Ireland and a recognised minority language in Scotland, with 1.5 million people reporting they could speak it in the 2011 census. https://en.wikipedia.org/wiki/Scots_language
