### ISSUE TITLE
Unable to link multiple Mastodon accounts to single website

### ISSUE THREAD

**Issue by jbmagination** [mastodon/mastodon#20259]
### Steps to reproduce the problem

1. Setup [website](https://jbmagination.com) with verification `rel="me"` for two accounts ([@JBMagination@mastodon.social](https://mastodon.social/@JBMagination) and [@JBMagination2@mastodon.social](https://mastodon.social/@JBMagination2))
2. Attempt to add website to both accounts
3. Only one (from my experience, the first on the page) will be verified

### Expected behaviour

Both accounts that I setup should be verified

### Actual behaviour

Only [@JBMagination2@mastodon.social](https://mastodon.social/@JBMagination2) is verified

### Detailed description

It appears that verification is only applied to one account, and the others are ignored even if on the same page. This has the potential to affect brands who want to have multiple accounts on an instance, as well as journalists and the like, who may in the future use a verified link to a trusted site like `washingtonpost.com` to prove their identity.

### Specifications

Mastodon 4.0.0rc1 (on https://mastodon.social)

**Comment by AlanBell** [comment]
it is because this line only checks the first matching link points back https://github.com/mastodon/mastodon/blob/cd0a87f170f795f3d2eeaadc06d6039aca395049/app/services/verify_link_service.rb#L36 so at the time of verifying you have to be first on the page.
I think you can verify one after another, (as a workaround right now) as long as at the time of saving the profile the link that points back is the first one with rel=me in it.

**Comment by AlanBell** [comment]
Just to confirm I understand the current behaviour, I think it will already allow multiple links to be verified if any are perfect match (i.e. someone copied and pasted the link and their server just got on and served it). If there are rel=me links but none of them are a perfect match then it will resolve the first one and see where it goes (for link shorteners).
So the non-working scenario is multiple link-shortened rel=me links if you are not the first one on the page. This does seem like it is already a good compromise, it does allow multiple people to verify the same page, but doesn't allow anyone bad to craft a page with a zillion rel=me links on it and have a mastodon server follow them all.

**Comment by jbmagination** [comment]
I'm going to close this because my issue is resolved, but also I'm leaning towards this being a mastodon.social issue.
