### ISSUE TITLE
Federated timeline not showing posts without a language tag even with no languagefiltering settings.

### ISSUE THREAD

**Issue by fantoro** [mastodon/mastodon#20254]
### Steps to reproduce the problem

1. Follow a user from an instance that doesn't tag languages by default.
1.1. (Optional) Leave language filtering settings on the defaults (all boxes unchecked).
2. Wait for a post without a language tag from the user.
3. Check the federated timeline.

### Expected behaviour

The user's post should show up.

### Actual behaviour

The user's post does not show up. The only way one could see that post is if browsing the home timeline or checking the user's profile.

### Detailed description

It appears to me that the bug has been introduced with #19291.

### Specifications

Mastodon 4.0.0rc2+glitch
Ruby 3.0.4p208

**Comment by ClearlyClaire** [comment]
Should be closed by #20294
