### ISSUE TITLE
Consider: Switching from ImageMagick to Vips

### ISSUE THREAD

**Issue by matthewford** [mastodon/mastodon#20269]
### Pitch

In Rails 7, the default image process is now vips https://github.com/rails/rails/pull/42744

It's faster and uses less memory, ruby-vips can also fall back to ImageMagick if needed (although kt-paperclip doesn't use ruby-vips which would require switching to ActiveStorage).

The is a guide on how to migrate to vips can be found here: https://gist.github.com/brenogazzola/a4369965a1da426d50f11d080fe2e563

On Heroku either a custom apt-file or buildpack would be needed, https://elements.heroku.com/buildpacks/brandoncc/heroku-buildpack-vips

As the image processor is using kt-paperclip you would need to use this fork for the image processor https://github.com/tsu-social/paperclip-vips

It might also be worth switching to ActiveStorage, but I opened another issue for that.

### Motivation

All servers: 
- Libvips is less CPU intensive and uses less memory: https://github.com/libvips/libvips/wiki/Why-is-libvips-quick
- Security. The list of known CVEs for vips is considerably smaller than ImageMagick.

**Comment by renchap** [comment]
Having switched from `imagemagick` to `vips` in a major project, I can confirm all the advantages @matthewford described above.

The security aspect is major and the speed/memory boosts are impresive.

A potential drawback here is that `libvips` is often quite outdated on many linux distributions, so this could be a problem for people self-hosting their instance without a pre-build docker image. This is not a blocker, but we will need to force a minimal `libvips` version and probably add some documentation on how to install it using third-party packages on some old-but-widly-used distros.

**Comment by nemobis** [comment]
For information on broader usage it's also possible to look at the Wikimedia wikis' experience with [VipsScaler](https://www.mediawiki.org/wiki/Extension:VipsScaler). See for example [VipsScaler implementation by volunteer developer improves image handling on Wikimedia sites](https://diff.wikimedia.org/2013/09/12/vipsscaler-implementation-wikimedia-sites/) (2013).

**Comment by renchap** [comment]
FYI switching to Vips is in the roadmap. No date yet, but we want to rework the whole media storage system and it will most definitely be part of it.
