### ISSUE TITLE
Option to remove "..." and "load more"/"see more" to automatically see ALL posts

### ISSUE THREAD

**Issue by eobet** [mastodon/mastodon#20271]
### Pitch

Imagine loading up Mastodon in either the app or on the web and just being able to scroll to see all posts.

We're so close, but still not there... we're lacking just one small option!

### Motivation

Mastodon is about social media browsing without an algorithm, right? So things don't get hidden from you without you being in control? Unfortunately, leave Mastodon for a few days, and things do get hidden from you!

Having to click these three small dots (or the "load more") is terrible UX (and having to scroll down after doing so, and then up while trying to remember where you left off is even worse)!

Now, there must have been a motivation for hiding all posts not older than a  few hours when you check back into Mastodon after a few days, but I personally can't see it. To me, that's "an algorithm" (even if a very basic one) and it doesn't belong.

Mastodon should have an option to offer an unbroken stream of ALL posts.

**Comment by Gargron** [comment]
It means you were disconnected from the streaming API and there may be a gap where you've missed posts before it reconnected.

**Comment by eobet** [comment]
@Gargron well, that’s the technical explanation but the practical effect (at least for me) is that many people I follow spend a lot of their time on Mastodon boosting their own toots because they know people miss them.

Maybe I’m following “the wrong people” but it’s a significant chunk and it’s only gotten worse in the last year…

I’ve also experienced people saying they miss posts from users in different time zones (probably because they’re unaware of the “load more” feature or because they don’t want to repeatedly have to click it like I do).
