### ISSUE TITLE
Invisible Character to allow user to impersonate owning site they dont own.

### ISSUE THREAD

**Issue by deidyomega** [mastodon/mastodon#20273]
### Steps to reproduce the problem

1.  Edit profile
2. https://www.google.com‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ :‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ @siteiown.com
3. ??
4. Profit / Scam Users

### Expected behaviour

the [‎ ] char should be removed, for "verified" sites, the @ and :  should be removed/ignored

### Actual behaviour

the expected behavior isn't happening

### Specifications

I'm just a user of this server, I dont know how to tell the version.

https://tech.lgbt/web/@deidyomega

Reproducable on Opera and Edge, I'm sure all chromium browsers are effected.
Windows 11 (though I doubt that will effect anything)

**Comment by Gargron** [comment]
#20217
