### ISSUE TITLE
Mastodon handle verification in profile metadata

### ISSUE THREAD

**Issue by oherrala** [mastodon/mastodon#20306]
### Pitch

Add support for Mastodon handle verification for profile metadata.

E.g. if my profile metadata on account `@first@mastodon.example` points to `@second@toots.example` and then in `@second@toots.example` account the profile points to `@first@mastodon.example` I'd get verification check mark on both.

### Motivation

Some people have multiple handles in same or different servers. Verification would help build confidence that the another account is in fact same person.

**Comment by ineffyble** [comment]
This should already be the case. Any links in your profile metadata get the `rel="me"` attribute.

**Comment by oherrala** [comment]
@ineffyble Oh right, thanks! I'll try the URL format.

**Comment by ineffyble** [comment]
@oherrala If one of the Mastodon servers is running the release candidate of 4.0.0 you may hit a bug that was recently fixed. If they're both on Mastodon 3.5.3 or older you should be fine.

**Comment by oherrala** [comment]
@ineffyble I can confirm using URL format works. Would be nice if the other format worked also, but this solved my issue so closing. Thanks!
