### ISSUE TITLE
Get /Well-know-handler

### ISSUE THREAD

**Issue by redegelde** [mastodon/mastodon#20309]
### Steps to reproduce the problem

1. fix 500 notice
2.
3.
...

### Expected behaviour

posting delivers short 500 notice on screen

### Actual behaviour

stalls and after few times post comes online

### Detailed description

User are complaining about shot 500 notice on screen while posten an massage

Log give me this error lines

GET /well-known-handler/host-meta 404 Not Found No custom well-known config 2.138 ms - 71
GET /well-known-handler/webfinger?resource=acct:redegelde@mastodon.education 404 Not Found No custom well-known config 0.857 ms - 71

### Specifications

App Title and VersionMastodon 3.5.3
App IDe090d064-1b58-4e00-9724-7d4a3a70a729
Package Version[org.joinmastodon.cloudronapp@1.8.3](https://my.mastodon.education/#/appstore/org.joinmastodon.cloudronapp?version=1.8.3)
Last Updated2 weeks ago

**Comment by ineffyble** [comment]
@redegelde That error suggests that the servers hosting the Mastodon instance you are using might be having some issues. Have you tried checking with the admins who run the instance?
