### ISSUE TITLE
New filters do not seem to apply to streaming timeline

### ISSUE THREAD

**Issue by chloe-the-catgirl** [mastodon/mastodon#20317]
### Steps to reproduce the problem

1. Create a new filter, called "CW" with one keyword "CW" (exact match). The filter should apply to the start page and should hide things behind a warning.
2. Open the start page. The warnings are applied to the current postings.
3. However, when a new post arrives, it's not hidden.
4. Reloading the page applies the filter, until there's a new one.

### Expected behaviour

The postings should be hidden behind a warning.

### Actual behaviour

They were visible like if there was no filter at all.

### Detailed description

As I said in the reproduction, the filters work as expected, as long as you don't wait for new tweets. Maybe it's important to know that I use the "press button to reveal new postings" setting of Mastodon, haven't tried with the "regular" streaming experience. Also, it's the simple UI, not the Tweetdeck-like complex UI.

### Specifications

Mastodon v4.0.0-rc2
Edge 107 on macOS

**Comment by ClearlyClaire** [comment]
Do you know if you're using v4.0.0-rc2, or a more recent development version? If it's v4.0.0-rc2, it is most likely to be fixed by #19963

**Comment by ClearlyClaire** [comment]
That is surprising. Have you restarted `mastodon-sidekiq` after applying the change?

**Comment by chloe-the-catgirl** [comment]
That's the one I was missing. Thanks! It's fixed by #19963, so this issue can be closed as well. :blush:
