### ISSUE TITLE
Automated post deletion is not working

### ISSUE THREAD

**Issue by benpro** [mastodon/mastodon#20327]
### Steps to reproduce the problem

1. Enable automated post deletion
2. Wait some days
3. Nothing is deleted

### Expected behaviour

Old posts deleted

### Actual behaviour

No deletion

### Detailed description

![Screenshot_20221110_213305](https://user-images.githubusercontent.com/1057913/201092829-ac80da8d-a564-46fd-aa59-392e9c99b6a0.png)

I see the Sidekiq recurring job, but not deletion tasks.
![Screenshot_20221110_213333](https://user-images.githubusercontent.com/1057913/201092889-6b0fe98a-e787-4349-90ee-9547ed7ee170.png)

### Specifications

Mastodon 3.5.3

**Comment by ClearlyClaire** [comment]
That scheduler is designed to only schedule deletion jobs when your instance is practically idle, so there is no guarantee it will enqueue anything at each step.

This could be the reason, or there could be a bug. Has it still not deleted anything? As you are your own instance admin, you can easily check what your last status was with a Rails console (`RAILS_ENV=production bundle exec rails c`):
```ruby
account = Account.find_local!(username)
account.statuses.reorder(id: :asc).first
```

If nothing gets deleted, you can check which status is supposed to get deleted next with:
```ruby
cutoff_id = account.statuses_cleanup_policy.compute_cutoff_id
account.statuses_cleanup_policy.statuses_to_delete(1, cutoff_id, account.statuses_cleanup_policy.last_inspected).reorder(id: :asc).first
```

**Comment by benpro** [comment]
Nothing has been deleted since 3d ago when I enabled the feature.

 ```ruby
irb(main):005:0> account = Account.find_local!('benoit')
irb(main):006:0> account.statuses.reorder(id: :asc).first
=> 
#<Status:0x000055f9252287c8
 id: 108090964024181346,
 uri: "https://toots.benpro.fr/users/benoit/statuses/108090964024181346",
 text: "Another cool feature is to see cherry blossoms near you. (You can select full blossoms, partial, ...).",
 created_at: Thu, 07 Apr 2022 13:13:39.617180000 UTC +00:00,
 updated_at: Thu, 07 Apr 2022 13:13:39.617180000 UTC +00:00,
```

April 2022? Shouldn't be now minus 3 months?

```ruby
irb(main):009:0> cutoff_id = account.statuses_cleanup_policy.compute_cutoff_id
irb(main):010:0> account.statuses_cleanup_policy.statuses_to_delete(1, cutoff_id, account.statuses_cleanup_policy.last_inspected).reorder(id: :asc).first
=> 
#<Status:0x000055f922ee2278
 id: 108090964024181346,
 uri: "https://toots.benpro.fr/users/benoit/statuses/108090964024181346",
 text: "Another cool feature is to see cherry blossoms near you. (You can select full blossoms, partial, ...).",
 created_at: Thu, 07 Apr 2022 13:13:39.617180000 UTC +00:00,
 updated_at: Thu, 07 Apr 2022 13:13:39.617180000 UTC +00:00,
 in_reply_to_id: nil,
 reblog_of_id: nil,
 url: nil,
 sensitive: false,
 visibility: "public",
 spoiler_text: "",
 reply: true,
 language: "en",
 conversation_id: 2069698,
 local: true,
 account_id: 1,
 application_id: 46,
 in_reply_to_account_id: 1,
 poll_id: nil,
 deleted_at: nil,
 edited_at: nil,
 trendable: nil,
 ordered_media_attachment_ids: nil>
```

**Comment by benpro** [comment]
Oh wait, it is changing... So I guess it is working, it is just super slow.

**Comment by benpro** [comment]
I would suggest to have some tootctl feature to know if deleting is in progress instead of some rails console commands.

**Comment by ClearlyClaire** [comment]
It is super slow! It is designed to not put strain on your server nor the network.
