### ISSUE TITLE
more compact notifications view

### ISSUE THREAD

**Issue by expertsleepers** [mastodon/mastodon#20329]
### Pitch

The notifications column could be made more compact, so you can scan over a lot of notifications quickly.

Specifically, boost notifications of my posts with embedded media (videos, bandcamp links etc.) don't need to show the embedded media, which just makes it huge. Consider this, which is using the full height of my screen to show me that a user favourited and boosted one post:
<img width="586" alt="Screenshot 2022-11-10 at 13 24 43" src="https://user-images.githubusercontent.com/7710860/201103494-528202f4-6aa1-45d9-9f53-2dc243d2bfb6.png">

### Motivation

Now the platform is taking off and we're all getting a lot more notifications, this would make it much easier to stay on top of things without missing important notifications.

**Comment by shleeable** [comment]
There was a bug a short while ago.. but it was actually a great feature.
I want to see this on concurrent notifications.

![image](https://user-images.githubusercontent.com/17537000/201113614-d66654f3-bb5b-4e9a-9b61-24a95c446b89.png)
