### ISSUE TITLE
Mobile view on user profiles could have some style changes for clarity

### ISSUE THREAD

**Issue by davidwolfpaw** [mastodon/mastodon#20334]
### Steps to reproduce the problem

1. Navigate to a user profile on a mobile web view of 360px or lower
2. Note the lack of visible profile picture

### Expected behaviour

Display profile picture

### Actual behaviour

profile picture hidden

### Detailed description

I noted this after a user pointed the issue out. When viewing a user profile, you don't get to see the user photo. I feel that this can cause confusion (as it did for that user) in ensuring that they clicked on the profile that they want to view more of.
 
![current layout, without profile photo](https://user-images.githubusercontent.com/1971070/201115781-3278f03f-91e6-4d13-8bf6-83bea285ec03.jpg)

![suggested layout, removing the `display: none` on the profile photo](https://user-images.githubusercontent.com/1971070/201115919-60e76b38-8e25-44bf-96f0-05d3eccdc545.jpg)

### Specifications

Mastodon v3.5.3

**Comment by ClearlyClaire** [comment]
The whole server-side-rendered interface will be discontinued in 4.0, replaced with the React web interface. There may be issues with it, but the avatar thing is not one anymore.
