### ISSUE TITLE
Firefox security preventing access to Android sign-in to @Romancelandia@club

### ISSUE THREAD

**Issue by SD-56** [mastodon/mastodon#20348]
### Steps to reproduce the problem

1.  using Android mobile
2.  Firefox app
3.  pasting in sign in link -  https://romancelandia.club/auth/sign_in
4.  Error message as per image attached
5.  Cannot bypass error message.

![Screenshot_20221110-185249](https://user-images.githubusercontent.com/117940889/201182877-3c79c31f-401c-4e3e-88a8-7c2a2394217d.png)

### Expected behaviour

EITHER - there should be no problem with Romancelandia.club's permissions  OR the user bypass-the-risk option should be present

### Actual behaviour

On the Android the error message can't be bypassed and so I cannot log into my Mastodon (romancelandia.club) account

### Detailed description

As above.

### Specifications

PC - 
Mastodon 3.5.3
Windows 10
Firefox 106.0.5

Phone - 
Firefox 106.1.0
Mastodon 1.1.3
Android 7.0

**Comment by ClearlyClaire** [comment]
This is not an issue with the Mastodon software, but an issue with this particular server, Firefox, and/or your internet connection.
