### ISSUE TITLE
Cannot login android app

### ISSUE THREAD

**Issue by rlresende** [mastodon/mastodon#20344]
### Steps to reproduce the problem

1. Open app
2. Enter the username and password and received an error with "Invalid E-mail address or password"

My device is a Xiaomi 11T Pro

### Expected behaviour

Make login in the app

### Actual behaviour

Cannot make login in the app

### Detailed description

1. Open app
2. Enter the username and password and received an error with "Invalid E-mail address or password"

My device is a Xiaomi 11T Pro

### Specifications

![photo1668105755 (1)](https://user-images.githubusercontent.com/2736213/201180322-4bfbbdff-e051-43c8-b038-aa0affc6528a.jpeg)
![photo1668105755](https://user-images.githubusercontent.com/2736213/201180325-fe7943ec-c990-485d-b9e3-b2d1a884c2cf.jpeg)

**Comment by ineffyble** [comment]
@rlresende Are you able to login to the same Mastodon instance via web?

**Comment by rlresende** [comment]
@ineffyble yes, in the same instance. By the way, i able to login via web and in another device a samsung galaxy a52 too.
