### ISSUE TITLE
Mastodon 4.0.0rc returns status 500 on POST /api/v1/filters

### ISSUE THREAD

**Issue by connyduck** [mastodon/mastodon#20358]
### Steps to reproduce the problem

try to create a new filter with POST /api/v1/filters

### Expected behaviour

status 200 success

### Actual behaviour

error 500

### Detailed description

--> POST https://mastodon.social/api/v1/filters
Content-Type: application/x-www-form-urlencoded
Content-Length: 67
User-Agent: Tusky/19.0-a9c6f695 Android/12 OkHttp/4.10.0
Authorization: Bearer ...
phrase=home&context%5B%5D=public&irreversible=false&whole_word=true

<-- 500 https://mastodon.social/api/v1/filters (142ms)

### Specifications

mastodon.social (v4.0.0rc1)

Works fine on chaos.social (3.5.3)

**Comment by trwnh** [comment]
Oh, it seems here is the issue:

https://github.com/mastodon/mastodon/blob/cf4992c918459187962a9e2f389f9ccb4f1b825d/app/controllers/api/v1/filters_controller.rb#L54-L64

keyword_params tries to slice whole_word from resource_params, but resource_params doesn't permit whole_word

**Comment by trwnh** [comment]
Actually never mind -- it was fixed in https://github.com/mastodon/mastodon/pull/19878

**Comment by ClearlyClaire** [comment]
Fixed by #19878 indeed!
