### ISSUE TITLE
Long moderated server names make server moderation list unusable

### ISSUE THREAD

**Issue by ajfite** [mastodon/mastodon#20351]
### Steps to reproduce the problem

View the server moderation list at instance/about (you can check out mine with the issue at https://toot.nclf.net/about) after blocking a server with an absurdly long name

### Expected behaviour

Server list is either horizontally scrollable or long server name is truncated

### Actual behaviour

List falls off edge of its container and you can't see the ban reasons for servers

### Detailed description

See photo examples:

Advanced view:
![image](https://user-images.githubusercontent.com/1069581/201187034-3cc761a6-4aee-4224-a46f-81839fca0f17.png)

Standard view:
![image](https://user-images.githubusercontent.com/1069581/201187071-4a8a32a5-2b4f-45a0-8a7f-b1bf1da7170a.png)

### Specifications

Firefox 106.0.5
Windows 11

Mastodon v4.0.0rc2+glitch (this is also present in non-glitch vanilla Mastodon)

**Comment by ClearlyClaire** [comment]
Fixed by #20391
