### ISSUE TITLE
Has the Mailers queue been merged with another queue?

### ISSUE THREAD

**Issue by ralfr** [mastodon/mastodon#20366]
### Steps to reproduce the problem

This probably isn't a bug report. I'm on 4.0.0rc2. In Sitekiq > Queues I no longer see a Mailers queue, just default, push, pull and scheduler. However, mails are being sent.

In fact, I observed a strange behavior. In order to speed up things, I added three Sidekiq processes, the two additional ones only serving default, push and pull and *not* scheduler (as advised as per the documentation.)

However, in the logs of our email provider (Mailgun) we observed, that Mastodon send SMTP requests for the same email recipient multiple times.

Is this a bug? What happened to the Mailers queue?

### Expected behaviour

n/a

### Actual behaviour

n/a

### Specifications

Mastodon 4.4.0rc2, non-docker

**Comment by ralfr** [comment]
This is really getting to a point where I probably have to shut down the instance until it gets resolved. I killed 3 of the 4 Sitdekiq processes and only have one running. Mastodon still is sending multiple SMTP requests to the mail provider for a single user. Sometimes the registration confirmation is sent 5 times within a five minute window.

**Comment by ralfr** [comment]
Here is an example of how the email queue looks. Accepted = SMTP request from Mastodon received. OK = Sent.

![Sending__Logs_-_Mailgun](https://user-images.githubusercontent.com/112841/201225187-0cc2f716-1883-47c3-8aa0-b1dbdb34d291.jpg)

**Comment by trwnh** [comment]
Fixed by https://github.com/mastodon/mastodon/pull/20274
