### ISSUE TITLE
Can't upload images on Mastodon.Top

### ISSUE THREAD

**Issue by ChristeosPir** [mastodon/mastodon#20369]
### Steps to reproduce the problem

1. On my Mastodon homepage: https://mastodon.top/web/@CP93.
2. Add text in Toot window.
3. Click on paperclip to add a file.
4. Select the file and click Open.
5. Progress bar goes almost to end and message says Uploading.
6. It stays there forever.
...

### Expected behaviour

Upload should complete and new Toot should be posted.

### Actual behaviour

Nothing.

### Detailed description

See Steps, above.

### Specifications

Mastodon 3.5.3
Firefox 106.0.5 64 bit
MacBook Pro 2019
macOS Monterey 12.6.1

**Comment by idanoo** [comment]
This will be due to that specific instance running behind.

The admin will need to increase the sidekiq workers.

**Comment by ineffyble** [comment]
As mentioned, you'll need to reach out to the admins who run mastodon.top for help with this.

**Comment by YJSoft** [comment]
Please ask your server admin first, then Upload to here when you sure that's not server's fault.

**Comment by ClearlyClaire** [comment]
In 3.5.3, uploads are all processed in background jobs. This is most likely Mastodon.Top being under load and thus taking a long amount of time before uploads are processed.
