### ISSUE TITLE
[Feature Request] Modify users language from user editor as admin/moderator

### ISSUE THREAD

**Issue by supernovae** [mastodon/mastodon#20362]
### Pitch

As an Admin or a Moderator - In the user editor, be able to modify/set the users language to match the language they're tooting in.

### Motivation

Users register on app/mobile and leave language set to "english" but speak in other language - local timeline shows stuff people can't read and the users native language timeline doesn't show it if they did select correct language.

**Comment by nemobis** [comment]
So far I did this by manually altering the database. :grimacing:
