### ISSUE TITLE
Block and/or mute all followers of a user

### ISSUE THREAD

**Issue by buerviper** [mastodon/mastodon#20392]
### Pitch

There should be an option to automatically block and/or mute all followers of a certain account at once. Currently, you can only block/mute either a single user or a whole instance, but these followers might be spread over multiple instances etc.

### Motivation

Users who engage in harassment might encourage their followers to harass certain other users, or you already know that followers of a troll account might engage in trolling themselves. These users would need to block/mute each of these single users individually if they are spread out over several instances or are members of popular instances which you don't want to block/mute in total - or it might take some time until these users (or their instances) are defederated, banned, etc. Going through the follower lists and blocking/muting each member individually is time-consuming for very large accounts.

**Comment by Nachtpfoetchen** [comment]
I think moderation in the end should not be the job of the users of an instance but of the moderation team of an instance. Instance wide moderation makes them safer and better for all users. 

Unfortunately some big instances are known for pretty bad moderation -  which is not how it should be.
Emphasizing on stronger block tools for the instance user would make the expirince  better for users on the poorly moderated instances and people that want to be in contact with these instances but in the end it would imo encourage  this kind of bad behavior from instance admins.
The solution is imo: some big instances should have better moderation. If they are not,  people that get harassed need to be on instances that take messurements to protect their users from harassment.
