### ISSUE TITLE
Add edit indicator for edited posts

### ISSUE THREAD

**Issue by Andre601** [mastodon/mastodon#20410]
### Pitch

There should be an indicator (Either text like `(Edited)` or an icon like a pencil or smth) on posts that have been edited by the author.

### Motivation

From what I can see is there no actual indicator for posts that have been edited.
This should be the case for the sake of transparancy, as a person could post a thing, gather replies, reactions, etc. and then edit the post to make it have a different meaning/tone (Basically write a message to gain favourites and reposts/boosts and then change it to make it look like people support your PoV, which may not be a favourible one).

**Comment by Cassolotl** [comment]
The indicator is meant to be an asterisk next to the timestamp, I think?

**Comment by Andre601** [comment]
> The indicator is meant to be an asterisk next to the timestamp, I think?

Oh yeah, there is one indeed... Tho given the fact I didn't see it shows that it isn't that clear to be honest...
Probably due to its location which by default seems to be at the bottom-right of the post which someone may not even look at because it's away from the main post...

Maybe in the top right (alongside the publicity and language indicators) could be a better place. Tho idk if it wouldn't be too crowded then...

**Comment by ClearlyClaire** [comment]
> Maybe in the top right (alongside the publicity and language indicators) could be a better place. Tho idk if it wouldn't be too crowded then...

The interface you're describing sounds like glitch-soc, not upstream Mastodon.

**Comment by Andre601** [comment]
> The interface you're describing sounds like glitch-soc, not upstream Mastodon.

That's true... Didn't know there is a difference between those and thought the one used is actually using Mastodon's default formats.
