### ISSUE TITLE
Language dropdown does not have sufficient contrast in high-contrast mode

### ISSUE THREAD

**Issue by zuzak** [mastodon/mastodon#20432]
### Steps to reproduce the problem

1. Turn on high-contrast dark mode
2. Click the button to switch language

### Expected behaviour

I was able to easily read the text while selected

### Actual behaviour

The contrast was too low and I couldn't read the text

### Detailed description

High contrast mode:
![image](https://user-images.githubusercontent.com/817054/201398423-b6a98c7f-c9e4-491c-8fb5-7fcb47b4984a.png)

I should be able to read the current-language translation of the language name while it's highlighted, to ensure I select the right one. At the moment, because the colour of the language name and the roll-overhighlight is the same, the text disappears at the exact moment I want to read it. Moreover, the text in both high contrast and light mode when not highlighted is such a light grey you can barely read it against the white dropdown.

This is not the case in the non-high-contrast dark skin, which ironically has higher contrast than the high-contrast version:

Dark mode:
![image](https://user-images.githubusercontent.com/817054/201399495-e6de28b6-56fe-45b8-a588-a7271c0e60f0.png)

Light mode:
![image](https://user-images.githubusercontent.com/817054/201399610-4addf479-239f-49eb-b5b1-47b9776d3def.png)

### Specifications

Mastodon 3.5.3; Chrome on Chrome OS.

**Comment by zuzak** [comment]
This seems fixed in 4.0.2.

**Comment by ChasBelov** [comment]
Not working in 4.1.0.
