### ISSUE TITLE
Bug: S3_ALIAS_HOST value is ignored when streamed posts are displayed.

### ISSUE THREAD

**Issue by MikeHuntington** [mastodon/mastodon#20434]
### Steps to reproduce the problem

1. Set a S3_ALIAS_HOST value in the environmental file and restart Mastodon
2. Go to the Federation page
3. When new posts are streamed in, the S3 url is incorrect.

The S3_ALIAS_HOST value is honored throughout the app, however whenever data is streamed in, it reverts the url to not use S3_ALIAS_HOST.

### Expected behaviour

use the S3_ALIAS_HOST value

### Actual behaviour

does not use the S3_ALIAS_HOST value

### Detailed description

When visiting the web app normally and browsing the app images and content load perfectly with the S3_ALIAS_HOST value in tact. 

However, when a new toot is made and the app streams in the new post, all the media and images are missing because S3_ALIAS_HOST value isn't being used. The same applies if you sit on the federation page and wait for new posts to steam in. 

The media urls only seem to be incorrect for newly steamed in content. Once you refresh the page, the urls are working perfectly, until new posts are streamed in again.

### Specifications

Mastodon 3.5.3
Node.js 16.18.0

Google Chrome 106

**Comment by ClearlyClaire** [comment]
Did you forget to restart `mastodon-sidekiq`?

**Comment by MikeHuntington** [comment]
> 

Wow that solved my issue. thank you so much. I only restarted the other services.
