### ISSUE TITLE
ProxyPass Nginx to Apache

### ISSUE THREAD

**Issue by AzisPT** [mastodon/mastodon#20462]
### Steps to reproduce the problem

So, I have a Windows Server 2016 running apache, and I installed Virtual Box in it running Debian 11 and I put mastodon working (I tested while I port forwarded the 80 to the Nginx server) but turns out I need the port 80 for the Apache server, so I am trying to ProxyPass the VM trough the Apache.

httpd.conf

<VirtualHost *:443>

ServerName domain.com

SSLEngine on

SSLProtocol -all +TLSv1.2

SSLHonorCipherOrder on

SSLProxyEngine On

SSLCertificateFile "C:\Certbot\live\server\fullchain.pem"

SSLCertificateKeyFile "C:\Certbot\live\server\privkey.pem"

ProxyPreserveHost On

RequestHeader set X-Forwarded-Proto "https"

ProxyPass /api/v1/streaming/ ws://192.168.1.28:4000/

ProxyPassReverse /api/v1/streaming/ ws://192.168.1.28:4000/

ProxyPass / http://192.168.1.28:3000/

ProxyPassReverse / http://192.168.1.28:3000/

</VirtualHost>

Apache error.log

[Fri Nov 11 22:58:33.793338 2022] [proxy:error] [pid 4296:tid 1868] (OS 10061)No connection could be made because the target machine actively refused it. : AH00957: http: attempt to connect to [192.168.1.28:3000](https://192.168.1.28:3000/) ([192.168.1.28:3000](https://192.168.1.28:3000/)) failed

[Fri Nov 11 22:58:33.793338 2022] [proxy_http:error] [pid 4296:tid 1868] AH01114: HTTP: failed to make connection to backend: [192.168.1.28](https://192.168.1.28/)

### Expected behaviour

I should be able to enter my instance

### Actual behaviour

I get prompted with a error 503

### Specifications

Mastodon 3.5.3

Running in a Debian 11 Virtual Machine with Nginx

Trying to Run in Apache on Windows

**Comment by ineffyble** [comment]
This error shows that nothing is listening in port 3000 on 192.168.1.28. So you'll need to investigate why that is. It could be wrong IP address, wrong port, that nginx in Debian is only binding to `localhost`, or something else.

**Comment by AzisPT** [comment]
```
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}
 
upstream backend {
    server 127.0.0.1:3000 fail_timeout=0;
}
 
upstream streaming {
    server 127.0.0.1:4000 fail_timeout=0;
}
 
proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=CACHE:10m inactive=7d max_size=1g;
 
server {
  listen 80;
  listen [::]:80;
  server_name masto.azisserver.me;
  root /home/mastodon/live/public;
  location /.well-known/acme-challenge/ { allow all; }
  location / { return 301 https://$host$request_uri; }
}
 
server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name masto.azisserver.me;
 
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers HIGH:!MEDIUM:!LOW:!aNULL:!NULL:!SHA;
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;
  ssl_session_tickets off;
 
  # Uncomment these lines once you acquire a certificate:
  ssl_certificate     /home/azis/Desktop/fullchain.pem;
  ssl_certificate_key /home/azis/Desktop/privkey.pem;
 
  keepalive_timeout    70;
  sendfile             on;
  client_max_body_size 80m;
 
  root /home/mastodon/live/public;
 
  gzip on;
  gzip_disable "msie6";
  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;
  gzip_buffers 16 8k;
  gzip_http_version 1.1;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml image/x-icon;
 
  add_header Strict-Transport-Security "max-age=31536000" always;
 
  location / {
    try_files $uri @proxy;
  }
 
  location ~ ^/(emoji|packs|system/accounts/avatars|system/media_attachments/files) {
    add_header Cache-Control "public, max-age=31536000, immutable";
    add_header Strict-Transport-Security "max-age=31536000" always;
    try_files $uri @proxy;
  }
 
  location /sw.js {
    add_header Cache-Control "public, max-age=0";
    add_header Strict-Transport-Security "max-age=31536000" always;
    try_files $uri @proxy;
  }
 
  location @proxy {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Proxy "";
    proxy_pass_header Server;
 
    proxy_pass http://127.0.0.1:3000;
    proxy_buffering on;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
 
    proxy_cache CACHE;
    proxy_cache_valid 200 7d;
    proxy_cache_valid 410 24h;
    proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
    add_header X-Cached $upstream_cache_status;
    add_header Strict-Transport-Security "max-age=31536000" always;
 
    tcp_nodelay on;
  }
 
  location /api/v1/streaming {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Proxy "";
 
    proxy_pass http://127.0.0.1:4000;
    proxy_buffering off;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
 
    tcp_nodelay on;
  }
 
  error_page 500 501 502 503 504 /500.html;
}
```

This is what I have in my Nginx, what could be wrong?

**Comment by ineffyble** [comment]
Your nginx is listening on 80/443. Your Mastodon web is listening on 3000. Are you trying to go Apache->nginx or Apache->mastodon?

**Comment by AzisPT** [comment]
I'm trying to go Apache -> Nginx

So, I have a VM running Nginx, but my Windows Server run's Apache, I want to show mastodon to people through the Apache

**Comment by ineffyble** [comment]
In that case you need your Apache config to proxy to port 80 or 443, which are the ports nginx is running on.

**Comment by AzisPT** [comment]
When I do that, it gives me an error in the browser that it is redirecting me too much times.

**Comment by ineffyble** [comment]
I would guess that's because you have a double-SSL situation and are telling nginx to redirect/upgrade the connection. You probably need to either change nginx to not redirect connections on port 80, or you'll need to set up your Apache proxy with SSL proxying.

**Comment by AzisPT** [comment]
Now I get this on the website:

Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: Error reading from remote server

Apache error:

[Sat Nov 12 11:50:58.841009 2022] [proxy:error] [pid 7872:tid 1860] AH00898: Error reading from remote server returned by /
[Sat Nov 12 11:50:58.888428 2022] [proxy_http:error] [pid 7872:tid 1860] (70014)End of file found: AH01102: error reading status line from remote server 192.168.1.28:443, referer: https://masto.azisserver.me/
[Sat Nov 12 11:50:58.897416 2022] [proxy_http:error] [pid 7872:tid 1860] (70014)End of file found: AH01102: error reading status line from remote server 192.168.1.28:443, referer: https://masto.azisserver.me/
[Sat Nov 12 11:50:58.897416 2022] [proxy:error] [pid 7872:tid 1860] AH00898: Error reading from remote server returned by /favicon.ico, referer: https://masto.azisserver.me/

**Comment by AzisPT** [comment]
I fixed the error above removing the http2 from the listen 443, but now I have the elephant saying something went wrong on our end.

**Comment by vincent-abel** [comment]
Reason: Error reading from remote server
Is often simply because you can't have a proper answer from the remote (in that case nginx). You should look into nginx error log to see what it sees/does

**Comment by AzisPT** [comment]
Error in Nginx: 111: Connection refused while connecting to upstream

**Comment by ineffyble** [comment]
> now I have the elephant saying something went wrong on our end.

You'll probably want to check the Mastodon logs for details of the error.

**Comment by ineffyble** [comment]
"Connection refused while connecting to upstream" suggests that Mastodon is not running correctly because nginx couldn't talk to it.

**Comment by AzisPT** [comment]
It's probably because I changed these two option from:

```
upstream backend {
    server 127.0.0.1:3000 fail_timeout=0;
}
 
upstream streaming {
    server 127.0.0.1:4000 fail_timeout=0;
}
```

to:

```
upstream backend {
    server 192.168.1.28:3000 fail_timeout=0;
}
 
upstream streaming {
    server 192.168.1.28:4000 fail_timeout=0;
}
```

Because when I put it with 127.0.0.1 it gives me the error of too many redirects.

**Comment by vincent-abel** [comment]
So get back to 127.0.0.1, for nginx to Work with it's backend.
And get to the bottom of the redirect error that is occuring between apache and nginx ;)

**Comment by AzisPT** [comment]
So I figured it out!

I used on the Debian 11 / Nginx side this code:

```
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

server {
  listen 80;
  listen [::]:80;
  server_name 192.168.1.28;

  keepalive_timeout    70;
  sendfile             on;
  client_max_body_size 0;

  root /home/mastodon/live/public;

  gzip on;
  gzip_disable "msie6";
  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;
  gzip_buffers 16 8k;
  gzip_http_version 1.1;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

  add_header Strict-Transport-Security "max-age=31536000";

  location / {
    try_files $uri @proxy;
  }

  location ~ ^/(emoji|packs|system/accounts/avatars|system/media_attachments/files) {
    add_header Cache-Control "public, max-age=31536000, immutable";
    try_files $uri @proxy;
  }
 location @proxy {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Proxy "";
    proxy_pass_header Server;

    proxy_pass http://127.0.0.1:3000;
    proxy_buffering off;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    tcp_nodelay on;
  }

  location /api/v1/streaming {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Proxy "";

    proxy_pass http://127.0.0.1:4000;
    proxy_buffering off;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    tcp_nodelay on;
  }

  error_page 500 501 502 503 504 /500.html;
}
```

And on the Apache side I used:

```
<VirtualHost *:443>
   ServerName masto.azisserver.me
 
   Protocols h2 h2c http/1.1

   SSLEngine on
   SSLProtocol -all +TLSv1.2
   SSLHonorCipherOrder on
   SSLCipherSuite EECDH+AESGCM:AES256+EECDH:AES128+EECDH
 
   SSLCertificateFile "C:\Certbot\live\azisserver.me\fullchain.pem"
   SSLCertificateKeyFile "C:\Certbot\live\azisserver.me\privkey.pem"
 
   ProxyPreserveHost On
   RequestHeader set X-Forwarded-Proto "https"

   ProxyPass / http://192.168.1.28:80/
   ProxyPassReverse / http://192.168.1.28:80/
</VirtualHost>
```

Thanks everyone who helped me!

**Comment by vincent-abel** [comment]
Glad to help. So what was the error on the apache/nginx configuration?

**Comment by AzisPT** [comment]
Apache was being redirected indefinitely because of some problem that I didn't quite understand, so I removed the port 443 and copied what was on it to the port 80 with some subtle changes and it worked!

**Comment by oelison** [comment]
That was my solution:
        ```
# RequestHeader set X-Forwarded-Proto "https" early
RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}
```

**Comment by AzisPT** [comment]
So, due to modifications in mastodon I will update the fix that I had done before, because some people can be interested in that.

Nginx:

`map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

upstream backend {
    server 127.0.0.1:3000 fail_timeout=0;
}

upstream streaming {
    # Instruct nginx to send connections to the server with the least number of connections
    # to ensure load is distributed evenly.
    least_conn;

    server 127.0.0.1:4000 fail_timeout=0;
    # Uncomment these lines for load-balancing multiple instances of streaming for scaling,
    # this assumes your running the streaming server on ports 4000, 4001, and 4002:
    # server 127.0.0.1:4001 fail_timeout=0;
    # server 127.0.0.1:4002 fail_timeout=0;
}

proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=CACHE:10m inactive=7d max_size=1g;

server {
  listen 80;
  listen [::]:80;
  server_name 192.168.1.21;

  keepalive_timeout    70;
  sendfile             on;
  client_max_body_size 99m;

  root /home/mastodon/live/public;

  gzip on;
  gzip_disable "msie6";
  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;
  gzip_buffers 16 8k;
  gzip_http_version 1.1;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml image/x-icon;

  location / {
    try_files $uri @proxy;
  }

  # If Docker is used for deployment and Rails serves static files,
  # then needed must replace line `try_files $uri =404;` with `try_files $uri @proxy;`.
  location = /sw.js {
    add_header Cache-Control "public, max-age=604800, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/assets/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/avatars/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/emoji/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/headers/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/packs/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/shortcuts/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/sounds/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/system/ {
    add_header Cache-Control "public, max-age=2419200, immutable";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    add_header X-Content-Type-Options nosniff;
    add_header Content-Security-Policy "default-src 'none'; form-action 'none'";
    try_files $uri =404;
  }

  location ^~ /api/v1/streaming {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Proxy "";

    proxy_pass http://streaming;
    proxy_buffering off;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";

    tcp_nodelay on;
  }

  location @proxy {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Proxy "";
    proxy_pass_header Server;

    proxy_pass http://backend;
    proxy_buffering on;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    proxy_cache CACHE;
    proxy_cache_valid 200 7d;
    proxy_cache_valid 410 24h;
    proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
    add_header X-Cached $upstream_cache_status;

    tcp_nodelay on;
  }

  error_page 404 500 501 502 503 504 /500.html;
}`

Apache:

`<VirtualHost *:443>
   ServerName yourdomain.com
 
   Protocols h2 h2c http/1.1

   SSLEngine on
   SSLProtocol -all +TLSv1.2
   SSLHonorCipherOrder on
   SSLCipherSuite EECDH+AESGCM:AES256+EECDH:AES128+EECDH
 
   SSLCertificateFile "C:\Certbot\live\yourdomain.com\fullchain.pem"
   SSLCertificateKeyFile "C:\Certbot\live\yourdomain.com\privkey.pem"
 
   ProxyPreserveHost On
   RequestHeader set X-Forwarded-Proto "https"

   ProxyPass / http://192.168.1.21:80/
   ProxyPassReverse / http://192.168.1.21:80/
</VirtualHost>`
