### ISSUE TITLE
Only show Translate button for supported languages

### ISSUE THREAD

**Issue by mkljczk** [mastodon/mastodon#20461]
### Pitch

I think /api/v2/instance should provide `target_languages` and `source_languages` lists with languages supported by the enabled translation provider and this feature should be utilized by frontend.

### Motivation

Both DeepL and LibreTranslate have endpoints for supported languages list. Making the button only visible if both languages are supported would make the feature less confusing for users. Now it doesn't return translations in such cases and throws an error.

**Comment by c960657** [comment]
Fixed in #23879 (new approach in #24037).
