### ISSUE TITLE
Could not connect to elasticsearch:7.17.4 deploy with docker

### ISSUE THREAD

**Issue by Tsuk1ko** [mastodon/mastodon#20472]
### Steps to reproduce the problem

1. Uncomment all parts about elasticsearch in `docker-compose.yml`
2. Setup and start docker (directory permissions have been set correctly)
3. A tip about "Could not connect to Elasticsearch" will show in `/admin/dashboard`, but elasticsearch container started successfully
4. Clear elasticsearch data folder and change `elasticsearch:7.17.4` back to `elasticsearch-oss:7.10.2` in `docker-compose.yml` (revert cc7cebb79a2a9ed284e027b76d1038afb4f2a6ef and e3cebfa457cb5e645ac69162391a4153a3c6c4ad)
5. Restart docker, the tip disappear

### Expected behaviour

Could connect to Elasticsearch

### Actual behaviour

Could not connect to Elasticsearch

### Specifications

Mastodon v4.0.0rc2
Docker 20.10.21
Docker Compose v2.4.1

**Comment by pedroCX486** [comment]
It works for me, did uncomment the depends_on line and check if elastic isn’t throwing the permission exception?

For future reference, if anyone is having that AccessDeniedException problem:

sudo chown -R 1000:1000 elasticsearch/

This solves it. Make sure also the docker-compose.yml has the variables needed for ES to boot up.

**Comment by riker77** [comment]
The problem still persisted for me, although I already did the things pedroCX486 mentioned. Looking at the logs of the elasticsearch container, I found this line in there:

`max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]`

So I set the `vm.max_map_count` accordingly on my Linux host.

`sysctl -w vm.max_map_count=262144`

In order for this setting to survive a reboot, I added the assignment to `/etc/sysctl.conf`.

After that, the start of the es container succeeds.

**Comment by Tsuk1ko** [comment]
@riker77 Thank you, it works for me!

**Comment by bold84** [comment]
For anyone else running into the issue... it's also wort checking, if the elastic search host in the .env.production file is set to the correct hostname. I have found it set to localhost, which didn't work with the docker-compose setup.
Setting it to 

es

helped.

**Comment by k5123** [comment]
Here's another pointer that solved ES problems for me: After following all prior suggestions, the last problem was inside the env file: the default sets a username and password. 

The default install with docker-compose builds an ES instance that doesn't use authentication with username/pass, therefore specifying ES_USER/ES_PASS *AT ALL* will lead to problems. 

Comment out both username/password for ES and it should work. It did for me at least.
