### ISSUE TITLE
Move block imports to a separate tool

### ISSUE THREAD

**Issue by kaniini** [mastodon/mastodon#20471]
### Pitch

I just accidentally imported all of my following list from Twitter (generated with Fedifinder) as blocks by accident, because my mouse pointer was sitting over the dropdown list and scrolled it (due to having two fingers on the trackpad by accident) rather than moving down to the import button.

It seems strange to me to have constructive outcomes (creating new follow relationships and bookmarks) on the same screen as destructive outcomes (creating new block relationships).

These should be two different screens, or at the very least, it should prompt for verification before proceeding with a destructive operation, e.g. a modal which says "you are about to import 400 block relationships, are you sure you want to continue?"

### Motivation

People who don't want to accidentally follow their blocking list, or block their following list.  I suspect this type of mistake happens frequently.

**Comment by stramargio** [comment]
Same happened here, tbh.

**Comment by rscmbbng** [comment]
Not the same issue, but an outcome of the lack of feedback on list imports: https://github.com/mastodon/mastodon/issues/19770

**Comment by rscmbbng** [comment]
Longer term it would be important to do a complete design overhaul of blocklist managment, though. There is quite some scientific literature, in addition to many anecdotes, on how blocklists are either not effective enough or easy to abuse. Designing an interface that would allow one to inspect a blocklist before it is applied could help mitigate some of that at least. I'd be happy to collaborate on that if there is the desire to look in to it.

**Comment by ClearlyClaire** [comment]
Agreed, but the main purpose is to import your own blocks from a previous account, or a different account you maintain.

**Comment by jsandburg** [comment]
There is also the problem where if you import your following list as blocks, you can't undo it by simply re-uploading your blocks list and overwriting. I'm not sure why that's an option when it doesn't work for blocks. In reality, you cannot unblock anyone unless you do it manually by going into your profile.

**Comment by ClearlyClaire** [comment]
> There is also the problem where if you import your following list as blocks, you can't undo it by simply re-uploading your blocks list and overwriting. I'm not sure why that's an option when it doesn't work for blocks. In reality, you cannot unblock anyone unless you do it manually by going into your profile.

Hm, that sounds like a bug. I'll try to investigate later. Which version of Mastodon are you using?
