### ISSUE TITLE
Add index to speed up slow query

### ISSUE THREAD

**Issue by robmobz** [mastodon/mastodon#20496]
### Pitch

I received a warning that the query
`SELECT SUM("account_stats"."statuses_count") FROM "accounts" INNER JOIN "account_stats" ON "account_stats"."account_id" = "accounts"."id" WHERE "accounts"."domain" IS NULL`
was slow taking 20ms.  Checking the execution plan I found that it was spending almost the whole time running a sequential scan identifying if 
`accounts.domain IS NULL`

Putting a partial index on accounts.domain speeds the query up by almost 2 orders of magnitude to 0.3ms.  This was done by running
`CREATE INDEX index_accounts_on_domain_null ON accounts (domain) WHERE (domain IS NULL);` in postgres.

### Motivation

This should increase database performance on this query.

**Comment by Gargron** [comment]
This looks like the heavily cached query of "number of posts by local users" that used to be displayed before 4.0. That display is no longer in Mastodon.

**Comment by bplein** [comment]
My instance runs v4.0.2 and I am getting this same slow query warning in pghero. So my guess is that it is NOT limited to pre-4.0.
