### ISSUE TITLE
A Fractal, Hierarchical and Signal View of the Fediverse

### ISSUE THREAD

**Issue by triplefox** [mastodon/mastodon#2050]
![Map of the internet](https://46qasb3uw5yn639ko4bz2ptr8u-wpengine.netdna-ssl.com/files/2015/11/internet-map-FB.jpg)

[Social complexity](https://en.wikipedia.org/wiki/Social_complexity) is a term known to academia. It's not something I've studied, but it engages with many mathematical concepts, including fractals.

![Fractal zoom](https://media.giphy.com/media/ufj9KLaQpUmm4/giphy-tumblr.gif)

In fractals, boundaries are ambiguous: You have no way of knowing their true measure, you can only approximate their shape and appearance, and at different levels of depth the same region may  present differently. 

Fractals are a truthful way to view the boundaries of social graphs: rules are not just rules, we always want exceptions, and exceptions on top of those exceptions. We first say "that group is bad" and then add "except for my friend" and then add "but only because we always play the same game together". At each level, another nuance appears.

![Dragon curve](https://media.giphy.com/media/1YhkF7Js55nGg/giphy.gif)

A fractal boundary is also an *unknowable* one. It is non-partisan, and not subject to control. It is there for our exploration. In terms of decentralization's political project, it maps well to our intuitions.  Attempts to dissect human relationships into hard boundaries tend to be injurious.

![Berlin wall](http://www.pitara.com/wordpress/wp-content/uploads/2001/09/berlin-wall.jpg)

There are many ways in which a fractal may *form*. But within a social network, a pragmatic way to do so is to represent our local space with a *hierarchy*: a multitude of trees, with the user at the center, and the branches of the tree representing various rules and actions, an accumulated history over time. The full network is a connecting together of different trees.

![Binary tree](https://media.giphy.com/media/ygUwDJOjip2/giphy.gif)

From this view, technology features like shared spaces, blocks, content warnings, and administration options can approximate what a user ideally wants in their tree, but may also distort it to include content they do not want, to add undesired connections or remove critical ones.

![Hackers](https://68.media.tumblr.com/76a24d12bf7e57c5048c6838ca6fd79e/tumblr_oglodqrnFy1ve01pfo1_500.gif)

Open networks have a tendency to center their trees around a computer system, not a user, with the justification that mastery of the computer is a sufficient substitute for user-centric design. This has led to a computing-focused design, and inaccessibility as a consequence. If we take pains to distinguish the technical issues from the user intent, these outcomes are not inevitable.

![Signals](https://media.giphy.com/media/GZhx1Jy50gfIY/giphy.gif)

What users ultimately see as the output of their social graph is a signal, represented in the form of a "stream" or timeline. It stands to reason that we should consider applying signal processing concepts as an element of tree construction.

Bad actors ultimately cause a user-visible impact by being "bad signals". Signal processing is a major basis for today's machine learning technology, and has historically been applied to fight spam. The interest of mobs - in celebrities and harassment targets alike - can be seen as a form of spamming. We could train a neural network to recognize the vocabulary of the "dude in your mentions" and filter all of them at a stroke, rather than relying on sharp-edged, possessable knowledge like blocklists.

In practical terms, these ideas suggest several design goals for Mastodon or adjacent systems:

* The underlying infrastructure for permissions, blocking, filtering, etc. should (logically, if not physically) map to a tree structure. New trees may be derived by rewriting old ones, in the same way that compilers transform source code through a series of intermediate tree representations.
* Allow users to self-select and share any number of groups within and across instances, applying those to their tree. The user themselves is simply a group of 1. Groups may represent abstract computations like "friend of my friend", user-controlled lists like "people I block", or stateful shared lists like "rooms" or "channels". Instances, being computing units, should not have total control, although the existing topology may continue by making a group containing everyone that is on an instance.
* Allow mixtures of blacklist and whitelist behaviors among groups, reframing the production of resulting timelines into a signal processing system, connecting the various source assets and processing nodes of the tree through [dataflow programming](https://en.wikipedia.org/wiki/Dataflow_programming). This architecture offers similarities to Unix and existing Internet technologies.
* Top-level UX may present this infrastructure in a simplified form, visualizing these structures in full or reducing them to checkboxes. Instances may limit some parameters of capability as allowed by processing power. Some forms of signal processing might also be purely client-side or farmed out to a dedicated server. Changes in interface and limits create different "social instruments" to play, each with different qualities.

These goals make for an ambitious software architecture which can be evolved piecemeal, by refining each of the approximations we currently use. Many existing issue threads coincide with these goals already; others can do so with a slight re-examination.

**Comment by LogicalDash** [comment]
_Open networks have a tendency to center their trees around a computer system, not a user, with the justification that mastery of the computer is a sufficient substitute._

A sufficient substitute for what, please?
