### ISSUE TITLE
Add "Post to List only"

### ISSUE THREAD

**Issue by TymeForChange** [mastodon/mastodon#20528]
### Pitch

Add ability to **post to a List only**.  Add to the existing visibility options on post composition window menu. (Bonus points for being able to add people to Lists without them following you and/or you following them.)

### Motivation

All users could benefit from this segmentation option. Could reduce server load / processing. Timeline hygiene and compactness. Reduce signal-to-noise ration. Make for a more enjoyable (/less overwhelming) experience of catching up with posts. 

Cannot rely upon people using hashtags judiciously or at all. So, filtering is not a solution for targeting certain people with certain messages.

Case scenario:  People love to say _"Know how to tell if someone is vegan? Don't worry they will tell you."_  That's because we can't **Post To List Only**! >> grin <<

**Comment by nightpool** [comment]
This is already planned with the groups feature

**Comment by TymeForChange** [comment]
No, not really. As post https://github.com/mastodon/mastodon/pull/19059 reads, Groups isn't a local, account-level feature -- something that a user creates & manages within their own account. 

Groups is an **overly-complicated** solution to _my request / case scenario_: requiring group approval of new members; what to do with posts after a user leaves group; boosts or no boosts; do they cross instances; moderation; etc. Overkill.

What I am proposing is so simple; and it seems that the _mechanics are already in place_ with Lists. Each List already has a unique ID. So, if frontend user simply posts to the unique List ID, the backend sends post to all users whose record includes that List ID. The List 'members' server is of no concern (as is the case with proposed Groups). As is, List members can only be Followers. Fine - compromise. 

So, basically, without this feature, user would have to @-mention multiple users individually in a singe post. No one would do that, nor would anyone want to see that noise on their timeline. Need a shortcut for that action. 

**Groups or no Groups, I maintain that "Post to List only" would be an asset and popular local, **account-level** feature.** (One Twitter doesn't have, btw.)  **And very quick/easy to implement.** 

BONUS points for making Lists (members) available as an export/import, so that List owner can share their List with others.

BONUS BONUS points for adding an "Add to List ____" bulk option on the Following/Followers page. (Already proposed under another #case.)

 I'd happily contribute how I can to complete this. I'd will gladly expound on the Pitch and Motivation, if desired.
