### ISSUE TITLE
Image's "Edit" button hides itself after adding an image description

### ISSUE THREAD

**Issue by nightlyonie** [mastodon/mastodon#20522]
### Steps to reproduce the problem

1. Create a new toot
2. Add an image
3. Click on "Edit" and add an image description
4. Click on "Apply"

### Expected behaviour

The "Edit" button for that image should remain.

### Actual behaviour

It doesn't; needing to re-attach that image to correct this image's description.

### Detailed description
after adding alt text, but before submitting my post, the option to edit the alt text before posting it disappears.

![A screenshot of me composing a toot. It reads "a toot or something" and contains an image. The image itself is a screenshot of a text editor, with a rickroll link put into it. Normally, there would be an "Edit" button in the upper right corner of the image, but it's not there.](https://user-images.githubusercontent.com/45924578/201493086-6f8edc1f-181f-4782-a133-ce1d99ff6095.png)

### Specifications

https://github.com/mastodon/mastodon/commit/31005aad12c6a915a00501765a6dab25878326cb

Reproduceable on Google Chrome (107.0.5304.110 (Official Build) (64-bit)) and Mozilla Firefox (106.0.5 (64-bit)).

**Comment by kescherCode** [comment]
Fixed by 2d54986a03675dbad940948177037ce2f12d11b9. Thanks Claire!
