### ISSUE TITLE
Allow web users to view remote posts/follower/following lists inline in the web application

### ISSUE THREAD

**Issue by SamStephens** [mastodon/mastodon#20529]
### Pitch

Currently when you view a user profile from your local instance via the web application, you only see their follower/following that are visible to the local instance.

A link is provided, "Browse more on the original profile", that takes you to the users home server. However in doing so you leave the web application and are no longer interacting with that list using your logged in Mastodon identity.

Rather than this link, I suggest a link that will pull that list into the web application. This is a smoother experience for users, and allows them to interact with the list directly using their Mastodon identity.

### Motivation

The primary motiviation for this feature is that the existing behavior is a barrier to Mastodon usage for those who are not sufficiently technical to understand how identity does not carry across servers in Mastodon.

I witnessed this personally recently, when a family member started on Mastodon, found one of their friends, and then went to their following list to try and find other people they know. They were incredibly confused by the experience, and were ready to give up on Mastodon until I explained why they couldn't interact with the list using their identity, and how to easily copy and paste the link to each person into the search of their own instance.

I believe the argument has been made that it's the responsibility of individuals to understand how federation works. My argument here is that it's very technical; not just involving the actual federated nature of Mastodon instances, but also technical details of how authentication cookies are scoped to a particular domain.

On this basis I argue there's an equity of access issue here. If we say that users have to understand Mastodon federation well enough to handle interactions that require them to navigate to remote servers, we are disenfranchising users that are not technical enough to work with the complexity of these interactions.

I believe this argument stands for all interactions that require you to navigate to remote instances - that they are a barrier to non-technical Mastodon users, that there's an equity of access issue.

This feature has already been discussed and dismiss previously via https://github.com/mastodon/mastodon/issues/8301. However I think the arguments made against this feature deserve re-examining.

> Proxying the request to the remote server from within the request-response cycle puts a lot of strain on the server; if the remote server takes a long time to respond, it would DoS the server

The Mastodon mobile applications have already solved this problem. Based on the comments from @nightpool below, the Android application uses [GetAccountStatuses.java](https://github.com/mastodon/mastodon-android/blob/ba3219d9fcc27bfd2986790b029c045cd2f7e959/mastodon/src/main/java/org/joinmastodon/android/api/requests/accounts/GetAccountStatuses.java), [GetAccountFollowers.java](https://github.com/mastodon/mastodon-android/blob/ba3219d9fcc27bfd2986790b029c045cd2f7e959/mastodon/src/main/java/org/joinmastodon/android/api/requests/accounts/GetAccountFollowers.java) and [MastodonAPIRequest.java#L81](https://github.com/mastodon/mastodon-android/blob/01970ab69b50c297d59c015bc9628705576e378f/mastodon/src/main/java/org/joinmastodon/android/api/MastodonAPIRequest.java#L81) to retrieve remote statuses and followers by proxying these requests through the local server. If this is a reasonable pattern of behavior for the Android application, why is it not for the web application?

**Comment by vitorgrs** [comment]
This is definitely a need. Should be one of top priorities right now.

**Comment by nightpool** [comment]
This is feasible but I think it's a bandaid for the fundamental issue, which is the difficulty of interacting with accounts on remote servers. I would prioritize that issue over this one. (For example, by reviving the protocol handler idea or implementing a browser extension that can let you interact with remote servers from their profile pages)

**Comment by nightpool** [comment]
> I think a major counter to all of these arguments is that the Mastodon mobile applications have already solved this problem. If I understand [GetAccountStatuses.java](https://github.com/mastodon/mastodon-android/blob/ba3219d9fcc27bfd2986790b029c045cd2f7e959/mastodon/src/main/java/org/joinmastodon/android/api/requests/accounts/GetAccountStatuses.java), [GetAccountFollowers.java](https://github.com/mastodon/mastodon-android/blob/ba3219d9fcc27bfd2986790b029c045cd2f7e959/mastodon/src/main/java/org/joinmastodon/android/api/requests/accounts/GetAccountFollowers.java) and [MastodonAPIRequest.java#L81](https://github.com/mastodon/mastodon-android/blob/01970ab69b50c297d59c015bc9628705576e378f/mastodon/src/main/java/org/joinmastodon/android/api/MastodonAPIRequest.java#L81) correctly, the Android application pulls remote statuses and followers by making requests to the remote server.

You have misunderstood this code. This is requesting the statuses, followers, etc from the domain of the *currently signed-in user*, not the remote user in question. It would definitely not be safe, secure, privacy-preserving, or promote a robust, standards-based version of interoperability to directly assume every remote server implements the Mastodon API and then make requests directly to them to expose the user's IP address. If we did choose to implement this, we would need to proxy the request through the local instance server to hide the user's IP, and then have the local instance server transform the ActivityPub-formatted payload into a standard REST format. Again, technically doable, just of dubious value. (And still leaves open the possibility of timing / identifiability concerns)

**Comment by SamStephens** [comment]
> You have misunderstood this code. 

Thanks @nightpool - I'll edit the original issue description to take this into account.

**Comment by SamStephens** [comment]
@nightpool 

> This is feasible but I think it's a bandaid for the fundamental issue, which is the difficulty of interacting with accounts on remote servers. I would prioritize that issue over this one. (For example, by reviving the protocol handler idea or implementing a browser extension that can let you interact with remote servers from their profile pages)

Good call; I actually meant to mention solving the problem of taking your identity to remove servers as a possibility, but forgot.

I guess the thing here is that the suggestion here can be implemented without any fundamental changes to the Mastodon model; we are simply taking behaviors the mobile applications already have and implementing them in the web application.

Whereas there's really complex issues with trust to solve with using your identity on a remote server. How do you set this up so I can interact with content on a remote server as seamlessly as I do on my local server, without allowing the remote server to spoof me and take actions I haven't consented to? I'm not privy to prior discussion, the protocol handler idea you mention for example, so I'm sure you've already contemplated these obstacles, but it's clear it's far from trivial and requires really thorough trust model assessment.

I will say I'm not a fan of needing a browser extension for this; it's just another barrier of entry to non-technical users.

**Comment by SamStephens** [comment]
@nightpool 

>If we did choose to implement this, we would need to proxy the request through the local instance server to hide the user's IP, and then have the local instance server transform the ActivityPub-formatted payload into a standard REST format. Again, technically doable, just of dubious value. (And still leaves open the possibility of timing / identifiability concerns).

If there's an API that the mobile applications are calling locally to get these statuses, isn't this already implemented? Aren't your timing/identifiability concerns already present? Isn't the only change needed to the frontend Mastodon application to consume the same APIs the mobile applications already consume?

And I think the statement "of dubious value" is unfairly dismissive of how the status quo is a barrier of entry to non-technical users. Everything I've seen of Mastodon values inclusivity. I'd argue making Mastodon more accessible to non-technical users is an important part of that inclusivity.

**Comment by afontenot** [comment]
> If there's an API that the mobile applications are calling locally to get these statuses, isn't this already implemented? Aren't your timing/identifiability concerns already present?

Unless I'm mistaken, they said that *it is not* implemented.

> This is requesting the statuses, followers, etc from the domain of the *currently signed-in user*, not the remote user in question.

Moreover, unless I'm mistaken, some servers hide their social graphs or hide them to non-users. In this case there would be no way for federated servers to know the complete list of followers.

**Comment by SamStephens** [comment]
@afontenot oh man, I'm sorry, I'm not having a good day for reading comprehension. Honestly, I've made such a mess of this issue at this point, I'm going to close it, and create a clean one based on my new understanding.

**Comment by SamStephens** [comment]
Apologies to @vitorgrs @nightpool @afontenot for making such a mess of this issue - I've hopefully done a better job of restating myself as https://github.com/mastodon/mastodon/issues/20533

**Comment by afontenot** [comment]
@SamStephens Don't worry about it, happens to the best of us!
