### ISSUE TITLE
public/packs data does not precompile

### ISSUE THREAD

**Issue by yawnbox** [mastodon/mastodon#20535]
### Steps to reproduce the problem

1. Follow "Installing from source" doc using Ubuntu 22.04 server

### Expected behaviour

"All done! You can now power on the Mastodon server" should result in a fully functional server

### Actual behaviour

missing packs data

### Detailed description

```
Running `RAILS_ENV=production rails db:setup` ...


Created database 'mastodon_production'
Done!

The final step is compiling CSS/JS assets.
This may take a while and consume a lot of RAM.
Compile the assets now? Yes
Running `RAILS_ENV=production rails assets:precompile` ...


yarn install v1.22.19
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
[4/6] Linking dependencies...
warning " > react-redux-loading-bar@4.0.8" has incorrect peer dependency "react-redux@^3.0.0 || ^4.0.0 || ^5.0.0".
warning Workspaces can only be enabled in private projects.
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 3.27s.
I, [2022-11-12T18:00:05.682512 #6250]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css
I, [2022-11-12T18:00:05.682735 #6250]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css.gz
I, [2022-11-12T18:00:05.688732 #6250]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css
I, [2022-11-12T18:00:05.688811 #6250]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css.gz
I, [2022-11-12T18:00:05.689790 #6250]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/favicon-db10337a56c45eb43c22ff5019546b520fa22c7281d4d385f235cbca67ed26bb.png
I, [2022-11-12T18:00:05.881043 #6250]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-a60bf0a452ed064fef3594cf52a4c998712da7c76150f890f4eaa644f59671e4.js
I, [2022-11-12T18:00:05.881140 #6250]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-a60bf0a452ed064fef3594cf52a4c998712da7c76150f890f4eaa644f59671e4.js.gz
I, [2022-11-12T18:00:05.886518 #6250]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-c31338f656687c1d733bb0f48d40acd076e24060f3dcff83b34870e4ccc2789d.css
I, [2022-11-12T18:00:05.886560 #6250]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-c31338f656687c1d733bb0f48d40acd076e24060f3dcff83b34870e4ccc2789d.css.gz
Compiling...
Compiled all packs in /home/mastodon/live/public/packs
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

Done!

All done! You can now power on the Mastodon server 🐘
```

but this is all that shows up:

```
mastodon@mastodon:~/live$ ls -alh public/packs/
total 860K
drwxrwxr-x  6 mastodon mastodon 4.0K Nov 12 18:00 .
drwxrwxr-x 10 mastodon mastodon 4.0K Nov 12 18:00 ..
drwxrwxr-x  2 mastodon mastodon 4.0K Nov 12 18:00 css
drwxrwxr-x  5 mastodon mastodon  32K Nov 12 18:00 js
-rw-rw-r--  1 mastodon mastodon 114K Nov 12 18:00 manifest.json
-rw-rw-r--  1 mastodon mastodon  24K Nov 12 18:00 manifest.json.gz
drwxrwxr-x  4 mastodon mastodon 4.0K Nov 12 18:00 media
drwxrwxr-x  2 mastodon mastodon 4.0K Nov 12 18:00 ocr
-rw-rw-r--  1 mastodon mastodon 663K Nov 12 18:00 report.html
```

### Specifications

You can see the web errors from the missing data at https://disobey.net

ubuntu v22.04.1
nginx v1.23.2
mastodon v3.5.3
yarn v1.22.19
node v16.18.1

**Comment by Elliesaur** [comment]
The fix that worked for me was to add to my .env.production file:
`RAILS_SERVE_STATIC_FILES=true`
For whatever reason it was not in there, causing 404's to display.

**Comment by yawnbox** [comment]
> The fix that worked for me was to add to my .env.production file:
> `RAILS_SERVE_STATIC_FILES=true`
> For whatever reason it was not in there, causing 404's to display.

Yes... that did it! Thank you!

Now why wasn't that part of the instructions? Or automatically there?

**Comment by afontenot** [comment]
Because it's undesirable / inefficient. You're supposed to set up nginx so that it serves static files itself. The docs could probably be more clear about this, although the "install from source" page links to [configuring your environment](https://docs.joinmastodon.org/admin/config/) which says:

> `RAILS_SERVE_STATIC_FILES`
>
> If set to true, Mastodon will answer requests for files in its `public` directory. This may be necessary if the reverse proxy (e.g. nginx) has no file system access to the `public` directory itself, such as in a containerized environment. It is a suboptimal setting because serving static files directly from the file system will always be much faster than serving them through the Ruby on Rails process.

So my recommendation would be to figure out why nginx isn't serving your static files. Is it a permissions issue for those files on your file system? I.e. does the user that nginx runs under have access to these files? Or is there no `location` directive for the static files in your nginx config at all?

**Comment by yawnbox** [comment]
This also seems to have resolved it.

`chown mastodon:www-data /home/mastodon/live/public/`

`systemctl restart mastodon-web mastodon-sidekiq mastodon-streaming nginx`

So this seems like something that should be built into the setup script. It's absolutely not clear.

Thank you.

**Comment by afontenot** [comment]
> /home/mastodon/live/public/

Are these directories not other-readable by default? I wonder if that's a choice you made, or if some part of the setup procedure led to them only being readable by the mastodon user and www-data group.

**Comment by yawnbox** [comment]
The official doc setup made everything in `/live` and automatically created and made everything owned by `mastodon:mastodon`

**Comment by Elliesaur** [comment]
> Because it's undesirable / inefficient. You're supposed to set up nginx so that it serves static files itself. The docs could probably be more clear about this, although the "install from source" page links to [configuring your environment](https://docs.joinmastodon.org/admin/config/) which says:
> 
> > `RAILS_SERVE_STATIC_FILES`
> > If set to true, Mastodon will answer requests for files in its `public` directory. This may be necessary if the reverse proxy (e.g. nginx) has no file system access to the `public` directory itself, such as in a containerized environment. It is a suboptimal setting because serving static files directly from the file system will always be much faster than serving them through the Ruby on Rails process.
> 
> So my recommendation would be to figure out why nginx isn't serving your static files. Is it a permissions issue for those files on your file system? I.e. does the user that nginx runs under have access to these files? Or is there no `location` directive for the static files in your nginx config at all?

Not a "could be clearer", it SHOULD actually state it. I know it is in the nginx config, but it does not work by default with permissions as-is.

**Comment by Elliesaur** [comment]
> This also seems to have resolved it.
> 
> `chown mastodon:www-data /home/mastodon/live/public/`
> 
> `systemctl restart mastodon-web mastodon-sidekiq mastodon-streaming nginx`
> 
> So this seems like something that should be built into the setup script. It's absolutely not clear.
> 
> Thank you.

Is it still working without the static file serving enabled in your .env file? I have found it did not pick up avatars or emoji's still. This went to the web service still and I needed to add in the static file serving to get them to work.

**Comment by yawnbox** [comment]
> Is it still working without the static file serving enabled in your .env file? I have found it did not pick up avatars or emoji's still. This went to the web service still and I needed to add in the static file serving to get them to work.

You're right. I didn't test that yet. Avatars are not working.

Yes I had commented out `RAILS_SERVE_STATIC_FILES=true` in `.env.production`

So this isn't fixed.

**Comment by afontenot** [comment]
I'm curious whether either or both of you might have an unusual umask. What does `umask` *run as the mastodon user* say? Anything other than 022 or 002 would be suspect.

**Comment by yawnbox** [comment]
I forgot to `chown` recursively, so it affected all sub-folders. Sorry.

`chown mastodon:www-data -R /home/mastodon/live/public/`

**Comment by yawnbox** [comment]
> I'm curious whether either or both of you might have an unusual umask. What does `umask` _run as the mastodon user_ say? Anything other than 022 or 002 would be suspect.

```
mastodon@ mastodon:~$ umask 
0002

```

**Comment by afontenot** [comment]
0002 is OK as well, so it's not that.

**Comment by yawnbox** [comment]
screenshot of avatar issue for context:

<img width="765" alt="Screenshot 2022-11-13 at 12 46 52 AM" src="https://user-images.githubusercontent.com/8809920/201513516-42813d56-cfb3-4535-b036-7cd31a163f39.png">

**Comment by afontenot** [comment]
If I'm reading the nginx config correctly, the avatars should be at /accounts/avatars not at /system/accounts/avatars. If you remove the /system from the URL does it happen to work? (To be clear, I don't know what the solution would be, it's just something to try.)

**Comment by afontenot** [comment]
```
root@mastodon:/home/mastodon/live/public# ls -alh system/
total 12K
drwxr-xr-x  3 mastodon www-data 4.0K Nov 13 00:30 .
d-wx-wx--x 11 mastodon www-data 4.0K Nov 13 00:30 ..
```

Uhh, the permissions on ".." are the permissions for `/home/mastodon/live/public`, right? I don't know how this happened, but this is clearly wrong. `d-wx-wx--x`

That says no one, not even the user-owner, has read permissions on the directory. You should check the whole chain while you're at it and make sure `/home/mastodon` and `/home/mastodon/live` are OK as well. You want all the directories to have 755 (`drwxr-xr-x`) permissions probably.

**Comment by yawnbox** [comment]
No change

```
root@mastodon:~# chmod -R 755 /home/mastodon/live/public 
root@mastodon:~# ls -alh /home/mastodon/live/public
total 392K
drwxr-xr-x 11 mastodon www-data 4.0K Nov 13 00:30 .
drwxrwxr-x 23 mastodon mastodon 4.0K Nov 12 23:24 ..
lrwxrwxrwx  1 mastodon www-data   15 Nov 12 17:53 500.html -> assets/500.html
-rwxr-xr-x  1 mastodon www-data  14K Nov 12 17:53 android-chrome-192x192.png
-rwxr-xr-x  1 mastodon www-data 4.8K Nov 12 17:53 apple-touch-icon.png
drwxr-xr-x  4 mastodon www-data 4.0K Nov 12 18:00 assets
drwxr-xr-x  3 mastodon www-data 4.0K Nov 12 17:53 avatars
-rwxr-xr-x  1 mastodon www-data 3.3K Nov 12 17:53 badge.png
-rwxr-xr-x  1 mastodon www-data  222 Nov 12 17:53 browserconfig.xml
-rwxr-xr-x  1 mastodon www-data 1.6K Nov 12 17:53 embed.js
drwxr-xr-x  2 mastodon www-data 136K Nov 12 17:53 emoji
-rwxr-xr-x  1 mastodon www-data 8.9K Nov 12 17:53 favicon-dev.ico
-rwxr-xr-x  1 mastodon www-data 8.9K Nov 12 17:53 favicon.ico
drwxr-xr-x  3 mastodon www-data 4.0K Nov 12 17:53 headers
-rwxr-xr-x  1 mastodon www-data  180 Nov 12 17:53 inert.css
-rwxr-xr-x  1 mastodon www-data 1.3K Nov 12 17:53 mask-icon.svg
-rwxr-xr-x  1 mastodon www-data 4.5K Nov 12 17:53 mstile-150x150.png
drwxr-xr-x  3 mastodon www-data 4.0K Nov 12 17:53 ocr
-rwxr-xr-x  1 mastodon www-data  94K Nov 12 17:53 oops.gif
-rwxr-xr-x  1 mastodon www-data  21K Nov 12 17:53 oops.png
drwxr-xr-x  6 mastodon www-data 4.0K Nov 12 18:00 packs
-rwxr-xr-x  1 mastodon www-data  158 Nov 12 17:53 robots.txt
drwxr-xr-x  2 mastodon www-data 4.0K Nov 12 17:53 shortcuts
drwxr-xr-x  2 mastodon www-data 4.0K Nov 12 17:53 sounds
lrwxrwxrwx  1 mastodon www-data   12 Nov 12 17:53 sw.js -> assets/sw.js
drwxr-xr-x  3 mastodon www-data 4.0K Nov 13 00:30 system
-rwxr-xr-x  1 mastodon www-data 1.4K Nov 12 17:53 web-push-icon_expand.png
-rwxr-xr-x  1 mastodon www-data 1.1K Nov 12 17:53 web-push-icon_favourite.png
-rwxr-xr-x  1 mastodon www-data  851 Nov 12 17:53 web-push-icon_reblog.png
```

**Comment by afontenot** [comment]
It might be useful to start a [discussion](https://github.com/mastodon/mastodon/discussions) if you want to keep trying to fix your specific problems, and leave this bug open for the issue with the installation instructions. Your nginx error logs suggest that nginx doesn't have access to the files in question, and that's an issue that should be fixable independently of whether the instructions resulted in a correctly configured system for you.

Alternatively, if you prefer, maybe one of the devs will weigh in on whether the existing instructions might somehow result in a completely borked installation.

**Comment by yawnbox** [comment]
the fix is permissions. cc @Elliesaur 

`root@mastodon:/home/mastodon# chmod -R 755 .`

**Comment by afontenot** [comment]
No don't do that!! 

That's going to make every *file* in the mastodon home directory executable. If you've done that I think the best course of action might be to wipe the installation and start over.

If Mastodon is running as the `mastodon` user, there are also very good reason not to make its code directories world-readable. You should only need the directories that are read by nginx to be world readable (or group readable if you are sure files are created with the correct permissions). In other words:

`chmod 755 /home/mastodon` and `chmod 755 /home/mastodon/public` where `public` is any directory that nginx needs to read.

**Comment by ryanwi** [comment]
Ran into this issue with nginx failing to read the mastodon app's public directory, ended up adding www-data to the mastodon group.

Behavior: All assets in the public directory. were returning 404 not found

Error logs showed:
```
/var/log/nginx# tail -f error.log
2022/11/14 06:32:07 [crit] 657#657: *488 stat() "/home/mastodon/live/public/explore" failed (13: Permission denied), client: 172.69.22.107, server: -, request: "GET /explore HTTP/2.0", host: "-"
2022/11/14 06:32:07 [crit] 657#657: *490 stat() "/home/mastodon/live/public/packs/css/common-50d0784d.css" failed (13: Permission denied), client: 172.69.22.56, server: -, request: "GET /packs/css/common-50d0784d.css HTTP/2.0", host: "-", referrer: "-"
```

Added www-data to mastodon group
```
gpasswd -a www-data mastodon
```
(via https://stackoverflow.com/questions/25774999/nginx-stat-failed-13-permission-denied)

**Comment by afontenot** [comment]
> Added www-data to mastodon group

Sure, that approach should work fine. Though in this case I think I'd want any code directories (stuff other than /live) to have user only (700) permissions. Nginx shouldn't need to read any of them.

**Comment by seangilleran** [comment]
Just coming by to say I had the exact same issue. Adding `www-data` to `mastodon` did the trick, although it seems a little kludge-y.

**Comment by yinnxinn** [comment]
> RAILS_SERVE_STATIC_FILES=true

I add this command in .env.production but still cannot find packs files after restart

**Comment by betodealmeida** [comment]
Same here. I did a fresh install of 4.12., though admittedly on Ubuntu 22.10. `chown` didn't help, but `gpasswd -a www-data mastodon` solved it.

**Comment by yinnxinn** [comment]
邮件已收到，谢谢
