### ISSUE TITLE
Update lists when user migrates to new server

### ISSUE THREAD

**Issue by kerim** [mastodon/mastodon#20538]
### Pitch

Currently (at least as of version 3.5.3), when someone in my lists migrates to a new server I automatically remained subscribed to follow them, but they are removed from all of my lists. Instead, the lists should all be updated to reflect their new location.

### Motivation

I spend a lot of time organizing my lists when I first follow someone, and if someone migrates servers a long time afterwards I can't easily remember which lists I added them to and why. It would be much easier if this was automatic.

**Comment by ClearlyClaire** [comment]
Depends on #19727
