### ISSUE TITLE
Verification using query parameters for systems that don't support link attributes.

### ISSUE THREAD

**Issue by phrees** [mastodon/mastodon#20532]
### Pitch

Some content management systems and static site generators don't support link attributes. To allow users of these systems to self validate accept query parameters as an alternative to rel="me" link attributes in validation requests.

E.g.

href="@username@host.social?rel=me"

in a link on a home page results in a green tick on the matching profile.

### Motivation

Implementing this would increase the number of validated users on Mastodon.

People who would benefit include:

- People with profiles on web apps that don't allow setting of link attributes.
- CMS users who don't have the technical experience to edit their own templates.

**Comment by nightpool** [comment]
No, this would directly defeat the security purposes of using rel attributes. If your CMS doesn't support rel=me links, that means that they don't give you permission to verify their page as your own.
