### ISSUE TITLE
Allow configuring Automated Post Deletion when account is being redirected

### ISSUE THREAD

**Issue by gunchleoc** [mastodon/mastodon#20550]
### Pitch

While an account is being redirected to a different account, enable the settings to configure automated post deletion on the old account without having to cancel the redirect first.

### Motivation

I wanted to clean up the account to free up space on the server, but I couldn't change the setting without unhooking the redirect, which is what I did.

This resulted in new follow requests, because people didn't read my manual notice in the profile.

**Comment by ClearlyClaire** [comment]
It is rather easy to allow every user to access this page, but I'm wondering if it makes sense presenting them to:
- non-approved users (probably not)
- non-confirmed users (probably not)
- disabled users
- suspended users
- users whose account has been turned a memorial
