### ISSUE TITLE
self-hosted instance dispersed images on about page and blank login

### ISSUE THREAD

**Issue by ntn888** [mastodon/mastodon#20561]
### Steps to reproduce the problem

the installed instance: https://mastodon.simplycreate.online/ has an unstructured landing page. and cannot login (blank page).
followed the steps to the T: https://docs.joinmastodon.org/admin/install/
execpt i found i had to also run: iptables --flush at the end  of firewall setup to open the ports 80/ssl.

### Expected behaviour

a properly formatted page

### Actual behaviour

a poorly structured page

### Specifications

Mastodon latest: 3.5.3 on ubuntu 20.04. 
tested on firefox & chrome and also on mobile. all same issue...

**Comment by AlanBell** [comment]
This isn't really a bug, your webpack server process isn't working (or needs more time) for some reason.

I don't know if it would be possible to have some text on the page that says "Your problem is webpack, go troubleshoot that bit" that gets hidden if the CSS loads.

**Comment by ntn888** [comment]
thanks for the input, i don't completely understand this meant?

do you need to close this question if it's not relevant here? i don 't have any idea of further trouble shooting...

**Comment by AlanBell** [comment]
sorry, I was a bit unclear, production instances are a bit different to a development setup (where there is a webpack-dev-server process running) for your case the asset precompilation bit in the setup process doesn't appear to have worked

**Comment by ntn888** [comment]
thanks it pointed me in the right direction. the issue is ubuntu version 22.04 (i neglectfully installed this version the instructions for 20.04). Anyway i found a fix: https://github.com/mastodon/mastodon/discussions/19651. thanks again!
