### ISSUE TITLE
Heroku deploy button doesn't work

### ISSUE THREAD

**Issue by bewuwy** [mastodon/mastodon#20591]
### Steps to reproduce the problem

1. Use the heroku deploy button (https://dashboard.heroku.com/new?button-url=https://github.com/tootsuite/mastodon&template=https://github.com/tootsuite/mastodon)
2. Click Deploy app

### Expected behaviour

A heroku app being created

### Actual behaviour

Heroku build error

### Detailed description

Trying to deploy mastodon to heroku, I got an error:

-----> Building on the Heroku-22 stack
-----> Deleting 1 files matching .slugignore patterns.
-----> Using buildpacks:
       1. https://github.com/heroku/heroku-buildpack-apt
       2. heroku/ruby
-----> Apt app detected
-----> Detected Aptfile or Stack changes, flushing cache
-----> Updating apt caches
       Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
       Get:2 http://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease [91.6 kB]
       Get:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
       Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [114 kB]
       Get:5 http://apt.postgresql.org/pub/repos/apt jammy-pgdg/main amd64 Packages [411 kB]
       Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1,792 kB]
       Get:7 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
       Get:8 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [761 kB]
       Get:9 http://archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [580 kB]
       Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [944 kB]
       Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [884 kB]
       Fetched 23.4 MB in 3s (8,738 kB/s)
       Reading package lists...
-----> Fetching .debs for ffmpeg
       Reading package lists...
       Building dependency tree...
       The following additional packages will be installed:
         alsa-topology-conf alsa-ucm-conf i965-va-driver intel-media-va-driver
         libaacs0 libasound2 libasound2-data libass9 libasyncns0 libavc1394-0
         libavcodec58 libavdevice58 libavfilter7 libavformat58 libavutil56 libbdplus0
         libblas3 libbluray2 libbs2b0 libcaca0 libcdio-cdda2 libcdio-paranoia2
         libcdio19 libchromaprint1 libcodec2-1.0 libdc1394-25 libdecor-0-0
         libdecor-0-plugin-1-cairo libdrm-amdgpu1 libdrm-common libdrm-intel1
         libdrm-nouveau2 libdrm-radeon1 libdrm2 libflac8 libflite1 libgbm1
         libgfortran5 libgl1 libgl1-amber-dri libgl1-mesa-dri libglapi-mesa libglvnd0
         libglx-mesa0 libglx0 libgme0 libgsm1 libiec61883-0 libigdgmm12
         libjack-jackd2-0 liblapack3 liblilv-0-0 libllvm13 libmfx1 libmp3lame0
         libmpg123-0 libmysofa1 libnorm1 libogg0 libopenal-data libopenal1
         libopenmpt0 libopus0 libpciaccess0 libpgm-5.3-0 libpocketsphinx3
         libpostproc55 libpulse0 libraw1394-11 librubberband2 libsamplerate0
         libsdl2-2.0-0 libsensors-config libsensors5 libserd-0-0 libshine3 libslang2
         libsnappy1v5 libsndfile1 libsndio7.0 libsord-0-0 libsoxr0 libspeex1
         libsphinxbase3 libsratom-0-0 libsrt1.4-gnutls libssh-gcrypt-4 libswresample3
         libswscale5 libtheora0 libtwolame0 libudfread0 libusb-1.0-0 libva-drm2
         libva-x11-2 libva2 libvdpau1 libvidstab1.1 libvorbis0a libvorbisenc2
         libvorbisfile3 libvulkan1 libwayland-client0 libwayland-cursor0
         libwayland-egl1 libwayland-server0 libx11-xcb1 libx264-163 libxcb-dri2-0
         libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-randr0 libxcb-shape0
         libxcb-sync1 libxcb-xfixes0 libxcursor1 libxfixes3 libxi6 libxinerama1
         libxkbcommon0 libxrandr2 libxshmfence1 libxss1 libxv1 libxvidcore4
         libxxf86vm1 libzimg2 libzmq5 libzvbi-common libzvbi0 mesa-va-drivers
         mesa-vdpau-drivers mesa-vulkan-drivers ocl-icd-libopencl1 pocketsphinx-en-us
         va-driver-all vdpau-driver-all xkb-data
       Suggested packages:
         ffmpeg-doc i965-va-driver-shaders libasound2-plugins alsa-utils libcuda1
         libnvcuvid1 libnvidia-encode1 libbluray-bdj jackd2 libportaudio2 opus-tools
         pciutils pulseaudio libraw1394-doc xdg-utils lm-sensors serdi sndiod sordi
         speex opencl-icd libvdpau-va-gl1
       The following NEW packages will be installed:
         alsa-topology-conf alsa-ucm-conf ffmpeg i965-va-driver intel-media-va-driver
         libaacs0 libasound2 libasound2-data libass9 libasyncns0 libavc1394-0
         libavcodec58 libavdevice58 libavfilter7 libavformat58 libavutil56 libbdplus0
         libblas3 libbluray2 libbs2b0 libcaca0 libcdio-cdda2 libcdio-paranoia2
         libcdio19 libchromaprint1 libcodec2-1.0 libdc1394-25 libdecor-0-0
         libdecor-0-plugin-1-cairo libdrm-amdgpu1 libdrm-common libdrm-intel1
         libdrm-nouveau2 libdrm-radeon1 libdrm2 libflac8 libflite1 libgbm1
         libgfortran5 libgl1 libgl1-amber-dri libgl1-mesa-dri libglapi-mesa libglvnd0
         libglx-mesa0 libglx0 libgme0 libgsm1 libiec61883-0 libigdgmm12
         libjack-jackd2-0 liblapack3 liblilv-0-0 libllvm13 libmfx1 libmp3lame0
         libmpg123-0 libmysofa1 libnorm1 libogg0 libopenal-data libopenal1
         libopenmpt0 libopus0 libpciaccess0 libpgm-5.3-0 libpocketsphinx3
         libpostproc55 libpulse0 libraw1394-11 librubberband2 libsamplerate0
         libsdl2-2.0-0 libsensors-config libsensors5 libserd-0-0 libshine3 libslang2
         libsnappy1v5 libsndfile1 libsndio7.0 libsord-0-0 libsoxr0 libspeex1
         libsphinxbase3 libsratom-0-0 libsrt1.4-gnutls libssh-gcrypt-4 libswresample3
         libswscale5 libtheora0 libtwolame0 libudfread0 libusb-1.0-0 libva-drm2
         libva-x11-2 libva2 libvdpau1 libvidstab1.1 libvorbis0a libvorbisenc2
         libvorbisfile3 libvulkan1 libwayland-client0 libwayland-cursor0
         libwayland-egl1 libwayland-server0 libx11-xcb1 libx264-163 libxcb-dri2-0
         libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-randr0 libxcb-shape0
         libxcb-sync1 libxcb-xfixes0 libxcursor1 libxfixes3 libxi6 libxinerama1
         libxkbcommon0 libxrandr2 libxshmfence1 libxss1 libxv1 libxvidcore4
         libxxf86vm1 libzimg2 libzmq5 libzvbi-common libzvbi0 mesa-va-drivers
         mesa-vdpau-drivers mesa-vulkan-drivers ocl-icd-libopencl1 pocketsphinx-en-us
         va-driver-all vdpau-driver-all xkb-data
       0 upgraded, 140 newly installed, 0 to remove and 4 not upgraded.
       Need to get 129 MB of archives.
       After this operation, 385 MB of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libslang2 amd64 2.3.2-5build4 [468 kB]
       Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 xkb-data all 2.33-1 [394 kB]
       Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdrm-common all 2.4.110-1ubuntu1 [5,360 B]
       Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdrm2 amd64 2.4.110-1ubuntu1 [37.7 kB]
       Get:5 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libusb-1.0-0 amd64 2:1.0.25-1ubuntu2 [52.7 kB]
       Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 alsa-topology-conf all 1.2.5.1-2 [15.5 kB]
       Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libasound2-data all 1.2.6.1-1ubuntu1 [19.1 kB]
       Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libasound2 amd64 1.2.6.1-1ubuntu1 [390 kB]
       Get:9 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 alsa-ucm-conf all 1.2.6.3-1ubuntu1.1 [41.1 kB]
       Get:10 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libva2 amd64 2.14.0-1 [65.0 kB]
       Get:11 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libmfx1 amd64 22.3.0-1 [3,105 kB]
       Get:12 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libva-drm2 amd64 2.14.0-1 [7,502 B]
       Get:13 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxfixes3 amd64 1:6.0.0-1 [11.7 kB]
       Get:14 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libva-x11-2 amd64 2.14.0-1 [12.6 kB]
       Get:15 http://archive.ubuntu.com/ubuntu jammy/main amd64 libvdpau1 amd64 1.4-3build2 [27.0 kB]
       Get:16 http://archive.ubuntu.com/ubuntu jammy/universe amd64 ocl-icd-libopencl1 amd64 2.2.14-3 [39.1 kB]
       Get:17 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 libavutil56 amd64 7:4.4.2-0ubuntu0.22.04.1 [290 kB]
       Get:18 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libcodec2-1.0 amd64 1.0.1-3 [8,435 kB]
       Get:19 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libgsm1 amd64 1.0.19-1 [27.7 kB]
       Get:20 http://archive.ubuntu.com/ubuntu jammy/main amd64 libmp3lame0 amd64 3.100-3build2 [141 kB]
       Get:21 http://archive.ubuntu.com/ubuntu jammy/main amd64 libopus0 amd64 1.3.1-0.1build2 [203 kB]
       Get:22 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libshine3 amd64 3.1.1-2 [23.2 kB]
       Get:23 http://archive.ubuntu.com/ubuntu jammy/main amd64 libsnappy1v5 amd64 1.1.8-1build3 [17.5 kB]
       Get:24 http://archive.ubuntu.com/ubuntu jammy/main amd64 libspeex1 amd64 1.2~rc1.2-1.1ubuntu3 [57.9 kB]
       Get:25 http://archive.ubuntu.com/ubuntu jammy/main amd64 libsoxr0 amd64 0.1.3-4build2 [79.8 kB]
       Get:26 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 libswresample3 amd64 7:4.4.2-0ubuntu0.22.04.1 [62.2 kB]
       Get:27 http://archive.ubuntu.com/ubuntu jammy/main amd64 libogg0 amd64 1.3.5-0ubuntu3 [22.9 kB]
       Get:28 http://archive.ubuntu.com/ubuntu jammy/main amd64 libtheora0 amd64 1.1.1+dfsg.1-15ubuntu4 [209 kB]
       Get:29 http://archive.ubuntu.com/ubuntu jammy/main amd64 libtwolame0 amd64 0.4.0-2build2 [52.5 kB]
       Get:30 http://archive.ubuntu.com/ubuntu jammy/main amd64 libvorbis0a amd64 1.3.7-1build2 [99.2 kB]
       Get:31 http://archive.ubuntu.com/ubuntu jammy/main amd64 libvorbisenc2 amd64 1.3.7-1build2 [82.6 kB]
       Get:32 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libx264-163 amd64 2:0.163.3060+git5db6aa6-2build1 [591 kB]
       Get:33 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libxvidcore4 amd64 2:1.3.7-1 [201 kB]
       Get:34 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libzvbi-common all 0.2.35-19 [35.5 kB]
       Get:35 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libzvbi0 amd64 0.2.35-19 [262 kB]
       Get:36 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 libavcodec58 amd64 7:4.4.2-0ubuntu0.22.04.1 [5,567 kB]
       Get:37 http://archive.ubuntu.com/ubuntu jammy/main amd64 libraw1394-11 amd64 2.1.2-2build2 [27.0 kB]
       Get:38 http://archive.ubuntu.com/ubuntu jammy/main amd64 libavc1394-0 amd64 0.5.4-5build2 [17.0 kB]
       Get:39 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libass9 amd64 1:0.15.2-1 [97.5 kB]
       Get:40 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libudfread0 amd64 1.1.2-1 [16.2 kB]
       Get:41 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libbluray2 amd64 1:1.3.1-1 [159 kB]
       Get:42 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libchromaprint1 amd64 1.5.1-2 [28.4 kB]
       Get:43 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libgme0 amd64 0.6.3-2 [127 kB]
       Get:44 http://archive.ubuntu.com/ubuntu jammy/main amd64 libmpg123-0 amd64 1.29.3-1build1 [172 kB]
       Get:45 http://archive.ubuntu.com/ubuntu jammy/main amd64 libvorbisfile3 amd64 1.3.7-1build2 [17.1 kB]
       Get:46 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libopenmpt0 amd64 0.6.1-1 [592 kB]
       Get:47 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libsrt1.4-gnutls amd64 1.4.4-4 [309 kB]
       Get:48 http://archive.ubuntu.com/ubuntu jammy/main amd64 libssh-gcrypt-4 amd64 0.9.6-2build1 [222 kB]
       Get:49 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libnorm1 amd64 1.5.9+dfsg-2 [221 kB]
       Get:50 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libpgm-5.3-0 amd64 5.3.128~dfsg-2 [161 kB]
       Get:51 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libzmq5 amd64 4.3.4-2 [256 kB]
       Get:52 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 libavformat58 amd64 7:4.4.2-0ubuntu0.22.04.1 [1,103 kB]
       Get:53 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libbs2b0 amd64 3.1.0+dfsg-2.2build1 [10.2 kB]
       Get:54 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libflite1 amd64 2.2-3 [13.7 MB]
       Get:55 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libserd-0-0 amd64 0.30.10-2 [40.8 kB]
       Get:56 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libsord-0-0 amd64 0.16.8-2 [21.2 kB]
       Get:57 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libsratom-0-0 amd64 0.6.8-1 [17.0 kB]
       Get:58 http://archive.ubuntu.com/ubuntu jammy/universe amd64 liblilv-0-0 amd64 0.24.12-2 [42.8 kB]
       Get:59 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libmysofa1 amd64 1.2.1~dfsg0-1 [1,157 kB]
       Get:60 http://archive.ubuntu.com/ubuntu jammy/main amd64 libblas3 amd64 3.10.0-2ubuntu1 [228 kB]
       Get:61 http://archive.ubuntu.com/ubuntu jammy-security/main amd64 libgfortran5 amd64 12.1.0-2ubuntu1~22.04 [882 kB]
       Get:62 http://archive.ubuntu.com/ubuntu jammy/main amd64 liblapack3 amd64 3.10.0-2ubuntu1 [2,504 kB]
       Get:63 http://archive.ubuntu.com/ubuntu jammy/main amd64 libasyncns0 amd64 0.8-6build2 [12.8 kB]
       Get:64 http://archive.ubuntu.com/ubuntu jammy/main amd64 libflac8 amd64 1.3.3-2build2 [111 kB]
       Get:65 http://archive.ubuntu.com/ubuntu jammy/main amd64 libsndfile1 amd64 1.0.31-2build1 [196 kB]
       Get:66 http://archive.ubuntu.com/ubuntu jammy/main amd64 libx11-xcb1 amd64 2:1.7.5-1 [7,790 B]
       Get:67 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpulse0 amd64 1:15.99.1+dfsg1-1ubuntu2 [297 kB]
       Get:68 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libsphinxbase3 amd64 0.8+5prealpha+1-13build1 [126 kB]
       Get:69 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libpocketsphinx3 amd64 0.8.0+real5prealpha+1-14ubuntu1 [132 kB]
       Get:70 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 libpostproc55 amd64 7:4.4.2-0ubuntu0.22.04.1 [60.1 kB]
       Get:71 http://archive.ubuntu.com/ubuntu jammy/main amd64 libsamplerate0 amd64 0.2.2-1build1 [1,359 kB]
       Get:72 http://archive.ubuntu.com/ubuntu jammy/universe amd64 librubberband2 amd64 2.0.0-2 [90.0 kB]
       Get:73 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 libswscale5 amd64 7:4.4.2-0ubuntu0.22.04.1 [180 kB]
       Get:74 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libvidstab1.1 amd64 1.1.0-2 [35.0 kB]
       Get:75 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libzimg2 amd64 3.0.3+ds1-1 [241 kB]
       Get:76 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 libavfilter7 amd64 7:4.4.2-0ubuntu0.22.04.1 [1,496 kB]
       Get:77 http://archive.ubuntu.com/ubuntu jammy/main amd64 libcaca0 amd64 0.99.beta19-2.2ubuntu4 [224 kB]
       Get:78 http://archive.ubuntu.com/ubuntu jammy/main amd64 libcdio19 amd64 2.1.0-3build1 [63.3 kB]
       Get:79 http://archive.ubuntu.com/ubuntu jammy/main amd64 libcdio-cdda2 amd64 10.2+2.0.0-1build3 [16.7 kB]
       Get:80 http://archive.ubuntu.com/ubuntu jammy/main amd64 libcdio-paranoia2 amd64 10.2+2.0.0-1build3 [15.9 kB]
       Get:81 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libdc1394-25 amd64 2.2.6-4 [88.8 kB]
       Get:82 http://archive.ubuntu.com/ubuntu jammy/main amd64 libglvnd0 amd64 1.4.0-1 [73.6 kB]
       Get:83 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglapi-mesa amd64 22.0.5-0ubuntu0.1 [35.3 kB]
       Get:84 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-dri2-0 amd64 1.14-3ubuntu3 [7,206 B]
       Get:85 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-dri3-0 amd64 1.14-3ubuntu3 [6,968 B]
       Get:86 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-glx0 amd64 1.14-3ubuntu3 [25.9 kB]
       Get:87 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-present0 amd64 1.14-3ubuntu3 [5,734 B]
       Get:88 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-sync1 amd64 1.14-3ubuntu3 [9,416 B]
       Get:89 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-xfixes0 amd64 1.14-3ubuntu3 [9,996 B]
       Get:90 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxshmfence1 amd64 1.3-1build4 [5,394 B]
       Get:91 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxxf86vm1 amd64 1:1.1.4-1build3 [10.4 kB]
       Get:92 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdrm-amdgpu1 amd64 2.4.110-1ubuntu1 [20.0 kB]
       Get:93 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdrm-nouveau2 amd64 2.4.110-1ubuntu1 [17.4 kB]
       Get:94 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdrm-radeon1 amd64 2.4.110-1ubuntu1 [21.5 kB]
       Get:95 http://archive.ubuntu.com/ubuntu jammy-security/main amd64 libllvm13 amd64 1:13.0.1-2ubuntu2.1 [22.2 MB]
       Get:96 http://archive.ubuntu.com/ubuntu jammy/main amd64 libsensors-config all 1:3.6.0-7ubuntu1 [5,274 B]
       Get:97 http://archive.ubuntu.com/ubuntu jammy/main amd64 libsensors5 amd64 1:3.6.0-7ubuntu1 [26.3 kB]
       Get:98 http://archive.ubuntu.com/ubuntu jammy/main amd64 libvulkan1 amd64 1.3.204.1-2 [128 kB]
       Get:99 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgl1-mesa-dri amd64 22.0.5-0ubuntu0.1 [7,471 kB]
       Get:100 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglx-mesa0 amd64 22.0.5-0ubuntu0.1 [156 kB]
       Get:101 http://archive.ubuntu.com/ubuntu jammy/main amd64 libglx0 amd64 1.4.0-1 [41.0 kB]
       Get:102 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgl1 amd64 1.4.0-1 [110 kB]
       Get:103 http://archive.ubuntu.com/ubuntu jammy/main amd64 libiec61883-0 amd64 1.2.0-4build3 [25.9 kB]
       Get:104 http://archive.ubuntu.com/ubuntu jammy/main amd64 libjack-jackd2-0 amd64 1.9.20~dfsg-1 [293 kB]
       Get:105 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libopenal-data all 1:1.19.1-2build3 [164 kB]
       Get:106 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libsndio7.0 amd64 1.8.1-1.1 [29.3 kB]
       Get:107 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libopenal1 amd64 1:1.19.1-2build3 [535 kB]
       Get:108 http://archive.ubuntu.com/ubuntu jammy-security/main amd64 libwayland-client0 amd64 1.20.0-1ubuntu0.1 [25.9 kB]
       Get:109 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdecor-0-0 amd64 0.1.0-3build1 [15.1 kB]
       Get:110 http://archive.ubuntu.com/ubuntu jammy-security/main amd64 libwayland-server0 amd64 1.20.0-1ubuntu0.1 [34.3 kB]
       Get:111 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgbm1 amd64 22.0.5-0ubuntu0.1 [32.6 kB]
       Get:112 http://archive.ubuntu.com/ubuntu jammy-security/main amd64 libwayland-cursor0 amd64 1.20.0-1ubuntu0.1 [10.7 kB]
       Get:113 http://archive.ubuntu.com/ubuntu jammy-security/main amd64 libwayland-egl1 amd64 1.20.0-1ubuntu0.1 [5,582 B]
       Get:114 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcursor1 amd64 1:1.2.0-2build4 [20.9 kB]
       Get:115 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxi6 amd64 2:1.8-1build1 [32.6 kB]
       Get:116 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxinerama1 amd64 2:1.1.4-3 [7,382 B]
       Get:117 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxkbcommon0 amd64 1.4.0-1 [125 kB]
       Get:118 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxrandr2 amd64 2:1.5.2-1build1 [20.4 kB]
       Get:119 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxss1 amd64 1:1.2.3-1build2 [8,476 B]
       Get:120 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libsdl2-2.0-0 amd64 2.0.20+dfsg-2ubuntu1.22.04.1 [582 kB]
       Get:121 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-shape0 amd64 1.14-3ubuntu3 [6,158 B]
       Get:122 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxv1 amd64 2:1.0.11-1build2 [11.2 kB]
       Get:123 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 libavdevice58 amd64 7:4.4.2-0ubuntu0.22.04.1 [87.5 kB]
       Get:124 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 ffmpeg amd64 7:4.4.2-0ubuntu0.22.04.1 [1,696 kB]
       Get:125 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libigdgmm12 amd64 22.1.2+ds1-1 [139 kB]
       Get:126 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 intel-media-va-driver amd64 22.3.1+dfsg1-1ubuntu1 [2,283 kB]
       Get:127 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libaacs0 amd64 0.11.1-1 [64.1 kB]
       Get:128 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libbdplus0 amd64 0.2.0-1 [52.2 kB]
       Get:129 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdecor-0-plugin-1-cairo amd64 0.1.0-3build1 [20.4 kB]
       Get:130 http://archive.ubuntu.com/ubuntu jammy/main amd64 libpciaccess0 amd64 0.16-3 [19.1 kB]
       Get:131 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdrm-intel1 amd64 2.4.110-1ubuntu1 [66.7 kB]
       Get:132 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgl1-amber-dri amd64 21.3.7-0ubuntu1 [4,433 kB]
       Get:133 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-randr0 amd64 1.14-3ubuntu3 [18.3 kB]
       Get:134 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 mesa-va-drivers amd64 22.0.5-0ubuntu0.1 [3,123 kB]
       Get:135 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 mesa-vdpau-drivers amd64 22.0.5-0ubuntu0.1 [3,247 kB]
       Get:136 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 mesa-vulkan-drivers amd64 22.0.5-0ubuntu0.1 [4,973 kB]
       Get:137 http://archive.ubuntu.com/ubuntu jammy/universe amd64 i965-va-driver amd64 2.4.1+dfsg1-1 [302 kB]
       Get:138 http://archive.ubuntu.com/ubuntu jammy/universe amd64 va-driver-all amd64 2.14.0-1 [3,984 B]
       Get:139 http://archive.ubuntu.com/ubuntu jammy/main amd64 vdpau-driver-all amd64 1.4-3build2 [4,510 B]
       Get:140 http://archive.ubuntu.com/ubuntu jammy/universe amd64 pocketsphinx-en-us all 0.8.0+real5prealpha+1-14ubuntu1 [27.6 MB]
       Fetched 129 MB in 6s (21.3 MB/s)
       Download complete and in download only mode
-----> Fetching .debs for libicu[0-9][0-9]
       Reading package lists...
       Building dependency tree...
       0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 4 not upgraded.
       Need to get 10.6 MB of archives.
       After this operation, 0 B of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libicu70 amd64 70.1-2 [10.6 MB]
       Fetched 10.6 MB in 1s (9,756 kB/s)
       Download complete and in download only mode
-----> Fetching .debs for libicu-dev
       Reading package lists...
       Building dependency tree...
       0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 4 not upgraded.
       Need to get 11.6 MB of archives.
       After this operation, 0 B of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libicu-dev amd64 70.1-2 [11.6 MB]
       Fetched 11.6 MB in 1s (10.9 MB/s)
       Download complete and in download only mode
-----> Fetching .debs for libidn12
       Reading package lists...
       Building dependency tree...
       0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 4 not upgraded.
       Need to get 60.6 kB of archives.
       After this operation, 0 B of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libidn12 amd64 1.38-4build1 [60.6 kB]
       Fetched 60.6 kB in 0s (954 kB/s)
       Download complete and in download only mode
-----> Fetching .debs for libidn-dev
       Reading package lists...
       Building dependency tree...
       0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 4 not upgraded.
       Need to get 166 kB of archives.
       After this operation, 0 B of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libidn-dev amd64 1.38-4build1 [166 kB]
       Fetched 166 kB in 0s (348 kB/s)
       Download complete and in download only mode
-----> Fetching .debs for libpq-dev
       Reading package lists...
       Building dependency tree...
       The following additional packages will be installed:
         libpq5
       Suggested packages:
         postgresql-doc-15
       The following packages will be upgraded:
         libpq-dev libpq5
       2 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
       Need to get 322 kB of archives.
       After this operation, 35.8 kB of additional disk space will be used.
       Get:1 http://apt.postgresql.org/pub/repos/apt jammy-pgdg/main amd64 libpq-dev amd64 15.1-1.pgdg22.04+1 [139 kB]
       Get:2 http://apt.postgresql.org/pub/repos/apt jammy-pgdg/main amd64 libpq5 amd64 15.1-1.pgdg22.04+1 [183 kB]
       Fetched 322 kB in 1s (366 kB/s)
       Download complete and in download only mode
-----> Fetching .debs for libxdamage1
       Reading package lists...
       Building dependency tree...
       The following NEW packages will be installed:
         libxdamage1
       0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
       Need to get 7,154 B of archives.
       After this operation, 31.7 kB of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxdamage1 amd64 1:1.1.5-2build2 [7,154 B]
       Fetched 7,154 B in 0s (221 kB/s)
       Download complete and in download only mode
-----> Fetching .debs for libxfixes3
       Reading package lists...
       Building dependency tree...
       The following NEW packages will be installed:
         libxfixes3
       0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
       Need to get 0 B/11.7 kB of archives.
       After this operation, 52.2 kB of additional disk space will be used.
       Download complete and in download only mode
-----> Fetching .debs for zlib1g-dev
       Reading package lists...
       Building dependency tree...
       0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 4 not upgraded.
       Need to get 164 kB of archives.
       After this operation, 0 B of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu jammy-security/main amd64 zlib1g-dev amd64 1:1.2.11.dfsg-2ubuntu9.2 [164 kB]
       Fetched 164 kB in 0s (2,161 kB/s)
       Download complete and in download only mode
-----> Fetching .debs for libcairo2
       Reading package lists...
       Building dependency tree...
       0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 4 not upgraded.
       Need to get 628 kB of archives.
       After this operation, 0 B of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libcairo2 amd64 1.16.0-5ubuntu2 [628 kB]
       Fetched 628 kB in 1s (945 kB/s)
       Download complete and in download only mode
-----> Fetching .debs for libcroco3
       Reading package lists...
       Building dependency tree...
E: Unable to locate package libcroco3
 !     Push rejected, failed to compile Apt app.
 !     Push failed

### Specifications

Mastodon 3.5.3

**Comment by ineffyble** [comment]
Hmm, that button still links to old repo org (tootsuite), not sure if that would impact anything or not.

**Comment by ineffyble** [comment]
@bewuwy where did you find that button?

**Comment by bewuwy** [comment]
Oh, it's not in the official repo, I didn't notice it.
