### ISSUE TITLE
4.0.0rc3 UI: profile picture doesn't link to origin instance anymore

### ISSUE THREAD

**Issue by abochmann** [mastodon/mastodon#20593]
### Steps to reproduce the problem

1. click on an avatar in the timeline to get the local cached profile loaded into the rightmost pane in the advanced UI
2. the profile picture is shown enlarged, replacing the previous functionality, where clicking on the profile image opened the profile on the origin instance
3. there is no other obvious way to open the original remote profile
4. instead the option is how hidden behind the 3 dots menu as "Open original page"

### Expected behaviour

there is an obvious and easily accessible way to view the full profile of a remote account

### Actual behaviour

previous functionality to that end has been replaced and is now hidden in a submenu

### Detailed description

Making it harder to access remote profiles with full information is detrimental to the general user experience, as locally cached profiles are almost always incomplete or out of date.

Maybe take an example from Pinafore, where clicking on a profile image also opens an enlarged view, but in addition to that, the username is clearly marked as a link leading to the origin instance.

Example screenshot from a profile shown in Pinafore, with an arrow pointing at the link in question:
![image](https://user-images.githubusercontent.com/9380844/201544280-3f1edaed-ac7c-4855-a59c-60e0ef2fcabe.png)

### Specifications

Mastodon 4.0.0rc3
Vivaldi 5.5.2805.44 (Chromium)

**Comment by ineffyble** [comment]
I think I'd re-title this issue to be "no obvious way to view remote profile" or similar, since the enlarged picture is essentially a new feature.

I do like the linking of the display name, I wonder if something similar is a good option here.

**Comment by Gargron** [comment]
Previous behaviour generated a lot of complaints, having an explicit option in dropdown seems better.
