### ISSUE TITLE
Images and styles are not loading and verification mail link is corrupted.

### ISSUE THREAD

**Issue by rickersilva** [mastodon/mastodon#20603]
### Steps to reproduce the problem

1. Install a new MAstodon instance in GCP with compute, db and storage separated.
2. Open your instance url
3. Create a new account
4. Verify account with link in email
...

### Expected behaviour

I expected to create a new accoutn succesfully

### Actual behaviour

Page loads without styles and verification link starts with http://url5266.oye.social so throws certification error

### Detailed description

I installed a new isntance for several times now and always got the same result.

first, the instance is not loading images nor styles.
![image](https://user-images.githubusercontent.com/6293792/201547260-ef4f5e19-60e0-4572-90f1-25d0ab61d34e.png)

I can create an account and receive the verification mail, but the link to verify starts like http://url5266.oye.social/ls/click?upn= and makes the certificate to throw an error.

this is the log in mastodon-web
Nov 13 22:02:12 oye-instance-1 bundle[32350]: [152d9a4b-48e4-49b5-a388-f4ab0f995db8] method=GET path=/auth/edit format=html controller=Auth::RegistrationsController action=edit status=200 duration=187.01 view=134.99 db=34.17
Nov 13 22:02:12 oye-instance-1 bundle[32348]: [d3fb59f2-fe39-4c35-92d3-20c4ac4fd124] method=GET path=/packs/js/locale_es-34a37704cbe8d343b6c3.chunk.js format=*/* controller=ApplicationController action=raise_not_found status=302 duration=19.35 view=0.00 db=4.56 location=https://oye.social/auth/edit
Nov 13 22:02:12 oye-instance-1 bundle[32350]: [ccf1bc1f-dd03-4ca5-90fb-c2ba1dbf460e] method=GET path=/packs/js/public-a52a3460655116c9cf18.chunk.js format=*/* controller=ApplicationController action=raise_not_found status=302 duration=34.64 view=0.00 db=18.89 location=https://oye.social/auth/edit
Nov 13 22:02:12 oye-instance-1 bundle[32350]: [0312909b-0d66-4256-8691-ede06e1a2fdc] method=GET path=/packs/js/common-997d98113e1e433a9a9f.js format=*/* controller=ApplicationController action=raise_not_found status=302 duration=45.57 view=0.00 db=26.88 location=https://oye.social/auth/edit
Nov 13 22:02:12 oye-instance-1 bundle[32350]: [cc2a92d1-31ab-4140-9dd2-94f2b372260f] method=GET path=/inert.css format=css controller=ApplicationController action=raise_not_found status=302 duration=35.09 view=0.00 db=21.36 location=https://oye.social/auth/edit
Nov 13 22:02:12 oye-instance-1 bundle[32350]: [dd45d679-8b62-4ef2-9c79-024ca90d640f] method=GET path=/packs/css/common-50d0784d.css format=css controller=ApplicationController action=raise_not_found status=302 duration=40.38 view=0.00 db=23.04 location=https://oye.social/auth/edit
Nov 13 22:02:12 oye-instance-1 bundle[32350]: [19a4fe5f-8d9a-4ef2-84b5-7c2b7517ed31] method=GET path=/packs/css/default-525fdc56.chunk.css format=css controller=ApplicationController action=raise_not_found status=302 duration=46.50 view=0.00 db=27.13 location=https://oye.social/auth/edit
Nov 13 22:02:12 oye-instance-1 bundle[32348]: [e17177c7-828f-48ce-b2d1-9a9168409dc7] method=GET path=/auth/edit format=*/* controller=Auth::RegistrationsController action=edit status=200 duration=61.87 view=38.36 db=11.96
Nov 13 22:02:12 oye-instance-1 bundle[32350]: [0437fc7f-f7db-49ea-bcbc-812e0d85a571] method=GET path=/auth/edit format=*/* controller=Auth::RegistrationsController action=edit status=200 duration=65.11 view=41.88 db=13.70
Nov 13 22:02:13 oye-instance-1 bundle[32350]: [3515f9b8-6514-4f66-ae7b-b45b67baa880] method=GET path=/auth/edit format=*/* controller=Auth::RegistrationsController action=edit status=200 duration=50.41 view=30.05 db=11.26
Nov 13 22:02:13 oye-instance-1 bundle[32348]: [b1ca04de-3484-4160-a859-a483d3296923] method=GET path=/auth/edit format=html controller=Auth::RegistrationsController action=edit status=200 duration=56.34 view=35.88 db=10.42
Nov 13 22:02:13 oye-instance-1 bundle[32348]: [6a6deed2-8a3f-46a8-8f8a-85a2e4967113] method=GET path=/auth/edit format=html controller=Auth::RegistrationsController action=edit status=200 duration=54.08 view=33.68 db=10.36
Nov 13 22:02:13 oye-instance-1 bundle[32348]: [d847f876-25fc-4514-b8a5-deb8c31e9723] method=GET path=/packs/media/images/logo-33a0fb4c065a0ccb90b51fcfdea6b3cf.svg format=svg controller=ApplicationController action=raise_not_found status=302 duration=12.54 view=0.00 db=3.97 location=https://oye.social/auth/edit
Nov 13 22:02:13 oye-instance-1 bundle[32350]: [f09654e0-aab6-4e8c-94e5-1ab62183b1f2] method=GET path=/auth/edit format=html controller=Auth::RegistrationsController action=edit status=200 duration=58.65 view=36.15 db=11.66
Nov 13 22:02:13 oye-instance-1 bundle[32348]: [f432aa84-136d-400b-a774-b03832f66593] method=GET path=/inert.css format=css controller=ApplicationController action=raise_not_found status=302 duration=12.89 view=0.00 db=3.46 location=https://oye.social/auth/edit
Nov 13 22:02:13 oye-instance-1 bundle[32350]: [8ecec958-485a-4c9c-a5b1-63804e855eb4] method=GET path=/auth/edit format=html controller=Auth::RegistrationsController action=edit status=200 duration=61.63 view=38.19 db=12.00
Nov 13 22:02:14 oye-instance-1 bundle[32348]: [9d54738b-760c-4ae1-be2e-e26069133e88] method=GET path=/auth/edit format=html controller=Auth::RegistrationsController action=edit status=200 duration=51.31 view=32.06 db=10.59

### Specifications

mastodon 3.5.3
ruby 3.0.3
nodejs 16.18.1

Brave
[Version 1.45.123 Chromium: 107.0.5304.110 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by capcom1701** [comment]
I've been chasing this around as well for 2 hours. I thought it was just me. Webpage looks exactly like yours on both safari and chrome. Looks fine on an iPhone app.

**Comment by Gargron** [comment]
> Have you precompiled? Usually that will fix the issue. My problem is I cannot get the precompiled to run clean.

Run `assets:clobber` to remove everything.

**Comment by danny6167** [comment]
I ran into this issue with the assets not loading after setting up my instance by following https://docs.joinmastodon.org/admin/install/.  I believe I followed it correctly.

Further investigation into logs revealed nginx didn't have permissions to access the `/home/mastodon/live/` folder.

I resolved this by adding the `www-user` user of my system to the `mastodon` group. This was on an Ubuntu 22.04 system.

**Comment by rickersilva** [comment]
> > Have you precompiled? Usually that will fix the issue. My problem is I cannot get the precompiled to run clean.
> 
> Run `assets:clobber` to remove everything.

ehre hould I run that? as root or as mastodon?

**Comment by capcom1701** [comment]
Try running it as su - mastodon in ~/live/ 

The precompiling affects the page display. I'm not clear on what might be causing the verification link issue.

**Comment by ClearlyClaire** [comment]
The verification link thing does not sound like something Mastodon itself may be doing. It may be something with the services you use to send mails.

**Comment by rickersilva** [comment]
> The verification link thing does not sound like something Mastodon itself may be doing. It may be something with the services you use to send mails.

you are right. Sendgrid has some link branding that makes all links go through a subdomain. I disabled that. I missunderstood what it was.
