### ISSUE TITLE
Suggestion - Media filter for Home feed

### ISSUE THREAD

**Issue by ineffyble** [mastodon/mastodon#20619]
### Discussed in https://github.com/mastodon/mastodon/discussions/20613

<div type='discussions-op-text'>

<sup>Originally posted by **sygninx** November 14, 2022</sup>
On my desktop (running the advanced web interface), my Local timeline has an option to show/hide only posts with Media.

My Home timeline has the option to show/hide boosts & replies, which is handy. If the show/hide option for Media can be added, it would be great as an additional filter. 

(I'm not a dev; I was asking about this on my account and someone suggested I request this as a feature here)</div>

**Comment by trwnh** [comment]
Duplicate of #6603

**Comment by ineffyble** [comment]
Closing as duplicate.
