### ISSUE TITLE
Consider including foreman as a development dependency

### ISSUE THREAD

**Issue by SamStephens** [mastodon/mastodon#20635]
### Pitch

[The current development setup instructions](https://github.com/mastodon/documentation/blob/31a159d456a245efe1514b29a6694aa9fb115eb4/content/en/dev/setup.md) have us install foreman manually in order to use it. Is there any reason not to simply include foreman in the Gemfile as a development dependency?

### Motivation

It makes setup simpler for new developers. It keeps consistency, with all development gems managed in the Gemfile. And it ensures there's no compatibility confusion with different foreman versions, by allowing the required foreman version to be constrained by an appropriate version specifier.

**Comment by renatolond** [comment]
It seems the recommendation from the Foreman wiki is to not include it as a bundled dependency: https://github.com/ddollar/foreman/wiki/Don%27t-Bundle-Foreman
(though I agree it makes development easier)

**Comment by SamStephens** [comment]
Oh that's interesting. It's made clear in https://github.com/ddollar/foreman/issues/573#issuecomment-213834698 that installation at the system level is the only supported mode of operation.

I find this kind of bizarre, honestly, why not include it as a development Gem, why is foreman so special? The upvotes on https://github.com/ddollar/foreman/issues/573#issuecomment-237287147 say at least 31 other people do too 😁. But if including in the Gemfile is unsupported, the current approach and documentation are appropriate.

Resolving this.
