### ISSUE TITLE
Role labels don't show up

### ISSUE THREAD

**Issue by koyuawsmbrtn** [mastodon/mastodon#20659]
### Steps to reproduce the problem

1. Click on a profile
2. No role label

### Expected behaviour

Role labels should display in profiles

### Actual behaviour

No role labels in profiles

### Specifications

Mastodon 4.0.0rc4
NodeJS 16.18.1
Ruby 3.0.3

Chrome Version 107.0.5304.107 (x64) on Windows 10

**Comment by ineffyble** [comment]
This is likely to not be addressed until v4.1.

**Comment by jensensen** [comment]
Seems that after upgrade to version 4.x former admins now are owner. And even with v4.0.2 there's no way to change the role.
