### ISSUE TITLE
Incorrect error message when using passwords that are too long

### ISSUE THREAD

**Issue by jdaviescoates** [mastodon/mastodon#20653]
### Steps to reproduce the problem

1. paste a long 128 character new passwords into change password boxes
2. click save
3. get a message telling me the new passwords don't match (they do).

The really issue is not that they don't match, but that they are too long. 

The UI should:

1. Let users know what the max length of pw is
2. display the correct error message when a pw is too long

Out of interest (and because it's not displayed anywhere): what is the current max pw length in mastodon? Thanks!
...

### Expected behaviour

When trying a pw that is too long a message should display saying something like "your password is too long, max length = x characters"

### Actual behaviour

When trying to use a nice long secure pw the error message when saving says it's because the pw don't match. That isn't true.

### Detailed description

At present it is not clear how long the max pw length is and when trying to use a password that is too long the error message displayed says it's because the passwords don't match, instead it should be made clear what the max length is and when trying to use a password longer than the max an error message should say that.

### Specifications

I'm not sure of the server specs, I'm just a user on it https://social.coop but I don't think this info is relevant for this bug.

**Comment by ineffyble** [comment]
This should already be the behaviour: https://github.com/mastodon/mastodon/blob/main/app/javascript/packs/public.js#L118

So either you've hit a weird edgecase or there's a regression here.

**Comment by ineffyble** [comment]
@jdaviescoates I found the issue. This was fixed in December 2021. Unfortunately https://social.coop is running a very old verison, from November 2021, which doesn't have this bugfix. You might want to suggest to the admin that they upgrade to a more recent version.

**Comment by jdaviescoates** [comment]
Thanks @ineffyble I'll let the https://social.coop admins know...

**Comment by jdaviescoates** [comment]
> The max password length is currently 72 characters.

Thanks. Is that info displayed on the latest version?
