### ISSUE TITLE
Official helm chart repository

### ISSUE THREAD

**Issue by TheAnachronism** [mastodon/mastodon#20670]
### Pitch

The current method to deploy the supplied helm chart makes it difficult for Git Ops environments, especially with updating their installations. This would be immensely improved, if there was a published helm chart version somewhere in a helm repo.
That way, the helm config files don't have to be copied into their Ops directory and just a simple version update is necessary.

### Motivation

I deploy basically everything in my cluster with ArgoCD. It's really nice and simple to use if there's an _Operations_ git repository where all the manifests for helm, kustomize or whatever are present. ArgoCD just has to use these manifests and that is it.

The problem with the current supplied method for deploying the helm chart, is that all the files have to be copied into that directory. Updating that copied version could get difficult compared to just making some changes in the configuration which version of the chart should be used from a remote helm repository.

**Comment by ineffyble** [comment]
This will be solved by #20427 if/when merged.

**Comment by TheAnachronism** [comment]
Nice, exactly this is what I'm looking for. Hoping to see this soon ^^
