### ISSUE TITLE
Support dash in tags like #Code-E

### ISSUE THREAD

**Issue by BuZZ-dEE** [mastodon/mastodon#20694]
### Pitch

Support dash in tags like [#DJ_Code-E](https://diasp.org/tags/dj_code-e) like it is possible in [Diaspora](https://diasp.org/tags/code-e).

https://diasp.org/tags/code-e
https://ravenation.club/tags/Code-E

vs

https://diasp.org/tags/codee
https://ravenation.club/tags/CodeE

### Motivation

Useful to tag artists with a dash in the name.

**Comment by rokejulianlockhart** [comment]
Really, shouldn't anything except whitespace constitute a tag? When would that be undesirable?
