### ISSUE TITLE
[Feature Request] Support cockroachdb

### ISSUE THREAD

**Issue by supernovae** [mastodon/mastodon#20702]
### Pitch

I'd like to be able to use a geo-redundant database that is mostly pgsql compatible to run Mastodon in multi-regions / zones.

### Motivation

Enable distributed databases to run Mastodon in multi-region/zone configuration.

/* CockroachDB is the world’s most evolved cloud SQL database —  giving all of your apps effortless scale, bulletproof resilience and low latency performance for users anywhere. */

This would be great for scaling up and distributing for even shared/hosted Mastodon instances.

**Comment by jfqd** [comment]
Anyone tried to use the `activerecord-cockroachdb-adapter` instead of the `pg` gem? There is a post about it on the [cockroachlabs](https://www.cockroachlabs.com/blog/app-rails-activerecord-cockroachdb/) site.

**Comment by jfqd** [comment]
@supernovae Do you have a link for us to the code, that fixes this support issue?

**Comment by wb14123** [comment]
@supernovae I'm also wondering if there is more info about the change since you marked this issue as completed.
