### ISSUE TITLE
SyntaxError: Unexptected token '.' when updating to v4.0

### ISSUE THREAD

**Issue by Michael-Brooks** [mastodon/mastodon#20706]
### Steps to reproduce the problem

1. Upgrade to v4 of Mastodon
2. Follow all upgrade steps including yarn install and assets:precompile
3. Restart mastodon-streaming service
4. Run `journalctl -u mastodon-streaming` and scroll to the bottom and see the error
...

### Expected behaviour

Streaming should start

### Actual behaviour

Streaming fails to start with error

### Detailed description

I have also tried removing node_modules and assets directory, reinstalled and re-compiled with no luck.

```
Nov 14 22:13:44 mastodon313onubuntu1804-s-1vcpu-1gb-lon1-01 node[5425]: SyntaxError: Unexpected token '.'
Nov 14 22:13:44 mastodon313onubuntu1804-s-1vcpu-1gb-lon1-01 node[5425]:     at wrapSafe (internal/modules/cjs/loader.js:915:16)
Nov 14 22:13:44 mastodon313onubuntu1804-s-1vcpu-1gb-lon1-01 node[5425]:     at Module._compile (internal/modules/cjs/loader.js:963:27)
Nov 14 22:13:44 mastodon313onubuntu1804-s-1vcpu-1gb-lon1-01 node[5425]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Nov 14 22:13:44 mastodon313onubuntu1804-s-1vcpu-1gb-lon1-01 node[5425]:     at Module.load (internal/modules/cjs/loader.js:863:32)
Nov 14 22:13:44 mastodon313onubuntu1804-s-1vcpu-1gb-lon1-01 node[5425]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
Nov 14 22:13:44 mastodon313onubuntu1804-s-1vcpu-1gb-lon1-01 node[5425]:     at Module.require (internal/modules/cjs/loader.js:887:19)
Nov 14 22:13:44 mastodon313onubuntu1804-s-1vcpu-1gb-lon1-01 node[5425]:     at require (internal/modules/cjs/helpers.js:74:18)
Nov 14 22:13:44 mastodon313onubuntu1804-s-1vcpu-1gb-lon1-01 node[5425]:     at Object.<anonymous> (/home/mastodon/live/node_modules/jsdom/lib/jsdom/browser/parser/index.js:4:20)
Nov 14 22:13:44 mastodon313onubuntu1804-s-1vcpu-1gb-lon1-01 node[5425]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
Nov 14 22:13:44 mastodon313onubuntu1804-s-1vcpu-1gb-lon1-01 node[5425]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Nov 14 22:13:44 mastodon313onubuntu1804-s-1vcpu-1gb-lon1-01 systemd[1]: mastodon-streaming.service: Main process exited, code=exited, status=1/FAILURE
Nov 14 22:13:44 mastodon313onubuntu1804-s-1vcpu-1gb-lon1-01 systemd[1]: mastodon-streaming.service: Failed with result 'exit-code'.
Nov 14 22:13:44 mastodon313onubuntu1804-s-1vcpu-1gb-lon1-01 systemd[1]: mastodon-streaming.service: Scheduled restart job, restart counter is at 5.
Nov 14 22:13:44 mastodon313onubuntu1804-s-1vcpu-1gb-lon1-01 systemd[1]: Stopped mastodon-streaming.
Nov 14 22:13:44 mastodon313onubuntu1804-s-1vcpu-1gb-lon1-01 systemd[1]: mastodon-streaming.service: Start request repeated too quickly.
Nov 14 22:13:44 mastodon313onubuntu1804-s-1vcpu-1gb-lon1-01 systemd[1]: mastodon-streaming.service: Failed with result 'exit-code'.
Nov 14 22:13:44 mastodon313onubuntu1804-s-1vcpu-1gb-lon1-01 systemd[1]: Failed to start mastodon-streaming.
```

### Specifications

Mastodon v4.0.2
Ruby: 3.0.3
Yarn: 1.22.19
Node: v16.18.1
npm: 8.19.2

**Comment by Michael-Brooks** [comment]
I'm going to reopen this because I thought I fixed the issue, but I haven't. I have tried migrating all the files in dist to `/etc/systemd/system` and reloaded the conf files, then restarted the services. I have tried reinstalling all node packages, clearing the cache and precompiling all assets. Any help would be appreciated.

**Comment by Michael-Brooks** [comment]
It turns out, I had NodeJS v12 installed via apt. Updated to v16 and it's all working now.

**Comment by xpat** [comment]
I'm getting this error today, after unsuccessfully upgrading to 4.0.0

```
/home/mastodon/live/node_modules/jsdom/lib/jsdom/browser/parser/html.js:170
Nov 16 22:25:56 teampoutineinstance node[898487]:     after._pushedOnStackOfOpenElements?.();
                                                                                                                                                                            ^
```

ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]
node --version v16.18.1
npm --version 8.19.2
nvm --version 0.39.2
yarn --version 1.22.19
Mastodon version 4.0.0 (which I figured out by going $cat live/lib/mastodon/version.rb)

**Comment by Volkor3-16** [comment]
> I'm getting this error today, after unsuccessfully upgrading to 4.0.0
> 
> ```
> /home/mastodon/live/node_modules/jsdom/lib/jsdom/browser/parser/html.js:170
> Nov 16 22:25:56 teampoutineinstance node[898487]:     after._pushedOnStackOfOpenElements?.();
>                                                                                                                                                                             ^
> ```
> 
> ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux] node --version v16.18.1 npm --version 8.19.2 nvm --version 0.39.2 yarn --version 1.22.19 Mastodon version 4.0.0 (which I figured out by going $cat live/lib/mastodon/version.rb)

https://github.com/mastodon/mastodon/issues/20218 Changing `/usr/bin/node` to `/usr/local/bin/node` fixed this for me.

**Comment by xpat** [comment]
I ended up replacing my messed up package.json with a fresh copy from the official repository and got it running again yesterday. Whew... But I altered so many other variables along the way, I don't know for sure what was extraneous and what was critical. 😧
