### ISSUE TITLE
Federation broken after update to 4.0

### ISSUE THREAD

**Issue by KaitoCross** [mastodon/mastodon#20710]
### Steps to reproduce the problem

1. Update from 3.5.0 to 4.0 according to instructions
2. Post new message
3. Wait for replies from users from other instances

### Expected behaviour

I should have received replies

### Actual behaviour

Replies do not arrive - my posts were sent out though.

### Detailed description

I updated from 3.5.0 to 4.0 and suddenly I cant see any incoming messages from other instances in my timeline anymore. The post appears on Mastodon.social and the timelines of my followers, but their replys do not make it to my timeline. The admin dashboard tells me "No Sidekiq process running for the scheduler, ingress queue(s). Please review your Sidekiq configuration". But I have not consciously altered my Sidekiq configuration at all, it should be the standard config.

### Specifications

Mastodon 4.0.1
Ruby 3.0.4p208
PostgreSQL | 11.18
Redis | 5.0.14

**Comment by KaitoCross** [comment]
Solved the problem on my machine: The service file mastodon-sidekiq.service was missing a parameter in ExecStart for the new Sidekiq queue. It was missing the -q ingress parameter.

**Comment by anon8675309** [comment]
@KaitoCross You are a saint. Thank you for documenting this, as the release notes were claimed that no changes were required to mastodon-sidekiq.service unless  "you customize Sidekiq processes/queues".

For any admins who want more explicit instructions:

```sh
sed -i 's/\(ExecStart=.*\)/ExecStart=\1 -q ingress -q scheduler/' /etc/systemd/system/mastodon-sidekiq.service
systemctl daemon-reload
systemctl restart mastodon-sidekiq.service
systemctl status mastodon-sidekiq.service
```

The output from the last command will likely say something like "sidekiq 6.5.7 live [5 of 5 busy]" which indicates that sidekiq is busy doing its thing.  Previously this likely said "[0 of 5 busy]" unless someone on your instance was tooting.

**Comment by poweredgenl** [comment]
out of curiosity - how to handle / pass this parameter to a docker setup ? (eg compose?) ... im running 4.0.2 and also in doubt in federation works (with relay servers)

**Comment by seungjin** [comment]
> out of curiosity - how to handle / pass this parameter to a docker setup ? (eg compose?) ... im running 4.0.2 and also in doubt in federation works (with relay servers)

Set your "command" in sidekiq service.
For mine, 
I did 
```
  sidekiq:
    image: tootsuite/mastodon:v4.0.2
    command: bundle exec sidekiq -q ingress -q scheduler
```
was originally 
` command: bundlie exec sidekiq`
