### ISSUE TITLE
Ability to change PWA icon and favicon

### ISSUE THREAD

**Issue by SJang1** [mastodon/mastodon#20726]
### Pitch

It would be nice to have a setting that does the ability to
- Change the PWA icon
- change favicon
of the server.

### Motivation

Servers can make their images by changing the server icon easily.

**Comment by lgE-1** [comment]
I also need this ability. The uniform icons make the instances too similar to each other, and such a lack of personalization would reduce the motivation of admin to run their own instances. At present, the technical threshold for modifying icons is relatively high, I hope it can be more convenient, or provide notes for modification.

**Comment by ThatOneCalculator** [comment]
It's a shame masto is lacking in this department compared to Calckey/Misskey...

![image](https://user-images.githubusercontent.com/44733677/207173578-b24a0e4f-9818-44d5-b61c-7922c55f39b8.png)

**Comment by LovesTha** [comment]
Server setting of icon is a minimum. Per user could be nice, but would be additional server load so probably not worth it.

**Comment by almereyda** [comment]
Is this possibly a duplicate of #7396?

**Comment by renchap** [comment]
Duplicate of #7396
