### ISSUE TITLE
Post-Docker Update, I Cannot Change The Server Thumbnail Picture, Displays Blank.

### ISSUE THREAD

**Issue by PhoenixSheppy** [mastodon/mastodon#20737]
### Steps to reproduce the problem

1. Update Docker image using 4.0.0 update instructions, upgrading DB, etc.
2. Reboot Containers
3. Check /about, thumbnail is blank.
4. You cannot change the icon, and are met with "Security verification failed. Are you blocking cookies?" when attempting to delete or change the icon.

### Expected behaviour

I should be able to change the server thumbnail icon.

### Actual behaviour

I cannot change my server thumbnail icon.

### Detailed description

3: 
![image](https://user-images.githubusercontent.com/20131900/201827939-6b2743f2-bda6-438e-a3d7-0e5cb93f6e55.png)

4:
![image](https://user-images.githubusercontent.com/20131900/201827995-2fa61897-9beb-491e-9195-3c5532015187.png)

### Specifications

Mastodon 4.0.1 (Docker / Tootsuite)
Nginx Reverse Proxy (Infront, proxying traffic)

**Comment by ineffyble** [comment]
Is there anything in the web container logs when this happens?

**Comment by PhoenixSheppy** [comment]
Fixed w/Update. Will reopen if necessary.
