### ISSUE TITLE
Cannot view my own public profile while logged in on v4.0.1

### ISSUE THREAD

**Issue by wolfteeth** [mastodon/mastodon#20742]
### Steps to reproduce the problem

1. Log into Mastodon server.
2. Visit my public URL for that server. e.g. `https://<server>/@<username>`

### Expected behaviour

Mastodon should direct me to the public version of my profile

### Actual behaviour

Mastodon opened my profile within the web app

### Detailed description

This is a confusing change in behavior from v3.5.x to v4.0.x. This behavior occurs whether using the advanced or standard web UI.

At the same time I also noticed that clicking my avatar in the web interface now shows me a larger version of the avatar, instead of directing me to my public profile. I don't mind that necessarily but there should be some way to view my public page without logging out.

### Specifications

Mastodon v4.0.1

**Comment by ineffyble** [comment]
I've been using incognito (private browsing) if I want to see how my profile looks to logged out users.

**Comment by wolfteeth** [comment]
It's a decent workaround but IMO the old behavior was good.

**Comment by ineffyble** [comment]
Perhaps some inspiration from Facebook would be useful here:

<img width="402" alt="image" src="https://user-images.githubusercontent.com/834880/201832618-cc2e3c25-0ca3-4dde-a3e2-2c890b430662.png">

**Comment by wolfteeth** [comment]
@ineffyble I was just thinking of something like this, actually. Some kind of preview mode would be nice.
