### ISSUE TITLE
Fix lack of margin/padding in advanced web viewer

### ISSUE THREAD

**Issue by xPhentom** [mastodon/mastodon#20757]
### Steps to reproduce the problem

**When I:**
Open Mastodon in the advanced web viewer.

**I expected:**
There to be enough spacing between the profile image and profile name in Toots

**What I currently see:**
 
![image](https://user-images.githubusercontent.com/5096867/201867353-a0ad7dcf-aa7e-409c-af52-b222a9bc2409.png)

### Expected behaviour

There to be enough spacing between the profile image and profile name in Toots

### Actual behaviour

See attached picture

### Specifications

Fosstodon instance
Mastodon version: v4.0.1

Checked the code for v4.0.2, doesn't seem to fix it yet.

**Comment by Michael-Brooks** [comment]
Have you ran a yarn update and re-compiled your assets?

**Comment by xPhentom** [comment]
Ah, looks like the issue only exists on qutebrowser, my bad. 
Should this be closed now? 😄

**Comment by ClearlyClaire** [comment]
Depend if we're doing something weird or qutebrowser is the weird one, I guess. But considering there is no issue in either Firefox or Chromium, I'd be inclined towards closing the issue.

**Comment by benjaminbhollon** [comment]
I know what's happening now that I know it's qutebrowser-specific—I've encountered this a few times in my own code.

Qutebrowser is based on qtwebengine 5 which seems to be based on Chromium 77, which is one version too early to have :is or :where support, which is probably being used in the CSS.

If I remember correctly, the qutebrowser team is working on an update to Qt6 which I expect would include a web engine update, hopefully fixing this problem.
