### ISSUE TITLE
Changing the listening IP from 127.0.0.1 to anything

### ISSUE THREAD

**Issue by grimkroton** [mastodon/mastodon#20755]
### Steps to reproduce the problem

1. Install a Mastodon instance like documented here: https://docs.joinmastodon.org/admin/install/
2. Review documentation here https://docs.joinmastodon.org/admin/config/
3. After adding `BIND=0.0.0.0` to `.env.production` then what? How do I apply this configuration? Restarting the service does not apply the config

### Expected behaviour

Web and streaming should have changed their listening IPs

### Actual behaviour

nothing happened

### Detailed description

I do not want to use the documented Nginx. So I need to expose the mastodon-web and the mastodon-streaming to 0.0.0.0 instead of 127.0.0.1, so I can implement my own reverse proxy. 

### Specifications

commit fbcbf7898f000d9d1a21d52e8a8d3ed4602aa7db (HEAD, tag: v3.5.3)

**Comment by grimkroton** [comment]
Updated to 4.0.2
After the restart of the services, nodejs picked up the new bind config and is listening to `0.0.0.0:4000`.  It looks like this line here https://github.com/mastodon/mastodon/blob/a1738f899142b7080bf50713066c72f56121673e/config/puma.rb#L9 is not picking up the variable from `.env.production`.

**Comment by grimkroton** [comment]
I tried these 2 options in `.env.production`:
`BIND=0.0.0.0`
and
`BIND='0.0.0.0'`

**Comment by grimkroton** [comment]
After changing the line https://github.com/mastodon/mastodon/blob/a1738f899142b7080bf50713066c72f56121673e/config/puma.rb#L9 manually from '127.0.0.1' to '0.0.0.0', and restarting the `mastodon-web` service, it is listening to `0.0.0.0`

**Comment by ClearlyClaire** [comment]
As explained in https://docs.joinmastodon.org/admin/config/#bind `BIND` has to be set outside of `.env.production` because it is used before `.env.production` gets loaded.
