### ISSUE TITLE
Ability to restrict followed hashtag to selected instances

### ISSUE THREAD

**Issue by marco-meer** [mastodon/mastodon#20765]
### Pitch

Suppose I'm interested in what people from a particular instance have to say about a particular topic, but the hashtag is ambiguous and causes interference from posts from other instances or the entire Fediverse. One solution would be to limit the feed to posts from selected instances.

### Motivation

To my knowledge, there is no tool to explicitly track what an entire specific community (instance) has to say about a specific topic. Now, with the new feature that one can follow a hashtag, this becomes a possibility. 

- Currently, you can follow individuals or hashtags, which leads to a personal timeline. 
- Then there's the local timeline, where you can only apply a negative filter to filter out things you don't want to see. 
- The same goes for the federated timeline. 

What is missing is the ability to track what other instances have to say about a particular topic. This could be accomplished by limiting the followed hashtags to selected instances. 

- Avoiding risks: I can imagine instances popping up that are mostly bots and flooding timelines via hashtags. Individual users could easily manage spam by excluding those instances from their followed hashtag feed, reducing the workload of admins.

- Strenghtening communities: By following a hashtag restricted to a select community, the community is able to communicate important positions as a whole. This could be interesting for journalists as well as for the interdisciplinary discourse between scientists.

**Comment by coffeehabit** [comment]
Why would you want to know what a distinct group of communities are thinking about a particular topic? That seems, I don't know how to quite phrase it, but easy to datamine with no real gain. What examples are there for benefits? What important positions to be recognized that aren't already recognized? One of the primary reasons Mastodon exists is to disrupt the creation of marketing algorithms which is what the vibe this suggestion gives me.

I was thinking of something tangentially similar earlier today - namely the follow/block priority.

If you follow someone on any domain, then display it on **Home**.
If you block a domain, continue to show the person you follow on that domain on **Home** and **Federated** until you unfollow them.
If you block a domain, but search for a person on that domain, allow the ability to follow them.
If you follow a hashtag, but the domain is blocked, then don't show the matching posts from that domain. (should be a given)

IDK if that's how things currently work but if not then it does seem like the logical choice.

**Comment by marco-meer** [comment]
It appears as if a similar functionality has been realized by https://git.kaki87.net/KaKi87/userscripts/src/branch/master/mastovueEmbedded
