### ISSUE TITLE
Cannot update to mastodon 4.0.x (debian 11 no docker)

### ISSUE THREAD

**Issue by luca-yinxing** [mastodon/mastodon#20789]
### Steps to reproduce the problem

1. Update mastodon to 4.0.0  (tried 4.0.2 first)
2. Update rbenv to 3.1.2 (tried 3.0.4 first)
3. bundle exec rails assets:precompile

### Expected behaviour

Update mastodon

### Actual behaviour

Error page on web interface

### Detailed description

some output where I got an error from 
`sudo journalctl -u mastodon-web --since "10 minute ago"`

```
ActionView::Template::Error (undefined local variable or method `role_id' for #<User id: 1, email: ".....>
Did you mean?  role):
6:
7:   %meta{ name: 'applicationServerKey', content: Rails.configuration.x.vapid_public_key }
8:
9:   = render_initial_state
10:   = javascript_pack_tag 'application', crossorigin: 'anonymous'
11:
12: .notranslate.app-holder#mastodon{ data: { props: Oj.dump(default_props) } }

app/models/user.rb:157:in `role'
app/models/account.rb:124:in `user_role'
app/presenters/initial_state_presenter.rb:9:in `role'
app/helpers/application_helper.rb:223:in `render_initial_state'
```

### Specifications

Mastodon 4.0.0
rbenv 3.1.2

**Comment by GitPuffy** [comment]
What about the other steps?

Run the pre-deployment database migrations by specifying the SKIP_POST_DEPLOYMENT_MIGRATIONS=true environment variable:

- Non-Docker: SKIP_POST_DEPLOYMENT_MIGRATIONS=true RAILS_ENV=production bundle exec rails db:migrate

- Docker: docker-compose run --rm -e SKIP_POST_DEPLOYMENT_MIGRATIONS=true web rails db:migrate

Precompile the assets:

- Non-Docker: RAILS_ENV=production bundle exec rails assets:precompile

- Docker: The assets are already precompiled during the build step

Restart all Mastodon processes
Now that the new code is running, we can finish the database migrations. This will run the post-deployment ones:

- Non-Docker: RAILS_ENV=production bundle exec rails db:migrate

- Docker: docker-compose run --rm web rails db:migrate

Restart all Mastodon processes

(Poorly copied from https://github.com/mastodon/mastodon/releases/tag/v4.0.0 )

**Comment by luca-yinxing** [comment]
Oh, you are right, I missed database migration, this makes sense about the error, thank you!
I'm closing the issue
