### ISSUE TITLE
Disabled publish button still uses blue.

### ISSUE THREAD

**Issue by arielcostas** [mastodon/mastodon#20787]
### Steps to reproduce the problem

Write a post that can't be posted. For example, it exceeds the character count, or is just empty lines with no actual text.

### Expected behaviour

The post button appears as a `disabled` purple, consistent with the rest of the new theme

### Actual behaviour

The post button appears as a `disabled` blue color

### Detailed description

Demo

Valid post - purple publish button:
![Valid post: purple publish button](https://user-images.githubusercontent.com/94913521/201961727-50591118-f194-455e-943c-f455b0b1f65e.png)

Invalid post (too long, same happens ) - blue disabled publish button
![Invalid post (too long)](https://user-images.githubusercontent.com/94913521/201961956-5c1d5a72-eb94-4901-9e9d-8b276dd66fca.png)

### Specifications

- Mastodon 4.0.2 without any local cache (tried both hard-reloading with Control+Shift+R and using incognito tabs)
- Instance: mastodon.online and another instance I'm a member of (prefer not to name)
- Google Chrome version 107 on Windows 11

**Comment by ineffyble** [comment]
As far as I can see, this is the behaviour for all disabled buttons in the light theme on 4.0.2, not just the publish button. 

Should be a simple fix at least.

**Comment by arielcostas** [comment]
@ineffyble for what I've seen in the DevTools, it's just some variable on `components.sass` that isn't set right.

On dark mode it also does look blue-ish when disabled, so I don't think it's just a light-theme error.

![image](https://user-images.githubusercontent.com/94913521/201976427-78d5cba8-38d2-463d-8395-09f83014e87d.png)

**Comment by ineffyble** [comment]
On dark mode it's blue when non-disabled and a very pale blue/grey when disabled, to me that checks out and makes sense visually?

**Comment by arielcostas** [comment]
> On dark mode it's blue when non-disabled and a very pale blue/grey when disabled, to me that checks out and makes sense visually?

I'd expect more of a purple-ish color I guess? It looks too blue to be a purple theme, but maybe that's just personal taste

**Comment by vmstan** [comment]
Closing as completed, as with the updated composer coming as part of 4.3 the state of the button is the same all the time.
