### ISSUE TITLE
puma and web service not starting

### ISSUE THREAD

**Issue by jp92004** [mastodon/mastodon#20825]
### Steps to reproduce the problem

Running RAILS_ENV=production /home/mastodon/.rbenv/shims/bundle exec puma -C config/puma.rb
or trying to start the web service or trying to tootctl cache clear

### Expected behaviour

No errors

### Actual behaviour

Errors out with uninitialized date contant

### Detailed description

[2393] Puma starting in cluster mode...
[2393] * Puma version: 5.6.5 (ruby 2.6.6-p146) ("Birdie's Version")
[2393] *  Min threads: 5
[2393] *  Max threads: 5
[2393] *  Environment: production
[2393] *   Master PID: 2393
[2393] *      Workers: 2
[2393] *     Restarts: (✔) hot (✖) phased
[2393] * Preloading application
[2393] ! Unable to load application: NameError: uninitialized constant Date::Error
Did you mean?  IOError
               Errno
Traceback (most recent call last):
	52: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `<main>'
	51: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `eval'
	50: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/bin/puma:23:in `<main>'
	49: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/bin/puma:23:in `load'
	48: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/puma-5.6.5/bin/puma:10:in `<top (required)>'
	47: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/puma-5.6.5/lib/puma/cli.rb:81:in `run'
	46: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/puma-5.6.5/lib/puma/launcher.rb:193:in `run'
	45: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/puma-5.6.5/lib/puma/cluster.rb:357:in `run'
	44: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/puma-5.6.5/lib/puma/runner.rb:150:in `load_and_bind'
	43: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/puma-5.6.5/lib/puma/configuration.rb:270:in `app'
	42: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/puma-5.6.5/lib/puma/configuration.rb:348:in `load_rackup'
	41: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
	40: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
	39: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
	38: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
	37: from config.ru:4:in `block in <main>'
	36: from config.ru:4:in `require'
	35: from /home/mastodon/live/config/environment.rb:5:in `<top (required)>'
	34: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
	33: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
	32: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	31: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	30: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	29: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `call'
	28: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each'
	27: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	26: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	25: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	24: from /home/mastodon/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	23: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
	22: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
	21: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
	20: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-6.1.7/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
	19: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:318:in `eager_load_all'
	18: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:318:in `each'
	17: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:219:in `eager_load'
	16: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:219:in `synchronize'
	15: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:234:in `block in eager_load'
	14: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `ls'
	13: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `each'
	12: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:41:in `block in ls'
	11: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:239:in `block (2 levels) in eager_load'
	10: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `cget'
	 9: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `const_get'
	 8: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:27:in `require'
	 7: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	 6: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	 5: from /home/mastodon/live/app/controllers/activitypub/base_controller.rb:3:in `<top (required)>'
	 4: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:27:in `require'
	 3: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	 2: from /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	 1: from /home/mastodon/live/app/controllers/api/base_controller.rb:3:in `<top (required)>'
/home/mastodon/live/app/controllers/api/base_controller.rb:27:in `<class:BaseController>': uninitialized constant Date::Error (NameError)
Did you mean?  IOError
               Errno

### Specifications

Mastodon 4.0.2
Ubuntu 18
Node 14
ruby 2.6.6

**Comment by ineffyble** [comment]
@jp92004 I believe the issue is you're using Ruby 2.6, Mastodon 4.0.2 is designed for Ruby 3.0.

**Comment by jp92004** [comment]
> @jp92004 I believe the issue is you're using Ruby 2.6, Mastodon 4.0.2 is designed for Ruby 3.0.

Gotcha. Will try to update and see if that helps!

**Comment by vmstan** [comment]
@jp92004 can you confirm this addressed your issue?

**Comment by jp92004** [comment]
> @jp92004 can you confirm this addressed your issue?

Alas, I can't confirm. I ended up doing a complete reinstall with a newer version of the OS, so it might have been the issue or something else. I'm sorry I can't provide more definitive information.
