### ISSUE TITLE
USABILITY: init db  before configuration is completed causes silent failures / broken instance 

### ISSUE THREAD

**Issue by ForestJohnson** [mastodon/mastodon#20820]
### Steps to reproduce the problem

0.  install mastodon
1.  `rails setup:db`
2.  set the `LOCAL_DOMAIN` environment variable.
3.  start the server
4.  Try to follow someone from a server that has `AUTHORIZED_FETCH` or `LIMITED_FEDERATION_MODE`,  or have them try to follow you.  
5.  Follows / Direct Messages / etc will fail silently with no clear indication of why printed in the logs. 

### Expected behaviour

The init db step, the application startup step, and/or the operation of the federation code should have loudly failed in such a way that the server admin can be informed about the server configuration being badly broken

### Actual behaviour

init db appeared to succeed without warnings. The server appeared to start and operate just fine.  Then later on, the server admin noticed that interactions with some other servers, but not all of them,  were silently failing.  It took lots of digging to figure out what went wrong.

### Detailed description

Here are the notes direct from my friend about his experience with this issue: 

https://destituent.social/@fack/109348387556190423

> Okay so notes on last night's troubleshooting.
> 
> It seems to only be *certain accounts* on octodon.social that I cannot follow (or remote follow).
> 
> It seems that the entirety of pixie.town's userbase is un-followable besides this weird bot federation account: [@pixie.town](https://social.pixie.town/about/more?instance_actor=true)

https://destituent.social/@fack/109348911863549191

> I fixed my shit.
> 
> So, on servers with `AUTHORIZED_FETCH` or `LIMITED_FEDERATION_MODE`, they fall back to this weird mode of having a fake user that acts like a access controlled gateway to the entire instance. The username is something like `domain.tld@domain.tld`. You can find these for pretty much every mastodon server, and they appear as a bot account. These are known as `instance-wide actors`.
> 
> So these get generated based on your `LOCAL_DOMAIN` value, upon running `rails setup:db` .

https://destituent.social/@fack/109348936945102784

> So what happened, is I likely deployed my very first app without having `LOCAL_DOMAIN` set initially.
> 
> Because of this, my instance couldn't be communicated with via an `instance-wide actor` because the value it had was either un-initialized or invalid.
> 
> Sure enough it was invalid. This can be seen both by querying the postgres database and curling the `https://domain.tld/actor#main-key` contents.

https://destituent.social/@fack/109348960342437384

> Querying the db showed: 
> 
> ```
> # SELECT username FROM accounts WHERE id=-99;
> 
>     username     
> ----------------
>  localhost:3000
> ```
> 
> Which corresponded with the value in the curl
> ```
>     "preferredUsername": "localhost:3000",
> ```
> 
> So a quick fix was to connect to psql and run the following update: UPDATE accounts SET username = 'destituent.social' WHERE id=-99;
> 
> Now I can toot at my friends over on pixie.town!
> 

### Specifications

Mastodon  v4.0.2

**Comment by facklambda** [comment]
Thanks for creating this @ForestJohnson !

**Comment by ClearlyClaire** [comment]
Oops! Good catch! I believe #22307 should address this issue.
