### ISSUE TITLE
Low contrast for already-boosted toot in dark theme of the web UI

### ISSUE THREAD

**Issue by nemobis** [mastodon/mastodon#20830]
### Steps to reproduce the problem

1. Use the web UI with dark theme
2. Boost a post on your timeline
3. Look again at the boosted post later

### Expected behaviour

It should be clear that the post was already boosted

### Actual behaviour

The boost button barely seems different due to low contrast

### Detailed description

If I'm not mistaken we have a contrast of #8c8dff vs #313543 i.e. 4.3:1, which at 18 pt might be just enough to qualify for WCAG 2.0 1.4.3 (Level AA), but if not for the size would be lower than what required even for level AA, let alone AAA.

### Specifications

Mastodon 4.0.2
![Screenshot_20221116_003905](https://user-images.githubusercontent.com/901528/202040732-c2e27d1c-ee21-47bf-8ad6-baebafe9bf66.png)

**Comment by Gargron** [comment]
It’s fixed in main

**Comment by vmstan** [comment]
@downeymj I apologize it should have been closed as completed 👍
