### ISSUE TITLE
AVIF cannot be uploaded: 500 Error processing thumbnail for uploaded media

### ISSUE THREAD

**Issue by saschanaz** [mastodon/mastodon#20834]
### Steps to reproduce the problem

1. Upload an AVIF file (Get one from e.g. https://libre-software.net/image/avif-test/)
2. See it uploads

### Expected behaviour

It should upload

### Actual behaviour

500 Error processing thumbnail for uploaded media

### Detailed description

An error occurs immediately when picking an AVIF image to upload.

### Specifications

Mastodon 4.0.0rc2, 4.0.1, 4.0.2

Firefox 106, Chrome 107

**Comment by afontenot** [comment]
I do see this on mastodon.social, but I'm thinking this is *probably* instance specific, relating to an outdated version of Imagemagick or maybe ffmpeg on instances that don't build everything in a container. Do you see this with an instance you run yourself?

**Comment by saschanaz** [comment]
No, I tested this on fosstodon.org, qdon.space, and mastodon.social and thought this might be an upstream Mastodon thing. But then I just found another instance that this just works, so maybe you are right...

**Comment by MrGeneration** [comment]
My docker compose 4.0.1 installation throws the following on the rails container:

```
mastodon-web-1        | [f29069b0-efe9-4b85-bde4-6c40b136116a] method=POST path=/api/v1/markers format=html controller=Api::V1::MarkersController action=create status=200 duration=28.12 view=0.89 db=5.15
mastodon-web-1        | [2499c466-97cb-43ee-ae3b-666d76c2413a] [paperclip] Trying to link /tmp/RackMultipart20221116-24-v4d314.avif to /tmp/db95853fae84fb0b300e0ccd6eb0e2c420221116-24-may5pa.avif
mastodon-web-1        | [2499c466-97cb-43ee-ae3b-666d76c2413a] [paperclip] Trying to link /tmp/db95853fae84fb0b300e0ccd6eb0e2c420221116-24-may5pa.avif to /tmp/009aa263bd3233d9667457c57c616ce520221116-24-h34pus.heif
mastodon-web-1        | [2499c466-97cb-43ee-ae3b-666d76c2413a] Command :: file -b --mime '/tmp/009aa263bd3233d9667457c57c616ce520221116-24-h34pus.heif'
mastodon-web-1        | [2499c466-97cb-43ee-ae3b-666d76c2413a] Command :: convert '/tmp/db95853fae84fb0b300e0ccd6eb0e2c420221116-24-may5pa.avif[0]' -auto-orient -resize "1764x1176>" -quality 90 +profile "!icc,*" +set modify-date +set create-date '/tmp/5dfdf3778a558cae98618c25ce57fb7c20221116-24-vkomox.jpeg'
mastodon-web-1        | [2499c466-97cb-43ee-ae3b-666d76c2413a] method=POST path=/api/v2/media format=html controller=Api::V2::MediaController action=create status=500 duration=180.20 view=5.12 db=4.89
```

Not sure if that helps.

**Comment by saschanaz** [comment]
Those HEIF lines look mysterious to me 🤔
