### ISSUE TITLE
ffmpeg pulls a lot of dependencies in the docker image

### ISSUE THREAD

**Issue by bobrik** [mastodon/mastodon#20838]
### Steps to reproduce the problem

1. Download `tootsuite/mastodon:v4.0.2`
2. Wonder why is it so big?
3. Discover that ffmpeg is responsible for a considerable chunk.

### Expected behaviour

ffmpeg takes up a reasonable space

### Actual behaviour

ffmpeg takes up a lot of space

### Detailed description

If you try to install ffmpeg on `ubuntu:20.04` docker image:

```
0 upgraded, 176 newly installed, 0 to remove and 0 not upgraded.
Need to get 84.5 MB of archives.
After this operation, 1184 MB of additional disk space will be used.
```

Having 1184MB for ffmpeg is ridiculous, you can download statically linked official ffmpeg and it will be under 100MB:

* https://ffmpeg.org/download.html -> https://johnvansickle.com/ffmpeg/

Luckily 1184MB is a lie, the actual size is actually 281MB. The accounting but is fixed in `ubuntu:22.04`:

```
0 upgraded, 181 newly installed, 0 to remove and 0 not upgraded.
Need to get 101 MB of archives.
After this operation, 309 MB of additional disk space will be used.
```

If you build mastodon image without ffmpeg, it shrinks from 1.79GB to 1.55GB:

```
ivan@vm:~$ docker images
REPOSITORY   TAG           IMAGE ID       CREATED        SIZE
mastodon     no-ffmpeg     ef9284b3c3a0   3 hours ago    1.55GB
mastodon     regular       a5e3237b8079   8 hours ago    1.79GB
```

My suggestion is to use the statically linked ffmpeg and put it into `/opt` (same as ruby and nodejs).

The downside is that you lose automatic updates from ubuntu whenever image is rebuilt.

I can open a PR if it makes sense.

### Specifications

Mastodon v4.0.2

**Comment by afontenot** [comment]
> you can download statically linked official ffmpeg and it will be under 100MB:

This doesn't seem to be true. I downloaded the latest git master build and extracted it, the total size (according to `du -sh`) is 159M. This change seems to have a lot of downsides to save a mere ~120 MB or so.

**Comment by bobrik** [comment]
> I downloaded the latest git master build and extracted it, the total size (according to du -sh) is 159M.

Looks like amd64 builds are larger than arm64:

```
$ du -ms Downloads/ffmpeg-git-20220910-*-static
176	Downloads/ffmpeg-git-20220910-amd64-static
99	Downloads/ffmpeg-git-20220910-arm64-static
```

There's both `ffmpeg` and `ffprobe`, which are of similar size:

```
$ ls -l Downloads/ffmpeg-git-20220910-amd64-static
total 341456
-rw-r--r--@  1 ivan  staff     35147 Sep 10 06:25 GPLv3.txt
-rwxr-xr-x@  1 ivan  staff  78502816 Sep 10 06:25 ffmpeg
-rwxr-xr-x@  1 ivan  staff  78392768 Sep 10 06:25 ffprobe
drwxr-xr-x@ 14 ivan  staff       448 Sep 10 06:25 manpages
drwxr-xr-x@ 20 ivan  staff       640 Sep 10 05:48 model
-rwxr-xr-x@  1 ivan  staff    690888 Sep 10 06:25 qt-faststart
-rw-r--r--@  1 ivan  staff      2276 Sep 10 06:25 readme.txt
```

Presumably those have a lot of statically linked stuff duplicated.

> This change seems to have a lot of downsides

Could you elaborate which specific downsides do you have in mind?

**Comment by afontenot** [comment]
> Could you elaborate which specific downsides do you have in mind?

Biggest one - either the Mastodon organization would have to build ffmpeg statically, or some external build would have to be trusted, or the build process would have to add building ffmpeg as a step, which would make it significantly longer than it already is. Also, as you say, it adds a maintenance burden from having to bump the dependency when the docker image is rebuilt.

**Comment by ineffyble** [comment]
Not fixed by #20678 but may be impacted since that change moves to Debian.

**Comment by bobrik** [comment]
@afontenot my suggestion was using the prebuilt binaries, not adding another step to build it from source.

> may be impacted since that change moves to Debian

On Bullseye:

```
0 upgraded, 185 newly installed, 0 to remove and 0 not upgraded.
Need to get 99.7 MB of archives.
After this operation, 324 MB of additional disk space will be used.
```

**Comment by nemobis** [comment]
> The downside is that you lose automatic updates from ubuntu whenever image is rebuilt.

And this is a huge downside, because ffmpeg is a major potential attack vector, and related vulnerability news more likely to be missed than for something clearly central to Mastodon like ruby and nodejs.

**Comment by bobrik** [comment]
Same as ubuntu, you can download statically linked ffmpeg without specifying version. This of course depends on ffmpeg producing new releases when vulnerabilities are fixed, which ubuntu isn't bound by, as they can apply a patch and push a new version themselves without waiting for upstream.

**Comment by bobrik** [comment]
If #21143 gets in, ffmpeg will be an even bigger portion of the image (as the overall size is reduced).

**Comment by lqdmist** [comment]
This is getting out of hand:
`0 upgraded, 225 newly installed, 0 to remove and 0 not upgraded.
Need to get 181 MB of archives.
After this operation, 623 MB of additional disk space will be used.`

**Comment by vmstan** [comment]
The 4.3 image that I'm working on right now has ffmpeg built from source with only the pieces needed for Mastodon running in a container.

**Comment by mjankowski** [comment]
Closing on assumption that those ffmpeg/docker changes either solved, or at least minimized as much as possible, the size issue here.

Please reopen if still not acceptable!
