### ISSUE TITLE
missing CSS on avatar image

### ISSUE THREAD

**Issue by jskinne3** [mastodon/mastodon#20841]
### Steps to reproduce the problem

1. Upgraded v3.1.3 -> v3.4.0 -> v3.4.1 -> v3.4.5 per each version's upgrade notes
2. Visit a profile page such as https://carhenge.club/@skiles
3. Find that avatar image appears underneath text and is much too wide

Note: adding this to custom CSS fixes the problem:
`.status__avatar img {max-width: 50px;} `

### Expected behaviour

Avatar image fits to the left of text

### Actual behaviour

Avatar image is too wide

### Detailed description

After a series of Mastodon version upgrades moving from v3.1.3 to v3.4.5 by steps, following the upgrade notes, I noticed that avatar images are too wide. They appear under the text of a toot on desktop and mobile views in Chrome.
![Desktop example](https://user-images.githubusercontent.com/546123/202092137-4bf1c80a-9427-405c-84b2-4f2d754d11e0.png)
![Mobile example](https://user-images.githubusercontent.com/546123/202092254-a90a5489-892b-4f20-8504-cb032ddda425.png)

This appears to be because of a missing CSS style. Adding this line to the custom CSS returns the avatar images to normal size:
`.status__avatar img {max-width: 50px;} `

My server (https://carhenge.club/) currently has this problem and has the above custom CSS applied to remediate it.

### Specifications

Mastodon v3.4.5
Ruby 2.6.6p146
Node v12.16.1

Chrome 107.0.5304.110 on Macbook
Chrome 107.0.5304.105 on Android

**Comment by ineffyble** [comment]
There's been substantial CSS changes in 4.0.0, hopefully those fix this when you upgrade next.

**Comment by jskinne3** [comment]
I was hoping to reach 3.5.3 and pause for a while before going to v4. Do you think there's another way to work it out?

**Comment by jskinne3** [comment]
Update: running `yarn install` appears to have fixed this problem. Perhaps it should be added to the v3.4.5 upgrade notes.
