### ISSUE TITLE
Fails to run "yarn install --pure-lockfile"

### ISSUE THREAD

**Issue by AndrijaSobak** [mastodon/mastodon#20849]
### Steps to reproduce the problem

I followed all the steps in documentation and it fails to run "yarn install --pure-lockfile" command.

### Expected behaviour

yarn install --pure-lockfile to run

### Actual behaviour

yarn install --pure-lockfile fails

### Detailed description

mastodon@ubuntu-4gb-nbg1-1:~/live$ yarn install --pure-lockfile
Unknown Syntax Error: Unsupported option name ("--pure-lockfile").

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
mastodon@ubuntu-4gb-nbg1-1:~/live$

### Specifications

Ubuntu 20.04.5 LTS
Mastodon 4.0.2
yarn 3.2.4
ruby 3.0.4p208 (2022-04-12 revision 3fa771dded)
Nodejs v16.18.1

**Comment by ineffyble** [comment]
Seems like Yarn is operating in modern/berry mode instead of classic/v1 mode.

Try `yarn set version classic`.

**Comment by AndrijaSobak** [comment]
This was the issue, I will close this for now.

Thank you very much @ineffyble
