### ISSUE TITLE
"Create account" button when logged out goes different places, depending on screen width

### ISSUE THREAD

**Issue by skyfaller** [mastodon/mastodon#20840]
### Steps to reproduce the problem

1. View a Mastodon 4.0+ site when logged out
2. Click the "Create account" button in desktop width
3. Observe the "Custom message when sign-ups are not available" that is configurable in Administration > Server Settings > Registrations, appears under "On this server". (My instance uses this to direct people to a form for requesting an invite.) There is also "On a different server" text that guides you to the ["official" server picker](https://joinmastodon.org/servers).
4. Resize your window to be narrow enough to trigger the mobile view (or check it out on your phone).
5. The same "Create account" button just takes you straight to the server picker, the user does not see the "Custom message when sign-ups are not available". There is no opportunity for a mobile user to see our invite request form.
...

### Expected behaviour

You should be able to see the "Custom message when sign-ups are not available" in mobile view

### Actual behaviour

"Custom message when sign-ups are not available" does not appear in mobile view

### Detailed description

I propose showing the same popup on both mobile and desktop, it should be consistent. If consistency is impossible or undesirable, we need an alternative way for people to see our invite request form when in mobile view.

### Specifications

Mastodon v4.0.2

Firefox 106.0.4

**Comment by tomresing** [comment]
Seems like a high priority bug to me.

**Comment by mediaformat** [comment]
Just to show and tell, social.coop uses the custom message to point to an alternate signup form.

It works on desktop, but on mobile there is no similar modal, which is somewhat an anti pattern 

https://user-images.githubusercontent.com/2895351/203674918-7424a5a7-f0d3-408c-9c96-82b45f7a448f.MOV
