### ISSUE TITLE
Custom emojis federation not always working

### ISSUE THREAD

**Issue by renatolond** [mastodon/mastodon#20855]
### Steps to reproduce the problem

I'm still not sure on which conditions it happens, but

1. Someone I follow on a remote instance toots with a custom emoji
2. Only the shortcode arrives
3. The custom emoji also does not appear in the admin panel for the remote instance

### Expected behaviour

Custom emoji should appear

### Actual behaviour

The shortcode appears instead

### Detailed description

I also tried copying the link and pasting on the search to try to force a re-fetch of the toot and it didn't work
Local sidekiq queue is empty

### Specifications

Mastodon 4.0.2 (donte fork)
Ruby 3.0.4
Node 14.19.1

Remote instance is also mastodon, on 3.5.3

**Comment by keskival** [comment]
This might be because the remote instance has actually lost that emoji. But it happens consistently when a not-locally-cached emoji is used in a remote profile: https://github.com/mastodon/mastodon/issues/17862

**Comment by renatolond** [comment]
I double-checked and the remote instance still had the emoji, I can see the emoji by opening the original link. It seems to happen sometimes when the emoji shortcode in the remote instance clashes with a local one in different case, but it's not the only case, so I'm not sure that's related

**Comment by trwnh** [comment]
it could be several reasons, maybe the custom emoji is an unsupported filetype (webp?) or is too large
