### ISSUE TITLE
show verification status near username

### ISSUE THREAD

**Issue by afgeissler** [mastodon/mastodon#20869]
### Pitch

I like the idea of verification via rel-me. I could be helpful if the successful verification was also signalled in the user name. For example, by a green tick in front of the username or as in the profile with a green background.

### Motivation

don't want to go to the profile just to check verification status

**Comment by ineffyble** [comment]
The problem is that this would be misleading. It would imply the user/person is verified, and they're not. What's verified is their relationship to a particular website.

If you move the tick away from the profile you get the exact same impersonation problem that's brought Twitter to its knees this month.

**Comment by afgeissler** [comment]
My idea was actually just to mirror the display in the profile to the usernames. If there is a verification tick in the profile, a symbol is displayed in the user name; if the tick disappears in the profile, the display in the user name must also disappear.
Perhaps another symbol could be used instead of a tick to show that the user is not verified but that the website is verified. 

Regardless of this, that feature request is also a good idea.

**Comment by sam1919** [comment]
Any symbol where users could mix it up with personal verification should be avoided, best I could imagine would be a small "globe" icon like the "public" icon from the Material symbol set:
https://fonts.google.com/icons?selected=Material+Symbols+Outlined:public

**Comment by trwnh** [comment]
![image](https://github.com/mastodon/mastodon/assets/10606431/abf2ad0a-de4d-4c6f-87a4-37a88ccfcd66)
