### ISSUE TITLE
wrong margin

### ISSUE THREAD

**Issue by mskf1383** [mastodon/mastodon#20862]
### Steps to reproduce the problem

1. set a RTL language like Persian or Arabic

### Expected behaviour

no 68px margin before posts

### Actual behaviour

there is a 68px margin at the start of posts

### Detailed description

I can't see that margin when a LTR language is set. It is only in RTL.

### Specifications

Mastodon 4.0.2 on https://social.tchncs.de on Firefox 106

**Comment by mskf1383** [comment]
https://github.com/mastodon/mastodon/blob/1bd00036c284bcafb419eaf80347ba49d1b491d9/app/javascript/styles/mastodon/rtl.scss#L153

**Comment by dariusk** [comment]
I believe this is the same problem reported in hometown-fork/hometown#1268 -- confirmed to be an issue on `mastodon.social`

![https://user-images.githubusercontent.com/266454/210888178-49ac1e84-bae3-4b59-8870-110ecbd5344e.png](https://user-images.githubusercontent.com/266454/210888178-49ac1e84-bae3-4b59-8870-110ecbd5344e.png)
