### ISSUE TITLE
Upgrade to Yarn v3 (Yarn modern/berry)

### ISSUE THREAD

**Issue by ineffyble** [mastodon/mastodon#20871]
### Pitch

At some point soon we need to bite the bullet and migrate away from Yarn 1 (Yarn Classic).

This should not entail too much work, and shouldn't require much work from admins/devs because the upgrade effectively makes the Yarn version managed by the repo, they won't have to install anything new globally (it should, theoretically, just work).

### Motivation

Significant performance and reliability improvements, avoiding tech debt, avoiding potential security issues once Yarn Classic goes EOL.

Also as Yarn 2/3 (modern) starts to become more widespread, more people will be using it with this repo without realising and hit issues like #20849, #20689, #15686, and https://discourse.joinmastodon.org/t/yarn-error-no-such-option-pure-lockfile/2431.

**Comment by xpat** [comment]
I'm stuck.  

Yesterday I upgraded one server on DigitalOcean no problem.  I then went to upgrade a second server and have had no luck getting it to run again.  So today, I deleted $live/.vendor/bundle and ran this command:

```
bundle install -j$(getconf _NPROCESSORS_ONLN)
```
and then this:


```
:~/live$ yarn install --pure-lockfile
Unknown Syntax Error: Unsupported option name ("--pure-lockfile").

$ yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
mastodon@teampoutineinstance:~/live$ which yarn
/home/mastodon/.nvm/versions/node/v18.12.0/bin/yarn
```
Is there a work-around that I'm not seeing mentioned?  (see also https://github.com/mastodon/mastodon/issues/15686)

**Comment by vmstan** [comment]
Project has upgrade to Yarn 4. Closing as completed.
