### ISSUE TITLE
Inconsistent translations of publish button

### ISSUE THREAD

**Issue by garritfra** [mastodon/mastodon#20882]
### Steps to reproduce the problem

1. Check translation for publish button beneath compose box
2. Hit "Reply" on any post
3. Check translation for publish button beneath compose box

### Expected behaviour

Both cases use consistent translations

### Actual behaviour

Results step 1:

<img width="306" alt="grafik" src="https://user-images.githubusercontent.com/32395585/202218304-4b8d1071-9967-4ccc-8c47-2f2c9106e247.png">

Results step 3:

<img width="300" alt="grafik" src="https://user-images.githubusercontent.com/32395585/202218409-b87d7587-b652-42fd-bf98-53f7fa0595aa.png">

### Detailed description

I'm unsure if this is just a faulty translation, or if the two use cases should actually use the same translation.

### Specifications

Mastodon 4.0.2

**Comment by ineffyble** [comment]
@garritfra Believe it or not, this is a feature. The exclamation mark gets added depending on the post visibility (it'll correspond with the visibility icon, e.g. world icon = public = !, padlock = unlisted = no !).

**Comment by garritfra** [comment]
@ineffyble oh! Interesting. I guess this issue can be closed then. Thanks for clarifying!
