### ISSUE TITLE
Explore Tabs disappear when clicking them

### ISSUE THREAD

**Issue by davglass** [mastodon/mastodon#20885]
### Steps to reproduce the problem

1. From Home, Click `#Explore`
2. Then click on each tab
...

https://user-images.githubusercontent.com/32551/202221507-aca6b20d-9219-4d2e-84c0-cb9b0a4e54be.mov

### Expected behaviour

The tabs should remain visible when clicking the other tabs

### Actual behaviour

The tabs seem to disappear when clicked

### Detailed description

Added video to show what happened.

### Specifications

Mastodon 4.0.2

**Comment by ineffyble** [comment]
@davglass What device and browser are you using?
