### ISSUE TITLE
Users on a List that are Unfollowed cannot be removed from the List

### ISSUE THREAD

**Issue by jcbeck37** [mastodon/mastodon#20883]
### Steps to reproduce the problem

1. Follow a user
2. Add that user to a list
3. Unfollow the user

### Expected behaviour

The user should be removed from the list OR you should be able to remove them

### Actual behaviour

1. The user's posts and boosts continue to be added to your List.
2. The unfollowed user remains in your Lists (though invisibly)
3. There is no way to remove them. On their profile, "Add or Remove from lists" is not present. On List -> Edit, the unfollowed users are not shown.

### Detailed description

Additionally, re-following does not give you the ability to then remove them from the List, and they still do not show up in List -> Edit, or marked as in a List from "Add or Remove from lists"

### Specifications

Mastodon 4.0.2
Firefox 106.0.5

**Comment by ClearlyClaire** [comment]
If you reload, are they still a member of the list? That should not happen. It is possible, though, that the UI does not accurately update known members of a list on unfollow.

Also note that *posts* don't get retroactively added to or removed from a list.

**Comment by jcbeck37** [comment]
They do not appear on lists. But I will have to test some more. As you said, posts/boosts don't get retroactively removed from a list. I don't have any records of exactly when I unfollowed the users, but I unfollowed most yesterday, and it seems like posts as recent as an hour ago are showing on my lists. I will have to do a more controlled test to be certain.

**Comment by jcbeck37** [comment]
OK - I believe this is just my brain being confused by seeing the dozens of posts/boosts by someone I unfollowed ~22 hours ago, but realizing now that they have more recent posts. Closing this - sorry!
