### ISSUE TITLE
About page hard to read in advanced mode, lacks Back button

### ISSUE THREAD

**Issue by eishiya** [mastodon/mastodon#20890]
### Steps to reproduce the problem

1. Enable advanced web interface
2. Navigate to your instance's About page

### Expected behaviour

I should be able to press Back to return like on other pages, and I should be able to read the full contents of the About page

### Actual behaviour

There is no Back button, the text is cramped, and server moderation reasons are not fully visible

### Detailed description

The About page contains a *lot* of useful information, especially on instances with extensive lists of rules. It used to open as a separate page and used to be easy to read, but as of Mastodon 4, it opens as a column in the advanced interface. I have my columns wider than normal via custom CSS and reading my instance's about page still feels bad. Narrow columns are fine for short toots, but not for a lengthy document that contains numerous lists.

Server moderation reasons are cut off and neither clicking nor hovering lets you see the full reason, the only way is to view the code of the page, which does contain the full text. Example:
![image](https://user-images.githubusercontent.com/70545646/202254053-a5e79651-a564-4f26-bb3e-12b23fb28b6d.png)
The "Reason not available" text also adds visual clutter, I think this placeholder should be shown at a lower opacity than actual reasons, or not displayed at all.

The old about/more page had explanations of what these different limits mean, and had clearer visual grouping for these different categories. The new about page doesn't have this information anywhere, and while the instances appear to be sorted by moderation type, there's no visual separation at all, so instances that are merely limited are visually lumped together with suspended instances.

In addition, it's difficult to search the about page (e.g. to refer to a particular rule or check if a particular instance of blocked) because the page is displayed alongside other columns, which also get searched.

I think that, like Settings, the content of this page justifies it having its own separate page and not just a column, at least in the advanced web interface.

On a somewhat related note: this whole page appears to be served dynamically now, and feels laggier than before. I like that I can collapse sections now, but if I close and reopen a section, it seems to re-fetch the entire content from the server, causing a delay during which a placeholder is shown. I think the whole page should be fetched once, and collapsing/expanding should be handled by the browser.

### Specifications

Mastodon 4.0.2

Firefox 105.0.3 (64-bit)
Windows 10 x64

**Comment by Phroneris** [comment]
Agreed!

But, some points such as the "Reason not available" thing and the collapsing/expanding content thing can be separated to each single issue, I think.
Currently there are a bit too many points in one issue.

**Comment by eishiya** [comment]
There is still one portion of this issue that hasn't been fixed: The reason on moderated servers is still truncated without any way to view the full reason short of looking at the raw HTML, even in the wider view. Is there another issue for this, or should I perhaps retool this one to be about that specific problem?

**Comment by mjankowski** [comment]
I'd say search the issues to see if it exists already, and if not make one (but leave this closed). Link back here if/when you do.
