### ISSUE TITLE
Update documentation needs additional clarity

### ISSUE THREAD

**Issue by JetForMe** [mastodon/mastodon#20909]
### Pitch

I would have asked about this on the Discourse, but new registrations are not allowed.

I'm upgrading from 3.5.3 to 4.0.2, and going through the 4.0.0 update [notes](https://github.com/mastodon/mastodon/releases/tag/v4.0.0). One step is "restart all Mastodon processes," but I have no idea which processes that refers to, or really how they were started (I built my server using the DigitalOcean image).

I've poked around the Mastodon docs looking for something that talks about starting and stopping the server, but haven't really found anything.

### Motivation

Everyone who's new to running a server.

**Comment by trwnh** [comment]
https://docs.joinmastodon.org/admin/upgrading/ ?

**Comment by randommouse** [comment]
`systemctl restart mastodon-web mastodon-sidekiq mastodon-streaming`

**Comment by randommouse** [comment]
> ### Pitch
> 
> I would have asked about this on the Discourse, but new registrations are not allowed.
> 
> I'm upgrading from 3.5.3 to 4.0.2, and going through the 4.0.0 update [notes](https://github.com/mastodon/mastodon/releases/tag/v4.0.0). One step is "restart all Mastodon processes," but I have no idea which processes that refers to, or really how they were started (I built my server using the DigitalOcean image).
> 
> I've poked around the Mastodon docs looking for something that talks about starting and stopping the server, but haven't really found anything.
> ### Motivation
> 
> Everyone who's new to running a server.

If you follow the installation instructions in the docs you will see near the end where the 3 services are enabled. Those are the services that you will restart. See my other comment for easy mode.
