### ISSUE TITLE
Punycode-Domain is displayed raw since update to version 4.0.2

### ISSUE THREAD

**Issue by Athesis** [mastodon/mastodon#20906]
### Steps to reproduce the problem

Use a Punycode-Domain

### Expected behaviour

Show human readable domain (for example ratatöskr.de)

### Actual behaviour

Shows Raw Punycode (for example xn--ratatskr-r4a.de)

### Detailed description

When using a Punycode Domain (For example, my Server https://www.ratatöskr.de) everywhere the domain is written in raw punycode (xn--ratatskr-r4a.de) instead of the human-readable domain (ratatöskr.de). Version 3.5.3 was handling it for most written domains correctly. 

### Specifications

Mastodon 4.0.2
Ruby 3.0.4

**Comment by ineffyble** [comment]
Probably same root cause as #20422. Are you able to test if you have the same issue with usernames and follows?

**Comment by Athesis** [comment]
No, mentions are working fine.

**Comment by qwell** [comment]
FWIW, [this is what a post from a punycode instance looks like](https://i.imgur.com/6YV9yn9.png), with a bunch of different links and tags.  All links and tags were input correctly, with links including https://.  This image is from the viewpoint of a remote user, but it's basically the same for the local user after sending.

Links 1 and 2 were entered as punycode domains - the results are not links.  Links 3 and 4 were entered as their decoded (xn--8r9a) form.
User 1 was a local tag with no domain.  User 2 was a full tag with punycode domain - the result is not a link.  User 3 was a full tag in decoded form.  User 4 is a full tag to a remote user.
