### ISSUE TITLE
'Invite mode' missing in v4

### ISSUE THREAD

**Issue by trendless** [mastodon/mastodon#20919]
### Steps to reproduce the problem

Adjust which level of user account can create invites: all users, moderators, admin only
...

### Expected behaviour

Dropdown list with options in 'Moderation > Invites'

### Actual behaviour

Dropdown list is missing from UI

### Detailed description

in 3.5.3, the ability to change the invite mode was present. In 4.0.3 it appears to be missing.

### Specifications

Mastodon 4.0.3

**Comment by trendless** [comment]
Thanks!!

**Comment by ThisIsMissEm** [comment]
@vmstan I believe this can be closed?
