### ISSUE TITLE
Mastodon just straight up doesn't work

### ISSUE THREAD

**Issue by TheJavaHacker** [mastodon/mastodon#20910]
### Steps to reproduce the problem

1. Follow the documentation on the website on Ubuntu 20.04.
2. Add IPv6 support to Ubuntu.
3. Add IPv6 address to nginx.
4. Put IPv6 behind cloudflare, as an AAAA record.
5.  Start the services, all appears okay
6. Go to domain in Browser, 524, then 502
7. Everything is broken.

### Expected behaviour

I should now be able to access Mastodon.

### Actual behaviour

I cannot Access Mastodon.

### Detailed description

Honestly I'm not going to lie, I've been stuck here for days trying to figure this whole thing out.
All I am stuck on is why I keep getting 502 errors. Cloudflare says it's nginx. nginx blames the mastodon software. Mastodon is blaming ruby.

This is my latest:
 `journalctl -xe -u mastodon-web.service
Nov 17 00:02:39 B519C48 bundle[364728]:         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/bin/puma:25:in `<top (required)>'
Nov 17 00:02:39 B519C48 bundle[364728]:         from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `load'
Nov 17 00:02:39 B519C48 bundle[364728]:         from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `kernel_load'
Nov 17 00:02:39 B519C48 bundle[364728]:         from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:23:in `run'
Nov 17 00:02:39 B519C48 bundle[364728]:         from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/cli.rb:486:in `exec'
Nov 17 00:02:39 B519C48 bundle[364728]:         from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
Nov 17 00:02:39 B519C48 bundle[364728]:         from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
Nov 17 00:02:39 B519C48 bundle[364728]:         from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
Nov 17 00:02:39 B519C48 bundle[364728]:         from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/cli.rb:31:in `dispatch'
Nov 17 00:02:39 B519C48 bundle[364728]:         from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
Nov 17 00:02:39 B519C48 bundle[364728]:         from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/cli.rb:25:in `start'
Nov 17 00:02:39 B519C48 bundle[364728]:         from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/exe/bundle:48:in `block in <top (required)>'
Nov 17 00:02:39 B519C48 bundle[364728]:         from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
Nov 17 00:02:39 B519C48 bundle[364728]:         from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/exe/bundle:36:in `<top (required)>'
Nov 17 00:02:39 B519C48 bundle[364728]:         from /home/mastodon/.rbenv/versions/3.0.3/bin/bundle:23:in `load'
Nov 17 00:02:39 B519C48 bundle[364728]:         from /home/mastodon/.rbenv/versions/3.0.3/bin/bundle:23:in `<main>'
Nov 17 00:02:39 B519C48 systemd[1]: mastodon-web.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited`

Any help is appreciated at this point. Cheers.

### Specifications

Mastodon from commit: f890fdc, I assume 4.0.2
Ruby 3.0.3
rbenv 3.0.3

**Comment by TheJavaHacker** [comment]
Closed because I'm a dumbass.

**Comment by jon6fingrs** [comment]
im a dumbass too. can you tell me how you fixed it?
