### ISSUE TITLE
Can't sign up to custom instance

### ISSUE THREAD

**Issue by ChildishGiant** [mastodon/mastodon#20928]
### Steps to reproduce the problem

try to sign up to a custom instance 

### Expected behaviour

I should be directed to the server's sign up

### Actual behaviour

I get sent to joinmastodon.org/servers 

### Detailed description

this then doesn't have my custom instance on. 

### Specifications

v4.0.2

**Comment by rbairwell** [comment]
Can you provide an example of an instance which does this? I can't say I've seen this myself (and I often go to the frontpage and about pages of "new instances" just to check them out): I suspect this might be an admin setting specifically set on that instance.

**Comment by Gargron** [comment]
It sounds like your custom server is not accepting new users.

**Comment by ChildishGiant** [comment]
Yep, that's it!
