### ISSUE TITLE
Remove "Share {user}'s profile"

### ISSUE THREAD

**Issue by eai04191** [mastodon/mastodon#20931]
### Pitch

When you open your profile in Mastodon's web UI, there is a ["Share {user}'s profile"](https://github.com/mastodon/mastodon/blob/7fdeed5fbca1b6b761029870f02a3f812288f0aa/app/javascript/mastodon/features/account/components/header.js#L219) item in the menu. Has anyone ever used this?

![image](https://user-images.githubusercontent.com/3516343/202415542-8ceebd07-7d3c-498b-bf94-92d02aba8e8b.png)

Probably no one has used it.

From what I've researched, this was added in the #10337. And it hasn't worked since then. This is because the action `this.handleShare` does not exist.

I've investigated further and looked for any issues that mention this, but haven't found any. This means that in the 3+ years since this feature was added, no one has had a problem with it not working.
(I think one of the reasons is that it doesn't display in Firefox, which is the preferred browser for open source people.)

It's easy to fix this not working, but what you really want is to remove this functionality.

### Motivation

No need to maintain features that no one uses. Removing features reduces the code developers (and translators) need to read.

**Comment by eai04191** [comment]
Fun fact, in the 4.0 UI, when you open your profile while not logged in, only this non-functional item appears in the menu.

![image](https://user-images.githubusercontent.com/3516343/202412446-08e70605-6ed5-4c31-b9e2-40f8e4c5a824.png)

**Comment by afontenot** [comment]
Interesting, in 4.0.2 on mastodon.social, I don't see this link anywhere I've looked. When logged out, the button is disabled and can't be clicked. See https://mastodon.social/@Gargron

**Comment by eai04191** [comment]
Your browser must support [`navigator.share`](https://caniuse.com/?search=navigator.share) for this item to appear.
Firefox doesn't have any support for this, so it doesn't add items to the menu (resulting in a state where the menu can't be opened because there are no menu items).

- Chrome on Windows
- Safari on macOS
- Edge on any OS

I have verified that they appear when I use these.
