### ISSUE TITLE
User retention average is wrongly calculated

### ISSUE THREAD

**Issue by Art4** [mastodon/mastodon#20938]
### Steps to reproduce the problem

1. I have an instance where no new users has been registered in the last 3 month
2. Now I'm looking an the user retention in the admin interface
3. At the first line there is the average of the user retention
...

### Expected behaviour

The average should only be calculated using the months with new user registrations.

### Actual behaviour

The average is calculated from all months, even if there where no new user registrations.

### Detailed description

This is the retention in my admin interface right now:

![grafik](https://user-images.githubusercontent.com/2162994/202444221-504d3439-da5a-4514-9c00-700b4d085ec7.png)

As you can see the average for 1 month shows 39%. It is calculated from last 6 month and devided by 6. The same goes for month 2 (devided by 5) and month 3 (devided by 4):

```
average_1 = (70 + 67 + 100 + 0 + 0 + 0) / 6
// average_1 =~ 39%

average_2 = (60 + 67 + 100 + 0 + 0) / 5
// average_2 =~ 45%

average_3 = (60 + 67 + 100 + 0) / 4
// average_3 =~ 57%
```

Looking at this average numbers it makes no sence for me that the average is lower than the numbers in the month with new user registrations. I don't understand why having no new user registration in one month reduces the average user retention.

### Proposal

I would suggest that the month without new users should be ignored in the average calculation. It would then look like this:

![grafik](https://user-images.githubusercontent.com/2162994/202444364-3baab9a2-37d9-4006-b256-57225565265c.png)

The average would be calculated like this:

```
average_1 = (70 + 67 + 100) / 3
// average_1 =~ 79%

average_2 = (60 + 67 + 100) / 3
// average_2 =~ 76%

average_3 = (60 + 67 + 100) / 3
// average_3 =~ 76%
```

### Specifications

Mastodon 4.0.2

**Comment by vmstan** [comment]
Is this an issue for you in newer versions of Mastodon @Art4
