### ISSUE TITLE
RSS Auto-discovery

### ISSUE THREAD

**Issue by kidehen** [mastodon/mastodon#20959]
### Steps to reproduce the problem

I cannot use an RSS reader to subscribe to RSS feed links embedded in Mastodon Profile Pages. 

Reproduction steps.
1. Visit a profile page of interest e.g., https://mastodon.social/@kidehen
2. Copy profile page URL to your host operating systems (OS) clipboard
3. Start an RSS reader app or visit a hosted RSS Readers homepage
4. Paste in the profile page URL from the OS clipboard

RSS Reader will report an error since it cannot an RSS feed URL.

**Comment by Aesthetikx** [comment]
Possibly already addressed by https://github.com/mastodon/mastodon/pull/20772

**Comment by ClearlyClaire** [comment]
Addressed by #20772 indeed
