### ISSUE TITLE
Increase the 500 character post limit

### ISSUE THREAD

**Issue by KRRW** [mastodon/mastodon#20980]
### Pitch

Users should be able to post longer status instead of forcing them to use threading.

### Motivation

People often argue that mastodon is not twitter, and maybe mastodon should not try to be twitter and stop forcing people to use threads and limiting users to short statuses.

**Comment by person1234-ux** [comment]
I agree but I do think the admin of an instance should be able to limit the size of a posts. The reason for this is that long post take up more space and if your paying for an instance you should be able to do what is necessary to bring down the cost.

**Comment by afontenot** [comment]
This sort of thing *already is* instance specific. Some instances have a 1000 character limit for example. The underlying protocol (ActivityPub) doesn't care either way. Vanilla Mastodon has long been standardized on a 500 character limit, and I don't think many people want to see that changed, but it already is up to you whether you join an instance with that limit or not.

**Comment by nightpool** [comment]
Thanks for the suggestion, we're not planning on changing the character limit at this time but we'll be sure to revisit this thread in the future if that changes.

**Comment by adulau** [comment]
Make it configurable would be the best approach? A lot of the mastodon fork allows to do it and people to use the fork which are less maintained and prone to unpatched security issues.

**Comment by Your-New-SJW-Waifu** [comment]
> Make it configurable would be the best approach? A lot of the mastodon fork allows to do it and people to use the fork which are less maintained and prone to unpatched security issues.

That's not going to happen. A pull request for this has already been submitted and turned down.
#5697

**Comment by Your-New-SJW-Waifu** [comment]
> @Your-New-SJW-Waifu any idea why they refuse to make this an option?
> 
> It's trivial to replace the character limit by modifying source code... there are like 50 blog posts about how to do this, in fact.. I don't get why less tech-savvy admins are the only ones locked out of having control over their instance's message lengths.

It's in that thread but basically Gargron says it's against his vision for mastodon. He wants servers differentiated by communities not features. He doesn't want features like higher character limit, larger uploads, theoretical optional features, etc. to play a role in people's decision on which server to join. 

This is why I migrated to Pleroma. It's highly customisable and really easy to hack on. It also has much better moderation tools and more features.
