### ISSUE TITLE
No confirmation email for aus.social

### ISSUE THREAD

**Issue by nicsommer** [mastodon/mastodon#21003]
### Steps to reproduce the problem

I tried to create a new account in aus.social on Mastodon - online. 
I have signed up to aus.social
I have not received a confirmation email
When I try and resend the confirmation email, I again don't receive it. I have been trying at various points over for 48 hours
I have checked my junk folder in my email account

### Expected behaviour

Received confirmation email to set up account on aus.social

### Actual behaviour

No email received 

### Detailed description

I signed up for aus.social with a non-gmail account. I haven't received the confirmation email. I have tried over two days to re-send, and I've checked my junk. 

I can't see that I'm doing anything wrong, please help!

![image](https://user-images.githubusercontent.com/118535184/202702367-75341770-5c87-47dc-beb3-1bbbc77a24c2.png)

### Specifications

Mastodon in Edge, and Android app

**Comment by SebastianBerlin** [comment]
Please contact the admins of _aus.social_ (→ https://aus.social/about). That's here no support-board for that instance. Thanks!
