### ISSUE TITLE
Server domain block api (/api/v1/admin/domain_blocks) GET method should allow anonymous access if the server publishes its list of blocks anyway

### ISSUE THREAD

**Issue by SteveDinn** [mastodon/mastodon#21017]
### Pitch

It's helpful to be able to share lists of blocked servers as well as *why* they're blocked. A good start for a new server (and there are many of those now) is to mirror another, more established (and trusted) server's list of blocked servers.

Rather than requiring an account on another server and an admin-level access token, if that server is already publishing the list of blocked servers on the site (e.g., https://mastodon.social/about), then it would make sense to publish the list in a consumable way. Making `GET /api/v1/admin/domain_blocks` public would accomplish this.

Mirroring blocked server lists could be as simple as this (in PowerShell):
```
$trustedServer = "mastodon.social"
$myServer = "myserver.example.social"
$myServerAuthToken = "asdfasdf_admin_token"

(Invoke-WebRequest -Uri "https://$trustedServer/api/v1/admin/domain_blocks" -Method "GET").Content |
    ConvertFrom-Json |
    Foreach-Object {
        $_.private_comment = "Mirrored from $trustedServer"
        Invoke-WebRequest `
            -Uri "https://$myServer/api/v1/admin/domain_blocks" `
            -Method "POST" `
            -Headers @{ Authorization = "Bearer: $myServerAuthToken" } `
            -ContentType "application/json" `
            -Body $($_ | ConvertTo-Json)
    }
```

### Motivation

There are so many new servers popping up all over right now. Most of them started by those that want to leave the bird site for a better alternative -- free from posts that most servers block. This would be a huge step in getting those new servers ramped up to speed. And then, once they get on their feet, server admins can decide whether or not to continue blocking any particular servers based on the reasons they were blocked in the first place. This would just provide a good starting point.

**Comment by ClearlyClaire** [comment]
There is already a public endpoint for that information (when available): `/api/v1/instance/domain_blocks`

**Comment by SteveDinn** [comment]
The only issue is that the `/instance/` version of the API returns obfuscated domain names, which are useless for mirroring.

**Comment by ClearlyClaire** [comment]
Well, if they are obfuscated, it's because the admin does not want to advertise them in any way, so it doesn't seem right to expose them through another API either.
