### ISSUE TITLE
Clicking on Hashtags in User Profile Reloads Interface in Advanced Web Interface

### ISSUE THREAD

**Issue by mtwb47** [mastodon/mastodon#21016]
### Steps to reproduce the problem

1. Click on User's Profile (It opens up in another pane)
2. If the user has included hashtags in their bio, click on it
3. It reloads the entire Advanced Web Interface instead of just opening the hashtag in a new panel.
...

### Expected behaviour

A new panel should open with the hashtag. 

### Actual behavior

It reloads the entire UI (as in it refreshes the page). It also happens when you click the back link on a panel that was opened in this manner.

### Detailed description

When you open a person's profile in the advanced web interface, it opens in the last panel, as it should.  If that user has hashtags in their bio, and you click on one of those hashtags, it reloads the entire interface, almost as if the page was refreshed.

This behavior also happens when you click the back button on a panel that was opened up after clicking on one of those hashtags. 

This behavior does not happen when you click on hashtags in other parts of the UI. 

Video of the issue here. https://imgur.com/a/K2K8JzW  (would upload to GitHub, but the file is too large)

### Specifications

Mastodon 4.0.2 on Fosstodon.org
Using Firefox Web browser., version 107 on Fedora 36.

**Comment by vmstan** [comment]
@mtwb47 does this behavior persist in newer versions of Mastodon?

**Comment by mtwb47** [comment]
It appears to be fixed.
