### ISSUE TITLE
"Installing from source" ends in loop of HTTP 301 - Moved Permanently

### ISSUE THREAD

**Issue by interN3rd** [mastodon/mastodon#21032]
### Steps to reproduce the problem

1. Visit https://docs.joinmastodon.org/admin/install/
2. Follow each and every installation step using defaults
3. Visit <yourdomain.com> where Mastodon is supposed to run
4. Get redirected infinite times
...

### Expected behaviour

At this point I should be able to visit my domain in the browser and see the elephant hitting the computer screen error page.

### Actual behaviour

I am able to visit my domain, but I don't see the elephant hitting the computer screen error page.

### Detailed description

I'm almost certain this is a layer-8 problem. I'm doing something stupid here, but I am stuck as hell and can't figure out the mistake I do by myself.

I run a VPS with Ubuntu 20.04 on it. Everything runs smooth during the installation steps, but as soon as nginx is involved, nothing is working how it's supposed to.

### Specifications

Mastodon latest and everything that is provided in the official installation guide

**Comment by fgbreel** [comment]
Try to `$ curl -I <yourdomain.com>` and check for the `Location` header.

It might the that you are accessing it via `http` and being redirected to `https`.
It can also be that your domain is pointing to something else.

But is hard to know for sure without more information.

Also good to check if this question has been already answered or not at https://github.com/mastodon/mastodon/discussions

**Comment by interN3rd** [comment]
Thank you for your quick response. When running `$ curl -I <yourdomain.com>`, it returns the following:

```
    HTTP/1.1 301 Moved Permanently
    Server: nginx/1.18.0 (Ubuntu)
    Date: Fri, 18 Nov 2022 18:16:28 GMT
    Content-Type: text/html
    Content-Length: 178
    Connection: keep-alive
   Location: https://<yourdomain.com>/ 
```
But this is (at least one time) expected behavior. I configered the `certbot` to redirect from http to https and it added the following to my `/etc/nginx/sites-available/mastadon` config file:

```
server {
    if ($host = <yourdomain.com>) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


  listen 80;
  listen [::]:80;
  server_name lllsecurity.com;
    return 404; # managed by Certbot


}
```
That's why I would expect a maximum of one redirect, but I get all of them.

**Comment by interN3rd** [comment]
Okay, I updated nginx to the newest version `1.23.2`, because version `1.18.0` seems a little old to me. And when I visit https://<yourdomain.com> now, I get to see a "Welcome to nginx!" page. The default nginx page, which doesn't even make sense to me, because there is only `mastodon` under `/etc/nginx/sites-enabled` and `/etc/nginx/sites-available`. I deleted the defaults. Where does it come from?

**Comment by afontenot** [comment]
I believe @fgbreel was suggesting you try `curl -I https://yourdomain.com` in order to see if you could tell what was causing the looping behavior. 

Maybe you could provide your nginx config as an attachment. If you didn't reboot the VPS after upgrading nginx (how did you do that - Ubuntu backports repository? building it yourself?) I would try that.

**Comment by interN3rd** [comment]
Aye, here's the output after performing `curl -I https://yourdomain.com`:

`curl: (7) Failed to connect to lllsecurity.com port 443: Connection refused`

This now looks like a firewall issue to me, then. Here's my `/etc/iptables/rules.v4`:

```
*filter

#  Allow all loopback (lo0) traffic and drop all traffic to 127/8 that doesn't use lo0
-A INPUT -i lo -j ACCEPT
-A INPUT ! -i lo -d 127.0.0.0/8 -j REJECT

#  Accept all established inbound connections
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

#  Allow all outbound traffic - you can modify this to only allow certain traffic
-A OUTPUT -j ACCEPT

#  Allow HTTP and HTTPS connections from anywhere (the normal ports for websites and SSL).
-A INPUT -p tcp --dport 80 -j ACCEPT
-A INPUT -p tcp --dport 443 -j ACCEPT

#  Allow SSH connections
#  The -dport number should be the same port number you set in sshd_config
-A INPUT -p tcp -m state --state NEW --dport 22 -j ACCEPT

# Allow Teamspeak-3-Server
-A INPUT -p udp --dport 9987 -j ACCEPT

#  Allow ping
-A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT

#  Log iptables denied calls
-A INPUT -m limit --limit 5/min -j LOG --log-prefix "iptables denied: " --log-level 7

#  Reject all other inbound - default deny unless explicitly allowed policy
-A INPUT -j REJECT
-A FORWARD -j REJECT

COMMIT
```

I copied it from https://docs.joinmastodon.org/admin/prerequisites/ and only added an entry for port 9987, because there's also a TeamSpeak 3 server. But maybe this is not related to iptables rules, since only the default config is loaded and there's nothing about https or ssl or port 443 in it.

Please see attached a file named `default_conf.txt`. It's the config from `/etc/nginx.d/` that seems to be used by nginx. 

And please also see attached a file named `mastodon.txt`. This is the config from `/etc/nginx/sites-enabled`. There is only the mastodon configuration file in there and this is the one I expect to be loaded, but it doesn't apparently.

[mastodon.txt](https://github.com/mastodon/mastodon/files/10046395/mastodon.txt)

[default_conf.txt](https://github.com/mastodon/mastodon/files/10046391/default_conf.txt)

**Comment by afontenot** [comment]
Among other possible problems, it seems likely that when you upgraded nginx you ended up adding an nginx config file (`/etc/nginx/nginx.conf`) that contains a line like `include /etc/nginx/conf.d/*.conf;`. This statement will include config files like `/etc/nginx/conf.d/default.conf`, which is present in the official nginx packages and might be the explanation for what you're seeing.

**Comment by interN3rd** [comment]
YES! Disabling the reference to `*.conf` and including `sites-enabled` did it. Thank you! You just saved my weekend, because it got so frustrating yesterday :D
