### ISSUE TITLE
Changing @handle from/to uppercase/lowercase should be possible without moving to a different account

### ISSUE THREAD

**Issue by tibor** [mastodon/mastodon#21051]
### Pitch

Users should be able to change @\handle to @\Handle or @\HaNdLe without having to move to another account

### Motivation

It’s just a simple text transformation which doesn’t need a complex solution like at the moment. Also, URLs are case insensitive at the moment already, so that content shouldn’t break.

**Comment by zeborah** [comment]
Looks like a duplicate of #20487
