### ISSUE TITLE
List of followed accounts does not transfer from old to new server; bugs in iOS client to re-follow

### ISSUE THREAD

**Issue by alansill** [mastodon/mastodon#21072]
### Steps to reproduce the problem

1. Create accont on new Mastodon server
2. Set up alias from new server to old and initiate account move from old to new server.
3. List of followers correctly populates on new server
4. List of follows by account on new server remains 0
5. Individually going through followers to decide who to follow works for some accounts but not others - clicking follow just flashes "following" and reverts back to "follow" on the rest. These cases appear to be those in which the perrson has also moved their account to a new server. 

### Expected behaviour

Both follower and followed account lists should be moved to the new server

### Actual behaviour

List of followers seems to transfer correctly, but list of followed accounts does not. 

### Detailed description

Moving an account from one Mastodon server to another should transfer both the followed acocunts and the follower accounts lists. The followed account list seems not to populate at all, even hours after initiating the account move. The list of followers seemsw to transfer corrrectly, but attempts to use that to partially rebuild a list of followed accounts seem to be only partially successful and clicking "follow" on some after the first 10 or so does not seem to work on the iOS client. (Re-following does seem to work through the web app, and the cases where it didnʻt work on the iOS one.) Even the approach above is a poor substitute for a correct transfer of the list of people you used to be following as it seems to be limited to trying to pick people out of your follower list to re-follow, and there seem to be bugs even there.

### Specifications

SERVER SOFTWARE

Mastodon	4.0.2
Ruby	3.0.4p208
PostgreSQL	13.8
Redis	6.0.16

CLIENT SOFTWARE
Mastodon for iOS v1.4.5 (144)

**Comment by ClearlyClaire** [comment]
As the migration screen explains, follows are not migrated, only your followers. You can export the list of people you follow and re-import that list on your new account, though.

**Comment by eishiya** [comment]
> As the migration screen explains, follows are not migrated, only your followers. You can export the list of people you follow and re-import that list on your new account, though.

Pardon my bumping this closed issue, but is there a reason for this? I looked around for explanations but the only mention I found was in the original issue about implementing account migration, where migrating follows was stated to be the easy part, and *followers* were meant to be the hard part. Was this done just to avoid duplicating the functionality of the existing export and import options, or is there some other reason?

**Comment by ClearlyClaire** [comment]
Migrating people you follow requires the new account to send follow requests anyway, so a mechanism would be required to share the list of followed people from the old server to the new server. This would have required another protocol extension, while we already had the import/export feature.
