### ISSUE TITLE
Filters don't work on explore

### ISSUE THREAD

**Issue by Elsensee** [mastodon/mastodon#21083]
### Steps to reproduce the problem

1. Set up a filter for a word (exact match)
2. Activate the filter on at least public timelines
3. Open the explore page where posts that gain traction on the fediverse are displayed (you know, /explore)

### Expected behaviour

Posts containing the words in your filters will be filtered. Either by hiding behind a warning or by hiding completely.

### Actual behaviour

Nothing happens. Every posts is still displayed.

### Specifications

Mastodon 4.0.2

**Comment by amyers735** [comment]
Also have noticed that users who you have blocked can still appear in the explore -> posts area as well

**Comment by Hyperlynx2** [comment]
Kind of amazed this doesn't work. It makes explore pretty unusable.

Completely defeats the purpose of filters, which are for filtering out topics that are popular but you don't want to read about!

**Comment by FediVideos** [comment]
Just had a user ask about this bug, might be good to fix it?

**Comment by githubusernameiscolby** [comment]
Thank you.

**Comment by githubusernameiscolby** [comment]
Thanks for reporting this bug. It’s been driving me crazy. How can they claim filters are the solution to controlling what content you see when they don’t work!?!

**Comment by JasonHein** [comment]
This bug annoys me a lot as well.

**Comment by zchilds** [comment]
Super annoying bug. Works fine on third party apps like Ice Cubes or Elk but not on the main site.

**Comment by supernovae** [comment]
Raised up by multiple users on my system as well.

**Comment by EttaK** [comment]
Any news on a fix? I'm using Mastodon thru Chrome on my desktop, and none of the filters I've set up are working :(

**Comment by zchilds** [comment]
@EttaK the workaround that I've found in the meantime is to use an alternate client like Elk. https://elk.zone/

Filters work properly there.

**Comment by zsolt-szabo** [comment]
Another user calling this bug out.

**Comment by N00BM4573R** [comment]
This hasn't been fixed...

**Comment by gardner** [comment]
This is kind of a deal breaker for me as a user. My explore page is filled with people that hate either the current US president or the previous Us president. 

I don’t live in the USA and I don’t want to read a bunch of polarised toxic hate messages. 

Help!

**Comment by carsonwhitley** [comment]
Would also love if this could be fixed.

**Comment by GrtFS** [comment]
Just waaaayyyy too many #Cats in #Explore

**Comment by dugite-code** [comment]
FYI this is fixed now: https://github.com/mastodon/mastodon/pull/25887 and is in the v4.2.0 beta1 https://github.com/mastodon/mastodon/pull/26339 I can confirm this is working as expected on mastodon.social
