### ISSUE TITLE
Mastadon confused by me emial

### ISSUE THREAD

**Issue by C-Puff** [mastodon/mastodon#21088]
### Steps to reproduce the problem

Mastadon confused in both my account creation and next day log in regarding my email.

### Expected behaviour

Create an account

### Actual behaviour

Completely confused by my email

### Detailed description

I made a Mastadon account yesterday for obvious reasons.
When I just tried to make an account, it told me my yahoo email was not a valid email account (it ends in .ca so I'm not sure if that's why it's confused). I instead tried to use my gmail and it accepted it, but then sent the verification code to my yahoo account. So I figured maybe my yahoo account went through after all.
Today I am trying to sign into Mastadon again and it's not accepting either my yahoo or gmail as a valid email.

### Specifications

Firefox 105.0.3

**Comment by fviz** [comment]
This could be an isolated issue to the server you are using. Have you tried making an account on a different server, and if so, do you get the same behavior?

**Comment by C-Puff** [comment]
Ah! That was the issue thank you so much. I was trying to log in on a different server without realising it. I wasn't aware that the log in page would be server specific.
Thank you so much! I opened the tab I used yesterday, logged out, then logged back in without problems. 👍

**Comment by chipbite** [comment]
@C-Puff please comment and close this issue, if it was resolved as you wrote.
You as creator can close it (I think - that is the way it most commonly works)
