### ISSUE TITLE
Feature request: adding accounts to lists without following them

### ISSUE THREAD

**Issue by novoid** [mastodon/mastodon#21092]
### Pitch

My Mastodon web timeline should not be filled with messages from accounts which are "only" part of a Mastodon list of mine. Therefore, it'd be cool if we could _optionally_ add accounts to lists without actually following them.

### Motivation

Mastodon gained much momentum lately, which is great. However, it asks for more and more features to handle higher volumes or follower numbers.

One possible improvement is that I, e.g., add high-volume accounts to a "high-volume personal list" similar to hashtag columns that show me messages related to that hashtag without a follower-relationship to its accounts. I can think of many different use-cases for that feature.

**Comment by slasherfun** [comment]
Seems like a duplicate of #6982 to me :)

**Comment by novoid** [comment]
Yes, I don't know why I haven't found it while doing my search. Thanks for clarifying.
