### ISSUE TITLE
Domain block entry is broken in audit log

### ISSUE THREAD

**Issue by rixx** [mastodon/mastodon#21116]
### Steps to reproduce the problem

1. Block any domain
2. Update to Mastodon 4.0.x
3. Look at audit log: It says "<mod> blocked domain https://"
![2022-11-19T18:57:44+01:00](https://user-images.githubusercontent.com/2657547/202864894-4dfd7fea-5ab7-4ce8-9537-2ddbea16c17a.png)

...

### Expected behaviour

Show the actual domain that was blocked.

### Actual behaviour

Domain name is missing.

### Specifications

Mastodon v4.0.2

**Comment by ClearlyClaire** [comment]
Did you run the post-deployment migrations?

**Comment by rixx** [comment]
Yes, all migrations have run.

**Comment by prplecake** [comment]
I'm seeing this, too. On glitch-soc latest.

The last entry that's correct, as in shows the domain, is on August 28, 2022, which was months before 4.0 was released. glitch-soc@978dd7e73c911441503ff803ffdce544ce50a33d is probably the latest merge, if that helps, however CompostInTraining@64c86653aac6281cf5aa8357674c143337770840 was the live commit, which merged in several upstream-merges from glitch-soc... I hope that makes sense.

All of the domains still exist in the database, so I think it's just the audit log that's broken. I don't see any errors in the logs although the logs don't appear very verbose, and I'm not sure how to increase that in prod.

**Comment by mtippmann** [comment]
Can confirm this after updating to 4.0.2 from 3.5.5 - we also ran the post-deployment migrations.

**Comment by ClearlyClaire** [comment]
Just to be sure, those were pre-migration admin action logs, not new log entries?

**Comment by mtippmann** [comment]
> Just to be sure, those were pre-migration admin action logs, not new log entries?

yes. here everything pre-update was scrambled, post-update was fine. except https://github.com/mastodon/mastodon/issues/22041 but this is unrelated I think.

**Comment by ClearlyClaire** [comment]
ok, so it's what I attempted to address in the post-deployment migration in #19649

I'll review it, try to catch anything that might be wrong with it, and see how I can make it more robust.

**Comment by ClearlyClaire** [comment]
I have identified the issue. Unfortunately, my migration script basically did not work as expected. I fixed it in #22091, but keep in mind that pre-4.0 logs about deleted objects (posts, users, domain blocks) will still show up incorrectly, as the information has been irremediably lost in the migration introduced when changing how they are stored.

**Comment by prplecake** [comment]
I disagree that the information has been completely lost. A better crafted migration would fix the "human identifier" which appears to be the only data missing from the `admin_action_logs`. As far as I can tell, the `target_id` is the ID of the record in `domain_blocks`. Likewise, the `target_id` for account suspensions has a matching ID in `accounts`, so I think this could be fixed fairly easily?

<img width="756" alt="Screenshot 2022-12-06 at 05 44 42" src="https://user-images.githubusercontent.com/83595468/205903029-b385c76f-383c-4f27-bb89-d577a0e0c40c.png">

If I were better at writing migrations I would take this upon myself to fix.

**Comment by ClearlyClaire** [comment]
> I disagree that the information has been completely lost. A better crafted migration would fix the "human identifier" which appears to be the only data missing from the `admin_action_logs`. As far as I can tell, the `target_id` is the ID of the record in `domain_blocks`. Likewise, the `target_id` for account suspensions has a matching ID in `accounts`, so I think this could be fixed fairly easily?
> 
> <img alt="Screenshot 2022-12-06 at 05 44 42" width="756" src="https://user-images.githubusercontent.com/83595468/205903029-b385c76f-383c-4f27-bb89-d577a0e0c40c.png">
> 
> If I were better at writing migrations I would take this upon myself to fix.

It's what my migration does, but it will only work if the `DomainBlock` (or other record) still exists, which may not be the case if the block has been lifted.

**Comment by prplecake** [comment]
Fair point, but the first migration didn't do that. The second migration from a few days ago (#22091) did.

Thank you for your hard work Claire, I really appreciate it.

**Comment by ClearlyClaire** [comment]
> Fair point, but the first migration didn't do that. The second migration from a few days ago (#22091) did.
> 
> Thank you for your hard work Claire, I really appreciate it.

Yeah, the old migration meant to do that but it did not actually save anything to the database, sorry about that :weary:

**Comment by ThisIsMissEm** [comment]
@ClearlyClaire I think this can be closed as "fixed"?

**Comment by ClearlyClaire** [comment]
Closing as partially fixed (through the backfilling migration), cases that the backfilling migration cannot address cannot be addressed at all because the information is lost.
