### ISSUE TITLE
Local timeline not updating for one user

### ISSUE THREAD

**Issue by packetcat** [mastodon/mastodon#21120]
### Steps to reproduce the problem

1. View local timeline in web interface or client
2.
3.
...

### Expected behaviour

local timeline should update as posts come in

### Actual behaviour

local timeline does not update

### Detailed description

> Hey friends! I'm hoping someone has an idea on this: my local timeline is really sparse, rarely updates, and doesn't show my local instance posts.
> I've checked with my instance admin [@guinan](https://tenforward.social/@guinan) . On both mobile and desktop, we tried logging out, clearing the caches, and logging back in. It's also not a filter issue, I have very few in place.
> 
> My local timeline hasn't updated in 3 days, and it's never updated frequently on my end (maybe one post every 2-5 days?) In my short time here. Almost all of the folks from my instance (tenforward.social) don't appear there at all. 
> 
> Ideas please? Thank you in advance!

- https://tenforward.social/@tarasovich/109371130580463970

I have also tried a feeds rebuild for this user with tootctl along with a tootctl cache clear and a restart of all Mastodon server processes. Only this user's local timeline is affected, federated is working as expected.

### Specifications

Mastodon 4.0.2
Ruby 3.0.4

**Comment by splaGit** [comment]
One of my users is facing exactly the very same issue today. My server is running v4.0.2 and Ruby 3.0.4 too.

**Comment by mjankowski** [comment]
The original issue here is from an old version of mastodon, and subsequent commenter did figure out their issue.

Going to close on assumption that either there was an explanation for this, or it was resolved in newer version. Please reopen if its still relevant to a 4.3 install!
