### ISSUE TITLE
Custom emojis: shortcode not replaced by emoji

### ISSUE THREAD

**Issue by schousda** [mastodon/mastodon#21138]
### Steps to reproduce the problem

1. upload a new custom emoji
2. set shortcode to something like "myemoji12345"
3. type the shortcode :myemoji12345: in the textbox or select the custom emoji from the emoji box
4. the shortcode will not be replaced by the uploaded emoji

If you set the shortcode the same as for an existing emoji like "postal_horn", the shortcode will be replaced by the uploaded emoji.

![image](https://user-images.githubusercontent.com/21222928/202871769-a7b515a9-9db3-4cbd-89a2-8c0373ccf594.png)
![image](https://user-images.githubusercontent.com/21222928/202871793-e8376c7d-b71c-4c0f-b47a-1569722d82d4.png)

...

### Expected behaviour

shortcode gets replaced by emoji

### Actual behaviour

shortcode stays

### Specifications

Mastodon 4.0.2

**Comment by catgoat** [comment]
Something similar is happening on my instance as well... In the web inspector, I see it looking for a path that returns a 403. I don't see these paths in my S3 bucket on digital ocean. None of these are new emojis, though. It looks like it is missing part of the path you would expect with /000/123/41 etc, and instead has a double slash.
<img width="699" alt="image" src="https://user-images.githubusercontent.com/42517495/202877671-55cae9c4-a50c-4985-abe1-b8e6574b6979.png">

But in the admin interface they load from a different url, which exists and works:
<img width="678" alt="image" src="https://user-images.githubusercontent.com/42517495/202877755-9e475ce2-5283-4980-b31d-ee06513c1f98.png">

I am using glitch-soc but iirc there isn't a big difference in how emojis are handled between the fork and the upstream repo.
