### ISSUE TITLE
More visible website verification

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#21130]
### Pitch

If someone has verified their identity in connection with a website, there could be a "verified" icon in their display name like on Twitter.

Obviously that is very hazardous, because someone could put "Captain Kirk" in their display name, be called `@captainkirk@mastodon.social`, and connect their profile to *any website they've made* (e.g. `notevenreallycaptainkirkhaha.com`) and get the verified symbol in their display name, and people would see them and be like "oh I guess that really is Captain Kirk! Gosh, he was born earlier than I expected."

So in order for it to actually work, you'd need the verified symbol to show which website their account is verified with.

How about a little modal that pops up when you hover that shows you the URL, and the modal appears directly over the verified symbol, you can click it without moving your cursor, and the website opens in a new tab? Then you can see if this person is legit.

### Motivation

A bunch of Twitter people have been posting lately saying "there's a bunch of Mastodon accounts pretending to be me, and I just want to confirm that I have not joined Mastodon and those people are not me." But people are fools who don't go all the way to profiles to check if things are verified due to it being hard work, so a lot of them just won't question a legit-looking person in a timeline before boosting or similar.

Also, imagine if you've gone to the care of checking that a celebrity or journalist is verified before you start following them, you're 100% sure that they are who they say they are, and then someone else boosts an account that has the exact same username and profile pic that you see in your home feed every day - you're obviously going to assume it's the same person, but it might not be. (With a verification symbol in their display name that is still a risk, but at least you can just hover your cursor over the verification symbol in their display name and check the website URL before boosting, instead of going all the way to their profile.)

Online misinformation is so risky, and some really [big names](https://mastodonapp.uk/@stephenfry) and even some [companies](https://archive.ph/eNWZh) and [big name charities with large crowdfunders](https://mastodon.world/@goodlawproject) have been joining Mastodon lately. The social methods for verifying someone's identity haven't really settled yet so I wouldn't be surprised if this needs to change at some point, but this seems like something simple that could help in the mean time.

**Comment by nemobis** [comment]
Duplicates or supersedes https://github.com/mastodon/mastodon/issues/20869

**Comment by trwnh** [comment]
![image](https://github.com/mastodon/mastodon/assets/10606431/0fc5ffab-1b40-48d1-bdc6-a90966d48133)
