### ISSUE TITLE
Server config: awkward to get Mastodon running without SSL

### ISSUE THREAD

**Issue by trisweb** [mastodon/mastodon#21139]
### Pitch

I've set up Mastodon behind an nginx proxy, which handles SSL and all certificates for all services I run.

When trying to get mastodon working without SSL, just plain http, it took jumping through some hoops to do so.

Specifically, despite setting the env var `FORCE_HTTPS=false` in .env.production, SSL was still being forced and pages would not load under normal HTTP.

After some hunting, the specific line I needed to modify was in `production.rb`:

```diff
diff --git a/config/environments/production.rb b/config/environments/production.rb
index dc5319535..0c8e482d3 100644
--- a/config/environments/production.rb
+++ b/config/environments/production.rb
@@ -44,7 +44,7 @@ Rails.application.configure do
   # Allow to specify public IP of reverse proxy if it's needed
   config.action_dispatch.trusted_proxies = ENV['TRUSTED_PROXY_IP'].split(/(?:\s*,\s*|\s+)/).map { |item| IPAddr.new(item) } if ENV['TRUSTED_PROXY_IP'].present?

-  config.force_ssl = true
+  config.force_ssl = false
   config.ssl_options = {
     redirect: {
       exclude: -> request { request.path.start_with?('/health') || request.headers["Host"].end_with?('.onion') || request.headers["Host"].end_with?('.i2p') }
```

This resolved the issue and Mastodon was able to be served without HTTPS.

I feel this is a valid production configuration in many circumstances if one knows what they're doing; of course wouldn't want it to be the default, but my sense is that setting the env var `FORCE_HTTPS=false` should also set `config.force_ssl = false` in production.

Just wanted to sense-check this before submitting a PR, but I am happy to do so, simply pulling the value of the env var into `config.force_ssl` as would be logical to the best of my knowledge.

Thanks!

### Motivation

I believe server admins might desire running a non-SSL mastodon to put behind an SSL proxy server, in production environments. I expected the FORCE_HTTPS=false setting to enable this, but there's a code change required to make it work as well.

**Comment by felixdoerre** [comment]
> I believe server admins might desire running a non-SSL mastodon to put behind an SSL proxy server

AFAIK Mastodon is always run behind a reverse proxy terminating the TLS-connections (as I dont see any config anywhere to configure certs and similar). You might just miss the `X-Forwarded-Proto`-header to give the mastodon process a hint if the site is accessed via https? Like here:
https://github.com/mastodon/mastodon/blob/main/dist/nginx.conf#L119 

I think `FORCE_HTTPS` should only be used if you want the website accessible by the end user via plain HTTP (and reflect that accurately via the `X-Forwarded-Proto`-header).

**Comment by trisweb** [comment]
Thanks! I'll try that and see if it works with the default production.rb. Will close as it doesn't appear others have this issue.
