### ISSUE TITLE
Mastodon PWA Chrome App icon is not well formatted 

### ISSUE THREAD

**Issue by jaredzimmerman** [mastodon/mastodon#21178]
### Steps to reproduce the problem

1. Go to Mastadon Instance
2. Install Chrome Desktop App (Chrome OS)
3. Launch app

### Expected behavior

App icon should either be circular or non-uniform

### Actual behavior

Square app icon is forced into white circular bound by OS

### Detailed description

![image](https://user-images.githubusercontent.com/430427/202880752-85b8ed8d-e179-4b79-8c15-f4856dc94a0d.png)

### Specifications

Chrome OS  Version 108.0.5359.45

**Comment by ineffyble** [comment]
This was fixed in #20904.
