### ISSUE TITLE
Admin interface: Show warnings sent to users in their relevant reports' audit log

### ISSUE THREAD

**Issue by yuvalne** [mastodon/mastodon#21214]
### Pitch

When resolving a report with a warning, the report audit log only shows that the report has been resolved, without the warning action that has been done. To see that a warning has been sent, a moderator has to go to the user's profile in the interface, where it appears under "strikes".

<img width="1065" alt="Screen Shot 2022-11-20 at 13 39 47" src="https://user-images.githubusercontent.com/97384040/202900746-376e9921-0e67-4f72-86a2-dc927ca8fb08.png">
<img width="1062" alt="Screen Shot 2022-11-20 at 13 40 51" src="https://user-images.githubusercontent.com/97384040/202900744-37c1e358-6a6d-43dd-ab2a-ca4d685a91e0.png">
<img width="1047" alt="Screen Shot 2022-11-20 at 13 36 01" src="https://user-images.githubusercontent.com/97384040/202900748-a4614792-c472-44b8-8b30-06f3e358d272.png">
<img width="1056" alt="Screen Shot 2022-11-20 at 13 36 11" src="https://user-images.githubusercontent.com/97384040/202900747-7d573f7e-9b78-415f-a563-5823989f3daf.png">

The interface should instead show the action in addition to the resolution, similarly to how it appears with other moderation actions.

<img width="1046" alt="Screen Shot 2022-11-20 at 14 04 54" src="https://user-images.githubusercontent.com/97384040/202900920-286bf278-8aa0-4335-8cdd-0856aff0341d.png">

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

### Motivation

The warning not appearing in the repot's audit log can cause confusion when there are multiple moderators going through reports, appearing as though no action has been taken in the report and it has simply been resolved.
Even if the moderator is aware of this issue, it requires them to go to a separate tab simply to see what actions have been done, and if there are multiple warnings, click on each of them to see which report they are related to.

**Comment by ClearlyClaire** [comment]
The code responsible for selecting which action log items to display:
https://github.com/mastodon/mastodon/blob/d2eb726962187226c85ef7f2ee1886cb0767bbd1/app/models/report.rb#L123-L142

This would need to include `AccountWarning` targets, but that requires a join on `account_warnings` to correctly select for the proper report.

**Comment by rixx** [comment]
This has been biting us repeatedly recently. Even when you just worked on a report, it is irritating to see it closed without any action taken. If you look at older reports, you basically have to go to that user's profile, look at the warnings, and see if there any warning at roughly the time when the report was closed to see what action was taken. That's … not great tbh, and adds quite a bit of work, and also makes us treat the report interface as fundamentally unreliable.
