### ISSUE TITLE
Error while running Vacuum::StatusesVacuum: private method `unlink_from_conversations' called for #<Status id:

### ISSUE THREAD

**Issue by renatolond** [mastodon/mastodon#21210]
### Steps to reproduce the problem

1. Let the Vacuum scheduler run
2. Check the logs and see that the StatusesVacuum errored out
3.
...

### Expected behaviour

StatusesVacuum cleans old statuses

### Actual behaviour

A lot of old statuses to be cleaned up

### Detailed description

I have a single instance for testing things for the donte fork. I expected that after enabling the StatusesVacuum, my data usage was going to strongly decrease, but I was surprised to see it was not the case.
I started the vacuum with 3.33GB of postgres usage and 22.3GB of media storage. When it finished, media storage was down to 20.3GB and no significant change happened in the postgres usage.
I then opened a rails console and did the same query that the VacuumScheduler does to get statuses to remove and did a count, I still had `2130695` that matched the query.
Then, checking my logs, I found the error:
```
Nov 19 14:28:28 lond-com-br bash[3469320]: Error while running Vacuum::StatusesVacuum: private method `unlink_from_conversations' called for 
```

Since the vacuum scheduler is globbing down the errors and only printing, I guess this went unnoticed.

Maybe the vacuum scheduler could schedule jobs instead of running all schedulers and globbing the errors?

Also, does this method needs to be called, since it's already called in the before_destroy of the status model?

### Specifications

Mastodon 4.0.2-donte
Ruby 3.0.3
Node 14.19

**Comment by ClearlyClaire** [comment]
Thanks for the report! This should be addressed by #21297

I want to raise the attention that the feature unconditionally deletes any old remote post, including DMs (which caused the issue) mentioning local users, posts that have been boosted, and so on

**Comment by renatolond** [comment]
Yeah, it needs to be more clear on admin panel and around the feature, because it's not clear that it does not take interactions into account.

**Comment by renatolond** [comment]
@ClearlyClaire I created #21307 with some improvements that I feel could make it more clear and overall safe.

**Comment by mjankowski** [comment]
The original issue of the private method being called here was resolved, and the feature has improved and had some options added to it since original issue as well.

Going to close this on assumption that those are sufficient to resolve this and that the other linked issue captures the rest of the improvement ideas. Please reopen if Im missing something!
