### ISSUE TITLE
make the cards and navlinks hoverable 

### ISSUE THREAD

**Issue by PritamSarbajna** [mastodon/mastodon#21213]
### Pitch

I hovered over the cards and navlinks but they they're not giving the feel of hovering. You can see below :

https://user-images.githubusercontent.com/90236635/202902167-e70cb0e1-81b1-4368-b9a2-3cfc6c4d69e4.mp4

> Note : You can assign me for this issue

### Motivation

Users will feel much more better experience.

**Comment by ClearlyClaire** [comment]
Seems like this issue should be filed in https://github.com/mastodon/joinmastodon
