### ISSUE TITLE
Standard sections in /about/more

### ISSUE THREAD

**Issue by Yamakaky** [mastodon/mastodon#2122]
I'm thinking a page with standardized sections including:

- Information about the host
- Privacy guidelines
- Moderation rules
- How the instance is funded: completely free, crowd-funded... Can include Patreon links, bitcoin addresses...
- Maybe a "More info" section

A bit like https://mastodon.social/about/more, but more structured and every section has to be filled. I think the Funding section is especially important.

**Comment by trwnh** [comment]
i think this has been done, so maybe the issue can be closed?

**Comment by Yamakaky** [comment]
Yeah, haven't checked but should be good
