### ISSUE TITLE
Browsing other instances for users to follow

### ISSUE THREAD

**Issue by eusebiu** [mastodon/mastodon#21241]
### Pitch

Be able to browse other instances to ease finding users to follow.

### Motivation

Since some users are on other instances, their posts do not appear on the current one.
In order to create a better timeline, being able to browse other instances would help that.

**Comment by eobet** [comment]
This feels like a duplicate of one of these:

https://github.com/mastodon/mastodon/issues/19307

https://github.com/mastodon/mastodon/issues/6942

**Comment by eusebiu** [comment]
Yes, indeed they are similar!
