### ISSUE TITLE
Translate button ignores poll options

### ISSUE THREAD

**Issue by boskee** [mastodon/mastodon#21247]
### Steps to reproduce the problem

1. Create a post with some poll options
2. Click "Translate" to translate it into another language

### Expected behaviour

Both the text and poll options should be translated

### Actual behaviour

Only the post text is translated, while poll options remain in their original language

### Detailed description

Translating posts that contain polls doesn't seem to translate the latter.

Before:
<img width="437" alt="Screenshot 2022-11-20 190742" src="https://user-images.githubusercontent.com/1312231/202921026-06afeeff-6065-4f2b-8a2b-776769591c47.png">

After:
<img width="434" alt="Screenshot 2022-11-20 190856" src="https://user-images.githubusercontent.com/1312231/202921075-b2f26dcf-2e2a-41d7-90ca-85dcaa072145.png">

As you can see German options remained untranslated

### Specifications

Mastodon 4.0.2

**Comment by JorgeStolfi** [comment]
See also #22398
