### ISSUE TITLE
Unable to get Post URL for follower-only posts or DMs

### ISSUE THREAD

**Issue by rohieb** [mastodon/mastodon#21244]
### Steps to reproduce the problem

1. On v4.0.2, expand a post in your timeline that has follower-only or mentioned-user-only visibility.
2. Click the three dots for the menu.

### Expected behaviour

There is an option to link to the post in question.

### Actual behaviour

There is no "Copy link to post" item like for other (public/unlisted) posts, which, after #19652 was implemented makes it impossible to refer to that post canonically.

### Detailed description

Use cases for linking to the canonical post URL include:
* sending it to same users who I know can read the post, because they also follow the user
* linking it to the same people in the current thread to solve ambiguities
* sending it to one of my other clients to interact there, e.g. answering in the same thread on my smartphone because I want to attach a photo I just took
* … probably others

The search box cannot resolve the links I get by copying the URL behind the timestamp of the post, which now always links to my local server.

### Specifications

Mastodon v4.0.2, viewed in Firefox 102

**Comment by ineffyble** [comment]
It's worth noting the local URL does work for remote users if they search for it.

E.g. if there's a post on Server A, and you view it on Server B, and send the Server B local link to someone on Server C, when they paste it into Server C's search it'll show the Server A post.

That's definitely not an ideal workaround though.

**Comment by ClearlyClaire** [comment]
> It's worth noting the local URL does work for remote users if they search for it.
> 
> E.g. if there's a post on Server A, and you view it on Server B, and send the Server B local link to someone on Server C, when they paste it into Server C's search it'll show the Server A post.
> 
> That's definitely not an ideal workaround though.

It does not work for private posts.
