### ISSUE TITLE
Verification of profile link fails if linked website and Mastodon server share the same base domain

### ISSUE THREAD

**Issue by janedenone** [mastodon/mastodon#21240]
### Steps to reproduce the problem

This issue was brought up almost [four years ago](https://discourse.joinmastodon.org/t/profile-link-verification-fails/1752), but has not been resolved. When adding profile link to a website (e.g. `https://domain.com`) which shares the base domain with a local Mastodon instance (e.g. `https://social.domain.com`), the link is not verified even though the website contains the required link back (`rel=me`).

As soon as the profile link points to the same website served under a different domain name (e.g. `https://domain.org`), the link is verified correctly.

I checked the following files

- `app/services/verify_link_service.rb`
- `app/workers/verify_account_links_worker.rb`
- `app/models/account/field.rb`

– but was not able to identify any requirement regarding the domain used in a profile link with respect to the Mastodon instance's domain (s. also this [Q&A](https://github.com/mastodon/mastodon/discussions/19579).

The issue is currently (11/2022) visible on [my own profile](https://social.eden.one/@jan).

### Expected behaviour

Profile link should be verified

### Actual behaviour

Profile link is not verified

### Detailed description

s. above

### Specifications

Mastodon 4.0.2 (and 3.5.3)
ruby 3.0.4 (and 3.0.3)

**Comment by ineffyble** [comment]
The linked thread indicated the issue was that the two sites (`social.domain.com` and `domain.com`) were hosted on the same server, which was the cause of the issue.

Is that the case for you?

**Comment by janedenone** [comment]
> The linked thread indicated the issue was that the two sites (`social.domain.com` and `domain.com`) were hosted on the same server, which was the cause of the issue.
> 
> Is that the case for you?

It was initially, but I moved the site to a different server (even to a different provider) to rule out this factor.

**Comment by ineffyble** [comment]
Interesting. I can't see anything in the code that would prevent this.

The verification is definitely working remotely, e.g. if I view you from `mastodon.social`:

<img width="125" alt="image" src="https://user-images.githubusercontent.com/834880/202964960-783abbd0-2328-4f4e-9790-464cda6b2056.png">

**Comment by janedenone** [comment]
That is really interesting (and I am glad I did not overlook something obvious in the code). How does the remote display of a profile page differ from the local display?

**Comment by ineffyble** [comment]
The remote server is performing verification itself. So it's definitely not some logic based on "instance domain vs verified link domain", although it could be something to do with "local domain vs verified link domain".

**Comment by janedenone** [comment]
Ok, so the issue is even less of a real problem (given that the verification of two sites served at the same base domain is already trivial), but it still bugs me. :)

Thanks for looking into this!

**Comment by janedenone** [comment]
afontenot provided [the solution](https://github.com/mastodon/mastodon/discussions/19579#discussioncomment-4193456) in my (older) Q&A post just now: Turns out eden.one still resolved to 127.0.0.1 on my Mastodon server, and removing an entry from /etc/hosts made the profile link turn green. Sorry again for the hassle, and thanks to everyone who took the time to help.

**Comment by ineffyble** [comment]
I was _wondering_ if there was some DNS shenanigans!

**Comment by ineffyble** [comment]
_Resets the counter: 0 days since it was DNS_
