### ISSUE TITLE
Add ability to edit captions and alt text after uploading media.

### ISSUE THREAD

**Issue by rkingett** [mastodon/mastodon#21253]
### Pitch

When editing a post, we should also have the ability to add and or edit alt text to an image.

Ideally, like on Facebook, I'd like the ability to add alt text to unlabeled media without editing the post itself, and edit the alt text without editing the post itself.

As for possibilities, we could have it function either way below.

1. Only the post author or logged in profile owner gets to add/edit their own alt text to their photos only.
2. Allow for anybody to suggest captions on media that's then denied or approved by the original poster.

### Motivation

We have the ability to edit posts, but I'd also like the ability to edit the alt text for an image along with a post. This would cut down on people having to make up hashtags, groups, and bots, to solve this shortcoming.

Facebook had this feature for many years. You can add and edit alt text for any picture even after it has been posted.

**Comment by nevillepark** [comment]
Heartily seconded; I've seen some confusion from users who are trying to edit alt text but find that the edit functionality doesn't let them do that.

I am not sure how allowing other people to add/edit alt text would work; it seems to me it could easily become a vector for harassment or just a ton of spam/notifications; but it is worth looking into.

**Comment by g1oria** [comment]
> Heartily seconded; I've seen some confusion from users who are trying to edit alt text but find that the edit functionality doesn't let them do that.
> 
> I am not sure how allowing other people to add/edit alt text would work; it seems to me it could easily become a vector for harassment or just a ton of spam/notifications; but it is worth looking into.

Maybe others could suggest an edit & the owner could choose to apply it as is, or adjust it? IDK, just a thought.

**Comment by rkingett** [comment]
Very happy [it is already a PR so closing this now](https://github.com/mastodon/mastodon/pull/20878)
