### ISSUE TITLE
docker-compose buld chokes on "COPY --link"

### ISSUE THREAD

**Issue by iwilliamson** [mastodon/mastodon#21252]
### Steps to reproduce the problem

1. git clone https://github.com/tootsuite/mastodon mastodon
2. docker-compose build

### Expected behaviour

The imge should build

### Actual behaviour

ERROR: dockerfile parse error line 8: Unknown flag: link

### Detailed description

Since the --link flag on COPY seems to be deprecated, the Dockerfile fails to work.  This was introduced in pull request:

Split off Dockerfile components for faster build times (#20933)

I think this is going to have to do with the version of docker being used.  I'm building on a reasonably up to date "Ubuntu 20.04.5 LTS"

### Specifications

Host:  

  lsb_release -a
  No LSB modules are available.
  Distributor ID: Ubuntu
  Description:    Ubuntu 20.04.5 LTS
  Release:        20.04
  Codename:       focal

Docker:

  Client:
   Version:           20.10.12
   API version:       1.41
   Go version:        go1.16.2
   Git commit:        20.10.12-0ubuntu2~20.04.1
   Built:             Wed Apr  6 02:14:38 2022
   OS/Arch:           linux/amd64
   Context:           default
   Experimental:      true
  
  Server:
   Engine:
    Version:          20.10.12
    API version:      1.41 (minimum version 1.12)
    Go version:       go1.16.2
    Git commit:       20.10.12-0ubuntu2 20.04.1
    Built:            Thu Feb 10 15:03:35 2022
    OS/Arch:          linux/amd64
    Experimental:     false
   containerd:
    Version:          1.5.9-0ubuntu1 20.04.4
    GitCommit:
   runc:
    Version:          1.1.0-0ubuntu1 20.04.1
    GitCommit:
   docker-init:
    Version:          0.19.0
    GitCommit:

**Comment by iwilliamson** [comment]
Alright, I see it's supposed to be built with "buildx", but that must have been added in a newer docker.

Is there any way to build this in the docker version I posted?

**Comment by iwilliamson** [comment]
For posterity, I followed the directions at https://bobcares.com/blog/docker-buildx to install buildx.  and can now "docker buildx build ."

**Comment by mimikun** [comment]
I have same issue.

@iwilliamson 
I have two questions.
Did you succeed in building the image with the `docker-compose build` command?
How did you type the command?

**Comment by mimikun** [comment]
I installed `buildx` and then built the image manually.

``shell
sudo docker buildx install # buildx install
sudo docker image build -t tootsuite/mastodon . # manual build
```
