### ISSUE TITLE
Videos and gifs are broken

### ISSUE THREAD

**Issue by Viss** [mastodon/mastodon#21258]
### Steps to reproduce the problem

1. Attempt to upload a video or a gif by attaching it to a post
2. observe that the result is either a black rectangle, or the first frame of animation, but no more
3. this seems to only happen on mastodon.social, other instances are posting gifs and videos with no issue

### Expected behaviour

The video should play, or the gif should animate

### Actual behaviour

You either see a black rectangle where the media should be, or the first frame of the video or animation

### Detailed description

I have a feeling it may have something to do with the content security policy, or how javascript chunking is trying to handle the media, I've included a screenshot of the chrome javascript console

<img width="896" alt="image" src="https://user-images.githubusercontent.com/1756255/202927778-d9278403-d1bf-41c4-90f1-209a3c68f849.png">

### Specifications

I'm using mastodon.social, which I'm presuming is using the newest code. 

I've verified this on a current android device, current chrome (as of sunday nov 20, 2022) and current firefox. behavior is the same.

**Comment by Viss** [comment]
Here's an example of what happens 
<img width="386" alt="image" src="https://user-images.githubusercontent.com/1756255/202927801-ba69e2e8-428f-462c-b948-d7cb286457be.png">

**Comment by Viss** [comment]
surely a dns problem would result in the images being broken, or not displaying, and not rendering improperly or showing only the first frame?

yesterday images on mastadon.social were proper broken - they wouldnt even load and the sites layout was broken because of that.

I dont think this issue is related to that.

**Comment by afontenot** [comment]
Gifs and videos are both converted (to smaller video files) by ffmpeg. This takes a lot of resources and can be an issue on overloaded servers, so I think it's very probable that this just one of the very many overloading issues on mastodon.social that have shown up in the last few weeks.

**Comment by Viss** [comment]
I would be a lot more appreciative of actual troubleshooting, versus assumptions and guesses.

**Comment by Gargron** [comment]
I would like a link to a post where this happens so I can find out if it's an issue with how the file is saved or with how it's retrieved.

**Comment by mrflix** [comment]
https://mastodon.social/@mrflix/109380902853342514

**Comment by Viss** [comment]
here's another: https://mastodon.social/@Viss/109380551504379006

**Comment by niklaskorz** [comment]
The same happens with our instance rheinneckar.social, in our case the object storage provider is https://www.exoscale.com/

**Comment by ineffyble** [comment]
This should be resolved on mastodon.social now.

@niklaskorz This should be resolved if you set S3_FORCE_SINGLE_REQUEST=true. 

It's unclear if this problem is the result of some change in 4.0, or an internal change at Exoscale (affected instances have all been ones using Exoscale).

**Comment by niklaskorz** [comment]
> This should be resolved on mastodon.social now.
> 
> @niklaskorz This should be resolved if you set S3_FORCE_SINGLE_REQUEST=true.
> 
> It's unclear if this problem is the result of some change in 4.0, or an internal change at Exoscale (affected instances have all been ones using Exoscale).

Ah good to know, thanks! That has indeed worked.

**Comment by Viss** [comment]
gifs work again! 
thanks everyone!

**Comment by splaGit** [comment]
Same issue on my server at v4.0.2 and it uses local storage.

**Comment by mrAceT** [comment]
Same issue here, version 4.0.2, using AWS S3 for storage (not at Amazon)

And the fix mentioned earlier (https://github.com/mastodon/mastodon/issues/21258#issuecomment-1323137725) worked for me too!
