### ISSUE TITLE
Getting blank web page (application fails to render)

### ISSUE THREAD

**Issue by Baldie-dev** [mastodon/mastodon#21273]
### Steps to reproduce the problem

1. Follow a guide how to deploy Mastodon server in Docker.

### Expected behaviour

The web application should launch

### Actual behaviour

The web application is throwing error

### Detailed description

I am getting blank page with following error message in the console:
```
application.js:7 Uncaught ReferenceError: regeneratorRuntime is not defined
    at 535 (application.js:7:21)
    at i (bootstrap:84:22)
    at n (bootstrap:45:15)
    at Array.t [as push] (bootstrap:32:11)
    at application-6f9a2c958394ead811f8.chunk.js:1:47
```

### Specifications

Used Dockerfile and docker-compose file from the repository. So I guess the latest versions.

**Comment by ClearlyClaire** [comment]
It looks like you may have been building the assets in a different way than intended. What guide were you following?

**Comment by Baldie-dev** [comment]
It was this guide: https://www.linode.com/docs/guides/install-mastodon-on-ubuntu-2004/

I have build docker image via:
` docker-compose build`

and then run setup:
`docker-compose run --rm web bundle exec rake mastodon:setup`

**Comment by ClearlyClaire** [comment]
ok, that seems pretty straightforward and I don't expect it to have caused such an issue :/

**Comment by Baldie-dev** [comment]
So I did following:
1. Backup the config:
```
docker-compose down --remove-orphans
mv docker-compose.yml ../
mv .env.production ../
```

2. Remove everything, download repo again and setup
```
rm -rf *
git clone https://github.com/mastodon/mastodon.git
mv mastodon/* .
cp ../docker-compose.yml .
cp ../.env.production .
docker-compose build
sudo chown -R 991:991 public
docker-compose run --rm web bundle exec rake mastodon:setup
```
3. Start it again
```
docker-compose up -d
```

Still getting the `Uncaught ReferenceError: regeneratorRuntime is not defined` error :(

**Comment by ClearlyClaire** [comment]
Yeah that is definitely weird… I'm not sure what's going on. Can you share a link to the instance you are trying to set up?
