### ISSUE TITLE
undefined method `account_id' for nil:NilClass (in app/models/status.rb reload_stale_associations code)

### ISSUE THREAD

**Issue by mdbraber** [mastodon/mastodon#21292]
### Steps to reproduce the problem

Do an API request for timeline e.g. `/api/v1/accounts/109363657537877487/statuses?exclude_replies=true&limit=100`. It seems that some results in the `reload_stale_associations` code in `app/models/status.rb` are actually `nil` and therefore return an `undefined method 'account_id' for nil:NilClass` error. Not sure if this is a problem in our database (some missing values somewhere?) or in the code.

### Expected behaviour

No nil:nilClass errors

### Actual behaviour

nil:nilClass errors

### Detailed description

In `app/models/status.rb:351` block in `reload_stale_associations!` is returning `undefined method 'account_id' for nil:NilClass`. So it seems `cached_items` has some `nil` items? 

```
      cached_items.each do |item|
        account_ids << item.account_id
        account_ids << item.reblog.account_id if item.reblog?
      end
```

### Specifications

Mastodon v4.0.2 (this error was also present in Mastodon v3.5.2)

**Comment by Gargron** [comment]
Related: #18207

**Comment by mdbraber** [comment]
@Gargron thanks for linking to that issues. Is this something then I should just keep 'as is' for now - seeing that the issue is marked as stale and it seems to be abundant (10's of errors per minute). Or is there a suggested fix?

**Comment by ClearlyClaire** [comment]
This is a very annoying one… my hope is that we have managed to squash all the places that could result in this database state occurring in 4.0.2, but if your database was already in this state before upgrading, it would persist until full deletion (that would take up to 30 days).

You could run the following SQL query to fix already-existing occurrences of the issue:
```sql
UPDATE statuses s SET deleted_at = r.deleted_at FROM statuses r WHERE s.reblog_of_id = r.id AND r.deleted_at IS NOT NULL;
```

**Comment by mdbraber** [comment]
Thanks @ClearlyClaire - so far that seems to have fixed our issue!

**Comment by ClearlyClaire** [comment]
You're welcome! Definitely keep an eye on this and don't hesitate to reopen the issue if it occurs again.
