### ISSUE TITLE
Link preview cards truncate URL

### ISSUE THREAD

**Issue by mattedgar** [mastodon/mastodon#21308]
### Steps to reproduce the problem

1. Go to https://mastodon.me.uk/@mattedgar/109380474332652448
2. Click the link presented in status content text
3. Go back and click the link presented in status card
...

### Expected behaviour

Both links go to https://www.gatenbysanderson.com/job/GSe87375/Chief-Information-Officer/

### Actual behaviour

text link goes to the full URL (https://www.gatenbysanderson.com/job/GSe87375/Chief-Information-Officer/) but card link truncates to https://www.gatenbysanderson.com/job/

### Detailed description

This is related to [#19538](https://github.com/mastodon/mastodon/issues/19538) but seemingly a more wide ranging issue than just stripping URL content after a hash

### Specifications

Mastodon v4.0.2
Chrome 107.0.5304.110

**Comment by ineffyble** [comment]
The problem here is that the site in question is declaring that the canonical URL that URL is just /job/:

```
<link rel="canonical" href="https://www.gatenbysanderson.com/job/" />
 ```

That's a bit of a misconfiguration if you ask me.

**Comment by mattedgar** [comment]
Thanks, that makes sense. I can raise with the site owner

Still feels wrong that the text link and status card behave differently in Mastodon, which is also what's happening in [#19538](https://github.com/mastodon/mastodon/issues/19538)

**Comment by ineffyble** [comment]
True, it's interesting. When I post this link on Facebook, all the details on the preview card come from the canonical URL (the jobs homepage). However, the link attached to the card is still the originally entered one.

**Comment by cambraca** [comment]
Here's another case: https://musicians.today/@cambraca/109580608195504779

Should the card maybe _not_ use the canonical URL from the <link> tag (or, in my case, apparently the one from the "og:link" meta tag), but instead just the original URL?

**Comment by imrehg** [comment]
Similar things happen when the posted URL has a query string (e.g. `https://github.com/ohmyzsh/ohmyzsh/pulls?q=is%3Apr+is%3Aopen+paru`), where the query string is totally removed, making the preview both more prominent than the link and also wrong (a different view than intended)

It really feels like using the canonical URL is a bit too clever / too oppinionated for its own good.

**Comment by durka** [comment]
Throwing in my $0.02 that it's really surprising/misleading to have the text link and preview card lead to different places. For another random example, an effect of this is turning NYT gift links into regular paywalled links (they are also implemented using a query parameter, with a `<link rel="canonical">`.

I could almost see it used as an attack. Imagine if goodsite.com put in a `<link rel="canonical" href="https://evilsite.com"/>`. Or just `<link rel="canonical" href="https://goodsite.com?referrer=mastodon"/>` to enable click-tracking.
