### ISSUE TITLE
Search posts not working?

### ISSUE THREAD

**Issue by dpreuss321** [mastodon/mastodon#21338]
### Steps to reproduce the problem

1. Press Search icon in app
2. See "posts" tab open. Search for text: bird
3. No result in Posts. No result, no matter what I search in that tab. (Search does work in the Accounts and Hashtags tabs)
...

### Expected behaviour

Find toots where I used word "bird", there are several.

### Actual behaviour

Message "no result"

### Detailed description

Looking at the issues DB here suggests we already have elastic search enabled.

If so, I expect Tusky to let me do text search.
True? 

I'm new here and not a developer. Let me know if I'm not asking in the right place :-) 

### Specifications

Tusky: 19.0
Android: 12
Device: pixel3
Instance: mstdn.ca

**Comment by ineffyble** [comment]
Does this issue occur on the web client at https://mstdn.ca? If not you should raise it with the Tusky developers

**Comment by renchap** [comment]
Closing this, as it misses details.
