### ISSUE TITLE
All pages returning 403 upon installation 

### ISSUE THREAD

**Issue by Liege72** [mastodon/mastodon#21339]
### Steps to reproduce the problem

1. Follow the instructions listed at https://docs.joinmastodon.org/admin/install/
2. Attempt to run your mastodon server/instance
3. Observe the 403 error on each page

### Expected behaviour

The mastodon instance should be up and running and I should see the UI.

### Actual behaviour

A 403 status code is thrown

### Detailed description

Doubt this is an issue for the majority of people, but I've been trying to fix this issue for quite a while now. I believe it is an issue with my `nginx.conf` or `/etc/nginx/sites-available/mastodon` file. You can view my the `mastodon` file here: https://hastebin.com/udifehibap.properties

### Specifications

Node v14.17.5
Ruby 3.2.33

*Unsure of how to check the version of mastodon

Firefox 107 Windows 11

**Comment by bobhy** [comment]
Do you have a known-working system backup you can revert to, or is this a question of reanimating the corpse?
Do you actually have files in /home/mastodon/live/public;?  
I've got this:
```bash
mastodon@redacted:~$ ll /home/mastodon/live/public
total 332
drwxrwxr-x 10 mastodon mastodon   4096 Nov 18 04:07 ./
drwxrwxr-x 22 mastodon mastodon   4096 Nov 21 01:53 ../
lrwxrwxrwx  1 mastodon mastodon     15 Nov 15 11:12 500.html -> assets/500.html
drwxrwxr-x  4 mastodon mastodon   4096 Nov 18 01:18 assets/
drwxrwxr-x  3 mastodon mastodon   4096 Nov 15 11:12 avatars/
-rw-rw-r--  1 mastodon mastodon   2998 Nov 18 00:36 badge.png
-rw-rw-r--  1 mastodon mastodon   1601 Nov 15 11:12 embed.js
drwxrwxr-x  2 mastodon mastodon 139264 Nov 18 00:36 emoji/
-rw-rw-r--  1 mastodon mastodon  15086 Nov 18 00:36 favicon.ico
drwxrwxr-x  3 mastodon mastodon   4096 Nov 15 11:12 headers/
-rw-rw-r--  1 mastodon mastodon    180 Nov 15 11:12 inert.css
drwxrwxr-x  3 mastodon mastodon   4096 Nov 15 11:12 ocr/
-rw-rw-r--  1 mastodon mastodon  95633 Nov 15 11:13 oops.gif
-rw-rw-r--  1 mastodon mastodon  16948 Nov 18 00:36 oops.png
drwxrwxr-x  6 mastodon mastodon   4096 Nov 18 01:21 packs/
-rw-rw-r--  1 mastodon mastodon    158 Nov 15 11:13 robots.txt
drwxrwxr-x  2 mastodon mastodon   4096 Nov 15 11:13 sounds/
lrwxrwxrwx  1 mastodon mastodon     11 Nov 18 00:36 sw.js -> packs/sw.js
lrwxrwxrwx  1 mastodon mastodon     15 Nov 18 00:36 sw.js.map -> packs/sw.js.map
drwxr-xr-x  4 mastodon mastodon   4096 Nov 18 09:49 system/
-rw-rw-r--  1 mastodon mastodon   1077 Nov 18 00:36 web-push-icon_expand.png
-rw-rw-r--  1 mastodon mastodon    721 Nov 18 00:36 web-push-icon_favourite.png
-rw-rw-r--  1 mastodon mastodon    590 Nov 18 00:36 web-push-icon_reblog.png
```

**Comment by Liege72** [comment]
I'd prefer to not revert to a backup. I just tried the whole process again in a different location within my server and I figure out that `mastodon-streaming` does not seem to be working correctly. You can see the specific error below:
```
Nov 21 21:05:42 server-liege-dev node[11308]: ReferenceError: globalThis is not defined
Nov 21 21:05:42 server-liege-dev node[11308]:     at Object.<anonymous> (/var/www/mastodon/node_modules/are-we-there-yet/node_modules/readable-stream/lib/ours/util.js:6:14)
Nov 21 21:05:42 server-liege-dev node[11308]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Nov 21 21:05:42 server-liege-dev node[11308]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Nov 21 21:05:42 server-liege-dev node[11308]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Nov 21 21:05:42 server-liege-dev node[11308]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Nov 21 21:05:42 server-liege-dev node[11308]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Nov 21 21:05:42 server-liege-dev node[11308]:     at Module.require (internal/modules/cjs/loader.js:692:17)
Nov 21 21:05:42 server-liege-dev node[11308]:     at require (internal/modules/cjs/helpers.js:25:18)
Nov 21 21:05:42 server-liege-dev node[11308]:     at Object.<anonymous> (/var/www/mastodon/node_modules/are-we-there-yet/node_modules/readable-stream/lib/stream.js:31:5)
Nov 21 21:05:42 server-liege-dev node[11308]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Nov 21 21:05:42 server-liege-dev systemd[1]: mastodon-streaming.service: Main process exited, code=exited, status=1/FAILURE
Nov 21 21:05:42 server-liege-dev systemd[1]: mastodon-streaming.service: Failed with result 'exit-code'.
Nov 21 21:05:42 server-liege-dev systemd[1]: mastodon-streaming.service: Scheduled restart job, restart counter is at 10.
Nov 21 21:05:42 server-liege-dev systemd[1]: Stopped mastodon-streaming.
Nov 21 21:05:42 server-liege-dev systemd[1]: mastodon-streaming.service: Start request repeated too quickly.
Nov 21 21:05:42 server-liege-dev systemd[1]: mastodon-streaming.service: Failed with result 'exit-code'.
Nov 21 21:05:42 server-liege-dev systemd[1]: Failed to start mastodon-streaming.
```
After some research, `globalThis` relates to nodes version so I've gone ahead and updated to node `v16.16.0`.

The files and folders in `/home/mastodon/live/public` are as follows:
```
500.html  avatars    embed.js  favicon.ico  inert.css  oops.gif  packs       sounds  sw.js.map                 web-push-icon_favourite.png
assets    badge.png  emoji     headers      ocr        oops.png  robots.txt  sw.js   web-push-icon_expand.png  web-push-icon_reblog.png
```

I'll check out the nginx 403 hints page you sent me and update you if I find anything. Thanks for the help, let me know if you see any issues above.

**Comment by afontenot** [comment]
You probably have an nginx log file at something like /var/log/nginx/error.log (and / or access.log) that will have some useful information here. 

My guess, based on getting a 403, is that there's a permission issue accessing /home/mastodon/live/public. You should see what user nginx is running as, and check permissions on /home/mastodon, /home/mastodon/live, /home/mastodon/live/public. Is each of these directories group-readable? Then you could add the nginx user (often www-data) to the mastodon group. If you do this you may want to make sure any directories under /home/mastodon that are *not* in `live` are user access only (700 permissions), as nginx shouldn't need to access those.

There could be other causes here, this is just a guess. Check permissions!

**Comment by Liege72** [comment]
The contents of the `error.log` file are below:
```
2022/11/22 00:01:57 [error] 36108#36108: *101 directory index of "/home/mastodon/live/public/" is forbidden, client: REDACTED, server: mastodon.liege.dev, request: "GET / HTTP/2.0", host: "mastodon.liege.dev"
2022/11/22 00:01:57 [error] 36108#36108: *101 directory index of "/home/mastodon/live/public/" is forbidden, client: REDACTED, server: mastodon.liege.dev, request: "GET / HTTP/2.0", host: "mastodon.liege.dev"
2022/11/22 00:40:48 [error] 36108#36108: *108 open() "/home/mastodon/live/public/explore" failed (2: No such file or directory), client: REDACTED, server: mastodon.liege.dev, request: "GET /explore HTTP/1.1", host: REDACTED
2022/11/22 00:53:08 [error] 36108#36108: *110 directory index of "/home/mastodon/live/public/" is forbidden, client: REDACTED, server: mastodon.liege.dev, request: "GET / HTTP/2.0", host: "mastodon.liege.dev"
```
The `/home/mastodon`, `/home/mastodon/live`, `/home/mastodon/live/public` directories all have 770 permissions (Owner: Read,Write,Execute; Group: Read,Write.Execute). After changing the directories to the above permissions, the `error.log` file added:
```
2022/11/22 01:21:26 [error] 36108#36108: *112 "/home/mastodon/live/public/index.html" is forbidden (13: Permission denied), client: REDACTED, server: mastodon.liege.dev, request: "GET / HTTP/2.0", host: "mastodon.liege.dev"
2022/11/22 01:21:26 [error] 36108#36108: *112 open() "/home/mastodon/live/public/favicon.ico" failed (13: Permission denied), client: REDACTED, server: mastodon.liege.dev, request: "GET /favicon.ico HTTP/2.0", host: "mastodon.liege.dev", referrer: "https://mastodon.liege.dev/"
2022/11/22 01:21:37 [warn] 63017#63017: conflicting server name "mastodon.liege.dev" on 0.0.0.0:443, ignored
2022/11/22 01:21:37 [warn] 63028#63028: conflicting server name "mastodon.liege.dev" on 0.0.0.0:443, ignored
```

> Edit: make sure that all the mastodon services are running and haven't failed as well.

As stated before, I figured out that `mastodon-streaming` is not working because of some `globalThis` issue. You can see all the details in my previous comment.

Appreciate your suggestions and assistance, let me know if this helps!

**Comment by afontenot** [comment]
Yes, this seems to indicate that I was right about it being a file permissions issue.

Your directories all have 770 permissions, and I assume the files are all probably 660? In that case, you should check what user nginx runs as (likely www-data) and add this user to the mastodon group. Something like (note the order, group before username).

    sudo usermod --append --groups mastodon www-data

Again, if you do this, my advice would be to make sure that directories in the mastodon home folder that are *not* in the `/home/mastodon/live/public` path are all user only (700 permissions).

Just to explain the issue quickly, taking the file `/home/mastodon/live/public/index.html` as an example, if this file is owned by the `mastodon` user and the `mastodon` group, and has 660 permissions, adding the nginx user (e.g. www-data) to this group will allow it to read the file. But that also requires the nginx user to have access to higher level directories.

**Comment by Liege72** [comment]
Got it; I've think I have correctly implemented these changes. It still does not work. :(

There is another issue that has caught my attention. Mastodon requires a nodejs to be a version `>=12`. I stated previously that my **node** was version `14.17.5` and I updated it to `16.16.0` (I've updated it to `19.1.0` now). Node and nodejs are two different things and it turns out my nodejs is only version `10.19.0`. Using logic and after some testing, it seems mastodon only really cares about nodejs and because the version is not `>=12`, it is failing (explains why `globalThis` is not recognized). I've tried numerous times to update nodejs, I've even uninstalled and reinstalled it, but it states that `10.19.0` is the latest version. 

I think if I can figure out how to update my **nodejs** to a version `>=12`, my issues will be fixed. 

Any ideas of what I can do here? Clearly something is outdated because it thinks `10.19.0` is the latest version of nodejs.

**Comment by afontenot** [comment]
My understanding is that the project requires node < 17.0 at present. See https://github.com/mastodon/mastodon/issues/20968 I'm not sure if that is documented or not. So regardless of which one is actually being used, it will probably not work. :-(

Regarding your specific node issues, it kind of sounds like you managed to install two separate versions somehow. I think I would probably start by trying to get rid of them all. Run `which node` and `which nodejs` to see what files those commands are from. Then (assuming you're on Debian or a derivative) you'd run `dpkg -S /usr/bin/node` (or whatever file you see) to get the package name. Then you can uninstall those packages. Check again to make sure there aren't any node commands left over. Then (again assuming Debian) make sure you don't have any old sources in your `/etc/apt/sources.list.d`.

After that the instructions in the [docs](https://docs.joinmastodon.org/admin/install/#system-packages) for installing nodejs should just work. I'd probably redo the steps after that for a fresh Mastodon installation just to be sure nothing got messed up.

**Comment by bobhy** [comment]
It sounds like you're dealing with a system config or installation prerequisites issue rather than a potential bug in mastodon.  This `issues` tab on github is more for bug reporting on mastodon itself: you may find broader help by raising subsequent questions on `discussions` tab (where I see others working through install issues) or even on [stackoverflow questions tagged mastodon](https://stackoverflow.com/questions/tagged/mastodon).   

But to answer your question about nodejs; yes, that's the package you want, but the version of nodejs available in your system's package manager (`yum` or `apt`?) is bound to be out of date.  You should install one downloaded direct from (nodejs.org)[https://nodejs.org/en/download/].  

This, and many subsequent gotchas that may be laying in wait for you, can be avoided by following the well-documented procedure at : https://docs.joinmastodon.org/admin/prerequisites/.

**Comment by Liege72** [comment]
Update: I've managed to fix the node and nodejs issues so that is not of concern anymore. All the mastodon services are up and running fine along with nginx, but I am still getting a 403. 

@afontenot I tried what you suggested (restarting the whole process and reinstalling) and when I get to the configuration part (`RAILS_ENV=production bundle exec rake mastodon:setup`), I get an error saying: "Could not locate Gemfile or .bundle/ directory."

Additionally, I've checked my `error.log` file again; you can see its contents below.
```
2022/11/23 03:22:56 [error] 327491#327491: *3 directory index of "/home/mastodon/live/public/" is forbidden, client: REDACTED, server: mastodon.liege.dev, request: "GET / HTTP/2.0", host: "mastodon.liege.dev"
2022/11/23 03:23:03 [error] 327491#327491: *5 directory index of "/home/mastodon/live/public/" is forbidden, client: REDACTED, server: mastodon.liege.dev, request: "GET / HTTP/1.1", host: "mastodon.liege.dev"
2022/11/23 03:23:03 [error] 327491#327491: *5 "/home/mastodon/live/public/test_404_page/index.html" is not found (2: No such file or directory), client: REDACTED, server: mastodon.liege.dev, request: "GET /test_404_page/ HTTP/1.1", host: "mastodon.liege.dev"
2022/11/23 03:23:10 [error] 327491#327491: *3 directory index of "/home/mastodon/live/public/" is forbidden, client: REDACTED, server: mastodon.liege.dev, request: "GET / HTTP/2.0", host: "mastodon.liege.dev"
```

@bobhy I'll move over to the discussions tab if the response to this comment doesn't work out; thank you for letting me know.

**Comment by afontenot** [comment]
The error log pretty much spells it out, no?

`directory index of "/home/mastodon/live/public/" is forbidden`

Try doing all of the following:

```
ls -la /home/mastodon
ls -la /home/mastodon/live
ls -la /home/mastodon/live/public
```

Correct permissions means that one of the following holds:

1. All of the directories on the /home/mastodon/live/public path (and descendants) have `drwxr-xr-x` permissions, which means they are readable by any user. `drwxrwxr-x` is also acceptable. In addition, files created *by Mastodon* in any public directory need to have the `-rw-r--r--` permission, meaning the are readable by any user. Some users have reported that files created by Mastodon are not world-readable; I don't know how to change this.
2. All of the directories and files on the /home/mastodon/live/public path (and descendants) have `drwxr-x---` or `drwxr-xr-x` permissions (on directories) and the same without the 'x' for files. *In addition*, you should see that every row shows `mastodon mastodon` indicating that the files and directories are owned by the mastodon user and group. **In this case** you can fix your issue by adding the nginx user (maybe `www-data`, but check) to the mastodon group, as I described [here](https://github.com/mastodon/mastodon/issues/21339#issuecomment-1322959650). 

Most users who have had similar issues to you have gone with (2), and added the nginx user to the mastodon group. That method works just fine but it's important to make sure that the public files aren't group-writable if you do. They need to be only writable by the Mastodon user. I don't know of any specific security issue this would cause, but it's best practice.

**Comment by Liege72** [comment]
No luck! I've listed the directory permissions for `/home/mastodon/live` and `/home/mastodon/live/public` below.
```
drwxrwxr-x  22 mastodon mastodon   4096 Nov 21 03:36 .
drwxr-xr-x   8 mastodon mastodon   4096 Nov 21 03:36 ..
drwxrwxr-x   2 mastodon mastodon   4096 Nov 21 00:08 .bundle
drwxrwxr-x   2 mastodon mastodon   4096 Nov 21 00:07 .circleci
drwxrwxr-x   2 mastodon mastodon   4096 Nov 21 00:07 .devcontainer
drwxrwxr-x   8 mastodon mastodon   4096 Nov 21 00:08 .git
drwxrwxr-x   4 mastodon mastodon   4096 Nov 21 00:07 .github
drwxrwxr-x  16 mastodon mastodon   4096 Nov 21 00:07 app
drwxrwxr-x   2 mastodon mastodon   4096 Nov 21 00:07 bin
drwxrwxr-x   3 mastodon mastodon   4096 Nov 21 03:36 build
drwxrwxr-x   3 mastodon mastodon   4096 Nov 21 00:08 chart
drwxrwxr-x   6 mastodon mastodon   4096 Nov 21 00:08 config
drwxrwxr-x   6 mastodon mastodon   4096 Nov 21 00:07 db
drwxrwxr-x   2 mastodon mastodon   4096 Nov 21 00:07 dist
drwxrwxr-x  18 mastodon mastodon   4096 Nov 21 00:07 lib
drwxrwxr-x   2 mastodon mastodon   4096 Nov 21 00:07 log
drwxrwxr-x 845 mastodon mastodon  36864 Nov 21 04:13 node_modules
drwxr-xr-x   9 mastodon mastodon   4096 Nov 21 04:14 public
drwxrwxr-x  21 mastodon mastodon   4096 Nov 21 00:07 spec
drwxrwxr-x   2 mastodon mastodon   4096 Nov 21 00:07 streaming
drwxrwxr-x   4 mastodon mastodon   4096 Nov 21 04:24 tmp
drwxrwxr-x   3 mastodon mastodon   4096 Nov 21 00:08 vendor
```
```
drwxr-xr-x  9 mastodon mastodon   4096 Nov 21 04:14 .
drwxrwxr-x 22 mastodon mastodon   4096 Nov 21 03:36 ..
drwxr-xr-x  4 mastodon mastodon   4096 Nov 21 04:14 assets
drwxr-xr-x  3 mastodon mastodon   4096 Nov 21 00:07 avatars
drwxr-xr-x  2 mastodon mastodon 159744 Nov 21 00:07 emoji
drwxr-xr-x  3 mastodon mastodon   4096 Nov 21 00:07 headers
drwxr-xr-x  3 mastodon mastodon   4096 Nov 21 00:07 ocr
drwxr-xr-x  6 mastodon mastodon   4096 Nov 21 04:14 packs
drwxr-xr-x  2 mastodon mastodon   4096 Nov 21 00:07 sounds
```

As for my nginx config in `/etc/nginx/sites-available/mastodon`, you can see it [here](https://hastebin.com/inugomonov.properties).
Not sure if it matters, but the nginx config in `/etc/nginx/nginx.conf`, you can see [here](https://hastebin.com/igayecuhon.nginx).

You suggestion regarding adding another user: I used the command: `sudo usermod -a -G mastodon www-data` and there was no output. I'm not exactly sure if that's a good or bad thing and weather I should see changes when I use `ls -la` (which there are none).

**Comment by afontenot** [comment]
You've got a duplicate server declaration in your nginx.conf file!

**Comment by Liege72** [comment]
Progress! There is no longer a 403 error, but a 502. I have a mastodon built page telling me: "We're sorry, but something went wrong on our end. " 

I am so close! Thank you for all this help, I really appreciate it. I'm doing some research on how to fix this issue. Let me know if you have any suggestions. Thank you again.

**Comment by Liege72** [comment]
According to [issue #7454](https://github.com/mastodon/mastodon/issues/7454), this is an issue with some sort of "puma" issue. I think this circles back to my issue relating to my gem file and bundle directory. As stated before, "when I get to the configuration part (RAILS_ENV=production bundle exec rake mastodon:setup), I get an error saying: "Could not locate Gemfile or .bundle/ directory."" 

Any suggestions?

**Comment by afontenot** [comment]
Since you're facing a different issue, this is probably a good spot to close this and start a discussion thread. Feel free to tag me there, although I'm probably a bit less useful at debugging Mastodon issues than more general sysadmin stuff.

**Comment by Liege72** [comment]
Good idea. Thank you for all your help along the way.
