### ISSUE TITLE
Change theme-color meta value to a lighter shade when light theme is selected

### ISSUE THREAD

**Issue by davidpmccormick** [mastodon/mastodon#21381]
### Pitch

When a user has the light theme selected, the meta `theme-color` value should reflect this with a more appropriate (lighter) value.

### Motivation

If you install the PWA as a standalone app, the top-bar of the app's chrome will have the `theme-color` background. This looks great if you're using the dark theme, but if you switch to the light theme it stands out.

**Comment by davidpmccormick** [comment]
FWIW I've added this to a run-arbitrary-JS chrome plugin which achieves what I'm after.

`document.head.querySelector("[name~=theme-color][content]").content = '#eff3f5';`

**Comment by renchap** [comment]
This has been fixed in https://github.com/mastodon/mastodon/pull/29795
