### ISSUE TITLE
Loading "About" page in advanced view doesn't have a Back button

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#21392]
### Steps to reproduce the problem

1. Have "advanced web interface" enabled
2. Click "About" in the footer

### Expected behaviour

able to navigate back to "getting started"

### Actual behaviour

not able to go back except with my browser back button

### Specifications

mastodon.social 4.0.2

**Comment by tamasys** [comment]
Looks like this might be the same as #20890?

**Comment by mjankowski** [comment]
Stale since https://github.com/mastodon/mastodon/pull/25973
