### ISSUE TITLE
WebFinger Urls not updating after migrating/redirecting

### ISSUE THREAD

**Issue by rbairwell** [mastodon/mastodon#21401]
### Steps to reproduce the problem

1. Setup a redirect from an account on server A to an account on server B
2. Query the webfinger url for the user on server A
3.
...

### Expected behaviour

Either a 301/302 redirect to server B's webfinger location or for the locations within the webfinger data to be updated

### Actual behaviour

Webfinger data and url remains the same

### Detailed description

I recently migrated my account from mastodon.social to mastoson.org.uk and, as part of the migration process, a redirect was put in place. (note: I did have to cancel and reset the redirect a couple of times as the destination server was under load and hadn't imported followers after 2 hours).

Since my old profile page at https://mastodon.social/@rbairwell displays
`has indicated that their new account is now:
rbairwell@mastodon.org.uk
`

I would have expected the WebFinger link at https://mastodon.social/.well-known/webfinger?resource=acct:rbairwell@mastodon.social to also reflect this fact so clients can automatically update.

However, going to that url in a browser or using a to such as https://webfinger.net/lookup/?resource=rbairwell%40mastodon.social gives no machine readable indication that my account can now be found at a different location:
`
{
  "subject": "acct:rbairwell@mastodon.social",
  "aliases": [
    "https://mastodon.social/@rbairwell",
    "https://mastodon.social/users/rbairwell"
  ],
  "links": [
    {
      "rel": "http://webfinger.net/rel/profile-page",
      "type": "text/html",
      "href": "https://mastodon.social/@rbairwell"
    },
    {
      "rel": "self",
      "type": "application/activity+json",
      "href": "https://mastodon.social/users/rbairwell"
    },
    {
      "rel": "http://ostatus.org/schema/1.0/subscribe",
      "template": "https://mastodon.social/authorize_interaction?uri={uri}"
    }
  ]
}
`

I would have either expected the urls to be updated to reflect the new location OR for the server to issue a 301 permanent redirect to the new WebFinger location such as:
`
HTTP/1.1 301 Moved Permanently
Location: https://mastodon.org.uk/.well-known/webfinger?resource=acct%3Arbairwell%40mastodon.org.uk
`

(I can confirm that this 301 redirect method does work in Tusky and 4.0.2's web client as my personal site redirects i 
this manner: https://rbairwell.dev/.well-known/webfinger?resource=acct%3Arbairwell%40rbairwell.dev allowing my profile to be found with @rbairwell@rbairwell.dev )

### Specifications

Mastodon 4.0.2 on both servers
Checked using Brave Browser on Android and third party tools.

**Comment by ineffyble** [comment]
The issue with doing this is it would prevent any of the content that is associated with your old account updating.

The way this is currently handled is that there's additional metadata added to the ActivityPub object of your old account (e.g. https://mastodon.social/users/rbairwell.json) indicating that it has "movedTo" your new account.

Clients read this metadata and should use it to show a notice, like mastodon.social does. That allows a human to get to your new account but also view content on your old account.

**Comment by rbairwell** [comment]
Thanks @ineffyble : I must admit at that point I was only really thinking of things "going fowards" and not for previous posts.
