### ISSUE TITLE
GIFs no Longer Work on .World server

### ISSUE THREAD

**Issue by KaysGramma** [mastodon/mastodon#21412]
### Steps to reproduce the problem

Uploaded a GIF from my local drive and from a GIF keyboard. Neither worked

### Expected behaviour

GIF should be animated

### Actual behaviour

Still photo

### Detailed description

I was able to successfully upload a GIF to my comment on Sunday afternoon. By Sunday evening, my GIFs were no longer animated, altho I’ve seen other people use them. I’m on the Mastodon.world server. Is this the issue? Did they disable this function? Anyone have anything to offer?

### Specifications

Mastodon

**Comment by ineffyble** [comment]
@KaysGramma If you're not the admin of mastodon.world you'll need to contact them about this issue, we don't have any insight or control.
