### ISSUE TITLE
Allow users to turn off audible notifications

### ISSUE THREAD

**Issue by Servelan** [mastodon/mastodon#21428]
### Pitch

I searched in the settings for how to turn off audible notifications and there isn't one.

I'm #ActuallyAutistic and as we all know we are...particular...in our experience of websites, visuals, sound, etc. because of sensory processing issues. 

Since the bird app has gone to heck under a new owner, people with disabilities, like me, will seek out other ways to connect (Mastodon!) and will need minor accommodation, little tweaks here and there.

I'd really like to turn off the beep when someone does something with a post of mine.  It's not something I chose, it's uncomfortable (being random and un-asked-for), and serves no useful purpose for me.  

If there's code to make it happen, there can be code to silence it, and I'd like the option to do so.  No rush, but sooner's better than later.

### Motivation

There's an outside and somewhat urgent impetus pushing implementation of accessibility features as mentioned.

**Comment by carlosefonseca** [comment]
Open the Notifications pane, click on the settings button to the right of the Notifications title bar, deselect all "Play Sound" options.

**Comment by rbairwell** [comment]
Yep, you can turn on/off sounds in the notification panel for each item (I've turned mine all off as well for the same reason) - and you should be able to mute your browser as well - at least on Chromium Windows browsers, if you right click on the tab there should be a "Mute site" option which will prevent the site from causing sound even if it wanted to.

**Comment by ineffyble** [comment]
Screenshot of the Notifications settings mentioned, this should meet your requirements.

<img width="606" alt="image" src="https://user-images.githubusercontent.com/834880/203445984-560b9145-3a4e-4160-bff7-456a424803d8.png">
