### ISSUE TITLE
Top-level follow button

### ISSUE THREAD

**Issue by irustyw** [mastodon/mastodon#21439]
### Pitch

As one of the thousands of Twitter refugees I'm trying to get adapt my habits to Mastodon. I was surprised initially to not find a Follow button.  But then I learned it's down one level.  That's inefficient for one of the most important features. It also is going to confuse every Twitter user who's used to seeing it as the most prominent option on the screen. If you want to retain these users, it needs to be more visible.  

### Motivation

Every person trying out Mastodon after giving up on Twitter.

**Comment by afontenot** [comment]
> I was surprised initially to not find a Follow button. But then I learned it's down one level.

By this, do you mean that you have to click through to the profile to see the button? If so, you probably want something like https://github.com/mastodon/mastodon/issues/14918 to be implemented. The request is basically asking for the little card you see when you hover over a username on Twitter.

**Comment by ineffyble** [comment]
It would be helpful to know if your experience is:

- Desktop or mobile
- Web or app
- When viewing a user from your local Mastodon instance or when viewing them on their remote instance (where you won't be logged in)
- On a server running Mastodon 3.5 or Mastodon 4.0

**Comment by ineffyble** [comment]
Alternatively a screenshot would be very helpful.

**Comment by irustyw** [comment]
> > I was surprised initially to not find a Follow button. But then I learned it's down one level.
> 
> By this, do you mean that you have to click through to the profile to see the button? If so, you probably want something like #14918 to be implemented. The request is basically asking for the little card you see when you hover over a username on Twitter.

Similar, but not the same.  Hover is not a clear UI and doesn't translate to mobile.  If that was implemented, I'd find it more useful but not a solution.

**Comment by irustyw** [comment]
> Similar, but not the same. Hover is not a clear UI and doesn't translate to mobile. If that was implemented, I'd find it more useful but not a solution.



> By this, do you mean that you have to click through to the profile to see the button? If so, you probably want something like #14918 to be implemented. The request is basically asking for the little card you see when you hover over a username on Twitter.

Sorry.  I need to amend my last response. I just checked twitter again on my desktop and the follow button is accessible from hover and the three dot menu.  Replicating that would be fine.  The follow option on Twitter is top-level only when searching for people so it's consistent with Mastodon.

**Comment by irustyw** [comment]
> It would be helpful to know if your experience is:
> 
> * Desktop or mobile
> * Web or app
> * When viewing a user from your local Mastodon instance or when viewing them on their remote instance (where you won't be logged in)
> * On a server running Mastodon 3.5 or Mastodon 4.0

I was using Desktop web (browser).  Not sure about Mastodon version.  
In my response to @afontenot I admitted that I got this wrong: a follow option from hover or the three dot menu would be fine.  

Should I retire this thread or is there a way to edit the request -- or perhaps merge it with the one afontenot referenced?

**Comment by ineffyble** [comment]
If you're happy that #14918 encapsulates the changes you'd like to see, then the best thing to do is close this request as a duplicate 🙂
