### ISSUE TITLE
Modified favicon not showing on Safari 16.1 on macOS Ventura 13.0.1

### ISSUE THREAD

**Issue by ralfr** [mastodon/mastodon#21436]
### Steps to reproduce the problem

I've modified all favicon files in `/live/public/packs/media/icons` and `live/app/javascript/icons`. I've run `rails assets:precompile`. I've cleared Safari's cache in `/Users/$user/Library/Safari/Favicon Cache` and `/Users/$user/Library/Safari/Touch Icons Cache`.

However, Mastodon Web UI still shows the blue default Mastodon icon in the tab bar.

You can check it out yourself at [home.social](https://home.social). (It does work in Chrome and all other browsers.)

Any idea?

### Expected behaviour

My updated favicon should show up!

### Actual behaviour

The default favicon shows up.

### Specifications

Mastodon 4.0.2, non-dockerized

**Comment by rbairwell** [comment]
The icon has updated for me.
![image](https://user-images.githubusercontent.com/775269/203441893-0bf399fd-fbf5-43f1-bf2a-53070c4729bc.png)

The favicon.ico is showing a last-modified date of Mon, 21 Nov 2022 14:42:37 GMT and favicon-32x32-35df61cd03ada5d305c309db6435bf42.png is showing Tue, 22 Nov 2022 22:33:50 GMT. 

I suspect nginx has/had cached the images. Have a look on how to flush/clear the cache if you experience the problem again.

**Comment by ralfr** [comment]
YesL I had to remove the .svg masked icon. That did the trick.

**Comment by rbairwell** [comment]
Brilliant. If issue is fixed, could you close it so the poor devs don't get too scared of the list of issues to work on ;)
