### ISSUE TITLE
Followers Do Not Migrate on a unstable server

### ISSUE THREAD

**Issue by WhiskeyOmega** [mastodon/mastodon#21442]
### Steps to reproduce the problem

Account options for redirect
Migrated account on one instance
Server failed.  

### Expected behaviour

Followers should have gone with the account redirect

### Actual behaviour

Job failed and followers didnt join new account. 

### Detailed description

I Tried to Migrate away from a instance to my own on Sunday so (3 days ago at time of writing this) Whilst trying to setup the migration the server was unstable going from slow to completely down. For some reason this stopped the followers being migrated over and the job failed. The redirect happened but as the server went down just as I was migrating nothing followed me over to my new instance. This also doesnt help that you only get migrations every 30 days even if the job failed so I have to wait now to cancel and set it up again or hope my followers refollow me on my new instance manually. 

### Specifications

Brave [Version 1.43.93]
Server instance that failed is on v3.5.3.
New Server is on v4.0.2

**Comment by nightpool** [comment]
There isn't enough info here to fix this, the admin of the instance that you migrated away from would need to open a bug report describing exactly what happened and why the job failed, since there are lots of different ways for instances to be "unstable" and we can't protect against all of them 

> This also doesnt help that you only get migrations every 30 days even if the job failed so I have to wait now to cancel and set it up again or hope my followers refollow me on my new instance manually.

The admin of the server can retrigger the job manually at any time

**Comment by krisnova** [comment]
> The admin of the server can retrigger the job manually at any time

Any more insight on how exactly an admin like myself would go about re-triggering the job? I am not seeing any documentation on such a thing.

**Comment by WhiskeyOmega** [comment]
> There isn't enough info here to fix this, the admin of the instance that you migrated away from would need to open a bug report describing exactly what happened and why the job failed, since there are lots of different ways for instances to be "unstable" and we can't protect against all of them
> 
> > This also doesnt help that you only get migrations every 30 days even if the job failed so I have to wait now to cancel and set it up again or hope my followers refollow me on my new instance manually.
> 
> The admin of the server can retrigger the job manually at any time

The Admin of the server doesnt know how to do this and I dont know how.

**Comment by nightpool** [comment]
> Any more insight on how exactly an admin like myself would go about re-triggering the job? I am not seeing any documentation on such a thing.

Going off of https://github.com/mastodon/mastodon/blob/main/app/controllers/settings/migrations_controller.rb, something like:

```ruby
MoveService.new.call(account.migrations.last)
```

should work. (where `user` is the user account in question)

**Comment by krisnova** [comment]
Thanks @nightpool I will give it a try!
