### ISSUE TITLE
Add ability to change/edit alt-text when editing a post

### ISSUE THREAD

**Issue by Pokefan5** [mastodon/mastodon#21445]
### Pitch

Let the user edit the alt-text of an image when editing a post the same way as when first uploading it. You can already do this by removing the image and re-uploading it, or (to my understanding) on the latest in development version of the mobile app.

### Motivation

Commenters can suggest alt-text to images that do not yet have any for the author to add. Also, typos can be fixed.

**Comment by ineffyble** [comment]
Duplicate of #20887
