### ISSUE TITLE
Handle account URLs pointing to own host

### ISSUE THREAD

**Issue by bramus** [mastodon/mastodon#21469]
### Steps to reproduce the problem

1. Visit https://mastodon.social/@bramus@mastodon.social

### Expected behaviour

For the page to understand that it’s an account on the same server

### Actual behaviour

The page keeps showing a spinner

### Detailed description

I would have expected for https://mastodon.social/@bramus@mastodon.social to redirect to https://mastodon.social/@bramus as it’s an account of that host viewed on that host.

### Specifications

Mastodon 4.0.2

**Comment by bramus** [comment]
I see that on https://github.com/mastodon/mastodon/blob/main/app/javascript/mastodon/features/account_timeline/index.js#L27 it’s trying to extract the `accountId`. Maybe [the called `normalizeForLookup` function](https://github.com/mastodon/mastodon/blob/main/app/javascript/mastodon/reducers/accounts_map.js#L4) could simply trim off the `LOCAL_DOMAIN` if detected?

**Comment by ClearlyClaire** [comment]
Nothing in Mastodon should lead to such URLs, so this is unsupported. That being said, this is easy enough—if slightly awkward—to fix, so we'll address it—at least for the non-IDN case.
