### ISSUE TITLE
Bulk import/export of federation domain blocks

### ISSUE THREAD

**Issue by thomas-alrek** [mastodon/mastodon#21463]
### Pitch

Currently, we have to add one domain block at a time. What I would like to see, is a feature that let's us both export a list of blocked domains to a CSV format (or similar), and import such a list directly from the web interface.

### Motivation

It takes a long time adding blocked servers now, since you have to add one at a time.
Often server admins share lists of blocked domains with each others. This would speed up the process, and make it so much easier for us moderators and administrators to keep our communities safe.

**Comment by ClearlyClaire** [comment]
I think this is addressed by #20597

![image](https://user-images.githubusercontent.com/384364/203518917-2639e541-e7f2-479e-82c4-5557e44641b9.png)
![image](https://user-images.githubusercontent.com/384364/203518986-d73a009a-513a-4831-884d-56ecb956291b.png)
![image](https://user-images.githubusercontent.com/384364/203519526-b518455c-a7d6-465d-9e77-2496988df73c.png)
