### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by KRRW** [mastodon/mastodon#21473]
### Steps to reproduce the problem

1. Importing blocks, mutes and follows from another server/instance

### Expected behaviour

Success

### Actual behaviour

Did nothing

### Detailed description

This seems to be only a problem on instances running latest version of Mastodon.

### Specifications

Mastodon 4.x+

**Comment by rbairwell** [comment]
I've not seen this problem when I imported a list from a 4.0.2 to a 4.0.2 instance.

I assume you have exported these items from the old server, imported into the new one, there was no error reported, and then you gave it time. Imports like these are deemed "low priority" and so if the instance is backlogged for whatever reason, the import will be delayed (I've had some take 3 to 16 hours before). It might be worth checking with your (new) instance admin what the Sidekiq queues are like.

**Comment by Flashbin** [comment]
Same thing here. Just set up a new instance (v4.0.2) and imports are not working. No errors, but I can see in the log that it's trying to put the csv on the S3 storage under `imports/data/000/000/009/original/following_accounts.csv`, but it never shows up there. There isn't even an imports folder in the bucket. Everything else related to S3 is working just fine.

**Comment by mrAceT** [comment]
I have the same problem, from 4.0.2 to 4.0.2.. looked everywhere.. no bug, no error, no mention of trouble.. but also, no import..

**Comment by mattstein** [comment]
Same! Two 4.0.2 instances, and after @Flashbin’s comment I set `S3_ENABLED=false`, ran `sudo systemctl restart mastodon-web` and tried again with no change in behavior. This is on a fresh single-user instance and I made sure the queue was idle every time before and after the attempt. 🤷‍♂️
