### ISSUE TITLE
Web::PushNotificationWorker throws "invalid base64".

### ISSUE THREAD

**Issue by Nebukadneza** [mastodon/mastodon#21481]
### Steps to reproduce the problem

1. Have the webapp(?) or the fedilab app connected and open
2. ?!? something happens !?!
3. Find traceback in `sidekiq` logs

### Expected behaviour

No tracebacks in the logs

### Actual behaviour

There are tracebacks

### Detailed description

Caused by unknown reproduction-steps / causes, I find a lot of these tracebacks in my `sidekiq` logs:

```
sidekiq_1_cd9c14ea115e | 2022-11-23T13:29:54.736866374Z 2022-11-23T13:29:54.736Z pid=7 tid=hgl3 WARN: {"context":"Job raised exception","job":{"retry":5,"queue":"push","class":"Web::PushNotificationWorker","args":[10,329],"jid":"34b85dcb9562583d07ccca44","created_at":1669209702.6571393,"enqueued_at":1669210194.7250526,"error_message":"invalid base64","error_class":"ArgumentError","failed_at":1669209702.7254102,"retry_count":4,"retried_at":1669209914.851075}}
sidekiq_1_cd9c14ea115e | 2022-11-23T13:29:54.736893321Z 2022-11-23T13:29:54.736Z pid=7 tid=hgl3 WARN: ArgumentError: invalid base64
sidekiq_1_cd9c14ea115e | 2022-11-23T13:29:54.736897279Z 2022-11-23T13:29:54.736Z pid=7 tid=hgl3 WARN: <internal:pack>:281:in `unpack1'
sidekiq_1_cd9c14ea115e | 2022-11-23T13:29:54.736900662Z /opt/ruby/lib/ruby/3.0.0/base64.rb:74:in `strict_decode64'
sidekiq_1_cd9c14ea115e | 2022-11-23T13:29:54.736903667Z /opt/ruby/lib/ruby/3.0.0/base64.rb:106:in `urlsafe_decode64'
```

It’s always related to `Web::PushNotificationWorker` and always a `ArgumentError: invalid base64`.

I notice two things from the users side:
* I don’t receive any desktop notifications in the web-ui, neither Android notifications using fedilab and unifiedpush
* Sometimes (direct/public) posts from instance-local users don’t show up in others instance-local users' home-timelines, even though the second user follows the first user. This may or may not be related to the posts containing photos?!? It happens randomly

I’m **not sure any of these two things has anything to do with the above traceback**. Both the "not showing up" and the traceback happen often but irregularly enough that I haven’t been able to correlate them.

### Specifications

* `docker-compose` setup
* Mastodon (`tootsuite/mastodon:v4.0` in `1e471191e3a6`, aka `v4.0.2`)
* Redis (`redis:7-alpine`, however sidekiq UI shows 6.0.10?!)
* No elasticsearch

**Comment by lilithmooncohen** [comment]
Seeing the same

**Comment by magsol** [comment]
Seeing the same, though my specifications are different:
 - helm setup
 - Mastodon 4.0.2
 - Redis 7.0.7
 - Using OpenSearch rather than ElasticSearch

These error messages appear in the Sidekiq UI maybe half a dozen times a day for me? That may or may not be relevant information, considering my instance has all of 2 users on it.

But yeah, the attached screenshot is the extent of the details in the sidekiq UI. 

<img width="830" alt="Screenshot 2022-12-19 at 11 03 22 AM" src="https://user-images.githubusercontent.com/135417/208468419-e4962fe4-8f78-4350-b9a4-2ffe9ee576fa.png">

**Comment by Gakamine** [comment]
2024 and I still have the same issue.
Do you have any update ? How did you fix this ?
Thank you!

**Comment by Gakamine** [comment]
In case someone still has this issue, I was able to solve it by simply regenerating the `VAPID_PRIVATE_KEY` and `VAPID_PUBLIC_KEY` in the env file.
The documentation is available here:
=> https://docs.joinmastodon.org/admin/config/#vapid_private_key

**Comment by ThisIsMissEm** [comment]
This could also come from the Web::PushSubscription having invalid base64 `[:keys][:p256dh]` or `[:keys][:auth]` which are expected to be base64 when the subscription is created, however, this isn't actually validated anywhere.

**Comment by ThisIsMissEm** [comment]
In Mastodon 4.3, you'll now receive an error when attempting to create the push subscription, if the supplied keys are not usable (we actually test whether we can use them to encrypt a message during the Web::PushSubscription validation step)

So this should hopefully be resolved — though there's currently no job to purge old subscriptions that just aren't valid yet.
