### ISSUE TITLE
Add a confirmation button to the search box

### ISSUE THREAD

**Issue by salty-horse** [mastodon/mastodon#21494]
### Pitch

The search should have a UI element you can click to initiate the search, after entering a search term.

### Motivation

Currently, the only way I could find  to "initiate" a search is by pressing the enter key.
It's customary (and maybe also best practice? I'm not an expert) to also have some kind of UI element that you can click, such as:
* A button labeled "Search".
* An icon (magnifying glass?)
* A drop-down list that appears with previous/suggested search terms, with the first option being the entered term.

**Comment by Gargron** [comment]
Fixed in #24305
