### ISSUE TITLE
the documentation cannot be easily viewed in Android portrait mode.

### ISSUE THREAD

**Issue by CharlesGodwin** [mastodon/mastodon#21498]
### Steps to reproduce the problem

1.Open https://docs.joinmastodon.org/ on android phone
2.Use portrait mode
3.None of the right hand side text is visible, and have to scroll down past ALL the index topics to see the test. That's a long distance.
...

### Expected behaviour

The cursor/screen should reposition at the topic's text.

### Actual behaviour

Not much. Click on a topic, nothing appears to change except the colour of the topic I touched,

### Detailed description

The documentation is unreadable in portrait mode on an Android device. The text is not positioned and it's a very, very, very long scroll to the text.

A Top link would help to return to the topics list too.

### Specifications

Android 13 Update November 5, 2022
Pixel 5
Chrome 107.0.5304.105
Google Support Services Version 3.21.1

**Comment by trwnh** [comment]
wrong repo, you want mastodon/documentation

there is a PR for collapsing the menu https://github.com/mastodon/documentation/pull/1061

**Comment by CharlesGodwin** [comment]
Thanks. I'll go there.
