### ISSUE TITLE
 Unstyled avatars and attachments on Safari iOS after upgrade to 4.0.2

### ISSUE THREAD

**Issue by capcom1701** [mastodon/mastodon#21522]
### Steps to reproduce the problem

1. Upgrade and precompile.
2. Restart mastodon services.
3. Open instance on safari browser on iOS device.
...

### Expected behaviour

Webpage should maintain styles on various browsers.

### Actual behaviour

Avatars and attachments are full-sized and on top of each other.

### Detailed description

Troubleshooting issue:
After the update, everything looks fine on Safari and Chrome on my MacBook, but the pages are unstyled on the iOS browser.
I've gone to other instances to make sure it wasn't some setting on my phone, but other instances look fine, so I'm convinced its an issue with my server.

I've tried both 
`RAILS_ENV=production bundle exec rake assets:precompile `
and
`RAILS_ENV=production bundle exec rake assets:clobber `

The precompile kept giving me an error about the yarn.lock file, so I dumped that file and re-ran yarn install.

The last precompile run gave me this output:

![output](https://user-images.githubusercontent.com/8906731/203659783-e9260cc6-9188-4249-ae2b-6ac44aa3d062.jpg)

I restarted services. The page still looks bad in the iOS browser.

Here's a shot of what I'm seeing when I open the instance in the iOS browser:
![IMG_0768](https://user-images.githubusercontent.com/8906731/203659911-9da736e6-c141-44ef-a04f-acf4f4c1a842.jpg)

I appreciate any help anyone can give on this. 

### Specifications

Mastodon | 4.0.2
Ruby | 3.0.4p208
PostgreSQL | 15.1
Redis | 5.0.7

iOS 16.1.1

**Comment by ineffyble** [comment]
Have you tried deleting your iOS cache/browsing data?

**Comment by capcom1701** [comment]
That was it. Precompile was working and I wasn't seeing it. Thank you, I shall now self-facepalm.
![intro-import](https://user-images.githubusercontent.com/8906731/203685037-e7301f75-23af-450e-a426-960867116cff.jpg)
