### ISSUE TITLE
Inconsistent Ukrainian localization related to muting user

### ISSUE THREAD

**Issue by NerveClasp** [mastodon/mastodon#21544]
### Steps to reproduce the problem

1. Choose to mute user in menu (reads "Приховати {username}")
2. See "Нехтуавти" button in the bottom left (button is misspelled - should read "Нехтувати" and inconsistent) 
3. See "Невизначено" as the first option in the dropdown, which means "Undefined"; should read "Назавжди" which is a better translation for indefinite

### Expected behaviour

localization is correct and consistent

### Actual behaviour

there are mistakes, inconsistencies, and wrong translation

### Detailed description

"Нехтувати" and "Приховати" is used for the same thing, which might confuse users. There is a typo in "Прихоавти" button. The first dropdown option should say "Назавжди" which means "forever" in Ukrainian, instead of "Невизначено" which means "undefined".
![hide_menu](https://user-images.githubusercontent.com/7347253/203701820-dab014b6-7cb9-4219-80df-0e14289badca.png)
![hide_misspelled_button](https://user-images.githubusercontent.com/7347253/203701836-ab673941-28ed-42a5-aeee-e7302fff4c0b.png)

Moreover "нехтувати" bares a slight negative connotation, like "ignore after a fight" or "neglect", whereas "приховати" is more neutral

### Specifications

Mastodon 4.0.2

**Comment by ineffyble** [comment]
As mentioned on the PR, localisation fixes should be submitted at the CrowdIn https://crowdin.com/project/mastodon

**Comment by NerveClasp** [comment]
@ineffyble sorry for the late reply - did not have elextricity for a few days. Submitted fixed translations at Crowdin. Thanks!
