### ISSUE TITLE
Extra slash causes OCR to fail on Wasabi

### ISSUE THREAD

**Issue by nmalcolm** [mastodon/mastodon#21541]
### Steps to reproduce the problem

1. Configure Wasabi as the CDN
2. Upload an image
3. Try to use OCR text recognition for alt text

### Expected behaviour

It should extract the text

### Actual behaviour

It fails without an on-screen error

### Detailed description

In `app/javascript/mastodon/features/ui/components/focal_point_modal.js` we have this line:

```
langPath: `${assetHost}/ocr/lang-data/`,
```

However, when it tries to load the trained data it loads "./eng.traineddata.gz", which results in the URL being `/ocr/lang-data//eng.traineddata.gz` with double forward slashes.

Wasabi doesn't like this, and throws a 404 not found error because it cannot find the key. Removing the extra slash fixes the problem.

### Specifications

Mastodon 4.0.2

**Comment by vmstan** [comment]
@nmalcolm is this still an issue for you on newer versions of Mastodon?
