### ISSUE TITLE
Allow to change default landing page

### ISSUE THREAD

**Issue by dorianim** [mastodon/mastodon#21567]
### Pitch

I'd be nice if it was possible to change the default landing page for non-logged in users.

### Motivation

Currently, all users land on the "explore" page, but I'd like them to land on the about page without disabling trends completely.
Our explore page looks very empty at the moment. I don't want potential new users to land on an empty page when visiting the instance for the first time. But I also don't want to just disable trends for all users.

**Comment by ClearlyClaire** [comment]
See #20808

**Comment by dorianim** [comment]
Ah, sorry. I didn't find that one
