### ISSUE TITLE
Verification of link fails for pages that contain multiple rel="me" links

### ISSUE THREAD

**Issue by jtayler** [mastodon/mastodon#21562]
### Steps to reproduce the problem

1.Add two different mastodon profile rel="me" links 
2.Only the FIRST listed will verify
3.The second will fail, if you reverse their order the other will verify
...

### Expected behaviour

The parser should examine all rel="me" links for a match

### Actual behaviour

The parser seems to stop after comparing the first rel="me" link it matches

### Detailed description

The parser should examine all rel="me" links for a match it seems to stop after the first listing

It seems very similar to this report https://github.com/mastodon/mastodon/issues/20944 which I also notice is true for the username which is case-insensitive and so the parser should not differentiate between @UsErNaMe and @username because they are both the same.

### Specifications

This does not seem to be dependent on version

**Comment by AlanBell** [comment]
It does check all rel=me links for an exact match, and for the first one it will resolve it in case a link shortener is being used - so it follows the link and any redirects then checks that the location it arrived at is the profile page.
It also only works with https pages now.
Got an example page with multiple links?

**Comment by jtayler** [comment]
Thanks, let me see. If I check this Mastodon profile: https://infosec.exchange/@mikehill  the user lists two links and both should indicate verified status.  The "TruAnon" link lists a different Mastodon profile first, IOC Exchange and if you visit that profile this same link seems to be working:  https://ioc.exchange/@MikeHill  What do you think could be wrong?

**Comment by AlanBell** [comment]
the href in theTruAnon page isn't to the https profile -> "http://infosec.exchange/@mikehill"

**Comment by AlanBell** [comment]
in fact they are both to the http profile, however the first link would be followed and it will redirect to the https version and match.

**Comment by jtayler** [comment]
yes, the links work but I guess they do redirect. I'll see if this resolves this issue, hopefully it does.

**Comment by AlanBell** [comment]
You will have to re-save the mastodon profile after fixing it to get the server to attempt to verify the links again.

**Comment by jtayler** [comment]
Ok, in my testing a change to https links seems to work in two places at once. a bit mysterious logical indicators from testing, so I push back to the user to report again if they have trouble after this change. If they report it works, I'll just close out this ticket if it's not already closed.

I do wonder, it seems the redirect into https should verify, since the bare http links seemed to click and route as expected.

**Comment by trwnh** [comment]
I think the logic is that *only* HTTPS links will be considered, and this check happens before any redirect -- meaning that HTTP links never get checked for a redirect.
