### ISSUE TITLE
Can't sign in from Safari/Chrome browser

### ISSUE THREAD

**Issue by liviu1406** [mastodon/mastodon#21594]
### Steps to reproduce the problem

I am trying to log into the platform from my laptop but without much luck. It just simply says invalid email address or password - which I have just changed. It doesn't make any sense.

### Expected behaviour

Let me log in.

### Actual behaviour

Invalid email or password

### Specifications

Using Safari and Chrome browsers in latest macOS Ventura.

**Comment by nmalcolm** [comment]
Make sure you're logging into the right server. You can't use your email and password to login to any server, it has to be the one you joined.

**Comment by ineffyble** [comment]
As mentioned, make sure you are logging in to the right Mastodon instance/server. If that's not working, you'll need to reach out to the admin of that server for assistance.
