### ISSUE TITLE
Web UI - Accessibility - Color Contrast - Purple Haze Theme

### ISSUE THREAD

**Issue by lefou23** [mastodon/mastodon#21601]
### Steps to reproduce the problem

1. Switch to Purple Haze Theme
2. Return to Mastodon

### Expected behaviour

Text and links in left column footer area should be visible.

### Actual behaviour

Cannot see links or text in left column footer area.

### Detailed description

When using Purple Haze Theme, the left column footer text and links are virtually invisible due to color contrast issues.
Current view:
<img width="1792" alt="Purple Haze Theme - current view" src="https://user-images.githubusercontent.com/1542373/203887395-58562593-f258-480c-a8bb-31c7e78c8003.png">

Potential visibility after colors are fixed:
<img width="1792" alt="Purplb Haze Theme, correction" src="https://user-images.githubusercontent.com/1542373/203887591-1d9d53e2-a555-4e14-a80c-488d35dc06b1.png">

Here were my temporary color adjustments:
.theme-purple-haze .column-link {
background: #ebccff;
color: #69428f; # no change
}

.theme-purple-haze .link-footer p {
color: #e6ccff;
margin-bottom: 20px; # no change
}

.theme-purple-haze .link-footer p a {
color: #cc99ff;
text-decoration: underline; # no change
}

### Specifications

Mastodon v4.0.2

Browser: Safari Version 16.1 (18614.2.9.1.12)
Mac OS: 13.0.1 (22A400)

**Comment by trwnh** [comment]
Purple Haze is not an official Mastodon theme -- ask your admin to fix their custom theme
