### ISSUE TITLE
Add API to store/retreive timeline "bookmark" info, that would facilitate transition between apps

### ISSUE THREAD

**Issue by andraz-kozelj** [mastodon/mastodon#21613]
### Pitch

A multitude of apps, also 3rd party, across platforms (mobile, desktop, different OSes) are used by a single user. Transition is not smooth, because some apps load timelines from the point where you left off the last time you were using that individual device, regardless of what you've been doing in the meantime on other platforms/devices.

Use-case
I'm using Mastonaut on my macOS, I close it, it sends the information where I left off to the server. On my way, I open up my Mastodon client on mobile, it reads the "bookmark", loads the content and displays the timeline at the point where I left off.

### Motivation

Less time wasted to sync between platforms/apps manually, enthusiasm is preserved, no double content reading...

**Comment by connyduck** [comment]
this api exists https://docs.joinmastodon.org/methods/markers/

**Comment by andraz-kozelj** [comment]
Will the web app honor this?
