### ISSUE TITLE
Reveal real IP of Cloudflare CDN

### ISSUE THREAD

**Issue by KumaTea** [mastodon/mastodon#21633]
### Pitch

Lots of poeple host their mastodon instance behind an CDN such as Cloudflare, to speed up connections from all over the world, and avoid DDoS, and so on.

But following the guide users will see their session (`auth/edit` & `settings/login_activities`) are from CF's IPs:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/36222458/204049106-302685f6-3dcd-4994-adb0-cd7feeb45591.png">

And they will be notified once it changes, which happens every time a new connection is established (maybe)

<img width="739" alt="image" src="https://user-images.githubusercontent.com/36222458/204049258-b9ea167c-da13-45b7-abc6-4e8419e1b3bd.png">

### Motivation

[CF's official docs](https://support.cloudflare.com/hc/en-us/articles/200170786-Restoring-original-visitor-IPs) does not help at all on this issue.

While [this post](https://discourse.joinmastodon.org/t/any-way-of-getting-a-true-users-ip-while-using-cloudflare-and-nigix/3810/4) by [Bobby99as](https://discourse.joinmastodon.org/u/Bobby99as) on Mastodon Meta Discussion Board works like a champ:

> fixed by removing
`proxy_set_header X-Real-IP $remote_addr;`
`proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`
and adding
`proxy_pass_request_headers on;`

![image](https://user-images.githubusercontent.com/36222458/204049703-ba00a750-a0f6-4cd7-8258-ae87ba4c221c.png)

That saved my day.

It would be really nice if these modification can be documented and added into the default nginx config.

**Comment by untitaker** [comment]
Those changes must not be in the default config. If the server then does not end up using Cloudflare it would allow a client to spoof their IP by sending their own X-Forwarded-For header. I do not know of a way to build a general purpose nginx config without leaving that hole open.

**Comment by afontenot** [comment]
Yeah, this probably falls under individualized deployment stuff. Probably a good idea to mention it in the docs though.

And yes, with spoofing there are several footguns here. For example with the config shown above, if the server is not properly configured to disallow connections that bypass Cloudflare (it is *very* easy to accidentally leak the true server IP), then the client will be able to spoof any IP once again. (I'm also not totally sure which incoming headers Cloudflare strips, so `proxy_pass_request_headers` might be unsafe as well.)

To prevent spoofing you have to configure the server to prevent connections from non-Cloudflare, or minimally tell nginx to only let Cloudflare IPs set `X-Forwarded-For`. Both are outside of what Mastodon would be able to do with a config file change.

**Comment by KumaTea** [comment]
> it would allow a client to spoof their IP

You're right... I do not really understand how `X-Forwarded-For` works but I make sure my server only accepts CF's IPs.

I just temporarily disabled that and connected by its real IP and the session page shows the **frontend** IP.

![I host the frontend and backend servers in a lan net](https://user-images.githubusercontent.com/36222458/204077317-ecd6fc95-c152-4621-a24b-8c17e3c0ebd0.png)

---

But maybe it's a good idea to just mention this, and add comments in [the config file](../blob/main/dist/nginx.conf)?

```
  location @proxy {
    proxy_set_header Host $host;
    # If you host your instance behind an CDN which hides your server's IPs
    # uncomment the following line
    # proxy_pass_request_headers on;
    # and comment the following **TWO** lines
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # MAKE SURE YOU DENY ALL CONNECTION EXCEPT YOUR CDN
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Proxy "";
    proxy_pass_header Server;
```
