### ISSUE TITLE
Extended Markdown parsing in messages

### ISSUE THREAD

**Issue by PointyFluff** [mastodon/mastodon#21658]
### Pitch

Reading code in black and white was a nightmare in 1991 and it's no better, now.

```rust
fn main() {}
``` 

style extended markdown would vastly improve readability and, I would argue, help with accessibility.

### Motivation

Why: To improve post readability

Who: Anyone who posts code snippets.

**Comment by robsonsobral** [comment]
#18958

**Comment by PointyFluff** [comment]
DOH! 🤦
