### ISSUE TITLE
Link Twitter handles of the form `@user@twitter.com`

### ISSUE THREAD

**Issue by j9t** [mastodon/mastodon#21668]
### Pitch

With many Mastodonians coming from Twitter, having ties to Twitter, and cross-posting content to and from Twitter, it would be helpful if Twitter handles of the form `@user@twitter.com` were similarly resolved as Mastodon handles, i.e., be made accessible by pointing to `https://twitter.com/user`.

### Motivation

The change would make especially current timelines, with many retoots and postings referring to Twitter more usable and useful. (Compare to [an example of the current handling](https://mas.to/@frontenddogma/109409806284638853), which isn’t very useful.)

Expanding Twitter references might also make it easier and more interesting for people to migrate, because it builds some form of a bridge.

And the change would also be a meaningful signal in terms of the power of an open Web, where such links are welcome and embraced.

**Comment by rbairwell** [comment]
I think that perhaps this should be a per server "Special @ name handling" setting - so admins can set up mapping so:
@%name%@twitter.com maps to https://twitter.com/%name%
@%name%@facebook.com maps to https://facebook.com/%name%
@%name%@linkedin.com maps to https://linkedin.com/in/%name%
to allow for future networks/custom settings (perhaps a big company would like to say "Oh yes, contact @ frank @<subdivison> for that" and want "<subdivison>" to link - without a TLD - to example.com/staff/frank

If the links are created on the users instances (i.e. where the post originated from) there shouldn't be too many issues with mapping etc - in fact, I believe that the backend could already support this using the HTML markup it creates for the content. So it'll "just" need the admin interface for the mappings to be stored, the database table creating and then intercepting/parsing usernames where it cannot find a corresponding .well-known/webfinger account or similar (to handle if say Twitter comes to the Fediverse the links will then automatically update from that point on).

Disadvantage: It'll make the job of auto-suggesting/completing usernames even more difficult than it is now for client apps.

**Comment by Cassolotl** [comment]
I opened this in 2017: *Link @username@twitter.com to Twitter profile pages #1849* And it was closed without action in 2018 by Gargron. Not saying this to put you off, maybe he's changed his mind, you never know! Just thought it might be helpful background. :)

**Comment by j9t** [comment]
Pulling this suggestion ([prompt](https://twitter.com/TwitterSupport/status/1604531265419591681)).

**Comment by rokejulianlockhart** [comment]
@j9t, that tweet has been deleted. What did it state?

**Comment by j9t** [comment]
> @j9t, that tweet has been deleted. What did it state?

Fortunately, the tweet was archived—it’s [the thread](https://web.archive.org/web/20221218175822/https://twitter.com/TwitterSupport/status/1604531265419591681) in which Twitter Support announced not to allow links to Mastodon and other platforms.
