### ISSUE TITLE
Website link verification is a fraught process. Can it be simplified or explained better? 

### ISSUE THREAD

**Issue by PrecisionWordcraft** [mastodon/mastodon#21697]
### Steps to reproduce the problem

1. I added the exact link as displayed on my profile page to my website's static index.html. (I use Storyblok, but links within the static index.html "should" work. I can see the link on my website now.)
2. The link to my website on my profile page specifies "HTTPS" as recommended in the Mastodon docs. 
3. My website is still not verified. I've refreshed my Mastodon profile page like five times. 
...

### Expected behaviour

The link to my website should show up as verified.

### Actual behaviour

It does not show up as verified. 

### Detailed description

The process to enable website verification through the link on the profile page is apparently quite fragile or is much more complicated than described in the online help and documentation.

I am told that links embedded within StoryBlok components, for example, won't be verified. But the docs mention nothing about the limitations of working with content management systems, which is how most people's web sites are rendered these days.

I have had to get my website developer involved to help me debug why the verification isn't working. This should have been as easy as adding a link to my site's index.html. But it's not. 

**How can we help people to make website verification easier**? Link verification is a pretty important piece of the security story here and if it's this easily messed up, users won't bother with it. 

### Specifications

Mastodon 4.0
Firefox 107.0
Windows 11

**Comment by nightpool** [comment]
The documentation unfortunately makes it very clear that a `rel=me` link is required. This is necessary for security purposes, unfortunately. If you have any suggestions about how to make it clearer, they would be appreciated, but unfortunately we aren't able to relax the security restrictions

**Comment by trwnh** [comment]
It may be that Storyblok is doing something weird with the link, yes, but another possibility is that you didn't save your profile after putting the link on the page?

**Comment by PrecisionWordcraft** [comment]
Link is showing up as verified now. It looks like there's a bit of a delay between adding the link and the verification process being completed. 

That might be worth noting in the docs - I'll make a PR. The Storyblok / CMS limitation should also be noted in the docs, and I'll do that.

**Comment by trwnh** [comment]
@PrecisionWordcraft added as part of https://github.com/mastodon/documentation/pull/1060/commits/ef91c5514740cab248c194988ad2b9f2d399bf54 :)
