### ISSUE TITLE
Mastodon will highly delay fetching media on edited posts

### ISSUE THREAD

**Issue by kescherCode** [mastodon/mastodon#21698]
### Steps to reproduce the problem

1. Make a post on a remote instance
2. Fetch it on mastodon.social or any other Mastodon instance (or have it federated to you)
3. Edit the post on the remote instance, deleting and reuploading either the same image or a different one (doesn't matter) and perhaps changing the image description
4. Fetch the post again (or have it federated to you)
...

### Expected behaviour

The image showing up

### Actual behaviour

The image is shown as a remote link, or as an empty image in apps as the media_proxy fails to fetch it for several attempts

### Specifications

51a33ce77a32b85eaff37670c40a497aaef13e18

**Comment by kescherCode** [comment]
I originally intended to title this "will not fetch media on edited post" because it really takes a while. The instance was not busy with other processing either, and this happens consistently on edited posts.

**Comment by rrgeorge** [comment]
In my experience it never fetches media for posts where the media was added/changed in the edit.

**Comment by kescherCode** [comment]
@rrgeorge I was under that same inpression shortly before sending the issue, but then I noticed "wait, that post now has media again. What is going on?"

**Comment by rrgeorge** [comment]
> @rrgeorge I was under that same inpression shortly before sending the issue, but then I noticed "wait, that post now has media again. What is going on?"

Are you sure it wasn’t after your media retention would’ve switched it to on-demand?

I have a post I’m looking at that was edited 40 mins ago to add media, that says “Not Available”. I’ll keep looking at it periodically to see if it ever shows up…

**Comment by kescherCode** [comment]
@rrgeorge media retention on-demand? no, mine's set to 180 days.

**Comment by rrgeorge** [comment]
I see. It seems to update the media after an hour.

**Comment by ClearlyClaire** [comment]
Fixed by #21565
