### ISSUE TITLE
Liberapay integration

### ISSUE THREAD

**Issue by goliv04053** [mastodon/mastodon#21699]
### Pitch

Add support to people give support to other people on Mastodon using Liberapay. Give the user the choice to put a liberapay button on the profile

### Motivation

Example: John is a content producer in a Mastodon instance and without algorithms from the other plataform which he was he now he don't got support to continue producing. With a Liberapay support he can put a direct option in his profile to people pay him and help him to build new content.

**Comment by rbairwell** [comment]
You can already add links to third party services like this in your Mastodon profile/bio. I can't see why a code change would be required (and if a special case/icon/section was made for Liberapay, why shouldn't one be made for Paypal, or Stripe, or... : that's either a lot of work maintaining all the options or "discrimination" for excluding somebody's favourite payment platform)

**Comment by goliv04053** [comment]
I gave this suggestion because it's completely free and open source so freedom with freedom.

**Comment by goliv04053** [comment]
Paypal and Stripe aren't open source

**Comment by ineffyble** [comment]
Related to #12385 (paid content) and tangentially related to #12794 (that one is focused on donating to server admins, not users)

**Comment by goliv04053** [comment]
No, i'm not saying to implement paid content. I'm saying that the idea is to implement a way to give support to other users without the paid content.

**Comment by YJSoft** [comment]
@goliv04053 Just add link to profile meta will be enough. No need to implement anything else.
