### ISSUE TITLE
Blocking domain via API does not appear to function

### ISSUE THREAD

**Issue by rrgeorge** [mastodon/mastodon#21718]
### Steps to reproduce the problem

1. Create OAuth Token for admin:read admin:write
2. Post a `domain=somedomain` to `/api/v1/admin/domain_blocks`
3. Response is: `{}` -- *There is some validation being done, because if domain was invalid, you do get a `{"error":"Validation failed: Domain is invalid, Domain is not a valid domain name"}`*
4. Check in federation moderation panel, observe domain was not added

### Expected behaviour

For the domain to be added to the domain blocks as posted

### Actual behaviour

Nothing

### Detailed description

Posting domain blocks to the `/api/v1/admin/domain_blocks` does not appear to do anything. 

### Specifications

Mastodon | 4.0.2
Ruby | 3.0.4p208
PostgreSQL | 13.8
Redis | 6.0.16

curl 7.74

**Comment by ineffyble** [comment]
I don't seem to be able to replicate this locally. 

```
$ curl --header "Authorization: bearer XXX" http://127.0.0.1:3000/api/v1/admin/domain_blocks --verbose --data "domain=mastodon.online"

{"id":"2","domain":"mastodon.online","created_at":"2022-11-27T06:27:21.644Z","severity":"silence","reject_media":false,"reject_reports":false,"private_comment":null,"public_comment":null,"obfuscate":false}
```

Are you able to check your mastodon web logs to see what's logged when you make the call?

**Comment by rrgeorge** [comment]
That command just returns `{}` for me.
The only log entry is: 
`Nov 27 00:49:00 helios bundle[2343300]: [b968ee37-6f2b-49f7-b070-cde51b5b6a65] method=POST path=/api/v1/domain_blocks format=*/* controller=Api::V1::DomainBlocksController action=create status=200 duration=10.43 view=0.55 db=1.70`

**Comment by ineffyble** [comment]
Are you able to have a look at what rows are in the `domain_blocks` table in postgres?

**Comment by rrgeorge** [comment]
It only shows rows manually entered via the web interface

**Comment by rrgeorge** [comment]
OMG. I just realized i had `/api/v1/domain_blocks` not `/api/v1/admin/domain_blocks`
