### ISSUE TITLE
Toot content removed from resolved report if toot is deleted after resolution

### ISSUE THREAD

**Issue by adistav** [mastodon/mastodon#21721]
### Steps to reproduce the problem

1. Toot
2. Report toot
3. Look in report: toot content appears there
4. Resolve the report
5. Look in report: toot content appears there
6. The original user deletes the toot
7. Look in report: toot content no longer appears there, as if the toot never existed

### Expected behaviour

The toot content should appear in the report indefinitely if deleted after the report is resolved. 

### Actual behaviour

Toot content disappeared from resolved report after toot is deleted.

### Detailed description

Toot content still appears in report if the moderator deleted the toot.
Toot content still appears in report if the user deleted the toot after the report was opened but before it was resolved.
Toot content no longer appears in report if the user deleted the toot after the report was opened but before it was resolved.
This is inconsistent.
Also, it is important to keep reported toots' content, in order to keep track of issues with users, and to audit moderators' actions.

### Specifications

Mastodon | 4.0.2
Ruby | 3.0.4p208
PostgreSQL | 15.1
Redis | 7.0.5

Firefox on Android:
107.1.0 (Build #2015915067), a4c625827+
AC: 107.0.7, 7d69de3da4
GV: 107.0-20221110173214
AS: 94.2.2

**Comment by vmstan** [comment]
@adistav does this persist in newer versions of Mastodon?
