### ISSUE TITLE
Missing RSS URL in href attribute of <link> tag from html <head> section of profiles. RSS feed not detectable.

### ISSUE THREAD

**Issue by StigNygaard** [mastodon/mastodon#21731]
### Steps to reproduce the problem

1. View html-source on a Mastodon Profile page, like f.ex. my profile https://mastodon.world/@stignygaard
2. Find &lt;link&gt; tag with attribute: type='application/rss+xml'.
3. With Mastodan server software v4.0.2 it will most likely look like this with empty/blank href attribute:
&lt;link href='' rel='alternate' type='application/rss+xml'&gt;

### Expected behaviour

Expected something like this which I have seen working on instances running older versions of Mastodan server: &lt;link href='https://mastodon.world/@stignygaard.rss' rel='alternate' type='application/rss+xml'&gt;

### Actual behaviour

With Mastodon server 4.0.2 I see: &lt;link href='' rel='alternate' type='application/rss+xml'&gt;

### Detailed description

The &lt;link&gt; tag that can make RSS feeds discoverable by bots, browsers or browser extensions supporting it, is present on profile pages on Mastodan servers, but is missing the vital URL in the href attribute.

It looks like it depends on version of server software. The following profile which - in the moment of writing this - is located on an instance running server software 3.4.6 has it correctly defined:
https://mastodon.cloud/@timbray
&lt;link href='https://mastodon.cloud/@timbray.rss' rel='alternate' type='application/rss+xml'&gt;

However on my own and most other profiles/instances (Typically on server software v4.0.2) the URL is missing in href attribute:
https://mastodon.world/@stignygaard
&lt;link href='' rel='alternate' type='application/rss+xml'&gt;

Disclaimer: I'm not an admin of Mastodan server myself. But after some investigation I believe it is related to the software version.

### Specifications

Mastodon 4.0.2

**Comment by afontenot** [comment]
I believe this was already fixed, Mastodon just hasn't shipped a new version yet. https://github.com/mastodon/mastodon/pull/20772
