### ISSUE TITLE
Searched-for hashtag does not appear in results

### ISSUE THREAD

**Issue by tomwalkr** [mastodon/mastodon#21753]
### Steps to reproduce the problem

In the web interface, search for a hashtag using the top-left 'Search or paste URL' input box. For example, `#css`.

### Expected behaviour

I would expect #css, the literal hashtag I searched for, to be the top result.

### Actual behaviour

It shows lots of hashtags beginning with the term instead, but not the actual hashtag.

### Detailed description

The result of searching for `#css` is:

> #CSS2022
> 0 people in the past 2 days
> #CSSTimeline
> 0 people in the past 2 days
> #cssPatterns
> 0 people in the past 2 days
> #CSSProfileHell
> 0 people in the past 2 days
> #cssChallenge2022
> 0 people in the past 2 days
> Load more

`Load more` loads hundreds more in similar vein that also all show '0 people in the past 2 days'.

I'm guessing that showing '0' for all is some kind of indexing issue, maybe instance-specific. But regardless of the indexing or popularity of a given hashtag, the literal hashtag I just searched for should always be the top result, or I should be given the option to go straight to it. Otherwise there is no way to go directly to a typed hashtag without editing the URL.

I have also tested with other hashtags and they seem to have the same issue, additionally I've seen other users asking about this issue. (I looked for a dupe here but found things that seem related eg https://github.com/mastodon/mastodon/issues/21409 but not quite this issue.)

### Specifications

Mastodon v4.0.2 
(web frontend on mastodon.social)

Firefox 107.0
macOS 12.6

**Comment by connorshea** [comment]
Probably a dupe of #17494 / potentially fixed by #21315

**Comment by tomwalkr** [comment]
You are right, dupe of https://github.com/mastodon/mastodon/issues/17494 / would be fixed by https://github.com/mastodon/mastodon/pull/21315

There's loads of stuff about Elasticsearch on that other thread but it's not really relevant to be honest, the searched-for term should always be top (which is what the patch does).
