### ISSUE TITLE
API: ScheduledStatus serializer returns application ID (as integer)

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#21777]
### Steps to reproduce the problem

GET /api/v1/scheduled_statuses or POST /api/v1/statuses?scheduled_at=...&...

### Expected behaviour

application ID is returned as a string or not at all

### Actual behaviour

application ID is returned as an integer

### Detailed description

https://github.com/mastodon/mastodon/blob/cec1e902e006730f68bde0a4334e5b819a12a475/app/serializers/rest/scheduled_status_serializer.rb#L13

The line above implies that the application_id should not be returned, but it is:

```json
{
    "id": "1",
    "scheduled_at": "2022-11-30T00:00:00.000Z",
    "params": {
        "text": "test post",
        "media_ids": null,
        "sensitive": null,
        "spoiler_text": null,
        "visibility": null,
        "language": null,
        "scheduled_at": null,
        "poll": null,
        "idempotency": null,
        "with_rate_limit": false,
        "in_reply_to_id": null,
        "application_id": 2
    },
    "media_attachments": []
}
```

### Specifications

main

**Comment by trwnh** [comment]
For that matter, should `params[scheduled_at]` be returned either? And why is it null?

**Comment by trwnh** [comment]
And the `in_reply_to_id` is also an integer, when status IDs are supposed to be strings in theory

**Comment by trwnh** [comment]
@nikclayton worth noting that on #33159 and/or https://github.com/mastodon/documentation/pull/1572 maybe?

**Comment by nikclayton** [comment]
Less of a concern for application_id as it's not documented in the output. But the change from int to string absolutely requires an API version bump.

I.e, this PR should be reverted, and a new PR that makes the same change at an API endpoint with a different version needs to happen.

**Comment by ClearlyClaire** [comment]
> I appreciate the fix, but this is a change to the API's documented return values (in_reply_to_id is documented as being an int).

There seem to be some confusion here. This is not about `in_reply_to_id` (and I can't find where it would be documented as being an int).

> Less of a concern for application_id as it's not documented in the output. But any change from int to string in the documented API absolutely requires an API version bump.

This is not a change from `int` to `string` but a removal of an attribute that should not have been included and which had no use to clients. I can't think of a single reason why a client would have *used* it.

That being said, it *was* documented, and I could imagine clients ingesting the attribute and expecting it to be here even if they do not ever do anything with it, so I'm not sure what we should be doing here.

**Comment by nikclayton** [comment]
I'm on mobile, so was going off the discussion rather than the actual change. Sorry for the confusion there.

https://docs.joinmastodon.org/entities/ScheduledStatus/#params-in_reply_to_id is documented as being an int, not a string.

The rule for API version bumps is that adding a property does not require a version bump, but changing a property's type does.

Removing or renaming (which is just a remove followed by an add) a property also requires a version bump.

**Comment by ClearlyClaire** [comment]
The `in_reply_to_id` thing is still out of topic for this issue, which is only about `application_id`. The related documentation PR (https://github.com/mastodon/documentation/pull/1572) also only changed `application_id` and not `in_reply_to_id`, which has been changed neither in implementation or documentation.

That being said, `in_reply_to_id` being an integer *is* an issue, as with our snowflake IDs, it's way above Javascript's `Number.MAX_SAFE_INTEGER`. It seems to be allowed by JSON itself though, as JSON does not seem to set limits on numbers.

I'm not sure how we should address this, but if we ever do a `/api/v2/scheduled_notifications`, we should really fix that.
