### ISSUE TITLE
API: Uncaught 500 error in canonical_email_blocks/test

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#21774]
### Steps to reproduce the problem

`POST /api/v1/canonical_email_blocks/test`

### Expected behaviour

422 validation failed: email and/or canonical_email_hash are required

### Actual behaviour

500 HTML NoMethodError undefined method `downcase` for nil:NilClass

### Specifications

main

**Comment by Narasimha1997** [comment]
I would like to work on this issue.
