### ISSUE TITLE
Time displayed more that 24h

### ISSUE THREAD

**Issue by kkretsch** [mastodon/mastodon#21781]
### Steps to reproduce the problem

With the current 4.0.2 version I just saw toot times posted like 24:31 when it was short after midnight.

### Expected behaviour

I would expect 00:31

### Actual behaviour

I see 24:31

### Specifications

Mastodon 4.0.2
![2022-11-28 08_36_40-Window](https://user-images.githubusercontent.com/1115638/204220592-16bb2193-bd34-4ebb-b6ca-4de535ed885b.png)

**Comment by kkretsch** [comment]
And as I just saw: The date is also one day +1. I see toots from the future!
System is a fresh setup of 4.0.2 and runs fine otherwise. Using  Ubuntu 22.04.1 LTS.
Toots from some minutes earlier are formatted OK:
![image](https://user-images.githubusercontent.com/1115638/204221698-92237ff7-31ee-49ed-af8d-e14afb5532e0.png)

**Comment by Cassolotl** [comment]
Duplicate of *Timestamp issue with UI lang + browser lang #18414* (May 2022)?

**Comment by kkretsch** [comment]
Yes, I did try to find any existing ticket but failed. I close this so the referred one can be used instead.
