### ISSUE TITLE
Upgrade Digital Ocean droplet to v.4

### ISSUE THREAD

**Issue by aretchless** [mastodon/mastodon#21807]
### Pitch

The Digital Ocean droplet is appealing in as far as it provides an administrator with a ready-to-use instance of Mastodon. Since it [currently installs version 3.5](https://marketplace.digitalocean.com/apps/mastodon), I've been told that it would be up to the administrator to perform their own upgrade to v4. This is complicated enough to deter would-be administrators like myself, who don't currently have time to get into the nitty gritty of a major version upgrade. 

It [sounds like](https://blog.joinmastodon.org/2019/04/mastodon-now-available-on-digitalocean/) the droplet is maintained by the core Mastodon group. Apologies if it is not your responsibility.

### Motivation

New administrators would benefit from a simplified setup process for new instances.

**Comment by nehemiagurl** [comment]
I'm all in for the droplet to be on v4 (I remember struggling to upgrade from 3.3 to 3.5 when I made my instance there), but isn't this a request to make to *Digitalocean themselves*, rather than Mastodon?

**Comment by aretchless** [comment]
@nehemiagurl - based on the J[oinmastodon blog post ](https://blog.joinmastodon.org/2019/04/mastodon-now-available-on-digitalocean/), it sounds like the Digital Ocean droplet was created by the Mastodon team. Also, the digital ocean page says that Mastodon is providing support for the droplet.

**Comment by nehemiagurl** [comment]
ah, I understand. Thanks for the clarification!

**Comment by markratledge** [comment]
As of 12/1/22, the DO Droplet is at v4.0.2.

**Comment by aretchless** [comment]
Great. Thanks @markratledge!
