### ISSUE TITLE
No option to cancel reply composition

### ISSUE THREAD

**Issue by TymeForChange** [mastodon/mastodon#21808]
### Steps to reproduce the problem

1. Click reply icon to an original post.
2. Begin typing a reply. 
3. Reconsider sending the reply (before clicking the form submit button).
4. Draft message cannot be cleared. No option available. 

### Expected behaviour

Reply composition operation cancelled

### Actual behaviour

no option available

### Detailed description

When composing a reply to a Post: if user decides not to submit the reply, there is no obvious/easy way to cancel this operation.  Deleting the text one has typed, still leaves the OP in view awaiting a typed reply. Clicking away, such as giving focus to another element (e.g., clicking the PUBLISH button on top bar for composing a new post), does not clear the reply window.  In fact, if you click the PUBLISH button -- an action expected to load a new, blank post window -- a duplicate Reply composition window/column is created. 

(Have had to refresh the browser to clear it.)

PROBLEM: User could easily accidentally send a reply that they wished to abort before sending.
![scrReplyReconsider-bug](https://user-images.githubusercontent.com/56969001/204361380-b894d6e4-87a4-4e11-bf28-a41f565c3f37.png)

### Specifications

Mastodon v4.0.2
Advanced Web Interface
Windows 10 Pro, Opera

**Comment by afontenot** [comment]
I think you are looking for this button:

![204361380-b894d6e4-87a4-4e11-bf28-a41f565c3f37](https://user-images.githubusercontent.com/3870410/204378172-6cb2bf71-e3d6-42c5-a38d-b56d02f09f67.png)

It looks to me like something has gone wrong in your web browser, or maybe you're using a user script or something. The post you're replying to doesn't have enough contrast. I'm using the dark theme as well but replies look just fine (tested in the advanced interface in Firefox). The lack of contrast makes it harder to see the "x".

**Comment by TymeForChange** [comment]
D'oh!  I see it now that you've pointed it out. Yup, not enough contrast with the [x]. So, a noteworthy #accessibility issue?

**Comment by afontenot** [comment]
@TymeForChange Yes, probably. Does it look like that by default in your web browser? Do you see the same thing when you're not in advanced mode? It's very strange, I wonder if you're using something like system-wide dark mode or a browser addon that modifies stuff like this. In Firefox it's perfectly normal.
