### ISSUE TITLE
tootctl media remove fails due to rate limiting on OpenStack SWIFT

### ISSUE THREAD

**Issue by brookmiles** [mastodon/mastodon#21826]
### Steps to reproduce the problem

1. store media using OpenStack SWIFT (OVH standard object storage in this case)
2. run `tootctl media remove`

### Expected behaviour

media is removed without errors

### Actual behaviour

many "429 Too Many Requests" errors, media is not removed

### Detailed description

Attempting to use `tootctl media remove` with concurrency above 1 on OVH OpenStack SWIFT storage results in a constant stream of "Too Many Requests" errors.

Setting concurrency to 1 allows the process to complete successfully however, due to the low concurrency, removing media is currently taking me about 50% of the time it takes to accumulate new media, eg. running `media remove` once a day is now taking as long as 12 hours. I expect this will continue to increase.

I'm speculating that auth tokens are being requested for each individual file removal instead of being cached as mentioned in #4889

OVH documentation states: https://docs.ovh.com/us/en/storage/object-storage/pcs/capabilities-and-limitations/#validity-period-of-a-token

> Validity period of a token
> A token is valid for 24 hours.
> Too many token requests will return a 429 Too Many Requests error.

Which appears to correspond with the errors reported by `media remove`:

```
Progress: |========
Error processing 109379827889359998: Expected([200, 201]) <=> Actual(429 Too Many Requests)
excon.error.response
  :body          => ""
  :cookies       => [
  ]
  :headers       => {
    "Connection"        => "close"
    "X-IPLB-Instance"   => "..."
    "X-IPLB-Request-ID" => "..."
  }
  :host          => "auth.cloud.ovh.net"
  :local_address => "..."
  :local_port    => 36462
  :path          => "//v3/auth/tokens"
  :port          => 443
  :reason_phrase => "Too Many Requests"
  :remote_ip     => "51.68.65.247"
  :status        => 429
  :status_line   => "HTTP/1.1 429 Too Many Requests\r\n"
```

### Specifications

Mastodon	4.0.2
Ruby	3.0.4p208

**Comment by mrdaemon** [comment]
I reported the same as #21602 

If this helps you in the short term, running it with `--concurrency=1` ensures the operation completes without a 429

**Comment by brookmiles** [comment]
> I reported the same as #21602
> 
> If this helps you in the short term, running it with `--concurrency=1` ensures the operation completes without a 429

Ah, so you did, missed that somehow! Will close this as duplicate.
