### ISSUE TITLE
Enable opt-in for social discovery via email and phone

### ISSUE THREAD

**Issue by jaredzimmerman** [mastodon/mastodon#21837]
### Pitch

Allow users to add phone number(s) and email(s) for social discovery via device contacts. Pair with user permissions for "Allow discovery via contact info" and mutual discovery only (symmetric relationship required for discovery) 

### Motivation

Discovery via twitter bio is limited to users who add mastodon user names to twitter bios, and people will stop using twitter eventually.

**Comment by ineffyble** [comment]
The issue with this is that would only let you discover other Mastodon users on the same instance as you, which could be no one at all.

**Comment by rbairwell** [comment]
Yep, you'll need a central repository to lookup that sort of data (which goes against the Mastodon way of thinking) - and security precautions will need to be taken to ensure it can't be enumerated/"mined" for user data exactly how Twitter was (see https://web.archive.org/web/20221124080139/https:/twitter.com/chadloder/status/1595557696131911680 and https://kolektiva.social/@chadloder/109406380942373215 "Any Twitter account with "Let others find you by your phone" enabled in Discoverability settings is affected."). - so really big privacy failure there!

**Comment by jaredzimmerman** [comment]
I was 90% sure that would be folks' response, sounds like I have a next project then...
