### ISSUE TITLE
Peer-consensus-based instance blocking ("Moderation Assistance by federation of bellwethers")

### ISSUE THREAD

**Issue by indrora** [mastodon/mastodon#21843]
### Pitch

You're an instance moderator, and your instance is part of a broader community of instances (e.g. "furries in tech", "information security experts", "papercraft and other artistry") and you've got a lot of instances to block (racists, homophobes, etc.).

Everyone complains about having to do this. Why can't larger communities communally flag and moderate together?

Each instance would be able to define a set of "Peer Moderation" instances. These are functionally outboxes that an instance can *optionally* turn on which have filtering notifications posted to them. This would be done through the same ActivityPub follow mechanism, complete with "approves followers" enabled should the instance moderation team want. 

These are 100% chosen by the individual instance. As an instance owner, you pick who your friends are. If you've got friends that run other instances, you choose to listen to them. If you want to listen to the firehose of bans out of a giant instance, so be it. Your peers and my peers don't have to be the same set. 

A large instance may choose to publish its ban notifications publicly. A small one may choose to publish them to only peers they specifically feel are worth peering with. 

When a user/instance is k-lined (As in irc or bbses of yore) on one instance, the moderator of that instance is given the opportunity to raise the offender to instances who have chosen to listen.

Each instance which is interested in following suit sends notifications to its peers, including limiting its scope of responses to only mutual peers ("you and I both listen to example.org, I'm going to also block example.com for spam".)

An instance may define a minimum bar ("80%") and quorum of responces among its chosen peers ("51%", minimum 3) to consider the group in consensus if it is unsure. For instance:

* instance A has many users, and is known to have good moderation
* Many other instances choose to engage in peer moderation with instance A; only E, H and I don't for this example.
* Instance B has engaged in peer moderation with instances A,B,D,E,F,G
* Instance C has engaged in peer moderation with instances A,B,F,G,H,I

The population

* positively ("I am too going to block this")
* neutrally ("I want consensus among my peers before I block")
* or negatively (ignoring the report entirely)

Or not at all, in which they neither benefit nor suffer, and are considered absent from voting. 

Once a plurality consensus of positive vs. ambivalent votes is achieved, ambivalent voters may have opted to automatically accept that population's choice or mull on it. If they accept the population's choice, they present a positive response to their ambivalent peers.

Instances which responded negatively may lodge their reasoning to not accept this during consensus-seeking. Motions in the negative have no effect on the rest of the group except possibly neutral voters. Taking no action is the same as ignoring the group and not blocking the instance.

The votes, as well as the instance and why it was blocked would be logged for each server moderator (since they're delivered to an inbox).

A worked example:

Instance A announces it has blocked example.com to B,C,D,F,G

Instances C,D,F cast a positive response, G casts uncertainty. 

Instance B receives [ (yes), yes, yes, yes, maybe ] and itself casts maybe. 4 yes, 2 maybe, with 6 total, but >51% of the population saying yes, E not knowing but counting towards the quorum population. B re-announces that it will block example.com to G.

Instance E is sent by B a "maybe? A is blocking example.com because reason" notification. It is free to ignore it or take action should it wish. if it does, instance B considers their positive action as a yes in the respondent population. E is even free to pass along its yes or uncertain message to its peers, but this is optional.

Instance C on the other hand sees [ (yes), maybe, yes, maybe ]. It has already cast a positive vote. if it had cast a Maybe vote, it would have [ yes, maybe, maybe, maybe ] and lacked a 51% population of peers responded, much less a consensus of yes. Should it cast a yes, it would inform B that it had cast yes. However, it would not take any action even automatically unless it received sufficient positive responces from the rest of its peer group (G, H, and I)

Members of the group who responded negatively (vs positive + ambivalent) may register their displeasure with their peers should they wish. 

The goal here is to allow for community moderation warnings while maintaining instance sovereignty. Only you know who your peers are and how they responded to the suggestion; you're waiting to hear what your peers are thinking. An instance that rubber-stamps all its requests has little effect on the results. The major automation is instances telling one another "I blocked this instance because reason" or "I'm uncertain about blocking this instance because reason, as suggested by this other instance". 

It should be noted that a suggestion which originates from a blocked instance is ignored -- that is, if you block a peer of a peer, you do not see that peer's suggestions (or may respond in kind that you have blocked the instance that is suggesting a block, optionally).

### Motivation

A lot of discussion has been brought along on how to handle banning instances, with the hashtag "Fediblock" being used quite a lot of this. However, this doesn't scale and leads to a lot of overhead work. 

Expanding moderation to "I'm willing to trust others to make a choice I can turn off if I choose to" allows for the broader Mastodon community to assist in lessening the load of others. If an instance is put up for banning that is already positively banned by that instance, it can be an automatic positive vote on behalf of that instance.

By creating a consensus system that doesn't punish those who are ambivalent about the results *and* allows the freedom to disagree with the group writ large without punishing those who agree, it provides a handful of very useful moderation approaches:

* An instance may peer with another instance dedicated to making block suggestions, with their own governance to create cabals and larger communities.
* An instance with only a few users may take advantage of the power of a larger member of the broader fediverse (e.g. mastodon.social) and be shielded by the extant knowledge of a popular instance. 
* Instances which use the non-open-federating model may use this as a way to suggest growth, inverting the model into opt-in federation that allows consensual peering. 
* Instances with asleep at the wheel (or overwhelmed) administrations will help others in the worst case.

Crucially, this is not one central distribution. This makes it harder (read: bordering on impossible) for instances to dogpile outside of a coordinated group who wish to be isolationist, and instead allows rings to form naturally as communities which share ideals peer with one another, through invitation and network effect. However, the "logged" portion of the proposal then falls on the individual instances to keep their own histories of their federated bans.

This is functionally "Who wants to go to coffee at starbucks with me" among peers, but for blocking of instances. Those who have no interest in the activity as a whole can ignore the question. Those who are interested if their direct peers are can express their tacit interest. Those who have objections to Starbucks may lodge their complaints but are otherwise not included, and those who positively want to go say so. 

This also avoids cascades: Ambivalent voters may wedge their change of heart. However when others suggest that the instance be blocked, they will say "oh I did that too" nearly automatically.

By proposing part of this in the ActivityPub standard, other backends (such as Misskey, WriteFreely, Akkoma, etc.) may make use of this without having to have explicit support for something Mastodon-specific.

**Comment by philpem** [comment]
> Acquainted followers are able to vote
>
>    positively ("I am too going to block this")
>    neutrally ("please positively inform me if you block this instance")
>    or negatively (ignoring the report entirely)
>
> Or not at all, in which they neither benefit nor suffer, and are considered absent from voting.

My immediate thought is that this still has issues with [dogpiling](https://en.wikipedia.org/wiki/Dogpiling_(Internet)), through the voting measure. With a sufficiently well-written story or a person with some standing in the community behind it, they can pretty much target whomever they like.

> An instance may peer with another instance dedicated to making block suggestions, with their own governance to create cabals and larger communities.

That seems like a slippery slope, birdsite has had several of these (Blocktogether, Altfurryblocker, and so on) and several of these have started out with good intentions but later on became snarled in the same "if you're not with us you're against us, thou art blocked" splitting behaviour that's beset almost all previous attempts.

Without a solution to this, it seems better to defer to a trusted single-party or small group, as the will of the masses is very easily manipulated via propaganda -- or .

**Comment by philpem** [comment]
Also perhaps I've misunderstood (apologies if I have) but it sounds like this proposal would effectively subvert moderation control. That is to say, in the sense that the moderation team (or indeed instance admin) are required to block instances voted in favour of.

I can see that being usable as a coercive control measure, by means of a larger instance blocking someone out of spite and rigging the vote, then using defederation from smaller instances as a threat. It's a human problem at the end of the day but I feel one worth bearing in mind.

**Comment by indrora** [comment]
> With a sufficiently well-written story or a person with some standing in the community behind it, they can pretty much target whomever they like.

They would need to convince not only you (to vote positively or follow if their friends are) and the others you peer with who also peer with the story spinner.

It is also not a final decision.

> That seems like a slippery slope, birdsite has had several of these (Blocktogether, Altfurryblocker, and so on) and several of these have started out with good intentions but later on became snarled

Since voting is murmur between instances, the only way to know who blocked who in a vote would be to have been privy to the peers an instance had at the time of the vote and plausibly deduce their possible votes.

> it sounds like this proposal would effectively subvert moderation control. That is to say, in the sense that the moderation team (or indeed instance admin) are required to block instances voted in favour of

Absolutely not. Voting no and casting no vote have the same effect on you. The only two things that you actively do are agree with the proposer or say "if enough people say yes and enough of my friends say they're interested, I'll do that."

**Comment by indrora** [comment]
I've updated the body to clarify some things about the process.

**Comment by warthog9** [comment]
I like the overall idea, there's a few things that I'd argue for in addition to this, but the bones of the idea I think are solid in general.

- Inside Mastodon I think there would need to be a few changes, not dramatic but would help make this better
  - The blocks need some sort of toggle for enable/disable.  Being able to have most of a block documented / recorded / etc but NOT enabled would make collecting commentary and documentation worthwhile.  This means that even admins/moderators today could leave additional commentary about a potential block without the block actually enforced.  Right now the block doesn't seem to have that capability.
  - I'd want to see information pertaining to these notifications and/or consensus calls with the block.  This may require expanding the comments for a block to be more a stream of comments vs. a single field.  If these went to separate database entries that would allow for a block's reasoning upstream to be updated locally as well, which would allow for things like "Unblocked for <reason>" to be added or amended.
  - Relatedly the comment fields, in the database, are already text fields but the fields presented are now just text input lines.  This likely would need to be changed to a text block, and/or the ability to have arbitrary number of comment blocks (like a bug discussion list, or like this comment)

An ability to publish a block list both programmatically ingestible, externally, and not explicitly fully public (right now to share a block list non-publicly it has to be extracted and shared elsewhere), would be in and of itself a useful feature.  Having it in the protocol itself would be better and allow individual systems to determine how they want to use that information as well.  Right now you can scrape the /about, or call the api to snag that but having this lower level seems like a benefit.

To the dogpiling argument: While this potentially lowers the barrier to the occurring, there's already nothing stopping that from occurring now, and from many individual users perspectives that's already defacto the result they see on the larger instances where the instance blocking a site causes it to be blocked for potentially 10s of thousands of users.  Associated the with us vs. against us stance may not actually be an unwanted position in the long term across the broader fediverse.  Those wanting to push for those stances will naturally form different rings of connection in the overall federation.  Users that want to participate in more of those rings will end up needing multiple accounts to participate in the spaces.  This is already, effectively, the case of users leaving an instance for another based on moderation choices.

**Comment by indrora** [comment]
I guess to frame this differently:

Instances would have a timeline of bans. Instances could follow that timeline. Boosting a ban = banning it and putting it on your timeline of bans, linked back to the original ban suggestion. If you're uncertain you could forward it to your mutuals and say "how do you feel about this? I'm on the fence" or "this is a bad idea and I won't be" if you disagree with it.

This would add, in the overall flow of banning an instance, the published interactions your peers had decided on if they chose to make that available to you. 

Admins could annotate their own timeline (e.g. via the mod talk) and retain history on why an instance was blocked. 

It's important to note that none of this is automatic. A moderator still has to go and push the button to ban an instance. They just have more information and early warnings on problematic instances. Instead of going "A says so", it's "A and my peers says so, and here's their reasons why.

**Comment by indrora** [comment]
The proper implementation of this is much lighter than I think I've described here as I think about it. 

Fundamentally, this gives instance operators a heads up from sources they trust of a potentially issue-ridden instance and allows them to read the wind of how their other trusted sources of ban notifications have handled it, while also allowing for "I don't know" and preemptive records. 

Ideally, the UI would look something (better than this) like this:

![image](https://user-images.githubusercontent.com/470584/204676271-d215d853-def1-4c10-b113-b08628f03a09.png)
