### ISSUE TITLE
AWS-S3 bricks Mastodon profile section !!

### ISSUE THREAD

**Issue by mrAceT** [mastodon/mastodon#21853]
### Steps to reproduce the problem

1. create your own instance
2. configure usage for S3
3. try and add an alias via /settings/aliases ..

### Expected behaviour

it should have added the alias (for migrating to my server)

### Actual behaviour

an error page

### Detailed description

**The thing is, I dug into the log found this:**
Storage server error: Failed to open TCP connection to [bucket].s3.de.amazonaws.com:443 (getaddrinfo: Name or service not known)
method=POST path=/settings/aliases format=html controller=Settings::AliasesController action=create status=503 duration=721.21 view=7.99 X-Accel-Mapping header missing

**.env.production**
S3_ENABLED=true
S3_BUCKET=[bucket]
AWS_ACCESS_KEY_ID=[key]
AWS_SECRET_ACCESS_KEY=[secret]
S3_REGION=de
S3_PROTOCOL=https
S3_HOSTNAME=storage.de.[**NOT_aws**].net

**The problem?**
I think that somewhere some default "[bucket].s3.[region].amazonaws.com" is set.. that doesn not use S3_HOSTNAME ?

### Specifications

Docker version  v4.0.2

**[update]**
I've dug a bit into the code.. maybe:
the call to '/aliases' does not read the config for AWS S3 (completely?) (and therefor skips reading S3_HOSTNAME) and so 'config/initializers/paperclip.rb' dos not get processed correctly. I altered the default => no effect.

**Comment by mrAceT** [comment]
**an other update..**
I think somewhere in the '/aliases' call there is an (unnecessary) call to a AWS storage engine. And I assume that that module uses the default hostname (you see in the error), because the manually set one (via S3_HOSTNAME) has been forgotten to be parsed.

**Comment by mrAceT** [comment]
This quite hinders me form "going live" with my instance, because I hope/expect (some) people will change instance.. this results in an error now because the necessary steps can not be taken..

**Comment by mrAceT** [comment]
I initiated a migration form an other server to mine.. and.. everything is crashing.. not only "aliases" crashes.. but practically everything in the profile is.

I have asked the admin of the other server to rescue my main account (should have used a test account.. crap..)

.. so for those that want to use AWS S3, but NOT from Amazon have a more or less bricked/useless Mastodon, until this is fixed.. I have found sponsors for my instance.. but I need that AWS-S3 for it to be financially viable.. so I do really, really hope this bug can be addressed before my sponsors pull back and the whole idea crashes.

As for me, the admin of that server needs to find the time this next weekend to figure out how to restore my account. So I'll be out of mastodon for a week.. ahh well, there's always Tw... never mind

**Comment by mrAceT** [comment]
I’ve had som help of an other mastodon instance owner.

It appears that I have bricked the whole S3 thing somehow.

I’ll keep this topic open, and tell more when I’ve figured out what and how I have broken things..

**Comment by nightpool** [comment]
We primarily use GitHub as a bug and feature tracker. For usage questions, troubleshooting of deployments and other individual technical assistance, please use Github Discussions, Discord, or another discussion forum.

Feel free to continue the discussion of the issue here, but I'm going to be marking the ticket as "closed". This won't affect your ability to comment on it, it's just a reflection of the fact that it's not a defect in the mastodon software, just a problem with your individual deployment.

**Comment by mrAceT** [comment]
@nightpool thanks for your reply.

And indeed, not a bug, maybe a problem with incomplete documentation.. I have figured it out, this is the correct setup if you want AWS-s3 and want u use caching via nginx:

S3_ENABLED=true
S3_BUCKET=[bucket]
S3_PROTOCOL=https
AWS_ACCESS_KEY_ID=[key]
AWS_SECRET_ACCESS_KEY=[secret]
S3_REGION=de
S3_ENDPOINT=https://storage.de.[AWSprovider].net
S3_HOSTNAME=storage.de.[AWSprovider].net
S3_ALIAS_HOST=media.[yourdomain]


I've tried all sorts pf settings,  and this is the only combinations of variables that I got to work..
