### ISSUE TITLE
Followed Hashtags don't show up under 'Following'

### ISSUE THREAD

**Issue by sammcj** [mastodon/mastodon#21868]
### Steps to reproduce the problem

1. Follow hashtags
2. Go to your 'Following' list (e.g. https://mastodon.social/@username/following)
3. Can't find the followed hashtags

### Expected behaviour

Following should show hashtags you're following

### Actual behaviour

Hashtags are missing

### Detailed description

It's not obvious where you can find your followed hashtags anywhere in the UI.

They don't show up under:

- Following (e.g. https://mastodon.social/@username/following)
- Settings -> Follows and followers
- Explore -> Hashtags (I think there should also be a + next to hashtags there to (un)follow them)

![following](https://user-images.githubusercontent.com/862951/204663925-2cecd26b-bceb-4050-83e4-395c8038cd6d.png)

![explore-hashtags](https://user-images.githubusercontent.com/862951/204663853-70a8096a-9213-4b22-b46f-462f60c34a02.png)

![settings-following](https://user-images.githubusercontent.com/862951/204664329-ea4f6495-cbc5-47b9-b635-185498d6abe8.png)

### Specifications

Mastodon v4.0.2

**Comment by connorshea** [comment]
Dupe of #20763

**Comment by sammcj** [comment]
Oh, whoops sorry! I'll close this then.
