### ISSUE TITLE
Split the pull queue in two types of low priority jobs

### ISSUE THREAD

**Issue by todoneunl** [mastodon/mastodon#21862]
Right now the low priority pull queue has a mixed bag of job types, like LinkCrawlWorker, ThreadResolveWorker,  ActivityPub::SynchronizeFeaturedTagsCollectionWorker,  FetchReplyWorker and ActivityPub::LowPriorityDeliveryWorker. Some of those are needed for a snappy user experience (like LinkCrawlWorker and ThreadResolveWorker), and others are really low priority and can be spread out over a long period of time.

So my proposal is to make the real low priority (non-UX) jobs have a separate queue where they can't delay e.g. embedded content (like Youtube or Peertube videos) and fetching of thread content.

I noticed this after I deleted a lot of unconfirmed and never used user accounts using the tootclt tool. Somehow a simple delete of a user that was never active, created many ActivityPub::LowPriorityDeliveryWorker jobs in the pull queue. A few hundreds of these deletes created millions of jobs in the pull queue. Resulting in delaying peoples UX, like embedded videos.

This is on the border of a bug and a feature request.

Running Mastodon v4.0.2

**Comment by rbairwell** [comment]
Would it be possible to have each task have its own queue (but with the ability to group multiple tasks into queues). This would give admins the most scaling flexibility (Link cards under high demand? Set that to it's own low priority queue!) - and if the default configuration has them grouped as they currently are (with the 6 queue groups) it'll be easy to start with.

**Comment by briandeheus** [comment]
We've had a similar issue. We suspended a user, which caused our pull queue to clog up. 

Very annoying, and incredibly easy to abuse for trolls.

**Comment by todoneunl** [comment]
Closing this one, because I think it's OK now. Although please have look to this new issue, that asks for prioritising suspended accounts. https://github.com/mastodon/mastodon/issues/33053
