### ISSUE TITLE
Errno::EROFS (Read-only file system @ dir_s_mkdir when using Digital Ocean volume

### ISSUE THREAD

**Issue by jberculo** [mastodon/mastodon#21860]
### Steps to reproduce the problem

1. Install mastodon on digital ocean droplet (ubuntu22.04)
3. mount a digital ocean volume (extra disk space), e.g. /mnt/volume
4. create a directory (e.g. system) on the volume, 
5. chown this dir to mastodon user, set permisions
6. remove system dir in public
7. create symlink dir in public to /mnt/volume/system
8. chown symlink

### Expected behaviour

No 500 errors when uploading to Mastodon

### Actual behaviour

500 errors when uploading to Mastodon

### Detailed description

When uploading files, you get a 500. In the logs the following is shown

[paperclip] Trying to link /tmp/7a80ee8e48107933a59a15df89b084fd20221129-1797-po6pyx.jpg to /tmp/2457a385b21a602a891f7ff1f64b8ac020221129-1797-d042la.jpg
Command :: file -b --mime '/tmp/2457a385b21a602a891f7ff1f64b8ac020221129-1797-d042la.jpg'
[paperclip] Trying to link /tmp/7a80ee8e48107933a59a15df89b084fd20221129-1797-po6pyx.jpg to /tmp/2dbfa4d53515a0bb483f384c3779458a20221129-1797-kyoq8a.jpg
method=POST path=/inbox format=html controller=ActivityPub::InboxesController action=create status=500 error='Errno::EROFS: Read-only file system @ dir_s_mkdir - /home/mastodon/live/public/system/cache/accounts/avatars/109/428' duration=562.43 view=0.00 db=9.45 key=https://mastodon.lol/users/xxx#main-key

Errno::EROFS (Read-only file system @ dir_s_mkdir - /home/mastodon/live/public/system/cache/accounts/avatars/109/428):

When manually trying to save files as the mastodon user, everything works
/home/mastodon/live/$ touch public/system/test

### Specifications

Mastodon 4.02 (just installed using the joinmastodon from source documentation)

This is a problem in all interfaces (apps, web)

**Comment by jberculo** [comment]
Thanks @Crashdoom! I tried it again per your instructions, and now it works.

Probably would be a gouud idea to document this somewhere properly, but I now see that it's not a mastodon problem per se, so I am closing this bug.

**Comment by manuelkamp** [comment]
this helped me also, so +1 for adding it to documentation

**Comment by taniki** [comment]
Thanks @Crashdoom! I was doing a whole `umount`/`mount` dance after each updates. There is no need to add the extra path in `/etc/systemd/system/mastodon-streaming.service`, right?

**Comment by Crashdoom** [comment]
> Thanks @Crashdoom! I was doing a whole `umount`/`mount` dance after each updates. There is no need to add the extra path in `/etc/systemd/system/mastodon-streaming.service`, right?

I did for all of our services just in case, but I’m actually unsure if mastodon-streaming uses the system mount.
