### ISSUE TITLE
Update PWA so app shows up in the app drawer

### ISSUE THREAD

**Issue by KenMacD** [mastodon/mastodon#21886]
### Pitch

PWA test tools flag a few issues with the current version:

* Does not register a service worker that controls page and `start_url`
* Manifest doesn't have a maskable icon
* Content is not sized correctly for the viewport

I'm not sure which of these (if any) affect the ability to have the app install as a proper PWA and show up in the app-drawer.

### Motivation

This would be useful because it would make the app fit with the other apps the user is already using.

**Comment by rbairwell** [comment]
Can you confirm which operating system/device you are seeing this issue on?
I'm unable to replicate it on a Google Pixel 3 phone running Android 12.

**Comment by KenMacD** [comment]
Oh, I think this is just a Firefox limitation. I retried it using Chrome and it does actually use the app drawer. Please disregard.
