### ISSUE TITLE
Unable to resolve moderator report if a post has been deleted

### ISSUE THREAD

**Issue by jgroszko** [mastodon/mastodon#21910]
### Steps to reproduce the problem

1. Someone submits a report on a multiple posts
2. The original poster deleted one of the posts
3. Click "Mark Sensitive" in the moderator report

### Expected behaviour

The moderator report is resolved and the selected posts are marked sensitive

### Actual behaviour

422 Unprocessable Entity error

### Detailed description

Someone reported a few posts on my instance but when I went to mark them as sensitive the moderator report page gave me an HTTP 422 error. One of the posts that was reported had been deleted by the original user. Didn't matter what combination of posts I had selected, it always gave the 422 error. I reported all the undeleted posts again and was able to resolve the new moderator report.

### Specifications

Mastodon | 4.0.2
Ruby | 3.0.4p208
PostgreSQL | 14.6
Redis | 6.2.7

Chrome 108.0.5359.71

**Comment by ClearlyClaire** [comment]
> 3\. Click "Mark Sensitive" in the moderator report

Where did you find this button?
