### ISSUE TITLE
Add user option to always display sensitive media

### ISSUE THREAD

**Issue by thomas-alrek** [mastodon/mastodon#21944]
### Pitch

I would like to see a feature where I as a user can opt-in to always reveal sensitive media or content.

### Motivation

I have thick skin, and am really just annoyed at having to click to reveal sensitive media or conent everytime. I do understand that many probably prefers to have it on as a default, but it would be nice to have the option to disable this. This would work like Reddit, where you have the option to always show NSFW media.

**Comment by nichu42** [comment]
It's right there under Preferences / Appearance / Sensitive Content / Always show media?!

**Comment by yuvalne** [comment]
Yup. Someone didn't check the docs.

<img width="623" alt="Screen Shot 2022-12-02 at 15 21 32" src="https://user-images.githubusercontent.com/97384040/205302145-b2a4ac14-9e21-4c83-8422-6b202be49381.png">

**Comment by ineffyble** [comment]
As mentioned, this is already a feature. Let me know if your request has been misunderstood.
