### ISSUE TITLE
Redis related error in web container ConnectionPool::Error (no connections are checked out)

### ISSUE THREAD

**Issue by gillesgagniard** [mastodon/mastodon#21960]
### Steps to reproduce the problem

1. Wait for a few days/weeks of uptime
2. The web container (running puma) starts streaming Redis ConnectionPool errors
3. Pages randomly fail to load up (for instance, followers page in my profile couldn't load anymore)

### Expected behaviour

The mastodon web container can be run without regular restarts.

### Actual behaviour

After a few days/weeks of uptime (random period), the mastodon web container needs to be restarted.

### Detailed description

This is basically a reoccurence of #20671, which has been closed, however latest Mastodon release 4.0.2 still has the same issue.

I'm running the standard Docker Compose setup including containerized redis and postgres, and use the officially built mastodon image.

Here is the error stack trace:

    ConnectionPool::Error (no connections are checked out):
    
    lib/mastodon/rack_middleware.rb:22:in `clean_up_redis_socket!'
    lib/mastodon/rack_middleware.rb:17:in `clean_up_sockets!'
    lib/mastodon/rack_middleware.rb:11:in `call'

Restarting the web container (and only this one !) temporarily fixes the issue. The redis container itself doesn't need to be restarted, so redis itself is running fine.

### Specifications

    docker.io/tootsuite/mastodon:v4.0.2
    docker.io/redis:7-alpine
    docker.io/postgres:14-alpine

**Comment by turion** [comment]
Also affected, using NixOS with mastodon 4.0.2 and redis 7.0.5

**Comment by arbolitoloco1** [comment]
I have the same issue running mastodon 4.1.4 on Ubuntu 22.04.2 with Redis 5:6.0.16-1ubuntu1 without using Docker. I don't think I changed any relevant setting that could cause this issue (maybe sidekiq concurrency?). Hopefully someone will find a way to fix it :)

**Comment by arbolitoloco1** [comment]
Changing Sidekiq's concurrency setting back to the default value doesn't seem to have any effect, but I found some interesting logs that pop up every time just before I start repeatedly getting the `ConnectionPool::Error (no connections are checked out)` exception once again, and a good part of the requests to my server start returning http error 500.
```
RedisCacheStore: read_entry failed, returned nil: Redis::TimeoutError: Connection timed out
RedisCacheStore: read_entry failed, returned nil: Redis::TimeoutError: Connection timed out
! Terminating timed out worker (worker failed to check in within 60 seconds): 2506785
! Terminating timed out worker (worker failed to check in within 60 seconds): 2506789
! Out-of-sync worker list, no 2506785 worker
! Out-of-sync worker list, no 2506785 worker
! Out-of-sync worker list, no 2506789 worker
- Worker 0 (PID: 2712774) booted in 49.21s, phase: 0
- Worker 1 (PID: 2712775) booted in 49.39s, phase: 0
Chewy request strategy is `mastodon`
Chewy request strategy is `mastodon`
Chewy request strategy is `mastodon`
```
These are the console logs I get while browsing a few pages on my instance, not all requests fail but a good part of them do
![image](https://github.com/mastodon/mastodon/assets/36609914/e19dfaf8-43b3-487e-baa1-e3852f6d5aac)

I also assume in my case the worker timed out due to a peak in cpu usage, from what I saw in my graphs
![image](https://github.com/mastodon/mastodon/assets/36609914/414b31b2-7f4a-4438-ab59-7b4bafcfea09)

**Comment by ThisIsMissEm** [comment]
Is anyone able to reproduce this on 4.2.0?

**Comment by arbolitoloco1** [comment]
I've been pulling from the main branch these last two months and haven't come across the error luckily :)

I think it's also important to mention that I modified a script I used to backup the server which was taking too much resources and generally caused this to fail

**Comment by ThisIsMissEm** [comment]
@vmstan I think we can close this issue

**Comment by SuperSandro2000** [comment]
Seeing this lately a lot. Anyone knows what needs to be tuned to fix this?
