### ISSUE TITLE
`tootctl domains purge` does not include subdomains, while instance blocks do

### ISSUE THREAD

**Issue by rixx** [mastodon/mastodon#21984]
### Steps to reproduce the problem

1. Run `tootctl domains purge`, eg on the recent spam domain activitypub-troll.cf 
2. Observe that no subdomains are purged.
...

### Expected behaviour

Domain blocks extend to subdomains, so purges should, too (or at least have an option to disable that mode)

### Actual behaviour

Subdomains do not get purged.

### Detailed description

Only the exact match is purged. In the case of the recent spam domain, this sucks – we have over 1k individual 1 user spam domains lying around now, and no real way to get rid of them.

### Specifications

Mastodon 4.0.2

**Comment by kescherCode** [comment]
This extends to the purge button in the admin UI if you only suspend an apex domain and then purge it.

**Comment by kescherCode** [comment]
This should be an explicit flag, though, both in the admin UI (maybe a checkbox) and on the CLI. You usually only want to purge the apex domain (old entries of instances that have moved to a new subdomain, etc.).
