### ISSUE TITLE
v4.0.2: Lists and pinned hashtag searches are not updated anymore in advanced web interface 

### ISSUE THREAD

**Issue by Marty-Crabneck** [mastodon/mastodon#21998]
### Steps to reproduce the problem

1. Search for some hashtag
2. Click "pin" in the result column
3. Wait until that hashtag should appear
4. Click browser reload button to see it actually appear
...

### Expected behaviour

It should show that blue glow and "X new items" in slow mode, as it does in the "home" column 

### Actual behaviour

Nothing happens

### Detailed description

I seem to remember that this worked in v3.5.
A list displayed in a pinned column should also show new content automatically imo, but i dunno if it did in 3.5.

### Specifications

Mastodon v4.0.2
Ruby 3.0.4p208
Node v16.13.2
Chromium Version 110.0.5445.0 (Developer Build)

**Comment by ClearlyClaire** [comment]
> 3\. Wait until that hashtag should appear

You mean wait for a new post with that hashtag to come up?

> It should show that blue glow and "X new items" in slow mode, as it does in the "home" column

It works as expected here, I can't reproduce the issue.

>  A list displayed in a pinned column should also show new content automatically imo, but i dunno if it did in 3.5.

Do you mean a list column, or a hashtag column? In any case, both work as expected here.

**Comment by AlpacaO** [comment]
I'm not sure if I'm reporting the same bug.
However. 
In v4.0.0rc4+glitch
I'm seeing a pinned list in the advanced web interface, not refresh, and not refresh with added users.

I've both added new users to the list, and removed users from the list, and it doesn't seem to cause the content in the pinned column to update. No amount of hard refreshing seems to get it to refresh.

**Comment by ClearlyClaire** [comment]
@AlpacaO editing a list members does not retroactively change the contents of the list timeline, it only affects new posts. That is a bit inconsistent with the Home timeline though, so I understand the confusion.

**Comment by AlpacaO** [comment]
If I create a new list with the people on it, will the new list get the complete list timeline?

**Comment by ClearlyClaire** [comment]
There is currently no way for list timelines to contain posts from members before the point the members were added to the list. If you create a new list, it'll start empty, and contain new posts as expected, but not posts older than the list's creation.
