### ISSUE TITLE
vagrant's start command does not work

### ISSUE THREAD

**Issue by eslerm** [mastodon/mastodon#21999]
### Steps to reproduce the problem

1. provision fresh vagrant vm: `vagrant up`
2. attempt `vagrant ssh -c "cd /vagrant && foreman start"`
4. test that foreman is in path: `vagrant ssh -c "which foreman"`
5. test that foreman is not in path after cd: `vagrant ssh -c "cd /vagrant && which foreman"`
6. check foreman env paths: `vagrant ssh -c "env | grep rvm"`

### Expected behaviour

foreman in path to start

### Actual behaviour

foreman not in path to start

### Detailed description

it appears that foreman is in `$PATH`, but cannot be used outside of `$HOME`

foreman has an argument to set the proc directory, which resolves needing env paths outside of home and feels better than cd

### Specifications

mastodon [f77ed3a](https://github.com/mastodon/mastodon/commit/f77ed3a6b202b0eba42e4ce2e76b09dcf70398b4)

**Comment by trwnh** [comment]
same issue as #19180?

**Comment by eslerm** [comment]
yes, duplicate issue

thanks
