### ISSUE TITLE
POST /oauth/token has not described parameters

### ISSUE THREAD

**Issue by 3DRaven** [mastodon/mastodon#21992]
### Steps to reproduce the problem

curl --request POST \
  --url https://mastodon/oauth/token \
  --header 'content-type: multipart/form-data' \
  --form client_id=X \
  --form redirect_uri=urn:ietf:wg:oauth:2.0:oob \
  --form grant_type=authorization_code \
  --form code=X

### Expected behaviour

By documentation: return access_token

### Actual behaviour

401 return status code without client_secret

### Detailed description

In documentation described
https://docs.joinmastodon.org/methods/oauth/#token
Request does not have client_secret parameter (with grant_type=authorization_code only?), 
but it has. I do not known it is error in API or in documentation. But 
without client_secret it looks more security aligned
because we do not need to publish our client_secret to 
client code.

### Specifications

Droplet from DigitalOcean
Mastodon Version 4.0.2 OS Ubuntu 20.04

**Comment by ineffyble** [comment]
This is following OAuth 2.0 specifications: https://www.oauth.com/oauth2-servers/access-tokens/authorization-code-request/

**Comment by 3DRaven** [comment]
Ok, yes. But  then it is mistake in documentation.

**Comment by trwnh** [comment]
Fixed in https://github.com/mastodon/documentation/pull/1060/commits/5795a3d778441796a784456ed0db1ceb6f74fd27 but https://github.com/mastodon/documentation/pull/1060 has not been merged yet

**Comment by ThisIsMissEm** [comment]
This is now fixed in the documentation.
