### ISSUE TITLE
LinkCrawlWorker: AddressFamilyError

### ISSUE THREAD

**Issue by kescherCode** [mastodon/mastodon#22018]
### Steps to reproduce the problem

1. Fetch https://mastodon.social/@georgrestle/109320263671765094, or have it otherwise try to crawl the URL http://www.sichtbar-machen.online/ linked in that post
2. Look at sidekiq retries/deads
...

### Expected behaviour

The link should be fetched fine

### Actual behaviour

IPAddr::AddressFamilyError: address family must be specified on http://www.sichtbar-machen.online/

### Specifications

4.0.2

**Comment by FrancisMurillo** [comment]
I figured out that the redirect from [http://www.sichtbar-machen.online/](http://www.sichtbar-machen.online/) is [https:/sichtbar-machen.online](https:/sichtbar-machen.online) that is missing  slash or `https:/` over `https://` where Ruby cannot parse it properly or is causing issue with the HTTP library.

```ruby
u = URI.parse "https:/sichtbar-machen.online"
# #<URI::HTTPS https:/sichtbar-machen.online>

u.scheme
# "https"

u.host
# nil

u.port
# 443

u.path
# "/sichtbar-machen.online"
```

```
$ curl -IL http://www.sichtbar-machen.online/
HTTP/1.1 302 Redirect
Content-Length: 152
Content-Type: text/html; charset=UTF-8
Location: https:/sichtbar-machen.online
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET

HTTP/2 200 
content-length: 34348
content-type: text/html
accept-ranges: bytes
server: Microsoft-IIS/10.0
x-powered-by: ASP.NET
```

**Comment by FrancisMurillo** [comment]
I agree and somehow browsers (and cURL) auto correct the missing slash and fetch the link. I was able to monkey patch `HTTP::Redirector` to fix the missing slash but I think this is an acceptable error.

**Comment by ineffyble** [comment]
Yeah, I'm inclined to say this is expected. Interesting how widely software ignores the error though.
