### ISSUE TITLE
Account persistence 

### ISSUE THREAD

**Issue by kurtfriedrichhotmail** [mastodon/mastodon#22013]
### Pitch

If a domain owner gets mad and shuts his/her servers down, or if they are hacked with ransomware or whatever, or any number of other bad things, then all those hosted user accounts are gone. Correct?

It would be great if someone would clone DNS or some other lazy replication scheme and then offer a package that sets of 3 domain owners would voluntarily join, and each host this replication. So we would not have a giant DB somewhere, just subsets in groups of 3. Maybe this could be an optional feature which hosters might charge for?

### Motivation

Shit happens. It would be a shame to have 10,000 accounts just disappear forever. Most people would pay to have a safely backed up account.

**Comment by rbairwell** [comment]
> If a domain owner gets mad and shuts his/her servers down, or if they are hacked with ransomware or whatever, or any number of other bad things, then all those hosted user accounts are gone. Correct?

Correct. The latter is why the Mastodon Server Covenant https://joinmastodon.org/covenant specifies that to be listed on JoinMastodon you need daily backups at a minimum.

> It would be great if someone would clone DNS or some other lazy replication scheme and then offer a package that sets of 3 domain owners would voluntarily join, and each host this replication. So we would not have a giant DB somewhere, just subsets in groups of 3. Maybe this could be an optional feature which hosters might charge for?

Alas, it wouldn't be anywhere near this easy. You'll need a full copy of their Postgresql database (which could be done with a read-replica), then you'll need people with access to that and the media storage (or a copy of the 100Gbs+ of media) and then access to DNS: and the ability to "standup" everything on new infrastructure in a short period of time (which for the larger instances would be more complex).  This doesn't take into account data protection laws (you agreed to share your Mastodon email address with site X: but you haven't with backup site Y etc) and similar paperworkish issues (if an admin goes AWOL how long should people wait before taking over? If the admin becomrd available again/sorts out the problem should everything be moved back?)

Just having DNS split across 3 servers wouldn't help as unless changes as the "best case" is the primary server (i.e. the current/main host) gets the records updates and it spreads to the others. Worse case, the 2 secondary servers switch to primary mode and make local changes - giving people a 1 in 3 (or 2 in 3) chance of hitting the correct system.

I agree that "something must be done"(tm), but this is more a meatware (human) issue than software.

I have seen talk of "collectives" of servers coming together to deal with spam, offer support, moderation etc and this would be something they should handle (but "Mastodon gGmbh" shouldn't as that'll push things to be more centralised a la Twitter): I suspect over time (in a couple of months for smaller instances as the $ bills grow, moderation work increases and it stops "being a fun hobby"), they'll be informal and then "formal insurance-type coverage" arrangements becoming available.

Just my 2p (via mobile so excuse typos)
