### ISSUE TITLE
Unpredictable scrolling behavior on timeline update in slow mode 

### ISSUE THREAD

**Issue by AlarithUhde** [mastodon/mastodon#22023]
### Steps to reproduce the problem

1. Activate "slow mode" ("Langsamer Modus")
2. manually update timeline by clicking on "X new posts" ("X neue Beiträge")

### Expected behaviour

The new posts should be added without scrolling the timeline, so that they are hidden above the mouse pointer. The user can then scroll upwards to read them.

### Actual behaviour

The timeline scrolling behavior is inconsistent. Sometimes it works as expected, sometimes not.

### Detailed description

Sometimes new posts are added as expected, i.e., hidden and above the mouse pointer so the user can scroll up to see all new posts. But sometimes the timeline scrolls down entirely so the user has to scroll down instead. Sometimes half the new posts are added below and half are added above the mouse pointer, so the user has to both scroll up and down to read all new posts.

The exact conditions for each behavior are not clear to me.

Given the position janking when deactivating the "slow mode" (e.g., https://github.com/mastodon/mastodon/issues/20552), this behavior makes both the slow and regular updating options annoying at the moment.

### Specifications

Mastodon 4.0.2
Firefox 102.5.0esr

**Comment by vmstan** [comment]
@AlarithUhde does this behavior persist on newer versions of Mastodon?

**Comment by AlarithUhde** [comment]
Yes, still persists.
