### ISSUE TITLE
Planable Posts

### ISSUE THREAD

**Issue by cawer1990** [mastodon/mastodon#22027]
### Pitch

I would like to be able to schedule my posts. Posts already written before should appear at a certain time.

### Motivation

I dont want to flood the timelines of my followers if i am in writing mood.

**Comment by ClearlyClaire** [comment]
Duplicate of #15912. Scheduled posts are implemented server-side, but there is currently no way to create them from the web interface. A lot of Mastodon apps do handle them, though. If you use Android, you could check out Tusky which has support for this feature.
