### ISSUE TITLE
Add account name/account and avatar to posts filtered with a warning

### ISSUE THREAD

**Issue by upstreamist** [mastodon/mastodon#22031]
### Pitch

When Mastodon hides a post to satisfy a filter set by the user, display the post author's name, account and avatar to the filter message, so that the reader knows not just the reason it was filtered, but also the post's source.

### Motivation

When a user sets a filter to hide incoming messages behind a CW, that indicates that they're at least open to the idea of clicking through the CW to see the underlying post. But in order for the feature to be useful for that purpose, they have to have more information to go than just the CW label they assigned to the filter. The post author can be useful for distinguishing, on the basis of trust, posts that might be worth opening, versus posts that are best left behind the CW.

**Comment by bchandos** [comment]
I agree and would like to see this, although I appreciate how compact the current filter indicators are (especially on mobile) and would appreciate seeing only the user's avatar.
