### ISSUE TITLE
Editing a toot reverts content-type selection to default

### ISSUE THREAD

**Issue by stiiin** [mastodon/mastodon#22037]
### Steps to reproduce the problem

1. Change the selection of the content-type in the editor to something else than the default
2. Write a toot and publish it
3. Edit the toot

### Expected behaviour

The editor uses the content-type that was used to publish the toot

### Actual behaviour

The editor uses the default content-type

### Detailed description

Since the editor reverts to the default content-type, which is something I rarely notice, I post the edited toot with the wrong formatting and I end up editing it a second time.

### Specifications

Mastodon v4.0.2+glitch
Firefox 102.5.0esr

**Comment by trwnh** [comment]
This is a glitch-soc issue; Mastodon doesn't have a content-type at all

**Comment by stiiin** [comment]
Oops, sorry. I'll see if I can direct this post to them.
