### ISSUE TITLE
Upgrade from 3.5.5 to 4.0.0 failure

### ISSUE THREAD

**Issue by kdmiller45** [mastodon/mastodon#22044]
### Steps to reproduce the problem

1.changed user to mastodon 
2. cd to /home/mastodon/live
3.  git fetch && git checkout v4.0.0
4. Checking out files: 100% (1570/1570), done.
Previous HEAD position was 696f7b360 Bump version to 3.5.5
HEAD is now at fb389bd73 Bump version to 4.0.0 (#20636)
5, mastodon@topicmaster:~/live$ RAILS_ENV=production bundle exec rails assets:precompile
rbenv: version `3.0.4' is not installed (set by /home/mastodon/live/.ruby-version)

How do I install the required rbenv 3.0.4 

Thanks for the help
Keith

### Expected behaviour

upgrade to 4.0.0
No note in upgrade documentation that rbrnv version 3.0.4 would be required or instructions how to upgrade it. after reading deeper it is mentioned on 4.0.0rc but no note where the .ruby-version file is located or how to overwrite it

Thanks

### Actual behaviour

bombed and reverted back to 3.5.5

### Specifications

Mastodon 3.5.5 => 4.0.0
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

**Comment by killerbees19** [comment]
Quote from the [release notes](https://github.com/mastodon/mastodon/releases/tag/v4.0.0):

> The recommended Ruby version has been bumped to 3.0.4. You can upgrade, or you can continue using the old version by overwriting the `.ruby-version` file with e.g. `3.0.3` which was recommended previously. The minimum version you can use is 2.7.

If you want to upgrade, take a look at the [install manual](https://docs.joinmastodon.org/admin/install/#installing-ruby):

> Once this is done, we can install the correct Ruby version:
> ```
> RUBY_CONFIGURE_OPTS=--with-jemalloc rbenv install 3.0.4
> rbenv global 3.0.4
> ```

Untested, but I think that should do the trick. Backup before proceeding!
