### ISSUE TITLE
List people by tags in their BIO or featured tags

### ISSUE THREAD

**Issue by Ciantic** [mastodon/mastodon#22052]
### Pitch

Lot's of people have tags listed in their bio, some have also featured tags. It would make following and finding people by profession easier, if we could list all people who have some tag in their bio.

### Use case

I would like to follow Mac people, so I could search all people who has #ios #mac in their bio and follow them faster.

### Motivation

Currently lot of new people complain their feed being empty, or can't find people to follow.

If we could list people by certaing tags, it would make finding people to follow easier.

**Comment by rbairwell** [comment]
Do you mean something like https://fediverse.info/explore/people and/or https://search.noc.social/ ?

Withi Mastodon itself, you can search by hashtags which might help find people talking about the subject: I then go to their profile and see who they are following/being followed by and see if there is anyone interesting.

**Comment by Ciantic** [comment]
I mean quiet simply like this:

![image](https://user-images.githubusercontent.com/64731/205620592-60f639da-a280-4aa3-a169-3acef406eaf8.png)

If I type #Mac to search, and go to People tab, I should see all people who has put #mac tag in their BIO. Right now it's just empty.

Since hashtags are sort of category specifications it would help finding people to follow without third party services.
