### ISSUE TITLE
editing a poll makes a mess

### ISSUE THREAD

**Issue by mrAceT** [mastodon/mastodon#22064]
### Steps to reproduce the problem

1. create a poll
2. let people vote
3. discover you made a typo and correct it

### Expected behaviour

just continue? Or warn before save? notify the persons voting for the altered option?

### Actual behaviour

vote count remains, ALL votes are gone

### Detailed description

Also, when new votes are done the percentages shown are on the whole total of votes. Even though those votes have gone..

So, say one can vote for "A" or "B"..
and one person voted "A" => 100% A, 0% B
when I edit option "B" (or "A") total votes remains 1, all results get 0%
then someone votes "B" => 0% A, 50% B

what ever one chooses as the best way to handle this.. the current route isn't the best one IMHO

### Specifications

Mastodon 4.0.2

**Comment by rbairwell** [comment]
I think this is a duplicate of https://github.com/mastodon/mastodon/issues/21696 and https://github.com/mastodon/mastodon/pull/21700 both of which are fixed but not "live" yet.

If you agree, can you please mark this issue as Closed/Resolved so it is easier for the developers to know what needs to be worked on.

**Comment by mrAceT** [comment]
Checked it
https://github.com/mastodon/mastodon/issues/21696 complains about the count error, cause likely the same
https://github.com/mastodon/mastodon/pull/21700 yup, same bug!

I do hope a warning gets given after editing..

I'll close this one (good catch on finding them)

**Comment by embeddedtofu** [comment]
The https://github.com/mastodon/mastodon/pull/21700 pull merely added a line which resets the stats, no warning is issued as this user https://mindly.social/@annecavicchi/109617307317324650 had just experienced.
