### ISSUE TITLE
for you information

### ISSUE THREAD

**Issue by usnotv** [mastodon/mastodon#22071]
### Pitch

https://github.com/LibreTranslate/LibreTranslate

### Motivation

it can help to partially understand texts in different languages

**Comment by rbairwell** [comment]
It is already implemented in Mastodon 4.0 onwards. It just needs the server administrator to install/set it up.

See also https://github.com/mastodon/mastodon/discussions/20903 .

If this answered your question, please mark this issue as Closed/Resolved so the developers know what needs to be worked on.
