### ISSUE TITLE
Vagrantfile doesn't work out of the box

### ISSUE THREAD

**Issue by techhead** [mastodon/mastodon#22074]
### Steps to reproduce the problem

Execute `vagrant up` on main branch.

Install hangs on my 2018 Macbook Pro (macOS Ventura 13.0.1). Vagrant 2.3.3. VirtualBox 7.0.4.

### Expected behaviour

Fully provision development server

### Actual behaviour

Install hangs at `yarn install`

### Detailed description

After several tweaks, I was able to get it working. I'm attaching a pull request and will provide more details below.

After I got past the Vagrantfile hanging on `yarn install`, I encountered the same issue as #19180. I fixed that as well.

In the process, I also brought Ubuntu and Node versions and dependencies up to date with the published documentation.

https://docs.joinmastodon.org/admin/install/

This is also related to issue #19410.

### Specifications

Mastodon edge

**Comment by techhead** [comment]
I spent an embarrassing amount of time on this, especially figuring out the first part, why the `yarn install` was hanging. There don't seem to be many others who have encountered this issue. (2018 Macbook Pro; Intel; macOS Ventura 13.0.1)

I first uninstalled and reinstalled both Vagrant 2.3.3 and VirtualBox 7.0.4. Noticed that the Guest Additions for the VM didn't match the installed version of VirtualBox, so I installed the vagrant-vbguest plugin.

`vagrant plugin install vagrant-vbguest`

No help.

Updated the Vagrantfile to use NodeJS v16 and Ubuntu 20.04 (Focal Fossa) as per the documentation. https://docs.joinmastodon.org/admin/install/

Also updated Vagrantfile to install all the system packages mentioned here. https://docs.joinmastodon.org/admin/install/#system-packages

Still it hangs.

Finally discovered that the issue was caused by the mount options on the /vagrant NFS mount.

https://github.com/mastodon/mastodon/pull/22075#discussion_r1039960280

**Comment by techhead** [comment]
After Vangrant moved successfully past the `yarn install`, `vagrant up` seemed to complete successfully.

```
To start server
  $ vagrant ssh -c "cd /vagrant && foreman start"
```

But when executing the above command, I'd get the response:

```
bash: foreman: command not found
```

This is issue #19180 and is also fixed by PR #22075. So I'll leave further comments and explanations there.

**Comment by techhead** [comment]
PR #22075 was merged. So this issue should be resolved.

**Comment by diasgab** [comment]
I had a similar issue than @techhead. In my case I was trying to run `composer install` and the process would just hang there, without any output.

I thought it was the mismatch between the VM vguest additions, but no, it was the params for mounting nfs.

I had `nfs_udp=false`

After removing that udp option and restarting the vm, everything worked properly!
