### ISSUE TITLE
From time to time an API call fails

### ISSUE THREAD

**Issue by pitosalas** [mastodon/mastodon#22098]
### Steps to reproduce the problem

I am using IFTTT to send a request to Mastodon whenver I post to my blog. Here are the parameters:

UTRL: https://ruby.social/api/v1/statuses?access_token=xxxxxxxEOS3OOss1
Verb: POST
Content Type: application/x-www-form-urlencoded
Body: status= Link blog entry for "a title": a description url (a url)
#some tags

It seems to work sometimes but sometimes I get: Status 422 - Unable to make a web request to ...

### Expected behaviour

A new item should be posted in Mastodon

### Actual behaviour

It doesn't

### Specifications

ruby.social: [About](https://ruby.social/about) · [Profiles directory](https://ruby.social/directory) · [Privacy policy](https://ruby.social/privacy-policy)

Mastodon: [About](https://joinmastodon.org/) · [Get the app](https://joinmastodon.org/apps) · [Keyboard shortcuts](https://ruby.social/keyboard-shortcuts) · [View source code](https://github.com/mastodon/mastodon) · v4.0.2

**Comment by ineffyble** [comment]
422 makes me think sometimes IFTTT is sending a broken/invalid request, are you able to find any pattern as to which ones fail?

**Comment by ClearlyClaire** [comment]
It would also be useful to get the body of the 422 reply, it usually tells what is going on.

Also, I'd advise against passing the access token in the URL. If possible, use the `Authorization` header with `Authorization: Bearer <token>`
