### ISSUE TITLE
Make mastodon http status notifications aware

### ISSUE THREAD

**Issue by hansw-nlo** [mastodon/mastodon#22119]
### Pitch

Dear all, 

I am sure there are hundreds of requests like this since the twitter move to mastodon. I am on hubzilla and used ActivityPub to reach 5 people using Mastodon. Worked like a charm until the flood came in. I disabled Mastodon and only discovered that instances will keep on trying to contact the user on my server so I made sure that 404's where generated. Did not help, I started to generate 403's, nothing new, the flood continues. 

Can you please fix this. I know how to handle it on my side, thinking about switching from a reject in the fw to a drop since nobody is watching it but that would mean a huge penalty on my server and probably oops on some smaller mastodon instances. 

All in all it could be fixed if people act, sadly they do not.

### Motivation

Preventing a DDOS

**Comment by ineffyble** [comment]
The solution to this would be to re-enable, block everyone who follows you, then disable again.

**Comment by hansw-nlo** [comment]
No, tried that. Does not work. I simply get flooded, the software should be http status aware on the mastodon side, on our side it already is.

**Comment by ineffyble** [comment]
Blocking should stop the remote users following you and thus queries from remote instances. If it doesn't, then I wonder if there's something missing in the Hubzilla implementation of ActivityPub.

**Comment by lazyteddy** [comment]
I can confirm that blocking is not a solution. I never enabled ActivityPub on my current Hubzilla server and hence was never connected to anybody on Mastodon (or Friendica, or Pleroma, or anywhere else that uses AP.) I still get thousands of requests from Mastodon servers a day.

It would be very much appreciated if somebody looked into this. Hubzilla (and, by extension, Zap and Streams) mark a site as dead after 30 days if delivery attempts remain unsuccessful. I would imagine something like this to be beneficial for both the Mastodon instance and the hub; all those requests are nothing but useless traffic that could be avoided.

The default behavior for Hubzilla without AP enabled is to send a 404 error to the site trying to deliver. This could be a starting point.

**Comment by hansw-nlo** [comment]
Sadly I might have broken a machine (small one) by dropping traffic. I suppose it comes down to who will break first. I will apologize to Ton when this is fixed.

**Comment by rbairwell** [comment]
Whilst I agree the Mastodon should respect the http status codes, there should be some leeway. I have experienced issues where webservers/proxies incorrectly return the wrong status code for a period of time for whatever reason (Cloudflare having an issue, network misconfiguration causing routes to go to the wrong server, software misconfiguration - especially during upgrades, load balancer failures etc).

I think if Mastodon receives a 4xx or 5xx code, it should double the retry period for that request every time it gets one of those statuses or invalid JSON and fails the task complete if it has gone over 48 hours. If a single domain has more than 20 failures (or 90% of all requests to it: whichever is highest) fail in a continual 5 day timespan, then that instance/domain should "blocked" from interaction for another 5 days (with admin/mods being able to reinstate) to save "spamming" non-Mastodon servers.

**Comment by lazyteddy** [comment]
> Whilst I agree the Mastodon should respect the http status codes, there should be some leeway. I have experienced issues where webservers/proxies incorrectly return the wrong status code for a period of time for whatever reason (Cloudflare having an issue, network misconfiguration causing routes to go to the wrong server, software misconfiguration - especially during upgrades, load balancer failures etc).

That is precisely why Hubzilla / Zap / Streams have the 30 day grace period before they mark a site as dead. I think it's a good compromise.

**Comment by hansw-nlo** [comment]
Good though @rbairwell . Sadly some even try harder without looking.

**Comment by hansw-nlo** [comment]
And not only a complete site but individual accounts are set that way.

**Comment by hansw-nlo** [comment]
Maybe I should compare mastodon to bitmining to get some attention?

@Gargron Can you do something?

**Comment by hansw-nlo** [comment]
Never mind, blocklist will be there in a week or so.
