### ISSUE TITLE
why this happen

### ISSUE THREAD

**Issue by yinnxinn** [mastodon/mastodon#22123]
### Steps to reproduce the problem

I fix #22111  by change config/webpacker.yml . and I get no 404 error , but the site display without style ..

Anyone could tell me why .

### Expected behaviour

display normally

### Actual behaviour

display without pattern

### Detailed description

![image](https://user-images.githubusercontent.com/23116748/206182463-7e055b9e-760a-42ae-ae4b-04b05dfa5935.png)

### Specifications

docker

**Comment by ClearlyClaire** [comment]
We can't help you without knowing what you changed in `config/webpacker.yml`

**Comment by yinnxinn** [comment]
> We can't help you without knowing what you changed in `config/webpacker.yml`

thanks for reply . fixed because of nginx config error
