### ISSUE TITLE
Replies to own posts are displayed in "Posts" view as well as "Posts and replies" view

### ISSUE THREAD

**Issue by velw** [mastodon/mastodon#22152]
### Steps to reproduce the problem

1. Publish a post
2. Publish a reply to your own post
3. Your reply to your own post appears above your initial post on your profile page, on both the "Posts" and the "Posts and replies" view.
...

### Expected behaviour

The interface descriptions suggest a reply should only be visible in the "Posts and replies" view, not both the "Posts" and the "Posts and replies" view.

### Actual behaviour

Your reply to your own post appears above your initial post on your profile page, on both the "Posts" and the "Posts and replies" view.

### Detailed description

As described, your replies to your own posts appear on your profile page, on both the "Posts" and the "Posts and replies" view.

This is inconsistent with how users' replies to any other posts are handled, so is counterintuitive.

It also makes threading a post yourself confusing in the profile view, because the posts appear backwards, starting from the end, for anyone who happens to visit the users' profile page. That may happen if they click on the "Posts and replies" view, but if they did that it's what they would be expecting.

### Specifications

Mastodon v4.0.2
Viewed in Firefox (98) and Samsung Internet. I don't think this behaviour varies by browser version.

**Comment by kepae** [comment]
I think that this behavior is working as intended and this issue should be closed, per https://github.com/mastodon/mastodon/pull/23257#issuecomment-1404669434.

(Unless the "interface descriptions" have more details that suggest otherwise? I don't know what they're referring to for sure.)

**Comment by velw** [comment]
> I think that this behavior is working as intended and this issue should be closed, per [#23257 (comment)](https://github.com/mastodon/mastodon/pull/23257#issuecomment-1404669434).
> 
> (Unless the "interface descriptions" have more details that suggest otherwise? I don't know what they're referring to for sure.)

The "interface descriptions" is the words (descriptions) in the interface. A "self-reply" is a "reply" (you can tell because it has the word "reply" in it). When you click the tab to see "Posts" you should see posts. When you click the tabs to see "Posts and replies" you should see posts and replies. What the site is doing is showing you (self) replies when it shouldn't be.

I really don't think this should have been closed -- especially not "because that's the way it has always worked and what people most familiar with coding it expect it to do". What about what your end users expect it to do?

**Comment by ClearlyClaire** [comment]
It indeed shouldn't have been closed as completed, but rather as not planned, changing that.

> I really don't think this should have been closed -- especially not "because that's the way it has always worked and what people most familiar with coding it expect it to do". What about what your end users expect it to do?

I believe that's also how most existing users expect it to work.

**Comment by velw** [comment]
> It indeed shouldn't have been closed as completed, but rather as not planned, changing that.

Thank you

> I believe that's also how most existing users expect it to work.

If the tab was called "Posts and interactions" I would expect it to work this way, and if this really is how most existing users want it to work perhaps that's what the tab should be called. A "self-reply" is a "reply"; a tab explicitly labelled as excluding replies but including them is very counterintuitive.
