### ISSUE TITLE
Excessive RAM usage by puma (until OOM killer)

### ISSUE THREAD

**Issue by leahoswald** [mastodon/mastodon#22201]
### Steps to reproduce the problem

Difficulty to explain. But we have 8 puma workers with 15 threads each. No special config for puma. There is only redis, with a fixed usage of RAM on the same system. 

### Expected behaviour

No excessive RAM usage

### Actual behaviour

A single puma worker process consumes up to 11GB RAM before it is killed by the oom killer

### Detailed description

Since a while we observe very huge RAM usage by the puma workers. We use MAX_THREADS=15 and WEB_CONCURRENCY=8. After less than 24 hours the puma service is killed by the OOM killer because the worker processes used up to 11GB RAM and consumed all 64 GB RAM that is available. We increase RAM multiple times but every time the puma workers just consume more RAM until they get killed.

![Screenshot2022-12-09_11-49-19](https://user-images.githubusercontent.com/1292551/206852226-95a833e5-aeb4-4d5f-9d2f-b1d19470cfa1.png)

### Specifications

Mastodon 4.0.2
Ruby 3.0.4
Up to date Debian 11

**Comment by ineffyble** [comment]
Is there anything in your logs that might give clues as to what's happening here?

**Comment by leahoswald** [comment]
For now noting but it's a good hint, I will increase the log level a little more.

**Comment by leahoswald** [comment]
Noting special in the info log and noting in the debug log too.

**Comment by leahoswald** [comment]
Looks like using `Environment="LD_PRELOAD=libjemalloc.so"` from [the service file in the mastodon repo](https://github.com/mastodon/mastodon/blob/main/dist/mastodon-web.service) helped but I have to wait a few hours to be sure. So it is a memory allocation problem.

**Comment by leahoswald** [comment]
Looks much better now after adding this option.

![Screenshot2022-12-10_17-54-14](https://user-images.githubusercontent.com/1292551/206866220-2fb0de6c-aac3-4cce-b429-e21900f84709.png)
