### ISSUE TITLE
Language Kurmancî shows up twice

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon#22200]
### Steps to reproduce the problem

1. Open the language picker
2. Type "Kurdish"
3. See that Kurmancî (kmr/ku) is listed twice

![Screenshot_2022-12-10-12-00-44-290-edit_com kiwibrowser browser](https://user-images.githubusercontent.com/6217438/206851756-ef14ca89-35a8-4f2b-a3e2-da4ac711bef3.jpg)

### Expected behaviour

Each language should be listed just once

### Actual behaviour

Kurmancî is being listed twice (kmr and ku)

### Detailed description

While trying to figure out which languages my Mastodon client should support (the API docs just say "ISO 639 language code", which should probably be specified – there's no way to query the supported languages, is there?) and after hearing that some [ISO 639-3 languages are missing](https://github.com/sk22/megalodon/issues/139) from Java's ISO 639-1 language list, I looked up the `LanguagesHelper` module, where I found two lines for the same (?) language:

```
ku: ['Kurmanji (Kurdish)', 'Kurmancî']
…
kmr: ['Kurmanji (Kurdish)', 'Kurmancî']
```

### Specifications

Mastodon v4.0.2

**Comment by sk22** [comment]
Seems to have been introduced by this commit: https://github.com/mastodon/mastodon/commit/b07906bdb0127cd73662506b519183cc51a2758e

**Comment by sk22** [comment]
From what I can tell, `ku` ([ISO 639-1](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=ku)) (or `kur` in [ISO 639-3](https://iso639-3.sil.org/code/kur)) is actually more the group of [Kurdish languages](https://en.wikipedia.org/wiki/Kurdish_languages) (kurdî) – that's also the name Java spits at me when I ask it for `new Locale("ku").getDisplayName(new Locale("ku"))`; not (necessarily) "Kurmancî", as the Mastodon language list suggests.

According to https://iso639-3.sil.org/code/kur, there's three languages for the macrolanguage "kur":
* ckb (Central Kurdish / Sorani, کوردیی ناوەندی / سۆرانی)
* kmr (Northern Kurdish / Kurmanji, کورمانجی / Kurmancî)
* sdh (Southern Kurdish, کوردی باشووری)

(Now unfortunately for me, Java/Android doesn't know the native name of "kmr", but it's in the Mastodon language list anyway)

**Comment by sk22** [comment]
So, I'd propose to remove `ku` in favor of `ckb`/`kmr` and possibly `sdh` – or would there be compatibility issues? :/

**Comment by sk22** [comment]
Or instead of removing `ku`, maybe renaming the display language to "Kurdî (Kurdish)" instead of "Kurmancî (Kurmanji (Kurdish))" would be an option?

**Comment by gunchleoc** [comment]
I made a Pull Request based off of issue https://github.com/mastodon/mastodon/issues/22647
