### ISSUE TITLE
Show focused toot at the top instead of at the bottom

### ISSUE THREAD

**Issue by agenbite** [mastodon/mastodon#22208]
### Steps to reproduce the problem

0. Focus a column in the advanced view.
1. Use the keyboard to select next toot through the `j` binding.
2. See the lower part of the focused toot align with the lowest part of its column.

### Expected behaviour

When scrolling with the keyboard, `j`/`k` navigation should put the focused toot at the top of its column.

### Actual behaviour

Right now, the next toot comes aligned at the bottom of the shown column, which, if you have a big font size or scarce screen real estate, will show long toots cropped at the top (hence impossible to read). 

### Specifications

Mastodon v4.0.2
Advanced web interface (in the standard one it's even worse, since the next toot shows right in the middle of the available space, not even aligned with anything).
Browser: qutebrowser v2.5.2
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144

Related: https://github.com/mastodon/mastodon/issues/19100#issuecomment-1320903559

**Comment by trwnh** [comment]
Fixed by #21797
