### ISSUE TITLE
/api/v1/instance/peers should be optional even on non-allowlist instances

### ISSUE THREAD

**Issue by kescherCode** [mastodon/mastodon#22222]
### Pitch

Not all instances want to provide the info which instances they're federating with, *especially* not since some hate sites are scraping instances for public domain blocks already. Therefore, add a .env option to disable the endpoint entirely, as it is not needed for federation.

### Motivation

Everyone that doesn't want to have peering data scraped by yet another scraping tool that does not care about consent would greatly benefit from this.

**Comment by ClearlyClaire** [comment]
It's controlled by `peers_api_enabled`, which it seems has disappeared from the admin UI in #19407

**Comment by f0x52** [comment]
Will it be coming back to the admin interface?

I would also expect `AUTHORIZED_FETCH` and especially `DISALLOW_UNAUTHENTICATED_API_ACCESS` to affect public availability of this endpoint, but they don't seem to at all?

**Comment by ClearlyClaire** [comment]
Other settings that seem to have been nuked with that design change are:
- `preview_sensitive_media`
- `activity_api_enabled`

I am personally in favor of adding them back to the admin interface, though I'm not sure where they should fit exactly. At worse I find it's acceptable to have an “Other” category.

**Comment by kescherCode** [comment]
I mean, there already is an other category. I suppose they can go there.

**Comment by Gargron** [comment]
Just want to address something from the OP:

> Not all instances want to provide the info which instances they're federating with

The peers API does not say who you're federating with, just who you are aware exists.

**Comment by f0x52** [comment]
Why is making this endpoint publicly accessible more important than the explicit choice to prevent unauthenticated api access?

Kind of moot point now that it's totally removed from the settings UI.. but I'm also not a fan of it having a "Recommended" badge without any further explanation why it would be recommended, so admins can make an informed choice.

**Comment by ClearlyClaire** [comment]
> The peers API does not say who you're federating with, just who you are aware exists.

That's true, except in limited federation mode the two are pretty much the same thing.

> but I'm also not a fan of it having a "Recommended" badge without any further explanation why it would be recommended, so admins can make an informed choice.

I suppose it is because Gargron wants to encourage the endpoint being available so he can do stuff like the “Network health” thing in https://joinmastodon.org/servers

**Comment by ShadowJonathan** [comment]
We see a lot of scraping on this endpoint, which makes me nervous, a toggle would be nice.
