### ISSUE TITLE
input handler takes about 1000ms per character typed into the posting box

### ISSUE THREAD

**Issue by BenLubar** [mastodon/mastodon#22225]
### Steps to reproduce the problem

1. type the word "test" into the posting box
2. ![image](https://user-images.githubusercontent.com/4257305/206890309-8d3b0103-c6ac-4bf0-9fad-fc3d816b8b3f.png)

### Expected behaviour

text I type should be added to the box by my browser and not delayed by 1 second

### Actual behaviour

whenever I touch my keyboard my laptop freezes up for 1 second

### Specifications

Mastodon nightly 2022-12-11
happens both on my Chromebook and my Windows 10 machine with Firefox

**Comment by ineffyble** [comment]
Hmm, I can't replicate this if I run Mastodon locally on HEAD of main (ad568924c064c41e056dfec651217dbe7bb637fc).

**Comment by rbairwell** [comment]
I've not seen this on Chromium based or Firefox on Windows 10 or Android on 4.0.2...
Have you got any plugins installed on the browser, debug/not-production settings enabled on the instance and/or any metrics gathering software on the instances (which could be interacting with the Javascript).

**Comment by BenLubar** [comment]
It's less noticeable right after I've restarted my browser or recently opened the tab

https://share.firefox.dev/3W9XhV4

maybe some event handler is being added multiple times?

**Comment by ClearlyClaire** [comment]
This is likely dependent on the number of loaded (or at least displayed) posts, and it may be worse using glitch-soc. Behind the hood, typing updates the redux store, and it is likely that some container does not select/memoize relevant store parts the way it should, causing wasteful re-renderings.

**Comment by ClearlyClaire** [comment]
After a quick investigation, I believe this is a glitch-soc issue, see https://github.com/glitch-soc/mastodon/pull/2063
