### ISSUE TITLE
Translate should translate entire post

### ISSUE THREAD

**Issue by eishiya** [mastodon/mastodon#22249]
### Pitch

The Translate button should translate all the content of a post, not just the body text.

### Motivation

The Translate button currently ignores all of these:
- CW text
- media descriptions
- polls (#21247)

This means that in many cases, the bulk of the post is left untranslated.

Regarding CWs, I think the Translate button should be available *outside* the CW, so that you can translate the post and read the CW before showing the rest of the post.

**Comment by ineffyble** [comment]
On the other hand, Translate does sometimes translate URLs which is not desired 🙃

**Comment by renchap** [comment]
Fixed in #24175
