### ISSUE TITLE
Please add Latin on CrowdIn

### ISSUE THREAD

**Issue by Michi83** [mastodon/mastodon#22248]
### Pitch

One of my followers, a Latin teacher, is eager to volunteer a Latin translation of the Mastodon UI. He already tried to contact the developers on CrowdIn and via other channels but hasn't recieved a response so far. Please add Latin on CrowdIn, so he can start.

### Motivation

Latin is still widely studied and many European languages, including English, derive a sizable part of their vocabulary from Latin. It shouldn't be difficult to recruit more volunteers with various levels of proficiency to get the work done quickly and ensure the future maintenance of the language. A Latin UI might allow Latin teachers to use Mastodon as a remote teaching tool. Some communities might still prefer Latin over English as their lingua franca. Some people are exploring the possibility of reviving Latin as a spoken language and social network with a Latin UI might be of interest to them.

**Comment by nemobis** [comment]
Agreed. Latin has a very active translator community, see for example https://translatewiki.net/wiki/Portal:La

**Comment by gunchleoc** [comment]
This has been done https://crowdin.com/project/mastodon/la-LA

**Comment by renchap** [comment]
Closing this as the language has been created on Crowdin.

Once the Crowdin translation is good enough for users, please open a Pull Request to update `app/helpers/languages_helper.rb` and `config/initializers/i18n.rb` to add the language (or open an issue asking us to do it).

Thanks!
