### ISSUE TITLE
Faulty Cache Behaviour: accounts_controller uses different TTL based on "Accept"-header

### ISSUE THREAD

**Issue by lifeofguenter** [mastodon/mastodon#22242]
### Steps to reproduce the problem

There are 2 ways to access a user profile:

1. **via file extension,** example: https://convo.casa/@lifeofguenter vs https://convo.casa/@lifeofguenter.rss
2. **via HTTP Accept header**, example: `curl -I -H 'application/json' https://convo.casa/@lifeofguenter` vs. `curl -I -H 'text/html' https://convo.casa/@lifeofguenter`

There are three different cache-control expire TTL based on the content-type:

1. HTML: [no-cache](https://github.com/mastodon/mastodon/blob/main/app/controllers/accounts_controller.rb#L19)
2. RSS: [1 minute](https://github.com/mastodon/mastodon/blob/main/app/controllers/accounts_controller.rb#L25)
3. JSON: [3 minutes](https://github.com/mastodon/mastodon/blob/main/app/controllers/accounts_controller.rb#L33)

Due to the different cache-behavior under the same URL it is not possible for a caching layer on-top to efficiently cache the requests.

With [BunnyCDN](https://bunny.net) this can be mitigated like so (but bypasses cache for non-suffix/accept-header requests):

![Screenshot from 2022-12-11 23-21-18](https://user-images.githubusercontent.com/241073/206932281-cdd0a045-e3dc-470e-b659-977873381b9f.png)

### Expected behaviour

Cache-Control should not change on "Accept" header, especially since its not easy to parse

### Actual behaviour

Cache-Control differs depending on Accept header

### Specifications

Mastodon 4.0.2 (official Docker image)

**Comment by ClearlyClaire** [comment]
The HTML version cannot and should not be cached, as it will set cookies, as well as render a user-specific access token when a user is logged in.

**Comment by lifeofguenter** [comment]
@ClearlyClaire exactly. The issue here is that there are different cache-times depending on the "Accept" header. So you would have to "Vary" by that, but given the complexity of the Accept header its not as simple as simply doing a key <> value check.

The primary intention should have most probably been to not change content + cache-control depending on Accept-header, but only based on different Path/URL ? (e.g. suffix .json == json)

**Comment by ClearlyClaire** [comment]
ActivityPub implementations fetch the JSON representation with an `Accept` header, not by adding `.json`

**Comment by lifeofguenter** [comment]
Yes, that is exactly the issue. You can not cache the exact same URL differently. How does the web server know which content to serve?

**Comment by ClearlyClaire** [comment]
How is this related to having different `Cache-Control` responses? The content would still depend on the value of `Accept` if the cache control policy was the same for all cases.

In any case, the current behavior is that mastodon sets the `Vary` header to depend on `Accept` (and `Signature` when `AUTHORIZED_FETCH` mode is set), so this is sound, although suboptimal.

In the future, it might make sense to split the existing `AccountsController` between `/users/:foo` which would only serve the JSON representation, and `/@:foo` which would serve the remaining ones, though. But `AUTHORIZED_FETCH` for instance would prevent caching in any case.

**Comment by lifeofguenter** [comment]
> How is this related to having different Cache-Control responses? 

This is related, because if html should not be cached, but other content-types should be, you will end up eventually with wrong cache data. E.g. its less significant what those values are, but more so if caching is suggested or not by the origin.

> In any case, the current behavior is that mastodon sets the Vary header to depend on Accept

You are right! I missed that header. So while not ideal because `Accept` can be very arbitrary, it at least should be "working as expected".

This is then an isolated issue with caching web servers that do not support `Vary` headers from the origin. I will close this ticket. Thank you for clarifying :)
