### ISSUE TITLE
Define Canonical URLs?

### ISSUE THREAD

**Issue by hackbod** [mastodon/mastodon#22245]
### Pitch

Define a canonical URL space for links to Mastodon posts (and maybe other things) that can be shared outside of Mastodon to get a more seamless experience when opening them.

For example, define a domain like "mastodon.link" as this space. This isn't a Mastodon instance, but just a namespace in which to put links that can then be redirected to the right place -- such as either the opener's own instance or the instance where the post lives. The URL contains all of the information needed to do the redirect, so the server behind this URL could probably serve a simple static page that parses the URL, allows the user to set their preferred instance (stored in a cookie), and perform the appropriate redirect.

This does violate the ideals of federation in creating a single point for these interactions. However, I think you can make this more appealing by viewing it as a convention: ideally things will know "mastodon.link" is special and can handle it without actually needing a server behind it, so the server sits there as a backstop for anything that isn't aware of it.

In particular, for mobile apps this gives them the ability to handle such links locally when they are tapped from elsewhere, without needing to touch the server.

### Motivation

Sharing links to Mastodon posts can be awkward, because there are multiple possible URLs that result in better or worse behavior.  In particular, I think current best practice is to share a link to the instance hosting the post, however this results in awkward interactions, such as: (1) when I open it I will end up on that instance, rather than my own instance where I could actually interact with it, and (2) mobile apps can't easily have these links directed to them since the set of possible domains is unlimited and undefined.

This could also help with other things, like "share with Mastodon" links being defined in this canonical URL space so the user only needs to configure in one place what their preferred instance is and then have such links work automatically everywhere.

**Comment by nightpool** [comment]
No, sorry, the entire purpose of Mastodon's decentralized model is that every individual instance can have whichever software it wants and acts as the root of trust for the post in question. You can visit #19679 for more info about handling cross-server interaction without resorting to a single, centralized domain name

**Comment by hackbod** [comment]
Thanks!  Yeah I totally get that this would move a bit in a direction from a pure distributed model which is tough.

However, if all that bug is talking about is a custom scheme and protocol handlers, that is not going to address the kinds of interactions I am considering here. We've gone through this a lot with app developers on Android. The problem with custom schemes is that they don't fail gracefully, so you can't use them for interop anywhere you don't know who will be opening them.

That is, I couldn't share a mastodon: link to my friends unless I knew all of them had configured the device they would be opening it on to understand it. If they didn't, they would just have a totally broken experience. I likewise couldn't use a mastodon: link for a "share with Mastodon" button on my web site.

I don't know if there is another solution for this besides defining a convention for the http namespace where such links can go, but I don't think a custom scheme is it.

Also to address the conflict with federation -- I am viewing this proposal as not something instances use themselves, in that case they can construct the right stuff they want and maybe a mastodon: scheme makes sense for them. Rather this is for when you want to take a link out of the Mastodon ecosystem and use it elsewhere, in a way that allows it to still get back to the right place when handled by someone else.

**Comment by nightpool** [comment]
The goal is NOT for users to share mastodon: links with other users, but for e.g. https://mastodon.social pages to be able to use mastodon: URLs to allow you to interact with the content on your own instance if you wish.
