### ISSUE TITLE
Viewing profile or home time line results in 500 error

### ISSUE THREAD

**Issue by SMJ** [mastodon/mastodon#22254]
### Steps to reproduce the problem

1. Load the profile page of the affected account url/@account
2. browser displays 500 errors

```
journalctl -xefu mastodon-web.service reports:

NoMethodError (undefined method `first' for nil:NilClass):
app/controllers/concerns/cache_concern.rb:43:in `cache_collection'
app/controllers/concerns/cache_concern.rb:54:in `cache_collection_paginated_by_id'
app/controllers/api/v1/accounts/statuses_controller.rb:25:in `cached_account_statuses'
app/controllers/api/v1/accounts/statuses_controller.rb:21:in `load_statuses'
app/controllers/api/v1/accounts/statuses_controller.rb:10:in `index'
app/controllers/concerns/localized.rb:11:in `set_locale'
lib/mastodon/rack_middleware.rb:9:in `call
```

### Expected behaviour

Profile page should load with a summary of account statuses

### Actual behaviour

500

### Detailed description

an attempt to bin/tootctl feeds build accountname was tried.

Using a small browser side, the profile of the account loads fine with a single 500, but attempting to scroll down into the account's toots results in endless 500s.

### Specifications

Mastodon 4.0.3
Ruby 3.0.4p208
Node v14.21.1

any browser

**Comment by ineffyble** [comment]
Is your Redis definitely running and is Mastodon definitely configured correctly to use it?

**Comment by SMJ** [comment]
This appears to be resolved.  The symptom is that an individual's profile can be loaded, but as soon as the status summary is pulled the page goes blank with numerous 500s reported in the client.  When rebuilding index_status_stats_on_status_id it was discovered that there were duplicate records in status_stats and conversations.  These could be identified with:

`select id, status_id, count(*) from status_stats group by id, status_id having count(*) > 1;`

Removing the 5 duplicate records allowed for a successful reindex index index_status_stats_on_status_id; seems to have resolve the issue.

Note that for large databases reindex can take quite a bit of time and requires locking, it is best to do this while your instance is offline.
