### ISSUE TITLE
Reply language should default to user language instead of previous comment language.

### ISSUE THREAD

**Issue by nuclearfall** [mastodon/mastodon#22250]
### Pitch

Current Behavior: Replying to a post, defaults to the previous poster's language.

Suggest: Replying should always to the user's default language. 

This is the behavior that is required to defeat language barriers in communication. I'm almost always going to be replying in EN, otherwise I wouldn't need the translation. So my reply should default to EN so my friend can translate my post EN -> DE and his reply won't be in EN if I do change my reply language language to EN.

### Motivation

To ensure that communication barriers are negated by translations in Mastodon. This benefits anyone who wants to communicate with anyone outside of their known languages.

**Comment by ineffyble** [comment]
Hmm, this makes sense in your context but falls down a bit for multilingual users. I wonder if the behaviour could depend on whether the post has been translated. E.g. clicking translate for a post will mean that replying to it will use the user's default language.

**Comment by eishiya** [comment]
If going based on translation status isn't possible, then I think a user preference would be good. I reply in the original language when I can, so I'd prefer to use the current behaviour, set the initial language to that of the post I'm replying to.

**Comment by ClearlyClaire** [comment]
> Hmm, this makes sense in your context but falls down a bit for multilingual users. I wonder if the behaviour could depend on whether the post has been translated. E.g. clicking translate for a post will mean that replying to it will use the user's default language.

Doing this based on translation status would definitely make sense!
