### ISSUE TITLE
Start dev environment error foreman

### ISSUE THREAD

**Issue by tomtom94** [mastodon/mastodon#22266]
### Steps to reproduce the problem

`vagrant up`has successfully worked, then

```
$ vagrant ssh -c "cd /vagrant && foreman start"
bash: foreman: command not found
Connection to 127.0.0.1 closed.
```

### Expected behaviour

should have started the server

### Actual behaviour

foreman not found

### Specifications

MacOs Monterey

**Comment by tomtom94** [comment]
It's ok I just made

```
git pull
```

and it works

**Comment by naught101** [comment]
Just git pull, or did you run some other command afterwards?

**Comment by naught101** [comment]
Ah, as per https://github.com/mastodon/mastodon/issues/19180, running `vagrant ssh -c "cd /vagrant && gem install foreman"` did it for me.
