### ISSUE TITLE
Can't view posts (or get redirected for boosts) with a migrated account

### ISSUE THREAD

**Issue by zigdon** [mastodon/mastodon#22262]
### Steps to reproduce the problem

1. Create an account on instance A
2. Migrate it to another instance B
3. Try to follow links to posts on A
  3.a Try to view a link to a boost of a post in another instance (C), posted on an account in A
4. Click on the `logout` button
5. Repeat 3.
...

### Expected behaviour

Links to A should still display content, just not allow posting

### Actual behaviour

Any link to A redirects to `A/auth/sign_in`

### Detailed description

Any attempt to follow a link to the original instance just leads to the redirect settings page, with an error `Your account is inactive because it is currently redirecting to <new_account>. [Cancel redirect])`

### Specifications

Observed on mastodon.social (v4.0.2)

**Comment by ClearlyClaire** [comment]
Sorry, I'm not sure I understand your issue, you are supposed to be able to view posts even when logged into an account that has moved (but apart from the log out button, it should not behave differently than when logged out). You also haven't told what happens when you “Click on the `logout` button”

When you write “Observed on mastodon.social”, does that mean mastodon.social is the “A”, “B” or “C” in the issue?

**Comment by zigdon** [comment]
I had an account on mastodon.social, migrated to tech.lgbt. whenever I'd try to follow a link to any post on m.s, it would redirect me to the migration page, rather than showing the post (or redirecting to another instance if it's a boost).

Once i logged out, it worked as expected.

Does that help? I can try collecting screenshots if not.

**Comment by zigdon** [comment]
After logginging to m.s, I get this:

![image](https://user-images.githubusercontent.com/44372/208459082-8cf98d63-393d-499f-98e2-f475c86dd54e.png)

Then clicking on https://mastodon.social/@Sarahnade@peoplemaking.games/109371235556370683, I end up there again.

**Comment by ClearlyClaire** [comment]
Oh! You're trying to see a remote post, that isn't something I tried! Thanks.
