### ISSUE TITLE
:verified: after display name does not translate to a blue checkmark

### ISSUE THREAD

**Issue by ssarhangi** [mastodon/mastodon#22293]
### Steps to reproduce the problem

add :verified: after display name in edit profile

### Expected behaviour

see a blue checkmark

### Actual behaviour

seeing :verified: text instead

### Specifications

Mastodon 4.0.2
Edge, Firefox browser

**Comment by ineffyble** [comment]
Does your Mastodon instance have a custom emoji with the name `verified`?

**Comment by nightpool** [comment]
There's nothing special in mastodon about the text `:verified:`, it's simply a custom emoji that some servers implement to make fun of Twitter.

**Comment by ssarhangi** [comment]
So, is it dependent on whether the server implements it? I like it to work so I can make fun of twitter too. Don't take the fun out of it. :-)
