### ISSUE TITLE
Auto-discovery for JSON rendition of Profile Pages

### ISSUE THREAD

**Issue by kidehen** [mastodon/mastodon#22306]
### Pitch

Currently, RSS feeds associated with a profile page are auto-discoverable via  <link rel="alternate" href="{rss-file-url}" /> embedded in the <head/> section of a profile page. That makes RSS feed discoverable by RSS-aware tools e.g., RSS Readers. 

It's just as important to offer similar functionality for enhancing the discovery of JSON files that provide a representation of ActivityStream, which can be achieved via <link rel="alternate" href="{profile-page-url}.json" />.  

### Motivation

Making the JSON representation of a users ActivityStreams easier to discover from their profile i.e., not solely depending on the manual addition of a ".json" extension to profile page URLs. 

Here's an example of what would happen automatically, using an ActivityStreams aware client that can visualize JSON:  https://mastodon.social/@kidehen/109512857632159050

**Comment by nightpool** [comment]
This already exists:

for the status page:
```
<link href='https://mastodon.social/users/kidehen/statuses/109512857632159050' rel='alternate' type='application/activity+json'>
```

and for the profile page:
```html
<link href='https://mastodon.social/users/kidehen' rel='alternate' type='application/activity+json'>
```

Additionally, you can just make your request with the right `Accept` header to begin with, which is what I recommend when writing a standalone client. The `link` tags are only useful for browser extensions or clients that are already processing the HTML for some other purpose.

**Comment by nightpool** [comment]
I don't understand your point. What client is processing the `link` tag to find the one with the right `type` parameter, but then can't process the `type` parameter when making the request?  If it has enough logic to find `type = "application/activity+json"` then it has enough logic to add `Accept: application/activity+json` to the outgoing request. In a browser, this would be using the `fetch` or `XMLHttpRequest` primitives.

**Comment by kidehen** [comment]
Do you know any Web Browser that will request "application/activity+json" for https://mastodon.social/users/kidehen? 

I have a [Browser Extension](https://medium.com/openlink-software-blog/openlink-structured-data-sniffer-osds-version-2-21-6-4026eddb47db) that can handle the value of the <link rel="alternate" .../> relation if there is an unambiguous URL denoting a document of a specific type. 

It appears to me that you are assuming that <link rel="alternate" type=application/activity+json" /> implies the following client request:

```
curl -ki https://mastodon.social/users/kidehen -H "Accept: application/activity+json" 
```

If so, I can apply to my tool -- but I wouldn't recommend this assumption for user-agents in general which is the reason i opened this issue. 

Being specific via the following offers more flexibility to clients.
`<link href='https://mastodon.social/users/kidehen.json' rel='alternate' type='application/activity+json'>`

**Comment by pfefferle** [comment]
@nightpool, the Accept header might be a clear requirement according to the AP spec, but not for rel-alternate. The [HTML spec states](https://html.spec.whatwg.org/dev/links.html#rel-alternate):

> If the alternate keyword is used with the `type` attribute, it indicates that the referenced document is a reformulation of the current document in the specified format.

So, I would also expect that <link rel='alternate' type='application/activity+json'> would work similarly to the RSS rel-alternate link and directly return the Activity-JSON!

I see that this is now widely adopted, but it still feels wrong, nevertheless.

I've been considering writing a [FEP](https://codeberg.org/fediverse/fep) that introduces rel-alternate as an alternative to content negotiation. This could lead to better ActivityPub support, especially on shared hosting (as seen in the WordPress implementation), and rel-alternate would be a perfect solution for that.

**Comment by nightpool** [comment]
The ActivityPub spec requires that clients send the Accept header. Given the current deployment of servers that require the Accept header and use it for content negotiation, I don't see that changing. It's more important that the URL in the `link rel=alternate` tag exactly matches the `id` of the returned object.

> This could lead to better ActivityPub support, especially on shared hosting (as seen in the WordPress implementation),

Nothing in ActivityPub really requires that *servers* need to support connection negotiation. For example, it's perfectly valid for a given server to support having a JSON-only `id` url with a separate HTML human-readable `url` property. It only says that clients need to. So implementing this proposal wouldn't improve anything for shared hosting.
