### ISSUE TITLE
CSP error for inlined two SVGs 

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#22317]
### Steps to reproduce the problem

1. visit https://mastodon.social
2. load console

`Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' https://aussocialstatic.b-cdn.net 'nonce-AAjcBDnkcDkU1YeybDx26w=='". Either the 'unsafe-inline' keyword, a hash ('sha256-7tsmGaw+rilRAyeDpgSgI1BtB1Cj9tGH8tjHKYTiDaE='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.`

### Expected behaviour

No errors

### Actual behaviour

errors

### Detailed description
I believe this is the cause

```
<use xlink:href="#logo-symbol-icon" style="color:#fff" />
```
and
```
<use xlink:href="#logo-symbol-wordmark" style="color:#fff"/>
```

seems to be missing the security hash or keyword.

### Specifications

main

**Comment by shleeable** [comment]
![image](https://user-images.githubusercontent.com/17537000/207771225-1d320f03-4726-4502-8fe1-b63eff87c1b4.png)

**Comment by afontenot** [comment]
I believe there's a PR already lined up to fix this: https://github.com/mastodon/mastodon/pull/20814
