### ISSUE TITLE
Docker Mastodon not working

### ISSUE THREAD

**Issue by redimongo** [mastodon/mastodon#22318]
### Steps to reproduce the problem

using the docker file and trying to install this I get the following error

**ERROR: dockerfile parse error line 8: Unknown flag: link**

### Expected behaviour

should install

### Actual behaviour

ERROR: dockerfile parse error line 8: Unknown flag: link

### Detailed description

trying to start a mastodon server using docker.

### Specifications

docker

```
# Clone mastodon to ~/live directory
git clone https://github.com/tootsuite/mastodon.git live
# Change directory to ~/live
cd ~/live
```

**Comment by shleeable** [comment]
Outdated docker version.

**Comment by redimongo** [comment]
> Outdated docker version.

Where is the updated correct docker?

**Comment by unknownconstant** [comment]
If you’re building with docker on some platforms you need to make sure you have buildkit enabled even with a recent version. Try `DOCKER_BUILDKIT=1 docker build .` instead.

If you’re unfamiliar with docker this is the sort of thing that would be really helpful in the instructions.

**Comment by redimongo** [comment]
> If you’re building with docker on some platforms you need to make sure you have buildkit enabled even with a recent version. Try `DOCKER_BUILDKIT=1 docker build .` instead.
> 
> If you’re unfamiliar with docker this is the sort of thing that would be really helpful in the instructions.

Yes, I did that but I am still getting the following error
```
docker-compose run --rm web bundle exec rake mastodon:setup
Building web
ERROR: dockerfile parse error line 8: Unknown flag: link

```

**Comment by darless** [comment]
@redimongo provide your docker information. 
```
docker version
docker-compose version
```

As others have stated you likely have an outdated docker version. Line 8 in Dockerfile is a `COPY` command that provides a link attribute that the version of docker you are using does not understand. 
```
COPY --link --from=ruby /opt/ruby /opt/ruby
```

The `COPY --link` was added in Dockerfile:1.4: [Web Link](https://docs.docker.com/engine/reference/builder/#copy---link)

**Comment by myConsciousness** [comment]
I encountered the same issue while setting up a Mastodon instance on an AWS EC2.

The problem is that the latest version of docker I can get on EC2 is `20.10.12`.

**Comment by dwb** [comment]
I got the same error. Setting `DOCKER_BUILDKIT=1` didn't get me past the error, presumably because `docker-compose` didn't pass it through. So I had to set `COMPOSE_DOCKER_CLI_BUILD=1` instead, and that worked.
