### ISSUE TITLE
Integrate Nostr 

### ISSUE THREAD

**Issue by ottman** [mastodon/mastodon#22311]
### Pitch

Mastodon can increase its decentralization and sovereignty with Nostr by following the model of the Minds-Nostr integration detailed here: https://www.minds.com/newsfeed/1445110266495766533. 

NIP-26 enables delegated event signing: https://github.com/nostr-protocol/nips/blob/master/26.md

### Motivation

All users would benefit from the sovereign keypairs, portability and interoperability with nostr. It would solve numerous issues that arise from being fully reliant on ActivityPub.

**Comment by nightpool** [comment]
No, sorry, we are not interested in supporting any non-ActivityPub protocols at this time.
