### ISSUE TITLE
Hashtag Auto-Discovery 

### ISSUE THREAD

**Issue by kidehen** [mastodon/mastodon#22340]
### Pitch

The following URL denotes an HTML based Mastodon Hashtag Page [https://mastodon.social/tags/KnowledgeGraph](https://mastodon.social/tags/KnowledgeGraph) (content-type "text/html").

The following URL denotes a JSON based Mastodon Hashtag Page [https://mastodon.social/tags/KnowledgeGraph.json](https://mastodon.social/tags/KnowledgeGraph.json).

Issue:
Why doesn't the HTML page include a cross-reference to the JSON page for easier auto-discovery by user-agents? 

Solution:
The issue above would be addressed via the following, placed in the <head/> section of the HTML doc:

`<link rel="alternate" type="application/activity+json" href="https://mastodon.social/tags/KnowledgeGraph.json" /> `

The same would also apply to RSS renditions using. 

`<link rel="alternate" type="application/rss+xml" href="https://mastodon.social/tags/KnowledgeGraph.rss" /> `

### Motivation

Making it easier for user-agents to discover structured data associated with a hashtag.

**Comment by brad2014** [comment]
Noting that for profiles, this was recently reported against 4.0.2 as https://github.com/mastodon/mastodon/issues/20770 and fixed by https://github.com/mastodon/mastodon/pull/20772, but is still missing for tags.

**Comment by nightpool** [comment]
Note for anyone who wants to implement this that the correct link tag would be `<link rel="alternate" type="application/activity+json" href="https://mastodon.social/tags/KnowledgeGraph" />`, same as we currently have for profiles.

**Comment by kidehen** [comment]
To be fixed properly, you need to operate on the premise that the following are equivalent uses of metadata to aid auto-discovery of structured data by user-agents:

HTTP Response Header:
```
Link: <{some-mastodon-resource-url}>; rel="alternate"; type="application/activity+json"
```
and

HTML Metadata in `<head/>` 
```
<link rel="alternate" type="application/activity+json" href="{some-mastodon-resource-url}" /> 
```

**Comment by mjankowski** [comment]
FYI, these discovery `link` elements were added in https://github.com/mastodon/mastodon/pull/33179 and will show up in next release.

I have not done the http `Link` headers yet, let me know if thats critical or also desired.

Separately - are there other pages which should have similar auto-discovery elements?
