### ISSUE TITLE
handles in messages get maimed

### ISSUE THREAD

**Issue by mro** [mastodon/mastodon#22379]
### Steps to reproduce the problem

1. post a new note containing e.g. 'lorem ipsum @bfdi@social.bund.de sit amet'
2. see a post rendered as 'lorem ipsum @bfdi sit amet' like e.g. at https://digitalcourage.social/@mro/109525103961137797

### Expected behaviour

lorem ipsum @bfdi@social.bund.de sit amet

### Actual behaviour

lorem ipsum @bfdi sit amet

### Specifications

Mastodon v4.0.2

**Comment by jwusch** [comment]
SO the rendered hyperlink still seems to resolve for the @bfdi post in the example.  Do you want the text that represents the hyperlink to be "@bfdi@social.bund.de"  I would think the current code base is trying to consolidate text in the post to ease effort to read it.  What would be cool for cross server identification of the poster, is for it to be fully rendered when this article is shown on other servers than which the post originated...

**Comment by nemobis** [comment]
Currently the Mastodon web UI shows the full handle of mentioned users when they're ambiguous (e.g. try mentioning multiple \@admin accounts)- Showing the full handle of all users unconditionally sounds like a client-side feature request. Have you checked whether some of the existing clients or [fediverse apps](https://delightful.club/delightful-fediverse-apps/) provide such an option?
