### ISSUE TITLE
Smart banner from link persists in the mastodon web app

### ISSUE THREAD

**Issue by GuillaumeRossolini** [mastodon/mastodon#22377]
### Steps to reproduce the problem

1. Add the web app to the iPhone home screen
2. Browse a timeline, find a toot with a link to a site that uses a smart app banner at the top, for example, ft.com
3. Tap that link, don't close the smart app banner
4. Exit the linked page, you are back on the mastodon timeline

### Expected behaviour

Smart app banner should be history

### Actual behaviour

The previous site's smart app banner persists in the mastodon timeline

### Detailed description

If you go to the top of the page and you scroll up, you can see the previous site's smart app banner.

However if you tap a new link without any smart app banner in it, then close that reader, then mastodon is back to normal.

I am unsure if the addition to home screen is necessary to reproduce this, I'm just describing my setup.

### Specifications

Using the instance at infosec.exchange
Client is an up to date iOS with Safari.

[Demo of the issue (screen capture)](https://drive.google.com/file/d/1aFkN_IF70rginKDq21mw3qmIx9RrMEPC/view?usp=drivesdk)

**Comment by ineffyble** [comment]
This almost seems like a Safari bug.
