### ISSUE TITLE
Rate limit rounds up to the nearest 10 minutes?

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#22384]
### Steps to reproduce the problem

if you get ratelimited at 1:20:01, or 1:29:59.. the rate limit is timeout is the same

`Rate limitedPlease retry after 1:30:00 PM`

### Expected behaviour

10 minute from the event?

### Actual behaviour

1-10 minute from the event

### Specifications

main

**Comment by jwusch** [comment]
Could you clarify what you mean by "rate limited"  screenshots help a bunch for context

**Comment by ineffyble** [comment]
Another way to put this is that rate limiting is using fixed windows, not rolling windows.

**Comment by nightpool** [comment]
Yes, this is how the rate limits are designed

**Comment by nightpool** [comment]
1.
