### ISSUE TITLE
Minor CSS pedantry - head-shot inset border on website

### ISSUE THREAD

**Issue by richardbrockie** [mastodon/mastodon#22386]
### Steps to reproduce the problem

View anyone's profile on both the web and iOS app.

### Expected behaviour

White border all the way around the inset on the web

### Actual behaviour

Left side of inset is missing white border

### Detailed description

The inset head-shot pic on the web interface has no border on the left:

<img width="357" alt="Screenshot 2022-12-16 at 1 47 22 PM" src="https://user-images.githubusercontent.com/10185602/208222361-b13126ad-70cd-42d4-81fe-fa78a875ec88.png">

The inset on the iOS app has the border all the way round:

![iOS](https://user-images.githubusercontent.com/10185602/208222364-c1e36ec5-1867-41d1-b307-7305223e9138.png)

I think having the border all the way round is nicer - could the website CSS be changed to follow the app?

Was originally reported in hachyderm.io's issue tracked: https://github.com/hachyderm/community/issues/205

### Specifications

Mastodon v4.0.2, Firefox, MS Edge (both MacOS)

**Comment by trwnh** [comment]
Fixed by #20994

**Comment by richardbrockie** [comment]
Thanks - I did do a search, but obviously didn't find the existing issue.
