### ISSUE TITLE
Show a user's bio and follow/block buttons when you hover over their name oravatar on a post

### ISSUE THREAD

**Issue by seanthegeek** [mastodon/mastodon#22405]
### Pitch

Show a user's bio and follow/block buttons when you hover over their name and avatar on a post, like Twitter does currently.

### Motivation

This would allow users to quickly follow accounts that created interesting posts without having to click into each author's profile.

**Comment by connorshea** [comment]
Probably a duplicate of #14918

**Comment by seanthegeek** [comment]
> Probably a duplicate of https://github.com/mastodon/mastodon/issues/14918

You're right. Closing,
