### ISSUE TITLE
Provide the option to make a list public and follow and clone public lists

### ISSUE THREAD

**Issue by seanthegeek** [mastodon/mastodon#22408]
### Pitch

Provide the option to make a list public, and allow anyone to view, follow, or clone that list.

Following a list would allow a user to have a read-only linked copy of the original list, so it stays in sync with the original author's list

Cloning a list would create a separate copy of the list that the user could edit as needed.

### Motivation

On Twitter, looking at other user's list is a great way to find content and accounts to follow.

**Comment by connorshea** [comment]
Duplicate of #8208

**Comment by seanthegeek** [comment]
> Duplicate of https://github.com/mastodon/mastodon/issues/8208

Sort of. I'm also describing a way to follow lists. I just updated the title to reflect this difference.
