### ISSUE TITLE
Theme / dark-mode toggle for unauthenticated sessions

### ISSUE THREAD

**Issue by dredmorbius** [mastodon/mastodon#22420]
### Pitch

Unauthenticated viewers should be able to toggle dark/light modes, select themes, or better yet, have Mastodon comply with device / browser theme settings (dark, light, etc.)

Mastodon's default dark-mode theme is unfriendly on some devices, particularly e-ink displays.  People in other instances might prefer higher or lower contrast displays or specific colour themes.

It's possible to toggle dark/light mode when logged in to a Mastodon instance.  It is **NOT** possible to do so when viewing an instance, toot, or thread when unauthenticated.

I'm requesting that a mode toggle, and if possible, device or browser theme compliance, be offered.

### Motivation

Mastodon is difficult or impossible to read in many cases on certain displays.

Toggling or matching reader-specified themes would facilitate this.

As it stands, it is all but impossible to read Mastodon sites from certain types of devices such as e-ink tablets.

My own experience is with a recent Onyx BOOX device using the default NeoReader, Firefox (Fennex), and EinkBro browsers.

EinkBro has a "force white background" feature, but this doesn't function as desired with Mastodon instances.  (I'm raising this issue separately with the EinkBro project.)

**Comment by ineffyble** [comment]
Related to #19231
