### ISSUE TITLE
Signups not accepting any email address

### ISSUE THREAD

**Issue by cloudcogsio** [mastodon/mastodon#22442]
### Steps to reproduce the problem

Complete a user signup/registration

### Expected behaviour

Signup is successful

### Actual behaviour

Error under the email field: uses a disallowed e-mail provider

### Detailed description

Running v4.0.2 on docker, using docker-compose.

Environment variables
EMAIL_DOMAIN_ALLOWLIST and EMAIL_DOMAIN_DENYLIST are NOT set.

Registration->Who can sign-up is set to "Anyone can signup"

The instance will not accept any signups by showing "uses a disallowed e-mail provider" beneath the email field when an attempt is made to process the signup.

### Specifications

Mastodon v4.0.2

**Comment by rbairwell** [comment]
I doubt this is a code issue as I'm sure many many other instances would have reported it. If you have access to the Joinmastodon.org discord, it may be worth asking in #server-owners .

What changes have you made since deploying the Docker-compose?

**Comment by cloudcogsio** [comment]
Agreed. I'm not on the discord server, I should just create a discussion topic now that I think about it.

**Comment by cloudcogsio** [comment]
> I doubt this is a code issue as I'm sure many many other instances would have reported it. If you have access to the Joinmastodon.org discord, it may be worth asking in #server-owners .
> 
> 
> 
> What changes have you made since deploying the Docker-compose?
> 
> 

I've added some environment variables related to the server name and SMTP configs. 

No changes were made to the docker image.

**Comment by ineffyble** [comment]
Double check that DNS is working from within your container.

**Comment by cloudcogsio** [comment]
After investigating it seems the bitnami docker image is setting an empty EMAIL_DOMAIN_ALLOWLIST environment variable.
Modifying /opt/bitnami/scripts/mastodon-env.sh to remove the variable export resolved the issue.

**Comment by natehouk** [comment]
Thanks for following up @cloudcogsio, I ran into the same issue.
