### ISSUE TITLE
[Onboarding] Simplify server selection for new users

### ISSUE THREAD

**Issue by funficient** [mastodon/mastodon#22506]
### Pitch

WHEN a new user wants to get started on Mastadon, THEY WANT to find a suitable server without needing to refer to a tutorial or video guide SO THAT they can confidently and easily get started.

To achieve this goal, it is recommended to simplify the current server selection page to reduce cognitive overload and make a selection easier and slightly more transparent (see motivation).

![image](https://user-images.githubusercontent.com/44545266/208474494-8fd8498c-ddd8-405c-91b2-b8f36562bcce.png)

1. Modify the text in the hero banner section to tell people that they can access all users on all servers by signing up to one.  For example: "To use it, you need to make an account with a provider—we call them servers—that lets you connect with other people across **any and all** Mastodon **servers**. **Once you have an account on a server you will be able to connect to any other user on all supported servers.**"
2. Improve the consistency and simplicity and with that reduce overwhelm by **moving the left-hand navigation options to the top** navigation bar as in the mock-up provided above.
3. Reduce the number of results displayed on the page to only display 2 - 3 rows (8 - 12 servers) at once with a button to load more.
4. Consider adding another multi-select filter to display a list of main rule categories as this is one of the most important considerations in choosing a server.  For example, options can include privacy, no bots, no crypto etc.

**View complete suggested workflow with more detail on** (access as guest without registering): 
https://app.conceptboard.com/board/8fcu-gc90-rguk-ete6-9kyr

**See discussion for more context:**
https://github.com/mastodon/mastodon/discussions/20397

### Motivation

It's confusing and overwhelming for a new user (especially non tech-savvy) to select a server when signing up initially.  They end up dropping off before they've completed onboarding.  This also means that existing users tend to go back to the old social networks to find the people that aren't on Mastadon yet or don't want to move because of the complexity.

This is partly because the average user isn't familiar with the architecture of the fediverse and the complexities around it, but partly because the current server selection page contains more options most users can effectively process cognitively when first encoutering a web page or service.  From research it has been proven that a user can only efficiently process between 4 and 7 items in their active memory at once.  

Currently, a new user has to figure out what the difference is between the left-hand navigation and the top navigation as well as choose a server from a very long list without understanding the impact of their choice.  This adds unnecessary confusion to the decision making process and can reduced simply by re-arranging the current page to have only one hierarchy and more descriptive intro title text.

**Comment by samuk** [comment]
LGTM. I'd also suggest changing the default sort to show instances with currently open registration (with no approval) at the top. Sort them by the number of active users.

Exposing the filters in the URL would be nice too. I'd like to be able to share a link to all the LGBTQ+ instances for example.

**Comment by samuk** [comment]
See specifically: https://github.com/mastodon/joinmastodon/issues/250

**Comment by funficient** [comment]
Logged on the joinmastodon repository https://github.com/mastodon/joinmastodon/issues/270.
