### ISSUE TITLE
Inconsistent use of the word toot/post/status

### ISSUE THREAD

**Issue by seanthegeek** [mastodon/mastodon#22503]
### Steps to reproduce the problem

1. View a post with replies

### Expected behaviour

The header shouuld say "Posts and replies"

### Actual behaviour

The header says "Toots and replies"

### Detailed description

"toot" was the original word for a post in Mastodon. In most places in the web UI "toot" has been replaced with "post". However, in a few places the words "toot" or "status" are still used. Some locals are worse than others.

![image](https://user-images.githubusercontent.com/44679/208476177-38c1583c-d3e6-4cb0-82f5-e46d0c0e6fb2.png)

![image](https://user-images.githubusercontent.com/44679/208476232-849e2ce1-fbb0-44c5-8b42-38ca24f79c02.png)

### Specifications

Mastodon v4.0.2+glitch

Example: https://infosec.exchange/@georgetakei@universeodon.com/109541082140846131

**Comment by ClearlyClaire** [comment]
The particular issue you are pointing out is a glitch-soc issue. Related: #22522
