### ISSUE TITLE
Migrations fail if database manually created.

### ISSUE THREAD

**Issue by mldulaney** [mastodon/mastodon#22524]
### Steps to reproduce the problem

1. Manually create postgres user /without/ createdb and database owned by user
2. Run mastodon rake setup task
3. failure
...

### Expected behaviour

Based on the principle of least privilege, it should be possible to manually create the database and have mastodon use it, creating the tables within the db as necessary.

### Actual behaviour

When the setup task encountered the existing database, it failed, rather than using the empty database.

### Specifications

Mastodon 3.5.3

**Comment by ineffyble** [comment]
`db:setup` does `db:create, db:schema:load, db:seed`. You should be able to just run the latter two yourself.

**Comment by mldulaney** [comment]
Be nice if this was in the docs :)
