### ISSUE TITLE
"Toots and replies" cannot be localized.

### ISSUE THREAD

**Issue by naiagoesawoo** [mastodon/mastodon#22522]
### Steps to reproduce the problem

1. Attempt to change the language on Mastodon. 
2. View a thread (ex. https://howlr.me/@Synnerette/109542256687024260)
3. The text for the "Toots and replies" header is not changed.
...

### Expected behaviour

The string should be translatable in en.json

### Actual behaviour

The string is not translatable

### Specifications

Mastodon 4.0.2
Ruby 3.0.4
Node v16.18.1

**Comment by rbairwell** [comment]
Which language are you changing to?

I believe "Toots and replies" is defined as "account.posts_with_replies" in the app/javascript/mastodon/locales/*.json file (although on "main" it is now "Posts and replies").

**Comment by ClearlyClaire** [comment]
This is a glitch-soc only string. It is translatable, but not translated. Since the string is actually identical to another one that is shared with upstream, I will make a change to re-use the latter.

**Comment by ClearlyClaire** [comment]
It was a glitch-soc-specific string but I changed it to using the shared `account.posts_with_replies` so there should be no need to translate it now as it should already be done in Mastodon.
