### ISSUE TITLE
Error increasing toot size

### ISSUE THREAD

**Issue by famassar** [mastodon/mastodon#22523]
### Steps to reproduce the problem

1.  nano live/app/javascript/mastodon/features/compose/components/compose_form.js --> chenge the TWO values 500 with others (i.e. 1000)
2. nano live/app/validators/status_length_validator.rb --> change the value 500 with another (i.e. 1000)
3. nano live/app/serializers/rest/instance_serializer.rb --> insert after :languages, :registrations,  the :max_toot_chars, string. The insert above the "private" word the string: 
def max_toot_chars 
   1000
end
Restart mastodon
4. Recompile: RAILS_ENV=production bundle exec rails assets:precompile
...

### Expected behaviour

The server is running with a new toot size (1000 characters, in the example) 

### Actual behaviour

The server works, but in thehome page there is an error 500

### Detailed description

TypeError: undefined is not an object (evaluating 'i.get("rules").isEmpty')
isEmpty (webpack:///app/javascript/home/mastodon/live/app/javascript/flavours/glitch/features/about/index.js:162:48)
gi (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:3577:75)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5035:13)
Kj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5029:29)
Ej (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:4815:6)
su ([native code]::)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2331:17)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:252:11)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2328:9)
gg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2320:2)
Ga (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5936:22)
gd (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:1075:7)
Qt ([native code]::)

### Specifications

Mastodon 4.0.2 +glitch (but without glitch the error is the same...)
Ruby	3.0.4p208
PostgreSQL	15.1
Redis	6.0.16

**Comment by ineffyble** [comment]
After making changes to frontend code, you may need to re-run static asset precompile (`RAILS_ENV=production bundle exec rails assets:precompile`).

**Comment by famassar** [comment]
I'm sorry I forget to wrote this passage in the steps above.
Obviosly I recompile static asset (with no success)

**Comment by famassar** [comment]
I insert MAX_TOOT_CHARS in .env.production and it works!
Many tanks!!
