### ISSUE TITLE
ActivityPub: Signed request date outside acceptable time window

### ISSUE THREAD

**Issue by justindthomas** [mastodon/mastodon#22536]
### Steps to reproduce the problem

I'm working on writing an ActivityPub server to interact with Mastodon in Rust. I'm having trouble with the Signature verification and noticed something that I suspect might be a problem.

The Rust `reqwest` library seems to send the headers as lower case. This is what they look like:

```
RequestBuilder {
        method: POST,
        url: Url {
            scheme: "https",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: Some(
                Domain(
                    "ser.endipito.us",
                ),
            ),
            port: None,
            path: "/users/justin/inbox",
            query: None,
            fragment: None,
        },
        headers: {
            "date": "20 Dec 2022 06:34:23 UTC",
            "digest": "4a26f60ac71570114c8b6e01e8769827d7acd4ac399abfb2e2226989b3f8051a",
            "signature": "keyId=\"https://enigmatick.jdt.dev/user/justin#main-key\",headers=\"(request-target) host date digest\",signature=\"nYI5M+snwWOzkOU6qME6OVRfH9F7lfq5wtouK3i2Wq8Nw818O5hDdeDRtUetZ2PZRbOo0enMepg/B9voeBw3WLYVOIHso6FupHioyAkzMmZ5iQl3i6iVIU9W311EbkE/4pSXh6zXEmawbRPg2xp1yyFNQqx/HUugcbr+eTKOKKW148iG1Qhn6TEpJ/BHxWS+I5jPzCTOCndg/udWkPEMwj2+4CeWtIsgyf8iuh0IbgusJUhnIJlErnAhrrkrTzZBwFO50Y6VHEU+tAufewnzK4DA3RRheqbwuThzigKymg1N8JjI949Mq1zuW/sqMBHVeeWDDdBw4ZWSpfL0sRPFTg==\"",
            "content-type": "application/ld+json; profile=\"http://www.w3.org/ns/activitystreams\"",
        },
    }
```

In the Mastodon code, the `matches_time_window` function seems to only look for a header of `Date`: https://github.com/mastodon/mastodon/blob/main/app/controllers/concerns/signature_verification.rb#L207

Could this be the root of my problem? I don't know that I can change the way the `reqwest` library works, but I can dig in and see if I can adjust the case of the `Map` keys used if that's the problem.

### Expected behaviour

The date submitted is within the window and should be accepted.

### Actual behaviour

It's not.

### Detailed description

See above.

### Specifications

Mastodon v4.0.2

**Comment by ClearlyClaire** [comment]
I believe your issue is that your `Date` header is not a RFC2616 date.

Related: #21617 should give better error messages around that.

**Comment by justindthomas** [comment]
> I believe your issue is that your `Date` header is not a RFC2616 date.

That was indeed the problem. I've adjusted and am using the `httpdate` crate instead of `chrono` to generate the right format.

I also put in a PR for some corrections to the documentation.

https://github.com/mastodon/documentation/pull/1119
