### ISSUE TITLE
Send a DM when a reported post is actioned

### ISSUE THREAD

**Issue by Deauthorized** [mastodon/mastodon#22535]
### Pitch

Any user who reports a post / comment should receive a DM from the instances actor account if the report is accepted / denied / actioned in any way.

It's one of the very very few things that Twitter does correctly, so idrk why it isn't a thing on Mastodon as well.

### Motivation

Transparency, for the main part.

**Comment by Crashdoom** [comment]
Duplicate of #14474 -- Would be amazing to have so we don't need to resort to using a bot and custom webhooks :/

**Comment by Deauthorized** [comment]
> Duplicate of #14474 -- Would be amazing to have so we don't need to resort to using a bot and custom webhooks :/

Mmm...
