### ISSUE TITLE
Accessibility of the “Sign out” button on the “/share” page

### ISSUE THREAD

**Issue by kytta** [mastodon/mastodon#22547]
### Pitch

When one user decides to share something on Mastodon via the /share endpoint (for example, by clicking on a “Share” button), the page has a “Sign out” button. Pretty useful, but the meaning of it may also be confusing for some people. It would be nice to improve the button's accessibility by doing the following:

- [x] add the `title` attribute to the button, so that on hover, it would say “Sign out”
- [x] add the `aria-*` attributes (or `alt` text) to the button, so that the screen readers would correctly title the button. Right now, it's a link with a text that consists of one unreadable character

### Motivation

Foremost, people with sight disabilities would profit from this. I also have received an email from a person that didn't understand the meaning and the reasoning behind even having this button there in the first place.

**Comment by rbairwell** [comment]
Out of interest, which platform are you on? (i.e. Chrome 108 on Windows 10 Pro, Safari 532 on Mac OS 23) etc?

On my Windows 10 Pro machine running Brave 1.46, clicking the "Share" button opens the browser/Windows default share interface (via [navigator.share](https://github.com/mastodon/mastodon/blob/7bdb2433f1a6e0b6a5e4df068003ac6e2e296048/app/javascript/mastodon/features/status/components/action_bar.js#L166) ). I actually can't find the `/share` endpoint documented or mentioned anywhere - could you provide a full example URL (feel free to mask out the instance name, post id and/or the username).

Just to confirm - your instance is running normal Mastodon v4.0.2 (on the Advanced web view, that's at the bottom of the "Getting started" column - on logged out, it's left hand panel) or is it running something like Mastodon v4.0.2+glitch ?

**Comment by kytta** [comment]
> Out of interest, which platform are you on? (i.e. Chrome 108 on Windows 10 Pro, Safari 532 on Mac OS 23) etc?

macOS Monterey 12.6.2, MacBook Pro 14'', 2021, M1 Pro, 16 GB

> I actually can't find the `/share` endpoint documented or mentioned anywhere - could you provide a full example URL

Yes, this is the URL used for "SHare" buttons on external pages. For example, you read an article and want to share it with others on Mastodon. The example URL would be `https://<INSTANCE_URL>/share?text=Hello%20World`.

I develop [share buttons](https://shareon.js.org/) and [an instance-agnostic share page for Mastodon](https://toot.kytta.dev/), which utilize this page.

> Just to confirm - your instance is running normal Mastodon v4.0.2

Yep.
