### ISSUE TITLE
Larger padding area on status action buttons

### ISSUE THREAD

**Issue by shuuji3** [mastodon/mastodon#22545]
### Pitch

This is a proposal to increase action button padding on each status card without changing the actual status card size. Enlarging the action buttons helps us to click/tap and can prevent false click/tap.

Currently, I'm experimenting with this change for only a multi-column view using the Stylus browser extension. But I'm happy to make a new PR to implement actual changes as I can write JavaScript/HTML/CSS.

Here are screenshots of my experiment:
![Screenshot 2022-12-20 at 18 40 29](https://user-images.githubusercontent.com/1425259/208648862-67b496f0-2b88-4d66-952d-90ee4da01f64.png) ![Screenshot 2022-12-20 at 18 34 21](https://user-images.githubusercontent.com/1425259/208648869-b3fbad07-0ac5-436f-bbd5-a5e0640bde39.png)
(left: before / right: after, the background color and grid are shown just for visual aid here)

You can try this change by yourself by installing this userstyle (need to edit for other domains):
[mastodon.social - larger action button — UserStyles.world](https://userstyles.world/style/7789/mastodon-social-larger-action-button)

### Motivation

I sometimes experience the failure to click the action button due to a relatively small clickable area. Then, I have to click the button carefully again. That experience was a bit frustrating to me and I noticed there was still enough margin around the small button area in the current UI. So it could be improved without large UI changes such as enlarging status height much.

Also, a larger button should be beneficial from the point of view of accessibility, especially for mobile users and high-resolution desktop users, who can see relatively small buttons.

I've searched the past issue but couldn't find a similar proposal. Since I'm new to this project, sorry if I missed something similar. Thanks!

**Comment by shuuji3** [comment]
Here's a preview for the single column:
![Screenshot 2022-12-20 at 20 12 53](https://user-images.githubusercontent.com/1425259/208653805-8558b87d-9683-4cae-a8d3-f926b0d16d32.png)

Actually, the same style is working without change.

**Comment by shuuji3** [comment]
Closing this since there seems to be no interest from others.

**Comment by LeoSantich** [comment]
This issue appears to be open and still requiring work from a beginner.  I would love to help if possible.

**Comment by eliphazbouye** [comment]
@shuuji3 @trwnh  this issue is still relevant?

**Comment by shuuji3** [comment]
@eliphazbouye Hi, it looks like the latest Mastodon UI has solved this issue so I can close this issue now. Here's the clickable area of action buttons on mastodon.social (v4.4.0-nightly.2024-11-13).

![Image](https://github.com/user-attachments/assets/935dc242-6fde-49d6-981d-b095bdd0d1e8)

Only the three dots button has a bit smaller area so maybe someone can create a PR for that.
