### ISSUE TITLE
Mastodon server migration docs do not include redis

### ISSUE THREAD

**Issue by smiba** [mastodon/mastodon#22556]
### Pitch

Currently, if you're following the mastodon docs on migrating to a new server you're not migrating your redis database.
(https://docs.joinmastodon.org/admin/migrating/)

This however results in temporarily having reduced features. The two most prominent issues I'm seeing right after my migration:
1. Active users is listed as "0" (because the right scheduled job in Sidekiq likely has not run yet?)
2. Trends are reset, they will all show really low numbers as the count has started over again

The active users is a bit annoying, but doesn't necessarily reduce functionality for those already registered, but no longer having the amount of posts in a certain hashtag be accurate can be quite annoying. It also means we're skipping over trends that might have been very popular 24 hours ago, but are not seeing much action at the moment.

If I had to do another migration, I'd absolutely consider moving my redis over. Another solution would be (at least for the active user count) to have a way to re-calculate this manually instead of waiting for the next cron

### Motivation

Both users and server admins will benefit from this, right now my instance will look like a ghost town for people who pass by. No one wants to register on an instance that looks like it has "0 active users" followed by trends that list only covering 3 posts (suggesting bad federation)

Other then it scaring off new users, it also makes trends temporarily inaccurate which is inconvenient for users.

**Comment by ClearlyClaire** [comment]
Hi! This issue would be better fitted to https://github.com/mastodon/documentation!

**Comment by smiba** [comment]
Agreed! Let me post is over there :)
