### ISSUE TITLE
Mute boosts by specific users

### ISSUE THREAD

**Issue by DBailey635** [mastodon/mastodon#22551]
### Pitch

The bird site has a feature that allows you to "turn off retweets" by specific users, so that your feed isn't filled with cat pictures or memes by those individuals who love to retweet. This is something useful that I would love to see implemented on Mastodon.

### Motivation

I have a few people that I follow who love to boost toots by others, but rarely write anything themselves. I don't want to mute everything they do, because when they do write a toot of their own, it's often insightful or very useful. Having the ability to hide boosts by specific users would help reduce irrelevant clutter in my feed.

**Comment by rbairwell** [comment]
This is already an option. In the web interface, if you click on a user you are following to open their profile, you'll be shown the "Unfollow" button, then the notification bell and then the "three dot menu" - click that and select "Hide boosts from ....". On the Tusky Android app, it's open then profile, select the three dots top right and select "Hide Boosts"

**Comment by DBailey635** [comment]
OK, sorry. I realised that I was looking at an account that I had already muted, so I wasn't seeing "Hide books from [user]" in the three dot menu. I'll close this issue.
