### ISSUE TITLE
Trending hashtag admin doesn't display checkboxes on small screens

### ISSUE THREAD

**Issue by odoketa** [mastodon/mastodon#22565]
### Steps to reproduce the problem

1. Go into trending hashtags on mobile phone
2. No checkboxes are displayed

### Expected behaviour

All trending pages should allow multi select on mobile

### Actual behaviour

Hashtags page doesn't allow multi select

### Detailed description

Trending posts and trending links display as expected on my phone. Trending hashtags don't have the select all checkbox, nor checkboxes to the left of each hashtag. It makes hashtag admin virtually impossible from mobile.

### Specifications

Mastodon | 4.0.2
Ruby | 2.7.0p0
PostgreSQL | 12.12
Redis | 5.0.7

My phone is android, pixel 6a, viewing in chrome. Bug also in Firefox, in both portrait and landscape orientation.

**Comment by DidierMalenfant** [comment]
Not sure if this is related or not but for me, the checkboxes actually disappear from time to time even when using the same screen. They come back without me being able to tell what I do differently either way. Same machine, same browser...
<img width="387" alt="ff561b80c613de80" src="https://user-images.githubusercontent.com/98774335/211274745-24fe9f26-e314-4b7d-ba36-373844a6c174.png">
<img width="829" alt="Screen Shot 2023-01-07 at 16 53 44" src="https://user-images.githubusercontent.com/98774335/211274750-27d094ff-581d-4afa-aebc-f84639801732.png">

**Comment by ClearlyClaire** [comment]
They disappear because the batch actions are marked optional to save space on narrower screens.

They can still be managed individually, but this is more cumbersome.

That being said, the saved space is fairly limited, and hashtags of all things are probably the things that take the least horizontal space, so I'd advocate never removing those options.

**Comment by DidierMalenfant** [comment]
> They disappear because the batch actions are marked optional to save space on narrower screens.

That's odd. My screen size doesn't change yet they appear and disappear for no reason on my end...
