### ISSUE TITLE
In official clients/frontend, group multiple favourites/boosts on one post to avoid notification area clutter

### ISSUE THREAD

**Issue by vibeisveryo** [mastodon/mastodon#22578]
### Pitch

Instead of, as is:

Notifications
- Alex favourited your post (@vibeisveryo: Hello!)
- Bella favourited your post (@vibeisveryo: Hello!)
- Bella boosted your post (@vibeisveryo: Hello!)
- Bella favourited your post (@vibeisveryo: Goodbye!)
- Carmen favourited your post (@vibeisveryo: Hello!)
- David favourited your post (@vibeisveryo: Hello!)
- David favourited your post (@vibeisveryo: Goodbye!)
- Emmanuel favourited your post (@vibeisveryo: Hello!)

Group the same action which does not carry information other than the actor (i.e. not replies, but boosts and favourites) in the same time period (say, 24h, maybe configurable) together. I do not currently see an option for this, and have 10 notifications I have to scroll through which are mostly redundant. Post change:

Notifications
- 5 people favourited your post (@vibeisveryo: Hello!) *Note: hovering over 5 people would show their names, and the UI element would probably show their avatars*
- Bella boosted your post (@vibeisveryo: Hello!)
- 2 people favourited your post (@vibeisveryo: Goodbye!)

Alternatively for the first one, say something like Alex, Bella, and 3 others favourited your post.

### Motivation

Reduce visual clutter in notifications and make it easier to separate notifications needing or inviting further engagement (replies) from notifications not doing so (favourites)

*Note: I searched other issues and believe this is not a duplicate.*

**Comment by albjeremias** [comment]
something like thissss!!!
![image](https://user-images.githubusercontent.com/26681446/209604123-c372baf8-e6c3-4d12-baf7-f852b682bb47.png)


[design on penpot](https://design.penpot.app/#/view/9c5ceddf-c68c-8036-8001-cf95c95013ce?page-id=9c5ceddf-c68c-8036-8001-cf95c95013cf&section=interactions&index=0&share-id=35dd4c70-bf14-80a7-8001-cfa502432c90)

design using https://penpot.app

**Comment by albjeremias** [comment]
related:
https://github.com/mastodon/mastodon/issues/1483

**Comment by graue** [comment]
I think this is actually a duplicate of #1483. @vibeisveryo, want to close this and subscribe to that issue, posting your design idea in a comment there?

**Comment by vibeisveryo** [comment]
Yup for sure.
