### ISSUE TITLE
Feature Request:  If account self identifies as BOT allow admin to set default post behavior for all bots.

### ISSUE THREAD

**Issue by supernovae** [mastodon/mastodon#22573]
### Pitch

Setting your account to bot should set your default post to unlisted. 

### Motivation

This would be a huge quality of life improvement for users who self-identify as a bot and instance owners who want to preserve the viability of the local channel by allowing instance owners to set the default post behavior of accounts that identify as bots.

**Comment by supernovae** [comment]
If users can opt out of being a bot, that is all the control they need.

being able to set up server controls/boundaries for bots is important.  If users don't want to be a bot, don't identify as a bot.

**Comment by smiba** [comment]
@supernovae I see you've closed this issue, have you ever figured it out? I'd love to kick bots out of my instances local/federated page. They take up 5%+ of the posts and often are extremely low quality (people runing markov chains that post every hour etc.)
