### ISSUE TITLE
follow link, when WEB_DOMAIN and LOCAL_DOMAIN are set, is incorrectly set to WEB_DOMAIN

### ISSUE THREAD

**Issue by jsdiaz** [mastodon/mastodon#22583]
### Steps to reproduce the problem

I set up an instance where I have the following configuration:

LOCAL_DOMAIN=mydomain
WEB_DOMAIN=social.mydomain

I generated a folllow link by clicking the "Follow" button under a user's profile page.

### Expected behaviour

The follow link that is generated from the "Follow" button under a user's profile should use the LOCAL_DOMAIN URL.

### Actual behaviour

The follow link that is generated from the "Follow" button under a user's profile incorrectly uses the WEB_DOMAIN URL.

### Detailed description

In this example, the generated link should be https://mydomain/@handle but instead is generated as https://social.mydomain/@handle.

This is contrary to the expected behavior that would be expected given the documentation at https://docs.joinmastodon.org/admin/config/#local_domain.

### Specifications

Mastodon 4.0.2
Ruby 3.04
Node 16.19.0

**Comment by ineffyble** [comment]
The follow link is a URL. URLs still use WEB_DOMAIN because the expectation is they won't be accessible on LOCAL_DOMAIN. 

LOCAL_DOMAIN only changes handles/usernames.

**Comment by jsdiaz** [comment]
That is not what the documentation states (see below) and that is also counterintuitive considering that the @handle@mydomain format signals the canonical location in the fediverse of the account. If LOCAL_DOMAIN changes the handles/usernames, it should also change the autogenerated handles/usernames that are generated for the use of other mastodon users wanting to correctly follow an account in the fediverse.

From https://docs.joinmastodon.org/admin/config/#local_domain:
> To install Mastodon on mastodon.example.com in such a way it can serve @alice@example.com, set LOCAL_DOMAIN to example.com and WEB_DOMAIN to mastodon.example.com. This also requires additional configuration on the server hosting example.com to redirect or proxy requests to https://example.com/.well-known/webfinger to https://mastodon.example.com/.well-known/webfinger.

**Comment by jsdiaz** [comment]
Apologies, I forgot to say that I understand that its a URL, but it would be a redundant URL for the user of that dialog box since they would be at the URL it was generates. I see that the URL generated would not work to plug into a browser and navigate to in a browser, but I was under the impression that the generated URL was for following another user on mastodon and would be plugged into the search box on a mastodon instance. This is the reason I thought this was a bug.

**Comment by ClearlyClaire** [comment]
The behavior is the expected one, the Webfinger handle is `username@LOCAL_DOMAIN`, but the actor is served at `https://WEB_DOMAIN/users/username`. This URL needs to be directly accessible, and having to redirect or proxy it from `LOCAL_DOMAIN` would kind of defeat the purpose of having the option to have different `LOCAL_DOMAIN` and `WEB_DOMAIN`
