### ISSUE TITLE
Admin page disappears after 4.0.0 upgrade

### ISSUE THREAD

**Issue by famassar** [mastodon/mastodon#22619]
### Steps to reproduce the problem

1. upgrade mastodon from 3.5.3 to 4.0.0 like official instructions
2. login wih an administrative account and go in the "settings" page
3.
...

### Expected behaviour

Administration panel appers in the left side

### Actual behaviour

the "moderation" and "administration" menu don't appears in the left side panel.

### Detailed description

The "moderation" and "administration" menu don't appears. Also if I call the url (https://<MY-NAME>/admin/dashboard) I receive an error (You are not authorized to view this page).
I upgrade to 4.0.2 but anything change

### Specifications

Mastodon 4.0.2

**Comment by ClearlyClaire** [comment]
Did you run the post-deployment migrations?

**Comment by famassar** [comment]
I think yes, but now i re-reun the post deployement and now seems to be ok.
I'm a stupid man!
Many thanks!

**Comment by ClearlyClaire** [comment]
You're welcome!
