### ISSUE TITLE
Enable user search by hashtags

### ISSUE THREAD

**Issue by frenchdevartist** [mastodon/mastodon#22625]
### Pitch

Users can define hashtags on their profile.
It could be useful to be able to search user by these hashtag.

### Motivation

It would be interesting to let user search easier to boost user discovery and exchange between users.

**Comment by innosflew** [comment]
I recently came around the site https://fediverse.info/explore/people which allows you to discover people who have hashtags in their bio and it made me think why is this not a built in feature? It would make so much sense considering there are so many people on the fediverse who put hashtags in their bio.

**Comment by nemobis** [comment]
Another directory is https://search.noc.social/

**Comment by brendanjones** [comment]
See https://github.com/mastodon/mastodon/pull/25599. Waiting for confirmation that it also works with hashtags, but if it does then it solves this issue.

**Comment by nemobis** [comment]
Il 07/07/23 15:51, Brendan Jones ha scritto:
> See https://github.com/mastodon/mastodon/pull/25599. Waiting for confirmation that it also works with hashtags, but if it does then it solves this issue.

You can test on https://mastodon.social/ or another instance running on 
the nightly with ElasticSearch enabled.

Hashtag words are indexed and matched, but if you search them with a 
hashtag nothing is found in the profile tab.

**Comment by nemobis** [comment]
![Screenshot_20230707_173856](https://github.com/mastodon/mastodon/assets/901528/922a61eb-2851-46b4-a9d8-1051f2b5c68d)
![Screenshot_20230707_173921](https://github.com/mastodon/mastodon/assets/901528/35cbe3e2-cc71-44e3-b09c-d3cab536c0b6)

**Comment by jsgoldstein** [comment]
I apologize for being unclear in https://github.com/mastodon/mastodon/pull/25599. That was only the first step in the two step process of fixing this. https://github.com/mastodon/mastodon/pull/25638 was the second step which should solve this issue.

**Comment by renchap** [comment]
Closing, this should now be fixed
