### ISSUE TITLE
Kurmancî language item count 

### ISSUE THREAD

**Issue by umitkabuli** [mastodon/mastodon#22647]
### Pitch

In Mastodon Web app Preferences->Other->filter languages, Kurmancî language item is doubled.

### Motivation

suitability for kurmacî language users

**Comment by ClearlyClaire** [comment]
This is because one is using the two-letter code `ku` and the other `kmr`.

I am not sure what we should do. My understanding is that `ku` most often refers to Kurmanji, but can also be used for Sorani (which we use `ckb` for).

**Comment by gunchleoc** [comment]
I think we should follow the [CLDR](https://www.unicode.org/cldr/charts/43/summary/root.html) as much as possible, which lists:

- [Central Kurdish](https://www.unicode.org/cldr/charts/43/summary/ckb.html) [ckb] with variant [Sorani Kurdish](https://www.unicode.org/cldr/charts/43/summary/en.html#3c2a09499c925302). Native language name: [کوردیی ناوەندی](https://www.unicode.org/cldr/charts/43/summary/ckb.html#50b99c1c6d99711a)
- [Kurdish](https://www.unicode.org/cldr/charts/43/summary/ku.html) [ku]. Native language name: [kurdî](https://www.unicode.org/cldr/charts/43/summary/ku.html#65b3e3fbf6497a70)
- [Southern Kurdish](https://www.unicode.org/cldr/charts/43/summary/sdh.html) [sdh]. Native language name: [کوردی خوارگ](https://www.unicode.org/cldr/charts/43/summary/sdh.html#3431fe353287aac2)

The Crowdin project uses [kmr](https://crowdin.com/project/mastodon/kmr) and Latin script as its locale code, which is not listed in the CLDR yet. According to Wikipedia, that's [Northern Kurdish](https://en.wikipedia.org/wiki/Northern_Kurdish). Native language names: ورمانجی, Kurmancî
