### ISSUE TITLE
Cleanup non local Avatars and Headers, e.g. unused since n days

### ISSUE THREAD

**Issue by vsatmydynipnet** [mastodon/mastodon#22652]
### Pitch

There is a real problem for smaller instances blowing up the harddisk, unable to cleanout things. E.g. this for a 3 user instance:

success Cleared cache.
Done in 0.12s.
gem and bundle cleanup
Cleaning up installed gems...
Clean up complete
USAGE
Attachments:	1,38 GB (357 MB local)
Custom emoji:	0 Bytes (0 Bytes local)
Preview cards:	35,6 MB
Avatars:	7,87 GB (265 KB local)
Headers:	17 GB (1,41 MB local)
Backups:	0 Bytes
Imports:	0 Bytes
Settings:	183 KB

### Motivation

I run this daily:

```
#!/usr/bin/env bash

echo "Mastodon Daily Cleanup"

cd /home/mastodon/live || exit 1;

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

echo "remove remote media"
RAILS_ENV=production NUM_DAYS=2 bin/tootctl media remove --days=2

echo "remove preview cards"
RAILS_ENV=production NUM_DAYS=2 bin/tootctl preview_cards remove --days=2

echo "remove orphans media"
RAILS_ENV=production NUM_DAYS=2 bin/tootctl media remove-orphans

echo "remove unreferenced statuses"
RAILS_ENV=production NUM_DAYS=2 bin/tootctl statuses remove

echo "cleanout cache"
RAILS_ENV=production NUM_DAYS=2 bin/tootctl cache  clear

echo "remove custom emojis statuses"
RAILS_ENV=production NUM_DAYS=2 bin/tootctl emoji purge

echo "cleanup yarn cache"
yarn cache clean

echo "gem and bundle cleanup"
gem clean
bundle clean

echo "USAGE"
RAILS_ENV=production NUM_DAYS=2 bin/tootctl media usage

```

but this does no cleanout non local stuff here:

```
Attachments:	1,38 GB (357 MB local)
Avatars:	7,87 GB (265 KB local)
Headers:	17 GB (1,41 MB local)
```

It would really help small instances to keep their resources low.

Thank you very much.

**Comment by ClearlyClaire** [comment]
Fixed by #22149
