### ISSUE TITLE
Confusing example of "handle" without the initial @

### ISSUE THREAD

**Issue by kresp0** [mastodon/mastodon#22666]
### Steps to reproduce the problem

1.- Go to Account > Account Settings > "Move to a different account" or "Moving from a different account"

2.- Read the description of the "Handle": "Specify the username@domain of the account[...]"

3.- Get an error when specifying an account with the format suggested.

### Expected behaviour

It should read "Specify the @username@domain of the account[...]"

### Actual behaviour

It reads: "Specify the username@domain of the account[...]"

### Specifications

Mastodon v4.0.2

**Comment by Gargron** [comment]
Are you saying the input requires the preceding `@`? Because I don't think it does.

**Comment by kresp0** [comment]
Sorry, I assumed it required the preceding `@` . Received a screenshot of a user with an error, but later found out it was caused because of a missing subdomain.
