### ISSUE TITLE
WARN: Net::SMTPFatalError: 550 relay access denied - please authenticate

### ISSUE THREAD

**Issue by glenmo** [mastodon/mastodon#22669]
### Steps to reproduce the problem

1. fresh install of mastodon 4.0.2 on VPS (not Docker)
2. ran setup script and successfully sent test email
3. subsequently all emails fail to send with error "WARN: Net::SMTPFatalError: 550 relay access denied - please authenticate" in logs
...

### Expected behaviour

When new users signup they should've received a confirmation email

### Actual behaviour

WARN: Net::SMTPFatalError: 550 relay access denied - please authenticate

### Detailed description

No confirmation email is sent. Here's the .env.production config:

LOCAL_DOMAIN=toolboxtalk.tech
SINGLE_USER_MODE=false
SECRET_KEY_BASE=xxxxxx
OTP_SECRET=xxxxxxxx
VAPID_PRIVATE_KEY=xxxxxxxx
VAPID_PUBLIC_KEY=xxxxxxxxx
DB_HOST=/var/run/postgresql
DB_PORT=5432
DB_NAME=mastodon_production
DB_USER=mastodon
DB_PASS=xxxxxxxx
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=
S3_ENABLED=true
S3_PROTOCOL=https
S3_BUCKET=files.toolboxtalk.tech
S3_REGION=syd1
S3_HOSTNAME=syd1.digitaloceanspaces.com
S3_ENDPOINT=https://syd1.digitaloceanspaces.com
AWS_ACCESS_KEY_ID=xxxxxxxx
AWS_SECRET_ACCESS_KEY=xxxxxxxxx
S3_ALIAS_HOST=files.toolboxtalk.tech
SMTP_SERVER=mail.smtp2go.com
SMTP_PORT=2525
SMTP_LOGIN=toolboxtalk
SMTP_PASSWORD=xxxxxxxxx
SMTP_AUTH_METHOD=plain
SMTP_OPENSSL_VERIFY_MODE=none
SMTP_ENABLE_STARTTLS=never
SMTP_FROM_ADDRESS='Mastodon <notifications@toolboxtalk.tech>'

### Specifications

Mastodon 4.0.2
Ruby 3.0.4p208
PostgreSQL 15.1
Redis 5.0.7

Chrome Version 108.0.5359.124 (Official Build) (x86_64)

**Comment by Fastidious** [comment]
@glenmo can you try changing `SMTP_FROM_ADDRESS` to a valid one, and try? I don’t think a space on an email address is valid.

**Comment by glenmo** [comment]
> Fastidious

@Fastidious thanks for the suggestion. I changed it to:

SMTP_FROM_ADDRESS='thestairhead@gmail.com'

but still no joy. Restarted mastodon and still getting same SMTP auth error

**Comment by Fastidious** [comment]
It seems to me, based on the error, that it might be a problems on `smtp2go.com` settings. Are you allowing `tookboxtalk.tech` on the relay?

**Comment by glenmo** [comment]
> It seems to me, based on the error, that it might be a problems on `smtp2go.com` settings. Are you allowing `toolboxtalk.tech` on the relay?

@Fastidious I initially thought the same as I was using Digital Ocean originally so switched to SMTP2Go and re-ran the mastodon install script... and the test email was sent fine and I can see it relaybed by SMTP2GO OK.

**Comment by rbairwell** [comment]
It's very odd that the test email will go through to SMTP2GO okay and yet it fails  under live (especially if you haven't changed the authentication details in the meantime).

I would NOT use your Gmail address as the SMTP_FROM_ADDRESS - that *will* cause you delivery issues - Google has, very sensible, setup an SPF record so that only emails originating from their netblocks should be allowed to be received (they've also setup a DKIM policy so that emails from gmail address "should be cryptographically signed" and if they aren't the receiving system should quarantine/mark it as spam).

In fact - this could be the cause of some of the "Relay Access Denied" messages as per [SMTP2Go's documentation](https://support.smtp2go.com/hc/en-gb/articles/900004806963-550-Administrative-Prohibition-or-Relay-Access-Denied-) . Reset it to just "notifications@toolboxtalk.tech" (i.e. no other text or spaces) and ensure you've added the email address (or the domain) the SMTP2Go's [Verified Sender](https://support.smtp2go.com/hc/en-gb/articles/115004408567).

**Comment by glenmo** [comment]
@rbairwell thank for the tips. I've reset the SMTP_FROM_ADDRESS from address to 'notifications@toolboxtalk.tech' (single quotes around email address), I've verified sender with SMTP2Go.

Below is the Activity Report form SMTP2Go... showing just the one test email sent when first setting up mastodon.

![image](https://user-images.githubusercontent.com/2049233/209405079-75d80b4e-6a70-438d-818f-dbe70fadf3ca.png)

Yes, I've restarted mastodon (so many times)!.

And... still getting relay denied messages in sidekiq logs.

**Comment by glenmo** [comment]
@rbairwell I've managed to use SMTP2GO's smart relay function from postfix on my mastodon server OK. I noted that SMTP2GO require sasl authentication for postfix. Are there sasl settings for mastodon?

SMTP2GO's settings below:

relayhost is [mail.smtp2go.com] followed by :2525.

	# sudo vi /etc/postfix/main.cf
	smtp_sasl_auth_enable = yes
	smtp_sasl_password_maps = static:yourSMTP2GOUsername:yourSMTP2GOPassword
	smtp_sasl_security_options = noanonymous
	smtp_tls_security_level = may
	header_size_limit = 4096000
	relayhost = [mail.smtp2go.com]:2525

	relay_destination_concurrency_limit = 20

**Comment by glenmo** [comment]
I've changed to trying to use localhost as my SMTP server (postfix) which can successfully relay to SMTP2GO however, I get this error message in the sidekiq logs:

WARN: OpenSSL::SSL::SSLError: hostname "localhost" does not match the server certificate

**Comment by glenmo** [comment]
Good news. Problem eventually solved. Once I got postfix on localhost successfully delivering SSL authenticated emails to SMTP2GO then setting mastodon to use localhost as the smtp server worked. 

Thank you everyone for your help :)
