### ISSUE TITLE
Cannot run any tootctl commands, missing mini_portile2

### ISSUE THREAD

**Issue by dwhagar** [mastodon/mastodon#22678]
### Steps to reproduce the problem

1. Install on Ubuntu
2. Attempt to run a tootctl command
3. See error
...
I know this isn't the best description, but I haven't customized anything but running the install and getting things setup within the web interface.  So far I haven't been able to get any of the command line stuff to work.

### Expected behaviour

Should run specified command

### Actual behaviour

Gives an error message saying it cannot find mini_portile2

### Detailed description

So, I'm trying to set up cron tasks to automatically clean things up as the cache used up all of my VPS's disk space and I had to manually delete the cache just to get things to run.  I wanted to run the command manually to make sure it worked before I trusted cron to do it.

   mastodon@hal:/var/www/mastodon$ RAILS_ENV=production /var/www/mastodon/bin/tootctl media remove
   Could not find mini_portile2-2.8.0 in any of the sources
   Run `bundle install` to install missing gems.

I then tried to run `bundle install` but it never installed that particular gem.  So I did some Googling and saw there was a command `gem install mini_portile2` to install it.  This would not run within the mastodon user context, as it has to run as root and I don't have that user account able to run sudo.  I went to the root shell and installed the gem that way.  Still, no dice.

I then forced bundler to reinstall all the gems using `bundle --redownload` from within the mastodon user account and in the correct directory.  Still, no dice.

I'm kind of out of ideas and I really need to make sure that my instance doesn't grow to 100+ gigs again.

### Specifications

Mastodon 4.0.2
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
Node.js v16.19.0
Ubuntu 20.04 LTS

**Comment by dwhagar** [comment]
I was finally able to fix the issue by manually running `bundle add mini_portile2`

**Comment by progval** [comment]
Same issue here, on a fresh install.

Mastodon 4.2.0
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]
Node.js v18.13.0
Debian 12

**Comment by ClearlyClaire** [comment]
Sounds like running `bin/tootctl` directly picks up the wrong ruby version or the wrong environment while prefixing it `bundle exec` should work. I am not completely sure how to fix that.

**Comment by progval** [comment]
@vmstan Why? This is still an issue

**Comment by kartikmandar** [comment]
Is there any fix?

**Comment by mjankowski** [comment]
I don't think this should happen on current versions of ruby/rails/mastodon.

If anyone is running mastodon 4.3 on ruby 3.3 (or 3.2) and still sees this, please describe your full setup.
