### ISSUE TITLE
Inaccurate error message when attempting to add an account to a list while a follow request is pending

### ISSUE THREAD

**Issue by seanthegeek** [mastodon/mastodon#22689]
### Steps to reproduce the problem

Attempt to add an account to a list via the web UI or API while a follow request is pending

### Expected behaviour

An error should be returned like "Cannot add add an account to a list while a follow request is pending"

### Actual behaviour

404: Record not found

### Specifications

4.0.2

**Comment by CarwilB** [comment]
In addition, this same message is returned even when the follow is automatic, but something (I'm not sure what) hasn't yet updated.

This issue would probably solve both: #19865

**Comment by ClearlyClaire** [comment]
Fixed in #19727
