### ISSUE TITLE
Inaccurate follow button status for a pending request until the page is refreshed

### ISSUE THREAD

**Issue by seanthegeek** [mastodon/mastodon#22692]
### Steps to reproduce the problem

In the web UI, click the Follow button on an account that requires followers to be approved.

### Expected behaviour

The follow button should immediately change to "Withdraw follow request"

### Actual behaviour

The button changes to "Unfollow", and does not change to "Withdraw follow request" until the page is refreshed

### Specifications

4.0.2

**Comment by matuszewskijan** [comment]
Hi Sean,
which browser are you using? I've tried to reproduce the error now but the `Withdraw follow request` button is properly displayed immediately to me.
I've checked on:
- Edge v108.0.1462.46
- Safari 15.3 (17612.4.9.1.8)

Mastodon 4.0.2

**Comment by seanthegeek** [comment]
Strange. The instance I use (infosec.exchange) seems to have made some kind of change that fixed this issue and #22522, even though the version number didn't change.
