### ISSUE TITLE
Inaccurate error message when trying to add an account to a list that is already in that list

### ISSUE THREAD

**Issue by seanthegeek** [mastodon/mastodon#22697]
### Steps to reproduce the problem

Attempt to use the API to add an account to a list it is already in. This can also occur if the UI element doesn't update for some reason and the user tries clicking add again.

### Expected behaviour

422: Account already added

### Actual behaviour

422: Account already taken

### Specifications

4.0.2

**Comment by vmstan** [comment]
@seanthegeek is this still an issue in newer versions?

**Comment by trwnh** [comment]
```
{
    "error": "Validation failed: Account has already been taken"
}
```

yes

**Comment by mjankowski** [comment]
Did https://github.com/mastodon/mastodon/pull/32930 fix this as side effect, or still issue on main?

**Comment by trwnh** [comment]
should still be the case, it’s a string that needs to be replaced in the error description
