### ISSUE TITLE
Editing statuses should support `scheduled_at`, if the status is not yet published

### ISSUE THREAD

**Issue by nikclayton** [mastodon/mastodon#22691]
### Pitch

The feature for editing statuses does not support modifying the `scheduled_at` property (https://github.com/mastodon/mastodon/blob/main/app/controllers/api/v1/statuses_controller.rb#L77, https://github.com/mastodon/mastodon/blob/main/app/services/update_status_service.rb).

It should, for statuses that (a) already have that property, and (b) the property value is still some time in the future.

### Motivation

Without this feature the only way to edit the post time for a scheduled status is to:

1. Make a copy of the old status
2. Set the scheduled_at property of the new status to the desired time
3. Issue an API call to delete the old status
4. Issue an API call to create the new status

This can result in duplicated statuses and/or data loss.

**Comment by danielmbrasil** [comment]
Hi @nikclayton, I think that could be accomplished using the `/api/v1/scheduled_statuses` endpoint.

[Here](https://docs.joinmastodon.org/methods/scheduled_statuses/#update) are the docs on how to update a schedule status' publishing date using a single request.

**Comment by nikclayton** [comment]
Ah, thanks for that.

Would it be possible to update the docs at https://docs.joinmastodon.org/methods/statuses/#edit and change:

> Edit a given status to change its text, sensitivity, media attachments, or poll. Note that editing a poll’s options will reset the votes.

and add a sentence, something like "Editing a scheduled status' publishing date is done with [...link...]." ?

Thanks again.

**Comment by trwnh** [comment]
> Would it be possible to update the docs [...] and add a sentence, something like "Editing a scheduled status' publishing date is done with [...link...]." ?

please file this issue at https://github.com/mastodon/documentation so it doesn't disappear into the ether!

**Comment by hueldoeu** [comment]
Delete and re-draft
Löschen und neu erstellen
