### ISSUE TITLE
Enable search of (User AND hashtag)

### ISSUE THREAD

**Issue by CarwilB** [mastodon/mastodon#22694]
### Pitch

Include in the search functionality the ability to list a @Username and a #Hashtag simultaneously.

### Motivation

This kind of joint search allows you to return to a prior conversation, your own or someone else's, and to cite your own previous arguments in a new context.

I found this while trying to reference my own prior thread without having to wade through everything I've written since then.

**Comment by renchap** [comment]
This is now implemented, search is using `AND` by default, so you can use `from:@account #hashtag`
