### ISSUE TITLE
QTs from other federating software should at least show a link to the QTed post, but they don't

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#22719]
### Steps to reproduce the problem

1. Get someone on awoo.fyi to QT you.
2. You get notified even though you're not tagged, but the QTed post is not visible and there is no link to the QTed post.

### Expected behaviour

At least a link to the post being QTed.

### Actual behaviour

Fails silently.

### Detailed description

> They're just link preview cards. Mastodon just doesn't display the preview. Other platforms in the fedi do. So, on Masto, all you see is the link.
-- https://tenforward.social/@Kichae/109569035812034196

> I've just QT'd your post. It's supported fine.  :furtease:
-- https://awoo.fyi/notice/AQvwQCSzXcXCKqLVKK

From Mastodon:
<img width="597" alt="Screenshot 2022-12-24 at 14 06 21" src="https://user-images.githubusercontent.com/6607512/209439881-cc60ac58-1b44-42ba-b841-b33748a8d1ce.png">

On originating instance:
<img width="615" alt="Screenshot 2022-12-24 at 14 06 38" src="https://user-images.githubusercontent.com/6607512/209439898-811764e7-3117-42c6-9741-d4f3e9fa48cc.png">

> So you're saying that Mastodon devs saw posts like this and decided to remove that part at the end? If so that's very silly and I'll open a Github issue about it!

-- me

> IIt appears so as it used to render just fine in earlier versions. QOTO was the first instance to implement it outside of misskey and it used to render in earlier versions just fine.

-- https://qoto.org/@freemo/109569078654260562

> If your instance doesnt explicitly strip it then it would look like this at the end of the post:
>
> [ QT: link to post being quoted ]
-- https://qoto.org/@freemo/109569002172019963

### Specifications

* v4.0.2+glitch (using vanilla theme/flavour)
* Chrome Version 108.0.5359.124 (Official Build) (arm64)
* Mac OS Ventura 13.0.1 (22A400)

**Comment by freemo** [comment]
To be clear, since I'm quoted here.. I am refering to the fact that the LINK used to render and not the preview card.

In the past youd see something like this at the end: `[QT: <link to quoted toot> ]`

Now the link and the preview just silently get stripped.

**Comment by Trinsec** [comment]
I just observed this as well. I consider this as very bad as it MODIFIES the contents of the post.

**Comment by trwnh** [comment]
> So you're saying that Mastodon devs saw posts like this and decided to remove that part at the end? If so that's very silly

That would be very silly indeed; however, that's not what's happening at all...

> I consider this as very bad as it MODIFIES the contents of the post.

The content of the post isn't modified.

```
~                                                                  trwnh@desktop
$ curl -H 'Accept: application/activity+json' https://awoo.fyi/notice/AQvwQCSzXcXCKqLVKK
<html><body>You are being <a href="https://awoo.fyi/objects/291f89af-3dfe-41d3-99f3-976c829b1ec5">redirected</a>.</body></html>
~                                                                  trwnh@desktop
$ curl -H 'Accept: application/activity+json' https://awoo.fyi/objects/291f89af-3dfe-41d3-99f3-976c829b1ec5
{"@context":["https://www.w3.org/ns/activitystreams","https://awoo.fyi/schemas/litepub-0.1.jsonld",{"@language":"und"}],"actor":"https://awoo.fyi/users/Ash","attachment":[],"attributedTo":"https://awoo.fyi/users/Ash","cc":["https://awoo.fyi/users/Ash/followers"],"content":"I&#39;ve just QT&#39;d your post. It&#39;s supported fine.  :furtease:","context":"https://awoo.fyi/contexts/f8da8f49-c25b-492c-8106-3ce37ceac2d4","conversation":"https://awoo.fyi/contexts/f8da8f49-c25b-492c-8106-3ce37ceac2d4","id":"https://awoo.fyi/objects/291f89af-3dfe-41d3-99f3-976c829b1ec5","published":"2022-12-24T13:50:34.654865Z","quoteUri":"https://eldritch.cafe/users/cassolotl/statuses/109568290574062395","quoteUrl":"https://eldritch.cafe/users/cassolotl/statuses/109568290574062395","sensitive":false,"source":{"content":"I've just QT'd your post. It's supported fine.  :furtease:","mediaType":"text/plain"},"summary":"","tag":[{"href":"https://eldritch.cafe/users/cassolotl","name":"@cassolotl@eldritch.cafe","type":"Mention"},{"icon":{"type":"Image","url":"https://awoo.fyi/emoji/Fur/furtease.png"},"id":"https://awoo.fyi/emoji/Fur/furtease.png","name":":furtease:","type":"Emoji","updated":"1970-01-01T00:00:00Z"}],"to":["https://www.w3.org/ns/activitystreams#Public","https://eldritch.cafe/users/cassolotl"],"type":"Note"}
```

awoo.fyi is not inserting the link. It is instead only including it via `quoteUri` and `quoteUrl`, neither of which is supported/understood by Mastodon, nor are they even standardized properties:

```json
"content":"I&#39;ve just QT&#39;d your post. It&#39;s supported fine.  :furtease:"
```

```json
"quoteUri":"https://eldritch.cafe/users/cassolotl/statuses/109568290574062395",
"quoteUrl":"https://eldritch.cafe/users/cassolotl/statuses/109568290574062395"
```

Per NodeInfo, awoo.fyi is running Rebased (Alex Gleason's fork of Pleroma): https://awoo.fyi/nodeinfo/2.1.json

This is a bug in Rebased as it should be including the link in the post content, preferably adopting an extension like FEP-e232 Object Links to markup such links in content by using a `Link` with the ActivityPub `mediaType` within the `tag` array. That way the fallback would be to have the link still readable. Alternatively, use a standard property like `attachment`; in that case, the fallback would be to have an attachment of unknown type. But the former would be preferable to the latter.

**Comment by Cassolotl** [comment]
@trwnh 

>> So you're saying that Mastodon devs saw posts like this and decided to remove that part at the end? If so that's very silly
>
> That would be very silly indeed; however, that's not what's happening at all...

I did think it would be surprising if the Mastodon devs went to the trouble of adding complicating code to remove something unnecessarily. Thanks for explaining.

**Comment by nightpool** [comment]
This is not something the Mastodon developers can fix without adding support for misskey's specific non-standard properties. This needs to be fixed on the Misskey side.

**Comment by trwnh** [comment]
@nightpool misskey is fine, the problem is with Rebased

**Comment by Cassolotl** [comment]
Would anyone be able to point me in the right direction for reporting the bug in the appropriate place?

**Comment by trwnh** [comment]
https://gitlab.com/soapbox-pub/rebased would be the place, although I am not entirely sure how receptive they'll be given their... "edgy" community, shall we say...

**Comment by Cassolotl** [comment]
Posted on the Rebased issue list here: https://gitlab.com/soapbox-pub/rebased/-/issues/162
