### ISSUE TITLE
Search isn't prioritizing local users (especially on username match)

### ISSUE THREAD

**Issue by ShadowJonathan** [mastodon/mastodon#22717]
### Steps to reproduce the problem

We have a user @david on my instance, whom I occasionally want to search

I type in `@david` in the search bar, and expect their result to be first.

### Expected behaviour

I expect @david to be first (or at least high up)

### Actual behaviour

Dozens of other davids (in the display name, not even username) show up first, and our @david is on "show more" click-through 3

### Detailed description

When I'm searching for a user, I expect local users to be prioritised, or become more visible.

With this, I can be more connected to my own community, and not have my search results drowned by dozens of other fuzzy-matching names across the fediverse.

### Specifications

Mastodon v4.0.2

**Comment by ShadowJonathan** [comment]
What I want is for Mastodon to look for an *exact* match first, and place that on the top of the search results, because if i went to the trouble of putting the whole username in myself, i want to get to that result fast.

Then, i would want it to place local results over remote results, no matter how much "trendiness" the remote results have.

**Comment by rbairwell** [comment]
I would like something slightly different: People mentioned in any of the posts I'm replying to (if appropriate), people  I'm following first, then exact local, then exact remote, then "fuzzy" local, and finally "fuzzy remote".

**Comment by ShadowJonathan** [comment]
@rbairwell I'm mainly talking about the search bar, but I agree with the ordering, though keep in mind that users ' mentions in threads are already pre-filled most of the time, so the first bit might be moot

**Comment by renchap** [comment]
I think this should be working correctly now with 4.2.

If not, can you please provide examples (if possible on mastodon.social or mastodon.online)

**Comment by ShadowJonathan** [comment]
It appears to be resolved, yeah
