### ISSUE TITLE
Consider introducing `podman` and/or `jails`/`cages` as rootless alternatives to Docker runtime.

### ISSUE THREAD

**Issue by HeavyRain266** [mastodon/mastodon#22736]
### Pitch

For readers, I don't want it to sound like "Boo, docker is super insecure, therefore it's terrible!" etc. So please do some additional research regarding how much damage can be caused when some malware escapes rootfull containers compared to rootless ones like `podman`, `jails`and `kubernetes` where it can only access userspace and not whole system.

Both, `podman` and `jails`/`cages` are running rootless containers, compared to `docker` which requires full root access + additional cgroup. That improves security a lot, especially when some malware is able to escape container and then take control over system or in rare cases entire machine or cluster when it somehow manage to escape designated VM hosted by AWS, Azure or DigitalOcean.

Mentioned `jails` and `cages` containerization mechanisms used by FreeBSD and OpenBSD, they are similar to podman but often more secure, especially on OpenBSD. Mostly because only super tiny percent of malware developers have basic understanding of either of them. That makes both really beneficial for security of small, medium and definitely large scale instances when either of them is used as Host (VM) + Guest (container).

### Motivation

Social medias are one of biggest targets for malware attacks and security should be the prority, not only service-level hardening but also system-level which is often skipped by Open Source communities, mostly caused by lack of experience and required knowledge.

All container runtimes mentioned above are step forward for improved system-level and even machine-level security harness.

**Comment by ineffyble** [comment]
My understanding is that Docker in general is not a recommended deployment technique (and indeed it's not mentioned at all on https://docs.joinmastodon.org/).

The container images built and published for Mastodon should be usable with any OCI-compliant runtime, and indeed I suspect one of their most common uses is not using Docker (Kubernetes via the official Helm chart, since recent Kubernetes uses containerd directly).

**Comment by ineffyble** [comment]
What exactly did you have in mind for "introducing" alternative container runtimes? E.g. what changes were you after?
