### ISSUE TITLE
Option to see preferred languages in Home timeline

### ISSUE THREAD

**Issue by danialbehzadi** [mastodon/mastodon#22787]
### Pitch

There is already a preferred languages in settings, but it applies only to Public timelines. It would be great if there was an option to apply it to home timeline too.

### Motivation

I follow some people who are posting in English and their native language which I don't understand and I want to read only their English posts.

**Comment by waldyrious** [comment]
This seems to be a duplicate of #11180.

**Comment by danialbehzadi** [comment]
Close as duplicate.
