### ISSUE TITLE
Add filter context for home only (not lists)

### ISSUE THREAD

**Issue by JoFAM** [mastodon/mastodon#22796]
### Pitch

Right now the filter context has the options "Home and lists", "Notifications", "Public Timelines", "Conversations" and "Profiles". I would like an option "Home only", which filters the content on the home feed but does show it in any custom list if applicable.

### Motivation

This would especially be handy if you follow accounts that post often about (possibly sensitive) topics for which you make a separate list. Your home feed doesn't get flooded with eg the latest news on the war in Ukraine, but you can find it in the list if you choose to.

**Comment by trwnh** [comment]
Duplicate of #21388

**Comment by JoFAM** [comment]
@trwnh thanks! I've searched to see whether this issue wasn't created already, but somehow overlooked that one. I close this one then.
