### ISSUE TITLE
"Intra-" instance post links do not work in search box

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#22804]
### Steps to reproduce the problem

Consider this URL: https://mastodon.gamedev.place/@aeva/109459515884489231  
This opens a particular post by `@aeva@mastodon.gamedev.place` on mastodon.gamedev.place.

Now consider this URL: https://mastodon.social/@aeva@mastodon.gamedev.place/109459516266753232 
This opens that same post, but instead, opens it on mastodon.social, which I use.

On mastodon.social I get the first link if I click … and say "Copy Link to Post" and the second if I right-click the time and copy the URL there.

If I paste the first link into "Search or Paste URL", it brings up the desired post on mastodon.social. 

### Expected behaviour

Therefore, I expect pasting the second link in the "Search or Paste URL" box should also work.

### Actual behaviour

But if I paste the second link into the box, it does nothing.

### Detailed description

**Why would I want this, when I could just paste the URL into your address bar?**

Well, simply enough: Because I want those links to work on my phone, where I use Tusky. Last week I pasted some URLs into a scratchpad, then later tried to open them on my phone and discovered there was *no* way to open them in Tusky. Tusky doesn't have its own URL opening facility, because it uses the search box instead (which it forwards to mastodon.social, my instance). Tusky could special case this, but the server is a more natural place to do it.

Anyway, logically, if mastodon.social *created* the https://mastodon.social/@aeva@mastodon.gamedev.place/109459516266753232 link, it should be able to parse it.

### Specifications

mastodon.social, current Chrome, Tusky 20 on Android 12

**Comment by ineffyble** [comment]
Interesting. This is limited to local links of remote posts.

E.g. if I'm on social.effy.space, I can paste https://mastodon.gamedev.place/@aeva/109459515884489231 OR https://mastodon.social/@aeva@mastodon.gamedev.place/109459516266753232 into the search box and get an identical result.

But if I paste https://social.effy.space/@aeva@mastodon.gamedev.place/109459515852765557 it doesn't work. I suspect this might be to do with the safeguards against making Mastodon make unexpected local requests.

**Comment by renchap** [comment]
This seems to be fixed, I am able to access the post by searching `https://mastodon.social/@aeva@mastodon.gamedev.place/109459516266753232`, both on mastodon.social and on a third instance.

**Comment by mcclure** [comment]
Can confirm running my original test case in Tusky works now. Thanks
