### ISSUE TITLE
Warn posters that followers-only posts are not necessarily limited-access

### ISSUE THREAD

**Issue by cerebrate** [mastodon/mastodon#22834]
### Pitch

Display a warning when a user makes a followers-only post and "Require follow requests" is _not_ checked, along the lines of `"Followers are automatically approved; this should _not_ be considered private?"`.

### Motivation

While it is by no means limited to this, [Mastinator](https://mastinator.com) - which provides an effective infinite number of throwaway anonymous read-only accounts - has highlighted the issue; if anyone is allowed to follow your account without requiring confirmation, followers-only posts are _de facto_ public posts for anyone who has/can create a spare Mastodon account, even if their original account is blocked.

Since this is evidently unclear to people who don't understand the implications of ActivityPub, it's worth pointing out explicitly at posting time that followers-only provides no real restriction on readers unless automatic following is disabled.

**Comment by howaboutlollmao** [comment]
Pleroma and its forks have such warning, so it is a bit boggling Masto doesn't.
![Screenshot_20221230_141456](https://user-images.githubusercontent.com/113662836/210064560-48c01519-2786-41ee-b8da-ece5969d25a1.png)

**Comment by ineffyble** [comment]
Mastodon 4.0.2 does do this. 

<img width="279" alt="image" src="https://user-images.githubusercontent.com/834880/210141445-fefe39a2-0dbe-4216-b404-e4c385bdbba0.png">

**Comment by cerebrate** [comment]
Apparently this was a local browser issue on my end. I withdraw the request on the entirely reasonably grounds that it already exists. 😬
