### ISSUE TITLE
other instnace Media URL broken on my instance but is OK everywhere else

### ISSUE THREAD

**Issue by prasket** [mastodon/mastodon#22857]
### Steps to reproduce the problem

Trying to see media files from another Mastondon instance. 

1) Followed user https://masto.mcgeo.xyz/@me while they had an SSL issue with broken images pointing to DigitalOcean spaces and no reverse proxy for media files. 
2) Helped instance fix   SSL issue and setup NGinx Proxy 
3) Old AND new posts on our instance (mastodon.seattlematrix.org) are still showing the broken SSL URL ex: https://files.masto.mcgeo.xyz.sfo3.digitaloceanspaces.com/media_attachments/files/109/598/265/594/531/126/original/2808902b344c2e8b.jpeg from post https://masto.mcgeo.xyz/@me/109598279729656753

### Expected behaviour

Once URL was fixed on mcgeo instance our instance [SM] would see images. 

### Actual behaviour

We are still seeing broken image URL links. 

### Detailed description

I have chatted in Matrix in #mastodon_admin:matrix.org about this and seems anyone who just now looks/adds McGeo instance is seeing the correct URLs. 

My biggest concern is that this is happening ALL over the Fediverse as folks are spinning up instances and seems docs are not quite that great in making sure users are setting up reverse proxy. We even had this issue for a couple of days when our instance started up (bad SSL no reverse proxy) so are others who followed someone on our instance also seeing this? 

### Specifications

Mastodon	4.0.2
Ruby	2.7.4p191
Redis	6.0.16

**Comment by AndrewKvalheim** [comment]
To illustrate the problem:

```console
$ http get 'https://masto.mcgeo.xyz/users/me' Accept:'application/json' | jq --raw-output '.icon.url'
https://files.masto.mcgeo.xyz/files.masto.mcgeo.xyz/accounts/avatars/109/422/279/865/312/996/original/b68928c78142ee4e.png
$ rails runner "puts Account.find_remote('me', 'masto.mcgeo.xyz').avatar_remote_url"
https://files.masto.mcgeo.xyz.sfo3.digitaloceanspaces.com/accounts/avatars/109/422/279/865/312/996/original/b68928c78142ee4e.png
```

**Comment by AndrewKvalheim** [comment]
Sounds like #16414 may offer a remedy.

**Comment by prasket** [comment]
Oh nice find @AndrewKvalheim thank you for digging more into this. I just asked the approver if they know when this will be merged in. I will go ahead and close this issue with this finding in hopes it is merged in. I might pull the change over to our instance and give it a try as well.
