### ISSUE TITLE
"Edit post" should warn before overwriting text in the post creation box

### ISSUE THREAD

**Issue by jonpincus** [mastodon/mastodon#22851]
### Steps to reproduce the problem

1. Spend a while constructing a good post
2. Before hitting Publish!, Click on "Edit" for another post
...

### Expected behaviour

Get a confirm dialog, warning me I'm about to overwrite my post

### Actual behaviour

My post-in-progress is replaced by the text of the post I'm editing

### Detailed description

It should work the same way it does if I hit reply in this situation

### Specifications

Mastodon 4.0.2 on indieweb.com

107.0.1 (64-bit) on a Mac

**Comment by cincodenada** [comment]
Just hit this, very frustrating, thanks for reporting. This seems fairly simple to fix, commenting here so I might remember to take a look when I have time.

**Comment by PauloVilarinho** [comment]
Hi I had some problems finding where to test this, @cincodenada would you be able to help me with this?
