### ISSUE TITLE
Show as much of a long post as a short post in a timeline rather than just the first line

### ISSUE THREAD

**Issue by seanthegeek** [mastodon/mastodon#22861]
### Pitch

Currently, posts over a certain length are collapsed so that only the first line is (barely) visible before clicking on it, while the content  of posts shorter than this are shown in full.

The content of long posts should be shown up to the point where they would collapsed. with "read more" at the bottom. 

### Motivation

This would improve the UX Currently it is easy to overlook long posts because only one line is shown. In order to get a sense of what the post is about, the reader must stop and view that specific post. This would solve those problems without taking up any more timeline space than shorter posts.

**Comment by seanthegeek** [comment]
Here's a screenshot of my own profile at https://infosec.exchange/@seanthegeek to illustrate the problem.

![Screenshot of a Mastodon timeline](https://user-images.githubusercontent.com/44679/210108408-3cd67821-09ea-41b3-b188-c54012242054.png)

**Comment by embeddedtofu** [comment]
That isn't vanilla Mastodon but a fork used by your instance, hence the v4.0.2+glitch version

https://wiki.infosec.exchange/faq/mastodon/glitch_soc

**Comment by seanthegeek** [comment]
Ah. I didn't notice that was a glitch-specific. feature.
