### ISSUE TITLE
remove space when searching

### ISSUE THREAD

**Issue by soloturn** [mastodon/mastodon#22873]
### Pitch

on any server it is not so easy to find other users. e.x. searching "brian krebs" finds nothing, and "briankrebs" finds something. would be cool if that could be improved a little, maybe remove the space automatically? 

### Motivation

it makes it easier to find users.

**Comment by renchap** [comment]
The issue in your example is that Brian Krebs does not include "Brian Krebs" anywhere in his account or bio, only "BrianKrebs" (username).

We can not really solve this, if they want to be searchable by their name, they need to include it somewhere.
