### ISSUE TITLE
Timeline View option with Original Posts Only, no Boosts

### ISSUE THREAD

**Issue by RockstarRaccoon** [mastodon/mastodon#22885]
### Pitch

When looking at someone's timeline, I would like the ability to select a view which is ONLY their original posts, without the boosts.  This would be called something like "Posts Only" or "Just Me" or "Originals", a name can be thought up, but essentially, it would show me their original posts only, without any boosts or anything that isn't just them.  The button could be situated in the top bar, on either the left or right side of the "Posts and Replies" button, as shown...
![image](https://user-images.githubusercontent.com/9086811/210155459-1cea8739-b5d0-4ef4-912c-a1ad3d123f9a.png)
![image](https://user-images.githubusercontent.com/9086811/210155529-09fef6f9-993d-4698-91e5-2e640a127aa7.png)

This could also be called "Posts", with the current "posts" view changed to something like "Feed" or "Timeline" or "All", as shown...
![image](https://user-images.githubusercontent.com/9086811/210155519-806cd6c3-88a8-47f1-af53-ab97b796b3c0.png)

This could also be done by adding a separate filter of sorts, beneath these options, to generate the timeline-view without boosts, perhaps from a dropdown of "advanced options", which might also be a useful spot for things like an option to filter images, certain keywords, CW content, etc.

### Motivation

_Copied from the post on my techhub profile..._
I don't like how, when I try to look at someone's profile, I sometimes see a wall of boosts, the last couple of which are from me, and have to dig to see What this person is actually saying about things and if I might want to follow them for that.

Boosts tell me what you like enough to repeat, not your original thoughts.  If you don't have original thoughts, you better be curating some epic boosts.

This would also help with that thing where you sometimes want to just see what your friends have been up to, but you can't because they hit the boost button so many times that other content is flowing to the top.

It would also help with the problem where people who post content for mass-viewing sometimes hesitate to boost because they don't want to hide their own original content from their audience.

**Comment by AsiaHand** [comment]
We can already alter the settings to hide future boosts from an individual user (using the ... on their profile), but I rarely want to do that, and it never helps when the issue arises! I would instead like a toggle to hide boosts from past posts and show original content on a person's profile. I would also like to be able to provide a URL of my own contributions based on original content only.

**Comment by yukimx2501** [comment]
Voting for this feature because it also allows us to filter follow requests. When I get a follow request, I'd like to know that the follower is a real person and not a bot or, to borrow reddit's terminology, "karma-farmer".

If an account's activity only consists of boosts, it's probable that they're a bot or a troll, but it's hard to distinguish without a "view posts without boosts" option. I need to scroll for serveral pages to make sure, and that makes it a time-consuming process.

Adding that option would allow me to see a user's "self-posts" before approving the follow request.

**Comment by arjunrbery** [comment]
Voting for this feature as well for the same reasons as yukimx2501. Thanks for your consideration.

**Comment by furechan** [comment]
Same here!

I would like to have an option see posts without boosts. Actually I would even prefer this to be the default view!

In fact "Posts and Replies" would also be better without  boosts in my opinion.

I find that views with boosts are generally way too noisy and would be better relegated to an alternate view.

Maybe this could just be an option in settings like (include boosts in profile timelines), or boosts could be relegated to a separate tab like "User Feed (incl Boosts)"

Thanks!

**Comment by jimrhiz** [comment]
I too would like to support this request.

In addition to usefulness for vetting follow requests as yukimx2501 describes above, and to amplify a point made by the OP, it would be helpful to see only original posts when viewing the profile of a user you notice whom you might wish to follow spontaneously, without distraction by the possibly much greater number of posts they have boosted from other people. This would give a better chance of assessing the value of making a follow, particularly in cases where you may end up following but hiding boosts.

Further, when you have already followed a user, to be friendly or reciprocal you may wish to boost one of their own original posts. Seeing those without what they have boosted would make a choice much easier.

**Comment by msliczniak** [comment]
something like:

https://example.com/@foo@bar.baz/posts

to go along with:

https://example.com/@foo@bar.baz
https://example.com/@foo@bar.baz/with_replies
https://example.com/@foo@bar.baz/media

**Comment by BotaFlo** [comment]
I would like to be able to share my profile URL with only my own post, something like :

https://fediserver.org/@profile/owns_only

so people who want to know about me could get what I really post without getting all the things I want to boost.

It's a way to show a more personnal relation. While boost sometimes look unpersonnal.

**Comment by alisynthesis** [comment]
I came to this issue while searching for a way to do exactly this. So yes, an upvote from me as well!

**Comment by FediVideos** [comment]
Had several new people asking if this is possible. Would be nice to tell them it is :)

**Comment by IkutiDev** [comment]
With no algorithm, boosts are ultra important, yet I would love to be able to just see creators post when going into their page. Or even if possible, pin specific user/add specific user to list, to have a curated place be it in simple or advanced mastodon UI to just see their content. This would allow me to go into main feed and just browse, but also have an easy way to catch up to specific users content from that day.

**Comment by herzenschein** [comment]
@RockstarRaccoon I think the third image would be the best option if it were to be implemented.

It feels more accurate to describe the general contents of the timeline as "Feed" than keep the rather too specific "Posts". The name "Posts", aside from the general meaning, could also imply "Posts Only" by itself (like what you did there), and it keeps the string short.

**Comment by Casuallynoted** [comment]
This is probably my most wanted addition for Masto. I’ve even had times when I tried to go back in my own profile and find a post I’d made a few days ago but gave up due to the sheer amount of boosts.

**Comment by brendanjones** [comment]
This is fixed in v4.2.0. Go to a person's "posts and replies" tab, it's now only their posts. e.g. https://fosstodon.org/@Brendanjones/with_replies

**Comment by RockstarRaccoon** [comment]
> This is fixed in v4.2.0. Go to a person's "posts and replies" tab, it's now only their posts. e.g. https://fosstodon.org/@Brendanjones/with_replies

Didn't notice this until just now, but I actually disagree.

I'm asking for the ability to see all their original-content posts, so I don't have to look at any boosts or replies which require context or any other things which weren't originated by them.  This is both for moderation checks, and for deciding if I should follow someone back or just follow whoever they're boosting.  The new way the "With-Replies" timeline works is a good step, but that's a separate feature from what's been implemented.

The website [justmytoots.com](justmytoots.com) implements this, but the user has to agree to it by putting it in their profile.  I'm asking for the functionality of that website to be an option when viewing a timeline, just like how viewing only media is an option.

**Comment by elduvelle** [comment]
Why is this closed? The original request was about the possibility to see only posts in a user's profile. The reason given for closing is that there is now an option to see posts *and* replies, which is not the same. I suggest reopening the issue and focusing on an option to see only the posts *without* the replies.

**Comment by firubat** [comment]
@Gargron This should not be marked as completed, as was mentioned, there should be an option to see only original posts without boosts or replies. Please reopen this issue.

**Comment by trwnh** [comment]
> there should be an option to see only original posts without boosts or replies

the next closest issue is #10011

**Comment by ergonomic-paragraph** [comment]
+1 vote to reopen this.

Going to the "Posts and Replies" tab only moves core of this issue from boosts to replies. Instead of the user's original content being scattered between tons of boosts, it's now scattered between tons of replies with no context.
