### ISSUE TITLE
Ban the word "toot" from all UI

### ISSUE THREAD

**Issue by dp1234567890** [mastodon/mastodon#22892]
### Pitch

Virtual all of the current 2.5 million users at Mastodon came from Twitter and have no more than 2 months of history. Nobody wants to call their lovingly crafted words a "toot". Call it a Post. Use the word Publish. Conduct a poll. Anything would be an improvement. It's time for Mastodon to grow up and drop the juvenile "toot".

### Motivation

This isn't 4th grade.

**Comment by Gargron** [comment]
Show me where you see “toot”
