### ISSUE TITLE
Server thumbnail does not get updated on https://joinmastodon.org/servers

### ISSUE THREAD

**Issue by tin-cat** [mastodon/mastodon#22904]
### Steps to reproduce the problem

1. Change the server thumbnail in your Mastodon instance via the "Administration" > "Server settings" > "Server thumbnail" > "Choose file" option:

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/4244804/210205807-601a7696-face-4cef-8ea9-7ae97b798c72.png">

2. Click "Save changes".
3. The server thumbnail does not get updated in https://joinmastodon.org/servers, and instead shows a flat grey background:

<img width="338" alt="image" src="https://user-images.githubusercontent.com/4244804/210205935-2f7e2649-fa92-477c-aedb-2dce4efd3665.png">

### Expected behaviour

The server thumbnail should change to the newly uploaded one on joinmastodon.org/server some time after it was uploaded on the Mastodon instance.

### Actual behaviour

The server thumbnail changes instead to a flat grey background.

### Detailed description

- This has been observed since the last week approximately.
- Does not appear to be a delay-related issue, since the server thumbnail is still being shown as a grey flat background on joinmastodon.org/server after several days.
- Images tested precisely comply with the 2:1 aspect ratio suggestion.

Different JPG images have been tested with the same results:

- Smaller and bigger resolutions.
- Really high and medium JPEG quality settings.
- Interlaced / Non-interlaced JPEG settings.

Since this is not an issue related to the Mastodon source code hosted on this repository, please accept my apologies if this issue has been wrongly posted here, and close or remove it.

### Specifications

Mastodon 4.0.2
Ruby 3.0.4p208
Mastodon instance URL: https://litmind.club
Mastodon instance server is running Debian 11

**Comment by renchap** [comment]
We had an issue with the server handling server thumbnails, and it should have been fixed now.

Your server is closed to registrations, so it no longer appears in the joinmastodon.org server list and I cant check if this has indeed been solved for your server.

Can you ping me here if you re-enable notifications and the thumbnail is still not showing?

**Comment by tin-cat** [comment]
Thank you for solving that so fast! I could see our thumbnails were being uploaded correctly, so I can confirm this has been solved.

We set our server to not accept new signups because of a completely unrelated issue (https://litmind.club/@litmind/109630446095097252)

Thanks team!
