### ISSUE TITLE
HTTP 500 Error Edit Profile Picture

### ISSUE THREAD

**Issue by socialistmia** [mastodon/mastodon#22917]
### Steps to reproduce the problem

1. Using app try and edit profile picture
2. Error is triggered
3.
...

### Expected behaviour

be able to upload profile photo

### Actual behaviour

error code triggered

### Specifications

chrome browser and mobile app

**Comment by beachburghbrian** [comment]
I'm having the same issue.  I'm using DigitalOcean droplet, DigitalOcean database cluster and DigitalOcean space.

**Comment by beachburghbrian** [comment]
Here is are my associated error messages from syslog:

Jan  3 16:27:57 CoolerSM-01-mastodon402onubuntu2004-s-1vcpu-2gb-amd-nyc1-01 bundle[26948]: [af2e1c5b-20a3-4331-aacb-d4db50b1556c] method=PUT path=/settings/profile format=html controller=Settings::ProfilesController action=update status=500 error='Aws::S3::Errors::SignatureDoesNotMatch: Aws::S3::Errors::SignatureDoesNotMatch' duration=1248.88 view=0.00 db=19.57
Jan  3 16:27:57 CoolerSM-01-mastodon402onubuntu2004-s-1vcpu-2gb-amd-nyc1-01 bundle[26948]: [af2e1c5b-20a3-4331-aacb-d4db50b1556c]
Jan  3 16:27:57 CoolerSM-01-mastodon402onubuntu2004-s-1vcpu-2gb-amd-nyc1-01 bundle[26948]: [af2e1c5b-20a3-4331-aacb-d4db50b1556c] Aws::S3::Errors::SignatureDoesNotMatch (Aws::S3::Errors::SignatureDoesNotMatch):

**Comment by thehokemon** [comment]
Same issue as [beachburghbrian](https://github.com/beachburghbrian) using a Digital Ocean Droplet. I read somewhere that ImageMagick was required and it's installed in my instance but it doesn't fix it. Is this a permission issue?

**Comment by beachburghbrian** [comment]
I ended up switching to aws instead of digitalocean.  The mastodon pattern on Amazon marketplace from ordinary experts  worked well and Amazon has hosting, email and storage, which avoids a lot of inter-vendor configuration nonsense.
