### ISSUE TITLE
I'm getting PG::TRDeadlockDetected when tootctl statuses remove

### ISSUE THREAD

**Issue by asterismo** [mastodon/mastodon#22915]
### Steps to reproduce the problem

When performing this

RAILS_ENV=production bin/tootctl statuses remove  --days 60

I get a log with this

/media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `exec_params': ERROR:  se ha detectado un deadlock (PG::TRDeadlockDetected)
DETAIL:  El proceso 6711 espera ShareLock en transacción 451671694; bloqueado por proceso 5648.
El proceso 5648 espera ShareLock en transacción 451671684; bloqueado por proceso 6711.
HINT:  Vea el registro del servidor para obtener detalles de las consultas.
CONTEXT:  mientras se borraba la tupla (722650,8) en la relación «statuses»
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `block (2 levels) in exec_no_cache'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `block in exec_no_cache'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/postgresql_adapter.rb:670:in `exec_no_cache'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/postgresql_adapter.rb:649:in `execute_and_clear'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/postgresql/database_statements.rb:72:in `exec_delete'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:185:in `delete'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `delete'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation.rb:594:in `delete_all'
        from /media/mastodon/live/lib/mastodon/statuses_cli.rb:106:in `block in remove_statuses'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:245:in `block in in_batches'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:229:in `loop'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/relation/batches.rb:229:in `in_batches'
        from /media/mastodon/live/lib/mastodon/statuses_cli.rb:103:in `remove_statuses'
        from /media/mastodon/live/lib/mastodon/statuses_cli.rb:41:in `remove'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /media/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from bin/tootctl:8:in `<main>'

### Expected behaviour

it should clear the statuses

### Actual behaviour

the task fails to complete

### Specifications

mastodon 4.0.2
postgresql 9.6
nodejs v14.21.1
ruby 3.0.4

**Comment by vmstan** [comment]
Hi @asterismo is this still an issue for you in newer versions or in your specific setup?
