### ISSUE TITLE
Ability to hide followers and follows from admins

### ISSUE THREAD

**Issue by SoniEx2** [mastodon/mastodon#22936]
### Pitch

It should be possible to completely hide followers and follows, not just from other users but also from admins entirely.

### Motivation

Admins just shouldn't have that level of control over users.

**Comment by rbairwell** [comment]
Admins, in theory, can access the database and read absolutely anything. I say "in theory" as Admins are unlikely to do this unless they have a real need to (such as legal requests) - the same as Facebook, Twitter and even your email provider - the system administrators there can access absolutely everything if they so wanted to. Believe me, admins are lazy (I'm one myself) and I won't go peaking at the database or peoples follows unless I had a need to: life is too short.

**Comment by SoniEx2** [comment]
Think about it, the software could be built such that admins cannot see the social graph even if they wanted to. Yes, it would require some changes to the protocol, but just imagine it. If it's hidden from the admins, if it's hidden from the instance itself, then instances can no longer control users' established social graphs. Obviously instances could still get in the way of setting up new connections and whatnot, which is important, but beyond that they'd have no control.

This is how we can build networks of consent.

**Comment by RianQuenlin** [comment]
Administrators pay the bills, your move.

**Comment by SoniEx2** [comment]
It's not a bad thing to want privacy... Instances should merely provide discovery and hosting, not control.
