### ISSUE TITLE
Location metadata sometimes left intact when uploading MP4 file downloaded from photos.google.com

### ISSUE THREAD

**Issue by taupehat** [mastodon/mastodon#22948]
### Steps to reproduce the problem

1. Record a video with phone
2. Once it has synced to Google Photos, download the video from there (it will be an MP4)
3. Upload to Mastodon
4. Download the video from the Mastodon instance
5. Run `mediainfo foo.mp4 | grep xyz`

### Expected behaviour

mediainfo command should not return data, or return a sentinel value such as +00.0000+00.0000/

### Actual behaviour

mediainfo command returns actual location metadata

### Specifications

Mastodon 4.0.2
Ruby 3.0.4p208
ffmpeg 4.4.2-0ubuntu0.22.04.1

**Comment by vmstan** [comment]
Is this still an issue for you in newer versions of Mastodon?

**Comment by vmstan** [comment]
Closed as stale.
