### ISSUE TITLE
Importing instance-wide domain block .csv fails without reason if "limit" is used not "silence"

### ISSUE THREAD

**Issue by meldra** [mastodon/mastodon#22958]
### Steps to reproduce the problem

1. Decide to block/limit a bunch of instances at once.
2. Cry at the prospect of doing all these one at a time and instead compile (seemingly) valid .csv to import
3. Not realize that "limit" is called "silence" in the backend because you've never seen that used, so you specify limited instances with "limit"
4. Try import this home-baked .csv into the federation table
...

### Expected behaviour

At minimum, there should be an error given in the UI about what is wrong with the .csv

### Actual behaviour

errorphant page

### Detailed description

More than 2 of us, across 2 instances, spent all of last night trying to figure what the .csv import was upset about, without access to wherever the server logs this to.

### Specifications

Mastodon	4.0.2+glitch
Ruby	3.0.4p208
PostgreSQL	14.6
Redis	6.0.16

**Comment by ClearlyClaire** [comment]
Oh, I had expected something like this to fail as a validation error, not fail as spectacularly.

That can easily be fixed, but the current behavior is to ignore lines that have validation errors, so if that were the case, it would have showed as if you tried to import 0 domains… that doesn't sound too helpful either, I'm trying to think about how to improve that.

**Comment by ClearlyClaire** [comment]
Would something like this work?

![image](https://user-images.githubusercontent.com/384364/211058510-a43f1581-39c0-4e8f-828e-481c5ab8e042.png)

**Comment by meldra** [comment]
that's great! honestly anything other than the errorphant is an improvement

**Comment by ClearlyClaire** [comment]
ok, #21470 should address it then!
