### ISSUE TITLE
--skip-sign-in-token doesn't work

### ISSUE THREAD

**Issue by willschulz** [mastodon/mastodon#22957]
### Steps to reproduce the problem

1. Create some account (named, for example, "turtle")
2. Run `tootctl accounts modify "turtle" --skip-sign-in-token`

### Expected behaviour

Message: OK

### Actual behaviour

Error message: "tootctl accounts modify" was called with arguments ["turtle", "--skip-sign-in-token"]

### Detailed description

I am trying to use the --skip-sign-in-token flag to disable emailed security codes, as per the tootctl documentation (https://docs.joinmastodon.org/admin/tootctl/#accounts-modify)

The same issue occurs when using this flag during account creation using `tootctl accounts create`

### Specifications

mastodon version 4.0.2
ruby 3.0.4p208

**Comment by Gargron** [comment]
Email security codes no longer exist in 4.0

**Comment by masukomi** [comment]
I just encountered this too. The docs describe this functionality as being viable. There is no indication in the version history (including the 4.0.0 note) that this has been removed. 

the docs need to be updated.

https://docs.joinmastodon.org/admin/tootctl/
