### ISSUE TITLE
CSV export of followers

### ISSUE THREAD

**Issue by VyrCossont** [mastodon/mastodon#22966]
### Pitch

Add CSV export of followers to the same settings page that allows export of following, mutes, blocks, bookmarks, etc.

This is not intended for re-import or account migrations, and requires very little additional code, since it's almost symmetric with exporting the accounts the user is following.

### Motivation

One of my users asked for this so she could do some offline analysis of her own followers list, and I was surprised it wasn't already there. Anyone looking to do similar analysis, or to back up the exact state of their account, might want this. It doesn't seem to be in the takeout archive already.

**Comment by yevgenypats** [comment]
Hey team 👋 ! Im Yevgeny, maintainer and founder @ [CloudQuery](https://github.com/cloudquery/cloudquery), an open source high performance ELT framework.

We would love to help with an initial version of CloudQuery [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), if you can help us maintain it. It should solve this issue and enable your users to sync Mastodon data to any database/datalake of the growing number of [CQ destinations](https://www.cloudquery.io/docs/plugins/destinations/overview).

See similar thing we did with [Plausible API](https://www.cloudquery.io/docs/plugins/sources/plausible/overview), [Plausible Docs](https://plausible.io/docs/integration-guides#bigquery) and [discussion](https://github.com/plausible/analytics/discussions/1777)

**Comment by VyrCossont** [comment]
Closing this. The related PR handles my own use case, but won't work efficiently for very large numbers of followers.

**Comment by rdela** [comment]
For others disappointed this did not make it in: https://fabulous.systems/posts/2023/06/fetch-own-followers-from-mastodon-api/
