### ISSUE TITLE
Archive exports should be allowed every 7 days, not every 10,080 minutes

### ISSUE THREAD

**Issue by placoderm** [mastodon/mastodon#22970]
### Steps to reproduce the problem

Try to create an archive every Saturday. At various times on Saturday.

### Expected behaviour

I should have been able to create an archive on Saturday since it was 7 days since my last archive.

### Actual behaviour

I couldn't and had to wait 10,080 minutes since my last archive.

### Detailed description

OK, I know this is a low stakes problem. But I have a habit worked out where I do a bunch of my backups (on several platforms) every Saturday morning. With the current restriction, I will only be able to do my backups 10,080 minutes after the previous week's backup. This is impractical since I don't do my backups at precisely the same time every week.

I only mention this because I'm guessing it isn't an insurmountable problem to solve.

### Specifications

Not a front end issue.

**Comment by suddjian** [comment]
alternatively could make the

**Comment by ineffyble** [comment]
So, what you're asking for is that exports should be allowed every 7301 minutes to 8741 minutes, depending on the time of day they're done at?

**Comment by placoderm** [comment]
I don't know the best way to solve it, just that it should be allowed every seven calendar days. There is not logical reason to require it be done precisely 10,080 minutes after the last request.

**Comment by placoderm** [comment]
> One issue with this is timezones, you'd need to track the local day it was for the user and compare against that.

Sorry, I missed that part of your comment.

I don't think it has to be that precise. I'm assuming that the rule is in place to reduce abuse, not because there is anything magical about 7 days. Personally, if my system got messed up because I moved time zones, then that would be on me. Just doesn't seem common enough to worry about.

One of the dangers of a decentralized system is that there is a greater chance of data loss. That pushes the responsibility over to the individual user, ultimately. Which I think is just fine. And it's good to tell users to take responsibility for their own content. And I also understand the need to put limits on how often a user can create an archive. I just think that the current parameters are oddly strict and unnecessarily inject friction in behaviour that should otherwise be encouraged.

**Comment by trwnh** [comment]
you could probably set the cooldown to midnight utc of whatever 7 days after would be. worst you could abuse that is oh no you made a backup every 6 days

**Comment by placoderm** [comment]
> oh no you made a backup every 6 days

Or it could just be set to every 8640 minutes (aka 6 days). I can't imagine that would trigger a flood of abuse. :-)

**Comment by jimrhiz** [comment]
A further complication with time zones is that the time the last archive was created may be displayed in UTC(?) on the Data Export page, instead of local time. At present I am not permitted to create a new archive, but the time shown for the last one, if interpreted as local time, is already more than 7 days ago. This is confusing, and leaves me uncertain as to how much longer I have to wait.

**Comment by jimrhiz** [comment]
To add further support to this suggestion, I want to download an archive every Sunday (it's useful for searching my own posts, because my instance doesn't have Elastic Search).

As things are now, I have to remember to do it at exactly the right time, or else the deadline slips back each week, and eventually might end up on Mondays which would be inconvenient. The proposed change would fix that.

**Comment by ipkpjersi** [comment]
I'm still new to ActivityPub and Mastodon so maybe this is a dumb question - but maybe someone will read my dumb question and benefit from it.

Is there a technical limitation as to why it's limited to every 7 days for exporting your posts, and not say like, every 3 days, or every day?

With decentralized platforms, I would think you would want to take full control of your data and I would think being able to export your posts at any time would be part of that, so I certainly hope it's not that the 7 day limit was an arbitrarily chosen value.

**Comment by trwnh** [comment]
> I certainly hope it's not that the 7 day limit was an arbitrarily chosen value.

It was, sadly.

> Is there a technical limitation as to why it's limited to every 7 days

It's an expensive process, hence the cooldown. There needs to be *some* cooldown, but there isn't any objective way to decide how long it should be, so "a week" was chosen, without considering that "exactly one week" is too precise.

**Comment by suddjian** [comment]
I opened a PR that changes it to 6 days, which should address the problem without needing to resort to complicated time zone shenanigans.
