### ISSUE TITLE
tootctl media remove-orphans fails with "The specified key does not exist" (S3 storage)

### ISSUE THREAD

**Issue by smiba** [mastodon/mastodon#22981]
### Steps to reproduce the problem

1. Run `RAILS_ENV=production bin/tootctl media remove-orphans`
2. Receive error "Error fetching list of files: The specified key does not exist."

### Expected behaviour

It should've started processing going through files in the S3 bucket

### Actual behaviour

Shows an error that the specified key does not exist

### Detailed description

When running the tootctl media remove-orphans command, a error is shown instead. 

There are no other issues with mastodon in regards to accessing it's files and uploading new posts. 
My configuration (S3 related entries) are:

```
S3_ENABLED=true
S3_BUCKET=files.woof.tech
S3_REGION=nl-ams
S3_HOSTNAME=s3.nl-ams.scw.cloud
S3_ENDPOINT=https://files-woof-tech.s3.nl-ams.scw.cloud
S3_PROTOCOL=https
S3_ALIAS_HOST=cdn.woof.tech
AWS_ACCESS_KEY_ID=<redacted>
AWS_SECRET_ACCESS_KEY=<redacted>
```

### Specifications

Mastodon 4.0.2
Ruby 3.0.4p208

Scaleway S3 as storage endpoint

**Comment by alwynispat** [comment]
I get the same issue, I’m using minio. I can’t believe no one else is having this issue. Is it the level of access is insufficient?

**Comment by smiba** [comment]
I've been digging into this issue and I think the problem is on my side.

I've misconfigured my S3 endpoint, and this script is never going to work unless I fix this and fix the directory structure in S3.

By changing the following values the script ends up working, but considers all files as "Unrecognized file found":

Old:
```
S3_BUCKET=files.woof.tech
S3_ENDPOINT=https://files-woof-tech.s3.nl-ams.scw.cloud
```

New:
```
S3_BUCKET=files-woof-tech
S3_ENDPOINT=https://s3.nl-ams.scw.cloud
```

The issue while all the files are not recognized in this configuration is because by essentially already providing the bucket in the endpoint URL, the S3_BUCKET variable ended up making a folder in this bucket. Essentially my bucket, instead of just being /, starts in "/files.woof.tech/".

Because this configuration is wrong, ListObjectsV2 fails, but I can't change it either as mastodon would suddenly start putting the files in the root of the bucket (which is correct), while the old content is still in this folder "files.woof.tech/" in the root directory

I hope it makes sense?

Anyways left for me to do is to move all files from that folder, to the root of the S3 bucket and then modify the configuration. It's a bit of a pain but right now my configuration is actually just wrong and it's been lucky it worked so far
