### ISSUE TITLE
Administration privileges were gone after upgrading from 3.5.2 to 4.0.2

### ISSUE THREAD

**Issue by fweng322** [mastodon/mastodon#22987]
### Steps to reproduce the problem

I upgraded from v3.5.2 to v4.0.2.  I followed [the instructions of upgrade note of 4.0.0](https://github.com/mastodon/mastodon/releases/tag/v4.0.0) , running `SKIP_POST_DEPLOYMENT_MIGRATIONS=true RAILS_ENV=production bundle exec rails db:migrate` .  After upgrading, the instance was up and running, but all the administration privileges of my account was gone.  I checked the first admin account I created for this instance.  It was gone too.

Not sure what steps might be missed when upgrading.  In the upgrade note it said to check if the systemd service files were up-to-date but I didn't see any instructions about how to make sure of it, also not sure if it is related to this administration problem.

Any suggestion about how to get my administration right back?

### Expected behaviour

I should be able to administrate my instance

### Actual behaviour

All my administation rights were gone.  

### Detailed description

For example, I could delete and ban spam toots and users with my own accounts before upgrading, but I can't do it now.

### Specifications

Mastodon v4.0.2.

**Comment by fweng322** [comment]
I checked the database, the `users` table and its data.  The `admin` field of my account is TRUE.  But I didn't find any way to do the administration operations.

**Comment by ineffyble** [comment]
Mastodon 4.0 has a more modular permission system, with a default 3 roles for `Moderator`, `Admin`, and `Owner`.

You can grant an account `Owner` access with [`tootctl`](https://docs.joinmastodon.org/admin/tootctl/#accounts-modify).

E.g. 

```
tootctl accounts modify USERNAME --role Owner
```

**Comment by ineffyble** [comment]
The fact you had this issue suggests you missed the step in the upgrade note where you run 

```
RAILS_ENV=production bundle exec rails db:migrate
```

afterwards to run all the post-deployment migrations.

Those post-deployment migrations should grant Owner to everyone who has admin in the DB.

**Comment by fweng322** [comment]
Thanks.  After running db:migrate again this issue solved.
