### ISSUE TITLE
`failed to connect: Connection refused - connect(2)` should affect job scheduling for a whole domain

### ISSUE THREAD

**Issue by jubalfh** [mastodon/mastodon#22984]
### Steps to reproduce the problem

1. look at the sidekiq queue
2. notice that the jobs trying to poll from or deliver to an URI are still queued every few minutes or so despite receiving *connection refused* error

### Expected behaviour

an exponential backoff should be applied to all requests for a whole domain

### Actual behaviour

an exponential backoff is not applied to all requests for a whole domain

### Detailed description

the jobs for various URIs of a domain are still being queued with the same frequency despite receiving a hard error (tcp connection refused).

### Specifications

Mastodon 4.0.2

**Comment by vmstan** [comment]
@jubalfh is this still an issue for you or can this be closed?

**Comment by vmstan** [comment]
Closed as stale.
