### ISSUE TITLE
Allow editing posts on the iOS app

### ISSUE THREAD

**Issue by rcboler** [mastodon/mastodon#22995]
### Pitch

Editing my posts is currently available on the web. Would be great to be able to do this on the iOS app, so I don’t need to switch between the two. (I didn’t see this on the public right now, forgive me if this is already underway.)

### Motivation

Everyone messes up sometimes! Just aiming for feature parity with the core post functions of the web app.

**Comment by trwnh** [comment]
mastodon/mastodon-ios

**Comment by rcboler** [comment]
Thanks for the redirect, @trwnh!
