### ISSUE TITLE
Quote Toots are worthless

### ISSUE THREAD

**Issue by SoniEx2** [mastodon/mastodon#22994]
### Pitch

There should be a way to link activitypub objects such that they open in the user's app.

### Motivation

Let's say you have a blog or a discord and you wanna link your account or posts, and you want those to open in the user's instance instead of your instance, so they can interact with it.

This would enable mastodon to be a much more effective attention sink. Because you'd click a link and then it'd open your mastodon. Not some read-only third party instance. Then you'd start scrolling your feed soon after.

This would boost mastodon usage, far more than quote toots ever could.

(is this a good sales pitch for eugen? no idea. we're not marketing professionals. but anyway.)

**Comment by trwnh** [comment]
In all seriousness you could do this with FEP-e232 Object Links. Just add a `mediaType` of ActivityPub on the Link inside the `tag` array.

On the authoring side, you would check if a link is an object link by trying to look it up in the local cache or resolve it via ActivityPub using the proper Accept header, and if you find something that resolves as a status or actor, add the proper content type via `mediaType`

**Comment by SoniEx2** [comment]
how is that gonna help discord users open their mastodon apps?
