### ISSUE TITLE
Don't allow guest users to search posts on Mastodon

### ISSUE THREAD

**Issue by n0toose** [mastodon/mastodon#23008]
### Pitch

In the `/explore` tab, users can search for users, content and hashtags on Mastodon **USING AN ADDRESS BAR ON THE TOP LEFT OF THE SCREEN**. I believe this feature should be more restricted or removed altogether.

### Motivation

Full text-based search is already disabled by default on most Mastodon instances, and allowing non-logged in users to search for posts allows for the large-scale scraping of user information without the possibility of the supposed malicious actor being held accountable.

**Comment by n0toose** [comment]
This was not reported as a security vulnerability, because it was clear to me that the way this feature works right now is intended behavior.

**Comment by RianQuenlin** [comment]
The Explore tab is the first place I look to make sure I'm not going into a nazi-ridden shithole.

**Comment by timtfj** [comment]
I feel the ability to search from there is needed—one thing someone needs to know when investigating a server to join or to suggest to a friend is what the search results are like.

And even as a logged-in user, sometimes you know that the best place to search for a given hashtag is on a different server that's full of people who use it. I wouldn't want to lose this option.

**Comment by n0toose** [comment]
> And even as a logged-in user, sometimes you know that the best place to search for a given hashtag is on a different server that's full of people who use it. I wouldn't want to lose this option.

Fair argument (that's actually on topic, edited the original post accordingly) -- hashtags exists for a reason -- but why should you be able to use the Mastodon frontend to search for every user account that a particular server federates with, for example? Is *every post ever* the same as using the Explore tab, which is essentially the closest thing to a curated experience that Mastodon currently offers to offer an insight into the vibe of the particular instance?

**Comment by nemobis** [comment]
Related: https://github.com/mastodon/mastodon/issues/22620

**Comment by n0toose** [comment]
Closing as a duplicate of https://github.com/mastodon/mastodon/issues/22620.
