### ISSUE TITLE
Group function for theme movement - alternative/better than a.gup.pe

### ISSUE THREAD

**Issue by underdog2k1** [mastodon/mastodon#23006]
### Pitch

For desktop users, in the "First Steps" -> Personal area, add the "Groups" function.

1. Join groups
2. Create group

There it should be possible to exchange texts on certain topics.

### Motivation

The current function a.gup.pe is too complicated for most. In addition, this is confusing.

With a "real" group function, like-minded people could network and exchange ideas more easily.

Group movements would benefit from this. That these are not dependent on individual & already existing organizations.

**Comment by FediVideos** [comment]
This is a duplicate of https://github.com/mastodon/mastodon/issues/139

Also, there's already an official groups function under development at https://github.com/mastodon/mastodon/pull/19059

**Comment by underdog2k1** [comment]
Forgive me and thanks for the tip
