### ISSUE TITLE
JavaScript: TypeError: undefined is not an object

### ISSUE THREAD

**Issue by marek-lach** [mastodon/mastodon#23033]
### Steps to reproduce the problem

A JavaScript error when trying to log-in

### Expected behaviour

Redirect to the actual login form after clicking the login button.

### Actual behaviour

Prevented from loggin in. Doesn’t redirect.

### Detailed description

TypeError: undefined is not an object (evaluating 'i.get("rules").isEmpty')
isEmpty (webpack:///app/javascript/opt/mastodon/app/javascript/flavours/glitch/features/about/index.js:162:48)
gi (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:3577:75)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5035:13)
Kj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5029:29)
Ej (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:4815:6)
su ([native code]::)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2331:17)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:252:11)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2328:9)
gg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2320:2)
Mj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:4850:22)
batch(function (webpack:///node_modules/react-redux/es/utils/Subscription.js:15:6)
notifyNestedSubs (webpack:///node_modules/react-redux/es/utils/Subscription.js:75:14)
handleChangeWrapper (webpack:///node_modules/react-redux/es/utils/Subscription.js:79:19)
currentReducer (webpack:///node_modules/redux/es/redux.js:264:31)
fetchServer (webpack:///app/javascript/opt/mastodon/app/javascript/flavours/glitch/actions/server.js:22:15)
promiseReactionJob ([native code]::)

### Specifications

Mastodon 4.0.2

**Comment by vmstan** [comment]
@marek-lach is this still an issue for you or can it be closed?

**Comment by marek-lach** [comment]
> @marek-lach is this still an issue for you or can it be closed?

Not an issue at the moment anymore.
