### ISSUE TITLE
Add support for emoji reactions to posts

### ISSUE THREAD

**Issue by billyanders** [mastodon/mastodon#23035]
### Pitch

Favorites are useful but limited in that they don't express why a post is "interesting". It's like a colleague sending you a pointer to a document without telling you why they are bringing it to your attention.

Implementing the increasingly common ability to express a reaction via a limited set of emojis, similar to LinkedIn (also, Facebook, Discord, WhatsApp, Signal, and now even RCS-based SMS) would express user sentiment. I would recommend a limited set -- eg, Like, Love, Shocking, Sad, Interesting, Support.

From a UX perspective, leveraging how other popular social networks represent this capability would make this addition seamless in its usability due to familiarity. Eg, press the favorite icon and it will expand, inline, to show all the available emojis for the user to choose from. Posts will display the aggregate count of all reactions when space is at a premium (e.g. when viewing the timeline), and show the individual reaction counts when a user is viewing an individual post.

**Comment by trwnh** [comment]
Duplicate of #4106

**Comment by shleeable** [comment]
This has been in discussion for a LONG TIME. It would be `cute`
https://github.com/mastodon/mastodon/pull/13275

**Comment by rollecode** [comment]
I've kinda grown fond of reactions here:

<img width="600" height="534" alt="Image" src="https://github.com/user-attachments/assets/c8c310fc-fe06-4612-a895-6d83f0903a67" />

Makes me wonder - if that kind of feature was added to statuses, would it be a bad thing?
