### ISSUE TITLE
Display date and time of server announcements

### ISSUE THREAD

**Issue by alxsimon** [mastodon/mastodon#23046]
### Pitch

The title says pretty much everything.
Announcements should display at what date and time they have been posted.

### Motivation

This is important in my view to add context. Users have no way to know how old the announcement is.

**Comment by imskr** [comment]
Can I work on this?

**Comment by ClearlyClaire** [comment]
I believe this is a duplicate of #18307, which would be addressed by #18329 if it ever got merged.
