### ISSUE TITLE
Hashtags as metadata and not counted as part of the toot

### ISSUE THREAD

**Issue by btaroli** [mastodon/mastodon#23041]
### Pitch

Why do tags take up toot space? Could hashtags merely be metadata? Allow us to tag for searching without need to constrain our thoughts.

### Motivation

With so many hashtag variants, often very limited toot length, and a growing call for the text of a post to be hashtag free, to better address screen readers and basic readability, and instead to summarize hashtags at the bottom of a toot. And then we get constrained in expressing hashtags (for searching) due to toot length.

**Comment by trwnh** [comment]
Duplicate of #10743

**Comment by trwnh** [comment]
Duplicate of #10743
