### ISSUE TITLE
Audio files sometimes don't play on some instances

### ISSUE THREAD

**Issue by FediVideos** [mastodon/mastodon#23056]
### Steps to reproduce the problem

1. Visit the post at https://mstdn.social/@feditips/109644044918079289 on mstdn.social through web browser and click play
2. Visit the same post on a different instance and click play
...

### Expected behaviour

It should play on all instances

### Actual behaviour

It doesn't play on mstdn.social (where it was posted) though the download link does work

### Specifications

Mastodon 4.0.2 (or other, depends on which instance you are viewing the post from)

**Comment by timtfj** [comment]
> 1. Visit the post at https://mstdn.social/@feditips/109644044918079289 on mstdn.social through web browser and click play
> 2. Visit the same post on a different instance and click play

Frustratingly, I've just tried this on mobile in Chrome for Android, and the following all played for me:

* mstdn.social page, mobile view
* mstdn.social page, desktop view
* mastodon.social search results page, mobile view
* mastodon.social search results page, desktop view
* mastodon.social post page, mobile view
* mastodon.social post page, desktop view

**Comment by FediVideos** [comment]
It just started working for me too, after not working at all on mstdn.social for five days including six hours ago when I posted this.

Presumably some kind of temporary server glitch?

I'll close this if the bug isn't repeatable. Timtfj, you for testing :pray:
