### ISSUE TITLE
Removing large numbers of media files from cloud object storage is very slow

### ISSUE THREAD

**Issue by metadaddy** [mastodon/mastodon#23073]
### Pitch

Currently, removing large numbers of media files from cloud object storage (S3, and other S3-compatible object stores such as Backblaze B2) is very slow. Mastodon admins [report that deleting 11,000 files takes approximately 1.5 hours](https://ricard.social/@ricard/109551417744385295), compared to [2,000 files in under a minute with local storage](https://troet.eloquer.de/@vash/109552533918829764). Not only does this impact performance, but it needlessly consumes API calls, which are a metered resource on most cloud object storage platforms.

The root cause appears to be that the (kt-)Paperclip library's [`flush_deletes`](https://github.com/kreeti/kt-paperclip/blob/master/lib/paperclip/storage/s3.rb#L411) method deletes objects one by one, rather than taking advantage of the S3 API's [`DeleteObjects`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html) action, which allows deletion of up to 1,000 objects per API call:

```ruby
      def flush_deletes #:nodoc:
        @queued_for_delete.uniq.each do |path|
          begin
            log("deleting #{path}")
            s3_bucket.object(path.sub(%r{\A/}, "")).delete
          rescue Aws::Errors::ServiceError => e
            # Ignore this.
          end
        end
        @queued_for_delete = []
      end
```

A fix would be to create batches of 1000 files, and call [`s3_bucket.delete_objects()`](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Bucket.html#delete_objects-instance_method) for each batch.

I notice that [kt-paperclip](https://github.com/kreeti/kt-paperclip) doesn't seem to be very active, so I'll submit a PR for a monkey patch here as well as a PR for the 'real' fix there.

### Motivation

Any Mastodon admin storing media files in a cloud object store such as S3 or Backblaze B2 will benefit from a fix for this issue.

**Comment by quicoto** [comment]
Yes, please. Since the process of deleting assets off the object storage is so slow I need to run the cronjob hourly rather than once a day.

Thank you

**Comment by Gargron** [comment]
I think that there’s probably no way to put this functionality into paperclip, but we could add this logic outside of the model where mass-deletes happen. Definitely good idea.

**Comment by metadaddy** [comment]
@Gargron It looks like the fix should be in `Paperclip::Storage::S3::flush_deletes`. This is the current code:

```ruby
      def flush_deletes #:nodoc:
        @queued_for_delete.uniq.each do |path|
          begin
            log("deleting #{path}")
            s3_bucket.object(path.sub(%r{\A/}, "")).delete
          rescue Aws::Errors::ServiceError => e
            # Ignore this.
          end
        end
        @queued_for_delete = []
      end
```

This is what I have so far, in [`config/initializers/paperclip.rb`](https://github.com/metadaddy/mastodon/blob/bulk-delete/config/initializers/paperclip.rb#L93):

```ruby
module Paperclip
    module Storage
      module S3Extensions
        OBJECTS_PER_BATCH = 1000 # Defined by https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html

        # Batch up deletes. See https://github.com/mastodon/mastodon/issues/23073
        def delete_objects(objects)
          begin
            log("deleting #{objects.size} objects")
            s3_bucket.delete_objects({
              delete: {
                objects: objects,
                quiet: true
              }
            })
          rescue Aws::Errors::ServiceError => e
            # Ignore this.
          end
        end

        def flush_deletes
          objects_to_delete = []
          @queued_for_delete.each do |path|
            log("deleting #{path}")
            objects_to_delete.push({key: path.sub(%r{\A/}, "")})
            if objects_to_delete.size == OBJECTS_PER_BATCH
              delete_objects(objects_to_delete)
              objects_to_delete = []
            end
          end
          if objects_to_delete.size > 0
            delete_objects(objects_to_delete)
          end
          @queued_for_delete = []
        end

        # Some S3-compatible providers might not actually be compatible with some APIs
        # used by kt-paperclip, see https://github.com/mastodon/mastodon/issues/16822
        if ENV['S3_FORCE_SINGLE_REQUEST'] == 'true'
          #...existing code...
        end
      end
    end
```

I need to build a dev environment so I can test that this indeed fixes the issue.

**Comment by Gargron** [comment]
This won’t do it, this will at most batch 2 or 3 deletes together, because this function is local to a single record.

**Comment by metadaddy** [comment]
> This won’t do it, this will at most batch 2 or 3 deletes together, because this function is local to a single record.

Yeah - I realized that last night. `Mastodon::MediaCLI::remove` needs to pause deletes before it loops through the media attachments, and resume them afterwards, ultimately resulting in a call to the `DeleteObjects` action.

I'm thinking that two methods, 'startBatch` and `endBatch` should live in `Paperclip::Storage::S3Extensions`, and the `endBatch` method should call `flush_deletes`. Something like this:

```ruby
        def flush_deletes
          unless @deletes_are_paused
            objects_to_delete = []
            @queued_for_delete.each do |path|
              log("deleting #{path}")
              objects_to_delete.push({key: path.sub(%r{\A/}, "")})
              if objects_to_delete.size == OBJECTS_PER_BATCH
                delete_objects(objects_to_delete)
                objects_to_delete = []
              end
            end
            if objects_to_delete.size > 0
              delete_objects(objects_to_delete)
            end
            @queued_for_delete = []
          end
        end

        def start_batch
          log("pausing deletes")
          @deletes_are_paused = true
        end

        def end_batch
          log("resuming deletes")
          @deletes_are_paused = false
          flush_deletes
        end
```

The next question is, how does `Mastodon::MediaCLI::remove()` call `start_batch`? That's what I'm trying to figure out now!

**Comment by metadaddy** [comment]
See pull request [23097](https://github.com/mastodon/mastodon/pull/23097).

**Comment by metadaddy** [comment]
@Gargron I think I've cracked it. See pull request https://github.com/mastodon/mastodon/pull/23097.
