### ISSUE TITLE
Links to media posts in profile are broken (web UI)

### ISSUE THREAD

**Issue by Roboron3042** [mastodon/mastodon#23070]
### Steps to reproduce the problem

1. Got to any profile with media uploaded and click on the media tab.
2. Right click on any media and select "Open URL in a new tab".
3. You get a 404 page instead of the post with the media.

### Expected behaviour

The media post link is instance.domain/@user/whatever

### Actual behaviour

The media post link is instance.domain/@undefined/whatever

### Detailed description

The very same link works when searching (and on the mobile app), but not when you open it in a browser tab.

### Specifications

Mastodon 4.0.2

**Comment by trwnh** [comment]
that's very weird, i have no idea why the `account.acct` would break only in the [media_item component](https://github.com/mastodon/mastodon/blob/f4a6365f55c3b16494337e0880b42108cc4a171a/app/javascript/mastodon/features/account_gallery/components/media_item.js#L133) and nowhere else -- the function `status.getIn(['account', 'acct'])` is called in multiple other locations and works fine in those locations.

**Comment by ClearlyClaire** [comment]
That's because `status.get('account')` is the account ID, in other places the account object is inlined using a selector through `makeGetStatus`

**Comment by tribela** [comment]
v4.1.2 still having this problem.

**Comment by ClearlyClaire** [comment]
Addressed by #24218, will try to think about it if we do another backport release.
