### ISSUE TITLE
Consider also supporting OAuth 2.0 implicit grant [aka: do not leak authorization token via query string]

### ISSUE THREAD

**Issue by untitaker** [mastodon/mastodon#23074]
### Pitch

Consider supporting [OAuth 2.0 implicit grant](https://www.rfc-editor.org/rfc/rfc6749#section-4.2) for web clients and other applications where distinction between [front-channel and back-channel](https://stackoverflow.com/a/46552095/1544347) doesn't make sense.

### Motivation

Two problems:

1. If one uses Elk or Pinafore today, credentials are leaked to the web server on elk.zone or pinafore.social via query string. Those credentials are fortunately short-lived, however, this could be avoided since the entire application lives in the browser anyway. Even if neither are spyware it is easy to imagine accidental leakage through web server's access logs.
2. Implicit grant does not require developers to pre-register their application using a separate API request to `/api/v1/apps`.

### Comparison between implicit grant and authorization code based

* Implicit grant does not require you to pre-register your application on `/api/v1/apps` to obtain a client key and client secret. This is more convenient for the application developer.

* Implicit grant directly returns the _access token_ as part of the URL _fragment_ of the redirect URI rather than returning a _authorization code_ as part of the URL _query string_.

  For people unfamiliar with the difference between authorization code and access token, the authorization code can be used in a [`POST /oauth/token` request](https://docs.joinmastodon.org/methods/oauth/#token) to request an access token. The access token is persisted by the application and used to make further API requests while the authorization code expires rather quickly.

  The **downside** to this flow is that instead of the (hopefully temporary) access code persisting as part of your browser history, the (more permanent) access token is persisted.

  I think this downside does not matter as much for web clients where the entire application state (including the access token) lives in the browser anyway, and is IMO also outweighed by the upside of not inherently sending any credential to the web server where it could end up in access logs.

### More resources

* https://stackoverflow.com/a/14718532/1544347
* https://stackoverflow.com/a/7688532/1544347

### Alternative: A non-standard solution

Both kinds of grants in OAuth 2.0 have their respective drawbacks. Authorization code based flows leak a credential to the server through query string, while implicit grant leaks the access token into browser history.

However, the problem of leaking the access code to the server could easily be solved with a proprietary parameter to the currently implemented flow that makes Mastodon return the authorization code in the fragment rather than the query string, without implementing an entirely different authorization flow or suffering the drawback of implicit grant where long-lived credentials are leaked into browser history.

**Comment by trwnh** [comment]
Implicit flow is deprecated for a variety of security reasons, and has even been removed entirely from OAuth 2.1. The best practice recommendation is to use PKCE with the authorization code flow. See https://oauth.net/2/grant-types/implicit/ and https://developer.okta.com/blog/2019/05/01/is-the-oauth-implicit-flow-dead for more info

**Comment by nightpool** [comment]
My understanding is that because pinafore and elk generate new client secret requests on the client-side, and they're never send to the server, there is no "leakage" here, since the query parameters need to be combined with the client secret to retrieve the access token, and only the client has the client secret. This is the authorization code grant working as expected, and moving to the implicit grant would be a downgrade in security with no upside.

**Comment by untitaker** [comment]
Thanks for catching that, indeed the client secret is never sent to the app backend or stored in the browser history so indeed implicit grant would be less secure here.
