### ISSUE TITLE
Increase information density

### ISSUE THREAD

**Issue by joshka** [mastodon/mastodon#23086]
### Pitch

Increase the characters per line to between 50-75 characters (perhaps user configurable?) for better readability.

Reduce whitespace. We can all agree that whitespace is nice from a design perspective to make things look pretty, but too much negatively effects speed of information consumption. The current Mastodon layout has (subjectively) significantly too much wasted space. For instance on a standard MBP15 I often have as few as 2 toots showing. Compare this to say tweetbot, where I might have 8-10 tweets showing.

### Motivation

Faster scrolling / information consumption.

**Comment by RockstarRaccoon** [comment]
Links are shortened to encourage their use and writing good descriptions for them.  If they take up 50 characters or more, that's at least 10% of a default character-length post taken up by the link, which can't be used for the CW and context.

**Comment by joshka** [comment]
This issue isn’t
about links. It’s
about text. What’s
within that text is
good enough.

;)
