### ISSUE TITLE
Actions taken from the report page should allow writing a description/reason

### ISSUE THREAD

**Issue by twilde** [mastodon/mastodon#23082]
### Pitch

The actions on the report page (/admin/reports/XXX) should allow writing a description/reason. Currently it is necessary to use the "Custom" action to be able to write a reason, and when doing so it is not clear if the post context or other items from the report are still included. It would be much more clear to go from a button like "suspend" to a "reason for suspension?" page, then complete the action.

### Motivation

Improve usability of moderation tools.

**Comment by ClearlyClaire** [comment]
I believe this is addressed by https://github.com/mastodon/mastodon/pull/22375
