### ISSUE TITLE
Scheduling images 

### ISSUE THREAD

**Issue by Madaeason915** [mastodon/mastodon#23088]
### Pitch

Please-a schedule feature for iOS to allow ability to post photos with alt text

### Motivation

I don’t know the extent its widely needed. It would be a game changer for me. If by some miracle someone could make this happen, I’d be the happiest user in the world. 🤞Thank you.

**Comment by ClearlyClaire** [comment]
Hi! Please file bugs for the iOS app here: https://github.com/mastodon/mastodon-ios
