### ISSUE TITLE
Vim style keyboard navigation in normal ui

### ISSUE THREAD

**Issue by joshka** [mastodon/mastodon#23085]
### Pitch

j/k etc. would make scrolling the UI nicer.

### Motivation

Anyone that's used to using Vim.

**Comment by jan-vandenberg** [comment]
This is already possible, though it's yanky and you to select a post first for it to work. Also see https://github.com/mastodon/mastodon/issues/19100 and others.

**Comment by joshka** [comment]
Got it, I’m going to close this to let the work continue there.
