### ISSUE TITLE
Search result "people" category is confusing (Web UI)

### ISSUE THREAD

**Issue by steevithak** [mastodon/mastodon#23092]
### Steps to reproduce the problem

1. Type an name in the Mastadon website search box
2. Hit "search" icon
3. Result shows four tabs/filters, one is filter for account profiles that match the search string but is label as "people"

### Expected behaviour

search filters should intuitive, non-surprising names

### Actual behaviour

search filter has confusing name that makes it unclear what search results will be included

### Detailed description

I frequently need to search for account profiles of organizations (e.g. companies, not-for-profit orgs, NGOs, news organizations, etc) and none of those would normally be categorized as "people". It would make much for sense to use the name "Accounts" or "Profiles" instead of "People" for the filter that limits search results to account profiles. This is particularly confusing for new users (once you've been here a while, you mentally classify it as a "known bug" and ignore it but at first it's not clear at all how to search for account profiles, particularly if you're not looking for a person's account. This should be an easy fix that would improve the UI experience for new users significantly as most new users spend a lot of time searching for account profiles to follow after signing up.

### Specifications

Mastodon v4.0.2

**Comment by renchap** [comment]
Closing, the category has been renamed into "profiles"
