### ISSUE TITLE
Bug?: account.approved webhook triggered on account still in confirming status

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#23098]
### Steps to reproduce the problem

1. setup webhook for account.approved.
2. notice an event with an unapproved account.

![image](https://user-images.githubusercontent.com/17537000/212529446-c6be18fd-449a-4b10-b8ec-b1e4aac42cfe.png)

### Expected behaviour

All accounts triggering on this webhook should be approved

### Actual behaviour

account was not approved, and broke the script that assumed the account is activated

### Specifications

main.

**Comment by ClearlyClaire** [comment]
You claim multiple times that the account wasn't **approved**, so the account was both unconfirmed (no email verification) and unapproved (no moderator approved it), or did the issue arise when it was approved by a moderator but not yet confirmed by the user?

**Comment by ClearlyClaire** [comment]
I marked #23245 as fixing this because I could find and fix an issue where approved accounts trigger the web hook even if the email wasn't confirmed, but I could not find an issue where the web hook would trigger for an unapproved account.
