### ISSUE TITLE
Verification email retry fails to update the message onscreen

### ISSUE THREAD

**Issue by alexbbrown** [mastodon/mastodon#23093]
### Steps to reproduce the problem

1. start registration process
2. enter email1@firstexample.com (replace with a real email address) and submit "GET ON WAITLIST" (or whatever)
3. observe screen "A message with a confirmation link has been sent to your email address." with "The confirmation e-mail was sent to email1@firstexample.com
5. press "Didn't receive confirmation instructions" 
6. enter email2@secondexample.com (replace with a real email address) and submit "RESEND CONFIRMATION INSTRUCTIONS"
3. observe screen "A message with a confirmation link has been sent to your email address." with "The confirmation e-mail was sent to email1@firstexample.com
...

### Expected behaviour

after submitting a revised email address, the next screen should show "3. observe screen "A message with a confirmation link has been sent to your email address." with "The confirmation e-mail was sent to email2@secondexample.com"

### Actual behaviour

after submitting a revised email address, the next screen should show "3. observe screen "A message with a confirmation link has been sent to your email address." with "The confirmation e-mail was sent to email@firstexample.com"

### Detailed description

After submitting a second, revised email address during sign-in, the confirmation screen should indicate - at a minimum - the most recent email submitted.

<img width="1024" alt="Screenshot 2023-01-14 at 18 11 42" src="https://user-images.githubusercontent.com/2532344/212521863-063e16bd-2912-4c44-b240-1fb437889501.png">

### Specifications

Mastodon 4.0.2

**Comment by alexbbrown** [comment]
Maybe I misunderstood the purpose of this UI.

Why does this screen allow you to enter a new address, if

* it doesn't update the user email address (based on the evidence above)
* it doesn't actually send to that address (as far I can tell)
* it doesn't seem to re-send to any address (as far as I can tell)

<img width="1024" alt="Screenshot 2023-01-14 at 18 12 18" src="https://user-images.githubusercontent.com/2532344/212522212-7af1011a-0a7e-4fa7-a52e-9948b15d6559.png">

**Comment by iamradioactive** [comment]
@alexbbrown, As per my observations, the application allows us to edit the email because the feature can be accessed without logging in as well. 

**Proposed solution:** When a user is logged in, the email field can be set to **read-only** since a message notifies them to update their email via account settings if needed. 

Please let me know what you think.

**Comment by ClearlyClaire** [comment]
Oh, this is a set of very interesting bugs!

- it *is* possible to change your email address after setting one from the account settings, but it does not overwrite the unconfirmed initial one until the new e-mail is clicked; this does make sense, but considering neither address is confirmed, it may be a bit confusing
- the address input on `/auth/confirmation/new` exists for unlogged users, but it is shown even if you are logged in, and is not used in this case… this is hugely confusing

**Comment by ClearlyClaire** [comment]
> * the address input on `/auth/confirmation/new` exists for unlogged users, but it is shown even if you are logged in, and is not used in this case… this is hugely confusing

Actually it's not exactly that either… it will send a mail to the user using this email address, if it exists, like when you're not logged in. But unlike when you are logged in, it will return you to the the screen about the initial confirmation e-mail, without the explanation you get when you are not logged in. So still very confusing.

I think the @iamradioactive's proposal to mark the field read-only if you are logged in, while not ideal, would be less confusing. The screen could have a reminder that “If that e-mail address is not correct, you can change it in account settings.”
