### ISSUE TITLE
Admin:read rights to a token not assigned via gui

### ISSUE THREAD

**Issue by oculos** [mastodon/mastodon#23099]
### Steps to reproduce the problem

1. I assign admin:read or admin:write to a token
2. I go to the database, and it's not assigned
3. I get permission errors when attempting to do something that requires `admin:write` or `:read`
4. I add these rights directly on the database, and things work.
...

### Expected behaviour

Giving `admin:read` to a token should work

### Actual behaviour

It doesn't work

### Specifications

Mastodon 4.0.2

**Comment by ClearlyClaire** [comment]
Seems like this should be fixed by https://github.com/mastodon/mastodon/pull/20918
