### ISSUE TITLE
Landscape orientation on iOS

### ISSUE THREAD

**Issue by dmitrizzle** [mastodon/mastodon#23091]
### Pitch

I'm using Mastodon for iOS `v1.4.9 (224)`. The landscape mode doesn't seem to exist, so I can't view images in landscape mode, or the websites.

It would be good to be able to do that, **specifically for image viewing**. Some websites' mobile versions cut off content in portrait mode (although, the latter isn't as important since I can pop them into Safari if needed).

### Motivation

I use Mastodon to connect with my photo community; image viewing is quite important. I understand that updating the entire interface to work in the landscape may be overkill, but it would be good to be able to view the images in multiple orientations.

I figure it's a feature and not a bug since this never worked for me.

**Comment by ClearlyClaire** [comment]
Hi! Please file bugs for the iOS app here: https://github.com/mastodon/mastodon-ios
