### ISSUE TITLE
Poll percentage for no was 107% (which is greater than 100%...)

### ISSUE THREAD

**Issue by jsoref** [mastodon/mastodon#23108]
### Steps to reproduce the problem

1. Browse through timeline
2. See https://mastodon.social/@dancinyogi@mastodon.sdf.org/109694132538004342
3. Vote
4. See 7% and 107% 

### Expected behaviour

Individual percentages should never be above 100%, and the general sum should be roughly 100% and not significantly beyond

### Actual behaviour

7% and 107%

### Detailed description

<img width="572" alt="image" src="https://user-images.githubusercontent.com/2119212/212634236-74531e35-8338-4e98-8ad5-7314fef538ea.png">

### Specifications

v4.0.2

Chrome Version 108.0.5359.124 (Official Build) (arm64)
macOS Ventura 13.1

Home instance is mastodon.social

**Comment by jsoref** [comment]
Fwiw, I'm not the only person who saw this: https://mastodon.social/@jsoref/109698005925013769

**Comment by Gargron** [comment]
It’s probably a multiple choice poll

**Comment by jsoref** [comment]
It doesn't appear to be. Did you look at it? Even if it was a multiple choice poll, that wouldn't justify any single answer getting >100% which happened here.

A better guess is that Boosts messed with the accounting.

**Comment by arittner** [comment]
> It’s probably a multiple choice poll

No. It's not a multiple choice. Why is it closed / completed? Is there a fix or already fixed?

**Comment by arittner** [comment]
Also wrong poll results via https://social.tchncs.de/@dancinyogi@mastodon.sdf.org/109694132468665136

![wrong poll](https://user-images.githubusercontent.com/5605065/212659023-b4bb6562-a758-47da-bcfc-99536b0056d6.png)
