### ISSUE TITLE
Media not deleted from Remote (r2) S3

### ISSUE THREAD

**Issue by gr8rehanna** [mastodon/mastodon#23100]
### Steps to reproduce the problem

Using Mastodon Latest Version\
Enabled S3 \
Using Cloudflare R2 (s3 compatible)\
------------\

 Click on NEW POST\
Attach photo \
Now cancel (do not post)

### Expected behaviour

Images once deleted from web should also get deleted from R2

### Actual behaviour

Images are still in bucket 

### Detailed description

Issue : Remote files are not deleted when deleted from web.

Click on + New Post (attach image)\
(its is now draft) \
Do not post cancel it.\

If user doesn't post images are uploaded in R2  and is expected to get deleted from R2. \ 
But image remains on R2 even if user doesn't post.

case 2.\
If user uploads a image on web/app.

After some time i .e: 10 minutes\
user decided to delete post(image)\
Click on DELETE - Now post is no longer available.
BUT On r2 image remains in bucket and is never deleted.

Am i doing something wrong?

### Specifications

Mastodon version: Latest
Browser: Chrome
Os : Linux /ubuntu

**Comment by Gargron** [comment]
Unused file will be deleted in 24 hours
