### ISSUE TITLE
Extensive Media Storage requirement

### ISSUE THREAD

**Issue by KDederichs** [mastodon/mastodon#23117]
### Steps to reproduce the problem

Mastodon seems to cache every media it comes across for a while, quickly bloating the media cache.

### Expected behaviour

It doesn't do that

### Actual behaviour

Harddrive fills up and services start up crashing

### Detailed description

Ok, while investigating the other error I came across it turns out: The harddrive is full.

Looking at the storage allocation Mastodon's Media Storage takes up like... 80% of that space.

While caching Media is nice it shouldn't fill up to the point where the drive is so full it crashes the Postgres database. 

IMO it should delete Media that's older than a week or something if you don't do that already.

Edit: Single user instance btw, and I surely didn't upload 10's of GB of media so that's from other instances.

### Specifications

Mastodon 4.0.1
Rails 3.0.4

**Comment by baldhead** [comment]
Same issue here (in 4.0.2)
For some reason, after clearing cache with 'tootcl media remove --days 1', I can still find (older) media in the /public/system/cache folder.

**Comment by Tslmuun** [comment]
> Same issue here (in 4.0.2) For some reason, after clearing cache with 'tootcl media remove --days 1'


Should be  “tootctl media remove --days=1”
