### ISSUE TITLE
Something with the tracking on my phone causes the page to jump to the settings in the middle of me typing, losing 1,000 character posts.

### ISSUE THREAD

**Issue by RockstarRaccoon** [mastodon/mastodon#23134]
### Steps to reproduce the problem

1. Go start making a long post.
2. Mess around with it until something triggers the settings page
3. Lose entire post.
4. Clicking the back button just takes you to an empty post page: I can find no way to recover these posts.

### Expected behaviour

It shouldn't have gone to the setting page, but even if there's something happening there, there should be a warning.

### Actual behaviour

Post screen disappears, with everything I've typed, zero warning as I'm shunted to the settings page for seemingly no reason.

### Detailed description

I'm not really sure what's causing it to jump to the settings page like this, whether it's the phone detecting input that isn't there, me accidentally hitting the button without realizing it, or the interface itself hitting some sort of input that makes it decide it needs to do that, but this really should not be happening regardless.  If there is a way to click something that instantly erases your post, there should either be a way back from that, or at the very least a warning before it does it so you can have it not happen.

This is a bug that Reddit actually had that they only recently patched, and it's absolutely aggravating, because it's bad UI design in the first place.

This is pretty critical for me, because sometimes I'm typing things that I'm not going to be able to type again, and it doesn't seem at all reasonable or perhaps totally even feasible for me to type everything in a separate window and copy it over, especially since I wouldn't have access to the character count I'm trying to keep things under.  Just now it happened right as I was trying to click the post button on something that was nearly a thousand characters long, and there wasn't a backup because I had written it in the moment without any plan to do anything but post it.

Obviously, the solution here is to either make it so, when you are suddenly taken to the settings page, in the middle of a post, it provides a way for you to get back to that post, OR immediately warns you when it sees you leaving a post that you've typed into, like it would on the desktop version.

### Specifications

Mastodon web interface on Google Chrome, using an Android Phone.  (Up to date as far as I know)

**Comment by RockstarRaccoon** [comment]
(Also apparently GitHub needs a warning for the close-issue button)

**Comment by ClearlyClaire** [comment]
> If there is a way to click something that instantly erases your post, there should either be a way back from that, or at the very least a warning before it does it so you can have it not happen.

Navigating out of the page when you have a non-empty compose form does trigger a confirmation dialog (using the [beforeunload](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event) event), so you should have had a confirmation screen and there is not much more we can do.

My guess is whatever issue caused the spurious navigation in the first place also discarded the confirmation dialog.

As it appears to be an issue with your device and nothing we can do, I am closing this issue. However, feel free to reopen if you re-encounter it and have some more information!
