### ISSUE TITLE
Mutes and Blocks "follow" migrated accounts

### ISSUE THREAD

**Issue by Aranjedeath** [mastodon/mastodon#23159]
### Pitch

As far as I can tell, when someone I have muted or blocked migrates their account from one server to another, the mute or block is lost (remains associated with the pre-migration account). This allows people to dodge these expressions of desired non-interaction. I have no idea how this should work, but that should be fixed so that when I express I do not want to hear from someone, or that they should not interact with me, that expression is preserved by the mastodon software on my behalf. 

### Motivation

Frankly it is selfish, there are some people I do not want to hear from and they have been server-hopping, which has resulted in me having to mute or block them over again. However, there are also significant upsides for people who are attacked online and have similar sorts of problems where it may be more dangerous than annoying to see someone again in the fediverse.

**Comment by trwnh** [comment]
it should carry over if they use the native account migration feature. i have seen users with a private note saying something along the lines of "this user moved from xxx which you had blocked"

**Comment by ClearlyClaire** [comment]
Blocks and mutes should already carry over if your server is made aware of the migration (which may not happen if a server-wide block is involved).
