### ISSUE TITLE
Notifications (bell) ignore filters (in Notifications column)

### ISSUE THREAD

**Issue by Truhe2342** [mastodon/mastodon#23165]
### Steps to reproduce the problem

1. Follow a user
2. Enable notifications for the user
3. Configure a filter for a hashtag
4. Let the user post something with that hashtag
5. Watch your Home and Notifications columns

### Expected behaviour

Notifications columns does not show the post (=behaves like Home column)

### Actual behaviour

Notification column does show the post (=ignores filter)

### Specifications

v4.0.2

**Comment by ClearlyClaire** [comment]
I can replicate the issue and will investigate it.
