### ISSUE TITLE
WebFE bug: Dragging image causes modal

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#23182]
### Steps to reproduce the problem

Just drag any image and it'll show a modal on at the very top of the screen... if you scroll a little, it cuts it off
![image](https://user-images.githubusercontent.com/17537000/213863902-100a5b6e-3a3c-4d7d-a1d3-b3f0e5104de2.png)

### Expected behaviour

Dragging an image should just do what the browser wants

### Actual behaviour

it bought up the drop and drag upload modal

### Specifications

main

**Comment by ClearlyClaire** [comment]
I am not sure I understand the issue. I'm unable to trigger the drag and drop upload UI by dragging a media attachment from Mastodon itself, and whenever I do trigger that UI by dragging a local file, I am unable to scroll.
