### ISSUE TITLE
Notification mails are sent several (min 5) times

### ISSUE THREAD

**Issue by memo-567** [mastodon/mastodon#23198]
### Steps to reproduce the problem

After updating to v4.1.0rc1, the notification and password reset mail is sent multiple ( min 4?) times.

### Expected behaviour

Mail should be sent only once.

### Actual behaviour

Mail is sent four times.

### Detailed description

![masto hw2k com -  2023 - 01 - 22  14 - 49](https://user-images.githubusercontent.com/58190287/213919410-2109d912-190e-430b-b23c-21098fc469ac.jpg)

### Specifications

![masto hw2k com -  2023 - 01 - 22  14 - 57](https://user-images.githubusercontent.com/58190287/213919601-58c95cff-8ed2-4499-bc29-8ff2ba8f5e39.jpg)

**Comment by memo-567** [comment]
Same with password reset mails.

**Comment by memo-567** [comment]
> "Disabling notification and enabling it afterwards stops sending."

Error on my part: The mails continue to be sent without a recognizable interval.

**Comment by memo-567** [comment]
Sidekicq:
![masto hw2k com -  2023 - 01 - 22  16 - 07](https://user-images.githubusercontent.com/58190287/213923078-06ec6e7a-2787-43de-8538-0f47750ac7d3.jpg)

**Comment by smiba** [comment]
This ticket needs more information about your mail server, as this likely is a misconfiguration on that side. The Sidekiq jobs seems to think something went wrong because the connection is not terminated correctly and will retry it (until it becomes a "failed" job)

**Comment by memo-567** [comment]
It seems to happen only if both, Mastodon and mail server are on the same host.

Any other works fine.

Btw. It works fine also - till the upgrade to v4.1.0rc1

**Comment by memo-567** [comment]
Summary, it works perfect with this mail server:

All other websites ✅
All mail clients ✅
Mastodon v4.0.2 ✅
Mastodon v4.1.0rc1 ❌

**Comment by ClearlyClaire** [comment]
> Btw. It works fine also - till the upgrade to v4.1.0rc1

So it used to work fine on v4.0.2?

It would be helpful if you could share your exact SMTP settings (except credentials of course) so we could try replicating the issue.

**Comment by memo-567** [comment]
> So it used to work fine on v4.0.2?

Yes, and the versions before.

**Comment by smiba** [comment]
Could you share your SMTP settings? It would greatly help debugging this issue

**Comment by memo-567** [comment]
```
SMTP_SERVER=localhost
SMTP_PORT=25
SMTP_AUTH_METHOD=none
SMTP_OPENSSL_VERIFY_MODE=none
SMTP_ENABLE_STARTTLS=auto
SMTP_FROM_ADDRESS='Mastodon <notifications@xxxx.xxx>'
```

**Comment by smiba** [comment]
Thanks! 

Do you have the name of your mail software + version as well? I forgot to ask for them earlier.

**Comment by memo-567** [comment]
Dovecot 2.3.13
Postfix 3.5.17

**Comment by ClearlyClaire** [comment]
I haven't tried to replicate the exact same setting yet, but I have no issue with Mastodon 4.1.0rc1 sending mails through Postfix 3.4.23 on a local network, and I can't see any change between 4.0.2 and 4.1.0rc1 that could explain a change in behavior like this… I'm honestly have no idea what's happening here

**Comment by memo-567** [comment]
Strange. So I have to stay with this.

However, I already use MailGun, so I can bypass the whole thing.

I'll test this again after upgrading to Mastodon v4.1.0

**Comment by smiba** [comment]
If switching to another mail provider fixes it, it strengthens my suspicion there is something wrong with your postfix or system configuration. 

Are you confident no additional changes were made to your system during the update from mastodon v4.0.2 to v4.1.0rc1, package updates etc?

**Comment by memo-567** [comment]
No changes at all, otherwise I would have looked at that first :)

**Comment by ClearlyClaire** [comment]
Thanks to another report, I believe I have found the culprit, which was an updated dependency with an undocumented change adding a default read timeout of 5 seconds: https://github.com/mikel/mail/commit/4f56234f04eb041810641ee0dfd717034a59b9dc

**Comment by memo-567** [comment]
Congrats and thank you for finding the cause.
Undocumented changes are terrible. Will that change back again in the next Mastodon release?

**Comment by vmstan** [comment]
@memo-567 can you confirm this issue has been fixed and can be closed?

**Comment by memo-567** [comment]
@vmstan 

Sorry, since these issue, I have uninstalled my mail server and use an external provider only   ¯\\\_(ツ)_/¯
