### ISSUE TITLE
Added "Has Blocked Users" count to a profile

### ISSUE THREAD

**Issue by alsutton** [mastodon/mastodon#23209]
### Pitch

Understanding if a user is prone to blocking others gives others a better understanding of whether they will be likely to engage in debate, or try to silence other users if they disagree. 

### Motivation

Some folk are sensitive to confrontation and debate, and choose to block others rather than discuss diverse viewpoints. Seeing if a user has a high block count will help folk judge whether there would be value in engaging in a debate with someone, or whether the person is unlikely to receive diverse view points well, and so it would be better to not try and engage them in a debate.

**Comment by smiba** [comment]
I personally don't think this is a good idea, blocks should not be public and are not a valid display of someone's "willingness" to engage in "debate" 

An inactive user will have way less people blocked, a very active user might have more people blocked. What I'm trying to say is that a blocked count is relative to someone's activity. 

Additionally I strongly believe anyone should be free to block anyone for any reason if they don't feel like interacting with them.

**Comment by alsutton** [comment]
I agree that anyone should be free to block anyone, but I don't think activity correlates with block count, to me it correlates with someones tendancy to block others as part of the habits they have on any particular platform.

Personally I've had social media accounts on sites for 10+ years, with tens of thousands of posts, and blocked a handful of people. Other folk have less than a thousand posts and have expressed gladness that they do not have to count the number of people they've blocked.

Having public blocks are, to me, part of an open and transparent system. Blocking does have a public effect in that folk can not interract with posts which directly mention them if they are blocked, and there seems, to me, to be value allowing everyone to differentiate between a post which mentions someone that the mentioned person has chosen not to respond to, and one where the mentioned person is unable to respond due to a block.

**Comment by Cassolotl** [comment]
I *strongly* feel that information related to one's blocking activity should remain private.
