### ISSUE TITLE
[Improvement] The login workflow is VERY confusing for registered users

### ISSUE THREAD

**Issue by Zeioth** [mastodon/mastodon#23200]
### Pitch

This is what most people are experiencing when trying to login into Mastodon:

* They search "Mastodon" on Google
* First result is Mastodon.Social → Click
* They try to login, they can't  → Because they are not registered on mastodon.social
* They try to recover password, and never get it → Because they are not registered on mastodon.social
* They try to register again → But it is not possible to register on mastodon.social.

### Motivation

It is very important we add a message to the login screen telling our users:

    You will only able to login from the server you originally registered on.

Even better, would be, to tell them what server is that → Maybe they deleted the registration email and they don't know anymore.

**This is currently a critical threat to Mastodon user adquisition.**

**Comment by jtormolobo** [comment]
I think this problem would be solved by adding a web client that redirects the servers.

When people register from the mobile, can be that they think of their instance as a parameter to include within the login, and not as much as a server to enter for the web client.

Adding a "mastodon.com" (or .org or whatever) with a login form that asks for the instance parameter (and positioned before mastodon.social) could fix that problem.

**Comment by ClearlyClaire** [comment]
I think this is addressed by https://github.com/mastodon/mastodon/pull/20946 which will be included in the upcoming release.
