### ISSUE TITLE
Add an API for reading the list of supported languages

### ISSUE THREAD

**Issue by j-f1** [mastodon/mastodon#23237]
### Pitch

Add an API route that exposes the contents of `LanguagesHelper::SUPPORTED_LOCALES`.

This could either be as a new key on `/api/v2/instance`, or as a separate route (`/api/v2/instance/languages`?).

The current language JSON data embedded in `initial-state` is 5.7kB, so I’m not sure if it’s worth having a whole new API route just to save 5kB per call to `/api/v2/instance`. Thoughts? I’d be happy to implement this if you’re willing to guide me on where the data should be exposed from.

### Motivation

Currently, apps that want to allow users to select the language they want to post using must maintain their own list of supported languages. Mastodon has its own such list, which is exposed to the frontend through the initial state. An API should be added to allow 1st and 3rd-party clients to download this list of languages for display to their users.

**Comment by VyrCossont** [comment]
This would be great for client devs. I ran into the lack of it while adding a language selector to the Feditext native client. Without such an API, there's no way to provide the user with a reliable list of the languages supported on a given server, especially if the admin has customized the list.

(Creating a status with an unsupported language currently succeeds but creates the status with the user's default language, which results in silently mistagged statuses.)
