### ISSUE TITLE
Dependency "GitLab OmniAuth OpenID Connect" will be archived soon

### ISSUE THREAD

**Issue by CSDUMMI** [mastodon/mastodon#23253]
### Steps to reproduce the problem

[gitlab-omniauth-openid-connect](https://github.com/mastodon/mastodon/blob/main/Gemfile#L43) is currently a dependency used by Mastodon to enable SSO Logins via OpenID Connect.

According to the source code repository for this dependency, this gem will be archived soon.

> NOTE: This project will be archived soon! All changes have been upstreamed in https://github.com/omniauth/omniauth_openid_connect.

[Repository Description](https://gitlab.com/gitlab-org/ruby/gems/gitlab-omniauth-openid-connect)

I believe we'll need to replace this gem in due time, probably by https://github.com/omniauth/omniauth_openid_connect. 

### Expected behaviour

Gems should be up-to-date and maintained

### Actual behaviour

GitLab OmniAuth OpenID Connect will be archived soon

### Specifications

Current Mastodon

**Comment by ClearlyClaire** [comment]
See https://github.com/mastodon/mastodon/pull/23223
