### ISSUE TITLE
No <bdi> in notifications

### ISSUE THREAD

**Issue by tusooa** [mastodon/mastodon#23285]
### Steps to reproduce the problem

1. Change name to something with unicode right-to-left override
2. Create a notification from that user
3. Look
...
![image](https://user-images.githubusercontent.com/299873/215282135-2be33386-48bc-4fce-a705-4e5f561ce378.png)

### Expected behaviour

The RLO should only affect the name part

### Actual behaviour

The RLO affects the notification header

### Specifications

https://lily-is.land/infra/glitch-lily
Firefox 109.0, GNU/Linux, Wayland

**Comment by nightpool** [comment]
this has been around for a while and I think the consensus is that it's too funny to change.

**Comment by tusooa** [comment]
> this has been around for a while and I think the consensus is that it's too funny to change. Alternatively this is a bug that we fixed but your admin hasn't back ported to their fork yet. can you confirm that this is an issue on a vanilla version of mastodon?

i saw bdi tags on  mastodon4.
