### ISSUE TITLE
Receiving error 422 when trying to upload an image to Mastodon through the API.

### ISSUE THREAD

**Issue by dav1dxyz** [mastodon/mastodon#23287]
### Steps to reproduce the problem

1. Try uploading an image using the Fetch API in Node.JS
2. Expect 200/202 status code
3. Receive 422 status code instead.

### Expected behaviour

It should have made a POST request, like in curl

### Actual behaviour

There was no POST request, and it doesn't matter what the value of `body` is. I always get `{ error: "Validation failed: File can't be blank" }`.

### Detailed description

Here is the Node.JS code that I am working with
```js
require("dotenv").config()
const fs = require("fs");
const { format } = require("path");

let form = new FormData();
const filePath = __dirname + "/logo.jpg";
form.append("file", fs.createReadStream(filePath));

async function test() {
        const media = await fetch("https://mstdn.social/api/v1/media", {
        method: "POST",
        headers: {
            "Authorization": `Bearer ${process.env.MASTODON_TOKEN}`,
            "Content-Type": "multipart/form-data"
        },
        body: form
    });

    console.log(media.status)

    let data = await media.json();
    console.log(data);
}

test();
```
I would expect this code to work the same as when using cURL where I can receive a media_id[] for the image I have uploaded
```sh
curl -H "Authorization: Bearer TOKEN" -X POST -H "Content-Type: multipart/form-data" https://mstdn.social/api/v1/media --form file="@logo.jpg"
{"id":"197469466799235973"...
```
However, I do not receive an ID from the POST request. Instead, I receive this error
```sh
422
{ error: "Validation failed: File can't be blank" }
```

### Specifications

Mastodon v4.0.2
Node v19.5.0

**Comment by nametoolong** [comment]
You might want to try commenting out the `Content-Types` field in headers. That's because a user agent should encode form data automatically, which might result in parameters like `Content-Type: multipart/form-data; boundary=something`. Manually setting a content type breaks this encoding.

**Comment by dav1dxyz** [comment]
> You might want to try commenting out the `Content-Types` field in headers. That's because a user agent should encode form data automatically, which might result in parameters like `Content-Type: multipart/form-data; boundary=something`. Manually setting a content type breaks this encoding.
> 
> EDIT: See https://muffinman.io/blog/uploading-files-using-fetch-multipart-form-data/ for a complete explanation.

Thanks! I have managed to fix the code by removing the Content-Type and using this
```js
const filePath = __dirname + "/furry.jpg";
form.append("file", new Blob([await fs.readFileSync(filePath)]));
```

So now I have this for my whole code :)
```js
require("dotenv").config()
const fs = require("fs");
const { format } = require("path");

let form = new FormData();

const filePath = __dirname + "/furry.jpg";
form.append("file", new Blob([await fs.readFileSync(filePath)]));

async function test() {
        const media = await fetch("https://tech.lgbt/api/v2/media", {
        method: "POST",
        headers: {
            "Authorization": `Bearer ${process.env.MASTODON_TOKEN}`,
        },
        body: form
    });

    console.log(media.status)

    let data = await media.json();
    console.log(data);
}

console.log(form);
test();
```

**Comment by dav1dxyz** [comment]
Thanks, I have managed to fix my code by removing Content-Type and doing this
```js
const filePath = __dirname + "/logo.jpg";
form.append("file", new Blob([await fs.readFileSync(filePath)]));
```

This is my whole code now :)
```js
require("dotenv").config()
const fs = require("fs");
const { format } = require("path");

let form = new FormData();

const filePath = __dirname + "/logo.jpg";
form.append("file", new Blob([await fs.readFileSync(filePath)]));

async function test() {
        const media = await fetch("https://mstdn.social/api/v2/media", {
        method: "POST",
        headers: {
            "Authorization": `Bearer ${process.env.MASTODON_TOKEN}`,
        },
        body: form
    });

    console.log(media.status)

    let data = await media.json();
    console.log(data);
}

console.log(form);
test();
```
