### ISSUE TITLE
API Responses Are Cached

### ISSUE THREAD

**Issue by lexi-the-cute** [mastodon/mastodon#23343]
### Steps to reproduce the problem

So, this concerns `/api/v2/instance` on my single user (not officially checked as single user) instance. I noticed that both the browser and server seem to cache the response for this data. On my end, I fixed the browser side by hiding the proxy's Cache-Control header and replacing it with no-cache for all responses that start with `/api`. I however still have to wait about a minute or two before my profile metadata updates so clients can retrieve fresh data. I've determined this is from the server side as I see stale data when using curl to get the API response. I made sure to turn on "Development Mode" on Cloudflare so that Cloudflare doesn't break it by caching the data (I have a pagerule to disable caching anyway, but that's another bug for another time).

```nginx
proxy_hide_header Cache-Control;
add_header Cache-Control no-cache;
```

### Expected behaviour

I expect the api response to update immediately

### Actual behaviour

The api response takes a minute or two to update

### Specifications

Mastodon: Detached head of v4.1.0rc2
[DigitalOcean One Click Install Droplet](https://marketplace.digitalocean.com/apps/mastodon): Version 4.0.2, OS Ubuntu 20.04

**Comment by ClearlyClaire** [comment]
Some API endpoints are cached on purpose because they can be queried by a lot of various stuff while rarely changing. This is the case of `/api/v2/instance`
