### ISSUE TITLE
Add a new translation target for toki pona

### ISSUE THREAD

**Issue by Daenyth** [mastodon/mastodon#23372]
### Pitch

The toki pona language community has a mastodon server, it would be nice if we could translate it. We have multiple people already signed up to work on it; February is translation month in the community.

It requires @Gargron or @ClearlyClaire (I'm told) to add a new custom language target in crowdin, as described here: 

https://support.crowdin.com/changing-target-languages/#adding-custom-languages

I suggest using "tok" for the crowdin code and locale code, to match the ISO 636-3 code. The text direction is left-to-right. For "plural forms", use "other"

### Motivation

We'd like to translate the software for you! It would benefit our community. I sent a DM to the mastodon project admins on crowdin and they suggested I open a ticket here. I originally asked on Crowdin in November but it seems like people don't really follow that page (https://crowdin.com/project/mastodon/discussions/263).

This should only require about 5 minutes of effort on your side to open the door for us

**Comment by ClearlyClaire** [comment]
> It requires @Gargron or @ClearlyClaire (I'm told) to add a new custom language target in crowdin, as described here:

Only @Gargron can do that, as far as I can tell.

**Comment by casperdewith** [comment]
> For “plural forms”, use “other”.

I don’t know what the other options of this dropdown menu look like, but Toki Pona doesn’t have any plural forms. Singular and plural are the same. Pick whatever option fits that.

**Comment by Daenyth** [comment]
@ClearlyClaire can you ask @Gargron to look at it? It should only take a few minutes to do it, and we've been waiting for some kind of response since november

**Comment by Daenyth** [comment]
Any luck?

**Comment by Daenyth** [comment]
@ClearlyClaire are you or anyone else able to reach Gargron?
This should take literally 5 minutes or less to do

**Comment by ymndoseijin** [comment]
great how almost a year will go by without any kind of answer for something the community would promptly translate!

**Comment by gregdan3** [comment]
Bumping this. The Linku project at https://linku.la/ and https://discord.gg/Q5hszzaJzw would like to use Crowdin to manage translations of the dictionary definitions of Toki Pona words. For now I can add a custom language target, I suppose?

@Gargron ?

**Comment by Daenyth** [comment]
Obviously the people running the project don't read issues, but is there **anyone** reading this? Can none of the contributors reach an admin either?

**Comment by Daenyth** [comment]
Well it's translation month again and we'd still like to improve mastodon if you'd let us

**Comment by polijan** [comment]
Adding support for one ISO 636-3 code shouldn't take over a year.
There are Mastodon instances in Toki Pona. So, pleeease, add this!

**Comment by TheOnlyTails** [comment]
This is way overdue for something that'd be open for more than a year, and would quite literally only take 2 minutes to do this (as someone who's managing The Linku Project's own Crowdin instance, along with @gregdan3).

**Comment by Gargron** [comment]
Done.

**Comment by Daenyth** [comment]
Thank you!! We're super excited
