### ISSUE TITLE
tootctl account cull errors if instance URL is set to a private address

### ISSUE THREAD

**Issue by solarisfire** [mastodon/mastodon#23375]
### Steps to reproduce the problem

Running the tootctl account cull:

bin/tootctl accounts cull
Error processing 109721536099353935: Mastodon::PrivateNetworkAddressError

Looking up this userid in the DB I find:
https://social.manalejandro.com/users/96i9yhgc3f

Whoever owns this sub-domain has pointed it to 127.0.0.1

Non-authoritative answer:
Name:    social.manalejandro.com
Address:  127.0.0.1

This is probably an attempt to do something malicious, should mastodon be handling this error better?

### Expected behaviour

Cull the ccount

### Actual behaviour

Account is left in tact.

### Specifications

Mastodon 4.1.0rc2
Node v16.19.0
ruby 3.0.4p208

**Comment by ClearlyClaire** [comment]
> This is probably an attempt to do something malicious, should mastodon be handling this error better?

The error is precisely Mastodon not performing the request because it could be malicious. That being said, in the context of `tootctl accounts cull` it should probably either be ignored, or dealt as the account being down, not stop the whole process.

**Comment by solarisfire** [comment]
So if someone does this with the DNS for their instance, the account is never culled? Or has to be manually deleted with "tootctl accounts delete"?

Just wondering what the guidance is from an administrative perspective.

**Comment by ClearlyClaire** [comment]
Instances are supposed to cleanly shut down, or otherwise unambiguously return a 410. `tootctl accounts cull` is meant to be cautious to avoid nuking records because of an accidental and temporary misconfiguration. You can use `tootctl domains purge` if you know the domain is definitely retired.
