### ISSUE TITLE
Request for Kalmyk language in "Posting language" dropdown menu

### ISSUE THREAD

**Issue by Sanal** [mastodon/mastodon#23394]
### Pitch

Add [Kalmyk language](https://en.wikipedia.org/wiki/Kalmyk_Oirat) in "Posting language" dropdown menu.

English name | Name | ISO 639-3
-- | -- | --
Kalmyk | Хальмг келн | xal

### Motivation

Increasing language diversity, representation and visibility

**Comment by nschonni** [comment]
This would need to be added/requested on https://crowdin.com/project/mastodon
