### ISSUE TITLE
[Performance Issue] Loading home page is very slow (8 seconds +)

### ISSUE THREAD

**Issue by horaceyoung** [mastodon/mastodon#23412]
### Steps to reproduce the problem

1. try loading m.otter.homes
2. it takes 8+ seconds to load

### Expected behaviour

Site loads within seconds

### Actual behaviour

Loading is very slow :-(

### Detailed description

Hi amazing people of mastodon. I'm a new and a desperate host of a mastodon instance m.otter.homes with around 200 users. Things were all nice and well, but the loading time is driving me crazy. It usually takes 8 seconds + to load the homepage, and it's very slow to switch between pages (for example accessing the settings page). 
But once you're in, the interactions and timelines seemed fine.
I suspected Nginx could be a bottleneck but found no viable tuning methods. I also tried the scaling methods on the official documentation but to no avail. I use cloudflare as CDN
I thank you in advance if you can give me any insights on how I can improve the performance. 

Here is a screenshot of www.webpagetest.org analyzing my site, the first GET request to root is terribly slow:
![image](https://user-images.githubusercontent.com/32321396/216998389-28abb691-da80-42f9-83cc-183e6bd2f074.png)

As for the usage of the machine, I don't think it a bottleneck:
![image](https://user-images.githubusercontent.com/32321396/216999817-87b519f6-ede9-44c7-b24a-1fe67c7cf47e.png)

I set both of these to 100 but there seems to be no significant effects:
WEB_CONCURRENCY=100
MAX_THREADS=100

Here is the configuration of my Nginx:
```
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

upstream backend {
    server 127.0.0.1:3000 fail_timeout=0;
}

upstream streaming {
    server 127.0.0.1:4000 fail_timeout=0;
}

proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=CACHE:10m inactive=7d max_size=1g;

server {
  listen 80;
  listen [::]:80;
  server_name m.otter.homes;
  root /home/mastodon/live/public;
  location /.well-known/acme-challenge/ { allow all; }
  location / { return 301 https://$host$request_uri; }
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name m.otter.homes;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers HIGH:!MEDIUM:!LOW:!aNULL:!NULL:!SHA;
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;
  ssl_session_tickets off;

  ssl_certificate    /path/to/certificate;
  ssl_certificate_key /path/to/certificate/key;

  keepalive_timeout    70;
  sendfile             on;
  client_max_body_size 80m;

  root /home/mastodon/live/public;

  gzip on;
  gzip_disable "msie6";
  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;
  gzip_buffers 16 8k;
  gzip_http_version 1.1;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml image/x-icon;

  location / {
    try_files $uri @proxy;
  }

  location = /sw.js {
    add_header Cache-Control "public, max-age=604800, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/assets/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/avatars/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/emoji/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/headers/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/packs/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/shortcuts/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/sounds/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/system/ {
    add_header Cache-Control "public, max-age=2419200, immutable";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ^~ /api/v1/streaming {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Proxy "";
    proxy_pass http://streaming;
    proxy_buffering off;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    tcp_nodelay on;
  }

  location @proxy {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Proxy "";
    proxy_pass_header Server;
    proxy_pass http://backend;
    proxy_buffering on;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_cache CACHE;
    proxy_cache_valid 200 7d;
    proxy_cache_valid 410 24h;
    proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
    add_header X-Cached $upstream_cache_status;
    tcp_nodelay on;
  }

  error_page 404 500 501 502 503 504 /500.html;
}
```

### Specifications

Mastodon 4.1.0rc2+glitch
Ruby  3.0.4p208
PostgreSQL 13.9
Redis 6.0.16

Specs of my machine:
OS: Debian 11
CPU: 3cores
Memory: 4GB

**Comment by nametoolong** [comment]
It seems to me Nginx is not a bottleneck. A peek at HTTP response headers suggests most of the time is spent in Rails (`x-runtime: 2.242468`), while something like https://m.otter.homes/@otter/109617900147859327/embed is sigificantly faster.

Are you running development mode by accident? My best guess is that something messed up in the asset pipeline which can be fixed by recompiling the assets (`bundle exec rails assets:precompile`; ensure `config.assets.compile` is false in `config/environments/production.rb`). Another possible explanation is excessive Puma threads but insufficient database connections (check `DB_POOL` and max connections in PG config; 100 threads are certainly too many for Puma to handle).

A good way to debug such performance issues is to bypass CDN locally and read Puma logs. Each request line is appended by its instrumentation (`duration=x.xx view=x.xx db=x.xx`), so you can find out where the bottleneck is.

**Comment by horaceyoung** [comment]
> 

Thank you so much for your reply! I do remember setting `config.assets.compile` when I was trying to bypass a compile error when switching to glitch. Let me try your methods.

Thank you again!

**Comment by horaceyoung** [comment]
> It seems to me Nginx is not a bottleneck. A peek at HTTP response headers suggests most of the time is spent in Rails (`x-runtime: 2.242468`), while something like https://m.otter.homes/@otter/109617900147859327/embed is sigificantly faster.
> 
> Are you running development mode by accident? My best guess is that something messed up in the asset pipeline which can be fixed by recompiling the assets (`bundle exec rails assets:precompile`; ensure `config.assets.compile` is false in `config/environments/production.rb`). Another possible explanation is excessive Puma threads but insufficient database connections (check `DB_POOL` and max connections in PG config; 100 threads are certainly too many for Puma to handle).
> 
> A good way to debug such performance issues is to bypass CDN locally and read Puma logs. Each request line is appended by its instrumentation (`duration=x.xx view=x.xx db=x.xx`), so you can find out where the bottleneck is.

Hi, I ensured config.assets.compile is set to false but bundle exec rails assets:precompile didn't seem to recompile the assets? May I know which location contains the Puma logs? Thanks~
![image](https://user-images.githubusercontent.com/32321396/217249542-2bd8c6c8-0359-4463-b7de-f7287bc5d687.png)
![image](https://user-images.githubusercontent.com/32321396/217249598-addd98e9-023b-4419-9b60-5bc2c312aa65.png)

**Comment by horaceyoung** [comment]
I didn't set DB_POOL in .env.produnction separately. I read it's defaulted to MAX_THREADS. would you suggest using a smaller number for this?

**Comment by horaceyoung** [comment]
I feel so dumb now as it's solved. I was browsing webpacker.yml and found I set compile: false to compile: true, which disabled dependence on precompilation somehow (I know zero to nothing about ruby). @nametoolong thank you so much!
```production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true```

**Comment by nametoolong** [comment]
It is great your instance is working again😄

For your reference, Puma logs are most likely available via journalctl under `mastodon-web.service`.

MAX_THREADS=100 is harmful due to lock contention. WEB_CONCURRENCY=100 is overkill because each process consumes some amount of memory. I would configure 5 processes, 10 threads each (MAX_THREADS=10 WEB_CONCURRENCY=5) for a 200-user instance, YMMV. [This article by speedshop](https://www.speedshop.co/2017/10/12/appserver.html) explains the in-depths of these numbers.
