### ISSUE TITLE
Link previews can change link

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#23439]
### Steps to reproduce the problem

Consider this post

https://mastodon.social/@mcc/109824720437658276

In this post, I link to https://en.wikipedia.org/wiki/Black_swan#/media/File:Black_Swan_skeleton.jpg , the Wikipedia entry for Black Swan but there is an anchor with meaningful navigation information. The part after the # is interpreted by JavaScript and brings up effectively a sub-page within the page, lightboxing one photo (the swan skeleton). Mastodon displays the link and also displays a preview box.

### Expected behaviour

The link should go to https://en.wikipedia.org/wiki/Black_swan#/media/File:Black_Swan_skeleton.jpg and so should the preview box.

### Actual behaviour

The link goes to the expected location. However, the preview box goes to https://en.wikipedia.org/wiki/Black_swan , the page for a black swan. The part after the #, despite being significant, has been stripped away, and the preview link goes to a visibly different page than I was trying to link to. Because the URL is truncated, a reader who clicked on the preview box would have no way of realizing they were going to a different URL than the one I actually linked.

### Detailed description

Notes:

In this case, the post basically makes sense even with the altered URL because a reader would see text explaining you should look at the skeleton and scroll down until they find a skeleton. However, one could imagine cases where a post would not make any sense at all with the altered URL, or "make sense" misleadingly with altered meaning which could lead to harmful social misunderstandings.

It is possible that the # stripping is not being done by the server, but is being done on the Wikipedia side (by… OpenGraph !?). If this is the case I don't know what to do about it.

### Specifications

mastodon dot social on Chrome on Windows 10, "advanced" web interface

**Comment by daprice** [comment]
FWIW, I’ve also run into quite a few cases where the link preview took me to an error page or completely broken site, but the original link in the text worked fine.

**Comment by ClearlyClaire** [comment]
Sounds like a duplicate of #19538. The issue is basically that Mastodon searches for the “canonical” representation of the linked page to build the preview card and avoid duplication, then the preview card references that “canonical” link and not the original link (and the information of which original link lead to discovering the canonical link is not stored).

**Comment by mcclure** [comment]
You're correct, it is a dupe. Maybe that should be looked at given it's a year old and has 8 dupes now…
