### ISSUE TITLE
Admin-set Follow Recommendations are case-sensitive

### ISSUE THREAD

**Issue by mattcoxonline** [mastodon/mastodon#23472]
### Steps to reproduce the problem

1. Go to Admin Dashboard
2. Click Server Settings
3. Click Discovery (/admin/settings/discovery)
4. Add accounts to Follow Recommendations field

### Expected behaviour

The accounts added should show on the "For You" page

### Actual behaviour

The accounts added do not show on the "For You" page if the character casing doesn't exactly match

### Detailed description

When adding a list of usernames to the list of Follow Recommendations, the list is case-sensitive. If you do not add the exact same casing as the username, then the account does not show.

**Example:** 
Target username is a local user, full username is `@Matt@mastodon.instance`

- Adding `@matt` does not show this user
- Adding `@Matt` does show this user

I don't know if this is _intentional_, or not. But I can't think of any reason why `@matt@mastodon.instance` would pose any security risk, rather than forcing the user to type `@Matt@mastodon.instance`

I would expect that if the username matches, regardless of character case, that it just works.

`@matt` = `@Matt` = `@MATT` = `@MaTt `

### Specifications

Mastodon v4.0.2 (Admin Dashboard)
All browsers, all operating systems.

**Comment by ClearlyClaire** [comment]
It's definitely not intentional, in fact there is code that is aiming to make it case-insensitive. Investigating.
