### ISSUE TITLE
In the advanced UI the compose toot column gets confused if you delete a post you're editing 

### ISSUE THREAD

**Issue by guest20** [mastodon/mastodon#23496]
### Steps to reproduce the problem

1. log into a mastodon v4.0.2 via the web UI
2. head to preferences and `Enable advanced web interface`
3. find a previously-tooted toot
4. click `Edit` on that toot , note that it sets up the editor in the column with the `geting started` / `local` / `federated` / `log out` buttons 
5. click `Delete` on the toot you just clicked Edit on and confirm it. 
6. You're now editing a toot that doesn't exist, and if you click `Update`, a `"404 not found"` box will fly out from the left hand side. 

### Expected behaviour

The editor should have been reset to "compose new toot" mode.

### Actual behaviour

The editor stayed in "edit toot" mode, referring to a toot that no longer exists

### Detailed description

The UI is left in a goofy state if you delete the post you're currently editing. 

### Specifications

* mastodon v4.0.2
* Windows 10
* Chrome Version 109.0.5414.120 (Official Build) (64-bit)

**Comment by ClearlyClaire** [comment]
Fixed by https://github.com/mastodon/mastodon/pull/22126

**Comment by guest20** [comment]
hey @ClearlyClaire thanks for the fix! That's amazing! 

There's also a bug in the same place if you are composing a new toot and have attached an image (via pasting). If you click a reply button and say "Reply" when asked "Replying now will overwrite the message you are currently composing. Are you sure you want to proceed?" and the image stays attached to the now-reply editor.

**Comment by ClearlyClaire** [comment]
I was going to say this was a known and very minor UX inconsistency, but the implications are different when editing a post, since the media attachment is already attached and thus can't be reused on the reply. I will have a look.

**Comment by ClearlyClaire** [comment]
https://github.com/mastodon/mastodon/pull/23504
