### ISSUE TITLE
Unable to download archive

### ISSUE THREAD

**Issue by koehn** [mastodon/mastodon#23494]
### Steps to reproduce the problem

1. Request archive and wait for it to complete on your mastodon.social account
2. Click link to download 

### Expected behaviour

Archive should download

### Actual behaviour

503 response object too large

### Detailed description

https://files.mastodon.social/backups/dumps/000/012/735/original/archive-[redacted]-[redacted].tar.gz

```
Error 503 Response object too large

Response object too large

Error 54113

Details: cache-chi-klot8100174-CHI [1675977529](tel:1675977529) [3314140028](tel:3314140028)

Varnish cache server

```

### Specifications

Browser doesn’t matter. Account is on mastodon.social; suspect CDN configuration issue.

**Comment by renchap** [comment]
This should now be fixed, could you please retry downloading your archive?

**Comment by koehn** [comment]
It is fixed. Thanks!
