### ISSUE TITLE
CHANGELOG for 4.1.0rc3 incorrectly indicates support for ruby 3.1

### ISSUE THREAD

**Issue by danorton** [mastodon/mastodon#23497]
### Steps to reproduce the problem

1. Install using Ruby 3.1.3
2. run `tootctl accounts create admin --email admin@DOMAIN --confirmed --role Owner`

See Changelog at Dependencies: **Ruby: 2.7 to 3.1**
Should read **Ruby: 2.7 to 3.0**

### Expected behaviour

Create new account

### Actual behaviour

Error `'visit_Psych_Nodes_Alias': Unknown alias: defaults (Psych::BadAlias)`

### Detailed description

Ruby 3.1 is bundled with Psych4, but Mastodon wants Psych3

See:
 - #20333 , which is still pending, and
 - The underlying problem described at https://stackoverflow.com/questions/71191685/visit-psych-nodes-alias-unknown-alias-default-psychbadalias
 - Ruby issue https://bugs.ruby-lang.org/issues/17866

### Specifications

Mastodon 4.0.1
Ruby 3.1.3
Node JS v19.6.0

**Comment by ClearlyClaire** [comment]
oof, this mistake has been in all release notes for over a year despite the explicit `< 3.1.0` in the `Gemfile`

**Comment by ClearlyClaire** [comment]
Fixed all release notes

**Comment by danorton** [comment]
@ClearlyClaire looks like there might a similar problem for NodeJS, which doesn’t work with version > 16. I’m getting 403 errors with node v18.14.0. I’ll back out to node v16 to be sure. 

cf. #20968
