### ISSUE TITLE
Private reply by original poster publicly visible

### ISSUE THREAD

**Issue by FakePlasticDunk** [mastodon/mastodon#23509]
### Steps to reproduce the problem

This is pretty much impossible for me to reproduce, I'd need three different accounts, but hypothetically, if it's what it seems to be then
1. Person A publishes a post
2. Person B replies 'mentioned only' to Person A 
3. Person A replies 'mentioned only' to Person B
4. Person C sees the reply from step 3 

### Expected behaviour

I shouldn't be able to see the post

### Actual behaviour

I can see it

### Detailed description

I've noticed this a few times, that I can occasionally see 'mentioned only' posts - the common factor appears to be that they are replies by the original poster to 'mentioned only' replies to their original post. This is the case on the Android apps I use, and also the default web client on my instance universeodon.com. Screenshot of the latest attached.
![Screenshot_20230209-190043](https://user-images.githubusercontent.com/123900329/218172450-4c45a2ef-e12b-440b-bd11-29d6329f4dba.png)

### Specifications

Whatever universeodon.com is running
I see it in the basic Mastodon Android app and also in whatever default browser client universeodon.com has installed. Sorry I can't be more precise about this, I have limited resources to do more than I have.

**Comment by trwnh** [comment]
What is the indicator that this post is "mentioned users only"? The most likely explanation is that the post is actually followers-only.

**Comment by FakePlasticDunk** [comment]
That is possible, good point. I can't see the post he was replying to, so I suppose if that was set to 'followers only', then given I'm not a follower of that person that would be right. And then when Shaun replied to that it would default to 'followers' only. I'd only seen the greyed out crossed through boost icon for 'mentioned only' so drew a possibly incorrect conclusion.

Sent from Yahoo Mail on Android 
 
  On Fri, 10 Feb 2023 at 22:22, ***@***.***> wrote:   


What is the indicator that this post is "mentioned users only"? The most likely explanation is that the post is actually followers-only.

**Comment by FakePlasticDunk** [comment]
You're right - it belatedly occurred to me that if I tried to reply to the reply then it should be automatically set to 'followers only', so tried that and it was. Apologies for taking your time.
Cheers,Duncan 

Sent from Yahoo Mail on Android 
 
  On Fri, 10 Feb 2023 at 22:22, ***@***.***> wrote:   


What is the indicator that this post is "mentioned users only"? The most likely explanation is that the post is actually followers-only.

**Comment by FakePlasticDunk** [comment]
Post was set to 'followers only', so all is in order.
