### ISSUE TITLE
Support "-" characters in hashtags

### ISSUE THREAD

**Issue by khalidabuhakmeh** [mastodon/mastodon#23508]
### Pitch

Allow hashtags to recognize `-` characters for better readability of more complex hashtags.

Somewhat related to this issue as well: https://github.com/mastodon/mastodon/issues/15323

### Motivation

While folks could mash up words, deciphering longer hashtags can sometimes be challenging.  For example, in the technical space, you might want to use a dash, such as "#entity-framework-core" instead of "#entityFrameworkCore".

**Comment by BuZZ-dEE** [comment]
Duplicate of #20694
