### ISSUE TITLE
Can't login after moving Mastodon to another port

### ISSUE THREAD

**Issue by keith-v-smith** [mastodon/mastodon#23539]
### Steps to reproduce the problem

I wanted to move Mastodon's HTTPS port (away from 443) so that it could share a server also running Apache and already listening on the same IP address and port (but with different web server names), as the traffic load on server was very light. For example: mastodon.example.com and www.example.com on the same server and IP address.

I could change the nginx config easily enough, and mastodon did seem to work for an anonymous visitor, but all attempts at signing in fail: error page with "Security verification failed. Are you blocking cookies?".

Steps to reproduce problem:
1. In the nginx config file, change the server's https port to be something other than 443 - eg: 442.
2. reload nginx
3. browse to page, eg: https://mastodon.example.com:442/
4. click on 'Sign in', enter valid credentials, click 'LOG IN'

Note: Attempts to reset a password, etc., also fail.

### Expected behaviour

Login and validation should have succeeded

### Actual behaviour

Error page shown with "Security verification failed. Are you blocking cookies?" message.

### Specifications

Mastodon v4.0.2 and 4.1.0

Browsers attempted: Chrome, Firefox, and Safari.  Cookies were allowed.

**Comment by nightpool** [comment]
Since it's required for accessing your web server, you need to include the port in your `LOCAL_DOMAIN`. this will also break all servers that are currently federating with you

**Comment by keith-v-smith** [comment]
@nightpool OK, that makes sense.  I did check the documentation but don't recall anything about being about to specify a port on LOCAL_DOMAIN.  Two questions:

1. Is is the standard ':' notation? ie: <domain | IP>[:<port>]
2. Does the same also apply to WEB_DOMAIN?

And I acknowledge the point about breaking servers that are federating with you, this is obviously something that would only be done during initial setup.

**Comment by nightpool** [comment]
yes and yes, if web_domain is set (otherwise it defaults to local_domain)

**Comment by qinyj12** [comment]
I have done what you said: 

# .env.production
LOCAL_DOMAIN=example.com:4433

#nginx.conf
listen 8080
……
listen 4433

but still get 'Security verification failed. Are you blocking cookies'.So whats wrong with my configuration?
