### ISSUE TITLE
Add "Upgrade Notes" to 4.1.0 Change Log

### ISSUE THREAD

**Issue by snail-coupe** [mastodon/mastodon#23532]
### Pitch

Previous change logs have included summary information about upgrading a realease.  The current one for 4.1.0 omits this.

Adding this would make it easier for unfamiliar server admins to perfrom the upgrade, without having the extrapolate from previous change logs

### Motivation

I think many unfamilar server admin would benefit.  The documention on docs.joinmastodon.org still refer to upgrading somewhere around 3.1.2....

As a recent Mastodon covert this will be my first server upgrade and so I am extra cautious about breaking it.

**Comment by snail-coupe** [comment]
Ignore this, I'm 100% convinced it wasn't on the page I was viewing earlier, but is now....

**Comment by snail-coupe** [comment]
It doesn't appear on: https://github.com/mastodon/mastodon/releases
but does on: https://github.com/mastodon/mastodon/releases/tag/v4.1.0

**Comment by trwnh** [comment]
github has started truncating release notes if they are "too long". there is confusingly no indicator that the release notes continue. probably github should add a "read more" link, but there is nothing the mastodon project can do about this...

**Comment by snail-coupe** [comment]
Ah how confusing. Thanks for the explanation!
