### ISSUE TITLE
Group Notifications by Post

### ISSUE THREAD

**Issue by Justinzobel** [mastodon/mastodon#23540]
### Pitch

Group notifications by the post that generated them.

I posted something last night and I woke up to around 60 notifications generated by this post, a few follows, 40 odd likes and 20 retoots.

I'd like the notifications list to just show me this toot and say under it 20 retoots and 40 likes. This makes the list far more manageable.

The text "20 retoots" would open a small dialog box showing all the accounts that retooted it and the time. 
The text "40 likes" would do the same.

### Motivation

This would allow users to easily see the impact of their toots without having to scroll and read each notification to see what it's about.

**Comment by Cassolotl** [comment]
Agreed, and elk.zone handles this quite nicely. Anyway, this is a duplicate of *Group Consecutive, Non-Mention Notification Events #1483*, I think?

**Comment by Justinzobel** [comment]
Thanks @Cassolotl I looked but didn't find this one.
