### ISSUE TITLE
Notification mails should contain profile name

### ISSUE THREAD

**Issue by McPringle** [mastodon/mastodon#23549]
### Pitch

Please add the profile name to the notification mail so the recipient can identify the profile the notification is related to.

### Motivation

I manage several different profiles. One for my own, one for the *Java User Group Switzerland*, and one for the *Java aktuell* magazine. When I receive a notification mail, I can see what happened (like a new follower), but I don't know for which profile. It would be great, to mention the profile name in the mail address of the recipient. That would make it really easy to create filters in the mail client.

Actual: `mail@host.tld`
Expected: `Profilename <mail@host.tld>`

**Comment by Keisial** [comment]
The email addresses for each account will be different, so you actually have the ability to do the filters already, it would just be handy to change it from `To: javausergroup@example.ch` to `To: "Java User Group Switzerland" <javausergrupo@example.ch>`

**Comment by HeitorMC** [comment]
Hey, I would like to on this issue in the next days :)

**Comment by HeitorMC** [comment]
I've already made a change to cover this case, and it's already merged. I think we can close this issue :)

**Comment by McPringle** [comment]
Thank you very much for your work, @HeitorMC!
