### ISSUE TITLE
Memoriam account indicator is missing

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon#23570]
### Steps to reproduce the problem

1. Turn an account into a memoriam
2. See the account's profile page
3.
...

### Expected behaviour

Indicate the account is in the memoriam

### Actual behaviour

Nothing different

### Detailed description

Related - #19922 
After v4.0, public page is changed into PWA. And memorial is missing feature now

### Specifications

v4.1.0

**Comment by yuvalne** [comment]
Same issue here.

Mastodon | 4.1.0
Ruby | 3.0.4p208
PostgreSQL | 15.1
Redis | 7.0.5
