### ISSUE TITLE
Confusing "Get on Waitlist" language in signup flow

### ISSUE THREAD

**Issue by aphyr** [mastodon/mastodon#23575]
### Pitch

We have signups enabled on woof.group, but approve applications by hand. We usually do this in a few minutes to a few hours. However, every week or two we get questions from users about whether signups are open, or people telling each other on (e.g.) Facebook or Telegram that the instance is closed.

It turns out that people are going to the signup page, seeing a button that reads "get on waitlist", and assuming that means they'll have to wait days or months to get an account, rather than a few minutes or hours.

![Screenshot from 2023-02-13 12-33-24](https://user-images.githubusercontent.com/3748/218530354-f10043b0-7b7c-4006-9850-5420befb0f84.png)

I'd like to suggest changing this button to say something like "Apply for an account". If we want to make the waiting aspect clear, maybe we could add a sentence of text along the lines of "Moderators generally review applications within a few hours/days/..."?

If folks are open to this idea, I'm happy to open a PR for it.

### Motivation

People are assuming they won't be able to get accounts, and skipping the application process altogether. I think slightly different language could reduce confusion. :-)

**Comment by ClearlyClaire** [comment]
Fixed by #20850

**Comment by aphyr** [comment]
Oh, whoops! Pardon the dup, I did an issue search but not a PR search. :-)
