### ISSUE TITLE
Lack of options to moderate since 4.1

### ISSUE THREAD

**Issue by ghtux** [mastodon/mastodon#23596]
### Steps to reproduce the problem

Before version 4.1 it was possible to warn users (strikes). Under customized action, for example, no action could be selected and users could be warned with templates.

Now only one action can be executed directly. In some cases this is neither necessary nor appropriate. Warning presets seem pretty useless now.

### Expected behaviour

Options like in v4.0

### Actual behaviour

No strikes, no warnings. Only direct actions possible.

### Specifications

Mastodon v4.1

**Comment by ClearlyClaire** [comment]
I'm confused, you should still be able to select the “custom” option when handling reports:
![image](https://user-images.githubusercontent.com/384364/218777063-de432cae-77fc-41f4-a43b-5a98510a7643.png)
![image](https://user-images.githubusercontent.com/384364/218777210-ced2bf76-6277-435d-9581-e75446044f22.png)

And you should still be given a wide array of options when visiting an account:
![image](https://user-images.githubusercontent.com/384364/218777356-01f7a35e-c758-4e5b-9d4b-52b4fbe65d28.png)

**Comment by ghtux** [comment]
Ok, I'm just an idiot. The message was for an account that is not on our instance.

Sorry!!!!!
