### ISSUE TITLE
Discussion: Delay federate update for 15m/30m/1h?

### ISSUE THREAD

**Issue by guanyun-helo** [mastodon/mastodon#23619]
### Pitch

Add a option for Admin which could delay federate update.

### Motivation

The pull process often drain my instance's cpu, but if I can delay the process for 15min and give more cpu to local worker, my instance will run realy smooth.

**Comment by TheAlienKnight** [comment]
While this seems like a good idea at first, it quickly breaks apart- because all you are doing is delaying the inevitable. If you postpone Sidekiq's pull queue, you just end up with more than it has to pull later. It also means your users will end up with a delay on content, DMs, etc. You'll end up in a cycle of delays, which is worse than having some spikes of content. But I may be thinking of this in the wrong way.

**Comment by guanyun-helo** [comment]
The pull queue will be delayed, but when the cpu is free late at night, the pull queue will be executed.

**Comment by guanyun-helo** [comment]
> While this seems like a good idea at first, it quickly breaks apart- because all you are doing is delaying the inevitable. If you postpone Sidekiq's pull queue, you just end up with more than it has to pull later. It also means your users will end up with a delay on content, DMs, etc. You'll end up in a cycle of delays, which is worse than having some spikes of content. But I may be thinking of this in the wrong way.


The pull queue will be delayed, but when the cpu is free late at night, the pull queue will be executed.

**Comment by guanyun-helo** [comment]
I'm not sure there is a way to give a separate queue to handle the DMs from the federation, which is a higher priority.

**Comment by smiba** [comment]
I mean, you could split up your sidekiq processes and simply stop the process processing that queue when you want to pause it. 

But I fully agree with @TheAlienKnight that this sounds like a bad idea, without the pull queue your users will not receive their new content. It doesn't make sense to delay this until "late at night", people will be confused why their timeline is basically silent
