### ISSUE TITLE
Ruby 3.2.1 - mastodon-web 500 error on image upload

### ISSUE THREAD

**Issue by supernovae** [mastodon/mastodon#23639]
### Steps to reproduce the problem

Upgrade to ruby 3.2.1 

restart mastodon-web - most everything runs fine, but uploads cause an error 500 on page to scroll by real quick

### Expected behaviour

Images Uploaded fine

### Actual behaviour

Error 500 

### Detailed description

installed ruby 3.2.1

```
sudo apt install rustc

su - mastodon

cd ~/.rbenv
git pull
cd plugins/ruby-build
git pull

cd ~/.rbenv && src/configure && make -C src

RUBY_CONFIGURE_OPTS=--enable-yjit rbenv install 3.2.1

rbenv global 3.2.1
rbenv local 3.2.1

exit
su - mastodon

cd ~/live

git fetch upstream main (you will need to pull down main mastodon branch, i call it upstream)

bundle install && yarn install

RAILS_ENV=production bundle exec rails assets:precompile

systemctl restart mastodon-web (on web services)
systemctl restart mastodon-sidekiq* (for sidekiq instances)
```

Got error 500 on uploads

Reverted back to ruby 3.0.4 and uploads started working (no 500s)

I'm trying to see if i can get some logs, but i log so heavily that the error already rolled off (and i only keep a short period in loki)

### Specifications

Mastodon 4.1.0 main branch with ruby 3.2.1 support

Systemd on Ubunto 22.0.4

Objects stored on S3

Revered back to ruby 3.0.4 and restarted and uploads worked without an errors.

**Comment by Keisial** [comment]
Upgrade page says you shall run '`RAILS_ENV=production bundle exec rails db:migrate`, but is not listed in your steps above. A mismatch between the code and the db vesion would explain what you are seeing.
