### ISSUE TITLE
Cannot open admin dashboard on Elasticsearch error

### ISSUE THREAD

**Issue by Saiv46** [mastodon/mastodon#23663]
### Steps to reproduce the problem

1. Replace ElasticSearch with it's alternative ([Zinc](https://github.com/zinclabs/zincsearch))
2. Start Mastodon server
3. Go to `/admin/dashboard`

### Expected behaviour

Web should load, maybe with warming message about Elasticsearch connection error

### Actual behaviour

Web returns error 500

### Detailed description

From logs:
```
  
Elasticsearch::Transport::Transport::Errors::Found ([302] ):
  
app/lib/admin/system_check/elasticsearch_check.rb:26:in `running_version'
app/lib/admin/system_check/elasticsearch_check.rb:11:in `pass?'
app/lib/admin/system_check.rb:15:in `block in perform'
app/lib/admin/system_check.rb:12:in `each'
app/lib/admin/system_check.rb:12:in `each_with_object'
app/lib/admin/system_check.rb:12:in `perform'
app/controllers/admin/dashboard_controller.rb:10:in `index'
app/controllers/concerns/localized.rb:11:in `set_locale'
lib/mastodon/rack_middleware.rb:9:in `call'
```

Opened issue at https://github.com/toptal/chewy/issues/877

### Specifications

Mastodon 4.1.0
Ruby 3.0.4 (from latest Mastodon docker image)
Chewy: 7.2 (from Gemfile)
~~Elasticsearch~~ Zinc: 0.3.6

**Comment by mackuba** [comment]
@Saiv46 are you using zincsearch on your instance? Does it work well? Is it something that's at least unofficially supported?

**Comment by Saiv46** [comment]
> @Saiv46 are you using zincsearch on your instance? Does it work well? Is it something that's at least unofficially supported?

Since then [mastodon.ml](https://mastodon.ml/about) migrated to Docker containers and ZincSearch is no longer used. I don't know now
