### ISSUE TITLE
Updated 4.0.2 -> 4.1.0, precompiling assets failed, 'succeeded' on retry with --verbose, but no "Followed hashtags" context menu items

### ISSUE THREAD

**Issue by Twangist** [mastodon/mastodon#23675]
### Steps to reproduce the problem

1. Update Mastodon, as per instructions, including release notes
2. On performing last release-specific step, failure but no useful error message:

```
mastodon@muso:~/live$ RAILS_ENV=production bundle exec rails assets:precompile
yarn install v1.22.19
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
[4/6] Linking dependencies...
warning Workspaces can only be enabled in private projects.
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 15.54s.
Compiling...

Compilation failed:

mastodon@muso:~/live$ 
```

3. Ran it again with `--verbose` flag:

```
mastodon@muso:~/live$ RAILS_ENV=production bundle exec rails assets:precompile --verbose
yarn install v1.22.19
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
Done in 0.90s.
Everything's up-to-date. Nothing to do
mastodon@muso:~/live$ exit
```

4. Restarted mastodon services, went to site (https:/muso.social) -- no "Follow hashtags" menu item in either of the two places it's supposed to appear. Perhaps the menus weren't precompiled properly?

### Expected behaviour

I expected the precompilation step to work, and the menu items to appear.

### Actual behaviour

It didn't, they didn't, respectively.

### Detailed description

Please let me know what additional info you may need. Thanks in advance.

### Specifications

Mastodon 4.0.2 -> 4.1.0 (the release, not 'main')
Ruby had been and still is ruby 3.0.4p208

**Comment by ClearlyClaire** [comment]
Hi, this is most likely to you running out of RAM when building the assets, and webpack considering they were built anyway.

To get out of this, run `RAILS_ENV=production bundle exec rails assets:clobber`.

To avoid running out of memory again, you can try to apply the following change before rebuilding the assets:
```patch
diff --git a/config/webpack/production.js b/config/webpack/production.js
index 143a23b99e..af6d354cf8 100644
--- a/config/webpack/production.js
+++ b/config/webpack/production.js
@@ -13,6 +13,7 @@ const sharedConfig = require('./shared');
 const root = resolve(__dirname, '..', '..');
 
 module.exports = merge(sharedConfig, {
+  parallel: 1,
   mode: 'production',
   devtool: 'source-map',
   stats: 'normal',
```

**Comment by Twangist** [comment]
Thanks. So *that*'s how you retry asset building (clobber them, then try again).
The change to apply before rebuilding: this is output from "git diff", I take it, so save that to a file then `git apply` that file, yes?

**Comment by Twangist** [comment]
Regrettably, recompilation failed, *because of `parallel` — no such config option. However from the error message, I see there _is_ `parallelism`, which seems to be what you intended. The precompile command and its output:

```
mastodon@muso:~/live$ RAILS_ENV=production bundle exec rails assets:precompile --verbose
yarn install v1.22.19
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
Done in 0.96s.
I, [2023-02-21T07:56:46.795126 #1135662]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css
I, [2023-02-21T07:56:46.795987 #1135662]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css.gz
I, [2023-02-21T07:56:46.802113 #1135662]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css
I, [2023-02-21T07:56:46.802478 #1135662]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css.gz
I, [2023-02-21T07:56:46.806855 #1135662]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/favicon-db10337a56c45eb43c22ff5019546b520fa22c7281d4d385f235cbca67ed26bb.png
I, [2023-02-21T07:56:46.820790 #1135662]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-a60bf0a452ed064fef3594cf52a4c998712da7c76150f890f4eaa644f59671e4.js
I, [2023-02-21T07:56:46.821255 #1135662]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-a60bf0a452ed064fef3594cf52a4c998712da7c76150f890f4eaa644f59671e4.js.gz
I, [2023-02-21T07:56:46.831100 #1135662]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-c31338f656687c1d733bb0f48d40acd076e24060f3dcff83b34870e4ccc2789d.css
I, [2023-02-21T07:56:46.831439 #1135662]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-c31338f656687c1d733bb0f48d40acd076e24060f3dcff83b34870e4ccc2789d.css.gz
Compiling...
Compilation failed:
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'parallel'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack >= v2.0.0 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           parallel: …
         }
       })
     ]
```
<hr/>
I saved your diff script above to a file and did `git apply <that-script>` before the attempted recompilation. I'm not sure if I can just do the same thing, but adding 'ism' to the script -- is the 2nd, 'index' line still correct?

**Comment by ClearlyClaire** [comment]
Sorry, I may misremember the `parallel` option, I will try to find the correct one. In any case, I am pretty sure the root issue is that you are running out of memory, so in the meantime you could retry with a swap file or while stopping other processes.

**Comment by ClearlyClaire** [comment]
The correct option is `parallelism` not `parallel`, sorry about that. The patch would thus be:
```patch
diff --git a/config/webpack/production.js b/config/webpack/production.js
index 143a23b99e..af6d354cf8 100644
--- a/config/webpack/production.js
+++ b/config/webpack/production.js
@@ -13,6 +13,7 @@ const sharedConfig = require('./shared');
 const root = resolve(__dirname, '..', '..');
 
 module.exports = merge(sharedConfig, {
+  parallelism: 1,
   mode: 'production',
   devtool: 'source-map',
   stats: 'normal',
```

You'd apply it with `patch -p1` then paste the patch and press ctrl+D

**Comment by Twangist** [comment]
I think you're right that too little memory is the real issue. But I'll retry with the above first (`parallelism`), thanks.

**Comment by Twangist** [comment]
Um, nix. I clobbered the assets, performed the patch as you described but `patch` failed:

```
mastodon@muso:~/live$ patch -p1
diff --git a/config/webpack/production.js b/config/webpack/production.js
index 143a23b99e..af6d354cf8 100644
--- a/config/webpack/production.js
+++ b/config/webpack/production.js
@@ -13,6 +13,7 @@ const sharedConfig = require('./shared');
 const root = resolve(__dirname, '..', '..');
 
 module.exports = merge(sharedConfig, {
+  parallelism: 1,
   mode: 'production',
   devtool: 'source-map',
   stats: 'normal',
patching file config/webpack/production.js
Hunk #1 FAILED at 13.
1 out of 1 hunk FAILED -- saving rejects to file config/webpack/production.js.rej
```
<hr/>

Contents of `config/webpack/production.js.rej`:

```
--- config/webpack/production.js
+++ config/webpack/production.js
@@ -13,6 +13,7 @@ const sharedConfig = require('./shared');
 const root = resolve(__dirname, '..', '..');
 
 module.exports = merge(sharedConfig, {
+  parallelism: 1,
   mode: 'production',
   devtool: 'source-map',
   stats: 'normal',

```

**Comment by ClearlyClaire** [comment]
If you've already applied the previous patch, discard it (`git reset --hard v4.1.0`). Once you're down compiling the assets, I would discard (`git reset --hard v4.1.0`) or stash (`git stash`) the changes.

**Comment by Twangist** [comment]
Even that didn't work, so I stopped the mastodon-* services, did a hard repo reset to 4.1.0, ran the emended patch again, ran the recompilation step again, and even with just one process it completed successfully and in record time (slight j/k).
Thanks Claire. I'll close this issue.

**Comment by brindy** [comment]
@ClearlyClaire I've been on a long haul upgrade from v3.1.3 and finally got to v4.1.0 thanks to the solution here.  However, I have noticed webpack failing to compile a bunch of times as I've gone from one version to the next... 

1. I wonder if this was always the problem/solution?
2. Any reason why the `parallelism` flag couldn't be set by default?

Thanks!

**Comment by Twangist** [comment]
>     2. Any reason why the `parallelism` flag couldn't be set by default?

`parallelism` isn't a flag, it's a number: max # of modules that can be compiled in parallel. Setting it to 1 says _do nothing in parallel_, to limit RAM usage at the cost of taking more time. So, not a good default!

**Comment by brindy** [comment]
Oh, that makes sense!  Thanks for the clarification.
