### ISSUE TITLE
When translating upon clicking the Translate link, only toot text translates, not title, alternative text or aria-label

### ISSUE THREAD

**Issue by ChasBelov** [mastodon/mastodon#23676]
### Steps to reproduce the problem

1. Visit https://ohai.social in English
2. Go to https://ohai.social/@fifischwarz@waag.social/109881292811866578
3. Click Translate

Expected and actual results: Toot is translated from Dutch into English

4. Hover over image

Expected result: Title text is translated from Dutch into English

Actual result: Title text remains in Dutch.

5. Right-click the image
6. Click inspect.

Expected result: title and alternative attributes are translated from Nederlands into English

Actual result: title and alternative attributes remain in Dutch.

7. In the inspector base, click the "a" tag immediately to the left of the "img" tag
    then
    div.media-gallery_item.standalone
    then
    div.media-gallery
    then
    div.detailed-status.detailed-status-publ...
    then
    div
    then 
    div.focusable.detailed-status_wrapper

Expected result: aria-label attribute on div.focusable.detailed-status_wrapper is translated

Actual result: aria-label attribute on div.focusable.detailed-status_wrapper remains in Dutch.

### Expected behaviour

Alternative text gets translated along with the toot

### Actual behaviour

Only the toot gets translated

### Detailed description

Mastodon has added the ability to translate toots inline at the click of a Translate link. However, only the toot gets translated, not the alternative text. This makes the alternative text unavailable to people who need translation in order to understand the content.

### Specifications

Mastodon 4.1.0
macOS 13.2.1
Firefox 110.0

### Screen prints 

I am unable to attach screen prints. I get the message "Something went really wrong, and we can't process that file." after multiple tries.

**Comment by renchap** [comment]
Fixed in #24175
