### ISSUE TITLE
Add Cantonese to the supported languages in the toot language drop-down

### ISSUE THREAD

**Issue by ChasBelov** [mastodon/mastodon#23700]
### Pitch

Colloquial Cantonese needs to be translated and pronounced differently from Mandarin and needs its own entry in the language drop-down, producing either a lang="yue" or lang="zh-YUE" attribute in the enclosing tag. 

Discussion: WebAIM reports suggest that three-letter language codes such as "yue" are not well supported by screen readers, so "zh-YUE" is likely the better choice. That said, I have not tested this.

### Motivation

People who engage socially using colloquial Cantonese characters would be able to mark their content correctly for language (and hopefully would begin doing so, since that would improve toot accessibility for colloquial Cantonese toots).

**Comment by ryliejamesthomas** [comment]
There's some discussion about this already in https://github.com/mastodon/mastodon/issues/18538, you may like to add your comment there.

**Comment by ChasBelov** [comment]
Closing as duplicate of #18538.

**Comment by ChasBelov** [comment]
Duplicate of #18538
