### ISSUE TITLE
WEB_CONCURRENCY at zero does not stop worker spawning

### ISSUE THREAD

**Issue by tabletcorry** [mastodon/mastodon#23714]
### Steps to reproduce the problem

1. Set `WEB_CONCURRENCY` to `0` in `.env.production`
2. Restart web process

### Expected behaviour

Puma should start as a single-process server

### Actual behaviour

Puma starts two child workers

### Detailed description

`WEB_CONCURRENCY` is supposed to define the number of child worker processes spawned by Puma. By default it is two.

When set to zero, it should cause Puma to spawn no children, running everything in a single process. But instead it spawns two children.

Spawning Puma as a single process grants considerable memory savings for smaller instances.

My patch fix is to comment out the `workers` from the config:

```diff
diff --git a/config/puma.rb b/config/puma.rb
index e59295445..b48c5491d 100644
--- a/config/puma.rb
+++ b/config/puma.rb
@@ -11,7 +11,8 @@ else
 end
 
 environment ENV.fetch('RAILS_ENV') { 'development' }
-workers     ENV.fetch('WEB_CONCURRENCY') { 2 }.to_i
+
+#workers     ENV.fetch('WEB_CONCURRENCY') { 2 }.to_i
 
 preload_app!

```

### Specifications

Mastodon 4.1.0
Ubuntu 22.04

**Comment by 33b5e5** [comment]
I dug into this because I was curious. My first thought was just use `WEB_CONCURRENCY=1`, but that still spawns 1 child worker. Whereas Puma itself supports `WEB_CONCURRENCY=0` as a single-process mode with no workers, as pointed out here.

See: https://puma.io/puma/Puma/DSL.html and search for `#workers(count)`

Agree it would be nice to support `WEB_CONCURRENCY=0`

**Comment by tabletcorry** [comment]
Ah, I am actually writing up my revised findings on this right now!

It turns out the issue is that you cannot set `WEB_CONCURRENCY` in `.env.production` and it _must_ be done in the system config (or wherever else you set your environment for Puma spawning).

So long as the environment variable is set, zero does work and runs Puma as a single process.
