### ISSUE TITLE
WebSocket/Streaming API throwing 401 errors with ERR! error: SSL required

### ISSUE THREAD

**Issue by seano-vs** [mastodon/mastodon#23716]
### Steps to reproduce the problem

My infrastructure is extremely similar to the vanilla [mastodon/chart](https://github.com/mastodon/chart) setup. So, there is a dedicated pod running mastodon-streaming with the following configmap/Envs:

```json
{
	"AWS_ACCESS_KEY_ID": "",
	"AWS_SECRET_ACCESS_KEY": "",
	"DB_HOST": "crunchy-mastodon-pgbouncer",
	"DB_NAME": "mastodon_production",
	"DB_POOL": "25",
	"DB_PORT": "5432",
	"DB_USER": "mastodon",
	"DEFAULT_LOCALE": "en",
	"ES_ENABLED": "true",
	"ES_HOST": "mastodon-elasticsearch-master-hl",
	"ES_PORT": "9200",
	"LIMITED_FEDERATION_MODE": "true",
	"LOCAL_DOMAIN": "dev.whatever",
	"MALLOC_ARENA_MAX": "2",
	"NODE_ENV": "production",
	"RAILS_ENV": "production",
	"REDIS_HOST": "mastodon-redis-master",
	"REDIS_PORT": "6379",
	"S3_ALIAS_HOST": "cdn-dev.whatever",
	"S3_BUCKET": "mastodev",
	"S3_ENABLED": "true",
	"S3_ENDPOINT": "",
	"S3_PERMISSION": "private",
	"S3_PROTOCOL": "https",
	"S3_REGION": "us-east-1",
	"SMTP_FROM_ADDRESS": "notifications@dev.whatever",
	"SMTP_LOGIN": "",
	"SMTP_PASSWORD": "",
	"SMTP_PORT": "587",
	"SMTP_SERVER": "e",
	"STREAMING_API_BASE_URL": "wss://streaming-dev.whatever",
	"STREAMING_CLUSTER_NUM": "1",
	"TRUSTED_PROXY_IP": "CLOUDFLARED_TUNNEL_IP"
}
```

I use the [cloudflared tunnel](https://github.com/cloudflare/cloudflared) in between my k8s cluster and the internet to terminate tls and other cloudlfare-y crap.

The pod seems to start just fine, without any issues and passes all health checks. I can curl the `http://{pod hostname}:4000/api/v1/streaming/health` and it works, and I can also reach the public `http://streaming-dev.whatever/api/v1/streaming/health` without problem. 

However.

Whenever I actually try to *use* the websocket by browsing feeds, I get 401 errors client-side:

![image](https://user-images.githubusercontent.com/64788907/219909937-1117f045-9b23-4bac-ae15-c07f1cf7d434.png)

...and `ERR! error: SSL required` errors on the server-side (on the mastodon-streaming pod).

![image](https://user-images.githubusercontent.com/64788907/219909960-846c0a52-a2d5-48af-a3a5-40a88050c097.png)

### Expected behaviour

the streaming websocket works

### Actual behaviour

it don't

### Detailed description

I'm really confused how to address the server-side `ERR! error: SSL required` errors. The only port it's listening on, `4000`, naturally won't communicate via https/wss and only responds to plaintext. However, the more I look into [prior issues](https://blog.vyvojari.dev/mastodon-behind-a-reverse-proxy-without-ssl-https/) around this, it seems like there is a [complicated](https://discourse.joinmastodon.org/t/mastodon-on-http-no-https/3020/3) [history](https://github.com/mastodon/mastodon/issues/21139) around forcing TLS on the application layer, and I'm unsure how to proceed. 

Also, everything else (see: web, sidekiq) as far as I can tell has been working fine for months. A quick issue search has shown that other folks have faced some similar enough issues but trying their methods haven't helped much. I've tried:

- Cutting out cloudflare completely
- Using an nginx proxy with the [suggested config](https://github.com/mastodon/mastodon/blob/main/dist/nginx.conf)
- rebuilding everything
- not using a dedicated subdomain 

And they have all yielded similar results. 

### Specifications

Mastodon 4.0.2

Ruby 3.0.4p208

Postgres 14.2

Redis 6.2.7

**Comment by seano-vs** [comment]
I figured it out. 

[This thread](https://discourse.joinmastodon.org/t/not-getting-new-messages-unless-i-reload-the-page/3805) is the only one I could find that was even remotely close to my issue, and they were talking about pg connection certs. I was in denial that this was the case, until I googled around the error some more and realized other people were facing this error when using pgbouncer.

Well, the certificate in my pgbouncer is definitely self-signed- and I [followed the instructions here](https://stackoverflow.com/questions/45088006/nodejs-error-self-signed-certificate-in-certificate-chain) to add this env: `NODE_TLS_REJECT_UNAUTHORIZED='0'` as well as `DB_SSLMODE=require`. And now everything is working. I've been tearing my hair out over this for a while.

Moral of this story: the node server that runs the streaming api cares a lot about certificate verification, but nothing else does.

**Comment by sinoru** [comment]
I think the `NODE_TLS_REJECT_UNAUTHORIZED` is temporary solution, and this issue should be addressed.
Actually, there are some tries to resolve this issue. https://github.com/mastodon/mastodon/pull/21431

**Comment by zeeZ** [comment]
> I think the `NODE_TLS_REJECT_UNAUTHORIZED` is temporary solution, and this issue should be addressed. Actually, there are some tries to resolve this issue. #21431

You'd have to set `DB_SSLMODE=no-verify` for the streaming API and `DB_SSLMODE=require` for any other sane clients with that change. `NODE_TLS_REJECT_UNAUTHORIZED` on the streaming server, *as far as I can tell*, only affects the database and redis connections, so it mght be fine.

See also #23716
