### ISSUE TITLE
Ruby parser error

### ISSUE THREAD

**Issue by jasonkodish** [mastodon/mastodon#23710]
### Steps to reproduce the problem

|After upgrading to Mastodon 4.1 when running any tootctl command (or at least media commands so far) this message comes up:

 parser/current is loading parser/ruby30, which recognizes 3.0.5-compliant syntax, but you are running 3.0.4
Ruby is 3.0.4 on the server. This did not happen on the test server I set up..just the production one.

### Expected behaviour

that error shouldn't come up

### Actual behaviour

The error shows up, but doesn't seem to affect anything. Appears to be just a warning

### Detailed description

I did notice when upgrading there was a gemlock file issue when doing the git fetch. I was able to resolve it by using the following commands:

git checkout Gemfile.lock

and

git --reset --hard HEAD

I don't know if this has anything to do with the ruby issue.

If the solution is up upgrade ruby, could this please be included in the upgrade instructions?
For now this doesn't appear to be a critical issue or have any effect but it could be an issue in later upgrades.

Many of us are new to this. I don't know how to update ruby without breaking thins.

### Specifications

Mastodon v4.1.0
Ruby 3.0.4p208
PostgreSQL15.1
Redis 5.0.7

**Comment by mjankowski** [comment]
FWIW, this error is effectively just a warning and is almost definitely not indicating an actual problem.

The versions of the `parser` gem map to specific ruby versions, and when you have a disconnect between the ruby being used and ruby targeted by a given version of the parser gem this warning comes up.

You can probably ignore it, but if you wanted to address it, then yes - upgrading to ruby 3.0.5 would likely make this error go away and likely not break anything else in the process.

Do your test and production servers have different ruby versions?

**Comment by jasonkodish** [comment]
Interestingly enough, I did end up upgrading the ruby version on the tallest server but for some reason the mastodon on there doesn't pick up that its 3.0.5 so I'm probably doing something wrong. The servers are all VMs with snapshots so Incan ropl back when neededSent from my Galaxy
-------- Original message --------From: Matt Jankowski ***@***.***> Date: 2023-02-20  11:12 a.m.  (GMT-07:00) To: mastodon/mastodon ***@***.***> Cc: jasonkodish ***@***.***>, Author ***@***.***> Subject: Re: [mastodon/mastodon] Ruby parser error (Issue #23710) 
FWIW, this error is effectively just a warning and is almost definitely not indicating an actual problem.
The versions of the parser gem map to specific ruby versions, and when you have a disconnect between the ruby being used and ruby targeted by a given version of the parser gem this warning comes up.
You can probably ignore it, but if you wanted to address it, then yes - upgrading to ruby 3.0.5 would likely make this error go away and likely not break anything else in the process.
Do your test and production servers have different ruby versions?

**Comment by jasonkodish** [comment]
Strangely enough the ruby versions are the same.Sent from my Galaxy
-------- Original message --------From: Matt Jankowski ***@***.***> Date: 2023-02-20  11:12 a.m.  (GMT-07:00) To: mastodon/mastodon ***@***.***> Cc: jasonkodish ***@***.***>, Author ***@***.***> Subject: Re: [mastodon/mastodon] Ruby parser error (Issue #23710) 
FWIW, this error is effectively just a warning and is almost definitely not indicating an actual problem.
The versions of the parser gem map to specific ruby versions, and when you have a disconnect between the ruby being used and ruby targeted by a given version of the parser gem this warning comes up.
You can probably ignore it, but if you wanted to address it, then yes - upgrading to ruby 3.0.5 would likely make this error go away and likely not break anything else in the process.
Do your test and production servers have different ruby versions?

**Comment by mjankowski** [comment]
Closing on assumption that this is either a non-issue, or was from a ruby version mismatch that has been resolved.
