### ISSUE TITLE
Show Moderation + Administration Quick Access on /home

### ISSUE THREAD

**Issue by mattcoxonline** [mastodon/mastodon#23747]
### Pitch

Whether you are a moderator or administrator, it can take up to 3 or 4 clicks to see whether there are any pending accounts that need approval. And if you do that journey, the answer could be that there are 0 things that need your attention.

I propose bringing the 'Quick Access' options from the Admin Dashboard to the /home page of Mastodon.

<img width="1512" alt="A mockup of the Quick Access panel in the bottom left corner of the Mastodon home screen" src="https://user-images.githubusercontent.com/673542/220061902-113b1573-e240-46fd-b8e8-95366ab075e0.png">

This mockup displays the concept in the most simplest form. I'm sure it it would suffice as a first version, but also sure it can be refined and some consideration should be put into place for how this works on mobile and accessibility measures.

### Motivation

Why is this needed?

- It reduces the journey for a user to get to the admin / moderation controls
- Has the possibility to increase the efficiency of moderation on an instance
- Gives an overview of how effectively the instance is moderated

Who would benefit from it?

- Admins and moderators
- Possibly anyone with a pending report / approval

**Comment by ThisIsMissEm** [comment]
@mattcoxonline hey, what do you think of the changes in #24838? — it's not exactly the mockup you had, but does at least give quicker access to the moderation reports and admin dashboard.

**Comment by ThisIsMissEm** [comment]
Whilst we probably can't add a "pending count" thing, since this data isn't available via the API, I have #24838 which adds quick links to the Moderation and Administration sections.

I think since this was reported, we also added notifications of new reports and new pending accounts, so you'll see these in your notifications tab.

**Comment by ErikLentz** [comment]
> [@mattcoxonline](https://github.com/mattcoxonline) hey, what do you think of the changes in [#24838](https://github.com/mastodon/mastodon/pull/24838)? — it's not exactly the mockup you had, but does at least give quicker access to the moderation reports and admin dashboard.

I don't think this accomplishes the goal. Having slightly easier access to these dashboards is OK, but the desire is a call to action. Right now, an instance admin receives no notifications within the Mastodon UI that there is a pending user activation, pending report, etc. They need to be monitoring their email client, which seems a bit byzantine.

**Comment by ThisIsMissEm** [comment]
@ErikLentz you might be filtering out those notifications because there are notifications for admin stuff & we can add more. ![Image](https://github.com/user-attachments/assets/981c5368-5966-42d5-9fab-033653f26a6e)

**Comment by mattcoxonline** [comment]
> [@mattcoxonline](https://github.com/mattcoxonline) hey, what do you think of the changes in [#24838](https://github.com/mastodon/mastodon/pull/24838)? — it's not exactly the mockup you had, but does at least give quicker access to the moderation reports and admin dashboard.

Sorry for the delay in responding, @ThisIsMissEm. I know you wrote this reply a while ago, but I somehow missed it. One day, I would love to see a count of the number of open moderation issues or pending membership approvals alongside the menu items in future, but I understand that if that data is not available to call, it's not possible for now. 

Thanks for making the changes you did! I noticed them in the newer versions of the software on my server and I really appreciate the quick links to the Admin + Moderation controls. 👏

I'll close this issue and a new one can be raised to pull in the notification count in future.
