### ISSUE TITLE
`tootctl` fails with an empty database password

### ISSUE THREAD

**Issue by RyanGibb** [mastodon/mastodon#23758]
### Steps to reproduce the problem

When trying to run a command that access the database, e.g.:
```
sudo -u mastodon RAILS_ENV=production OTP_SECRET=$(sudo cat /var/lib/mastodon/secrets/otp-secret) SECRET_KEY_BASE=$(sudo cat /var/lib/mastodon/secrets/secret-key-base) VAPID_PRIVATE_KEY=$(sudo cat /var/lib/mastodon/secrets/vapid-private-key) VAPID_PUBLIC_KEY=$(sudo cat /var/lib/mastodon/secrets/vapid-public-key) DB_PASS= DB_NAME=mastodon /nix/var/nix/profiles/system/etc/profiles/per-user/mastodon/bin/tootctl media remove
```

I get the error:
```
/nix/store/gxzdgbn3zmhb39a6myvfj1g1khx0w134-mastodon-gems-4.1.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client': connection to server at "::1", port 5432 failed: fe_sendauth: no password supplied (ActiveRecord::ConnectionNotEstablished)
```

Setting a database password with:
```
sudo -u postgres psql --command="ALTER USER mastodon WITH PASSWORD 'pass';"
```

And rerunning the failing command with `DB_PASS=pass` then works.

This is also the case with `DB_PASS=""`.

### Expected behaviour

It should have picked up that there is no database password.

### Actual behaviour

It failed with an error saying no password was supplied.

### Specifications

Mastodon v4.1.0

**Comment by mjankowski** [comment]
Is the issue here that the app works fine but tootctl fails ... or that they both fail with empty password?

**Comment by RyanGibb** [comment]
Hmm, I'm not sure, I opened this two years ago. Happy to close if it's not reproducible on the latest release.

**Comment by mjankowski** [comment]
Sounds good ... it's either resolved, or contingent on some setting I don't have.

If anyone else hits this on latest, please reopen!

**Comment by LordGrimmauld** [comment]
Still an issue

**Comment by mjankowski** [comment]
> Still an issue

Can you confirm version details (and maybe general host/env description) of what the failure looks like?
