### ISSUE TITLE
Cannot attach .webp's

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#23781]
### Steps to reproduce the problem

I download a webp of a guy white water rafting from https://developers.google.com/speed/webp/gallery1 and I attempt to attach it to a post on Mastodon.

### Expected behaviour

It uploads.

### Actual behaviour

"500 error processing thumbnail for uploaded media"

### Detailed description

If you don't support webp you should at least have a error message that cites the format instead of a weird message about thumbnails.

An [older issue](https://github.com/mastodon/mastodon/issues/21492) complains that webps are not allowed in avatars and that issue specifically says you can attach them to "toots". So apparently this worked at one time.

### Specifications

Chrome for Windows 10
mastodon dot social running v4.1.0rc3
Also reproduced the problem via the API with Tusky for Android

**Comment by mcclure** [comment]
Originally found out about this from [this user reporting a bug on Tusky](https://mastodon.social/@andreasio/109885264099384153)

**Comment by renchap** [comment]
There are 2 things here:
- mastodon.social is running an older `imagemagick version that is not supporting webp`. This should change very soon and WebP should be processed correctly
- the error message could be improved if an image format is not supported

**Comment by sdubinsky** [comment]
Imagemagick relies on ffmpeg, and ffmpeg does not currently handle processing animated .webp files.  It's an open bug: https://trac.ffmpeg.org/ticket/4907

**Comment by ClearlyClaire** [comment]
This seems to have been fixed, with mastodon.social having been updated.

**Comment by mcclure** [comment]
Great news!

Unfortunately… #25007 :)

**Comment by ClearlyClaire** [comment]
:weary:
