### ISSUE TITLE
Following followers is failing

### ISSUE THREAD

**Issue by Servelan** [mastodon/mastodon#23784]
### Steps to reproduce the problem

1.  Go to follows/followers
2.  Click on a bunch of people who follow you but that you haven't yet followed back.

### Expected behaviour

I'm following all those people whose profile I checked and am pleased

### Actual behaviour

Angry Mastodon 'an error has occured' page appears and I am not pleased

### Detailed description

When I click on one or two and get Angry Mastodon Page, I can go and look at the account that failed to create a mutual relationship and follow manually, but then why have a page to do this with nifty  check boxes en masse in the first place?  Issue is the same on Firefox and Chrome, so not a browser-specific issue.  

### Specifications

Newsie.social is all I got for ya.

**Comment by ClearlyClaire** [comment]
I think this may happen because one of your followers has moved accounts and Mastodon does not allow you following someone who has moved accounts. This triggers an error that is not properly handled. I will try to improve the error handling.
