### ISSUE TITLE
Hashtag search not working properly if hashtag contains a german umlaut

### ISSUE THREAD

**Issue by sozialwelten** [mastodon/mastodon#23785]
### Steps to reproduce the problem

1. Use the Mastodon Search to look for a term containing a German Umlaut (e.g. "ökologisch", "möglichkeit", "köln")
2. Look through the resulting posts
3. Realize that there should be a lot more search results and a lot of postings are not being displayed

### Expected behaviour

All the postings that are connected with the instance containing the hashtag with the umlaut should be found

### Actual behaviour

Only some postings or none at all containing the hashtag with the umlaut are found

### Detailed description

Since the update from 3.x to 4.x it was changed how [hashtags are being normalized](https://github.com/mastodon/mastodon/pull/18795). I assume that as an unintended result, now a lot of postings are not being found anymore when using the integrated search function, while the specific term contains a German Umlaut. As direct proof that a significant amount of search results are not being displayed please see my [screenshot that I have posted here](https://github.com/mastodon/mastodon/pull/18795#issuecomment-1429412879). My Mastodon profile clearly states that I have used the hashtag "möglichkeit" 242 times yet no posting at all is being found when I search for the term "möglichkeit".

### Specifications

Mastodon 4.0.0
Mastodon 4.0.1
Mastodon 4.0.2
Mastodon 4.1.0

**Comment by sozialwelten** [comment]
Some additional information after some more experimentation:

I do not know if this is consistent, but it seems to me that postings which contain hashtags with German Umlaute that have been written after the update from Mastodon 3.x to 4.x, can be found more often than postings containing hashtags with German Umlaute that have been written before the Mastodon 3.x to 4.x update.

An example is the search for the hashtag "professionalitätsmagie"

As a result of the search from my instance I get one search result.
Search URL: https://ifwo.eu/tags/Professionalit%C3%A4tsmagie
Search results in one posting: https://ifwo.eu/@u4/109381523555962038

My postings are not available in the search result. Since I know that I have used this hashtag before I was able to find at least one of my postings containing the exact same hashtag "professionalitätsmagie" which has not been part of the search results.

Posting that does not show up in search results while it definitely should: https://ifwo.eu/@sozialwelten/103261155438374200

When I click the hashtag "professionalitätsmagie" from the posting that did not show up in the search results I again only get the results that showed up in the search results but again not the posting from which I clicked the hashtag.

Since the posting that doesn't show up was written before Mastodon 4.x and since newer postings seem to be found I think that the bug might mostly apply to postings with hashtags that have been written before 4.x.

**Comment by jsgoldstein** [comment]
@sozialwelten Are you still having a problem here?

I think https://github.com/mastodon/mastodon/pull/18808 should have fixed the problem from https://github.com/mastodon/mastodon/pull/18795.

When I search for "professionalitätsmagie" and scroll down far enough I eventually find the posts you referred to. This is true from both https://ifwo.eu/tags/professionalit%C3%A4tsmagie and https://mastodon.social/tags/professionalit%C3%A4tsmagie

For example:
<img width="904" alt="Screenshot 2023-12-04 at 10 35 14 AM" src="https://github.com/mastodon/mastodon/assets/15234688/a5e1957f-39f8-40aa-b369-11180b2f6fea">

**Comment by renchap** [comment]
Closing as this seems to be resolved. If not, please re-open and add more details so we can investigate.

**Comment by sozialwelten** [comment]
@jsgoldstein The result is an edited toot. The toots with German Umlaute that have been posted before 2022 (before 4.0.0) can only be found in the described way if the toot has been edited.

> Closing as this seems to be resolved. If not, please re-open and add more details so we can investigate.

Not fixed, but I don't care anymore. Would have been nice if you had given me at least 24 hours to respond before closing.
