### ISSUE TITLE
Authentication history: shows my IP as 127.0.0.1

### ISSUE THREAD

**Issue by Me4Linux** [mastodon/mastodon#23807]
### Steps to reproduce the problem

1.Login: mastodon.online
2. Go to "Preferences/Account".
3. "Sessions" and "View authentication history of your account" show my Login-IP as 127.0.0.1 since Feb. 17th 2023.

### Expected behaviour

Was expecting to see my IP instead of localhost.

### Actual behaviour

127.0.0.1 is shown as IP from where I logged in.

### Specifications

Mastodon 4.1.0
Firefox 102 ESR and 110, Debian 11
Fennec 110, Android 12
Logged in from different network connections.

**Comment by renchap** [comment]
Thanks for the report @Me4Linux, a recent change in our infrastructure created this issue.

It should now be fixed!
