### ISSUE TITLE
JSON view of hashtags broken in 4.1.0

### ISSUE THREAD

**Issue by sl1txdvd** [mastodon/mastodon#23846]
### Steps to reproduce the problem

1. Open  https://mastodon.social/tags/johnmastodon.json 

### Expected behaviour

JSON of toots should appear

### Actual behaviour

No JSON of toots :(

### Detailed description

There used to be a JSON view of hashtags. It seems to be broken in 4.1.0

1. Open 4.1.0 and see there are no toots: https://mastodon.social/tags/johnmastodon.json 
2. Check 4.0.2 and find toots: https://kolektiva.social/tags/johnmastodon.json

I use this to get posts for my followed hashtags on a single user instance. Did it break in 4.1.0 or was it discontinued for some reason? I could not find anything on the bug tracker.

### Specifications

Mastodon 4.1.0

**Comment by ClearlyClaire** [comment]
This was purposefully changed in #23460 because of the high load and limited usefulness of these representations.

**Comment by sl1txdvd** [comment]
Alright, thanks for clearing that up. I'll have to change my script to use the api then.
