### ISSUE TITLE
Site not working on Chrome, appears to be MathJax error

### ISSUE THREAD

**Issue by DanielMedic** [mastodon/mastodon#23862]
### Steps to reproduce the problem

1. Go to my Mastodon server (qoto.org).

2. Receive following error message:

> Due to a bug in our code or a browser compatibility issue, this page could not be displayed correctly.
> 
> Try refreshing the page. If that does not help, you may still be able to use Mastodon through a different browser or native app.
> 
> Mastodon v3.2.1

3. Copy stacktrace; see results in details below.

### Expected behaviour

The site should have loaded as usual.

### Actual behaviour

Error message reported above.

### Detailed description

Stacktrace:

ReferenceError: MathJax is not defined

ReferenceError: MathJax is not defined
    at n._renderMathJax (https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:244059)
    at n.componentDidMount (https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:244194)
    at cs (https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1100697)
    at wu (https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1118386)
    at t.unstable_runWithPriority (https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1137706)
    at Va (https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1062357)
    at _u (https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1115052)
    at su (https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1111206)
    at https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1062648
    at t.unstable_runWithPriority (https://qoto.org/packs/js/common-7c6b4a7034598e032d8d.js:2:1137706)

_renderMathJax (webpack:///app/javascript/mastodon/components/status_content.js:108:4)
componentDidMount (webpack:///app/javascript/mastodon/components/status_content.js:114:9)
Ji (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5161:45)
q.focus (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6408:21)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2816:9)
Jj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6204:2)
Kj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5895:4)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2851:16)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)

### Specifications

Google Chrome 110.0.5481.177
macOS 10.14.6
Mastodon v3.2.1

**Comment by YounsooChoi** [comment]
Consider opening issue here? https://git.qoto.org/qoto/qoto/-/issues

**Comment by lutoma** [comment]
I think the MathJax related stuff is only present in the modified qoto.org version of Mastodon, so this is not a problem with Mastodon itself: https://git.qoto.org/qoto/qoto/-/commit/0719283e18dd41fe5ef0a8b0a3a94b66d316fcd9

**Comment by DanielMedic** [comment]
> Consider opening issue here? https://git.qoto.org/qoto/qoto/-/issues

That's a very good idea, thanks!

**Comment by DanielMedic** [comment]
Appears to be fixed now.  Thanks for the comments and suggestions.
