### ISSUE TITLE
A missing sentence was found in the localization target.

### ISSUE THREAD

**Issue by fofwisdom** [mastodon/mastodon#23861]
### Steps to reproduce the problem

1. go to Preferences
2. go to Import and select the Domain Blocking List
3. select 0 KB csv and upload
...
"open has contents are not what they are reported to be" 
![화면 캡처 2023-02-24 182435](https://user-images.githubusercontent.com/205521/221162814-069f4792-e865-4d4e-9023-024911c6f973.png)

### Expected behaviour

A Korean message should be output.

### Actual behaviour

An English message was output.

### Detailed description

The sentence was not found in Crowdin.
![image](https://user-images.githubusercontent.com/205521/221163852-19e494b4-f54c-4fcc-8116-6786b093408c.png)

### Specifications

Mastodon 4.1.0
Ruby 3.0.4
Node.js 18.14.2

**Comment by ClearlyClaire** [comment]
Indeed, that string is coming from a dependency and is neither translated there nor in Mastodon.

Note that #21054 would stop using this codepath and this translation string altogether (though now that you mention it, I should verify it correctly behaves on empty files).

**Comment by ClearlyClaire** [comment]
Closing as https://github.com/mastodon/mastodon/pull/21054 has been merged and this codepath is not used anymore.
