### ISSUE TITLE
Hashtag Filter with wildcards

### ISSUE THREAD

**Issue by MikeTango** [mastodon/mastodon#23876]
### Pitch

Please make the filter list for any hashtag bigger and enable wildcards - it would help a lot if you could filter out 
#gay* or #*furry.

### Motivation

This feature is needed to get rid of a flood of unwanted dick picks that otherwise show up when filtering for hashtags. Before the obligatory gatekeeping starts: I am not anti gay. I'm just not into cock. The example can be set to any #*stuff*

**Comment by BenAveling** [comment]
Largely similar to  #9458

**Comment by MikeTango** [comment]
Pretty identical and sorry i didn't search back to the stone age for it.
