### ISSUE TITLE
App still crashes on every post or reply attempt iOs iPhone 12

### ISSUE THREAD

**Issue by DaveT-T** [mastodon/mastodon#23906]
### Steps to reproduce the problem

Create post will flash compose screen for one second then app will crash

Reply to any post same behavior

Updated with recent app supposed to fix this.

iPhone 12 iOs 16.1.1

### Expected behaviour

Compose and post used to work prior to previous update

### Actual behaviour

app crash

### Detailed description

Create post will flash compose screen for one second then app will crash

Reply to any post same behavior

Updated with recent app supposed to fix this.

iPhone 12 iOs 16.1.1

Please also consider keeping previous versions in app store so that we can revert to known working version if an update goes wonky.  iOs does not allow undo of an update unless previous versions are offered in app store

### Specifications

iPhone 12 iOs 16.1.1     App version recent release

**Comment by Cassolotl** [comment]
I think this might belong on the iOS issue list? It can be found here: https://github.com/mastodon/mastodon-ios/issues

**Comment by walbarello** [comment]
Based on the information provided, it seems that there may be a bug or issue with the app that is causing it to crash when attempting to create or reply to a post. It's possible that this issue was introduced in a recent update.

Here are some steps you can take to try and resolve the issue:

    Try force quitting the app and restarting your phone. This can sometimes resolve temporary issues with apps.

    Check to see if there are any updates available for the app. If so, try updating to the latest version to see if the issue has been resolved.

    If the issue persists, try uninstalling and reinstalling the app. This can sometimes resolve more persistent issues.

    If none of the above steps resolve the issue, you may need to reach out to the app's support team for further assistance.

Regarding the request to keep previous versions of the app available on the app store, this is ultimately up to the app developer. However, you can try reaching out to them and requesting this feature. It's possible that they may consider implementing it in the future.

**Comment by DaveT-T** [comment]
Thanks.   This thread *is* the app developer.   All App Support links lead to this place and this place alone.

Official Mastodon app for iPhone.

(Also normal support stuffs already attempted and no change.  Problem started with app update a few weeks ago and did not change with recent update stating app crash was fixed.)

Appreciate your taking the time to offer assist though.  = : )

See no option to move this thread into the Mastodon IOS category if anyone can assist on that...

**Comment by DaveT-T** [comment]
Inexplicably....*third* time i deleted app and reinstalled it is now behaving properly...
