### ISSUE TITLE
missing scheduled_at in /api/v1/announcements .

### ISSUE THREAD

**Issue by tateisu** [mastodon/mastodon#23903]
### Steps to reproduce the problem

- set announcements with `scheduled_at`
- get /api/v1/announcements , it has no `scheduled_at`
- webUI shows announcements at `scheduled_at`
- app can't emulate correct behavior.

### Expected behaviour

/api/v1/announcements contains `scheduled_at`

### Actual behaviour

/api/v1/announcements has no `scheduled_at`

### Specifications

Mastodon 4.0.2

**Comment by trwnh** [comment]
isn't `scheduled_at` an admin-only parameter? once this datetime is reached, the announcement is published and the datetime should be available via `published_at`

**Comment by tateisu** [comment]
that means the app have to periodically reload /api/v1/announcements because the app can't receive streaming event always?
