### ISSUE TITLE
In Moderation, Accounts search: tolerate @ in front of username

### ISSUE THREAD

**Issue by christofs** [mastodon/mastodon#23919]
### Steps to reproduce the problem

1. I want to search for a user based on their username
2. I go to Preferences, Moderation, Accounts and search using the field username
3. I type in "@xyz" and hit the search button

### Expected behaviour

The account with handle @xyz / username "xyz" is found

### Actual behaviour

No account is found

### Detailed description

It would be convenient if the search could just strip the initial "@" from the user's entry, if there is one, in order to avoid empty search results when the only reason for the empty search is that the "@" is not expected input. Doesn't sound complicated to me! 

### Specifications

Mastodon | 4.1.0
Ruby | 3.0.4p208
PostgreSQL | 14.7
Redis | 7.0.8

**Comment by HeitorMC** [comment]
Can I work on this one? :grimacing:

**Comment by HeitorMC** [comment]
I've already made a change to cover this case, and it's already merged. I think we can close this issue :)

**Comment by ThisIsMissEm** [comment]
@vmstan can be closed as "fixed"
