### ISSUE TITLE
Interface suggests you can edit an image focal point, but you can't.

### ISSUE THREAD

**Issue by velw** [mastodon/mastodon#23910]
### Steps to reproduce the problem

1. Open an existing post that has an image attached
2. Choose "Edit" on the media attachment
3. Move the focal point
4. Click "Apply"
...

### Expected behaviour

The focal point should change

### Actual behaviour

The focal point does not change

### Detailed description

1. Open an existing post that has an image attached
2. Choose "Edit" on the media attachment
3. Move the focal point
4. Click "Apply"

The focal point should change. It does not change. If you choose "Edit" on the media attachment again, the focal point is once more displayed in its original position (unchanged).

### Specifications

Mastodon 4.1.0 advanced web interface 
Firefox 109.0

**Comment by ClearlyClaire** [comment]
No estimate for when there will be a release nor when it will be applied to the server you use, sorry.

**Comment by velw** [comment]
> No estimate for when there will be a release nor when it will be applied to the server you use, sorry.

Ah, ok - thanks for the info. Roughly how often do releases typically happen?
