### ISSUE TITLE
Searching up specific hashtags to moderate

### ISSUE THREAD

**Issue by anampses** [mastodon/mastodon#23923]
### Pitch

Unless I am missing something, it appears there is no way for me to moderate a specific hashtag without it showing up in the "Trending hashtags" of my Mastodon admin panel.

For example, I can go to exampleinstance.com/admin/trends/tags and click on one of the trending tags at any given moment, in this case #trendingnow is Trending #10 at the moment. When you click on #trendingnow to moderate it takes you to a very specific URL of that hashtag to moderate: https://exampleinstance.com/admin/tags/444233

But how do I find a hashtag for me to moderate if it isn't trending? If I want to block and blacklist a specific tag (say for example, #illegalcontent ) there is no way for me to know the exact address with admin/tags/##### at the end of URL to moderate it.

Please consider adding some way for me to quickly find a specific hashtag that isn't trending for me to disallow users from using the hashtag, disallowing it from trending, or disallowing it from appearing in searches and suggestions.

### Motivation

It is imperative this feature is added to prevent bad actors from sharing illegal content using specific hashtags that are not trending.

**Comment by anampses** [comment]
Please.. I implore the devs to look into this very serious issue of tags used to share abuse content. 

https://pawoo.net/@sylvia_eng/109925695636334261

**Comment by anampses** [comment]
Please.. I implore the devs to look into this very serious issue of tags used to share abuse content. 

https://pawoo.net/@sylvia_eng/109925695636334261

**Comment by myrrhashad** [comment]
This would be so useful, i've been waiting for something like this for a long time !

**Comment by kaiserkiwi** [comment]
I was really confused as I wanted to moderate a abusive hashtag before it gets to the Trends. I searched for over half an hour now and got to this issue now. 

The hashtag now trended and I could block it for my users but this can't really be the solution. There must be a way on the Hashtag page to get to the moderation view or search in there for specific hashtags.

**Comment by renchap** [comment]
Related to #17059

**Comment by ThisIsMissEm** [comment]
This has been completed via #29986, which is shipping in Mastodon 4.3

There would need to be a separate feature added to create a hashtag that your instance currently isn't aware of (though you could always do a private mention and include a hashtag in order to "create" it on your instance, such that you can then moderate it)
