### ISSUE TITLE
Make replies to self Unlisted by default

### ISSUE THREAD

**Issue by somaamos** [mastodon/mastodon#23922]
### Pitch

When replying to your own posts, the default visibility should be Unlisted. This will support threads in a socially acceptable way.

This could be a configuration option with Unlisted as the default. Admin could choose to allow configuration. 

### Motivation

Threads, while not formally supported, are a nice way for people to post longer messages. The social expectation in the community is that you make replies Unlisted to avoid spamming timelines. It is all too easy to forget this. It is nice that if you mark the first reply Unlisted, subsequent replies inherit that settings -- but it is not sufficient. 

This change would support expected behavior by default while allowing users (and admin?) to modify as needed or desired.

**Comment by trwnh** [comment]
this won't affect anything other than the public timelines. is the concern only about having your self-replies show up in the public timelines?

**Comment by somaamos** [comment]
I was thinking of follower timelines but you are correct, this won't have the desired effect

**Comment by somaamos** [comment]
Closing because the suggestion won't have desired effect
