### ISSUE TITLE
Make private messages easier to identify

### ISSUE THREAD

**Issue by louzaonet** [mastodon/mastodon#23950]
### Pitch

Private messages should be marked in another way to make easier to identify in the timeline, not only with the @.

Something like a different background color, or similar.

How can a visually impaired know easily that the message received is private?

### Motivation

I see some users having issues with this, disabling boost button and the @ at the bottom is not enough.

**Comment by Zarkon55555** [comment]
This is a good idea. I'm visually impaired and this would be of great help

**Comment by louzaonet** [comment]
Thanks @Zarkon55555 

I was thinking about this, the background color should be ok for me.

I know there are different levels in visual impairment, so maybe the solution should include something different, like tagging private messages with a "Private" just before the message itself for text to speech applications and devices.

**Comment by Gargron** [comment]
I like how Ivory does it with "Private mention" above the post.

**Comment by louzaonet** [comment]
Just installed Ivory to see, looks a good solution for web interface and official apps, and it's compatible with text to speech.

**Comment by Danie10** [comment]
We just need to remember this is not just a 1:1 DM because if say 3 people are mentioned in it, it is a private group discussion then between all three of those people. It's also not encrypted, it is just not on the public feed timeline (as far as I know). Benefits are it is compatible still across Fediverse so could include a Friendica, Hubzilla, etc account too.

**Comment by jdebp** [comment]
Toot.Wales does this with a border, and thus presumably has the CSS for this already done, somewhere.

**Comment by ashemedai** [comment]
The current advanced web view of mastodon.social has a differentiator with a different background colour for private mentions., However, for dark mode it is rather painful to see at a glance (top half a normal mention, bottom the private mention):
![image](https://github.com/mastodon/mastodon/assets/610865/9997cd5e-95f7-4b6d-aecd-63d85ddc7473)
