### ISSUE TITLE
Usernames in bio link to remote instance page instead of opening in current instance

### ISSUE THREAD

**Issue by nclm** [mastodon/mastodon#23971]
### Pitch

When someone mentions other usernames in their bio (for instance “Creator of @project” or “Best friend of @person”) and these users are not on your current instance, the links created open the profile pages on the remote instance in a new tab.

This suggestion is about opening these profiles directly in the current instance, just like username links in posts themselves.

### Motivation

The current behaviour makes it harder to follow the users linked or favourite their posts, as you have to go back to your instance and copy-paste their username or URL there. If you were never leaving your instance in the first place, the process would be smoother.

**Comment by trwnh** [comment]
- #1399
- #2136
- #3185
- #3982
- #9946
- #22414
