### ISSUE TITLE
Mastodon reply-box layout breaks if a status language contains dialect/region specifier

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#23990]
### Context

Regular behavior: If a status has a non-English language set, and I reply to it, Mastodon automatically copies the original post's language's code into my reply.

[<img width="540" src="https://user-images.githubusercontent.com/277318/223188212-e7b49e30-b7e6-42dd-8c4d-0b17327d5551.png">](https://user-images.githubusercontent.com/277318/223188212-e7b49e30-b7e6-42dd-8c4d-0b17327d5551.png)

For example here my reply box shows Danish.

### Steps to reproduce the problem

Bug behavior: I got a reply from a user whose server was reporting "en-us" language for his statuses. <a href="https://mastodon.social/@lapo@f.lapo.it/109976145338061924">see post here</a>, <a href="
https://mastodon.social/api/v1/statuses/109976145338061924">see JSON here</a>.

When I reply to this post, Mastodon tries to fit "EN-us" into the little box where you set language, and the layout breaks:

![image](https://user-images.githubusercontent.com/277318/223187533-59de7311-38ea-45fd-b6bc-c8bf340c1481.png)

### Expected behaviour

The box should not look weird. Either you should detect and crop off the -us, or you should grow the space on the right for en-us to be displayed.

### Actual behaviour

The box looks weird.

### Specifications

mastodon dot social running v4.1.0, Chrome 110.0.5481.178 (Official Build) (64-bit), Windows 10 Build 19045, advanced mode. I normally run "stylus" to alter Mastodon's CSS but I turned it off for these tests/screenshots.

**Comment by mcclure** [comment]
Oh, **one other thing**: Notice the post by Lapo Luchini has an offer to "translate". My language is set to English so you should not offer to translate from "en-us" to "en". Sometimes it does make sense to offer to translate between two iso languages that differ only by dialect code (for example, zh-Hans vs zh-Hant) but for other languages (en, es, pt) the dialects are fully mutually intelligible and the machine language translator will have nothing to do. Indeed, if I click the "translate" button, I get only a 503 error; apparently DeepL just errors if you ask it to translate en-us to en.

**Comment by trwnh** [comment]
Duplicate of #19302

**Comment by mcclure** [comment]
So it is
