### ISSUE TITLE
Some static assets do not have proper cache-control headers when served by Rails

### ISSUE THREAD

**Issue by renchap** [mastodon/mastodon#24021]
### Steps to reproduce the problem

When `RAILS_SERVE_STATIC_FILES` is set, Rails is not setting any `Cache-Control` header for some files.

For example:
- `/oops.png`
- `/robots.txt`
- `/favicon.ico`
- `/sounds/boop.mp3`
- `/ocr/lang-data/eng.traineddata.gz`
- `/emoji/*`

Packs and other assets have a correct `Cache-Control` header set. This is detrimental to caching when using a CDN or reverse proxy cache, and should decrease the load on origins quite a lot.

### Expected behaviour

Static files have a correct `Cache-Control` header

### Actual behaviour

They dont

### Detailed description

This can be fixed by custom configuration on your proxies, but I think it should be handled out of the box.

### Specifications

Mastodon 4.1.0, using the official Docker container.

**Comment by untitaker** [comment]
ptal https://github.com/mastodon/mastodon/pull/24083
