### ISSUE TITLE
burger drop down is disabled on logged out remote toots

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#24039]
### Steps to reproduce the problem

Just noticed. the burger drop down is disabled on logged out remote toots.. so I cannot grab the original toot link easily

for example, https://theradio.au/@atomicpoet@mastodon.social/109990695811464974  I cannot recover the https://mastodon.social/@atomicpoet/109990695301612661 original link easily

### Expected behaviour

Able to click and copy the "link to original toot"

### Actual behaviour

burger menu is disabled. I cannot copy anything

### Specifications

main

**Comment by untitaker** [comment]
When logged out, those pages redirect to the original URL. There are however some glitches that make it possible to view them on the remote instance, for example when navigating between messages in threads.

So technically you _can_ easily grab the URL by reloading the page, but there's a bunch of things that are confusing about this behavior.
