### ISSUE TITLE
Remove the ability for instances to ban other instances

### ISSUE THREAD

**Issue by idc77** [mastodon/mastodon#24067]
### Pitch

Bubbles fighting bubbles.
Boxes vs boxes.
Recently mastodon.online banned freeatlantis.com
I was observing a discussion about that.
When I checked the banned site I found little that is banworthy.
Banning an instance for the  political views of some people on that instance? It has to stop.
I run my own instance, because I was banned on 2 instances for posting facts people didn't like, facts presented on Wikipedia. For the record, I was never banned on Twitter, Facebook/Instagram, Google+ or (forgot that one socnet's name).
Giving 1 person control over atm ~170k people on mastodon.online deciding what they can and can not read or interact with is too much power in one person's hand.
We can't have progress as a society if we exclude each other and stay in our bubbles.
Likewise 1 person deciding for all other people regardless if they support an idea or not is a dictatorship.
The freeatlantis instance was banned by many instances because "right wing" blah-blubb. A dictatorship is by default right wing, faschist if you like.
The fact that the ban button is so easily accessible makes it easy to ban instances that supposedly support a certain point of political view.
Just because someone is an administrator of an instance doesn't make them more important than the rest of their users.
You could say,"then don't join such an instance". When largest instance is a dictatorship, but it has all the action going, do you really want to tweet all alone for yourself?
I know, relays are a thing, but many don't even accept 1 person instances.
So essentially Mastodon is a broken concept, by allowing 1 server admin to decide over 170k of their users.

### Motivation

We need to de-bubble the internet, not make it into more echo-chambers and more bubbles.
Censorship is strong on Mastodon. Stronger than on any corporation owned service.
We need to tone down censorship. Make it harder for server admins to ban content with a simple click/tap.

The left the right, the pacifists the warmongers, the straight the lbgt, we need to talk to one another.
Only talking to one another at least gives us the opportunity to understand the other, if we even want that.
If not there are still the mute and block account options.

But 1 person deciding for 170k others is a dictatorship.

**Comment by smiba** [comment]
Terrible idea that has been discussed here before.

Facts are that there are terrible places on the internet, but even ignoring the "bad" instances (as this is subjective), trolls still exist and abusive instances also need to be able to be banned.

No one owes you or someone else a platform. The cool thing about mastodon is that you can just move instances too! Does your admin not play nice and bans a bunch of instances? Just move. Does your admin not moderate their instance correctly, leading to them being banned from a bunch of instances? Just move :)

It's that simple

**Comment by vkbo** [comment]
> The left the right, the pacifists the warmongers, the straight the lbgt, we need to talk to one another. 

No one is obligated to talk to people who hate them for who they are. Free speech is also about being able to exist online without being harassed and scared into silence. While nothing will ever be perfect, the current features of Mastodon *are* necessary.

For those of us who spent their time on message boards in the "old" internet, this is familiar territory. Admins and moderators sometimes get a bit overzealous, but on Mastodon you can move servers, so you aren't really limited by this.
