### ISSUE TITLE
follower/following routes cause errors in web-app

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#24078]
### Steps to reproduce the problem

try to load the following links:

- https://mastodon.social/users/Gargron/following
- https://mastodon.social/users/Gargron/followers

### Expected behaviour

they load a useful representation

### Actual behaviour

they load an error in the web-app

### Specifications

mastodon.social

**Comment by trwnh** [comment]
for the purposes of federation or for browsing the linked data web, sure, you can do that. but it would be nice if the urls also worked in HTML browsers.

**Comment by TheDevJoao** [comment]
@trwnh I'm currently working on your suggestion, expect a PR to solve this soon :thumbsup:
