### ISSUE TITLE
Support `.well-known/oauth-authorization-server` from RFC 8414

### ISSUE THREAD

**Issue by saschanaz** [mastodon/mastodon#24099]
### Pitch

Implement `.well-known/oauth-authorization-server` as a way to tell the clients about the OAuth server configuration e.g. about the URLs of endpoints. https://datatracker.ietf.org/doc/html/rfc8414

### Motivation

A client software may want to support various other server software in addition to Mastodon, and in that case it's easier to have metadata endpoint for the server configuration so that it doesn't have to manage the hardcoded list of configurations for each.

**Comment by saschanaz** [comment]
Mastodon uses Doorkeeper and it's supported there: https://github.com/doorkeeper-gem/doorkeeper-openid_connect/pull/152

**Comment by ThisIsMissEm** [comment]
Specifically a reference implementation is at: https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/master/app/controllers/doorkeeper/openid_connect/discovery_controller.rb

But we wouldn't necessarily want to use doorkeeper-openid_connect, as Mastodon is only a OAuth 2.0 provider, not an OIDC provider.

**Comment by ThisIsMissEm** [comment]
I've offered to implement this in doorkeeper, but haven't received a reply: https://github.com/doorkeeper-gem/doorkeeper/issues/1587

**Comment by ThisIsMissEm** [comment]
Okay, given that I've received no response from the Doorkeeper team in 2 months, and the sheer amount having this implemented would make it easier to develop API consuming applications that request the lowest scopes of data possible, I think the path forwards would be to just implement this API endpoint directly in the mastodon codebase, based on the code from this comment: https://github.com/mastodon/mastodon/issues/24099#issuecomment-1793148258

**Comment by ThisIsMissEm** [comment]
@saschanaz this can be closed as completed as of 4.3, since #29191 has landed for that release.

**Comment by saschanaz** [comment]
Nice, I can confirm it's supported now 👍
