### ISSUE TITLE
Notifications from limited accounts do not arrive for admins/mods

### ISSUE THREAD

**Issue by davidwolfpaw** [mastodon/mastodon#24117]
### Steps to reproduce the problem

1. Have a local user limited
2. The local user sends a DM or message to an admin or mod who does not follow them 
3. The admin/mod does not receive notification of the message

### Expected behaviour

A user who is limited should still notify admins/mods when they message

### Actual behaviour

DMs are sent by limited user, but admin/mod does not get notified, so it looks as if they are ignored

### Detailed description

It makes sense that if a user is limited, others who do not follow them will not get notified when they message, either publicly or via DM.

However we have had issues with users DMing an admin or moderator, and not having a response because while the messages are sent, the recipients are not notified.

While admins/mods may not necessarily want every message from limited users, it has led to further interpersonal issues, as the user understandably feels that they have been ignored. In my case I would have responded to the user when I got their message, but I was not notified of any of their messages.

I am suggesting that an option exist for a capability that can be added to user roles that allows you to bypass the limit feature, and receive messages from limited users. This would allow mods and admins, or any other user role created, to opt-in to letting limited users message them for moderation purposes.

### Specifications

Mastodon v4.1

**Comment by ShadowJonathan** [comment]
I suggest a specific toggle in the admin interface for "have limit users be able to direct-message people with the role <X>", or have the Direct Messages interface also list limited users, in a manner similar to how other platforms to "Message Requests"
