### ISSUE TITLE
'Disclose application used to send posts' setting doesn't work

### ISSUE THREAD

**Issue by ruudschilders** [mastodon/mastodon#24128]
### Steps to reproduce the problem

1. Unchecked the option 'Disclose application used to send posts' in https://mastodon.world/settings/preferences/other
2. Clicked 'Save changes' 
3. Posted from an iOS app

A user mentioned this issue to me. He tested with 5 different iOS apps.

I then tested with 1 app (Toot!) from 3 different instances. All have this problem

### Expected behaviour

App name should not be visible under post.

### Actual behaviour

App name was mentioned under the post.

### Detailed description

Unchecking this setting doesn't prevent the app name being mentioned below the posts.

![e034a5036e41d37e](https://user-images.githubusercontent.com/26794282/225640432-ca5cfab5-7591-4d3b-bd93-91bf36427fd7.jpeg)

### Specifications

Mastodon 4.1.0

Different iOS apps (Toot!, Mammoth, Ivory, Mona etc)

**Comment by davidpatrickanasco** [comment]
I am the original user mentioned above. Tried this on other iOS Mastadon apps, still the issue persists. The only time I do not see an app disclosed is when I post from the mastodon.world site.

**Comment by trwnh** [comment]
You can always see your own applications, but no one else can. I agree this is a bit confusing, though -- perhaps an "only visible to you" indicator might be useful?

**Comment by NeuroSan** [comment]
It turns out that the server admin will also know what software you used for posts, right?
