### ISSUE TITLE
Request for ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ (Cherokee) language option

### ISSUE THREAD

**Issue by devsalad** [mastodon/mastodon#24127]
### Pitch

Requesting that an option for ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ (Cherokee language) be added to the list of languages when posting on Mastodon. 
 
Language codes:
ISO 639-2 — [chr](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?code_ID=90)
ISO 639-3 — [chr](https://iso639-3.sil.org/code/chr)

ᏣᎳᎩ (Cherokee)

### Motivation

https://en.m.wikipedia.org/wiki/Cherokee_language

> Cherokee or Tsalagi (Cherokee: ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ, Tsalagi Gawonihisdi [[dʒalaˈɡî ɡawónihisˈdî]](https://en.m.wikipedia.org/wiki/Help:IPA)) is an endangered-to-[moribund](https://en.m.wikipedia.org/wiki/Moribund_language)[[a]](https://en.m.wikipedia.org/wiki/Cherokee_language#cite_note-11) [Iroquoian language](https://en.m.wikipedia.org/wiki/Iroquoian_languages)[[4]](https://en.m.wikipedia.org/wiki/Cherokee_language#cite_note-Ethnologue18-4) and the [native language](https://en.m.wikipedia.org/wiki/Native_language) of the [Cherokee](https://en.m.wikipedia.org/wiki/Cherokee) people

Active Cherokee speaker and ones learning the language would benefits from this option.

**Comment by nschonni** [comment]
Think this needs to be added to https://crowdin.com/project/mastodon
