### ISSUE TITLE
v4.1.1 archive download fails with OpenStack Swift object storage

### ISSUE THREAD

**Issue by hugogameiro** [mastodon/mastodon#24146]
### Steps to reproduce the problem

Using OpenStack Swift object storage, request an user archive and attempt to download it.

### Expected behaviour

Download to happen

### Actual behaviour

Something went wrong page

### Detailed description

Logged: "Storage must be instantiated with the :openstack_temp_url_key option"

Setting `openstack_temp_url_key` with a key in [`fog_credentials`](https://github.com/mastodon/mastodon/blob/ab85f59c30ff523cb2a6551ca1f36779c2fa81f3/config/initializers/paperclip.rb#L116-L127) stops that error and generates what looks like a valid temp URL (https://domain/path?temp_url_sig=hash&temp_url_expires=timestamp) but the generated URL will fail with '401 Unauthorized: Temp URL invalid'. 

Manually removing the `temp_url_sig` and `temp_url_expires` parameters from the URL allows the download. So, I'm not even sure if it makes sense to use temporary URL for OpenStack Swift as the container is what sets permissions and if that is public, a temporary URL is redundant.

For now I have changed [`redirect_to @backup.dump.expiring_url(Time.now.utc + 10)`](https://github.com/mastodon/mastodon/blob/ab85f59c30ff523cb2a6551ca1f36779c2fa81f3/app/controllers/backups_controller.rb#L16) to `redirect_to full_asset_url(@backup.dump.url)` and it works fine but this will disable the temp URL introduced in #24136 for Fog.

### Specifications

Mastodon 4.1.1 with OpenStack Swift object storage

**Comment by ClearlyClaire** [comment]
> Setting `openstack_temp_url_key` with a key in [`fog_credentials`](https://github.com/mastodon/mastodon/blob/ab85f59c30ff523cb2a6551ca1f36779c2fa81f3/config/initializers/paperclip.rb#L116-L127) stops that error and generates what looks like a valid temp URL (https://domain/path?temp_url_sig=hash&temp_url_expires=timestamp) but the generated URL will fail with '401 Unauthorized: Temp URL invalid'.

I am not familiar with OpenStack Swift, but I think that's something that should work…

> Manually removing the `temp_url_sig` and `temp_url_expires` parameters from the URL allows the download. So, I'm not even sure if it makes sense to use temporary URL for OpenStack Swift as the container is what sets permissions and if that is public, a temporary URL is redundant.

Indeed. Though I have also seen a worthy suggestion that is that the reverse proxy could forbid direct access to the files without query string.

A future improvement could also be to have a different bucket/container for user archive takeouts, although that adds some admin burden and would require some non-obvious migration path.

**Comment by ClearlyClaire** [comment]
I think #24200 should address the issue, but it would be nice if you could double-check! It could also be nice if we managed to find out why setting `openstack_temp_url_key` did not work, but I don't know how to investigate that.

**Comment by hugogameiro** [comment]
@ClearlyClaire Sure, no problem and after testing it, yes #24200 is good and fixes the problem.

On my initial testing using a similar patch it wasn't working because I was using the wrong `SWIFT_TEMP_URL_KEY`. I could have found the problem sooner but when I understood that OpenStack Swift did not support Object ACL I gave up. Sorry if that caused you any trouble looking deeper into this.
