### ISSUE TITLE
v4.1.1 - Index update strategy is undefined for current context

### ISSUE THREAD

**Issue by hugogameiro** [mastodon/mastodon#24149]
### Steps to reproduce the problem

Running `tootctl media remove --prune-profiles` in an instance with ElasticSearch

### Expected behaviour

Process the command

### Actual behaviour

Returns an error for each file that it attempts to delete

### Detailed description

Running `tootctl media remove --prune-profiles` works fine in a Mastodon installation without ElasticSearch but when ElasticSearch is enabled it returns:
> Error processing XXXX:   Index update strategy is undefined for current context.
>  Please wrap your code with `Chewy.strategy(:strategy_name) block.`

I was only able to reproduced this when `--prune-profiles` is set. Running just `tootctl media remove` works fine. Could be related to #24046.

### Specifications

Mastodon v4.1.1
ElasticSearch OSS 7.10.2

**Comment by bplein** [comment]
Also happening for `tootctl accounts prune` on v4.1.1 as well.

**Comment by SurplusXoyo** [comment]
I used `docker-compose run --rm web tootctl accounts refresh --all --verbose` to re-fetch the media file and I got the same error.

**Comment by saschafoerster** [comment]
Same here. Also a loot of remote avatars are not shown anymore, might be different issue.

**Comment by baskinsy** [comment]
I can confirm the sawm issue after upgrading to v4.1.1

**Comment by arazilsongweaver** [comment]
I am running into this issue as well. Container is version 4.1.1. Podman is version 4.3.1. Debian Bookworm host. Elasticsearch is enabled.

**Comment by shleeable** [comment]
@ClearlyClaire  Side effect of #24046?

**Comment by JerryLerman** [comment]
Seeing the same

**Comment by saschafoerster** [comment]
Maybe a helpful detail: 
When I only refresh a certain account, it works: I get "Ok" and header and avatar are back. 
`docker compose run --rm web bundle exec tootctl accounts refresh RKI@social.bund.de`

But when I do this: 
`docker compose run --rm web bundle exec tootctl accounts refresh --all`
then it breaks. 
```
Error processing 905:   Index update strategy is undefined for current context.                                                                                      
  Please wrap your code with `Chewy.strategy(:strategy_name) block.`
```

**Comment by ClearlyClaire** [comment]
Thanks! Seems like the parallelization code is indeed the culprit here.

Can you try applying this change?
```patch
diff --git a/lib/mastodon/cli_helper.rb b/lib/mastodon/cli_helper.rb
index 8704edd75e..ad82050ea7 100644
--- a/lib/mastodon/cli_helper.rb
+++ b/lib/mastodon/cli_helper.rb
@@ -52,11 +52,13 @@ module Mastodon
 
             progress.log("Processing #{item.id}") if options[:verbose]
 
-            result = ActiveRecord::Base.connection_pool.with_connection do
-              yield(item)
-            ensure
-              RedisConfiguration.pool.checkin if Thread.current[:redis]
-              Thread.current[:redis] = nil
+            Chewy.strategy(:mastodon) do
+              result = ActiveRecord::Base.connection_pool.with_connection do
+                yield(item)
+              ensure
+                RedisConfiguration.pool.checkin if Thread.current[:redis]
+                Thread.current[:redis] = nil
+              end
             end
 
             aggregate.increment(result) if result.is_a?(Integer)
```

**Comment by hugogameiro** [comment]
@ClearlyClaire Unless The patch returns: `undefined local variable or method 'result'`

**Comment by hugogameiro** [comment]
@ClearlyClaire That looks good, all working as expected, at least running `tootctl media remove --prune-profiles` returns no errors with that patch. Thank you so much.

**Comment by saschafoerster** [comment]
It just works. The bonn.social remote avatars and headers are back. Thank you a lot @ClearlyClaire and congratulations to the marriage @Gargron! ❤️

**Comment by baskinsy** [comment]
Great work. Can someone please share the commands to apply the specific patch to a running installation?

**Comment by DatAres37** [comment]
> It just works. The bonn.social remote avatars and headers are back. Thank you a lot @ClearlyClaire and congratulations to the marriage @Gargron! heart

Did you have to do a full refresh for all accounts? That would take multiple days if the indicator is correct :dizzy_face:

**Comment by saschafoerster** [comment]
Yep, it took about half a day with my server, around 500.000 images have been reloaded.

**Comment by TomaszDom** [comment]
I'm not sure if this issue is being taken lightly or not, but the same problem shows up when I'm trying to run a clean install of 4.1.1 using `docker compose run --rm shell bundle exec rake db:setup`, so this version is simply not possible to install. Downgrading the docker image to 4.1.0 fixes it. 4.1.1 is two weeks old, has nobody tried installing a fresh 4.1.1 in this time?

**Comment by ClearlyClaire** [comment]
> I'm not sure if this issue is being taken lightly or not, but the same problem shows up when I'm trying to run a clean install of 4.1.1 using `docker compose run --rm shell bundle exec rake db:setup`, so this version is simply not possible to install. Downgrading the docker image to 4.1.0 fixes it. 4.1.1 is two weeks old, has nobody tried installing a fresh 4.1.1 in this time?

Hi! We're working on a release with the fix, but in the meantime, you can do `db:setup` with Elasticsearch disabled (`ES_ENABLED=false`)
