### ISSUE TITLE
Errno::EACCES: Permission denied @ apply2files

### ISSUE THREAD

**Issue by andyhubbert941** [mastodon/mastodon#24160]
### Steps to reproduce the problem

1. Upgraded dockerised system to 4.1.1 from 4.1.0 
2. Checked Sidekiq to ensure all working
3. Lots of error messages (>1000) with Errno::EACCES: Permission denied @ apply2files /app/www/public/system/cache/
4. Tried restarting all dead jobs - same errors
...

### Expected behaviour

None of these errors as previously

### Actual behaviour

Getting these errors when nothing has changed to filesystem permissions

### Detailed description

Error as above

Logs state exactly the same as sidekiq error

This just appears odd as everything is working as expected and I am able to upload images and post and have federated and home timelines with images and no issues front end

Wondering if I should be concerned? Didn't have this problem previously. Server has been down for ~48hrs due to some networking malfunctions but had a graceful and proper shutdown prior to this and no issues on restart

Nothing obvious showing but as it was posting errors and wasn't doing this prior to 4.1.1 then I have decided to submit a bug report - apologies this is my first so let me know if there is anything else you need

I've tried `tootctl cache clear ` and still getting the same issue. 

### Specifications

Mastodon 4.1.1 Release on Docker

Image provided by Linuxserver.io 

Base OS - Unraid

**Comment by andyhubbert941** [comment]
> Do you have a stack trace for these errors (check sidekiq's logs)?

Where would I find these logs?

**Comment by ThisIsMissEm** [comment]
> > Do you have a stack trace for these errors (check sidekiq's logs)?
> 
> Where would I find these logs?

For docker, you'd use `docker logs` — https://docs.docker.com/engine/reference/commandline/logs/

As Sidekiq outputs it's logs to stdout / stderr.

**Comment by mjankowski** [comment]
Closing on assumption this was resolved?

If not, please reopen and add some logs (and current version, if different from previous report)

**Comment by ThisIsMissEm** [comment]
Most likely the issue was incorrect filesystem permissions on /app/www/public/system/cache/
