### ISSUE TITLE
(GoToSocial) NoMethodError: undefined method 'filter_map'

### ISSUE THREAD

**Issue by nichu42** [mastodon/mastodon#24225]
### Steps to reproduce the problem

1. Federate with GoToSocial instance
2. Open Sidekiq and check Retries section

### Expected behaviour

Federation with GoToSocial works without error messages

### Actual behaviour

Repeated errors for ActivityPub::SynchronizeFeaturedCollectionWorker

### Detailed description

My retry queue is full of errors for `ActivityPub::SynchronizeFeaturedCollectionWorker` like this:

`NoMethodError: undefined method 'filter_map' for "https://gotosocialhost.tld/users/johndoe/statuses/01GRDXPXMM0BXHB02YN2PWZDA1":String`

### Specifications

Ubuntu 22.04.2 LTS
Mastodon 4.1.1
Ruby 3.0.4p208
PostgreSQL 12.12
Redis 5.0.7
Sidekiq v6.5.8

**Comment by tsmethurst** [comment]
This is likely because when there's only a single pinned entry, GoToSocial returns just the single id under orderedItems, rather than an array with a single entry (https://docs.gotosocial.org/en/latest/federation/federating_with_gotosocial/#featured-aka-pinned-posts)

**Comment by trwnh** [comment]
@tsmethurst this is not consistent with the activitystreams 2.0 requirement to generate equivalent output to JSON-LD compacted documents. per the activitystreams.jsonld context definition, `orderedItems` is defined as an alias for `as:items` that has set `@container: @list`, which means that it MUST be an array (and order matters -- if it were `@container: @set`, it would be forced to an array where order does not matter)

**Comment by tsmethurst** [comment]
Darn, this looks like a bug in the library we use for ActivityPub then. I'll see if we can fix it in our fork, thanks for explaining @trwnh

**Comment by tsmethurst** [comment]
We fixed this in GtS here: https://github.com/superseriousbusiness/gotosocial/pull/1673#event-8944845917

So I think this issue can be closed :)

**Comment by nichu42** [comment]
Thanks @tsmethurst!
