### ISSUE TITLE
Blurhash issues prevent mastodon installation or update on yunohost installations

### ISSUE THREAD

**Issue by panomaki** [mastodon/mastodon#24230]
### Steps to reproduce the problem

Yunohost (yunohost.org) is a managed linux server solution allowing for easy package management. This works by scripting package installs from source.

Since yunohost 4.0.2 compiling the mastodon sources aborts as blurhash 0.1.6 is not compatible with newer ruby versions. See (https://github.com/YunoHost-Apps/mastodon_ynh/pull/361) for a detailed description. With 4.0.0 patching the Gemfile and Gemfile.lock before installation worked; with newer releases this route seems locked (see https://github.com/YunoHost-Apps/mastodon_ynh/issues/367).

The issue has been solved by pull request https://github.com/mastodon/mastodon/pull/23517 where @Gargron bumped the version to 0.1.7. Unfortunately, this pull request has not been merged into the 4.0.3 or 4.1.1 releases by @ClearlyClaire yet.

It would be of great help if the bump to blurhash 0.1.7 could make its way to releases soon; a manually patched fork does not show any problems and is running fine here for some time.

### Expected behaviour

Succesful compilation of mastodon sources

### Actual behaviour

Aborted compilation on blurhash

### Specifications

Mastodon 4.0.2, 4.1.0, 4.1.1 in combination with yunohost (https://github.com/YunoHost-Apps/mastodon_ynh)

**Comment by ClearlyClaire** [comment]
Bumping the dependency in a backport release would be simple, but there might be other issues. Which version of Ruby is YunoHost using?

**Comment by panomaki** [comment]
ruby -v shows  3.0.3p157 (2021-11-24 revision 3fb7d2cadc)

**Comment by panomaki** [comment]
This issue was solved by release 4.1.2 (https://github.com/mastodon/mastodon/releases/tag/v4.1.2). Tested on development machine, automated tests should run later. Thanks for your cooperation!
