### ISSUE TITLE
Version 4.1.1 blocks cached images from external sources

### ISSUE THREAD

**Issue by GreenFootballs** [mastodon/mastodon#24235]
### Pitch

We're developing a browser extension for use with Mastodon, and just noticed that the latest update (4.1.1) has a new content security policy that is blocking images from external sites. Our extension needs to access images from our remote server, in order to put together posts for Mastodon among other things, and the CSP now makes that impossible.

Is there any chance we could get you to reconsider this particular content policy? It seems overly restrictive, and I'm sure other browser extensions will have similar problems.

P.S. I submitted as a feature request, not a bug, because I'm requesting a change. If it fits better in a different category, let me know.

### Motivation

Users of browser extensions that work with Mastodon will need to access images from other sites.

**Comment by Gargron** [comment]
What is the change in the content security policy that you are seeing? What error are you encountering?

**Comment by GreenFootballs** [comment]
The error we see in the console is:

> StrategyHandler.js:159
> Refused to connect to 'https://example.com/images/green_footballs/2023/03/16/FrT2DtdagAEVto0.jpg' because it violates the document's Content Security Policy.

This happens trying to load any image from our server.

**Comment by GreenFootballs** [comment]
OK, I checked and you're right, the CSP is the same. But for some reason it's throwing a CSP error!

I just discovered that If I empty cache and do a hard reload, the images load OK. So maybe it's related to Mastodon's cache somehow?

**Comment by GreenFootballs** [comment]
Yes, same. It looks like the images are blocked when they're pulled from the cache.

**Comment by GreenFootballs** [comment]
Wondering if StrategyHandler.js might be checking cached items now, when it didn't before.

**Comment by SurplusXoyo** [comment]
I also encountered the same problem, it runs fine without cache, but after cache it is prevented from loading.

**Comment by jgillich** [comment]
4.1.1 is also when CSP broke for us (#24158). After downgrading to 4.1.0, the issue persisted, so it's something related to the browser cache. After fixing our config and upgrading to 4.1.1 again, we still had to ask everyone to clear their cache.

**Comment by trobichaux** [comment]
This is what has been happening to me since I tried upgrading my docker installation from v4.1.0 to v4.1.1. Here is a screenshot of the browser console. 
![image](https://user-images.githubusercontent.com/40219305/229193360-6fdefed6-64f2-4f38-919a-56071695ca1f.png)

**Comment by aaro-n** [comment]
I did my own research and after configuring cors for nginx, the images stored in AliCloudoss loaded properly.
Tip: Security issues may be encountered.
introduction: mastodon source station deployed in oracle phoenix, global CDN using cloudflare, in mainland China using AWS cloudfront, picture storage in ali cloud OSS Tokyo, picture CND using cloudflare, using tencent cloud hong kong vps reverse generation cloudflare, and in mainland China using baidu cloud acceleration as picture cdn.
Try to solve: first in the Tencent Cloud Hong Kong nginx configuration into CORS, you can load pictures normally, after setting CORS in accordance with the documentation of AliCloud oss, found that also loaded normally.
Code:
```
        # 允许跨域
    location / {  
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
        add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
    
        if ($request_method = 'OPTIONS') {
            return 204;
        }
    } 

```
Highlights: After configuring CORS, the browser refresh can load images normally, and the CORS I provide may have security risks.
Reference: [CORS 跨域问题解决办法](https://www.xggm.top/archives/1147.html)

**Comment by GreenFootballs** [comment]
I've tried various combinations of CORS settings, including the ones in the comment above, with no luck.

**Comment by GreenFootballs** [comment]
Still no news on this? It's a serious problem.

**Comment by GreenFootballs** [comment]
I don't think the declarativeWebRequest API lets you modify or remove the content-security-policy header. I've experimented with it and attempting to manipulate the CSP header does nothing.

And honestly, it would be a really bad idea even if it were possible. The CSP is there for a reason, and browser extensions shouldn't disable it.

**Comment by GreenFootballs** [comment]
But another point on this subject: if this CSP is supposed to be more secure because it blocks images from external sources, it fails because it's only blocking external images AFTER they've been loaded once and are pulled from the browser cache. In other words, the remote image always displays at least once, so this restrictive CSP doesn't make anything more secure.

**Comment by GreenFootballs** [comment]
Update: I came up with a partial solution, by sending images to the extension as base 64 encoded data URLs. But of course there's a down side - much more data has to be exchanged.

I really wish you'd consider relaxing this extremely strict CSP.

**Comment by sdhawley** [comment]
I'm not sure how this ever worked, the content security policy is set to allow from asset_host (eg mastodon.example.com) but the cached files are served from files.example.com. The file server is allowed for media files by the content security policy, so no problem seeing videos.

It does seem like it would make sense to add files.example.com to the allowed sources in the content security policy for img, but maybe someone who is more familiar with this area can explain why not.

**Comment by scafaria** [comment]
@GreenFootballs not sure if my issue is related; figured I'd link it here:
https://github.com/mastodon/mastodon/issues/24877

**Comment by sdhawley** [comment]
Experimenting this afternoon I found that I had S3_PROTOCOL set to http, changing this to https images now load.

**Comment by scafaria** [comment]
Thanks @sdhawley. I'm new to coding against the Mastodon API and I don't run a sever myself. ([My use case](https://youtu.be/Bif2HLXSMhs) is for a Chrome extension that helps people find and follow Mastodon friends who they used to know on Twitter). I suppose my question is, is it fair to assume consistent images behavior for Mastodon once I obtain a 'avatar_static' url from the API? Or will it always be the case that different server administrators are free to use different S3_PROTOCOL, etc. etc.? 

I'm aware that there's a way to use a "proxy script" on the backend as @GreenFootballs has described and as I see described [here](https://stackoverflow.com/questions/43871637/no-access-control-allow-origin-header-is-present-on-the-requested-resource-whe/43881141#43881141). But my privacy goal for end-users is to avoid sending data about their browsing habits to my server. Aside from this cors images issue, an all-client-based solution works. I'd love advice on how to meet the privacy goal plus fulfill [this use case](https://www.youtube.com/watch?v=Bif2HLXSMhs) to help people flee Twitter for Mastodon. Thanks!

**Comment by sdhawley** [comment]
@scafaria I think the issue you are seeing is because of differences in individual server configs. Some are sending the CORS header and others aren't so your fetch is blocking access because fetch is a browser method. I think that rather than a mastodon API thing it is an nginx config thing.

Since you are writing a browser extension I imagine you have some options to override this behavior but I've never made an extension so I'm not much help here.

**Comment by scafaria** [comment]
OK, thank you. I'll try the options I mentioned above as a fallback.

**Comment by kypeli** [comment]
I am seeing the same issue on my own Mastodon instance. Everything works fine with Firefox and the mobile clients, but on Chrome it gives the following error.

<img width="944" alt="Screenshot 2023-05-08 at 7 11 35" src="https://user-images.githubusercontent.com/39245/236732152-cdeb6341-a6b5-4b0c-9003-acfac206c04f.png">

I am serving the images through Nginx with a local cache that is backed by S3. Address of the instance is mastodon.kypeli.com and images are served thought media.mastodon.kypeli.com. My Mastodon version is 4.1.2.

I followed the instructions from here https://thomas-leister.de/en/mastodon-s3-media-storage/

**Comment by kypeli** [comment]
I suggest re-labeling this as _bug_.

**Comment by kypeli** [comment]
@BeepSterr Thanks for the workaround! That's certainly one way to deal with this. Seems to solve the issue for me as well.

Do you know why this solves the issue?

**Comment by BeepSterr** [comment]
@kypeli When you have the service worker the requests for images seem to go trough it? (I honestly am not too familiar with serviceworkers myself). Maybe somewhere in there the CSP headers get mangled?

**Comment by tokpig** [comment]
我也遇到了这样的问题，我无法解决

**Comment by GreenFootballs** [comment]
I'm happy to report in this thread that the CSP blocking issue for external images has been fixed in the latest nightly build running at mastodon.social.
