### ISSUE TITLE
Markdown functionality standards

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#24246]
### Pitch

# References
https://www.markdownguide.org/basic-syntax/
https://www.markdownguide.org/cheat-sheet/
https://www.markdownguide.org/extended-syntax/
https://docs.gitlab.com/ee/user/markdown.html
https://cloud.google.com/apigee/docs/api-platform/publish/portal/markdown-reference

# standard markdown Syntax

## Headings
```
# Heading level 1
## Heading level 2
### Heading level 3
#### Heading level 4
##### Heading level 5
###### Heading level 6
```
![image](https://user-images.githubusercontent.com/17537000/227675519-3baaa275-816f-4a1b-977c-e026221229fb.png)

## highlight
```
I need to highlight these ==very important words==.
```
![image](https://user-images.githubusercontent.com/17537000/227676475-4d93c8b3-e716-464c-90f8-1822f2e9fb72.png)

## Bold
```
I just love **bold text**.
```
![image](https://user-images.githubusercontent.com/17537000/227699921-33d751d7-66c2-42c5-a051-3d15e537bf83.png)

## Italic
```
Italicized text is the *cat's meow*.
```
![image](https://user-images.githubusercontent.com/17537000/227700113-b373203c-ba1f-44fd-b7f1-3c2b604a8ce4.png)

## Bold and Italic
```
This text is ***really important***.
```
![image](https://user-images.githubusercontent.com/17537000/227700140-a70dd66d-6c7a-486b-bb3b-f9f32eceb3f7.png)

## Strikethrough
```
~~The world is flat.~~ We now know that the world is round.
```
![image](https://user-images.githubusercontent.com/17537000/227676591-f865e347-6763-4110-99fd-4f5a519068b6.png)

## Subscript
```
H~2~O
```
![image](https://user-images.githubusercontent.com/17537000/227677691-d7e1531b-2998-437d-8857-04fda04c0cb9.png)

## Superscript
```
X^2^
```
![image](https://user-images.githubusercontent.com/17537000/227676671-4254155c-5f0a-4aab-ae1a-85265bbd130f.png)

## Blockquotes
```
> Dorothy followed her through many of the beautiful rooms in her castle.
```
![image](https://user-images.githubusercontent.com/17537000/227676694-52c2b9cd-0d9a-4500-842d-4a56f6c9f6da.png)

## Blockquotes with Multiple Paragraphs
```
> Dorothy followed her through many of the beautiful rooms in her castle.
>
> The Witch bade her clean the pots and kettles and sweep the floor and keep the fire fed with wood
```
![image](https://user-images.githubusercontent.com/17537000/227676713-2a196a79-a90e-451b-9a67-a3fc3064b698.png)

## Nested Blockquotes
```
> Dorothy followed her through many of the beautiful rooms in her castle.
>
>> The Witch bade her clean the pots and kettles and sweep the floor and keep the fire fed with wood.
```
![image](https://user-images.githubusercontent.com/17537000/227676728-d6b70cdb-0db8-4ae5-b3a0-3b5defc23fd9.png)

## Blockquotes with Other Elements
```
> #### The quarterly results look great!
>
> - Revenue was off the chart.
> - Profits were higher than ever.
>
>  *Everything* is going according to **plan**.
```
![image](https://user-images.githubusercontent.com/17537000/227676749-501ef3ae-5e0e-422a-a82e-83f7b7d8a05a.png)

## Ordered List
```
1. First item
2. Second item
3. Third item
4. Fourth item 
```
![image](https://user-images.githubusercontent.com/17537000/227676775-65a74cb7-57f2-4b36-ba81-688c8769b7ef.png)

## Unordered Lists
```
- First item
- Second item
- Third item
- Fourth item
* First item
* Second item
* Third item
* Fourth item 
```
![image](https://user-images.githubusercontent.com/17537000/227676791-ebdb6703-8088-4670-95c0-ee3406f88da1.png)

## Code
```
this is some `code`
```
![image](https://user-images.githubusercontent.com/17537000/227676808-486aeccd-e50a-4c96-9b81-48f52a9fb359.png)

## Multiple Line Code

```
\```
{
  "firstName": "John",
  "lastName": "Smith",
  "age": 25
}
\``` 
```
![image](https://user-images.githubusercontent.com/17537000/227677462-951b3339-207b-4579-826b-f2a0e7ea4b92.png)

## Multiple Line Code with syntax highlighting
```json
{
  "firstName": "John",
  "lastName": "Smith",
  "age": 25
}
```
![image](https://user-images.githubusercontent.com/17537000/227676918-6c7ab0ef-1070-4848-a739-70a2bc7a920f.png)

## Horizontal Rules
```
***
---
```
![image](https://user-images.githubusercontent.com/17537000/227676972-e247d4f5-5407-4190-8995-24c8077d2591.png)

## Formatting Links
```
I love supporting the **[EFF](https://eff.org)**.
This is the *[Markdown Guide](https://www.markdownguide.org)*.
See the section on [`code`](#code).
```
![image](https://user-images.githubusercontent.com/17537000/227677028-95604014-255b-4673-88e0-259acc444c9e.png)

## Escaping Characters
```
\* Without the backslash, this would be a bullet in an unordered list.
```
![image](https://user-images.githubusercontent.com/17537000/227677075-befb4a04-e1c4-425f-869e-88e48ef5f47b.png)

# non standard markdown
from https://oat.zone/markdown-plus/###

## Spoilered text
```
cw me being nice to you ||did you know that you're cute? just a fact||
```
![image](https://user-images.githubusercontent.com/17537000/227676385-f667370c-497a-4b86-a67b-958c48b18905.png)
on click
![image](https://user-images.githubusercontent.com/17537000/227676398-daeafcc3-669b-4d4b-8b56-ce6eff9b484c.png)

## Colours
![image](https://user-images.githubusercontent.com/17537000/227676320-2edd2cd3-0313-4121-9d18-f82402443eac.png)

### Motivation

#markdown

**Comment by Gargron** [comment]
Thank you for the suggestions but we already have a list of syntax rules we intend to support and is not going to be extensive. Mastodon remains a microblogging platform.
