### ISSUE TITLE
Connection to remote postgres fails

### ISSUE THREAD

**Issue by Gartral** [mastodon/mastodon#24301]
### Steps to reproduce the problem

1. check out mastodon git
2. comment out the `build` lines in docker-compose.yml
3. set up remote database with user `mastodon` and database `mastodon` psql command to create database is `CREATE DATABASE mastodon with template template0 encoding unicode;`
4. run `docker-compose run --rm web bundle exec rake mastodon:setup`
5. follow prompts
6. It fails to create the database.
...

### Expected behaviour

it creates the database.

### Actual behaviour

it errors.

### Detailed description

When setting up the for a remote database the database seems to not initialize in a way the docker installer likes. I've tried through both pgAdmin and the psql command line tomake a mastodon database with UTF8 encoding and it fails every time. I readily admit that I don't know a hell of a lot about postgres and from using i for this project I'm extremely confused by it. But I feel that after explicitly following the instructions in the error that it should work. 

### Specifications

versions of Mastodon, ruby, web frameworks: whatever Docker is trying to pull down
Postgres: 14.7
Host OSes: Ubuntu 22.04
Docker-compose 1.29.2 
Docker: 20.10.21
redis: 6.0.16

**Comment by vmstan** [comment]
Hi @Gartral is this still an issue for you?
