### ISSUE TITLE
MFA: Allow setting up Security Keys (e.g. Yubikey) before TOTP (authenticator app)

### ISSUE THREAD

**Issue by nehemiagurl** [mastodon/mastodon#24312]
### Pitch

Currently, if one wants to set up multi-factor authentication for their account, they have to first and foremost set up a TOTP device (i.e. authenticator app) with no option to add a security key first.
![Screenshot_20230328-082555_Firefox](https://user-images.githubusercontent.com/109424320/228137139-5f625bcf-9aef-4a9a-b834-0a2adb419ee5.jpg)
Even if one goes directly to the URL of the security keys page, they get redirected to the TOTP page if TOTP has not been set:
![Screenshot_20230328-082651_Firefox](https://user-images.githubusercontent.com/109424320/228427389-4aa96985-919f-4464-9f71-df533d9788f5.jpg)

### Motivation

Security keys are often considered more secure than TOTP, as they are practically immune to social engineering and phishing. While the fear of losing the key is understandable, giving the user backup codes + recommending they set TOTP as well should be more than enough.
Even if TOTP is preferable, I still see no reason to block Security Keys entirely before setting up TOTP.

**Comment by BirdInFire** [comment]
Already discussed here : https://github.com/mastodon/mastodon/issues/16693

**Comment by nehemiagurl** [comment]
@BirdInFire You're right, I'll close this one as duplicate.
