### ISSUE TITLE
Add/remove from home feed

### ISSUE THREAD

**Issue by SoniEx2** [mastodon/mastodon#24323]
### Pitch

It should be possible to add/remove from home feed, in addition to block/mute.

### Motivation

Since you need to follow someone to see locked posts, and locked replies to other ppl (obviously locked replies to you still show up thanks to this not being twitter), it would be useful to be able to see those without having them shoved down your throat.

A simple way to remove from home feed would do that.

(Also mutes are way too aggressive/don't actually work for this.)

**Comment by yungsinatra0** [comment]
I'm not sure how relevant it is to this suggestion (if needed I can create a separate issue for it), but it would be nice to add functionality to remove an account from the home feed (basically muting the account), but let it post it within existing lists. That way you can "clean" your home feed, while still getting the content from those accounts in the separate lists.

**Comment by SoniEx2** [comment]
we think #22048 does this, actually? not entirely sure how they handle locked posts.

**Comment by SoniEx2** [comment]
yes, this issue is solved by #22048 as far as we can tell.

**Comment by yungsinatra0** [comment]
that's nice, do you know when it will be available in the live build? I can't seem to find it at the moment.
