### ISSUE TITLE
Broken message in German when you hide image

### ISSUE THREAD

**Issue by Wuzzy2** [mastodon/mastodon#24353]
### Steps to reproduce the problem

0. Set language to German
1. Look at a toot with an image in it
2. Click the "crossed-out eye" (?) icon on the top left corner of the image to hide it
3. Read the message that appears

### Expected behaviour

Image gets hidden

### Actual behaviour

Image gets hidden, but in the center, a gibberish text appears

### Detailed description

Specifically, when I hide an image within a toot with the "eye" icon, the gibberish text appearing in the middle reads as follows:

> {number, plural, one {Medium ausgeblendet} other {Medien ausgeblendet})

Note: The phrase "Medium ausgeblendet" is German for "Medium hidden" or something like that.

### Specifications

Mastodon 4.1.1.
Observed on fosstodon.org on 01/04/2023, but also in pretty much all other instances.
Using the German translation.

**Comment by c960657** [comment]
This issue has been fixed in #23527 (see https://github.com/mastodon/mastodon/pull/23527/commits/70335bb2d38191d1e413b54e45be7dd464cff0a6).

**Comment by Wuzzy2** [comment]
Thank you.
