### ISSUE TITLE
I'd like an option to escape the advanced view (specifically for hash tags, but viewing toots too)

### ISSUE THREAD

**Issue by guest20** [mastodon/mastodon#24358]
### Pitch

I'd like an option to open a hash-tag in non-advanced view so I can have a quick, focused scroll through a bundle of posts like I'd get in the view on a mobile app. 

Right now the only way to do this is to right-click the hash tag and open it in a incognito tab and browse in logged-out mode (but that means i have to copy/paste the links back into the search box to interact with them)

### Motivation

On occasion I want to do a focused browse of hash-tag. There's no way escape the advanced view.

opening a hashtag to view the posts puts it in the right-most column in the advanced view, and re-loads all of the other columns. This is especially noticeable when you go to another instance where I'm  not logged in, and it doesn't know I have advanced view set, because on someone else's instance I can browse the list of posts on a hash-tag in the simplified view.

**Comment by mcclure** [comment]
Cosign: I love the advanced view and always prefer it, but sometimes I want to take a screenshot of a mastodon thread and sometimes the advanced view is not appropriate for this. In this case I have to use an incognito tab as guest20 says. A temporary "escape the advanced view for this one browser tab only" trick would be great for this.

**Comment by guest20** [comment]
@mcclure I'm betting screenshoting stuff is far more common than hyperfocusing over a new hashtag.

**Comment by trwnh** [comment]
possibly related #25893

**Comment by Signez** [comment]
Should be actually fixed by #25893 yeah — it's merged now, so on main, opening any link in a new tab opens it outside the advanced view, with a button letting you jump back to the advanced view if needed.

**Comment by guest20** [comment]
Neat!

**Comment by renchap** [comment]
Fixed by #25893
