### ISSUE TITLE
Add function to Mod tools to send note to reporter on resolving report

### ISSUE THREAD

**Issue by ArnonClark** [mastodon/mastodon#24367]
### Pitch

Add optional field in moderation reporting page to send text to reporter when resolving a report with no actions taken. 

### Motivation

It would be nice to be able to be able to include sending a response back to a user reporting an issue to advise them as to the result of their moderation request if no action is taken. It gives the option of including the reason no action was taken, and perhaps letting the mod explain to the reporter why their report/request wasn't actioned. Would make the process smoother and encourage feedback to inform the reporting user as to best practices (ie - filtering, hiding sensitive media, etc..) If I've missed the way that can be done, my apologies.

**Comment by vwchu** [comment]
Similar to #18154.

**Comment by ArnonClark** [comment]
Closing to add to to Related: https://github.com/mastodon/mastodon/issues/18154.
