### ISSUE TITLE
API - error: "Forbidden" - while trying to create a new account using API

### ISSUE THREAD

**Issue by ScriptSathi** [mastodon/mastodon#24362]
### Steps to reproduce the problem

1. Create an application with `write:accounts` permission
2. Curl the `/api/v1/accounts/` endpoint with data and the bearer token to create a new user.

### Expected behaviour

A `Token` instance is return

### Actual behaviour

{   "error": "Forbidden" } output

### Detailed description

Hello ! 

I'm new to mastodon and the api and didn't find issues related to this.
I've deployed a local instance of mastodon for testing but i can't find the solution for the account creation using the api, and the error is not documented.

To give more context, i'm using an `Owner` account to create an application with `write:accounts` permissions, and used the given access_token to request the API.
I can verify that my token is working with the endpoint `/api/v1/accounts/verify_credentials` (documentation [here](https://docs.joinmastodon.org/methods/accounts/#verify_credentials))
For this request i got the following output
```json
{
  "id": "110118939140013635",
  "username": "Sathi",
  "acct": "Sathi",
...
  "source": {
    "privacy": "public",
    "sensitive": false,
    "language": null,
    "note": "",
    "fields": [],
    "follow_requests_count": 0
  },
...
  "roles": [
    {
      "id": "3",
      "name": "Owner",
      "color": ""
    }
  ],
  "fields": [],
  "role": {
    "id": "3",
    "name": "Owner",
    "permissions": "1048575",
    "color": "",
    "highlighted": true
  }
}
```

But when i try to create a new account, has it is document [here](https://docs.joinmastodon.org/methods/accounts/#create), i got an unexpected error "Forbidden".

The below command make the request
```bash
curl -X POST -k \
-H "Authorization: Bearer DWq-JdGSXMYRbaNdydz6cXH37ZZ-9CR0NK9-F88zVtI" \
-d '{"username":"smallwolf684","password":"beta","email":"fake@email.com","agreement":true,"locale":"fr"}' \ 
https://mastodon.lan/api/v1/accounts/
```
And i got the following output
```json
{
  "error": "Forbidden"
}
```

(And thanks a lot for the massive work on mastodon :pray: )

### Specifications

I'm running Mastodon instance inside a docker-compose
The image is `tootsuite/mastodon:v4.1.0`

**Comment by cryptoodles** [comment]
@ScriptSathi Try adding the `push` permission to your application. When you’re creating a new account, I think it may need that permission and not just ‘write’.

**Comment by ScriptSathi** [comment]
> @ScriptSathi Try adding the `push` permission to your application. When you’re creating a new account, I think it may need that permission and not just `write`.

I've tried to add all the available permissions, but I still got the same output :(

But as it is a local instance, is it something linked to my server configuration ? Could it be possible ?
It's basically the default server configuration I use. But maybe I miss something…
