### ISSUE TITLE
will edge (main) also get the v4.1.2 tag?

### ISSUE THREAD

**Issue by GuidoDr** [mastodon/mastodon#24411]
### Pitch

edge still reports back as v4.1.1 even though a release v4.1.2 has been released.
Therefore it would be great if edge does also get the new version number. ;-)

### Motivation

I would expect that edge (main) is always ahead of the releases. ;-)

**Comment by ClearlyClaire** [comment]
Fixed by #24427

Everything that was in 4.1.2 was in `main`, but 4.1.2 is branched off.
