### ISSUE TITLE
v4.1.2 - TypeError: Symbol does not have #dig method

### ISSUE THREAD

**Issue by hugogameiro** [mastodon/mastodon#24414]
### Steps to reproduce the problem

1. Generate a data export archive
2. Click the download link

### Expected behaviour

Download the archive

### Actual behaviour

"We're sorry, but something went wrong on our end."

### Detailed description

Attempting to download a data export archive returns "We're sorry, but something went wrong on our end". The logs:
```
method=GET path=/backups/XXX/download format=html controller=BackupsController action=download status=500 error='TypeError: Symbol does not have #dig method' duration=9.35 view=0.00 db=2.04
TypeError (Symbol does not have #dig method):
app/controllers/backups_controller.rb:16:in `dig'
app/controllers/backups_controller.rb:16:in `download'
app/controllers/concerns/localized.rb:11:in `set_locale'
lib/mastodon/rack_middleware.rb:9:in `call'
lib/public_file_server_middleware.rb:18:in `call'
```
Was only able to reproduce the problem when using OpenStack Swift object storage, local storage does not have this problem but have not test S3.

### Specifications

Mastodon v4.1.2
OpenStack Swift

**Comment by ClearlyClaire** [comment]
Oops… sorry, I think the following should fix it:
```patch
diff --git a/app/controllers/backups_controller.rb b/app/controllers/backups_controller.rb
index 0687b62c50..5891da6f6d 100644
--- a/app/controllers/backups_controller.rb
+++ b/app/controllers/backups_controller.rb
@@ -13,7 +13,7 @@ class BackupsController < ApplicationController
     when :s3
       redirect_to @backup.dump.expiring_url(10)
     when :fog
-      if Paperclip::Attachment.default_options.dig(:storage, :fog_credentials, :openstack_temp_url_key).present?
+      if Paperclip::Attachment.default_options.dig(:fog_credentials, :openstack_temp_url_key).present?
         redirect_to @backup.dump.expiring_url(Time.now.utc + 10)
       else
         redirect_to full_asset_url(@backup.dump.url)
```

**Comment by hugogameiro** [comment]
@ClearlyClaire Yep, that fixes it :) Thanks and no problem at all, I should also have fully tested #24200 during our exchanges to debug OpenStack Swift temp URL in #24146.
