### ISSUE TITLE
Survey display - text truncated

### ISSUE THREAD

**Issue by yarko** [mastodon/mastodon#24444]
### Steps to reproduce the problem

1. Any survey with lines longer that screen width
2.
3.
...

### Expected behaviour

Text of survey choice visible

### Actual behaviour

text of survey choice truncated

### Detailed description

This is the display on this app:
![E3C9D117-CFD3-40CD-839E-D30DCD050FDD](https://user-images.githubusercontent.com/36553/230380890-6824053a-da80-42bf-93a5-cdaba339e303.jpeg)

This is the same survey viewed w/ metatext (iOS):
![0D3DAC58-F87C-4DE3-BA1B-87ACC58C2384](https://user-images.githubusercontent.com/36553/230381051-8e410334-39c1-48cd-b46f-a015dfad4345.jpeg)

This is the survey displayed w/ megalodon (android):

![F10CC81E-AE10-40EF-85E2-3A438AD5A1FB](https://user-images.githubusercontent.com/36553/230381217-ba108cf2-db41-4e86-ab1c-8838b96415c3.jpeg)

### Specifications

mastodon for iOS 1.5 (286)
iOS 16.3.1 (20D67)
iPhone11 Pro Max 512G

**Comment by ClearlyClaire** [comment]
Hi! Reports for the iOS app should be opened in https://github.com/mastodon/mastodon-ios
