### ISSUE TITLE
Mastodon Reports monthly logins, not monthly active users

### ISSUE THREAD

**Issue by supernovae** [mastodon/mastodon#24528]
### Steps to reproduce the problem

I used a script to export my users and their last login date and noticed that my unique active users who last logged in within 30 days was a fraction of what the API was returning.

I basically calculated the days since last used and found everyone who logged in < 30 days and the numbers were significantly less than what is reported on the api endpoint

curl https://universeodon.com/api/v2/instance | jq '.usage.users.active_month'

returns:  13468

But if i export my users and their last login date and calculate 30 days (just to say 1 month) I get

6453 users.

I would expect many of my users are loged in on a phone, ipad, elk or browser so it seems like returning unique sessions is what we're tracking over a 30 day period. (i could be wrong... i'd love to be wrong)

### Expected behaviour

Return accounts that have a last logged in date within 4 weeks.

### Actual behaviour

Returns number of logins or "Sessions"

### Detailed description

I see the API calls this:

https://github.com/mastodon/mastodon/blob/af49d93fd6168c089530240a9ab4eccb975b8c42/app/presenters/instance_presenter.rb#L58

  def active_user_count(num_weeks = 4)
    Rails.cache.fetch("active_user_count/#{num_weeks}") { ActivityTracker.new('activity:logins', :unique).sum(num_weeks.weeks.ago) }
  end

Which to me suggests that we're returning "activity:logins"  not list of unique users with a last logged in date 4 weeks ago.

I believe activity:logins unique would still count my phone, my ipad and my computer as unique logins would it not?

Looking at the code, it appears to do unique logins too:  

https://github.com/mastodon/mastodon/blob/main/app/controllers/api/v1/instances/activity_controller.rb

My guess is logins != users

### Specifications

Mastodon 4.1.2

**Comment by supernovae** [comment]
Could very well be a  big in my mastodon.py lol.

I ran some database queries and i get similar numbers

SELECT COUNT(DISTINCT user_id) FROM users WHERE current_sign_in_at >= NOW() - INTERVAL '30 days';

13835

 - almost within the % error of cardinality on redis

**Comment by Gargron** [comment]
`activity:logins` is a daily HyperLogLog of all user IDs that have performed authenticated requests.
