### ISSUE TITLE
Option to hide own boosts

### ISSUE THREAD

**Issue by Oblomov** [mastodon/mastodon#24539]
### Pitch

Timelines and list views should have an option to hide boosts from the user. Note that this is different from #21632 / #23170 because it's not about hiding toots boosted by the toot author, but about hiding toot boosted by the user browsing the timeline.

### Motivation

This feature would be beneficial to any user that browses the timelines less frequently and that boosts interesting contents when going over the backlog: after doing some catch-up and boosting potentially tens of toots, refreshing the timeline will show an update dominated by the recent boosts of the user themselves, potentially giving less visibility to actually fresh content that has reached the timeline in the meantime.

(I've frequently experienced this particularly during my morning browsing sessions, and I'm sure I'm not the only one affected by this.)

**Comment by yuvalne** [comment]
Duplicate of #20093.

**Comment by Oblomov** [comment]
Thanks, I don't know how  I missed it.
