### ISSUE TITLE
`fr-QC` locale is less common than `fr-CA`

### ISSUE THREAD

**Issue by evanp** [mastodon/mastodon#24538]
### Steps to reproduce the problem

1. Search for `fr-QC`
2. Search for `fr-CA`
3. Compare results.

### Expected behaviour

We should be using the most common code

### Actual behaviour

We are using a very unusual code

### Detailed description

We've had problems on cosocial.ca with the Canadian French language code, fr-QC. The more common ICU locale is fr-CA. As far as I can tell, the language choices are not specific to Quebecois French compared to the French spoken in the rest of Canada.

If there's intention in including fr-QC, it might make sense to have a synonymous code for fr-CA.

### Specifications

mastodon 4.1

**Comment by gunchleoc** [comment]
The CLDR doesn't even list this code. [Wikipedia has `fr-ca` even for Québécois](https://fr.wikipedia.org/wiki/Fran%C3%A7ais_qu%C3%A9b%C3%A9cois) rather than a generic Canadian French, so we should go for it.
