### ISSUE TITLE
Verified checkmark after self-verification

### ISSUE THREAD

**Issue by yordiak** [mastodon/mastodon#24544]
### Pitch

I think that a nice feature would be an automatic verification mark (it can be anything, like a mammoth ;) ) once users have applied at least once self-verification method (e.g., on their personal website, on their academic webpage, etc)

### Motivation

I believe that this feature will enable users to easily identify which users have verified themselves, without the necessity to having a look at users' profiles

**Comment by RianQuenlin** [comment]
Verification shows one thing: That you control the website that you're linking to. _Nothing more._ This is by design.

**Comment by ClearlyClaire** [comment]
Showing any kind of verification mark without showing what is verified would be highly misleading.
