### ISSUE TITLE
Role badges appears to not be working

### ISSUE THREAD

**Issue by JustDalek** [mastodon/mastodon#24608]
### Steps to reproduce the problem

1. Create or edit a role
2. Enable "Display role as badge on user profiles"
<img width="514" alt="image" src="https://user-images.githubusercontent.com/78516780/233461948-79390de7-05d2-47ad-ae26-9ec848aba516.png">

3. Check assigned profiles
<img width="412" alt="image" src="https://user-images.githubusercontent.com/78516780/233462050-2b965184-8d45-4545-84de-97e5c165a0b0.png">

4. Badge is not present
<img width="313" alt="image" src="https://user-images.githubusercontent.com/78516780/233462088-c0619561-a152-43b9-8ec2-becdd2b55673.png">

### Expected behaviour

Role present

### Actual behaviour

Role missing

### Detailed description

Just submitting a post regarding roles not properly working

### Specifications

Mastodon v4.1.2
Brave browser

**Comment by justdaj** [comment]
Duplicate with #20031
