### ISSUE TITLE
"something went wrong on our end." but no errors in the log

### ISSUE THREAD

**Issue by lionpanthera** [mastodon/mastodon#24611]
### Steps to reproduce the problem

Loading the root page of the server after migration

### Expected behaviour

No error

### Actual behaviour

Error

### Detailed description

I'm sure this isn't a bug, but I don't know what else to do.

I just migrated my Mastodon server by following this guide:
https://docs.joinmastodon.org/admin/migrating/

Everything seemed to go OK, but after staring the the server, loading the root page of the web server just results in "We're sorry, but something went wrong on our end.".

I looked for a troubleshooting guide and found this:
https://docs.joinmastodon.org/admin/troubleshooting/

It told me to look in "journalctl -u mastodon-web", so, here's the result of that:

```
Apr 20 23:58:30 dgfp systemd[1]: Started mastodon-web.
Apr 20 23:58:31 dgfp bundle[36718]: [36718] Puma starting in cluster mode...
Apr 20 23:58:31 dgfp bundle[36718]: [36718] * Puma version: 6.2.1 (ruby 3.2.2-p53) ("Speaking of Now")
Apr 20 23:58:31 dgfp bundle[36718]: [36718] *  Min threads: 5
Apr 20 23:58:31 dgfp bundle[36718]: [36718] *  Max threads: 5
Apr 20 23:58:31 dgfp bundle[36718]: [36718] *  Environment: production
Apr 20 23:58:31 dgfp bundle[36718]: [36718] *   Master PID: 36718
Apr 20 23:58:31 dgfp bundle[36718]: [36718] *      Workers: 2
Apr 20 23:58:31 dgfp bundle[36718]: [36718] *     Restarts: (✔) hot (✖) phased
Apr 20 23:58:31 dgfp bundle[36718]: [36718] * Preloading application
Apr 20 23:58:39 dgfp bundle[36718]: [36718] * Listening on http://127.0.0.1:3000
Apr 20 23:58:39 dgfp bundle[36718]: [36718] Use Ctrl-C to stop
Apr 20 23:58:39 dgfp bundle[36718]: [36718] - Worker 0 (PID: 36774) booted in 0.01s, phase: 0
Apr 20 23:58:39 dgfp bundle[36718]: [36718] - Worker 1 (PID: 36775) booted in 0.0s, phase: 0
Apr 20 23:58:44 dgfp bundle[36775]: [50472315-da22-4aaf-ac38-47df3ed0aaa7] Chewy request strategy is `mastodon`
Apr 20 23:58:44 dgfp bundle[36775]: [50472315-da22-4aaf-ac38-47df3ed0aaa7] method=POST path=/inbox format=html controller=ActivityPub::InboxesController action=create status=202 duration=30.78 view=0.00 db=6.28 key=https://mastodon.top/users/drenenalsi#main-key
Apr 20 23:59:03 dgfp bundle[36774]: [b3a75b48-cae5-42c2-ae5f-78b3bf25f120] Chewy request strategy is `mastodon`
Apr 20 23:59:03 dgfp bundle[36774]: [b3a75b48-cae5-42c2-ae5f-78b3bf25f120] method=POST path=/inbox format=html controller=ActivityPub::InboxesController action=create status=202 duration=33.75 view=0.00 db=6.15 key=https://mstdn.social/users/tomgoyens#main-key
```

None of this looks like an error, and the troubleshooting guide has no further suggestions.

There must be an error being logged somewhere, where do I look?

### Specifications

Mastodon 4.1.2
Ruby 3.2.2
Node.js 16.20.0

**Comment by lionpanthera** [comment]
OK, it turned out I fixed one of them, which was a DNS error. My bad.

I'm still getting the same error, but at least I have stuff in the log now:

````
Apr 20 23:48:41 dgfp bundle[36396]: [f58d5155-bdc0-4f41-af78-cd394abade5c] method=GET path=/api/v1/accounts/lookup format=*/* controller=Api::V1::Accounts::LookupController>
Apr 20 23:48:41 dgfp bundle[36396]: [f58d5155-bdc0-4f41-af78-cd394abade5c]
Apr 20 23:48:41 dgfp bundle[36396]: [f58d5155-bdc0-4f41-af78-cd394abade5c] NoMethodError (undefined method `[]' for nil:NilClass):
Apr 20 23:48:41 dgfp bundle[36396]: [f58d5155-bdc0-4f41-af78-cd394abade5c]
Apr 20 23:48:41 dgfp bundle[36396]: [f58d5155-bdc0-4f41-af78-cd394abade5c] app/models/concerns/has_user_settings.rb:15:in `prefers_noindex?'
Apr 20 23:48:41 dgfp bundle[36396]: [f58d5155-bdc0-4f41-af78-cd394abade5c] app/models/account.rb:127:in `user_prefers_noindex?'
Apr 20 23:48:41 dgfp bundle[36396]: [f58d5155-bdc0-4f41-af78-cd394abade5c] app/serializers/rest/account_serializer.rb:142:in `noindex'
Apr 20 23:48:41 dgfp bundle[36396]: [f58d5155-bdc0-4f41-af78-cd394abade5c] app/controllers/api/v1/accounts/lookup_controller.rb:8:in `show'
Apr 20 23:48:41 dgfp bundle[36396]: [f58d5155-bdc0-4f41-af78-cd394abade5c] app/controllers/concerns/localized.rb:11:in `set_locale'
Apr 20 23:48:41 dgfp bundle[36396]: [f58d5155-bdc0-4f41-af78-cd394abade5c] lib/mastodon/rack_middleware.rb:9:in `call'
Apr 20 23:49:39 dgfp bundle[36392]: [c5fb92ad-d330-44c0-86fc-f367f6d37ce4] method=GET path=/api/v1/instance format=*/* controller=Api::V1::InstancesController action=show s>
````

I guess the critical part is "NoMethodError (undefined method `[]' for nil:NilClass):" - but I don't even know where to start with that.

**Comment by lionpanthera** [comment]
Actually, maybe that error is a red herring? It appears twice in the log, but doesn't re-occur if I refresh the error page.

So I'm still not sure I'm looking in the right place for errors.

**Comment by lionpanthera** [comment]
Alright, I might be getting somewhere. I scoured the web and found a suggestion to try "journalctl -xf -u mastodon-*" (Maybe this should be in the troubleshooting guide?)

Anyway, this seems to be happening a lot:

Apr 21 00:26:03 dgfp node[37008]: ERR! ad51a9ab-d748-4acc-901e-204de425c2db Error: Missing access token

I'm not sure what the "access token" is, but I guess this is a failure to migrate something across from the old server? I did everything the guide told me to...

**Comment by lionpanthera** [comment]
Well. It's working. But at great cost.

In a moment of desparation, I did this:

```
RAILS_ENV=production bin/rails db:migrate
RAILS_ENV=production bundle exec rails assets:clobber
RAILS_ENV=production bundle exec rails db:migrate
RAILS_ENV=production bundle exec rails assets:precompile
sudo systemctl restart mastodon-*.service
RAILS_ENV=production ~/live/bin/tootctl cache clear
RAILS_ENV=production bundle exec rails db:migrate
sudo systemctl restart mastodon-*.service
```

There was no great purpose to all this. But I was angry and had run out of ideas.

And now the error is gone... and also, every post on the server. The timelines are empty.

I don't know which command nuked every single post, but I am sad.

**Comment by Kitanit** [comment]
There was an identical error in the docker, I migrated the database (although the changelog did not say so) and actually started the migration and then everything started running as it should
![image](https://user-images.githubusercontent.com/65107731/233582648-5eaf76a6-6ba2-4683-9938-fdd2ae560426.png)

**Comment by ClearlyClaire** [comment]
You were indeed missing `bundle exec rails db:migrate`.

> although the changelog did not say so

You are running development code, not a release, so there is no release note to tell you to run `db:migrate`. But when running on development code, it's a good habit to run these.
