### ISSUE TITLE
a seperator is needed to seperate posts on mastodon feed

### ISSUE THREAD

**Issue by pawanmkr** [mastodon/mastodon#24616]
### Pitch

I was using mastodon but don't like the feed UI. the posts are stacked one after other there should be some space or separator with some space that indicates both the post are not related and are different.

<img width="1440" alt="Screenshot 2023-04-22 at 8 56 34 AM" src="https://user-images.githubusercontent.com/53852047/233759701-b952b3dd-c3de-433f-bf3d-fc85eb1f8f43.png">

### Motivation

i think this feature makes the UI much better and also easy to understand for a new comer.

**Comment by RianQuenlin** [comment]
![image](https://user-images.githubusercontent.com/88654233/233767545-952de752-1717-4fea-8a56-ac34d1ec0507.png)

**Comment by trwnh** [comment]
is the request to have the separator made more prominent? because, as pointed out above, there is already a separator
