### ISSUE TITLE
FATAL:  role "mastodon" does not exist

### ISSUE THREAD

**Issue by LuckyCoders** [mastodon/mastodon#24659]
### Steps to reproduce the problem

1. docker compose run --rm web bundle exec rake mastodon:setup
2. docker compose up
```
live-db-1         | 2023-04-25 22:54:39.026 UTC [93] FATAL:  role "mastodon" does not exist
live-web-1        | Exiting
live-web-1        | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client': FATAL:  role "mastodon" does not exist (ActiveRecord::ConnectionNotEstablished)
```
...

### Expected behaviour

Mastodon runing

### Actual behaviour

exited with code 0

### Detailed description

```
# Redis
# -----
REDIS_HOST=live-redis-1
REDIS_PORT=6379

# PostgreSQL
# ----------
DB_HOST=live-db-1
DB_USER=mastodon
DB_NAME=mastodon_production
DB_PASS=
DB_PORT=5432
```

### Specifications

Mastodon from ghcr.io/mastodon/mastodon

**Comment by ManVTish** [comment]
Hi @LuckyCoders, I believe this is a simple fix, you need to figure out the correct DB_USER value for your environment or create if it's not already created. If your environment is production, then you might want to check with your provider. For local env you can check this [stackoverflow](https://stackoverflow.com/questions/39024056/postgresql-fatal-role-does-not-exist#:~:text=ActiveRecord%3A%3ANoDatabaseError%3A%20FATAL%3A%20role%20Caused%20by%3A%20PG%3A%3AConnectionBad%3A%20FATAL%3A%20role,using%20the%20psql%20client%2C%20as%20the%20postgres%20role%3A) answer.

**Comment by ManVTish** [comment]
If that works, then please close this issue. Thanks.

**Comment by mjankowski** [comment]
Closing on the assumption that no followup means this was resolved -- please reopen with current details/results if not.
