### ISSUE TITLE
/api/v1/notifications limit is not respected, returns more than 30 notifications

### ISSUE THREAD

**Issue by nikclayton** [mastodon/mastodon#24684]
### Steps to reproduce the problem

Fetch notifications, assuming the API respects the documented limits

### Expected behaviour

No more than 30 notifications returned

### Actual behaviour

More than 30 notifications returned

### Detailed description

https://docs.joinmastodon.org/methods/notifications/#query-parameters notes, for the `limit` parameter:

> Integer. Maximum number of results to return. Defaults to 15 notifications. Max 30 notifications.

However, sending the following request:

> GET https://mastodon.social/api/v1/notifications?limit=90

with my bearer token does not return 30 notifications, it returns 90

I am unsure if this is obsolete documentation or a bug in the code.

### Specifications

`mastodon.social`, today. At the time of writing it reports v4.1.2 on the site and via `/api/v2/instance`.

**Comment by ManVTish** [comment]
Hi @nikclayton , I believe that it's an outdated doc rather than problem in the code. As the default number is 40 & max limit can be given as a query parameter. Hence you got 90 records rather than 30. Let me know your thoughts so we can go ahead and close this issue. Thanks.

**Comment by ManVTish** [comment]
Hey @nikclayton if you agree, should I open a PR to fix the doc?

**Comment by nikclayton** [comment]
Yep -- I'm agnostic as to whether this is the code not following the docs or the docs being out of date w.r.t. the code.

If you think a doc PR is the appropriate fix that's all good with me.

**Comment by ManVTish** [comment]
I agree with you. Okay, I'll go ahead and raise a PR to update the doc, I guess we'll find out. Thanks.

**Comment by trwnh** [comment]
the limit was raised in 4.1 to 40/80, so 90 should still be too much -- are you sure you're getting 90?

**Comment by ManVTish** [comment]
Yeah, I realized the max notifications that can be returned is twice of default number of notifications. This would mean:
1) we need documentation changes
2) debugging and fixing the code if it's returning more than 80 (as mentioned by @nikclayton)

Thanks @trwnh

**Comment by ManVTish** [comment]
Hi @trwnh , I'm trying to debug the issue but I guess I'll need data to do so. There is no seeds data for notifications. Meanwhile I'm taking help of test cases (even facing error while running tests related to `Webpacker::Manifest::MissingEntryError`). Any thoughts on data for notifications?
Thanks.

**Comment by trwnh** [comment]
testing on my own account i set a limit of `90` and got back 80 results, so that part seems to not be the case. i guess this issue can be closed

**Comment by ManVTish** [comment]
Okay, cool. Hey @nikclayton can you please take a look again and close this issue if you agree. Thanks.
cc @trwnh

**Comment by ManVTish** [comment]
Hi @nikclayton , I have already created a [PR](https://github.com/mastodon/documentation/pull/1210) to fix the doc. It was reviewed and approved by @trwnh . Thanks.

**Comment by nikclayton** [comment]
Ah sweet, thanks.
