### ISSUE TITLE
PWA Notifications

### ISSUE THREAD

**Issue by HOWTEKNO** [mastodon/mastodon#24710]
### Steps to reproduce the problem

After putting my keys how do I trigger the notifications prompt on iPhone?
I don't seem to get any notifications prompt

### Expected behaviour

prompt to allow notifications 

### Actual behaviour

Nothing 

### Specifications

Calckey
v13.1.4.1
Docker
Reverse Proxy Nginx

**Comment by ThatOneCalculator** [comment]
This is the issue tracker for Mastodon. Calckey is not Mastodon, in fact, it's entirely different software. Here's the issue tracker for Calckey: https://codeberg.org/calckey/calckey/issues
