### ISSUE TITLE
Remove blocks

### ISSUE THREAD

**Issue by SoniEx2** [mastodon/mastodon#24734]
### Pitch

Blocks could simply be removed.

### Motivation

Blocks were created by social media engineers to avoid moderating their platforms. Since mastodon has a lot more moderators, they're not really needed, and if anything they prevent effective moderation. Removing blocks could go a long way to improving mastodon moderation.

**Comment by RianQuenlin** [comment]
Somebody got blocked.

**Comment by SoniEx2** [comment]
we're tired that moderators won't remove assholes because we could "just block them instead".

as if that solves the problem.

**Comment by Wild1145** [comment]
I would suggest that if your moderator / admin is refusing to take appropriate action on those that are breaking server rules or being abusive you should move instance or petition your instance admin to block the remote instance in question. Blocks are exceptionally useful when someone just isn't your cup of tea but ultimately isn't breaking the rules.
