### ISSUE TITLE
Scheduler::SuspendedUserCleanupScheduler backs up the scheduler queue

### ISSUE THREAD

**Issue by supernovae** [mastodon/mastodon#24733]
### Steps to reproduce the problem

I seem to have hit a size/data representation where the "Scheduler::SuspendedUserCleanupScheduler" takes a while to run and backs up all other tasks in the schedular queue - which means trends get delayed, indexing is delayed. Since this is a single threaded queue, other jobs queue up which impact features on mastodon.

### Expected behaviour

Perhaps Scheduler::SuspendedUserCleanupScheduler needs its own queue?

### Actual behaviour

Jobs backup if you run suspensions (which is pretty common suspending Vietnam casino spam)

### Detailed description

The Scheduler::SuspendedUserCleanupScheduler causes the scheduler queue to backup.

![image](https://user-images.githubusercontent.com/1461719/235354135-41bf8559-07fe-4696-a57c-35ad5f431852.png)

### Specifications

Mastodon 4.1.2

**Comment by ElanHasson** [comment]
Same here, except I haven't suspended anyone.

**Comment by verymilan** [comment]
Ah, so I am not alone. :) 
Tho I have not yet understood how to exactly pin it down like this, but I can say that it works the queue down a few jobs when restarted.

**Comment by verymilan** [comment]
I have also noticed strage redis timeouts for at least this queue worker... however measuring redis latency all looks fine.
```
ERROR: Error fetching job: Connection timed out
WARN: Redis::TimeoutError: Connection timed out
WARN: mastodon/live/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/connection/hiredis.rb:59:in `rescue in read
```

So right now i workaround the queue flooding by restarting the affected sidekiq with cron but we noticed never sending scheduled toots due to the timeout.
