### ISSUE TITLE
See result of poll

### ISSUE THREAD

**Issue by pabloscloud** [mastodon/mastodon#24746]
### Pitch

I tried to search it, but didn't find an open issue.

Option to see results and block adding a vote afterwards.

Alternatively always add an extra option to the poll.

### Motivation

Many times I find polls were I can't vote cause I am not in the group of people that are allowed to vote (say only blind people cause of an accessibility question).

Some already add an extra option "See results" so they don't vote to see the otherwise biased results cause they would just vote something to see the results.

**Comment by pabloscloud** [comment]
> For these, i star or bookmark the poll.
> 
> WIth Vyr's advanced search, you can also search via "has:poll keyword"

You might do that but many don't. When I participate in a poll, i get a notification when it ends, but that's not the case for bookmarked or stared toots with polls

**Comment by pabloscloud** [comment]
"See results" is now on the roadmap of the android app 🤔

**Comment by Cassolotl** [comment]
Related: *[Feature request] Option to be notified of poll results for polls you haven't voted in #11092*

**Comment by allo-** [comment]
Another option should be abstention (increase the number of total votes without adding a vote to one of the options), see https://github.com/mastodon/mastodon/issues/25339
