### ISSUE TITLE
Search Opt Out/Opt in feature that federates to other instance 

### ISSUE THREAD

**Issue by TechnicallySky** [mastodon/mastodon#24764]
### Pitch

Add a toggle for search opt in, ideally by default this would be off 

### Motivation

Many people face harassment and trolling from places such as the Kiwi farms, with the addition of search it is my understanding that there is no intent on offering a way of opting out, this could cause an issue as a common method on Twitter was to search people writing styles until they located their Twitter profile. Which made it nearly impossible to use social media. Offering a way to opt out is vital, and better yet to prevent unintended indexing it should be off by default.

**Comment by trwnh** [comment]
- https://github.com/mastodon/mastodon/pull/23808

**Comment by SkyMTF** [comment]
> we think global search should be opt-in but home feed search should be opt-out. (the opt-in is to accept follow requests.)

" (the opt-in is to accept follow requests.)" Are you referring to home feed or global with that comment

**Comment by SoniEx2** [comment]
1. you opt-out of global search
2. you make a post
3. user follows you, you accept follow request
4. you make another post
5. user can search post from step 4, but not post from step 2

global search vs home feed search.

**Comment by SkyMTF** [comment]
> 1. you opt-out of global search
> 2. you make a post
> 3. user follows you, you accept follow request
> 4. you make another post
> 5. user can search post from step 4, but not post from step 2
> 
> global search vs home feed search.

Yeah this makes sense, also a way to have opt out of global search the default. Also maybe opt out for followers too, I have my followers open but don't want global search
