### ISSUE TITLE
Unusual gray seam on all avatars (in light mode only) after last update

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#24791]
### Steps to reproduce the problem

Yesterday Mastodon.social updated to a 4.1.2 which features minor interface differences such as special marking for PMs. I did not use the website yesterday but today I see that there is a one-pixel gray line immediately to the right of all avatars. I see it in both Advanced and non-Advanced mode and I see it in both Chrome and Firefox. I do not see it in dark theme or high contrast theme. I only see it in light theme. It looks unintentional and kinda bad.

![image](https://user-images.githubusercontent.com/277318/235703192-c3bcf556-7cf9-48b2-8ca3-95a9b7d66468.png)

![image](https://user-images.githubusercontent.com/277318/235704277-992dc3ce-98bd-40a2-bdfe-667e1ae23b8b.png)

### Expected behaviour

avatar

### Actual behaviour

gray line

### Detailed description

Based on something I saw on one load, I think this might somehow be the alt text and/or preload rectangle persisting after the avatar is loaded.

### Specifications

Chrome 112.0.5615.138. I was able to reproduce with all browser plugins turned off.

**Comment by ClearlyClaire** [comment]
I think this is the `box-shadow` on `.status__avatar` added in #24549 and which I honestly don't understand the purpose of.
