### ISSUE TITLE
Production assets build should be tested in CI

### ISSUE THREAD

**Issue by renchap** [mastodon/mastodon#24814]
### Pitch

The `assets:precompile` task broke multiple times in the past due to inconsistent `test` vs `production` settings.

For example:
- https://github.com/mastodon/mastodon/pull/24811
- https://github.com/mastodon/mastodon/pull/24374

We should have the CI run the assets precompile step, so those errors are caught before they are merged.

### Motivation

Currently we notice them because the docker image build fails, but this needs to be caught before.

**Comment by nschonni** [comment]
CI already does run the precompile https://github.com/mastodon/mastodon/blob/a2a22bad236868c4f32d30c00eb899d8bb7be64d/.github/workflows/test-ruby.yml#L50

**Comment by nschonni** [comment]
I submitted something to run a prod build as part of CI, but a better approach may be to figure out why `test` is using commonjs https://github.com/mastodon/mastodon/blob/27bafabb647f0d7fb2ace29ce61e8d18f58c5fe0/babel.config.js#L68-L70 instead of behaving like production

**Comment by ClearlyClaire** [comment]
IIRC we used to build production assets in CI a long time ago but switched away from this because it took significantly longer. That being said, considering there have been multiple issues with not caught by CI in the past, it does make sense to build production assets in CI.

**Comment by renchap** [comment]
The minification step is only enabled in `production`, and this indeed takes a long time to build. But this is also the part that seem to fail when modern ES features are used.

Minifying in tests makes it harder to debug, so I am not sure this is a good idea.

**Comment by ClearlyClaire** [comment]
It makes sense to me building as an extra target, as #24839 is doing. The downside is that it's extra work, the upsides are that this extra work does not have to block the other tests that can run in parallel (though I'm not sure how parallel Github workflows are), and that tests do not end up running on minified JS.

**Comment by nschonni** [comment]
From https://github.com/mastodon/mastodon/actions/runs/4884550439?pr=24839 to looks like it's 1m 14s vs 1m 57s for the actual precomple step timings

**Comment by nschonni** [comment]
Outside of the additional CI job, took a quick pass to see about harmonizing the Babel config with  #24854, but it looks like it needs some more updates to support the transforms for the modules used in the testing libraries
