### ISSUE TITLE
Require additional confirmation when blocking a domain

### ISSUE THREAD

**Issue by stefanbohacek** [mastodon/mastodon#24853]
### Pitch

When blocking a domain via the web interface, a warning is shown explaining the severity of this action:

![Domain block confirmation on the web: "Are you really, really sure you want to block the entire mastodon.social? In most cases a few targeted blocks or mutes are sufficient and preferable. You will not see content from that domain in any public timelines or your notifications. Your followers from that domain will be removed.](https://user-images.githubusercontent.com/3909390/236263899-702ab8e9-9fb0-4e6a-889b-9eedb6b16e5d.png)

This warning is not present in the Android app:

![Domain block confirmation on Android: "Confirm to block mastodon.social](https://user-images.githubusercontent.com/3909390/236264000-7de3e3bf-89cf-4456-a383-0b982b8a25c7.png)

The prompt on Android should show the same message. (I would also suggest visually distinguishing this option from the others, as it's fairly easy to tap it by accident, if you want to report an account.)

![Menu from the Android Mastodon app showing options for blocking and muting a user, or blocking a whole domain](https://user-images.githubusercontent.com/3909390/236264052-ddeda886-92e2-4ea7-a02c-a1d803a6d6c5.png)

Considering the consequences of this action, I propose an additional level of confirmation that would require the user to type out the name of the domain as to avoid blocking it by accident.

Here's how it could look on the web.

![A suggested domain block confirmation on the web that now shows an additional input field for the name of the domain you want to block](https://user-images.githubusercontent.com/3909390/236264136-0bdab5f1-617e-4873-bc87-d343b6fa59f7.png)

This is inspired by a similar prompt you see when you delete a code repository on GitHub.

![A dialogue from GitHub prompting the user to type out the name of the project they want to delete.](https://user-images.githubusercontent.com/3909390/236264208-47fb018a-80d7-4e23-92fc-aa032a5cc1e2.png)

### Motivation

I accidentally blocked mastodon.social. Unblocking it doesn't seem to bring back people you follow or your followers.

(Currently I'm reviewing server logs on my self-hosted instance and looking through the database to see if I can find the accounts that were dropped and manually refollowing.)

**Comment by stefanbohacek** [comment]
Here's a thread with other people who experienced this problem, courtesy of @stefanhayden:

https://federate.social/@mattblaze/110318081572887843

**Comment by simon-frankau** [comment]
From a user experience point of view, having a warning around an irreversible action is still not as helpful as making the action reversible, even if there are warnings.

While I don't want to derail this request, which seems relatively cheap and easy to do, I'd like to propose that unblocking restore existing follows etc. (maybe optionally), to see what others think. (I'll probably also have to look into technical feasibility!) If it looks useful, I can raise this as another feature request.

**Comment by ThisIsMissEm** [comment]
![Image](https://github.com/user-attachments/assets/05baf7d2-f783-49b6-93f7-50cf26911d3f)

I believe this is completed as of 4.3.0

**Comment by stefanbohacek** [comment]
@ThisIsMissEm Yes, this is definitely much better!

And the warning in the Android app is more descriptive now. But I think it would be more useful to find out from the wider community if this is still a problem.

Personally, I have learned from making this mistake once.

**Comment by wupatz** [comment]
> .. I think it would be more useful to find out from the wider community if this is still a problem.

I linked a costly accidental domain block in the comments at https://github.com/mastodon/mastodon/issues/27361#issuecomment-2682844481

There I make the case to not show domain blocks at the same level as user blocks unless there is an easy undo.

**Comment by stefanbohacek** [comment]
@wupatz "You have blocked mastodon.social, removing 2,416 of your followers and 33 accounts you follow."

Yikes!
