### ISSUE TITLE
Husky clobbers git hooks directory, causing systems with git-lfs installed to constantly install hooks

### ISSUE THREAD

**Issue by ThisIsMissEm** [mastodon/mastodon#24884]
### Pitch

Replace or remove husky, to prevent it from clobbering the git hooks directory, which breaks git-lfs, since husky insists on the hooks directory being committed to git.

An alternative is [lefthook](https://github.com/evilmartians/lefthook), if the pre-commit hooks are really desired (CI will catch issues anyway, plus you can always configure your editor to run linting tasks to alert you of issues as you work).

### Motivation

Currently the project uses husky to run a few pre-commit hooks for lint-staged; In recent versions of husky, it overrides the location of the git hooks folder from `.git/hooks/` to `.husky`. The integration between git-lfs and git happens via git hooks, so if you have git-lfs installed, then the git-lfs scripts will automatically install into the `.husky` directory which is under version control, this causes git operations to make your local working checkout dirty, and for some operations to fail (e.g., Sourcetree has an embedded git-lfs, so if you stage files in sourcetree, then try to commit via command line where you don't have git-lfs installed, the hooks will crash, preventing commits).

**Comment by ThisIsMissEm** [comment]
Alternatively, we could add the following files to `.gitignore`:

```
.husky/post-checkout
.husky/post-commit
.husky/post-merge
.husky/pre-push
```

As these are added by git-lfs (just by having git-lfs installed on your system)

**Comment by ClearlyClaire** [comment]
cc @nschonni @renchap

**Comment by nschonni** [comment]
Not sure, but a quick search sounds like it's a Sourcetree issue that has existed for awhile rather than something with husky https://stackoverflow.com/a/73653051

**Comment by ThisIsMissEm** [comment]
I've a ticket with Sourcetree & they're working on a fix, but it may still be worth investigating Lefthook as it runs faster (it's a Go binary instead of Node.js program)

**Comment by nschonni** [comment]
No strong feels either way if you want to swap to lefthood. Looking at https://github.com/evilmartians/lefthook/blob/master/docs/install.md#node, just beware with the native binaries, as they can sometimes be a pain with Node with sniffing architectures and switching workspaces between OSs

**Comment by ThisIsMissEm** [comment]
Yeah, but we could also install it with ruby: https://github.com/evilmartians/lefthook/blob/master/docs/install.md#-ruby
