### ISSUE TITLE
Missing service worker for the PWA to be marked installable in Chrome

### ISSUE THREAD

**Issue by darkdragon-001** [mastodon/mastodon#24888]
### Steps to reproduce the problem

1. Open timeline in Google Chrome / Chromium
2. Open More tools > Developer tools
3. Open tab "Lighthouse"
4. Run PWA test

### Expected behaviour

Test passes and app is installable

### Actual behaviour

Test fails and app is not installable

### Detailed description

Test fails with 

> [Does not register a service worker that controls page and `start_url`](https://developer.chrome.com/docs/lighthouse/pwa/service-worker/)

### Specifications

Google Chrome 112.0.5615.165

**Comment by renchap** [comment]
The Service Worker is installed if you are logged-in. If this is the case, then Lighthouse properly reports that the PWA is installable.
