### ISSUE TITLE
Cannot run Mastodon inside a systemd-nspawn container due to overzealous network address syntax req

### ISSUE THREAD

**Issue by jernst** [mastodon/mastodon#24891]
### Steps to reproduce the problem

1. Attempting to run Mastodon 4.1.2 inside a Linux systemd-nspawn container started with -n (local NAT).
2. When attempting to log on after clicking "Log In", a "something went wrong" error is displayed on the web page
3. The system journal says:

```
May 06 21:07:31 ubos-container postgres[22624]: 2023-05-06 21:07:31.322 PDT [22624] ERROR:  invalid input syntax for type inet: "fe80::249a:57ff:fed6:695f%host0/128"
May 06 21:07:31 ubos-container postgres[22624]: 2023-05-06 21:07:31.322 PDT [22624] CONTEXT:  unnamed portal parameter $5 = '...'
May 06 21:07:31 ubos-container postgres[22624]: 2023-05-06 21:07:31.322 PDT [22624] STATEMENT:  INSERT INTO "session_activations" ("session_id", "created_at", "updated_at", "user_agent", "ip", "access_token_id", "user_id") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"
May 06 21:07:31 ubos-container bundle[22583]: [fb8c9ae0-531d-41b3-a8f6-84cfae4bc229] method=POST path=/auth/sign_in format=html controller=Auth::SessionsController action=create status=500 error='ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type inet: "fe80::249a:57ff:fed6:695f%host0/128"
May 06 21:07:31 ubos-container bundle[22583]: CONTEXT:  unnamed portal parameter $5 = '...'
May 06 21:07:31 ubos-container bundle[22583]: ' duration=71.51 view=0.00 db=3.26
May 06 21:07:31 ubos-container bundle[22583]: [fb8c9ae0-531d-41b3-a8f6-84cfae4bc229]
May 06 21:07:31 ubos-container bundle[22583]: [fb8c9ae0-531d-41b3-a8f6-84cfae4bc229] ActiveRecord::StatementInvalid (PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type inet: "fe80::249a:57ff:fed6:695f%host0/128
```

This appears to reference IPv6 address `fe80::249a:57ff:fed6:695f` that is generated by systemd for the host side of the virtual network interface. It appears it isn't expecting the `%host0` that's a relatively new syntax from the Linux kernel I believe. Guess it needs to be chomped off before attempting the insert.

### Expected behaviour

No crash is always nicer

### Actual behaviour

Crash

### Detailed description

See above.

### Specifications

Mastodon 4.1.2
Arch Linux aarch64 as host (under Parallels on macOS on Apple silicon), UBOS (like Arch) in the container -- however, it's unlikely that this problem has anything to do with aarch64 or Arch or UBOS; all newer kernels and systemd should be similar.

**Comment by renchap** [comment]
You have an issue here, as your local-only IPv6 address is seen by Mastodon (Rails) as the source IP for the user, and this is most probably incorrect.

You should set [`ALLOWED_PRIVATE_ADDRESSES`](https://docs.joinmastodon.org/admin/config/#allowed_private_addresses) so Rails uses the proper IP address for your users.

**Comment by jernst** [comment]
Running into this again, and attempting to follow the advice.  I added to `.env.production`:

```
ALLOWED_PRIVATE_ADDRESSES=::/0
```

rebooted all daemons, but no change in behavior. Is that one of the supported ways that setting is supposed to be changed?

I'm noticing that the stack trace with the problem seems related to `ActiveRecord` and not to the code in `request.rb` that appears to not let certain requests in by checking, among other things, `ALLOWED_PRIVATE_ADDRESSES`.

**Comment by renchap** [comment]
Well, there are 2 issues here:
- PostgreSQL's `inet` column type does not accept the `%host0` part of the IP address
- But Mastodon sees the user's IP as `fe80::249a:57ff:fed6:695f%host0/128`, which is a link-local address, and this should not be the case.

… and I just saw my mistake above, you should not use `ALLOWED_PRIVATE_ADDRESSES` (which is for outbound request), but [`TRUSTED_PROXY_IP`](https://docs.joinmastodon.org/admin/config/#trusted_proxy_ip).

You can set it to `fe80::/10` (potentially in addition to other expected values from the default) and see if it fixes the issue?

**Comment by jernst** [comment]
It does! Not sure how, but that's okay :-) ty!!

**Comment by renchap** [comment]
You can check this is working properly by signing into your instance, then Preferences > Account, and ensure that the IP logged for your session is your public IP address.

**Comment by renchap** [comment]
This will cause issues with rate-limiting and security. You should try adding `127.0.0.1` to `TRUSTED_PROXY_IP`.

**Comment by jernst** [comment]
I'm failing to specify both of these values. The regex seems to say: separate with space and/or comma, so I tried

```
TRUSTED_PROXY_IP=fe80::/10 127.0.0.1
```

but the effect is the same as if I hadn't specified the setting at all. This works:

```
TRUSTED_PROXY_IP=fe80::/10
```
