### ISSUE TITLE
Custom invite_request: does no longer work

### ISSUE THREAD

**Issue by eWalthert** [mastodon/mastodon#24950]
### Steps to reproduce the problem

We changed "Why do you want to join? *" to a more specific message.
This was changes on line 130 inside `simple_form.en.yml`.

After we are getting messages like "Twitter is broken", "I need to get of Twitter" again, I checked and the message is back to default. Checking `simple_form.en.yml` our message is still there. I also changed `simple_form.en-GB.yml`, but it remains default.

This is most likely the case since the last update, but nobody has realised it.

### Expected behaviour

Custom invite request.

### Actual behaviour

Standard invite request: Why do you want to join? *

### Specifications

Mastodon 4.1.2
Ruby  2.7.0p0
PostgreSQL 15.2
Redis  5.0.7

**Comment by eWalthert** [comment]
@aaaaalbert thanks for pointing me the way. Indeed the edit is on line 270, `nano` chopped the file, therefore my wrong count. I don’t really know what I’m doing when using `RAILS_ENV=production bundle exec rake mastodon:setup`, so I will check in with my brother, that set up the server and instance in the frist place.

**Comment by aaaaalbert** [comment]
> I don’t really know what I’m doing when using `RAILS_ENV=...`

I feel you :-)

If you don't mind a few days delay, I will check my shell history for the exact steps that I took back then. I discovered them GitHub-searching my way through the issue tracker and old PRs, so the info is *somewhere* in here, but I forgot to note it down separately. If if find them, I will suggest them for addition to the Mastodon docs.

**Comment by aaaaalbert** [comment]
Sure sure, no worries. (I can't promise that it will help in your case, anyway ;-)

**Comment by aaaaalbert** [comment]
The good news first: I found [the hint](https://github.com/mastodon/mastodon/issues/21067#issuecomment-1321943075) again. The idea is to `clobber` the assets first, then `recompile` them again from the `live` directory in your Mastodon user account:

`RAILS_ENV=production bundle exec rails assets:clobber && RAILS_ENV=production bundle exec rails assets:precompile`

The actions are explained when you run Rails with the `--tasks` command line switch like this:

```
:~/live$ RAILS_ENV=production bundle exec rails --tasks
# ...
rails assets:clean[keep]                   # Remove old compiled assets
rails assets:clobber                       # Remove compiled assets
rails assets:environment                   # Load asset compile environment
rails assets:generate_static_pages         # Generate static pages
rails assets:precompile                    # Compile all the assets named in config.assets.precompile
# ...
```

The semi-bad news: This didn't suffice to cause a change to `simple_form.en.yml` be visible in my instance. (I didn't try with the setting you wanted to change though, so YMMV.) I have to say that I'm not exactly well informed how the settings from the `yml` file are supposed to end up in the various places of the web page either.

Finally: Look was suggested as an enhancement in #21281 already :-) Maybe there is hope for a GUI-level implementation. Sorry that none of this is a short term fix for your problem.

**Comment by ThisIsMissEm** [comment]
Have started work on a solution here: https://github.com/mastodon/mastodon/pull/31702

**Comment by ClearlyClaire** [comment]
Closing. This is an invalid issue. For the related feature request, see #21281

In the meantime, I believe the string you want to change is `auth.sign_up.manual_review` in `config/locales/en.yml`
