### ISSUE TITLE
Web frontend on touch devices: give users a way to know if media attached to posts have descriptions

### ISSUE THREAD

**Issue by pezcurrel** [mastodon/mastodon#24967]
### Pitch

I think it would be very useful if the web frontend, on touch devices, gave users a way to know if media attached to posts have descriptions.

### Motivation

Currently, when using the official Mastodon web frontend on touch devices, there is no way for users to know if a media attached to a post has or has not a description, so they can't decide what to do if description is missing (boost or not, add description in a reply, and so on - see https://fedi.tips/how-do-i-make-posts-more-accessible-to-blind-people-on-mastodon-and-the-fediverse/).

**Comment by Gargron** [comment]
Fixed by #24782
