### ISSUE TITLE
Lists without Boosts

### ISSUE THREAD

**Issue by mogoh** [mastodon/mastodon#25009]
### Pitch

This feature suggestion is, that one should be able to disable/hide boosts from certaint lists.

### Motivation

I have some friends, that I follow, that only toot from time to time, that I won't want to miss.
I could put them all in a list and disable their boosts all together, but that is not what I want.
I just want to open a list to see what they tooted today.
I haven't found the possibility to do that.

**Comment by risa-spirelli** [comment]
Duplicate of https://github.com/mastodon/mastodon/issues/11506
