### ISSUE TITLE
`lint-staged` launches Rubocop on ignored files

### ISSUE THREAD

**Issue by renchap** [mastodon/mastodon#25038]
### Steps to reproduce the problem

1. Edit a file that should be ignored by Rubocop
2. `git add <file>`
3. `git commit`

### Expected behaviour

Rubocop should not be run on this file

### Actual behaviour

`lint-staged` runs Rubocop on the file, and the commit fails

### Specifications

Occurs on `main`

**Comment by renchap** [comment]
@nschonni do you know if there is an easy way to handle this?

**Comment by nschonni** [comment]
Can you give me a specific reproduction so I can try it locally?

**Comment by ClearlyClaire** [comment]
> Can you give me a specific reproduction so I can try it locally?

Make any change to e.g. `db/schema.rb` and watch the commit hook erroring out.

**Comment by nschonni** [comment]
Thanks @ClearlyClaire I'll give that a try. As a temporary thing, you can use `--no-verify` when committing from the command line to skip checks (if you didn't already know that)

**Comment by nschonni** [comment]
@ClearlyClaire I was able to reproduce it with that file! Found a flag that makes `lint-staged` happy

**Comment by drewlustro** [comment]
For those wondering, it's `--force-exclusion` 🤦
