### ISSUE TITLE
`Identity.destroy` should not destroy the `User` and `Account` it points to.

### ISSUE THREAD

**Issue by defnull** [mastodon/mastodon#25066]
### Steps to reproduce the problem

1. Let a user login via some SSO mechanism (e.g. OpenID Connect). This creates a new `Identity -> User -> Account` chain.
2. Add another `Identity` manually to allow a second person to manage the same mastodon profile (e.g. to have someone manage a public profile while the original owner is on vacation). Having multiple identities point to the same `User` works just fine, those are one-directional one-to-one connections. This may also happen if another SSO login has the same primary email address, because Mastodon maps new SSO logins to existing `User` records based on email, if such a user exists already.
3. One of the users now has different duties, so you open a console, find the `Identity` matching their SSO identity and destroy it.
5. Realize in horror that the associated `User` and `Account` entries are now gone, with no way to recover.

### Expected behaviour

Deleting an `Identity` should not destroy the associated `User`, just detach it from an SSO account.

### Actual behaviour

Deleting an `Identity` destroys the `User` it points to, even if there may be other identities pointing to the same `User` record, or if the user also has a password and could still login without SSO.

### Detailed description

The `Identity` model exists to map an SSO login to a mastodon user and account. It represents a one-directional connection from SSO identity to `User`. There can be multiple identities pointing to the same user (e.g. because Mastodon auto-assigned a new identity to an existing user based on the email address). So, deleting an `Identity` should just remove the association between SSO login and `User`, and NOT destroy the `User` record and everything connected to it.

### Specifications

Mastodon 4.1.2

**Comment by ClearlyClaire** [comment]
> Add another `Identity` manually to allow a second person to manage the same mastodon profile (e.g. to have someone manage a public profile while the original owner is on vacation). Having multiple identities point to the same `User` works just fine, those are one-directional one-to-one connections. This may also happen if another SSO login has the same primary email address, because Mastodon maps new SSO logins to existing `User` records based on email, if such a user exists already.

That is not an explicitly supported feature, but that makes sense and should indeed work.

> Realize in horror that the associated `User` and `Account` entries are now gone, with no way to recover.

It does destroy the `User` record, which can be an issue, as that holds settings, backups and a few other things, but it should not destroy the `Account`.
