### ISSUE TITLE
Links to external sites should always open in a new tab or window

### ISSUE THREAD

**Issue by csu** [mastodon/mastodon#2514]
If clicking on a username, tag, etc. is going to leave the Masto web interface, it should open the link in a new tab instead of the current one. 

For example, sometimes clicking on a username opens it in the third pane and sometimes it leaves the UI (and I lose my place). It's not really clear when it uses which behavior, so it should always open external links in new tabs/windows.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
i'm pretty sure external links have `target=_blank` added to them now
