### ISSUE TITLE
Link is not recognized as a link due to url parameters

### ISSUE THREAD

**Issue by Jelfff** [mastodon/mastodon#25150]
### Steps to reproduce the problem

I included the following link in my post.  The url parameters tell an ArcGIS server to restyle the data so it appears on the map as a red line.

https://mappingsupport.com/p2/gissurfer.php?center=39.675352,-105.207825&zoom=12&basemap=USA_basemap&overlay=TrailsSegment&data=overlay^name=TrailsSegment^url=https://partnerships.nationalmap.gov/arcgis/rest/services/USGSTrails/MapServer^layers=0^dynamicLayers=[{"ID":0,"source":{"type":"mapLayer","mapLayerId":0},"drawingInfo":{"renderer":{"type":"simple","symbol":{"type":"esriSLS","style":"esriSLSSolid","color":[255,0,0,255],"width":1.2}},"showLabels":false}}]

Here is another example of a link that Mastodon did not correctly recognize.  The data file on Google Drive is a GPX file.
https://mappingsupport.com/p2/gissurfer.php?basemap=USA_scanned_topo&data=Bandera.gpx^https://drive.google.com/uc?id=1TVj3kiCIp7BKjSvGzDmkGEs-EniOCWGD

### Expected behaviour

The link should have been recognized as a link.

### Actual behaviour

Mastodon did not correctly recognize the link.

### Detailed description

I had to use a short link in my post.  This link will open the map and display the trail data.
https://bit.ly/3iPNJ3n 

### Specifications

Mastodon v4.1.2
Using Firefox 113.0.2

**Comment by renchap** [comment]
This seems to be caused by the caret in search params. Those are not handled in `twitter-text`, which is used to parse status content.

I submitted a tentative fix.

**Comment by Jelfff** [comment]
Thank you renchap!

**Comment by Jelfff** [comment]
Thank you ClearlyClaire!
