### ISSUE TITLE
Some settings are not exposed through the API

### ISSUE THREAD

**Issue by grishka** [mastodon/mastodon#25158]
### Pitch

Some important account settings can only be changed through the web app, or I can't find where they are in the API.

For example:
- opt out of search indexing
- disclose application used to send posts
- filter languages
- whether the followers and following lists are hidden
- there's probably more that I didn't notice

In the web app, the section where these settings are changed doesn't use the API, it's a server-side-rendered page:
![Снимок экрана 2023-05-29 в 14 42 01](https://github.com/mastodon/mastodon/assets/1478258/d883816e-f28b-4e58-87f3-07d60bffa8b5)

### Motivation

Client apps would be able to offer a more complete experience if the API matches the features available on the web.

**Comment by grishka** [comment]
Actually, there isn't even any kind of `POST`/`PATCH` corresponding to `GET /api/v1/preferences` 😭

**Comment by trwnh** [comment]
Yep... #7021

**Comment by andypiper** [comment]
Thanks, let's close this in favour of the existing issue #7021 (duplicate)

**Comment by andypiper** [comment]
(to be clear - closed as dupe, not necessarily as not planned)
