### ISSUE TITLE
Admin API

### ISSUE THREAD

**Issue by dasoran** [mastodon/mastodon#2517]
I would like Admin API because I would like to proceed report users in SmartPhone App.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by jabyrd3** [comment]
i would love to be able to fetch a list of domain blocks and make new instance-wide domain blocks, as well. It looks like the api currently only supports adding domain_blocks specific to a single user.

**Comment by t-aus-m** [comment]
I would love to see some kind of admin API implemented since right now, moderating on mobile is quite the pain.

**Comment by trwnh** [comment]
Isn't this `/api/v1/admin`? Also #10741 is a duplicate
