### ISSUE TITLE
Scheduler::FollowRecommendationsScheduler takes days and reads over 24TB from db

### ISSUE THREAD

**Issue by garyx** [mastodon/mastodon#25191]
### Steps to reproduce the problem

1. Run the Scheduler::FollowRecommendationsScheduler scheduled query and it takes at least 27 hours to run, it's a daily scheduled query so they pile up on the DB and slow it down. 

```
EXPLAIN (analyze, buffers) SELECT
  account_id,
  sum(rank) AS rank,
  array_agg(reason) AS reason
FROM (
  SELECT
    account_summaries.account_id AS account_id,
    count(follows.id) / (1.0 + count(follows.id)) AS rank,
    'most_followed' AS reason
  FROM follows
  INNER JOIN account_summaries ON account_summaries.account_id = follows.target_account_id
  INNER JOIN users ON users.account_id = follows.account_id
  LEFT OUTER JOIN follow_recommendation_suppressions ON follow_recommendation_suppressions.account_id = follows.target_account_id
  WHERE users.current_sign_in_at >= (now() - interval '30 days')
    AND account_summaries.sensitive = 'f'
    AND follow_recommendation_suppressions.id IS NULL
  GROUP BY account_summaries.account_id
  HAVING count(follows.id) >= 5
  UNION ALL
  SELECT account_summaries.account_id AS account_id,
         sum(status_stats.reblogs_count + status_stats.favourites_count) / (1.0 + sum(status_stats.reblogs_count + status_stats.favourites_count)) AS rank,
         'most_interactions' AS reason
  FROM status_stats
  INNER JOIN statuses ON statuses.id = status_stats.status_id
  INNER JOIN account_summaries ON account_summaries.account_id = statuses.account_id
  LEFT OUTER JOIN follow_recommendation_suppressions ON follow_recommendation_suppressions.account_id = statuses.account_id
  WHERE statuses.id >= ((date_part('epoch', now() - interval '30 days') * 1000)::bigint << 16)
    AND account_summaries.sensitive = 'f'
    AND follow_recommendation_suppressions.id IS NULL
  GROUP BY account_summaries.account_id
  HAVING sum(status_stats.reblogs_count + status_stats.favourites_count) >= 5
) t0
GROUP BY account_id
ORDER BY rank DESC;
                                                                                                           QUERY PLAN                                                                                                           
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Sort  (cost=3593985.86..3593985.87 rows=2 width=72) (actual time=112104413.401..112104415.499 rows=29919 loops=1)
   Sort Key: (sum((((count(follows.id))::numeric / (1.0 + (count(follows.id))::numeric))))) DESC
   Sort Method: quicksort  Memory: 4976kB
   Buffers: shared hit=31839911 read=3294071 dirtied=1025 written=26, temp read=3130289577 written=9879
   ->  GroupAggregate  (cost=10126.46..3593985.85 rows=2 width=72) (actual time=148491.041..112104235.557 rows=29919 loops=1)
         Group Key: account_summaries.account_id
         Buffers: shared hit=31839911 read=3294071 dirtied=1025 written=26, temp read=3130289577 written=9879
         ->  Merge Append  (cost=10126.46..3593985.81 rows=2 width=72) (actual time=148490.251..112103838.120 rows=32478 loops=1)
               Sort Key: account_summaries.account_id
               Buffers: shared hit=31839911 read=3294071 dirtied=1025 written=26, temp read=3130289577 written=9879
               ->  GroupAggregate  (cost=9122.61..9122.65 rows=1 width=72) (actual time=1817.853..2186.162 rows=3758 loops=1)
                     Group Key: account_summaries.account_id
                     Filter: (count(follows.id) >= 5)
                     Rows Removed by Filter: 28965
                     Buffers: shared hit=1763449
                     ->  Sort  (cost=9122.61..9122.62 rows=1 width=16) (actual time=1817.759..2142.309 rows=112103 loops=1)
                           Sort Key: account_summaries.account_id
                           Sort Method: quicksort  Memory: 8327kB
                           Buffers: shared hit=1763449
                           ->  Nested Loop  (cost=1003.69..9122.60 rows=1 width=16) (actual time=697.050..1780.184 rows=112103 loops=1)
                                 Buffers: shared hit=1763449
                                 ->  Nested Loop  (cost=1003.40..9122.27 rows=1 width=24) (actual time=697.011..1373.967 rows=206956 loops=1)
                                       Buffers: shared hit=1185772
                                       ->  Gather  (cost=1002.98..9121.80 rows=1 width=24) (actual time=696.976..733.408 rows=323601 loops=1)
                                             Workers Planned: 2
                                             Workers Launched: 2
                                             Buffers: shared hit=6543
                                             ->  Hash Left Join  (cost=2.98..8121.70 rows=1 width=24) (actual time=326.534..403.155 rows=107867 loops=3)
                                                   Hash Cond: (follows.target_account_id = follow_recommendation_suppressions.account_id)
                                                   Filter: (follow_recommendation_suppressions.id IS NULL)
                                                   Rows Removed by Filter: 790
                                                   Buffers: shared hit=6543
                                                   ->  Parallel Seq Scan on follows  (cost=0.00..7764.62 rows=134862 width=24) (actual time=0.013..39.284 rows=108657 loops=3)
                                                         Buffers: shared hit=6416
                                                   ->  Hash  (cost=1.88..1.88 rows=88 width=16) (actual time=326.390..326.392 rows=88 loops=3)
                                                         Buckets: 1024  Batches: 1  Memory Usage: 13kB
                                                         Buffers: shared hit=3
                                                         ->  Seq Scan on follow_recommendation_suppressions  (cost=0.00..1.88 rows=88 width=16) (actual time=326.333..326.358 rows=88 loops=3)
                                                               Buffers: shared hit=3
                                       ->  Index Scan using index_account_summaries_on_account_id on account_summaries  (cost=0.42..0.47 rows=1 width=8) (actual time=0.002..0.002 rows=1 loops=323601)
                                             Index Cond: (account_id = follows.target_account_id)
                                             Filter: (NOT sensitive)
                                             Rows Removed by Filter: 0
                                             Buffers: shared hit=1179229
                                 ->  Index Scan using index_users_on_account_id on users  (cost=0.29..0.33 rows=1 width=8) (actual time=0.002..0.002 rows=1 loops=206956)
                                       Index Cond: (account_id = follows.account_id)
                                       Filter: (current_sign_in_at >= (now() - '30 days'::interval))
                                       Rows Removed by Filter: 0
                                       Buffers: shared hit=577677
               ->  GroupAggregate  (cost=1003.84..3584863.11 rows=1 width=72) (actual time=146672.394..112101579.780 rows=28720 loops=1)
                     Group Key: account_summaries_1.account_id
                     Filter: (sum((status_stats.reblogs_count + status_stats.favourites_count)) >= '5'::numeric)
                     Rows Removed by Filter: 66058
                     Buffers: shared hit=30076462 read=3294071 dirtied=1025 written=26, temp read=3130289577 written=9879
                     ->  Nested Loop  (cost=1003.84..3584863.08 rows=1 width=24) (actual time=145893.640..112099524.392 rows=1407861 loops=1)
                           Join Filter: (statuses.account_id = account_summaries_1.account_id)
                           Rows Removed by Join Filter: 754156458891
                           Buffers: shared hit=30076462 read=3294071 dirtied=1025 written=26, temp read=3130289577 written=9879
                           ->  Index Scan using index_account_summaries_on_account_id on account_summaries account_summaries_1  (cost=0.42..10079.65 rows=316791 width=8) (actual time=0.029..3644.349 rows=316864 loops=1)
                                 Filter: (NOT sensitive)
                                 Rows Removed by Filter: 3818
```

![image](https://github.com/mastodon/mastodon/assets/1842280/af345737-94fd-4588-81a1-944e5a594334)

### Expected behaviour

The query should not take so long and read the DB for TB of data

### Actual behaviour

The query takes a long time to run and is reading TB of data

### Detailed description

I started seeing Scheduler::FollowRecommendationsScheduler piling up as a scheduled query in sidekiq and a lot of the qureies being run at the same time I ended up having to kill them manually. 

So I start looking into the query and run it manually and the query did finish roughly 27 hours later.  Running the query with EXPLAIN( buffers, analyze) I see that this query is if I am reading the results right reading 24TB of data out of the DB. 

### Specifications

mastodon 4.1.2

**Comment by ClearlyClaire** [comment]
There are a few things that seem odd and inefficient, but the main one is the part where it looks at recent posts: it seems like it goes through *all* statuses and filtering a posteriori instead of using the adequate indexes…

Can you share the output of `\d+ statuses`? Also, did you recently do any unusual database operation?

**Comment by garyx** [comment]
> There are a few things that seem odd and inefficient, but the main one is the part where it looks at recent posts: it seems like it goes through _all_ statuses and filtering a posteriori instead of using the adequate indexes…
> 
> Can you share the output of `\d+ statuses`? Also, did you recently do any unusual database operation?

Hi @ClearlyClaire 

There shouldn't have been any unusual database operations that we know of. We have only been upgrading the db schema through the mastodon upgrades and we have gone through the config on the db server and we did not spot any thing there or in the logs.  



`# \d+ statuses
                                                                         Table "public.statuses"
            Column            |            Type             | Collation | Nullable |            Default             | Storage  | Compression | Stats target | Description 
------------------------------+-----------------------------+-----------+----------+--------------------------------+----------+-------------+--------------+-------------
 id                           | bigint                      |           | not null | timestamp_id('statuses'::text) | plain    |             |              | 
 uri                          | character varying           |           |          |                                | extended |             |              | 
 text                         | text                        |           | not null | ''::text                       | extended |             |              | 
 created_at                   | timestamp without time zone |           | not null |                                | plain    |             |              | 
 updated_at                   | timestamp without time zone |           | not null |                                | plain    |             |              | 
 in_reply_to_id               | bigint                      |           |          |                                | plain    |             |              | 
 reblog_of_id                 | bigint                      |           |          |                                | plain    |             |              | 
 url                          | character varying           |           |          |                                | extended |             |              | 
 sensitive                    | boolean                     |           | not null | false                          | plain    |             |              | 
 visibility                   | integer                     |           | not null | 0                              | plain    |             |              | 
 spoiler_text                 | text                        |           | not null | ''::text                       | extended |             |              | 
 reply                        | boolean                     |           | not null | false                          | plain    |             |              | 
 language                     | character varying           |           |          |                                | extended |             |              | 
 conversation_id              | bigint                      |           |          |                                | plain    |             |              | 
 local                        | boolean                     |           |          |                                | plain    |             |              | 
 account_id                   | bigint                      |           | not null |                                | plain    |             |              | 
 application_id               | bigint                      |           |          |                                | plain    |             |              | 
 in_reply_to_account_id       | bigint                      |           |          |                                | plain    |             |              | 
 poll_id                      | bigint                      |           |          |                                | plain    |             |              | 
 deleted_at                   | timestamp without time zone |           |          |                                | plain    |             |              | 
 edited_at                    | timestamp without time zone |           |          |                                | plain    |             |              | 
 trendable                    | boolean                     |           |          |                                | plain    |             |              | 
 ordered_media_attachment_ids | bigint[]                    |           |          |                                | extended |             |              | 
Indexes:
    "statuses_pkey" PRIMARY KEY, btree (id)
    "index_statuses_20190820" btree (account_id, id DESC, visibility, updated_at) WHERE deleted_at IS NULL
    "index_statuses_local_20190824" btree (id DESC, account_id) WHERE (local OR uri IS NULL) AND deleted_at IS NULL AND visibility = 0 AND reblog_of_id IS NULL AND (NOT reply OR in_reply_to_account_id = account_id)
    "index_statuses_on_account_id" btree (account_id)
    "index_statuses_on_deleted_at" btree (deleted_at) WHERE deleted_at IS NOT NULL
    "index_statuses_on_in_reply_to_account_id" btree (in_reply_to_account_id) WHERE in_reply_to_account_id IS NOT NULL
    "index_statuses_on_in_reply_to_id" btree (in_reply_to_id) WHERE in_reply_to_id IS NOT NULL
    "index_statuses_on_reblog_of_id_and_account_id" btree (reblog_of_id, account_id)
    "index_statuses_on_uri" UNIQUE, btree (uri text_pattern_ops) WHERE uri IS NOT NULL
    "index_statuses_public_20200119" btree (id DESC, account_id) WHERE deleted_at IS NULL AND visibility = 0 AND reblog_of_id IS NULL AND (NOT reply OR in_reply_to_account_id = account_id)
Foreign-key constraints:
    "fk_9bda1543f7" FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
    "fk_c7fa917661" FOREIGN KEY (in_reply_to_account_id) REFERENCES accounts(id) ON DELETE SET NULL
    "fk_rails_256483a9ab" FOREIGN KEY (reblog_of_id) REFERENCES statuses(id) ON DELETE CASCADE
    "fk_rails_94a6f70399" FOREIGN KEY (in_reply_to_id) REFERENCES statuses(id) ON DELETE SET NULL
Referenced by:
    TABLE "favourites" CONSTRAINT "fk_b0e856845e" FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE CASCADE
    TABLE "bookmarks" CONSTRAINT "fk_rails_11207ffcfd" FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE CASCADE
    TABLE "statuses" CONSTRAINT "fk_rails_256483a9ab" FOREIGN KEY (reblog_of_id) REFERENCES statuses(id) ON DELETE CASCADE
    TABLE "custom_filter_statuses" CONSTRAINT "fk_rails_2f6d20c0cf" FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE CASCADE
    TABLE "polls" CONSTRAINT "fk_rails_3e0d9f1115" FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE CASCADE
    TABLE "media_attachments" CONSTRAINT "fk_rails_3ec0cfdd70" FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE SET NULL
    TABLE "status_stats" CONSTRAINT "fk_rails_4a247aac42" FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE CASCADE
    TABLE "mentions" CONSTRAINT "fk_rails_59edbe2887" FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE CASCADE
    TABLE "status_pins" CONSTRAINT "fk_rails_65c05552f1" FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE CASCADE
    TABLE "status_trends" CONSTRAINT "fk_rails_68c610dc1a" FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE CASCADE
    TABLE "statuses" CONSTRAINT "fk_rails_94a6f70399" FOREIGN KEY (in_reply_to_id) REFERENCES statuses(id) ON DELETE SET NULL
    TABLE "status_edits" CONSTRAINT "fk_rails_a960f234a0" FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE CASCADE
    TABLE "statuses_tags" CONSTRAINT "fk_rails_df0fe11427" FOREIGN KEY (status_id) REFERENCES statuses(id) ON DELETE CASCADE
Access method: heap
`

**Comment by garyx** [comment]
> Could you post a link with your explain & query on this website: https://explain.dalibo.com
> 
> (using the `EXPLAIN` query they show)
> 
> Thanks!

Sure, just give me three or so days. I'll post it when it's done.

**Comment by renchap** [comment]
> > Could you post a link with your explain & query on this website: https://explain.dalibo.com
> > (using the `EXPLAIN` query they show)
> > Thanks!
> 
> Sure, just give me three or so days. I'll post it when it's done.

I feel you!

We have been able to reproduce this on mastodon.social and I am gathering the explain plan from there so we have something easier to work with.

The issue seems to come from postgres doing a full join of `statuses x account_summaries`, creating nearly 1000 billion rows to then filter out.

We are not sure yet why postgres is using this plan, but this is definitely not normal and we will improve this query.

**Comment by renchap** [comment]
For your case, it looks like the postgres planner is not choosing the correct plan, which makes this heavy query a lot heavier.

Could you send the output for:

```sql
SELECT
  schemaname, relname, last_autoanalyze, last_analyze 
FROM
  pg_stat_all_tables 
WHERE 
  relname IN ('statuses', 'status_stats', 'account_summaries');
```

**Comment by renchap** [comment]
Ok thanks. What postgres version are you running?

Your issue comes from this in the plan:
`Rows Removed by Join Filter: 754156458891`

I am not sure why it is doing this as your statistics are not *that* out of date.

FYI, on mastodon.social (which most probably has more data than your instance?) this query runs in about 8 minutes, but has a different plan.

**Comment by garyx** [comment]
> Ok thanks. What postgres version are you running?
> 
> Your issue comes from this in the plan: `Rows Removed by Join Filter: 754156458891`
> 
> I am not sure why it is doing this as your statistics are not _that_ out of date.
> 
> FYI, on mastodon.social (which most probably has more data than your instance?) this query runs in about 8 minutes, but has a different plan.

Our instance is quite big at social.vivaldi.net, the statuses table has reached 43GB and this query takes forever to pass through that amount of data.

**Comment by renchap** [comment]
> > Ok thanks. What postgres version are you running?
> > Your issue comes from this in the plan: `Rows Removed by Join Filter: 754156458891`
> > I am not sure why it is doing this as your statistics are not _that_ out of date.
> > FYI, on mastodon.social (which most probably has more data than your instance?) this query runs in about 8 minutes, but has a different plan.
> 
> Our instance is quite big at social.vivaldi.net, the statuses table has reached 43GB and this query takes forever to pass through that amount of data.

How many statuses do you have?

`SELECT reltuples AS estimate FROM pg_class WHERE relname = 'statuses';`

Also by any chance, are you on the server owner/Patron Discord server (or interested in joining it)? This would help debugging this :)

You can shoot me an email or a Mastodon DM if you want an invite link.

**Comment by garyx** [comment]
Here is the result 

```
# SELECT reltuples AS estimate FROM pg_class WHERE relname = 'statuses';

   estimate    
---------------
 5.4122572e+07
(1 row)
```

**Comment by garyx** [comment]
I have already disabled the scheduler some time ago so that's not an issue. 

Check this link for the visualizer

https://explain.dalibo.com/plan/aegb5587859994ff
