### ISSUE TITLE
Disable right click and other easy saves on images

### ISSUE THREAD

**Issue by ch3252** [mastodon/mastodon#25200]
### Pitch

Disabling right click and other options to save images in Mastodon will help all image creators control who uses their images and for what purpose. Right now, it's too easy for someone to save an image and then pretend it's theirs. That was a major problem over on Twitter. Vero has solved it and I respectfully ask that Mastodon does the same. This isn't something that can be done by a third party using the REST API.

### Motivation

All image creators will benefit by having additional security that their images won't be stolen.

**Comment by daprice** [comment]
“All image creators will benefit”? I sometimes post images that I want people to save and use, and I’m sure others do as well. Why should your “right” to control what other people do override my right to share things that I want shared, on a platform that’s about sharing?

**Comment by Gargron** [comment]
I have no plans to build DRM into Mastodon.
