### ISSUE TITLE
Mastodon users are federated with empty name field

### ISSUE THREAD

**Issue by Nutomic** [mastodon/mastodon#25233]
### Steps to reproduce the problem

1. Run `curl -H 'Accept: application/activity+json' https://social.tchncs.de/@ivanhoe | jq`
2. Check value of `name` field
3. Notice that it is `""` (empty string)

### Expected behaviour

If the user didnt set a name, the field should be set to null instead, or not be set at all

### Actual behaviour

It is set to empty string

### Detailed description

This adds unnecessary complications for other platforms that federate with Mastodon because its necessary to check the name value manually.

https://github.com/LemmyNet/lemmy/pull/2887

### Specifications

Mastodon v4.1.2

**Comment by ClearlyClaire** [comment]
That does not sound *wrong* but I agree having it unset or `null` would make more sense.

I'm slightly afraid the change might break some third-party software though, although that seems fairly unlikely.

**Comment by Nutomic** [comment]
You could also fallback to set `preferredUsername` value as `name` if the latter is empty. This seems to be the default behaviour for new accounts.
