### ISSUE TITLE
Lack of EXIF metadata stripping

### ISSUE THREAD

**Issue by Eriner** [mastodon/mastodon#25262]
### Steps to reproduce the problem

upload picture with iOS or desktop web client.

https://noagendasocial.com/@eriner/110483127773047527

Download image and examine EXIF metadata.

### Expected behaviour

exif metadat should be stripped

### Actual behaviour

exif metadata is not stripped

### Specifications

iOS app and desktop client.

**Comment by Eriner** [comment]
Maybe related? https://github.com/mastodon/mastodon/pull/23726

**Comment by Eriner** [comment]
Example from mastodon.social: https://files.mastodon.social/media_attachments/files/110/480/757/835/036/672/original/7e904616a725d998.jpeg

**Comment by Gargron** [comment]
Which metadata is it not stripping? I can't see any when I download your examples. If it's the color profile, that's supposed to not be stripped so the colors remain accurate.

**Comment by Eriner** [comment]
From the mastodon.social link above:

![](https://static.noagendasocial.com/media_attachments/files/110/483/297/322/655/364/original/9a76bb29a1c0216a.png)

**Comment by Gargron** [comment]
That's the color profile. It needs to be there or the colors will be washed out.

**Comment by Eriner** [comment]
I haven't found any images with GPS coords or anything yet, but I've only checked 2 or 3 images.

**Comment by Eriner** [comment]
I tested images with GPS coordinates and the GPS coordinates were correctly stripped from the exif metadata. Sorry for the noise.
