### ISSUE TITLE
Autocomplete results (@ / #) cut off in compose form

### ISSUE THREAD

**Issue by llamacucumber** [mastodon/mastodon#25263]
### Steps to reproduce the problem

1. Click on the compose form on a server running the latest build of Mastodon. This can be reproduced on Mastodon Social as of June 4th.
2. Try to autocomplete a username or a hash tag by typing @nm or #cat 
3. The results are cut off, only one or less than one has room to display

### Expected behaviour

Four autocomplete results should appear

### Actual behaviour

One autocomplete result appeared

### Detailed description

<img width="346" alt="image" src="https://github.com/mastodon/mastodon/assets/18673584/cf9cfd15-ca01-4752-9775-dceafc855531">

<img width="607" alt="image" src="https://github.com/mastodon/mastodon/assets/18673584/5d92551a-a30a-46ac-b966-6ba72484a8db">

<img width="609" alt="image" src="https://github.com/mastodon/mastodon/assets/18673584/b0badc84-3b41-4ea7-814c-b8cdf26bb2df">

<img width="344" alt="image" src="https://github.com/mastodon/mastodon/assets/18673584/aaf86679-42b8-4029-83fe-727ad9cb561e">

Quickly playing around with the css, disabling overflow: hidden on .compose-form__highlightable resolves the immediate problem, but I don't know the side-effects.

### Specifications

Google Chrome Version 114.0.5735.90 (Official Build) (arm64)
Mastodon v4.1.2+nightly-20230523 on Mastodon Social
+ Also tested on the June 3rd source code running on Veganism Social

**Comment by ClearlyClaire** [comment]
This is a regression introduced by https://github.com/mastodon/mastodon/pull/24872 but simply removing the `overflow: hidden` reintroduces #24792
