### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by EpicJosch** [mastodon/mastodon#25343]
### Steps to reproduce the problem

1. Install with Debian 11 Tutorial
2. Try to access the website
3. Error comes up

### Expected behaviour

Mastodon should open

### Actual behaviour

Error appears

### Detailed description

I installed Mastodon in the EXACT way the guid told me and even tried with debian and ubuntu. Every time i get the ERROR "ERR_TOO_MANY_REDIRECTS". Config:

[config.txt](https://github.com/mastodon/mastodon/files/11686686/config.txt)

![grafik](https://github.com/mastodon/mastodon/assets/50040609/1e910d61-08d8-4dae-a49c-f8aae6338048)

### Specifications

Mastodon 4.1.2

**Comment by Lastorder-DC** [comment]
You've added SSL to `http` entry, resulting infinite loop. 

http block should look like this
https://github.com/mastodon/mastodon/blob/main/dist/nginx.conf#L16-L23

**Comment by EpicJosch** [comment]
Worked now. Thanks for the incredible fast response!!!
