### ISSUE TITLE
Update Full Text Search Configuration

### ISSUE THREAD

**Issue by Wild1145** [mastodon/mastodon#25362]
### Pitch

The current `tootctl search deploy` script assumes you are running a "Standard" and "Best Practice" Elasticsearch deployment, which even our documentation does not tell you to configure. A change should be made to enable you to define if you are running a single node "Development" Cluster which is what our doc's tell you to deploy, or if you're deploying a multi (3+) node "Production" Cluster capable of index replication. 

This will enable you to deploy the search functionality without health warnings in the cluster. 

This would require indexes to be deleted and re-created if this is part of an update, though important to also note the current logic and functionality is not broken, just not good practice. 

### Motivation

Currently when you deploy search onto a single node cluster, all of the indexes created are showing a yellow health warning. This is because we are creating the clusters with the demand of one primary and one secondary index. If you deploy actual health monitoring to your Elastic cluster, it's always going to be showing you there is a problem that you can't fix without scaling up your cluster. 

Given the nature of this data is able to be re-built over and over again (Though is time consuming) giving you the ability to deploy your indexes in a configuration which is compatible with a single node would make a lot of sense while retaining the current functionality. 

**As a stretch goal being** able to define in configuration how many replicas for each index may be useful for search clusters that are seeing significant read demand, however I've yet to see this crop up as a problem and would add complexity.

**Comment by renchap** [comment]
This has been implemented using the new `ES_PRESET` setting in 4.2.

Documentation PR is in progress (https://github.com/mastodon/documentation/pull/1279)
