### ISSUE TITLE
On first load, mastodon.social (advanced view) shows "back" link that goes nowhere

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#25372]
### Steps to reproduce the problem

I open https://mastodon.social .

### Expected behaviour

I expect to see three columns: Home feed, Notifications feed, "Getting Started" pane.

### Actual behaviour

The "Getting Started" column has a "BACK" link on it. But I just opened this window. There is nowhere to go back to.

### Detailed description

It looks like this

<img width="352" alt="Screen Shot 2023-06-11 at 4 06 10 PM" src="https://github.com/mastodon/mastodon/assets/277318/fc121d4a-c11b-40f2-acf5-f70aaae87fac">

If I click the "Back" link, it takes me (in the same column) to a search for nothing at all, and it says it "can not find anything for these search terms".

<img width="358" alt="Screen Shot 2023-06-11 at 4 03 49 PM" src="https://github.com/mastodon/mastodon/assets/277318/fdb22de3-da47-4c40-85ef-de36e73d6cba">

Expected behavior: It should not do that.

### Specifications

I have seen this in Chrome on multiple computers. The server (m.s) is running v4.1.2+nightly-20230523 . I have been noticing this problem for the last day. I am *pretty sure* I never saw this problem before 2 days ago.

I use the "advanced" layout. I have not tried testing with the regular layout.

**Comment by renchap** [comment]
#25281 should fix this

**Comment by mcclure** [comment]
> #25281 should fix this

Thanks, I looked for related issues but didn't think to check the PRs.
