### ISSUE TITLE
Mastodon server can not communicate within the federation

### ISSUE THREAD

**Issue by mk050** [mastodon/mastodon#25379]
### Steps to reproduce the problem

1. When using my server (https://social.schleswig-holstein.de/explore) I try find any other profiles / hashtags / posts suchs as @tagesschau@ard.social but I can not find any
2. Mistake "503 Remote data could not be fetched" ( https://social.schleswig-holstein.de/api/v2/search?q=%40tagesschau%40ard.social&resolve=true&limit=5)

### Expected behaviour

Should be able to find other accounts

### Actual behaviour

Mistake "503 Remote data could not be fetched"

### Detailed description

When using my server (https://social.schleswig-holstein.de/explore) I try find any other profiles / hashtags / posts suchs as @tagesschau@ard.social but I can find none. I get mistake "503 Remote data could not be fetched".

Also if I am trying to find accounts on my server from other servers such as mastodon.social I can find them and send a follow request but the request never reaches my account.

### Specifications

Mastodon 4.1.2 (Edge)

**Comment by disgustipated** [comment]
> We managed to fix it, it's been a problem with the proxy-config!

could you elaborate on what the problem was?

**Comment by mk050** [comment]
> > We managed to fix it, it's been a problem with the proxy-config!
> 
> could you elaborate on what the problem was?

We had to add our internal proxy in the ".env.mastodon" (where also the SMTP server etc is configured).

We had to add the following:
http_proxy: "http://PROXY-IP:Port"
https_proxy: "http://PROXY-IP:Port"
no_proxy: "localhost,127.0.0.1/8,_domain_,es"
HTTP_PROXY: "http://PROXY-IP:Port"
HTTPS_PROXY: "http://PROXY-IP:Port"
NO_PROXY: "localhost,127.0.0.1/8,_domain_,es"
