### ISSUE TITLE
Adding the Languages Filter

### ISSUE THREAD

**Issue by WIZARDELF** [mastodon/mastodon#25382]
### Pitch

Please add the feature that enables users to set what languages they want to see in feeds.

This feature had better be implemented in two cases: for text content and for multimedia content. Generally, people do not care about the languages for a video or a picture.

### Motivation

I am fed with a number of text content in languages I totally cannot know. It shall be useful to empower users to filter what languages they expect for their feeds.

**Comment by Gargron** [comment]
Preferences -> Other
