### ISSUE TITLE
Unable to boost/reblog if client's default posting privacy is set to "Mentioned people only"

### ISSUE THREAD

**Issue by JunyuKuang** [mastodon/mastodon#25394]
### Steps to reproduce the problem

1. Set an account's default posting privacy to "Mentioned people only" (this Mention Only option is somehow not configurable on the web, but available in some third-party apps);
2. Try boosting a post on a public timeline.

### Expected behaviour

Successfully boost/reblog

### Actual behaviour

Boost failed with error message: 422 Validation failed: Visibility is reserved

### Detailed description

This issue can be reproduced on the Mastodon website, and third-party apps.

### Specifications

Tested on https://universeodon.com with Mastodon v4.2.0

**Comment by ClearlyClaire** [comment]
> 1. Set an account's default posting privacy to "Mentioned people only" (this Mention Only option is somehow not configurable on the web, but available in some third-party apps);

I think the issue lies there: “Mentioned people only” is not meant to be available as a default posting privacy, but it's not currently enforced.

Boosting happens with the default posting privacy unless specified otherwise, but boosting something with “Mentioned people only” privacy does not make sense within Mastodon, since boosts do not mention people.

**Comment by ClearlyClaire** [comment]
Just opened #25513 to prevent you from setting the default privacy setting to “Mentioned people only”, as it was unintended.

> * User can't check their boosts' privacy levels on the timeline;

That is true and definitely an UX miss.

> * The setting screen for default privacy level doesn't mention the side effect on boosting. Even if a user set the default post privacy to Followers Only, they may not want to limit their boost's visibility to just followers only.

The API allows you to overwrite the visibility of your boosts, and so does the boost confirmation dialog (but it has to be enabled) in the Web UI.

**Comment by JunyuKuang** [comment]
@ClearlyClaire Thank you for the update. Maybe we should also optimize the error message on boosting failure, so users who already set their default privacy to "mentioned only" won't be confused. Currently the error message displayed on the web "422 Validation failed: Visibility is reserved" provides so little clue on how to solve the problem. Maybe we can change the error message to something like "boost is disabled, because your default post privacy is set to mention only."
