### ISSUE TITLE
`api/v1/statuses/.../history` endpoint can return an empty array on an edited status

### ISSUE THREAD

**Issue by nikclayton** [mastodon/mastodon#25398]
### 1 - search for status

On a Mastodon server running 4.1.2 (I used tooot.im), search for the post with the URL https://spore.social/@tamarasiuda/110522895217050705.

Nothing particularly special about this post (I think), except that it's been edited.

This makes the following HTTP request:

`GET https://tooot.im/api/v2/search?q=https%3A%2F%2Fspore.social%2F%40tamarasiuda%2F110522895217050705&type=statuses&resolve=true&limit=20&offset=0&following=false`

As expected, this returns JSON with a single entry in the `statuses` property:

```
...

    "statuses": [
        {
            "id": "110522895225071526",
            "created_at": "2023-06-11T01:05:44.000Z",
...
```

### 2 - fetch the status

Use the ID from the `id` property to fetch the status, and `GET https://tooot.im/api/v1/statuses/110522895225071526`

This returns `200`, and a status with the `edited_at` property set:

```
...
    "edited_at": "2023-06-11T11:24:17.000Z",
...
```

### 3 - fetch the edit history

Fetch the edit history of the status, with `GET https://tooot.im/api/v1/statuses/110522895225071526/history`

Per https://docs.joinmastodon.org/methods/statuses/#history, fetching the history should "Get all known versions of a status, including the initial and current states.".

Given that this status **has** been edited this should return an array of at least two entries.

It returns an empty array.

### Expected behaviour

An N-element array with at least two entries should have been returned.

### Actual behaviour

An empty JSON array, `[]`, is returned.

### Detailed description

In the web UI this manifests as a "Edited -1 times" tooltip if you hover over the "Edited Jun 11, 13:24" text on the status. In clients that expect the API endpoints to follow documented behaviour it results in a crash (https://github.com/tuskyapp/Tusky/issues/3743).

I think this is two bugs.

1. The status has been edited, so there should be at least two entries.
2. Even if the status hadn't been edited, fetching the history of a status should always return at least one entry, which would be the original status content (per the documentation, which says it fetches "all known versions of a status, including the **initial** and current state" (emphasis mine).

This may be related to https://github.com/mastodon/mastodon/issues/23292, I'm unsure.

### Specifications

Mastodon 4.1.2

**Comment by nikclayton** [comment]
What are API clients supposed to do in this case? Show an error when the user tries to get the history? Or try an API call to the remote server and hope that the original status was public so it doesn't need to be authenticated?

**Comment by ClearlyClaire** [comment]
I think the WebUI just show an empty list, but it would make sense to always have at least one version (server-side change).

> Or try an API call to the remote server and hope that the original status was public so it doesn't need to be authenticated?

Generally, we don't recommend doing this kind of things, but it could work.

**Comment by nikclayton** [comment]
Please also update the API documentation.

**Comment by ClearlyClaire** [comment]
How should it be updated? The code is now consistent with the documentation.

**Comment by nikclayton** [comment]
Currently it says:

> Get all known versions of a status, including the initial and current states.

"intial and current" implies that the returned array will always have at least two entries. If I've read the code change correctly that's still not the case.

Something like:

> Get versions of a status known to this server.
>
> **Returns:** Non-empty array of StatusEdit. If there is only one entry in the array the server does not have the edit history for this status, and this will be the status' most recent content known to this server. If there are multiple entries in the array they represent the different versions of the status, and are sorted with the oldest version first.

One thing this doesn't address -- if a status has been edited 4 times, so exists in versions (oldest first) A, B, C, D, E, what are the possible states a server can be in if it has a copy of that status.

1. It only has one version, which may be any of A, B, C, D, or E
2. If it has multiple versions they are always contiguous, but not necessarily exhaustive. So if a server has versions B and D it also has version C but is not guaranteed to have version A.
3. If it has multiple versions they are not necessarily contiguous, a server could have versions B and D without version C).
4. If it has multiple versions they are contiguous and exhaustive, a server has version D then it also has versions A, B, and C).
5. If it has multiple versions they are exhaustive but not necessarily contiguous, a server has version D it will also have version A, but not necessarily B or C.

**Comment by ClearlyClaire** [comment]
> "intial and current" implies that the returned array will always have at least two entries. If I've read the code change correctly that's still not the case.

Ah, right, this is inaccurate in case the initial one is not known.

> One thing this doesn't address -- if a status has been edited 4 times, so exists in versions (oldest first) A, B, C, D, E, what are the possible states a server can be in if it has a copy of that status.

If the status is local, it'll always be exhaustive. If the status is remote, the only guarantees are that the edits are ordered and they include the current version. If the status is from a followed user, it will most likely include all edits, otherwise all bets are off.

**Comment by nikclayton** [comment]
Thanks. It would be great if the docs were updated to make the clear.
