### ISSUE TITLE
WebSocket connection restarting repeatedly

### ISSUE THREAD

**Issue by cluelessdev404** [mastodon/mastodon#25412]
### Steps to reproduce the problem

(Meant to put "Troubleshooting" tag but it's not available)
Hello, I'm setting up a Mastodon instance at the moment and I'm encountering a strange issue. When the home page is loaded, the timeline starts stuttering as the refresh bar just above the posts (3 dots) pops in and out. Not "stuttering" as in the occasional refresh, I mean as in once a second. 
Checking the WS requests in the browser, I see that websockets are listed from wss://.../api/v1/streaming/? repeatedly and quickly for each stutter, with status 101. However, no websocket is listed from https://.../api/v1/markers. 
Looking at the Docker logs, I see a new worker starting up for each websocket connection, but nothing else. I also see no errors in the NGINX log.

I would greatly appreciate any help with this, thanks!

### Expected behaviour

WebSocket connections remain

### Actual behaviour

WebSocket connections drop and retry connection

### Specifications

Mastodon 4.1.2
Brave 1.52.122 Chromium: 114.0.5735.110 (Official Build) (x86_64)]

**Comment by ThisIsMissEm** [comment]
Do you have this instance running somewhere that I could check? WebSockets use 101 status for upgrading from http to websocket protocol, there shouldn't be a "new worker per connection", as websockets (streaming) is a node.js process that runs `yarn start` / `node streaming/index.js`, and uses one process for many connections.

I'm also not sure I understand:
> However, no websocket is listed from https://.../api/v1/markers.

As markers are completely unrelated to streaming & websockets.

**Comment by cluelessdev404** [comment]
Sorry, fixed

**Comment by makidrone** [comment]
I'm wondering what the issue was. I'm having the same issue and I can't figure out whats going on.

**Comment by makidrone** [comment]
> I'm wondering what the issue was. I'm having the same issue and I can't figure out whats going on.

I switched away from using the linuxserver docker image to the official images and now I've got things working
