### ISSUE TITLE
verified links (rel=me) do not seem to work: everything seems to get a checkmark

### ISSUE THREAD

**Issue by naknomum** [mastodon/mastodon#25415]
### Steps to reproduce the problem

1. created a page elsewhere with `<a rel="me" href="my-mastodon-url">` in it
2. added link to above page from mastodon profile
3. link showed with :heavy_check_mark: as expected
4. created a _different_ page elsewhere, with `<a rel="me" href="some-other-mastodon-url">` in it
5. added link (to different page) to my mastodon profile
6. **link also showed with :heavy_check_mark: on it**

### Expected behaviour

link without my mastodon url would NOT be shown verified

### Actual behaviour

link showed verified

### Detailed description

am i crazy or does _everything_ seem to get **verified** no matter what?  maybe i am misunderstanding things.

### Specifications

appears to be mastodon v4.1.2

**Comment by connyduck** [comment]
Could you share links to the pages you mentioned?

**Comment by naknomum** [comment]
> Could you share links to the pages you mentioned?

update!  i just revisited the pages i was testing in more detail. this was an **error on my part**.  the site i was testing with had an errant `rel="me"` that appears to be the cause of what i was seeing. behavior is as expected now. i will close this issue. thanks for checking in.
