### ISSUE TITLE
Receiving `/api/v1/admin/accounts ` response when making pagination request with `/api/v2/admin/accounts` endpoint

### ISSUE THREAD

**Issue by k3yss** [mastodon/mastodon#25438]
### Steps to reproduce the problem

1.  Make a `GET` request to `/api/v2/admin/accounts` endpoint 
2. On the  **HTTP Link** header  we receive `/api/v1/admin/accounts ` response

### Expected behaviour

I should receive a `v2` response when requesting for pagination

### Actual behaviour

I am receiving a `v1` response when requesting for pagination

### Detailed description

I am implementing moderation tools for **KDE's** Mastodon client **Tokodon**. While implementing pagination, I am encountering an issue where the **HTTP Link header**  is returning a `v1` (Version 1) response instead of `v2` (Version 2). This caused problems with the query parameters. To resolve this issue, I added the following code: `url.toString().replace("/v1/", "/v2/");` which effectively fixed the problem.

### Specifications

Mastodon- 4.0.2
Ruby- 3.0.4p208
PostgreSQL-15.1
Redis- 5.0.7

**Comment by trwnh** [comment]
this looks like it's happening because the v2 controller inherits from the v1 controller but doesn't override `after_action :insert_pagination_headers, only: :index`

https://github.com/mastodon/mastodon/blob/e686a54064191f23898e707b2fee68ad2feaa358/app/controllers/api/v1/admin/accounts_controller.rb#L128-L138

unfortunately i do not know what `api_v1_admin_accounts_url` is or where it comes from.

**Comment by redstrate** [comment]
> unfortunately i do not know what `api_v1_admin_accounts_url` is or where it comes from.

I don't know a smidge of Ruby yet, but maybe it is auto-generated? For example, [the mutes controller uses a similar url function/variable](https://github.com/mastodon/mastodon/blob/e686a54064191f23898e707b2fee68ad2feaa358/app/controllers/api/v1/mutes_controller.rb#L36)... so maybe if we use `api_v2_admin_accounts_url` and override the `after_function` you mentioned, it could work? I'll try modifying it myself :thinking:

**Comment by renchap** [comment]
> unfortunately i do not know what `api_v1_admin_accounts_url` is or where it comes from.

This is a route helper, generated from the route definition here:

https://github.com/mastodon/mastodon/blob/c9d06d10d4e936ee4f741ec2fecca7f91ca61997/config/routes/api.rb#L205-L206
