### ISSUE TITLE
mstdn.ca is broken

### ISSUE THREAD

**Issue by banksxs** [mastodon/mastodon#25442]
### Steps to reproduce the problem

1. It happened after turning on advanced web interface
2. I signed up to another server (social strangers) and turned the same setting on
3. It wasn't happening to social strangers, just mstdn.ca
4. Is it the server that is the issue? Ivory is fine.

![image](https://github.com/mastodon/mastodon/assets/102607958/88e6794a-609d-45fc-ab96-5998928a8e60)

...

### Expected behaviour

Web interface shows

### Actual behaviour

weird images, text out of whack

### Specifications

Chrome
Version 114.0.5735.111 (Official Build) (32-bit)

Windows 10 Enterprise

**Comment by trwnh** [comment]
This issue tracker is for the Mastodon project, not for mstdn.ca -- I'd advise reaching out to your admin for assistance.
