### ISSUE TITLE
Receive id of status or receive all recent context of user 

### ISSUE THREAD

**Issue by AndreZila01** [mastodon/mastodon#25449]
### Pitch

I would like collect all context of user and them consult like the old request of twitter (`"../users/{userid}/tweets"`), with date and the context or receive all status id between two dates...

### Motivation

Make the request more friendly and simple to learn!

**Comment by trwnh** [comment]
`GET /api/v1/accounts/:id/statuses`

**Comment by AndreZila01** [comment]
@trwnh i know that, but is more simple if you make a request api like this: 
![image](https://github.com/mastodon/mastodon/assets/56931353/e5c1baef-9668-4a35-9360-70416962fe77)

**Comment by trwnh** [comment]
How do you want the API request to be made?

**Comment by AndreZila01** [comment]
remove some received data on request api like account and media_attachments.
I can receive the data of account on https://mas.to/api/v2/search and media_attachments i cannot understand why the dev need that information but add a another header like Bool 'visible_media_attachments'.
