### ISSUE TITLE
Publish button "highlight" appearance is nearly indistinguishable from normal 

### ISSUE THREAD

**Issue by azurelunatic** [mastodon/mastodon#25505]
### Steps to reproduce the problem

1. Go to compose a toot. 
2. Tab through the page with the aim of selecting the Publish button. 
3. Notice the change in appearance of the Publish button when it is highlighted. 
...

### Expected behaviour

The Publish button should have a substantial change that is easy to notice. 

### Actual behaviour

The Publish button seems slightly more saturated. 

### Detailed description

People who primarily use a pointer to click the Publish button may not notice this, but the visual highlight of the button when it is highlighted for keyboard use is nearly indistinguishable from the un-highlighted version. I had to stare very carefully at the button and observe the obvious highlight of other elements in the compose box, and the outline of the links below the compose box, before I realized that there is a change, it's just very subtle. 

I propose a more obvious change. 

Outline? More different colors? Flip colors? 

### Specifications

v4.1.2 on blorbo.social

**Comment by teeerevor** [comment]
@azurelunatic I agree, too subtle.

Would copying the https://joinmastodon.org/ purple buttons do the trick?

Current button

![2023-06-29 14 40 41](https://github.com/mastodon/mastodon/assets/17292/fbbc7074-6e19-49d8-969e-463384246879)

with the joinmasterdon.org colors

dark
![2023-06-29 10 47 21](https://github.com/mastodon/mastodon/assets/17292/b85c34b7-c896-4ea2-a041-1a6c064685d5)

and light

![2023-06-29 14 50 48](https://github.com/mastodon/mastodon/assets/17292/aba0e94d-be1d-490a-b40f-2b651829150c)

I think outline and better keyboard controls would be good to but might be a matter for another issue
