### ISSUE TITLE
Redirect @username@domain.name as a URL to domain.name/@username

### ISSUE THREAD

**Issue by nclm** [mastodon/mastodon#25501]
### Pitch

I’m not a developer and I have no idea if this is even feasible. But utility wise, it would be super practical.

Websites support being accessed with a username, in the format `username@domain.name`.

If the website is not made for that, it will probably show an error, for instance on Firefox it will tell you “You are about to log in to the site “domain.name” with the username “username”, but the website does not require authentication.”

What if Mastodon servers actually supported that? Not to log you in, but to redirect you to the actual profile in question.

### Motivation

You could type `@username@domain.name` (“domain.name” being a Mastodon server), and the server would be configured so that it redirects you to `domain.name/@username`. That’s what I don’t know if it is technically possible?

If it is, it would just make for a quick shortcut when you run into a Mastodon handle without a link. Just paste it into your browser’s address bar, and it would get to the right place!

**Comment by trwnh** [comment]
I don't think it's possible. What you are referring to is known as "HTTP Basic Authentication" and is basically like trying to log in to `domain.name` with a username of `username` and an empty password.
