### ISSUE TITLE
Option To Hide Individual Posts In Various Feeds

### ISSUE THREAD

**Issue by tinker123456** [mastodon/mastodon#25529]
### Pitch

Have a "hide" option on any toot or comment.

### Motivation

Often there is a post you don't want to see in a slow moving feed.

You don't have a problem with the author, but the only options for getting rid of that toot or comment is to mute or block the author.

Kind of wasteful.

**Comment by timtfj** [comment]
The "add to filter" option for a toot achieves this, unless I've misunderstood what you want to do. It asks you to pick an existing filter or create a new one.
