### ISSUE TITLE
 We're sorry, but something went wrong on our end.

### ISSUE THREAD

**Issue by Y3flamex** [mastodon/mastodon#25545]
### Steps to reproduce the problem

im trying to set up a server but this is all that comes up
i already set everything up and configured the server
(im new to this so im sorry if i dont provide enough details idk what i have to provide)

### Expected behaviour

mastodon home page

### Actual behaviour

error screen

### Specifications

mastodon 4.1.2
ruby 3.0.6p216
node v16.20.0

**Comment by snowmanninja** [comment]
Does it give any errors when you attempt to build/deploy? 

like when you get to RAILS_ENV=production bundle exec rake mastodon:setup step. 

it also helps to know if your installing from source or 1 click install like from digital ocean.

**Comment by Y3flamex** [comment]
i mispelt one of the domains ahaha sorry for the bother
