### ISSUE TITLE
`/api/v1/accounts/.../statuses` does not paginate pinned statuses

### ISSUE THREAD

**Issue by nikclayton** [mastodon/mastodon#25555]
### Steps to reproduce the problem

1. Fetch https://mastodon.social/api/v1/accounts/109241526707263377/statuses (that's my account)
2. Observe that the reponse has a `Link` header allowing pagination through the results (as expected)
3. Fetch my pinned statuses with https://mastodon.social/api/v1/accounts/109241526707263377/statuses?pinned=true

### Expected behaviour

The pinned response should also have a `Link` header allowing pagination through pinned statuses

### Actual behaviour

There is no `Link` header

### Detailed description

Paginating through regular results works, so does paginating through an account's statuses that have a tag (using `?tagged=...`), so this looks like an oversight.

### Specifications

mastodon.social running v4.1.2+nightly-20230619 at the time of writing

**Comment by Gargron** [comment]
What's the use case? People have 1-5 pinned posts, in which scenario would they not all be returned in one page?

**Comment by ClearlyClaire** [comment]
> Is 1-5 a hard limit? It's not documented at https://docs.joinmastodon.org/methods/statuses/#pin

5 posts is a hard limit in mainline Mastodon, although some forks may do otherwise

> Also, `pinned` respects the `limit` parameter, so it's entirely possible to make an API request like `?pinned=true&limit=3` and then not be able to paginate through the results.

Right, that does feel inconsistent.
