### ISSUE TITLE
account media tab has broken links to the toots.

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#25566]
### Steps to reproduce the problem

1. visit the media tab of a user account https://aus.social/@shlee/media
2. The media links to https://aus.social/@undefined/110596899882792856
3. it should link to https://aus.social/@shlee/110596899882792856

### Expected behaviour

the media should link to the toot.

### Actual behaviour

404

### Specifications

v4.1.3

**Comment by trwnh** [comment]
Duplicate of #23070
