### ISSUE TITLE
`/api/v1/emails/check_confirmation` returns HTTP 500 with unauthenticated user

### ISSUE THREAD

**Issue by danielmbrasil** [mastodon/mastodon#25594]
### Steps to reproduce the problem

1. Make an unauthenticated GET request to `/api/v1/emails/check_confirmation`

### Expected behaviour

HTTP 401 Unauthorized

### Actual behaviour

HTTP 500 `NoMethodError`

### Detailed description

When making an unauthenticated GET request to `/api/v1/emails/check_confirmation` a `NoMethodError` is raised and the page returns HTTP 500. Here's the error message:
```
NoMethodError at /api/v1/emails/check_confirmation

undefined method `confirmed?' for nil:NilClass
```

### Specifications

main

**Comment by Cantzon** [comment]
Me and a friend couldn't sign up due to emails not being sent (as of 5 minutes ago).
