### ISSUE TITLE
Tooltip on usernames is missing an @

### ISSUE THREAD

**Issue by mxamber** [mastodon/mastodon#25601]
### Steps to reproduce the problem

1. publish a post mentioning any user by username
2. hover the mouse over the mention

### Expected behaviour

the tooltip should read "@username@instance.example"

### Actual behaviour

the tooltip reads "username@instance.example"

### Detailed description

The username is presented like an email address (as username@instance.example) instead of the customary @username@instance.example format. During the peak of the Twitter-to-Mastodon migration, there was a lot of confusion around this from new users, and it seems this issue is being replicated in Mastodon, even though usernames are spelled as @username@instance.example everywhere else.

![image](https://github.com/mastodon/mastodon/assets/13611718/91ae61ce-02e3-4c09-a525-b989cf8597f2)

### Specifications

Tested in Mastodon 4.1.2

**Comment by trwnh** [comment]
i'm not sure this is a bug, but more a case of differing expectations? the tooltip is the acct and not the username. but maybe there's no reason to present the acct to the end user like this...

**Comment by mxamber** [comment]
To say the least, it's inconsistent with how usernames are displayed everywhere else on the user-facing side.

**Comment by forsamori** [comment]
I'll pick this one up and add the @ - then we'll see if the main Mastodon devs agree or not :D

**Comment by forsamori** [comment]
Here you go if you want to track the PR :) https://github.com/mastodon/mastodon/pull/25684

**Comment by forsamori** [comment]
Well it was approved by the Founder and CEO of Mastodon so I guess that's as good as anything :D

**Comment by mxamber** [comment]
Oh that's lovely! Thank you!

**Comment by forsamori** [comment]
Just to keep this nice and clean, would you mind closing this please?

**Comment by mxamber** [comment]
Fixed via #25684
