### ISSUE TITLE
User is redirected to `/explore` after signing in

### ISSUE THREAD

**Issue by renchap** [mastodon/mastodon#25600]
### Steps to reproduce the problem

1. Open a private browsing session on mastodon.social
2. Sign-in with an existing account

### Expected behaviour

I am redirected to my personal timeline after logging in

### Actual behaviour

I am redirected to `/explore`

### Detailed description

This might come from https://github.com/mastodon/mastodon/pull/25396

### Specifications

Mastodon edge on mastodon.social

**Comment by Signez** [comment]
Narrowing down the bug: it's not that we are redirected to `/explore` on login, it's that we are redirected to _the page we were before clicking on the button to sign-in_.

If you open https://mastodon.social/home in a private browsing session, the page will show up with an empty state in the main column, and if you login, you will be redirected correctly to `/home`.

Should we force the redirection on `/home` only if we were on `/explore` before signing in? …or should we do it in any cases, which can create confusion or frustration if we were on a specific post?

**Comment by ClearlyClaire** [comment]
I think it makes sense to redirect to `/home` if the newly-logged-in user would otherwise be redirected to what can be a logged-out landing page: `/about`, `/explore`… or the single user's profile on single-user instances… that one may be a bit more tricky

**Comment by ClearlyClaire** [comment]
Actually we already have that kind of logic, it was just not updated with the addition of the explore page.

**Comment by RichardJECooke** [comment]
I don't know if this is related, but I'm trying to create a Mastodon for the first time ever, and the https://mastodon.social/auth/sign_up link just takes me back to the explore. I can't create an account in any browser.

**Comment by ClearlyClaire** [comment]
> I don't know if this is related, but I'm trying to create a Mastodon for the first time ever, and the https://mastodon.social/auth/sign_up link just takes me back to the explore. I can't create an account in any browser.

Hi! This doesn't look related at all, but it's odd. Can you describe what is happening in as much details as you can?

**Comment by RichardJECooke** [comment]
I logged a bug, but in case you can help: There are no errors in the console. Network errors only for some .svg files, then a 302 redirect back to the explore page. There is this line though: None of the “sha256” hashes in the integrity attribute match the content of the subresource at “https://mastodon.social/packs/js/locale/en-json-59c070a7278ea3716c70.chunk.js”. The computed hash is “47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=”.
