### ISSUE TITLE
Update CONTRIBUTING.md with additional requirements for API additions

### ISSUE THREAD

**Issue by andypiper** [mastodon/mastodon#25639]
### Pitch

Add information to `CONTRIBUTING.md` to specify that additions and updates to the API should also have an accompanying PR against the [documentation](https://github.com/mastodon/documentation).

### Motivation

This will help to reduce the chances for the API endpoints to be undocumented as they are added.

**Comment by ThisIsMissEm** [comment]
The API docs aren't automatically generated, are they? Should we work towards having them auto-documenting?

**Comment by trwnh** [comment]
no, they're not auto-generated, and it has been a historical challenge because there isn't an easy way to do so. in particular, version history is especially difficult to keep track of.

**Comment by mjankowski** [comment]
Resolved by https://github.com/mastodon/mastodon/pull/28274
