### ISSUE TITLE
Content Warning label

### ISSUE THREAD

**Issue by StyXman** [mastodon/mastodon#25643]
### Pitch

Allow a short explanation for the warned content, maybe 20-25 chars max.

### Motivation

People are different. Some are scared by spiders, some are epileptic. Content warnings are useful for when you're sure you can be presenting sensitive content to people, but there is no way to tell them what content it is. Epileptic people might like spiders, and arachnophobes might like a music video with lots of strobes.

**Comment by keerifox** [comment]
Am I misunderstanding or are you requesting the following functionality?

![2023-06-30_22-17-09](https://github.com/mastodon/mastodon/assets/29272208/fb3a5917-676d-42be-9285-7d37e1f8925f)

![image](https://github.com/mastodon/mastodon/assets/29272208/f458c560-efa7-40b7-9347-14214b623c70)

**Comment by StyXman** [comment]
Right, it can be implemented with simple text. Sorry, I didn't think about it. Closing.
