### ISSUE TITLE
Allow disabling "The poll you voted in has ended" notifications

### ISSUE THREAD

**Issue by RedAuburn** [mastodon/mastodon#25655]
### Pitch

<img src="https://github.com/mastodon/mastodon/assets/26939824/efc1bbb4-39b6-4641-9a82-436202912bd1" width="400"/>

these notifications are not useful and i'd like to mute them, but it doesn't seem to be supported.

it should be possible to mute them here:
<img src="https://github.com/mastodon/mastodon/assets/26939824/3292a411-0e21-46c3-9934-d33e46c13046" width="400"/>
 

### Motivation

this would be useful for people who vote on a lot of polls, as currently it can clutter the notification feed

**Comment by EwanCroft** [comment]
Is this not sufficient? (seen under the settings at [_~/notifications_](https://mastodon.social/notifications))

![image](https://github.com/mastodon/mastodon/assets/121812160/382ac0bb-d68e-4592-89a4-bb9d3d2a1bf9)

**Comment by quidquid** [comment]
What! 🤯  I've been looking for this as well. Turns out there's a whole world of notification preferences that aren't even hinted at in Preferences > Notifications. Combining or at least linking these two areas would make the options more discoverable, I think.
