### ISSUE TITLE
Add Hashtag follows to lists

### ISSUE THREAD

**Issue by Angular-Angel** [mastodon/mastodon#25689]
### Pitch

Allow adding hashtags that you follow to your lists. For bonus points, also add a checkbox to lists that will allow them to remove any posts they include from your main timeline. So I can have my nature posts in my nature list and nowhere else, my tech posts in a list and nowhere else, etc, etc.

### Motivation

If I follow a bunch of nature hashtags, I want to be able to collect them in a list. Same for other kinds of hashtags.

**Comment by brendanjones** [comment]
Duplicate of https://github.com/mastodon/mastodon/issues/7692
