### ISSUE TITLE
Lists: Reply Policy - UI and documentation

### ISSUE THREAD

**Issue by TymeForChange** [mastodon/mastodon#25692]
### Steps to reproduce the problem

1. Click on your handle.
2. Open options menu.
3. Select "Lists".
4. Click the filter icon.
5. Section that reads "Show replies to:" options.

![Lists-reply-policy](https://github.com/mastodon/mastodon/assets/56969001/6a213584-7110-4976-9dbd-2ad217a981b6)
![scrList-replies-policy](https://github.com/mastodon/mastodon/assets/56969001/a576c784-06d2-492b-8faf-8045ceba753d)

### Expected behaviour

In each option description, the word "to" should read "of" or "from" instead.

### Actual behaviour

The word "to" implies a different action. Not best word choice.

### Detailed description

Using the word "to" implies a _delivery_ option rather than a _display_  option. Even though one clicks the filter icon to see these options, it might not be clear to all (>>clears throat<<) that these are **display filters**. See attached screenshots. 

### Specifications

Mastondon  v4.1.2
not browser specific

**Comment by arpitj007** [comment]
> ### Steps to reproduce the problem
> 1. Click on your handle.
> 2. Open options menu.
> 3. Select "Lists".
> 4. Click the filter icon.
> 5. Section that reads "Show replies to:" options.
> 
> ![Lists-reply-policy](https://user-images.githubusercontent.com/56969001/250660332-6a213584-7110-4976-9dbd-2ad217a981b6.PNG) ![scrList-replies-policy](https://user-images.githubusercontent.com/56969001/250660334-a576c784-06d2-492b-8faf-8045ceba753d.png)
> 
> ### Expected behaviour
> In each option description, the word "to" should read "of" or "from" instead.
> 
> ### Actual behaviour
> The word "to" implies a different action. Not best word choice.
> 
> ### Detailed description
> Using the word "to" implies a _delivery_ option rather than a _display_ option. Even though one clicks the filter icon to see these options, it might not be clear to all (>>clears throat<<) that these are **display filters**. See attached screenshots.
> 
> ### Specifications
> Mastondon v4.1.2 not browser specific

Can I take this bug?

**Comment by forsamori** [comment]
@arpitj007 Go for it :D

**Comment by trwnh** [comment]
No, it's very much replies *to* people. "From" implies the original poster, not the target. The feature and parameter works based on who the list member replied *to*.

**Comment by TymeForChange** [comment]
As written ("to"), it implies that MY replies will be treated thusly:
1. Show my replies to any followed user;
2. Show my replies to members of the list;
3. Show my replies to no one.

As is, that would be a useful feature IF there also existed an option for the original post directly to the list. [Which got me excited for 2 seconds.]

Whereas, if using the word "of" (or "from"), it implies:
1. Show me replies of/from any followed user;
2. Show me replies of/from members of the list;
3. Show me replies of/from no one.

Why not leave this issue open for discussion by others?

**Comment by trwnh** [comment]
The subject of the sentence is the user in the list, not yourself. "From" doesn't make sense.

**Comment by TymeForChange** [comment]
"No, it's very much replies to people. "From" implies the original poster, not the target. The feature and parameter works based on who the list member replied to."

In that case, what you are describing is a very different action.  Not a display option but a **delivery** option. (When then needs to option to send original post directly to list.)

**Comment by trwnh** [comment]
Put another way: the full sentence is "Show replies *from* list members *to* other list members"

**Comment by TymeForChange** [comment]
Then state it that way! Else, you have created an ambiguity.  As a grammarian, I can tell you that the #1 rule of writing is clarity.

**Comment by TymeForChange** [comment]
_"Put another way: the full sentence is "Show replies from list members to other list members / to users you follow / to no one""_

Dude, you literally just made _my_ point.  But, even that sentence describes to different actions (/use cases): one based on the sending and one of the receiving.

**Comment by TymeForChange** [comment]
Based on this existing language: _Description: Which replies should be shown in the list._

I maintain that the word "to" in the options should read "from" instead. 

Reopen for discussion. #democracy

**Comment by trwnh** [comment]
This was explained earlier in the discussion: https://github.com/mastodon/mastodon/discussions/25688#discussioncomment-6347657

say you have a list with A and B in it, and C not in it. you follow all three of these people. you also have the following posts:

```
A: post 1, top-level
A: post 2, self-reply to post 1
B: @A post 3, in reply to post 1
C: @A post 4, in reply to post 1
A: @B post 5, in reply to post 3
A: @C, post 6, in reply to post 4
```

- `followed` will show you all posts except for post 4. notably, post 6 will show up because you follow C, even though C is not in the list.
- `list` will show you all posts except for posts 4 and 6. notably, posts 3 and 5 will show up because they are replies to members of the list (A and B).
- `none` will show you only posts 1 and 2. notably, post 2 is included because self-replies are not considered the same as replies to other people.

**Comment by TymeForChange** [comment]
Right. So, the word "of" or "from" should be used rather than "to" in the option descriptions -- docs & UI. (Colloquially, most English-speakers would probably say 'from'.)

Because your stated scenario describes this:

Show [me] replies from any followed user;
Show [me] replies from members of the list;
Show [me] replies from no one.

**Comment by TymeForChange** [comment]
"List replies are always _from_ list members. "

Exactly!! You've made my point yet again. 

But, by all means, close the issue so that no other voices can be heard. #ttsl

**Comment by trwnh** [comment]
Your point is to invert the subject and the target, such that the sentence becomes incorrect. The option controls the visibility of replies "to" the specified target. If you want to control who the replies are "from", you add or remove members to the list. I'm not sure how many other ways I can say the same thing.

**Comment by forsamori** [comment]
At the risk of raising my head over the parapet, and as a native English speaker, _and_ understanding the context of the wording and the implied action, I agree with @trwnh. As to whether or not this should say closed, six-and-half-a-dozen 😉

**Comment by TymeForChange** [comment]
Here is a screenshot of Posting Defaults in account settings.  The word "to" is used here. This is about _delivery_ (send).  Lists filter setting is about _display_ (receive). Send = "to"; Receive = "from".

![scrPosting-Policy](https://github.com/mastodon/mastodon/assets/56969001/c7a615ab-217c-4b3e-b51a-d4806b6ac8cb)

Whatever. #ffs

**Comment by trwnh** [comment]
The list filtering is done based on who the list member is sending "to".
