### ISSUE TITLE
YouTube time embed shows "Video Not Available"

### ISSUE THREAD

**Issue by WolfShadowheart** [mastodon/mastodon#25695]
### Steps to reproduce the problem

1. Come across a YouTube shortlink (in this case, it was time-stamped). An image of the time-stamp is shown.
2. Click the embed to play it in Mastodon
3. Video shows as unavailable, "watch on YouTube" starts from the beginning.
4. Clicking just the YouTube shortlink leads to the proper time stamp

### Expected behaviour

When clicking an embedded YouTube time-stamped link it should play.

### Actual behaviour

YouTube shows the video as unavailable

### Detailed description

My friend just joined Mastodon and posted a time-stamped link to a YouTube video. For both of us the embedded link showed as unavailable, but when we click on the timestamp and went directly to YouTube the video played. For engagement, ideally the YouTube embed has the time-stamp and plays right there. 

Thank you!

### Specifications

v4.1.2+nightly-20230627

Firefox

**Comment by forsamori** [comment]
Do you have an example of the shortlink in question? I've tried https://youtu.be/Mt0rY8qefQY?t=1474 in my own local test instance - seems to work as expected (albeit it doesn't play at the timestamp, but that's another issue).

It could be also that the YouTube video isn't set to play on embedded players, but I'd need the actual video link to confirm that.

**Comment by WolfShadowheart** [comment]
> Do you have an example of the shortlink in question? I've tried https://youtu.be/Mt0rY8qefQY?t=1474 in my own local test instance - seems to work as expected (albeit it doesn't play at the timestamp, but that's another issue).
> 
> It could be also that the YouTube video isn't set to play on embedded players, but I'd need the actual video link to confirm that.

Yes, absolutely! I just didn't see if it was something that I should drop in, though it is just a youtube link :) 

Here is the permalink: [here](https://mastodon.social/@chicleXX/110652586826761845)

direct link: https://mastodon.social/@chicleXX/110652586826761845

youtube link from the post: [youtu.be/AjmnjFid2_4?t=4](https://youtu.be/AjmnjFid2_4?t=4)

Thank you for your response!

**Comment by forsamori** [comment]
@WolfShadowheart Lol, it works on my local instance, but I'm getting the same issue when I use my real Mastodon account - very strange. Thanks for the interesting bug, will take a look at this :)

**Comment by WolfShadowheart** [comment]
> Did some investigation on this.
> 
> I'm reasonably confident in saying that the video you linked has content embed settings that prevent it from being played in certain environments. It's likely to be a regional lock or something similar. I don't think this will be something we can fix, and is instead the intended behaviour of YouTube's embedded player (you can configure rules for embedded videos as the uploader).
> 
> That being said, if someone does think this is fixable, please feel free to use these logs:
> 
> Here's the debug output for the issue described above:
> 
> ```
> {
>   "ns": "yt",
>   "el": "embedded",
>   "cpn": "KTrXPJzvGIG0kDWS",
>   "ver": 2,
>   "cmt": "0",
>   "fs": "0",
>   "rt": "20.501",
>   "euri": "",
>   "lact": 1,
>   "cl": "543893475",
>   "mos": 0,
>   "state": "80",
>   "volume": 100,
>   "cbrand": "apple",
>   "cbr": "Safari",
>   "cbrver": "16.1",
>   "c": "WEB_EMBEDDED_PLAYER",
>   "cver": "1.20230627.01.00",
>   "cplayer": "UNIPLAYER",
>   "cos": "Macintosh",
>   "cosver": "10_15_7",
>   "cplatform": "DESKTOP",
>   "autoplay": "1",
>   "epm": 1,
>   "hl": "en_GB",
>   "cr": "GB",
>   "len": "0",
>   "fexp": "23983296,24007246,24080738,24135310,24362594,24362687,24364789,24366065,24366917,24370597,24380264,24383853,24384776,24388278,24415864,24416291,24439361,24501421,24533809,24539309,24559327,24695883,39324104",
>   "feature": "oembed",
>   "size": "546:410:2",
>   "muted": "0",
>   "docid": "AjmnjFid2_4",
>   "vct": "0.000",
>   "vd": "NaN",
>   "vpl": "",
>   "vbu": "",
>   "vpa": "1",
>   "vsk": "0",
>   "ven": "0",
>   "vpr": "1",
>   "vrs": "0",
>   "vns": "0",
>   "vec": "null",
>   "vemsg": "",
>   "vvol": "1",
>   "vdom": "1",
>   "vsrc": "0",
>   "vw": "0",
>   "vh": "0",
>   "debug_error": "{\"errorCode\":\"auth\",\"errorDetail\":\"0\",\"errorMessage\":\"Video unavailable\",\"Vm\":\"\",\"pI\":\"0;a6s.0\",\"eG\":2,\"cpn\":\"KTrXPJzvGIG0kDWS\"}",
>   "relative_loudness": "NaN",
>   "user_qual": 0,
>   "release_version": "youtube.player.web_20230627_01_RC00",
>   "debug_videoId": "AjmnjFid2_4",
>   "0sz": "true",
>   "op": "",
>   "yof": "true",
>   "dis": "",
>   "gpu": "Apple_GPU",
>   "debug_playbackQuality": "unknown",
>   "debug_date": "Tue Jul 04 2023 15:29:38 GMT+0100 (British Summer Time)"
> }
> ```
> 
> And now for my local Mastodon instance (which doesn't reproduce this error):
> 
> ```
> {
>   "ns": "yt",
>   "el": "embedded",
>   "cpn": "xqt58dBk2UX__azU",
>   "ver": 2,
>   "cmt": "0",
>   "fmt": "244",
>   "fs": "0",
>   "rt": "68.579",
>   "euri": "http://localhost:3000/",
>   "lact": 0,
>   "cl": "543893475",
>   "mos": 0,
>   "state": "444",
>   "volume": 100,
>   "cbrand": "apple",
>   "cbr": "Chrome",
>   "cbrver": "114.0.0.0",
>   "c": "WEB_EMBEDDED_PLAYER",
>   "cver": "1.20230627.01.00",
>   "cplayer": "UNIPLAYER",
>   "cos": "Macintosh",
>   "cosver": "10_15_7",
>   "cplatform": "DESKTOP",
>   "epm": 1,
>   "hl": "en_GB",
>   "cr": "GB",
>   "len": "28.981",
>   "fexp": "23848211,23858057,23983296,24004644,24007246,24080738,24135310,24208765,24271462,24360281,24364789,24366065,24366917,24380264,24383853,24389415,24415864,24439361,24559327,39324104",
>   "feature": "oembed",
>   "afmt": "251",
>   "size": "546:410",
>   "inview": "0",
>   "muted": "0",
>   "docid": "AjmnjFid2_4",
>   "ei": "uCykZM29BNOvxN8P6rKB4Ag",
>   "plid": "AAX_qhtcchFRGxfw",
>   "referrer": "https://www.youtube.com/embed/AjmnjFid2_4?feature=oembed&autoplay=1&auto_play=1",
>   "of": "ceCrKAuuKchZbE4fVbaJzw",
>   "vm": "CAEQARgEOjJBRmtzQzRxV3lUc3pla3pUUHotYXUyYm9jaWwzak5UdFhBUFlWSEpnYnB4SVRaOThwZ2JkQVBta0tESmFMSlJmX2Q2NEtrNlo3aFVjaDJCcUhUeGxydnFHV2FwUkI5eU01TzV5eGpiblBNQ0RpYjU3ZzM5WFRGMDk0dmppa0RhZWJ2d29vV3dlb3lBa0lFUTdXSEdLczdxNGgB",
>   "vct": "0.000",
>   "vd": "28.981",
>   "vpl": "",
>   "vbu": "0.000-28.981",
>   "vpa": "1",
>   "vsk": "0",
>   "ven": "0",
>   "vpr": "1",
>   "vrs": "4",
>   "vns": "2",
>   "vec": "null",
>   "vemsg": "",
>   "vvol": "1",
>   "vdom": "1",
>   "vsrc": "1",
>   "vw": "546",
>   "vh": "410",
>   "lct": "0.000",
>   "lsk": false,
>   "lmf": false,
>   "lbw": "2798935.556",
>   "lhd": "0.028",
>   "lst": "0.000",
>   "laa": "itag_251_type_3_src_reslicegetRequestInfoForRange_segsrc_reslicegetRequestInfoForRange_seg_2_range_314991-459254_time_20.0-29.0_off_0_len_144264_end_1_eos_1",
>   "lva": "itag_244_type_3_src_reslicegetRequestInfoForRange_segsrc_reslicegetRequestInfoForRange_seg_5_range_2048747-2205960_time_26.7-28.9_off_0_len_157214_end_1_eos_1",
>   "lar": "itag_251_type_3_src_getRequestInfoForRange_segsrc_getRequestInfoForRange_seg_2_range_314991-459254_time_20.0-29.0_off_0_len_144264_end_1_eos_1",
>   "lvr": "itag_244_type_3_src_getRequestInfoForRange_segsrc_getRequestInfoForRange_seg_5_range_2048747-2205960_time_26.7-28.9_off_0_len_157214_end_1_eos_1",
>   "laq": "0",
>   "lvq": "0",
>   "lab": "0.000-28.981",
>   "lvb": "0.000-28.962",
>   "ismb": 13320000,
>   "relative_loudness": "-3.577",
>   "optimal_format": "480p",
>   "user_qual": 0,
>   "release_version": "youtube.player.web_20230627_01_RC00",
>   "debug_videoId": "AjmnjFid2_4",
>   "0sz": "false",
>   "op": "",
>   "yof": "true",
>   "dis": "",
>   "gpu": "ANGLE_(Apple,_Apple_M2_Pro,_OpenGL_4.1)",
>   "debug_playbackQuality": "large",
>   "debug_date": "Tue Jul 04 2023 15:30:20 GMT+0100 (British Summer Time)"
> }
> ```

How interesting! Well, thank you very much for your research into this, I'm glad that it is semi-reproducible and I figured it was likely more to do with YouTube than its embed links or Mastodon, but it's always worth bringing it up! 

My apologies for any time wasted with this, I hope the findings can be helpful in some way in the future!

Thanks again! (I will close with comment, feel free to let me know if it should remain open, or if there is anything else I should mention.

**Comment by forsamori** [comment]
@WolfShadowheart No time wasted at all on this, don't worry - time well spent :)
