### ISSUE TITLE
Some replies don't show up in apps, only when you visit home instance via web.

### ISSUE THREAD

**Issue by eobet** [mastodon/mastodon#25699]
### Steps to reproduce the problem

1. Read replies to a post in an app
2. Look at the same replies on the web
3. Look at the same replies on the web from the originating instance
...

### Expected behaviour

In each case, there should be the same replies

### Actual behaviour

Only when you visit the originating instance do you see all replies

### Detailed description

Mastodon is apparently developed to favour large instances, but if you are on a small instance you sometimes miss replies from other people on small instances.

The way you often notice this is when you see someone reply to a reply and you can't see that original reply.

I could be wrong, but I'm fairly certain it's not because of a block or defederation. I suspect it's because nobody on my server follows anyone on the server of the person who replied (and possibly the poster who got replied to doesn't either).

### Specifications

v4.1.2+glitch

**Comment by eobet** [comment]
I just noticed another thread where I on my instance actually see more replies to the original post than what the original author's instance displays...

**Comment by trwnh** [comment]
If you see more replies on your instance than on the origin instance, it's because the origin instance blocks them. In general, what you see is relative to which server you use. You see whatever is delivered to you, minus whatever is blocked. Delivery happens when at least one person follows or is mentioned by the post author.

**Comment by eobet** [comment]
@trwnh I think you (again) misunderstood what I was saying with the issue I created.

But closing this as I was made aware that they seem to be the same as:

https://github.com/mastodon/mastodon/issues/34
https://github.com/mastodon/mastodon/discussions/22608
