### ISSUE TITLE
Support UnifiedPush

### ISSUE THREAD

**Issue by johnlpe** [mastodon/mastodon#25729]
### Pitch

Please add support for [UnifiedPush](https://unifiedpush.org) push notification protocol/standard.

We need push notifications, but we don’t want use centralized online service that read we all notifications, like Android has Google Firebase Messaging Service and iOS has Apple Push Notification service. UnifiedPush protcol is the solution for this. UnifiedPush is open protocol/standard for connection between online service (Application Server) → notification service (Push Server) and notification service’s client (Push Distributor) → application (End User Application). It enables the user to choose the service through he receives his push notifications.

<img src="https://raw.githubusercontent.com/UnifiedPush/documentation/main/static/img/animation-flow.svg" width="300"/> <img style="float: right;" src="https://github.com/mastodon/mastodon/assets/138632900/a52dd1a5-c972-4e00-8e65-4fec1aa3a5a0" width="300" />

### Motivation

Especially GNU/Linux on mobile is very big need of push notifications and with UnifiedPush we can fix it.

**Comment by johnlpe** [comment]
@Gargron

**Comment by nightpool** [comment]
This is already possible using the open WebPush standard that mastodon supports. See https://docs.joinmastodon.org/methods/push/ for more details
