### ISSUE TITLE
Login button has been pushed off screen (or made too narrow, depending on device screen width) on mobile devices

### ISSUE THREAD

**Issue by josephrocca** [mastodon/mastodon#25730]
### Steps to reproduce the problem

1. Visit mastodon.social on mobile when not logged in
2. Observer that login button has been pushed off the screen, or is too narrow to show any text

For example:

![image](https://github.com/mastodon/mastodon/assets/1167575/1f6efb43-57b2-425f-a4c1-8fe3bf84d7e9)

### Expected behaviour

Login button should be shown properly

### Actual behaviour

Login button is not shown properly on mobile

### Specifications

mastodon.social - v4.1.2+nightly-20230627

Chrome v114

**Comment by renchap** [comment]
This has already been fixed by https://github.com/mastodon/mastodon/pull/25631 and the fix is now deployed on mastodon.social
