### ISSUE TITLE
Much fewer languages in Trending posts/statuses than in Public Timelines' filter language

### ISSUE THREAD

**Issue by KNTRO** [mastodon/mastodon#25731]
### Steps to reproduce the problem

1. This is the list of languages on Public Timelines, at: Settings > Preferences > Other (It's around 198 languages‼ 🤯).
![image](https://github.com/mastodon/mastodon/assets/2568821/fab1ef0a-62c9-4358-8f8e-4f612c487d65)

2. And this is the list of languages at: Admin > Trends > Statuses.
![image](https://github.com/mastodon/mastodon/assets/2568821/034ca04a-8657-4065-ae96-e7f556e5cfc8)

3. As you can tell by the small size of the scrollbar, there's not even the 20% of the languages from the first screenshot. And I'm sure there's A BUNCH of public posts that users liked, replied to, or favorited, every week in OTHER DIFFERENT LANGUAGES beyond the main twentieth or thirtieth ones. Why they don't appear here?

### Expected behaviour

I think more than 40 languages should appear in the language dropdown menu from the Trending posts webpage almost everyday

### Actual behaviour

Usually, no more than 30 languages are displayed instead everyday

### Specifications

Mastodon 4.1.2
Ruby 3.0.6p216
PostgreSQL 9.6.24
Redis 6.0.16

Mozilla Firefox 102.13.0esr (64-bit)

**Comment by Gargron** [comment]
The dropdown only displays languages for which there is something to show.
