### ISSUE TITLE
Unable to precompile assets (Ubuntu 22.04, Node 16.20.1, Yarn 1.22.19)

### ISSUE THREAD

**Issue by sacsar** [mastodon/mastodon#25741]
### Steps to reproduce the problem

1. Follow the instructions through `yarn install --pure-lockfile`
2. Copy `.env.production.sample` to `.env.production` and update it as applicable
3. Run `RAILS_ENV=production bundle exec rails assets:precompile`
4. Fail because `caniuse-lit` is outdated`.
5. Run `npx updatebrowserslist-db@latest` as instructed (this will modify the lock file)
6. Run `RAILS_ENV=production bundle exec rails assets:clobber`
7. Run `RAILS_ENV=production bundle exec rails assets:precompile`

### Expected behaviour

Assets are precompiled

### Actual behaviour

Several `Module parse failed: Unexpected token` errors.

### Detailed description

I get a number of errors of the form:
```
ERROR in ./app/javascript/mastodon/containers/media_container.js 1:999                       
Module parse failed: Unexpected token (1:999)                                                
File was processed with these loaders:                                                       
 * ./node_modules/babel-loader/lib/index.js                                                  
You may need an additional loader to handle the result of these loaders.
```
- `ERROR in ./app/javascript/mastodon/components/relative_timestamp.js 1:4180`
- `ERROR in ./app/javascript/mastodon/features/compose/components/compose_form.js 1:2099`
- `ERROR in ./app/javascript/mastodon/features/ui/components/modal_root.js 1:1798`
- `ERROR in ./app/javascript/mastodon/containers/mastodon.js 1:1399`

Curiously, I also get the same `Module parse failed: Unexpected token` error in as a *warning* in a few files as well.

I have tried bumping `webpack` and `babel` deps with no luck. I don't _think_ I'm running out of memory--I have `--max-old-space-size` set via `NODE_OPTIONS`, which solved the failures about the Javascript heap being out of memory. However, I'm running on a Digital Ocean droplet with 1gb of ram and a 1gb swap file, so it's certainly possible. I wouldn't expect the failure to occur so consistently, though.

I'm changing `parallel: true` in the webpack config to `parallel:false` and seeing what happens now.

### Specifications

Mastodon: 4.1.2
Ubuntu: 22.04.2
yarn: 1.22.19
node: 16.20.1
Bundler: 2.4.15

**Comment by fwenzel** [comment]
I see the same issue on `docker-compose build`: `caniuse-lite is outdated` when building a docker release.

**Comment by ysdev** [comment]
I have seen similar error.
After trying for several hours, I have found that the message `Browserslist: caniuse-lite is outdated.` was just a warning, not an error.
Without executing `npx update-browserslist-db@latest` assets were precompiled as expected.

Trying to roll `yarn.lock` back and run `RAILS_ENV=production bundle exec rails assets:precompile` again might resolve the problem.

**Comment by joshbrand** [comment]
Can confirm a rollback and recompile worked to resolve.

**Comment by gytisrepecka** [comment]
> Trying to roll `yarn.lock` back

How do you do that?

**Comment by renchap** [comment]
> > Trying to roll `yarn.lock` back
> 
> How do you do that?

`git checkout yarn.lock`

Mastodon 4.1 does not support Node 18 and up, and does not support Yarn 3 either.

You need to stick to Node 16 (use `nvm` to install it if needed) and yarn 1 (or "classic").

Once those dependencies are installed, please ensure you remove any local changes, remove your `node_modules/` folder, run `yarn install`, then retry compiling the assets.

**Comment by vmstan** [comment]
@sacsar can you confirm this issue has been resolved for you?
