### ISSUE TITLE
There is no difference with the "posts" tab and the "posts and replies" tab

### ISSUE THREAD

**Issue by CZakarya** [mastodon/mastodon#25748]
### Steps to reproduce the problem

1.Go to an account
2.Click on "posts"
3.Click on "posts and replies"
4.Notice that there are replies on both of them

### Expected behaviour

The posts tab should only have posts

### Actual behaviour

Replies are also in the posts tab

### Detailed description

There doesn't seem to be a difference between the two tabs. If you are only supposed to be able to see posts and replies at the same time, why is there a dedicated tab for posts if it doesn't work.

### Specifications

Mozilla Firefox 102.10.0 ESR
I also noticed this on the Android app (version 2.0.1 (61)

I saw this on mstdn.party and mastodon.social

**Comment by trwnh** [comment]
Self-replies don't count as replies, and boosts are shown on both

**Comment by Zakarya1000** [comment]
I get boosts being shown on both, but why would self replies not count as replies. They are literally called "self replies". Can there at least be a setting for self replies to not be replies?

**Comment by trwnh** [comment]
The reasoning is that self-replies are continuations of a thread, and therefore count as part of the "original post" rather than as a "reply".

**Comment by Zakarya1000** [comment]
For the way I use Mastodon, that makes no sense. Can I have a way to turn that off for my profile, and other people see it too?

**Comment by Zakarya1000** [comment]
I'll do a feature request

**Comment by trwnh** [comment]
Closing as outdated, the tabs have been changed so that

- the first one shows posts, self-replies, and boosts
- the second one shows posts, all replies, and no boosts

Also linking #10011 for a related suggestion that would allow people to better filter profiles instead of hardcoding the above interpretation.
