### ISSUE TITLE
Links from user media are targeting @undefined user

### ISSUE THREAD

**Issue by skobkin** [mastodon/mastodon#25767]
### Steps to reproduce the problem

1. Go to someone's profile.
2. Open "Media"
3. Point to any photo and open it in the new tab or check the DOM tree.

![image](https://github.com/mastodon/mastodon/assets/967576/e252d271-650f-468f-808b-0a29a029f7e6)

### Expected behaviour

Correct link to original post with valid username

### Actual behaviour

Invalid link with "@undefined" username in the URL

### Detailed description

Media links in the profile are broken.

### Specifications

Mastodon 4.1.3

Vivaldi 6.1.3035.100 (Stable channel) stable (64-bit) 
Linux

**Comment by shleeable** [comment]
This is a known bug.. fixed in main.

**Comment by skobkin** [comment]
Good to know. 

I found it a long time ago. Thought that it would be fixed fast, but it wasn't and when I finally went to Github, I didn't find it in the issues. Didn't check in closed though.

**Comment by ClearlyClaire** [comment]
I think this is fixed by #24218

**Comment by skobkin** [comment]
@ClearlyClaire Do you know which release will it be in?

**Comment by trwnh** [comment]
should be in 4.2
