### ISSUE TITLE
Non-latest patch version transiently tagged as latest while CI build ongoing

### ISSUE THREAD

**Issue by davidlougheed** [mastodon/mastodon#25765]
### Steps to reproduce the problem

1. look at the GHCR `mastodon` image tags while build is still ongoing

### Expected behaviour

non-latest versions should never be tagged 'latest' (in this case, 4.0.x when 4.1.x exists)

### Actual behaviour

'momentarily', a mastodon 4.0.x release was tagged as latest

### Detailed description

see screenshot 
![Screen Shot 2023-07-06 at 10 55 21 AM](https://github.com/mastodon/mastodon/assets/357970/1f831fc7-567f-499f-b98f-f76bc6bb4928)

presumably this latest tag will be later moved to the 4.1.x version being published, but this could mean anyone pulling `latest` will accidentally downgrade their version if the action is not yet finished.

### Specifications

GitHub CI

**Comment by renchap** [comment]
Yes this is an issue with our current build system, will need to check how to fix it.

Thanks for reporting!

**Comment by renchap** [comment]
Looks like this PR did not fix it…
