### ISSUE TITLE
Regression: Image previews broke with 4.1.3 upgrade when using ImageMagick older than 6.9.7-7

### ISSUE THREAD

**Issue by maswan** [mastodon/mastodon#25769]
### Steps to reproduce the problem

After a 4.1.3 upgrade images are broken in the feed.

### Expected behaviour

![working](https://github.com/mastodon/mastodon/assets/6428197/2350eec1-1204-4d55-82f3-94d4b11e2492)

### Actual behaviour

![broken](https://github.com/mastodon/mastodon/assets/6428197/5f1f13f8-1b2b-43db-9225-af5babe2062e)

### Detailed description

From sidekiq-logs:

Jul 06 16:21:24 dorkovo.acc.sunet.se bundle[741]: convert-im6.q16: not authorized `/tmp/7789b16fc06c754a4127528ab748041220230706-741-r0qbta20230706-741-nosrkt.png' @ error/constitute.c/ReadImage/412.

### Specifications

Mastodon 4.1.3
Ubuntu 18.04
Imagemagick 8:6.9.7.4+dfsg-16ubuntu6.15

**Comment by ClearlyClaire** [comment]
We've seen reports of this issue with ImageMagick 6.9.7 indeed. We will try to find a fix, but in the meantime, more recent versions of ImageMagick should work.

**Comment by mstdn** [comment]
Just updated to v7 but still same error:

"500Error processing thumbnail for uploaded media"
<img width="619" alt="screen" src="https://github.com/mastodon/mastodon/assets/57602062/889f297f-cd2e-48a4-a1a0-3a7b708ab064">

**Comment by supernovae** [comment]
I have missing images only on random posts - can't see which ones or why.

For example - this particular users inline posts are missing image, but the inline for discord/slack works and the embiggen works. https://universeodon.com/@HamiltonsLive/110667934646324162

**Comment by renchap** [comment]
If you are running an old OS (like Ubuntu 18.04, which is out of support) then your ImageMagick version does not support the policy file from the latest security patches.

We suggest you upgrade your OS at some point, but in the meantime people tried https://github.com/SoftCreatR/imei/#one-step-automated-install to compile a recent version of ImageMagick and it worked fine, so you may want to try this.

**Comment by maswan** [comment]
18.04 does have extended support options for a couple of more years, but yes, we will move to a new server in a while.

**Comment by soupglasses** [comment]
Hachyderm runs correctly with an Arch packaged version of ImageMagick.

Interestingly it packages a lot more into the binary: `Delegates (built-in): bzlib cairo djvu fontconfig freetype heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png raqm raw rsvg tiff webp wmf x xml zip zlib` compared to @mstdn's output.

For @supernovae, it could be that only png images are affected in your instance?

**Comment by mstdn** [comment]
Just recompiled with the right additional packages installed

All seems to work again:
<img width="636" alt="Scherm­afbeelding 2023-07-06 om 18 36 01" src="https://github.com/mastodon/mastodon/assets/57602062/7feee3ae-a389-4e27-9043-20215decdf23">

We still have a lot less delegates though

**Comment by soupglasses** [comment]
My hunch is that the problems come from the missing `jpeg` and/or `png` delegates. I have not looked deeply into this theory however, but seems to be the common factor for functioning vs non-functioning thumbnails.

**Comment by renchap** [comment]
If `convert -version` do not show `jpeg` / `png` in your Delegates, then yes the issue comes from your ImageMagick installation. But then you would have got problems on older Mastodon versions as well.

We identified a change in ImageMagick regarding `<policy pattern="*">` handling somewhere between ImageMagick 6.9 and 6.11, and are trying to figure out how to fix it.

**Comment by amorgner** [comment]
Had the same issue, replacing the policy.xml as described in @maswan's post fixed it for us.

**Comment by ClearlyClaire** [comment]
Upon investigating, we discovered the `policy.xml` we wrote relies on an undocumented change published in ImageMagick 6.9.7-7, meaning that version is the minimum supported version.

At this time, we do not feel confident writing a `policy.xml` that would serve its purpose while maintaining compatibility with earlier versions of ImageMagick. Therefore, we advise updating to more recent versions of ImageMagick.

> Had the same issue here (Ubuntu 18.04.6 LTS, imagemagick 8:6.9.7.4+dfsg-16ubuntu6.15), replacing the policy.xml as described in @maswan's post fixed it for us.

We would strongly advise against doing that.

**Comment by solarbirdy** [comment]
I have complete failure to load images with Debian Bullseye and ImageMagick 6.9.11-60.

**Comment by ClearlyClaire** [comment]
@solarbirdy that is surprising… can you give the output of the following command (ran as the Mastodon user in the code directory)?
```sh
MAGICK_CONFIGURE_PATH=$(pwd)/config/imagemagick identify app/javascript/images/preview.png
```

**Comment by solarbirdy** [comment]
app/javascript/images/preview.png PNG 1200x620 1200x620+0+0 8-bit sRGB 340408B 0.000u 0:00.000

**Comment by amorgner** [comment]
> @solarbirdy that is surprising… can you give the output of the following command (ran as the Mastodon user in the code directory)?
> 
> ```shell
> MAGICK_CONFIGURE_PATH=$(pwd)/config/imagemagick identify app/javascript/images/preview.png
> ```

When I change the `policy.xml` back to the version that shipped with v4.1.3, I get

```$ MAGICK_CONFIGURE_PATH=$(pwd)/config/imagemagick identify app/javascript/images/preview.png
identify-im6.q16: not authorized `app/javascript/images/preview.png' @ error/constitute.c/ReadImage/412.```

**Comment by ClearlyClaire** [comment]
ok so the issue is not the same as other people… is there anything in `mastodon-sidekiq` or `mastodo-web` logs?

**Comment by ClearlyClaire** [comment]
> > @solarbirdy that is surprising… can you give the output of the following command (ran as the Mastodon user in the code directory)?
> > ```shell
> > MAGICK_CONFIGURE_PATH=$(pwd)/config/imagemagick identify app/javascript/images/preview.png
> > ```
> 
> When I change the `policy.xml` back to the version that shipped with v4.1.3, I get
> 
> ```
> identify-im6.q16: not authorized `app/javascript/images/preview.png' @ error/constitute.c/ReadImage/412.```
> ```

Yes, we are aware of that, the `policy.xml` is not interpreted as it should by versions of ImageMagick earlier than 6.9.7-7, and we can't write a policy with the same meaning as far as I know.

**Comment by solarbirdy** [comment]
@ClearlyClaire in the log directory? no. nothing related in syslog either. are there other places to look?

**Comment by ClearlyClaire** [comment]
> @ClearlyClaire in the log directory? no. nothing related in syslog either. are there other places to look?

To see the logs, you'd do `journalctl -u mastodon-web --follow` and `journalctl -u mastodon-sidekiq --follow` and try to upload something

**Comment by solarbirdy** [comment]
@ClearlyClaire unfortunately those are both torrential floods, what should I try to find in there?

**Comment by ClearlyClaire** [comment]
I can't see any obvious error in there. Are you comfortable with sharing your Mastodon instance's URL so I can see if I can spot something else?

**Comment by solarbirdy** [comment]
oh yeah totally - mastodon.murkworks.net, I'm @ moira there.

**Comment by ClearlyClaire** [comment]
```
$ curl https://mastodon.murkworks.net/system/cache/accounts/avatars/109/298/856/993/767/281/original/121d1fa8f753ed45.png
curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

your issue is really weird but lies at the reverse proxy's level, it may be a `nginx` bug, if you have `http2` enable, try disabling that?

**Comment by solarbirdy** [comment]
Huh. Disabled and now we're loading images. That's weird.

**Comment by maswan** [comment]
FWIW: Backporting the ubuntu 20.04 package to 18.04 is a a simple recompile, and now I'm on 6.9.10. The switch to a newer server is planned for this month, but it didn't seem good to wait for that to be patched for this vulnerability.

**Comment by renchap** [comment]
> FWIW: Backporting the ubuntu 20.04 package to 18.04 is a a simple recompile, and now I'm on 6.9.10. The switch to a newer server is planned for this month, but it didn't seem good to wait for that to be patched for this vulnerability.

Could you describe how you backported the package? We will write down a document to help other people hit by this issue

**Comment by gemelen** [comment]
Was trying to apply suggestions from above, but without luck.
So, after an upgrade to 4.1.3 my instance lost image previews for most of the things coming from federated instances. And also, image upload is broken too, both from web and from a mobile app (Tusky in my case).

So far I upgraded ImageMagick, getting
```[root@sidekiq-dzkzqynjg ~]# convert --version
Version: ImageMagick 7.1.1-10 Q16-HDRI x86_64 21178 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5)
Delegates (built-in): bzlib fontconfig freetype gslib heic jng jp2 jpeg lcms lqr lzma png ps tiff webp x xml zlib
Compiler: gcc (12.2)```

and disabled HTTP2 for all parts in Nginx.

**Comment by amorgner** [comment]
I have just compiled ImageMagick-7.1.1, reinstalled the `policy.xml` of v4.1.3 and the error is gone.

Here are the steps to compile and install ImageMagick-7.1.1 on Ubuntu 18.04:

```# apt update
# apt-get install build-essential pkg-config checkinstall libx11-dev libxext-dev zlib1g-dev libpng-dev libfreetype6-dev libxml2-dev libjpeg62-dev
# cd /opt/
# wget http://www.imagemagick.org/download/ImageMagick.tar.gz
# tar xvzf ImageMagick.tar.gz
# cd ImageMagick-7.1.1-12/
# ./configure
# make
# make install
# ldconfig /usr/local/lib
# convert -version
Version: ImageMagick 7.1.1-12 Q16-HDRI x86_64 21239 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5)
Delegates (built-in): freetype jng jpeg png x xml zlib
Compiler: gcc (7.5)```

I still have to add some more IM delegates, but so far it looks good:

```$ MAGICK_CONFIGURE_PATH=$(pwd)/config/imagemagick identify app/javascript/images/preview.png
app/javascript/images/preview.png PNG 1200x620 1200x620+0+0 8-bit sRGB 340408B 0.000u 0:00.000```

**Comment by nightpool** [comment]
I'm trying out IMEI now and it seems to be working well

**Comment by maswan** [comment]
> 



> > FWIW: Backporting the ubuntu 20.04 package to 18.04 is a a simple recompile, and now I'm on 6.9.10. The switch to a newer server is planned for this month, but it didn't seem good to wait for that to be patched for this vulnerability.
> 
> Could you describe how you backported the package? We will write down a document to help other people hit by this issue

First grab the three files in the righthand table of https://packages.ubuntu.com/focal/imagemagick-6.q16:

`wget http://archive.ubuntu.com/ubuntu/pool/universe/i/imagemagick/imagemagick_6.9.10.23+dfsg-2.1ubuntu11.9.dsc
wget http://archive.ubuntu.com/ubuntu/pool/universe/i/imagemagick/imagemagick_6.9.10.23+dfsg.orig.tar.xz
wget http://archive.ubuntu.com/ubuntu/pool/universe/i/imagemagick/imagemagick_6.9.10.23+dfsg-2.1ubuntu11.9.debian.tar.xz`

Install build dependencies (the first row is the build dependencies for the imagemagick that's in 18.04, the second row are the new ones that the new package wants).

`apt build-dep imagemagick`
`apt install libwebp-dev jdupes` 

Extract the source package:

`dpkg-source -x imagemagick_6.9.10.23+dfsg-2.1ubuntu11.9.dsc`

Build the  binary package (unsigned changes, unsigned source):
`cd imagemagick-6.9.10.23+dfsg`
`dpkg-buildpackage -us -uc`

This will create a bunch of packages, it seems like the ones you want to install install are:
`dpkg -i imagemagick_6.9.10.23+dfsg-2.1ubuntu11.9_amd64.deb imagemagick-6-common_6.9.10.23+dfsg-2.1ubuntu11.9_all.deb imagemagick-6.q16_6.9.10.23+dfsg-2.1ubuntu11.9_amd64.deb libmagickwand-6.q16-6_6.9.10.23+dfsg-2.1ubuntu11.9_amd64.deb libmagickcore-6.q16-6_6.9.10.23+dfsg-2.1ubuntu11.9_amd64.deb`

**Comment by maswan** [comment]
Oh  yeah, depending on how tiny your OS install is you might want to `apt install build-essential` as well, that's the basic set of packages that a debian or ubuntu system assumes you have on a host that is able to build packages from source. I already had that installed on my server.

**Comment by renchap** [comment]
Thanks everybody for your help on this.

We created #25776 with more informations on the issue and ways to fix it.

If you are running Ubuntu 18.04, we crafter a custom `policy.xml` file you can use and that still improves the security of your instance.

Release notes have been updated to point to the new issue as well.
