### ISSUE TITLE
Default privacy setting ignored in replies when follow requests are turned on

### ISSUE THREAD

**Issue by timtfj** [mastodon/mastodon#25770]
### Steps to reproduce the problem

1. Set your profile to require follow requests.
2. Set the default posting privacy to Public.
3. Post a public toot
4. Reply to a public post from another user.

### Expected behaviour

The default privacy setting of the reply should be Public.

### Actual behaviour

The default setting of the reply is Followers-only.

### Detailed description

That is, the reply is initially set as Followers-only and has to be manually changed. Most times I forget to do this, and have to either delete-and-redraft or have my reply invisible to other people in the discussion.

I've included "post a public toot" in the steps since this shows that the erroneous setting isn't being remembered from the previous toot.

With follow requests turned off, the privacy setting when replying defaults to Public as expected.

### Specifications

Mastodon 4.1.2 (mastodon.online)
Chrome 114.0.5735.131
Android 7.0; HUAWEI VNS-L31 Build/HUAWEIVNS-L31

**Comment by trwnh** [comment]
can't reproduce on mastodon.social v4.1.2+nightly-20230705 -- possibly fixed?

**Comment by timtfj** [comment]
I tried saving a different default privacy then changing it back to public, and I _think_ replies are now behaving properly, so maybe it's fixed itself. I'll wait a while in case it reappears, though.

Also I'm wondering whether the issue was that I'd never explicitly set the default privacy for that account, simply accepted Public.

**Comment by trwnh** [comment]
> Also I'm wondering whether the issue was that I'd never explicitly set the default privacy for that account,

Maybe?

**Comment by timtfj** [comment]
Closing this as the issue seems to be no longer ocurring.
