### ISSUE TITLE
v4.1.3 /small image not being generated

### ISSUE THREAD

**Issue by hugogameiro** [mastodon/mastodon#25778]
### Steps to reproduce the problem

1. go to a profile that uses dlvr.it to post
2. before v4.1.3 all posts with images render the /small image and after v4.1.3 do not

### Expected behaviour

/small images are generated

### Actual behaviour

/small images are not generated

### Detailed description

Since upgrading to v4.1.3 I see that accounts that use dlvr.it (and on one Tusky) do not have /small images, leaving any view that uses those paths broken.

This is happening on Mastodon.social, see [example](https://mastodon.social/@canal26/media) (click 'load more' and you will see when it stopped working) and I don't believe it's related to #25776.

Looking at the logs in debug mode, no errors are presented and no mentions of /small attempting to be generated or stored.

### Specifications

Mastodon v4.1.3

**Comment by ClearlyClaire** [comment]
Thanks for the report! It is indeed distinct from #25776, and we've seen multiple consistent reports about posts created with dlvr.it having this issue. We're currently investigating.

**Comment by renchap** [comment]
For people arriving on this issue, please note that we plan to release new versions with this fix soon.
