### ISSUE TITLE
Broken images after 4.1.3 / 4.0.5 / 3.5.9 upgrade

### ISSUE THREAD

**Issue by renchap** [mastodon/mastodon#25776]
# Problem description

The recent security releases (4.1.3, 4.0.5, 3.5.9) include a security improvement targeting ImageMagick (used by Mastodon to process image files).

Unfortunately, one of the features used by this patch only works with ImageMagick 6.9.7-7, released in February 2017.

Some older Operation Systems, like Ubuntu 18.04, ship with an ImageMagick version older than this, causing every image processing to fail. Github issue: https://github.com/mastodon/mastodon/issues/25769

# Solutions

## If you are running Ubuntu 18.04

Ubuntu 18.04 is no longer supported, except through Ubuntu's extended support plans. We strongly suggest you plan an Operating System upgrade soon, to a more recent LTS version.

In the meantime, you have 2 ways of solving the issue. You need to do this on every server running Puma (`mastodon-web`) and Sidekiq.

### Use a custom ImageMagick policy file

We crafted a custom ImageMagick policy configuration that should provide the same security as the one included in the latest Mastodon releases. 

Please note this is specific to the ImageMagick provided in Ubuntu 18.04, and should not be used with any other version of ImageMagick (see the Technical Details below for more information).

To use this custom file, you need to override the `config/imagemagick/policy.xml` file with this one:

<details>
<summary>Click here to show the content</summary>

```xml
<policymap>
  <!-- WARNING: This file is specifically meant for the
    ImageMagick version shipped with Ubuntu 18.04 and may not
    be as secure with other versions.

    If possible, update to ImageMagick 6.9.7-7 or newer and use
    the file shipped with Mastodon.
  -->

  <!-- Set some basic system resource limits -->
  <policy domain="resource" name="time" value="60" />

  <policy domain="module" rights="none" pattern="URL" />

  <policy domain="filter" rights="none" pattern="*" />

  <!--
    Ideally, we would restrict ImageMagick to only accessing its own
    disk-backed pixel cache as well as Mastodon-created Tempfiles.

    However, those paths depend on the operating system and environment
    variables, so they can only be known at runtime.

    Furthermore, those paths are not necessarily shared across Mastodon
    processes, so even creating a policy.xml at runtime is impractical.

    For the time being, only disable indirect reads.
  -->
  <policy domain="path" rights="none" pattern="@*" />

  <!-- Disallow any coder by default, and only enable ones required by Mastodon -->
  <policy domain="coder" rights="none" pattern="{BGR,BMP,BRAILLE,CALS,CMYK,DDS,DNG,DOT,EPT,FAX,FITS,GRADIENT,HTML,ICON,INLINE,JBIG,JP2,MAGICK,META,MPEG,MPR,PCD,PCX,PDF,PICT,PLASMA,PNM,PS,PS2,PS3,PSD,RAW,SIXEL,SUN,SVG,TGA,TIFF,TTF,TXT,URL,UYVY,VIFF,WMF,XC,XPM,XTRN,YCbCr}" />
</policymap>
```

</details>

Once this file has been changed, you do not need to restart any process, it will be picked up by new invocations of ImageMagick.

### Compile a custom ImageMagick version

The alternative would be to compile a more recent ImageMagick version on your system.

There are multiple ways of doing so, here are some that have been used by fellow admins:
- Use [ImageMagick Easy Install](https://github.com/SoftCreatR/imei/#one-step-automated-install)
- [Rebuild Ubuntu's 20.04 package into an Ubuntu 18.04 version](https://github.com/mastodon/mastodon/issues/25769#issuecomment-1624245831)
- [Compile ImageMagick 7.1.1 on your server](https://github.com/mastodon/mastodon/issues/25769#issuecomment-1624218698)

## If you are running another Operating system

You need to update your installed ImageMagick version to 6.9.7-7 or more recent. ImageMagick releases contain a lot of security fixes (in addition to the feature we are using), so this would be a good idea anyway.

Please refer to your Operating System documentation on how to do so.

# Technical details

The latest releases add a custom ImageMagick `policy.xml` file, to lockdown ImageMagick capabilities and prevent it from processing any image format that is not supported by Mastodon, as well as set sane resource limits and disable non-used features.

The provided [`policy.xml`](https://github.com/mastodon/mastodon/blob/main/config/imagemagick/policy.xml) file first disable every ImageMagick coders, then enable the ones we want to allow.

Unfortunately, this feature was introduced in version 6.9.7-7. This was not documented in any changelog, but [is mentioned in some other places](https://book.hacktricks.xyz/network-services-pentesting/pentesting-web/imagemagick-security).

Without this feature, you can only disallow the coders you do not want to be used, but this requires you to list all of them, and the list depends on the exact ImageMagick version you are running. This is not suitable for a software like Mastodon, which can be deployed on many different systems with a wide range of ImageMagick versions.

**Comment by carstencodes** [comment]
Hello there,

I am experiencing still broken images.

I am running Mastodon 4.1.4 on docker. This contains imagemagick 6.9.11

I have also updated the policy.xml file, but it does not work. Is there anything else to try?

Regards

Carsten

**Comment by renchap** [comment]
If you are running ImageMagick 6.9.11, the you dont need the custom `policy.xml` file and you should revert this change.

Can you check your Puma and Sidekiq logs when you upload an image and check if you have any errors there?

**Comment by carstencodes** [comment]
Ok, I'll do. But the issue does not appear when uploading images but when looking at images from my timeline.

**Comment by suchipi** [comment]
Thank you so much for the detailed writeup, @renchap! This fixed my issue.

**Comment by tbolon** [comment]
For others here struggling to find the version of imagemagick installed on their distribution, use `convert -version` command.

**Comment by bagoker** [comment]
hi folks, sorry to resurrect this but I'm having the same issue.
I managed to figure out that I was running Ubuntu 18.04 so I figured the problem was caused by my old OS version, but I'm still having this issue even on 22.04. I've updated the system, all packages, and Masto to 4.1.6. Imagemagick is above the recommended minimum (I've got 7.1.1-15). Any advice appreciated and please let me know if you want me to get logs for you and where from.

**Comment by razzeee** [comment]
@bagoker did you figure this out, I'm seeing something similar on an instance

**Comment by abejaranoh** [comment]
Hallo everyone, not sure if this is the right place to post this... but we just installed a mastodon instance on ubuntu 22 and we cant see any image, internal or external https://mastodon.flisol.info/@fosdem@fosstodon.org we are using version 4.2.5. Does anyone have an idea?

thanks
