### ISSUE TITLE
Repository docker compose file does meet best practice wrt image tagging

### ISSUE THREAD

**Issue by thewishy** [mastodon/mastodon#25772]
### Steps to reproduce the problem

#25766 comments that best practice is not to use latest, but to specify an image version.

The repository example docker-compose file does not specify any tags, and those using it as an example are therefore unlikely to include the tags. 

### Expected behaviour

Example docker-compose.yml should reference a tag, if this is indeed best practice

### Actual behaviour

No tag is specified

### Detailed description

I'd suggest that the docker compose example is updated to reference either the current release, or a tag of "example" and a comment that this should be updated to a target release

### Specifications

N/A

**Comment by vmstan** [comment]
Specific tags are currently specified in `docker-compose.yml`
