### ISSUE TITLE
List management needs improvement and hashtag support.

### ISSUE THREAD

**Issue by steinareliassen** [mastodon/mastodon#25818]
### Pitch

Lists are a great feature of mastodon to allow the user to see a portion of followers, but the usage is limited by a non-intuitive interface.

I want to be able to edit a list, and have an overview over all the friends AND hashtags I follow, and simply click a checkbox next to their name to add them to the list.

### Motivation

List functionality would be a lot more used, adding a clear benefit to mastodon, if the UI to manage lists was a bit easier to use.

In addition, not being able to add hashtags you follow to a list is a clear disadvantage.

**Comment by brendanjones** [comment]
Might want to make the separate parts of this more specific. The adding hashtags to lists part is already covered by https://github.com/mastodon/mastodon/issues/7692, so this is duplicate.

**Comment by trwnh** [comment]
#22623 is related as well, but this issue is asking for the management to be done from the "list edit" UI rather than the "following manager" UI.

**Comment by steinareliassen** [comment]
@trwnh @brendanjones 

There are probably a few issues that can spin off this, like it is very unintuitive now how to get to list management (go to list, click the settings on the top right of the list, rather than a visible edit button), and the fact that lists are shown under "PERSONAL", while followers are a set under preferences, this seems highly illogical, a list is a group of friends and those things belong together.

My main problem however is how to add a person to a list. I get a lil search thing and I need to remember what friends I have in order to add them. I then end up having to have my friends list open in one tab of a browser and the list edit functionality open in another tab, switch between them to remember who is on my list, so that I can add them.

What I want is to have my list of followers / following, and be able to click on a person I am following (or more) by checking  the the checkbox, and clicking "add to list". When adding to a list, I can also get the option to create a new list. Similarly I want to be able to see what list the person I follow is on, and remove them from the list from the following UI directly.

There are different solutions to do this that are equally user friendly, but as it is now, having to go to the list edit and manually search up users is not one of them. As it is now, I am tempted to create a tool to manage users / lists in an easier fashion (via rest apis), but I feel it would be best if this was a part of core mastodon features.

**Comment by trwnh** [comment]
You can do this per-profile by going to a profile > menu > "Add or remove from lists", or you can do it per-list by editing the list and searching up sccounts that you follow. Yes, you could probably streamline it a bit by doing it from the following list and/or relationship manager, instead of having to open each profile.

**Comment by steinareliassen** [comment]
@trwnh 

Per profile would be a simpler way to do it, if I from the following list got to the profile view from my server when I clicked on the follower. I don't, instead I am taken to the profile view on their server.

I then have to copy the profile URL into the search field and search for it, in order to open the "local view" of the profile where I can add / remove user from list.

Maybe this could be then solved easily if the overview of followers / following allowed me to open the users profile viewed from my instance, instead of on their instance

https://mymastodon.instance/@user@theirmastaton.instance

instead of
https://theirmastodon.instance/@user

Each user on my follower page is mentioned with the users name as a link to their profile, and their mastodon user-address. One of them could link to a local version of the profile.

**Comment by trwnh** [comment]
I meant that you can already do per-profile:

![image](https://github.com/mastodon/mastodon/assets/10606431/33012370-8f04-4e03-abe0-8b195aeac62b)

> if I from the following list got to the profile view from my server when I clicked on the follower. I don't, instead I am taken to the profile view on their server.

This is weird, it definitely should load locally. Which server are you on? When I click on someone I'm following from my following list, it opens in-app.

**Comment by steinareliassen** [comment]
Just to make sure we are on the same page. If I am on
https://mymastodon.instance/relationships

And click on a user there, I am taken off server. If I click on a user in my feed, 

https://mymastodon.instance/home , I am taken to an "in app" view of their profile.

https://mymastodon.instance/relationships is however where it is most logically for me to manage my friend / lists.

I am on mastodon.green, running v4.1.4

**Comment by trwnh** [comment]
OK, yeah, that matches what should be happening. The `/relationships` page is rendered in a settings page and not in the web-app. If you want to manage lists from there, that would be #22623.

**Comment by steinareliassen** [comment]
Yes, this would make it more or less exactly what #22623 is asking for. I would think a simple fix to make it a lot easier to manage was simply to render one of the lines for the user to be a link to https://theirmastodon.instance/@user to quickly get to the profile. I'll close this issue then as this then has become a duplicate :)
