### ISSUE TITLE
Some endpoints are not cached by Varnish because of authorization / cookie headers

### ISSUE THREAD

**Issue by emilweth** [mastodon/mastodon#25826]
### Steps to reproduce the problem

Add varnish in front of mastodon-web
Make queries to these endpoints while being connected : 
 - `/api/v1/custom_emojis`
 - `/api/v(1|2)/instance`
 - `/api/v1/instance/translation_languages`

### Expected behaviour

Varnish caching these endpoints, according to cache-control

### Actual behaviour

Varnish not caching them because of Authorization / Cookie header in the request

### Specifications

Mastodon v4.1.4+nightly-20230708 on Kubernetes

**Comment by Gargron** [comment]
Do you have read replicas setup with Makara?

**Comment by emilweth** [comment]
At the moment I wrote the issue, yes
But Varnish is not caching them because of the Authorization / Cookie header in the request; not in the response

**Comment by Gargron** [comment]
I believe it may not be possible to omit sending a cookie for API requests made through JS as long as the page and the API are on the same domain, so this could be a "wontfix".
