### ISSUE TITLE
Can't follow someone on misskey.io

### ISSUE THREAD

**Issue by yaomtc** [mastodon/mastodon#25844]
### Steps to reproduce the problem

1. I try to follow this person: https://mastodon.social/@takuyarawr@misskey.io/
2. On the Android app it says "Pending", and on desktop it says "Cancel follow"
3. Checked again later, I see it hasn't changed

This person does not have follows restricted, I do not need their approval to follow, but it doesn't go through.

![Screenshot_20230708_225210](https://github.com/mastodon/mastodon/assets/5534045/a1ca7f69-f3a6-4b66-b39a-1663adedcd6d)

### Expected behaviour

Should be able to follow right away

### Actual behaviour

The "follow" function doesn't work

### Specifications

Using Firefox on Linux and the Mastodon Android app (2.0.1) from F-Droid.

**Comment by sinoru** [comment]
It can be occurred by misskey.io own side, which is caused by these days misskey.io is unstabled.

**Comment by ryliejamesthomas** [comment]
Which instance are you on? Mastodon.social is blocked by misskey.io

**Comment by yaomtc** [comment]
Huh... Mastodon.social, yes. That's odd. Thank you for the info.

**Comment by yaomtc** [comment]
Mastodon.social is now refederated(?) with Misskey.io.
