### ISSUE TITLE
Remove 500 character limit

### ISSUE THREAD

**Issue by johnlpe** [mastodon/mastodon#25852]
Mastodon is an ActivityPub server and it allows read content without limits. Please, remove 500 charter limit and allow Mastodon users also post content without limits. Besides, some services (that run Mastodon) already disable the restriction.

**Comment by EmilJacobs** [comment]
I agree the limit should at least be customisable by the instance admins. Now there is a way to do it, if you run your own instance, by editing the config files. I'm not sure if this also allows for there to be no limit at all and I'm not sure if no limit at all is helpful. But the current limit of 500 is too limiting.

Now, I host my instance with masto.host, which for maintenance reasons indicated they're not willing to change the config files, which is a reasonable position. Therefore, this is an upstream issue: let admins decide what the limit should be.

**Comment by hny-gd** [comment]
It would indeed be nice to be able to increase the limit without having to patch  the source code but instead in a configuration setting somewhere.
