### ISSUE TITLE
the backspace-to-go-back feature interferes with browsers that already implement the feature globally.

### ISSUE THREAD

**Issue by Zazcallabah** [mastodon/mastodon#25862]
### Steps to reproduce the problem

1. use firefox
2. use `about:config` to set the `browser.backspace_action` property to 0. this enables backspace-to-go-back.
3. open any mastodon page.
4. navigate around
5. press backspace

### Expected behaviour

go back one page

### Actual behaviour

you go back two pages, because both the browser and the page navigates back one step.

### Detailed description

The issue is somewhat deep. Someone felt that backspace-to-go-back was essential to a webpage, and when chrome et al removed the feature from major browsers, they added it to mastodon to compensate.

I feel this is bad practice, the feature was removed from major browsers for a reason. A bad reason, in my opinion, but it should not be re-implemented by websites on an arbitrary basis. Core navigation should be provided by the browser.

In either case, it needs to be optional if it isnt removed, so firefox users that have enabled the browser-feature (or other browser users that use extensions to enable the feature) can use mastodon.

https://github.com/mastodon/mastodon/issues/8432 is related, but was closed without discussing nor fixing the root cause.

### Specifications

Mastodon v4.1.4
Firefox 115.0.1

**Comment by fruchti** [comment]
This can probably be fixed by adding the event parameter `e` to `handleHotkeyBack` and calling `e.preventDefault();`. I don’t run a Mastodon instance, so I sadly cannot test this.

**Comment by DanielGibson** [comment]
This problem still persists.
