### ISSUE TITLE
New post toast doesn't style correctly for light theme users

### ISSUE THREAD

**Issue by vmstan** [mastodon/mastodon#25910]
### Steps to reproduce the problem

1. Use light theme
2. Post new status
3. Toast does not have correct coloring
...
Since PR https://github.com/mastodon/mastodon/pull/25564 the new toast does not have visible text for users of the light theme.

<img width="249" alt="CleanShot 2023-07-11 at 08 48 17@2x" src="https://github.com/mastodon/mastodon/assets/3002053/c251f533-d780-4c6a-a16d-240b5bfba525">

### Expected behaviour

Visible text

### Actual behaviour

Not visible text

### Detailed description

Either the entire box should be styled for light users, or the text color be inverted

### Specifications

Mastodon 4.1.4 + main

**Comment by nickjuntilla** [comment]
How do you set the theme to light?
