### ISSUE TITLE
"Show today's trends" checkbox not respected on nightly

### ISSUE THREAD

**Issue by bchandos** [mastodon/mastodon#25925]
### Steps to reproduce the problem

1. Be on v4.1.4+nightly-20230711
2. Uncheck "Show today's trends" in settings

### Expected behaviour

On mobile, "hashtag" icon should be replaced with a "search" icon, and no trending posts should be displayed after clicking.

### Actual behaviour

Trending posts, hashtags, and news appear in the interface.

### Detailed description

I'm using mastodon.online, which I understand is always running nightly. Very recently, I noticed the "search" icon in my the mobile web interface had been replaced with the default "hashtag" icon, and shows trending posts, hashtags, and news. I had explicitly turned this feature off.

I toggled this setting (saving in between), but it remains with the default display of trending items.

I apologize I don't have alternate accounts on other servers to confirm this is related to the nightly, nor the means to spin up a test environment.

### Specifications

Server v4.1.4+nightly-20230711
Android 13, Vivaldi (chromium) browser

**Comment by Gargron** [comment]
The option is only intended for disabling the trends at the bottom right of the screen.

**Comment by bchandos** [comment]
I apologize for misunderstanding this feature. However I'm quite certain the behavior has changed. The search icon has changed and that tab is now filled with popular posts and hashtags, where is was a plain search input previously. What changed?

**Comment by horaceyoung** [comment]
> I apologize for misunderstanding this feature. However I'm quite certain the behavior has changed. The search icon has changed and that tab is now filled with popular posts and hashtags, where is was a plain search input previously. What changed?

Got to know this feature from a user from my instance. This toggle can be misleading in its function (from turning off Explore entirely to only turning off a section on the screen). Adding some explanation would be better.
