### ISSUE TITLE
Cannot change email address

### ISSUE THREAD

**Issue by fsutter** [mastodon/mastodon#25936]
### Steps to reproduce the problem

1. Go to Account setting
2. Enter a new email address

### Expected behaviour

My email address should be updatable.

### Actual behaviour

Got: "Something isn't quite right yet! Please review the error below"

### Detailed description

Hi,

Initially I've registered with a gmail address.
I wanted to change it to a personal (domain that I own) one.

But I got this error:
![image](https://github.com/mastodon/mastodon/assets/54981491/44c8e03b-9fed-409d-b43e-285eb077e754)

I cannot understand why my personal domain is not allowed.

Many thanks in advance and kind regards. 

fsutter

### Specifications

Microsoft Edge

**Comment by renchap** [comment]
This is an issue with your particular instance, you should contact their admin to know why they blocked your domain.
