### ISSUE TITLE
Hundreds of slow queries after posting to 40k followers

### ISSUE THREAD

**Issue by wiegelmann** [mastodon/mastodon#25949]
### Steps to reproduce the problem

Publish a post to 40k followers on a 6 year old instance.

### Expected behaviour

Sidekiq should process the publishing jobs in background.

### Actual behaviour

UI freezes for minutes and CPU load jumps to 400% for Postgres

### Detailed description

PostgreSQL slow query log shows multiple slow queries after posting something.

Accounts table with 700k rows. Already re-indexed and executed VACUUM on the accounts table.

**The following query with 3462 ids in the where clause**

`LOG:  duration: 3224.768 ms  execute <unnamed>: SELECT "accounts"."username", "accounts"."domain", "accounts"."private_key", "accounts"."public_key", "accounts"."created_at", "accounts"."updated_at", "accounts"."note", "accounts"."display_name", "accounts"."uri", "accounts"."url", "accounts"."avatar_file_name", "accounts"."avatar_content_type", "accounts"."avatar_file_size", "accounts"."avatar_updated_at", "accounts"."header_file_name", "accounts"."header_content_type", "accounts"."header_file_size", "accounts"."header_updated_at", "accounts"."avatar_remote_url", "accounts"."locked", "accounts"."header_remote_url", "accounts"."last_webfingered_at", "accounts"."inbox_url", "accounts"."outbox_url", "accounts"."shared_inbox_url", "accounts"."followers_url", "accounts"."protocol", "accounts"."id", "accounts"."memorial", "accounts"."moved_to_account_id", "accounts"."featured_collection_url", "accounts"."fields", "accounts"."actor_type", "accounts"."discoverable", "accounts"."also_known_as", "accounts"."silenced_at", "accounts"."suspended_at", "accounts"."hide_collections", "accounts"."avatar_storage_schema_version", "accounts"."header_storage_schema_version", "accounts"."devices_url", "accounts"."sensitized_at", "accounts"."suspension_origin", "accounts"."trendable", "accounts"."reviewed_at", "accounts"."requested_review_at" FROM "accounts" WHERE "accounts"."id" IN ($1, $2, $3, ...... $3462)`

**Plus 377 queries with parameters: $1 = '1' and each taken 2500 - 3500 ms**

`LOG:  duration: 2650.217 ms  execute <unnamed>: SELECT "accounts"."username", "accounts"."domain", "accounts"."private_key", "accounts"."public_key", "accounts"."created_at", "accounts"."updated_at", "accounts"."note", "accounts"."display_name", "accounts"."uri", "accounts"."url", "accounts"."avatar_file_name", "accounts"."avatar_content_type", "accounts"."avatar_file_size", "accounts"."avatar_updated_at", "accounts"."header_file_name", "accounts"."header_content_type", "accounts"."header_file_size", "accounts"."header_updated_at", "accounts"."avatar_remote_url", "accounts"."locked", "accounts"."header_remote_url", "accounts"."last_webfingered_at", "accounts"."inbox_url", "accounts"."outbox_url", "accounts"."shared_inbox_url", "accounts"."followers_url", "accounts"."protocol", "accounts"."id", "accounts"."memorial", "accounts"."moved_to_account_id", "accounts"."featured_collection_url", "accounts"."fields", "accounts"."actor_type", "accounts"."discoverable", "accounts"."also_known_as", "accounts"."silenced_at", "accounts"."suspended_at", "accounts"."hide_collections", "accounts"."avatar_storage_schema_version", "accounts"."header_storage_schema_version", "accounts"."devices_url", "accounts"."sensitized_at", "accounts"."suspension_origin", "accounts"."trendable", "accounts"."reviewed_at", "accounts"."requested_review_at" FROM "accounts" WHERE "accounts"."domain" IS NULL AND "accounts"."suspended_at" IS NULL AND (id > 0) ORDER BY "accounts"."id" ASC LIMIT $1`

All queries using the same parameter:

DETAIL:  parameters: $1 = '1'

### Specifications

Mastodon 4.1.4
Postgres 15

![Screenshot 2023-07-20 at 11 37 48](https://github.com/mastodon/mastodon/assets/6149471/73da28bd-8169-4cb4-9316-db2f3ee7eff6)

**Comment by mjankowski** [comment]
I'm not sure this matters for the query speed, but is this on a single user instance? (trying to pin down where the slowness occurs on backend).

Can you run this in rails console: `Account.local.without_suspended.where('id > 0').explain`

And paste the QUERY PLAN portion of the output?

**Comment by wiegelmann** [comment]
Yes, from a single-user instance.

```
EXPLAIN for: SELECT "accounts"."username", "accounts"."domain", "accounts"."private_key", "accounts"."public_key", "accounts"."created_at", "accounts"."updated_at", "accounts"."note", "accounts"."display_name", "accounts"."uri", "accounts"."url", "accounts"."avatar_file_name", "accounts"."avatar_content_type", "accounts"."avatar_file_size", "accounts"."avatar_updated_at", "accounts"."header_file_name", "accounts"."header_content_type", "accounts"."header_file_size", "accounts"."header_updated_at", "accounts"."avatar_remote_url", "accounts"."locked", "accounts"."header_remote_url", "accounts"."last_webfingered_at", "accounts"."inbox_url", "accounts"."outbox_url", "accounts"."shared_inbox_url", "accounts"."followers_url", "accounts"."protocol", "accounts"."id", "accounts"."memorial", "accounts"."moved_to_account_id", "accounts"."featured_collection_url", "accounts"."fields", "accounts"."actor_type", "accounts"."discoverable", "accounts"."also_known_as", "accounts"."silenced_at", "accounts"."suspended_at", "accounts"."hide_collections", "accounts"."avatar_storage_schema_version", "accounts"."header_storage_schema_version", "accounts"."devices_url", "accounts"."sensitized_at", "accounts"."suspension_origin", "accounts"."trendable", "accounts"."reviewed_at", "accounts"."requested_review_at" FROM "accounts" WHERE "accounts"."domain" IS NULL AND "accounts"."suspended_at" IS NULL AND (id > 0)

QUERY PLAN

 Gather  (cost=1000.00..119038.27 rows=1 width=1457)
   Workers Planned: 2
   ->  Parallel Seq Scan on accounts  (cost=0.00..118038.17 rows=1 width=1457)
         Filter: ((domain IS NULL) AND (suspended_at IS NULL) AND (id > 0))
 JIT:
   Functions: 2
   Options: Inlining false, Optimization false, Expressions true, Deforming true
(7 rows)
```

**Comment by mjankowski** [comment]
Few more ideas...

How many total account rows are there? - run `Account.count` in rails console

Can you figure out the `accounts.id` value for the single user account, and then run:

`Account.local.without_suspended.where('id = 123').limit(1).explain`

...substituting whatever their ID is instead of 123.

From either a `psql` session or `rails dbconsole` session, can you run:

`select indexname, indexdef from pg_indexes where tablename = 'accounts';`

**Comment by wiegelmann** [comment]
After some cleanup jobs reduced the accounts table to 583k rows:

`Account.count`
=> 583604

`Account.local.without_suspended.where('id = 1').limit(1).explain`
=> 
EXPLAIN for: SELECT "accounts"."username", "accounts"."domain", "accounts"."private_key", "accounts"."public_key", "accounts"."created_at", "accounts"."updated_at", "accounts"."note", "accounts"."display_name", "accounts"."uri", "accounts"."url", "accounts"."avatar_file_name", "accounts"."avatar_content_type", "accounts"."avatar_file_size", "accounts"."avatar_updated_at", "accounts"."header_file_name", "accounts"."header_content_type", "accounts"."header_file_size", "accounts"."header_updated_at", "accounts"."avatar_remote_url", "accounts"."locked", "accounts"."header_remote_url", "accounts"."last_webfingered_at", "accounts"."inbox_url", "accounts"."outbox_url", "accounts"."shared_inbox_url", "accounts"."followers_url", "accounts"."protocol", "accounts"."id", "accounts"."memorial", "accounts"."moved_to_account_id", "accounts"."featured_collection_url", "accounts"."fields", "accounts"."actor_type", "accounts"."discoverable", "accounts"."also_known_as", "accounts"."silenced_at", "accounts"."suspended_at", "accounts"."hide_collections", "accounts"."avatar_storage_schema_version", "accounts"."header_storage_schema_version", "accounts"."devices_url", "accounts"."sensitized_at", "accounts"."suspension_origin", "accounts"."trendable", "accounts"."reviewed_at", "accounts"."requested_review_at" FROM "accounts" WHERE "accounts"."domain" IS NULL AND "accounts"."suspended_at" IS NULL AND (id = 1) LIMIT $1 [["LIMIT", 1]]

QUERY PLAN

Limit  (cost=0.42..8.44 rows=1 width=1458)
   ->  Index Scan using index_accounts_on_id on accounts  (cost=0.42..8.44 rows=1 width=1458)
         Index Cond: (id = 1)
         Filter: ((domain IS NULL) AND (suspended_at IS NULL))
(4 rows)

`select indexname, indexdef from pg_indexes where tablename = 'accounts';`

 index_accounts_on_id                        | CREATE UNIQUE INDEX index_accounts_on_id ON public.accounts USING btree (id)
 index_accounts_on_uri                       | CREATE INDEX index_accounts_on_uri ON public.accounts USING btree (uri)
 index_accounts_on_moved_to_account_id       | CREATE INDEX index_accounts_on_moved_to_account_id ON public.accounts USING btree (moved_to_account_id) WHERE (moved_to_account_id IS NOT NULL)
 index_accounts_on_url                       | CREATE INDEX index_accounts_on_url ON public.accounts USING btree (url text_pattern_ops) WHERE (url IS NOT NULL)
 index_accounts_on_username_and_domain_lower | CREATE UNIQUE INDEX index_accounts_on_username_and_domain_lower ON public.accounts USING btree (lower((username)::text), COALESCE(lower((domain)::text), ''::text))
 search_index                                | CREATE INDEX search_index ON public.accounts USING gin ((((setweight(to_tsvector('simple'::regconfig, (display_name)::text), 'A'::"char") || setweight(to_tsvector('simple'::regconfig, (username)::text), 'B'::"char")) || setweight(to_tsvector('simple'::regconfig, (COALESCE(domain, ''::character varying))::text), 'C'::"char"))))
(6 rows)

**Comment by mjankowski** [comment]
In the Rails console, can you run both of these and report back on how long the sql query takes (should be visible in console itself, or in logs) for each?

`Account.local.without_suspended.where('id > 0').first`

`Account.local.without_suspended.where('id = 1').first`

**Comment by wiegelmann** [comment]
timing = Benchmark.measure

`Account.local.without_suspended.where('id > 0').first`

timing.to_s()
=> "  0.002647   0.000000   0.002647 (  0.239045)\n"

`Account.local.without_suspended.where('id = 1').first`

timing.to_s()
=> "  0.002256   0.000170   0.002426 (  0.003288)\n"

**Comment by mjankowski** [comment]
I suspect that when this - https://github.com/mastodon/mastodon/pull/25126 - makes it into a release, it might help that query. Specifically, the `index_accounts_on_domain_and_id` key might be used by the query planner to find the local user with the index and avoid the scan.

**Comment by bt90** [comment]
> Yes, from a single-user instance.
> 
> ```
> EXPLAIN for: SELECT "accounts"."username", "accounts"."domain", "accounts"."private_key", "accounts"."public_key", "accounts"."created_at", "accounts"."updated_at", "accounts"."note", "accounts"."display_name", "accounts"."uri", "accounts"."url", "accounts"."avatar_file_name", "accounts"."avatar_content_type", "accounts"."avatar_file_size", "accounts"."avatar_updated_at", "accounts"."header_file_name", "accounts"."header_content_type", "accounts"."header_file_size", "accounts"."header_updated_at", "accounts"."avatar_remote_url", "accounts"."locked", "accounts"."header_remote_url", "accounts"."last_webfingered_at", "accounts"."inbox_url", "accounts"."outbox_url", "accounts"."shared_inbox_url", "accounts"."followers_url", "accounts"."protocol", "accounts"."id", "accounts"."memorial", "accounts"."moved_to_account_id", "accounts"."featured_collection_url", "accounts"."fields", "accounts"."actor_type", "accounts"."discoverable", "accounts"."also_known_as", "accounts"."silenced_at", "accounts"."suspended_at", "accounts"."hide_collections", "accounts"."avatar_storage_schema_version", "accounts"."header_storage_schema_version", "accounts"."devices_url", "accounts"."sensitized_at", "accounts"."suspension_origin", "accounts"."trendable", "accounts"."reviewed_at", "accounts"."requested_review_at" FROM "accounts" WHERE "accounts"."domain" IS NULL AND "accounts"."suspended_at" IS NULL AND (id > 0)
> 
> QUERY PLAN
> 
>  Gather  (cost=1000.00..119038.27 rows=1 width=1457)
>    Workers Planned: 2
>    ->  Parallel Seq Scan on accounts  (cost=0.00..118038.17 rows=1 width=1457)
>          Filter: ((domain IS NULL) AND (suspended_at IS NULL) AND (id > 0))
>  JIT:
>    Functions: 2
>    Options: Inlining false, Optimization false, Expressions true, Deforming true
> (7 rows)
> ```

Wait. Did the JIT compiler really trigger for that simple query?

**Comment by wiegelmann** [comment]
Looks better now. Thanks!
