### ISSUE TITLE
New search button on top bar on Android mobile web UI pushes profile avatar off the screen

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#25990]
### Steps to reproduce the problem

1. Have a Pixel 6a running Android 13.
2. Use the browser Firefox.
3. "Install" a Glitch instance via "Add to Home screen", and log in.
4. It looks like this, with the profile avatar at the top right shoved off the side of the screen, and it doesn't scroll to the side:
![photo_2023-07-13_20-19-01](https://github.com/glitch-soc/mastodon/assets/6607512/d5cdf5f1-9a66-4df1-9e1c-32702bf95a6e)

### Expected behaviour

Space for everything on the top bar of the UI.

### Actual behaviour

Avatar gets shoved off the right side of the screen.

### Detailed description

I initially reported this here: https://github.com/glitch-soc/mastodon/issues/2298 Because I thought it was a Glitch (fork) issue, but then was asked to put it here.

### Specifications

v4.1.3+glitch

Android 13, Pixel 6a

Firefox

**Comment by tfardet** [comment]
This issue could be corrected by dropping this new icon and replacing the error-inducing hashtag icon in the left menu by a search icon, thus fixing #19768 at the same time.

**Comment by Cassolotl** [comment]
Yeah, that'd work. I was also thinking that if the profile avatar gets shoved off the side of the screen, the site could detect that and change the full length "mastodon" logo to just an "m" with the elephant head, or something else equally shorter.

**Comment by renchap** [comment]
Fixed by #29787
