### ISSUE TITLE
upload audio files

### ISSUE THREAD

**Issue by RustoMCSpit** [mastodon/mastodon#26020]
### Pitch

i want to upload my song files but mastodon onky accepts images and videos

### Motivation

to share music and audio recordings in .mp3 and .ogg

**Comment by beryllium** [comment]
I believe this is already supported?

https://docs.joinmastodon.org/user/posting/#media

> _Audio (MP3, OGG, WAV, FLAC, OPUS, AAC, M4A, 3GP) up to 40MB. Audio will be transcoded to MP3 using V2 VBR (roughly 192kbps)._
