### ISSUE TITLE
warning: already initialized constant

### ISSUE THREAD

**Issue by Modrx** [mastodon/mastodon#26047]
### Steps to reproduce the problem

RAILS_ENV=production bundle exec rake mastodon:setup

### Expected behaviour

no warnings

### Actual behaviour

showing warnings

### Detailed description

When I run the following command:

RAILS_ENV=production bundle exec rake mastodon:setup

I am getting the following warnings:

/usr/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/var/www/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/usr/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/var/www/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:214: warning: previous definition of BUFSIZE was here
/usr/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/var/www/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:541: warning: previous definition of Socket was here

### Specifications

Mastodon 4.1.4
Ruby 2.7
Node 16.20.1

**Comment by mjankowski** [comment]
At whatever point you upgrade Mastodon and/or Ruby, can you confirm whether you still see this output? (Ruby 2.7 is past EOL, and even 3.0 will be EOL soon)
