### ISSUE TITLE
New instance, file uploads & federation not working

### ISSUE THREAD

**Issue by pinkgator** [mastodon/mastodon#26082]
### Steps to reproduce the problem

1. Set up Mastodon according to [the guide on the docs site](https://docs.joinmastodon.org/admin/install/) using the setup wizard
2. [Load site in browser](https://fedi.valentines.monster)
3. Attempt to upload avatar & banner, failed
4. Attempt to upload post with image attachment, failed
5. Attempt to load profile on a different instance by doing [the same way I would on other instances](https://fedi.valentines.monster/@miles@denden.world), failed

### Expected behaviour

Images should have uploaded properly, profile should have loaded after a moment

### Actual behaviour

Image uploads gave "Something went wrong on our end" and "500 Internal Server Error" & profile is loading forever

### Detailed description

I went through journalctl and for each attempt to upload an image it gave "Aws::S3::Errors::XAmzContentSHA256Mismatch (Aws::S3::Errors::XAmzContentSHA256Mismatch)
As for loading the profile, there aren't any error messages from it.
[Trying to load the admin profile on another instance](https://toot.cat/@snake@fedi.valentines.monster) yielded a 404 error.
I'm thinking I configured the object storage wrong but I'm not entirely sure how to fix that.

I want to clarify that I don't have a lot of experience with this, just wanted to make a personal instance for myself and people I know so I don't have to deal with worrying about the rules of other instances. In other words please put things as plainly as possible

### Specifications

Mastodon 4.1.4
Ruby 3.0.4
Node.js 16.18.1

Firefox 115.0.2

**Comment by rasos** [comment]
This looks as there is something wrong with your S3 AWS setup.

**Comment by pinkgator** [comment]
> This looks as there is something wrong with your S3 AWS setup.

I think so too, but I'm not really sure what I did wrong, how to check that, or how to fix it. Going through the documentation and trying things didn't give me anything that fixed it.

**Comment by pinkgator** [comment]
didn't mean to close it

**Comment by pinkgator** [comment]
> This looks as there is something wrong with your S3 AWS setup.

I think so too, but I'm not sure what I did wrong or how to fix it. I went through the documentation & nothing I did affected anything

**Comment by pinkgator** [comment]
i went through and tried to follow [the proxying object storage](https://docs.joinmastodon.org/admin/optional/object-storage-proxy/) guide thinking maybe I did something wrong the first time I tried it, and upon trying to reload nginx i got "Job for nginx.service failed."
Tried what the top reply [here](https://www.reddit.com/r/Mastodon/comments/yn8psg/failing_to_create_certs_for_nginx_during_install) said and after stopping nginx it's refusing to start at all, keeps giving "failed with result 'exit code'"
![help2](https://github.com/mastodon/mastodon/assets/66587281/28cb37a8-13a1-426b-8caa-f8174e52695a)
![error](https://github.com/mastodon/mastodon/assets/66587281/f007b245-b838-4db6-ba2b-68a927a54e3c)

**Comment by pinkgator** [comment]
Reinstalled everything with YunoHost and increased the RAM from 4GB to 8 and it works. Having different issues now that I'll open a seperate issue for if I can't figure them out.
