### ISSUE TITLE
CSP not working if media-cdn does a redirect to a diferent host

### ISSUE THREAD

**Issue by lifeofguenter** [mastodon/mastodon#26122]
### Steps to reproduce the problem

Unfortunately with jortage, it will do a redirect,

from: https://pool.jortage.com/convocasa/accounts/headers/109/355/486/308/409/408/original/ca7b0873361667c5.jpeg

to: https://blob.jortage.com/blobs/b/363/b3634791bb4b2f5949feb750af68e7b4b834b45bbc1e1aab5c0a6adcebbab9c2427be16be6bd81230d0ed94c41f7aafa0d913c4d64be13ba59852511bfd1aa58

glitch supports something like this:

```
EXTRA_DATA_HOSTS=https://blob.jortage.com
```

I do not know when this change was introduced but it unfortunately breaks all my images.

### Expected behaviour

CSP policy should allow redirect

### Actual behaviour

CSP policy blocks all embeded images

### Mastodon instance

convo.casa

### Mastodon version

v4.1.5

### Browser name and version

Firefox 102.13.0esr

### Operating system

Debian Bookworm

**Comment by lifeofguenter** [comment]
Closing this. I do not think redirects to a different host are currently supported by browsers at all - when using csp.

**Comment by selectric401** [comment]
I would argue that it has been supported in the past, as this exact setup has worked in the past. Unfortunately, something changed for my instance as of 4.3.0 which stopped this from working as well. I'm investigating further to open a new issue if necessary, but a regression has definitely been introduced at some point here.
