### ISSUE TITLE
'Reblogs' list only shows most recent 40-item page

### ISSUE THREAD

**Issue by aschrijver** [mastodon/mastodon#26121]
### Steps to reproduce the problem

1. [This toot](https://social.coop/@smallcircles/110755972839994395) is now boosted 206 times
2. Whenever clicking on boost icon below the toot to `/reblogs` only last 40 items are shown.
3. And there's no UI chrome to show more than the 40-item page.
...

### Expected behaviour

Either the full list of 'boosters' is shown, or UI to navigate between pages.

### Actual behaviour

Only the most recent 40 accounts are shown that boosted the toot

### Detailed description

Just extra FYI. Helge in [fediverse devs](https://matrix.to/#/!uHqAjmOtrLtidOiczC:matrix.org/$i4Us6bxM1ucWrWJpNBvxMpWx50CIqWbvUv20_xxhm-s?via=matrix.org&via=mozilla.org&via=matrix.bottomservices.club) chat made aware that the API call is paged:

> https://social.coop/api/v1/statuses/110755972839994395/reblogged_by
> Then if you look at the headers you see
> Link: https://social.coop/api/v1/statuses/110755972839994395/reblogged_by?max_id=110757548633191096; rel="next", https://social.coop/api/v1/statuses/110755972839994395/reblogged_by?since_id=110758036549519882; rel="prev"
> I think you need to select next to get the next 40 entries.
> Then if you do it 4 times, you get everybody who reblogged.

### Mastodon instance

social.coop

### Mastodon version

v4.1.4

### Browser name and version

Firefox 115.0

### Operating system

Ubuntu 23.04

**Comment by timothyjrogers** [comment]
I hope to submit a PR addressing this bug, but I'm very new to the Mastodon code base so I'll leave my findings here in case that takes overly long or I'm just way off base.

The hard cut at 40 seems to come from `DEFAULT_ACCOUNTS_LIMIT` as defined in the [base_controller](https://github.com/mastodon/mastodon/blob/bb23116e8d17b0fa7564a0f713c48753cfba7023/app/controllers/api/base_controller.rb#L5), as referenced in `paginated_statuses` in the [reblogged_by_accounts_controller](https://github.com/mastodon/mastodon/blob/bb23116e8d17b0fa7564a0f713c48753cfba7023/app/controllers/api/v1/statuses/reblogged_by_accounts_controller.rb#L30) that provides the list of accounts that have reblogged a post.

The `rebloggged_by_accounts_controller` does seem to return the expected pagination headers as described in the issue, however as far as I can find the frontend never uses them. See the path from [reblogs/index.jsx](https://github.com/mastodon/mastodon/blob/bb23116e8d17b0fa7564a0f713c48753cfba7023/app/javascript/mastodon/features/reblogs/index.jsx#L44-L48) to [interactions.js](https://github.com/mastodon/mastodon/blob/bb23116e8d17b0fa7564a0f713c48753cfba7023/app/javascript/mastodon/actions/interactions.js#L271-L282) where the `accountIds` property gets updated. From what I can tell the frontend passes in the next ID for the pagination, but the function that builds the list doesn't actually respect that ID and only ever calls `/api/v1/statuses/${id}/reblogged_by` without parameters, thus only ever returning that default 40.

**Comment by timothyjrogers** [comment]
I have a PR open addressing this now and I've tested it in a local instance with greater than 40 reblogs on a toot; additional rebloggers are now fetched from the paginated API similar to other paginated views.

I do notice that the "who favorited the toot" has this same behavior, so if this was confirmed as a bug that likely is to. I'll see if there is an open issue regarding that and if not I'll log one, rather than muddying this issue.
