### ISSUE TITLE
Allow 𝕏 (U+1D54F) as an alternative character for signaling hashtags

### ISSUE THREAD

**Issue by mcepl** [mastodon/mastodon#26140]
### Pitch

The growing popularity of the character X made even the owner of the well established brand throw away its good will and renaming his business to the plain X.

Mastodon could use a little bit of this popularity for itself.

### Motivation

Every user and administrator of servers federated in the Mastodon network would benefit from the increased popularity of the network.

**Comment by Gargron** [comment]
I don't follow.
