### ISSUE TITLE
Opening an invite link when already logged in results in an error

### ISSUE THREAD

**Issue by emilweth** [mastodon/mastodon#26142]
### Steps to reproduce the problem

1. Be logged in on your mastodon server
2. Click an invite link for the same server

### Expected behaviour

A redirection to the invite link owner profile?

### Actual behaviour

` Missing required parameter: client_id.`

### Detailed description

![image](https://github.com/mastodon/mastodon/assets/7402764/8367b584-31fa-492a-a115-cd39d6161c8a)

### Mastodon instance

rivals.space

### Mastodon version

v4.1.5+nightly-2023-07-24

### Browser name and version

Firefox 113.0.2 (64-bit)

### Operating system

I use arch btw

**Comment by ClearlyClaire** [comment]
I'm unable to reproduce it. Is that something you can reproduce reliably? Is there perhaps a specific sequence of action leading to this?

Do you have any local change?

**Comment by emilweth** [comment]
Not at all, i'm running the latest nightly completly vanilla

Some details : 

Clicking on `https://rivals.space/invite/vYgN4CGz` (from twitter e.g.) or directly typing it in the browser gives a 302 redirect to the oauth page
```
HTTP/2 302 Found
age: 0
cache-control: no-cache
content-security-policy: base-uri 'none'; default-src 'none'; frame-ancestors 'none'; font-src 'self' https://statics.rivals.space; img-src 'self' https: data: blob: https://statics.rivals.space; style-src 'self' https://statics.rivals.space 'nonce-IbxaWGRhthlraKM4syKKPw=='; media-src 'self' https: data: https://statics.rivals.space; frame-src 'self' https:; manifest-src 'self' https://statics.rivals.space; form-action 'self'; child-src 'self' blob: https://statics.rivals.space; worker-src 'self' blob: https://statics.rivals.space; connect-src 'self' data: blob: https://statics.rivals.space https://cdn.rivals.space wss://rivals.space; script-src 'self' https://statics.rivals.space 'wasm-unsafe-eval'
content-type: text/html; charset=utf-8
date: Mon, 24 Jul 2023 12:55:37 GMT
location: https://rivals.space/oauth/authorize
referrer-policy: same-origin
server: Mastodon
set-cookie: _session_id=xxxxx; path=/; expires=Wed, 24 Jul 2024 12:55:37 GMT; HttpOnly; SameSite=Lax; secure
set-cookie: _mastodon_session=xxxxxxxxxxxxx; path=/; HttpOnly; SameSite=Lax; secure
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-cache: MISS
x-content-type-options: nosniff
x-frame-options: DENY
x-request-id: 92b3fb7d-01c5-4bab-ba61-0f66fb79a938
x-runtime: 0.013395
x-xss-protection: 0
content-length: 102
X-Firefox-Spdy: h2
```

**Comment by emilweth** [comment]
Closing since it was a one-time issue
