### ISSUE TITLE
Mastodon should have docker setup for development env

### ISSUE THREAD

**Issue by varun-s22** [mastodon/mastodon#26156]
### Pitch

As the title suggests, Mastodon, should have a docker setup for local development process.

### Motivation

It would help new developers take on tasks, without having to install libraries on their local device.

**Comment by varun-s22** [comment]
hey @andypiper @Gargron and others.. any thoughts on this?

**Comment by andypiper** [comment]
It could be a useful idea, but at the moment we don't have a lot of time to spend on this particular concept, so if anyone wants to contribute something I'd be happy to test it out.

**Comment by andypiper** [comment]
Another possibility might be use of Vagrant. Adding here for future reference.

**Comment by varun-s22** [comment]
sure thanks @andypiper.. i'll look into it and start with the setup

**Comment by ChaelCodes** [comment]
A dev environment for Docker is supported in [.devcontainer](https://github.com/mastodon/mastodon/tree/main/.devcontainer). Instructions for using Docker were recently added to the [README.](https://github.com/mastodon/mastodon/blob/main/README.md#docker)

I'm currently running into issues setting it up, but it does exist.

**Comment by vmstan** [comment]
Closed as mostly duplicative of #16747 but also devcontainers are available.
