### ISSUE TITLE
Links without an image still embed with space for an image, taking up extra space on the timeline for no reason

### ISSUE THREAD

**Issue by ianh** [mastodon/mastodon#26161]
### Steps to reproduce the problem

Post something with a link without an associated image, e.g. http://icculus.org/fatelf/ in https://mastodon.social/@dougall/110774073509557855.

### Expected behaviour

The link either doesn't get an embed at all or gets a small embed with no space for an image.

### Actual behaviour

The link gets a large embed with space left for a photo-sized image.

### Mastodon instance

mastodon.social

### Mastodon version

v4.1.5+nightly-2023-07-25

### Browser name and version

Safari 16.2 (17614.3.7.1.7, 17614)

### Operating system

macOS 12.6.2 (21G320)

**Comment by ianh** [comment]
This has been substantially improved with #26250, but I'll leave this open in case you want to track removing the preview image entirely for pages that don't have one.

**Comment by vmstan** [comment]
Closed as fixed.
