### ISSUE TITLE
debbugs link card links to https://bugs.debian.org/cgi-bin/<a href="bugreport.cgi?bug=1034000">1034000</a>

### ISSUE THREAD

**Issue by nabijaczleweli** [mastodon/mastodon#26169]
### Steps to reproduce the problem

1. post https://bugs.debian.org/1034000

### Expected behaviour

normal embed

### Actual behaviour

it does embed but the link is bogus

### Detailed description

![image](https://github.com/mastodon/mastodon/assets/6709544/63f26b85-5031-4950-884c-c1c359bd04dc)

### Mastodon instance

101010.pl

### Mastodon version

v4.1.5

### Browser name and version

firefox deved 87.0b9 (64-bit)

### Operating system

windows 10

### Technical details

See it live at: https://101010.pl/@nabijaczleweli/110775414329587819
Twitter (used to at least) embed these sensibly. It's entirely possible that it's debbugs replying weird, as well.

**Comment by nabijaczleweli** [comment]
hm. is this good. wat da hel.
```
$ curl -L 'https://bugs.debian.org/1034000' | grep 'link rel=.*canonical'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   307  100   307    0     0    604      0 --:--:-- --:--:-- --:--:--   604
100 77888    0 77888    0     0  23799      0 --:--:--  0:00:03 --:--:-- 44154
<link rel="canonical" href="&lt;a href=&quot;bugreport.cgi?bug=1034000&quot;&gt;1034000&lt;/a&gt;">
```

**Comment by Gargron** [comment]
This is an error on the website's side.

**Comment by nabijaczleweli** [comment]
looks like it's not good and link rel=canonical [should just have an url](//developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#canonical), yeah. superseded by https://bugs.debian.org/1042014
