### ISSUE TITLE
All toots I post, there's a toast notification saying "Příspěvek zveřejněn", which google tells me is Czech?  I do not speak Czech, and have my language settings on British English.

### ISSUE THREAD

**Issue by Pxtl** [mastodon/mastodon#26167]
### Steps to reproduce the problem

1. Use language English (British)
2. Toot on Mastodon.Social
3. See toast notification "Příspěvek zveřejněn."

### Expected behaviour

Toast notification "Post published"

### Actual behaviour

Toast notification "Příspěvek zveřejněn"

### Detailed description

![image](https://github.com/mastodon/mastodon/assets/5386926/3dc48e92-e6f9-4623-b224-2e9b7ff2f598)

confirmed that using default English does *not* show this error.  I'm Canadian but will settle for British spelling because I'm a snot.

### Mastodon instance

mastodon.social

### Mastodon version

v4.1.5+nightly-2023-07-25

### Browser name and version

FireFox 115.0.2 (64-bit)

### Operating system

Windows 10.

### Technical details

Firefox inspector console screenshot:

![image](https://github.com/mastodon/mastodon/assets/5386926/60992f25-465a-41d4-88a5-e6a06424b302)

**Comment by renchap** [comment]
This was caused by a user adding translations to the wrong language on Crowdin: https://crowdin.com/project/mastodon/activity-stream?lang=99&translation_id=15467

Those translations have been reverted. They will be pulled into Github soon (this PR: https://github.com/mastodon/mastodon/pull/26072)

**Comment by Pxtl** [comment]
Great!  I'm curious though @renchap, does MastodonUI's resources framework not support just failing over to vanilla "en" where "en-GB" is unavailable? It feels like cases where there's no need to distinguish between English dialects, it would make sense to skip over the key altogether.  But of course, I've no experience with Crowdin which may make "just do all the keys" the optimal strategy for organizational purposes.

**Comment by renchap** [comment]
Mastodon uses translations keys, like `compose.published.body`.

Crowdin generated a JSON file for each language, with those keys and the translations as values. If there is no translation for this language, the base language (english) is used in the file.

It allows to only load 1 translation file (the one for your current locale)
