### ISSUE TITLE
New web UI poll selection is bad UX

### ISSUE THREAD

**Issue by ashemedai** [mastodon/mastodon#26160]
### Steps to reproduce the problem

1. Select an option on a poll in the advanced web interface with nightly
2.
3.
...

### Expected behaviour

Unambiguous selection visible between non-selected options

### Actual behaviour

The selected option is barely distinguishable from the non-selected option.

### Detailed description

The advanced web UI currently on mastodon.social has a UI styling for polls' radio buttons that is:

- different from the single column standard view
- barely distinguishable from the non-selected options

This leads to a bad UI and subsequently UX. You want to have the selected option.

Mastodon nightly (both standard and advanced view):
![image](https://github.com/mastodon/mastodon/assets/610865/c369d738-d852-44c3-89df-1ce4f8b2660c)
![image](https://github.com/mastodon/mastodon/assets/610865/75c7343f-dac4-4de7-a0ea-53124a4996d4)

4.1.5's UI:
![image](https://github.com/mastodon/mastodon/assets/610865/35a716b8-c5ee-4e62-9bae-0e2e72e19f77)
![image](https://github.com/mastodon/mastodon/assets/610865/79c26679-d551-4188-b874-2a74048c11e5)

### Mastodon instance

mastodon.social

### Mastodon version

v4.1.5+nightly-2023-07-25

### Browser name and version

Firefox 105.0.3

### Operating system

Windows 10

**Comment by ClearlyClaire** [comment]
> different from the single column standard view

No, the styling has changed in both single-column and advanced column.

That was done in #26139, and I agree that while it did improve color consistency, it completely removed the `active` style.

**Comment by ashemedai** [comment]
> > different from the single column standard view
> 
> No, the styling has changed in both single-column and advanced column.

Yeah, looks like I left that in by accident from my editing and testing, mea culpa for the confusion.

**Comment by teeerevor** [comment]
@ashemedai @ClearlyClaire Sorry, I updated the poll creation form, but messed up the poll selection styles. I'll fix now.

**Comment by ashemedai** [comment]
@teeerevor It happens. Thanks for fixing!
