### ISSUE TITLE
OpenGraph previews allow for unreasonably long titles

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#26176]
### Steps to reproduce the problem

I [do not like the new Opengraph preview formatting](https://mastodon.social/@mcc/110776317425727468)¹, with the very large title and the lack of a distinction between user content and OpenGraph-embedded content. I think it was better before. However this aside, the new preview formatting has a bug. There is no limit on the length of the title, and the title is included in its entirety in very large text regardless of its length.

As a test, I tried creating a small² page whose opengraph title preview is the complete text of the Communist Manifesto³. I then posted it in a post on mastodon.social. Mastodon dutifully included *the entire title* in its page rendering, including in panes such as Home, in large text:

![image](https://github.com/mastodon/mastodon/assets/277318/869c723a-707d-4e29-9a37-a56f81f8d8a2)

The post in which I do this is [here](https://mastodon.social/@mcc_test_tusky/110776523342424829). In order to see it, you will need to follow mastodon user [mcc_test_tusky](https://mastodon.social/@mcc_test_tusky) (follow requests are currently not required). I *could* repost the test post with unrestricted permissions, but that would make it possible to boost the status, and I don't think you want this. For similar reasons, I am not going to post the link to the opengraph page in this issue, although you can get it from the status.

### Expected behaviour

Titles should truncate at some reasonable length (probably before being inserted into the database, to prevent DOSing). In addition, maybe the title should not be so large to start with. In addition, maybe it should be possible for a user to dismiss or collapse a post preview (as is already possible with image attachments).

### Actual behaviour

Titles can be arbitrarily long, so long I was not able to find the upper limit, which offers incredible opportunities for griefers. If the Communist Manifesto test post above is on your feed, your feed becomes briefly more or less unusable. Imagine if I had posted that post without restrictions and many people had boosted it, so that the post potentially appears in your timeline multiple times. Mastodon.social would be unusable for quite a while.

### Detailed description

-

### Mastodon instance

mastodon.social

### Mastodon version

 v4.1.5+nightly-2023-07-25

### Browser name and version

Chrome 114.0.5735.248 64-bit

### Operating system

Windows 10

### Technical details

I do not know whether this problem affects older versions of Mastodon before the Very Large preview formatting was introduced, and I don't have a way to test.

<small>¹ I explain my reasoning in the link there, if it matters.  
² Other, of course, than the inclusion of the complete text of the Communist Manifesto.  
³ Actually not the complete text but only the first 900 lines. Section 3 and following have more complex formatting and therefore were awkward to include in the title preview. This is still very long however.</small>

**Comment by mcclure** [comment]
Confirmed, this issue does not affect older versions of mastosoc: I spoke with a user on chaos.social, which is running v4.1.5, and this is what the preview looked like for him.

![image](https://github.com/mastodon/mastodon/assets/277318/8c1f80cb-41b5-4001-9a29-e50b3f12b40a)

**Comment by mcclure** [comment]
Follow-up, although Graham Suberland did *not* have page display broken by the very long opengraph title on vanilla 4.1.5, he also mentioned that the complete title text *was* included in his browser's HTML. So although this is not a serious bug on vanilla 4.1.5, there is still *probably* something worth fixing as a user could still potentially degrade another's user experience at low cost to themselves by sending many messages with multi-megabyte opengraph titles.

https://gist.github.com/gsuberland/337c957c6eb53610c62db3556a6f1c7e

**Comment by renchap** [comment]
Thanks for the report, it is indeed not intended.

Those new previews still need some tweaks and they should land in the coming days. We will truncate the content so this does not happen :)

I personally agree with the fact that preview-related content should be visually separated and we are having discussions about it.

**Comment by renchap** [comment]
Should be fixed by #26250

**Comment by ThisIsMissEm** [comment]
@renchap does this perhaps require changes to the rails code? E.g., such that the previews render in a similar fashion across all clients.

**Comment by mcclure** [comment]
This is marked as completed, but with the change is the web code truncating the *stored*/transmitted-to-user title length, or is it only truncating the displayed size? I'd still wonder about the DOS potential of forcing a mastodon instance to store and broadcast very long strings, even if those strings are hidden from being displayed.
