### ISSUE TITLE
Favicon changes when link previews load in web interface

### ISSUE THREAD

**Issue by aadilayub** [mastodon/mastodon#26186]
### Steps to reproduce the problem

1. Open an instance running mainline mastodon (e.g. mastodon.online)
2. Scroll through the public timeline (or any timeline) with external links in it

### Expected behaviour

The favicon of the site stays as it is

### Actual behaviour

The favicon of the site changes

### Detailed description

I've seen this happen on several mastodon instances. When scrolling through the timeline, the favicon changes to the icon of the last link that had a preview card in the timeline.

[Screencast from 2023-07-26 09-06-00.webm](https://github.com/mastodon/mastodon/assets/31581044/2036a6b8-8274-4717-bf9f-a11fc859a710)

### Mastodon instance

mastodon.online

### Mastodon version

v4.1.5+nightly-2023-07-25

### Browser name and version

Firefox 115.0.2

### Operating system

Fedora Linux 38

**Comment by ClearlyClaire** [comment]
In your screencast, the preview cards seem to get dynamically replaced with something that is not built into Mastodon. Are you perhaps using some browser extension?

**Comment by aadilayub** [comment]
You're right! This was being done by [Graze for Mastodon](https://addons.mozilla.org/en-US/firefox/addon/graze). I didn't even know it was doing that. Thanks, closing.
