### ISSUE TITLE
Creation of a custom role with priority below `-2,147,483,648` yields an `out of range` error.

### ISSUE THREAD

**Issue by liamstojanovic** [mastodon/mastodon#26256]
# Summary
When creating a custom role from the admin _Add role_ page (`/admin/roles/new`), the _Priority_ input field accepts integer values < `-2,147,483,648` which yields a rails `out of range` error upon submitting the form.

# Steps
- Navigate to the _Add role_ page
- Enter an arbitrary string for the _Name_ field
- Enter `-2,147,483,649` for the _Priority_ field
- Click _Save Changes_ to submit the form
<img width="963" alt="outofrange" src="https://github.com/mastodon/mastodon/assets/14226058/d53e2421-4dd9-4f06-b842-e6b46d91cdd6">

# Additional information
Priority value input validation prohibits an entry above `999` (presumably so that no custom role supersedes the Owner role), but there is no input validation for negative integers.

### Expected behaviour

The Priority input field for the Add role form should forbid entering a negative value that exceeds the bound of a 4-byte signed integer

### Actual behaviour

A negative value can be entered into the priority input field, yielding an out of range error upon form submission 

### Mastodon instance

dev environment

### Mastodon version

v4.1.5

### Browser name and version

Brave 1.56.11

### Operating system

macOS 13.4.1 (c)

**Comment by mjankowski** [comment]
It does seem like we could catch this with a validation instead of an error ... but we can't add "not negative", because we have some special IDs used for the everyone/nobody roles which are negative. We could pick some other negative value that's lower than our needs but higher than the integer limit.
