### ISSUE TITLE
'Import domain blocks' case-sensitive on booleans

### ISSUE THREAD

**Issue by mejofi** [mastodon/mastodon#26253]
### Steps to reproduce the problem

When importing a blocklist with booleans defined as 'False', the import routine in the web interface fails to recognise these as properly set to 'false', resulting in an assumption that they should be 'true' instead.

### Expected behaviour

Booleans should be recognised regardless of case used

### Actual behaviour

Only lowercase imports properly, capitalised fails

### Detailed description

When importing a blocklist file with the following contents;
```
#domain,#severity,#reject_media,#reject_reports,#public_comment,#obfuscate
domain.example,silence,False,False,,False
```
Mastodon will assume it needs to limit the domain, and reject both media and reports, even though both are set to 'False'. If a lowercase version is used instead, like;
```
#domain,#severity,#reject_media,#reject_reports,#public_comment,#obfuscate
domain.example,silence,false,false,,false
```
it imports as expected, only limiting the domain, and not rejecting either media or reports. This suggests that there is some form of case sensitivity at play for the booleans in these import files, even though 'False' is a valid expression of that boolean.

If this is not intended, it should be considered a bug.

### Mastodon instance

ngmx.com

### Mastodon version

v4.1.5

### Browser name and version

Firefox 115.0.2 (64-bit)

### Operating system

macOS 13.5

### Technical details

All details should be in the detailed description field, let me know if you need anything else beyond that. Also, if this is a known issue, please flag it as such. I searched existing tickets and couldn't find anything that covered this particular problem, hence the new ticket.

**Comment by ThisIsMissEm** [comment]
Have finally opened a PR to fix this.
