### ISSUE TITLE
mastodon-embed class missing on some embeds

### ISSUE THREAD

**Issue by stefanbohacek** [mastodon/mastodon#26265]
### Steps to reproduce the problem

1. Open a post on mastodon.social with an account on this instance.
2. Copy the embed code.
3. Observe the "mastodon-embed" class on the iframe.
4. Open the same post from another instance.
5. Copy the embed code.
6. The "mastodon-embed" class is no longer present on the iframe.
7. Repeat the above steps between any other two instances, the result will always be the same. Embedding a post on the same instance will result in an iframe code that contains the "mastodon-embed" class, but when switching between instances, the class will be missing.

### Expected behaviour

When embedding a Mastodon post, the iframe code should always contain the "mastodon-embed" class.

### Actual behaviour

The "mastodon-embed" class is missing when embedding a post from another Mastodon instance.

### Detailed description

Others have been able to replicate this behavior between other Mastodon instances:

- https://masto.ai/@cybeardjm/110804495822833108
- https://bonn.social/@Johannes/110803406551772847

### Mastodon instance

Any two instances

### Mastodon version

v4.x.x

### Browser name and version

Any

### Operating system

Any

### Technical details

Correct embed code:

```
<iframe
  src="https://mastodon.social/@Mastodon/110640658973976934/embed"
  class="mastodon-embed"
  style="max-width: 100%; border: 0"
  width="400"
  allowfullscreen="allowfullscreen"
></iframe>
<script src="https://mastodon.social/embed.js" async="async"></script>
```

Incorrect embed code of the same post when embedded from another instance.

```
<iframe
  src="https://mastodon.social/@Mastodon/110640658973976934/embed"
  width="400"
  allowfullscreen="allowfullscreen"
  sandbox="allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox allow-forms"
></iframe>
```

**Comment by wolfgang101** [comment]
I think the embed code changed somewhere along the way.

Looking at embed.js (e.g. https://ohai.social/ ) there is a note saying that `iframe.mastodon-embed` are legacy embed iframes and the code now is looking for an `iframe` with the `data-embed-url` attribute.

PS: The reason I found this post was because I'm looking for the sandbox attribute which currently does not include the "allow-popups" directive, but shows in your sample code. Browsers block any links from being opened by directly clicking on the contents within the IFrame.

**Comment by stefanbohacek** [comment]
@wolfgang101 There is also another change coming in 4.3 where embeds are no longer `iframe`s, but `blockquote`s instead.

- https://github.com/mastodon/mastodon/pull/31766
- https://stefanbohacek.online/@stefan/113132795285871413

**Comment by wolfgang101** [comment]
Excellent news. So we close this open issue as wont-fix?

**Comment by stefanbohacek** [comment]
Yes, I suppose we can!
