### ISSUE TITLE
Sort toots in search results chronologically

### ISSUE THREAD

**Issue by jtmtzrwj** [mastodon/mastodon#26276]
### Pitch

Hi. Would it be possible to have the results sorted chronologically for the "posts" tab. Is there an operator similar to include/exclude to be able to see the results in order.

### Motivation

This would benefit users (like me) who would like to see filtered version of their timeline. Example: I would like to only see my toots about what "I" am watching or reading etc sorted chronologically. This would not work using hashtags as it would also show other people's post using the same hashtag.

**Comment by Gargron** [comment]
Fixed in #26344
