### ISSUE TITLE
Streaming server cannot handle DATABASE_URL without password and separate DB_PASS 

### ISSUE THREAD

**Issue by kaikoga** [mastodon/mastodon#26288]
### Steps to reproduce the problem

Set `DATABASE_URL` without DB password, and provide DB password through `DB_PASS`.

### Expected behaviour

Web and streaming servers could connect to database.

### Actual behaviour

Streaming server could not connect to database.

### Detailed description

Let the values of ENV vars be
```
DATABASE_URL=postgresql://user@dbhost.example.com:5432/mastodon_production
DB_PASS=mypassword
```

and `Rails.application.config.database_configuration[Rails.env]` in rails console looks like
```
   "database"=>"mastodon_production",
   "username"=>"user",
   "password"=>"mypassword",
   "host"=>"dbhost.example.com",
   "port"=>5432,
```

while `pgConfigFromEnv(process.env)` in Node is
```
> pgConfigFromEnv(process.env)
{
  user: 'user',
  password: '',
  port: '5432',
  host: 'dbhost.example.com',
  database: 'mastodon_production',
  max: 10,
  connectionTimeoutMillis: 15000,
  application_name: ''
}
```

I have tried this setup because this is a k8s deployment and `DATABASE_URL` is provided through configmap while `DB_PASS` is from secret.

### Mastodon instance

t.kaikoga.net

### Mastodon version

v4.1.5+nightly-2023-07-30

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
- Node.js version: v16.20.1

**Comment by ThisIsMissEm** [comment]
I've done up a small fix in #26295, however, it is worth noting that the code for handling database configuration between ruby and node.js isn't entirely consistent (it's a bit of a mess we need to refactor and fix at some point)
