### ISSUE TITLE
"Execution expired" TCP errors for S3 requests in sidekiq

### ISSUE THREAD

**Issue by flaki** [mastodon/mastodon#26296]
### Steps to reproduce the problem

Since upgrading to 4.x at [flaki.social](https://flaki.social) I have been seeing hundreds of these in the sidekiq "dead" tab:

```
Seahorse::Client::NetworkingError: Failed to open TCP connection to s3.flak.is:443 (execution expired)
```

These are `pull`-s for `LinkCrawlWorker`.

`s3.flak.is` is a self-hosted Minio server that is used as object storage for my Mastodon instance, but these errors only started showing up since 4.x (I have upgraded from 3.x in one step so can't say which minor version caused them to start appear, currently running 4.1.5), so I don't think Minio is the culprit.

Simultaneously some remote media is missing from the UI in the web/mobile client and it takes a click to view, I'm assuming those are due to dead fetches that are retried on-demand? This is just a hypothesis though.

I'm happy to do some more digging if I get some pointers, this seems to be maybe some sort of timeout issue, has anything changed recently regarding these timeouts?

### Expected behaviour

Dead processes such as these don't appear

### Actual behaviour

500+ dead entries in a week on a small personal server

### Mastodon instance

flaki.social

### Mastodon version

v4.1.5

### Technical details

Running a customized docker image based on the v4.1.5 image.

`ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]`

`node v16.18.1`

**Comment by flaki** [comment]
For people experiencing the same issue, I believe I have found the culprit, see #12459 for details.

The TL;DR seems that the default S3 timeouts are set to 5 seconds, this can be too low for certain configurations and you can try upping `S3_OPEN_TIMEOUT` and/or `S3_READ_TIMEOUT` respectively.

I have stumbled upon these config entries accidentally while reading the [config](https://docs.joinmastodon.org/admin/config/#s3), as I installed from an earlier version (where these were not available yet).

It seems that increasing the default timeout has fixed the issue, so I am going to close this for now.

**Comment by eallion** [comment]
Same
