### ISSUE TITLE
Upgraded to 4.1.6 but UI still shows 4.1.5

### ISSUE THREAD

**Issue by solick** [mastodon/mastodon#26308]
### Steps to reproduce the problem

1. have a 4.1.5 version running (native no docker)
2. upgrade to 4.1.6
3. the UI unter getting started / Preferences still shows v4.1.5 as version

and yes i did a refresh of the browser even opened in a new browser

### Expected behaviour

Shows correct version

### Actual behaviour

shoes 4.1.5

### Mastodon instance

wireless-iot.social

### Mastodon version

v4.1.6

### Browser name and version

Chrome, Safari

### Operating system

Debian on server, MacOS in Client

**Comment by renchap** [comment]
Did you restart the web (Puma) and worker processes after the upgrade?

**Comment by solick** [comment]
i performed

sudo systemctl restart mastodon-web mastodon-sidekiq mastodon-streaming

**Comment by renchap** [comment]
You probably did not update correctly your files.

Are you using git? What does `git status` looks like?

**Comment by solick** [comment]
indeed you are right, the version was still at 4.1.5 although I fetched and checkout the 4.1.6 (I checked in the history).

Now as I did the update process again the server is now on the correct version.
