### ISSUE TITLE
Web UI: Advanced mode: Column for user should include user's boosts

### ISSUE THREAD

**Issue by keithdtyler** [mastodon/mastodon#26332]
### Pitch

I'm dabbling with using Mastodon to follow Lemmy groups (federation innit?) and it works, but the "noise level" of groups is larger than most people toot, which means my home feed gets overpopulated with the Lemmy group content.

I tried putting the group "user" in a dedicated advanced mode column. But when you do that, it doesn't seem to include boosts -- and the Lemmy-Mastodon integration relies on boosts to deliver group posts and comments.

### Motivation

To improve federated integration for users between Lemmy and Mastodon

**Comment by ClearlyClaire** [comment]
Hi! Which version of Mastodon are you using, and what kind of column have you put the group in?

**Comment by JorgeStolfi** [comment]
That column should have three separate radio button selectors, "Posts", "Boosts", "Replies", and the person could click any 1, 2, or 3 of them.  

Maybe also add a fourth button, "Favs".

**Comment by keithdtyler** [comment]
Retracting.
