### ISSUE TITLE
Sort "people" search results so that people with more of the search terms in their name are closer to the top

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#26347]
### Pitch

If a person's display name or username contains more of the words typed into the search box, they should appear at the top of the search results - above people whose name contains only one of the words typed into the search box.

### Motivation

Today I searched for a particular person by first and last name in the search box, like so:

<img width="894" alt="Screenshot 2023-08-05 at 00 25 12" src="https://github.com/mastodon/mastodon/assets/6607512/8eb020f5-177a-4c6f-9f1b-843b15244147">

The person I was looking for was the first result with both words in their name, and they were in position 16, way below 15 people who had only one of the words in their name. This was them:

<img width="307" alt="Screenshot 2023-08-05 at 00 25 28" src="https://github.com/mastodon/mastodon/assets/6607512/0ad6768b-3789-4a20-ab28-f0408d2ecfd3">

This person should have been at the top. I shouldn't have had to click "show more" to find them.

**Comment by Gargron** [comment]
I can reproduce this on mastodon.social.

**Comment by Gargron** [comment]
I have the first clue. This person's name has `Dekker🇪🇺` instead of `Dekker`, so that's actually not matched at all, they're in the results for the `Martijn` match alone. We need to change the analyzers on the index to properly split out emoji.
