### ISSUE TITLE
Smaller left most column on advanced web interface

### ISSUE THREAD

**Issue by jasonycw** [mastodon/mastodon#26348]
### Pitch

The left most column for you to search and post should be able to be minimize.

### Motivation

Right now, it's consuming too much space on the left
<img alt="image" src="https://github.com/mastodon/mastodon/assets/4518597/fb8d0546-43a3-4138-b997-7c7364ddb29e">
Compare to Tweetdeck
<img alt="image" src="https://github.com/mastodon/mastodon/assets/4518597/f67b1b0c-0dfa-4adf-830b-5ed938364c99">

**Comment by Cassolotl** [comment]
Related: *Compose drawer could squish down and become sticky with a ⬅️ button #9868*
