### ISSUE TITLE
Importing Lists CVS results in one list per username instead of all users in one list

### ISSUE THREAD

**Issue by Cragsand** [mastodon/mastodon#26355]
### Steps to reproduce the problem

Reproduction:
1. Export lists with a single list in it with multiple usernames added to that list from https://mastodon.social/settings 
2. Import the CVS file using either merge or overwrite (both produce the same result)

Here is my example list I'm trying to import:
[lists.csv](https://github.com/mastodon/mastodon/files/12268065/lists.csv)

![Screenshot_20230805_214618_Sheets](https://github.com/mastodon/mastodon/assets/49168045/adad9f9c-1532-487b-9c54-419893019e36)
...

### Expected behaviour

The single list gets populated with all usernames

### Actual behaviour

One list is created for each entry, resulting in many empty lists

![Screenshot_20230805_212651_Firefox](https://github.com/mastodon/mastodon/assets/49168045/802868da-6773-4ee8-b27b-5165417f5f87)

### Detailed description

Exporting and importing lists does not work as expected. Instead every comma separated entry creates a new list with the same name. All of the lists are empty.

### Mastodon instance

mastodon.social

### Mastodon version

v4.1.5+nightly-2023-07-31

### Browser name and version

Firefox Android 115.2.1 (Build #2015962859), 046c284cb9+ GV: 115.0.2-20230710165010 AS: 115.0

### Operating system

Android 

### Technical details

EDIT:

Oops sorry for accidentally closing and reopening I did not mean to do that.

The issue could also be that exporting lists is not functioning, and the formatting in the CVS is wrong but I'm not sure how to check that.

I searched for example lists but could not find other examples.

**Comment by ClearlyClaire** [comment]
I believe I have identified the issue, but can you check whether these lists are all one account only, or if some have more than one?

**Comment by Cragsand** [comment]
> I believe I have identified the issue, but can you check whether these lists are all one account only, or if some have more than one?

I tried re-importing again and it added all 40 accounts to one of the lists but also creates 39 empty lists with the same name.

This is the list I'm importing with 40 accounts but only one list. https://github.com/mastodon/mastodon/files/12268065/lists.csv 

If it helps I imported the list successfully with no issues on https://infosec.exchange which runs v4.1.4+glitch version of Mastodon.

Thank you for the update Claire!

**Comment by Cragsand** [comment]
Yes I'm sure, I don't know why it populated the first list the second time I tried it.

I deleted my list and re-imported to reproduce it again. This time I recorded it in a video here:

[https://www.youtube.com/watch?v=kR1rjQ4puR4](https://www.youtube.com/watch?v=kR1rjQ4puR4)

**Comment by ClearlyClaire** [comment]
The lists not having contents is expected, as those are not backfilled. Can you check that all lists have accounts in them?

**Comment by ClearlyClaire** [comment]
When you do “Edit list” they're all empty? That is very weird and I don't have an explanation for this, especially since the import system did not list any failure…

**Comment by Cragsand** [comment]
> When you do “Edit list” they're all empty? That is very weird and I don't have an explanation for this, especially since the import system did not list any failure…

Oh you are correct. My bad for not clicking the "Edit list" button! Sorry I did not realize that the posts doesn't populate older posts. The list is being populated, it is just making lots of duplicate lists.

**Comment by ClearlyClaire** [comment]
Thanks for the confirmation! So what happens is that a bunch of your imports were processed at the same time, and each checked if a list of the expected name existed, found that it was not the case, and created one.

What I did in #26372 instead is create the lists before queuing the import jobs, which means the lists will already exist when the import jobs run, and the issue will not arise. This isn't a perfect fix, though, but we're limited by the absence of uniqueness constraint on lists.
