### ISSUE TITLE
Some accounts not appearing in search that should be

### ISSUE THREAD

**Issue by cedewey** [mastodon/mastodon#26358]
### Steps to reproduce the problem

1. Follow @palantir@mastodon.social
2. Search "palantir"

### Expected behaviour

@palantir@mastodon.social should appear in the people list

### Actual behaviour

No results are shown

### Detailed description

This is happening with some other accounts I follow as well. I haven't detected a pattern yet.

### Mastodon instance

social.coop

### Mastodon version

v4.1.4

### Browser name and version

Firefox 115.0.3 

### Operating system

Pop!_OS 22.04 LTS

**Comment by cedewey** [comment]
![mastodon-search-broken](https://github.com/mastodon/mastodon/assets/1270531/a58e0a9e-4d64-49ba-9854-7b7aa900ab95)

**Comment by Gargron** [comment]
We can't help with this, please reach out to social.coop instead.
