### ISSUE TITLE
Unable to add a photo - rendering a 502

### ISSUE THREAD

**Issue by siemvaessen** [mastodon/mastodon#26350]
### Steps to reproduce the problem

1.Create Toot
2.Add image from desktop (jpg)
3. 502 appears
4. Unable to edit and add

Erroglog from console:

/api/v2/media:1     Failed to load resource: the server responded with a status of 502 ()
...

### Expected behaviour

The image should have been added to the post

### Actual behaviour

502

### Detailed description

See reproduction steps.

I then deleted the post, posted a new one and that went through.

### Technical details

XX

**Comment by Gargron** [comment]
We can't help with HTTP 502 Gateway Errors. This is a server-specific availability or configuration issue.

**Comment by siemvaessen** [comment]
Hi @Gargron - where can I then report devops issues for https://mastodon.social/ then as it appears on the https://mastodon.social/ server(s)?

**Comment by Gargron** [comment]
Please check status.mastodon.social for known issues. You can email support@mastodon.social to report an issue.
