### ISSUE TITLE
Can't recover account

### ISSUE THREAD

**Issue by dwalkerart** [mastodon/mastodon#26364]
### Steps to reproduce the problem

1. I am trying to recover my account for mastodon.social and mastodon.disabled but it won't work.
2. Tried the forget password for djcarmichael18@gmail.com and dwalkerprofessional@gmail.com but didn't work or wasn't what I had expected.
3.
...

### Expected behaviour

I wanted it to actually go to my first email since I believed to have signed up for Mastodon with that email first.

### Actual behaviour

Again, it didn't work for the first email and I double-checked to make sure it was the right email.

### Mastodon instance

mastodon.social/mastodon.disabled

**Comment by Gargron** [comment]
We can't help you here and you probably don't want your e-mail publicly exposed like this.
