### ISSUE TITLE
adding subdomain block fails if base domain block already in place and also silently removes base domain block

### ISSUE THREAD

**Issue by brookmiles** [mastodon/mastodon#26374]
### Steps to reproduce the problem

1. add a domain block for `test.example`
2. add a domain block for `subdomain.test.example`

### Expected behaviour

At least one of the domain blocks should have remained in place, probably the base domain.

### Actual behaviour

The base domain block was mysteriously removed, and the subdomain block does not appear to have been added either, although it is logged as being added in the audit log.

### Detailed description

At a minimum, the base domain probably should be left in place.

Ideally, an information warning or error message should be generated to inform the user of whatever actual actions were taken, such as indicating failure and instructing them to remove the base domain first.

Audit log should accurately reflect whatever actions were actually taken.

### Mastodon version

v4.1.5

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]
- Node.js version: v16.20.1

**Comment by jazmichaelking** [comment]
Confirmed recreated on 4.1.6 Ruby version 3.0.6p216

![image](https://github.com/mastodon/mastodon/assets/3419832/6c218413-d689-4f19-ae4c-58a783ffdce4)
![image](https://github.com/mastodon/mastodon/assets/3419832/cb544d88-4fc5-4a2b-8adb-8daf40b4d5eb)


example.com set to No limits imposed
test.example.com not present

**Comment by ClearlyClaire** [comment]
oof, I can indeed confirm a logic error with adding a domain block on a subdomain of something already blocked, but my understanding of it does not seem to align with the description you're making: what I'm observing is the existing (broader) block gets updated with the parameters of the subdomain block, **including its name**.
