### ISSUE TITLE
Implement /.well-known/openid-configuration

### ISSUE THREAD

**Issue by grahhnt** [mastodon/mastodon#26398]
### Pitch

Mastodon has oauth already, it would be convenient for developers to easily grab oauth/openid endpoints via a standard

/.well-known/openid-configuration spec: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata

### Motivation

Third-party developers would easily be able to grab configuration via the /.well-known/openid-configuration endpoint

**Comment by ThisIsMissEm** [comment]
The above comment makes this a duplicate ticket of #24099

**Comment by trwnh** [comment]
https://github.com/mastodon/mastodon/blob/33bd8eccd5ed3b9e87140103cf63cd7aa02c22e2/config/initializers/3_omniauth.rb#L73C1-L106 ???

**Comment by ThisIsMissEm** [comment]
> https://github.com/mastodon/mastodon/blob/33bd8eccd5ed3b9e87140103cf63cd7aa02c22e2/config/initializers/3_omniauth.rb#L73-L106
> 
> ???

That is for Mastodon (through Devise) to act as a client application to another OIDC server, not for Mastodon (through Doorkeeper) to act as an OIDC server.

**Comment by trwnh** [comment]
i guess closing as non-actionable until/unless mastodon becomes an oidc provider then
