### ISSUE TITLE
Click on live feed's header doesn't go up on deck mode

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon#26405]
### Steps to reproduce the problem

1. Open live feed on deck mode (Not pinned)
2. Click header "Live feed"
3.
...

### Expected behaviour

Scroll up to top

### Actual behaviour

Not scroll up to top

### Detailed description

![image](https://github.com/mastodon/mastodon/assets/5047683/a693a2e9-48ff-428f-a972-9c7d99356896)
Clicking red area is not working (Even the mouse cursor is changed into hand icon. which means clickable)
Clicking blue area is working but Unnecessarily `history.pushstate`

On single column layout. It works as intended

### Mastodon instance

qdon.space, mastodon.social

### Mastodon version

v4.1.5, v4.2.0+nightly-2023-08-09

### Browser name and version

Firefox 115.0.1

### Operating system

Ubuntu 22.04

**Comment by ClearlyClaire** [comment]
I can confirm the issue, and the issue also affects the “Explore” column in the same way.
