### ISSUE TITLE
In light of "Add new public status index" #26344, change post visibility of applicable users to "unlisted" during update

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#26412]
### Pitch

Soon there is an update coming that changes Mastodon so that all public posts with their accounts set to "discoverable" are searchable from instances with search enabled.

During this update, anyone with their accounts set to "discoverable" and their default post visibility set to "public" should have their post visibility automatically changed to "unlisted", and they should get the following pop-up:

> On [date] this server was updated to Mastodon version [version]. This update included a major change to search. Public posts from accounts set to "discoverable" will be searchable using plain text search terms. Any new public posts from "discoverable" accounts will now be irreversibly searchable across all up-to-date Mastodon servers.
>
> Your account is set to "discoverable" and your default post visibility was set to "public" at the time of the update, which means that any new posts were likely to be searchable. As Mastodon has an opt-in, informed consent ethos, your default post privacy has been changed to "unlisted". This can be changed in settings; click here to jump to the setting.

### Motivation

During the next update, which implements #26344, a bunch of people who have set their profiles to "discoverable" (on the understanding that only their profiles will become easy to find) and set their default post visibility to "public" (on the understanding that plaintext search has significant limitations) will suddenly be posting posts that are visible in searches to anyone with an instance with search enabled.

There is no way to change a post's visibility retroactively.

Mastodon's ethos and mission statement was once to offer a social network that prioritises and preserves users' privacy, though there's no mention of that on the Join Mastodon homepage now. In fact, there's no ethos/mission statement on that site at all. But the original goal, as I understand it, was to be better in terms of privacy. This warning pop-up would ensure that everyone on the instance knows what they're in for and isn't dropped into irreversible indexability.

See also #26408.

**Comment by Cassolotl** [comment]
@brendanjones That would work for me too.

**Comment by renchap** [comment]
Hi,

Thanks for sharing your concerns about search with us. The mentioned PR is not done yet and discussions are in progress on how the exact implementation will be, leaning towards having a specific flag for indexing posts into Mastodon's built-in search.

I am closing this issue, not to dismiss your point, but because discussions about this are happening in many places and the mentioned PR will have changes that should fix the issue you (and many other) are concerned about.
