### ISSUE TITLE
Pushing changes from git to crowdin is sometimes misconfigured

### ISSUE THREAD

**Issue by gunchleoc** [mastodon/mastodon#26443]
### Steps to reproduce the problem

Filter for strings translated by user Gargron in the Crowdin UI for languages that he doesn't speak.

### Expected behaviour

WHen the English source string changes, the translation becomes empty

### Actual behaviour

Translation is kept and does not match the English source anymore, e.g. whole sentences can go missing.

### Detailed description

When the English source string for an existing JSON key is changed, old translations are kept on Crowdin. This makes translations go out of sync with the English source.

This doesn't happen all the time, e.g. the recent change from "favourites" to "favorites" behaved correctly, but the `gd` translation of `compose_form.publish_form` was autotranslated to "Foillsich" =  "Publish" instead of "Post ùr" =  "New Post" https://crowdin.com/translate/mastodon/52/en-gd#15293

### Mastodon instance

N/A

### Mastodon version

9dff838

### Browser name and version

Firefox

### Operating system

Linux Mint

**Comment by gunchleoc** [comment]
Here's an example where a whole sentence is missing from the translation: https://crowdin.com/translate/mastodon/52/en-gd#15295

> These are news stories being shared the most on the social web today. Newer news stories posted by more different people are ranked higher.

> Seo na naidheachdan air a bhithear a’ bruidhinn an-dràsta fhèin air an fhrithealaiche seo is frithealaichean eile dhen lìonra sgaoilte.

**Comment by gunchleoc** [comment]
I'm now thinking this might have been some sort of manual push that @Gargron did by mistake, because now I am also seeing English-language strings as translations, e.g. this one: https://crowdin.com/translate/mastodon/52/en-gd#15315

**Comment by renchap** [comment]
For context, translations upload should be done automatically when a Pull Request is merged, using this Github Action: https://github.com/mastodon/mastodon/blob/main/.github/workflows/crowdin-upload.yml

You can see a log of those uploads here: https://github.com/mastodon/mastodon/actions/workflows/crowdin-upload.yml

Upload are done using a Crowdin API key belonging to @Gargron, this is why the uploads are with his name.

**Comment by ClearlyClaire** [comment]
Hi! I have no explanation for this. However, we have changed how we upload translatable strings in mid-July. Have you seen any issue since then?

**Comment by gunchleoc** [comment]
This seems to have been a one-time occurrence. I have created a discussion in Crowdin to let people know: https://crowdin.com/project/mastodon/discussions/317

Later pushes to Crowdin were fine, so unless you want to investigate more to prevent this from happening again, this issue can be closed.

**Comment by gunchleoc** [comment]
Did some more digging. Found this commit by @Gargron: https://github.com/mastodon/mastodon/commit/8bfbd19d2b8a5929288a89fb5ea3e7a34e3a64e3

This is a few hours after the occurrence, so I am assuming that he noticed the problem after it happened, fixed it, probably to cater to a change in the Crowdin config spec, and then didn't tell anybody about it.

I know he's a busy guy, but some communication here would have saved us the time we just spent dissecting the issue. Also, translators now have less time for fixing the strings before the upcoming release.

**Comment by ClearlyClaire** [comment]
I'm actually not sure, Mastodon is the *only* occurrence I can find of `skip_untranslated_strings: 1`, and the documentation at https://developer.crowdin.com/configuration-file/ has an example where it's `true`… not really sure what's going on there

**Comment by ClearlyClaire** [comment]
> I know he's a busy guy, but some communication here would have saved us the time we just spent dissecting the issue. Also, translators now have less time for fixing the strings before the upcoming release.

How so?

**Comment by gunchleoc** [comment]
*scratches head* I now went for the "load more" button on Crowdin and there was one more occurrence of this on Dec 15, 2022 but my locale looks clean: no translations listed for the gd locale on that date.

**Comment by gunchleoc** [comment]
I don't think we'll be able to track down what went wrong here, so I'm closing this to unclutter the issue tracker.
