### ISSUE TITLE
Mastodon archive has media folder, but all the files are 0kb

### ISSUE THREAD

**Issue by ronilaukkarinen** [mastodon/mastodon#26469]
### Steps to reproduce the problem

1. Go to your instance's /settings/export and request your archive
2. Wait for archive to compile
3. See the download size being different than above

![image](https://github.com/mastodon/mastodon/assets/1534150/3859958b-82d1-4c09-96bc-e1c4f4c17854)

4. See all files under media being 0kb

### Expected behaviour

Should contain complete archive

### Actual behaviour

Media files are zero kb

### Detailed description

Not sure which log to look at about this. I have S3 in .env.production:

```S3_ENABLED=true
S3_PROTOCOL=https
S3_BUCKET=xxxxx
S3_REGION=auto
S3_HOSTNAME=xxxxx
S3_ENDPOINT=xxxxx
AWS_ACCESS_KEY_ID=xxxxx
AWS_SECRET_ACCESS_KEY=xxxxx
S3_ALIAS_HOST=xxxxx
```

Can S3 or a bug in Mastodon cause this?
Please advice.

### Mastodon instance

mementomori.social

### Mastodon version

v4.2.0+nightly-2023-08-12

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]
- Node.js version: v16.20.1

**Comment by Gargron** [comment]
Which S3 provider?

**Comment by ronilaukkarinen** [comment]
> Which S3 provider?

Cloudflare R2.

**Comment by ClearlyClaire** [comment]
Do you have other issues with media? Try with `S3_DISABLE_CHECKSUM_MODE=true`

**Comment by ronilaukkarinen** [comment]
> Do you have other issues with media? Try with `S3_DISABLE_CHECKSUM_MODE=true`

No other issues that I know of. What does that parameter do? It disables some checksum check? I'll try it tonight.

**Comment by ClearlyClaire** [comment]
It disables checksum checks that have recently been introduced in a dependency update and that are incompatible with some S3-compatible providers, see #26394

**Comment by ronilaukkarinen** [comment]
> There is not, but removing the latest archive from the database (`Account.find_local('your_username').user.backups.reorder(created_at: :desc).first.destroy`) should do the trick

Thanks!
