### ISSUE TITLE
Privacy and reach: unify settings so "all boxes checked" = "most discoverable/public"

### ISSUE THREAD

**Issue by digitalcircuit** [mastodon/mastodon#26493]
## Pitch

On the `Privacy and reach` panel, invert the name and default for two existing settings so "all boxes checked" means "most discoverable/public"

| Old | Old setting name | … | New | New setting name
|------------------|---------------------------|----|-------------------|---------------------------
❌ | `Manually review new followers` | ➡ | ✔️  | `Automatically accept new followers`
❌ | `Hide follows and followers from profile` | ➡ | ✔️  | `Show follows and followers on profile`

**The resulting outcome remains the same as before.**  Accounts will still be unlocked by default (`locked` = `false`) and not hide followers/followed by (`hide_collections` = `false`).¹

This merely changes how it's presented to the user at the UI layer using [the new `setting_inverse_alias()` function introduced with the privacy tab](https://github.com/mastodon/mastodon/pull/26484 ).

```ruby
# Example addition to app/models/user_settings.rb
setting_inverse_alias :unlocked, :locked
setting_inverse_alias :show_collections, :hide_collections
```

New hint text:
* `Automatically accept new followers`
  * `People can follow you without requesting approval and you will not need to accept or reject new followers.`
* `Show follows and followers on profile`
  * `People can browse through your follows and followers.  People you follow will see that you follow them regardless.`

¹ Some folks pointed out wanting to change these defaults, or letting the instance administrator configure the defaults.  If so, I'd suggest doing that separately for easier review.

*[Feature request is sourced from my past comment](https://github.com/mastodon/mastodon/pull/26344#issuecomment-1676195299)*

## Motivation

* Makes it easier to opt in to the traditional social media experience ("just check all the boxes on this page!")
* Simplifies locking down one's account if being harassed ("uncheck all of the boxes on this page")
* Potentially reduces cognitive load by keeping a consistent privacy outcome (becoming more public/discoverable/reachable) for each checkbox

### Before
![Screenshot of the "Privacy and reach" settings panel showing "Manually review new followers" and "Hide follows and followers from profile" unchecked](https://zorro.casa/sync/Hosting/Utilities/Development/Mastodon/issues/privacy%20unify%20checkboxes/Privacy%20and%20reach%20-%20before.png#v2)
> * `Manually review new followers`
>   * `People will request to follow you and you will be able to accept or reject new followers.`
> * `Hide follows and followers from profile`
>   * `People will not be able to browse through your follows and followers.  People you follow will see that you follow them regardless.`

### After
![Screenshot of the "Privacy and reach" settings panel showing "Automatically accept new followers" and "Show follows and followers on profile" checked and recommended](https://zorro.casa/sync/Hosting/Utilities/Development/Mastodon/issues/privacy%20unify%20checkboxes/Privacy%20and%20reach%20-%20after%20mockup.png#v2)
> * `Automatically accept new followers` (recommended)
>   * `People can follow you without requesting approval and you will not need to accept or reject new followers.`
> * `Show follows and followers on profile` (recommended)
>   * `People can browse through your follows and followers.  People you follow will see that you follow them regardless.`

**Comment by ClearlyClaire** [comment]
This makes sense to me.

> This merely changes how it's presented to the user at the UI layer using [the new `setting_inverse_alias()` function introduced with the privacy tab](https://github.com/mastodon/mastodon/pull/26484).
> 
> ```ruby
> # Example addition to app/models/user_settings.rb
> setting_inverse_alias :unlocked, :locked
> setting_inverse_alias :show_collections, :hide_collections
> ```

Unfortunately, it will be a bit more complex than this, as those are not settings but `Account` attributes.
