### ISSUE TITLE
Can't use rake secret to generate Application Secrets (from docker image)

### ISSUE THREAD

**Issue by ciencia** [mastodon/mastodon#26490]
### Steps to reproduce the problem

1. Download repository
2. Run `docker compose run --rm -- web rake secret` inside the repository

### Expected behaviour

rake secret generates the secrets I need to run the application

### Actual behaviour

An error prevents rake secret from executing

### Detailed description

```
rake aborted!
Gem::LoadError: You have already activated rake 13.0.3, but your Gemfile requires rake 13.0.6. Prepending `bundle exec` to your command may solve this.
<internal:/opt/ruby/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/opt/ruby/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/opt/mastodon/config/boot.rb:8:in `<top (required)>'
/opt/mastodon/config/application.rb:1:in `require_relative'
/opt/mastodon/config/application.rb:1:in `<top (required)>'
<internal:/opt/ruby/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/opt/ruby/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/opt/mastodon/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

### Mastodon version

main

### Technical details

I've actually "solved" my necessity to generate a secret by running

`docker compose run --rm --user=root -- web bash`

Then inside of the container:

`gem install rake -v 13.0.6`

And finally `rake secret` works

**Comment by renchap** [comment]
You need to run `docker compose run --rm -- web bundle exec rake secret`, or `docker compose run --rm -- web bundle exec rails secret`.

Where did you find this command? Maybe we need to update some documentation

**Comment by ciencia** [comment]
It's on the .env.production.sample file

https://github.com/mastodon/mastodon/blob/main/.env.production.sample#L43

And also on the documentation page:

https://docs.joinmastodon.org/admin/config/#secrets

Note that `rake mastodon:webpush:generate_vapid_key` has the same problem, too

**Comment by mjankowski** [comment]
The actual command here has changed in recent release, and also all the example commands in the production sample now either go through binstubs, or have explicit "bundle exec" in front of that, so I think that should minimize that.

Going to call this resolved by https://github.com/mastodon/mastodon/pull/30917 and by the discussion on this issue ... but please reopen if I'm missing something (and please open issues/PRs on docs repo if there are similar wordings there)
