### ISSUE TITLE
Add descriptions (alt-text) to profile picture and header picture

### ISSUE THREAD

**Issue by colinleroy** [mastodon/mastodon#26505]
### Pitch

They're missing. It would be nice to be able to have descriptions of these pictures too.

### Motivation

As an accessibility feature, it would benefit the whole community.

**Comment by Cassolotl** [comment]
Duplicate of *Add ALT-Tag to banner and profile pictures and make the value editable for acessiblility reasons #10313* (March 2019)

**Comment by vmstan** [comment]
Closed as duplicate.
