### ISSUE TITLE
Can mastodon increase the cap on frame rate for video uploads?

### ISSUE THREAD

**Issue by saket** [mastodon/mastodon#26514]
### Pitch

Mastodon rejects videos that were recorded above 60fps. This restriction is probably okay for videos taken from camera, but it unfortunately also affects screen recordings taken by Android (and probably iOS too). Considering that 90/120hz is the new standard on phone displays these days, could Mastodon lift this restriction?

### Motivation

This will benefit users who'd want to upload screen recordings to mastodon from their mobile. 

FWIW Android does not offer any way to change the frame rate of screen recordings. As a developer, I can find a way to reduce my video's frame rate, but the average person is surely going to give up.

**Comment by JustDalek** [comment]
Mastodon is experimenting with not caching remote videos locally per the roadmap

If that feature is implemented, and an admin can configure what videos they allow locally (size, fps, dimensions, whatever)

Then sure, I wouldn't mind that. Wont bother my storage at that point

**Comment by saket** [comment]
Turns out the frame limit was already bumped to 120fps a few months ago. It should be available as part of v4.2.0.

https://github.com/mastodon/mastodon/commit/9bda93374093c738f1007922b2e8df58043c718f
