### ISSUE TITLE
v4.2.0-beta1 not working after clean new installation on Ubuntu 22.04

### ISSUE THREAD

**Issue by DalekDave** [mastodon/mastodon#26526]
### Steps to reproduce the problem

1. Followed the 'Installing from source' instructions at docs.joinmastodon.org 
2. Proposed version for installation was v4.2.0-beta1
3. Proceeded with installation, using ruby-3.2.2 as required (won't install with ruby-3.0.x)
4. Used Nginx config and systemd service files distributed with v4.2.0-beta1
5. Successfully started Nginx and systemd with these files
6. Visited https://burnout.cafe
7. Site does not display correctly (only 2 logo graphics, nothing else).

OS: Ubuntu server 22.04
Web server: Nginx 1.18
Posgresql version:  14.8

Installation site: https://burnout.cafe
Full command line output from the installation process (with service and Nginx conf files):
[Mastodon v420 installation output for burnout cafe.txt](https://github.com/mastodon/mastodon/files/12369281/Mastodon.v420.installation.output.for.burnout.cafe.txt)

### Expected behaviour

Should have displayed Mastodon Web interface

### Actual behaviour

Only displayed 2 logo graphics on white page

### Detailed description

See attached full output from the installation process, with command line 'cat' of the systemd service and Nginx conf files.

### Mastodon instance

https://burnout.cafe

### Mastodon version

v4.1.2-beta1

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2):  ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
- Node.js version: (from `node --version`, eg. v18.16.0): v16.20.2

**Comment by DalekDave** [comment]
Request:
Please can you help me troubleshoot this and get burnout.cafe working?
And thank you so much for your work on Mastodon! :)

**Comment by DalekDave** [comment]
Elasticsearch version: 8.9.1

**Comment by BossMAN559** [comment]
try
chmod a+x /home/mastodon/

**Comment by renchap** [comment]
Do you have anything in your `public/packs` directory? You should find all the JS/CSS here.

Can you show what errors are displayed in your browser inspector's console when you load the page?

I suspect that your nginx config is invalid and is not serving your JS/CSS properly.

**Comment by DalekDave** [comment]
That

> try chmod a+x /home/mastodon/

That seems to have solved the problem, thank you for the tip!
