### ISSUE TITLE
for posts and DMs, make the text entry box smaller

### ISSUE THREAD

**Issue by alreadyinuse** [mastodon/mastodon#26539]
### Pitch

For typing DMs and posts, I suggest to shrink the text entry box down to something like 5 characters, for both texts and posts.

### Motivation

Because obviously, if 91 characters is good, then 5 will be even better.  The text entry box for typing posts and DMs is way too big.  When I'm replying to someone's DM, I can view about 91 characters of what I'm typing.  When I'm creating a post, I can view 420 characters, (or I can view 91, it all depends, because the DM interface also randomly creates posts, which is just brilliant by the way...)

Reducing the size of the text entry box will really help people create better quality posts and DMs, by forcing them to compose the entire thing in their mind, and then making them peck it out one character at a time, like Stephen Fing Hawking.  He was a genius.  Just think what a better world this would be if we could use this one simple trick to encourage Hawking's level of brilliance in the users of Mastodon, especially the users who happen to be on the GUI development team... 

I maximize my productivity by shrinking down all my windows as much as possible:
![image](https://github.com/mastodon/mastodon/assets/65797538/e3b3ceb7-a954-4437-8f0a-e349d29ac65a)

**Comment by michelv** [comment]
Do you feel that you have helped in any way?

**Comment by alreadyinuse** [comment]
> Do you feel that you have helped in any way?
Oh, when you leave a tag on the side of a building, you never know who may eventually see your tag and be inspired to think outside the box of the broken system
