### ISSUE TITLE
Using public key cryptography as an alternative to passwords 

### ISSUE THREAD

**Issue by Fntoomen** [mastodon/mastodon#26572]
### Pitch

It would be really cool if you gave the user the option to use public key cryptography as an alternative to passwords.
You would store the public key in your database and the user in order to log in will have to prove that he knows the private key.

### Motivation

It would make login in much safer.

- The server won't actually store the secret (private key) needed to log in. Instead it will have your public key, which when leaked won't cause any issues. It's safer then peppering, salting and hashing a password.
- When you prove to a fishing website that you know the private key, you won't share it as would be the case with passwords - in order to prove that you know the password you have to type it in.
- Private key would be harder to guess/bruteforce than the statistical password.

**Comment by renchap** [comment]
Kind of duplicate to https://github.com/mastodon/mastodon/issues/20383

Passkeys allow password-less login in a standardised manner

**Comment by dhthwy** [comment]
This truly cripples the usability of your software. I don't know why you won't implement this. How long have you had? It's a no-brainer. Really, you're going to let passwords be exposed? Reconsider your approach to this issue, until then I cannot use or recommend your software.
