### ISSUE TITLE
Special character break out-of-band hashtags

### ISSUE THREAD

**Issue by misterzwiebel** [mastodon/mastodon#26585]
### Steps to reproduce the problem

Post a toot that contains a list of hashtags at the end.
One of the hashtags needs to contain a special character like äöü. (e.g. Köln)

### Expected behaviour

Render all hashtags

### Actual behaviour

Only renders the hashtag that contains a special character, ignoring everything else

### Detailed description

<img width="443" src="https://github.com/mastodon/mastodon/assets/88088481/ec8719fb-e756-4061-9a0e-d83c3ddc1db2">

### Mastodon instance

krassestegang.social

### Mastodon version

v4.2.0+beta2

### Browser name and version

Safari 14.1.2

### Operating system

macOS 11.6.6

**Comment by gunchleoc** [comment]
I can reproduce that: https://ailbhean.co-shaoghal.net/@gunchleoc/110939719935582492

My server is running [main](https://ailbhean.co-shaoghal.net/@gunchleoc/110939719935582492) (a few commits after 4.2.0-beta1

**Comment by cadusilva** [comment]
> This should be fixed by #26614, can you check whether that's the case?

I had the same issue at `bolha.one` but this fix worked for me.

![Toot I published that says 'This is a test' with a bunch of hashtags for testing special characters in them](https://github.com/mastodon/mastodon/assets/8684263/3a28f2c7-b374-4e96-bc3a-94cf056165a2 "Toot I published that says 'This is a test' with a bunch of hashtags for testing special characters in them")

**Comment by dadall** [comment]
Running beta3 and still having the issue :

![image](https://github.com/mastodon/mastodon/assets/2796341/3c826e5a-77e9-4dad-8365-24fec0c47320)

**Comment by ClearlyClaire** [comment]
I can't reproduce it, but we do use a browser API for the normalization/comparison work, so this might possibly depend on your browser and/or locale, which isn't great.

**Comment by gunchleoc** [comment]
I pulled up a post by dada that has the problem: https://diaspodon.fr/@dada/110854459668938326

![image](https://github.com/mastodon/mastodon/assets/4095570/8e92b39f-05e4-4f51-aa74-d312bec258f8)

Then displayed it via my server: https://ailbhean.co-shaoghal.net/@dada@diaspodon.fr/110854459661316837

![image](https://github.com/mastodon/mastodon/assets/4095570/7397b427-cc1e-44db-a014-69273fc1d7b0)

It is still broken with the direct link, but fine when routed through my server. I'm wondering whether everything went OK with the update on diaspodon.fr.  Maybe it just needs a bit of TLC with `RAILS_ENV=production bundle exec rails assets:precompile`?

**Comment by ClearlyClaire** [comment]
Oh, right, it's also displaying the tag with pre-beta3 styles, so the assets are indeed probably outdated!

**Comment by dadall** [comment]
```
mastodon@diaspodon:~/live$ RAILS_ENV=production bundle exec rails assets:precompile
Everything's up-to-date. Nothing to do
mastodon@diaspodon:~/live$
```

Is there a way to force this task?

**Comment by dadall** [comment]
Assets fixed, nodejs version fixed, the issue seems to be almost fixed cf https://diaspodon.fr/@dada/111062740793665139

Hastags are no more displayed with the fancy thing around them :D

**Comment by ClearlyClaire** [comment]
why “almost” fixed? this behaves as expected

**Comment by dadall** [comment]
Ah? Oh. Perfect then! I thought this was the expected behavior : 
![expected](https://github.com/mastodon/mastodon/assets/2796341/5d06a761-a29d-442a-9d51-3731e70e3439)

**Comment by ClearlyClaire** [comment]
No, the styling has changed to de-emphasize them! Your post is exhibiting the expected behavior!
