### ISSUE TITLE
Allow ruby tags in the HTML sanitizer

### ISSUE THREAD

**Issue by dahlia** [mastodon/mastodon#26592]
<i>(Originally posted in <https://github.com/mastodon/mastodon/issues/8474#issuecomment-1647334955>.)</i>

### Pitch

To improve accessibility for East Asian language speakers, it would be worth adding the following tags for ruby characters: [`<ruby>`][1], [`<rt>`][2], and [`<rp>`][3].

[1]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ruby
[2]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rt
[3]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rp

### Motivation

Ruby characters are a common element in so-called CJK, East Asian texts, and are often needed due to the fact that Chinese characters are not phonetic (basically).  They are used primarily …

- to attach phonetic characters to esoteric Chinese characters that are difficult to read,
- to help children who can't yet read Chinese characters well,
- and to give screen readers hints about the pronunciation of rare words that aren't in the dictionary,

… all of which are basically to increase accessibility.

For more information on ruby characters, you can check out the [Wikipedia on this topic][4].

[4]: https://en.wikipedia.org/wiki/Ruby_character

**Comment by wind0204** [comment]
As a Korean person, I don't read the Chinese characters. I think however for the demographics in which Chinese characters are utilized this would be very nice and helpful.

**Comment by ThisIsMissEm** [comment]
I think I know how to do a PR for these. Do these tags require additional attributes?

**Comment by dahlia** [comment]
> I think I know how to do a PR for these. Do these tags require additional attributes?

No, they don't require any attributes.

> Also, how do these affect the layout flow of text? E.g., if using a reset would additional css be needed to style them correctly?

Although I don't have much experience with CSS, I found these tags mostly orthogonal to other styles.  Their positions and alignments are determined by properties like [`ruby-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/ruby-position) and [`ruby-align`](https://developer.mozilla.org/en-US/docs/Web/CSS/ruby-align) which are dedicated for these tags.

**Comment by ThisIsMissEm** [comment]
The other question I have is: would this only affect third-party content, or would it also need/benefit from some way to compose this in Mastodon?

also curious how this might affect mobile clients.

**Comment by dahlia** [comment]
> The other question I have is: would this only affect third-party content, or would it also need/benefit from some way to compose this in Mastodon?

It may benefit from providing a way to compose ruby tags in Mastodon, but I believe it should be a separate issue.  For this issue, we can assume this only affect third-party contents.

**Comment by ThisIsMissEm** [comment]
I've started this PR to implement support for ruby tags: https://github.com/mastodon/mastodon/pull/30897

**Comment by ThisIsMissEm** [comment]
Surprised this didn't auto close, but yeah. cc @vmstan
