### ISSUE TITLE
v4.2.0-beta2: Admin-Dashboard not accessible

### ISSUE THREAD

**Issue by markusblogde** [mastodon/mastodon#26598]
### Steps to reproduce the problem

1. Upgrade mastodon from v4.2.0-beta1 to v4.2.0-beta2
2. Login and open Admin-Dashboard -> Something went wrong

### Expected behaviour

Admin-Dashboard should open

### Actual behaviour

Something went wrong

### Mastodon instance

mastodontech.de

### Mastodon version

v4.2.0-beta2

### Browser name and version

Firefox 116.0.3 (64-Bit

### Operating system

Windows 11

### Technical details

syslog:

```
Aug 22 10:52:28 web247 bundle[1029719]: I, [2023-08-22T10:52:28.997116 #1029719]  INFO -- : [7a6a2fbd-983b-4c06-8341-55cccb0c0576] method=GET path=/admin/dashboard format=html controller=Admin::DashboardController action=index status=500 allocations=40429 duration=77.51 view=0.00 db=15.66
Aug 22 10:52:28 web247 bundle[1029719]: F, [2023-08-22T10:52:28.997778 #1029719] FATAL -- : [7a6a2fbd-983b-4c06-8341-55cccb0c0576]
Aug 22 10:52:28 web247 bundle[1029719]: [7a6a2fbd-983b-4c06-8341-55cccb0c0576] NoMethodError (undefined method `dig' for nil:NilClass):
Aug 22 10:52:28 web247 bundle[1029719]: [7a6a2fbd-983b-4c06-8341-55cccb0c0576]
Aug 22 10:52:28 web247 bundle[1029719]: [7a6a2fbd-983b-4c06-8341-55cccb0c0576] app/lib/admin/system_check/elasticsearch_check.rb:44:in `message'
Aug 22 10:52:28 web247 bundle[1029719]: [7a6a2fbd-983b-4c06-8341-55cccb0c0576] app/lib/admin/system_check.rb:19:in `block in perform'
Aug 22 10:52:28 web247 bundle[1029719]: [7a6a2fbd-983b-4c06-8341-55cccb0c0576] app/lib/admin/system_check.rb:13:in `each'
Aug 22 10:52:28 web247 bundle[1029719]: [7a6a2fbd-983b-4c06-8341-55cccb0c0576] app/lib/admin/system_check.rb:13:in `each_with_object'
Aug 22 10:52:28 web247 bundle[1029719]: [7a6a2fbd-983b-4c06-8341-55cccb0c0576] app/lib/admin/system_check.rb:13:in `perform'
Aug 22 10:52:28 web247 bundle[1029719]: [7a6a2fbd-983b-4c06-8341-55cccb0c0576] app/controllers/admin/dashboard_controller.rb:10:in `index'
Aug 22 10:52:28 web247 bundle[1029719]: [7a6a2fbd-983b-4c06-8341-55cccb0c0576] app/controllers/concerns/localized.rb:11:in `set_locale'
Aug 22 10:52:28 web247 bundle[1029719]: [7a6a2fbd-983b-4c06-8341-55cccb0c0576] lib/mastodon/rack_middleware.rb:9:in `call'
```

**Comment by jmrplens** [comment]
Same here. I have the same error in the log.

I guess it has to do with the change to view ElasticSearch statistics.

Debian 11
ElasticSearch 7.17.12
Redis (main, cache and sidekiq) 7.2.0
PostgreSQL 15

**Comment by ClearlyClaire** [comment]
Hi, thank for your report!

This should be an easy fix, but I'm surprised `Chewy.client.indices.get_settings['chewy_specifications']` would return `nil` in that case.

**Comment by solarisfire** [comment]
Can we please get some proper instruction for how to upgrade from v4.2.0-beta1 to v4.2.0-beta2 correctly?

**Comment by ClearlyClaire** [comment]
This is not really a failure to update to v4.2.0-beta2 but a bug in v4.2.0-beta2, and I don't know the root cause of it for now.

That being said, I believe running `tootctl search deploy --reset-chewy` should do the trick.

**Comment by markusblogde** [comment]
Ok, I will check `tootctl search deploy --reset-chewy`, but it will run the next 3 hours...

**Comment by jmrplens** [comment]
> This is not really a failure to update to v4.2.0-beta2 but a bug in v4.2.0-beta2, and I don't know the root cause of it for now.
> 
> 
> 
> That being said, I believe running `tootctl search deploy --reset-chewy` should do the trick.

I just finished running it and restarted but no change. Same log.

**Comment by ClearlyClaire** [comment]
Alright, let's try to find out the root cause. Can you open a Rails console (`RAILS_ENV=production bundle exec rails c`) and try the following commands? Copy the full output for each line:

```ruby
Chewy::Stash::Specification.index_name
Chewy.client.cluster.health['status']
Chewy.client.cluster.health['number_of_nodes']
Chewy.client.indices.get_mapping['instances']
Chewy.client.indices.get_settings['instances']
Chewy.client.indices.get_settings[Chewy::Stash::Specification.index_name]
```

**Comment by jmrplens** [comment]
> Chewy::Stash::Specification.index_name
> Chewy.client.cluster.health['status']
> Chewy.client.cluster.health['number_of_nodes']
> Chewy.client.indices.get_mapping['instances']
> Chewy.client.indices.get_settings['instances']
> Chewy.client.indices.get_settings[Chewy::Stash::Specification.index_name]



```bash

Loading production environment (Rails 7.0.7)
irb(main):001:0> Chewy::Stash::Specification.index_name
=> "mastodon_chewy_specifications"
irb(main):002:0> Chewy.client.cluster.health['status']
=> "yellow"
irb(main):003:0> Chewy.client.cluster.health['number_of_nodes']
=> 1
irb(main):004:0> Chewy.client.indices.get_mapping['instances']
=> nil
irb(main):005:0> Chewy.client.indices.get_settings['instances']
=> nil
irb(main):006:0> Chewy.client.indices.get_settings[Chewy::Stash::Specification.index_nam
e]
=> 
{"settings"=>
  {"index"=>
    {"routing"=>{"allocation"=>{"include"=>{"_tier_preference"=>"data_content"}}},
     "number_of_shards"=>"1",
     "provided_name"=>"mastodon_chewy_specifications",
     "creation_date"=>"1692715319266",
     "number_of_replicas"=>"0",
     "uuid"=>"Hc2az4MKSvGLId_G1gq8Xg",
     "version"=>{"created"=>"7171299"}}}}

```

**Comment by ClearlyClaire** [comment]
oooh, that makes a lot of sense, I'll be working on a patch, thanks!

**Comment by ClearlyClaire** [comment]
Can you give https://github.com/mastodon/mastodon/pull/26605 a try? If you use docker, you can check https://github.com/mastodon/mastodon/pkgs/container/mastodon/120924204?tag=pr-26605

**Comment by markusblogde** [comment]
> Can you give #26605 a try? If you use docker, you can check https://github.com/mastodon/mastodon/pkgs/container/mastodon/120924204?tag=pr-26605

Done. Dashboard is now accessible! Thank you

**Comment by jmrplens** [comment]
Solved!
Thanks 🥰
