### ISSUE TITLE
Out-of-band hashtags not hidden in posts with content warnings

### ISSUE THREAD

**Issue by joenepraat** [mastodon/mastodon#26611]
### Steps to reproduce the problem

1. Compose a new post with a content warning and a hashtag on the last line
2. Publish the post
3. When you view the post collapsed (default when viewing posts with content warnings) the regular content is hidden, but the hashtag is not.

![afbeelding](https://github.com/mastodon/mastodon/assets/41594439/f4de532f-0025-4612-a3f2-3df7c85a1c22)

### Expected behaviour

Hashtags in a post with content warnings should be part of the hidden post content, because hashtags mostly have the same issues as the text or media content (think especially about NSFW content here). _Edit: I think the easiest way to fix this is is to disable out-of-band hashtags for CW posts all together._

### Actual behaviour

Hashtag is shown as out-of-band, like regular posts

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.0+nightly-2023-08-22

### Browser name and version

Firefox 116.0.3

### Operating system

Ubuntu 23.04

**Comment by joenepraat** [comment]
See https://mastodon.social/@joenetest/110934515275195526 for an example.

**Comment by joenepraat** [comment]
Also with image (https://mastodon.social/@joenetest/110934656806949022).

![afbeelding](https://github.com/mastodon/mastodon/assets/41594439/c4575dbc-97f4-4fee-bb3c-6be828342a6e)

**Comment by renchap** [comment]
Thanks for reporting this, it should be fixed soon
