### ISSUE TITLE
Home timeline shows toots from people I don't follow

### ISSUE THREAD

**Issue by BjornW** [mastodon/mastodon#26621]
### Steps to reproduce the problem

1. Login in Mastodon.social 
2. Go to Home
3. Read toots, replies and boosts of people you follow. 
Instead the Home timeline includes completely unrelated people I don't know nor are they connected (via replies or boost) with people I follow. Somehow I get to see all kinds of message I'm not interested in, including messages with content I'd rather not see.

### Expected behaviour

The Home timeline should only display statuses (toots, replies & boosts) from people I follow (see also https://docs.joinmastodon.org/methods/timelines/#home) 

### Actual behaviour

The Home timeline displays unrelated toots of people I don not follow nor do the people I follow, follow these people

### Detailed description

The Home timeline suddenly includes completely unrelated people I don't know nor are they connected (via replies or boost) with people I follow. Now I get to see all kinds of message I'm not interested in including message with content I'd rather not see. It feels a bit like an algorithmic timeline similar to for instance Twitter (X) (used to have?) has.

I'd expect the Home timeline to only display statuses (toots, replies and boosts) from people I follow

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.0+nightly-2023-08-22

### Browser name and version

Firefox 115.0.2

### Operating system

Ubuntu Linux 22.04.3 LTS

**Comment by BjornW** [comment]
I am following quite a lot of hashtags, but the hashtags are filtered into a different column (see screenshot). 
![screenshot-2023-08-23_16-38-32](https://github.com/mastodon/mastodon/assets/65042/f99ded5b-2085-4bcc-aeb4-c951cd7cd834) For instance I follow the #ccccamp23 hashtag. 

The toots I received in my Home Timeline, of people I do not follow, did also not contain the hash tags I follow.  I have the feeling this might be a bug & if this is not a bug but intended behavior I'd like to change this behavior in the preferences ;)

**Comment by BjornW** [comment]
@ClearlyClaire thank you, I've removed all the 'followed hashtags' and this seems to have fixed the issue. So for anyone following this issue this seems to be the solution.

Note: I still find it very confusing that by following certain hashtags I get all kinds of toots, boosts and replies from people I don't follow in my timeline. Perhaps a specific Hashtags timeline would be better & more clear to end-users. Or maybe the documentation found here https://docs.joinmastodon.org/methods/timelines/#home needs an update.

**Comment by KevinGimbel** [comment]
> Perhaps a specific Hashtags timeline would be better & more clear to end-users. 

I agree with this! Either this, or a "followers only" view/timeline. I also follow a few hashtags and I rarely see any posts from the people I follow.

**Comment by ClearlyClaire** [comment]
> Note: I still find it very confusing that by following certain hashtags I get all kinds of toots, boosts and replies from people I don't follow in my timeline.

This is the whole point of the hashtag follow feature, though. But there's an important bit that we are still missing, that is displaying that a post got inserted in your timeline because you were following a hashtag. We are aware of that and it is planned, but unfortunately, this is a bit more complex to implement.

> Perhaps a specific Hashtags timeline would be better & more clear to end-users.

I guess that could be useful as well, but that would be a different feature!

> Or maybe the documentation found here https://docs.joinmastodon.org/methods/timelines/#home needs an update.

Opened a PR to update it: https://github.com/mastodon/documentation/pull/1282

**Comment by verymilan** [comment]
Thats odd... it happened yesterday to me. I have some hashtag columns in the advanced webinterface and all of the sudden it spills it into the home timeline... doesn't look right. Rebuilding my timeline did not help.

**Comment by ClearlyClaire** [comment]
@verymilan which version of Mastodon is your server running?

**Comment by ClearlyClaire** [comment]
4.1.6 does not clean up your feed from unfollowed hashtags, so this is still consistent with this coming from a followed hashtag!

**Comment by renchap** [comment]
Closing this, issue for displaying why a post is in your timeline (because it comes from a hashtag you follow) is here: #26079
