### ISSUE TITLE
Full Text Search brings up very old posts before recent ones

### ISSUE THREAD

**Issue by Matt-Swift** [mastodon/mastodon#26683]
### Steps to reproduce the problem

1. Search a term (in this example, `test search`)
2. Browse through the resulting posts

### Expected behaviour

Posts are shown in reverse chronological order

### Actual behaviour

Posts from 2016-2018 are shown before the most recent ones

### Detailed description

![image](https://github.com/mastodon/mastodon/assets/33199242/02e56c4f-a24f-4692-a106-953f4415bb0f)

This happens with all search terms, but the example above was to get one with just a small number of old posts at the top. Certain other terms will have potentially several dozen or hundreds of posts before you get to recently posted ones (test on a search term like `Mastodon` and keep scrolling)

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.0-nightly.2023-08-27

### Browser name and version

Floorp 11.1.2

### Operating system

Debian 12

**Comment by ClearlyClaire** [comment]
Should be addressed by #26686 (not deployed on mastodon.social yet)

**Comment by renchap** [comment]
Closing as this is in 4.2 and has been deployed.
