### ISSUE TITLE
Comment edits not propagating across instances as expected

### ISSUE THREAD

**Issue by RockstarRaccoon** [mastodon/mastodon#26731]
### Steps to reproduce the problem

Imagine three users on three instances: User A on Instance A, who is mutually following User B from Instance B, and User C from Instance C who is mutually following with User B.  User A and User C are not following each other at all, nor is anyone from instance C following user A.

So the connection looks like...
A <-> B <-> C
...and there is no connection to User A from Instance C, thus making User A invisible to User C outside of the following interaction...

1. User B makes a post on Instance B.
2. User A responds to post from Instance A, then edits their own comment.
3. User C, from Instance C, from which no one follows user A, looks at post by user A, and sees comment by user B.

### Expected behaviour

Edit from User A should proliferate to instant C, and be visible to user C

### Actual behaviour

Edit from User A does not proliferate to Instance C, so only the original post shows for User C

### Detailed description

As described above, the edit to a comment should be proliferating, but is not.

### Mastodon instance

https://writing.exchange/@raccoon/110976535994429708

### Mastodon version

v4.1.6--ff3

### Browser name and version

Chrome

### Operating system

Android

### Technical details

I think the operative part of this bug is that the post itself is being proliferated to a server which isn't following me, but the edit isn't similarly proliferated, so they see the version with the major typo, without the immediate edit.

**Comment by ClearlyClaire** [comment]
Both posts and edits are supposed to be forwarded, so I am not sure what may have been going on. In your example, is it possible that the post from B was fetched for another reason than the forwarding itself (e.g. A replied)?

**Comment by fasiha** [comment]
Thanks for confirming that both posts and edits are supposed to flow @ClearlyClaire! That helps set expectations, because I'm encountering the same behavior as @RockstarRaccoon:
- @22@sfba.social posts
- @22@hachyderm.io (who follows them) sees the post and boosts
- @PleaseCaption@botsin.space already follows @22@hachyderm.io and so sees the boost (and nobody on botsin.space follows @22@sfba.social)
- Now, @22@sfba.social edits their post
- @22@hachyderm.io sees the edit instantly
- However, @PleaseCaption@botsin.space never sees the edit (tested after 30+ minutes)

There is a sort-of workaround: after a while, if @PleaseCaption@botsin.space *searches* for the original URL (via `/api/v2/search` or the search box), the edited toot appears in the search, and the original toot temporarily shows the edit. But if I refresh @PleaseCaption@botsin.space, the old unedited toot is still shown.

(I'm hoping we can find the bug in Mastodon where edits aren't being propagated, but it's possible that solving that issue won't solve this secondary issue, wherein the `search` endpoint returns the latest toot but it doesn't overwrite the old toot in SQL?)

**Comment by ClearlyClaire** [comment]
> Can I ask: were edits always supposed to be forwarded, or is that a recent change?

They were always supposed to be forwarded.

> There is a sort-of workaround: after a while, if @[PleaseCaption@botsin.space](mailto:PleaseCaption@botsin.space) _searches_ for the original URL (via `/api/v2/search` or the search box), the edited toot appears in the search, and the web interface temporarily shows the edit. But if I refresh @[PleaseCaption@botsin.space](mailto:PleaseCaption@botsin.space) web client, the old unedited toot is still shown.
> 
> (I'm hoping we can find the bug in Mastodon where edits aren't being propagated, but it's possible that solving that issue won't solve this secondary issue, wherein the `search` endpoint returns the latest toot but it doesn't overwrite the old toot in SQL?)

I can't see how updates would be returned without being persisted to the database. It's possible cache doesn't get invalidated, I will investigate! In the meantime, can you check whether it's been updated for `PleaseCaption@botsin.space`?

**Comment by fasiha** [comment]
Thank you so much @ClearlyClaire, you are a force of nature 🙌!

> In the meantime, can you check whether it's been updated for `PleaseCaption@botsin.space`?

Yes, at some point in the last ten hours, botsin.space persisted the edit so when I pull up the web interface, I see the edit.

Give me a few hours, I'll triple-check that behavior that I reported, where search shows the edit but old un-edited toot is shown on refresh.

**Comment by fasiha** [comment]
Can confirm a potential cache issue:

1. `@22@sfba.social` toots
2. `@22@hacyderm.io` (a follower) boosts
3. `@PleaseCaption@botsin.space` sees the the original post (and AFAIK nobody on `botsin.space` follows `@22@sfba.social`)
4. `@22@sfba.social` edits toot
5. `@22@hacyderm.io` sees the edit
6. `@PleaseCaption@botsin.space` doesn't see the edit for 10+ hours
7. I search for the toot link in the botsin.space web interface, and the edited toot is found
8. If I click on it and refresh my browser, it shows the original unedited toot

Curiously, if I refresh again, the edit shows up briefly before being replaced by the original unedited toot? (Maybe the browser is caching the edited toot but the server sends it the original?):

![Safari window in botsin.space shows the original toot. I refresh, the edited toot briefly flashes before replaced by the original toot](https://github.com/mastodon/mastodon/assets/37649/85728a58-d732-4b0a-857c-a75981fc4ce0)

Should I post this in a new issue?

**Comment by ClearlyClaire** [comment]
Yes, please open a new issue! It would also be very helpful if you could watch the XHR queries in your browser's development/network tab and see if you can spot which query results in the old version of the post being returned. In the meantime, I will try to replicate the issue on my side.

**Comment by fasiha** [comment]
@ClearlyClaire I found a twist on the scenario described above https://github.com/mastodon/mastodon/issues/26731#issuecomment-1720713281 where edits are not being propagated:

- account 1 on sfba.social (running v4.2.1) posts something
- account 2 on hachyderm.io (v4.2.1) who follows the above account boosts that post
- account 3 on botsin.space (v4.1.9) who follows the hachyderm account 2 (and not the sfba.social account 1!) sees the boosted toot
- hachyderm.io account 2 *unboosts*
- sfba.social account 1 edits their toot
- hachyderm.io account 2 sees the edit and then re-boosts
- botsin.space sees only the original unedited toot

This workflow was revealed while testing the `@PleaseCaption@botsin.space` bot and is a plausible one: someone who follows the bot (the hachyderm.io account 2) boosts a post without image captions. The bot notified them and they unboosted. The original author (sfba.social account 1) edits their post to add image captions, so now hachyderm.io re-boosts. Unfortunately, PleaseCaption bot (botsin.space) doesn't see the edit.

Note that the original workflow described above https://github.com/mastodon/mastodon/issues/26731#issuecomment-1720713281 is indeed fixed. However, adding the unboost+reboost steps causes this issue to strike again.

Should I open a new issue?

**Comment by ClearlyClaire** [comment]
> Should I open a new issue?

Yes, I think so!
