### ISSUE TITLE
Feature request: List time zone alongside time in emails

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#26788]
### Motivation

In the Mastodon preferences, my timezone is blank. Because of this, emails ("you got a mention" notification emails; "Your account has been accessed from a new IP address" use times from a mystery timezone. I assume it is UTC, which I assume is server time.

Receiving emails with times in UTC is fine, and if I have left my timezone blank, it is surely the most reasonable thing for the server to do. **However**, the problem is that when I look at an email I *don't know* what the timezone is.

![image](https://github.com/mastodon/mastodon/assets/277318/112ad2c7-8393-44df-b829-6279ae70075f)

If I am in my email client I of course won't remember what I have my timezone prefs set to over on Mastodon. At the moment I read that email, what "20:19" means is a total mystery.

### Pitch

One of the following:

1. When an email lists a time, it should always explicitly mention the time zone ("UTC" or other).
2. When an email lists a time, it should always explicitly mention the time zone *if the user has a blank time zone in their preferences*.

I would prefer (1) because, even if I set my time zone to the city where I live, imagine if I went traveling. I would not have a way to be sure, if I am in Germany and I receive an email with a time, that that email is US East Coast time. But you could argue most users, if they set a time zone, you can assume they always want to communicate in that time zone and will know what time zone they set.

However, if the user has *not* set a time zone, then definitely it would be helpful to specify because the user can't figure it out by double-checking their prefs.

**Comment by ClearlyClaire** [comment]
We currently use `I18.l`, which under the hood uses the localized format template `time.formats.default`.

The best way to handle this would probably be to define a `time.formats.with_timezone` template (e.g. `%b %d, %Y, %H:%M %Z` for English).

This is rather easy but will require translators to translate a new format string, which might be a bit late in the release cycle.
