### ISSUE TITLE
Uploadinv mp4 video fails with HTTP code 502

### ISSUE THREAD

**Issue by quinncomendant** [mastodon/mastodon#26791]
### Steps to reproduce the problem

Uploading a mp4 video file to mastodon.social fails:

1. Create a post with the attachment of [this mp4 video file](https://send.strangecode.com/f/rpreplay-final1693853781.mp4).
2. Chrome DevTools > Network shows a HTTP code 502 on the `/api/v2/media` endpoint.

Here's the "copy as cURL" for this POST request from DevTools:

```
curl 'https://mastodon.social/api/v2/media' \
  -H 'authority: mastodon.social' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'authorization: Bearer (redacted)' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundaryisRjZkaUcMQMpL1O' \
  -H 'cookie: _session_id=(redacted)' \
  -H 'dnt: 1' \
  -H 'origin: https://mastodon.social' \
  -H 'referer: https://mastodon.social/publish' \
  -H 'sec-ch-ua: "Chromium";v="116", "Not)A;Brand";v="24", "Microsoft Edge";v="116"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.69' \
  -H 'x-csrf-token: (redacted)' \
  --data-raw $'------WebKitFormBoundaryisRjZkaUcMQMpL1O\r\nContent-Disposition: form-data; name="file"; filename="RPReplay_Final1693853781.mp4"\r\nContent-Type: video/mp4\r\n\r\n\r\n------WebKitFormBoundaryisRjZkaUcMQMpL1O--\r\n' \
  --compressed
```

![SCR-20230904-nczw](https://github.com/mastodon/mastodon/assets/6884276/de1d9d10-b1bb-4d6d-be59-c4621a7f7df8)

### Expected behaviour

Video should upload successfully

### Actual behaviour

Video upload fails

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.0-nightly.2023-09-04

**Comment by Gargron** [comment]
I tested the video and cannot reproduce any issue. HTTP 502 suggests this was a temporary issue with mastodon.social's availability.

**Comment by saket** [comment]
Not sure if this is the same issue, but I'm receiving HTTP `502` errors from https://mastodon.social for this video: 

https://drive.google.com/file/d/1MSCfi4hZvt9KPDGTtI1m5iMzA_tHAixC/view?usp=drive_link

**Comment by saket** [comment]
Here's another image that's triggering a 502 HTTP error: 

https://drive.google.com/file/d/1PfC7URJJtaMp_Wf3KgUeikp1tgsZ_Qcb/view?usp=drive_link
