### ISSUE TITLE
Some posts are experiencing hashtags not showing in v.4.2.0

### ISSUE THREAD

**Issue by fofwisdom** [mastodon/mastodon#26797]
### Steps to reproduce the problem

  I don't know how to reproduce it. Write the address of the post where the issue is occurring instead.
1. original (v4.1.6) - https://duk.space/@Karin_Official/111012571140369639
![image](https://github.com/mastodon/mastodon/assets/205521/0512e9de-4247-46b0-8366-760d7dd55612)
2. issue posts
- v4.2.0-nightly.2023-09-04 - https://mastodon.social/@Karin_Official@duk.space/111012571713629170
![image](https://github.com/mastodon/mastodon/assets/205521/4fb46d1b-733d-435f-9398-b38efe9e8860)
- v4.2.0-beta3 - https://netsphere.one/@Karin_Official@duk.space/111012571171699796
![image](https://github.com/mastodon/mastodon/assets/205521/f1931975-ce06-4551-8748-7b521a128c34)
- v4.2.0-beta3 - https://muri.network/@Karin_Official@duk.space/111012571141664014
![image](https://github.com/mastodon/mastodon/assets/205521/bd6b97ef-e94f-4949-8dbe-55f05c07f58e)

### Expected behaviour

hashtag exposed.

### Actual behaviour

hashtag not exposed.

### Detailed description

  The hashtag is used at the very bottom of the original post and is delivered correctly to other servers. It is delivered to the subscriber's home timeline.
  However, when users on other servers view the post, the hashtag is not exposed.

### Mastodon instance

mastodon.social
netsphere.one
muri.network

### Mastodon version

v4.2.0-nightly.2023-09-04
v4.2.0-beta3

### Browser name and version

Google Chrome 116.0.5845.141 & Microsoft Edge 116.0.1938.69

### Operating system

Microsoft Windows 22H2 22621.2215

**Comment by jsobralgitpush** [comment]
Can i work on this issue?

**Comment by ClearlyClaire** [comment]
> Can i work on this issue?

Sorry, just noticed this! I've just managed to figure out the cause, so if you still want to help, you can help by reviewing #26960!
