### ISSUE TITLE
Non-interactive posts are not searchable in Asian languages

### ISSUE THREAD

**Issue by fofwisdom** [mastodon/mastodon#26792]
### Steps to reproduce the problem

1. v4.2.0-beta3 upgrade
2. Search for text in uninteracted posts written in Korean using hashtags
...

### Expected behaviour

Posts found

### Actual behaviour

All posts written in Korean are not found

### Mastodon instance

netsphere.one

### Mastodon version

v4.2.0-beta3

### Browser name and version

Chrome 116.0.5845.163

### Operating system

Android 13

**Comment by Gargron** [comment]
Can you provide an example post text and example search query?

**Comment by fofwisdom** [comment]
I apologize for the inconvenience. This is a false positive, This was an issue with stemming in ElasticSearch.
please close this case.
