### ISSUE TITLE
Separate "public status search" from the user-token-required "personal search"

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#26806]
### Pitch

Use a new API and separate UI for the new "public status search" upcoming in Mastodon 4.2 -- something like `GET /api/v1/search/public` or `GET /api/v1/statuses/public`.  The public status index can be served without a token, while the personal search would require a user token.

### Motivation

The two features are both nominally "search", but they actually diverge quite a bit in user expectations and use cases. Using mastodon.social with the search patch rolled out for the 4.2 prerelease is an extremely frustrating experience. I am sure that a lot of people want and appreciate the widened scope of a "public status index", but I am increasingly convinced that this should be separate functionality. Having to add a clunky parameter like in:inbox or scope:classic to every single search is a bad experience, and this should instead be presented as at *least* a checkbox, and on the backend it should be a separate API route.

**Comment by Gargron** [comment]
You can choose your personal index with `in:library`. It makes no sense for them to be separate APIs. I could imagine it being a UI option on the pop-out like Reddit's search all vs search current subreddit.

**Comment by trwnh** [comment]
> You can choose your personal index with in:library

Either this hasn't been merged, hasn't been deployed, doesn't work as expected, or there's a larger issue with the whole search system now. I'm inclined to believe it's the last of these, because I can't even get results for `from:trwnh` or `from:me` or `from:trwnh@mastodon.social` or any variant, for things I know I've posted. (My account is not marked `indexable`, for reference.)

**Comment by Gargron** [comment]
I don't believe it's been deployed yet.
