### ISSUE TITLE
Setting couldn't be open in 4.2.0 beta 3

### ISSUE THREAD

**Issue by ttrace** [mastodon/mastodon#26809]
### Steps to reproduce the problem

1. open user setting from WebUI https://ostatus.taiyolab.com/settings/preferences/appearance
2. Something Wrong error image returns

### Expected behaviour

opening setting interface

### Actual behaviour

Something Wrong error image returns

### Detailed description

because admin_software_updates_path is not defined, software_updates can't be rendered.

### Mastodon instance

ostatus.taiyolab.com

### Mastodon version

v4.2.0 beta 3

### Browser name and version

All

### Operating system

All

### Technical details

because admin_software_updates_path is not defined, software_updates can't be rendered.
I commented out config/navigation.rb:7

**Comment by renchap** [comment]
Did you run the migrations and restart your processes after updating to beta3?

**Comment by ClearlyClaire** [comment]
`admin_software_updates_path` should be defined by the `resources :software_updates, only: [:index]` line in `config/routes/admin.rb`. Do you have local changes, by any chance?

**Comment by ttrace** [comment]
Thanks,I did migration and restarting, checking no-changes around admin.rb.  
But I take same error occurs.

Sep 06 09:34:14 ip-172-31-8-84 bundle[1039656]: [3f13aa5c-9d2e-43af-8043-d8f6d8ac7203] ActionView::Template::Error (undefined local variable or method `admin_software_updates_path' for #<ActionView::Base:0x0000000003f7c8>):
Sep 06 09:34:14 ip-172-31-8-84 bundle[1039656]: [3f13aa5c-9d2e-43af-8043-d8f6d8ac7203]     20:               = fa_icon 'bars'
Sep 06 09:34:14 ip-172-31-8-84 bundle[1039656]: [3f13aa5c-9d2e-43af-8043-d8f6d8ac7203]     21:               = fa_icon 'times'
Sep 06 09:34:14 ip-172-31-8-84 bundle[1039656]: [3f13aa5c-9d2e-43af-8043-d8f6d8ac7203]     22:
Sep 06 09:34:14 ip-172-31-8-84 bundle[1039656]: [3f13aa5c-9d2e-43af-8043-d8f6d8ac7203]     23:           = render_navigation
Sep 06 09:34:14 ip-172-31-8-84 bundle[1039656]: [3f13aa5c-9d2e-43af-8043-d8f6d8ac7203]     24:
Sep 06 09:34:14 ip-172-31-8-84 bundle[1039656]: [3f13aa5c-9d2e-43af-8043-d8f6d8ac7203]     25:     .content-wrapper
Sep 06 09:34:14 ip-172-31-8-84 bundle[1039656]: [3f13aa5c-9d2e-43af-8043-d8f6d8ac7203]     26:       .content
Sep 06 09:34:14 ip-172-31-8-84 bundle[1039656]: [3f13aa5c-9d2e-43af-8043-d8f6d8ac7203]
Sep 06 09:34:14 ip-172-31-8-84 bundle[1039656]: [3f13aa5c-9d2e-43af-8043-d8f6d8ac7203] (eval):7:in `block (2 levels) in eval_config'
Sep 06 09:34:14 ip-172-31-8-84 bundle[1039656]: [3f13aa5c-9d2e-43af-8043-d8f6d8ac7203] (eval):4:in `block in eval_config'
Sep 06 09:34:14 ip-172-31-8-84 bundle[1039656]: [3f13aa5c-9d2e-43af-8043-d8f6d8ac7203] (eval):3:in `eval_config'
Sep 06 09:34:14 ip-172-31-8-84 bundle[1039656]: [3f13aa5c-9d2e-43af-8043-d8f6d8ac7203] app/views/layouts/admin.html.haml:23
Sep 06 09:34:14 ip-172-31-8-84 bundle[1039656]: [3f13aa5c-9d2e-43af-8043-d8f6d8ac7203] app/views/layouts/admin.html.haml:6
Sep 06 09:34:14 ip-172-31-8-84 bundle[1039656]: [3f13aa5c-9d2e-43af-8043-d8f6d8ac7203] app/controllers/concerns/localized.rb:11:in `set_locale'
Sep 06 09:34:14 ip-172-31-8-84 bundle[1039656]: [3f13aa5c-9d2e-43af-8043-d8f6d8ac7203] lib/mastodon/rack_middleware.rb:9:in `call'
Sep 06 09:34:14 ip-172-31-8-84 bundle[1039656]: [3f13aa5c-9d2e-43af-8043-d8f6d8ac7203] lib/public_file_server_middleware.rb:18:in `call'

**Comment by ClearlyClaire** [comment]
What's the output of `git diff v4.2.0-beta3`?

**Comment by ttrace** [comment]
thanks. I found diff it was too many. I've left so far from v4.2.0-beta3. I'm going to merge again.
