### ISSUE TITLE
The account_id parameter of the search API is not supported

### ISSUE THREAD

**Issue by noellabo** [mastodon/mastodon#26837]
### Steps to reproduce the problem

Call the search API with an account_id parameter.

### Expected behaviour

`/api/v2/search` supports `account_id` parameter

### Actual behaviour

It seems that the `/api/v2/search` `account_id` parameter is no longer supported since v4.2 beta 3.

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.0-nightly.2023-09-06

**Comment by Gargron** [comment]
Hm, I thought these params were undocumented, but I guess I was wrong. How widespread is the usage? `from:`, `before:` and `after:` can be used in the query text instead of `account_id`, `max_id` and `min_id`.

**Comment by noellabo** [comment]
There may not have been any client applications that were actually used, but v3/search is required if you want to make destructive changes to public specifications.

How about passing the initial value of the flag to SearchQueryTransformer to maintain compatibility?
