### ISSUE TITLE
When OMNIAUTH_ONLY=true the web interface stuck and cannot log in v4.2.0

### ISSUE THREAD

**Issue by MFYDev** [mastodon/mastodon#26849]
### Steps to reproduce the problem

1. Use the latest nightly docker image
2. In the env, set `OMNIAUTH_ONLY=true` because I am using OIDC login and it works well
3. Run `docker compose up -d` and you will see that you stuck on the page you are in
4. The problem never happens on 4.1.7 or earlier version

### Expected behaviour

It should not be stuck and when you click log in you will be able to see the login page with a single button log in with the OAuth

### Actual behaviour

It will stuck on the page

### Mastodon instance

mfy.social

### Mastodon version

v4.2.0 Nightly

### Browser name and version

Edge Latest

### Operating system

macOS 13.5.1

### Technical details

https://github.com/mastodon/mastodon/blob/81caafbe84240bfb730f5001b33add97ebcbe9dc/spec/requests/content_security_policy_spec.rb#L20

I checked the detailed log and browser's console log, seems like this line is causing the problem? I am just guessing

**Comment by ClearlyClaire** [comment]
What do you mean by “you stuck on the page you are in”? Can you provide more details? Which part of the flow is it stuck on? What's in the browser's console log?

**Comment by MFYDev** [comment]
Hi @ClearlyClaire , thank you for the reply and let me give you more details:
1. The page I am in means that: I set the env without OMNIAUTH_ONLY=true firstly and Mastodon worked fine. I logged in and view some pages and all are functional.
2. After I added OMNIAUTH_ONLY=true to the env and recreate the container, this problem will happen, I cannot neither log in nor log out
![image](https://github.com/mastodon/mastodon/assets/53750381/9d6ff69e-2a85-4d78-b717-b70a72addd19)
The log in button will become like this:
![image](https://github.com/mastodon/mastodon/assets/53750381/8a1134ef-a941-459a-abce-7b341c223543)
And when I click the button I will get this error in browser's console log 
![image](https://github.com/mastodon/mastodon/assets/53750381/8413c799-5ade-494f-b167-6db610866056)
```
Refused to send form data to 'https://mastodondomain/auth/auth/openid_connect' because it violates the following Content Security Policy directive: "form-action 'self'".
```

**Comment by MFYDev** [comment]
This problem only happens in the nightly image for version 4.2.0, I tried to do the same thing and use the latest tag for the image which is the version 4.1.7, it works fine without any issues. So this is weird. As https://github.com/mastodon/mastodon/blob/81caafbe84240bfb730f5001b33add97ebcbe9dc/spec/requests/content_security_policy_spec.rb#L20 This commit was done two month ago, which should influence both the version. I am not familiar with Mastodon's source code, this is just my guess

**Comment by ClearlyClaire** [comment]
> `Refused to send form data to 'https://mastodondomain/auth/auth/openid_connect' because it violates the following Content Security Policy directive: "form-action 'self'".`

Is that a *different* domain? It sounds like it shouldn't be.

`form-action 'self'` is involved, yes, but it's only part of the issue; there was an interstitial page before #26083

**Comment by MFYDev** [comment]
It is the same domain for sure, which is mfy.social same as the main domain

**Comment by MFYDev** [comment]
> form-action 'self' is involved, yes, but it's only part of the issue; there was an interstitial page before https://github.com/mastodon/mastodon/pull/26083

Yeah you are right, this issue must have something related to this PR

**Comment by ClearlyClaire** [comment]
oh, right, this does a `POST` to `https://mfy.social/auth/auth/openid_connect` which is a fine first step, but then that page does a 302 to an external domain, which is allowed by certain browsers and blocked by other browsers

cc @CSDUMMI

**Comment by CSDUMMI** [comment]
Sorry, I forgot to include this in the PR I made introducing the single-step login with 'OMINAUTH_ONLY=true'. 

The way I solved this before was by adding another env variable `SSO_HOST` with the domain of the SSO provider used. 

But I think a better solution would be to extract the domain from the configuration variable used, such as `OIDC_ISSUER`.

I can make a PR with a bug fix for that.

**Comment by MFYDev** [comment]
@ClearlyClaire @CSDUMMI Thank you so much for confirming this!
