### ISSUE TITLE
Admin role can create invite link despite missing permission

### ISSUE THREAD

**Issue by kidhab** [mastodon/mastodon#26851]
### Steps to reproduce the problem

1. By default the "Admin" role don't have the permission called "Invite Users" (screenshot 1)
2. Login with an account that belongs to the "Admin" role
3. Got to `/invites`
4. Button "Generate Invite Link" is present and working

### Expected behaviour

Without the permission the button should not be present.

### Actual behaviour

Admin role can create invite links without permission

### Detailed description

I'm not sure what is causing this behaviour. We have tested this with two identical and newly created Mastodon instances. By default on both instances the "Admin" role don't have the permission to create invite links.

The described problem only occurs one instance.

We run both instances via docker compose and didn't configure anything despite some admin accounts.

![Bildschirmfoto vom 2023-09-08 11-24-51](https://github.com/mastodon/mastodon/assets/32387157/cbbfdbaf-3916-45e2-ad28-1b528e9c988f)
![Bildschirmfoto vom 2023-09-08 11-24-13](https://github.com/mastodon/mastodon/assets/32387157/ff6cc3d7-d523-4195-b183-6bca23b50daf)

### Mastodon instance

the instances are not public available

### Mastodon version

v4.1.7

### Browser name and version

102.15.0esr

### Operating system

Debian 12

**Comment by ClearlyClaire** [comment]
There are two invite-related permissions, one labelled “Invite users” and one under moderation that is called “Manage invites”. Are you sure you are not confusing these? Additionally, all users inherit from the default permissions. Do the default permissions include the right to invite users?

**Comment by kidhab** [comment]
> There are two invite-related permissions, one labelled “Invite users” and one under moderation that is called “Manage invites”. Are you sure you are not confusing these?

Can you point me in the right direction - where exactly do I find the permission under "moderation"? I can't find it at my test instances.


> Additionally, all users inherit from the default permissions. Do the default permissions include the right to invite users?

I looks like the invite permission is not a default permission.


I hope I am mixing something up but I didn't touch the permissions or anything else. This behaviour occured at two identical and freshly created Mastodon instances (via docker compose).

**Comment by ClearlyClaire** [comment]
> Can you point me in the right direction - where exactly do I find the permission under "moderation"? I can't find it at my test instances.

It's the last item in the “moderation” section, and it's one of the permissions for the default “Admin” roles:
![image](https://github.com/mastodon/mastodon/assets/384364/29ead587-f121-49e8-89d9-619b0ef8b528)

> I looks like the invite permission is not a default permission.

It is one of the default permissions. You can edit them at `/admin/roles/-99/edit`:
![image](https://github.com/mastodon/mastodon/assets/384364/185f04f3-9a42-4575-8b93-4a11ad9a2a90)
![image](https://github.com/mastodon/mastodon/assets/384364/f3c24fd5-8de8-4e2e-9133-71b114b81329)

**Comment by kidhab** [comment]
Thanks for your very helpful comments and screenshots. I really appreciate it.

With your help I figured out that this was indeed a configuration error on one of the two instances.

Therefore: Sorry for the noise.

**Comment by ClearlyClaire** [comment]
> Therefore: Sorry for the noise.

No problem! If anything, this lets us know this part of the interface is not clear enough!
