### ISSUE TITLE
"Unlisted" posts literally listed(!) for all profile visitors

### ISSUE THREAD

**Issue by ell1e** [mastodon/mastodon#26864]
### Steps to reproduce the problem

1. Post something as "unlisted"
2. Go to your profile, click on "Posts" while **logged out** (since being logged in would be the only acceptable reason for it to still show up then)
3. It's literally listed

### Expected behaviour

Unlisted posts only show up on my profile for myself when logged in, and nobody else since the literal point is that they aren't listed

### Actual behaviour

Unlisted posts are trivially and openly listed on profile

### Detailed description

I suggest this is possibly a bigger security problem, since this just doesn't seem to match at all what the name suggests and therefore puts posters using this at high risk. I think 99% of all people coming from any other platform will assume "unlisted" means if you have the post's url you can read it without password or login, but otherwise it won't be listed anywhere which simply doesn't seem to be true.

### Mastodon instance

mastodon.social

### Mastodon version

 v4.2.0

### Browser name and version

Firefox 118.0b3

### Operating system

openSUSE Leap

**Comment by Gargron** [comment]
Unlisted is the same as public but opted-out of discovery features like the live feeds.

![image](https://github.com/mastodon/mastodon/assets/184731/0e57b481-6823-4fa7-b8e6-6e68d13e288d)

**Comment by ell1e** [comment]
I'm not sure how the text is supposed to make that clear for newcomers. I thought "discovery, ah, so just all ways to discover it via listings", and isn't that also how Youtube does unlisted videos? I haven't ever seen any platform do it differently, which is why this seems jarring.

I also don't quite get the in-between that you're suggesting this is. If I want followers to see it, then probably I would want it to be in the live feed, right? Otherwise, I probably only want people who actually are poked directly at it to see it, or what's the point of still having it on my profile? I don't understand the use case of that.

**Comment by brawaru** [comment]
From the conversations I've seen around here it seems that Gargron and others are well aware that the current terms — and this visibility setting in particular — are problematic. All it does is prevents the post from showing in search and live feeds, but it doesn't affect the post visibility to others in any way. There's a reason it's absent from the mobile apps from the start. It's probably going to be changed or removed altogether, but @Gargron is welcome to correct me on this one.

**Comment by ell1e** [comment]
I think that it doesn't affect visibility for those who know the link is expected. But that "Unlisted" still has it listed in other places than when I have that direct link to it (or to whatever is a response to) is so weird. I would find it useful for cases like the one I described in the comment above, if it actually were as unlisted as I had thought.

**Comment by trwnh** [comment]
there is a major point of confusion in that "unlisted" on youtube/etc means "available only via direct url", but in this case it just means "opted out of discovery features". imo, what is "unlisted" should actually be called "public", and what is currently "public" should be called "discoverable".

see also:

- #21245
- #21645 (this one literally asks for inverse functionality)
- #23038 (this one too)

it has parallels to the confusion around "mentions only" scope which has previously been called "direct messages" (incorrectly) and is currently called "private mentions" (which is discussed in #24837 and other issues)

**Comment by brendanjones** [comment]
Huh, I wasn’t aware unlisted could be misunderstood in this way. That’s not a dig, unlisted is extremely confusing and needs changes (see my comments on https://github.com/mastodon/mastodon/issues/23038#issuecomment-1697433132). It’s just a different way of interpreting the term that hasn’t occurred to me, presumably because I’m not familiar with the quoted examples of how it’s used on other platforms, like how it’s used on YouTube.  

To me, your profile isn’t a list, and it’s not a discovery feature, so I’d never expect unlisted posts to not show up on my profile.

**Comment by ell1e** [comment]
Maybe it's really just me, but I would assume most people would consider your public profile also a discovery feature. Apart from whether they do or not, for practical reasons and real world use cases, I think this feature would be way more useful if it was actually also not listed on the profile like I explained above.

**Comment by trwnh** [comment]
"Unlisted" has been renamed to "Quiet public" in the latest commits. There is also a tooltip that explains exactly where it will not show up.
