### ISSUE TITLE
Search requests should be stored in a query string

### ISSUE THREAD

**Issue by edent** [mastodon/mastodon#26868]
### Pitch

I'd like to be able to share the URl of a search - for example https://mastodon.social/search?q=mastodon%20fediverse

(Longer term, I'd like to be able to save search requests the same way I save hashtag searches, but this would be a great intermediate step.)

### Motivation

Twitter allows me to share a search in a GET request.  For example https://twitter.com/search?q=mastodon%20fediverse

This would be a useful way to be able to share search results with other users - whether they're logged in or not.

**Comment by pbsds** [comment]
This would also allow you to register your own mastodon instance as a search engine in the browser, massively speeding up finding and following users on other instances

**Comment by renchap** [comment]
This is planned, probably for 4.3 :)

**Comment by sarajw** [comment]
Just adding my wish for this, it definitely feels like it's missing! In this instance I'd like to share all the posts I livetooted during a conference, based on being from me and having a certain hashtag.

**Comment by mprove** [comment]
Supporting search queries would also add a little bit more of social knowledge building to the platform. It is a reward for using tags wisely, rather than toot and forget.

**Comment by edent** [comment]
Just wondering if there was any update to this suggestion?

BlueSky has this, for example, https://bsky.app/search?q=mastodon

But this doesn't work https://mastodon.social/search?q=bluesky

**Comment by renchap** [comment]
There is an up-for-grab issue about this: https://github.com/mastodon/mastodon/issues/29991

Unfortunately I did not have time to work on it, and nobody offered to have a go at it, but I will help anyone wanting to change this :)

**Comment by pbsds** [comment]
does this project have a "good-first-issue" label?

**Comment by renchap** [comment]
Yes it does
