### ISSUE TITLE
Docker Build failds: `Could not load OpenSSL`

### ISSUE THREAD

**Issue by CSDUMMI** [mastodon/mastodon#26888]
### Steps to reproduce the problem

1. `git checkout main`
2. `docker compose build --progress plain`
3. Canceled with error:
```
#20 27.04 Bundler 2.4.10 is running, but your lockfile was generated with 2.4.13. Installing Bundler 2.4.13 and restarting using that version.
#20 27.21 There was an error installing the locked bundler version (2.4.13), rerun with the `--verbose` flag for more details. Going on using bundler 2.4.10.
#20 27.29 Could not load OpenSSL.
#20 27.29 You must recompile Ruby with OpenSSL support.
#20 ERROR: process "/bin/bash -o pipefail -c apt-get update &&     apt-get install -y --no-install-recommends build-essential         git         libicu-dev         libidn-dev         libpq-dev         libjemalloc-dev         zlib1g-dev         libgdbm-dev         libgmp-dev         libssl-dev         libyaml-0-2         ca-certificates         libreadline8         python3         shared-mime-info &&     bundle config set --local deployment 'true' &&     bundle config set --local without 'development test' &&     bundle config set silence_root_warning true &&     bundle install -j\"$(nproc)\" &&     yarn install --pure-lockfile --production --network-timeout 600000 &&     yarn cache clean" did not complete successfully: exit code: 17
```

### Expected behaviour

Build succeeds

### Actual behaviour

Build fails

### Mastodon version

main

**Comment by Ameobea** [comment]
Hitting this as well when trying to upgrade to the 4.2.0 release.

I'm using `docker-compose` and an otherwise clean install.  Maybe I have some kind of Docker cache for one of the involved images which is causing this build to break there, idk.

**Comment by Ameobea** [comment]
I bisected this build issue to commit https://github.com/mastodon/mastodon/commit/b749de766f5a6158fd0b5f3c3201943083fc7979 which bumps the tag of the Docker `node` image from Debian bullseye to bookworm.

I dug into this further.  I tried to repro the build failure on my desktop, but it works there; it only fails when building on the server on which I run my Mastodon instance.

**After more investigation, I found that the hashes of the `ruby-jemalloc` image used by the build process are different between the server and my local desktop**

Server:

```
[
    {
        "Id": "sha256:c9d180a360e5d39e463cbb202eb10bc4e6d44af3f6ba53fbd26874027aea9ec9",
        "RepoTags": [
            "ghcr.io/moritzheiber/ruby-jemalloc:3.2.2-slim"
        ],
        "RepoDigests": [
            "ghcr.io/moritzheiber/ruby-jemalloc@sha256:9f452d67da4ffdc9abc103015ca447f442d324946a78cefcea9d35f558ce9a93"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2023-06-05T07:47:27.743594335Z",
```

Desktop:

```
[
    {
        "Id": "sha256:6bebe65ca9cf60a9d55145104943af2493c46a593c36d9ada11f0940db7a280e",
        "RepoTags": [
            "ghcr.io/moritzheiber/ruby-jemalloc:3.2.2-slim"
        ],
        "RepoDigests": [
            "ghcr.io/moritzheiber/ruby-jemalloc@sha256:9a1487af836fada451d706b4b9b4f17a42e82cab5bcef1d77cb577134473f9a6"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2023-09-18T09:01:47.627305986Z",
```

My guess is that whoever maintains that `ruby-jemalloc` image force-pushed a new version of the package to the same tag.  My server has the old version cached, and my desktop picked up the new one.

I ran `docker image rm ghcr.io/moritzheiber/ruby-jemalloc:3.2.2-slim` on the server.  This cleared out that old stale `ruby-jemalloc` image, re-fetched the new one, and fixed my build.

So yeah - there's a workaround for that @NahNick and @CSDUMMI.  The issue isn't technically on mastodon's side, and it should go away the next time they upgrade their ruby version (as long as the `ruby-jemalloc` maintainer doesn't do this again in the future).
