### ISSUE TITLE
Hide register button when OMNIAUTH_ONLY is true

### ISSUE THREAD

**Issue by rasos** [mastodon/mastodon#26919]
### Steps to reproduce the problem

We run a Mastodon instance with Keycloak and let the users register outside of Mastodon. Still, there is a register button, which we can not hide. 

### Expected behaviour

When we allow users to login only via OIDC, we do not want to show any Register button, text or password reset text.  When a user clicks on the register button, it is non-functional.

### Actual behaviour

Register button, text or password reset text are shown.

### Detailed description

When we have set

```
OIDC_ENABLED: "true"
OMNIAUTH_ONLY: "true"
```

any register button, text or password reset text should not be shown.

### Mastodon instance

fairmove.net

### Mastodon version

v4.1.6

### Browser name and version

Firefox 117

### Operating system

Xubuntu

related to #20672, similar but more detailed than #21748

**Comment by ClearlyClaire** [comment]
I believe this will be addressed by the `ONE_CLICK_SSO_LOGIN` environment variable in the upcoming 4.2.0 version!

See https://github.com/mastodon/mastodon/pull/26083 https://github.com/mastodon/mastodon/pull/26857

**Comment by rasos** [comment]
Wonderful, this now works on 4.2.0 as expected when offering login and registration with SSO with 

```
  OMNIAUTH_ONLY: "true"
  ONE_CLICK_SSO_LOGIN: "true"
```
