### ISSUE TITLE
Unable to set a specific time zone

### ISSUE THREAD

**Issue by Izorkin** [mastodon/mastodon#26925]
### Steps to reproduce the problem

1. Set time zone to "(GMT+03:00 ) Moscow" in interface settings.

### Expected behaviour

A time zone will be set up Moscow

### Actual behaviour

Time zone will be set St. Petersburg

### Mastodon version

v4.2.0-rc1

### Browser name and version

Vivaldi

### Operating system

Windows 10

**Comment by ClearlyClaire** [comment]
The dropdown contains many aliases for the same underlying timezones, which is the case here.

https://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html#method-c-all

> There are multiple [TimeZone](https://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html) objects per time zone, in many cases, to make it easier for users to find their own time zone.

**Comment by Izorkin** [comment]
This does not happen with other cities in same GMT+03:00.

**Comment by ClearlyClaire** [comment]
> This does not happen with other cities in same GMT+03:00.

That's true, but it occurs for other timezones still, e.g. Osaka, Sapporo and Tokyo are the same timezone internally.

**Comment by Izorkin** [comment]
In that case, if set Yakutsk, it should save as Tokyo, as it does with Osaka, Sapporo. Or is there a gradation by country?

**Comment by ClearlyClaire** [comment]
> In that case, if set Yakutsk, it should save as Tokyo, as it does with Osaka, Sapporo. Or is there a gradation by country?

Multiple timezones share the same offset at a point in time, and multiple dropdown entires share a same timezone.
