### ISSUE TITLE
http: invalid Host header at db:migrate update v4.1.7 to v4.2.0-rc1 using docker

### ISSUE THREAD

**Issue by jfrede** [mastodon/mastodon#26928]
### Steps to reproduce the problem

1. stop mastodon docker containers mastodon-web-1 mastodon-streaming-1 mastodon-sidekiq-1
2. change docker-compose.yml to version v4.2.0-rc1
3. docker-compose run --rm -e SKIP_POST_DEPLOYMENT_MIGRATIONS=true web bundle exec rails db:migrate

### Expected behaviour

do the database migration

### Actual behaviour

output "http: invalid Host header" after 10 seconds

### Detailed description

tried to update to v4.2.0-rc1 at update i got the error. 

docker-compose run --rm -e SKIP_POST_DEPLOYMENT_MIGRATIONS=true web bundle exec rails db:migrate
[+] Running 4/0
 ✔ Container mastodon-es-1              Running                   0.0s 
 ✔ Container mastodon-db-1              Running                  0.0s 
 ✔ Container mastodon-redis-1           Running                 0.0s 
 ✔ Container mastodon-libretranslate-1  Running           0.0s 
http: invalid Host header

### Mastodon instance

https://radiosocial.de/

### Mastodon version

v4.2.0-rc1

### Technical details

If this is happening on your own Mastodon server, please fill out those:
Docker Compose version 2.17.3
postgres:15
redis:7
elasticsearch:8.9.2
tootsuite/mastodon:v4.2.0-rc1

**Comment by renchap** [comment]
Can you try to not start es/libretranslate when running your migrations?

You should not stop your redis/db when upgrading Mastodon, this is not needed.

So, start them back: `docker-compose up db redis`

Then run the migrations, without starting the other containers: `docker-compose run --no-deps --rm -e SKIP_POST_DEPLOYMENT_MIGRATIONS=true web bundle exec rails db:migrate`

You can also try to start ES & libre translate independently, then running the migration.

**Comment by jfrede** [comment]
At the moment I'm rolling back a full backup because i got some strange problems after restarting the v4.1.7 containers. 
Next try I'll snapshot db and es independently.

**Comment by jfrede** [comment]
sry wrong button.

**Comment by jfrede** [comment]
Still the same result. 

docker-compose down

docker-compose up -d db redis
[+] Running 2/2
 ✔ Container mastodon-redis-1  Started                                      0.3s 
 ✔ Container mastodon-db-1     Started                                       0.4s 

docker-compose run --no-deps --rm -e SKIP_POST_DEPLOYMENT_MIGRATIONS=true web bundle exec rails db:migrate
http: invalid Host header

**Comment by jfrede** [comment]
Solved the Problem it was not Mastodon it was docker-compose in OpenSUSE.
Updated to the latest version from the Factory release and everything works now. 

Docker Compose version 2.21.0 is working

Kind Regards,
Joerg
