### ISSUE TITLE
v4.2.0 failing to install with npm dependency error

### ISSUE THREAD

**Issue by alsutton** [mastodon/mastodon#27020]
### Steps to reproduce the problem

Following the upgrade instructions, when I reach the `yarn install --frozen-lockfile` step I get the following error;

```
➤ YN0061: │ source-map-url@npm:0.4.1 is deprecated: See https://github.com/lydell/source-map-url#deprecated
➤ YN0060: │ @mastodon/mastodon@workspace:. provides react (paab8a) with version 18.2.0, which doesn't satisfy what emoji-mart-lazyload requests
➤ YN0060: │ @mastodon/mastodon@workspace:. provides react (p169d8) with version 18.2.0, which doesn't satisfy what react-motion requests
➤ YN0060: │ @mastodon/mastodon@workspace:. provides react (pf0721) with version 18.2.0, which doesn't satisfy what react-notification requests
➤ YN0060: │ @mastodon/mastodon@workspace:. provides react (pf1db3) with version 18.2.0, which doesn't satisfy what react-router-scroll-4 requests
➤ YN0060: │ @mastodon/mastodon@workspace:. provides react (padeee) with version 18.2.0, which doesn't satisfy what react-swipeable-views requests
➤ YN0060: │ @mastodon/mastodon@workspace:. provides react-dom (p6df7f) with version 18.2.0, which doesn't satisfy what react-router-scroll-4 requests
➤ YN0002: │ @types/react-overlays@npm:3.1.0 doesn't provide react (p8a3da), requested by react-overlays
➤ YN0002: │ @types/react-overlays@npm:3.1.0 doesn't provide react-dom (p3824c), requested by react-overlays
➤ YN0002: │ @types/react-select@npm:5.0.1 doesn't provide react (p53bc3), requested by react-select
➤ YN0002: │ @types/react-select@npm:5.0.1 doesn't provide react-dom (p18d87), requested by react-select
➤ YN0002: │ @types/react-textarea-autosize@npm:8.0.0 doesn't provide react (p4b202), requested by react-textarea-autosize
➤ YN0002: │ react-swipeable-views-utils@npm:0.14.0 doesn't provide react (p74d53), requested by react-event-listener
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 22s 553ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 22s 708ms
```

Re-trying to run yarn results in the same error

### Expected behaviour

Clean upgrade

### Actual behaviour

Upgrade can not be upgraded due to a dependency error

### Detailed description

Node version;

ii  nodejs                            16.20.2-deb-1nodesource1       arm64        Node.js event-based server-side javascript engine

### Mastodon instance

snapp.social

### Mastodon version

v4.1.8 trying to go to v4.2.0

### Technical details

```
mastodon@ip-172-30-2-166:~/live$ ruby --version
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [aarch64-linux]
mastodon@ip-172-30-2-166:~/live$ node --version
v16.20.2
mastodon@ip-172-30-2-166:~/live$
```

**Comment by ClearlyClaire** [comment]
That is a little surprising, do you have any local change?

**Comment by alsutton** [comment]
Not that I'm aware of. git status showed no changed files in the checkout.

**Comment by ClearlyClaire** [comment]
And without the flag, it installs fine? Still no change, even to yarn.lock?

**Comment by alsutton** [comment]
It installs fine without the flag, yarn.lock seems to have been pretty much rewritten so there's a lot of churn in git diff.

[yarn.lock.txt](https://github.com/mastodon/mastodon/files/12689521/yarn.lock.txt)

**Comment by renchap** [comment]
You seem to be using Yarn 3. Mastodon 4.2.0 requires Yarn 1.

**Comment by edmondburnett** [comment]
Encountered a similar problem here, except it hangs forever after reaching the line `Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code`. Waited 3 hours since the processes seemed to be busy, but it made no progress in that time. 

I aborted it with CTRL-C and ran it again without `--frozen-lockfile` and it completed successfully in less than a minute.

**Comment by alsutton** [comment]
We do have yarn 3, which is the current stable release, installed;

```
mastodon@ip-172-31-22-143:~$ yarn --version
3.5.0
```

Is there a plan to upgrade to the latest stable release? v1.x doesn't seem to be getting updates any more, so we have a concern about installing and running software which is no longer supported on our servers

**Comment by dj-sf** [comment]
I'm also having issues with emoji-mart and React 18.  It seems that the emoji-mart package listed in the package.json does not have React 18 listed as a peer dependency... only React 17.  this particular version of emoji-mart ([emoji-mart-lazyload](https://github.com/mashirozx/emoji-mart)) is a fork of the official one and has not been updated since 2021.

```
npm i -S @inrupt/solid-ui-react
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @mastodon/mastodon@undefined
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0-0 || ^16.0.0 || ^17.0.0" from emoji-mart@3.0.1-j
npm ERR! node_modules/emoji-mart
npm ERR!   emoji-mart@"npm:emoji-mart-lazyload@latest" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/vscode/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vscode/.npm/_logs/2023-09-22T04_26_09_163Z-debug-0.log
```

I get the feeling that it's not a problem with yarn and rather just an issue with mastodon using a very out-of-date package.  I think we should look into either updating or replacing it.

**Comment by dj-sf** [comment]
actually I think i might be having a separate issue but the emoji-mart tie in may have been a coincidence.

**Comment by alsutton** [comment]
@dj-sf Your symptoms are very similar to mine. Are you running yarn 3 (check via `yarn --version`), if so can you downgrade to yarn 1 (which I was able to do via `npm install --global --force yarn` and see if the error persists.

**Comment by dj-sf** [comment]
when I run `yarn --version` I get 1.22.19, so I think I have the correct yarn version.

**Comment by dj-sf** [comment]
there is another issue open that is more closely related to the emoji-mart fork problem ( #18609 )

**Comment by renchap** [comment]
> Is there a plan to upgrade to the latest stable release? It [seems the be something that's recommended by the yarn team](https://yarnpkg.com/migration/overview), and v1.x doesn't seem to be getting updates any more, so we have a concern about installing and running software which is no longer supported on our servers

@alsutton Yes this is planned, but not for 4.2. You need yarn 1 installed for Mastodon 4.2 and below.

> I'm also having issues with emoji-mart and React 18. It seems that the emoji-mart package listed in the package.json does not have React 18 listed as a peer dependency... only React 17. this particular version of emoji-mart ([emoji-mart-lazyload](https://github.com/mashirozx/emoji-mart)) is a fork of the official one and has not been updated since 2021.
> 
> ```
>  npm i -S @inrupt/solid-ui-react
>  …
>  ```

@dj-sf you must use `yarn` to manage the project dependencies, not `npm` as you are doing in your example.

**Comment by dj-sf** [comment]
@renchap thanks, I'll give that a try next before I get too deep into the dependency upgrades.  

On a side note, why are we using both Yarn and npm in Mastodon?  

Also, could we add something to the documentation to specify that we should use yarn and not npm?

**Comment by dj-sf** [comment]
Installing using yarn fixed my issue. Also:

> On a side note, why are we using both Yarn and npm in Mastodon?  

^ Disregard this lol I didn't understand how yarn works.
