### ISSUE TITLE
New hashtag display does not work with Hashtags  in non-Latin scripts

### ISSUE THREAD

**Issue by gunchleoc** [mastodon/mastodon#27028]
### Steps to reproduce the problem

1. Write a post with non-Latin hashtags on the bottom, e.g. [#ᎠᏂᏴᏫᏯᎢ](https://mastodon.scot/tags/%E1%8E%A0%E1%8F%82%E1%8F%B4%E1%8F%AB%E1%8F%AF%E1%8E%A2) [#ᏣᎳᎩ](https://mastodon.scot/tags/%E1%8F%A3%E1%8E%B3%E1%8E%A9)#ᏣᎳᎩᎦᏬᏂᎯᏍᏗ [#Cherokee](https://mastodon.scot/tags/Cherokee) [#Хальмг](https://mastodon.scot/tags/%D0%A5%D0%B0%D0%BB%D1%8C%D0%BC%D0%B3) [#ХальмгКелн](https://mastodon.scot/tags/%D0%A5%D0%B0%D0%BB%D1%8C%D0%BC%D0%B3%D0%9A%D0%B5%D0%BB%D0%BD) [#Kalmyk](https://mastodon.scot/tags/Kalmyk) [#Kurmancî](https://mastodon.scot/tags/Kurmanc%C3%AE) [#Kurdî](https://mastodon.scot/tags/Kurd%C3%AE) [#Kurdish](https://mastodon.scot/tags/Kurdish) [#Kurmanji](https://mastodon.scot/tags/Kurmanji) [#简体中文](https://mastodon.scot/tags/%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87) [#繁體中文](https://mastodon.scot/tags/%E7%B9%81%E9%AB%94%E4%B8%AD%E6%96%87) [#繁體中文](https://mastodon.scot/tags/%E7%B9%81%E9%AB%94%E4%B8%AD%E6%96%87) [#廣東話](https://mastodon.scot/tags/%E5%BB%A3%E6%9D%B1%E8%A9%B1) [#Chinese](https://mastodon.scot/tags/Chinese) [#Cantonese](https://mastodon.scot/tags/Cantonese)

### Expected behaviour

Hashtags are reamphasized and after the first few, we see the "... ore" thing

### Actual behaviour

Hashtags are formatted like normal post text

### Detailed description

See post https://mastodon.scot/@gunchleoc/111104415527211771 for an example

![image](https://github.com/mastodon/mastodon/assets/4095570/6394b1f0-c5d8-4bc0-8ad1-5a439ad1a7ea)

I also tested what happens when you add 5 Latin--script hashtags in front - this will not fix it

![image](https://github.com/mastodon/mastodon/assets/4095570/4b69a6e4-6f24-4338-8b67-2ec8cdf38337)

### Mastodon instance

mastodon.scot

### Mastodon version

v4.2.0

### Browser name and version

Firefox 117.0.1

### Operating system

Linux Mint

**Comment by aslakr** [comment]
Is there supposed to be no space in `#ᏣᎳᎩ#ᏣᎳᎩᎦᏬᏂᎯᏍᏗ`, not `#ᏣᎳᎩ #ᏣᎳᎩᎦᏬᏂᎯᏍᏗ` or `#ᏣᎳᎩ_ᏣᎳᎩᎦᏬᏂᎯᏍᏗ`?

**Comment by gunchleoc** [comment]
You're right, that was a typo with a missing blank space in my post. When I add the blank space, the formatting is fixed.
