### ISSUE TITLE
Unable to post animated gif or mp4: "422 Error processing thumbnail for uploaded media"

### ISSUE THREAD

**Issue by annatech** [mastodon/mastodon#27025]
### Steps to reproduce the problem

    1. User clicks on paperclip icon to attach an animated .gif or .mp4 file to a post.
    2. The media item uploads and the post window indicates that it is uploading and then processing
    3. The attached file should appear in the post window, pending publishing.

### Expected behaviour

The attached file should appear in the post window, pending publishing

### Actual behaviour

"422 Error processing thumbnail for uploaded media", file fails to attach

### Detailed description

I discovered and have been trying to resolved for the past couple months a strange issue which prevents users from posting animated gifs to my Mastodon instance.

Current behavior:

    User clicks on paperclip icon to attach an animated gif to a post
    The media item uploads and the post windows indicates that it is uploading and then processing
    After about 28.5 seconds, the upload stalls and throws the following error:
    -- "422 Error processing thumbnail for uploaded media"
    After that, the page needs to be reloaded before the attachment action can work again.

Expected behavior:

    User clicks on paperclip icon to attach an animated gif to a post
    The media item uploads and the post windows indicates that it is uploading and then processing (xhr calls complete successfully)
    A thumbnail of the gif (which has been converted to an .mp4 file in the background) appears and is ready for posting

Investigation:
I noticed that, during this event, Sidekiq reports the following retry action:

    Queue: default
    Job: PostProcessMediaWorker
    Arguments: %id_of_media%
    Error:
    (example)
    Errno::ENOENT: No such file or directory @ rb_sysopen - /opt/mastodon/public/system/media_attachments/files/110/888/339/885/320/433/original/e4b9cc41c743c791.mp4

NOTE:
My instance is configured to work with S3 and CloudFront, deployed via Terraform Cloud.

The processed gif file appears as an mp4, successfully, with the correct S3 directory path.
Example:
/media_attachments/files/110/888/339/885/320/433/original/e4b9cc41c743c791.mp4 

So far, I have been unable to identify WHY Sidekiq fails with a reference to a missing local file, when the instance is otherwise correctly configured to store and serve media via S3 + CloudFront.

### Mastodon instance

https://shotgunlife.social

### Mastodon version

v4.2.0-rc2

### Browser name and version

All Browsers

### Operating system

Any OS

### Technical details

This issue occurs both via the UI and also via POST /api/v2/media. The end result is always the same.

**Comment by renchap** [comment]
It looks like that your Sidekiq process tries to access the files locally and not from your S3 provider. This is most likely caused by your environment variables not being correctly set for your Sidekiq process. This process should use the same environment variables as your web process.

**Comment by annatech** [comment]
> It looks like that your Sidekiq process tries to access the files locally and not from your S3 provider. This is most likely caused by your environment variables not being correctly set for your Sidekiq process. This process should use the same environment variables as your web process.

Very interesting. I was not aware of that. 

One thing to note is that the gif or mp4 file do successfully get written to the associated S3 bucket. The asynchronous POST /api/v2/media call is mostly successful. I suspect Paperclip experiences an issue somewhere in that workflow which defaults to referencing the local storage (in my case, under /opt/mastodon/public/system...) rather than the correct S3 location. 

As a counterpoint, if I upload an animated gif as my profile header, Mastodon uses a non-async method to upload and process the file, resulting in successful processing of the file. I suspect the reason async processing is used for status posts is to improve concurrency and prevent blocking the DOM from other browser events. Maybe.

**Comment by annatech** [comment]
@renchap I am testing your suggestion and I think you might have identified my issue. Let me test this evening to confirm this works.

Thanks!

**Comment by annatech** [comment]
@renchap your suggestion helped me resolve my post-processing error.
