### ISSUE TITLE
ActionView::Template::Error (Webpacker can't find locale/en-json.js in /opt/mastodon/public/packs/manifest.json)

### ISSUE THREAD

**Issue by barberio** [mastodon/mastodon#27031]
### Steps to reproduce the problem

1. Pull and run tootsuite/mastodon:v4.2.0 docker install
3. Test using the web client.
3. Crashes with "ActionView::Template::Error (Webpacker can't find locale/en-json.js in /opt/mastodon/public/packs/manifest.json)" error

### Expected behaviour

Content should be served

### Actual behaviour

No content served.

### Detailed description

Appears to be a spurious or stray dependency not packaged with the docker image?
Work around is to roll back to v4.1. (This suggests it is time to think about having a LTS tagged release instead of just latest release)

### Mastodon version

v4.2.0

### Technical details

Docker Image tagged v4.2.0 digest 0fe0d49c3252

**Comment by stoppableforce** [comment]
This is happening to me in a self-hosted, non-Docker instance as well.

**Comment by renchap** [comment]
The docker image is correct and should work fine, as this is what we are deploying on our own instances.

I suspect your setup is not standard, could you please describe it a bit more?

**Comment by barberio** [comment]
Perfectly ordinary docker-compose set up based on tootsuite images and normal configuration. Nothing special applied.

Please note - With the standard setup, the Webpacker generated assets are stored in the external volume containing the public packs, the docker image *should* be performing an "assets:clobber assets:precompile" if they're out of sync with what Mastodon's current codebase expects. Try testing with an out of sync packs directory?

**Comment by barberio** [comment]
Identified as there being a single volume mount for public having been mistakenly made, hence assets being out of sync. I'm at a loss as to how it worked at all in previous versions!

Perhaps a little better documentation on the mount paths for docker volumes, since on first glance it looks like /opt/mastodon/public is a persistent storage directory, and technically is if you're regenerating assets at boot, but since docker only generates assets that get stored there at build time this causes problems if a user treats it as such.
