### ISSUE TITLE
Link to documentation in Frontend is broken

### ISSUE THREAD

**Issue by Joshix-1** [mastodon/mastodon#27034]
### Steps to reproduce the problem

![image](https://github.com/mastodon/mastodon/assets/57299889/b4887926-eed9-4f23-9dfb-099b429ff61d)
links to
[https://docs.joinmastodon.org/admin/optional/elasticsearch/#scaling](https://docs.joinmastodon.org/admin/optional/elasticsearch/#scaling) (404)

### Expected behaviour

200 Ok

### Actual behaviour

404 Not Found

### Detailed description

Link broken.

### Mastodon instance

fosspri.de

### Mastodon version

v4.2.0

### Browser name and version

N/A

### Operating system

N/A

### Technical details

```sh
$ git grep -n "#scaling"
app/lib/admin/system_check/elasticsearch_check.rb:44:      Admin::SystemCheck::Message.new(:elasticsearch_preset_single_node, nil, 'https://docs.joinmastodon.org/admin/optional/elasticsearch/#scaling')
app/lib/admin/system_check/elasticsearch_check.rb:50:      Admin::SystemCheck::Message.new(:elasticsearch_preset, nil, 'https://docs.joinmastodon.org/admin/optional/elasticsearch/#scaling')
```

**Comment by renchap** [comment]
Thanks.

The correct URL is https://docs.joinmastodon.org/admin/elasticsearch/#scaling, I will add a redirect from the old URL to the new one, and the URL displayed in the admin panel will be fixed in the next version.

**Comment by Joshix-1** [comment]
It doesn't seem like, there is an element with scaling as id. So what does the #scaling in the end do?

**Comment by Joshix-1** [comment]
It doesn't seem like, there is an element with scaling as id. So what does the # scaling in the end do?
