### ISSUE TITLE
Search and Discoverability are not part of onboarding

### ISSUE THREAD

**Issue by pkreissel** [mastodon/mastodon#27033]
### Steps to reproduce the problem

1. New User signs up for the platform 
2. He does not learn that he needs to manually turn on discoverability by going to settings, then click Profile, then click Privacy and Reach and then click TWO checkboxes to be discoverable in search and algorithm
3. The user gets no engagement, leaves Mastodon and joins Bluesky. 

### Expected behaviour

User should learn that he needs to turn that on in order to be discoverable

### Actual behaviour

Users join Bluesky

### Detailed description

Search and Discoverability are the most important features for journalists and activists. In the current implementation, both will choose Bluesky over Mastodon. 

Google Search Indexing is on by default for new users, but Mastodon Search Engine is opt in. I can explain this to literally nobody. Nobody understands. It makes no sense at all. 

Search and Discoverability is so important for learning about new trends and topics in the community. It's completely ok that some users don't want to be found. But you should not need to click through dozens of menus in order to finally turn on discoverability. If any non tech-savvy person joined mastodon today I would have to EXPLAIN to them that they need to turn that on. This alone shows, that it is not solved well. 

Why is Google Search opt out, but the most important feature for so many people, search&discoverability is opt in?

### Mastodon instance

mastodon.social

### Mastodon version

v4.2

### Browser name and version

Safari@latest

### Operating system

macOS@latest

**Comment by renchap** [comment]
Thanks for this suggestion.

We plan to add those settings to onboarding in a future version, but this requires a significant amount of work and we did not had the time to include this in the 4.2 release.

**Comment by BennyBolivar** [comment]
Jesus, just make it opt-out.

**Comment by JustDalek** [comment]
> Jesus, just make it opt-out.

Forreal. Anyone who doesn't want their content to be public should

A: Private their accounts/Make Follower only posts
B: Consider not using social networking/social media sites. Which are among the most public of services.

I don't understand the ideology of "I want this to be public and sharable (boosts) but don't you dare search for it".

**Comment by KDederichs** [comment]
Agreed, making it opt-out would make a lot more sense.
Making it opt-in and hiding it away deep in the settings is too much friction for 99% of internet users

**Comment by ThisIsMissEm** [comment]
Could we do a migration that sets all current users to explicit opt-out (rather than a "not configured" value), and then switch to opt-in for all new users?

Then in a future version we make it part of onboarding to choose?

**Comment by Gargron** [comment]
Fixed in #27876
