### ISSUE TITLE
Error in Mastodon 4.2.0 upgrade instructions for rbenv/Ruby (link provided removed instructions).

### ISSUE THREAD

**Issue by KuJoe** [mastodon/mastodon#27049]
### Steps to reproduce the problem

This is a minor issue, but one that might stump some users who aren't familiar with rbenv or Ruby.

The link provided in step 0 (upgrading Ruby to 3.2.2) no longer includes instructions on how to update the list of available versions.

Here is the code that was removed previously:
`sh  
cd ~/.rbenv/plugins/ruby-build  
git pull`

### Expected behaviour

Link provided is expected to have instructions for updating the list of Ruby versions.

### Actual behaviour

The link no longer contains those instructions.

### Detailed description

I'm unsure why they were removed or where they went, but I found in an older version of the readme the required instructions:

`sh  
cd ~/.rbenv/plugins/ruby-build  
git pull`

**Comment by ClearlyClaire** [comment]
That section has indeed been removed from the upstream README in https://github.com/rbenv/rbenv/commit/33f8621ec8cd0fc3f0101e04a55db6bf822d735e

I need to look into it deeper

**Comment by ClearlyClaire** [comment]
I believe https://github.com/rbenv/ruby-build/wiki#updating-ruby-build has more accurate, up-to-date and stable instructions, updated the release notes accordingly.
