### ISSUE TITLE
After 4.2.0 migration, using `ioredis`, you must force IPv6 resolution for the streaming API

### ISSUE THREAD

**Issue by AlyxPractice** [mastodon/mastodon#27043]
### Steps to reproduce the problem

Following the migration to `ioredis` (https://github.com/mastodon/mastodon/pull/26581) I had connection issues to my Redis instance on fly.io, using IPv6.

I was using :
```
REDIS_HOST = "my-instance-redis.internal"
REDIS_PORT = "6379"
```

But now I need to force the IPv6 resolution using the `family` parameter : 
```
REDIS_URL = "redis://my-instance-redis.internal:6379/?family=6"
```

I found some occurrences of this parameter here and there: 
- https://github.com/redis/ioredis/blob/ec42c82ceab1957db00c5175dfe37348f1856a93/test/unit/utils.ts#L198-L205
- https://github.com/redis/ioredis/blob/ec42c82ceab1957db00c5175dfe37348f1856a93/lib/utils/index.ts#L241-L246

Maybe we could add a warning to the administrator in the changelog about that? Ideally, a way to resolve the hostname, no matter if it's IPv4 or IPv6 on top of their library would be super cool to avoid any issues like this.

I'm creating this issue to help others mostly if they spot something similar.

### Expected behaviour

`ioredis` library should do the hostname IPv6 resolution "natively"

### Actual behaviour

`ioredis` failed to connect to IPv6 Redis instances, except if you force it using the `family` parameter in `REDIS_URL`

### Mastodon instance

`3615.computer`

### Mastodon version

v4.2.0

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: `v3.2.2p53`
- Node.js version: `v20.6.1`

I did not save the log showing the issue, but from my search history it was something like `Error: getaddrinfo ENOTFOUND`.

**Comment by vmstan** [comment]
Does this impact the regular Mastodon process connections to Redis as well or just for the streaming API?

**Comment by VictorBersy** [comment]
> Does this impact the regular Mastodon process connections to Redis as well or just for the streaming API?

Sidekiq was in a working state so it seems to only impact the streaming API.

**Comment by VictorBersy** [comment]
I'll try to write some code to easily reproduce the issue and eventually make a PR here or on `ioredis`. `ioredis` seems to use https://nodejs.org/api/dns.html#dnslookuphostname-options-callback under the hood.

**Comment by ThisIsMissEm** [comment]
@VictorBersy I think you'd be better filing this as an upstream issue in ioredis: https://github.com/redis/ioredis/issues

By default ioredis assumes IPv4, per https://github.com/redis/ioredis/blob/main/lib/redis/RedisOptions.ts#L192, when it should probably not assume IPv4 (by passing `0` for the family instead of `4`)

**Comment by ThisIsMissEm** [comment]
Could someone try adding in `family: 0` to https://github.com/mastodon/mastodon/blob/c953dca1dee71f32b547e68977568cd076a6f7ae/streaming/index.js#L248-L253

That should fix this issue. Essentially ioredis sets `family: 4` by default, which means it can't connect to ipv6, setting family to `6` forces ipv6, a family of `0` means "auto detect": https://nodejs.org/docs/latest-v20.x/api/net.html#socketconnectoptions-connectlistener

**Comment by ThisIsMissEm** [comment]
In fact, here's even a pull request you can test: https://github.com/mastodon/mastodon/pull/31229
