### ISSUE TITLE
After updating to 4.2.0, version showing as 4.2.9

### ISSUE THREAD

**Issue by edmondburnett** [mastodon/mastodon#27042]
### Steps to reproduce the problem

1. Perform update procedure from v4.1.9 to v4.2.0
2. Observe the reported version in the UI is showing as v4.2.9

### Expected behaviour

Version should show 4.2.0

### Actual behaviour

Version shows 4.2.9

### Detailed description

After upgrading to v4.2.0, the version number listed in the lower-left side of the UI is incorrect:

![Screen Shot 2023-09-21 at 2 25 26 PM](https://github.com/mastodon/mastodon/assets/1209199/21077e3d-1937-4322-b7b2-27f88e257a2f)

Doesn't seem to be a custom theme issue, I switched over to the Mastodon default theme and it's the same.

### Mastodon instance

vael.town

### Mastodon version

v.4.2.9

### Browser name and version

Firefox 117.0.1

### Operating system

Ubuntu 22.04.2 LTS

### Technical details

Non-docker installation on Ubuntu 22.

**Comment by vmstan** [comment]
Are you running from source or a Docker container?

Is there any reason you'd have had a customized version.rb file under lib/mastodon folder? What does that look like?

**Comment by edmondburnett** [comment]
I'm running from source.

I checked the `lib/mastodon/version` file, and it does indeed have the wrong value here:

```
module Mastodon
  module Version
    module_function

    def major
      4
    end

    def minor
      2
    end

    def patch
      9
```

Not sure where this came from as I never customized it. But, it could have been a merge mistake of some kind.

**Comment by edmondburnett** [comment]
Thanks for the tip! I resolved it simply by replacing this file.

**Comment by kwatson** [comment]
I also had this issue -- from looking at the git blame on the file, this appears to be caused by going from 4.1.9 and merging in 4.2.0. Now I'm wondering what else may have not been brought over with the 4.2 merge. Perhaps that's not the best upgrade strategy? 🤔

**Comment by vmstan** [comment]
The instructions should be to checkout the 4.2.0 release and compile.

**Comment by edmondburnett** [comment]
Yeah, the instructions assume that you're working off of a completely stock copy, which is reasonable I suppose. Mine only has light UI modifications, so I merge new releases to retain my changes, and manually review & fix any conflicts. 

It's just weird the version file only partially merged, and I didn't notice any conflict.
