### ISSUE TITLE
Link in the post and link of preview are different

### ISSUE THREAD

**Issue by cjaone** [mastodon/mastodon#27056]
### Steps to reproduce the problem

1. Go to https://social.tchncs.de/@mspro/111092208456534993
2. Click on the post link
3. Click on the preview link

### Expected behaviour

After clicking on the preview link the remote web server shows the expected web page

### Actual behaviour

After clicking on the preview link the remote web server shows a 404 error page

### Detailed description

Post and preview links are different.
The '?' character is URL encoded:

Post link:
https://www.boeckler.de/de/faust-detail.htm?sync_id=HBS-008697
Preview link:
https://www.boeckler.de/de/faust-detail.htm%3Fsync_id=HBS-008697 (? is encoded by %3F)

There are 2 problems:

1. The remote web server does not show the correct page. I believe this is **_not_** Mastodon's fault: The web server should be able to decode the URL and display the correct web page anyway.
2. Mastodon creates a preview URL which is different from the URL in the post. I think this should be solved. Then the web page would not display the 404 error page. It is the post creators' responsibility to post a correct URL but Mastodon should not change it to a different URL in the preview, even if it it's semantically equivalent to the original URL (except for " of course which is used in the a href).

### Mastodon instance

https://social.tchncs.de/

### Mastodon version

v4.2.0

### Browser name and version

Firefox 117.0.1

### Operating system

Linux

**Comment by ClearlyClaire** [comment]
Hi! Thank you for your report!

This seems to be caused by Mastodon's preview-card deduplication logic selecting the page's `og:url` field… which in this case is incorrect. I'm not sure what we should do in this case.
