### ISSUE TITLE
Streaming service doesn't start after upgrading to 4.2.0, node error

### ISSUE THREAD

**Issue by baskinsy** [mastodon/mastodon#27069]
### Steps to reproduce the problem

1. Ruby was upgraded to 3.2.2 first.
2. Upgrade from 4.1.9 according to the instructions. 
3. Streaming server refused to start with node error
4. Replaced systemd files as proposed
5. Starting the streaming service fails again.
6. Timelines are not refreshing (local and federated), only home and notifications are working as expected

### Expected behaviour

Streaming server should start

### Actual behaviour

Streaming server doesn't start with node error

### Detailed description

Streaming service fails to start either with old systemd files, error is this:

```
Sep 22 19:39:15 srv1 systemd[1]: Started mastodon-streaming on port 4000.
Sep 22 19:39:16 srv1 node[2981936]: /home/mastodon/live/node_modules/jsdom/node_modules/whatwg-url/lib/URL.js:1
Sep 22 19:39:16 srv1 node[2981936]: SyntaxError: Invalid or unexpected token
Sep 22 19:39:16 srv1 node[2981936]:     at Object.compileFunction (node:vm:360:18)
Sep 22 19:39:16 srv1 node[2981936]:     at wrapSafe (node:internal/modules/cjs/loader:1126:15)
Sep 22 19:39:16 srv1 node[2981936]:     at Module._compile (node:internal/modules/cjs/loader:1162:27)
Sep 22 19:39:16 srv1 node[2981936]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
Sep 22 19:39:16 srv1 node[2981936]:     at Module.load (node:internal/modules/cjs/loader:1076:32)
Sep 22 19:39:16 srv1 node[2981936]:     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
Sep 22 19:39:16 srv1 node[2981936]:     at Module.require (node:internal/modules/cjs/loader:1100:19)
Sep 22 19:39:16 srv1 node[2981936]:     at require (node:internal/modules/cjs/helpers:119:18)
Sep 22 19:39:16 srv1 node[2981936]:     at Object.<anonymous> (/home/mastodon/live/node_modules/jsdom/node_modules/whatwg-url/webidl2js-wrapper.js:3:13)
Sep 22 19:39:16 srv1 node[2981936]:     at Module._compile (node:internal/modules/cjs/loader:1198:14)
Sep 22 19:39:16 srv1 systemd[1]: mastodon-streaming@4000.service: Main process exited, code=exited, status=1/FAILURE
Sep 22 19:39:16 srv1 systemd[1]: mastodon-streaming@4000.service: Failed with result 'exit-code'.
Sep 22 19:39:16 srv1 systemd[1]: mastodon-streaming@4000.service: Scheduled restart job, restart counter is at 5.
Sep 22 19:39:16 srv1 systemd[1]: Stopped mastodon-streaming on port 4000.
Sep 22 19:39:16 srv1 systemd[1]: mastodon-streaming@4000.service: Start request repeated too quickly.
Sep 22 19:39:16 srv1 systemd[1]: mastodon-streaming@4000.service: Failed with result 'exit-code'.
Sep 22 19:39:16 srv1 systemd[1]: Failed to start mastodon-streaming on port 4000
```

### Mastodon instance

kafeneio.social

### Mastodon version

V4.2.0

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: v3.2.2
- Node.js version: V16.20.2

**Comment by chrisdimas** [comment]
We solved it by removing `/home/mastodon/live/node_modules/jsdom/node_modules` and  `yarn cache clean && yarn install --check-files`. The URL.js file was empty for some unknown reason so we had to rebuild it.

**Comment by specktator** [comment]
We solved it by removing `/home/mastodon/live/node_modules/jsdom/node_modules` and  `yarn cache clean && yarn install --check-files`. The URL.js file was empty for some unknown reason so we had to rebuild it.
