### ISSUE TITLE
Hide attached media from liked posts in Notifications

### ISSUE THREAD

**Issue by anampses** [mastodon/mastodon#27067]
### Pitch

Prior to the latest v4.2.0, notifications received for posts with attached media that was liked or commented on would just show the text and who made the interaction. But now with the new update, the notification column automatically display the media itself alongside the post and can take up a frustratingly large amount of space when someone is just trying to quickly scroll through all the likes or comments. 

Unless I am missing this option somewhere in v4.2.0, please consider adding an option in notification settings to hide media.

### Motivation

Attached images in posts take up way too much space in the notification column. Having an option to hide media and show just the likes or comments like it used to be prior to v4.2.0 would benefit a lot of artists that use Mastodon to share their works and not have their notifications bogged down by all their drawings.

**Comment by WelshPixie** [comment]
Seconding this on behalf of one of our users: https://mastodon.art/@berrefjord/111113525757627047 (and also form me, who posts a lot of media that gets lots of interactions XD)

**Comment by PinballsWizard** [comment]
Adding support that this change has been a negative one, especially combined with the lack of 16:9 cropping as in https://github.com/mastodon/mastodon/issues/22993, and an option to control if media is shown would be a vast improvement.  Less notifications show in the space afforded to them, and like others I don't need to see my own art each time someone likes the post.

**Comment by anampses** [comment]
Issue has been addressed with v4.3
