### ISSUE TITLE
Content doesn't resize to % of screen width and isn't customisable

### ISSUE THREAD

**Issue by sammcj** [mastodon/mastodon#27075]
### Steps to reproduce the problem

1. Use a modern monitor size and resolution (say, 27-34", 4-5k)
2. Open a mastodon site
3. Note that the content is squished into a small strip in the middle of the page.

![bookmark-first-design](https://github.com/mastodon/mastodon/assets/862951/888f9ac0-670b-4954-8e5e-345c8d5940c0)

### Expected behaviour

Content to be resized to a % of your screen/browser width - or be configurable (e.g. 

### Actual behaviour

Content is squashed into a very narrow column in the middle of the screen requiring lots of vertical scrolling and eye movement.

### Detailed description

Having content compressed into such a narrow column is probably really sensible for mobile phones and maybe tablets - however on the desktop it has a number of disadvantages.

- Content can become quite hard to read if it's longer than a sentence or two.
- If you're someone that tries to avoid excessive scrolling or window switching (e.g. RSI, hand/wrist damage, differently abled etc...).
- If you get eye fatigue from excessive vertical eye movement (I don't have any evidence for this, however I could imagine it might be a thing).
- It can have a negative impact on computer performance and power usage, if you're constantly have to wake up the processor and GPU you're going to use more energy (this varies by hardware, OS and browser).
- It's generally a waste of screen real estate, I'm not saying there has to be wall to wall content I think that could be distracting, but it lends itself to being put to use within reason.

Personally if there were an option to adjust it myself I'd probably set it to something like 50% of my browser window up to a maximum of 50% of my display resolution, but a simple drag option on the column divers that stored their state would suffice.

### Mastodon instance

aus.social

### Mastodon version

v4.2.0

### Browser name and version

Firefox 118

### Operating system

macOS 13.5.2

### Technical details

It seems to be the `.columns-area__panels__main` style which is hard coded to a max of just 600px:

```
.columns-area__panels__main {
	max-width: 600px;
	padding: 0 10px;
}
```

Doubling this to twice it's current max, at 1200px content is vastly more readable and requires significantly less scrolling and vertical screen space:

![SCR-20230923-iqoc](https://github.com/mastodon/mastodon/assets/862951/69d48fde-dd45-4de8-8fee-32f7d818ae85)

**Comment by eishiya** [comment]
FWIW almost every size in Mastodon is set in pixels, which means Mastodon doesn't even respect the user's font size settings in their browser, so it has problems even on smaller screens. The column width is just the tip of the iceberg. The reliance on pixels severely hinders the web UI's visual accessibility and responsiveness.

**Comment by trwnh** [comment]
See #8632 and #11413
