### ISSUE TITLE
Upgrade to v4.2: Duplicate key error at database migration

### ISSUE THREAD

**Issue by rthees** [mastodon/mastodon#27083]
### Steps to reproduce the problem

I'm upgrading my Mastodon instance from 4.1.9 to 4.2. Everything worked fine, untill i came to the database-migration with `SKIP_POST_DEPLOYMENT_MIGRATIONS=true RAILS_ENV=production bundle exec rails db:migrate`

### Expected behaviour

The database should migrate without errror

### Actual behaviour

The migration was aborted with a duplicate key error.

### Detailed description

This is the output where it happens during migration:

```
- Migrating preview_cards.image_description (~1002190 rows)
   -> Migrated 7000 rows (~0.70%, 2:27 remaining, safe to interrupt)
   -> Migrated 15000 rows (~1.50%, 2:20 remaining, safe to interrupt)
   -> Migrated 25000 rows (~2.49%, 2:03 remaining, safe to interrupt)
   -> Migrated 32000 rows (~3.19%, 2:07 remaining, safe to interrupt)
   -> Migrated 38000 rows (~3.79%, 2:13 remaining, safe to interrupt)
   -> Migrated 45000 rows (~4.49%, 2:14 remaining, safe to interrupt)
   -> Migrated 52000 rows (~5.19%, 2:16 remaining, safe to interrupt)
-- remove_column(:preview_cards, :image_description)
   -> 0.0085s
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_preview_cards_on_url"
DETAIL:  Key (url)=(https://lemmy.ml/c/linux_gaming) already exists.
```

Then the output continues with error logs:
```
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `exec'
...
...
...
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)"
```

### Mastodon instance

wue.social

### Mastodon version

v4.2

### Technical details

- Ruby version: 3.2.2
- Node.js version: 18.18.0

**Comment by ClearlyClaire** [comment]
Hi! It looks like your database indexes were corrupted before you started the update process (see <https://docs.joinmastodon.org/admin/troubleshooting/index-corruption/>).

Unfortunately, the migration script has not been updated for the v4.2.0 release, so you'll need to fetch the changes from https://github.com/mastodon/mastodon/pull/27147 before you run it again.

**Comment by mjankowski** [comment]
Closing on assumption that those changes are now in a release, and that doing that presumably solved this -- please reopen if not!
