### ISSUE TITLE
Toots in Chinese regional variants are not rendered in the correct font

### ISSUE THREAD

**Issue by timdream** [mastodon/mastodon#27081]
### Steps to reproduce the problem

1. Post a toot with language set to a specific zh locale code, e.g. `zh-tw`.
2. Observe the post on Web.

### Expected behaviour

The post is rendered in a font for `zh-tw`

### Actual behaviour

The post is rendered in a font for `zh`

### Detailed description

(See technical details below)

### Mastodon instance

mastodon.social

### Mastodon version

v4.1.2

### Browser name and version

Safari Version 16.6 (18615.3.12.11.2)

### Operating system

macOS 13.5.2 (22G91)

### Technical details

Inspecting the generated HTML I can see

```html
<div class="status__content__text status__content__text--visible translate" lang="zh"><p>文字</p></div>
```

with `lang="zh"` being the problem there. The `lang` attribute should be marked with `zh-tw` to allow browsers to pick the right font.

## Background

As part of [Han Unification](https://en.wikipedia.org/wiki/Han_unification), Unicode assigns one code point for all regional variants of the same character. Browsers and other text rendering technologies therefore rely on the context (user-specified toot locale, in this example) to pick the right font.

The same Wikipedia article illustrates this:

![](https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Source_Han_Sans_Version_Difference.svg/2560px-Source_Han_Sans_Version_Difference.svg.png)

The resulting text rendering is not unreadable, but it would feel foreign and unprofessional to readers. That being said, I suspect the fix is also relatively trivial (don't even require a new UI) so overall ROI for fixing this issue should pass the bar.

**Comment by gunchleoc** [comment]
Bug confirmed
