### ISSUE TITLE
Setting Posting Language to `zh-tw` will change the default posting to `ZH` (Chinese) instead of the correct regional variant (`ZH-TW`)`

### ISSUE THREAD

**Issue by poga** [mastodon/mastodon#27085]
### Steps to reproduce the problem

1. In `Preferences` -> `Others` -> `Posting Language` drop down, set it to `繁體中文（台灣）`(`ZH-tw`)
2. Go back to `Home`
3. The default posting language in the compose form becomes `ZH` instead of `ZH-tw`

### Expected behaviour

The default posting language should become `ZH-TW`

### Actual behaviour

Default changed to `ZH`

### Mastodon instance

g0v.social

### Mastodon version

v4.2.0

### Browser name and version

Brave v1.58.131 Chromium: 117.0.5938.92 (arm64)

### Operating system

MacOS 13.5.2

**Comment by gunchleoc** [comment]
Bug confirmed.
