### ISSUE TITLE
"Hide these posts from home" setting does not update in UI when switching lists

### ISSUE THREAD

**Issue by brookmiles** [mastodon/mastodon#27097]
### Steps to reproduce the problem

1. Create more than one List
2. Enable "Hide these posts from home" on one list, and disable it on another.
3. Open one of the lists and open the Settings panel at the top of the page.
4. Leaving the Settings panel open, click on the second list.

### Expected behaviour

The "Hide these posts from home" should change to reflect the currently selected list.

### Actual behaviour

"Hide these posts from home" does not change to reflect the state of the currently selected list.

### Detailed description

When selecting a different list to view, the list title, contents, and other settings such as "Show replies to:" are updated to show the settings for the newly selected list, but "Hide these posts from home" does not update when switching lists.

Closing and re-opening the Settings panel will refresh the display, and the "Hide these posts from home" setting will correctly reflect the setting for the current list.

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.0

### Browser name and version

Firefox 117.0.1

### Operating system

Windows 10

**Comment by brianholley** [comment]
I've reproduced this bug on Firefox 119.0 and Chrome 118.0.5993.120. It looks like a pretty straightforward bug where the react-toggle control is using `defaultChecked` instead of `checked`, so it's only set at initial render time and not updated. I'm preparing a PR.
