### ISSUE TITLE
URL for a post displays (in Slack, text message) the instance logo rather than abbreviated message (as previously)

### ISSUE THREAD

**Issue by mikehamca** [mastodon/mastodon#27101]
### Steps to reproduce the problem

1. Click on a post in the web interface.
2. Copy the URL to the clipboard.
3. Paste the URL into a Slack message, text message, etc.
4. The instance logo is displayed, with no hint as to the post content
5. Previously, an abbreviated version of the message would be displayed

### Expected behaviour

The pasted URL should display as an abbreviated version of the post at the link

### Actual behaviour

The pasted URL displays the instance logo.

### Detailed description

Before the upgrade, pasting the URL of a mstdn.ca post into a message (text, Slack, etc.) would display the post — an abbreviated version for a long post, the full post for a brief post. 

Now, after the upgrade, the pasted URL always has the same display — the instance's logo — with no information about the linked post.

Two files are attached. The first shows how pasted URLs are currently displayed (instance logo); the other shows how pasted URLs previously displayed (abbreviated message)
------------
<img width="674" alt="Screenshot 2023-09-24 at 7 39 41 AM" src="https://github.com/mastodon/mastodon/assets/117941733/67780791-1924-4f4b-a054-9a17bc1d41f0">
<img width="674" alt="Screenshot 2023-09-24 at 3 00 28 AM" src="https://github.com/mastodon/mastodon/assets/117941733/fb9c2bdb-16fa-4b3b-bfab-49c4e4c0c4ce">

### Mastodon instance

mstdn.ca

### Mastodon version

v4.2.0+glitch

### Browser name and version

Vivaldi 6.2.3105.51 (Stable channel) (arm64)  Revision	76144063ae8137b05a189fe91dfaf1ac12ce492d

### Operating system

macOS Version 13.6 (Build 22G120)

**Comment by Gargron** [comment]
It seems like you’re linking to the deck URL in one of them.

**Comment by mikehamca** [comment]
> It seems like you’re linking to the deck URL in one of them.

Aha! I see the "deck" now in the link. So I can just edit the link by hand before pasting it.

Thanks. That's a good workaround. I wonder why the "deck/" is now being inserted into the URL. It wasn't before. Both before and I after I just click the post age info to put it in focus and copy the link.

More experimentation shows that the "deck/" insertion happens because I am using the Advanced Web Interface. When I deled "deck/", I get a URL that displays correctly.

Now that I have a workaround, it's not such an issue. But it does seem odd that "deck/" is being inserted just because I'm using the AWI. I guess deleting "deck/" from post URLs is just the price to pay for using the AWI.

**Comment by ClearlyClaire** [comment]
Oh, we most probably want to have a redirect from `/deck/<path>` to `/<path>` when logged out.
