### ISSUE TITLE
Do not use color alone to indicate status of boost, like

### ISSUE THREAD

**Issue by mikehamca** [mastodon/mastodon#27108]
### Pitch

At one time the notification bell changed color when activated, which was difficult for some who are colorblind to see. (I'm colorblind, so I noticed.) The interface was revised so that "notifications off" has the bell as outline and "notifications on" has the bell as solid: clear to everyone, including the colorblind.

I also have trouble with the "like" star (what Mastodon calls "favorite," though one can click the star on many posts, so it seems more "like" than "favorite"). The star seems to change slightly, from a gray to a dark gold, but it's difficult for me to see. 

I also have trouble (though less trouble) in seeing clearly whether "boost" is activated (dark blue) or not (black). Again, I think symbol status should be indicated by some change other than (or in addition to) a change in color.

I suggest making unclicked-star an outline and a clicked-star solid. The boost symbol could similarly become solid if it is on (boosted). Color change can also be used, but in addition a change other than in color would be clear for all, colorblind or not.

### Motivation

I'm colorblind and I often cannot tell whether the star is clicked or not — and I also have to look **very** carefully at the "boost" symbol to see whether I've turned it on (dark blue) or not (block) — again, it would be helpful if symbol status were not indicated solely by color.

**Comment by ClearlyClaire** [comment]
This may require a bit of work for the reblog icon, as we have a custom one with multiple variants and animation steps, but otherwise I do like the idea of using outline-only variants for buttons that are not active.

Here is what it may look like:
![image](https://github.com/mastodon/mastodon/assets/384364/3bb26486-cd27-4cf8-b820-2f6e87bb3d6e)

**Comment by mikehamca** [comment]
The boost icon is not so great a problem as the like icon. With the boost icon, I sometimes hover to see if its current label is "Unboost" (as opposed to "boost"), and that works (although my cursor arrow covers most of the popup text — I use a large cursor arrow because I have some problems with visual acuity). My real issue is the "like" star. The different between dark gray and dusky gold is hard for me to see.  

I also have noted the boost animation, which is helpful (and independent of color) when I do boost a post. The issue arises when I later encounter a post I have boosted and want to know whether I did boost it (or not). That's when I peer at the label.

**Comment by rybak** [comment]
I've created a [userstyle](https://userstyles.world/style/12245/mastodon-more-readable-unboosts) which attempts to address the issue using simple CSS:

![demo of userstyle](https://github.com/mastodon/mastodon/assets/624072/beb549be-e8aa-4dc0-9323-45922ba74aeb)

**Comment by rybak** [comment]
Has this issue been addressed?

![boost button without boost](https://github.com/mastodon/mastodon/assets/624072/32317e90-22da-42fe-8c24-3a7f7cd525e2)

![boost button with boost](https://github.com/mastodon/mastodon/assets/624072/eb614421-9289-4f81-b097-fa02cb0e9980)

**Comment by ClearlyClaire** [comment]
Yeah, I'll close it as I think this has been solved. Feel free to discuss if you disagree!

**Comment by mikehamca** [comment]
The think the little internal square that appears when boost is activated
is brilliant. Totally solves the issue in an elegant way. Thank you!

Michael
