### ISSUE TITLE
Admin Audit Logs cannot be filtered for "disable_2fa_user"

### ISSUE THREAD

**Issue by ThisIsMissEm** [mastodon/mastodon#27167]
### Steps to reproduce the problem

1. Via the admin account moderation tools, disable a users' 2FA (you can test this on an account by setting `otp_required_for_login` to true without actually setting up 2FA)
2. Go to the audit log, observe that an entry was created "ACTOR disabled two factor requirement for user USER"
3. From the "filter by action" drop down, select "disable 2fa"

### Expected behaviour

The audit log entry for disabling 2fa should be show

### Actual behaviour

The audit log entry for disabling 2fa is not shown

### Detailed description

I saw this via a subtle change in #24103, which was closed, but the bug that was fixed was never fixed in main.

### Mastodon version

main

**Comment by ThisIsMissEm** [comment]
Have logged this as a bug, instead of directly doing a PR as I suspect we'll need better test coverage for the audit logs controller.

**Comment by ThisIsMissEm** [comment]
Perhaps also pertinent here is that the disabling of 2FA via tootctl does not result in an audit log entry, when it almost certainly should.

**Comment by ClearlyClaire** [comment]
> Perhaps also pertinent here is that the disabling of 2FA via tootctl does not result in an audit log entry, when it almost certainly should. (I noticed this whilst attempting to reproduce this bug)

The issue with `tootctl` is that you are not doing these operations as a Mastodon user, but I guess this could be registered as a log with a `nil` `account_id`

**Comment by ThisIsMissEm** [comment]
> > Perhaps also pertinent here is that the disabling of 2FA via tootctl does not result in an audit log entry, when it almost certainly should. (I noticed this whilst attempting to reproduce this bug)
> 
> The issue with `tootctl` is that you are not doing these operations as a Mastodon user, but I guess this could be registered as a log with a `nil` `account_id`

I was thinking for `tootctl` you could use the instance actor account as the `account_id`? That's about as close as you'd get?
