### ISSUE TITLE
Same-instance profile links not working when logged out

### ISSUE THREAD

**Issue by lapcat** [mastodon/mastodon#27163]
### Steps to reproduce the problem

1. Open https://mastodon.social/@marcoarment in a web browser.
2. Click on the [@atpfm](https://mastodon.social/@atpfm) link or the [@overcastfm](https://mastodon.social/@overcastfm) link.

### Expected behaviour

The link is opened

### Actual behaviour

Nothing

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.0

### Browser name and version

Google Chrome 117

### Operating system

macOS 13.6

### Technical details

The links have a `click` handler `handleMentionClick`.

https://github.com/mastodon/mastodon/blob/57f592fed50747f3c97718a2761e17bafe6c8698/app/javascript/mastodon/features/account/components/header.jsx#L185

**Comment by ClearlyClaire** [comment]
This seems to only happen when logged out. I will investigate further.
