### ISSUE TITLE
Live Feeds has two scrollbars in advanced interface

### ISSUE THREAD

**Issue by eishiya** [mastodon/mastodon#27176]
### Steps to reproduce the problem

1. Switch to the /deck/ interface
2. Navigate to Live Feeds.
3. Observe the scrollbars.

### Expected behaviour

There should be one, functioning scrollbar.

### Actual behaviour

There are two scrollbars, of which one does nothing.

### Detailed description

The new "Live feeds" column has a scrolling child element that displays the actual feed, which allows the This Server/Other Servers/All selector to stay on the screen as you scroll. However, the whole column *also* has a scrollbar, but this scrollbar can never do anything because the column's content is always sized to its height.

Firefox:
![image](https://github.com/mastodon/mastodon/assets/70545646/83f55106-9682-4810-a38c-793eb40a0303)
Chrome:
![image](https://github.com/mastodon/mastodon/assets/70545646/d1fbe2ac-45bd-44c7-adf0-16093a7e19ee)

The column's scrollbar should be hidden for the Live Feeds scrollbar, leaving only the child element's scrollbar.

### Mastodon instance

mastodon.art

### Mastodon version

v4.2.0

### Browser name and version

Firefox 116.0.2, Chrome 117.0.5938.92 

### Operating system

Windows 10 x64

**Comment by ClearlyClaire** [comment]
That's weird, I can't reproduce this. Do you perhaps have any custom style?

**Comment by ClearlyClaire** [comment]
Nevermind, disabling overlay scrollbars in Firefox, I can reproduce this.
