### ISSUE TITLE
Links with anchors in them create hashtags

### ISSUE THREAD

**Issue by gunchleoc** [mastodon/mastodon#27175]
### Steps to reproduce the problem

Post this:

> 21:45 Edinburgh to Perth due 23:06
> Facilities on the 21:45 Edinburgh to Perth due 23:06.
> http://www.journeycheck.com/scotrail/route?id=16801062571L71Y30051270923&action=search&from=&to=&savedRoute=&formTubeUpdateType=&formTubeUpdateLocation=Service+Updates&formTubeUpdatePeriod=#16801062571L71Y30051270923

### Expected behaviour

Post has no hashtags

### Actual behaviour

Post shows hashtag #16801062571L71Y30051270923 on the bottom

### Detailed description

Wrote an RSS bot that is pulling links with hashtags in them. The end of the link is parsed as a hashtag

![image](https://github.com/mastodon/mastodon/assets/4095570/22494cbe-375b-4c53-8f31-f7575c43fd66)

### Mastodon instance

mastodon.scot

### Mastodon version

v4.2.0

### Browser name and version

Firefox 118.0

### Operating system

Linux Mint

**Comment by ClearlyClaire** [comment]
Seems similar to #23275

I think `Tag::HASHTAG_RE` needs to be adjusted to reject `=`. I also wonder if this shouldn't be changed to a negative lookbehind.
