### ISSUE TITLE
Admin dashboard retention chart displays incorrectly for UTC -x users

### ISSUE THREAD

**Issue by vmstan** [mastodon/mastodon#27174]
### Steps to reproduce the problem

1. Open `/admin/dashboard`
2. View retention chart
3. Notice August is missing (it’s September currently)

![IMG_0792](https://github.com/mastodon/mastodon/assets/3002053/055f91c9-6b98-4288-8510-7b913d6e0159)

But after changing device timezone to UTC (server is also UTC) 

![IMG_0793](https://github.com/mastodon/mastodon/assets/3002053/d74cfec1-8a3f-4e15-a6fb-958e144101ce)

August appears!

### Expected behaviour

All months appear

### Actual behaviour

No latest month

### Detailed description

Reproduced by multiple folks in UTC -x time zones, in #server-admin Discord.

### Mastodon instance

vmst.io

### Mastodon version

v4.2.0

### Browser name and version

Any

### Operating system

Any

**Comment by vmstan** [comment]
@rrgeorge pointed out the timezone issue 

@ThisIsMissEm suggested:

> looks like in the dashboard controller the times aren't in UTC necessarily: ```@time_period = (29.days.ago.to_date...Time.now.utc.to_date)```

> Looks like it looses the timezone info when creating the ` Admin::Metrics::Retention.new(` value from the retention controller. where as the other measures use `to_datetime`, retention uses `to_date`

**Comment by akhil-rasheed** [comment]
I'd like to take this up. Any pointers on where to start?
