### ISSUE TITLE
Something has stopped the Wayback Machine correctly displaying profile pages

### ISSUE THREAD

**Issue by christianp** [mastodon/mastodon#27196]
### Steps to reproduce the problem

A user on mathstodon.xyz reported that web.archive.org is no longer displaying snapshots of their profile page properly, since we updated to 4.2.0.

### Expected behaviour

The Wayback Machine's snapshot of a user's profile page should look pretty much the same as the live version

### Actual behaviour

The Wayback Machine snapshot shows a blank background

### Detailed description

The example I was shown was https://web.archive.org/web/20230928163239/https://mathstodon.xyz/@Inquiry.

The same problem applies to mastodon.social. The last snapshot for @ Gargron that displays properly is [2023-05-22](https://web.archive.org/web/20230522210451/https://mastodon.social/@Gargron); [the next one on 2023-05-24](https://web.archive.org/web/20230524032045/https://mastodon.social/@Gargron) and all subsequent ones until now show a blank page.

This is really a problem for the internet archive team to solve, but it's due to a change in mastodon so might be fixable here.

Am I right to guess that profile page content is now loaded through JS after the HTML has loaded? I suppose that would mean the internet archive can't archive it properly.

### Mastodon instance

mastodon.social and mathstodon.xyz

### Mastodon version

I guess 4.2?

### Browser name and version

any

### Operating system

any

**Comment by ShadowJonathan** [comment]
I recommend this issue be closed in favour of #27405, since that one has accumulated more information atm, and is past triage

**Comment by trwnh** [comment]
Closing in favor of #27405 yeah
