### ISSUE TITLE
Caught mastodon.social dropping boosts

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#27195]
### Steps to reproduce the problem

I am logged into mastodon.social. At this exact moment, if I open https://mastodon.social/@graydon@types.pl , I see this

![image](https://github.com/mastodon/mastodon/assets/277318/dadcb6dd-c0d2-41ad-92f2-a4cd2a0271a7)

Notice the reference to a "last boost".

If I go directly to graydon's feed on types.pl https://types.pl/@graydon , I see this:

![image](https://github.com/mastodon/mastodon/assets/277318/d3d307d7-9130-4bd2-94fd-70fd75dff8ed)

Beneath the crawfordsm post, I see the microplastics post. There is a post missing from this feed, but *only* when I view from mastodon.social.

@crawfordsm@mastodon.social is on mastodon.social, so I assume that there is not a federation issue preventing me from seeing the post. I do not have crawfordsm blocked or muted. I have no filters which hide posts completly (only hide with warning) and none of my filters would apply to this post. It is possible crawfordsm has me blocked, but I assume not because I can see the original post on mastodon.social https://mastodon.social/@crawfordsm/110700335570308419 , I can see crawfordsm's profile, and the UI does not stop me from trying to @-mention Dr. Crawford.

### Expected behaviour

I expect that boosts and regular statuses should be shown to me in chronological order if the account is on a peer server in good standing.

### Actual behaviour

Post from my instance boosted on other instance missing from user feed

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.0+pr-27116-50e1f46

### Browser name and version

Chrome 117.0.5938.92 (Official Build) (64-bit)

### Operating system

Windows 10

**Comment by noellabo** [comment]
This problem occurs when you are logged in to the target server and you are using domain blocking (one or more servers are blocking it).

Posts boosted by local accounts will no longer be displayed in the list of local accounts' posts.

This is a bug caused by https://github.com/mastodon/mastodon/commit/1f99d862874fc1976b2a462dda01d1dc03d98e34.

When using where.not to test whether a boost by a local account is included in a domain-blocking server, it seems to malfunction if domain is NULL. Maybe you need to fix the where condition.

**Comment by ClearlyClaire** [comment]
Interestingly, I can view that boost from my mastodon.social account.

> This problem occurs when you are logged in to the target server and you are using domain blocking (one or more servers are blocking it).
> 
> This is a bug caused by [1f99d86](https://github.com/mastodon/mastodon/commit/1f99d862874fc1976b2a462dda01d1dc03d98e34).
> 
> When using where.not to test whether a boost by a local account is included in a domain-blocking server, it seems to malfunction if domain is NULL. Maybe you need to fix the where condition.

I have a hard time following here, but this bit of code looks like it could be the culprit, I'll investigate it, thanks!

**Comment by ClearlyClaire** [comment]
Found the issue, it's indeed because of `.where.not(reblog: { accounts: { domain: current_account.excluded_from_timeline_domains } })`, which excludes posts from accounts with a `NULL` `domain`.
