### ISSUE TITLE
tootsuite/mastodon:v4.2: ActionView::Template::Error (undefined method `[]' for nil:NilClass):

### ISSUE THREAD

**Issue by mkarg** [mastodon/mastodon#27218]
### Steps to reproduce the problem

I was using Mastodon 4.1.7 for several time successfully. 😃  Today I updated to 4.2 by dropping my docker container and creating a new one using the official image `tootsuite/mastodon:v4.2`. When I am starting a new container using mastodon:v4.2 then I am getting the stack trace below rather promptly in the container's log. As a consequence, the UI simply says that "We're sorry, but something went wrong on our end. ", as the API server always answers with `500`. 😢 
```
infra-mastodon-1  | F, [2023-09-29T16:27:12.142079 #11] FATAL -- : [6d2a739c-e068-418b-aa3a-05ceb4bc869a]
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a] ActionView::Template::Error (undefined method `[]' for nil:NilClass):
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a]      7:
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a]      8:   %meta{ name: 'applicationServerKey', content: Rails.configuration.x.vapid_public_key }
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a]      9:
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a]     10:   = render_initial_state
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a]     11:   = javascript_pack_tag 'application', crossorigin: 'anonymous'
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a]     12:
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a]     13: .notranslate.app-holder#mastodon{ data: { props: Oj.dump(default_props) } }
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a]
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a] app/models/concerns/has_user_settings.rb:15:in `prefers_noindex?'
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a] app/models/account.rb:139:in `user_prefers_noindex?'
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a] app/serializers/rest/account_serializer.rb:146:in `noindex'
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a] app/helpers/application_helper.rb:210:in `render_initial_state'
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a] app/views/shared/_web_app.html.haml:10
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a] app/views/shared/_web_app.html.haml:1
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a] app/views/home/index.html.haml:7
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a] app/controllers/concerns/localized.rb:11:in `set_locale'
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a] lib/mastodon/rack_middleware.rb:9:in `call'
infra-mastodon-1  | [6d2a739c-e068-418b-aa3a-05ceb4bc869a] lib/public_file_server_middleware.rb:18:in `call'
```

### Expected behaviour

No FATAL errors in the log, UI works

### Actual behaviour

FATAL errors in the log, UI says there is something wrong, API server responds with 500

### Detailed description

see above

### Mastodon instance

mastodon.headcrashing.eu

### Mastodon version

v4.2

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2): ruby 3.2.2 (2023-03-30 revision e51014f9c0) [aarch64-linux]
- Node.js version: (from `node --version`, eg. v18.16.0): v20.6.1

**Comment by mkarg** [comment]
I don't know if this is related, but I do assume it: At the same time, the PostgreSQL database tells me this in the log file repeatedly:
```
infra-postgres-1  | 2023-09-29 22:15:13.060 UTC [9108] ERROR:  column lists.exclusive does not exist at character 163
infra-postgres-1  | 2023-09-29 22:15:13.060 UTC [9108] STATEMENT:  SELECT "list_accounts"."account_id" FROM "list_accounts" WHERE "list_accounts"."list_id" IN (SELECT "lists"."id" FROM "lists" WHERE "lists"."account_id" = $1 AND "lists"."exclusive" = $2) AND "list_accounts"."account_id" = $3
infra-postgres-1  | 2023-09-29 22:15:19.063 UTC [27] LOG:  checkpoint complete: wrote 82 buffers (0.5%); 0 WAL file(s) added, 0 removed, 0 recycled; write=8.164 s, sync=0.020 s, total=8.205 s; sync files=31, longest=0.011 s, average=0.001 s; distance=499 kB, estimate=729 kB
```

**Comment by ibigbug** [comment]
having same issue, running with Docker

**Comment by ibigbug** [comment]
not sure if it's safe to rollback to prev version as there are db migrations

**Comment by mkarg** [comment]
> not sure if it's safe to rollback to prev version as there are db migrations

My target is not to use 4.1 anymore, but to get a correctly working 4.2.

**Comment by attie** [comment]
I just bumped into this too... read the release notes: https://github.com/mastodon/mastodon/releases/tag/v4.2.0

> Using Docker:
> 1. Run the pre-deployment database migrations by specifying the `SKIP_POST_DEPLOYMENT_MIGRATIONS=true` environment variable: `docker-compose run --rm -e SKIP_POST_DEPLOYMENT_MIGRATIONS=true web bundle exec rails db:migrate`
> 2. Restart all Mastodon processes
> 3. Run the post-deployment database migrations: `docker-compose run --rm web bundle exec rails db:migrate`
> 4. If you use Elasticsearch, rebuild the search indexes with `docker-compose run --rm web bin/tootctl search deploy --reset-chewy`

**Comment by mkarg** [comment]
Thank you, this indeed fixed my problem!

It is a bit sad that (a) this is not told on the image's page on Docker Hub, and (b) this is not automatically executed by the image on startup (like typical for docker images).
