### ISSUE TITLE
Exact Word Matching in Search

### ISSUE THREAD

**Issue by mullaney** [mastodon/mastodon#27217]
### Pitch

Under the current implementation if you search for posts which contain the work `improv`, you get lots of posts that include words like `improve`, `improvement`, and `improving` and almost no posts about improv. 

I would expect that searching for a word prioritizes exact matches instead of partial text matches. Perhaps this is considered a feature of the current search, but it does make it difficult when you are only interested in posts that have an exact word match. 

I would propose a prefix for searching that would focus the search results on exact word matches. For instance using `word:improv` or `match:improv` would only return posts with that word and not `improve` or other variations.

### Motivation

I think this would help in cases where one is looking for a very specific word whose letters happen to be a subset of another word. I'm having trouble finding other good examples of this behavior besides "improv". Perhaps this is not expected behavior, but improv is a special case.

**Comment by ClearlyClaire** [comment]
You can force exact matches by using quote marks: `"improv"`
