### ISSUE TITLE
It is possible to open poll result and THAN vote in it

### ISSUE THREAD

**Issue by jklawiter** [mastodon/mastodon#27222]
### Steps to reproduce the problem

1. In Advanced interface click show results in a poll on left (stream pane)
2. Open the post in right pane by clicking on it's date
3. You can still vote in this poll
...

### Expected behaviour

You should not be able to vote in poll you have seen results

### Actual behaviour

but you can do it :)

### Detailed description

One [Screenshot](https://files.mastodon.social/media_attachments/files/111/153/319/978/496/901/original/4c10c369501fa849.png) can be better than any description. ;-)

### Mastodon instance

mastodon.social

### Mastodon version

4.2.0+pr-27116-50e1f46

### Browser name and version

115.2.1esr

### Operating system

Linux - Gentoo 17.1 stable

**Comment by mjankowski** [comment]
Closing on assumption that there are actual many scenarios where you might want to do this, and its ok to do it.
