### ISSUE TITLE
Notifications are not working properly

### ISSUE THREAD

**Issue by itzzenxx** [mastodon/mastodon#27224]
### Steps to reproduce the problem

1. Make a post
2. People interact with it
3. All interactions federate, however not all interactions appear in notifications

### Expected behaviour

All posts federated should have appeared in notifications

### Actual behaviour

Not all posts federated should have appeared in notifications

### Detailed description

Whenever I make a post, not all interactions that federate with my instance show up in my notifications tab. I am unsure as to why and I don't know what to look for to solve this issue.

### Mastodon instance

mstdn.plus.st

### Mastodon version

v4.2.0+glitch

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
- Node.js version: v20.6.1

**Comment by ClearlyClaire** [comment]
Hi! How do you know some interactions are not leading to notifications? In which context do you see these interactions? Are you perhaps muting the users who interacted with you? Or maybe [rejecting notifications from non-followers](https://mstdn.plus.st/settings/preferences/notifications#user_settings_attributes_interactions.must_be_follower)?

**Comment by itzzenxx** [comment]
> How do you know some interactions are not leading to notifications?

Checking the replies and interactions in a post, I'll see that some replies appeared in notifications, however some others will appear under a post with me mentioned, however it will not appear in my notifications.

> Are you perhaps muting the users who interacted with you? Or maybe [rejecting notifications from non-followers](https://mstdn.plus.st/settings/preferences/notifications#user_settings_attributes_interactions.must_be_follower)?

These notification issues are not just happening with my account, but are happening with other users and new accounts.And I am not rejecting notifications from non-followers.

**Comment by ClearlyClaire** [comment]
> however some others will appear under a post with me mentioned, however it will not appear in my notifications

Are these posts merely in reply to a post that mention you, or are they mentioning you themselves? Are you checking the replies on your own server or on another server?

**Comment by itzzenxx** [comment]
> Are these posts merely in reply to a post that mention you, or are they mentioning you themselves? 

Both forms of mentioning me

> Are you checking the replies on your own server or on another server?

The replies are on another server, however if the posts appear in my notificiations or not are random.

**Comment by ClearlyClaire** [comment]
Are you comfortable sharing an example of a publicly-accessible reply that does not appear in your notifications?

**Comment by itzzenxx** [comment]
I have attached two screenshots, one of a thread I made with replies, and one with my screenshots 

the post: 
![image](https://github.com/mastodon/mastodon/assets/81382281/43246d90-3106-4e78-93f8-4b58a4d7d192)

my notifications, lacking some mentions: 
![image](https://github.com/mastodon/mastodon/assets/81382281/6a3ec9f5-756b-4999-b210-9235d78ac2e9)

**Comment by itzzenxx** [comment]
Here's two other posts as well

Post 2: 
![image](https://github.com/mastodon/mastodon/assets/81382281/ce005f94-89e1-45a6-b30f-3ef961e177d4)
Notifications for Post 2:
![image](https://github.com/mastodon/mastodon/assets/81382281/470b8dfa-a6bc-41e5-81d6-17fdaa382440)

Post 3: 
![image](https://github.com/mastodon/mastodon/assets/81382281/fc3a71f8-fa41-40bb-9b4b-46be3ef010c4)
Notifications for Post 3: 
![image](https://github.com/mastodon/mastodon/assets/81382281/7e1bc3e2-4e2d-406a-bab2-6713d7e7407a)

**Comment by itzzenxx** [comment]
Also, post interactions also are affected:

Favorites for a post:
![image](https://github.com/mastodon/mastodon/assets/81382281/071bb465-bf8e-464a-aa4d-2b23f1bedbe3)
Notifications for that post:
![image](https://github.com/mastodon/mastodon/assets/81382281/07b2197e-b347-4eaf-b454-9a7d33243a31)

**Comment by ClearlyClaire** [comment]
Is there any error in the `mastodon-sidekiq` logs?

**Comment by itzzenxx** [comment]
Nothing out of the ordinary in sidekiq logs it seems

**Comment by ShadowJonathan** [comment]
Are any of these servers muted/silenced/limited on an instance level, per-chance?

**Comment by itzzenxx** [comment]
No, none of these instances are limited, nor are their users.

**Comment by ShadowJonathan** [comment]
I'm curious if the notification worker is bypassing the dead queue, I know I had to add a commit to our server to have the backup worker go to the dead jobs queue, since upstream mastodon added a flag to remove that

**Comment by itzzenxx** [comment]
> I know I had to add a commit to our server to have the backup worker go to the dead jobs queue, since upstream mastodon added a flag to bypass that

Is it possible for us to add this to our server and see if it solves anything?

**Comment by ClearlyClaire** [comment]
Failed `LocalNotificationWorker` jobs end up in the dead queue, but I fail to see the relevance here.

**Comment by itzzenxx** [comment]
Of course the thing I don't suspect was the cause, it was with our redis setup and something not working I guess. I managed to fix it by switching it out with dragonflydb and now the notifications seem to be working correctly.
