### ISSUE TITLE
Notifications do not update in real time for old versions of Safari since update to ver 4.2.0

### ISSUE THREAD

**Issue by WSCP-GH** [mastodon/mastodon#27227]
### Steps to reproduce the problem

1. Before ver 4.2.0 notifications and mentions automatically refreshed in Safari.
2. I would see the count of notifications I'd not checked.
3. When I clicked on Notifications tab/link I would see the new notifications.4. 
...
Now none of this happens unless I manually refresh the page.

Note: Posts/Home timeline continues to automatically refresh (only Notifications is affected.)

### Expected behaviour

Notifications automatically pushed to Safari

### Actual behaviour

I have to manually click the reload icon to see notifications.

### Detailed description

1. Before ver 4.2.0 notifications and mentions automatically refreshed in Safari.
2. I would see the count of notifications I'd not checked next to the Notifications link.
3. When I clicked on Notifications tab/link I would see the new notifications.
...
Now none of this happens unless I manually click the reload icon to refresh the page. 
Home and Live Feeds update automatically, just not Notifications.

### Mastodon instance

techhub.social

### Mastodon version

v 4.2.0

### Browser name and version

Safari Version 14.1.2 (14611.3.10.1.7)

### Operating system

macOS 10.14.6

**Comment by ClearlyClaire** [comment]
This does not seem related to push notifications, but to websocket. Do you have any error in your browser's console?

In the case you are an admin of your server, can you check that `mastodon-streaming` is running, and whether there are errors in its logs?

**Comment by WSCP-GH** [comment]
You may be right, but I don't know how to fix it as it worked before 4.2.0

This is the console msg: "WebSocket network error: The operation couldn’t be completed. Socket is not connected"

I'm just a user, not an admin. Restarting the computer didn't make any difference. I did a search on web socket not connected in Safari and none of the explanations that I could understand helped—I saw a couple places a recommendation to enable NSURLSession websocket in the Developer/Experimental menu in Safari, but that option is not available.

**Comment by ClearlyClaire** [comment]
It sounds like a deployment issue on your instance's side. It's probably best to reach out to your admins.

**Comment by WSCP-GH** [comment]
I've exchanged a number of messages with my instance admin. He believes if it was a deployment issue it would show up for other users and platforms. Seems it's only a problem with (my?) Safari. Which is puzzling as the other timelines in the web app in Safari, Home and Live Feeds, are auto updating just fine which he says also use the web socket. He thought it was auth related, but logging out and back in didn't help (plus I've been receiving Private Mentions, etc, just not until I do a manual refresh of the page.) However, something changed with 4.2.0 to break auto update of Notifications for me.

**Comment by nicdex** [comment]
I am the admin of the mentioned instance.

I have no error in my mastodon-streaming logs except "... Error: Missing access token", this is why I thought it could be auth related. i.e.
```
Oct 04 23:14:27 web1 node[2545993]: ERR! df25c390-9420-43d3-9be7-xxxxxxxxxxxx Error: Missing access token
```
I also looked at my access logs using the user latest IP and I find working websocket connections.
```
X.X.X.X - - [03/Oct/2023:00:XX:XX +0000] "GET /api/v1/streaming?access_token=XTOKENX&stream=user HTTP/1.1" 101 27132 "-" "-"
X.X.X.X - - [03/Oct/2023:00:XX:XX +0000] "GET /api/v1/streaming?access_token=XTOKENX&stream=user HTTP/1.1" 101 33768 "-" "-"
X.X.X.X - - [03/Oct/2023:00:XX:XX +0000] "GET /api/v1/streaming/? HTTP/1.1" 101 60864 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15"
X.X.X.X - - [03/Oct/2023:12:XX:XX +0000] "GET /api/v1/streaming/? HTTP/1.1" 101 2 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15"
X.X.X.X - - [03/Oct/2023:15:XX:XX +0000] "GET /api/v1/streaming/? HTTP/1.1" 101 1704221 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15"
X.X.X.X - - [03/Oct/2023:15:XX:XX +0000] "GET /api/v1/streaming/? HTTP/1.1" 101 160262 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15"
X.X.X.X - - [03/Oct/2023:16:XX:XX +0000] "GET /api/v1/streaming/? HTTP/1.1" 101 248448 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15"
X.X.X.X - - [03/Oct/2023:17:XX:XX +0000] "GET /api/v1/streaming/? HTTP/1.1" 101 303893 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15"
X.X.X.X - - [03/Oct/2023:17:XX:XX +0000] "GET /api/v1/streaming/? HTTP/1.1" 101 289004 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15"
X.X.X.X - - [03/Oct/2023:18:XX:XX +0000] "GET /api/v1/streaming?access_token=XTOKENX&stream=user HTTP/1.1" 101 2288452 "-" "-"
```
So the websocket error might be unrelated.

**Comment by ClearlyClaire** [comment]
The `/api/v1/streaming?access_token=XTOKENX&stream=user` bits are weird, or at least they shouldn't be coming from the Mastodon Web UI. I suppose this could be another client doing that.

The other log entries look fine.

I'm not sure what could be causing the “WebSocket network error: The operation couldn’t be completed. Socket is not connected” client-side error, and I don't think we have changed anything related to that recently. I'll keep looking!

**Comment by Jerry-infosecexchange** [comment]
I have 3 people reporting the same thing on my instance. I have been assuming it was something unique to their configuration since it seems to work fine for most others, I see no errors, I am wholly unable to reproduce the problem.

**Comment by ClearlyClaire** [comment]
@Jerry-infosecexchange do you know which browser they use?

@WSCP-GH is there anything else in your browser console? Is there any stack trace you can share?

**Comment by Jerry-infosecexchange** [comment]
Note: I tried brave on an iPad and did not have the issue.

**Comment by ThisIsMissEm** [comment]
We made no changes to authentication between the latest 4.1.x release and 4.2.0, as far as I recall?

> The /api/v1/streaming?access_token=XTOKENX&stream=user bits are weird, or at least they shouldn't be coming from the Mastodon Web UI. I suppose this could be another client doing that.

@ClearlyClaire this looks like an eventsource connection.. but the 101 says it's websockets; the server isn't actually fussy as to how parameters are supplied, rather confusingly (docs say only two methods of passing them works, but in practice it accepts everything).

How we establish connections would be a good candidate to refactor & clean up in 4.3 or sooner (e.g., moving to signed tokens), but that'll be a breaking API change, so a `/api/v2/streaming` endpoint, I guess?

It could be that Brave / Safari or a firewall is doing something weird with the Sec-WebSocket-Protocol header (because we currently use the access token for that value & not actually a registered websocket subprotocol)

**Comment by ThisIsMissEm** [comment]
Those user agents also don't identify as Brave? Which from what I can tell is meant to include the word "Brave" — I was looking to see if there was a specific software version, like an outdated browser, that may be buggy?

**Comment by ClearlyClaire** [comment]
> @ClearlyClaire this looks like an eventsource connection.. but the 101 says it's websockets; the server isn't actually fussy as to how parameters are supplied, rather confusingly (docs say only two methods of passing them works, but in practice it accepts everything).

I think it's a third-party client, the EventSource codepath wouldn't trigger in this case.

> Those user agents also don't identify as Brave? Which from what I can tell is meant to include the word "Brave"

Those are logs about the original poster, which is using Safari (and likely also a third-party client).

**Comment by ThisIsMissEm** [comment]
What could also help is getting users to share details from http://www.supportdetails.net/ (yes, I know it's not https, it's just the only tool I know that does the same thing)

**Comment by Jerry-infosecexchange** [comment]
One thing to note: for one of the 3 people having the issue, I was able to confirm that their home and “all” timelines were feeding real time updates. The issue seemed constrained to just notifications.

**Comment by ThisIsMissEm** [comment]
> > @ClearlyClaire this looks like an eventsource connection.. but the 101 says it's websockets; the server isn't actually fussy as to how parameters are supplied, rather confusingly (docs say only two methods of passing them works, but in practice it accepts everything).
> 
> I think it's a third-party client, the EventSource codepath wouldn't trigger in this case.
> 
> > Those user agents also don't identify as Brave? Which from what I can tell is meant to include the word "Brave"
> 
> Those are logs about the original poster, who is using Safari (and likely also a third-party client).

Ah! Okay! It could be an issue with the browser & operating system being out of date & no longer supported by Apple but I'm doubtful anything in 4.2.0 would break that? 

(i.e., it might be hard to reproduce due to the specific software versions)

We did start closing WebSocket connections that sent us binary data (instead of text data).

**Comment by ThisIsMissEm** [comment]
> One thing to note: for one of the 3 people having the issue, I was able to confirm that their home and “all” timelines were feeding real time updates. The issue seemed constrained to just notifications.

Okay, this is really weird @Jerry-infosecexchange, because it's all the same connection logic, there's no difference between the types of connection & if we'd somehow broken notifications, we'd know about it from everyone.

**Comment by Jerry-infosecexchange** [comment]
It would be good to have the others with the problem in this thread confirm this is the case.

**Comment by ClearlyClaire** [comment]
Ok, so your case at least seems to be because of running an outdated browser.

> I hope I'm not "very outdated." I am stuck with an older OS due to software I need for my business that is incompatible with new versions of macOS unfortunately. Sigh.

Support for Safari 14 seems to have been discontinued in 2021, and while I am not familiar with Apple's security policies, my understanding is that it has multiple known unpatched critical security vulnerabilities. I would encourage you to update in a way or another.

**Comment by WSCP-GH** [comment]
I understand your position, but I hoped the development team would provide more backward compatibility than commercial software for a 2 year old browser. 

Thanks for your time looking into this issue.

**Comment by ThisIsMissEm** [comment]
> I understand your position, but I hoped the development team would provide more backward compatibility than commercial software for a 2 year old browser.
> 
> Thanks for your time looking into this issue.

The problem isn't so much a desire not to support backwards compatibility, but just, as we're all on newer systems we can't actually reproduce / debug the problem, if we can't reproduce it, then there's not anything we can do to fix it.

It shouldn't have broken, but I'm not sure why it would have.

**Comment by ClearlyClaire** [comment]
@ThisIsMissEm this is not a websocket issue—the websocket error probably was a transient issue—, it's our code using `Object.hasOwn` in a couple places, and in particular in `app/javascript/mastodon/store/middlewares/sounds.ts`, which runs on incoming notifications. `Object.hasOwn` is supported on all major maintained browsers versions, but it's not supported in older unmaintained versions like Safari 14.1.2.

**Comment by ThisIsMissEm** [comment]
> @ThisIsMissEm this is not a websocket issue—the websocket error probably was a transient issue—, it's our code using `Object.hasOwn` in a couple places, and in particular in `app/javascript/mastodon/store/middlewares/sounds.ts`, which runs on incoming notifications. `Object.hasOwn` is supported on all major maintained browsers versions, but it's not supported in older unmaintained versions like Safari 14.1.2.

Ah, okay @ClearlyClaire! So that file changed between 4.1.x and 4.2.x and hence the bug was created.

**Comment by ThisIsMissEm** [comment]
@ClearlyClaire the base polyfills may also be broken because of this: https://github.com/mastodon/mastodon/blob/main/app/javascript/mastodon/polyfills/base_polyfills.ts#L7

 #27289

**Comment by ThisIsMissEm** [comment]
Will be fixed by #27289

**Comment by ClearlyClaire** [comment]
We have decided not to add support for browsers that old.

**Comment by ThisIsMissEm** [comment]
@ClearlyClaire would it be wise to add a ticket saying "hey, sorry, to use Mastodon, you'll need to upgrade to a more modern browser?" for these cases?
