### ISSUE TITLE
LinkCrawlWorker does not handle non-UTF8 charsets

### ISSUE THREAD

**Issue by ShadowJonathan** [mastodon/mastodon#27230]
### Steps to reproduce the problem

1. Post or receive a status with https://www.worldconcerthall.com/en/schedule/herrmann_korngold_with_lamsma_wagner_and_kodaly_from_rotterdam/77834/ in it

### Expected behaviour

The `LinkCrawlWorker` will fetch the URL properly

### Actual behaviour

The `LinkCrawlWorker` crashes with "ArgumentError: invalid byte sequence in UTF-8"

### Detailed description

When looking at the above URL, the headers indicate `content-type: text/html; charset=ISO-8859-1`, a non-UTF8 charset.

We have around hundreds of these dead workers littering the dead worker queue, and nearly every one of them failed in this similar fashion. I think it's a fixable problem, so i'm reporting it here.

### Mastodon instance

tech.lgbt

### Mastodon version

v4.2.0-rc2+glitch

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
- Node.js version: v18.12.1

**Comment by pegli** [comment]
Also happening on my server running 4.2.0 release:
* Ruby version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
* Node.js version: v20.6.1

**Comment by ShadowJonathan** [comment]
Digging a bit, there does seem to be code that's supposed to detect charset and set up a chunker for that charset, but then i'm confused if it misses that code somewhere along the way.

**Comment by jmrplens** [comment]
Also in 4.3.0-alpha.0 (AKA Main branch):

- Ruby 3.2.2p53 +YJIT
- PostgreSQL 16.0
- Redis 7.2.2 (Main, Cache and Sidekiq in separate services and 2 replica each)
- Tested with Node 20 and 21
- Elasticsearch 7.17.14

**Comment by vmstan** [comment]
Also see these in my instance.

**Comment by vmstan** [comment]
I think I have a possible fix that checks the encoding and re-encodes to UTF-8 if it's not. I was able to generate a link preview for that particular link you shared where it doesn't before, and I haven't seen any of the UTF-8 errors for a while. Need to play with it some more though.

<img width="571" alt="image" src="https://github.com/mastodon/mastodon/assets/3002053/ece71962-27ae-4e68-95f9-582ddaaffbfd">

**Comment by StrangeMinds1960** [comment]
Has anyone got any further than this?  I see a good percentage of this error in my dead queue (running v4.2.8)

**Comment by oneiros** [comment]
@vmstan Any luck with your possible fix? Otherwise I might take a look into this.
