### ISSUE TITLE
Account moderation filter dropdowns do not revert to previous values after applying a filter and then using web browser back button

### ISSUE THREAD

**Issue by colinstu12** [mastodon/mastodon#27236]
### Steps to reproduce the problem

1. From Mastodon web site, navigate to Settings > Moderation > Accounts
2. Change the Location dropdown from Local to Remote (it will then apply the filter and return correct results)
3. Press the browser's back button (or alt + left arrow, or backspace if supported)
4. It will then return the previous filter's results, yet the dropdown still says what was previously applied

I haven't tested this with all the dropdowns and fields, but one would expect that the currently applied filter would match up with the returned results. I can see the URL is obviously changing and returning the relevant results, but the filter UI is not refreshing/updating. 

### Expected behaviour

One would expect that the currently applied filter would match up with the returned results. 

### Actual behaviour

Filter isn't updated to reflect the results that are now returned (and updated URL after using back button)

### Mastodon instance

birdbutt.com

### Mastodon version

v4.2.0

### Browser name and version

Chrome 117

### Operating system

macOS 14.0

**Comment by ThisIsMissEm** [comment]
I can't reproduce this with the steps provided on `main`, could you test on a newer version of Mastodon to see if this has been resolved?

@vmstan could we apply the `status/needs additional details` label to this issue? (perhaps we need a "pending closure" or "awaiting commenter" or something labels.

**Comment by colinstu12** [comment]
> could you test on a newer version of Mastodon to see if this has been resolved?

Just retested it, verified that I couldn't recreate it either anymore, seems to be resolved now. Closing.
