### ISSUE TITLE
Feature: Syntax to filter original posts by a single user by tags

### ISSUE THREAD

**Issue by azbulutlu** [mastodon/mastodon#2723]
How would it work?
a variation of a tag (e.g. #tag@username@server) and/or a url (https://server/@username/#tag) 
Only posts and replies by this user would show (depending on the viewer's access to private posts). 
Posts by others that has the tag that the user boosted would not show.

Use cases:
An artist links to this tag or url on their profile to give quick access to all their art posts
An artist or any user can categorize their posts using personal tags and give links to view their writing/art on individual categories
Finding a user's other posts in a popularly used tag
A user who posts and boosts a lot can quickly find something they posted a few days ago on a specific topic

other relevant issues:
#2331: having a tag viewing as default could add to this feature. 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
This has been added with @user/tagged/tagname now, right?

**Comment by azbulutlu** [comment]
yes it has and thank you
