### ISSUE TITLE
bug: image does not downscale

### ISSUE THREAD

**Issue by Ahwxorg** [mastodon/mastodon#27252]
### Steps to reproduce the problem

1. Go to edit your user profile (banner image)
2. Upload an image that's a higher resolution than supported
3. Get an error, see:

![image](https://github.com/mastodon/mastodon/assets/87855602/b74d8ca8-35d3-4b03-a56c-2bc0c61e455a)

### Expected behaviour

Mastodon should downscale the image

### Actual behaviour

Mastodon threw an error

### Mastodon instance

social.ahwx.org

### Mastodon version

v4.1.9

### Browser name and version

114.0.5735.198 (Official Build, ungoogled-chromium) (arm64)

### Operating system

macOS 13.5.2

**Comment by Ahwxorg** [comment]
It might be an issue on my side, I'd like to know!

**Comment by lamemakes** [comment]
Hey! I just retried this with the latest version of Mastodon and couldn't recreate. It seems like it properly downscaled and saved. All images I tried were larger than the 400x400.

**Comment by Ahwxorg** [comment]
I'll upgrade and try again. Thanks.

**Comment by vmstan** [comment]
> I'll upgrade and try again. Thanks.

Did the upgrade resolve this for you?

**Comment by Ahwxorg** [comment]
I was clearing my GitHub notifications and stumbled upon this. I've since closed my personal instance and moved to a public instance, since Mastodon was hard to host behind multiple proxies. Sorry for not following up on this!
