### ISSUE TITLE
https://mastodon.social/relationships?activity=dormant consistently results in an error page

### ISSUE THREAD

**Issue by juancnuno** [mastodon/mastodon#27288]
### Steps to reproduce the problem

1. Navigate to https://mastodon.social/relationships?activity=dormant I usually do it via Preferences - Follows and followers - Dormant
2. See the "We're sorry, but something went wrong on our end." error page

### Expected behaviour

A list of dormant people that I'm following

### Actual behaviour

An error page

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.1-rc1+pr-27261-37da69c

### Browser name and version

Google Chrome Version 117.0.5938.132 (Official Build) (64-bit)

### Operating system

Debian

**Comment by ClearlyClaire** [comment]
Thanks for the report! This appears to be a regression from #27116, going to investigate and fix it.
