### ISSUE TITLE
Add Elasticsearch storage to administrator dashboard

### ISSUE THREAD

**Issue by vmstan** [mastodon/mastodon#27292]
### Pitch

4.2 added public full text search with dependencies on Elasticsearch, which greatly increased possible growth of the Elasticsearch databases compared to previous versions. 4.2 also added many great health check metrics and version detection for ES into the administrator dashboard. One area where it did not add any monitoring was storage usage.

Currently the easiest way to monitor size of the ES databases is through `/_cat/indices?v` but administrators who either aren't familiar with, lack other tooling, or too busy to check this regularly may run into a condition where their ES database fills up available space without proper monitoring.

(Side note, just in writing this request, I had noticed that the `pri.store.size` value for the `public_statuses` index had nearly doubled in size since the last time I looked at it, only a few days ago.)

I would propose adding a monitor which provided a total of the primary indexes listed at this API endpoint.

![CleanShot 2023-10-05 at 09 58 34@2x](https://github.com/mastodon/mastodon/assets/3002053/92fe465a-36f3-4351-9225-059745cfe5a9)

Total is roughly 3.7GB

![CleanShot 2023-10-05 at 10 05 44@2x](https://github.com/mastodon/mastodon/assets/3002053/d0152bff-fd97-4a7d-bdad-731c2dda61f8)

### Motivation

All administrators using Elasticsearch would benefit from this addition.

**Comment by renchap** [comment]
You probably want `store.size` here, as this represents the total storage, including replicas. Or maybe both, but I am not sure how to display it.

PR welcome for this :)

**Comment by vmstan** [comment]
> You probably want `store.size` here, as this represents the total storage, including replicas. Or maybe both, but I am not sure how to display it.

I wasn't sure if `store.size` would be correct, as the other components don't really factor in replicas.

> PR welcome for this :)

I'm thinking about it ;)
