### ISSUE TITLE
Mastodon 4.2.x randomly truncates posts coming in from at least Hubzilla

### ISSUE THREAD

**Issue by JupiterRowland** [mastodon/mastodon#27305]
### Steps to reproduce the problem

1. Have a Hubzilla channel with PubCrawl on and connections on mastodon.social as an example of an instance that runs at least Mastodon 4.2.0.
2. Create a post on Hubzilla, preferably one that's significantly longer than 500 characters. Add at least one not-too-common hashtag so it can be found more easily.
3. Go to `https://mastodon.social/tags/<the hashtag used in the post>` in the Web browser of your choice (tested with the original Mozilla build of Firefox on Debian GNU/Linux).
4. Scroll down until you find your post.
5. Compare how mastodon.social renders your post with what your original Hubzilla post looks like.

### Expected behaviour

The full post text is always shown on Mastodon.

### Actual behaviour

Chances are the post is truncated and incomplete.

### Detailed description

Since Mastodon 4.2.0 was released, it seems to randomly truncate posts from at least Hubzilla. It does so both to posts that came in after the upgrade of an instance to 4.2.x and to posts that have been on an instance before the 4.2.x upgrade.

It doesn't happen to each post. It happens both to Hubzilla posts (first posts in a thread) and to Hubzilla comments (replies to posts which are something different on Hubzilla), and it happens to comments on both Mastodon and Hubzilla posts.

Also, even truncated posts can still be over 500 characters long on instances that only allow for 500 characters. And posts that are well under 500 characters are truncated, too.

There seems to be no pattern. There is nothing that indicates when and why a post is truncated, other than all truncated posts I know about have hashtags in the text rather than all hashtags at the end or no hashtags at all. Also, Hubzilla posts with summaries that became/become Mastodon posts with content warnings seem to never be truncated.

That said, posts are never truncated in the middle of a word.

The issue clearly lies on Mastodon's side. It started happening with the release of Mastodon 4.2.0 while Hubzilla did not have a new release at that time. Also, Mastodon 4.1.9 shows posts perfectly fine which Mastodon 4.2.0 truncates.

Here is a proof, although it's a minor example.

Original Hubzilla comment:
https://hub.netzgemeinde.eu/display/b64.aHR0cHM6Ly9odWIubmV0emdlbWVpbmRlLmV1L2l0ZW0vMzU0NTJkMmQtNDI0OC00NjI5LTg3MjgtZWE0YTlhOWIyNDBk
Mastodon 4.1.9 (noc.social) showing the whole post:
https://noc.social/@MarvinTheMartian/111115829359100943 (scroll down to my post)
Mastodon 4.2.0 (tooters.org), full stop at the end of the last sentence is missing:
https://tooters.org/@victor/111115391740487664 (scroll down to my post)

More examples can be found by [searching mastodon.social for the hashtag #ImageDescription](https://mastodon.social/tags/imagedescription) and finding at my posts. For example:

Original Hubzilla comment, very short even:
https://hub.netzgemeinde.eu/display/b64.aHR0cHM6Ly9odWIubmV0emdlbWVpbmRlLmV1L2l0ZW0vYWFjOWE2YTUtZTc1Zi00Njc5LWFiNjgtNGYyYzI5ZDJmMjI5
Mastodon 4.2.0 (mastodon.hardcoredevs.com), truncated mid-paragraph after the hashtag `#ImageDescription`:
https://mastodon.hardcoredevs.com/@Andres/110894302610589500 (my comment is right below)
This is a special case because the whole thread was written before Mastodon 4.2.0.

Original Hubzilla comment:
https://hub.netzgemeinde.eu/display/b64.aHR0cHM6Ly9odWIubmV0emdlbWVpbmRlLmV1L2l0ZW0vOGYxYTQwMTUtNTc0Zi00YzEzLThkZTMtNDdhN2ViNGVjYjc1
Mastodon 4.2.1-rc1+pr-27261-37da69c (mastodon.social), entire second paragraph is missing:
https://mastodon.social/@hikingdude/111091316259559387 (my comment is right below)

Original Hubzilla comment:
https://hub.netzgemeinde.eu/display/b64.aHR0cHM6Ly9odWIubmV0emdlbWVpbmRlLmV1L2l0ZW0vMDAyMDk4MjgtM2VjOC00MDUwLTlhN2QtMmIzM2M2Njk3OWVj
Mastodon 4.2.1-rc1+pr-27261-37da69c (mastodon.social), truncated mid-paragraph after the hashtag `#Friendica`:
https://mastodon.social/@urlyman/111028486166963680 (my comment is right below)

Original Hubzilla comment:
https://hub.netzgemeinde.eu/channel/jupiter_rowland?mid=b64.aHR0cHM6Ly9odWIubmV0emdlbWVpbmRlLmV1L2l0ZW0vZDIzY2NkMjItMzUzNy00ODI4LWEzMDgtYjQ5YjY0MGU5MTQx
Mastodon 4.2.0 (ieji.de), truncated mid-paragraph after the hashtag `#AltText`:
https://ieji.de/@soonix/111008439620893974 (my comment is right below)

It also happens to Hubzilla posts. I don't have an example of a Hubzilla post truncated on Mastodon that can be seen by scrolling up from a Mastodon reply, but here is an example with a raw Mastodon link (which will open Hubzilla in a Web browser, though):

Original Hubzilla post:
https://hub.netzgemeinde.eu/channel/jupiter_rowland?mid=b64.aHR0cHM6Ly9odWIubmV0emdlbWVpbmRlLmV1L2l0ZW0vMTM2MmE1NmUtYzU0Ny00MDU4LTgxZGMtNTRiZmMzMzgxNDVh
Mastodon 4.2.1-rc1+pr-27261-37da69c (mastodon.social), the last paragraph is missing:
https://mastodon.social/@jupiter_rowland@hub.netzgemeinde.eu/111158674653031871

The same may happen to posts from other projects, especially Friendica and (streams). I don't have any evidence of this happening or not happening yet.

Also, I can't test this on mobile apps, so I can't say if this is a Web interface or backend issue.

### Mastodon instance

mastodon.social, fosstodon.org, norden.social, tooters.org, ieji.de, mastodon.hardcoredevs.com

### Mastodon version

v4.2.0, v4.2.1-rc1+pr-27261-37da69c

### Browser name and version

Firefox 118.0.1, original Mozilla build

### Operating system

Debian 13 "trixie" (testing)

**Comment by ClearlyClaire** [comment]
This looks like an issue with the client-side code handling the hashtag bar.

Direct mastodon.social link to one of the short posts exhibiting the issue, to ease reproduction: https://mastodon.social/@jupiter_rowland@hub.netzgemeinde.eu/111088353358864253
