### ISSUE TITLE
/api/v1/announcements seems to ignore parameter "with_dismissed"

### ISSUE THREAD

**Issue by cage2** [mastodon/mastodon#27310]
### Steps to reproduce the problem

1. just call the endpoint /api/v1/announcements without any parameter

### Expected behaviour

the announcements object with "read" attribute with value "true" should be removed from the results

### Actual behaviour

object are returned even if "read" attribute value is "true"

### Detailed description

Hi!

I already submitted this question to glitch but seems to me that mastodon could be also affected.

I do not know if I am doing it wrong (if yes, sorry!) but seems to me that the parameter "with_dismissed" is just ignored.

I was not able to find any reference to this issue in the bug report system here.

Bye!
C.

**Comment by cage2** [comment]
Hi @ClearlyClaire !

Thanks for your prompt reply!

Should I file an issue on https://github.com/mastodon/documentation about this?

Thanks!
C.

**Comment by ClearlyClaire** [comment]
Yes please!
