### ISSUE TITLE
Privacy: app you sent a post is displayed without checking the box "Display from which app you sent a post"

### ISSUE THREAD

**Issue by TinoJ** [mastodon/mastodon#27319]
### Steps to reproduce the problem

1. Post something from Sengi web client V1.6.0 and view it on v4.2.1-rc1+pr-27261-28c1753

### Expected behaviour

The information "Sengi" should not be displayed

### Actual behaviour

The client app information "Sengi" is displayed

### Mastodon instance

https://mastodon.online/

### Mastodon version

v4.2.1-rc1+pr-27261-28c1753

### Browser name and version

Chrome Version 117.0.5938.150 (Offizieller Build) (32-Bit

### Operating system

Win11

![2023-10-07_16-47-41-Privacy and reach - Mastodon](https://github.com/mastodon/mastodon/assets/18018490/6e7bb654-7b3d-4edc-9179-02d00c2f581a)
![2023-10-07_16-43-47-Post](https://github.com/mastodon/mastodon/assets/18018490/4de124ba-74ca-4c0f-a96b-d9ca9f6a1f63)

**Comment by trwnh** [comment]
> You will always be able to see which app published your post regardless.

Are you logged in?

**Comment by TinoJ** [comment]
I checked again with checkbox enabled/disabled and login/logout scenarios and the function seems okay. Maybe I got fooled by an still existing session in the browser. Or I was just stupid. :) Thanks.
