### ISSUE TITLE
Clarify in UI when toot will be automatically collapsed!

### ISSUE THREAD

**Issue by eobet** [mastodon/mastodon#27329]
### Pitch

Just as with the character count which ticks down as you type there should be a warning when you have made a toot that’s so long that it will automatically be presented as collapsed in the web timeline!

### Motivation

Nobody probably reads collapsed toots (at least I know I don’t unless I use an app which never collapses anything), as you can’t even fully make out a single line of text from them and you don’t even see if they contain any pictures without expanding them first (and the target for expanding them is very, very tiny unlike a CW even).

(I honestly can’t understand the reasoning why long toots get punished by being presented using _even less space_ than regular toots!)

**Comment by ClearlyClaire** [comment]
Is this about Mastodon proper, about a fork (e.g. glitch-soc), or about an app?

**Comment by eobet** [comment]
Oh! Sorry... you're right it appears to be a glitch-soc feature.
