### ISSUE TITLE
Releasenotes: Missing Ruby-Version in typescript

### ISSUE THREAD

**Issue by ilsd** [mastodon/mastodon#27346]
### Steps to reproduce the problem

1. Open https://github.com/mastodon/mastodon/releases/tag/v4.2.0
2. Scroll down to _Update steps_
3. Read _Non-Docker only: 0. … RUBY_CONFIGURE_OPTS=--with-jemalloc rbenv install_ 
...

### Expected behaviour

Should be: `RUBY_CONFIGURE_OPTS=--with-jemalloc rbenv install 3.2.2`

### Actual behaviour

The Version `3.2.2` is missing

### Detailed description

At least in my case the missing ` 3.2.2` resulted in reinstalling 3.0.6.

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by renchap** [comment]
Were you in a directory with the code from v4.2.0 checked out?

`rbenv install` should use the version in `.ruby-version`, which is 3.2.2 for Mastodon v4.2.0

**Comment by ilsd** [comment]
No, probably not. IIRC I did the fetch later. Sorry for the false alarm and thanks for your comment!
