### ISSUE TITLE
API reports incorrect Version

### ISSUE THREAD

**Issue by chrisschm** [mastodon/mastodon#27367]
### Steps to reproduce the problem

After Update from 4.2.0 to 4.2.1 the **/api/v2/instance** still reports 4.2.0 while _/api/v1/instance_ is sending 4.2.1

### Expected behaviour

/api/v2/instance Version=4.2.1

### Actual behaviour

/api/v2/instance Version=4.2.0

### Mastodon instance

social.jcs-net.de

### Mastodon version

v4.2.1

### Technical details

- ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
- Node.js v16.20.2

**Comment by ClearlyClaire** [comment]
Those endpoints are cached for a few minutes.

**Comment by chrisschm** [comment]
> Those endpoints are cached for a few minutes.

I think this is the answer. v2 is reporting the correkt version without changes now. (close)

Thanks Claire
