### ISSUE TITLE
The onboarding quotas are completely arbitrary

### ISSUE THREAD

**Issue by Oreolek** [mastodon/mastodon#27362]
### Steps to reproduce the problem

(This is about the prompt introduced in #25267)

The prompt pops up when the home feed is not going fast enough. Problem is, I'm subscribed to English speakers - geographically mostly American and European. There is a clear lull hour, about 1pm GMT, when Americans are still sleepy and Europeans just don't post much, so the home feed is stalling.

### Expected behaviour

do not show this text for people who already know how to subscribe

### Actual behaviour

i see the toast

### Detailed description

My account is 6 years old, I'm subscribed to 900+ accounts, I'm perfectly fine catching up with the old posts. And every day, about the same time, I see this piece of condescending foolishness.

![1](https://github.com/mastodon/mastodon/assets/308627/79ced1fd-6301-45a2-9d5b-a5996a6bd019)

### Mastodon instance

icosahedron.website

### Mastodon version

v4.2.0

### Browser name and version

Librewolf 118

### Operating system

Arch Linux

**Comment by ClearlyClaire** [comment]
Hi! You should be able to click the cross to dismiss that banner for good.

**Comment by Oreolek** [comment]
Okay, here's another thing: see the "1 new item" below? When it goes to about 2 or 3, the popup hides itself along with the cross button. So I have to be quick enough to dismiss or it will nag me again. So far, I was not quick enough.

**Comment by ClearlyClaire** [comment]
Ah, there might also be inconsistent handling of slow mode, I'll try to look into it!

**Comment by lambda** [comment]
I suspect that this might be the same issue that I tracked down in #27197, and submitted PR #27466 for. Can you check to see if you can reproduce it the same way, by posting your own status which shows up in the "1 new item" pending statuses, and causes the explore prompt to pop up?

**Comment by ClearlyClaire** [comment]
Yes, I can confirm the issue, and also that it is addressed by your PR!
