### ISSUE TITLE
release notes for 4.2.1: minor link problem

### ISSUE THREAD

**Issue by jku** [mastodon/mastodon#27360]
### Steps to reproduce the problem

I was looking for upgrade instructions for 4.2.1. The release notes (https://github.com/mastodon/mastodon/releases/tag/v4.2.1) contain this:

>  if you're installing from an earlier version, please check the [4.2.0 release notes](https://github.com/mastodon/mastodon/releases/tag/v4.1.9) as they contain important information on how to update.

Link url is not for 4.2.0 but 4.1.9

### Expected behaviour

url should have been https://github.com/mastodon/mastodon/releases/tag/v4.2.0

### Actual behaviour

link url was https://github.com/mastodon/mastodon/releases/tag/v4.1.9

**Comment by ClearlyClaire** [comment]
Oops! Fixed, sorry about that!
