### ISSUE TITLE
Performance issues causing major costs for hosting (Inquiry)

### ISSUE THREAD

**Issue by ludiusvox** [mastodon/mastodon#27375]
### Steps to reproduce the problem

Jerry@infosec.exchange is having to spend thousands a month to host the Mastodon Framework.  His donations barely keep him afloat, the Ruby performance profile is about 400-440 requests per second per core.  This is a very under-performing rest API.  On the contrary, Rocket.rs can process 47,000 REST API requests per second.  Hyper.rs another less structured web framework is even faster with less security is about 75-85k REST API requests per second.  What needs to be done to refactor the code for an improved framework.

### Expected behaviour

I expected a higher performing stack

### Actual behaviour

It's very slow costing thousands of dollars in server upgrades

### Mastodon instance

infosec.exchange

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by steinhobelgruen** [comment]
With "refactor" you mean "rewrite in a different programming language"? Because both examples that you have given are for Rust.

**Comment by joenepraat** [comment]
I think this must be partly a configuration issue and partly that he uses very expensive hosting.

**Comment by ludiusvox** [comment]
Ruby is queried at 440 requests per second. Ruby has a GIL (Global Interpreter Lock), which means that it runs sequentially.

The two examples I gave are rust frameworks, but Java is a good language also that is multi threaded.

Java is a primary language for big enterprise SW development projects, being strongly typed and has its own garbage collector, a major framework being spring boot.

C# also has the swagger API framework that's work also that is multi threaded.

I previously suggested Rust.js because it's open source sponsored by the mozilla.org foundation and it's very fast about as fast as C language, and has more security on its headers.

I was just suggesting the Ruby is not a good backend sw for a social network use case, especially as the userbase grows and a better multithreaded language such as Java/C#/Rust.rs, in lieu of python or ruby for production code.

**Comment by Cassolotl** [comment]
You put "inquiry" in the title of this issue. What is your question?

**Comment by renchap** [comment]
Closing this as it is not actionnable. We can not change the programming language for Mastodon. We care a lot about performance, and each version bring major improvements on this front.

I have been personally in touch with Jerry from Infosec.exchange to help him reduce his costs.

**Comment by steinhobelgruen** [comment]
You *could* try to reimplement Mastodon in a different programming language on your own but actually it probably would make more sense to try one of the other implementations of ActivityPub like GoToSocial (written in golang) or to join a project that is already doing what you want to do like https://github.com/rustodon/rustodon

But neither will be quick wins.

**Comment by ludiusvox** [comment]
@steinhobelgruen that's really smart!  I am better off contributing with others every time because I am looking at this project I am just one person, there is 1000 people working on the main mastodon!

I like the concept of listener supported news and public radio I listen to, this project is very similar.

  But yeah I will try to help also, if you guys can bandaid Jerry because I don't think I can handle a project this scale by myself.  

I just started going through the controllers on GitHub this project is huge!

Thanks for the directions!
