### ISSUE TITLE
Change AcceptHeaders to solve issues with WebP and AVIF images in preview links

### ISSUE THREAD

**Issue by LeoEurope** [mastodon/mastodon#27370]
### Steps to reproduce the problem

1. Drop any of the links in https://github.com/mastodon/mastodon/issues/14983#issuecomment-1520594700 into a post
2. View the post in the web interface or an app
3. Notice that there is no preview
...

### Expected behaviour

To show a full preview card like it does for any other links

### Actual behaviour

The post only contains a link, without a link preview.

### Detailed description

Currently Mastodon doesn’t support OpenGraph images in WebP or AVIF format if those are sent in the OG:Image tag of a URL. A link will just show up as a link, without the full preview card. It’s not a web interface issue as those images aren’t imported, even if an app would support WebP or AVIF, the image simple isn’t there.

See https://github.com/mastodon/mastodon/issues/14983#issuecomment-1520594700 for a list of example URLs where this is not working.

Until the deeper lying issue of getting ImageMagick to fully support WebP and AVIF is solved, adding AcceptHeaders to explicitly allow image/jpg, image/png and image/gif as the only acceptable image formats would tell the web server to send a JPG, PNG or GIF instead. Most sites will comply.

That would solve most (but not all) of the issues around the problematic example URLs listed above.

As more and more websites are switching to serving WebP and AVIF this issue will become more and more common over time.

### Mastodon instance

mstn.social

### Mastodon version

4.2.0

**Comment by renchap** [comment]
I do not think that this is valid. Mastodon does not set any `Accept` headers when fetching a preview image, so the origin servers should fallback to the most common format, which is JPEG.

As replied in the linked issue, none of the URLs you mentioned are showing this problem.

**Comment by DamonHD** [comment]
Why not set an Accept header to allow more compact formats to be returned by the site when it has them available?  This would take the edge off the preview stampede for example.
