### ISSUE TITLE
Failed to setup dev env following README

### ISSUE THREAD

**Issue by igxlin** [mastodon/mastodon#27398]
### Steps to reproduce the problem

Simply follow the [Docker section](https://github.com/mastodon/mastodon?tab=readme-ov-file#docker) in the README file.

### Expected behaviour

Manage to set up dev environment and visit dev server

### Actual behaviour

Unable to finish the post create script

### Detailed description

There are some problems in the current setup guide and related scripts.

- The `.devcontainer/Dockerfile` doesn't indicate working directory. Thus `docker compose -f .devcontainer/docker-compose.yml exec app .devcontainer/post-create.sh` cannot find `.devcontainer/post-create.sh` from `/`.
- The mounted directory is not owned by docker. Thus `yarn` in the `post-create.sh` doesn't work.
- `bin/` in the project directory is not added into `PATH`. Thus `foreman start -f Procfile.dev` cannot find `webpack-dev-server`.

I found there was an existent PR (https://github.com/mastodon/mastodon/pull/26921) when I wanted to create one. Please help review and merge it to make the setup guide work.

Thanks.

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by KDederichs** [comment]
Same issue, it's just not working.

Even if you fix it by adding a workdir directive to the Dockerfile you'll just run into different issues (for some reason the RAILS_ENV is set to 'test' causing it to fail).

That section needs to be removed or actually be updated with working instructions.

**Comment by justjavac** [comment]
Same issue

**Comment by BrunoFenzl** [comment]
Same issue. I opened a similar one at #30213

**Comment by mjankowski** [comment]
Based on other similar feedback we did a bunch of updates to devcontainers a few months back and suspect that (for most people, most of time) they should be more or less equivalent to the native experience.

If that's NOT the case (on latest main) please re-open this with details...
