### ISSUE TITLE
Text does not display in gif/video link previews

### ISSUE THREAD

**Issue by jeremyjackson89** [mastodon/mastodon#27406]
### Steps to reproduce the problem

1. Make a post with some text and a gif/video.
2. Share the post somewhere else.
3. Only the gif/video is displayed in the link preview, losing any other context.

### Expected behaviour

I should see the post text along with gif/video.

### Actual behaviour

Only the gif/video is displayed.

### Detailed description

I've noticed this most recently when I've tried to share my own updates. As a user, it's frustrating to lose all context and it makes it harder to share things.

I've seen this behavior on:

- Discord
- iMessage/SMS
- LinkedIn

## Example:
I link to this post https://mastodon.social/@jeremyjackson/111234168452232253

It looks likes like this on mastodon.social:

![Screenshot 2023-10-14 at 1 02 46 PM](https://github.com/mastodon/mastodon/assets/8271117/7b4835cb-d88d-45c2-bbaf-09d1021a885f)

However, it looks like this everywhere else:

![Screenshot 2023-10-14 at 1 00 56 PM](https://github.com/mastodon/mastodon/assets/8271117/9534b848-269a-48d2-b6d4-045523e7b779)

All context and information is lost to anyone who doesn't click the link and the preview makes it look like that the post only contains the gif/video, so why would someone bother clicking the link at that point? Every time something like this is shared it'd have to be paired with a "please click the link" message _or_ the post content itself (which would make sharing the link in the first place redundant).

Apologies if this is not the correct label or if this the fault of the other platforms 🙇‍♂️ 

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.1

**Comment by Gargron** [comment]
This is a Discord issue, nothing we can do about it. They choose not to print `og:description` when there's `og:video`. Websites like fxtwitter fix a similar issue by putting the text of the post in `og:title` instead (which is what gets printed as bold blue text on Discord) but I wouldn't want to resort to a hack like that.

**Comment by jeremyjackson89** [comment]
> This is a Discord issue, nothing we can do about it. They choose not to print `og:description` when there's `og:video`. Websites like fxtwitter fix a similar issue by putting the text of the post in `og:title` instead (which is what gets printed as bold blue text on Discord) but I wouldn't want to resort to a hack like that.

Ah, ok. My apologies then. Thanks for the info 🙇‍♂️
