### ISSUE TITLE
Back button should close models and not navigate away

### ISSUE THREAD

**Issue by edlerd** [mastodon/mastodon#27422]
### Steps to reproduce the problem

1. Open a toot with an image
2. Click the image

### Expected behaviour

The back link of the browser should close the zoomed view

### Actual behaviour

the back link navigates away.

### Detailed description

* opening the zoomed image should add to the browser history (closing should go back in history).

This behaviour is desired for any modal that is opened (the back button should close the modal and not navigate away.

### Mastodon instance

mastodon.social

### Mastodon version

v4.1.2

### Browser name and version

Chrome 117.0.5938.149

### Operating system

Ubuntu 22.04

**Comment by edlerd** [comment]
I would like to work on this issue.

**Comment by edlerd** [comment]
That's true I can now use the back button on the Dev branch and even on mastodon.social.
Sorry for the confusion. I wonder if this was recently changed?

**Comment by ClearlyClaire** [comment]
No, this has been like this for years. Please reopen if you run into any issue though!
