### ISSUE TITLE
Going back to "Explore" after opening post moves back to a random place

### ISSUE THREAD

**Issue by JCWasmx86** [mastodon/mastodon#27451]
### Steps to reproduce the problem

1. Go to "Explore": https://mastodon.social/explore
2. Click some post
3. Go back. (Either browser back-button, or two-finger swipe on the touchpad)

### Expected behaviour

I should end up at the place where I left

### Actual behaviour

I'm somewhere at the top of the page

### Detailed description

See this video:

[Screencast from 2023-10-17 19-39-39.webm](https://github.com/mastodon/mastodon/assets/63594136/c96f13d0-1aad-4d02-91a2-772bbd4b9fe5)

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.1

### Browser name and version

Firefox 118.0.2

### Operating system

Fedora 38

**Comment by vmstan** [comment]
I am unable to reproduce this behavior in either Firefox 118 or Safari 17.

**Comment by Gargron** [comment]
No, it’s absolutely a thing and very annoying. The view reloads when you navigate back to it, so items change positions even as your scroll position remains the same.

**Comment by vmstan** [comment]
Won't argue with you :) I wonder if maybe there's a browser cache/memory threshold that causes it to start then, as I even tried on Linux with Firefox and couldn't get it to happen but I was only poking at it for 5 minutes with each config.

**Comment by Gargron** [comment]
The trending posts have to actually change between when you view the screen first and then return to notice the issue.
