### ISSUE TITLE
soft returns in content warning

### ISSUE THREAD

**Issue by bosonno** [mastodon/mastodon#27460]
### Pitch

everybody wants soft returns

### Motivation

i think you want soft returns too

**Comment by bosonno** [comment]
aka sweet return

**Comment by Informeli** [comment]
If my digital search is correct a soft return is a system to present automated linebreaks when a line becomes too long.
Does that match you definition?

**Comment by bosonno** [comment]
no i would call that a word wrap
i want to [shift]+[return]

**Comment by Informeli** [comment]
Thanks

**Comment by vmstan** [comment]
Closed for lack of clarity/context, please resubmit with more information if required.
