### ISSUE TITLE
`--verbose` option in `tootctl media remove` is not useable as the document state.

### ISSUE THREAD

**Issue by Lori3f6** [mastodon/mastodon#27506]
### Steps to reproduce the problem

1. run `tootctl media remove --verbose --dry-run` 

### Expected behaviour

Works as intended

### Actual behaviour

Error with feedback `ERROR: "tootctl media remove" was called with arguments ["--verbose"]`

### Mastodon instance

https://melon.blue

### Mastodon version

v4.2.1

### Technical details

tootsuite/mastodon:v4.2.1 docker bundle is used here.

```
mastodon@web:~$ tootctl media remove --verbose --dry-run
ERROR: "tootctl media remove" was called with arguments ["--verbose"]
Usage: "tootctl media remove"
```
which works not as the document state.
https://docs.joinmastodon.org/admin/tootctl/#media-remove
source:
https://github.com/mastodon/documentation/blob/master/content/en/admin/tootctl.md?plain=1#L664

Not sure this issue should be opened here or document side? 
Either add a `--verbose` function or change the document fixes the problem.

**Comment by danielmbrasil** [comment]
Hey, this was fixed in  #30536. I think this issue can be closed now.
