### ISSUE TITLE
More clearly show why a report was received

### ISSUE THREAD

**Issue by ThisIsMissEm** [mastodon/mastodon#27537]
### Pitch

In 4.2.0, a feature was introduced to forward reports to all the mentioned instances in a post, however, when receiving the report, it is unclear to the administrator why they've received it, since it looks to be between two remote users (reporter and reported account).

We should try to clarify in the UI why the instance admin has also received the report.

### Motivation

This will improve the clarity of the reporting interface given the new changes in 4.2.0 which have been a source of numerous questions and confusion.

**Comment by ClearlyClaire** [comment]
Would a banner like this work?
![image](https://github.com/mastodon/mastodon/assets/384364/76b0c27d-f893-4e35-8a08-c65532c0e052)

**Comment by ThisIsMissEm** [comment]
@ClearlyClaire yes, that was exactly what I was thinking.
