### ISSUE TITLE
autocomplete is disabled for home server prompt - UX barrier

### ISSUE THREAD

**Issue by ke352802081770314** [mastodon/mastodon#27532]
### Steps to reproduce the problem

1. use "open post on original server" on any nonlocal post, to see that post on its home server, or follow a link to a mastodon post not on my server
2. click on reply, favorite or similar interaction
3. observe that since 4.2 instead of an URL to click copy for pasting into your home server, a popup appears: "You are not logged in to this server. Where is your account hosted?" with an entry field below, how nice!
4. single-click into that entry field a couple of times, expecting that your home server will be suggested as an auto-completion because you've done this before - nothing happens
5. use the source inspection feature of your browser to find out that the entry field `<input type="text" placeholder="Domain of your home server, e.g. mastodon.social" aria-label="Domain of your home server, e.g. mastodon.social" autocomplete="off" autocapitalize="none" spellcheck="false" value="">` a) has autocomplete=off set and b) does not have a name attribute which may help the browser to identify the autocomplete scope specifically
...

### Expected behaviour

the input field should allow autocompletion, because my home server is neither particularly secret nor will it frequently change, so having to type it again and again obstructs using Mastodon as a fediverse instance

### Actual behaviour

as described above - autocompletion is explicitly suppressed by Mastodon

### Detailed description

all detail is included above. I consider this a bug because I cannot think of any reason for the current setting, but I am just as happy if it is considered a suggestion.

### Mastodon instance

mstdn.animexx.de

### Mastodon version

v4.2.0

### Browser name and version

Firefox 117.0.1

### Operating system

Linux Ubuntu 20.04LTS

**Comment by vmstan** [comment]
This was an intentional choice as during feature development it was highlighted that on mobile especially it broke the search interaction.

https://github.com/mastodon/mastodon/pull/26267#issuecomment-1659456098 has a video example
