### ISSUE TITLE
hash-tag bar appears on posts ending with (containing?) a link with a fragment

### ISSUE THREAD

**Issue by nabijaczleweli** [mastodon/mastodon#27552]
### Steps to reproduce the problem

1. post `lets go https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111895#c4`

### Expected behaviour

the post contains `lets go https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111895#c4`

### Actual behaviour

the post contains `lets go https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111895#c4`, then vertical space, then the hash-tag bar with `#c4` in it

### Detailed description

github is saying that "Something went really wrong, and we can't process that file. Try again." for my screenshot, and it's refusing to accept URLs with a data scheme, so here's a data URL with a scrussy to open separately via pasting: <data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA54AAAEqAQAAAABVMLIAAAAAAmJLR0QAAKqNIzIAAAAJcEhZcwAACxMAAAsTAQCanBgAAAfiSURBVHja7d3NTuNIAgfwsrxq94HBc0zUEB/2BYiQtkGb4HmAeQhakYbLiKaFNAoi3WUU7XIJ7StoaPIKjfrCqLMTt1jhC0uuHFZgFGl8GXUcRdo4il21VU6gE3oMgeCyNNRfAiWx5B/16Y9UCACPJ2+AaDFHPaB4rE3BAhBrrFFDxJh1/QqagrHHHMUkjOtXoCbr+u2hLn04yRhFvREbdRaGUNwbsVEHaxODqCbNd4zoa9XIXEP9yEsq6lZhGP37OxQ5+g/re9UbROemTyJHN5wJFQ2iHf8oalQqOhPzR4NolwFacybSR8NtGn314q9QH7FH573ohwy2hlEmU64XAwqwEQMKhyd8NujTOFDAUY5ydFxUFLbJ70XyM8sIRRQ9vUQ1Jqhga0AMXqHoDJuSihv6Yb257RbQ0klugVH1igs1u9XZ8RBa+m1VZYQ++en4h9nkTuloavmn1dUPjNAfjhdnp7e/MRI//u1/L1ihx98vtaZ3fGPuZesMMkOPl2and/5jrLysn8FZZujybPLn0tHi8l/3XrFC8fFSv/e2dlVW1QtLS63mjkfG6UWJ1ZDpzUYJthO++G/6bI7xUSa4qMjzg/hDX19c3dJhGHh184qHh4eHh4eHh+dannz1yjf0DDF5ABKi9ofbHwS9fnNjuo/OsUST1BIOwEyEqFpw5bql1ExDVbeNNwso6ZlqdecXN91yC0czkp14+HcznsDXnmw76nnNggSFKkp7JqzufHRzXQ/ZK1I7GQG6ul+aWp6bP/19JZfeNurpt+m35upm8mMi92zr6OXik+fJ0sOjuX2LoDOnE6BO0EOC/tN8sZk8SOQOt0yKPosAhe+9xHJiAH1B0LfJX9xPra1NgqrRoJnhklJ0N/nx1FjfMtesaEr6av5am168tVe3kx+Th6RN541o2hT+q997f4Pp8glMo08epr23U+yW0LwhtTreyemDj9MprzdOj9S0fvJmhqCQjlN/o1UqELTueif/jWCCeLoIBAP0b/vK9JHW+yHPHAAmIpn0ZQuoWv9tOIFOBfDLJqf3SgSoARTtcjkJXc6iDt2dcPmxmIeHh4eHhyfOQMwmgyc9gsWocKmBx70zTQaRbrznEFEELWZ0glmPNWJGnzJDv+MoRznKUY5ylKN/RlQtK0K3U5JrVZZotVqkaAMzRFf394vP3pWmfswxRHPvZ0SCJv78aCzVSzrSh+47v/Y7ZDtk0t1dv3asMkTp1WOwOFRkWVLCBdfNkC0qOPTBAp/wHwiVol+K+kfo+zjQgzjQShzor3Gg1VhQ7bEMGaxx9NGhggVWrp7Q/1ogGf0NxtXLKQCCgyKw6DmAQX5PkQfyCKio5aUNTzkcWKRPP3sh2NowKg+ikjaAim4PbdyCGsoVqhZdtYjU+m2oYjghqORdotIu2TBKSSm6ieCtaAqEoTK6H1pes7Vb2nQIHWpTeeGyTW9GB6p3tph/vqnn21pwOnpeq3eNdZRvN+2yI19g2W65WPcQQGoR6/DQhUJlHStmuYtINxA8bDb9RspQdRcaNVjzFNuR3dE60uZZvh2sYjk/P28RFK81OnbVUTq43G57uOZjAVeLuAZtD2uZdaza5S75hUSEax3fWgCEw4YMG5bScGVvNLSIXreRiA18fo6H0Wobe/jcxxs9tOH30WoXw8YlmiGo30fxHVAYoE2sZLoX2nota2XtirOwZlegMdU6y9pFew+0ztYaSpugZsWurNfyOCXpTSvrGAUgNLJ1QyYdQ9oryJkRqxepjkJLilKZdQOsm6rp25WVTNas4qJXP8si8fAMNNGrBkaAoNXNyroOA9T2LeAC9TNF8xTNyKkRUX3SoZ2OoHM9tObbBwQ9rOJNgmZwD11pIFq9ZtU+6KFas+Fb5FwdXqG7N6FgGBVsijqpfkmV82yvpBVJ3yUoLFLUe9UAKkV1Ur16XqYozlqiBTojlHT4AoqiImkzANyzVKb7SSPoXr9Nf32uZ0j1mrRNHW+tsWVTtEPRwktavShrmQZofkFJm+a+HQklI4/OSPgspbYODYKW/cveq3v1oPfuAc8Leq/SNTHpvXrQe5vYv2gggD9nMUUtifbetjsKWkS9CR+ilBKgst5Hy2RmqAfjlKAutFGAVsk41dU2RRsBCj9n+igdp3TM346So0ywoE3dS8n1AJV9OiM1yYy0ieo1MiPhFCjk6YwE5K5ZJjOSHsxIX1BI0Lol0hmpfTDOBdTAPEvjfJmNE+6dD+L3Q8UBVHFiQFVmqDVQUotfiXOUoxzlKEfjQ0VevRzl6P3Qx7Oa7vGskIxlAWosS21jWVTMw8PDw8PDw8PzqHPK6t8qDqN55qbkxYAK+64bB3rKHv3wbpt9m3ZF9qiYE70Y0HIM6As38ThQHh4eHh4eHh4enkeRwTfeRs6430Nzr3f4wm5TyCN++6Z0HzQ/JiqHo+HvlxfGRJXwjytPh+7CGxNVsXX5cZDrWQjbhYDGRCF2JCtskxX2h7rjou7kYsimjQdDldfWtR2EoTgMVbBzZ9QZ3kEYKuBP1h33PSoqF72wkqakkF4qYWM8VNIKoagc0kvFsA9MhaKT89bwNJgJ672hJb07+tWEnwkbp0rXjQi94bt7FN8Ja9MwtDEqmgifIe+MmuOjKGQXkhmGFkdFbzgifxeCCiG9YHLkpTDfPtxpyF/C/kweHh4eHh4eHp6Q/B8tfcJrc83nCAAAAABJRU5ErkJggg==>

### Mastodon instance

101010.pl

### Mastodon version

v4.3.0-alpha.0

### Browser name and version

firefox deved 87.0b9 (64-bit)

### Operating system

windows 10

**Comment by vmstan** [comment]
I'm able to reproduce this on my 4.3 instance, but not on mastodon.online at 4.2.1.

@ClearlyClaire possible this was introduced with https://github.com/mastodon/mastodon/pull/27271

**Comment by vmstan** [comment]
Confirmed as fixed by @ClearlyClaire
