### ISSUE TITLE
nightly source : admin dashboard is empty

### ISSUE THREAD

**Issue by zoubidabida** [mastodon/mastodon#27553]
### Steps to reproduce the problem

just click on administration 
it show "dashboard", the date and the 4 lines of reports etc that are waiting to be processed,
then nothing else is shown.
It used to work a couple days ago.
I do daily pull from source on the main branch at night and I just noticed it today.
I run Ubuntu 23.04.

journalctl -f doesn't show any error

And a second problem is that for a couple weeks, the loading of the administration page takes more than 10-15 seconds to display. It used to take a couple seconds before that.

### Expected behaviour

should show the dashboard

### Actual behaviour

it's empty

### Mastodon instance

lepoulsdumonde.com

### Mastodon version

v4.3.0alpha nightly from source

### Browser name and version

firefox 118

### Operating system

win 11

**Comment by ClearlyClaire** [comment]
> And a second problem is that for a couple weeks, the loading of the administration page takes more than 10-15 seconds to display. It used to take a couple seconds before that.

I think this may be the S3 check or one of the other tests timing out. Are you using S3? Are requests to the public-facing S3 endpoints possible from your server?

**Comment by zoubidabida** [comment]
> > it show "dashboard", the date and the 4 lines of reports etc that are waiting to be processed,
> > then nothing else is shown.
> 
> Have assets been successfully built? Is there perhaps some stale cache? Any error in the browser's console?

Hi 
I just did a new pull and a recompile and it’s working again. 
i don’t know what happened !
You can close the issue I guess. 

Thanks for the quick reply 😊
