### ISSUE TITLE
I can't find my country in the Time Zone

### ISSUE THREAD

**Issue by Chipsum** [mastodon/mastodon#27607]
### Steps to reproduce the problem

1.Trying to choose the right time zone

### Expected behaviour

should have found my country in the list

### Actual behaviour

I can't find my country in the list

### Detailed description

my country is in the GMT+1, and there are so many GMT+1 countries, and I wanna see my country there.

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.1

### Browser name and version

FireFox 119.0

### Operating system

Windows 11

**Comment by vmstan** [comment]
What exactly would that country be?

**Comment by Chipsum** [comment]
Algiers/Algeria
