### ISSUE TITLE
sort and filter following by activity similar to UnTweeps

### ISSUE THREAD

**Issue by Goldmaster** [mastodon/mastodon#27604]
### Pitch

Chances are that in among @Gargron@mastodon.social and the other real zingers you follow there's a load of lapsed users clogging your account. Pick a time scale (say, 30 days) and the feature scans who you folow and shows you who hasn't posted or reposted in that time, allowing you to unfollow anyone who's dormant.

### Motivation

This idea would be relatively similar to [UnTweeps](https://superlucky.me/unfollow-twitter-accounts/) which doesn't exist anymore. This feature would let you sort and filter people you follow by activity such as last post or repost x number of days ago or average posts per day maybe. This would allow users to unfollow people who may not be active, this feature would help organise and maintain who you follow more easily rather than forgetting who you follow.

**Comment by vmstan** [comment]
Under `/relationships?activity=dormant` you can see who you follow that hasn't been active. It's not as granular as what you're proposing but there are also some third party apps that do this.

**Comment by Goldmaster** [comment]
ah, many thanks. i wasn't sure if such a thing exists for mastodon or if it could be an inbuilt feature

**Comment by Goldmaster** [comment]
hi there, I have noticed you have closed this as not planned. are you saying that there is no point developing such feature, as there are 3rd party tools out there, that could do such a thing?
