### ISSUE TITLE
document_parsing_exception errors from a status with an invalid date

### ISSUE THREAD

**Issue by mszucs** [mastodon/mastodon#27639]
### Steps to reproduce the problem

1. Unclear how we acquired this status, but [this post](https://mk.itzti.li/notes/9la79fmeadxw63t4) arrived in our instance with an invalid timestamp:

```
created_at: Thu, 07 Nov 11968 17:22:13.599000000 UTC +00:00,
updated_at: Sat, 28 Oct 2023 15:09:01.341614000 UTC +00:00,
```

2. since then, a sidekiq job fails once per minute trying to deal with this status:

```
Oct 31 15:05:09 - bundle[3249279]:       `{"type"=>"document_parsing_exception", "reason"=>"[1:62] failed to parse field [last_status_at] of type [date] in document with id '47476'. Preview of field's value: '11968-11-07T17:22:13.599Z'", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"failed to parse date field [11968-11-07T17:22:13.599Z] with format [strict_date_optional_time||epoch_millis]", "caused_by"=>{"type"=>"date_time_parse_exception", "reason"=>"Failed to parse with all enclosed parsers"}}}`
```

### Expected behaviour

Sidekiq should be able to deal with whatever statuses it might encounter

### Actual behaviour

Sidekiq dies dealing with this status once per minute

### Mastodon instance

cosocial.ca

### Mastodon version

v4.2.0

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
- Node.js version: v16.20.2

**Comment by wiegelmann** [comment]
Confirmed, with another post example: https://myfriendsare.gay/notice/APx5K7aeglknMfm1A0

`Mon Jun 09 4200 14:34:56 GMT+0200`

Invalid date time stored in the statuses table

```
select id, created_at from statuses order by created_at desc limit 2;
         id         |         created_at         
--------------------+----------------------------
 111313273469836211 | 11968-11-07 17:22:13.599
 110900139960185644 | 4200-06-09 12:34:56.054444
```

Invalid date time stored in the tags table

```
select id,last_status_at from tags where last_status_at is not null order by last_status_at desc limit 2;
  id   |      last_status_at      
-------+--------------------------
  8641 | 11968-11-07 17:22:13.599
 10045 | 11968-11-07 17:22:13.599
```

Elastic indexing job failed

```
Import failed for `TagsIndex` with: Index errors: `{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse field [last_status_at] of type [date] in document with id '97127'. Preview of field's value: '11968-11-07T17:22:13.599Z'", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"failed to parse date field [11968-11-07T17:22:13.599Z] with format [strict_date_optional_time||epoch_millis]", "caused_by"=>{"type"=>"date_time_parse_exception", "reason"=>"Failed to parse with all enclosed parsers"}}}` on 1 documents: ["97127"]
```

**Comment by MiGrandjean** [comment]
Same here, thx for the SQL statement @wiegelmann 

```
mastodon=> select id, created_at from statuses order by created_at desc limit 5;
         id         |         created_at         
--------------------+----------------------------
 111313270076190733 | 11968-11-07 17:22:13.599
 110089373688730456 | 4200-06-09 12:34:56.054444
 111335548329658252 | 2023-11-01 13:34:05
 111335548095541136 | 2023-11-01 13:34:03
 111335548188850215 | 2023-11-01 13:34:03
(5 rows)
```

- Mastodon: 4.2.1
- Ruby: 3.2.2p53
- PostgreSQL: 15.4
- Redis: 5.0.7
- Elasticsearch: 7.17.13

**Comment by moyitpro** [comment]
I manually implemented the fix and removed the offending posts that were causing the indexing issues, but the sidekiq job still fails after rebuilding the ElasticSearch index, it still gives the error even that post is deleted:



Message | Import failed for `TagsIndex` with: Index errors: `{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse field [last_status_at] of type [date] in document with id '137017'. Preview of field's value: '11968-11-07T17:22:13.599Z'", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"failed to parse date field [11968-11-07T17:22:13.599Z] with format [strict_date_optional_time\|\|epoch_millis]", "caused_by"=>{"type"=>"date_time_parse_exception", "reason"=>"Failed to parse with all enclosed parsers"}}}` on 1 documents: ["137017"]
-- | --

It's the same post mentioned that is causing this. Any idea how to fix this?

**Comment by edsu** [comment]
I noticed a similar problem. It looks like the fix isn't released yet, but will go out with 4.2.2? Did anyone come up with a temporary solution? I guess the solution is to update or delete the offending row from statuses?

**Comment by ClearlyClaire** [comment]
In a Rails console, you could do the following:
```ruby
Status.where(created_at: ...'0000-01-01T00:00:00Z'.to_datetime).in_batches.update_all(created_at: '0000-01-01T00:00:00Z'.to_datetime.utc)
Status.where(created_at: '9999-12-31T23:59:59Z'.to_datetime...).in_batches.update_all(created_at: '9999-12-31T23:59:59Z'.to_datetime.utc)
```

**Comment by mszucs** [comment]
You may also need:


```
Tag.where(last_status_at: ...'0000-01-01T00:00:00Z'.to_datetime).in_batches.update_all(last_status_at: '0000-01-01T00:00:00Z'.to_datetime.utc)
Status.where(last_status_at: '9999-12-31T23:59:59Z'.to_datetime...).in_batches.update_all(last_status_at: '9999-12-31T23:59:59Z'.to_datetime.utc)
```

To unblock the indexing process.

**Comment by hugogameiro** [comment]
BTW: in a couple of tests I did, after fixing the date issue the ElasticSearch index did not unblock and I had to rebuild the full index to get it to update for new posts.

**Comment by mszucs** [comment]
> @mszucs If my logic is correct what you had in mind would be:
> 
> ```
> Tag.where(last_status_at: ...'0000-01-01T00:00:00Z'.to_datetime).in_batches.update_all(last_status_at: '0000-01-01T00:00:00Z'.to_datetime.utc)
> Tag.where(last_status_at: '9999-12-31T23:59:59Z'.to_datetime...).in_batches.update_all(last_status_at: '9999-12-31T23:59:59Z'.to_datetime.utc)
> ```
> 
> The second line should not start with `Status.where` but `Tag.where`, right?

Yes thanks, I corrected that.

**Comment by edsu** [comment]
It looks a full reindex will be needed to fill in the gaps? Is that best done with `RAILS_ENV=production bin/tootctl search deploy`

**Comment by ClearlyClaire** [comment]
Yes, errors for an extended time may lead to gaps. In that case, `RAILS_ENV=production bin/tootctl search deploy` is indeed the way to fix that.
