### ISSUE TITLE
User is redirected to the URL in the referer after succesful SAML authentication

### ISSUE THREAD

**Issue by quartje** [mastodon/mastodon#27664]
### Steps to reproduce the problem

1. Use SAML to login
2. User is redirected to the ACS location
3. User is not redirected to the Mastodon site, but to the URL present in the referer
...

### Expected behaviour

Redirect to the Mastodon site

### Actual behaviour

Redirect to the URL present in the referer header

### Detailed description

We have implemented SSO with SAML. We are hosting the IdP on the same domain as our Mastodon instance. 
When a SAML login succeeds, the user is redirected to back the SAML IdP. The redirection seems to be coming from the referer header. It should redirect the user to the Mastodon instance itself. 

When I instruct my browser not to send the referer header I get the correct behaviour
This behaviour is observed since version 4.2.0

### Mastodon instance

https://test.social.edu.nl (behind a firewall)

### Mastodon version

v4.2.0

### Browser name and version

Firefox 119.0

### Operating system

Chromium 119

### Technical details

The logs are showing:
D, [2023-11-03T07:48:49.404749 #14] DEBUG -- omniauth: (saml) Callback phase initiated.
I, [2023-11-03T07:48:49.741865 #14]  INFO -- : [441210b0-c5de-4647-8bb2-70043a0a75ab] method=POST path=/auth/auth/saml/callback format=html controller=Auth::OmniauthCallbacksController action=saml status=302 allocations=30920 duration=233.42 view=0.00 db=47.93 location=https://test.social.edu.nl/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp

**Comment by vmstan** [comment]
Just to clarify, this bug started with Mastodon 4.2.0? You have 4.1.2 listed as the version in the notes and I wasn't able to load the URL to verify (perhaps internal only?)

**Comment by quartje** [comment]
It started on 4.2.0 indeed! The URL is behind a firewall, our public instance is still on 4.1.9 and not experiencing these issues

**Comment by vmstan** [comment]
There are definitely a few SAML related changes in 4.2.

@mjankowski @ClearlyClaire @CSDUMMI are there any additional variables that would need to be set for this redirect to work?

**Comment by ClearlyClaire** [comment]
If possible, can you share an HTTP Archive (.har) from a login attempt that behaves this way?

Also, if I understand correctly, you are having the ACS on the same exact domain Mastodon is running on. This breaks some assumptions it makes.

**Comment by quartje** [comment]
@ClearlyClaire: Your understanding is correct. We host a SAML proxy using SimpleSAMLphp on the exact same domain. This allows us to present federated users with the ability to choose their nickname. 

I've attached a HAR archive of the login.

[test.social.edu.nl.har.gz](https://github.com/mastodon/mastodon/files/13263787/test.social.edu.nl.har.gz)

**Comment by ClearlyClaire** [comment]
> @ClearlyClaire: Your understanding is correct. We host a SAML proxy using SimpleSAMLphp on the exact same domain. 

It would definitely be easier and safer to use a different domain for that, Mastodon expects to be in full control of the domain it is installed on.

You could try the following patch, but I'm not sure it's worth the extra complexity:
```patch
diff --git a/app/controllers/application_controller.rb b/app/controllers/application_controller.rb
index 5f8725f6fc..4a0e350a3d 100644
--- a/app/controllers/application_controller.rb
+++ b/app/controllers/application_controller.rb
@@ -65,7 +65,7 @@ class ApplicationController < ActionController::Base
     redirect_uri = URI(request.referer)
     return if redirect_uri.path.start_with?('/auth')
 
-    stored_url = redirect_uri.to_s if redirect_uri.host == request.host && redirect_uri.port == request.port
+    stored_url = redirect_uri.to_s if redirect_uri.host == request.host && redirect_uri.port == request.port && !Rails.application.routes.recognize_path(redirect_uri).key?(:unmatched_route)
 
     store_location_for(:user, stored_url)
   end
```

> This allows us to present federated users with the ability to choose their nickname.

I'm afraid I don't understand what you mean here.
