### ISSUE TITLE
Content Security Policy blocks custom user stylesheet (Stylus, etc)

### ISSUE THREAD

**Issue by chriskirknielsen** [mastodon/mastodon#27661]
### Steps to reproduce the problem

1. Install a browser extension like Stylus
2. Add a custom style for your Mastodon feed (feel free to use [mine for mastodon.social](https://gist.github.com/chriskirknielsen/a23bc197f0c08ef6cbc9101156a99964))
3. Notice no changes are applied
4. Open the console and see `Content-Security-Policy: The page's settings blocked the loading of a resource at inline ("style-src").`

### Expected behaviour

Custom styles should apply

### Actual behaviour

CSP blocks inline-style and inline-style-src

### Detailed description

I have been using Stylus for years, and have customised my Mastodon instance a little bit to make what I feel are much needed accessibility/legibility improvements: links/mentions/hashtags stand out, "preview cards" are a little quieter, the scrollbar stands out, etc.

As of today (maybe yesterday?), all these styles no longer apply due to a change in the CSP, and it's honestly throwing me off as I had made it better (in my eyes, subject to taste of course).

I can understand preventing script injections but preventing styles seems like an overreach to me. Unless we can inject custom styles in our user settings, it would be lovely if this CSP change could be reverted to allow custom styles. Mine really improve my experience.

(I'd be open to other ways to do this via an extension that might modify the network requests and whatnot… but would really just rather use Stylus out of convenience)

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.1+pr-27634-22407c7

### Browser name and version

Firefox 119

### Operating system

macOS Ventura 13.5

### Technical details

I'm using the Stylus extension on Firefox, version `1.5.37`. Enabling the "Patch CSP to allow style assets" option did not change the results. Note that I also tried in Chrome via Stylus.

I also attempted to inject the styles in a manually created `<style>` tag via DevTools, and attempted to import a CSS file via `<link>` — also blocked.

**Comment by nightpool** [comment]
This is a bug in Stylus or Firefox. Nothing Mastodon does should be able to block Stylus from injecting their styles, since addons operate as part of the user-agent. Unfortunately, we can't really make our CSP less secure against our attacks to compensate for bugs in Firefox. 

That said, nothing about Mastodon's CSP behavior should have changed, as far as I know of, in the last few weeks. So maybe a Firefox or Stylus update broke it?

**Comment by chriskirknielsen** [comment]
Thanks for your quick reply @nightpool! Much appreciated.

I tried injecting a `<style>` tag via DevTools in Chrome (v118) where I do not have any Stylus custom styles for mastodon.social, and I still get a CSP error:

> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' https://mastodon.social 'nonce-uTFuUNj/wT1rNRN/VST/Qg=='". Either the 'unsafe-inline' keyword, a hash ('sha256-wCSo7HorY6Dehh8wmfdK8wATh7nj6pBPh70ulKcAPv4='), or a nonce ('nonce-...') is required to enable inline execution.

Same procedure in Firefox:

> Content-Security-Policy: The page's settings blocked the loading of a resource at inline ("style-src").

To be fair I don't use Chrome for Mastodon, so it's possible this has been happening for a long time, but it only just started on Firefox via Stylus, and the same _kind_ of CSP error is showing up on both browsers. Could be a coincidence but if you, or anybody else, have a minute to give this a try on your end to check if also happens I'd be grateful!

Thanks again!

**Comment by nightpool** [comment]
Devtools is not a reliable indicator, it runs code in the context of the webpage, not the content script (which has elevated addon permissions). I have no problems injecting a stylus style on Chrome:

<img width="343" alt="image" src="https://github.com/mastodon/mastodon/assets/233815/92e7ced2-8bf8-4a9a-9a97-94f07218e073">
<img width="1218" alt="image" src="https://github.com/mastodon/mastodon/assets/233815/5e23da77-667c-4d4b-8fe5-95bf00b00fac">

**Comment by chriskirknielsen** [comment]
Well colour me confused! Thanks for taking a look at this and sorry for the incorrect report!
