### ISSUE TITLE
Account query (referencing @username) triggers an extremely slow query

### ISSUE THREAD

**Issue by alsutton** [mastodon/mastodon#27666]
### Steps to reproduce the problem

1. Run on the database CPU constrained machine so the problem becomes more obvious (e.g. 1 core, 2GB VM running PostgreSQL)
2. Post via the web interface and reference a user using `@`
3. Watch as the username completion is slow and the database load sky-rockets.

### Expected behaviour

Fast username completion

### Actual behaviour

Username completion doesn't complete in a reasonable time

### Detailed description

Here is the performance graph from our Amazon RDS instance showing the query which appears to be triggered. The complexity seems to be what's causing the performance lag.

<img width="1284" alt="Screenshot 2023-11-03 104826" src="https://github.com/mastodon/mastodon/assets/430714/12b7642b-eac8-4563-a306-53df2b175779">
 
This can be correlated with a "username completion via the web interface" attempt via the metrics for the last 24 hours;

<img width="1281" alt="Screenshot 2023-11-03 105346" src="https://github.com/mastodon/mastodon/assets/430714/fed33811-32e3-4b47-ac6a-0d4bafda8575">

### Mastodon instance

snapp.social

### Mastodon version

v4.2.1

### Browser name and version

Edge latest

### Operating system

Windows 11

### Technical details

Constraining the db machine makes the problem more obvious. We could throw more CPUs at the problem, but as you can see from our 24hr load graph, most of the time the machine is well within the compute budget we've allocated.

**Comment by vmstan** [comment]
@alsutton I realize this issue has been stale for a while, but is this still an issue for you?

**Comment by alsutton** [comment]
We've upgraded the database to a larger machine to preserve a good user experience, so, for me, the issue has been resolved, but the performance issue may still exist.
