### ISSUE TITLE
Zlib::DataError: incorrect header check on Amazon links

### ISSUE THREAD

**Issue by vmstan** [mastodon/mastodon#27676]
### Steps to reproduce the problem

- Observed in Sidekiq logs

Noticing a larger and larger number of `Zlib::DataError: incorrect header check` errors in the dead queue from LinkCrawlWorker, relating to sites such as like amazon.com, bit.ly, amzn.to, amazon.ca, relinks.me

<img width="729" alt="Screenshot 2023-11-03 at 3 27 57 PM" src="https://github.com/mastodon/mastodon/assets/3002053/ed20c69b-4018-48f9-b232-a04adf6a15f4">

### Expected behaviour

No errors

### Actual behaviour

Errors

### Detailed description

Example URLs:
- https://amzn.to/46YBIwv
- https://amzn.to/3QmuQlz
- https://www.amazon.com/dp/B00I0EI0XW
- https://relinks.me/B07GFR69BH
- https://bit.ly/3KNR12R

### Mastodon instance

vmst.io

### Mastodon version

v4.3.0-alpha.0+io

### Technical details

- Ruby 3.2.2. +YJIT

**Comment by vmstan** [comment]
Now that I'm clicking through those relinks.me and bit.ly links also point to Amazon pages as well.

**Comment by shleeable** [comment]
@oneiros please investigate with the other similar issues

**Comment by oneiros** [comment]
Do you still get these?

I have a hard time reproducing this with the URLs given above. Might have to do with the version of `zlib` on your operating system (my Ubuntu machines have `1.2.11`)?

**Comment by vmstan** [comment]
I actually haven't seen them since about the time I reported them. I run the Docker containers which would be Debian Bookworm so `1.2.13`

When I was getting them there were a lot, it's possible it was something on Amazon side at the time?

**Comment by vmstan** [comment]
Yeah I just tried to reproduce with the same links, and not seem them anymore.

**Comment by oneiros** [comment]
Thanks for checking. Seems to have been on amazon's side or some other temporary thing. I am closing this for now, feel free to reopen if this occurs again.
