### ISSUE TITLE
Container build error due to missing config/webpack/tests

### ISSUE THREAD

**Issue by BlankRH** [mastodon/mastodon#27678]
### Steps to reproduce the problem

1. Build container in github codespace

### Expected behaviour

Successful build

### Actual behaviour

Got an error

### Detailed description

Error message: webpack config /workspaces/mastodon/config/webpack/tests.js not found, please run 'bundle exec rails webpacker:install' to install Webpacker with default configs or add the missing config file for your custom environment.

The file was deleted in #27333

**Comment by vmstan** [comment]
@renchap was that file intended to be deleted? I got the same error a couple days ago trying to get a container going.

**Comment by renchap** [comment]
Yes, this is intended.

I am not sure what is trying to use this file, it should not be used. Maybe the container needs to be re-created from scratch (once #27788 is merged)?

**Comment by vmstan** [comment]
I get the same error even with that patch.

**Comment by renchap** [comment]
I do not understand what command is launched that will try to load this file.

It must be a webpack (or webpacker?) invocation with `NODE_ENV=tests`, but I cant figure out what is calling it 🤔
