### ISSUE TITLE
Content cache retention period

### ISSUE THREAD

**Issue by VladlenO** [mastodon/mastodon#27677]
### Steps to reproduce the problem

1. Open "content storage".
2.
![Screenshot_20231103_221507](https://github.com/mastodon/mastodon/assets/91730566/1c079ae1-8ab0-403d-88c8-27b62524faaa)

3.
...

### Expected behaviour

Deleted cache

### Actual behaviour

Deleted all content - favorites, comments, bookmarks. 

### Detailed description

If it's a cache, then when I delete it and make a subsequent request, I should get the data again.
But I can't do it.
I know exactly who recently responded to my posts.
I did this: I went to the instance of the person who responded to my posts (via a browser, and I was not logged in to that person’s instance, but I was logged in to my instance).  I found his answer and clicked reply, after which a pop-up window asked me to log in or specify my server, which I did.  I was redirected to my server, where I saw the person's response and could respond to him.  but there were many answers.  I do not see them.
However, the database has not decreased.  I know that all this is in the database, how can I now restore all the replies to my posts, as well as bookmarks and favorites, which were also deleted by themselves?

at the very least, the description of the option is not true.
![Screenshot_20231103_192112_com keylesspalace tusky](https://github.com/mastodon/mastodon/assets/91730566/223b4fc3-72c8-476b-8a54-898970449e7b)
(If the post cache is deleted, but I access it, why doesn't it load again?  If I see these posts in tusky, then they are not in the browser, but if you go through the response from another instance, then everything is there in my domain.  Let me clarify once again that the size of the database has not decreased.)

Perhaps there is a team to restore connections?

### Mastodon instance

zocial.ee

### Mastodon version

V4.1.6

### Browser name and version

Tusky and Huawey browser

### Operating system

Harmony OS

**Comment by vmstan** [comment]
If the 'Content cache retention period' option is left blank, as it is in your screenshot, the feature is disabled. You need to either add a number of days to tell the vacuum service to start cleaning up, or run `tootctl` commands to do it. https://docs.joinmastodon.org/admin/tootctl/#statuses-remove

**Comment by VladlenO** [comment]
> If the 'Content cache retention period' option is left blank, as it is in your screenshot, the feature is disabled. You need to either add a number of days to tell the vacuum service to start cleaning up, or run `tootctl` commands to do it. https://docs.joinmastodon.org/admin/tootctl/#statuses-remove

The problem is that if there is a number, then it deletes everything and does not load it again when required.  That is, it does not update the cache.  In fact, this option works like data remover, without updating it on request.

**Comment by VladlenO** [comment]
> If the 'Content cache retention period' option is left blank, as it is in your screenshot, the feature is disabled. You need to either add a number of days to tell the vacuum service to start cleaning up, or run `tootctl` commands to do it. https://docs.joinmastodon.org/admin/tootctl/#statuses-remove

In other words: if you call it a cache, then I can delete it and then re-cache it on demand.  In addition, imagine the following: for example, you cleared your browser cache, now you not only cannot open this page, but your bookmarks and favorites have also disappeared.  How does this relate to cache?

**Comment by VladlenO** [comment]
So how does this happen?  An account where posts are not accessible from the browser, but are visible through the application.  There they open with an error.  I open the same post in another account (I change the user who is not active on my server, and the post is available).  I change it back to active user and the post is available again without errors.  What the hell is this?  Where did my posts go?  I have attached a video of this process.  I want to emphasize that these posts are not visible at all from the browser!!!
Video: https://digic.cloud/s/y5Dz4gLrKsrnKgy

**Comment by vmstan** [comment]
To answer your question from #27733, I believe if you have your media cache retention settings to at least 14 days it would prevent preview card data from being removed and unable to be restored from cache.

**Comment by vmstan** [comment]
Closed by #27733
