### ISSUE TITLE
"Failed to compile" error on development server

### ISSUE THREAD

**Issue by jamesadney** [mastodon/mastodon#27686]
### Steps to reproduce the problem

1. `git clone https://github.com/mastodon/mastodon.git`
2. `bundle install`
3. `yarn install`
4. `foreman start`
5. Visit 'localhost:3000' in browser

### Expected behaviour

Page renders successfully

### Actual behaviour

Get "Failed to compile" error message

### Detailed description

The full message is:

> Failed to compile.
> 
> ./app/javascript/mastodon/features/emoji/emoji_unicode_mapping_light.ts 18:15-32
> "export 'unicodeToFilename' was not found in './unicode_to_filename'

- 0e3401bc1c24fc1f6d7e04e9d2 appears to be the commit when the issue was introduced.
- JS tests (`yarn run test`) are passing.
- If I manually set `NODE_ENV=production` then the site _does_ render successfully.
  ```shell
  RAILS_ENV=development ./bin/rails tmp:clear assets:clean
  NODE_ENV=production foreman start
  ```

### Mastodon instance

localhost

### Mastodon version

3bf2a7296e6d80d5cd9d5d3cba1507af6ba83dfd

### Technical details

OS: Ubuntu 23.10

`ruby --version`

> ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]

`node --version`

> v20.9.0

**Comment by zunda** [comment]
I see the same problem here on Mastodon 3bf2a7296e6d80d5cd9d5d3cba1507af6ba83dfd, Ubuntu 22.04.3, ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux] and node v20.8.0.

**Comment by zunda** [comment]
It looks like we can just set `BABEL_ENV` rather than `NODE_ENV` to work around this and get the front-end running on the browser, i.e.,:

```
RAILS_ENV=development ./bin/rails tmp:clear assets:clean
BABEL_ENV=production foreman start
```

**Comment by renchap** [comment]
I also see this, and I am not sure what is causing it exactly, because it does not appear on CI 🤔 

It can be solved by replacing `exports.` by `export const` in `app/javascript/mastodon/features/emoji/unicode_to_filename.js` and `/Users/renchap/dev/mastodon/mastodon/app/javascript/mastodon/features/emoji/unicode_to_unified_name.js` so those files are proper ESM.

**Comment by renchap** [comment]
Possible fix here: https://github.com/mastodon/mastodon/pull/27691

**Comment by hailiang-wang** [comment]
Come to the same problem, https://github.com/Castodon/castodon/issues/1
Great to know it has been fixed now, I am using the previous codes.
