### ISSUE TITLE
any url returns an empty page if no cookie is previously existant

### ISSUE THREAD

**Issue by zoubidabida** [mastodon/mastodon#27697]
### Steps to reproduce the problem

try any page on my instance, like : 
[https://lepoulsdumonde.com/@nico](nico) or [https://lepoulsdumonde.com/](home)
Only a grey window is displayed.
the console logs : 
```Uncaught Error: No current user (me) defined when calling `accountsReducer`
    at accounts (accounts.ts:51:11)```
But when you already have an existing connection to the server (I guess when you have an existing cookie), everything works fine.
For example, on my main browser, firefox 119 on win 11, I can log in and out, get any url because I've been using it with an account for a long time.
But if I go to chrome which I never used to access my instance, or on my phone, or if a friend tries to connect to my instance, I get this error, and only a grey empty window is displayed.
I don't get any error logs in journalctl.
I tried pulling main again, and deleting the packs and cache and recompiling, restarting all services with no success.
I'm using the latest nightly main branch from source pull.
I don't know when the problem appeared exactly.

### Expected behaviour

display the web page

### Actual behaviour

empty window

### Mastodon instance

lepoulsdumonde.com

### Mastodon version

v4.3.0alpha nightly from source

### Browser name and version

firefox 119, chrome 119

### Operating system

win 11, ios, win10

**Comment by vmstan** [comment]
@renchap likely a result of #26559

**Comment by vmstan** [comment]
I'm able to reproduce it.

**Comment by uandreew** [comment]
I have the same problem.

**Comment by renchap** [comment]
Woops sorry, fix should be in #27698
