### ISSUE TITLE
"Something went wrong on our end" when updating profile photo

### ISSUE THREAD

**Issue by anayebi** [mastodon/mastodon#27703]
### Steps to reproduce the problem

I tried to "Edit Profile" and chose a picture less than 2 mb for my profile picture, but after I hit "Save Changes", I keep getting a "Something went wrong on our end".

### Expected behaviour

The profile picture should have updated

### Actual behaviour

"Something went wrong on our end" error

### Mastodon instance

mstdn.science

### Mastodon version

v4.2.0

### Browser name and version

Both Chrome and Safari

### Operating system

macOS 13.2.1

**Comment by vmstan** [comment]
Hi @anayebi, are you the admin of the instance, or are you able to loop them in to provide logging on the server side as to what might be going on when this is being attempted?

**Comment by anayebi** [comment]
I’m not the admin but it looks like it’s working again now, so closing this issue.
