### ISSUE TITLE
API lacks attribute "follow-requested-by" in Relationship

### ISSUE THREAD

**Issue by tateisu** [mastodon/mastodon#2771]
I want to check relationship about authenticated user is follow-requested-by other user.
(FYI: Relationship.requested attribute means the opposite. "authenticated user sent follow request to other user.")

- /api/v1/accounts/:id/followers returns list that includes both of followers and follow-requested-by.

- also Relationship.followed_by attribute means both of followed_by and follow-requested-by.

- "follow-requested-by" or similar is not included in Notification.

Seems currently we can get "follow-requested-by" by only using /api/v1/follow_requests .
But it's not good for showing relationship correctly, and notify the events to authenticated user.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x ] This bug happens on a1.3.2

**Comment by tateisu** [comment]
https://mastodon.juggler.jp/@tateisu/760173

then I found both of  (Relationship.followed_by =true,false ) in accounts that returns /api/v1/follow_requests . (second is remote user)

**Comment by trwnh** [comment]
i believe there is now a `requested` and `requested_by` attribute on the Relationship entity https://github.com/mastodon/mastodon/blob/679aca46da56228a3219d1c6f0c942adcfb8fdb1/app/serializers/rest/relationship_serializer.rb#LL6C19-L6C19

**Comment by silverpill** [comment]
@trwnh `requested_by` is not documented: https://docs.joinmastodon.org/entities/Relationship/
