### ISSUE TITLE
Implement a like feature

### ISSUE THREAD

**Issue by Elgueromiranda** [mastodon/mastodon#27711]
### Pitch

Each post should have a like feature so people can all agree on whats popular with a counter so people get some of idea of the traffic their ideas are getting on the site to attract more users.

### Motivation

I think this is a pretty standard feature that most social media websites have that is very useful and intuitive to use and it would drive up traffic and interactions between users. The feature would also be one of the easier features to implement since it can just be managing the state of the post.

**Comment by benjaminbhollon** [comment]
Is there a functional difference between this and the standard "favorite" that Mastodon uses and GtS already has implemented?

**Comment by trwnh** [comment]
this already exists; it is currently called "favourite"
