### ISSUE TITLE
Explore prompt still shows up with out of order posts

### ISSUE THREAD

**Issue by lambda** [mastodon/mastodon#27726]
### Steps to reproduce the problem

1. Load a home timeline with plenty of activity, in which one of the most recent 20 posts was received out of order and had been created more than 10 hours ago

### Expected behaviour

Expect to see no explore prompt prompting you to follow more people

### Actual behaviour

See an explore prompt that prompts you to follow more people

### Detailed description

This looks like it's the same issue as #27211 which didn't actually fix the issue; in fact, it made it worse (though thankfully easier to debug) as now the explore prompt shows up the entire time the out of order post is in the latest 20 posts.

If a post from another server arrives at your server over 10 hours late, then it can show up in the latest 20 posts which are used to calculate whether the explore prompt should show up, and it will be used as the oldest post when calculating the average gap. If there's over a 10 hour delta between this and the newest post, then the calculation will decide to show the explore prompt.

In #27211 a change was made to try to address this issue; but that changed it from looking at the last post in the list (ordered by the order they are arranged on your timeline), to looking at the one with the oldest timestamp. Now, the explore prompt will show up the entire time this post which is displayed out of order is in the latest 20, not just when it's at the end of the list.

For example, here are a couple of the values I extracted for the oldest and newest when looking at this in the debugger:

* Newest: Date Mon Nov 06 2023 07:34:30 GMT-0500 (Eastern Standard Time)
* Oldest: Date Sun Nov 05 2023 12:35:52 GMT-0500 (Eastern Standard Time)

I think that a quick fix for this might be to sort by the created date before looking at the first 20 statuses, so you'll get the latest 20 by created date, rather than taking the latest 20 by displayed order.

### Mastodon instance

hachyderm.io

### Mastodon version

v4.2.1

### Browser name and version

FIrefox 119.0

### Operating system

Ubuntu 22.04.3 LTS (Jammy Jellyfish)

**Comment by lambda** [comment]
Hmm. I submitted PR  #27728 for this by sorting by created at timestamp, but thinking about it a little more, it looks like the default when loading the home timeline is to only load 20 posts, which means that this prompt would still show up if one of those posts were out of order; that patch would only help in cases when you had loaded more than 20 posts, so sorting by created at timestamp would eliminate the few out of order posts. If only 20 are loaded, the sorting won't make a difference.

In a [thread about this and related bugs](https://mastodon.social/@mcc/111364539288215381) it was pointed out that using local storage for storing the dismissal state for this feature is inconvenient when people are moving around between different browsers; and between that and all of the subtleties of implementing this on the client side (races when statuses aren't yet loaded, merging the pending and displayed status lists, some posts being delayed and so old posts showing up, and only having a window of about 20 posts to look at), it seems like it might be more robust to implement this feature on the server side, so the dismissal state could be stored persistently between browsers, and the calculation could look at a larger window and more easily filter out of order posts.

The disadvantage is that that would require API changes, and both client and server side changes, so it would be a bigger feature than just a quick fix to the client side logic. 

I'm open to suggestions on other potential solutions as well.

**Comment by lambda** [comment]
I suppose one other potential solution would be to walk through the list, and filter out any posts that are out of order (posted earlier than a post later in the list), but this would still trigger the bug if delayed posts showed up at the end of the list.

Only having a list of potentially 20 or fewer statuses to base this calculation on is quite limiting; doing it on the server side would make it much easier to filter out these out-of-order statuses without substantially limiting the windows of posts that we're looking at, and reducing the window of posts that we're looking at would make this calculation more noisy and thus more likely to pop up the prompt on a busy timeline that just happens to have had a brief lull.

Finally, I think just removing the feature should be considered. I'm not sure it's pulling its weight; it's somewhat complicated and fiddly, and it puts up a very intrusive banner. It is able to be dismissed, but when you hit these bug cases, it can sometimes pop up and disappear before you have a chance to dismiss it, so can keep bothering you until you are fast enough to dismiss it.

And some people might not want to have really busy timelines; maybe some people like to follow only a few folks, and see a few updates a day. Suggesting that people keep following more people until their timeline is very busy seems like the kind of social media growth hacking that causes social media to be a problem, it's OK sometimes for people to have social media feeds that aren't particularly busy.

**Comment by renchap** [comment]
Closing as the explore prompt has been replaced by a follow suggestions widget in #28878
