### ISSUE TITLE
Media cleanup job fails with read timeout each day

### ISSUE THREAD

**Issue by brookmiles** [mastodon/mastodon#27752]
### Steps to reproduce the problem

1. Set "Media cache retention period" to your preferred cleanup period, eg. 7 days
2. Wait a few days and observe logs / media storage size

### Expected behaviour

Media is cleaned up daily

### Actual behaviour

Media cleanup job fails each day with a timeout error

### Detailed description

Since upgrading to v4.2.1 the test server I have this setting enabled on has failed to clean up every day with timeout errors:

```
Oct 21 03:12:07 rabbit bundle[821007]: E, [2023-10-21T03:12:07.202325 #821007] ERROR -- : Error while running Vacuum::MediaAttachmentsVacuum: Net::ReadTimeout with #<TCPSocket:(closed)>
Oct 22 03:12:07 rabbit bundle[821007]: E, [2023-10-22T03:12:07.450756 #821007] ERROR -- : Error while running Vacuum::MediaAttachmentsVacuum: Net::ReadTimeout with #<TCPSocket:(closed)>

[repeats daily]

Nov 05 03:12:08 rabbit bundle[821007]: E, [2023-11-05T03:12:08.555438 #821007] ERROR -- : Error while running Vacuum::MediaAttachmentsVacuum: Net::ReadTimeout with #<TCPSocket:(closed)>
Nov 06 03:12:07 rabbit bundle[821007]: E, [2023-11-06T03:12:07.930777 #821007] ERROR -- : Error while running Vacuum::MediaAttachmentsVacuum: Net::ReadTimeout with #<TCPSocket:(closed)>
```

On my test server there isn't enough media for this to really matter, but other admins have also reported seeing these timeouts and noted that media is no longer being cleaned up by this setting as it was before upgrading to 4.2 (@rrgeorge , @vmstan )

### Mastodon instance

various

### Mastodon version

v4.2.1

### Technical details

- Ruby version: 3.2.2p53
- Node.js version: v16.20.1

Media storage on S3, in my case OVH.

**Comment by vmstan** [comment]
So I was having this issue while testing the 4.2 releases, and then sort of forgot about it as I moved to doing things through `tootctl` based cronjobs, but have gone back and retested what I fixed the errors for me.

`config/initializers/paperclip.rb` currently has `retry_limit: 0` hardcoded. To fix these errors, I have added an ENV variable called `S3_RETRY_LIMIT` and set it to `1`.

**Comment by rrgeorge** [comment]
> `config/initializers/paperclip.rb` currently has `retry_limit: 0` hardcoded. To fix these errors, I have added an ENV variable called `S3_RETRY_LIMIT` and set it to `1`.
I have had this modified to be 1 already, and still have this issue.

**Comment by ClearlyClaire** [comment]
@brookmiles does reducing the `LIMIT` in `app/lib/attachment_batch.rb` help?

**Comment by brookmiles** [comment]
> @brookmiles does reducing the `LIMIT` in `app/lib/attachment_batch.rb` help?

Will let you know tomorrow!

**Comment by brookmiles** [comment]
> @brookmiles does reducing the `LIMIT` in `app/lib/attachment_batch.rb` help?

@ClearlyClaire I reduced it from 1_000 to 100 and there was no timeout today 👍

**Comment by ClearlyClaire** [comment]
Interesting. What S3 provider are you using?

@Gargron what are your thoughts on this? Should we reduce the batch size? Make it configurable? Dynamically adjust it?

**Comment by brookmiles** [comment]
> Interesting. What S3 provider are you using?

I'm on OVH High Performance

**Comment by vmstan** [comment]
I noticed today my storage had doubled in size after 2-3 weeks of running with the vacuum scheduler instead of my pervious `tootctl media remove` scripts. Had 574,888 files when I ran it.

Once this is cleaned up I'll modify it with the changes @ClearlyClaire suggested and monitor.

**Comment by NicoBerlo** [comment]
I've noticed the same problem in the past three days. Usually this happens once or twice a week, but now it's everyday.
<img width="1115" alt="Capture d'écran 2023-11-30 093308" src="https://github.com/mastodon/mastodon/assets/53380703/9ddc1a49-6676-419f-b5e4-af1328b37cc2">

red bars are negative deltas on my cloudflare R2 bucket. circles are from the daily vacuum_scheduler process and other red bars are from my cron jobs running every 3 hours. See how daily vacuum doesn't happen any more on the last three days on the right hand side.

**Comment by ClearlyClaire** [comment]
@vmstan so even lowering the batch size does not fix the issue in your case? What provider are you using?

**Comment by vmstan** [comment]
It does not. It just causes it to fail faster. I ran it in debug for a while last night and could see the delete calls to the S3 bucket being made and then one is sent that returns almost immediately with the error and then all batch deletes stop.

Looking at the code it doesn't seem like there is any retry or error handling built in currently?

**Comment by ClearlyClaire** [comment]
Yeah, the job aborts on error, which is not necessarily a bad thing if errors are infrequent… but in your case, I don't know what may cause `Start End Mismatch: element 'DeleteResult' not closed`

**Comment by vmstan** [comment]
Yeah I couldn't sort that either, I didn't see DeleteResult anywhere in the batch code, but then I wasn't sure if it was part of Paperclip or the response from the Digital Ocean S3 API, since it's different than what others are experiencing?

**Comment by NicoBerlo** [comment]
> Yeah, the job aborts on error, which is not necessarily a bad thing if errors are infrequent

in certain scenarios, an initial failure might be followed by success upon retrying. However, if the process consistently fails for several days at the first attempt, it can lead to an unnecessary accumulation of data in the storage for days at a time (which happened to me)
Maybe there could be at least one retry ?

**Comment by vmstan** [comment]
So I took a stab at adding some really basic retry logic to `app/lib/attachment_batch.rb` and was able to get it to fail, retry, and then continue processing.

<img width="1196" alt="Screenshot 2023-12-01 at 2 11 16 PM" src="https://github.com/mastodon/mastodon/assets/3002053/f563cd3e-bd78-4fc4-90c0-0dd507829c8a">
