### ISSUE TITLE
DEPRECATION WARNING: Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2.

### ISSUE THREAD

**Issue by GuidoDr** [mastodon/mastodon#27757]
### Steps to reproduce the problem

v4.3.0-nightly.2023-11-07 (docker image)
`tootctl cache clear ` and `tootctl media remove-orphans` are both showing the below warning:

DEPRECATION WARNING: Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2.

Check the Rails upgrade guide at https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format
for more information on how to upgrade.
 (called from <main> at /opt/mastodon/config/environment.rb:7)

### Expected behaviour

running without showing warnings

### Actual behaviour

runs with the showed warnings

### Detailed description

see above "steps to reproduce"

### Mastodon version

v4.3.0-nightly.2023-11-07

### Technical details

image: ghcr.io/mastodon/mastodon:edge

**Comment by ClearlyClaire** [comment]
This warning is known and expected. This will be fixed by #27393, but we want to merge it closer to 4.3.0 release to give more time to admins for a smooth upgrade.
