### ISSUE TITLE
Problems Serving Request

### ISSUE THREAD

**Issue by sallyFoster** [mastodon/mastodon#27772]
### Steps to reproduce the problem

Trying to post this image

![IMG_9634](https://github.com/mastodon/mastodon/assets/104597302/84bca93c-85de-49dc-9c08-111f8bc18c8a)

### Expected behaviour

The image gets posted

### Actual behaviour

I get a server error

### Detailed description

![IMG_9659](https://github.com/mastodon/mastodon/assets/104597302/55e9c218-f8d2-4df6-b7d9-72b24f5f96a6)

### Mastodon instance

toots.matapacos.dog

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by vmstan** [comment]
Are you the administrator of this server? If so, what logs do you see when this file is uploaded?
