### ISSUE TITLE
Some user profiles don't open.

### ISSUE THREAD

**Issue by 101010pl** [mastodon/mastodon#27793]
### Steps to reproduce the problem

1. Go to user profile: https://[101010.pl](https://101010.pl/@grzgrz)/@grzgrz

### Expected behaviour

Open Profile

### Actual behaviour

Error

### Mastodon instance

101010.pl

### Mastodon version

v4.3.0-alpha.0

### Browser name and version

Edge 119.0.2151.44

### Operating system

Windows 11

### Technical details

TypeError: Cannot set properties of undefined (setting 'volume')
_syncVideoToVolumeState (webpack:///app/javascript/mastodon/features/video/index.jsx:449:24)
_syncVideoFromLocalStorage (webpack:///app/javascript/mastodon/features/video/index.jsx:460:11)
ih (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:144:188)
lk (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:261:421)
jk (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:260:445)
fk (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:259:430)
Xk (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:283:95)
Tk (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:281:400)
Dk (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:273:438)
jg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:127:104)

**Comment by vmstan** [comment]
Possibly related to #27488

**Comment by vmstan** [comment]
It doesn't appear to be all user profiles, as just looking at local timeline https://101010.pl/@adamklimowski and https://101010.pl/@ciekawe both work. But the one you added and https://101010.pl/@xaphanpl appear broken.

**Comment by vmstan** [comment]
Looping in @thehydrogen or @ClearlyClaire

**Comment by thehydrogen** [comment]
Will investigate! Hadn't noticed this in my testing
