### ISSUE TITLE
“About” and “Privacy policy” links take you out of the advanced UI

### ISSUE THREAD

**Issue by sayunuh** [mastodon/mastodon#27971]
### Steps to reproduce the problem

1. In the “Getting started” column of the Advanced UI, click on the “About” or “Privacy policy” link.

### Expected behaviour

The page is opened in the column.

### Actual behaviour

A new browser tab opens.

### Detailed description

The Advanced UI is capable of displaying these pages, which can be seen by directly inputting the URL path /deck/about and /deck/privacy-policy. The behaviour changed since v4.2.0, I believe.

(Though them not having the “Back” button is a bit awkward. Probably a column header should ideally be added when opened in this context, but that is another issue.)

### Mastodon instance

mofu.kemo.no

### Mastodon version

v4.2.1

### Browser name and version

Google Chrome 116.0.5845.187

### Operating system

macOS 10.13.6

**Comment by ClearlyClaire** [comment]
This is by design, those pages are text-heavy and display really poorly in a width-constrained column.

**Comment by sayunuh** [comment]
That’s unfortunate, because we have applied a custom CSS that allows these pages to be viewed as comfortably as possible even in a narrow column by dynamically reducing margins etc.

**Comment by trwnh** [comment]
a propos of nothing, i find it weird that these pages are supposedly too big to show in a column, but somehow perfectly viewable on a mobile viewport…?!
