### ISSUE TITLE
Search not updating since October 28; daemon.log reports a bizarre timestamp; sidekiq reports can't import

### ISSUE THREAD

**Issue by solarbirdy** [mastodon/mastodon#27970]
### Steps to reproduce the problem

This isn't so much a "steps to repro" as "my instance isn't updating elasticsearch's database due to what looks like a broken timestamp." It stopped on October 28th. (It's a small instance and we don't use search much so I didn't notice until a few days ago.)

### Expected behaviour

search should continue updating

### Actual behaviour

search has not continued updating

### Detailed description

Elasticsearch is happy and running fine and is version 7. But I am seeing this in sidekiq:

Chewy::ImportFailed: Import failed for `TagsIndex` with: Index errors: `{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse field [last_status_at] of type [date] in document with

And this in daemon.log:

`{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse field [last_status_at] of type [date] in document with id '16013'. Preview of field's value: '11968-11-07T17:22:13.599Z'", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"failed to parse date field [11968-11-07T17:22:13.599Z] with format [strict_date_optional_time||epoch_millis]", "caused_by"=>{"type"=>"date_time_parse_exception", "reason"=>"Failed to parse with all enclosed parsers"}}}`

DocumentID changes, timefield is always 11968-11-07T17:22:13.599Z and I don't know what to do with this.

### Mastodon instance

mastodon.murkworks.net

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
- Node.js version: v16.20.2

**Comment by solarbirdy** [comment]
I note that Michael asked me to open this, but I'd already opened a discussion here:

https://github.com/mastodon/mastodon/discussions/27968

and since now I see this is the same issue as here:

https://github.com/mastodon/mastodon/issues/27639

this should probably be closed? But I don't know how to find and remove the bad posts. If someone can help me with that (knowing that I am not comfortable with SQL) then I would appreciate it, but it should probably be on the discussion rather than here.

**Comment by vmstan** [comment]
Yeah sorry I didn't know you had a discussion open as well. This is fixed by https://github.com/mastodon/mastodon/pull/27655
