### ISSUE TITLE
Report forwarding should not go to single user instances

### ISSUE THREAD

**Issue by FediVideos** [mastodon/mastodon#27983]
### Pitch

Forwarding of reports to remote instances should only be possible if the instance has two or more users. If there's only a single user on the remote instance, this option should not be available. Perhaps it could be greyed out with a brief explanation why it isn't possible.

### Motivation

At the moment, it's possible for a user to anonymously forward their report to the admin of the remote instance hosting the problematic post. However, if this remote instance is a single user instance, then the person who wrote the problematic post is also the admin. (And some of the nastiest most abusive accounts do use single user instances.)

Users usually don't know the remote instance is single user, so they may be accidentally sending their report to the very person they are complaining about (albeit anonymously). In some situations, despite the anonymity, this report forwarding may tell an abuser that the victim has made the complaint, and trigger further abuse.

To avoid this situation, it would be good to only allowing forwarding to remote instances with more than one user.

Obviously abusers will make second accounts to avoid this, but at least this is friction for them if they have to do that.

**Comment by ClearlyClaire** [comment]
While I understand the reasoning, I am not sure this is a reasonable thing to do. Indeed:
- this would make reporting slightly less predictable to users
- single-user instances rarely have a single account (even when not for abuse purposes)
- an instance not being single-user does not mean its moderators will not be abusive either
