### ISSUE TITLE
Unable to mute users without web UI error

### ISSUE THREAD

**Issue by vmstan** [mastodon/mastodon#28003]
### Steps to reproduce the problem

1. Try to mute a user

### Expected behaviour

User is muted

### Actual behaviour

"Oops, an expected error has occurred"
(It appears the user is also then muted.)

### Mastodon instance

vmst.io, mastodon.online

### Mastodon version

v4.3.0-alpha.0, v4.3.0-nightly.2023-11-19

### Browser name and version

Safari

### Operating system

macOS

**Comment by holmesrichards** [comment]
Confirmed in Firefox, Linux Mint 21.2.

That error message is pretty useless, conveys no information about cause or possible remedy.
