### ISSUE TITLE
Unable to upload Videos and GIFs

### ISSUE THREAD

**Issue by vikrammudaliar** [mastodon/mastodon#28041]
### Steps to reproduce the problem

1. Attach a GIF or Video to a post
...

### Expected behaviour

It should upload and process

### Actual behaviour

Its stuck in processing

### Detailed description

Hi, I am unable to post GIFs or Videos in my Mastodon server, I don;t see any errors in logs
its just stuck in processing, I am getting a 201 from /v2/media and then constant 206, but nothing happens after hours tooIts 

Definitely not to do with size as I upload large png, it works, but GIFs and Video is not working

I see the file is uploaded in /public/system/media_attachments as well
but the UI is stuck in processing

### Mastodon instance

zh.pp.social

### Mastodon version

v4.2.1

### Browser name and version

Any Browser

### Operating system

Any OS

### Technical details

Output of RAILS_ENV=production bundle exec rails c:

Chewy console strategy is `urgent`
Loading production environment (Rails 7.0.8)
irb(main):001:0> Sidekiq::Queue.new.size
=> 0
irb(main):002:0> Sidekiq::Queue.new('media').size
=> 0
irb(main):003:0> MediaAttachment.where(status: nil).count
=> 44
irb(main):004:0> Sidekiq::DeadSet.new.size
=> 0
irb(main):005:0> Sidekiq::Queue.new.clear
=> true
irb(main):006:0> Sidekiq::Queue.new('media').clear
=> true

**Comment by vmstan** [comment]
Is this a new implementation, or were they working before a recent upgrade?

**Comment by vikrammudaliar** [comment]
Its a new implementation, I am a little confused on the NodeJS, Yarn and other versions
as the docker has it different and the documentation has it different.

Could you please help me with the versions requirement for Ubuntu 22.04

**Comment by vmstan** [comment]
Node 20 and Ruby 3.2.2 are the recommended versions for Mastodon 4.2.x, the documentation site has pending updates for this.

To the video/GIF issue, do you have ffpmeg installed? Do videos and GIFs that are posted on other instances appear normally when they federate to your server?

**Comment by vmstan** [comment]
If you're running 4.2.1 it's Yarn 1 (classic) but 4.3.x (main) will be Yarn 4.

**Comment by vikrammudaliar** [comment]
> If you're running 4.2.1 it's Yarn 1 (classic) but 4.3.x (main) will be Yarn 4.

Thanks @vmstan
