### ISSUE TITLE
Migrating to a new machine throws errors on feeds build and site is broken afterwards

### ISSUE THREAD

**Issue by gb5256** [mastodon/mastodon#28068]
Hi,
I am a newby on Mastodon.
Trying to move my server instance to a new machine.
Everything works ok until I get to this point:

Runnning this:

    RAILS_ENV=production ./bin/tootctl feeds build

Creates this output:

    Error processing 109370448892390286: undefined method `[]' for nil:NilClass
    Error processing 109347761770771258: undefined method `[]' for nil:NilClass
    Error processing 109671110977800918: undefined method `[]' for nil:NilClass

If I finish all the other steps in the docs, I see the website, but I see no server stats (but this might be because Redis is not moved) but I also see no posts.

If I click on the "Learn more" button, I get the "oh no" error. The error report of that one says this:

TypeError: i.get(...).isEmpty is not a function
isEmpty (webpack:///app/javascript/mastodon/features/about/index.jsx:164:52)
wi (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:3592:9)
di (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:3577:10)
Bc (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:1068:2)
bd (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5339:57)
bd (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5336:6)
Error(p (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5325:19)
Xj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5115:84)
lc.onCommitFiberUnmount (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5136:31)
fa (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:1927:89)
d.hasOwnProperty (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:4519:386)

Not sure what do to from here.
I have re-done the whole process now 3 times to check if human error is involved, but I get the same errors.

PS: In contrast to the current Docs on Installing Mastodon, I have to install runby 3.2.2 as required by mastodon, while the docs still say 3.0.2

Any help highly appreciated.
gb5256

**Comment by vmstan** [comment]
@gb5256 are you still having issues with deploying?
