### ISSUE TITLE
Mastodon Instance can’t federate with some servers, can’t follow some users (code 401)

### ISSUE THREAD

**Issue by evoscope** [mastodon/mastodon#28061]
### Steps to reproduce the problem

1. Find a profile on a different server (e.g. mastodon.social)
2. Follow that profile
3. Reload the page
4. See that follow request is pending

### Expected behaviour

Follow request works and instance gets federated with the other server

### Actual behaviour

Follow requests don't work, my instance can't be seen by other servers, Sidekiq throws error 401

### Detailed description

Hi everyone,

I am fairly new to hosting and mastodon, but I managed to set up a mastodon instance on a RPi4 following this tutorial: https://pimylifeup.com/raspberry-pi-mastodon/https://pimylifeup.com/raspberry-pi-mastodon/

The instance seemed to run as intended in the beginning, registration works and mails are being sent. With accounts on the instance it’s possible to follow some users on instances like [chaos.social](http://chaos.social/), however, trying to follow users on for example [mastodon.online](http://mastodon.online/) fails. I can find users on this instance, I can hit „Follow“ and the button changes to „Followed“, but after reloading the paged it states that the follow-request is pending. I’ve tried this with my own account on [mastodon.online](http://mastodon.online/) and the request never gets delivered. 

Sidekiq shows the following errors (in this case for a follow request for @Gargron on [mastodon.social](http://mastodon.social/): 

`Mastodon::UnexpectedResponseError: https://mastodon.social/users/Gargron/inbox returned code 401
`

and

`Stoplight::Error::RedLight: https://mastodon.social/users/Gargron/inbox
`

From my account on [mastodon.online](http://mastodon.online/) I am also not able to see or find my own instance. For some other servers, I am not even able to see them once I am logged in to my own instance: when I navigate to their profiles and hit follow, I am prompted to type my instance URL, once I am hitting „Take me home“ I get the „page not found“-error.

I read some things about LOCAL_DOMAIN and WEB_DOMAIN, but those have never been changed and are identical.

Can someone point me in the right direction? Any help is appreciated - thank you!

### Mastodon instance

mastodon.biophonpodcast.de

### Mastodon version

v4.1.2

### Technical details

- Ruby version: v3.2.2
- Node.js version: 21.2.0

**Comment by renchap** [comment]
Your domain (`mastodon.biophonpodcast.de`) seems to only resolve over IPv6 and does not have an IPv4. I think this is the issue, as some instances are not able to reach out to IPv6-only hosts (this is the case for mastodon.online and mastodon.social)

**Comment by evoscope** [comment]
> Your domain (`mastodon.biophonpodcast.de`) seems to only resolve over IPv6 and does not have an IPv4. I think this is the issue, as some instances are not able to reach out to IPv6-only hosts (this is the case for mastodon.online and mastodon.social)

Yes, that is definitely the case since my ISP is only providing IPv6... Does that mean I won't be able to host an instance without those restrictions or is there a way around that?

**Comment by vmstan** [comment]
Your host may already have a 6>4 proxy in place, otherwise getting to most of the Internet would be extremely problematic.

**Comment by evoscope** [comment]
Thank you for your help - the problem was indeed the missing IPv4-Address. I am running it on a VPS now and everything is working like it should.
