### ISSUE TITLE
Make notification sounds a user option

### ISSUE THREAD

**Issue by ChasBelov** [mastodon/mastodon#28097]
### Pitch

I'm inferring from #27493 that administrators have the ability to set whether Mastodon notifications on an instance have a sound. Please make that a user preference on the Settings Notification tab. My instance has Mastodon set to make sounds on notification, but I don't want any sounds upon notification; I just want it to show up on my notification tabs silently.

### Motivation

Users who leave Mastodon open but are distracted by random sounds when they are concentrating on something else.

**Comment by ClearlyClaire** [comment]
This is not set by admins but by users. This is the “Play sound” toggle in the settings in the notifications column:
![image](https://github.com/mastodon/mastodon/assets/384364/65004f46-c86d-4018-96bd-e50080c8463d)

**Comment by ChasBelov** [comment]
Confirmed. It's actually a usability issue then, for which I will file a separate issue.

**Comment by ChasBelov** [comment]
Usability issue filed as #28110
