### ISSUE TITLE
Request uri must have schema. possibly add 'http://' to the request uri?

### ISSUE THREAD

**Issue by kamilprzybyl** [mastodon/mastodon#28151]
### Steps to reproduce the problem

1. Register your app in Azure AD for SSO integration.
2. Configure Mastodon helm chart. Enable OIDC, and fill the required fields that match your Azure AD settings.
4. Install Mastodon helm chart on a Kubernetes cluster.
5. Access the Mastodon instance and sign in via Azure AD.
6. Enter your Azure AD credentials when prompted, expect to be redirected back to Mastodon.
7. See the error message: `Could not authenticate you from OpenIDConnect because “Request uri must have schema. possibly add 'http://' to the request uri?”.`

### Expected behaviour

User initiates login, provides Azure AD credentials, and successfully redirects back to Mastodon without encountering errors.

### Actual behaviour

User initiates login via Azure AD. After providing Azure AD credentials, the redirection back to Mastodon displays an error: "Could not authenticate you from OpenIDConnect because 'Request URI must have a schema. Possibly add 'http://' to the request URI?'"

### Detailed description

Logs flow from the Mastodon's backend:
`D, [2023-11-30T13:44:53.156410 #10] DEBUG -- omniauth: (openid_connect) Request phase initiated.`
`D, [2023-11-30T13:48:23.959492 #10] DEBUG -- omniauth: (openid_connect) Callback phase initiated.`
`E, [2023-11-30T13:48:24.304848 #10] ERROR -- omniauth: (openid_connect) Authentication failure! Request URI must have schema. Possibly add 'http://' to the request URI?: ArgumentError, Request URI must have schema. Possibly add 'http://' to the request URI?`
`I, [2023-11-30T13:48:24.307504 #10] INFO -- : [d7ba9573b1c852325b6a10f620583035] method=GET path=/auth/auth/openid_connect/callback format=html controller=Auth::OmniauthCallbacksController action=failure status=302 allocations=499 duration=1.59 view=0.00 db=0.00 location=https://mydomain.social/auth/sign_in`

Fact: The Redirect URI has indeed an "https://" as a prefix.

### Mastodon version

v4.2.1

### Technical details

- Kubernetes version: 1.26.10
- OS: flatcar [3602.2.1]

**Comment by trwnh** [comment]
is this a duplicate of #28143?

**Comment by kamilprzybyl** [comment]
So apparently I misconfigured my OIDC settings.

Turns out that when `discovery` is set to false, you should also manually provide all four `jwks_uri`, `auth_endpoint`, `token_endpoint`, and `user_info_endpoint` along.

I skipped `jwks_uri`, and `user_info_endpoint` as it seemed not relevant to me. This is the configuration that is working for me:

```
display_name: "Sign in with Azure AD"
issuer: https://login.microsoftonline.com/{tenant}/v2.0
discovery: false
scope: "openid,profile,email"
uid_field: email
client_id: REDACTED
client_secret: REDACTED
redirect_uri: https://{your_domain}/auth/auth/openid_connect/callback
jwks_uri: https://login.microsoftonline.com/{tenant}/discovery/v2.0/keys # NEED when discovery != true 
auth_endpoint: https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize # NEED when discovery != true 
token_endpoint: https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token # NEED when discovery != true 
user_info_endpoint: https://graph.microsoft.com/oidc/userinfo # NEED when discovery != true 
```
