### ISSUE TITLE
Issue: YouTube video starts playing when it shouldn't

### ISSUE THREAD

**Issue by testuser51** [mastodon/mastodon#28168]
### Steps to reproduce the problem

1. Make a post with a link to a YouTube video
2. Click on the button to open the video on the original website in a new tab
3. The video starts playing in the social network itself in the previous tab

![image](https://github.com/mastodon/mastodon/assets/53906414/fd0af5a1-dcf1-4678-ab8a-6ec66e438339)

### Expected behaviour

Video does not start playing

### Actual behaviour

Video starts 

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.2+pr-28082-54a234c

### Browser name and version

Firefox 120.0.1

### Operating system

Windows 11 Pro 23H2

**Comment by dhthwy** [comment]
fwiw, I've confirmed this.

**Comment by testuser51** [comment]
The problem no longer appears 

Firefox 131
v4.3.0-rc.1+pr-32223-dccfe46
