### ISSUE TITLE
Offset parameter is not validated, leading to 500 Internal Server Error

### ISSUE THREAD

**Issue by bocops** [mastodon/mastodon#28197]
### Steps to reproduce the problem

1. Access API endpoint `/api/v1/directory` or `/api/v2/search` with `offset` set to a negative value (plus other parameters set to anything as necessary to successfully make the call).

### Expected behaviour

A negative offset should lead to a response like 422 Unprocessable Entity, because the request was well-formed but illegal/invalid.

### Actual behaviour

Response is 500 Internal Server Error

### Detailed description

Offset parameter is not validated before being used in both [search_controller.rb](https://github.com/mastodon/mastodon/blob/456597dae5251af841e46ab0608e0d44a7de1197/app/controllers/api/v2/search_controller.rb) and [directories_controller.rb](https://github.com/mastodon/mastodon/blob/456597dae5251af841e46ab0608e0d44a7de1197/app/controllers/api/v1/directories_controller.rb).

Other parameters that might be used similarly wrong are validated - for example the `limit` parameter seems to be interpreted as positive even if a negative value is given.

If there are other endpoints using an offset parameter, they may be affected as well.

### Mastodon instance

all

### Mastodon version

v4.2.1

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by bocops** [comment]
This has probably been fixed with #28282, although not yet in any live 4.2.x release that I could check myself.

**Comment by mjankowski** [comment]
I suspect it did resolve it - were you able to verify?

If this is still happening on current (4.3) release, please reopen.
