### ISSUE TITLE
Track Blocked Users / Suggest Blocking Instance

### ISSUE THREAD

**Issue by Robbie-Norlyn** [mastodon/mastodon#28190]
### Pitch

Mastodon feature idea: Your account keeps track of how many users from each instance you have blocked; if it reaches a set limit, then it prompts you to suggest blocking the entire instance.

### Motivation

I believe that this will be incredibly useful for users and admins for content moderation.

**Comment by ThisIsMissEm** [comment]
This is duplicated by https://github.com/mastodon/mastodon/issues/29383 in many regards.

@vmstan I think we should close this issue as a duplicate, since #29383 has more details.
