### ISSUE TITLE
Onboarding page (/start) errors when logged out

### ISSUE THREAD

**Issue by TheEssem** [mastodon/mastodon#28201]
### Steps to reproduce the problem

1. Go to `https://<instance domain>/start` on any instance on v4.2.0 or later while logged out
2. See the page output

### Expected behaviour

The page should either return a 403 or some alternative content.

### Actual behaviour

The page throws a rendering error with a stack trace.

### Detailed description

Before the onboarding page refactor, the page would render correctly but with no follow suggestions. Now it returns a page that suggests something is broken on the instance.

I recognize that this page isn't intended to be viewed by logged-out users, so it would probably be a good idea to validate that when attempting to load the page.

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.2+pr-28082-54a234c

### Browser name and version

Floorp 11.6.1 (based on Firefox ESR 115)

### Operating system

EndeavourOS Linux

### Technical details

Here's the output of the "Copy error report" button:
```
TypeError: e is null
account (webpack:///app/javascript/mastodon/features/onboarding/index.jsx:123:90)
wi (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:3592:9)
di (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:3577:10)
Bc (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:1068:2)
bd (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5339:57)
bd (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5336:6)
Error(p (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5325:19)
Xj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5115:84)
Rj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5048:9)
ul (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:7037:14)
kl (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6852:2)
Q (webpack:///node_modules/react/cjs/react.production.min.js:121:76)
R (webpack:///node_modules/react/cjs/react.production.min.js:127:2)
M (webpack:///node_modules/react/cjs/react.production.min.js:81:120)
```

**Comment by jh97uk** [comment]
I can't seem to replicate this issue on MacOS 12.3.1 using Firefox 122. I've tried both mastodon.social and mstdn.social . Perhaps this has been fixed now?

**Comment by timothyjrogers** [comment]
I can reproduce this on Windows in both Chrome and Firefox both on my dev instance with current `main` code as well as on a production instance running `4.2.8`.

When accessing `/start` unauthenticated you get this rendering error:

![image](https://github.com/mastodon/mastodon/assets/1100533/0ba5d900-8be0-4689-9626-3e0a808be1e4)

As opposed to when you access something like `/home` you get this permissions error:

![image](https://github.com/mastodon/mastodon/assets/1100533/3b31bc11-dcbb-41a1-ab8d-10c01fd063da)

**Comment by timothyjrogers** [comment]
I submitted a fix here: https://github.com/mastodon/mastodon/pull/30023

That makes `/start` show the consistent "You need to login..." message if you are unauthenticated, instead of throwing the rendering error.
