### ISSUE TITLE
Cant find Husky git?

### ISSUE THREAD

**Issue by MConsuela** [mastodon/mastodon#28257]
### Steps to reproduce the problem

1. Upgrade Mastodon using "sudo yunohost app upgrade mastodon -u https://github.com/YunoHost-Apps/mastodon_ynh --debug"
2.
3.
...

### Expected behaviour

Upgrading Mastodon

### Actual behaviour

Stopped Upgrading

### Detailed description

681842 WARNING husky - .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)
681868 WARNING error Command failed with exit code 1.

### Mastodon instance

-

### Mastodon version

v4.2.1

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)
3.2.2
v18.19.0

**Comment by p37307** [comment]
You might get specific help at YunoHost-Apps since you are upgrading via it, if I understand you post correctly. Here is its Mastodon instance issue page. https://github.com/YunoHost-Apps/mastodon_ynh/issues

**Comment by MConsuela** [comment]
i see, its not very active tho :)

**Comment by p37307** [comment]
Looks like they upgraded 4.2.3~ynh1 ( https://github.com/YunoHost-Apps/mastodon_ynh/pull/418 ) 16 hours ago and tested some failures a few hours ago. ( https://github.com/YunoHost-Apps/mastodon_ynh/pull/419  https://github.com/YunoHost-Apps/mastodon_ynh/pull/420 )

 Somebody is around. ;) Good luck. Hope you get it resolved.

**Comment by ClearlyClaire** [comment]
Feel free to reopen with more details if that cannot be sorted out on their side, but this appears to be an issue with the YunoHost package.

**Comment by MConsuela** [comment]
Thanks, tried to reopen but it seems to not work?

This is the Full Log: https://paste.yunohost.org/raw/uvicumotus

**Comment by ClearlyClaire** [comment]
Looking at your log file, it *seems* to break because of husky not finding the `.git` indeed, but on my end, this does not make `yarn install --pure-lockfile` return a failure code, and the installation can proceed.

Can you share the output of `yunohost log share 20231208-102118-backup_restore_app-mastodon`?

**Comment by MConsuela** [comment]
Here you go, thanks for the help so far :)

https://paste.yunohost.org/raw/ugumasisod

**Comment by ClearlyClaire** [comment]
Thanks. Interestingly, this doesn't mention `husky` at all. I don't understand YunoHost to know for sure, but I suppose this may be caused by the `ld_preload: unbound variable` error:
```
2023-12-08 02:32:21,754: WARNING - /var/cache/yunohost/app_tmp_work_dirs/app_fgeqynw6/restore: line 123: ld_preload: unbound variable
2023-12-08 02:32:21,756: DEBUG - ++ ynh_exit_properly
2023-12-08 02:32:21,760: DEBUG - ++ [[ restore =~ ^install$|^upgrade$|^restore$ ]]
2023-12-08 02:32:22,266: DEBUG - ++ ynh_clean_setup
2023-12-08 02:32:22,266: DEBUG - ++ true
2023-12-08 02:32:22,266: DEBUG - ++ exit 1
2023-12-08 02:32:23,269: ERROR - Could not restore mastodon: An error occured inside the app restore script
```

This really doesn't look like a Mastodon issue but an issue with the YunoHost package. Please bring the issue to them.
