### ISSUE TITLE
"Change language" button in the panel to create a new status has line wrap for long language tags

### ISSUE THREAD

**Issue by myl7** [mastodon/mastodon#28250]
### Steps to reproduce the problem

1. Open the index page
2. For wide desktop, focus on the status creating panel on the left; For other devices, click the button "New post" on the right top
3. Now we can see the "Change language" button (no text, but just an icon button with the language tag as the value) has line wrap, causing the button part long together with a large line spacing

<img src="https://github.com/mastodon/mastodon/assets/49339031/9491d2f5-3310-421b-bd9a-88a1f04168c8" width=300px />

### Expected behaviour

The langage tag should be displayed in only one line, with a slightly large icon button

### Actual behaviour

The langage tag breaks at `-` and has line wrap

### Mastodon instance

https://social.myl.moe

### Mastodon version

v4.2.3

### Browser name and version

Mozilla Firefox 120.0.1

### Operating system

Arch Linux

### Technical details

After F12 to check the CSS, the icon button has a `width` style, which can cause the line wrap.
The related code seems to be at:

https://github.com/mastodon/mastodon/blob/af66d3d836b89286423d4ba9fe1518bb6317b499/app/javascript/mastodon/features/compose/components/privacy_dropdown.jsx#L268

I am not sure. Maybe just a larger `size` can resolve the problem.

**Comment by ClearlyClaire** [comment]
Hi! This has been addressed already in the development version thanks to #27100
