### ISSUE TITLE
user profile view "posts and replies" does not include boosts

### ISSUE THREAD

**Issue by ke352802081770314** [mastodon/mastodon#28292]
### Steps to reproduce the problem

1. click on a user name
2. in the profile, note that the initial view is "posts", it contained the pinned posts first, then a mix of initial posts, boosts and self-replies to initial posts ("threads") but no replies to other posts. fine.
3. switch to "posts and replies", notice that pinned posts and boosts are absent

### Expected behaviour

based on the titles, I expected that "posts and replies" contains a superset of "posts", i.e. the complete timeline I'd see if i followed that user

### Actual behaviour

boosts are missing. When someone boosts and then replies to a post, there is no view to show both to provide the relevant context

### Detailed description

my expectations could be adjusted to the present situation by renaming "posts" to "pins, posts and boosts" so that I understand what is missing in "posts and replies" (I don't mind leaving out the pinned posts, I already saw them before switching to the other view)

I would prefer that either "post and replies" also contains boosts, or there is a further tab "everything" that does.

* when making a decision whether to follow a user, I use "posts and replies" expecting to see what would land in my timeline if I do, now I know that I have to examine both "posts" AND "posts and replies" to get a feel for it, that is more work
* as mentioned above, context is missing, and I would have to click on a reply to see the thread, even if the user had tried to help me by boosting the post they are referring to first.

### Mastodon instance

mstdn.animexx.de

### Mastodon version

v4.2.0

### Browser name and version

Firefox 120.0

### Operating system

Linux Ubuntu 20.04LTS

**Comment by Cassolotl** [comment]
This is intentional: *Change reblogs to be excluded from "Posts and replies" tab in web UI #26302*

Boosts are included in "posts", though.

**Comment by ke352802081770314** [comment]
Thank you for clarifying. As shown in the comments there, it was a deliberate choice that a completze view of activities is not provided, so I'll have to note it and puzzle together the things I am trying to see.

**Comment by trwnh** [comment]
See also:
- #10011
