### ISSUE TITLE
Sign up in very easy mode

### ISSUE THREAD

**Issue by stemy2** [mastodon/mastodon#28294]
### Pitch

I think it would be useful to propose the choice of an "easy mode", it would select automatically the server among the ones that are listed on the official site and explaining in tldr mode.

### Motivation

The main reason for many people to not join Mastodon is that is too difficult and too time-wasting to choose the server based on the rules and the place where it is hosted, it would be easier for dummies.

**Comment by renchap** [comment]
Where would you like this?

At the moment, the official mobile apps have an "easy" sign-in button directing toward mastodon.social, same for joinmastodon.org.

If you are on an instance, it will offer you to sign up locally (if registrations are open).

**Comment by trwnh** [comment]
Closing this issue because it is not related to the Mastodon server software. As mentioned previously, it would be better suited for the point-of-first-contact, like joinmastodon.org
