### ISSUE TITLE
Short videos does not display on Firefox

### ISSUE THREAD

**Issue by liofeu** [mastodon/mastodon#28307]
### Steps to reproduce the problem

1. Upload a short video in a Mastodon post
2. Open the message

### Expected behaviour

The video is displayed and can be played

### Actual behaviour

The video is described as GIF but nothing is played

### Detailed description

I uploaded short (less than a few sec) .mp4, .mov, .m4a video files (without sound). They seem to be treated as GIF probably because they are short or because they was no sound (fine to me), but nothing is displayed and it cannot be played:
![Capture d’écran 2023-12-09 à 17 36 03](https://github.com/mastodon/mastodon/assets/8751025/ecee20da-fdc9-4fb1-8bfb-8824e73a9323)

The issue occurs on Firefox (120.0.1 (64 bits)) but not on Chrome or Safari.
I tested it on instance "musicians.today" and "tooter.social" and found the issue on both.
Fine with a longer sound&video mp4 file.

Also note that nothing is displayed when I click on the ALT button even if I filled this tag.

### Mastodon instance

musicians.today

### Mastodon version

v4.2.3

### Browser name and version

Firefox 120.0.1 (64 bits)

### Operating system

macOS 10.15.7

**Comment by vmstan** [comment]
Do you have a copy of the video you can share?

**Comment by liofeu** [comment]
The issue seems to have disappear.
