### ISSUE TITLE
Update "e-mail" -> "email" in API responses and user-facing screens

### ISSUE THREAD

**Issue by andypiper** [mastodon/mastodon#28317]
Per https://github.com/mastodon/documentation/pull/1365#issuecomment-1849964942 we are modernizing the user of the term "email" across the app and docs.

**Comment by morgankar** [comment]
Is this issue still open? If it is, I would like to work on this!

**Comment by andypiper** [comment]
Yes, actually I only just opened it last week to align with documentation changes. Happy to review a PR on this.

**Comment by morgankar** [comment]
Great, I would love to do this one! Can you assign me this issue please ? Thank you Andy

**Comment by 7H3XXX** [comment]
Is this issue still open ?

**Comment by morgankar** [comment]
@andypiper Can I replace the "e-mail" with "email" **everywhere** in the repository instead of only user-facing screen?

**Comment by beanieyi** [comment]
I will work on this issue if allowed to!

**Comment by andypiper** [comment]
@beanieyi sure, I have yet to see a PR that addresses this issue and would be happy to review one if submitted.

**Comment by beanieyi** [comment]
Sounds good!

**Comment by trwnh** [comment]
Fixed in #31317 maybe? Is there anything else left to do?

**Comment by andypiper** [comment]
I think there is also [this](https://github.com/mastodon/documentation/pull/1365#issuecomment-1849964942) (in the docs repo) to merge.
