### ISSUE TITLE
Remove the limit to number of posts which can be pinned and add a new, separate "Pinned posts" column to profiles columns

### ISSUE THREAD

**Issue by pezcurrel** [mastodon/mastodon#28348]
### Pitch

I think it would be very good to remove the limit to number of posts which can be pinned and add a new, separate "Pinned posts" column to profiles columns.

### Motivation

I often find myself having to unpin some posts from "posts" column in my profile, to make space for others (just as, i guess, many others do). I think it would be good to have no limits to the number of posts which can be pinned (currently, it's 5), because they can be used to show what one thinks are the most important things for them, and what and how they think of them; and removing the limits of post which can be pinned would require a dedicated, separate column to be added to profiles column (the top 5 pinned posts could remain on top of the "posts" column, as they are now, or just don't show there any longer).

(It would also be very useful to have the ability to easily order pinned posts - see also: https://github.com/mastodon/mastodon/issues/28163 -, more so if you removed the limit to the number of posts that can be pinned).

**Comment by trwnh** [comment]
Duplicate of #6828 and #19657

**Comment by trwnh** [comment]
Reopening as not a duplicate anymore.
