### ISSUE TITLE
Missing content in link embeds of Mastodon posts

### ISSUE THREAD

**Issue by maia-s** [mastodon/mastodon#28392]
### Steps to reproduce the problem

1. Post a link to a Mastodon post on e.g. Discord or anywhere else a link to a Mastodon post will embed a preview of the post

### Expected behaviour

Embeds show full content of the post (where reasonable)

### Actual behaviour

Embeds are missing content

### Detailed description

1. Post text is cut off with an ellipsis at a certain point. The posts this happen to aren't particularly long. If this can't be fixed, can the limit at least be enlarged?
2. Posts with a video only embeds the video, without any text
3. Posts with multiple images only display the first image in the embed.
4. (Feature Request) Often there's no way to tell if a Mastodon embed is Mastodon. Can it mention Mastodon in the embed?

**Comment by Gargron** [comment]
This is a Discord issue. We put the full text in there, all the images, etc.
