### ISSUE TITLE
A new signup that lets the user pick from two or three hand-picked servers

### ISSUE THREAD

**Issue by bluebbberry** [mastodon/mastodon#28406]
### Pitch

Instead of being directed towards mastodon.social, the user is presented with two or three hand-picked servers that pose an implicit question, e.g.:

![pic-1](https://github.com/mastodon/mastodon/assets/145382759/a4b8d961-b340-4858-9998-98be694b06b7)

Users should intuitively be able to choose the server that fits to their needs. Through this, they gain a sense of reclaiming their own digital agency. This introduces the concept of dezentrallized, interconnected services to the user with a positive outcome that they consider in the future again.

An alternative could look like this:

![pic-2](https://github.com/mastodon/mastodon/assets/145382759/5d5d63b2-9e70-4165-9115-8484751dc0b0)

Or more playful:

![pic-3](https://github.com/mastodon/mastodon/assets/145382759/bafdc973-a625-45bf-b3b7-28d668b86c10)

Of course, the option to pick from all servers should still be available in the sub-menu.

### Motivation

Dezentrality is the key feature of Mastodon, because it gives users agency to a degree that they doesn't find on the internet anymore these days. This should be reflected in the onboarding and I think the signup is the best moment for that.

There are three main options to tackle this, two of which have been tried out on a broad scale:

1. Full Choice (November 2022 implementation; still available in the sub-menu of the current signup): Gives users the choice between all (or a big amount of) existing Mastodon servers.
2. No Choice, default to mastodon.social (current implementation): remove the threshold of choosing altogether and default to a certain, well-established server. This hides the choice at the beginning, making the entry as convenient as possible. The complete idea will become clear eventually; maybe it could be explicitly introduced to the user later.
3. Small-Scale Choice: Introduce choice to a limited degree thus lowering the threshold, e.g. let user choose between three instances based on implicit questions (what are my values, how intense should my timeline be, etc.)

The option to choose would be the one that gives the user a certain sense of agency without overwhelming them. The current implementation of no choice, while certainly being better than the first one, does a bad job here. I think that is, because it is based on a wrong assumption, namely that a new user is actually able to pick from all the Mastodon-servers the right one on first try. It also assumes that they are immediatly mature enough to take on that responsibility of choosing for themselves, while this sense of responsibility has been eroded for decades. Partly, I think to this assumption also contributed the hope that you stay on your Mastodon server forever; as if you are able or that it is even possible to pick your Mastodon server "on first glance" even though of course its the people that are there, which you cannot see in that inital server list

Regardless of the actual reason, this assumption leads to a fairly presumptuous conclusion: either the user knows enough to choose the right server from the list of all servers, or they aren't and need to be hold by their hand. Instead of giving the user agency, it leaves them back felling immature: because you cannot decide for yourself, we decide for you.

The motivation is of course not bad per se. New users need guidance and the new freedom that comes with more options also puts new responsibility on the user, which can feel scary. A kind of "no swimmers area" is a good idea here, but why not include in it a first taste of what dezentrality means?

If the average user isn't ready to pick the right server and based on the descriptions of the server that's not possible anyways, why not step away from that high standard. Instead of putting the user in the position to choose the perfect server for a live-time or not choose at all, why not give them the choice between a handful of trusted servers that sets them off on a journey for finding their perfect server and already pushes them in the right direction. And it already gives them the feeling that to the server they are currently on, there is always an alternative. This is the decentralized mindest that should be fostered by the onboarding process for being a mature Mastodon-user in the future.

One could argue that this approach will scare away potential users. However, I would argue that the current implementation only removes the confusion of users on first glance, because it plunges them in a dezentralized world without being introduced to the concept of it. Also, it gives them a false sense of being on the "main server", which they are be reluctant to leave, resulting in a giant entry-server, which people use like every other centralized service. If people are on Mastodon but in their minds are still in a walled garden, we have effectively gained nothing.

So I would argue that the third option is the best one. Now the key goal of the new signup should be that the choice that is posed to them can intuitively be answered by most new users. This way, they will feel a sense of reclaiming their agency without being overwhelmed by the new possibilites they have. Then, chances are higher that they consider migrating again in the future and eventually internalize it as a permanent option of the digital world.

**Comment by trwnh** [comment]
This doesn't seem to be targeted at individual servers or the software project, but rather an external promotional avenue like joinmastodon.org or likewise.
