### ISSUE TITLE
Spam/Junk inbox, "Quarantine"

### ISSUE THREAD

**Issue by ShadowJonathan** [mastodon/mastodon#28429]
### Pitch

Primarily a user-story; have a seperate API toggle/"inbox" for retrieving replies or DMs "marked as spam". (Possibly named "Quarantine" (as an alternative to "junk" or "spam", to make it more neutral)

These would be picked up by filters, semi-automatic means, or otherwise.

Users would still have the ability to go through these DMs/replies and view them.

(optional) Possibly, servers/users marked as limited should have DMs automatically delivered here, so they are "out of the way", but not completely inaccessible for users.

### Motivation

While the recent spam waves from .social, .online, and .world are partially 'to blame' for bringing this up again, I think this could be turned into a feature, where spam is acknowledged as an aspect of federated networks, and users have a way to sort/access them, similar to email.

This does not mean that spam will begone, but it means that it is not massively disruptive to users. It could also provide a way to retrieve "hidden" messages, instead of completely sequestering, like "limit" currently does.

**Comment by trwnh** [comment]
#12181
