### ISSUE TITLE
Anchors in URLs are displayed as hashtags on posts

### ISSUE THREAD

**Issue by clarfonthey** [mastodon/mastodon#28438]
### Steps to reproduce the problem

Creating the post:

```
I'm going to post this without context for a mastodon bug report: https://www.youtube.com/watch?v=8wUOUmeulNs#t=1m22s
```

The result is a post with an incorrect `#t` hashtag at the bottom under the list of hashtags.

### Expected behaviour

This post which contains no hashtags should not have a hashtag listed in the hashtags list.

### Actual behaviour

This post which contains no hashtags has a hashtag listed in the hashtags list.

### Detailed description

As a Mastodon User, I would like to be highly constrained in the way I write bug reports to ensure that all bugs fit into the two neat boxes of "frontend" and "backend." As a Mastodon User, I would additionally like to be forced to include all information in required fields, because I cannot be trusted to file useful, terse bug reports when simply provided with a template.

As a Mastodon User, I would like to be forced to fill out the form again if I label something as a frontend issue instead of a backend issue after doing additional investigation.

As a @ clarfonthey @ toot.cat, I would like to search `in:library #t` and not find the example post I shared.

### Mastodon instance

toot.cat

### Mastodon version

v4.3.0-alpha.0+glitch

### Browser name and version

Firefox 119.0

### Operating system

`Linux 6.5.9-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 26 Oct 2023 00:52:20 +0000 x86_64 GNU/Linux/Genuine Edition`

### Technical details

Although the markup in the post only includes one link to the URL *and* the URL is properly shortened, removing the hashtag, the hashtag is still detected by the backend and the post shows up on the listing for the hashtag "extracted" from the URL.

Additionally, the instance runs the Glitch fork of Mastodon, but I have no reason to believe that this issue does not exist in mainline.

**Comment by vmstan** [comment]
I actually wasn't able to reproduce this on mastodon.online or vmst.io which are on `main`/4.3 as well. 

This has been tweaked a couple times in https://github.com/mastodon/mastodon/issues/27552 and https://github.com/mastodon/mastodon/pull/27271 so it's possible these haven't been taken up by Glitch @ClearlyClaire 

Also possible toot.cat isn't running these, but the last commit was from October.

**Comment by clarfonthey** [comment]
Oh huh, I tried searching for this but really didn't know where to start. That PR does look like it fixes the issue, but I'll wait for Claire to respond in case it didn't make it onto the Glitch fork.

**Comment by ClearlyClaire** [comment]
It should have been merged into glitch-soc at the end of October (https://github.com/glitch-soc/mastodon/pull/2449), but please note the incorrect tagging happens at the moment of authoring, not displaying.

**Comment by clarfonthey** [comment]
I'll close this then; toot.cat is probably just a bit out of date.
