### ISSUE TITLE
API documentation says “Authorization” header required for getting account’s followers/following but it actually isn’t

### ISSUE THREAD

**Issue by sayunuh** [mastodon/mastodon#28482]
### Steps to reproduce the problem

1. In your browser, open `https://mastodon.social/api/v1/accounts/13179/followers` (Followers list of `@Mastodon@mastodon.social`)

### Expected behaviour

According to the documentation ( https://docs.joinmastodon.org/methods/accounts/#followers ), an Authorization header is required, and you didn’t provide one, so an Unauthorized error is expected.

### Actual behaviour

The server happily returns the followers list.

### Detailed description

Assuming that the behaviour is intended, the “REQUIRED” label should be removed from the documentation. And probably the response sample of “401: Unauthorized” below, too. The `following` API seems to have the same issue as `followers`.

### Mastodon instance

mastodon.social and others

### Mastodon version

v4.2.3+pr-28367-d3dbf08

**Comment by trwnh** [comment]
Please file this issue against https://github.com/mastodon/documentation instead

**Comment by sayunuh** [comment]
@trwnh Thank you for the direction and the pull request.
