### ISSUE TITLE
Add the ability to compose a thread (write multiple posts at the same time)

### ISSUE THREAD

**Issue by brendanjones** [mastodon/mastodon#28486]
### Pitch

I'd like to be able to compose more than one post at a time, and then post them all at once in a thread.

Honestly Twitter's thread composer implementation is great, I'd say use the exact same UX but adapted for the Mastodon UI:

<img width="606" alt="Screenshot 2023-12-24 at 00 10 54" src="https://github.com/mastodon/mastodon/assets/16049594/6f725ebb-f1e3-4461-931f-09fb111fcf58">

### Motivation

It's currently quite frustrating composing a thread. Many problems with the current situation:

1. People can start replying to the thread before you're actually done with it.
2. If it's a long thread, you're better to go write the thread in another app before pasting it in one-by-one into Mastodon. Especially because the composer box is too small (fixed by https://github.com/mastodon/mastodon/issues/26603 and https://github.com/mastodon/mastodon/issues/19816).
3. There's the risk of losing text if you write a post, realise it's over the character limit, then have to cut text, post, then paste the excess text into the reply.
4. The UX of writing a thread is frustrating - every time you post you have to navigate to the new post before you can reply to it.

I'm sure someone must have requested this already but I've searched high and low for this feature request and couldn't find anything. Please let me know if this is duplicate!

**Comment by chrisschm** [comment]
At least it would be helpfull for the reader too, because the writer could show the number of included posts of the thread in first post and the second (to the last) posts of the thread could made unlisted by default. I am supporting this suggestion.

**Comment by Cassolotl** [comment]
Might be a duplicate of *Creating thread at once, without publishing first post (Web-interface masotodon.social) #27349*?

**Comment by brendanjones** [comment]
Uggh yes, thank you, I knew it must exist. Though in my defence that’s not a great title on that one. Righto, closing this.
