### ISSUE TITLE
Animated gif instead of mp4 when gif is smaller.

### ISSUE THREAD

**Issue by tinspin** [mastodon/mastodon#28499]
### Pitch

I uploaded a small .gif animation for my latest retro game: https://multiplayeronlinestandard.com/monsters2.gif (330KB) and mastodon compressed this thing into something ugly (blur at the start) and larger: http://move.rupy.se/file/334b1958481df97a.mp4 (833KB)

### Motivation

Because this is unintelligent and lazy. Everyone.

**Comment by vmstan** [comment]
Duplicate of #15471
