### ISSUE TITLE
Language switcher does not have enough space

### ISSUE THREAD

**Issue by mattholy** [mastodon/mastodon#28502]
### Steps to reproduce the problem

It is on the homepage

### Expected behaviour

<img width="275" alt="image" src="https://github.com/mastodon/mastodon/assets/22177897/2c5331a3-74dc-4a1c-8fc2-04a12c45d2e8">

### Actual behaviour

<img width="322" alt="image" src="https://github.com/mastodon/mastodon/assets/22177897/e77f1cf5-8ba3-49c8-85ad-f2d52722b670">

### Detailed description
When remove or disable width property, it seems ok.
<img width="209" alt="image" src="https://github.com/mastodon/mastodon/assets/22177897/e009bda2-3c1f-4f4d-84e8-cb2833266fa9">

### Mastodon instance

social.kryta.app

### Mastodon version

v4.2.3

### Browser name and version

MS EDGE 120.0.2210.91

### Operating system

MacOS 14.2.1

**Comment by vmstan** [comment]
This should be fixed by the pending redesign in #28119
