### ISSUE TITLE
Streaming endpoint on Vagrant sends 301 redirect to localhost

### ISSUE THREAD

**Issue by sgtatham** [mastodon/mastodon#28539]
### Steps to reproduce the problem

I wanted to test an in-development Mastodon client's use of the streaming API endpoints such as `/api/v1/streaming/user`, so I set up a development instance using Vagrant as follows:
1. cloned the git repo on Ubuntu 22.04, obtaining the head commit 6374358357ee81b5f137f471f028a56974109155
2. ran `vagrant up` in the root of the checkout, and authorised it to add `mastodon.local` to my `/etc/hosts`
3. ran the suggested startup command `vagrant ssh -c "cd /vagrant && foreman start"`
4. created a test user on the instance using the web UI, and authenticated my test client

The client tried to access the streaming API, by sending an HTTP request as follows (observed via `strace`, since in this environment we're using cleartext HTTP):
```
GET /api/v1/streaming/user HTTP/1.1
authorization: Bearer LHfBPlUXWkgVSZl5DMSiBOTD1CeaidAWwWs8TiUKmUk
accept: */*
host: mastodon.local
```

### Expected behaviour

I expected that this GET request would return a 200 status and begin delivering chunked data, starting with a line such as ":)" and continuing with ":thump" heartbeats interleaved with update events.

### Actual behaviour

The web server on the Vagrant instance returned a 301 redirect to a URL on "localhost", so my client next tried to connect to the host machine, and got 404 because _that_ web server knows nothing about the test Mastodon instance.

### Detailed description

The full HTTP response from the Mastodon test server was:
```
HTTP/1.1 301 Moved Permanently
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 0
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin-when-cross-origin
X-RateLimit-Limit: 300
X-RateLimit-Remaining: 299
X-RateLimit-Reset: 2023-12-31T14:55:00.170985Z
Location: http://localhost/api/v1/streaming/user
Content-Type: text/html; charset=utf-8
Cache-Control: private, no-store
Content-Security-Policy: default-src 'none'; frame-ancestors 'none'; form-action 'none'
X-Request-Id: 0b582768-c006-4a45-b808-49803c87e1d4
X-Runtime: 0.126129
Server-Timing: cache_read.active_support;dur=0.02, sql.active_record;dur=0.66, cache_generate.active_support;dur=1.31, cache_write.active_support;dur=0.11, instantiation.active_record;dur=0.23, start_processing.action_controller;dur=0.00, redirect_to.action_controller;dur=0.03, process_action.action_controller;dur=7.38
vary: Authorization, Origin
Content-Length: 0
```

### Mastodon instance

mastodon.local (installed via Vagrant)

### Mastodon version

v4.3.0-alpha.0

### Technical details

Software versions that `vagrant up` installed for me:
```
vagrant@mastodon:~$ ruby --version
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
vagrant@mastodon:~$ node --version
v20.10.0
```

**Comment by ClearlyClaire** [comment]
My understanding is that in a development environment, unless `REMOTE_DEV` is set to `true`, the streaming server host will be overridden to `localhost`.

The following patch should fix the issue:
```patch
diff --git a/.env.vagrant b/.env.vagrant
index 69c1bf1fb3..cea5c5a13f 100644
--- a/.env.vagrant
+++ b/.env.vagrant
@@ -1,4 +1,5 @@
 VAGRANT=true
 LOCAL_DOMAIN=mastodon.local
+REMOTE_DEV=true
 BIND=0.0.0.0
 DB_HOST=/var/run/postgresql/
```

However, `REMOTE_DEV` (introduced in #504, re-used in #5942) is undocumented, and I wonder if it's not better to use the `REMOTE_DEV` code path unconditionally.

**Comment by sgtatham** [comment]
Thank you! I didn't know about `REMOTE_DEV`. But I'm afraid that when I enabled it using your patch and spun up a fresh Vagrant VM, the streaming still didn't work, for a different reason.

Now, my client on the host machine tries to access `http://mastodon.local/api/v1/streaming/user`, by connecting to 192.168.42.42 port 80 and sending `GET /api/v1/streaming/user HTTP/1.1` (plus bearer token and other headers, similarly to my original report). The result is still a 301 redirect, and it contains the header
```
Location: http://mastodon.local/api/v1/streaming/user
```
... i.e. a redirect to exactly the same URL. So my client promptly sends another copy of exactly the same `GET` request down the existing still-open connection, and gets into a redirect loop (which my HTTP library eventually notices and reports as a failure).

I spotted this in the startup messages:
```
10:35:03 stream.1  | WARN Streaming API now listening on 0.0.0.0:4000
```
so I manually tried connecting to port 4000 of the VM, via the curl command
```
curl -v http://mastodon.local:4000/api/v1/streaming/user -H 'Authorization: Bearer xxxxx'
```
and _that_ did what I expected: curl received the initial `:)` greeting.

So I guess it was correct that the main web server sent me a 301, but it should have redirected to `http://mastodon.local:4000/api/v1/streaming/user` rather than straight back to plain `mastodon.local`?

**Comment by ClearlyClaire** [comment]
Can you try the following?
```patch
diff --git a/app/controllers/api/v1/streaming_controller.rb b/app/controllers/api/v1/streaming_controller.rb
index 0cdd00d62f..0cb6e856f2 100644
--- a/app/controllers/api/v1/streaming_controller.rb
+++ b/app/controllers/api/v1/streaming_controller.rb
@@ -13,7 +13,9 @@ class Api::V1::StreamingController < Api::BaseController
 
   def streaming_api_url
     Addressable::URI.parse(request.url).tap do |uri|
-      uri.host = Addressable::URI.parse(Rails.configuration.x.streaming_api_base_url).host
+      base_url = Addressable::URI.parse(Rails.configuration.x.streaming_api_base_url)
+      uri.host = base_url.host
+      uri.port = base_url.port
     end.to_s
   end
 end
```

**Comment by sgtatham** [comment]
I'm happy to. But is that in addition to the patch in your PR (which I've only just noticed), or without it?

**Comment by ClearlyClaire** [comment]
It's in addition to the earlier patch!

**Comment by sgtatham** [comment]
That looks good from the server side! Testing with curl, now my request for `http://mastodon.local/api/v1/streaming/user` returns a redirection to `http://mastodon.local:4000/api/v1/streaming/user`, and if I request that URL in turn with the same bearer token, I get a live streaming connection.

(It still doesn't work in my test client, because that doesn't keep the bearer token when it follows a redirect. But _that_ is unquestionably my problem and not yours!)

**Comment by sgtatham** [comment]
This all looks good! I've just updated to git commit bd415af9a11fe7057c9f428b7bdaeb8d4fb3a77b, removed all my local patches, and re-checked again. Everything works – my test client can now access the streaming service on the test VM with no trouble at all.

Thank you for the quick response and fixes!
