### ISSUE TITLE
not auto clearing cache

### ISSUE THREAD

**Issue by vengefulpunk** [mastodon/mastodon#28583]
### Steps to reproduce the problem

normal server operation will not auto clear cache

### Expected behaviour

cache cleared every 10 days

### Actual behaviour

cache is never cleared

### Detailed description

After my initial upgrade to 4.2.x I noticed media cache is not being cleared automatically anymore. Manually running ./bin/tootctl media remove does still work. 

### Mastodon instance

darktundra.xyz

### Mastodon version

4.2.3

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.2.2
- Node.js version: v16.20.2

**Comment by vmstan** [comment]
I suspect this is fixed by #28184 but do you have error messages in your Sidekiq scheduler logs along the lines of what is seen in https://github.com/mastodon/mastodon/issues/27752?

**Comment by vengefulpunk** [comment]
I am still reasonably new to administering a mastodon server, but I should have thought to check Sidekiq, and it does seem like it is the same issue. Thanks!
