### ISSUE TITLE
Blocklist Feed Support

### ISSUE THREAD

**Issue by kkarhan** [mastodon/mastodon#28605]
### Pitch

Besides manually adding a CSV file for blocks under ``/settings/imports`` , the option to automatically pull and update / overwrite blocklists would be greatly appreciated.

This could also provide a good substitute for the following suggestions without requiring much rework, as being able to pull a CSV or TSV [should work behind the scenes anyway](https://github.com/mastodon/mastodon/issues/116#issuecomment-1629675982) but is just not made accessible via UI or API. 
- #116 
- #10304 
- #11510 

OFC these requests demand either adding more functions to ActivityPub or require massive reworkings of the API.

The big advantage of this is that said blocklists could be automatically updated and also corrected without user interaction [i.e. once per day].

### Motivation

Personal motivations in regards to block-evasions by cyber-harrassers aside, I do maintain multiple blocklists in a [public git repo](https://github.com/greyhat-academy/lists.d) and also have multiple accounts that should be able to sync & use these.

Thus it seems reasonable to instead of [manually downloading and uploading a blocklist](https://github.com/greyhat-academy/lists.d/blob/main/activitypub.domains.block.list.tsv) to just provide a [raw feed URL to pull it from](https://raw.githubusercontent.com/greyhat-academy/lists.d/main/activitypub.domains.block.list.tsv) and sync with, including the ability to add multiple lists, set sync intervals and add manual overrides [both as user customization and for testing / debugging purposes]...

This works for [basically any blocking solution - regardless if application-side or network-side I know and use on a daily basis](https://github.com/greyhat-academy/lists.d/blob/main/blocklists.list.tsv) and I think this is quite reasonable to implement.

Espechally for those that [want to ban threads and those that federate with them entirely from their interactions](https://github.com/greyhat-academy/lists.d/blob/main/activitypub.threads.domains.block.list.tsv)... 

Also as [previously stated by a different person](https://github.com/mastodon/mastodon/issues/10304#issuecomment-1629803788) this would greatly reduce labour for moderating instances and also allow admins across instances to collaborate more effectively.

I'll gladly go into more details if need be but this should explain the premise, problem and suggested solution as well as the reason why I think this should be added / implemented this way.

**Comment by kkarhan** [comment]
Furthermore this could also be used as a means to block attackers by moderators/administrators, [restrict signups](https://github.com/greyhat-academy/lists.d/blob/main/blocklists.list.tsv#L27) to [combat floodings by spammers](https://github.com/greyhat-academy/lists.d/issues/46) as well as [banning bots that violate ``robots.txt``](https://github.com/greyhat-academy/lists.d/issues/48) so aggressively that people got essentially [DDoS'd into getting taken offline by their hosters as per excessive traffic](https://www.youtube.com/watch?v=Hi5sd3WEh0c)...

Furthermore, this allows for automatic updates and thus [correction of blocklists in case of mistakes](https://github.com/greyhat-academy/lists.d/issues/17), which is desireable for this exact use-case.

This may not be perfect, but I'm convinced it's a compromise that is workable for everyone that cares and could also be used across other ActivityPub implementations, thus helping not just Mastodon but the general ecosystem that Mastodon is part of...

**Comment by trwnh** [comment]
Duplicate of #116

**Comment by kkarhan** [comment]
I disagree! 

This is not a duplicate but rather an extension of existing functionality (blocklist import) to also include Feed-URLs instead of manually uploading one file after the other.

**Comment by kkarhan** [comment]
This is something a lot of applications and systems do - espechally in networking and web security...

You want to be able to just parse [blocklists](https://github.com/greyhat-academy/lists.d/blob/main/blocklists.list.tsv) to protect against [Spammers](https://www.spamhaus.org/drop/), [Attackers](https://mcfp.felk.cvut.cz/publicDatasets/CTU-AIPP-BlackList/) and [Crawlers](https://platform.openai.com/docs/gptbot) the same way you'd use an [AdBlocker](https://adaway.org/) and block [Advertising](https://pgl.yoyo.org/adservers/).

It's not that hard given that there is already a blocklist feature and it works, but manually updating it is tideous and doesn't scale...

@trwnh please reopen this issue...

**Comment by kkarhan** [comment]
Considering the current Spam Flood, Blocklist Feed Support with automatic removal is kinda necessary, as Mastodon does not have any good, built-in tools yet to handle removals automatically...

@ErikUden made a good [Blocklist re: Spammy instances](https://github.com/Mastodon-DE/blocklists/blob/main/spam/2024-02-15/2024-02-15-spam-domain_mutes-erik-uden.txt) and it should be kinda self-evidential to support blocklist feeds.

**Comment by kkarhan** [comment]
PS: This issue and any of my posts are being reaction-spammed by [a known harrasser who threatens any critic with baseless bs](https://github.com/greyhat-academy/lists.d/issues/52) and I'd recommend to block [said user](https://github.com/kromonos).

I've already informed GitHub Support Staff re: the past actions of said user, who's a right-extremist hatespeech troll [at best](https://github.com/greyhat-academy/lists.d/blob/232aed982e0c29ebfdb94179ebead84f079f96d3/activitypub.domains.block.list.tsv#L6).

**Comment by trwnh** [comment]
@kkarhan this issue asks for subscribable blocklists. #116 asks for subscribable blocklists. the magnitude of the issue does not change the fact that it is a duplicate.

**Comment by kkarhan** [comment]
@trwnh I disagree.

1.  #116 requests a custom, specific & new mechanism between Mastodon Servers and not something as simple as a Feed-URL where it pulls a TSV file from and updates from those.

2.  #116 aims towards something solely implemented for instance/server admins, not something that can be used client-side and/or by the users for their accounts...

3. Worse: Client-Side there is no way to properly *update* said lists even manually as of today: 
The only option in terms of list imports are "merge" and "replace", so it doesn't even allow for a way to automatically delist entries [unlike any other blocklist system I know of where it does that automatically with feed-URLs!] increasing labour needed exponentially because now one has to basically run a ```git``` server or similar version control system just to automate pulling and merging of multiple sources into one file per category [i.e. domain blocklist and user blocklist], making it basically more labour than justifyable to i.e. import @ErikUden 's [Spam Blocklist](https://github.com/Mastodon-DE/blocklists/blob/main/spam/2024-02-15/2024-02-15-spam-domain_mutes-erik-uden.txt) both as administrator and user because now one has to not only manually delist domains by looking at git diffs...

4. Even *if* this was a duplicate I feel it should've been prioritized way more given the excessive workload it puts on any instance that isn't a single person's microblog.

**Comment by MadokVaur** [comment]
I've long observed that specific individual's activity here and it seems to be limited entirely to finding ancient, unresolved, but still open issues and flagging any new reference to the same issue as "Duplicate -- closed" and thus re-burying the ancient, unresolved, open issue -- assuring that the issue will never be discussed in the present, and thus has no hope of ever being resolved

An interesting focus

Seems a little bit OCD, or deliberately obstructive

But that's only my opinion, of course...

**Comment by kkarhan** [comment]
@MadokVaur I tend to guess more that it's a *deliberate act* to prevent any productive solution to the issue at hand and basically dismissing the problem as such without being honest or just openly gaslight those opening the issue.

Had @trwnh [actually read the very beginning of it]( https://github.com/mastodon/mastodon/issues/28605#issue-2066712368 ) it would've been clear this ain't a duplicate!

Q: Is there a way to escalate this issue to someone who actually takes making Mastodon a better solution serious?
Cuz this [nonchalant attitude]( https://github.com/mastodon/mastodon/issues/28605#issuecomment-1878651595) is frustrating!

**Comment by kkarhan** [comment]
Here's a good example of how such a blocklist feed feature could look like: [pfBlockerNG]( https://docs.netgate.com/pfsense/en/latest/packages/pfblocker.html )

![Bildschirmfoto vom 2024-06-23 12-30-46](https://github.com/mastodon/mastodon/assets/30401796/1774f666-7de5-4587-801e-c3f8ca0f662a)

**Comment by MadokVaur** [comment]
> Q: Is there a way to escalate this issue to someone who actually takes making Mastodon a better solution serious? Cuz this [nonchalant attitude](https://github.com/mastodon/mastodon/issues/28605#issuecomment-1878651595) is frustrating!

Having observed this conduct by this individual repeatedly over an extended period of time, I can only surmise that the Mastodon management knows who he is, knows what he's doing, and allows it to continue with their tacit approval because it effectively re-buries unresolved issues they just don't want to address

I've seen nothing that leads me to think that he's working under explicit orders; it's only his particular fetish

Oh, they may get around to a particular issue at some time in the future, but only when they're good and ready

Meanwhile, on it goes...

**Comment by kkarhan** [comment]
This feature is espechally important because there's also [no way to report posts of accounts that blocked the reporting user](https://github.com/mastodon/mastodon/issues/23249)...

**Comment by Krutonium** [comment]
> Duplicate of [#116](https://github.com/mastodon/mastodon/issues/116)

I agree with @kkarhan - This isn't a duplicate. It's asking for a similar but fundamentally different thing.

**Comment by kkarhan** [comment]
Does someone know a maintainer that could reopen this issue?

Cuz it's obviously *not a duplicate*!

**Comment by kkarhan** [comment]
**_Friendly reminder that this issue should be reopened as it is clearly not a duplicate!_**

**Comment by kkarhan** [comment]
Can _ANYONE_ **confirm or deny** that Mastodon will implement this?
- Because it seems [on the roadmap](https://joinmastodon.org/roadmap). 

<img width="716" height="127" alt="Image" src="https://github.com/user-attachments/assets/4d36928a-97e5-407b-9f93-84bd823e5783" /> 

To me it thus seems _vital to reopen this issue_ as something that is **IN FACT, PLANNED**... 

After all, this can also alleviate issues like:
- https://github.com/mastodon/mastodon/security/advisories/GHSA-5h2f-wg8j-xqwp 

Just saying so [in public...](https://jorts.horse/@kkarhan/116462590581884312)


Cc:  @trwnh
