### ISSUE TITLE
Empty favourite notification received on mastodon.social (local->local)

### ISSUE THREAD

**Issue by saper** [mastodon/mastodon#2865]
The last toot from the thread:

https://mastodon.social/@applecandy/5138248

has been favourited by myself ([@saper@mastodon.social](http://mastodon.social/@saper)) few hours later.

It appeared as an empty notification on the toot author's side:

![Empty fav notification received](https://files.mastodon.social/media_attachments/files/000/408/806/original/58d303945f20b140.jpg "Problematic notification")

The client used above was [Amaroq](https://github.com/ReticentJohn/Amaroq) (by @ReticentJohn)

From the web it is more confusing:

![Mixed up fav notification](https://files.mastodon.social/media_attachments/files/000/408/888/original/c32d28c42190beea.jpg "Mixed up fav notificaiton")

I didn't favourite that one at all.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).
- [X] This bug happened on mastodon.social 1.3.3 (as of `Sun May  7 00:39:29 UTC 2017`) between two local users
- [X] Permission to show other users' screens and toots granted

**Comment by unarist** [comment]
When you favourited that toot, you saw it directly? or boosted one?

**Comment by unarist** [comment]
Oh, it happen on mastodon.social. Could you check what happens on the database, @Gargron?

**Comment by unarist** [comment]
This issue seems to be caused by race condition on `/api/v1/statuses/:id/favourite` and `/api/v1/statuses/:id/unfavourite`. Since unfavourite can be called between `Favourite` creation and `Notification` creation, then notification with missing activity remains.

For example, double clicking favorite button quickly may cause this issue I think.

**Comment by hidrarga** [comment]
I'm not sure if this is related, but I get this strange behaviour for one of my notifications : 

![image](https://user-images.githubusercontent.com/2971096/47722555-f32c5d00-dc52-11e8-9361-890443d99133.png)

As you can see, my toot was fav twice by the same person. I don't know if she really did fav twice my toot. I have access to the server of my instance, so I can try to get more info if you tell me where and what to look for.

I'm running on Mastodon v2.5.2
