### ISSUE TITLE
Following WordPress Server from mastodon appears to work, but follow disappears after logout/login

### ISSUE THREAD

**Issue by jjschwarz** [mastodon/mastodon#28685]
### Steps to reproduce the problem

1. Login to mastodon.lothlorien.net
2. Search for @n4jjs.com@n4jjs.com or @schwarzspanish.com@schwarzspanish.com
3. Log out of Mastodon
4. Log back in and check list of people followed.  Both are gone
...

### Expected behaviour

The follow should have completed

### Actual behaviour

I can see a "Cancel Follow" on both users like it is pending

### Detailed description

I was using an early version of the WordPress ActivityPub plugin on these sites.  It appears for some reason now that I have upgraded to a working version that both sites refuse to function from the server where I did the original test (mastodon.lothlorien.net).  I have checked and neither is block in the federation area, but both do show up as failing under the Federation area.  Users on other instances appear to not be affected, so this leads me to believe the issue is in Mastodon on this particular server.

### Mastodon instance

mastodon.lothlorien.net

### Mastodon version

v4.2.3

### Technical details

No sign of any obvious errors in the log.  I did file case https://github.com/Automattic/wordpress-activitypub/issues/591 just in case this was on the WordPress side.

**Comment by jjschwarz** [comment]
OK, I was finally able to get a debug that might give a clue:

Jan 10 12:52:19 mastodon.lothlorien.net bundle[851]: 2024-01-10T17:52:19.218Z pid=851 tid=5tmp3z WARN: {"context":"Job raised exception","job":{"retry":16,"queue":"push","dead":false,"args":["{\"@context\":\"https://www.w3.org/ns/activitystreams\",\"id\":\"https://mastodon.lothlorien.net/2c850a2d-0e9b-4a36-a9c8-c62e5b30741e\",\"type\":\"Follow\",\"actor\":\"https://mastodon.lothlorien.net/users/jason\",\"object\":\"https://n4jjs.com/@n4jjs.com\"}",109307799703588249,"https:/n4jjs.com/index.php/wp-json/activitypub/1.0/users/0/inbox",{"bypass_availability":true}],"class":"ActivityPub::DeliveryWorker","jid":"81b86fd39c215155dae09c9d","created_at":1704909139.1165545,"enqueued_at":1704909139.1166928}}

Jan 10 12:52:19 mastodon.lothlorien.net bundle[851]: 2024-01-10T17:52:19.218Z pid=851 tid=5tmp3z WARN: Mastodon::UnexpectedResponseError: https://n4jjs.com/index.php/wp-json/activitypub/1.0/users/0/inbox returned code 401

**Comment by renchap** [comment]
Pinging @pfefferle

**Comment by pfefferle** [comment]
I have some questions:

* What WordPress ActivityPub plugin version do you use?
* Do you see the follow request in your WordPress instance?
* Do you use mod_sec on your server?

**Comment by jjschwarz** [comment]
I am on v2.0.1 of the plugin and I am not seeing the follow request.  I am not using mod_sec on the server.  The odd part is I have multiple WordPress blogs on the server (different vhosts) and some work...but others do not.  It is actually happening for multiple hosts.  I believe it is the plugin because I am getting a 401 error on the inbox post.  See additional detains at https://github.com/Automattic/wordpress-activitypub/issues/591 .

**Comment by jjschwarz** [comment]
Retested today on v2.3.0 of the WordPress plugin against v4.2.8 of Mastodon and I am still seeing the same issue.  Any suggestions?

**Comment by jjschwarz** [comment]
> Let's discuss that in the ActivityPub plugin repo. This seems to be no Mastodon issue!

I opened cases in both because I was unable to tell which side was the issue.

**Comment by pfefferle** [comment]
No problem :)

Can you close this one?
