### ISSUE TITLE
Powershell: Unable to upload image. "Validation failed: File has contents that are not what they are reported to be"

### ISSUE THREAD

**Issue by Memor-X** [mastodon/mastodon#28690]
### Steps to reproduce the problem

1. Store file as Bytes with `[System.IO.File]::ReadAllBytes`
2. Store encoded string of file using `[System.Text.Encoding]::GetEncoding('ISO-8859-1').GetString`
3. Generate boundary value using `[System.Guid]::NewGuid().ToString();`
4. Store Linefeed character (using `"`r`n"`)
5. build API Body

```
$bodyLines = ( 
                            "--$boundary",
                            "Content-Disposition: form-data; name=`"file`"; filename=`"image$($image.Extension)`";",
                            "Content-Type: application/octet-stream$LF",
                            $fileEnc,
                            "--$boundary--$LF"
                        ) -join $LF
```

`$image` = file object obtained from `Get-ChildItem`. `$image.Extension` returns the file extension, ie. .jpg, .png
`$fileEnc` = encoded string from step 2
`$boundary` = boundary value from step 3
`$LF` = Linefeed character from step 4

6. Invoke API with 
```
Invoke-RestMethod -Uri "${mastodon_baseuri}/api/v2/media" -Method POST -ContentType "multipart/form-data; boundary=`"$boundary`"" -Body $bodyLines -Headers $header
```

`$header` is the barer token

### Expected behaviour

Successful API Request returning MediaAttachment to fetch ID from

### Actual behaviour

API Fails returning the error message " "error": "Validation failed: File has contents that are not what they are reported to be"

### Detailed description

I have created a powershell script that allows me to automate posting Tweets to other social media. currently only have Mastodon and Bluesky set up

Script for Mastodon has been working fine for months but today (22/01/2024 Australian East Coast) the image upload for Mastodon has been failing returning with the message 

> "error": "Validation failed: File has contents that are not what they are reported to be"

![image](https://github.com/mastodon/mastodon/assets/122759652/a3082c38-e9cb-4bf3-b700-f4a6a7f038de)

to confirm that it isn't the image i have attempted to repost the last successful use of the API so to using the same images that have worked that used .png and .jpg files where the images came from difference sources

- https://mastodon.social/@MemorX/111723603013850298 (uses 1 .png made from Snipping Tool)
- https://mastodon.social/@MemorX/111722835716874936 (uses 2 .jpg, both made from Prt Scrn + Paste into twitter and 1 .png downloaded from KnowYourMeme)

however these too failed to upload the image.

Bellow is the code used for uploading images. no changes have been made to this code since the 18th of October 2023

```
Write-Log "Uploading Image - $($image.FullName)"

            $fileBytes = [System.IO.File]::ReadAllBytes($image.FullName);
            $fileEnc = [System.Text.Encoding]::GetEncoding('ISO-8859-1').GetString($fileBytes);
            $boundary = [System.Guid]::NewGuid().ToString();
            $LF = "`r`n";

            $header = @{"Authorization" = "Bearer $mastodon_token"}
            $bodyLines = ( 
                            "--$boundary",
                            "Content-Disposition: form-data; name=`"file`"; filename=`"image$($image.Extension)`";",
                            "Content-Type: application/octet-stream$LF",
                            $fileEnc,
                            "--$boundary--$LF"
                        ) -join $LF
            $apiResult = Invoke-RestMethod -Uri "${mastodon_baseuri}/api/v2/media" -Method POST -ContentType "multipart/form-data; boundary=`"$boundary`"" -Body $bodyLines -Headers $header
            $imageParam += @($apiResult.id.ToString())
```

NOTE: `Write-Log` is just a function that allows me to quickly change logging such as text color or what i need pre/appended to the output. this can be replaced with `Write-Host`

the code is based off the the StackOverflow Answer here -> https://stackoverflow.com/a/50255917/1028804 as could not find any good example of using the Mastodon API to upload images

given how the code has suddenly stopped working after 3 months, i suspect there has been a recent change to Mastodon however am unsure if a bug has been introduced or if a recent change has exposed an existing issue with how i make the API Request

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.3+pr-28367-c675590

**Comment by ClearlyClaire** [comment]
Do you know when was the last successful upload?

**Comment by Memor-X** [comment]
> Do you know when was the last successful upload?

it would be this post https://mastodon.social/@MemorX/111723603013850298 posted my time (Australian Eastern Daylight Time) 9th of January at 1:21pm. the API request to /api/v1/statuses would have been made right after the image was uploaded which generally takes a second or two

**Comment by ClearlyClaire** [comment]
That is surprising, as there has been no code change on mastodon.social between this successful upload and now.

**Comment by Memor-X** [comment]
I believe I may have found the cause. while sorting out my downloads folder i found a Powershell installer and was reminded that i had updated Powershell to 7.4.0 on the 10th of January. given the date i uninstalled it and reinstalled 7.3.8 which i had an installer for and retesting the script is now working

![image](https://github.com/mastodon/mastodon/assets/122759652/bc9b6318-f528-429d-b1de-8ff6373bfe05)

i do not know what has changed between 7.3.8 and 7.4.0 of Powershell but as it appears to be Powershell and not Mastodon causing my problem i'll close this Bug
