### ISSUE TITLE
Constant errors on Firefox

### ISSUE THREAD

**Issue by Lulukaros** [mastodon/mastodon#28691]
### Steps to reproduce the problem

null

### Expected behaviour

null

### Actual behaviour

null

### Detailed description

not sure if it's a browser issue but it keeps giving error from time to time when wanting to view home or notification

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.3+pr-28367-c675590

### Browser name and version

Firefox 121.0.1

### Operating system

Windows 11

### Technical details

error code: NotFoundError: Node.removeChild: The node to be removed is not a child of this node
lc.onCommitFiberUnmount (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5136:122)
f (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5222:9)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5263:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5263:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5258:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5258:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5258:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
b (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5426:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
ek (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5242:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
b (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5426:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
ek (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5242:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
b (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5426:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
ek (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5242:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5263:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5258:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
b (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5426:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
ek (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5242:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
b (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5426:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5263:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5263:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5258:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5258:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
b (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5426:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
ek (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5242:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
ek (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5242:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5258:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
b (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5426:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
ek (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5242:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5263:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5258:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5258:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
b (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5426:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
ek (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5242:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
b (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5426:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
ek (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5242:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5258:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
ek (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5242:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5258:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5258:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5258:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5258:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5263:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5263:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5263:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5258:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
b (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5426:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
ek (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5242:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
ek (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5242:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5258:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5263:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5263:9)
ak (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5232:64)

**Comment by Gargron** [comment]
Are you using any browser extensions that might mess with the contents of the page?

**Comment by Lulukaros** [comment]
i use ublock origin, could it actually be what's causing my issue even though mastodon has no ads

**Comment by Lulukaros** [comment]
turned ublock off, and it still crashed after a while, so i don't think it's on my end

**Comment by ClearlyClaire** [comment]
This really looks like a browser extension messing with the DOM, but I'm not sure how to spot which one without resorting to trial and error.

**Comment by Lulukaros** [comment]
@ClearlyClaire can an extension be the cause even when it shouldn't interfere?, for example an extension that changes something on youtube, or things like that

**Comment by Lulukaros** [comment]
Omg i think i've figured it out, while i'm not sure 100% but i think the cause of the errors is an extension called *Bionic Reader*, could you please try the extension to make sure 100% it's the cause. here's the link https://addons.mozilla.org/en-US/firefox/addon/bionic-reader/

**Comment by ClearlyClaire** [comment]
Reading the description of that extension, it is very likely the culprit. They even point out:
> Some websites may not work properly with this extension. They may use text node as a placeholder for other element and will break the page if we modified it.

**Comment by Lulukaros** [comment]
i see, well i'm glad i finally got rid of those errors, thank you for your time <3
