### ISSUE TITLE
GitHub codespace doesn't launch because of post-create.sh failure (+ workaround included)

### ISSUE THREAD

**Issue by mnvr** [mastodon/mastodon#28752]
### Steps to reproduce the problem

When I use the [README instructions to create GitHub codespace](https://github.com/mastodon/mastodon#github-codespaces), the codespace doesn't successfully start and instead goes into recovery mode.

### Expected behaviour

Codespace should've launched

### Actual behaviour

post-create.sh fails, and the codespace goes into recovery mode

### Detailed description

Firstly, a big thank you to whoever worked on the ability to launch Mastodon in a GitHub codespace. For my use case (I was writing a [Mastodon Theme Generator](https://mnvr.github.io/mast/) for producing Custom CSS for the color theme, and the ability to preview the CSS changes in a codespace helped a lot!)

However, when I would create the codespace, it would instead go into recovery mode. This is because `.devcontainer/post-create.sh` fails.

The workaround that worked for my use case was to edit `.devcontainer/post-create.sh` (within the codespace itself) and comment out the following line at the end of the file:

```sh
RAILS_ENV=test ./bin/rails assets:precompile
```

After commenting this out and restarting the codespace, the codespace launches fine.

Another thing, not an issue, but something I had to look around a bit to find, was the default credentials (just mentioning this here in case this helps someone in the future who is trying to find these):

* Email `admin@<domain>`, where `<domain>` is where your codespace is running.
  So this'll be something like `admin@xxx-3000.app.github.dev`.
* Password `mastodonadmin`

**Comment by SchBenedikt** [comment]
I've also an issue doing this:

```
    at async CC (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:479:4775)
    at async NeA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:612:11107)
devcontainer process exited with exit code 1
Failed to create container.
Error: Command failed: /bin/sh -c .devcontainer/post-create.sh
Error code: 1302 (UnifiedContainersErrorFatalCreatingContainer)
Container creation failed.
```

**Comment by ykzts** [comment]
I think #28963 will fix this.

**Comment by mjankowski** [comment]
We did a bunch of work on devcontainers/codespaces a few months back, and in process this post-create script no longer exists.

Closing this on assumption we resolved this issue, but please reopen if you can replicate this (or similar) on current code.
