### ISSUE TITLE
Cannot downgrade role when at the same priority level

### ISSUE THREAD

**Issue by Krystool** [mastodon/mastodon#28761]
### Steps to reproduce the problem

1. Add several users to owner role
2. Try to downgrade a user to admin or mod role
3. Bugs out
...

### Expected behaviour

User should be downgraded

### Actual behaviour

User cannot be downgraded

### Mastodon instance

biscuit.town

### Mastodon version

v4.2.0

### Browser name and version

Opera GX latest

### Operating system

Windows 10 Latest

**Comment by ClearlyClaire** [comment]
This is intentional so that new admins/moderators cannot demote their peers and take over an instance. You can use `tootctl accounts modify` from the CLI if you want to demote a user.
