### ISSUE TITLE
Follow request 

### ISSUE THREAD

**Issue by Photoshop-Art** [mastodon/mastodon#28770]
### Steps to reproduce the problem

1. Nothing just receiving a follow request.
2. I have to accept

### Expected behaviour

Follower should be accepted automatically 

### Actual behaviour

I have to do it manually 

### Detailed description

Auto accepting a follow request is turned on in settings. I'm using web. So I dunno what's happening. 🤔

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-alpha.

### Browser name and version

FF, Chrome...

### Operating system

W11 2311

### Technical details

-

**Comment by Ember-ruby** [comment]
not a bug, people from instances that are limited/silenced by the server will be put in follow requests

**Comment by trwnh** [comment]
There should be a header to the following effect:

> Even though your account is not locked, the mastodon.social staff thought you might want to review follow requests from these accounts manually.
