### ISSUE TITLE
ostatus.org domain dropped and redirects to spam poker site

### ISSUE THREAD

**Issue by rwetzlmayr** [mastodon/mastodon#28773]
### Steps to reproduce the problem

1. Opening the link[2][rel] provided in [Mastodon's webfinger response](https://mastodon.social/.well-known/webfinger?resource=acct:mastodon.social@mastodon.social) now leads to a spammy poker site via a 301 reply

```
$ wget https://ostatus.org/
--2024-01-17 05:13:22--  https://ostatus.org/
Resolving ostatus.org (ostatus.org)... 188.114.97.3, 188.114.96.3, 2a06:98c1:3121::3, ...
Connecting to ostatus.org (ostatus.org)|188.114.97.3|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.shinshine.com/ [following]
--2024-01-17 05:13:23--  https://www.shinshine.com/
Resolving www.shinshine.com (www.shinshine.com)... 188.114.96.3, 188.114.97.3, 2a06:98c1:3120::9, ...
Connecting to www.shinshine.com (www.shinshine.com)|188.114.96.3|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.casanovabrospizza.com/ [following]
--2024-01-17 05:13:23--  https://www.casanovabrospizza.com/
Resolving www.casanovabrospizza.com (www.casanovabrospizza.com)... 104.21.89.133, 172.67.189.75, 2606:4700:3037::6815:5985, ...
Connecting to www.casanovabrospizza.com (www.casanovabrospizza.com)|104.21.89.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://hartdistrictteachers.org/ [following]
--2024-01-17 05:13:23--  https://hartdistrictteachers.org/
Resolving hartdistrictteachers.org (hartdistrictteachers.org)... 172.67.142.204, 104.21.54.222, 2606:4700:3030::6815:36de, ...
Connecting to hartdistrictteachers.org (hartdistrictteachers.org)|172.67.142.204|:443... connected.
HTTP request sent, awaiting response... 200 OK
```

2. ostatus.org is referenced in Mastodons `RemoteFollow.redirect_uri_template` function

### Expected behaviour

Links provided in a webfinger response should refer to legit sites

### Actual behaviour

A link provided in a webfinger response refers to a spammer site

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-alpha.0+pr-28693-b6706f7

**Comment by trwnh** [comment]
Link relations are not necessarily meant to be resolved. They're just identifiers.

**Comment by intentionally-left-nil** [comment]
@trwnh Having URI's point to malicious sites isn't okay. If it's literally just an identifier without meaning, you should replace the ref with something that can't be hijacked in the future. Something like https://example.com/some-uuid (since there's an RFC about that URL)

With mastodon being part of the fediverse (& the reference code being copied in multiple places) we really should fix this upstream
