### ISSUE TITLE
Filter Options Enhancement for home timeline

### ISSUE THREAD

**Issue by kensoh** [mastodon/mastodon#2879]
Does anyone wish that there are more filter options for home timeline? As Mastodon continues to grow, providing different filtering options for users would be a game-changer where power is really given to the users.

There seems to be regex (regular expression) filtering now but most users won't be able to use it effectively without some tool or resource. And it can quickly become very complex and unmanageable. 

Home timeline quickly fills up by who posts the most? Can have grey btw mute/unmute? Cross-posted in Mastodon - https://mastodon.social/@kensoh/5219986

---

Can't find duplicate of this. Somehow new issue template didn't show up, typing manually instead.

**Comment by wxcafe** [comment]
I thought I saw an issue about this previously but I can't find it right now. I'm leaving this open for now

**Comment by kensoh** [comment]
@wxcafe my [post in Mastodon](https://mastodon.social/@kensoh/5219986) only has 3 boosts and 3 favorites with ***0 comments***. If you are ok with the idea, can I just close the issue? Doesn't look like something people are interested to have.

**Comment by wxcafe** [comment]
nah, people are interested in this. I've seen people look for a way to filter toots already, plus it's a good anti-harassment feature.

**Comment by awooga** [comment]
is there any documentation of how to use regular expressions in the filter box - would be nice if default message was example of a filter - i am noob to mastodon and cannot fathom how to add even simple filter

**Comment by Gargron** [comment]
Simplest filter: keyword

Multiple keywords: keyword1|keyword2

**Comment by awooga** [comment]
Excellent example thanks - and that filters keyword out - Yes ?
Is there example of opposite how to filter in ? 

Would be nice to have count of toots in last minute for the filter - as this shows if its works or not very easily ;)

**Comment by awooga** [comment]
Also can we have "Filter Help" link , on the column filter dialog, to page on instructions and examples of filters for noobs, if mastodon breaches the million user mark - not everyone will be olde computer experts.. lolz

**Comment by fenarinarsa** [comment]
A good start would also be to see what webapps like tweetdeck do.
There is not even a checkbox to invert the regex filter :)

**Comment by trev-dev** [comment]
I'm not sure if there's already a way to do this or not, but it would be nice to have a way to filter out _specific users_ from my "home timeline" that I otherwise would rather see in a separate list. This way I would be able to move spammy users (that I still enjoy) to a place where I can check up on their toots without _muting_ them and going to their profile directly.

**Comment by Gaffen** [comment]
+1 for being able to filter users from the home timeline; I have news accounts that I follow that I'd much rather move to their own list so that they don't flush out all the content from the other user accounts I follow.

Happy to contribute to implementing this feature too if it's not too complicated!

**Comment by steelman** [comment]
Unlike on cecntralised SM on fedi you need to follow somebody (from their server's point of view) to get their posts delivered to your server. And when they get there it is a matter of filtering them into right bin.

**Comment by trwnh** [comment]
regex filters have long since been removed in favor of keyword filters. see #18955 for a ticket that tracks current issues with the new filter system
