### ISSUE TITLE
nodejs disappears from the container (main branch)

### ISSUE THREAD

**Issue by troit5ky** [mastodon/mastodon#28828]
### Steps to reproduce the problem

1. docker compose build
2.  docker compose up -d
3. [FATAL tini (7)] exec node failed: No such file or directory
...

### Expected behaviour

Start the streaming backend

### Actual behaviour

[FATAL tini (7)] exec node failed: No such file or directory

### Mastodon version

commit 93957da

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by renchap** [comment]
This is expected, the streaming server now lives it it's own container.

The `docker-compose.yml` file in `main` has not been updated yet to not break compat with 4.2 (as it currently hardcodes the 4.2 images) if people download it from Github, but will be before 4.3.

In the meantime, you can change the compose file to use `streaming/Dockerfile` for the streaming image.

**Comment by SergSel2006** [comment]
Could you please describe where I could find information on how to build it?
I tried to use streaming dockerfile but there were some errors:
```
=> ERROR [streaming streaming  6/10] COPY package.json yarn.lock .yarnrc.yml /opt/mastodon
 => ERROR [streaming streaming  7/10] COPY .yarn /opt/mastodon/.yarn
 => ERROR [streaming streaming  8/10] COPY ./streaming /opt/mastodon/streaming
------
 > [streaming streaming  6/10] COPY package.json yarn.lock .yarnrc.yml /opt/mastodon/:
------
------
 > [streaming streaming  7/10] COPY .yarn /opt/mastodon/.yarn:
------
------                                                                                           > [streaming streaming  8/10] COPY ./streaming /opt/mastodon/streaming:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref 2bd17192-a391-46eb-add5-ce6df65a8d26::oqjwonm8nt2i5z3sr02p2armh: "/streaming": not found

**Comment by troit5ky** [comment]
> Could you please describe where I could find information on how to build it? I tried to use streaming dockerfile but there were some errors:
> 
> ```
> => ERROR [streaming streaming  6/10] COPY package.json yarn.lock .yarnrc.yml /opt/mastodon
>  => ERROR [streaming streaming  7/10] COPY .yarn /opt/mastodon/.yarn
>  => ERROR [streaming streaming  8/10] COPY ./streaming /opt/mastodon/streaming
> ------
>  > [streaming streaming  6/10] COPY package.json yarn.lock .yarnrc.yml /opt/mastodon/:
> ------
> ------
>  > [streaming streaming  7/10] COPY .yarn /opt/mastodon/.yarn:
> ------
> ------                                                                                           > [streaming streaming  8/10] COPY ./streaming /opt/mastodon/streaming:
> ------
> failed to solve: failed to compute cache key: failed to calculate checksum of ref 2bd17192-a391-46eb-add5-ce6df65a8d26::oqjwonm8nt2i5z3sr02p2armh: "/streaming": not found
> ```

me to, i'm using prebuild image.

**Comment by nomad-geek** [comment]
Alright. This took me a minute to figure out so here's the solution for anyone else that stumbles into this.
In your docker-compose.yml streaming service, you'll want to adjust this:
`build: .`
to
`build:
      dockerfile: ./streaming/Dockerfile
      context: .`

**Comment by PhieF** [comment]
I also had to rename the image for streaming when rebuilding it

I've put a random name "    image: ghcr.io/mastodon/streaming:v4.2.7" in my case otherwise there would be a confusion between streaming and web

**Comment by xarinatan** [comment]
it started working again for me when I recently tried again on the 4.2 branch, I'm not sure what changed, perhaps the local git repo docker builds the image from wasn't on the correct branch yet, but I'm not sure.

**Comment by renchap** [comment]
Closed by 31554
