### ISSUE TITLE
LinkCrawlWorker fails with Errno::ENAMETOOLONG

### ISSUE THREAD

**Issue by smiba** [mastodon/mastodon#28821]
### Steps to reproduce the problem

1. Let LinkCrawlWorker in Sidekiq process a link that is affected, the following post seems to trigger this issue: https://very.tastytea.de/notes/9o0dw2kljs

### Expected behaviour

LinkCrawler should've given the temporary file a correct name

### Actual behaviour

LinkCrawler ended up with the filename containing all headers, making it too long. The operation fails and ends up in the dead queue

### Mastodon instance

woof.tech

### Mastodon version

v4.1.11-3-woof

### Technical details

- Ruby 3.0.4p208
- Node.js v16.20.2

Using some backported changes from main onto v4.1.11 (Like #28788), but this issue seems to happen on mainline mastodon as well

Logs:

```
Jan 19 15:15:47 woof-tech-mastodon-prod bundle[4091868]: 2024-01-19T15:15:47.065Z pid=4091868 tid=1yb5g class=LinkCrawlWorker jid=9febc4943b665a5240d5540a INFO: start
Jan 19 15:15:47 woof-tech-mastodon-prod bundle[4091868]: 2024-01-19T15:15:47.345Z pid=4091868 tid=1yb5g class=LinkCrawlWorker jid=9febc4943b665a5240d5540a INFO: Adding dead LinkCrawlWorker job 9febc4943b665a5240d5540a
Jan 19 15:15:47 woof-tech-mastodon-prod bundle[4091868]: 2024-01-19T15:15:47.347Z pid=4091868 tid=1yb5g class=LinkCrawlWorker jid=9febc4943b665a5240d5540a elapsed=0.281 INFO: fail
Jan 19 15:15:47 woof-tech-mastodon-prod bundle[4091868]: 2024-01-19T15:15:47.347Z pid=4091868 tid=1yb5g WARN: {"context":"Job raised exception","job":{"retry":0,"queue":"pull","class":"LinkCrawlWorker","args":[111688311417973189],"jid":"9febc4943b665a5240d5540a","created_at":1704228394.274077,"enqueued_at":1705677347.065164,"error_message":"File name too long @ rb_sysopen - /tmp/d603ba193612fc3ba84766851f3938c920240119-4091868-wwu875.png22response-content-typeimage2FpngExpires1704866743SignatureTOuki<part of sig>qDdV2LRe0kMjCZLAVHMmzdGSeMjRjSlPMnd1S-dRLeCjI62qA__Key-Pair-IdAP<part of key pair>5A","error_class":"Errno::ENAMETOOLONG","failed_at":1704228412.275545,"retry_count":-1,"retried_at":1705677240.856181}}
Jan 19 15:15:47 woof-tech-mastodon-prod bundle[4091868]: 2024-01-19T15:15:47.347Z pid=4091868 tid=1yb5g WARN: Errno::ENAMETOOLONG: File name too long @ rb_sysopen - /tmp/d603ba193612fc3ba84766851f3938c920240119-4091868-4gdtvo.png22response-content-typeimage2FpngExpires1704866743SignatureTOuki<part of sig>qDdV2LRe0kMjCZLAVHMmzdGSeMjRjSlPMnd1S-dRLeCjI62qA__Key-Pair-IdAP<part of key pair>5A
Jan 19 15:15:47 woof-tech-mastodon-prod bundle[4091868]: 2024-01-19T15:15:47.347Z pid=4091868 tid=1yb5g WARN: /home/mastodon/.rbenv/versions/3.0.6/lib/ruby/3.0.0/tempfile.rb:141:in `initialize'
Jan 19 15:15:47 woof-tech-mastodon-prod bundle[4091868]: /home/mastodon/.rbenv/versions/3.0.6/lib/ruby/3.0.0/tempfile.rb:141:in `open'
Jan 19 15:15:47 woof-tech-mastodon-prod bundle[4091868]: /home/mastodon/.rbenv/versions/3.0.6/lib/ruby/3.0.0/tempfile.rb:141:in `block in initialize'
```

Sidekiq: 
```
Errno::ENAMETOOLONG: File name too long @ rb_sysopen - /tmp/d603ba193612fc3ba84766851f3938c920240119-4091868-4gdtvo.png22response-content-typeimage2FpngExpires1704866743SignatureTOukiuVPhRnvSiQFunalnM3[...]
```

**Comment by ClearlyClaire** [comment]
This is because the `content-disposition` header returned by the particular server hosting the preview card's images return a very long file name composed of the request's headers, and our code uses the server-provided filename as part of the temporary filename.

I am not sure to which extent the server-provided filename is useful for our purposes, if it's useful at all. My guess is that at most the file extension is useful for sanity checks and guessing the expected file type.

**Comment by smiba** [comment]
Good catch!

If we wish to keep using the server-provided filename, would it maybe make more sense to truncate long filenames so they still get tried? Would probably be the easiest workaround as well.

Not sure how Misskey processes it, the preview does seem to work on there.

**Comment by ShadowJonathan** [comment]
possibly best to hash the names, maybe
