### ISSUE TITLE
Images hosting in S3 are blocked by Content Security Policy (connect-src)

### ISSUE THREAD

**Issue by henryclw** [mastodon/mastodon#28842]
### Steps to reproduce the problem

1. Host everything including the s3 storage on my server.
2. Post an image
3. Load the homepage
4. The image could not be loaded.

---

My .env.production is something like:
```env
S3_ENABLED=true
S3_BUCKET=mastodata
AWS_ACCESS_KEY_ID=xxx
AWS_SECRET_ACCESS_KEY=yyy
S3_PROTOCOL=https
S3_HOSTNAME=s3.example.com
S3_ENDPOINT=https://s3.example.com/
S3_FORCE_SINGLE_REQUEST=true
# S3_ALIAS_HOST=s3.example.com/mastodata
```
I tried using `S3_ALIAS_HOST` and not using `S3_ALIAS_HOST`, both of them don't work.

The webpage tried to fetch the correct address of the image, but due to Content Security Policy, it was blocked.

![image](https://github.com/mastodon/mastodon/assets/97804910/ee8757e6-17d3-4d8e-a70b-d70092ce351f)
![image](https://github.com/mastodon/mastodon/assets/97804910/df717ca6-ebad-436a-a05f-7daa0da08c60)

```
Refused to connect to 'https://s3.example.com/mastodata/cache/accounts/avatars/111/796/170/184/288/825/original/98d6e6a9c04e870d.png' 
because it violates the following Content Security Policy directive: "connect-src 'self' data: blob: https://mastodon.example.com https://mastodon.example.com wss://mastodon.example.com".
```

A further detail of a Content-Security-Policy example from a response shows that:
```
base-uri 'none'; default-src 'none'; frame-ancestors 'none'; font-src 'self' https://mastodon.example.com; img-src 'self' https: data: blob: https://mastodon.example.com; style-src 'self' https://mastodon.example.com 'nonce-QEJ8yxCuFUsX/YBXY9+t8w=='; media-src 'self' https: data: https://mastodon.example.com; frame-src 'self' https:; manifest-src 'self' https://mastodon.example.com; form-action 'self'; child-src 'self' blob: https://mastodon.example.com; worker-src 'self' blob: https://mastodon.example.com; connect-src 'self' data: blob: https://mastodon.example.com https://mastodon.example.com wss://mastodon.example.com; script-src 'self' https://mastodon.example.com 'wasm-unsafe-eval'
```

![image](https://github.com/mastodon/mastodon/assets/97804910/2d6ee2d7-8421-48e0-8ef8-eb25125a40cd)

I'm not sure if simply adding my s3 host (s3.example.com) in connect-src could help or not.

And I'm also confused with these code:
My s3 hostname should go in `s3_hostname_host`
https://github.com/mastodon/mastodon/blob/main/app/lib/content_security_policy.rb#L56
Then it should go in `cdn_host_value`
https://github.com/mastodon/mastodon/blob/main/app/lib/content_security_policy.rb#L22
Then it should be a part of `media_hosts`
https://github.com/mastodon/mastodon/blob/main/app/lib/content_security_policy.rb#L12
Then it should be a part of `connect_src`
https://github.com/mastodon/mastodon/blob/main/config/initializers/content_security_policy.rb#L60

### Expected behaviour

The image could be loaded

### Actual behaviour

The image is blocked by Content Security Policy

### Mastodon instance

mastodon.novadata.app

### Mastodon version

v4.2.3

### Browser name and version

Chrome 120.0.6099.218

### Operating system

Windows 10, 10.0.19045.3803

**Comment by ClearlyClaire** [comment]
Have you recently added the S3 config after having used the server without it? I believe the issue is `https://mastodon.novadata.app/sw.js` being cached with old `Content-Security-Policy` headers.

When querying your server, I get the proper Content-Security-Policy headers, including the S3 server.

**Comment by henryclw** [comment]
@ClearlyClaire Thank you for your kind reply.

> Have you recently added the S3 config after having used the server without it? I believe the issue is `https://mastodon.novadata.app/sw.js` being cached with old `Content-Security-Policy` headers.

Nope, I believe I've used `docker compose down -v` to remove everything from the old config, clear the nginx cache using `rm -r /var/cache/nginx/*`, then start the whole mastodon service with the new config (with S3) from the beginning.

> When querying your server, I get the proper Content-Security-Policy headers, including the S3 server.

Wow, this is totally new to me. I tried to repeat the process, turns out. Logged-in user could not get the correct `https://mastodon.novadata.app/sw.js` , but unlogged-in user using incognito chrome tab could get the correct one.

I've tried clearing the cache of nginx this morning once again, but things still don't work out. If this script is not be cached with nginx, is the mastodon container having its own cache? Would you mind telling me how to manually refresh/regenerate `https://mastodon.novadata.app/sw.js` within the container? Is there a rake command that could do such a job?

**Comment by henryclw** [comment]
Let me sum this up a little bit:

Working situation (even after clearing nginx cache):
1. logged-in user, ctrl + F5 hard reload
2. unlogged-in user, normal browsing

Bugged situation:
1. logged-in user, normal browsing
2. logged-in user, F5 reload

**Comment by ClearlyClaire** [comment]
Yeah, that can be stored in the browser's cache as well for a while.

**Comment by henryclw** [comment]
It worked after clearing browser cookies. Previously I only cleared browser cache, not cookies yet.
Thank you for your kind help. Have a great day @ClearlyClaire 🚀

**Comment by Qvisl9** [comment]
所以最终怎么处理，我也遇到了这个问题，只能用ctrl+f5强制，才能加载。

**Comment by ClearlyClaire** [comment]
The responses for the service worker are cached for a bit, including the Content-Security-Policy. It should fix itself after a while.

**Comment by tokpig** [comment]
我也遇到了这个问题，我更换了s3的域名后，sw.js 的 content-security-policy 依旧是以前的s3域名，无法清理。

I also encountered this issue. After changing the S3 domain name, the content-security-policy of sw.js still has the old S3 domain name and cannot be cleared.

**Comment by ClearlyClaire** [comment]
Yes, this file is cached for a bit.
