### ISSUE TITLE
Adding "/" as a shortcut for directly going to the search bar

### ISSUE THREAD

**Issue by tusharxoxoxo** [mastodon/mastodon#28841]
### Pitch

Currently, on Mastodon, by pressing "s" we can go to the search bar and search. But I feel that it's not common to have "s" as a search, I am suggesting that both "s" and "/" will perform the same action going directly to the search bar 

s | / → for going to search bar

### Motivation

To me "/" feels the de facto standard of directly going to the search and I think public have also developed this as a very common muscle memory for doing so, almost everyone use "/" for search on YouTube, Gmail, or any other google service, we can perform the same on Twitter, it works on all search engines like google, DuckDuckGo, brave, bing. 

I am suggesting that having both buttons "s" and "/" as a shortcut for directly going to the search bar

**Comment by tusharxoxoxo** [comment]
I want to add this feature, waiting for the confirmation from the community whether this a good idea or bad

**Comment by renchap** [comment]
This has been recently implemented.
