### ISSUE TITLE
Hashtagged Post Not Showing Up in /@user/tagged url (and hence not RSS feed)

### ISSUE THREAD

**Issue by cogdog** [mastodon/mastodon#28855]
### Steps to reproduce the problem

1. I post daily responses to a creative challenge using the hashtag #dailycreate
2. I am using the link from my featured hashtags to monitor and follow via RSS, via https://social.fossdle.org/@cogdog/tagged/dailycreate (and https://social.fossdle.org/@cogdog/tagged/dailycreate.rss

...

### Expected behaviour

I should see all posts I have tagged #dailycreate at https://social.fossdle.org/@cogdog/tagged/dailycreate

### Actual behaviour

I only see some, today I published this post using #dailycreare https://social.fossdle.org/@cogdog/111800409671476558 but it does not appear in  https://social.fossdle.org/@cogdog/tagged/dailycreate

### Detailed description

I can see my post in the general of all tags using #dailycreate https://social.fossdle.org/tags/dailycreate

This seems inconsistent, I would expect to be able to follow my own content using a specific tag but it is not

### Mastodon instance

social.fossdle.org

### Mastodon version

v4.2.0

### Browser name and version

Chrome Version 119.0.6045.159

### Operating system

macOS 12.6.6

**Comment by mjankowski** [comment]
Still an issue in 4.3?

I'm having trouble replicating this (amongst normal statuses that I'd expect to show up). Could this have been caching issue or something?

**Comment by cogdog** [comment]
Thanks for checking. This was so long ago, I have moved instances ;-) I cannot replicate and would agree it was a caching issue.

I appreciate this!
