### ISSUE TITLE
When flash message alert appear then link footer is visible only partially

### ISSUE THREAD

**Issue by olekstomek** [mastodon/mastodon#28867]
### Steps to reproduce the problem

1. Go to https://infosec.exchange/home (it is important that you should use account which was moved from infosec.exchange instance)
2. You see alert message 
> "This account is marked as moved to [@olekstomek@pol.social](https://pol.social/@olekstomek), and may thus not accept new follows."
3. Part on left down corner is visible only partially:
![image](https://github.com/mastodon/mastodon/assets/26818304/0bf55712-35ef-4793-aae7-3122767ccc7b)

### Expected behaviour

All text in footer should be visible

### Actual behaviour

Part on left down corner is visible only partially

### Mastodon instance

infosec.exchange

### Mastodon version

v4.3.0-alpha.0+glitch

### Browser name and version

Microsoft Edge Version 120.0.2210.144 (Official build) (64-bit)

### Operating system

OS Name	Microsoft Windows 10 Enterprise

### Technical details

When alert `#mastodon > div > div > div.flash-message.alert` (`flash-message alert`) is visible
![image](https://github.com/mastodon/mastodon/assets/26818304/39e909e6-cf15-4930-bd23-e392fbb84629)
then footer `#mastodon > div > div > div.columns-area__panels > div.columns-area__panels__pane.columns-area__panels__pane--compositional > div > div > div.link-footer` (`link-footer`) is visible partially:
![image](https://github.com/mastodon/mastodon/assets/26818304/0bf55712-35ef-4793-aae7-3122767ccc7b)

**Comment by olekstomek** [comment]
I know that I create this issue on version v4.3.0-alpha.0+glitch, so it is [this fork](https://github.com/glitch-soc/mastodon). But before closing this issue I added manually code in browser to simulate what happen when fllash message alert will appear. And the problem is the same. 
Go to https://pol.social/home (now it it v4.2.0) and add:
 
```
<div class="flash-message alert">
<span>This account is marked as moved to <a target="_blank" href="https://pol.social/@olekstomek" class="permalink">@olekstomek@pol.social</a>, and may thus not accept new follows.</span>
    
</div>
```
in `#mastodon > div > div`
![image](https://github.com/mastodon/mastodon/assets/26818304/565d1834-9723-4524-b3fa-01dc690c02c0)

The result in footer `#mastodon > div > div > div.columns-area__panels > div.columns-area__panels__pane.columns-area__panels__pane--compositional > div > div > div.link-footer` 
is visible like:
![image](https://github.com/mastodon/mastodon/assets/26818304/2bd9d29a-6bae-4566-b716-ee5146460e42)
but should be visible full footer like:
![image](https://github.com/mastodon/mastodon/assets/26818304/018d81d8-500c-4760-af46-5649825a0ca5)

**Comment by Gargron** [comment]
We don’t render flash messages in that layout.
