### ISSUE TITLE
SSO and registration status of an instance

### ISSUE THREAD

**Issue by manuviens** [mastodon/mastodon#28918]
### Pitch

One negative side of using SSO exclusively (i.e. disabling registrations directly in the applications) with Mastodon (and PeerTube as well) is that they report (nodeinfo) that registrations are disabled on the instances, whereas this is not true - you simply have to go through SSO!

### Motivation

It would be handy to have environment variables to specify a custom URL for registration in this use case.

**Comment by renchap** [comment]
https://github.com/mastodon/mastodon/pull/25014 added `SSO_ACCOUNT_SIGN_UP`, did you try this?

**Comment by manuviens** [comment]
How it works?
I tried `SSO_ACCOUNT_SIGN_UP=https://www.fedi.quebec/inscription/` in my .env.production, but it doesn't seem to have any effect.

Here is my .env.production variables related to the external authentication :
```
OIDC_ENABLED=true
OIDC_DISPLAY_NAME=mon compte fediquebec
OIDC_DISCOVERY=true
OIDC_ISSUER=https://auth.fedi.quebec/application/o/pouet/
OIDC_AUTH_ENDPOINT=https://auth.fedi.quebec/application/o/authorize/
OIDC_TOKEN_ENDPOINT=https://auth.fedi.quebec/application/o/token/
OIDC_USER_INFO_ENDPOINT=https://auth.fedi.quebec/application/o/userinfo/
OIDC_JWKS_URI=https://auth.fedi.quebec/application/o/pouet/jwks/
OIDC_END_SESSION_ENDPOINT=https://auth.fedi.quebec/application/o/pouet/end-session/
OIDC_SCOPE=openid,profile,email
OIDC_UID_FIELD=sub
OIDC_CLIENT_ID=myid
OIDC_CLIENT_SECRET=mykey
OIDC_REDIRECT_URI=https://pouet.fedi.quebec/auth/auth/openid_connect/callback
OIDC_SECURITY_ASSUME_EMAIL_IS_VERIFIED=true
OMNIAUTH_ONLY=true
SSO_ACCOUNT_SIGN_UP=https://www.fedi.quebec/inscription/
```

**Comment by manuviens** [comment]
Ok, I finished my coffee.

I removed the message and set `Anyone can sign up` at https://pouet.fedi.quebec/admin/settings/registrations...

Merci @renchap !
