### ISSUE TITLE
Clicking on the emoji icon when the picker is open does not close it

### ISSUE THREAD

**Issue by renchap** [mastodon/mastodon#28927]
Tiny bug report: clicking on the emoji icon when the emoji picker is opened should close the picker (in the same way clicking again the poll or cw icon closes the poll or cw fields). Right now, clicking the emoji icon again seems to reopen the emoji picker which is already opened.

_Originally posted by @nclm in https://github.com/mastodon/mastodon/issues/28119#issuecomment-1911588913_

**Comment by jh97uk** [comment]
Oh no! I messed up the merge, the first commit needs removing. I'll fix tomorrow and properly submit a merge request. I'm too tired to be doing git stuff, clearly! 😆

**Comment by renchap** [comment]
Fixed in #29012
