### ISSUE TITLE
Mastodon is hoarding other server's data

### ISSUE THREAD

**Issue by samip5** [mastodon/mastodon#28930]
### Steps to reproduce the problem

1. Run an instance for a while
2. See that your storage usage starting to grow dramatically by time
3. Reach out of storage due to it
4. Have no way to limit it

### Expected behaviour

I should be able to limit it, and/or clear it

### Actual behaviour

It grows till disk is full

### Detailed description

I really think this is a bug, as it shouldn't be hoarding data like this without any ability to control it.

Most of the space is used by public/system/cache which currently is at 62G and resulting in alerts of the filesystem being almost full and we have no way to actually limit its size.

### Mastodon instance

sauna.social

### Mastodon version

v4.2.0

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: v3.2.2
- Node.js version: v16.20.2

**Comment by Joshix-1** [comment]
There are content retention settings.
![image](https://github.com/mastodon/mastodon/assets/57299889/6fbaffb1-8ba8-4d21-b192-f77dc5d5316b)

**Comment by nemobis** [comment]
This can probably continue at https://github.com/mastodon/mastodon/discussions/19260

Meanwhile, on your own instance you can set up appropriate cleanup scripts, like: https://ricard.dev/improving-mastodons-disk-usage/

**Comment by samip5** [comment]
> Meanwhile, on your own instance you can set up appropriate cleanup scripts, like: https://ricard.dev/improving-mastodons-disk-usage/

The problem is that media at least doesn't really account for most of the data.

**Comment by smiba** [comment]
> > Meanwhile, on your own instance you can set up appropriate cleanup scripts, like: https://ricard.dev/improving-mastodons-disk-usage/
> 
> The problem is that media at least doesn't really account for most of the data in my case.

Within mastodon, what is your space usage showing as? (On the admin dashboard)
![Dashboard_-_Woof_tech__Mastodon_](https://github.com/mastodon/mastodon/assets/3308142/c93afffb-4680-40d0-ad9a-e931d430c82d)
(This thing)

Could you let us know what folders are taking up the most space on your drive? Is it content storage? Redis? PostgreSQL? (ElasticSearch if you have it enabled?)

**Comment by samip5** [comment]
>Within mastodon, what is your space usage showing as? (On the admin dashboard)

![Screenshot 2024-01-29 at 0 12 30](https://github.com/mastodon/mastodon/assets/1703002/d9edc1d6-a1b1-43af-87ed-66ce17ca9288)


> Could you let us know what folders are taking up the most space on your drive?

public/system/cache as stated in the start of the issue.

**Comment by smiba** [comment]
What's your media cache retention period configured as? Keep in mind Mastodon keeps a copy of every post it is aware of, but you can reduce the space it ends up taking up by having it purge older content from the cache.

**Comment by samip5** [comment]
> What's your media cache retention period configured as? Keep in mind Mastodon keeps a copy of every post it is aware of, but you can reduce the space it ends up taking up by having it purge older content from the cache.

Default, which now after looking at it seems  to default to hoarding it indefinitely?

**Comment by smiba** [comment]
Yes, by default it never removes cache content. You might want to experiment with setting it to 31 days ("Media cache retention period"), or even less if you need more space. 

If you set it too low your instance might have to redownload a lot of content on demand which is taxing

**Comment by smiba** [comment]
> > What's your media cache retention period configured as? Keep in mind Mastodon keeps a copy of every post it is aware of, but you can reduce the space it ends up taking up by having it purge older content from the cache.
> 
> What exactly does "every post it is aware of", actually mean in a more broad sense? Does it just collect anything and everything, or is it for those that specifically subscribe to/follow or be followed things that makes this happen?

![axbom-visibility-of-a-toot-3](https://github.com/mastodon/mastodon/assets/3308142/34c32931-3898-437e-a2e9-fcc5c6e27a63)

It does collect "anything and everything", but only if it gets fed the data in the first place. This diagram kinda explains it a little more. Any post that hits your instance will get saved for future use

**Comment by vmstan** [comment]
As pointed out you need to set a media content retention period and can do so in the admin interface.

You can also a process to clean up media files from the CLI https://docs.joinmastodon.org/admin/tootctl/#media-remove

I would caution not to set the post retention period in the web interface and instead use https://docs.joinmastodon.org/admin/tootctl/

Using the post retention in the web interface will remove **any** remote content beyond that date while the CLI tool will only remove unnecessary content that has never been interacted with.

**Comment by mjankowski** [comment]
Closing on the assumption that the issue here is addressed by some combination of running cleanup scripts and/or setting the retention settings. If you feel that doesn't actually address whatever is being stored/accumulated, can you re-open and add more detail about what's being stored beyond expectations?

**Comment by samip5** [comment]
Firstly, only org members can re-open and 2nd: It does cache remote media while none of the commands/retention settings seem to do much of anything.

So no, it was NOT addressed.

**Comment by smiba** [comment]
@samip5 Did you try to set the media cache retention period? This should remove older cache content taking up space

**Comment by samip5** [comment]
> @samip5 Did you try to set the media cache retention period? This should remove older cache content taking up space

I did yes.

**Comment by smiba** [comment]
Did it get rid of cache media older than the configured expiry period? What did you configure it as?

**Comment by mjankowski** [comment]
> It does cache remote media while none of the commands/retention settings seem to do much of anything.

Can you give a before/after from running the tootctl script of the admin panel showing storage usage, and also the output of `du -sh public/system/cache/*` ?

**Comment by samip5** [comment]
> > It does cache remote media while none of the commands/retention settings seem to do much of anything.
> 
> Can you give a before/after from running the tootctl script of the admin panel showing storage usage, and also the output of `du -sh public/system/cache/*` ?

Before:
![Screenshot 2024-03-04 at 21 44 39](https://github.com/mastodon/mastodon/assets/1703002/e523596f-e821-45c7-b1a4-78a18b861ce8)
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       102G  100G  3.0G  98% /
$ du -sh public/system/cache/*
11G	public/system/cache/accounts
2.1G	public/system/cache/custom_emojis
63G	public/system/cache/media_attachments
8.7G	public/system/cache/preview_cards
```

After:

![Screenshot 2024-03-04 at 21 51 41](https://github.com/mastodon/mastodon/assets/1703002/b7dae896-bbdc-4a18-8446-2fbeb679a7aa)
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       102G   61G   42G  60% /
$ du -sh public/system/cache/*
11G	public/system/cache/accounts
2.1G	public/system/cache/custom_emojis
24G	public/system/cache/media_attachments
8.7G	public/system/cache/preview_cards
```

So it seems only my cron job is not doing it's thing then... which is

```
SHELL=/bin/bash
PATH=/home/mastodon/.rbenv/shims:/home/mastodon/.rbenv/bin:/usr/local/bin:/usr/bin:/bin

###
### Mastodon cronjobs for media cache purging
###
### Clean up media every day at midnight as weekly is not enough
@daily /home/mastodon/live && RAILS_ENV=production bin/tootctl media remove

**Comment by mjankowski** [comment]
Well, that's good to confirm the task works. The cron suggestion from guides is:

```
@weekly RAILS_ENV=production /home/mastodon/live/bin/tootctl media remove
```

In your version, is there a missing `cd` in front of the first command? Or, what error output if any do you see in cron logs?

**Comment by samip5** [comment]
> Well, that's good to confirm the task works. The cron suggestion from guides is:
> 
> ```
> @weekly RAILS_ENV=production /home/mastodon/live/bin/tootctl media remove
> ```
> 
> In your version, is there a missing `cd` in front of the first command? Or, what error output if any do you see in cron logs?

It seems I do indeed are missing a cd.
The cron logs are just this:
```
Mar 04 00:00:01 mastodon CRON[3357172]: (mastodon) CMD (/home/mastodon/live && RAILS_ENV=production bin/tootctl media remove)
```

**Comment by mjankowski** [comment]
Sounds good -- hopefully updating the cron entry solves the issue.

Closing this on assumption that the task is actually working fine and it was a config issue, but please leave comment if that's not true.
