### ISSUE TITLE
Generating archive doesn't work

### ISSUE THREAD

**Issue by ruudschilders** [mastodon/mastodon#28934]
### Steps to reproduce the problem

1. I go to https://journa.host/settings/export
2. I click 'Request your archive'
3. It will say 'Compiling your archive' for a long time, also after refreshing.
4. After refreshing (after about 30 minutes?) this message will be gone, and the button 'Request your archive' shows again.
5. In the background, I see a log entry about paperclip saving a zip file to a backup folder.

Is there anything I should look for in the error log to understand what's happening? I've seen https://github.com/mastodon/mastodon/issues/24380 and even though I don't think that's the issue here, I've implemented the workaround by defining the `proxy_redirect` but that didn't help
...

### Expected behaviour

A link should appear to download the archive

### Actual behaviour

No link appears

### Detailed description

This issue occurs on at least 2 instances, which run in Docker and are behind Cloudflare. They use S3 storage.
It happened on 4.2.3 and also after upgrading to 4.2.4

### Mastodon instance

journa.host

### Mastodon version

v4.2.4

### Technical details

We use the latest docker images

**Comment by jeremiak** [comment]
@ruudschilders Not sure if it's something you did or if it was the Mastodon update that got rolled out today but FWIW I can now download my archive on journa.host. If it was you, thanks!

**Comment by ruudschilders** [comment]
I applied the workaround mentioned here: https://github.com/mastodon/mastodon/issues/26551#issuecomment-1686231515

**Comment by jeremiak** [comment]
Oh awesome, thank you!

**Comment by mjankowski** [comment]
I'm going to close this on the assumption that "generating the archive" (narrowly defined) is actually working, and the real issue is the S3 configuration from linked issue, which is captured elsewhere. Please reopen if I've misunderstood!

**Comment by jeremiak** [comment]
It's at least working now on the instance I'm a part of. Thanks!!
