### ISSUE TITLE
Implement multipin (up to 3 posts could be pinned)

### ISSUE THREAD

**Issue by Twilightssuperb** [mastodon/mastodon#28960]
### Pitch

If I create a thread and pin it first post, sometimes I need to add something important, but I don't want to break the line or theme that I'm describing there.

When I pin some discrete post in addition to first pinned item, it's better solution.

Or, as compromise, make some special public favorite posts collection at user profile page (**near** the "Posts"/"Posts with replies"/"Media"), like Twitter Premium user can have now

### Motivation

More valuable information would be available.

Russian social media dzen.ru allows up to 5 pins, AFAIK.

**Comment by trwnh** [comment]
Mastodon already allows up to 5 pins as well.
