### ISSUE TITLE
[MAS-139] Blocklist subscriptions

### ISSUE THREAD

**Issue by RokeJulianLockhart** [mastodon/mastodon#29022]
### Pitch

The ability to subscribe to multi-instance blocklists in a manner which doesn't necessitate any manual intervention.

### Motivation

Blocklist management is difficult for administrators - it's a manual process despite the usage of centralized blocklists. Standardizing the subscription and implementation process would be helpful.

**Comment by trwnh** [comment]
Duplicate of #116 and several others
