### ISSUE TITLE
Many things broken after update to 4.2.5 (not posting, no log-in, no admin/dashboard)

### ISSUE THREAD

**Issue by eWalthert** [mastodon/mastodon#29056]
### Steps to reproduce the problem

After updating the instance to the mandatory new version, we are experiencing major issues.
1. Posting result with an internal server error 500
2. We can no longer log into the instance. "We're sorry, but something went wrong on our end. " 
3. We can not reach the administration panel. /admin/dashboard/

### Expected behaviour

Things should be working as before.

### Actual behaviour

Many things are broken and the instance is no longer functional.

### Detailed description

We tried all the restarts of sidekiq and mastodon.
Looked into patches, that are already fixed in our version.

### Mastodon instance

typo.social

### Mastodon version

v4.2.5

### Technical details

- Ruby version: 3.0.2p107
- Node.js version: v16.20.2

**Comment by alansill** [comment]
Adding this problem: since the update, we are getting repeated emails saying that a critical update is available even though we have upgraded to the latest available release. Can this be controlled or cleared?

**Comment by eWalthert** [comment]
The issue got resolved. 
After the update, the usage of space got immensely increase, which lead to a shortage of storage on the server. 
This lead to all the malfunctions above. Increasing the disc-space resolved the issue.
This increase of data already happened with the last update. Is there a way to prevent this or to purge this data?
