### ISSUE TITLE
[Android] onboarding broken, not possible to verify email

### ISSUE THREAD

**Issue by MishOdeh** [mastodon/mastodon#29063]
### Steps to reproduce the problem

1. register a new email in the Android app (latest)
2. wait for verification email
3. notice how the email doesn't have a verification link, but has an "Account Setting" link instead, which will lead you to change your password rather than verify your email. 
...

### Expected behaviour

Verify email link

### Actual behaviour

Account settings link 

### Mastodon instance

Android app latest version

### Mastodon version

Latest

**Comment by Gargron** [comment]
Which server did this occur with? Can you show what the email looked like in a screenshot?

**Comment by MishOdeh** [comment]
> Which server did this occur with? Can you show what the email looked like in a screenshot?

![Screenshot_20240202_154234_Gmail.jpg](https://github.com/mastodon/mastodon/assets/125658541/62b61583-db7b-452a-88af-05fbea56e1d5)

**Comment by Gargron** [comment]
It looks like there may be a visual bug where a button is rendered as plain text. Is “Confirm and return to Mastodon on Android” clickable?

**Comment by MishOdeh** [comment]
> It looks like there may be a visual bug where a button is rendered as plain text. Is “Confirm and return to Mastodon on Android” clickable?

Good catch, you are right, I can have a look if you could point me towards the file that contains the email
