### ISSUE TITLE
Regression: Suggestion.source is documented as a string, currently returns list of strings

### ISSUE THREAD

**Issue by VyrCossont** [mastodon/mastodon#29071]
### Steps to reproduce the problem

1. On `mastodon.social`, call [`/api/v2/suggestions`](https://docs.joinmastodon.org/methods/suggestions/#v2)
2. Attempt to decode output as documented, as an array of [`Suggestion`](https://docs.joinmastodon.org/entities/Suggestion/) objects
3. Decoding fails because object has changed from documented format

### Expected behaviour

`Suggestion.source` should be a string

### Actual behaviour

`Suggestion.source` is an array of strings

### Detailed description

I'm not sure when this changed, but it's not documented, or backwards compatible with existing clients. My suggestion for the fix would be to keep `source` as a string, populate it with the first or most important of the possible source strings, deprecate `source`, and return the full list of sources as a new `sources` property on `Suggestion`.

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-02-02

**Comment by trwnh** [comment]
I believe this was added recently in main (see https://github.com/mastodon/documentation/issues/1398 for more), but yes, it does represent a breaking API change. I'd like to see this reworked to be backwards-compatible, or otherwise use an /api/v2 method prefix.

**Comment by andypiper** [comment]
Noted and I agree that a change like this which is visible via nightly on mastodon.social and mastodon.online should not be causing disruption -> we should look into ways to either make it backwards compatible, or move to a different prefix until a formal relase is made. Will follow up with the rest of the team here.
