### ISSUE TITLE
Wildcard, */* in an HTTP request Accept header irrespective to q-values sets higher preference

### ISSUE THREAD

**Issue by csarven** [mastodon/mastodon#29110]
### Steps to reproduce the problem

1. `curl -iLH'Accept: application/ld+json' https://w3c.social/users/csarven`
2. `curl -iLH'Accept: application/ld+json, application/activity+json' https://w3c.social/users/csarven`
3. `curl -iLH'Accept: application/ld+json, application/activity+json, */*' https://w3c.social/users/csarven`
4. `curl -iLH'Accept: application/ld+json, application/activity+json, */*; q=0.1' https://w3c.social/users/csarven`
5. `curl -iLH'Accept: application/ld+json, text/html' https://w3c.social/users/csarven`
...

### Expected behaviour

Conform to user agent's preferred representation when it can be generated

### Actual behaviour

When server detects `*/*` in Accept header, responds with `text/html`

### Detailed description

Given example:

`Accept: application/ld+json, application/activity+json, */*; q=0.1`

have the following precedence:

1. `application/ld+json`, `application/activity+json` (quality value 1)
2. `*/*` (quality value 0.1)

However, when `*/*` is present, the server responds with `text/html` irrespective to the q-values.

As per https://www.rfc-editor.org/rfc/rfc9110#section-12.5.1 , such behaviour is not an error but it may be inadequate provided that it already capable of providing a representation that's preferred by user agent. After all, when the request includes:

`Accept: application/ld+json, application/activity+json`

the server is capable of responding with:

`Content-Type: application/activity+json`

In fact, even with:

`Accept: application/ld+json, text/html`

the server responds with:

`Content-Type: application/activity+json`

### Mastodon instance

w3c.social

### Mastodon version

v4.2.5

**Comment by renchap** [comment]
After a quick look, there should not be anything in Mastodon touching this behaviour, this might be a Rails issue?

**Comment by mjankowski** [comment]
Yes - this is a rails issue. Whether it's a bug or a clever workaround for poorly formed headers from some browsers is up for debate (Search the rails issue history for this if you have a free afternoon).

I'm going to close this as wontfix since its sort of below our control ... that said, if there's some client thing that can't be done because of this, please reopen. Might also be useful to improve API docs around this subtlety?
