### ISSUE TITLE
bot accounts don't need who to follow 

### ISSUE THREAD

**Issue by markrprior** [mastodon/mastodon#29168]
### Steps to reproduce the problem

Just refreshing the browser view of my bot account to see if anyone had asked it questions and now I see a "who to follow" section. An account that is already tagged as automated doesn't need suggestions on other accounts to follow.

### Expected behaviour

Don't show a "who to follow" list in the timeline

### Actual behaviour

A "who to follow" list is shown in the timeline

### Detailed description

<img width="1233" alt="Screenshot 2024-02-12 at 14 58 52" src="https://github.com/mastodon/mastodon/assets/6236685/465397c6-af0b-4116-9f6c-d26d4c265015">
A screenshot of an automated account being suggested accounts to follow

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-02-03

### Browser name and version

Firefox 122.0.1 (64-bit)

### Operating system

macOS 14.3.1

**Comment by ClearlyClaire** [comment]
Hi! You can just click “Don't show this again”

**Comment by Gargron** [comment]
It's created on demand when you load the page. I'd guess most bots never open the web app in the browser so this shouldn't be an issue.
