### ISSUE TITLE
Suggestion for the Mastodon web interface: align/put the "Back" links in the same layout

### ISSUE THREAD

**Issue by KNTRO** [mastodon/mastodon#29213]
### Pitch

I've noted that the "Back" link is set in different positions.

It's aligned **to the left** on the profile:
![Back1](https://github.com/mastodon/mastodon/assets/2568821/2213243d-4e8a-4faf-aa44-ff3da40e8d87)

However, it's aligned **to the right** when searching for hashtags:
![Back2](https://github.com/mastodon/mastodon/assets/2568821/c1acbdc9-3b57-49cc-bd2e-e563110478e3)

### Motivation

I think that putting the "Back" link in the same place is a more consistent and friendly choice, in my humble opinion. I think we all would benefit from this, especially new comers.

Thanks for reading!

Kind regards. 🙂

**Comment by KNTRO** [comment]
@brendanjones Hi, Brendan!

Thank you a lot for reading! I'm glad you liked my suggestion. 😸

Whenever you make the change, you can close this suggestion.

Have a nice weekend. Thank you again!

**Comment by brendanjones** [comment]
I can't make the change or close the issue, I'm not a developer and I'm not in the Mastodon team :)

**Comment by KNTRO** [comment]
@brendanjones Oh, my bad. I'm sorry. 🤣

**Comment by brendanjones** [comment]
This back link being on the right is the silliest little inconsistency in design and it's killing me that I can't just change it because I don't know how. So you know what you've got me doing @KNTRO ? I'm literally learning how to set up a freakin dev environment right now because I'm sick of being reliant on developers to fix tiny front-end problems. You might think I've got better things to do on my Saturday night, but you'd be wrong.

It might take a year or two but if this is not fixed by 2026 then please feel free to hold me accountable. 😆

**Comment by KNTRO** [comment]
> I'm sick of being reliant on developers to fix tiny front-end problems.

Welcome to the world of FOSS.

Unfortunately. 😅

> You might think I've got better things to do on my Saturday night, but you'd be wrong.

As a matter of fact, I'd be doing the very same thing. 😃

**Comment by brendanjones** [comment]
Aha this is not a FOSS problem, this is a me problem; I am not a developer. Working out how to do little fixes like this without creating more work for others would actually be a great thing for my work - for such simple fixes as this it takes longer to explain the problem to another than to fix it yourself, and my time is cheaper than a dev's anyway. It also means not distracting devs from harder work, thus preventing the mental load of switching. So I'm treating this as an educational experience :)

**Comment by trwnh** [comment]
![image](https://github.com/mastodon/mastodon/assets/10606431/c99e65b4-9e99-48f7-a93e-20b1ea1f5cd0)
