### ISSUE TITLE
Add "yarn install --force" to the documentation

### ISSUE THREAD

**Issue by M-Stenzel** [mastodon/mastodon#29236]
### Pitch

Upgrading from version 4.2.5. to 4.2.6. was unsuccessful in the first run. 
It stopped after the 2nd step

`yarn install v1.22.19
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
$ husky install
husky - Git hooks installed`

Adding the "--force" switch to yarn resulted in

`yarn install v1.22.19
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
[4/6] Linking dependencies...
[5/6] Rebuilding all packages...
[6/6] Cleaning modules...
$ husky install
husky - Git hooks installed`

With the switch, all the packages were built. Success!

May I suggest that you mention to use the "--force" switch, if needed, in the documentation.

### Motivation

Help improve documentation in order that upgrade process gets facilitated.

**Comment by renchap** [comment]
This is expected, there has been no change in JS packages between 4.2.5 and 4.2.6, so yarn did not need to change the installed packages.
