### ISSUE TITLE
Bad link in v4.2.7 release notes

### ISSUE THREAD

**Issue by danorton** [mastodon/mastodon#29246]
### Steps to reproduce the problem

1. URL https://github.com/mastodon/mastodon/releases/tag/v4.2.7
2. The hyperlink that reads “GHSA-jhrq-qvrm-qr36" links to 404 broken link https://github.com/mastodon/mastodon/security/advisories/GHSA-jhrq-qvrm-qr36

### Expected behaviour

I surmise that the link should refer to a security advisory

### Actual behaviour

HTTP status 404

### Mastodon instance

mastodon.social

### Mastodon version

v4.2.7

### Browser name and version

Firefox 105.0.3

### Operating system

macOS 13.4.1

**Comment by renchap** [comment]
The link is correct, but we did not publish the advisory yet. It will be done before end-of-day tomorrow (cant tell when exactly for now).

**Comment by renchap** [comment]
The advisory has been published.
