### ISSUE TITLE
Long display name rendering issue on /admin/accounts/ page

### ISSUE THREAD

**Issue by colinstu12** [mastodon/mastodon#29259]
### Steps to reproduce the problem

1. With the correct permissions, go to the Moderation > Accounts (/admin/accounts/) page.
2. With an existing user that has a very long display name, find/look at it...

### Expected behaviour

Display name should truncate so that everything doesn't get pushed off (post count, follower count, last active time)

### Actual behaviour

The display name takes up all/the entire width

### Detailed description

<img width="860" alt="Screenshot 2024-02-17 at 09 45 33" src="https://github.com/mastodon/mastodon/assets/64501599/eec7486b-b09d-4ec2-93e9-ae66064edbb8">

### Mastodon instance

birdbutt.com

### Mastodon version

v4.2.7

### Browser name and version

Firefox 122

### Operating system

macOS 14.3.1

**Comment by ThisIsMissEm** [comment]
This issue also occurs with long usernames too, and the fix proposed in #29316 handles that as well.
<img width="906" alt="Screenshot 2024-08-17 at 21 29 04" src="https://github.com/user-attachments/assets/5125aba2-4a2d-4030-a399-49f87e9c626f">
