### ISSUE TITLE
report figures in the public information

### ISSUE THREAD

**Issue by Tealk** [mastodon/mastodon#29300]
### Pitch

It would be great if the number of reports could be read out in one of the public information.

There is /nodeinfo/2.0 and /api/v1/instance

### Motivation

This could be used to create a nice overview of how many reports have been created and how many have been edited.
It would make a great graph.

**Comment by ThisIsMissEm** [comment]
This is already covered by #27561 which proposed introducing a full set of metrics for moderation of servers

Keep in mind: a high report count doesn't necessarily mean a bad server, especially if those reports are acknowledged in a timely manner, so we need to be careful about how the numbers could misrepresent servers of varying sizes and moderation skills/teams/workflows

**Comment by ThisIsMissEm** [comment]
@vmstan I think we can close this as a dupe, if the OP agrees?

**Comment by Tealk** [comment]
> Keep in mind: a high report count doesn't necessarily mean a bad server, especially if those reports are acknowledged in a timely manner, so we need to be careful about how the numbers could misrepresent servers of varying sizes and moderation skills/teams/workflows

I only want to show it in grafana for information purposes, it's more about having an overview of how much effort is involved in the project.



> if the OP agrees?

yes
