### ISSUE TITLE
report option to forward to other servers mentioned in toot

### ISSUE THREAD

**Issue by unusualevent** [mastodon/mastodon#29344]
### Pitch

Mastodon's user facing report flow should have the option to forward the report not just to the original server, but to any servers mentioned in the conversation.

1. spam @ A mentions user1 @ B and user2 @ C
2. user1 @ B reports and forwards to A, as well as C.
3. mods at A, B, & C all get the benefit of advance-notice crowdsource moderation

### Motivation

The recent spam wave has lots of cross-instance mentions to multiple folks, not just on the same server.

**Comment by ThisIsMissEm** [comment]
This is already implemented in some clients (i.e., web) but not implemented in most others. What we probably need here is a way for mods to forward reports onwards, and there are tickets for that..

**Comment by unusualevent** [comment]
@ThisIsMissEm  I know it supports forwarding to the author's server - but are you saying it supports forwarding to the other mentioned users' servers too?

**Comment by ThisIsMissEm** [comment]
> @ThisIsMissEm I know it supports forwarding to the author's server - but are you saying it supports forwarding to the other mentioned users' servers too?

@unusualevent should do, yes!

**Comment by trwnh** [comment]
Fixed by #25866
