### ISSUE TITLE
Admin user itself needs to be approved on fresh installed v4.2.8 instance

### ISSUE THREAD

**Issue by coreice** [mastodon/mastodon#29380]
### Steps to reproduce the problem

1. Install Mastodon v4.2.8 on a fresh server
2. Run the installation scripts like the documentation
3. Log into the instance when the installation procedure is finished
4. Run into the issue where the `admin` user needs to be validated by... an admin.

![image](https://github.com/mastodon/mastodon/assets/10442497/c5f0df10-a199-4fcd-8dc8-658f7abfc6ae)
_(Sorry for the Dutch screenshot, but the yellow message bar says the account needs to be validated by one of 'our employees'.)_

### Expected behaviour

The first user created during install should not have an activation requirement.

### Actual behaviour

The admin user needed to be activated, being unable to use a new install of Mastodon as the unactivated user cannot access or change the server related settings in the Web UI.

### Detailed description

When logging in after the installation script and procedure has been finished, most server admin related pages redirect to `/auth/edit`. Mastodon comes with the message that the account needs to be judged cq. approved by the administrator. 

But actually your are put into a vicious circle. As the `admin` user is the newly created and only user on a fresh Mastodon instance, you cannot approve yourself because the server keeps redirecting you to `/auth/edit`.

To validate this is an issue inside the newly released v4.2.8, I have done an installation with v4.2.7. Here I experienced no issues with the administration account after finishing installation.

### Mastodon instance

A non-public instance for testing purposes.

### Mastodon version

v4.2.8

### Browser name and version

Safari v17.3.1

### Operating system

macOS 14.3.1

### Technical details

Server is running Ubuntu 22.04 LTS, PostgresSQL 16.2.

**Comment by renchap** [comment]
This has been fixed by #29379 and a note has been added to the release notes about a workaround (using `tootctl modify <username> --approved`)

**Comment by cavuugroup** [comment]
> This has been fixed by #29379 and a note has been added to the release notes about a workaround (using `tootctl modify <username> --approved`)

for my fresh installation it was:
`./tootctl accounts approve admin`

**Comment by dilroopg** [comment]
sudo docker exec -it -w /app/www mastodon bin/tootctl accounts approve "username" if using runtipi
