### ISSUE TITLE
429 error on timeline endpoints before reaching configured rate limits

### ISSUE THREAD

**Issue by progval** [mastodon/mastodon#29392]
### Steps to reproduce the problem

1. Send 80 requests to each of `/api/v1/announcements`, `/api/v1/timelines/home`, and `/api/v1/notifications` within a minute

### Expected behaviour

HTTP 200 response

### Actual behaviour

HTTP 429 errors

### Detailed description

this happens with the default configuration

```
  throttle('throttle_authenticated_api', limit: 1_500, period: 5.minutes) do |req|
    req.authenticated_user_id if req.api_request?
  end

  throttle('throttle_per_token_api', limit: 300, period: 5.minutes) do |req|
    req.authenticated_token_id if req.api_request?
  end

  throttle('throttle_unauthenticated_api', limit: 300, period: 5.minutes) do |req|
    req.throttleable_remote_ip if req.api_request? && req.unauthenticated?
  end
```

this is an issue because the fallback in `app/javascript/mastodon/actions/streaming.js` retries with a random delay which averages to 90 requests every 5 minutes, causing this rate limit to kick in for users with 2 tabs open

### Mastodon instance

oc.todon.fr

### Mastodon version

v4.2.8

### Technical details

- `ruby v3.1.2p20`
- `node v18.19.0`

**Comment by progval** [comment]
> Can you add more detail about how to recreate the condition here? Is this purely from having two browser tabs open and doing (a lot of) things with the UX ... or also having some scripted automation make those 80 reqs each?

I reproduced it with automation, but it initially happened to one of my users for an unknown reason. I'm guessing it was two browser tabs because I don't see how else it could have happened.

> Separately - is your expected/actual description in the issue backwards?

Yes, fixed

**Comment by mjankowski** [comment]
Does this happen *regularly* to this specific user, or just a one-off? It seems like even with multiple tabs open it would be hard to hit that limit just from the regular fallback polling.

**Comment by progval** [comment]
a one-off

**Comment by mjankowski** [comment]
Going to close on assumption that this was a one-off ... and/or there was a bug that is now fixed. Please reopen if you can replicate this consistently on 4.3 server.
