### ISSUE TITLE
Unlisted bot toots are not displayed by other servers in the profile overview and in the hashtag search

### ISSUE THREAD

**Issue by Sam4000der2** [mastodon/mastodon#29400]
### Steps to reproduce the problem

1.  Publish toots via API as a bot or manually in the unlisted setting - account have to be marked as automated
2. Check whether they are visible from other instances. 
3. it seems to affect all unlisted toots from profiles marked as automated. Regardless of whether the toots are published manually or automatically.
4. Corresponding toots are not displayed.

### Expected behaviour

All toots should be displayed.

### Actual behaviour

Unlisted toots are not displayed.

### Detailed description

Apparently only affects accounts set up as automated accounts in combination with the unlisted function.

I have checked 3 instances.

As soon as you follow the account, all new toots are displayed. But not the old ones.

My examples:
https://toot.berlin/@opnv_bot
https://berlin.social/@opnv_bot
https://mastodon.berlin/@opnv_bot

The corresponding toots are also not displayed in the hashtag search. 

It will probably be a bug in the server software.

Occurs independently of the browser. Repeatable under Chromium and Tusky, among others.

All instances have version v4.2.8 installed. 

### Mastodon instance

https://berlin.social/

### Mastodon version

v4.2.8

**Comment by trwnh** [comment]
Unlisted posts don't show up in hashtag search, but they should show up on profiles. What seems to be the case here is that your examples show three completely different accounts. For example, note that https://toot.berlin/@opnv_bot is not the same as https://berlin.social/@opnv_bot -- to access the berlin.social account from toot.berlin, the link would be https://toot.berlin/@opnv_bot@berlin.social -- and to access the toot.berlin account from berlin.social, the link would be https://berlin.social/@opnv_bot@toot.berlin
