### ISSUE TITLE
Support for short videos (aka reels, shorts, tiktok)

### ISSUE THREAD

**Issue by leandrokemp** [mastodon/mastodon#29428]
### Pitch

Currently Mastodon does have support for videos. However those are normal videos people can post in a regular post.
It would be great if there was an exclusive tab on the app that auto plays short videos (eg. max 15 sec). Then you can go to the next video by swiping up, similar to the the way Instagram reels and Tiktok short videos work.

The videos selection could be based on:
- Language
- Most watched *
- Most liked
- Watched by you (similar videos) *
- Liked by you (similar videos)

* "watched" videos would only be counted if most of the video content was watched. Eg. when video is watched for only one or 2 seconds, it wouldn't be counted as "watched".

Would it be possible to implement a feature like this with the fediverse?

### Motivation

Short videos are the most popular feature in social media apps recently, like Instagram reels and Tiktok. Even You Tube has this feature now (YouTube Shorts).
I believe that Mastodon would be able to attract more users if it had this feature.
Also, when I using Mastodon, sometimes I miss this feature and it drives me back to Instagram.

**Comment by renchap** [comment]
Mastodon is intended as a microblogging platform, with a focus on text. This feature will probably never be implemented.

If you are looking for Instagram alternatives, Pixelfed (which is also part of the Fediverse, and interoperable with Mastodon) is probably a better fit.
