### ISSUE TITLE
Mastodon is presenting .jpgs as .webps 

### ISSUE THREAD

**Issue by Servelan** [mastodon/mastodon#29432]
### Steps to reproduce the problem

Found a funny graphic I wanted to save to another social  medium.  Right clicked on it and it only wants to save as a .webp.  Searched for a bug report on this; couldn't find one.

### Expected behaviour

.jpg is presented as a .jpg

### Actual behaviour

it's presented and can only be saved as a .webp

### Detailed description

Right click on the graphic to save from here (or whatever you do to save it): https://universeodon.com/@AnneTheWriter1/112007072682031876  If you look at the image information, it's a .jpg

Same post, here: https://elk.zone/universeodon.com/@AnneTheWriter1/112007072682031876 and here, on newsie.social:  https://universeodon.com/@AnneTheWriter1/112007072682031876:  it's only savable as a webp.

URL for the image: https://assets.newsie.social/cache/media_attachments/files/112/007/072/756/478/452/original/a92608bc06c8cb3c.**jpg**

This is disconcerting and undermines confidence.  If this is happening, what else is being manipulated?

### Mastodon instance

newsie.social

**Comment by renchap** [comment]
This is not coming from Mastodon. Those websites are using Cloudflare and probably have enabled something that automatically convert the image files to other format than the original one, based on the request's `Accept` header.

This is a common feature nowadays with CDNs, as it allows serving smaller files (hence less bandwidth, less CPU used for decoding) to browsers that support them.

```
# With Chrome accept header
$ curl -s 'https://assets.newsie.social/cache/media_attachments/files/112/007/072/756/478/452/original/a92608bc06c8cb3c.jpg' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  --compressed -I | grep 'content-type'
content-type: image/webp

# Without it
$ curl -s 'https://assets.newsie.social/cache/media_attachments/files/112/007/072/756/478/452/original/a92608bc06c8cb3c.jpg' \
  --compressed -I | grep 'content-type'
content-type: image/jpeg
```
