### ISSUE TITLE
Profile featured hashtags defect

### ISSUE THREAD

**Issue by tenebrios** [mastodon/mastodon#29481]
### Pitch

The profile featured hashtags are "supposed" to only show what "we" posted under those tags but it doesn't. 
It actually shows what everyone else has posted under those tags as well.

This needs to be fixed 

### Motivation

Beneficial because it is a feature that is not working properly

**Comment by trwnh** [comment]
Cannot reproduce -- featured tags are of the form `https://mastodon.social/@trwnh/tagged/nowplaying` while tag timelines are of the form `https://mastodon.social/tags/nowPlaying`

**Comment by tenebrios** [comment]
> Cannot reproduce -- featured tags are of the form `https://mastodon.social/@trwnh/tagged/nowplaying` while tag timelines are of the form `https://mastodon.social/tags/nowPlaying`

Cannot reproduce?
So if you add a tag to your featured list and then you open that tag, you're only seeing the posts that "you" entered under that tag??
It doesn't do that for me.
It shows me everyone's posts on all of Mastodon that used that particular tag.
That's not how the featured tag should work.

**Comment by trwnh** [comment]
From which server are you observing this behavior?

**Comment by tenebrios** [comment]
> From which server are you observing this behavior?

I'm using the web app.
I "was" using the app from the app store but it seems to not work now. 
I tried uninstalling the app and reinstalling it but now when I try to log in it can't retrieve the server (mastodon.social). I even tried entering other servers and the same result. The app store app can't retrieve the servers.

So I'm using the "web app" now.
People are still following me. I don't know what they're using or if the app store app is working for them but I'm still getting new followers everyday.

Back to the hashtag issue.
I was not able to make the featured hashtag list using the app store app.
I ended up making the featured using the web version of mastodon. 
Then the list appeared on the app.

When I opened a featured tag (either on the app or the web), it did not only shown me my posts under those tags. It showed me everyone elses posts as well that used those tags.

I have since removed my featured tags for that reason. 

Lastly, on the web version I saw the featured list on my profile page on the bottom right. It showed a list of 2 out of the 10.
On the web app, that list is no where to be seen on my profile

**Comment by tenebrios** [comment]
Fyi
When I say "web app", that means I opened Mastodon from my phone but on the web. 
From there I downloaded the web app version.
Visually it's quite different from the app store version.
Access to saved photos on our phone is actually much easier with the web app compared to the app store version

**Comment by trwnh** [comment]
Ah, this is a bug in the Android app, and should be filed against https://github.com/mastodon/mastodon-android instead.

**Comment by tenebrios** [comment]
> Ah, this is a bug in the Android app, and should be filed against https://github.com/mastodon/mastodon-android instead.
> 
> EDIT: [mastodon/mastodon-android#786](https://github.com/mastodon/mastodon-android/issues/786)

What does "should be filed against" mean?
Will it actually be fixed?
If so, when can we expect it to be fixed?

In addition, if they fix it, the featured list is no where to be seen on the web app.
After the featured list is made, where can it be found on the web app?
