### ISSUE TITLE
Ability to open a specific hashtag in the moderation interface

### ISSUE THREAD

**Issue by nileane** [mastodon/mastodon#29491]
### Pitch

Currently, you can't open a specific hashtag in the moderation interface, unless it is currently trending on the instance.
It is possible using the direct url `https://domain/admin/tags/#`, but you need the database id # to open up the correct one. There should be a way, in the moderation interface, to search for a specific hashtag.

### Motivation

This would help preventively disable the use of a hashtag on the instance, without having to wait for it to be on the trending hashtags page.

This would also allow admins and moderators to go back to a previously disabled hashtag to re-allow its use on the instance.

**Comment by gunchleoc** [comment]
I also have a bunch of hashtags that I would like to block, but I can't, because they're not trending.
