### ISSUE TITLE
Upload GIF results in a 422

### ISSUE THREAD

**Issue by aneillans** [mastodon/mastodon#29511]
### Steps to reproduce the problem

Upload GIF on API. file is accepted with a 202.
Status response received a 422.

### Expected behaviour

GIF should be accepted and converted to MP4 and attached.

### Actual behaviour

Post is rejected.

### Detailed description

Uploading a GIF file on API, any size, and the conversion completes correctly as per the log. This is accepted and a 202 returned.

The status is, however, responded with a 422 when linked.

### Mastodon version

4.3.0

### Technical details

Mar 05 16:32:33 m bundle[2532417]: I, [2024-03-05T16:32:33.233063 #2532417]  INFO -- : [8938830a-f1c9-4225-bfd4-3e25deec36b1] Command :: ffmpeg -nostdin -i '/tmp/058c7d82d0cfe51d836c5bfcc699971620240305-2532417-7utnqe.gif' -loglevel 'fatal' -preset 'veryfast' -movflags 'faststart' -pix_fmt 'yuv420p' -vf 'crop=floor(iw/2)*2:floor(ih/2)*2' -c:v 'h264' -c:a 'aac' -b:a '192k' -map_metadata '-1' -frames:v '36000' -b:v '216268' -maxrate '408268' -bufsize '1081340' -y '/tmp/058c7d82d0cfe51d836c5bfcc699971620240305-2532417-7utnqe20240305-2532417-z0la08.mp4'
Mar 05 16:32:33 m bundle[2532417]: I, [2024-03-05T16:32:33.304765 #2532417]  INFO -- : [8938830a-f1c9-4225-bfd4-3e25deec36b1] [paperclip] Trying to link /tmp/058c7d82d0cfe51d836c5bfcc699971620240305-2532417-7utnqe20240305-2532417-z0la08.mp4 to /tmp/c99f0cf0da0950fe20a59c89ea57ef1d20240305-2532417-ouemhw.mp4
Mar 05 16:32:33 m bundle[2532417]: I, [2024-03-05T16:32:33.372561 #2532417]  INFO -- : [8938830a-f1c9-4225-bfd4-3e25deec36b1] Command :: ffmpeg -nostdin -ss '0' -i '/tmp/c99f0cf0da0950fe20a59c89ea57ef1d20240305-2532417-ouemhw.mp4' -loglevel 'fatal' -vf 'scale='\''min(640\, iw):min(640\, ih)'\'':force_original_aspect_ratio=decrease' -f 'image2' -vframes '1' -y '/tmp/c99f0cf0da0950fe20a59c89ea57ef1d20240305-2532417-ouemhw20240305-2532417-sjwn5n.png'
Mar 05 16:32:33 m bundle[2532417]: I, [2024-03-05T16:32:33.442191 #2532417]  INFO -- : [8938830a-f1c9-4225-bfd4-3e25deec36b1] Command :: convert '/tmp/c99f0cf0da0950fe20a59c89ea57ef1d20240305-2532417-ouemhw20240305-2532417-sjwn5n.png' -depth 8 RGB:-
Mar 05 16:32:33 m bundle[2532417]: I, [2024-03-05T16:32:33.528921 #2532417]  INFO -- : [8938830a-f1c9-4225-bfd4-3e25deec36b1] [paperclip] Trying to link /tmp/c99f0cf0da0950fe20a59c89ea57ef1d20240305-2532417-ouemhw20240305-2532417-sjwn5n.png to /tmp/9a5c2350346aea493b6b4ae23aad731720240305-2532417-bz9okk.png
Mar 05 16:32:33 m bundle[2532417]: I, [2024-03-05T16:32:33.579088 #2532417]  INFO -- : [8938830a-f1c9-4225-bfd4-3e25deec36b1] [paperclip] Trying to link /tmp/c99f0cf0da0950fe20a59c89ea57ef1d20240305-2532417-ouemhw.mp4 to /tmp/99b198a2875b1bb6b8675c3334bd14c620240305-2532417-6n1c4.mp4
Mar 05 16:32:33 m bundle[2532417]: I, [2024-03-05T16:32:33.579455 #2532417]  INFO -- : [8938830a-f1c9-4225-bfd4-3e25deec36b1] Command :: file -b --mime '/tmp/99b198a2875b1bb6b8675c3334bd14c620240305-2532417-6n1c4.mp4'
Mar 05 16:32:33 m bundle[2532417]: I, [2024-03-05T16:32:33.588911 #2532417]  INFO -- : [8938830a-f1c9-4225-bfd4-3e25deec36b1] [paperclip] saving media_attachments/files/112/044/038/788/718/223/original/c2b6cff19fdfbbe0.mp4
Mar 05 16:32:33 m bundle[2532417]: I, [2024-03-05T16:32:33.829786 #2532417]  INFO -- : [8938830a-f1c9-4225-bfd4-3e25deec36b1] [paperclip] saving media_attachments/files/112/044/038/788/718/223/small/c2b6cff19fdfbbe0.png
Mar 05 16:32:33 m bundle[2532417]: I, [2024-03-05T16:32:33.898239 #2532417]  INFO -- : [8938830a-f1c9-4225-bfd4-3e25deec36b1] method=POST path=/api/v2/media format=html controller=Api::V2::MediaController action=create status=202 allocations=169783 duration=729.14 view=1.39 db=3.49
Mar 05 16:32:34 m bundle[2532404]: I, [2024-03-05T16:32:34.020512 #2532404]  INFO -- : [7a638cd7-5b5f-4563-8fa4-72290ae80327] method=POST path=/api/v1/statuses format=html controller=Api::V1::StatusesController action=create status=422 allocations=2966 duration=12.34 view=0.47 db=2.34

**Comment by mjankowski** [comment]
Is this against a production instance somewhere, or local dev environment?

Are those requests generated by the Web UI app? A native client? a programming api/lib? curl? etc.

Depending on prior answers this may or may not be relevant - but if is relevant (direct api access or something) -- what does the full http request body to the `/api/v1/statuses` endpoint look like?

**Comment by aneillans** [comment]
Tested against both production (live) instances, as well as a copy spun up locally, same behaviour.

My current tests are using the megalodon nodejs library, will grab the full payload (both request and response).

**Comment by aneillans** [comment]
Response to the media upload:

{
  id: '112045269931184159',
  type: 'gifv',
  url: null,
  preview_url: 'https://<instance>/media_attachments/files/112/045/269/931/184/159/small/8886a7ed42131d87.png',
  remote_url: null,
  preview_remote_url: null,
  text_url: null,
  meta: {
    original: {
      width: 256,
      height: 256,
      frame_rate: '2/1',
      duration: 4,
      bitrate: 63680
    },
    small: { width: 256, height: 256, size: '256x256', aspect: 1 }
  },
  description: null,
  blurhash: 'U48:^}NFbia{^,WA9ZWTs[s:={aw58Ri^*og'
}

I noticed that the url is empty - that doesn't look right to me ?

**Comment by mjankowski** [comment]
> I noticed that the url is empty - that doesn't look right to me ?

I believe when an upload needs "processing", that does return null in the serializer when it's not done yet.

That said -- I think this was the request where you get a 202? What does the status request/response where you get the 422 look like?

**Comment by rasos** [comment]
Seems to be related to the `ffmpeg` version, see https://github.com/mastodon/mastodon/issues/26170#issuecomment-1872928352

**Comment by vmstan** [comment]
@aneillans is this still an issue for your deployment?
