### ISSUE TITLE
OAuth /oauth/authorize doesn't return `code` parameter

### ISSUE THREAD

**Issue by Eriner** [mastodon/mastodon#29525]
### Steps to reproduce the problem

Attempt to sign in to https://noauthority.social with Tusky or any other Android app. On successful authentication, the application redirects to the mobile web interface and does not return the `code` parameter in the response from `/oauth/authorize`.

### Expected behaviour

show the app authorize screen

### Actual behaviour

opens web interface

### Detailed description

Might be related to #28776.

### Mastodon instance

noauthority.social

### Mastodon version

v4.2.7

### Technical details

App successfully registers:

**Request**
```
POST /api/v1/apps HTTP/1.1
Host: noauthority.social
User-Agent: Tusky/24.1 Android/14 OkHttp/4.11.0
Content-Type: application/x-www-form-urlencoded
Content-Length: 149
Accept-Encoding: gzip, deflate, br
Connection: close

client_name=Tusky&redirect_uris=oauth2redirect%3A%2F%2Fcom.keylesspalace.tusky%2F&scopes=read%20write%20follow%20push&website=https%3A%2F%2Ftusky.app
```

**Response**
```
HTTP/2 200 OK
Date: Thu, 07 Mar 2024 19:17:07 GMT
Content-Type: application/json; charset=utf-8
Vary: Accept-Encoding
Vary: Authorization, Origin
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-Xss-Protection: 0
Referrer-Policy: same-origin
Referrer-Policy: origin
X-Ratelimit-Limit: 300
X-Ratelimit-Remaining: 299
X-Ratelimit-Reset: 2024-03-07T19:20:00.403762Z
Cache-Control: private, no-store
Etag: W/"80f692e1d568bb2778482b251b16cf93"
Content-Security-Policy: default-src 'none'; frame-ancestors 'none'; form-action 'none'
X-Request-Id: dca393e3-3e2b-4df3-8693-bae381f24fc0
X-Runtime: 0.008112
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
Permissions-Policy: accelerometer=(), autoplay=(), camera=(), display-capture=(), encrypted-media=(), fullscreen=(self), gamepad=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), usb=(), screen-wake-lock=(), xr-spatial-tracking=()
Cf-Cache-Status: DYNAMIC
Server: cloudflare
Cf-Ray: 860cec8118a7825c-IAD
Alt-Svc: h3=":443"; ma=86400

{"id":"4208","name":"Tusky","website":"https://tusky.app","redirect_uri":"oauth2redirect://com.keylesspalace.tusky/","client_id":"-jnmX9SOuM6O3GL5RUoollTm_wV5F98Pmcg3tlSmRb8","client_secret":"[REDACTED]","vapid_key":"[REDACTED]}
```

App then GETs the OAuth endpoint:

**Request**
```
GET /oauth/authorize?client_id=-jnmX9SOuM6O3GL5RUoollTm_wV5F98Pmcg3tlSmRb8&redirect_uri=oauth2redirect%3A%2F%2Fcom.keylesspalace.tusky%2F&response_type=code&scope=read%20write%20follow%20push HTTP/2
Host: noauthority.social
Sec-Ch-Ua: "Chromium";v="122", "Not(A:Brand";v="24", "Android WebView";v="122"
Sec-Ch-Ua-Mobile: ?1
Sec-Ch-Ua-Platform: "Android"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Linux; Android 14; ONEPLUS A6003 Build/UQ1A.240205.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.90 Mobile Safari/537.36 Tusky/24.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
X-Requested-With: com.keylesspalace.tusky
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```

**Response**
```
HTTP/2 302 Found
Date: Thu, 07 Mar 2024 19:17:07 GMT
Content-Type: text/html; charset=utf-8
Location: https://noauthority.social/auth/sign_in
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-Xss-Protection: 0
Referrer-Policy: same-origin
Referrer-Policy: origin
Cache-Control: private, no-store
Content-Security-Policy: base-uri 'none'; default-src 'none'; frame-ancestors 'none'; font-src 'self' https://noauthority.social; img-src 'self' https: data: blob: https://noauthority.social; style-src 'self' https://noauthority.social 'nonce-9jBaNbPV0N/7BDrkm1fIMA=='; media-src 'self' https: data: https://noauthority.social; frame-src 'self' https:; manifest-src 'self' https://noauthority.social; form-action 'self'; child-src 'self' blob: https://noauthority.social; worker-src 'self' blob: https://noauthority.social; connect-src 'self' data: blob: https://noauthority.social https://static.noauthority.social wss://noauthority.social; script-src 'self' https://noauthority.social 'wasm-unsafe-eval'
Set-Cookie: _mastodon_session=[REDACTED]; path=/; HttpOnly; SameSite=Lax; secure
X-Request-Id: 1438acbe-9fb0-4fb0-8289-9e2a94421beb
X-Runtime: 0.002167
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
Permissions-Policy: accelerometer=(), autoplay=(), camera=(), display-capture=(), encrypted-media=(), fullscreen=(self), gamepad=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), usb=(), screen-wake-lock=(), xr-spatial-tracking=()
Cf-Cache-Status: DYNAMIC
Server: cloudflare
Cf-Ray: 860cec83dc31825c-IAD
Alt-Svc: h3=":443"; ma=86400

<html><body>You are being <a href="https://noauthority.social/auth/sign_in">redirected</a>.</body></html>
```

[API documentation](https://docs.joinmastodon.org/methods/oauth/#response)

The request flow then continues with the GET and POST to `/auth/sign_in`, which returns a 302 to the root (`https://noauthority.social`). A `code` parameter is not returned with a 200 or in the `Location` header of the 302.

Let me know if there is any additional debugging information I can provide, or if you'd like me to test something.

**Comment by drboone** [comment]
See also #26535.

**Comment by ThisIsMissEm** [comment]
The requests & responses here are all correct, if you are not logged in and you request `/oauth/authorize` you'll be redirected to `/auth/sign_in`; Once you have completed the sign_in, you should be redirected back to `/oauth/authorize` (however, if you're already using the given application and force_login is not true, then you'll be automatically redirected back to the applications `redirect_uri` with the given parameters for the redirect.

I'd need to know the response to `POST /auth/sign_in` response, which is after you've signed in. **Please don't share the `POST /auth/sign_in` request as this could contain sensitive data.** In the response, there should be a Location header that redirects to `/oauth/authorize` which may in turn automatically redirect back to the application's oauth redirect_uri, instead of showing the oauth consent dialog (since you've already consented)

However, there is a circumstance that can happen where a previous session exists which says "redirect to `/`" on sign in, not `/oauth/authorize` as expected. I'm still not 100% sure under which circumstances the redirect to / happens under.

**Comment by nikclayton** [comment]
This looks like the Referrer-Policy problem again. The site is returning two headers, one of which is "origin", so the path will not be included.

https://github.com/pachli/pachli-android/issues/210

**Comment by Eriner** [comment]
DUH! I can't believe I missed that. Thank you for the second set of eyes.
