### ISSUE TITLE
DB Migration from 4.0.2 to 4.2.8 results in Makara error

### ISSUE THREAD

**Issue by cybiko123** [mastodon/mastodon#29536]
### Steps to reproduce the problem

1. cd /var/www
2. wget https://github.com/mastodon/mastodon/archive/refs/tags/v4.2.8.tar.gz
3. tar -xzvf v4.2.8.tar.gz 
4. cd mastodon-4.2.8/
5. cp -R * ../mastodon
6. cd ../mastodon
7. RAILS_ENV=production /home/mastodon/.rbenv/versions/3.2.2/bin/bundle install
8. yarn install --frozen-lockfile
9. SKIP_POST_DEPLOYMENT_MIGRATIONS=true RAILS_ENV=production /home/mastodon/.rbenv/versions/3.2.2/bin/bundle exec rails db:migrate

### Expected behaviour

DB should have been migrated to latest version

### Actual behaviour

rails aborted!\nNameError: uninitialized constant Makara

### Mastodon instance

social.joshanders.com

### Mastodon version

4.0.2

### Technical details

- Ruby version: 3.2.2
- Node.js version: 16.20.2

**Comment by Gargron** [comment]
Makara has been removed. If you have a custom config/database.yml, revert it to the one distributed with the repository. See these notes for how to switch over your replica configuration:

https://github.com/mastodon/mastodon/releases/tag/v4.2.0 -> "Database replica configuration"

**Comment by cybiko123** [comment]
Thanks for the hint. It appears there was a stray config/initializers/makara.rb file causing that issue. However, it wasn't the only one; I eventually just did a clean install (with .env.production, the DB, and public/ backed up).
