### ISSUE TITLE
Add a system check for non-populated views

### ISSUE THREAD

**Issue by renchap** [mastodon/mastodon#29534]
### Pitch

When restoring the database from a `.sql` dump, the materialised views are not populated.

This can be checked with 

```sql
select schemaname as schema_name,
       matviewname as view_name,
       matviewowner as owner, ispopulated
from pg_matviews
order by schema_name,
         view_name;
```

We should have a system check (or something more visible, when starting the app?) with either instructions for the admin to fix it (`refresh materialized view …` SQL command), or a button/CLI that does it.

### Motivation

People regularly ask why they are getting non-populated view errors, like in https://github.com/mastodon/mastodon/issues/29531

**Comment by ClearlyClaire** [comment]
Note that since https://github.com/mastodon/mastodon/pull/28111, refreshing a materialized view will populate it instead of erroring out if it was not materialized, so the issue should fix itself on its own with time.
