### ISSUE TITLE
Allow more context for report notes

### ISSUE THREAD

**Issue by cd24** [mastodon/mastodon#29540]
### Pitch

Either, remove the character limit on moderator notes in report -or- allow attaching files with supplemental information in the report.

### Motivation

Sometimes it's useful to be able to attach long-form content to moderation reports. For example, e-mail communications with other admins. Often, these types of communications are long and won't fit the 500 character limit. This can make tracking relevant documentation harder, and recovering context for appeals more difficult.

**Comment by varjmes** [comment]
Thanks for suggesting this, I was coming here to do the same!

Whilst I know it's hard to define a specific limit for what one should allow for any piece of content, and `500` was likely chosen for a reason, I'm finding myself hampered as an Admin. Report appeals have a limit of [2000 characters](https://github.com/mastodon/mastodon/blob/d39d6255613b146a8a68d0873afa8180fba8dfc7/app/models/appeal.rb#L29) as do [account notes](https://github.com/mastodon/mastodon/blob/d39d6255613b146a8a68d0873afa8180fba8dfc7/app/models/account_note.rb#L21).

So a person appealing a ban can write a lengthy essay, and I can write an essay not associated to a specific report, but when writing a note about a specific and current incident I am respond to I have to write in an external app and then eyeball it to separate it into what I hope looks like 500 characters. My estimations are frequently wrong so it's a lot of enter, fail, rechunk, enter, fail. It's very useful to be able to tie commentary to a specific report.

I'd happily just make a PR to increase that number, for example, to `2000` to try and make it consistent with other reporting texts but I don't want to dive in without understanding if there is a reason for this number being so low.

_how it looks when trying to write up the resolution to a report_

<img height="300" src="https://github.com/mastodon/mastodon/assets/542140/f35a0061-d80e-4bd3-82ae-b2f20045a751" />


Totally irrelevant to the report interface but about another character limit, I notice the invite request character limit is a unique count of `420`. Is there a reason for this or could we bump it to a nice round `500` if for no other reason but to satisfy my (legitimate) OCD? :D

**Comment by ThisIsMissEm** [comment]
We've increased the character limit significantly recently, so in 4.3 you'll now have 2000 characters for report notes: https://github.com/mastodon/mastodon/pull/30288 — we can always increase that too if really necessary.

The original idea of report notes was to keep log of small-ish messages about the status of a report, and then you read through them all and that gives you the current status; kind of like comments on an outage incident or bug ticket; The primary goal was to allow for handing things over between moderators in different timezones.

To be honest, we probably need a lot more work in the UX department here, by actually doing user-studies with moderators and seeing how they use the tools provided.

**Comment by ThisIsMissEm** [comment]
@cd24 @varjmes given the character limit in 4.3 is now 2000 characters for report notes, would this be considered completed?

There's a separate feature that's been proposed in conversations for "Incident Reports" where you'd be able to do a write up and tie together a whole bunch of information into a well formatted report with a title and such, so you could link together multiple reports into an "incident"
