### ISSUE TITLE
Old Explore Icon in Advanced Interface

### ISSUE THREAD

**Issue by ocdtrekkie** [mastodon/mastodon#29561]
### Steps to reproduce the problem

Under "Getting Started", the old "# Explore" option is present in the column.

### Expected behaviour

The modern compass Explorer icon should be present.

### Actual behaviour

The hashtag icon is displayed next to Explore.

### Detailed description

When clicking on Explore, the new icon is used at the top of the Explore column, it just doesn't show on the Getting Started tab.

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-02-23

### Browser name and version

Firefox 123.0.1

### Operating system

Windows 11 22H2

**Comment by Pham1993** [comment]
Hi
