### ISSUE TITLE
(optionally?) Display edits as diffs 

### ISSUE THREAD

**Issue by caitp** [mastodon/mastodon#29655]
### Pitch

It can be hard to easily identify what changed in an edit. Edits may be in links which are not fully rendered in the UI, or in subtle character differences in long text posts. a diff view would be very helpful.

While a desktop client can easily copy different versions into a web based diff such as diffchecker.com, or into a command line app -- ideally the server and client should handle this too, or at least make it easy. On my instance, on Safari, I can't even highlight the text and would have to screenshot and use OCR, which is potentially a vulnerability wrt character swaps

### Motivation

See above

**Comment by trwnh** [comment]
Duplicate of #20783
