### ISSUE TITLE
Notification message padding

### ISSUE THREAD

**Issue by nclm** [mastodon/mastodon#29697]
### Steps to reproduce the problem

1. Deny notifications 
2. Open the notification menu
3. Look at the message “Desktop notifications are unavailable due to previously denied browser permissions request”

### Expected behaviour

The message should look well integrated in the menu

### Actual behaviour

The message looks non-integrated in the menu, at least because of missing padding

### Detailed description

<img width="623" alt="Screenshot 2024-03-21 at 16 10 10" src="https://github.com/mastodon/mastodon/assets/923008/f6ae3b2e-1134-486d-934a-929a6bdd9e59">

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-03-19

### Browser name and version

n/a

### Operating system

n/a

**Comment by ClearlyClaire** [comment]
Fixed by https://github.com/mastodon/mastodon/pull/29658

**Comment by mcclure** [comment]
I don't think this is fixed

![image](https://github.com/user-attachments/assets/41736ba8-4ced-4232-a1d9-bcf8103675cc)

**Comment by ClearlyClaire** [comment]
Oops, there are two messages, only one of the two has been fixed.
