### ISSUE TITLE
[webinterface] Make role-specific styling possible again

### ISSUE THREAD

**Issue by Sirs0ri** [mastodon/mastodon#29703]
### Pitch

User roles (e.g. "Admin", or custom roles) have a color attribute ([docs](https://docs.joinmastodon.org/entities/Role/#color)) and pre-4.2.0 that color was used to theme the role badge on an account's profile.

With the 4.2.0 release, these badges were redesigned ([original PR here](https://github.com/mastodon/mastodon/pull/26281)) and the redesign removed not only the coloring itself, but also any way of identifying different badges through CSS selectors.

The roles previously got a CSS class based on their ID, I'd like to propose to expose a role's ID as a `data-role-id` attribute to the frontend again.

### Motivation

We'd like to add custom styling for different roles on our instance, to highlight Moderators or supporters, through custom CSS. However, at the moment there's no simple way of knowing which role(s) the current user has.

**Comment by renchap** [comment]
Good idea, submitted a PR to add a `data-account-role-id` attribute on the badges.
