### ISSUE TITLE
Lookup doesn't work "Record not found" on external non Mastodon ActivityPub server

### ISSUE THREAD

**Issue by arobase-che** [mastodon/mastodon#29709]
### Steps to reproduce the problem

1. Setup a ActivityPub server and add a user.
2. Go to your mastodon instance et try to access the user profile page from here. 
3. The mastodon mammoth gets upset on his keyboard with a 404 error code.

In the dev console, you can see that the lookup resquest yeld:
 
```json
{
    "error": "Record not found"
}
```

I'm sorry if it's because I don't understand the basics of how ActivityPub works internally.  
Looks like a bug to me but I also have nowhere to ask for help.

### Expected behaviour

The user information should be accessible in the Web UI.

### Actual behaviour

404, with angry mammoth

### Detailed description

I'm trying to setup an ActivityPub server compatible with Mastodon.
The server is up and running but Mastodon doesn't check any information and return 404.

I would except it to _do a WebFinger first_, them get the information of the user and finally display the information in the Web interface.

### Mastodon instance

mastodon.xyz

### Mastodon version

v4.2.7

### Technical details

The ActivityPub I'm trying to reach is setup by me at https://re7.ache.one (a recipe website in french).

3 endpoints are accessible:

1.  The webfinger one: https://re7.ache.one/.well-known/webfinger?resource=acct:ache@re7.ache.one
     It adverts the user "ache" with that json:
      ```json
      {
          "aliases": [
              "https://re7.ache.one/recettes/"
          ],
          "links": [
              {
                  "href": "https://re7.ache.one/recettes",
                  "rel": "http://webfinger.net/rel/profile-page",
                  "type": "text/html"
              },
              {
                  "href": "https://re7.ache.one/users/ache",
                  "rel": "self",
                  "type": "application/activity+json"
              }
          ],
          "subject": "acct:ache@re7.ache.one"
      }
      ```
2. The `users` endpoint with all the information about the user. (https://re7.ache.one/users/ache).
3. The `inbox` endpoint not used here.

When I access https://mastodon.xyz/@ache@re7.ache.one the lookup in the dev console returns `"Record not found"` but **no webfinger has been made**.
I don't see any log in the ActivityPub server.

The [lookup documentation](https://docs.joinmastodon.org/methods/accounts/#lookup) say that it skips the WebFinger resolution but I don't understand why should it skip that resolution. Wasn't the goal of the lookup to make the WebFinger resolution ?

I may have miss something in how ActivityPub works but I'm expecting the instance I'm logged in to make a webfinger, extract the information and to fill the information in the web ui.
From here, I should be able to see the user information the last recipes and I should be able to follow / block the user.

_________________

To debug that case, I setup a local dev mastodon instance. Setup everything but I can't even make it works with another mastodon account.

http://mastodon.local:3000/@ache@mastodon.xyz

It gives up on the same error "Record not found". In the local mastodon log I got:

```
05:00:23 web.1     | Started GET "/api/v1/accounts/lookup?acct=ache%40mastodon.xyz" for 10.0.2.2 at 2024-03-22 05:00:23 +0000
05:00:23 web.1     | Cache read: blocked_ips ({:compress=>true, :compress_threshold=>1024})
05:00:23 web.1     | Cache generate: blocked_ips ({:compress=>true, :compress_threshold=>1024})
05:00:23 web.1     |   IpBlock Pluck (0.1ms)  SELECT "ip_blocks"."ip" FROM "ip_blocks" WHERE "ip_blocks"."severity" = $1  [["severity", 9999]]
05:00:23 web.1     |   ↳ app/models/ip_block.rb:39:in `block in blocked?'
05:00:23 web.1     | Cache write: blocked_ips ({:compress=>true, :compress_threshold=>1024})
05:00:23 web.1     | Cache write: rack::attack:5703612:throttle_unauthenticated_api:10.0.2.2 ({:compress=>true, :compress_threshold=>1024, :expires_in=>278})
05:00:23 web.1     | Processing by Api::V1::Accounts::LookupController#show as */*
05:00:23 web.1     |   Parameters: {"acct"=>"ache@mastodon.xyz"}
05:00:23 web.1     |   DomainBlock Load (3.3ms)  SELECT "domain_blocks".* FROM "domain_blocks" WHERE "domain_blocks"."domain" IN ($1, $2) ORDER BY CHAR_LENGTH(domain) DESC LIMIT $3  [["domain", "mastodon.xyz"], ["domain", "xyz"], ["LIMIT", 1]]
05:00:23 web.1     |   ↳ app/models/domain_block.rb:73:in `rule_for'
05:00:23 web.1     |   Account Load (0.2ms)  SELECT "accounts"."id", "accounts"."username", "accounts"."domain", "accounts"."private_key", "accounts"."public_key", "accounts"."created_at", "accounts"."updated_at", "accounts"."note", "accounts"."display_name", "accounts"."uri", "accounts"."url", "accounts"."avatar_file_name", "accounts"."avatar_content_type", "accounts"."avatar_file_size", "accounts"."avatar_updated_at", "accounts"."header_file_name", "accounts"."header_content_type", "accounts"."header_file_size", "accounts"."header_updated_at", "accounts"."avatar_remote_url", "accounts"."locked", "accounts"."header_remote_url", "accounts"."last_webfingered_at", "accounts"."inbox_url", "accounts"."outbox_url", "accounts"."shared_inbox_url", "accounts"."followers_url", "accounts"."protocol", "accounts"."memorial", "accounts"."moved_to_account_id", "accounts"."featured_collection_url", "accounts"."fields", "accounts"."actor_type", "accounts"."discoverable", "accounts"."also_known_as", "accounts"."silenced_at", "accounts"."suspended_at", "accounts"."hide_collections", "accounts"."avatar_storage_schema_version", "accounts"."header_storage_schema_version", "accounts"."devices_url", "accounts"."suspension_origin", "accounts"."sensitized_at", "accounts"."trendable", "accounts"."reviewed_at", "accounts"."requested_review_at", "accounts"."indexable" FROM "accounts" WHERE LOWER("accounts"."username") != '' AND LOWER("accounts"."username") = 'ache' AND LOWER("accounts"."domain") = 'mastodon.xyz' ORDER BY "accounts"."id" ASC LIMIT $1  [["LIMIT", 1]]
05:00:23 web.1     |   ↳ app/models/concerns/account/finder_concern.rb:41:in `account'
05:00:23 web.1     | Completed 404 Not Found in 56ms (Views: 2.2ms | ActiveRecord: 3.5ms | Allocations: 3153)
```

On the lock up of 'http://mastodon.local:3000/api/v1/accounts/lookup?acct=ache%40mastodon.xyz'.

The mastodon.local instance is launch with the command `sudo vagrant ssh -c "cd /vagrant && foreman start"`  
I guess the sudo wasn't necessary.

Thank you for any help

**Comment by Gargron** [comment]
The goal of the lookup API method is to faciliate converting a username to an internal account ID. To assign an internal account ID in the first place, the account needs to be resolved. This either happens automatically when the server processes an activity from or involving the given account, or it can be done manually using the search API with `resolve` param set to `true`.

**Comment by arobase-che** [comment]
Thank you very much ! 

@trwnh: It works ! 

@Gargron: Ok. Turn out I understood the concept of ActivityPub but not how Mastodon works.  
I took me too much time to understand that.

Using a resolve (actually just typing the name in the search bar) and fixing the content-type header fix my issue.
I will send a patch to the activityPub server software.
