### ISSUE TITLE
Add "accept all" / "deny all" options to Filtered Notifications column

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#29721]
### Pitch

The new "Filtered Notifications" column (mastodon.social v4.3.0-nightly.2024-03-19)

![image](https://github.com/tuskyapp/Tusky/assets/277318/3326c07e-ae2b-4eca-be8d-97b2dcd07356)

Should have two buttons, probably in a drop down menu like the "gear" other columns have. These two buttons should say "Accept all" and "Deny all" and do what they say.

### Motivation

I have a mild case of RSI which becomes significant if I do many repetitive actions over a short time. A computer task which requires me to click many times in a row can cause this to flare up.

If I were to use notification filters, "accept all"/"deny all" options would help me in two distinct situations:

* **Everything is great.** Either I received many contacts on a viral "toot" overnight, or I left my account unattended for a while and got a lot of traffic in the meantime.
* **Everything is terrible.** Someone is harassing me, and to do so they created many sockpuppet accounts.

In both these cases, I could have so many items in the "Filtered Notifications" column that clicking the accept/dismiss buttons for each one [would become a burden](https://github.com/mastodon/mastodon/issues/29723). With "Accept all" / "Deny all" options, I could pick out the handful of good notifications (in the first case) or the handful of dubious notifications (in the second case) and bulk accept/deny the rest.

**Comment by ClearlyClaire** [comment]
I'm a little worried about accidentally dismissing legitimate requests lost in a sea of malicious ones. I suppose only discarding requests that have been loaded (and thus possibly inspected, even if just cursorily) and having a confirmation modal would work.

**Comment by ClearlyClaire** [comment]
Fixed by #31309
