### ISSUE TITLE
Website doesn't work anymore with QtWebEngine

### ISSUE THREAD

**Issue by chusopr** [mastodon/mastodon#29724]
### Steps to reproduce the problem

1. Install any qtwebengine-based browser (e.g., [Falkon](https://www.falkon.org/), [Otter](https://otter-browser.org/), [Angelfish](https://apps.kde.org/gl/angelfish/))
2. Access any page under mastodon.social
3. Get a blank page.

### Expected behaviour

See mastodon.social website

### Actual behaviour

Getting an empty page.

### Detailed description

I noticed a few days ago that I was getting a blank page in mastodon.social with Falkon. Using private browser didn't make a difference. Other browsers like Firefox or Google Chrome still worked.

Today I noticed Angelfish and Fiery were not able to display the site either. I was also able to reproduce the issue with Otter.

What all these browsers have in common is that all use Qt WebEngine.

I tested different devices with different builds of Qt WebEngine and even different architectures with always the same result.

I haven't changed my Qt WebEngine version, so I guess it's some change introduced in mastodon.social recently.

Other WebKit-based browsers that don't use Qt's implementation still work (e.g., [Epiphany](https://wiki.gnome.org/Apps/Web), which uses WebKitGTK).

The same thing happens with mastodon.online.

Other instances using v4.2.8 are not affected.

Falkon:

![falkon](https://github.com/mastodon/mastodon/assets/3270352/5e3b3314-825a-4e7f-b786-917bbc1593f3)

Angelfish:

![angelfish](https://github.com/mastodon/mastodon/assets/3270352/058abdae-ab99-4a6b-bb31-2d4de6a7ac75)

Fiery:

![fiery](https://github.com/mastodon/mastodon/assets/3270352/5d153e7f-69ea-4ad6-9bd9-b3efe44ddf8a)

Otter:

![otter](https://github.com/mastodon/mastodon/assets/3270352/c315e04e-6904-48d5-802e-071f6bcb1033)

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-03-19

### Browser name and version

Falkon 23.08.5

### Operating system

Gentoo Linux

### Technical details

I can see these errors in the browser console, I don't know if they are relevant:

```
The source list for Content Security Policy directive 'script-src' contains an invalid source: ''wasm-unsafe-eval''. It will be ignored.
```
```
Uncaught TypeError: Object.hasOwn is not a function
    at y (emoji_utils.js:138)
    at v (emoji_utils.js:121)
    at Object.<anonymous> (emoji_mart_search_light.js:28)
    at s (bootstrap:84)
    at Object.<anonymous> (common-18891181d013c23e0faa.js:2)
    at s (bootstrap:84)
    at Object.<anonymous> (store.js:1)
    at s (bootstrap:84)
    at Module.1266 (application-ff75040d736bae231bbb.chunk.js:1)
    at s (bootstrap:84)
y @ emoji_utils.js:138
v @ emoji_utils.js:121
(anonymous) @ emoji_mart_search_light.js:28
s @ bootstrap:84
(anonymous) @ common-18891181d013c23e0faa.js:2
s @ bootstrap:84
(anonymous) @ store.js:1
s @ bootstrap:84
1266 @ application-ff75040d736bae231bbb.chunk.js:1
s @ bootstrap:84
n @ bootstrap:45
t @ bootstrap:32
(anonymous) @ application-ff75040d736bae231bbb.chunk.js:1
```
```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' https://mastodon.social 'nonce-W4BXAPTNcPWSC5MfJLOfbw=='". Either the 'unsafe-inline' keyword, a hash ('sha256-ARQRP2j3BghXhSFmA9TRDuJFA4SddOm78a2XhD4cfrE='), or a nonce ('nonce-...') is required to enable inline execution.

(anonymous) @ VM9:1
(anonymous) @ VM9:1
```

**Comment by ClearlyClaire** [comment]
Should be fixed by https://github.com/mastodon/mastodon/pull/29654 (deployed on mastodon.online but not mastodon.social yet)

**Comment by chusopr** [comment]
Indeed, mastodon.online now seems to works for me.
I hope this fix won't be required anymore with Qt WebEngine 6, but unfortunately my distribution hasn't stabilized Plasma 6 yet.
