### ISSUE TITLE
`/api/v1/reports` requires integer rule ID, but rule IDs are strings that may not be numbers

### ISSUE THREAD

**Issue by daprice** [mastodon/mastodon#29753]
### Steps to reproduce the problem

1. Call `/api/v1/instance/rules` to get instance rules.
2. Report a rule violation using `/api/v1/reports` which requires a rule ID.

### Expected behaviour

`/instance/rules` should return IDs in a format that is guaranteed to be accepted by `/reports`

### Actual behaviour

`/instance/rules` returns IDs as strings ("not guaranteed to be a number” according to docs), but `/reports` requires integer IDs

### Detailed description

As an app developer, I thought I was supposed to [always treat IDs provided by Mastodon as strings](https://docs.joinmastodon.org/api/guidelines/#id). The docs for [`Rule`](https://docs.joinmastodon.org/entities/Rule/) state this as well. But [`/api/v1/reports`](https://docs.joinmastodon.org/methods/reports/#post) requires the rule ID as an integer, even though the rules API does not guarantee that the rule IDs *are* integers.

In practice with mastodon.social, this doesn’t appear to cause any problems, as the rule IDs there are parseable as integers, but it seems like an oversight that could lead to rules not being reportable and may cause interoperability issues for client apps that also support non-Mastodon instances.

### Mastodon instance

any

### Mastodon version

v4.0.0 and up

**Comment by ThisIsMissEm** [comment]
@daprice I believe this is a documentation issue, as from what I can tell, passing a string will be converted to the integer rule ID automatically.

I don't think there's explicitly anything broken here, unless you've found a situation where this definitely throws an error?

**Comment by daprice** [comment]
If `/reports` is intended to accept the IDs back as strings, then yes, it’s just a documentation issue.

**Comment by daprice** [comment]
ah, there’s already a PR to fix it: mastodon/documentation#1467

**Comment by noxxi17** [comment]
Look I don't know who you are or what you want but if you don't stop the aliens from tainting our planet we will all be doomed! P.s. I need a date, either of you two wanna skip rocks and burn fatties down by the bay? We can catch crabs and boil them? Come on,if this is all you've got to do, message me 5157099228 I look forward to hearing from you.
