### ISSUE TITLE
Text color on filter selection screen is illegible

### ISSUE THREAD

**Issue by vmstan** [mastodon/mastodon#29782]
### Steps to reproduce the problem

1. From web interface, use dark mode
2. Open post view, click on … menu
3. Select “filter this post”
4. Observe text in white color on nearly white modal

### Expected behaviour

Text can be read

### Actual behaviour

Text cannot be read

### Detailed description

![IMG_2349](https://github.com/mastodon/mastodon/assets/3002053/e047ed4e-6e48-4ce4-9244-64df1ea5d4fd)

### Mastodon instance

vmst.io

### Mastodon version

v4.3.0-alpha.3

### Browser name and version

Safari

### Operating system

macOS

### Technical details

Observed in multiple browsers and on mastodon.online

Shows correctly on 4.2.8 instances.

**Comment by vmstan** [comment]
Reported by @maikelthedev

**Comment by vmstan** [comment]
Fixed by #31349

cc @maikelthedev

**Comment by maikelthedev** [comment]
It works thank you.
