### ISSUE TITLE
Breaking change should be in the release notes RAILS_SERVE_STATIC_FILES

### ISSUE THREAD

**Issue by jucajuca** [mastodon/mastodon#29798]
### Steps to reproduce the problem

After updating to the version 4.2.8 my static files stopped working.

This was caused by a change tin the configuration that was not documented.

RAILS_SERVE_STATIC_FILES used to be "enabled"
now it should be "true".

https://github.com/mastodon/mastodon/blame/main/config/application.rb#L94

### Expected behaviour

static files should be served

### Actual behaviour

static files serving is not working

### Mastodon instance

toot.gemeinschaffen.com/

### Mastodon version

v4.2.8

### Browser name and version

firefox

### Operating system

linux 20.04

**Comment by renchap** [comment]
This comes from https://github.com/mastodon/mastodon/commit/f0e727f958cd9428b2c56a3c6a65bbbf176bfa0d

Before, any value was valid, now it only checks for `true`

**Comment by mjankowski** [comment]
Seems accurate now in docs - https://github.com/mastodon/documentation/blob/main/content/en/admin/config.md?plain=1#L204-L206 - not sure on full change history.
