### ISSUE TITLE
Web interface: Display full handle (like before the design change) or give a easy way to copy the full handle

### ISSUE THREAD

**Issue by mborus** [mastodon/mastodon#29849]
### Pitch

On the profile page on the web interface, the user name used to be displayed in the format 

    @user@mastodon.social

making it easy to cut and paste the user name whenever I needed to pass on my handle.

This was **recently changed** to

    @user [mastadon.social] <- Box element

Now it's no longer possible to mark, **cut and paste** it.

There's a copy link button, but that copies the format

    https://mastodon.social/@user
    
So now, when I have to enter my handle, I need to open a text editor and change this to the old format manually.    

### Motivation

The old way of displaying the full handle made it very easy to copy and share handles in email or situations, where you're asked to fill in the handle. The design change made sharing handles a hassle.

It would be helpful is the profile had one way to getting the handle to the clipboard, so you could paste it into other applications.

**Comment by ClearlyClaire** [comment]
There are two ways to copy the full handle:
- click the username, this will select the username in full, complete with the (hidden) domain part; then copy it
- click the box element, then click the handle, which will be selected in full, you can then copy it

**Comment by mborus** [comment]
Thanks, that solved it you my personal use. 

I'm closing it request then, but it's not expected behaviour, I wouldn't have found it without someone explaining how this works. 

Mayby I've been on the internet too long...
