### ISSUE TITLE
add "accessibility" as a label to existing issue

### ISSUE THREAD

**Issue by rzeta0** [mastodon/mastodon#29860]
### Pitch

I'd like to add "accessibility" as a label to feature request I previously raised

https://github.com/mastodon/mastodon/issues/29835

### Motivation

The suggestion, if implemented, will also fix an accessibility issue, as described in that issue:

https://github.com/mastodon/mastodon/issues/29835

**Comment by renchap** [comment]
Please do not open a new issue for asking about actions on other issues. You can ask in comments of the other issue.
