### ISSUE TITLE
Option to set media as sensitive is missing entirely from the compose form

### ISSUE THREAD

**Issue by letydoesstuff** [mastodon/mastodon#29882]
### Steps to reproduce the problem

1. Write a public post and upload any media
2. Attempt to set the media as sensitive, without setting a content warning, which used to be possible

### Expected behaviour

There should be an option to set just the media as sensitive without marking the entire post with a CW.

### Actual behaviour

There is no option to set the media as sensitive without marking the entire post with a CW.

### Detailed description

Basically just what's written above.

The problem likely originated in in mastodon/mastodon#28119, and mastodon/mastodon#29248 seems to imply this behavior was intentional, but it is not explicitly written anywhere.

Sorry if I'm raising another non-issue again, but I just do not agree with making this purposeful change without a dedicated PR or discussion about it anywhere. I feel there is significant difference between an entire post being marked with a content warning, and therefore being collapsed by default in user timelines, and just having the media marked as sensitive.

If this truly was intentional, I'd like to argue that there is cultural precedence against this, the most simple of which is that many news articles have censored imagery and media contained within their articles that you need to click to open, but the articles themselves are still displayed on the front pages of sites and papers.

Visual content can, should, and regularly is held to a different standard than textual content, and justly deserves separate display controls.

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-alpha.3+pr-29862-0540f75

### Browser name and version

Vivaldi 6.6.3271.57, but the problem is browser agnostic

### Operating system

Windows 11 Pro for Workstations 22631.3374, but the problem is OS agnostic

**Comment by Gargron** [comment]
Just leave the optional CW field empty. The media is marked as sensitive and the text is not collapsed.

**Comment by letydoesstuff** [comment]
Yes, that seems to work! So thank you very much for your time and response. I know this is coming across as nitpicky, but that caveat to the content warning system is less than entirely clear from the UI. Especially for those used to how the content warning flag is popularly used.
