### ISSUE TITLE
Admin user itself needs to be approved on fresh installed v4.2.8 instance

### ISSUE THREAD

**Issue by bobby365** [mastodon/mastodon#29880]
I tried using the workaround posted down below but I keep getting this error. ERROR: Missing RAILS_ENV environment variable, please set it to "production", "development", or "test". I just downloaded the latest version of Mastodon from the install docs

> This has been fixed by #29379 and a note has been added to the release notes about a workaround (using `tootctl modify <username> --approved`)

for my fresh installation it was:
`bin/tootctl accounts approve admin`

_Originally posted by @cavuugroup in https://github.com/mastodon/mastodon/issues/29380#issuecomment-1970936012_

**Comment by renchap** [comment]
You need to run

```
RAILS_ENV=production bin/tootctl accounts approve admin
```
