### ISSUE TITLE
Cant find Database Entries?

### ISSUE THREAD

**Issue by MConsuela** [mastodon/mastodon#29908]
### Steps to reproduce the problem

1. Deactivated the IP Address showing up by commenting out this lines in the NGINX

```
#proxy_set_header X-Real-IP $remote_addr;
#proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

2.   The IP of "some users" redirects to 127.0.0.1 now, but not for all
3.  i googled and found the database query to use to change the last ip as following

```
update users set last_sign_in_ip='127.0.0.1';
update users set current_sign_in_ip='127.0.0.1';
```
4. but this is what i get 
`ERROR:  column "last_sign_in_ip" of relation "users" does not exist`

so it seems this is a old column?  if so, does anyone have the right and updated one?`
...

### Expected behaviour

delete IPs

### Actual behaviour

keeping feww IPs and the code for the Database query does not work

### Mastodon version

v4.2.8

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by mjankowski** [comment]
What are you trying to do?

**Comment by MConsuela** [comment]
> What are you trying to do?

Delete the IP addresses which is needed for security, all current users show 127.0.0.1 as IP address but older registered users still show the real IP, so i need to flush the IP Addresses from the PostgreSql Database, just the commands are outdated.

**Comment by mjankowski** [comment]
Depending which IPs you want to remove, the relevant tables/columns are:

- login_activities.ip
- session_activations.ip
- users.sign_up_ip

**Comment by MConsuela** [comment]
Thanks, just when i do this

`update users set login_activities.ip='127.0.0.1';`

i now mysteriously get 

`ERROR:  relation "users" does not exist`
