### ISSUE TITLE
Notes no longer automatically refreshing to reflect changes

### ISSUE THREAD

**Issue by FediVideos** [mastodon/mastodon#29916]
### Steps to reproduce the problem

1. Write a note on an account profile
2. After seeing "note saved" message, leave profile
3. Navigate back to profile, the saved updates aren't visible. They have been saved, but you have to refresh the page to see the saved version. If you don't refresh, you just see the old version.
...

### Expected behaviour

When the feature was originally introduced, the notes automatically updated so that you saw the latest version straight away when you navigated back to the page.

### Actual behaviour

At some point one update removed the auto-refresh of notes, so that if you navigate back it shows the old version until you manually refresh the page.

### Detailed description

Because the notes no longer auto-refresh, it's really easy to think you've lost work, or accidentally overwrite a previous update.

The notes are being saved correctly, it's just the updated version isn't displayed without a manual page refresh.

This didn't happen a while ago, the original version of notes behaved correctly. At some point the automatic refreshing of notes content broke.

### Mastodon instance

social.growyourown.services

### Mastodon version

v4.2.8

### Browser name and version

Firefox 123.0.1

### Operating system

Ubuntu Linux

**Comment by renchap** [comment]
Might have been introduced by https://github.com/mastodon/mastodon/pull/26601

**Comment by renchap** [comment]
I am not able to reproduce this on the latest version (on mastodon.social), so I think this has been fixed.

I tested by:
- clicking on a profile
- add a note
- validate that the note is updated
- go back to home screen
- click again on the same profile
- the note still has the new value

**Comment by FediVideos** [comment]
The timeline sounds like it could have been that typescript change which is the culprit.

I set up a test account on mastodon.social and it does indeed seem to be fixed. If this is the case on the next release version I'll close the issue. Thanks for your help with this!

**Comment by adam-lab** [comment]
Tangentially, this feature (profile notes) does not seem to be documented.
https://docs.joinmastodon.org/user/network/#follow

Documentation will help users confirm that they have the correct expectations for the feature, and also answer weird ideas they might get like "is the note visible to the person whose profile it is on"

**Comment by FediVideos** [comment]
This has been fixed in 4.3.0 so closing, well done Masto devs! Brilliant! 🥳
