### ISSUE TITLE
Empty Statuses response

### ISSUE THREAD

**Issue by mtiessler** [mastodon/mastodon#29924]
### Steps to reproduce the problem

1. GET request to https://mastodon.social/api/v2/search?q=mastodon&limit=11

### Expected behaviour

Receive statuses

### Actual behaviour

    "statuses": []

### Detailed description

The request should return:
```
{
   "accounts": [...],
   "statuses": [...],
   "hastags": [...]
}
```
But it always returns
```
{
   "accounts": [...],
   "statuses": [ ],
   "hastags": [...]
}
```

**Comment by renchap** [comment]
Statuses search is only available for logged-in users.
