### ISSUE TITLE
Logged-out view is wider than screen, left edge cut off, can’t be scrolled

### ISSUE THREAD

**Issue by daprice** [mastodon/mastodon#29979]
### Steps to reproduce the problem

1. Visit a mastodon server while logged out.

### Expected behaviour

Landing page layout should be responsive and not go off the screen horizontally

### Actual behaviour

Landing page layout appears to be a fixed width wider than the screen, but can’t be scrolled horizontally. This appears to affect *all* logged out views including viewing a post, etc.

### Detailed description

This is what I see when I visit mastodon.social in Safari on an 11” iPad Pro. The left side of the page is off the edge of the screen and I can’t scroll it into view. Even if I manually zoom in/out, that part remains cut off as if there’s negative padding/margin on those elements. The right side of the page also appears to have less padding than it should.

![IMG_0975](https://github.com/mastodon/mastodon/assets/3615519/42f09faa-7f19-4b75-a3ef-1b9fcbd62033)

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-04-10

### Browser name and version

Safari (iPadOS 17.4.1)

### Operating system

iPadOS 17.4.1

### Technical details

Also affects desktop Safari if the window is narrower than the width of the page content. Can also reproduce in Firefox.

Mastodon servers running v4.2.8 don’t have this issue.

**Comment by Clarevh** [comment]
I also find this on my iPad (iPadOS 17.5.1, iPad Air 4th generation), sometimes also a cut off on the right but more noticeable on the left. 4.2.x is ok, 4.3.x isn’t.
![IMG_1044](https://github.com/user-attachments/assets/db0928c6-849e-4057-9de0-eda60634a542)

**Comment by daprice** [comment]
Looks like this was fixed(?) by #31889. I’m not sure that giving tablet users a hilariously wide version of the phone layout where you can see one post at a time was the *best* way to fix it, but it was certainly *a* way to fix it.

![IMG_ACDC79945185-1](https://github.com/user-attachments/assets/6f1fe061-a3ae-42df-905a-5b447349e4d3)
(the screenshot displayed on GitHub understates the absolute physical size of this article thumbnail. It’s as big as my hand)
