### ISSUE TITLE
Allow searching for hashtags in admin UI

### ISSUE THREAD

**Issue by renchap** [mastodon/mastodon#29986]
## Preliminary note

This issue is part of our "help wanted" issues. It represents something that we know we want to implement, and that is defined enough that a contributor can implement it in a way that it would get merged.

If you want to work on this, please add a comment saying so and ask any questions you need, then open a PR referencing this issue!

## Description

There is currently no way to see the details about a tag (ex: `/admin/tags/1`) that is not trending (except by looking up it's tag ID in the database).

A new "Moderation > Hashtags" page should be added to the admin panel, with a field to search for an hashtag (maybe using the existing auto-complete endpoint from the composer?).

Clicking on a hashtag (or typing its full name?) should open the tag detail page.

This would solve https://github.com/mastodon/mastodon/issues/23923

**Comment by ThisIsMissEm** [comment]
I'd be interested in working on this, provided I've financial backing (I'm a freelancer, so time is money)

**Comment by ThisIsMissEm** [comment]
@renchap would being able to preemptively "create" a hashtag before it's been used also be within the scope of work here?

**Comment by renchap** [comment]
> @renchap would being able to preemptively "create" a hashtag before it's been used also be within the scope of work here?

Let's say it would be an additional feature. We did not discuss this internally but I can see how this could be useful

> Same with splitting the "allow / disallow" usage of this hashtag into local and remote usage? e.g., #29264

Probably out of the scope as it has more impacts

**Comment by scottjenson** [comment]
**UX discussion of this feature**
From #29264 the key request is: 
"Please consider adding some way for me to quickly find a specific hashtag that isn't trending for me to disallow users from using the hashtag, disallowing it from trending, or disallowing it from appearing in searches and suggestions."

This implies there are TWO things that need to be added: 1) The ability to find a hashtag and 2) an ability to moderate it. #2 actually has a follow on requirement to a) show all moderated tags and b) be able to remove that moderation. 

#1 implies the ability to search, see a list of matching hashtags and selecting one. That is likely a "Search:" field with a popup of found items that populates as you type. Selecting one from the popup moves it to a "banned" section below the search box (Maybe better label?).

I'm assuming there is no other action other than banning? If there is, the UX becomes more complex. Assuming it is just banning, then selecting the hashtag from the search results places it in a list below. Everything in the list is banned. Selecting anything from that list allows a "Remove from list" button below that list to remove on it. This list needs to scroll and should likely be alphabetized. Bonus points for Shift-select to grab a range of hashtags with an "are you sure?" confirmation (as I assume this action won't be able to be undone).

**Comment by ThisIsMissEm** [comment]
There's actually a few potential actions:
- preventing usage of a hashtag (local)
- preventing usage of a hashtag (remote) - not currently implemented but see #29264 
- preventing the trending of a hashtag
- preventing searching of a hashtag (not sure if this is implemented)
- adding content warning to hashtag (not implemented)

**Comment by scottjenson** [comment]
That's helpful, thank you. I have to ask, is that level of granularity necessary? i.e. would you prevent local usage but ALLOW trending? I'm only asking as having it be "available" or "blocked from everything" might be enough for 99% of most use cases. It would be helpful if some admins could chime in with their needs. If all/nothing is too strong, maybe it would be better to have 2-3 mutually exclusive levels. That prevents there being 2^5 possible states for each hashtag which feels a bit overkill.

**Comment by ThisIsMissEm** [comment]
Well, one implies the other, if you prevent all usage, then that implies it won't ever trend; if you only prevent remote usage, it could still trend & be used locally, if you only block trending then it's still usable.

**Comment by p37307** [comment]
It may seem like overkill, but if a feature is going to be added, it probably is best to iron out all possible use cases and implement. 

I can see an instance setup for a special purpose, like legal, art, medical, etc, that may not want local usage of a hashtag but don't have a problem with its users finding out that something is trending. 

I like the ability to be able to preemptively "create" a hashtag. 

Maybe this is off topic, I don't know if it is mentioned, or not anywhere, but it would be great if it would respect case, esp if a tag is being created via Mastodon. Some apps aren't respecting the case of letters in hashtags. I know there is a couple fields in the database and why, maybe it is a technical reason, the display as and the actual field that holds the name, is different. Searching for a tag, and editing it, should be case-insensitive, though.

**Comment by scottjenson** [comment]
@p37307 It usually is overkill. The whole point of UX design is to give you the functionality you actually need, not 2^5 combinations that can actually problems, i.e. you can imagine some nonsensical pairings. "throwing it in to be safe" is almost never safe and often creates more problems than it solves.

This can easily spiral into a huge discussion, and I don't think we are the intended users. I'm just trying to avoid clutter, extra programming work, and a UX that creates impossible combinations that can cause trouble.

It would help if actual admins chime in so we have some feedback from the people that are going to be using this.

**Comment by p37307** [comment]
@scottjenson, I am talking as an admin and not as a user. Currently, I export popular hashtags from the database to create an offline directory just to get the tag ID number so I can go into the UI (url instance/admin/tags/tagID and edit tags directly that have fallen out of the current moderation UI. 

With the tag table fields being, "id, name, created_at, updated_at, usable, trendable, listable, reviewed_at, requested_review_at, last_status_at, max_score, max_score_at, display_name", it would be great if the name and display name respected each other.

**Comment by ShadowJonathan** [comment]
My usecase is to simply find a damn hashtag.

If a user tells me "This <obscure hashtag> is in the wrong casing, could you fix it?", then I cannot even find the hashtag, since its buried in the 178th page on the "trending" pages.

Just have a way to find the hashtags, or even just to put the name in the URL path so I (a technically savvy admin) can find it without much hassle.

**Comment by ThisIsMissEm** [comment]
@scottjenson I should probably clarify that the "moderation of a hashtag" already exists. This page has existed for ages, but the problem was that to get to it, you needed to know the internal database assigned ID of the hashtag, making it next to impossible to access.

<img width="1257" alt="Screenshot 2024-06-30 at 23 24 41" src="https://github.com/mastodon/mastodon/assets/30827/a42f56e9-8286-4eaf-acaa-60c5a3288e08">

All this change does is give a UI to find a hashtag by name and then link to that page. Here's what I've ended up implementing for now for that:

<img width="1243" alt="Screenshot 2024-06-30 at 23 14 47" src="https://github.com/mastodon/mastodon/assets/30827/0ced7bff-2532-44f9-9b27-e033c0e00c6f">

**Comment by scottjenson** [comment]
All I can do is speak from a UX point of view and what you've proposed feels reasonable in scope:
1. It's only a search function
2. It points to an existing page (and apparently doesn't change this page in any way)

My UX comments would be:

- What is the purpose of the RESET button? If it just clears the search results, that feels unnecessary. 
- The Search field is very wide. Having a much smaller text input and the SEARCH button to the right would feel much calmer
- Having the filters above the query area separates them from the results. I'd suggest having the Staus/Order popups underneath the Search box to tie things together visually.
- Does clicking on a link take me to an entire different panel? If so, how do I get back to these results? The BACK button?

If you'd like, I'm happy to mock something up. I just wanted to get your feedback first.

**Comment by ThisIsMissEm** [comment]
@scottjenson this design is inline with the design used on all other admin pages. Sure we could do a complete UX overhaul of the admin pages, but that's completely out of scope for now

The search is a GET request, so you can just use the browser back button; but if you look at the PR you'll note I've also included a back link in the tag details page.

**Comment by ThisIsMissEm** [comment]
@scottjenson if you'd like to better understand the admin tools you're welcome to request an account on https://sandbox.mastodon.iftas.org

**Comment by scottjenson** [comment]
I certainly don't want to ask for a style that is different from existing panels.  I didn't realize that. The majority of my comments were more about the top to bottom ordering. Those issues aren't critical, just a nice to have.

**Comment by renchap** [comment]
Done in #30880
