### ISSUE TITLE
Allow admins to configure instance favicon and logo

### ISSUE THREAD

**Issue by renchap** [mastodon/mastodon#29987]
## Preliminary note

This issue is part of our "help wanted" issues. It represents something that we know we want to implement, and that is defined enough that a contributor can implement it in a way that it would get merged.

If you want to work on this, please add a comment saying so and ask any questions you need, then open a PR referencing this issue!

## Description

At the moment, admins can not change the logo or favicon for their instance, as those are statically generated by the `branding:generate_app_icons` rake task.

We would like an admin to be able to go to "Administration > Server settings > Appearance", select an app icon and a base favicon (SVG files, feel free to add support for PNG maybe?), have the backend process them similar to what the rake task currently does, and store those files into the media storage.

If those files exist, then they should be used by the application.

This would solve https://github.com/mastodon/mastodon/issues/7396

## Implementation notes

It may be needed to store a server setting for this, so there is a way to know that these icons have been installed (and maybe store their path in the setting?).

This may be similar to how the Mascot is currently implemented.

Those icons are used in `app/views/layouts/application.html.haml` and `app/serializers/manifest_serializer.rb`.

They should probably be moved to a helper and not be directly embedded in those files as the code will become a bit more complex.

It might be a good occasion to review the header and manifest to ensure that every icon recommended nowadays is here.

**Comment by FawazFarid** [comment]
Looking to pick this up 👍🏼
