### ISSUE TITLE
Link preview fails to decode UTF-8.

### ISSUE THREAD

**Issue by dhoepfl** [mastodon/mastodon#29996]
### Steps to reproduce the problem

See [this post](https://norden.social/@SheDrivesMobility/112297639947321017).

The link preview says “LÃ¼neburg Aktuell · Apr 8” instead of “Lüneburg Aktuell · Apr 8”.

### Expected behaviour

Incorrect encoding in one tag should not break others.

### Actual behaviour

See above: “LÃ¼neburg” instead of “Lüneburg”.

### Detailed description

I suspect the incorrectly truncated UTF-8 sequence at the end of the og:description tag triggers this error: `<meta property="og:description" content="Aufruf gegen den Landesparteitag der AfD Niedersachsen am 20. April in Unterlüß     Gemeinsam gegen rechts – für eine vielfältige Gesellschaft!     Die niedersächsische AfD h�...">`

### Mastodon instance

layer8.space, and on original page on norden.social

### Mastodon version

v4.2.8

### Browser name and version

Firefox 125.0.1

### Operating system

Windows 10

**Comment by PuercoPop** [comment]
Reading the code, each tag is processed independently 

https://github.com/mastodon/mastodon/blob/35b517c207a5a5b24d5ac67ed9ad98943dcc3d7f/app/lib/link_details_extractor.rb#L182-L184

I checked the spec file and there is no data using utf8. Trying to reproduce locally would involve updating the spec https://github.com/mastodon/mastodon/blob/35b517c207a5a5b24d5ac67ed9ad98943dcc3d7f/spec/lib/link_details_extractor_spec.rb#L210

**Comment by mjankowski** [comment]
Was this fixed in 4.3?

If I modify that spec to use `"Lüneburg Aktuell"` as the value, I do see it correctly extracted using current code. Also possible I'm not fully replicating/understanding here.

**Comment by PuercoPop** [comment]
@mjankowski Yes, it seems to have been fixed by https://github.com/mastodon/mastodon/pull/30780
