### ISSUE TITLE
web dashboard (mine) not loading (bug or browser incompatibility): https://social.mindplex.ai/getting-started. 

### ISSUE THREAD

**Issue by colleenpridemore** [mastodon/mastodon#30038]
### Steps to reproduce the problem

1. go to https://social.mindplex.ai/getting-started using chrome Version 123.0.6312.124 (Official Build) (64-bit)
2.
3.
...

### Expected behaviour

dashboard should load

### Actual behaviour

error page is ciisplayed

### Mastodon instance

mastatdon.social

### Mastodon version

v4.1,1

### Browser name and version

chrome Version 123.0.6312.124 (Official Build) (64-bit)

### Operating system

Win  11

**Comment by renchap** [comment]
This instance seems to be based on a modified Mastodon code, and I could not find the source for it (which is a licence violation). This should probably be reported to the website owner.
