### ISSUE TITLE
The 'Publish' button should provide some feedback

### ISSUE THREAD

**Issue by joachim-n** [mastodon/mastodon#30054]
### Steps to reproduce the problem

1. Go to the home page, e.g. https://drupal.community/home
2. Write a post and click 'Publish'

### Expected behaviour

Some sort of feedback that my post has worked, and a way to see it

### Actual behaviour

Nothing

### Detailed description

There's no feedback that a post has been successful, and there's no way to find it to look at it.

### Mastodon instance

drupal.community

### Mastodon version

v4.1.15

### Browser name and version

Firefox 105.0.3

### Operating system

Mac 13.4.1

**Comment by renchap** [comment]
I think this is fixed in `main` as we reworked the composer, and there is now a toast notification when you post.
