### ISSUE TITLE
Error: `422 can't verify CSRF token authenticity` on explore page

### ISSUE THREAD

**Issue by da5nsy** [mastodon/mastodon#30066]
### Steps to reproduce the problem

1. Visit typo.social/explore
2. Scroll down
3. See error:

![Screenshot_20240425-110837](https://github.com/mastodon/mastodon/assets/3739866/282a3222-78ea-424b-af98-9fc3ec97bbe4)

On desktop (Windows, Firefox) no error is produced, but scrolling stops at the same point, suggesting to me that the error occurs but is not communicated.

### Expected behaviour

No error

### Actual behaviour

Error (and then no additional posts will load)

### Detailed description

Also reported here:
- https://www.reddit.com/r/Mastodon/comments/18fmda5/422_cant_verify_csrf_token_authenticity/?rdt=43597
- https://mementomori.social/@rolle/110802929745486086
- Possible duplicate of https://github.com/mastodon/mastodon/issues/1236 (I can't tell)

### Mastodon instance

typo.social

### Mastodon version

v4.2.8

### Browser name and version

Firefox on Android, 124.2.0 (Build #2016012559), 7a0e399c7b+ GV: 124.0.2-20240401114208 AS: 124.0 2024-04-01T17:18:00.821594648

### Operating system

Android 13

**Comment by ClearlyClaire** [comment]
I am unable to reproduce this issue.

**Comment by da5nsy** [comment]
I am currently able to reproduce reliably. Are there any logs or additional info I could provide?

**Comment by ClearlyClaire** [comment]
If you are able to get your browser's network log (which is more work on mobile), I would be interested in knowing which request fails with a 422 error.

**Comment by da5nsy** [comment]
You were correct - that did indeed take some work haha

![image](https://github.com/mastodon/mastodon/assets/3739866/eece0f5e-f01d-4182-a85a-d0637762ff6e)

## Response headers
```
HTTP/2 422 
date: Fri, 03 May 2024 10:05:17 GMT
content-type: application/json; charset=utf-8
access-control-allow-origin: *
access-control-allow-methods: POST, PUT, DELETE, GET, PATCH, OPTIONS
access-control-expose-headers: Link, X-RateLimit-Reset, X-RateLimit-Limit, X-RateLimit-Remaining, X-Request-Id
access-control-max-age: 7200
server: Mastodon
x-frame-options: DENY
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: same-origin
x-ratelimit-limit: 300
x-ratelimit-remaining: 298
x-ratelimit-reset: 2024-05-03T10:10:00.861004Z
cache-control: private, no-store
content-security-policy: default-src 'none'; frame-ancestors 'none'; form-action 'none'
x-request-id: af3d3c4d-49f7-4f9f-ac2f-eb41e77f7b48
x-runtime: 0.004334
strict-transport-security: max-age=63072000; includeSubDomains
vary: Authorization, Origin
X-Firefox-Spdy: h2
```

## Request headers
```
PUT /api/web/settings HTTP/2
Host: typo.social
User-Agent: Mozilla/5.0 (Android 13; Mobile; rv:125.0) Gecko/125.0 Firefox/125.0
Accept: application/json, text/plain, */*
Accept-Language: en-GB
Accept-Encoding: gzip, deflate, br
Referer: https://typo.social/explore
Content-Type: application/json
Content-Length: 1308
Origin: https://typo.social
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
TE: trailers
```

---

Notes to future self: to do this:
- install adb by installing android studio
- Add adb to path
- Follow [these](https://firefox-source-docs.mozilla.org/devtools-user/about_colon_debugging/index.html#setup-tab) instructions to connect
- Click on network
- _(Don't try to use HTTP Toolkit - it looks like a cool tool but struggles with third party apps, e.g. Firefox if device is not rooted)_

**Comment by ClearlyClaire** [comment]
I still can't reproduce the issue nor find a code path that would trigger an attempt to save settings. Can you reliably reproduce this? If so, are you doing anything unusual? Do you perhaps use a browser extension that would interact with Mastodon?

**Comment by da5nsy** [comment]
> Can you reliably reproduce this?

Yes.

> If so, are you doing anything unusual?

I don't think so. I had the "uBlock Origin" add-on enabled, but disabling it doesn't change the behaviour.

Curiously, if I open a private browsing tab, and go to the same site I get a different but similar behaviour. Now the list shows the same posts (currently stopping after only 2 posts) but _doesn't_ then deliver the error code. 

![image](https://github.com/mastodon/mastodon/assets/3739866/36420c1a-7c86-4bdd-8048-beda3f01ccea)
![image](https://github.com/mastodon/mastodon/assets/3739866/da2a71e3-6c4c-43cf-b96e-ce0eee1f5516)

**Comment by ClearlyClaire** [comment]
There being only two trending posts is not indicative of any error. There being only two trending posts is expected for a small server with little activity.

The only error is the 422 error, which is caused by an attempt to save settings for a logged-out user. However, I currently don't understand what could have triggered it.

**Comment by da5nsy** [comment]
I'm happy to clear my cache to see if that resolves it, but if that does resolve it then I assume that removes the possibility of us working out what the underlying issue is? 

I tried logging out of any other logged in mastodon servers (there were 2) but that didn't change anything.

**Comment by ClearlyClaire** [comment]
So every time you visit https://typo.social/explore while logged out on your browser on Android, you get the 422 error? I wonder if the debugger could help us get some info there. Try opening the debugger and going to “Breakpoints” → “XHR Breakpoints” and add a breakpoint on `/api/web/settings`, but I'm afraid the stack trace will be unreadable because of the javascript minimization.

**Comment by da5nsy** [comment]
> So every time you visit https://typo.social/explore while logged out on your browser on Android, you get the 422 error?

Correct.

> Try opening the debugger and going to “Breakpoints” → “XHR Breakpoints” and add a breakpoint on /api/web/settings

<img width="960" alt="Screenshot_20240507_170507" src="https://github.com/mastodon/mastodon/assets/3739866/cfaa6e7e-1567-4401-8e4c-c2bada1f41ab">

Ping me a message

**Comment by ClearlyClaire** [comment]
The stack trace doesn't go below the `settings.js:29`? hm… if you can, try to set a breakpoint on `settings.js:35` and try again…

**Comment by da5nsy** [comment]
> The stack trace doesn't go below the settings.js:29?

I'm not quite sure what I'm looking at but I think the answer is no. 
I've uncollapsed the bits below but I suspect that's not what you mean.

![image](https://github.com/mastodon/mastodon/assets/3739866/b35b2a3c-a0cb-4aa6-97da-3f7ee93d465f)
![image](https://github.com/mastodon/mastodon/assets/3739866/aaaa821c-10ea-4244-8398-555256dd0d7d)

> set a breakpoint on settings.js:35 and try again…

If I did it right, and I've interpreted it right, it didn't hit that breakpoint:

![image](https://github.com/mastodon/mastodon/assets/3739866/bc164d68-1924-42bc-a466-03b8b577e361)

**Comment by ClearlyClaire** [comment]
Thanks! That's super helpful! I think the culprit is `dismissable_banner.tsx:45` :eyes:

Basically, when you dismiss the “These are posts from across the social web that are gaining traction today. Newer posts with more boosts and favorites are ranked higher.” banner, this is saved in your browser's `localStorage`… and the server-side settings! Except those do not exist for logged-out users.

Since you've dismissed the banner, and that state has been correctly saved into your `localStorage`, visiting the page again will attempt to synchronize the server-side settings with your `localStorage` value, except trying to do that will fail because you are not logged in, hence the 422.

**Comment by da5nsy** [comment]
Very cool! Thanks for the explanation! 🎉

**Comment by da5nsy** [comment]
@ClearlyClaire - Just a little note of thanks - this process has been really cool! 
I've learnt some things and felt like I helped (a tiny tiny little bit) to improve a piece of software that I use daily and have a lot of love for! 🎉 
Thank you!

**Comment by OutOfThisPlanet** [comment]
Thought I might chip in...

I am on 4.2.10 (docker), and I still get this same  error message when logged out. 
Everything works fine when logged in.

Could there also be an issue with my reverse proxy setup?

**Comment by ClearlyClaire** [comment]
No, this is a bug in 4.2.x, it's fixed in the development version but not in any release yet.

**Comment by Heretical-I** [comment]
The only time I ever see this "error" is when I'm using Torbrowser, and it seems to have no effect on my 'user experience'... operation in the browser. It appears erratically on my page at kafenio.social (advanced interface) when using torbrowser but never see it using Firefox.
