### ISSUE TITLE
Web interface options for boosted/favorited posts expanded to turn off these notifications (currently only for email notifications)

### ISSUE THREAD

**Issue by ashrama** [mastodon/mastodon#30129]
### Pitch

Currently the Mastodon web interface options only allow turning off email notifications for boosts and favorites. Expanding this functionality to be able to disable these notifications from your notifications feed would also be desirable particularly for those with a lot of interaction or disabled folk like myself who find it difficult to engage when having to scroll through numerous boost and favorite notifications to see replies or other engagement.

### Motivation

It would benefit everyone that does not wish to see boost or favorited notifications in their feed, but particularly those with disabilities where these notifications detract from more engaging interactions.

**Comment by renchap** [comment]
We are working on notifications grouping, which should alleviate this issue as boost and like notifications will now be grouped for the same status.

**Comment by ashrama** [comment]
Excellent, but I think it would still be great to be able to disable them entirely if desired.

**Comment by renchap** [comment]
In fact, you can already do it. In the web interface, go to the Notifications tab, then click on the notification settings, and you have a panel to choose if you want to display them.

<img width="613" alt="image" src="https://github.com/mastodon/mastodon/assets/42070/34f4636a-2186-4918-a4f7-cca1597f070e">

**Comment by ashrama** [comment]
That interface looks completely different to the web interface I see.  Which version is that on?  My server is running 4.2.8 and has the following:
![Mastodon notification options 4 2 8](https://github.com/mastodon/mastodon/assets/13570210/afe9d35a-961d-4cdb-908c-2a58256a8c70)

**Comment by renchap** [comment]
This is not the same panel. You can access the notifications settings by clicking "notifications" in the main app menu, then the settings icon.

<img width="1176" alt="image" src="https://github.com/mastodon/mastodon/assets/42070/c1006602-b369-4af5-9247-f5cf6d69b7df">

We know this is unclear and will work on improving this.

**Comment by ashrama** [comment]
Ahhh, I see.  This does indeed address my problem.  Thank you.  The confusion on my part in your first image was due to me using the advanced view which lays things out a little differently.
