### ISSUE TITLE
Sort order on Pending Trending Hashtag moderation page inconsistant

### ISSUE THREAD

**Issue by snail-coupe** [mastodon/mastodon#30135]
### Steps to reproduce the problem

1. Goto the "pending review" page for trending hashtags (admin/trends/tags?status=pending_review) when there are multiple tags awaiting approval 
2. observe what hashtags are on the first page
3. Hit Ctrl+R or your favourite page reload process.
4. observe a completely different set of hashtags.

### Expected behaviour

The hashtags for review will always appear in a consistent order

### Actual behaviour

The sort order appears random, this is exacerbated when there are multiple pages 

### Detailed description

I think the above covers it well.  The reason this is a specific issue is I have ~800 tags to review and my intended process was to start at the end, allow all the ones I liked on the last page, then I could disallow anything remaining on the last page.  However since the contents of the page keep changing it means I can't know which tags on the page I have already discounted and haveto review them all again.

### Mastodon instance

mstdn.crmbl.uk

### Mastodon version

v4.2.8

### Browser name and version

Vivaldi 6.7.3329.21 (Stable channel) (64-bit) 

### Operating system

Windows 11

**Comment by ThisIsMissEm** [comment]
I believe this would be the required fix, however, in my local development environment, I don't have any data to test this with: https://github.com/mastodon/mastodon/pull/31473
