### ISSUE TITLE
Appeal interface should display post content when an appeal is opened for review 

### ISSUE THREAD

**Issue by cd24** [mastodon/mastodon#30142]
### Pitch

Any content (post, media, or accounts) that is made inaccessible through moderation action should sill be accessible to moderators when an appeal is reviewed. Similarly, if the moderator intervention is overturned then the content should be restored; which is not possible if it's been purged from the system.

When intervening with reports, there should be an option to "deny appeal" which would have today's behavior of (near) immediate deletion. However, this should require opt-in so that any appeal can be fully actioned. 

### Motivation

While there are definitely compliance cases where media should be immediately purged, offending content should generally be accessible for appeal. The moderation team at SFBA requires that a different moderator than the intervening one reviews any appeal. Not having the context for the posts makes this checked workflow much more difficult; since the content is often deleted before the appeal is filed or reviewed. 

This aggressive deletion pattern makes auditing and reviewing moderation interventions near impossible at times. 

![486-622-max](https://github.com/mastodon/mastodon/assets/6901054/39c77e6b-1538-450c-8fb3-5060fda9b0e1)

**Comment by MadokVaur** [comment]
Interestingly, every single one of those deleted posts were mine (as many as I checked, which was most)

I went on SFBA and deleted them and anything similar before even responding to the two Warnings I'd received

In every case, I was criticizing Gargron and the German / US non-profit status tempest-in-a-tea-pot that blew up several days ago

In every case, I quoted Gargron directly and provided links back into the Mastodon blog entry I was citing.

"Providing receipts" as the kids say

All that said, the triggering event was when I replied to a Famous Mastodon Personality(tm) who took great exception to my temerity in not swallowing what he said wholesale

After I received two Warnings and when I finally clicked "Appeal" (after deleting all the relevant posts and more) I replied to the Appeal

"No appeal. I can see that our boy Gargron is a protected class. So noted."

I then exported my Follows and my Lists and merged those at a previous instance where I had a dormant account

Executive summary: I'm gone, and you won't need to trouble yourself with my unpopular opinions any further.

**Comment by ClearlyClaire** [comment]
There are two issues at hand:
1. posts being deleted from the database before the appeal gets reviewed: currently, reported posts are supposed to be kept in the database for this purpose for up to 30 days
2. it being impossible to undo post deletion: unfortunately, the way we currently treat post deletion on the federated level does not allow us to restore existing posts, as it clashes with our mechanism to prevent replaying signed post creation for posts that were already deleted

If that report was indeed against @MadokVaur's posts and I understand the timeline of the actions correctly, the deletions would be far more recent than 30 days old, so they should have been kept in the database. I'll try to figure out what happened, but any additional detail would be helpful.

**Comment by MadokVaur** [comment]
> If that report was indeed against @MadokVaur's posts and I understand the timeline of the actions correctly, the deletions would be far more recent than 30 days old, so they should have been kept in the database. I'll try to figure out what happened, but any additional detail would be helpful.

I will continue with this to say only that, yes, those posts absolutely were mine

Here's a link from the Warning email:

https://sfba.social/web/@FinchHaven/112345951464412983

**Comment by ClearlyClaire** [comment]
So, just to make sure I got the timeline of events correct:
1. You got a moderation warning quoting your posts
2. You proceeded to delete those posts
3. You appealed the warning
4. Neither you nor mods can see the posts in the appeal

All of these happened in the past week or so.

**Comment by MadokVaur** [comment]
I received the Warning emails (two, actually) on April 28, 2024

I went to the posts listed in the Warnings and deleted them

I deleted other potentially-offensive posts in my Bookmarks as a safeguard -- I'd been down this road before on a previous instance with (in my opinion) arbitrary and ill-defined moderation applied selectively

After I'd deleted numerous posts I clicked through the Appeal link

I did not *make* any appeal sensing it would be a lost cause; I replied *to* the appeal, see my first post

EOF

**Comment by ClearlyClaire** [comment]
I think I understand what is happening: posts are preserved if there are *open reports* about them.
https://github.com/mastodon/mastodon/blob/9e260014c72fa83740d70d2d603e836f86e64b55/app/services/remove_status_service.rb#L156
https://github.com/mastodon/mastodon/blob/9e260014c72fa83740d70d2d603e836f86e64b55/app/models/status.rb#L268-L270

In this case, the report was closed (by issuing a warning) when the posts were deleted. We probably also want to check if there is a relevant warning that may be appealed.

**Comment by cd24** [comment]
> Thank you. I'll let @cd24 confirm that we are talking about the same report/appeal, and in the meantime I'll try figuring out what may have gone wrong.

Yes, I believe those are the same posts - though the problem would be more general than just warnings. 

IMO anything that can be appealed should be able to show all the relevant content for the appeal (even if the post is deleted or the account was suspended). We wouldn't want to keep content forever, but a 'review period' where moderated content is retained until appeal would be ideal (with escape hatches for content that has legal requirements to be removed immediately). Then I expect the content would be retained until reviewed. 

This would make it immensely easier for other mods to review activity!

Bonus points if the mastodon UI can tell the user this period has elapsed if they exceed it when filing an appeal.
