### ISSUE TITLE
Links with # turn into tags

### ISSUE THREAD

**Issue by madeindex** [mastodon/mastodon#30182]
### Steps to reproduce the problem

When you make a post on Mastodon and include a link with a # in it e.g. https://...org/#example
the post will have the # example under it.
See this post for a live example:
https://mastodon.social/@madeindex/112388235443765052
Other social media platforms have this issue also, some of them even do not display the link at all.

### Expected behaviour

No hashtag under the post

### Actual behaviour

A hashtag under the post

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0

### Browser name and version

/

### Operating system

/

**Comment by ClearlyClaire** [comment]
Thank you for your report! We already fixed a similar issue in #27584, but I can reproduce it with your example. This seems to be caused by the last character before the hash not being an ASCII character. I'll investigate!

**Comment by madeindex** [comment]
> Thank you for your report! We already fixed a similar issue in #27584, but I can reproduce it with your example. This seems to be caused by the last character before the hash not being an ASCII character. I'll investigate!

Thank you for the fast reply and work on this wonderful project :)
Wow looks like you fixed it even faster!
Nestlé always up to no good, even by Wikipedia spelling it's name correctly ;)
