### ISSUE TITLE
Docker overlays are large due to node_module cache and other finds

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#30253]
### Steps to reproduce the problem

Use ncdu to check folder sizes..
![image](https://github.com/mastodon/mastodon/assets/17537000/2085a6e7-af98-469a-9fbb-7035b7dc8da7)

* node_modules/.cache/@renchap/compression-webpack-plugin 
* node_modules/.cache/terser-webpack-plugin

![image](https://github.com/mastodon/mastodon/assets/17537000/fe9fa763-888e-43e6-8f82-869be8a14e29)

### Expected behaviour

Less node cache?

### Actual behaviour

Bloated filesystems

### Mastodon instance

aus.social

### Mastodon version

v4.2.8

### Technical details

Stock docker

**Comment by renchap** [comment]
The Docker image has been completely reworked in `main`. Closing as I think this is no longer relevant.
