### ISSUE TITLE
#30040 Introduced a lot of database queries to initial page loads

### ISSUE THREAD

**Issue by JasonPunyon** [mastodon/mastodon#30250]
### Steps to reproduce the problem

You can reproduce this problem by loading the /home page.

### Expected behaviour

Fewer round trips to the database

### Actual behaviour

Too many round trips to the database

### Detailed description

#30040 adds the ability for admins to configure favicons. An effect of that PR is now every time the `application.html.haml` layout is run (on things like initial loads of /home) a series of queries are sent to the database...

![image](https://github.com/mastodon/mastodon/assets/157782/03b447a0-2497-4bb0-bd4a-9bc6f92817ff)

All these queries are repeatedly going for one of two rows, the `favicon` row or the `app_icon` row.

These queries originate from the `site_icon_path` calls in the loops here.

https://github.com/mastodon/mastodon/blob/d09b02efb653e59488cac530db8ae2757ad0cd02/app/views/layouts/application.html.haml#L14-L20

I don't know what the right number of queries is (I could see two, I could see zero) but this feels like too much.

### Mastodon instance

Local development

### Mastodon version

v4.3.0-alpha.3

**Comment by ClearlyClaire** [comment]
Thanks for your report! The code indeed lacks the caching that is performed in e.g. `InstancePresenter`. It may make sense to move it to `InstancePresenter` with caching similar to the other `SiteUpload` objects.

**Comment by renchap** [comment]
Fixed by #30259
