### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by nferrari** [mastodon/mastodon#30294]
### Steps to reproduce the problem

1. Create a new application under Development settings section on the web interface, with default scopes (read/write/follow)
2. Keep access token from this application
3. Follow [official documentation](https://docs.joinmastodon.org/methods/statuses/#create) to post a new status through API

### Expected behaviour

Status should be posted

### Actual behaviour

Error "The access token is invalid"

### Detailed description

Following theses steps, I managed to post twice, but then got this error.
I even tried to regenerate access token (from web interface), or even to [obtain a new token from API](https://docs.joinmastodon.org/methods/oauth/#token) (with appropriate `write` scope).

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-05-13

**Comment by ThisIsMissEm** [comment]
Do you have example code or additional information that could help us triage this issue?

**Comment by nferrari** [comment]
Thank you for your answer I just found my PEBCAK.

**Comment by ThisIsMissEm** [comment]
> Thank you for your answer I just found my PEBCAK.

@n0toose I'm curious what your PEBCAK was though?

**Comment by nferrari** [comment]
Sure! See my bad Python fstring placement (applicable on the header key instead of value):

```python
# Post on Mastodon
mastodon_url = 'https://mastodon.social/api/v1/statuses'
mastodon_headers = {f'Authorization': 'Bearer {settings.MASTODON_TOKEN}'}
r = requests.post(mastodon_url, headers=mastodon_headers, data={"status": social_message})
```

**Comment by ThisIsMissEm** [comment]
Aha, okay!

**Comment by n0toose** [comment]
> @n0toose I'm curious what your PEBCAK was though?

I presume that I have been confused with @nferrari and that I'm not somehow involved here?

**Comment by ThisIsMissEm** [comment]
Sorry, yes, my bad!
