### ISSUE TITLE
Ambiguity of Terms and Privacy Policy translations

### ISSUE THREAD

**Issue by akihikodaki** [mastodon/mastodon#3032]
Translations of formal documents such as terms and privacy policy often include a notice that the original is in enforcement and the translation is just for reference.

For example, the FSF, providing AGPL-3.0, the license applied for this project, says:
> The FSF does not approve license translations as officially valid. The reason is that checking them would be difficult and expensive (needing the help of bilingual lawyers in other countries). Even worse, if an error did slip through, the results could be disastrous for the whole free software community. As long as the translations are unofficial, they can't do any legal harm.

https://www.gnu.org/licenses/translations.html

Additionally we should also consider that contributors of translations for such documents are volunteers; they are not obligated to keep the translations up-to-date and translations could deviate from the original.

Concerning the above, I suggest those translations should have:
* a notice that translations are just for a reference or that the original takes precedence over translations in case they are conflicting with each other
* a notice that translations may not be up-to-date

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Perhaps we should not translate those at all... Or allow them to be configured entirely in site settings. There was a PR that tried to do this, but it got stuck halfway because the author didn't address the issues I pointed out.

**Comment by akihikodaki** [comment]
> Perhaps we should not translate those at all...

I still believe they helps people much to understand it. Especially, many Japanese people are simply unable to read English texts.

> Or allow them to be configured entirely in site settings.

That would be good if it also allows to have translations. For example, pixiv, the Japanese company owning Pawoo instance, has its own privacy policy and similar texts both in English and in Japanese. They, and possibly other companies, are likely to want translating feature.

It is unlikely to eliminate the need of the default terms and privacy policy and its translations. I guess many instances are using the default one.

> There was a PR that tried to do this, but it got stuck halfway because the author didn't address the issues I pointed out.

Here I mention the PR for convenience to refer to: #2603

**Comment by Gargron** [comment]
But how do we implement translations with user (admin) input?

**Comment by akihikodaki** [comment]
We would need a new table, or just refer to files provided by the administrator as the CSS does.

**Comment by trwnh** [comment]
obsoleted by #19310 so this issue can probably be closed
