### ISSUE TITLE
Notifications are big in screen size & data volume  - Collapse them instead

### ISSUE THREAD

**Issue by madeindex** [mastodon/mastodon#30328]
### Pitch

Hello,
Notifications about boosts, favorites... of a post on Mastodon can be huge in vertical screen size & probably also create unnecessary data volume. Especially when a post was long & you get several boosts / favorites, it can quickly become hard to keep an overview.

Some [other users on Mastodon](https://mastodon.social/@madeindex/112440950761510684) and in the 2 suggestion threads below agree that notifications are too big. Some users even go as far as using extension to try and improve this themselves.

Suggestion: If notifications were collapsed to only show a summary or the date and could be expanded / loaded with a click, that would create a much better user experience in my opinion.

This is an example:
![Screenshot_mastodon_notifications_size](https://github.com/mastodon/mastodon/assets/166755288/68d75e25-bbce-4506-91d4-c851c352074f)

Another option, to only hide or thumbnail the media has been suggested by:
https://github.com/mastodon/mastodon/issues/27067
https://github.com/mastodon/mastodon/issues/29488

### Motivation

Users & the environment would benefit

**Comment by renchap** [comment]
This will be changed soon with the introduction of the grouped notifications in the UI.

**Comment by joric3** [comment]
> This will be changed soon with the introduction of the grouped notifications in the UI.

Oh, thanks, that's something I'm really looking forward to.

**Comment by madeindex** [comment]
With the recent notification update - this suggestion can be marked as **solved**, _thank you everyone_!!! :)

**Comment by shaedrich** [comment]
Thank you for implementing this feature! In most cases, this looks amazing! 👍🏻 

However, there's one particular case: Every now and then, posts only really start at the second line. The first line then only contains auto-filled at-mentions and such, so no helpful information.\
Therefore, I wonder if the number of lines shown could be increased by default or made configurable. Another option would be to collapse the line breaks in that preview—what do you think?
![image_2024-08-29_09-40-24](https://github.com/user-attachments/assets/0c41493a-7b18-4f52-acd7-f1ce7d0cab6b)

**Comment by madeindex** [comment]
> Thank you for implementing this feature! In most cases, this looks amazing! 👍🏻
> 
> However, there's one particular case: Every now and then, posts only really start at the second line. The first line then only contains auto-filled at-mentions and such, so no helpful information. Therefore, I wonder if the number of lines shown could be increased by default or made configurable. Another option would be to collapse the line breaks in that preview—what do you think? 
Sounds good - I think you need to open a new issue or suggestion though, as this one was closed.

**Comment by madeindex** [comment]
> Thanks for the hint 👍🏻 I copied it to #31618 for now.

& you instantly got a reply - amazing :)

**Comment by shaedrich** [comment]
Yep, thanks for the hint—very efficient :)

I ended up, adding my suggestions to #31668 where they fit better.
