### ISSUE TITLE
Tracking issue RE: Paperclip, Azure EOL, rest client, etc

### ISSUE THREAD

**Issue by mjankowski** [mastodon/mastodon#30352]
### Background

- For file attachment on various DB models throughout the app, Mastodon relies on paperclip
- With the introduction of Rails activestorage solution, the original paperclip gem was [deprecated in 2018](https://thoughtbot.com/blog/closing-the-trombone)
- There is a [kt-paperclip](https://rubygems.org/gems/kt-paperclip) fork that is more or less maintained, and which Mastodon now uses instead of paperclip
- We support various storage backends, including Azure
- For azure specifically, we rely on [md-paperclip-azure](https://github.com/mistydemeo/paperclip-azure) which is itself a fork of the orignal paperclip-azure gem (not updated in ~5 years) and provides an interface between paperclip and the official azure gem.

### Issues

- The situation where we are using a fork of an unmaintained adapter (azure) to interface with a fork of an unmaintained gem (paperclip) feels a bit precarious, but the migration from paperclip to AS would be one of the more substantial code and data/storage migrations we've attempted both on dev side and on instance admin side.
- The [azure-storage-ruby](https://github.com/Azure/azure-storage-ruby) gem will be retired in Sep 2024, in favor of using the REST api directly.
- The azure-storage-common gem is our last remaining gem with a hard version lock to faraday 1.x, which prevents updating there.

**Comment by mjankowski** [comment]
Maybe relevant - https://github.com/rails/rails/issues/49983#issuecomment-2116426565 - someone is working on a replacement gem for azure/activestorage which sounds like it will implement just the subset of the Azure REST API that is needed by AS.

This might be good to either use directly or build a paperclip adapter on top of.

**Comment by JoeDupuis** [comment]
I would need to look at kt-paperclip after I am done with AS, I could look into making the gem work for paperclip too. I don't think it would be hard to support both 🤔 
I might need to find a more generic name for the gem though 😆

**Comment by JoeDupuis** [comment]
I renamed the Gem to `azure-blob-storage`. Nothing in it make it specific to Active Storage.

**Comment by renchap** [comment]
Link to `azure-blob-storage`: https://github.com/JoeDupuis/azure-blob-storage

**Comment by JoeDupuis** [comment]
After discussing it internally, I will be renaming it to `azure-blob` later tonight. It's too close to the existing gem name.
Sorry for the flip flop. 

It should make it easier to use too (shorter namespace).

**Comment by JoeDupuis** [comment]
Done, I've renamed the gem: 
https://github.com/JoeDupuis/azure-blob
https://rubygems.org/gems/azure-blob
