### ISSUE TITLE
No new data pulled since 2023

### ISSUE THREAD

**Issue by erazze** [mastodon/mastodon#30396]
### Steps to reproduce the problem

1. Logging in
2. Going to Home, Explore, Federated or Lists or
3. Going to members profiles

### Expected behaviour

New toots should be visible

### Actual behaviour

No new toots visible, streams staying on 17th Nov 2023

### Detailed description

I've left my server for a while on v4.0.2 and today I wanted to upgrade it to v4.1.15 (at least) what was successfully done.
But, all datas (postings, profiles, etc) are stuck on 17th Nov. 2023. There are no new updates since then, EXCEPT one single account is up to date and new toots come through. Just one.

I've noticed that sidekiq was wrong configured, because "-q default -q push -q pull -q ingress" within the ExecStart line were missing. Now, it looks like this:

`ExecStart=/home/mastodon/.rbenv/shims/bundle exec sidekiq -c 15 -q default -q push -q pull -q ingress -q mailers -q scheduler`

After changing the line, I did "systemctl daemon-reload" and "systemctl restart mastodon-sidekiq" without any errors.

Everything else works like expected, but no new data and I really don't know why. Is someone able to assist?
Thanks!

### Mastodon instance

razze.social

### Mastodon version

v4.1.15

### Technical details

- Ruby version: v3.0.4
- Node.js version: v16.20.2

**Comment by renchap** [comment]
Can you check your `mastodon-web` and `mastodon-sidekiq` logs and see if you have any errors there?

Also, if you access the Sidekiq Web dashboard (on `/sidekiq`), are there unprocessed jobs?

**Comment by erazze** [comment]
Hi, thanks for checking!

> Can you check your `mastodon-web` and `mastodon-sidekiq` logs and see if you have any errors there?

since the last starts ther are smilar warnings:
```
Mai 22 14:52:46 h2991960.stratoserver.net systemd[1]: Started mastodon-web.
Mai 22 16:04:37 h2991960.stratoserver.net systemd[1]: /etc/systemd/system/mastodon-web.service:17: Unknown key name 'ProcSubset' in section 'Service', ignoring.
Mai 22 16:04:37 h2991960.stratoserver.net systemd[1]: /etc/systemd/system/mastodon-web.service:18: Unknown key name 'ProtectProc' in section 'Service', ignoring.
Mai 22 16:21:11 h2991960.stratoserver.net systemd[1]: /etc/systemd/system/mastodon-web.service:17: Unknown key name 'ProcSubset' in section 'Service', ignoring.
Mai 22 16:21:11 h2991960.stratoserver.net systemd[1]: /etc/systemd/system/mastodon-web.service:18: Unknown key name 'ProtectProc' in section 'Service', ignoring.
Mai 22 18:02:04 h2991960.stratoserver.net systemd[1]: /etc/systemd/system/mastodon-web.service:17: Unknown key name 'ProcSubset' in section 'Service', ignoring.
Mai 22 18:02:04 h2991960.stratoserver.net systemd[1]: /etc/systemd/system/mastodon-web.service:18: Unknown key name 'ProtectProc' in section 'Service', ignoring.
```

```
Mai 22 16:21:16 h2991960.stratoserver.net systemd[1]: Started mastodon-sidekiq.
Mai 22 18:02:04 h2991960.stratoserver.net systemd[1]: /etc/systemd/system/mastodon-sidekiq.service:17: Unknown key name 'ProcSubset' in section 'Service', ignoring.
Mai 22 18:02:04 h2991960.stratoserver.net systemd[1]: /etc/systemd/system/mastodon-sidekiq.service:18: Unknown key name 'ProtectProc' in section 'Service', ignoring.
```

> Also, if you access the Sidekiq Web dashboard (on `/sidekiq`), are there unprocessed jobs?

No. All queues are empty, sidekiq is idle, After upgrading to 4.1.15 and adding -q push -q pull, it started working but it seems to be done. As you can see on the website, https://razze.social/home and https://razze.social/public verything stopped on 17. Nov 2023, without the @tagesschau@ard.social account for whatever reason. Do I have a way to find out, why this account is up to date and others are not?

**Comment by renchap** [comment]
Has your server been offline for a while?

You seem to be the only user on your server. Are you following accounts that recently posted?

**Comment by erazze** [comment]
> Has your server been offline for a while?

Yes, I lacked discipline for a while and during that time the SSL certificate also expired. But before I switch to a managed host, I want to try my own server at least once again.

> You seem to be the only user on your server. Are you following accounts that recently posted?

Yes, I did some checks on accounts I follow on their native instance websites. My data is not beeing updated, I dont receive their toots. On https://razze.social/home you can see zucker's last posting is on 17. Nov. 2023 (execpt a direct interaction with me, what was synced). But on chaos.social, their last post was 10h ago.
