### ISSUE TITLE
Having issues with image cache on modified URL preview image

### ISSUE THREAD

**Issue by iamdtms** [mastodon/mastodon#30417]
### Steps to reproduce the problem

1. Create a post with an URL image content
2. Update the preview image of the URL attached - on the page itself
3. Update the post itself
4. The preview image does not change

### Expected behaviour

the preview image updates

### Actual behaviour

no update happens, the previous image served

### Detailed description

The thread with mas.to admin can be see here:
https://elk.zone/mas.to/@trumpet/112497304757661973

### Mastodon instance

mas.to

### Mastodon version

v4.2.8

### Technical details

Probably a global thing

**Comment by vmstan** [comment]
Link previews are only regenerated after 14 days. There is no method to detect source changes without constantly checking the source every time the preview is requested which is computationally expensive for the instance but also leads to unnecessary traffic on the source (which is federated among tens of thousands of instances and already a source of complaints in itself.)
