### ISSUE TITLE
Due to a bug in your code or a  browser incompatibiltiy issue

### ISSUE THREAD

**Issue by colleenpridemore** [mastodon/mastodon#30420]
### Steps to reproduce the problem

1.I was signed into my account here: https://social.mindplex.ai/public/local
2.then I went to my feed at top center/left and hit HOME and one other place near there (sorry I can't remember what that very last action was, but I was hit with the following:
https://social.mindplex.ai/public/local -- And I'm sure that doesn't help, but I thought I'd attempt to make you aware of some kind of issue.  
3.
...

### Expected behaviour

should have just adjusted a preference in my account (I'm assuming, can't remember)

### Actual behaviour

I was taken to another page with the error message on it

### Mastodon instance

mastadon social

### Mastodon version

Mastodon v4.1.1

### Browser name and version

Chrome Version 125.0.6422.78 (Official Build) (64-bit)

### Operating system

Edition	Windows 10 Home Version	22H2 Installed on	‎5/‎23/‎2024 OS build	19045.3803 Experience	Windows Feature Experience Pack 1000.19053.1000.0

### Technical details

Hope some of this info will assist. I wish I could have been more specific, I just don't remember what that last action was, but I think it was some kind of preference top center/left near the link that says HOME.

**Comment by renchap** [comment]
Same as my previous reply to another of your issues: https://github.com/mastodon/mastodon/issues/30038#issuecomment-2079762742

> This instance seems to be based on a modified Mastodon code, and I could not find the source for it (which is a licence violation). This should probably be reported to the website owner.
