### ISSUE TITLE
`tootctl accounts migrate` not documented

### ISSUE THREAD

**Issue by ShadowJonathan** [mastodon/mastodon#30430]
[`tootctl accounts migrate`](https://github.com/mastodon/mastodon/blob/a5c808e9b033eeb605dcf6b36dc14ddb1127db7b/lib/mastodon/cli/accounts.rb#L530) exists in the code, but not in the [docs](https://docs.joinmastodon.org/admin/tootctl/#accounts)

**Comment by trwnh** [comment]
Please file this issue against https://github.com/mastodon/documentation -- thank you for pointing this out!

**Comment by ShadowJonathan** [comment]
Ah its mentioned in https://github.com/mastodon/documentation/issues/1211, ill close this
