### ISSUE TITLE
URL of "boosts" is "/reblogs"

### ISSUE THREAD

**Issue by madeindex** [mastodon/mastodon#30457]
### Steps to reproduce the problem

Noticed a small fragment from the begin of Mastodon, which might be difficult to change though.
When you press boosts on a post it redirects you to the URL with /reblogs.
If you decide to change it, that should probably be handled with care (proper seo/technical redirect for all old links).

Example screenshot:
https://mastodon.social/@madeindex/112507221410837587

Thank you for all your amazing work!
-MadeInDex

### Expected behaviour

/boosts

### Actual behaviour

/reblogs

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-05-17

### Browser name and version

/

### Operating system

/

**Comment by madeindex** [comment]
> Is there a UX issue or bug here ... or is it just irritating to have that word in the url?

I'm not sure if it's a UX issue or just a matter of preference. There aren't many options [when adding a new issue](https://github.com/mastodon/mastodon/issues/new/choose).

It seems that some terms have been renamed, but the URLs haven't been updated e.g.: "_/favourites_" for "_favorites_", and "_/public/local_" for "_Live feeds_".

-Your [MadeInDex](https://madeindex.org) **Author A** :)

**Comment by trwnh** [comment]
Updating the URLs to match the localization would be unnecessarily confusing. There should not be an expectation for the flavour text to match the route name...

Internally, they're called "reblogs": https://github.com/mastodon/mastodon/blob/30c2a6c01c9f001ecad9c4c3291931e8484f292a/app/models/status.rb#L66

**Comment by mjankowski** [comment]
Yeah, I'd agree w/ that assessment -- the favourites table is called favourites, reblogs are reblogs, etc. In the event we do some large internal rename/refactor, it would make sense to keep domain concepts and urls synced. Until then, perhaps contemplate these two objects:

- https://en.wikipedia.org/wiki/Buffalo_buffalo_Buffalo_buffalo_buffalo_buffalo_Buffalo_buffalo
- https://github.com/mastodon/mastodon/blob/v4.3.2/app/models/status.rb#L408-L410
