### ISSUE TITLE
When blocking a user, add a prompt to ask whether or not they should also be muted (and vice versa)

### ISSUE THREAD

**Issue by Yamakyu** [mastodon/mastodon#30469]
### Pitch

When blocking a user, add a window or a prompt to ask whether or the user should also be muted. This makes the process of blocking + muting a user quicker and smoother. It could be a simple checkbox, or an additional dialog.

Same when muting a user : ask whether said user should also be blocked.

### Motivation

More often than not, any user that I block I do because I want them to completely disappear from my network, and I want to disappear from theirs. Blocking a user prevent interaction, but doesn't prevent their post from being visible, and notably in search or explore/trending. Removing them from these feeds requires to also mute them. This is especially annoying for users on instances with questionable content.

This request is to make it easy and simple to both mute and block at the same time, if need be, while also letting the flexibility to only block or only mute.

**Comment by renchap** [comment]
You should not need to mute a user after blocking it. A block should have the same effects at a mute (plus additional effects due to being a block). If it does not, then this is a bug.

Could you please provide some reproduction steps so we can confirm it does not behave correctly?

**Comment by Yamakyu** [comment]
Thanks for getting in touch

Your comment makes me think this may be a client thing actually. I just double checked, and blocking a user on the main Mastodon web client does remove said user from search.
I usually do not use the main Mastodon web client, and instead alternate between a few others, depending on devices. This may be the problem.

I'm positive I have experienced blocked users appearing in search/trending multiple times in these clients. I suppose this issue may be closed, since I couldn't actually replicate it in the main web client.
