### ISSUE TITLE
Image file size needlessly increases

### ISSUE THREAD

**Issue by AndrewKvalheim** [mastodon/mastodon#30460]
### Steps to reproduce the problem

1. Post an image:
    - [sample-1-input.png](https://github.com/mastodon/mastodon/assets/1844746/22a8fe89-9d1a-4fe3-ab2b-c895b796e353) (27 kB)
    - [sample-2-input.jpg](https://github.com/mastodon/mastodon/assets/1844746/c9f18c09-0aea-49ae-b01d-96817d1c1695) (348 kB)
1. View the posted image in Mastodon.

### Expected behaviour

The output file size is less than or equal to the input file size.

### Actual behaviour

The output file size is greater than the input file size.

### Detailed description

Given the above sample images, Mastodon produces:

- [sample-1-output.png](https://github.com/mastodon/mastodon/assets/1844746/33bb9624-119e-471e-8119-d803fc24accf) (31 kB), 115% of the original size
- [sample-2-output.jpg](https://github.com/mastodon/mastodon/assets/1844746/08d851a0-91ce-4e4c-93f0-777fb6a35404) (419 kB), 121% of the original size

When Mastodon’s attempted resize results in a larger file, the original smaller file should simply be used instead.

### Mastodon instance

kvalhe.im

### Mastodon version

v4.2.8

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x86_64-linux]
- Node.js version: v20.11.1

**Comment by renchap** [comment]
This might be fixed by #30090

**Comment by vmstan** [comment]
It is, or at least in the testing of sample image 2 the resulting file is 161 KB.
