### ISSUE TITLE
In Memoriam accounts should not be allowed in follow recommendations

### ISSUE THREAD

**Issue by renchap** [mastodon/mastodon#30466]
### Steps to reproduce the problem

Reported on Discord, an user has memorialized accounts recommended to them in follow suggestions.

### Expected behaviour

They are not recommended

### Actual behaviour

They are recommended

### Mastodon instance

rivals.space

### Mastodon version

Latest nightly

### Browser name and version

-

### Operating system

-

**Comment by wheatear-dev** [comment]
Hi 👋 

I took a punt at fixing this, over at #31474 . 😌 

A few notes:
1. Testing requires a setup of both _infrastructure_ and _data_, which I quite happily lack 😅 
2. I am without the _pre-requisite_ permissions to run the workflow on GitHub actions.

**Comment by kernal053** [comment]
Hi @wheatear-dev, I myself was looking around this issue. Your code seems to fix account suggestion for all sources except for `FriendsOfFriendsSource`. I think we'll need to add check in source_query method too for memorialized accounts.

**Comment by wheatear-dev** [comment]
Hi @kernal053, thank you for this observation. I can shortly action your suggestion. 😌 

However - while we're talking - I have no desire to tread on the toes of other potential contributors. 😅 

Is there any way to share authorship on the PR (#31474)? 😆 

Seeing as I would never have noticed the `FriendsOfFriendsSource`, fair is fair. 😄 

Maybe if you committed this suggestion on top of [the feature branch](https://github.com/wheatear-dev/mastodon/tree/fixes/recommend-in-memoriam), and I pulled the changes? 🤔

**Comment by renchap** [comment]
Yes it has been fixed, thanks for pinging us, the PR was not properly linked to this issue and it did not autoclose.
