### ISSUE TITLE
Release 4.2.9 breaks our IP anonymization method

### ISSUE THREAD

**Issue by 0x46616c6b** [mastodon/mastodon#30501]
### Steps to reproduce the problem

1. Install Mastodon v4.2.9
2. Configure Reverse Proxy to send X-Forwarded-For "127.0.0.1" to upstream
3. Try to open your Mastodon installation

### Expected behaviour

It should work

### Actual behaviour

Access denied

### Detailed description

Since https://github.com/mastodon/mastodon/security/advisories/GHSA-c2r5-cfqr-c553 was fixed in 4.2.9 our approach to anonymize IP addresses is broken. In prior versions this worked and we don't want to store IP addresses in the database, also not for a short period of time (see undocumented option IP_RETENTION_PERIOD, https://docs.joinmastodon.org/admin/config/#ip_retention_period).

So after we rolled out 4.2.9 nobody was able to connect to our mastodon instance. We only see the following logs

```
 [f19d7133-c3ec-4740-888c-fc750661fa7c] ActionDispatch0:0:0:0:0:0:0:0RemoteIp0:0:0:0:0:0:0:0IpSpoofAttackError (IP spoofing attack?! client 0.0.0.0 is not a trusted proxy HTTP_CLIENT_IP=nil HTTP_X_FORWARDED_FOR="0.0.0.0"):
```

(we also anonymize IP addresses in logs)

What we do is to overwrite the `X-Forwarded-For` header in our reverse proxy to not send real IP adresses to mastodon.

### Mastodon instance

systemli.social

### Mastodon version

v4.2.9

### Technical details

We use the stock docker images from mastodon.

**Comment by tribela** [comment]
How about setting forwarded ip to `0.0.0.0` instead of `127.0.0.1`?
We have alt onion domain and set X-Forwarded-For as `0.0.0.0`

**Comment by smiba** [comment]
Doesn't this run into issues where a single abuser could make the instance unavailable to everyone by simply triggering rate limits? Various rate limits in mastodon are IP based as seen in https://github.com/mastodon/mastodon/blob/df9e26158d9787859b24bdc276af478abf05e1af/config/initializers/rack_attack.rb

I don't think 0.0.0.0 is excluded, which means that every user will count towards the same limit. I should note that even if it's excluded, it means that your instance effectively runs without rate limits.

If this is fine then continue on, but it's something to keep in mind

**Comment by 0x46616c6b** [comment]
> How about setting forwarded ip to `0.0.0.0` instead of `127.0.0.1`? We have alt onion domain and set X-Forwarded-For as `0.0.0.0` And still working fine.
> 
> I realised that I was considered that onion service could bypass api limit by setting it's ip to `127.0.0.1`

We tried to set the `X-Forwarded-For` header to `0.0.0.0` but this not worked for the streaming service. We saw constantly the error `TypeError: invalid range on address: 0.0.0.0/0`. We also changed the `TRUSTED_PROXY` setting to `0.0.0.0/0`.

**Comment by 0x46616c6b** [comment]
We solved the IP anonymization with setting `X-Forwarded-For` to our public IP address and also added this IP to `TRUSTED_PROXY` setting.
