### ISSUE TITLE
RSS: page not available in requested format

### ISSUE THREAD

**Issue by avidseeker** [mastodon/mastodon#30524]
### Steps to reproduce the problem

* https://fosstodon.org/@eff@mastodon.social.rss: returns "This page is not available in the requested format."
* https://mastodon.social/@eff.rss: works as expected

### Expected behaviour

@eff@mastodon.social.rss should work the same as @eff.rss

### Actual behaviour

@eff@mastodon.social.rss doesn't work.

**Comment by Gargron** [comment]
`https://mastodon.social/@eff.rss` is the correct URL for that account. How do you come across the other URL?

**Comment by avidseeker** [comment]
I didn't come across it. I expect other instances to mirror RSS feed just as they mirror regular Mastodon feed.

**Comment by Gargron** [comment]
I don't think this is something we want to do. Please use the canonical RSS feed instead.
