### ISSUE TITLE
mastodon-web and mastodon-sidekiq fail to start with permission denied on /home/mastodon/.rbenv/shims/bundle

### ISSUE THREAD

**Issue by mergedeyes** [mastodon/mastodon#30538]
### Steps to reproduce the problem

1. Installed the server like here: https://docs.joinmastodon.org/admin/install/
2. Added a few relays.
3. Added S3 Storage like described here: https://techbits.io/backblaze-b2-s3-storage-mastodon/
4. Restarted the server with "init 6"

### Expected behaviour

Start the mastodon-services

### Actual behaviour

mastodon-web.service and mastodon-sidekiq.service fail to start.

### Detailed description

Hello everyone,
today I installed Mastodon on my VPS.
After failing to install Mastodon for a few times, I finally succeeded.
I logged in, added a few relays and then added S3 object storage.
After restarting the entire VPS, mastodon-web.service and mastodon-sidekiq.service failed to start.
Below a are few logs and my configs. If you need any more information to help me, please let me know! Thanks!

systemctl status mastodon*:
> ● mastodon-streaming@4000.service - mastodon-streaming on port 4000
>      Loaded: loaded (/etc/systemd/system/mastodon-streaming@.service; disabled; preset: enabled)
>      Active: active (running) since Mon 2024-06-03 22:32:32 CEST; 34min ago
>    Main PID: 969 (node)
>       Tasks: 11 (limit: 11889)
>      Memory: 31.0M
>         CPU: 10.621s
>      CGroup: /system.slice/system-mastodon\x2dstreaming.slice/mastodon-streaming@4000.service
>              └─969 /usr/bin/node ./streaming
> 
> Jun 03 22:32:32 mastodon.XXX.de systemd[1]: Started mastodon-streaming@4000.service - mastodon-streaming on port 4000.
> Jun 03 22:32:33 mastodon.XXX.de node[969]: WARN Streaming API now listening on 127.0.0.1:4000
> 
> ● mastodon-streaming.service - mastodon-streaming
>      Loaded: loaded (/etc/systemd/system/mastodon-streaming.service; enabled; preset: enabled)
>      Active: active (exited) since Mon 2024-06-03 22:32:32 CEST; 34min ago
>     Process: 966 ExecStart=/bin/echo mastodon-streaming exists only to collectively start and stop mastodon-streaming@ instances, shimming over the migration to templated mastodon-streaming systemd unit (code=exited, status=0/SUCCESS)
>    Main PID: 966 (code=exited, status=0/SUCCESS)
>         CPU: 1ms
> 
> Jun 03 22:32:32 mastodon.XXX.de systemd[1]: Starting mastodon-streaming.service - mastodon-streaming...
> Jun 03 22:32:32 mastodon.XXX.de echo[966]: mastodon-streaming exists only to collectively start and stop mastodon-streaming@ instances, shimming over the migration to templated mastodon-streaming systemd unit
> Jun 03 22:32:32 mastodon.XXX.de systemd[1]: Finished mastodon-streaming.service - mastodon-streaming.
> 
> × mastodon-web.service - mastodon-web
>      Loaded: loaded (/etc/systemd/system/mastodon-web.service; enabled; preset: enabled)
>      Active: failed (Result: exit-code) since Mon 2024-06-03 22:39:44 CEST; 27min ago
>    Duration: 24ms
>     Process: 1105 ExecStart=/home/mastodon/.rbenv/shims/bundle exec puma -C config/puma.rb (code=exited, status=203/EXEC)
>    Main PID: 1105 (code=exited, status=203/EXEC)
>         CPU: 22ms
> 
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: mastodon-web.service: Scheduled restart job, restart counter is at 5.
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: Stopped mastodon-web.service - mastodon-web.
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: mastodon-web.service: Start request repeated too quickly.
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: mastodon-web.service: Failed with result 'exit-code'.
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: Failed to start mastodon-web.service - mastodon-web.
> 
> × mastodon-sidekiq.service - mastodon-sidekiq
>      Loaded: loaded (/etc/systemd/system/mastodon-sidekiq.service; enabled; preset: enabled)
>      Active: failed (Result: exit-code) since Mon 2024-06-03 22:32:34 CEST; 34min ago
>    Duration: 21ms
>     Process: 1013 ExecStart=/home/mastodon/.rbenv/shims/bundle exec sidekiq -c 25 (code=exited, status=203/EXEC)
>    Main PID: 1013 (code=exited, status=203/EXEC)
>         CPU: 18ms
> 
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Scheduled restart job, restart counter is at 5.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: Stopped mastodon-sidekiq.service - mastodon-sidekiq.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Start request repeated too quickly.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Failed with result 'exit-code'.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: Failed to start mastodon-sidekiq.service - mastodon-sidekiq.

**cat /home/mastodon/live/.env.production:**
> LOCAL_DOMAIN=mastodon.XXX.de
> SINGLE_USER_MODE=false
> SECRET_KEY_BASE=XXX
> OTP_SECRET=XXX
> VAPID_PRIVATE_KEY=XXX
> VAPID_PUBLIC_KEY=XXX
> DB_HOST=/var/run/postgresql
> DB_PORT=5432
> DB_NAME=mastodon_production
> DB_USER=mastodon
> DB_PASS=XXX
> REDIS_HOST=localhost
> REDIS_PORT=6379
> REDIS_PASSWORD=XXX
> SMTP_SERVER=smtp.postmarkapp.com
> SMTP_PORT=587
> SMTP_LOGIN=XXX
> SMTP_PASSWORD=XXX
> SMTP_AUTH_METHOD=plain
> SMTP_OPENSSL_VERIFY_MODE=none
> SMTP_ENABLE_STARTTLS=always
> SMTP_FROM_ADDRESS='Mastodon <notifications@mastodon.XXX.de>'
> S3_ENABLED=true
> S3_PROTOCOL=https
> S3_ENDPOINT=https://s3.us-west-002.backblazeb2.com
> S3_HOSTNAME=s3.us-west-002.backblazeb2.com
> S3_BUCKET=mastodon-XXX
> AWS_ACCESS_KEY_ID=XXX
> AWS_SECRET_ACCESS_KEY=XXX

**systemctl cat mastodon-web:**
> [Unit]
> Description=mastodon-web
> After=network.target
> 
> [Service]
> Type=simple
> User=mastodon
> WorkingDirectory=/home/mastodon/live
> Environment="RAILS_ENV=production"
> Environment="PORT=3000"
> Environment="LD_PRELOAD=libjemalloc.so"
> ExecStart=/home/mastodon/.rbenv/shims/bundle exec puma -C config/puma.rb
> ExecReload=/bin/kill -SIGUSR1 $MAINPID
> TimeoutSec=15
> Restart=always
> ProcSubset=pid
> ProtectProc=invisible
> CapabilityBoundingSet=
> NoNewPrivileges=true
> ProtectSystem=strict
> PrivateTmp=true
> PrivateDevices=true
> PrivateUsers=true
> ProtectHostname=true
> ProtectKernelLogs=true
> ProtectKernelModules=true
> ProtectKernelTunables=true
> ProtectControlGroups=true
> RestrictAddressFamilies=AF_INET
> RestrictAddressFamilies=AF_INET6
> RestrictAddressFamilies=AF_NETLINK
> RestrictAddressFamilies=AF_UNIX
> RestrictNamespaces=true
> LockPersonality=true
> RestrictRealtime=true
> RestrictSUIDSGID=true
> RemoveIPC=true
> PrivateMounts=true
> ProtectClock=true
> SystemCallArchitectures=native
> SystemCallFilter=~@cpu-emulation @debug @keyring @ipc @mount @obsolete @privileged @setuid
> SystemCallFilter=@chown
> SystemCallFilter=pipe
> SystemCallFilter=pipe2
> ReadWritePaths=/home/mastodon/live
> 
> [Install]
> WantedBy=multi-user.target

**journalctl -e -u mastodon-web:**

> Jun 03 22:32:33 mastodon.XXX.de systemd[1]: mastodon-web.service: Scheduled restart job, restart counter is at 3.
> Jun 03 22:32:33 mastodon.XXX.de systemd[1]: Stopped mastodon-web.service - mastodon-web.
> Jun 03 22:32:33 mastodon.XXX.de systemd[1]: Started mastodon-web.service - mastodon-web.
> Jun 03 22:32:33 mastodon.XXX.de (bundle)[1006]: mastodon-web.service: Failed to locate executable /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:32:33 mastodon.XXX.de (bundle)[1006]: mastodon-web.service: Failed at step EXEC spawning /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:32:33 mastodon.XXX.de systemd[1]: mastodon-web.service: Main process exited, code=exited, status=203/EXEC
> Jun 03 22:32:33 mastodon.XXX.de systemd[1]: mastodon-web.service: Failed with result 'exit-code'.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: mastodon-web.service: Scheduled restart job, restart counter is at 4.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: Stopped mastodon-web.service - mastodon-web.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: Started mastodon-web.service - mastodon-web.
> Jun 03 22:32:34 mastodon.XXX.de (bundle)[1014]: mastodon-web.service: Failed to locate executable /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:32:34 mastodon.XXX.de (bundle)[1014]: mastodon-web.service: Failed at step EXEC spawning /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: mastodon-web.service: Main process exited, code=exited, status=203/EXEC
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: mastodon-web.service: Failed with result 'exit-code'.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: mastodon-web.service: Scheduled restart job, restart counter is at 5.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: Stopped mastodon-web.service - mastodon-web.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: mastodon-web.service: Start request repeated too quickly.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: mastodon-web.service: Failed with result 'exit-code'.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: Failed to start mastodon-web.service - mastodon-web.
> Jun 03 22:39:43 mastodon.XXX.de systemd[1]: Started mastodon-web.service - mastodon-web.
> Jun 03 22:39:43 mastodon.XXX.de (bundle)[1086]: mastodon-web.service: Failed to locate executable /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:39:43 mastodon.XXX.de (bundle)[1086]: mastodon-web.service: Failed at step EXEC spawning /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:39:43 mastodon.XXX.de systemd[1]: mastodon-web.service: Main process exited, code=exited, status=203/EXEC
> Jun 03 22:39:43 mastodon.XXX.de systemd[1]: mastodon-web.service: Failed with result 'exit-code'.
> Jun 03 22:39:43 mastodon.XXX.de systemd[1]: mastodon-web.service: Scheduled restart job, restart counter is at 1.
> Jun 03 22:39:43 mastodon.XXX.de systemd[1]: Stopped mastodon-web.service - mastodon-web.
> Jun 03 22:39:43 mastodon.XXX.de systemd[1]: Started mastodon-web.service - mastodon-web.
> Jun 03 22:39:43 mastodon.XXX.de (bundle)[1091]: mastodon-web.service: Failed to locate executable /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:39:43 mastodon.XXX.de (bundle)[1091]: mastodon-web.service: Failed at step EXEC spawning /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:39:43 mastodon.XXX.de systemd[1]: mastodon-web.service: Main process exited, code=exited, status=203/EXEC
> Jun 03 22:39:43 mastodon.XXX.de systemd[1]: mastodon-web.service: Failed with result 'exit-code'.
> Jun 03 22:39:43 mastodon.XXX.de systemd[1]: mastodon-web.service: Scheduled restart job, restart counter is at 2.
> Jun 03 22:39:43 mastodon.XXX.de systemd[1]: Stopped mastodon-web.service - mastodon-web.
> Jun 03 22:39:43 mastodon.XXX.de systemd[1]: Started mastodon-web.service - mastodon-web.
> Jun 03 22:39:43 mastodon.XXX.de (bundle)[1096]: mastodon-web.service: Failed to locate executable /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:39:43 mastodon.XXX.de (bundle)[1096]: mastodon-web.service: Failed at step EXEC spawning /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:39:43 mastodon.XXX.de systemd[1]: mastodon-web.service: Main process exited, code=exited, status=203/EXEC
> Jun 03 22:39:43 mastodon.XXX.de systemd[1]: mastodon-web.service: Failed with result 'exit-code'.
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: mastodon-web.service: Scheduled restart job, restart counter is at 3.
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: Stopped mastodon-web.service - mastodon-web.
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: Started mastodon-web.service - mastodon-web.
> Jun 03 22:39:44 mastodon.XXX.de (bundle)[1101]: mastodon-web.service: Failed to locate executable /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:39:44 mastodon.XXX.de (bundle)[1101]: mastodon-web.service: Failed at step EXEC spawning /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: mastodon-web.service: Main process exited, code=exited, status=203/EXEC
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: mastodon-web.service: Failed with result 'exit-code'.
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: mastodon-web.service: Scheduled restart job, restart counter is at 4.
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: Stopped mastodon-web.service - mastodon-web.
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: Started mastodon-web.service - mastodon-web.
> Jun 03 22:39:44 mastodon.XXX.de (bundle)[1105]: mastodon-web.service: Failed to locate executable /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:39:44 mastodon.XXX.de (bundle)[1105]: mastodon-web.service: Failed at step EXEC spawning /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: mastodon-web.service: Main process exited, code=exited, status=203/EXEC
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: mastodon-web.service: Failed with result 'exit-code'.
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: mastodon-web.service: Scheduled restart job, restart counter is at 5.
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: Stopped mastodon-web.service - mastodon-web.
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: mastodon-web.service: Start request repeated too quickly.
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: mastodon-web.service: Failed with result 'exit-code'.
> Jun 03 22:39:44 mastodon.XXX.de systemd[1]: Failed to start mastodon-web.service - mastodon-web.

**systemctl cat mastodon-sidekiq:**

> [Unit]
> Description=mastodon-sidekiq
> After=network.target
> 
> [Service]
> Type=simple
> User=mastodon
> WorkingDirectory=/home/mastodon/live
> Environment="RAILS_ENV=production"
> Environment="DB_POOL=25"
> Environment="MALLOC_ARENA_MAX=2"
> Environment="LD_PRELOAD=libjemalloc.so"
> ExecStart=/home/mastodon/.rbenv/shims/bundle exec sidekiq -c 25
> TimeoutSec=15
> Restart=always
> ProcSubset=pid
> ProtectProc=invisible
> CapabilityBoundingSet=
> NoNewPrivileges=true
> ProtectSystem=strict
> PrivateTmp=true
> PrivateDevices=true
> PrivateUsers=true
> ProtectHostname=true
> ProtectKernelLogs=true
> ProtectKernelModules=true
> ProtectKernelTunables=true
> ProtectControlGroups=true
> RestrictAddressFamilies=AF_INET
> RestrictAddressFamilies=AF_INET6
> RestrictAddressFamilies=AF_NETLINK
> RestrictAddressFamilies=AF_UNIX
> RestrictNamespaces=true
> LockPersonality=true
> RestrictRealtime=true
> RestrictSUIDSGID=true
> RemoveIPC=true
> PrivateMounts=true
> ProtectClock=true
> SystemCallArchitectures=native
> SystemCallFilter=~@cpu-emulation @debug @keyring @ipc @mount @obsolete @privileged @setuid
> SystemCallFilter=@chown
> SystemCallFilter=pipe
> SystemCallFilter=pipe2
> ReadWritePaths=/home/mastodon/live
> 
> [Install]
> WantedBy=multi-user.target

**journalctl -e -u mastodon-sidekiq:**

> Jun 03 22:32:15 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Main process exited, code=exited, status=203/EXEC
> Jun 03 22:32:15 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Failed with result 'exit-code'.
> Jun 03 22:32:16 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Scheduled restart job, restart counter is at 3.
> Jun 03 22:32:16 mastodon.XXX.de systemd[1]: Stopped mastodon-sidekiq.service - mastodon-sidekiq.
> Jun 03 22:32:16 mastodon.XXX.de systemd[1]: Started mastodon-sidekiq.service - mastodon-sidekiq.
> Jun 03 22:32:16 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Main process exited, code=exited, status=203/EXEC
> Jun 03 22:32:16 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Failed with result 'exit-code'.
> Jun 03 22:32:16 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Scheduled restart job, restart counter is at 4.
> Jun 03 22:32:16 mastodon.XXX.de systemd[1]: Stopped mastodon-sidekiq.service - mastodon-sidekiq.
> Jun 03 22:32:16 mastodon.XXX.de systemd[1]: Started mastodon-sidekiq.service - mastodon-sidekiq.
> Jun 03 22:32:16 mastodon.XXX.de (bundle)[607]: mastodon-sidekiq.service: Failed to locate executable /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:32:16 mastodon.XXX.de (bundle)[607]: mastodon-sidekiq.service: Failed at step EXEC spawning /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:32:16 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Main process exited, code=exited, status=203/EXEC
> Jun 03 22:32:16 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Failed with result 'exit-code'.
> Jun 03 22:32:16 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Scheduled restart job, restart counter is at 5.
> Jun 03 22:32:16 mastodon.XXX.de systemd[1]: Stopped mastodon-sidekiq.service - mastodon-sidekiq.
> Jun 03 22:32:16 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Start request repeated too quickly.
> Jun 03 22:32:16 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Failed with result 'exit-code'.
> Jun 03 22:32:16 mastodon.XXX.de systemd[1]: Failed to start mastodon-sidekiq.service - mastodon-sidekiq.
> Jun 03 22:32:32 mastodon.XXX.de systemd[1]: Started mastodon-sidekiq.service - mastodon-sidekiq.
> Jun 03 22:32:32 mastodon.XXX.de (bundle)[971]: mastodon-sidekiq.service: Failed to locate executable /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:32:32 mastodon.XXX.de (bundle)[971]: mastodon-sidekiq.service: Failed at step EXEC spawning /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:32:32 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Main process exited, code=exited, status=203/EXEC
> Jun 03 22:32:32 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Failed with result 'exit-code'.
> Jun 03 22:32:32 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Scheduled restart job, restart counter is at 1.
> Jun 03 22:32:32 mastodon.XXX.de systemd[1]: Stopped mastodon-sidekiq.service - mastodon-sidekiq.
> Jun 03 22:32:32 mastodon.XXX.de systemd[1]: Started mastodon-sidekiq.service - mastodon-sidekiq.
> Jun 03 22:32:32 mastodon.XXX.de (bundle)[985]: mastodon-sidekiq.service: Failed to locate executable /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:32:32 mastodon.XXX.de (bundle)[985]: mastodon-sidekiq.service: Failed at step EXEC spawning /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:32:32 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Main process exited, code=exited, status=203/EXEC
> Jun 03 22:32:32 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Failed with result 'exit-code'.
> Jun 03 22:32:33 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Scheduled restart job, restart counter is at 2.
> Jun 03 22:32:33 mastodon.XXX.de systemd[1]: Stopped mastodon-sidekiq.service - mastodon-sidekiq.
> Jun 03 22:32:33 mastodon.XXX.de systemd[1]: Started mastodon-sidekiq.service - mastodon-sidekiq.
> Jun 03 22:32:33 mastodon.XXX.de (bundle)[997]: mastodon-sidekiq.service: Failed to locate executable /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:32:33 mastodon.XXX.de (bundle)[997]: mastodon-sidekiq.service: Failed at step EXEC spawning /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:32:33 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Main process exited, code=exited, status=203/EXEC
> Jun 03 22:32:33 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Failed with result 'exit-code'.
> Jun 03 22:32:33 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Scheduled restart job, restart counter is at 3.
> Jun 03 22:32:33 mastodon.XXX.de systemd[1]: Stopped mastodon-sidekiq.service - mastodon-sidekiq.
> Jun 03 22:32:33 mastodon.XXX.de systemd[1]: Started mastodon-sidekiq.service - mastodon-sidekiq.
> Jun 03 22:32:33 mastodon.XXX.de (bundle)[1005]: mastodon-sidekiq.service: Failed to locate executable /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:32:33 mastodon.XXX.de (bundle)[1005]: mastodon-sidekiq.service: Failed at step EXEC spawning /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:32:33 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Main process exited, code=exited, status=203/EXEC
> Jun 03 22:32:33 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Failed with result 'exit-code'.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Scheduled restart job, restart counter is at 4.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: Stopped mastodon-sidekiq.service - mastodon-sidekiq.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: Started mastodon-sidekiq.service - mastodon-sidekiq.
> Jun 03 22:32:34 mastodon.XXX.de (bundle)[1013]: mastodon-sidekiq.service: Failed to locate executable /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:32:34 mastodon.XXX.de (bundle)[1013]: mastodon-sidekiq.service: Failed at step EXEC spawning /home/mastodon/.rbenv/shims/bundle: Permission denied
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Main process exited, code=exited, status=203/EXEC
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Failed with result 'exit-code'.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Scheduled restart job, restart counter is at 5.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: Stopped mastodon-sidekiq.service - mastodon-sidekiq.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Start request repeated too quickly.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: mastodon-sidekiq.service: Failed with result 'exit-code'.
> Jun 03 22:32:34 mastodon.XXX.de systemd[1]: Failed to start mastodon-sidekiq.service - mastodon-sidekiq.

**ls -la /home/mastodon/.rbenv/shims/bundle:**

> -rwxr-xr-x 1 mastodon www-data 399  3. Jun 19:16 /home/mastodon/.rbenv/shims/bundle

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x86_64-linux]
- Node.js version: v20.14.0

uname -v: #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03)

**Comment by markrsmith83** [comment]
What are the owner and group on the files in /home/mastodon/.rbenv/shims/bundle ? Should be mastodon (or your main mastodon user) for both owner and group.

**Comment by mergedeyes** [comment]
> What are the owner and group on the files in /home/mastodon/.rbenv/shims/bundle ? Should be mastodon (or your main mastodon user) for both owner and group.

As mentioned on my initial post: 
`-rwxr-xr-x 1 mastodon www-data 399 3. Jun 19:16 /home/mastodon/.rbenv/shims/bundle`
 But I since abandoned the project of setting up Mastodon and used my VPS for something different.

Nevertheless, if someone is having the same trouble, maybe @celestora answer could help.

**Comment by ThisIsMissEm** [comment]
@renchap given this is no longer needing a response from the person who opened it & it's likely specific to their setup, I think it'd be appropriate to close this issue
