### ISSUE TITLE
Bizarre, Chrome-only(?) scrollwheel breakage in web Mastodon

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#30537]
### Steps to reproduce the problem

I am using mastodon.social (currently showing v4.3.0-nightly.2024-05-31-security) in Chrome (123.0.6312.106 (Official Build) (64-bit) (cohort: Stable)) on Windows 10 (19045). I use "Advanced"/deck interface.

I am currently seeing a 100% reproducible error where the scrollwheel stops working. This appeared sometime in the last 24 hours and will not go away.

To reproduce: Find a post with a GIF attachment. The GIF *must* be in the leftmost column of the advanced interface (I have not yet experimented with non-Advanced). I am able to reproduce it more often with this post than I am with other posts https://mastodon.social/@b3ll/112554111511501861 . Put the mouse over the GIF and wait for the mouse cursor to change to a magnifying glass, wiggle the mouse a little if you have to. Now try to scroll. The scrollwheel will not work. Not only will it not work, it will *continue* not working, even after I move the mouse away from the GIF. It will not work in any of the advanced columns. Sometimes scrollwheel support will come back after "fiddling around" e.g. waiting 10 seconds, switching to another tab and back etc, but it doesn't seem consistent in what makes it come back.

I plugged the same mouse into my Linux laptop running Firefox and was **not** able to reproduce this there. This suggests it may be a Chrome problem, but also, I was not able to reproduce it in any non-Mastodon tab, even with many tabs open.

Problem history: Started seeing this last night, didn't worry about it, saw it this morning, restarted Chrome and accepted an update to 123.0.6312.106, was still seeing the problem, realized I could make it happen reproducibly with the GIF trick, rebooted the whole computer (no Windows update occurred), still seeing the problem even with minimal other activity on the computer (like, GMail and a YouTube tab playing music, no non-Chrome apps).

Expected behavior: Scrollwheeling over a GIF is no different from scrollwheeling elsewhere (as seen in Firefox for Linux)

---

Uncertain observations: When the scrollwheel is "stuck" it seems like the screen is *sometimes* not updating as it should. I can scroll only by grabbing a scroll indicator on a scrollbar and dragging it, I can't ever scroll by clicking the scrollbar outside the indicator. *Sometimes* when I'm in the problem state I don't get live updates while scrolling with the scroll indicator, *sometimes* when I'm in the problem state selecting text seems not to update the screen with a text selection (but if I copy with ctrl-c, the text I selected goes in the clipboard), *once* the entire Mastodon tab went pure white and stayed that way displaying nothing but I could select and copy text. (That last bug *really* sounds like a Chrome problem.) None of these effects are as consistent as the broken scrollwheel. Never saw anything like this before last night.

**Comment by mcclure** [comment]
Disabled Advanced interface. Scrolled down to Adam Bell post in feed. Tried to reproduce. Couldn't reproduce. Turned Advanced interface back on. Scrolled down to Adam Bell post in feed. Tried to reproduce. Reproduced.

**Comment by mcclure** [comment]
Notes on extensions because I just realized I didn't mention this in the original post: On both Chrome and Firefox I run with uBlock Origin and Stylus which I use to impose some very minor CSS changes on Mastodon, however, if I disable the Stylus extension and reload mastodon.social I am still able to reproduce

**Comment by mcclure** [comment]
Logged into Mastodon on Firefox for Windows and tried really hard to reproduce, could not reproduce

**Comment by mjankowski** [comment]
Did this ever resolve itself ... and/or did we narrow down to a specific commit where this started happening?

**Comment by mcclure** [comment]
Sorry, I should have updated— this is a bug in Chrome, it expresses on sites other than Mastodon, it has been confirmed by the Chromium project and is in their to-fix pool.

https://issues.chromium.org/issues/361038870

I don't currently have access to Chrome so I cannot confirm it's happening this moment, but the Chromium bug is still open so I assume so.

**Comment by mjankowski** [comment]
Thanks for update -- I'm going to close this on the assumption that there's not actually anything we can do on mastodon code side and that it's a chrome edge case that they'll have to handle in the browser - please reopen if I'm missing something.
