### ISSUE TITLE
[Android] Next button on multi-image overlay stops GIF playback

### ISSUE THREAD

**Issue by fwenzel** [mastodon/mastodon#3061]
STR:
* on Chrome on Android open a toot with multiple GIF attachments.
* press the `>` button on that overlay to go to the next GIF

Actual:
* image advances, but does not animate the GIF.

Expected:
* second GIF also animates.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
