### ISSUE TITLE
[FR] Rewrite Masto Links to go to User's Instance

### ISSUE THREAD

**Issue by khemarato** [mastodon/mastodon#30630]
### Pitch

Many posts contain links to toots instead of being a "proper" retoot. These links are currently rendering as links, not as toots.

### Motivation

It's annoying to have to click on a Masto link in my Masto instance, get taken to an external server, click "Take me home", enter my instance, and then submit... just to view a shared toot.  This should be solvable on the home instance.

**Comment by Gargron** [comment]
Open PR for this: #26917

**Comment by khemarato** [comment]
Oi.... so stale 😢

**Comment by trwnh** [comment]
I'm going to go ahead and close this as a duplicate of https://github.com/mastodon/mastodon/issues/1399 and/or https://github.com/mastodon/mastodon/issues/21869 to prevent this from being orphaned later.
