### ISSUE TITLE
Changing text sign up page

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#3066]
Hello i didy own instance of mastodon and i'm trying to change the text on the signup page.

I did the modifications for fr.yml but nothing work do you know how can i do to get it working ? 

Thanks. Lot

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
Can you clarify which text you are trying to change?

**Comment by Zirconiumirish** [comment]
Yes sure.

Juste changing the paragraph text in the about page (SIgn up page)
Where it present the concept of mastodon with highlight word.

Thanks
