### ISSUE TITLE
Custom emoji federation from external servers is broken

### ISSUE THREAD

**Issue by letydoesstuff** [mastodon/mastodon#30706]
### Steps to reproduce the problem

1. Open a post from an external server containing a custom emoji uploaded after 2024-06-06

### Expected behaviour

The custom emoji shortcode is replaced with the custom emoji

### Actual behaviour

The custom emoji shortcode displays as plaintext

### Detailed description

To start, this also doesn't only affect newly uploaded custom emoji, some older custom emoji also appear to be breaking as well. I suspect this has to do with mastodon/mastodon#30578.

Using [this thread](https://doesstuff.social/@lety/112613689071785119) for comparison, here's how some custom emoji look from my instance running the 2024-06-03 nightly. I uploaded the onion emoji a few hours ago, and the magnifying glass emoji some time months ago.

<img height="540" alt="2024-06-03_emojifederation" src="https://github.com/mastodon/mastodon/assets/48048071/bc2e1c3e-3890-4ed9-a471-3d995aa53c25">

The emoji still federate just fine on this other instance running the 2024-06-01 nightly. (Thanks @ronilaukkarinen for keeping Mementomori.social up to date so I have a point of reference!)

<img height="540" alt="2024-06-01_emojifederation" src="https://github.com/mastodon/mastodon/assets/48048071/1e773a05-3372-44a1-af7d-aaf5565d6513">

And here's how they look on Mastodon Social running the 2024-06-06 nightly. The older emoji in this specific case renders just fine, while the new emoji doesn't display at all.

<img height="540" alt="2024-06-06_emojifederation" src="https://github.com/mastodon/mastodon/assets/48048071/7489ede9-7331-48da-bae9-25bb78b1a571">

Proactively disclosing now that I have a zero-width space between the emoji and really verbose shortcodes for accessibility reasons, neither of which should be causing issues or my emoji wouldn't render on any other instances.

And as I mentioned at the start of the issue, this doesn't only affect new custom emoji, but it definitely affects *all* new custom emoji. Some older custom emoji uploaded months and months ago previously rendered just fine and are now retroactively broken.

The [last post in the earlier thread](https://doesstuff.social/@lety/112613773037878460) illustrates this, with all my custom emoji rendering just fine on my instance (left) and some just not working on Mastodon Social (right).

<img height="270" alt="2024-06-03_emojispam" src="https://github.com/mastodon/mastodon/assets/48048071/019366cb-7245-4f29-b192-33a603f375e8"><img height="270" alt="2024-06-06_emojispam" src="https://github.com/mastodon/mastodon/assets/48048071/0d041b41-dc74-47cb-9bbd-5c14adb69f06">

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-06-06

**Comment by ClearlyClaire** [comment]
I am unable to reproduce this, I think this should be fixed since v4.3.0-nightly.2024-06-07 or v4.3.0-nightly.2024-06-08. Can you try again with one of those?

**Comment by letydoesstuff** [comment]
It appears to be fixed! I'm assuming 30578 actually addressed this, my bad.

Sorry for not testing more rigorously, I don't quite understand how to best set up multiple test environments so I really only catch federation issues that are live, and this specific issue required multiple servers to upload/check emoji across. 

Mastodon Social is now running v4.3.0-nightly.2024-06-14, and external custom emoji are now showing up correctly.

**Comment by dillfrescott** [comment]
Custom emoji on the newest version of mastodon just doesnt work. And the tootctl emoji purge --remote-only just gets stuck

**Comment by dillfrescott** [comment]
Like no progress or anything sadly
