### ISSUE TITLE
Something went wrong after upgrade

### ISSUE THREAD

**Issue by irrelevantdotcom** [mastodon/mastodon#30722]
### Steps to reproduce the problem

Accessing instance homepage, I get "We're sorry, but something went wrong on our end."

### Expected behaviour

home page should be displayed

### Actual behaviour

I get "We're sorry, but something went wrong on our end."

### Detailed description

I did an upgrade from 4.2.8 to 4.2.9. Followed the steps in the guide, which isn't much.  I didn't see any errors.  
Rebooted the server afterwards, as ubuntu was telling me to do so when I'd logged in..
Could not access instance via web after this.

### Mastodon instance

irrelevant.me.uk

### Mastodon version

4.2.9

### Browser name and version

Opera One(version: 110.0.5130.66)

### Operating system

Windows 10

### Technical details

Might be this? "Client 127.0.0.1 is not a trusted proxy"
```
mastodon@fediverse2:~/live$ systemctl status mastodon-web
● mastodon-web.service - mastodon-web
     Loaded: loaded (/etc/systemd/system/mastodon-web.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2024-06-15 00:16:56 UTC; 40min ago
    Process: 2739 ExecReload=/bin/kill -SIGUSR1 $MAINPID (code=exited, status=0/SUCCESS)
   Main PID: 827 (ruby)
      Tasks: 29 (limit: 14249)
     Memory: 473.2M
     CGroup: /system.slice/mastodon-web.service
             ├─ 827 puma 6.4.2 (tcp://127.0.0.1:3000) [live]
             ├─2821 puma: cluster worker 0: 827 [live]
             └─2826 puma: cluster worker 1: 827 [live]

Jun 15 00:57:35 fediverse2 bundle[2821]: [0fc91f7e-e07f-4f03-bf60-b2e67089fc5c]
Jun 15 00:57:35 fediverse2 bundle[2821]: [0fc91f7e-e07f-4f03-bf60-b2e67089fc5c] lib/action_dispatch/remote_ip_extensions.rb:49:in `calculate_ip'
Jun 15 00:57:35 fediverse2 bundle[2821]: [0fc91f7e-e07f-4f03-bf60-b2e67089fc5c] config/initializers/rack_attack.rb:17:in `remote_ip'
Jun 15 00:57:35 fediverse2 bundle[2821]: [0fc91f7e-e07f-4f03-bf60-b2e67089fc5c] config/initializers/rack_attack.rb:66:in `block in <class:Attack>'
Jun 15 00:57:35 fediverse2 bundle[2821]: F, [2024-06-15T00:57:35.628745 #2821] FATAL -- : [14118113-873a-44ee-8378-f10fa662bb09]
Jun 15 00:57:35 fediverse2 bundle[2821]: [14118113-873a-44ee-8378-f10fa662bb09] ActionDispatch::RemoteIp::IpSpoofAttackError (IP spoofing attack?! client 127.0.0.1 is not a truste>
Jun 15 00:57:35 fediverse2 bundle[2821]: [14118113-873a-44ee-8378-f10fa662bb09]
Jun 15 00:57:35 fediverse2 bundle[2821]: [14118113-873a-44ee-8378-f10fa662bb09] lib/action_dispatch/remote_ip_extensions.rb:49:in `calculate_ip'
Jun 15 00:57:35 fediverse2 bundle[2821]: [14118113-873a-44ee-8378-f10fa662bb09] config/initializers/rack_attack.rb:17:in `remote_ip'
Jun 15 00:57:35 fediverse2 bundle[2821]: [14118113-873a-44ee-8378-f10fa662bb09] config/initializers/rack_attack.rb:66:in `block in <class:Attack>'
```

**Comment by renchap** [comment]
Your Mastodon configuration is probably invalid. 

Have a look at the [TRUSTED_PROXY_IP](https://docs.joinmastodon.org/admin/config/#trusted_proxy_ip) configuration option, I expect it to be incorrectly set.

**Comment by irrelevantdotcom** [comment]
Yes that was the first thing I checked. It's set to the IP of the nginx
proxy that this sits behind, as it has been since I set this up in the
first place. I tried adding 127.0.0.1, with no effect. The documentation
says all the localhost addresses should be automatically trusted.

**Comment by irrelevantdotcom** [comment]
A further note... the full error line that I quoted above is:
`ActionDispatch::RemoteIp::IpSpoofAttackError (IP spoofing attack?! client 127.0.0.1 is not a trusted proxy HTTP_CLIENT_IP=nil HTTP_X_FORWARDED_FOR="86.131.231.117, 192.168.200.102"):`
I'm wondering if that "nil" for HTTP_CLIENT_IP is causing the issue ?  And where it's supposed to be set. The values in the Forwarded_for seem correct...

**Comment by irrelevantdotcom** [comment]
I've tried adding as many different headers as I could to the reverse proxy, but with no success.
In desperation I disabled the spoofing check in Rails, and this has allowed the instance to be accessible again!
When I have some time, I'll try setting up another instance on a different VM to try and identify what might be going wrong.  If I find out, I'll update this thread.

In the meantime if anybody else hits this issue, the way to disable the spoofing is:
in ./live/config/application.rb
Under
```
module Mastodon
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 7.0
```
add
` config.action_dispatch.ip_spoofing_check = false`

and reload the services.

**Comment by renchap** [comment]
You should probably add `192.168.200.102` to your trusted IPs, from what I can understand

**Comment by ClearlyClaire** [comment]
Disabling IP spoofing checks is a bad idea, as it opens your server to much easier attacks on password enumeration and so on.

> I'm wondering if that "nil" for HTTP_CLIENT_IP is causing the issue ?

No, it's fine.

From my understanding of your setup, you have `192.168.200.102` acting as a reverse-proxy in front of another reverse-proxy in `127.0.0.1`, while `86.131.231.117` is the final client IP address. If that's indeed the case, leaving `TRUSTED_PROXY_IP` unset should fix your issue, as both `127.0.0.1` and `192.168.200.102` are trusted by default.

If you do set up `TRUSTED_PROXY_IP`, it *replaces* the defaults, so you need to set both `127.0.0.1` and `192.168.200.102`.

**Comment by irrelevantdotcom** [comment]
TRUSTED_PROXY_IP had been set to (just) 192.168.200.102 since I got this instance up and running at the end of 2022.  I'd not touched it since.  I only started having problems when I upgraded 4.2.8 > 4.2.9.    I tried adding 127.0.0.1 to this, but it didn't work.

I have just tried removing the definition completely, so leaving it unset as suggested, whilst removing my line supressing the spoofing check, and I again am back to "Something went wrong" with the same message about 127.0.0.1 not being trusted in the status.  Is there anything I need to do, other than restart mastodon-web.service, to get it to reload .env.production ?

**Comment by ClearlyClaire** [comment]
Yes, it is expected that `TRUSTED_PROXY_IP` being set to `192.168.200.102` would have previously worked with your setup and break with 4.2.9.

`systemctl restart mastodon-web.service` should be enough to reload `.env.production`; make sure you haven't set `TRUSTED_PROXY_IP` in another place, like the `mastodon-web.service` systemd unit file.

**Comment by irrelevantdotcom** [comment]
Ah, it was indeed in there, too.  Commented it out, and we're up and running. (After I remembered to do a `systemctl daemon-reload`)  Thank you!

I do think that, to avoid confusion again, the mention of TRUSTED_PROXY_IP on the github releases page (where I checked for any specific upgrade instructions) could be expanded to mention that this might be an issue - that it's not needed if you are only using proxies on local IPs (it it all RFC 1918 addresses?) as well as the current phrasing that only says when it IS needed. Anyway, Thanks again for your help!

**Comment by ClearlyClaire** [comment]
Updated the release notes blurb from:
> [!IMPORTANT]
> Mastodon is now performing stricter checks to prevent client IP address spoofing. This means that if one of your reverse proxy is not on Mastodon's local network, you will need to set `TRUSTED_PROXY_IP` accordingly, listing the IP address of every trusted reverse-proxy.

to:
> [!IMPORTANT]
> Mastodon is now performing stricter checks to prevent client IP address spoofing. This means that if one of your reverse proxy is not on Mastodon's local network, you will need to set `TRUSTED_PROXY_IP` accordingly, listing the IP address of every trusted reverse-proxy (including local network ones). See [the documentation](https://docs.joinmastodon.org/admin/config/#trusted_proxy_ip) for more information.

**Comment by irrelevantdotcom** [comment]
That's a lot better, and the explanation on the documentation link is very
clear. Thank you for adjusting this.
