### ISSUE TITLE
Favicon customization doesn’t touch svg `mask-icon`

### ISSUE THREAD

**Issue by daprice** [mastodon/mastodon#30728]
### Steps to reproduce the problem

1. As a server admin, customize favicon using capabilities introduced in #30040

### Expected behaviour

Users should be able to see the customized icon everywhere and/or admin should be able to configure the svg mask-icon separately

### Actual behaviour

The svg `mask-icon` is still the mastodon logo in the mastodon brand color, so users may see it as their browser’s tab icon rather than the custom one

### Detailed description

Ideally, the admin should be able to upload their own properly formatted vector file for the `mask-icon`, choose a color for it, and see a preview of how it would be displayed in the admin interface along with the other icons. Maybe the admin should be able to disable the mask-icon if they use a custom favicon without uploading a matching `mask-icon`.

### Mastodon instance

N/A

### Mastodon version

anything that includes #30040

### Browser name and version

Safari (any version)

### Operating system

any apple OS

**Comment by renchap** [comment]
We should probably simply remove `mask-icon`, either all the time, or only when a custom instance icon is used.

According to https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs this is not useful anymore (and even apple.com no longer uses it).
