### ISSUE TITLE
Webfinger not working?

### ISSUE THREAD

**Issue by adamcnaglich** [mastodon/mastodon#30747]
### Steps to reproduce the problem

1. search for my user without a subdomain (@adam@n5h.co)

### Expected behaviour

Expect to find my user at @adam@mastodon.n5h.co

### Actual behaviour

I get a 503 or a 404

### Detailed description

Im trying to cleanup my new server and changed the local domain so that i don’t see the subdomain as part of the username, but it doesn’t seem to be working in full. Of note, i’m unsure how to check that the redirect I added to my conf in synology is working (im a noob).

### Mastodon instance

mastodon.n5h.co

### Mastodon version

v4.2.9

### Browser name and version

Safari for iPadOS

### Operating system

iPadOS

**Comment by ClearlyClaire** [comment]
Generally speaking, changing your domain name after the fact isn't supported by Mastodon. That being said, changing the `LOCAL_DOMAIN` while keeping the `LOCAL_DOMAIN` should, in theory, be handled by Mastodon.

In any case, the issue seems to be lying elsewhere. I tried resolving `adam@n5h.co`, but this fails because `n5h.co` itself has no IP address associated.

**Comment by adamcnaglich** [comment]
Thank you for helping. I read that changing the domain was not good, but I figured that because I was the only user on the instance I wouldn’t get into much trouble — that being said, what could I have messed up and how could I go about fixing it?

If adam@n5h.co is not resolving, where should I look? Does that mean that the nginx conf code I pasted is not working as I planned? I did just add a WWW CNAME record.

**Comment by adamcnaglich** [comment]
Fixed the unresponsive n5h.co by adding a DNS alias and creating an ssl cert. I also figured out that the redirect was not working due to Synology overwriting the redirect I added to the configuration file (whenever nginx restarted).

**Comment by ClearlyClaire** [comment]
> Thank you for helping. I read that changing the env domain was not good, but I figured that because I was the only user on this new instance that that warning didn’t really apply... what could I have messed up and how can I go about fixing it?

If your server has not previously federated with anyone, then the warning doesn't apply, indeed.

Everything now appears to be correct save for the fact that the SSL cert used for n5h.co uses the wrong domain name, preventing the webfinger query.
