### ISSUE TITLE
Recent decrease in gif playback quality

### ISSUE THREAD

**Issue by shmiel** [mastodon/mastodon#30804]
### Steps to reproduce the problem

1. Upload animated gif
2. View on timeline
3. Gif plays faster and with more artifacting than in uploaded file

### Expected behaviour

Gif playback is the same on source computer and when viewing uploaded file on timeline

### Actual behaviour

Gif plays back faster and with more artifacting

### Detailed description

In the last three days, I've noticed a significant decrease in the quality of playback for uploaded animated gifs. They're sped up and lower-quality with more blurring and artifacts. Specifically this seems to have begun on June 19th.

I can show the change really clearly on the media tab of my profile, as I've uploaded an animated gif every day for the last month: https://mastodon.online/@ephesossh/media

Starting at the one labeled 802, the quality decreases drastically, visible in the thumbnail and the gif itself. I've attached an example of the uploaded .gif and the viewed .mp4 version from the web UI.

This is not a machine- or browser-specific issue, as I've reproduced the issue on both my Windows machine running Firefox, and my Macbook running Chrome. (Currently traveling so I don't have the exact windows/firefox versions at hand right now)

### Mastodon instance

mastodon.online

### Mastodon version

v4.3.0-nightly.2024-06-20

### Browser name and version

Chrome 125.0.6422.176, also Firefox (version unknown)

### Operating system

macOS 12.1, also Windows 10 (version unknown)

### Technical details

![20240620-shoppingbag](https://github.com/mastodon/mastodon/assets/744309/8380f1c9-7632-4c45-83b5-ecbcd847ab5e)

https://github.com/mastodon/mastodon/assets/744309/6aabc1c5-7dd8-4801-9cb4-2a514c32a1e7

Attached originally uploaded .gif and the displayed .mp4 version from the web interface

**Comment by shmiel** [comment]
Okay it's been pointed out to me that the version being converted by Mastodon is actually the correct length, verified by https://onlinegiftools.com/analyze-gif and just what I see in Aseprite before I export the file.

The fact that I'm seeing it in the slower version in my OSes, in web views (including here in this very issue report!), and older posts is baffling, but I do have to conclude that this isn't a Mastodon issue, this is an... everything else issue? And I see that the nightly version that mastodon.online is using was dated to roughly when the issue began so... good job Mastodon on fixing that?

I'm confused as heck but I think I can close this, closing as completed because it wasn't really Mastodon's issue.

**Comment by letydoesstuff** [comment]
"Issue" caused by incorrectly formatted .gifs and then mastodon/mastodon#30569 building ffmpeg from scratch on Docker, causing it to use the newest version of ffmpeg possible. On older versions of ffmpeg (my server seems to be pulling v4.4.2 from the system), ffmpeg wouldn't correctly parse gif timecodes and would instead default to 10 fps/100ms delay.

This behavior changed in [gitweb/ffmpeg.git@c6b6356](https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/c6b6356635f598b095606cd126f31bc6ab916225) when ffmpeg started using a proper gif parser.

**Comment by shmiel** [comment]
Closing for real, it was late and I was tired
