### ISSUE TITLE
LinkCrawlWorker NoMethodError: undefined method `xpath' for an instance of Array

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#30841]
### Steps to reproduce the problem

![image](https://github.com/mastodon/mastodon/assets/17537000/be8ceca9-e9f1-4924-afd9-a3e021800209)

### Expected behaviour

No dead jobs

### Actual behaviour

Dead jobs

### Mastodon instance

aus.social

### Mastodon version

Main

### Technical details

Docker.

**Comment by renchap** [comment]
Can you provide a status for which this is happening?

**Comment by vmstan** [comment]
https://mastodon.social/users/neo2/statuses/112689415123927469 which links to https://www.neo2.com/sandalias-planas-verano-crocs/ triggers it
