### ISSUE TITLE
Server does not decode precent encoded @

### ISSUE THREAD

**Issue by noelk** [mastodon/mastodon#30843]
### Steps to reproduce the problem

https://social.bund.de/@bfdi works as expected but a %40 encoded @ results in an error.

https://social.bund.de/%40bfdi returns an error
https://mastodon.social/%40Mastodon returns an error

### Expected behaviour

the %40 should be rewritten to @
https://social.bund.de/%40bfdi  -> https://social.bund.de/@bfdi 

### Actual behaviour

error "The page you are looking for isn't here. "

### Detailed description

this was reported and closed in #15153 but wasn't reopened after reporting it is still an issue.
The patch #23593 does not fix it and the comments are confirming it is still a problem.

### Mastodon instance

https://social.bund.de but also https://mastodon.social

### Mastodon version

4.2.9

sorry, if it should/could be handled different but I#m not able to reopen the closed bug #15153

**Comment by timothyjrogers** [comment]
I've opened a PR resolving this issue: https://github.com/mastodon/mastodon/pull/31184

There was an existing route that seemed to try and redirect percent-encoded profile paths to the decoded version, but as far as I can tell the constraint was never appropriately matching and thus the 404's. After much reading I think there's some combination of subtle issues with Rails automatically decoding encoded values and the way regex captures work in the paths/constraints on the routes that was just not working as expected. The updated route in my PR maintains this intent and redirects %40<username> to @<username>.
