### ISSUE TITLE
Problems after Server Migration (No federation)

### ISSUE THREAD

**Issue by TheRealKingS** [mastodon/mastodon#30856]
### Steps to reproduce the problem

1. Migrate my Instance to a new Server, following the guide at https://docs.joinmastodon.org/admin/migrating/
2. Starting up all services
3. Upgrade to 4.3.0
4. Restart all Services again

### Expected behaviour

Everything should work

### Actual behaviour

Error 500 at posting and no federation

### Detailed description

I tried to migrate my instance to a new server. I dumped my complete PostgreSQL Database, imported it on the new server and follow generally the guide at https://docs.joinmastodon.org/admin/migrating/.

After Upgrade to 4.3.0 (maybe it's to fresh?) i got the following Error in the mastodon-web.service: https://pastebin.com/bYs6pEe4

PostgreSQL tables involved:

public.statuses: https://pastebin.com/i8D5yMxy

### Mastodon instance

mstdn.myifn.de

### Mastodon version

v4.3.0-alpha.4+glitch

### Technical details

Ruby version:
```
ruby --version
ruby 3.3.3 (2024-06-12 revision f1c7b6f435) [x86_64-linux]
```

Node Version
```
node --version
v20.15.0
```

**Comment by renchap** [comment]
Did you forget to run the migrations after upgrading to 4.3?

**Comment by TheRealKingS** [comment]
Nope, here is the output of the db:migrate with debug information:

```
 RAILS_ENV=production bin/rails db:migrate
D, [2024-06-27T16:56:39.148144 #2836738] DEBUG -- : [dotenv] Set LOCAL_DOMAIN, SINGLE_USER_MODE, SECRET_KEY_BASE, OTP_SECRET, VAPID_PRIVATE_KEY, VAPID_PUBLIC_KEY, DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PASS, REDIS_HOST, REDIS_PORT, REDIS_PASSWORD, REDIS_NAMESPACE, SMTP_SERVER, SMTP_PORT, SMTP_AUTH_METHOD, SMTP_OPENSSL_VERIFY_MODE, SMTP_FROM_ADDRESS, MAX_TOOT_CHARS, MAX_PINNED_TOOTS, MAX_BIO_CHARS, MAX_PROFILE_FIELDS, HCAPTCHA_SECRET_KEY, HCAPTCHA_SITE_KEY, IP_RETENTION_PERIOD, SESSION_RETENTION_PERIOD, ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY, ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT, ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY, RAILS_LOG_LEVEL, and LOG_LEVEL
I, [2024-06-27T16:56:39.148189 #2836738]  INFO -- : [dotenv] Loaded .env.production
D, [2024-06-27T16:56:39.454687 #2836738] DEBUG -- :   ActiveRecord::SchemaMigration Load (0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
D, [2024-06-27T16:56:39.456254 #2836738] DEBUG -- :    (0.0ms)  SELECT pg_try_advisory_lock(6820806995890093290)
D, [2024-06-27T16:56:39.456482 #2836738] DEBUG -- :   ActiveRecord::SchemaMigration Load (0.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
D, [2024-06-27T16:56:39.457160 #2836738] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.4ms)  SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 ORDER BY "ar_internal_metadata"."key" ASC LIMIT 1  [[nil, "environment"]]
D, [2024-06-27T16:56:39.457506 #2836738] DEBUG -- :    (0.1ms)  SELECT pg_advisory_unlock(6820806995890093290)
```

should be fine

**Comment by ClearlyClaire** [comment]
I wonder if your database migration from the old server to the new was complete? Are you sure the database dump was complete, and the import proceeded to the end without any error?

**Comment by TheRealKingS** [comment]
Well if found the problem: the following INDEX was missing:

```
CREATE UNIQUE INDEX index_account_stats_on_account_id ON public.account_stats USING btree (account_id)
```

After creating the index, the 500er was gone.

**Comment by ClearlyClaire** [comment]
Good! But the index being missing could be indicative of other failures when migrating the database, I'd take some time to double-check that it were correctly imported if I were you.
