### ISSUE TITLE
Unable to link to URLs ending with a @

### ISSUE THREAD

**Issue by CarePackage17** [mastodon/mastodon#30860]
### Steps to reproduce the problem

1. Look at this post: https://mastodon.gamedev.place/@CarePackage17/112688958098239356
2. Try clicking the link
3. Observe it leads to a 404 instead of https://gta.fandom.com/wiki/TW@

### Expected behaviour

The link should include the @ as part of its URL: https://gta.fandom.com/wiki/TW@

### Actual behaviour

the link gets broken

### Mastodon instance

mastodon.gamedev.place

### Mastodon version

4.2.9

### Browser name and version

Firefox Nightly 129

### Operating system

Android

**Comment by ClearlyClaire** [comment]
This indeed happens when the `@` appears at the end of an URL. This behavior seems inherited from the `twitter-text` library we use to detect links and mentions. We could probably edit `config/initializers/twitter_regex.rb` to change that, but I am not sure which could be the implications.

**Comment by adamniedzielski** [comment]
I believe that this can be tagged as "status/confirmed" / "status/identified".
