### ISSUE TITLE
Disable automatic "Approval required for sign up" enabling

### ISSUE THREAD

**Issue by idc77** [mastodon/mastodon#30881]
### Pitch

I don't want to log into my admin account every few days and check this setting.
Every time I visit, the damn setting auto sets itself to approval required.
I don't want that!
I want everyone to be able to sign up, especially with only 5 active accounts.

### Motivation

Don't be annoying

**Comment by ClearlyClaire** [comment]
Hi!

We're sorry this feature is an annoyance to you, but it's very deliberate on our end to avoid abandoned servers becoming hosts for abusive and spam accounts.

We do not intend to remove this feature. If you really want to disable it, you can use the `DISABLE_AUTOMATIC_SWITCHING_TO_APPROVED_REGISTRATIONS` environment variable.
