### ISSUE TITLE
Failed to attach image (status 500 or error 500, IDK)

### ISSUE THREAD

**Issue by Twilightssuperb** [mastodon/mastodon#30886]
### Steps to reproduce the problem

1. Just try to upload any picture to post draft.
2. Get no media on input field. "500" message (error? server status?)
3. Try again.
...

### Expected behaviour

Images must be attached

### Actual behaviour

See above

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-06-20

### Browser name and version

Chrome 118

### Operating system

Win 8.1 x64

**Comment by lapcat** [comment]
I'm also seeing this currently on mastodon.social with both the web interface (Safari Mac) and with Mona app.

**Comment by headquarter8302** [comment]
It's definitely an HTTP 500 error seeing the console output. Also seeing this on the mastodon.social instance with Chrome 126

**Comment by Twilightssuperb** [comment]
Oh, I've just managed to upload image! 😅😅

**Comment by renchap** [comment]
This was an issue with our storage on mastodon.social, this is now fixed.
