### ISSUE TITLE
In Advanced mode, dismissing notifications does not decrease the notification counter

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#30896]
### Steps to reproduce the problem

I'm in the Advanced view. I have 6 "filtered mentions" showing in the notifications column.
I click to see the filtered notifications, this happens in a new column. I checkmark all the filtered notifications ("yes, allow them").
The "you have 6 filtered notifications!" box in the notifications column does not update. It stays there showing I have 6 filtered notifications. A few seconds pass.
I click "load more" on the filtered notifications tab. It shows a message saying there are no filtered notifications.
I click the "6 filtered notifications" box. Nothing changes.

![screenshot](https://github.com/mastodon/mastodon/assets/277318/15bb0088-05ab-4c6a-bfe5-60553c01fe23)

A few seconds after that, just after I took this screenshot, the 6 filtered notifications box disappears.

This isn't terrible, but it's not as good as it could be.

### Expected behaviour

Accepting or rejecting a filtered notifications group should cause the notifications column to update.

### Actual behaviour

According to Claire on discord, the filtered notifications box updates on some kind of fixed timer, like 2 minutes.

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-07-02

### Browser name and version

126.0.6478.63 (Official Build) (64-bit) (cohort: Control)

### Operating system

Windows 10

### Technical details

ublock origin is on. userstyles/stylus is not on

**Comment by renchap** [comment]
From Discord:

> it would definitely make sense to refresh when you accept or reject a notification request, though, if that's not the case already
> yeah, it's currently polled every 2 minutes, and not refreshed when accepting or rejecting a request
> another related issue is that accepting a request backfills the notifications feed asynchronously, and the web interface does not know about the new notifications unless it gets reloaded

**Comment by mcclure** [comment]
@renchap , could you specify exactly which version of mastodon.social has this fix (eg is it in v4.3.0-nightly.2024-08-01 ?)
