### ISSUE TITLE
I disabled notification filtering but you're filtering notifications anyway (from hidden profile users?)

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#30894]
### Steps to reproduce the problem

Opened up Mastodon.social this morning. Saw this in my notifications column

!["Notifications from 2 people you may know"](https://github.com/mastodon/mastodon/assets/277318/4c16493d-4982-4e80-99ca-20d8bda54595)

I like the new notification filter UI. I don't like how it takes up more space now, but it's attractive. But that's not the point. The point is, *I shouldn't be seeing filtered notifications*, because I turned that feature off:

![Notification filters](https://github.com/mastodon/mastodon/assets/277318/10165de0-c845-4a65-97bc-4fdbeb3e4ab9)

Filtered notifications are a particular problem for me because I mostly access Mastodon through Tusky, and due to the newness, complexity, and relatively slow documentation process for this new feature, filtered notifications are not shown at all in Tusky.

### Expected behaviour

I should be able to understand why filters are applied or not applied.

### Actual behaviour

I don't understand what the software is doing.

### Detailed description

On looking closer, I had mentions from two people in my filtered notifications box. (I actually had only two mentions, but for one person it had filtered also four "favs" dating back to April into the box. Not sure if that's a bug.) Both mentions were deeply innocuous. One used the word "damn" in a gentle way (I am unafraid of blasphemy).

What I do notice is both users had "this profile has been hidden by the moderators of mastodon.social" status.

Maybe it is a good idea for "hidden" users to also have their notifications filtered. I don't know. I think your choices for who gets their profiles "hidden" are good enough that I **do** appreciate those users being limited from following me without approval. But I think you're a little too trigger happy for me to feel like those users' notifications should also be followed. If I could turn off that filter type I probably would. But I can't, and the fact that I can turn off four *other* categories creates an expectation in my mind I should be able to turn off the fifth.

### Mastodon instance

mastodon.social
"advanced mode"

### Mastodon version

v4.3.0-nightly.2024-07-02

### Browser name and version

126.0.6478.63 (Official Build) (64-bit) (cohort: Control)
ublock origin is on. userstyles/stylus is **not** on

### Operating system

Windows 10

**Comment by renchap** [comment]
This is probably unclear and we are considering adding something to explain it.

Before this, some notifications were silently dropped, for example notifications from server-wide limited accounts. Many people did not knew this (and rightly so, this was very not documented) and thought there were bugs, consistency problems or other causes.

Those now appear in filtered notifications instead of being dropped, allowing the user to accept those (allowing those limited-but-non-followed account to appear), or dismiss them, or (soon) block them.

**Comment by anshwad10** [comment]
I am facing this same problem, but I am not able to find any of the "filtered notifications" controls. And I am not able to find anythign about this in the docs either - What's going on?

**Comment by anshwad10** [comment]
Oh ok I found it now. It wasn't in the settings tab, which is why I was confused
