### ISSUE TITLE
Number of followers decline

### ISSUE THREAD

**Issue by tenebrios** [mastodon/mastodon#30939]
### Steps to reproduce the problem

1. Sudden and drastic drop in followers
2.
3.
...

### Expected behaviour

Follower amount should have remained as is

### Actual behaviour

Follower quantity dropped 

### Detailed description

Today I had 1970 followers.
Within the past half hour it dropped to 1831 unexpectedly. 

What could have caused this to happen?

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by renchap** [comment]
This is most probably not a bug. A remote server maybe blocked your account, causing the people on this server to stop following you.

**Comment by tenebrios** [comment]
> This is most probably not a bug. A remote server maybe blocked your account, causing the people on this server to stop following you.

Wow
That's very strange behavior 🤔 
Oh well
