### ISSUE TITLE
Can't make admin user with admin CLI

### ISSUE THREAD

**Issue by sunwoo1524** [mastodon/mastodon#30945]
### Steps to reproduce the problem

1. I tried to install mastodon with docker and `rake mastodon:setup` following https://www.liquidweb.com/blog/how-to-set-up-mastodon-server/
2. But an error occured when making admin. It's about Redis.
3. When I copied generated .env.production content and pasted in .env.production(it was empty), it worked.
4. There wasn't any users in my mastodon, so I tried to make admin user with admin CLI.
5. I entered this commands, but it doesn't work with errors:
- `tootctl accounts create admin --email (email) --confirmed --role Owner`
```
Failure/Error: email
    taken
Failure/Error: account.username
    taken
Failure/Error: account.username
    reserved
```

- `tootctl accounts create admin --email (email) --confirmed --role Owner --force`
```
Failure/Error: email
    taken
Failure/Error: account.username
    taken
Failure/Error: account.username
    reserved
```

- `tootctl accounts create admin --email (email) --confirmed --role Owner --force --reattach`
```
Failure/Error: account.username
    reserved
```

### Expected behaviour

It should made the admin user.

### Actual behaviour

It didn't make any users. And it occured errors...

### Mastodon version

v4.2.10

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by ThisIsMissEm** [comment]
The "admin" username is a [reserved username](https://github.com/mastodon/mastodon/blob/main/config/settings.yml#L24) — I'm not sure if it's possible to override that or if we'd want to allow such via the CLI

The `rake mastodon:setup` task explicitly bypasses the validations when creating a user / account, which is why it can create an "admin" user, despite this reserved username validation

**Comment by ThisIsMissEm** [comment]
You best bet is probably to go via the rails console at the moment (`rails c`) and first look for an Account with the given username: `Account.find_local('admin')`, if none exists, then you could do:

```ruby
email = '...'
password = '...'
owner_role = UserRole.find_by(name: 'Owner')
user = User.new(email: email, password: password, confirmed_at: Time.now.utc, account_attributes: { username: 'admin' }, bypass_invite_request_check: true, role: owner_role)
user.save(validate: false)
user.approve!

Setting.site_contact_username = 'admin'
```

You can enter the above line by line into the rails console.
