### ISSUE TITLE
There isn't a time zone setting available for Eastern Daylight Time (EDT)

### ISSUE THREAD

**Issue by PrivacyFriendlyMuffins** [mastodon/mastodon#30955]
### Steps to reproduce the problem

1. Go into Preferences.
2. Look at the dropdown list for time zones, found at the top.

### Expected behaviour

There should be a `(GMT-04:00) Eastern Daylight Time` or something of the like.

### Actual behaviour

The only GMT-04:00 time zone is Atlantic Time, which is not used in the continental US, even if functionally identical to EDT.

### Detailed description

My current time zone is Eastern Daylight Time, or UTC-4. However, in Settings, there is only GMT-4 as Atlantic Time as the closest option.

Although they are quantitatively the same values, there is a qualitative difference between Atlantic Time and Eastern Daylight Time, the former of which is only used outside the contiguous United States.

I admit this is potentially a nitpick, but it could also confuse new users (myself included), which I think is a clear reason to consider it.

&nbsp;

---
**EDIT**: A thing occurred to me while writing another issue here (see #30956): I suppose it could also be that the system is using GMT-5 as referencing that geographical area, as opposed to being equivalent to UTC-5. In other words, the time zone is just the nominal time zone designated to that area, with a DST offset automatically put in. Is this the case?

### Mastodon instance

retro.pizza

### Mastodon version

v4.2.10

### Browser name and version

LibreWolf 127.0.2-2

### Operating system

Windows 10 Home, version 22H2

### Technical details

I'm not the server admin, merely a user. But if there are any things I can provide that anyone might need, just ask and I'll do my best. :)

**Comment by mjankowski** [comment]
There is an option of `(GMT-05:00) Eastern Time (US & Canada)` which is probably what you want?
