### ISSUE TITLE
Remove "Top Active Servers" from Admin Dashboard page to reduce unnecessary server load.

### ISSUE THREAD

**Issue by brookmiles** [mastodon/mastodon#31017]
### Pitch

Remove "Top Active Servers" from Admin Dashboard page.

### Motivation

As I and others have observed https://github.com/mastodon/mastodon/issues/31014, the Top Active Servers display on the Admin Dashboard page causes excessive load on the server CPU, occupying one or more CPU for minutes at a time, potentially up to an hour depending on hardware specs, database size, system load, etc.

This is particularly problematic on servers already running at or over their CPU capacity during surges, as an admin simply using the Admin menu to administer the server, post announcements, etc. can't easily avoid continually triggering costly database queries which serve no purpose, especially since the admin will likely never see results of the query even if they wanted to.

**Comment by ThisIsMissEm** [comment]
Opened a PR for this here since it's a straight forwards change UI-wise: https://github.com/mastodon/mastodon/pull/31020
