### ISSUE TITLE
Mentioned handles are rendered as plaintext without link if the sharp s ('ß') character appears in the previous word

### ISSUE THREAD

**Issue by Schlaftablette** [mastodon/mastodon#31021]
### Steps to reproduce the problem

1. Write a post with the following content and send it

`Gemäß @Gargron@mastodon.social`

### Expected behaviour

The handle is rendered with a link to the profile: Gemäß @Gargron

### Actual behaviour

The handle is rendered as plaintext: Gemäß @Gargron@mastodon.social

### Detailed description

Apparently when a handle is mentioned after a "ß" (sharp s) character it is always rendered as plaintext.

Please find the following post where it was first observed:
https://nrw.social/@melsdung/112784007422571926

The issue could also be reproduced with the 3rd party app "Tusky" using mastodon.online.

### Mastodon instance

mastodon.online and nrw.social

### Mastodon version

v4.2.10 (nrw.social) and v4.3.0-nightly.2024-07-11 (mastodon.online)

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by adamniedzielski** [comment]
Interesting bug. It only happens when `ß` is the last character before the handle. It also doesn't happen to other special characters in German (for example `ä`)
<img width="606" alt="Screenshot 2024-07-24 at 13 21 47" src="https://github.com/user-attachments/assets/079bf096-5b19-4a53-a73a-4cfbe0b34809">
