### ISSUE TITLE
Show moderator actions also in the UI (incl. an API), instead of only by email

### ISSUE THREAD

**Issue by joenepraat** [mastodon/mastodon#31024]
### Pitch

When giving a user a warning or after other moderator actions, an email is send to the user. The problem is that not all users check their email very often or they used an anti-spam email address during signing up.

I suppose to show the content of moderator emails as a notification.

### Motivation

If the user won't see moderator emails, they will not have the option to reflect on their own behavior. Some users will only notice what they missed when they are suspended or when their account is frozen.

**Comment by ClearlyClaire** [comment]
This has already been implemented in #30065
