### ISSUE TITLE
Please require clicking on something to show the profile popup

### ISSUE THREAD

**Issue by Jolly-Friend-9876** [mastodon/mastodon#31025]
### Pitch

Please require something like clicking an ellipsis button near the profile name to show the profile popup recently implemented.

### Motivation

If you are in your timeline and are scrolling with your mouse wheel, if you aren't exactly over the scrollbar, you now get those profile popups obscuring the content. And sometimes you are over the popup itself, so your scrolling through your timeline stops cold, and you have to repoint your mouse. During timeline browse, I will know when I want to learn more about the person to see the popup; otherwise it should not show by default to ruin the content browsing experience.

**Comment by vmstan** [comment]
https://github.com/mastodon/mastodon/pull/30931 made hover cards optional.
