### ISSUE TITLE
Mastodon rejects multiple rel=self links in webfinger, breaching webfinger spec

### ISSUE THREAD

**Issue by CutestNekoAqua** [mastodon/mastodon#31084]
### Steps to reproduce the problem

1. implement webfinger endpoint with multiple ``rel: self`` entries in the ``links`` array, but using different ``type``s (example: application/json & application/activity+json)
2. query it using mastodon (for example @aprl@social.lysand.org), see that the user isnt resolved
3. query webfinger yourself, and see that there are multiple rel tags indeed (for example: https://social.lysand.org/.well-known/webfinger?resource=acct:aprl@social.lysand.org )

### Expected behaviour

Mastodon picks rel=self with type=application/activity+json

### Actual behaviour

mastodon shits itself

### Detailed description

This is valid, in spec webfinger, and thus every other fedi server for example akkoma and misskey support such webfinger, but mastodon discards it as invalid for some reason. I did not find the place in code yet but this issue has been around for a long time but never got fixed. Afaik this breaches webfinger spec because the spec never mentions there only being one rel=self tag. it instead should scan for a rel=self & type=application/activity+json tag

### Mastodon instance

any

### Mastodon version

v4.2.10

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by CutestNekoAqua** [comment]
Fyi I am willing to throw some money at the person fixing this, if this is fixed in the next weeks, because this is a really annoying bug and I would fix it myself but I cant be bothered enough to learn ruby.

**Comment by CutestNekoAqua** [comment]
How do i best add a bounty to this? https://gitpay.me?

**Comment by ClearlyClaire** [comment]
It seems that our code indeed does not look at the `type` of links, and does not correctly handle multiple links with the same `rel` attribute, and in practice will use the last value:
https://github.com/mastodon/mastodon/blob/ced5e853c7d7c7f2b849d904964ef92e93ad27c8/app/lib/webfinger.rb#L28-L30

I'm a bit surprised by this, but that's what the current code does.

Unfortunately, there is no real specification for ActivityPub actor links in webfinger, but the closest to that is our own documentation, which mentions `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` and `application/activity+json` types: https://docs.joinmastodon.org/spec/webfinger/

I think we should change our code to pick a link with a preference to these types, and fallback to anything for backward compatibility.

**Comment by CutestNekoAqua** [comment]
I dont think mastodon should "fall back" to using any random rel=self if type isnt found, just simply for the reason of that encouraging bad webfinger impls. I am a big ally of strong standards vs. loosely defined ones.

PS: sorry if this is a bit unreadable, cant be bothered to markdown after midnight ^,^'

**Comment by ClearlyClaire** [comment]
I was suggesting that for backward compatibility, under the assumption were not currently checking the types. But as I pointed out in the edit, we do in fact check the type already, so I see no reason to change that. What needs to be done is to filter/select the correct link instead of just considering the last one.
