### ISSUE TITLE
Group notifications have unrequired margin-left/padding-left

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#31090]
### Pitch

Original
![image](https://github.com/user-attachments/assets/7e74483d-99a9-4104-af5d-fdc9f5cf0fd1)

alpha group
![image](https://github.com/user-attachments/assets/ad17b6ea-3514-4ffb-bddc-e05e302e9531)

`$icon-margin: 48px;` is adding a weird left padding.

https://github.com/mastodon/mastodon/blob/23a37308503ff2d384fed662542bd8dd5a86e6a7/app/javascript/styles/mastodon/components.scss#L10537-L10551

**Fixed**
![image](https://github.com/user-attachments/assets/f36b25fd-6b34-451b-bade-a3f1ababd91e)

![image](https://github.com/user-attachments/assets/6b6358ce-f73d-4c89-9283-3e2a3566c25a)

### Motivation

I really like the additional metadata with "X mentioned you"... but the gap is annoying

**Comment by renchap** [comment]
This is as intended by our designer. We plan (someday) to rework how posts are displayed in the main timeline, and have a left gutter there as well.

**Comment by shleeable** [comment]
Yikes.

**Comment by shleeable** [comment]
![image](https://github.com/user-attachments/assets/259baa8d-100a-42e4-8213-e14682b57148)
![image](https://github.com/user-attachments/assets/d1bb2f60-33f6-4442-92d4-7f76c85afe1b)
