### ISSUE TITLE
Feature to search inside one's account

### ISSUE THREAD

**Issue by RZHSSNZDH** [mastodon/mastodon#31112]
### Pitch

I think it is a neccessery feature that user to be able to search inside one's account, between his/her toots.

### Motivation

In discussions sometimes one needs to refer the others to a toot which knows the sender of it. Finding it would be very easier if there is the feature.

**Comment by p37307** [comment]
Go to the search box, enter **from:me SEARCHTEXT** 

Add **in:library** if you want to search for posts you've interacted with.

If Advanced search options is enabled on your instance, there are more operators.

If you want to search within a reply, search "from:me is:reply SEARCHTEXT"

You can add 
has:media, before:date, during:date, after:date and other operators. Date format is YYYY-MM-DD.
