### ISSUE TITLE
Show number of views

### ISSUE THREAD

**Issue by tenebrios** [mastodon/mastodon#31132]
### Pitch

Under each post it should show the number of views. This would pertain more to video posts.
It should be viewable for all to see.

### Motivation

It would show how popular a page is and how many are looking.

**Comment by renchap** [comment]
This is not possible to accurately track this metric because Mastodon is federated.

Additionally, this would cause privacy and performance problems.

Closing as not planned.

**Comment by tenebrios** [comment]
> This is not possible to accurately track this metric because Mastodon is federated.
> 
> Additionally, this would cause privacy and performance problems.
> 
> Closing as not planned.

I see Twitter shows the views but...ok then

**Comment by MadokVaur** [comment]
> I see Twitter shows the views but...ok then

Twitter is one monolithic social media site under the single control of that fascist Elon Musk

There are currently some 10,771 different, autonomous, active Mastodon servers

Here: https://fedidb.org/software/mastodon

See any difference between the two?

**Comment by tenebrios** [comment]
> > I see Twitter shows the views but...ok then
> 
> Twitter is one monolithic social media site under the single control of that fascist Elon Musk
> 
> There are currently some 10,771 different, autonomous, active Mastodon servers
> 
> Here: https://fedidb.org/software/mastodon
> 
> See any difference between the two?

It really doesn't matter what you want to label him as. Anyone in power is corrupt in some way.
gates being one of the worst.

I do believe we are close to something like the gov "shutting off" apps like fb, Twitter, YouTube etc.
Can the same happen with Mastodon? Can they shut it off?

**Comment by colinstu12** [comment]
> I do believe we are close to something like the gov "shutting off" apps like fb, Twitter, YouTube etc.
> Can the same happen with Mastodon? Can they shut it off?

1 domain vs 10000 domains.... I think you just answered your own question as to which one is easier to shut down.

**Comment by tenebrios** [comment]
> > I do believe we are close to something like the gov "shutting off" apps like fb, Twitter, YouTube etc.
> > Can the same happen with Mastodon? Can they shut it off?
> 
> 1 domain vs 10000 domains.... I think you just answered your own question as to which one is easier to shut down.

I was hoping that would be the case but can they over reach and do something like contact the ceo and demand the whole platform turned off?

**Comment by colinstu12** [comment]
> I was hoping that would be the case but can they over reach and do something like contact the ceo and demand the whole platform turned off?

Nobody is beholden to Mastodon or their CEO or any of that. Not to mention this 'platform' is just one of many that are part of the ActivityPub protocol, which is a part of the even greater Fediverse. There's no just "shutting it all down". 

It's all open source, it can all be forked and further changed etc as needed if some issue does come up and maintainers/contributors are MIA.

**Comment by tenebrios** [comment]
This is good to hear. Great to hear.
We'd have a way to communicate and be in the loop should the powers that be do something nefarious with the other apps like fb.
