### ISSUE TITLE
Incorrect title for embed card

### ISSUE THREAD

**Issue by ianh** [mastodon/mastodon#31140]
### Steps to reproduce the problem

1. View this post while logged in to mastodon.social: https://mastodon.social/@irene@discuss.systems/112181463045792188

### Expected behaviour

The embed card displays the title of the page

### Actual behaviour

The embed card displays a different title

### Detailed description

The text in the displayed title is the title of a different post from the same domain which has also been posted to Mastodon.

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-07-25

### Browser name and version

Safari 17.4.1

### Operating system

macOS 12.7.3

**Comment by adamniedzielski** [comment]
I tried to reproduce the bug locally, but with no success

<img width="634" alt="Screenshot 2024-07-25 at 10 59 04" src="https://github.com/user-attachments/assets/91e5947e-8eeb-47c4-a971-ed8c812dd442">

**Comment by ianh** [comment]
Here's what it looks like to me on mastodon.social, for the record: ![image](https://github.com/user-attachments/assets/39d8b8c2-a4de-4833-8eab-f07d44a5e9a0)

**Comment by c960657** [comment]
The linked page, https://irenezhang.net/blog/2024/03/27/msr.html, contains the following:
```
<link href="https://irenezhang.net/" rel="canonical">
```
It basically states that https://irenezhang.net/blog/2024/03/27/msr.html is equivalent to https://irenezhang.net, and hence the two pages share the same preview card.

The owner of the website should fix this issue.

**Comment by mjankowski** [comment]
Closing on assumption (from last comment) that we actually are parsing this correctly per expected rules, and its a one-off issue with this page. Please reopen if I'm missing something here and there's more to do.
