### ISSUE TITLE
Rspec Runtime Errors From email_spec Dependency

### ISSUE THREAD

**Issue by timothyjrogers** [mastodon/mastodon#31197]
### Steps to reproduce the problem

1. Create a dev environment using Vagrant, per [Setting up a dev environment](https://docs.joinmastodon.org/dev/setup/)
2. Execute the `rspec` tests (`vagrant ssh -c "cd /vagrant && rspec"`)
3. Observe errors in output

### Expected behaviour

Rspec tests run without runtime errors from the test framework itself

### Actual behaviour

Rspec fails with an error bubbled up from the email_spec dependency

### Detailed description

I have provided an output example below executing a single test for brevity, but the error occurs when running the full test suite as well. I have not reproduced in a non-Vagrant dev environment but nothing about this scenario seems specific to Vagrant.

```
mastodon>vagrant ssh -c "cd /vagrant && rspec ./spec/routing/accounts_routing_spec.rb:9"
Resolving dependencies...
[dotenv] Set ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY, ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT, and ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
[dotenv] Loaded .env.development

An error occurred while loading ./spec/routing/accounts_routing_spec.rb.
Failure/Error: require 'email_spec/rspec'

NameError:
  uninitialized constant EmailSpec
# /usr/share/rvm/gems/ruby-3.3.4@mastodon/gems/email_spec-2.3.0/lib/email_spec/rspec.rb:2:in `block in <top (required)>'
# /usr/share/rvm/gems/ruby-3.3.4@mastodon/gems/email_spec-2.3.0/lib/email_spec/rspec.rb:1:in `<top (required)>'
# /usr/share/rvm/gems/ruby-3.3.4@mastodon/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
# /usr/share/rvm/gems/ruby-3.3.4@mastodon/gems/zeitwerk-2.6.16/lib/zeitwerk/kernel.rb:34:in `require'
# ./spec/rails_helper.rb:44:in `<top (required)>'
# ./spec/routing/accounts_routing_spec.rb:3:in `<top (required)>'
Run options: include {:locations=>{"./spec/routing/accounts_routing_spec.rb"=>[9]}}

All examples were filtered out
 0/0 |============================================ 100 ============================================>| Time: 00:00:00

Finished in 0.00042 seconds (files took 6.25 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
Coverage report generated for RSpec to /vagrant/coverage. 1156 / 41014 LOC (2.82%) covered.
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
```

### Mastodon instance

local

### Mastodon version

main

### Technical details

Happening in local development environment (Vagrant)

**Comment by timothyjrogers** [comment]
This came up while adding some new tests, but thinking back I've seen all the examples get skipped on most if not all the fixes I've submitted. That leads me to think this has been impacted for awhile, I just wasn't familiar with rspec to realize what it was doing.

Adding the following three additional `require`s to https://github.com/mastodon/mastodon/blob/main/spec/rails_helper.rb fixes the issue, although I'm not sure if there's some underlying reason why they were removed or previously unnecessary. After adding the `email_spec` requiremenet additional dependency errors manifest as you move through `rails_helper.rb`, ultimately requiring the other two.

```
require 'rspec-sidekiq'
require 'email_spec'
require 'database_cleaner/active_record'
```

I'll open a PR adding these in unless someone has a more correct solution. If the `rspec` tests were just broken I would hope someone else noticed it and maybe it's specific to the current Vagrantfile or something?

**Comment by timothyjrogers** [comment]
@mjankowski  very kindly pointed out you need to set `RAILS_ENV=test` in order for the test dependencies to be pulled in, so this is actually not a functional problem for the tests. Big thank you to them.

I'm not sure if there's a more detailed page somewhere on running the test suites -- I've just been referencing [Setting up a dev environment](https://docs.joinmastodon.org/dev/setup/) which just calls out running `rspec`. Maybe it would be worth calling out `RAILS_ENV=test rspec` like it does for database migrations (`RAILS_ENV=development rails db:migrate
`) on that page. It's also possible Ruby/Rails folk are just in the habit of doing that, which I'm not.

**Comment by mjankowski** [comment]
Glad that helped ... and yeah, the typical/standard rails app expectation would be that you do NOT set this env var at all for local testing and development. When you run the test suite, they see the var not set, set it to test mode, then run themselves. When you run dev server, it sees it not set, sets to development, runs.

However, we have a check in the boot process which insists that the env var be set to proceed -- this is to mitigate apparent historical issues where people were accidentally running their production servers in dev mode (I think?) -- and it has this side effect of upending some normal expectations in that regard.

The issue you had here is basically the same as the issue in devcontainers linked issue ... and will be "solved" by the same thing, if it gets merged (always setting to `test` env in spec helper).
