### ISSUE TITLE
Table rendering issues with new Hashtag moderation search view

### ISSUE THREAD

**Issue by vmstan** [mastodon/mastodon#31212]
### Steps to reproduce the problem

Table is using `.batch-table` but without a toolbar or any options, so the top of the table doesn't render in the new admin theme.

<img width="830" alt="image" src="https://github.com/user-attachments/assets/34884d29-9bb9-4311-8c80-a9ae23e455f3">

### Expected behaviour

Border complete

### Actual behaviour

Incomplete border

### Mastodon instance

vmst.io

### Mastodon version

v4.3.0-alpha

### Browser name and version

All

### Operating system

All

**Comment by vmstan** [comment]
@ThisIsMissEm I was looking at creating a dedicated the table styling here as an option to fix this, but wasn't sure if there were additional enhancements that would make the existing batch-table styling more appropriate.

**Comment by ThisIsMissEm** [comment]
Yeah, as I noted in the pull request, I wasn't super happy with using the `.batch-table` and similar classes in various parts. I guess in the future maybe we may want a batch table here, I'm just not sure right now.
