### ISSUE TITLE
Notifications not generated for mention received from NodeBB

### ISSUE THREAD

**Issue by julianlam** [mastodon/mastodon#31230]
### Steps to reproduce the problem

1. [NodeBB] Create a new post and tag a user on a mastodon instance (in this case, it was @julian@bb.devnull.land to @devnull@crag.social)
2. [Mastodon] Navigate to the sender's profile (https://crag.social/@julian@bb.devnull.land)
3. [Mastodon] Note that the post has been correctly received, and contains a mention, but that your notification inbox remains empty

### Expected behaviour

I should have been notified due to the mention

### Actual behaviour

I was not notified

### Detailed description

Additional details here: https://community.nodebb.org/topic/18210/mentions-and-notifications-over-the-fediverse

Here is the full Note object containing two mentions, when queried via S2S API:

```
{
	"@context":"https://www.w3.org/ns/activitystreams",
	"id":"https://bb.devnull.land/post/72",
	"type":"Note",
	"to":[
		"https://www.w3.org/ns/activitystreams#Public",
		"https://bb.devnull.land/uid/1"
	],
	"cc":[
		"https://bb.devnull.land/uid/1/followers",
		"https://crag.social/users/devnull",
		"https://activitypub.academy/users/babeta_zondaist"
	],
	"inReplyTo":"https://bb.devnull.land/post/71",
	"published":"2024-07-30T02:49:42.616Z",
	"url":"https://bb.devnull.land/post/72",
	"attributedTo":"https://bb.devnull.land/uid/1",
	"context":"https://bb.devnull.land/topic/38",
	"audience":"https://bb.devnull.land/category/-1",
	"sensitive":false,
	"summary":null,
	"name":"Re: Testing a notification",
	"content":"<p>no context or audience <a href=\"https://crag.social/@devnull\">@devnull@crag.social</a> <a href=\"https://activitypub.academy/@babeta_zondaist\">@babeta_zondaist@activitypub.academy</a></p> ",
	"source":{
		"content":"no context or audience @devnull@crag.social @babeta_zondaist@activitypub.academy",
		"mediaType":"text/markdown"
	},
	"tag":[
		{
			"type":"Mention",
			"href":"https://crag.social/users/devnull",
			"name":"@devnull@crag.social"
		},
		{
			"type":"Mention",
			"href":"https://activitypub.academy/users/babeta_zondaist",
			"name":"@babeta_zondaist@activitypub.academy"
		}
	],
	"attachment":[
	],
	"replies":[
	]
}
```

### Mastodon instance

crag.social, mastodon.social

### Mastodon version

v4.2.10

### Technical details

`crag.social` is hosted via masto.host, but @trwnh, who originally notified me of this issue, has an account on `mastodon.social`.

I was directed to post an issue here by @renchap

**Comment by julianlam** [comment]
@renchap most recently, see your post from today, and the reply that was received, but you were probably not notified about: https://oisaur.com/@julian@community.nodebb.org/112882228388222052

**Comment by ClearlyClaire** [comment]
Hi! Are you able to share the `Create` activity that is sent to Mastodon?

**Comment by ClearlyClaire** [comment]
My hunch was that you were hitting a Mastodon quirk that requires mentioned actors to also be in `to` or `cc` for notifications to get generated (`silenced_account_ids` in `ActivityPub::Activity::Create#process_audience` which is then passed down to `FanOutOnWriteService#notify_mentioned_accounts!`), but the activity above does seem to have mentioned users in `cc`, so I'm not sure what may be happening.

I will temporarily add some instrumentation to my server to try and debug that.

**Comment by ClearlyClaire** [comment]
@julianlam can you try mentioning `@Claire@sitedethib.com` from the same account as in your previous example?

**Comment by julianlam** [comment]
@ClearlyClaire I tried (afk at the moment) but sitedethib.com's webfinger endpoint is serving a `.bin` and so the actor assertion on my end fails

**Comment by ClearlyClaire** [comment]
A `.bin`? It returns a redirect. Try `@Claire@social.sitedethib.com` if NodeBB doesn't handle redirects yet.

**Comment by julianlam** [comment]
Got it, that worked 🙂 post sent

**Comment by ClearlyClaire** [comment]
Thanks, got the post and some debug output, but no notification! And it's not hitting the code path I thought :thinking:

Will investigate some more and will get back to you when I have an explanation.

**Comment by ClearlyClaire** [comment]
Ah, there's actually a crash I did not notice, before it gets to distributing the posts to notifications and timelines!

Mastodon chokes on the empty array `replies` attribute, while it expects a `Collection` (either embedded or just an URI of one).

**Comment by julianlam** [comment]
Oh, now that's interesting, because I didn't even think of that. 

I went from not sending `replies` at all to sending a potentially 404'ing URI:

![image](https://github.com/user-attachments/assets/8b02c63f-e842-421b-8a9f-33f5eb61c214)

and from there, to send a `[]` if there weren't any replies:

![image](https://github.com/user-attachments/assets/e4fe539b-be7d-4d82-b780-00a2f1466ff1)

... but I didn't actually think about whether `[]` was the correct data structure. I'll swap that out with a `null` and report back.

**Comment by julianlam** [comment]
![image](https://github.com/user-attachments/assets/8812947f-0334-4ff8-b2b7-a2b9751e663d)

Confirmed working.

It's entirely up to you whether you'd like to leave this issue open. Could be Mastodon could better handle bad data structures for `replies`, but looks like this one was on me :sweat_smile:

**Comment by ClearlyClaire** [comment]
Yeah, leaving this open because I'm thinking about making error handling a little more robust here.

**Comment by julianlam** [comment]
Thank you so much for your time and attention!
