### ISSUE TITLE
Multiple values for TRUSTED_PROXY_IP?

### ISSUE THREAD

**Issue by jernst** [mastodon/mastodon#31260]
### Steps to reproduce the problem

I'm attempting to have both link-local IPv6 addresses and IPv4 localhost as `TRUSTED_PROXY_IP`s. I observe:

The following statements work as expected in `.env.production`:

* `TRUSTED_PROXY_IP=fe80::/10`
* `TRUSTED_PROXY_IP=127.0.0.1`

The following statements do not do anything for either address:

* `TRUSTED_PROXY_IP=fe80::/10,127.0.0.1`
* `TRUSTED_PROXY_IP=fe80::/10, 127.0.0.1`
* `TRUSTED_PROXY_IP=fe80::/10 127.0.0.1`
* `TRUSTED_PROXY_IP="fe80::/10,127.0.0.1"`
* `TRUSTED_PROXY_IP="fe80::/10, 127.0.0.1"`
* `TRUSTED_PROXY_IP="fe80::/10 127.0.0.1"`

From the code (but I'm not a Ruby guy) it appears to me it should accept more than one value, separated by whitespace and an optional comma. (I don't know about the quotes.)

### Expected behaviour

Able to specify more than one value

### Actual behaviour

Specifying more than one value is as if nothing was specified at all

### Mastodon instance

my own test installation

### Mastodon version

v4.2.10

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.0.6p216 (from Arch Linux)
- Node.js version: v20.16.0

**Comment by ClearlyClaire** [comment]
All of your examples should be working as intended. How did you come to the conclusion that it was not working? How (docker, bare installation, dev environment, …) are you running Mastodon?

**Comment by jernst** [comment]
Context: automated installation of Mastodon (and other Fediverse server-side apps) in a Linux systemd-nspawn container for the purposes of testing running them against each other with https://feditest.org/. It works fine for the purposes of the automated test, but if the user uses a browser to attempt to access the/one of the Mastodon instance(s) in the container from the host while the test is running (we have a `feditest run --interactive` mode for debugging), depending on their networking setup, they cross that local host-container virtualized network interface with either IPv4 or IPv6.

Re "how did you come to the conclusion it wasn't working"? I tried 127.0.0.1 and got an error in the log that the link-local ipv6 address couldn't be parsed (ActiveRecord), then I tried fe80::/10 and got an error that 127.0.0.1 wasn't allowed, then I tried the setting with both values and got both errors.

I'm closing this, however, because I seem to have found a configuration that works well enough for our purposes, and this is likely not going to be of interest to a lot of other parties...

**Comment by ClearlyClaire** [comment]
> Re "how did you come to the conclusion it wasn't working"? I tried 127.0.0.1 and got an error in the log that the link-local ipv6 address couldn't be parsed (ActiveRecord)

I'm curious to see the error, `ActiveRecord` should not be involved here. But maybe there's something specific with link-local addresses.

**Comment by jernst** [comment]
The link-local issue: #24891
