### ISSUE TITLE
Follows don't have a bottom border separator?

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#31272]
### Steps to reproduce the problem

1. Receive a mention
2. Receive a follow

### Expected behaviour

There should be a line between them

### Actual behaviour

There is not a line between them

### Detailed description

![image](https://github.com/user-attachments/assets/b897d1e2-4c78-4c66-83e7-fa65e05e2da9)

![image](https://github.com/user-attachments/assets/ef9ddd4e-bec4-4088-8bdc-a4588eb7e819)

### Info

mastodon.social
v4.3.0-nightly.2024-08-01
Firefox 129.0b9

**Comment by renchap** [comment]
Closing, this should have been fixed
