### ISSUE TITLE
 setup Mastodon , didn't work. I ended up with blank front page

### ISSUE THREAD

**Issue by qiancsff** [mastodon/mastodon#31281]
### Steps to reproduce the problem

 setup Mastodon , didn't work. I ended up with blank front page (only Mastodon logo was shown). Then I reinstalled whole server with debian11(https://docs.joinmastodon.org/admin/install/)
 I've tried this sudo usermod -a -G www-data mastodon but didn't work. Thanks for your help

sudo chmod +rx /home/mastodon/

Localhost: 80 cannot open website
Open localhost: 3000 and only see mastodon log
Why is it that www.xxx.com can open the website on this machine?

**Comment by renchap** [comment]
This means that the static JS/CSS files are not being server. You should be able to confirm this using your browser console. What do you see here?

I am not sure what is happening here, but I suspect this is due to your setup. Does it work when you are not using Cloudflare tunnels? 

Do you have CSS and Javascript files in `public/packs/` ?

**Comment by qiancsff** [comment]
Localhost: 80 cannot open website
Open localhost: 3000 and only see mastodon log
Why is it that www.xxx.com can open the website on this machine?

**Comment by hidetoshi-tamaki** [comment]
Hello,

I am experiencing the same issue. I set up the system from scratch using Ubuntu 22.04.4 LTS, following the steps in this guide: https://docs.joinmastodon.org/admin/install/.

> This means that the static JS/CSS files are not being served. You should be able to confirm this using your browser console. What do you see here?

In the browser console, I see several 404 errors for JS and CSS files. Here is the relevant data from the console:

```
strict MIME checking is enabled.
example.com/:1 Refused to apply style from 'https://example.com/packs/css/common-a729b6b0.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
example.com/:1 Refused to apply style from 'https://example.com/inert.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
example.com/:1 Refused to apply style from 'https://example.com/packs/css/default-df299a32.chunk.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
example.com/:1 Refused to apply style from 'https://example.com/inert.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
example.com/:1 Refused to apply style from 'https://example.com/packs/css/common-a729b6b0.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```
(Note: I replaced the actual domain with example.com.)

> Do you have CSS and JavaScript files in public/packs/?

Yes, I can see several files here. I have "common-a729b6b0.css" and "default-df299a32.chunk.css" in the css folder. However, I do not see "inert.css". Here are the files in public/packs:

```
$ ls /home/mastodon/live/public/packs
css  manifest.json     manifest.json.gz  ocr          sw.js     sw.js.gz   sw.js.map.br
js   manifest.json.br  media             report.html  sw.js.br  sw.js.map  sw.js.map.gz

```
And here are the files in the css folder:

% ls /home/mastodon/live/public/packs/css
common-a729b6b0.css              contrast-ffdc2fd9.chunk.css.map.br  mailer-47e61cac.chunk.css.gz
common-a729b6b0.css.br           contrast-ffdc2fd9.chunk.css.map.gz  mailer-47e61cac.chunk.css.map
common-a729b6b0.css.gz           default-df299a32.chunk.css          mailer-47e61cac.chunk.css.map.br
common-a729b6b0.css.map          default-df299a32.chunk.css.br       mailer-47e61cac.chunk.css.map.gz
common-a729b6b0.css.map.br       default-df299a32.chunk.css.gz       mastodon-light-7cb52d19.chunk.css
common-a729b6b0.css.map.gz       default-df299a32.chunk.css.map      mastodon-light-7cb52d19.chunk.css.br
contrast-ffdc2fd9.chunk.css      default-df299a32.chunk.css.map.br   mastodon-light-7cb52d19.chunk.css.gz
contrast-ffdc2fd9.chunk.css.br   default-df299a32.chunk.css.map.gz   mastodon-light-7cb52d19.chunk.css.map
contrast-ffdc2fd9.chunk.css.gz   mailer-47e61cac.chunk.css           mastodon-light-7cb52d19.chunk.css.map.br
contrast-ffdc2fd9.chunk.css.map  mailer-47e61cac.chunk.css.br        mastodon-light-7cb52d19.chunk.css.map.gz
Please let me know if you need any additional information to help resolve this issue.

**Comment by hidetoshi-tamaki** [comment]
In my case, the issue was resolved by executing the command below with root privileges.

```
# chmod o+x /home/mastodon
```

I'm not sure if this workaround is a safe method, but it would be very helpful if the documentation mentioned this.
Ref: [Fresh install displays only empty pages #5803](https://github.com/mastodon/mastodon/issues/5803)

**Comment by vmstan** [comment]
@qiancsff  Is this still an issue for you?
