### ISSUE TITLE
Ubuntu 22.04.4 LTS installation of Mastodon V4.2.10 , why are there so many warnings, is this normal, and how to resolve these warnings?

### ISSUE THREAD

**Issue by qiancsff** [mastodon/mastodon#31295]
Ubuntu 22.04.4 LTS installation of Mastodon V4.2.10 , why are there so many warnings, is this normal, and how to resolve these warnings?

![222](https://github.com/user-attachments/assets/7d3c1c0f-fd17-4499-9e38-31b38905a289)

**Comment by renchap** [comment]
This is expected, and you can ignore those. This will get better with 4.3.

Closing as this is not a real issue.
