### ISSUE TITLE
"Remote data could not be fetched" error when fetching a post that mentions a defunct account not cached by my instance

### ISSUE THREAD

**Issue by Razem** [mastodon/mastodon#31327]
### Steps to reproduce the problem

Problem 1 - manual fetching:
1. Write a post that mentions a defunct account that is cached by your instance (instance A)
2. Try fetching the post (by searching its URL) on another instance (instance B) where the defunct account is not cached
3. You will get the following error: 503 Remote data could not be fetched

Problem 2 - federation:
1. Have an account (account A) on an instance (instance A) where some defunct account is cached
2. Have an account on another instance (instance B) where the defunct account is not cached
3. Follow account A from account B
4. From account A, write a post that mentions the defunct account
5. This post never reaches instance B, i.e., the post is not visible on account A's profile on instance B

### Expected behaviour

The post should federate / be fetched as expected

### Actual behaviour

The post doesn't federate and cannot be fetched manually, resulting in an error

### Detailed description

**Example:**
The post https://mastodon.pirati.cz/@keddie/112879938095998245 mentions the account `@honza@datastory.cz` (which should lead to https://gts.datastory.cz/users/honza), but it's defunct. The instance **mastodon.pirati.cz** has this account cached, so it can be mentioned without any problems.

However, on the instance **mamutovo.cz**, this account is not cached. So even though I follow the author of the post (`@keddie@mastodon.pirati.cz`), I am not able to see the post on my instance. Attempting to manually fetch the post results in the described error.

### Mastodon instance

mamutovo.cz

### Mastodon version

v4.2.10

### Browser name and version

Google Chrome 127.0.6533.100

### Operating system

Windows 10

**Comment by renchap** [comment]
An attempt at fixing this is here: https://github.com/mastodon/mastodon/pull/29215

**Comment by rrgeorge** [comment]
I am also seeing evidence of this in my sidekiq logs. Frequently I will see a dead `activitypub::ProcessingWorker` with a dns error, where the domain is no longer resolvable. Every single one I've investigated is the result of a mention. See the example status: https://mastodon.social/@Viss/113205416136151127 mentions an account via a (now defunct) twitter mirror, resulting it it only being able to federate to servers that have seen that account (and instance) before.
