### ISSUE TITLE
Home feed shows post from someone I'm not following

### ISSUE THREAD

**Issue by solitha** [mastodon/mastodon#31336]
### Steps to reproduce the problem

I was just browsing my Home feed.

### Expected behaviour

I should be only seeing posts from (or boosted by) those I follow

### Actual behaviour

Random person's post showed up

### Detailed description

Not sure what other details I can offer. I use "Deck" mode. I was just catching up on my feed before signing off for the night and noticed this random person's post in my feed, not a boost. I wondered why I followed him, opened his profile, realized I was not following him. Tried reloading the screen and the post was still there.

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-08-05

### Browser name and version

Firefox 128.0.3

### Operating system

Windows 11 10.2.22631

### Technical details

![firefox_RPJDH0wUmO](https://github.com/user-attachments/assets/4f677ac9-5897-4676-80ff-a501acefa91e)

**Comment by renchap** [comment]
This is most probably because you follow a hashtag, and the post contains this hashtag.

We know this is a common mistake and are looking into ways of better indicating this in the UI.

Closing for now, please reopen if this is not what happened.
