### ISSUE TITLE
CORS Access-Control-Allow-Origin missing in Follow endpoint

### ISSUE THREAD

**Issue by MidnightLightning** [mastodon/mastodon#31350]
### Steps to reproduce the problem

```
curl --location --request OPTIONS 'https://mastodon.social/users/Midnight/following' \
--header 'Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"' \
--header 'Origin: http://example.com'
```

### Expected behaviour

`Access-Control-Allow-Origin` header set with wildcard or the Origin hostname

### Actual behaviour

No `Access-Control-Allow-Origin` field set at all

### Detailed description

In attempting to use pure ActivityPub interfaces to communicate with a Mastodon server, using a standalone web front-end (so adheres to CORS restrictions), JavaScript is able to do a query for the Actor object at `https://mastodon.social/users/Midnight`, but attempting to fetch the `following` Collection fails.

```js
fetch('https://mastodon.social/users/Midnight/following', {
  headers: {
    Accept: 'application/ld+json; profile="https://www.w3.org/ns/activitystreams"'
  }
})
```

Running that in a web browser results in a CORS error as the request attempts to do an OPTIONS preflight check and it fails due to no `Access-Control-Allow-Origin` header

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-08-08

### Technical details

Using the Mastodon-specific API endpoint (`https://mastodon.social/api/v1/accounts/6219/following`) does work, but for attempting to treat a Mastodon server as purely an ActivityPub server, [the specification indicates](https://www.w3.org/TR/activitypub/#following) the `following` Collection SHOULD exist for each Actor, though could be presented as empty if the server wishes to filter based on permission of the requesting user.

**Comment by ThisIsMissEm** [comment]
ActivityPub doesn't actually specify that CORS must be enabled for AP endpoints, the collection does exist, but it isn't available via cross site requests.

Interesting note: the response to CORS requests seems to be a "not found" error, even though the GET would be found..

**Comment by MidnightLightning** [comment]
@ThisIsMissEm Yes, ActivityPub as a standard doesn't mention CORS at all, which means it doesn't say it must be implemented, nor that it must not be implemented. Mastodon already has it implemented in some ActivityPub endpoints, and all the Mastodon-specific API endpoints, so it seems Mastodon as a project is okay with cross-site front-end requests for public data. It seems odd odd to me that they'd implement this only "halfway" and not be uniform.

**Comment by ThisIsMissEm** [comment]
@MidnightLightning okay, sounds like you might know more history on this than me — I had a read through the linked issue but it didn't seem to have any merges of pull requests.

**Comment by MidnightLightning** [comment]
@ThisIsMissEm Yes, the linked issue hasn't had any pull requests that continued on to get merged, but https://github.com/mastodon/mastodon/pull/15695 was proposed as linked to that issue, and eventually got "closed" rather than merged. It became closed because it was not commented-no, nor acted-upon by the maintaining team for 10 months and the project's bot closed it, so no human on the maintaining team seems to have weighed-in on this topic for some time now.

**Comment by vmstan** [comment]
This is something we probably need to look at, I'm closing this one as a duplicate of https://github.com/mastodon/mastodon/issues/10400 but we can also reopen the PR.
