### ISSUE TITLE
Browser crashes on Windows 11

### ISSUE THREAD

**Issue by znmeb** [mastodon/mastodon#31392]
### Steps to reproduce the problem

1. Browse to mastodon.social
2. Log in

### Expected behaviour

Log in and use Mastodon

### Actual behaviour

My home page flashed, then I got a crash.

### Detailed description

![image](https://github.com/user-attachments/assets/67d2a3d9-3cba-4955-980a-26e9dc4df927)

Here's the traceback:

```
TypeError: n is undefined


@https://mastodon.social/packs/js/common-81e30f7b38745cf6b34f.js:2:1357289
@https://mastodon.social/packs/js/common-81e30f7b38745cf6b34f.js:2:112298
e@https://mastodon.social/packs/js/common-81e30f7b38745cf6b34f.js:2:1543509
t.useSyncExternalStoreWithSelector/d</<@https://mastodon.social/packs/js/common-81e30f7b38745cf6b34f.js:2:1543714
useSyncExternalStore@https://mastodon.social/packs/js/common-81e30f7b38745cf6b34f.js:2:1448121
t.useSyncExternalStore@https://mastodon.social/packs/js/common-81e30f7b38745cf6b34f.js:2:1515745
t.useSyncExternalStoreWithSelector@https://mastodon.social/packs/js/common-81e30f7b38745cf6b34f.js:2:1543785
n@https://mastodon.social/packs/js/common-81e30f7b38745cf6b34f.js:2:112339
Ee@https://mastodon.social/packs/js/common-81e30f7b38745cf6b34f.js:2:1357230
mi@https://mastodon.social/packs/js/common-81e30f7b38745cf6b34f.js:2:1441138
jc@https://mastodon.social/packs/js/common-81e30f7b38745cf6b34f.js:2:1500107
yl@https://mastodon.social/packs/js/common-81e30f7b38745cf6b34f.js:2:1489357
bl@https://mastodon.social/packs/js/common-81e30f7b38745cf6b34f.js:2:1489285
ml@https://mastodon.social/packs/js/common-81e30f7b38745cf6b34f.js:2:1489146
ol@https://mastodon.social/packs/js/common-81e30f7b38745cf6b34f.js:2:1485981
cl@https://mastodon.social/packs/js/common-81e30f7b38745cf6b34f.js:2:1486363
Ba@https://mastodon.social/packs/js/common-81e30f7b38745cf6b34f.js:2:1427512
rl/<@https://mastodon.social/packs/js/common-81e30f7b38745cf6b34f.js:2:1483936



LabelRenderer (webpack:///app/javascript/mastodon/features/notifications_v2/components/notification_mention.tsx:43:6)
selector.name] (webpack:///node_modules/react-redux/dist/react-redux.legacy-esm.js:123:36)
useSyncExternalStoreWithSelector (webpack:///node_modules/use-sync-external-store/cjs/use-sync-external-store-with-selector.production.min.js:11:203)
useSyncExternalStoreWithSelector (webpack:///node_modules/use-sync-external-store/cjs/use-sync-external-store-with-selector.production.min.js:11:419)
useDeferredValue (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:178:367)
useMemo (webpack:///node_modules/react/cjs/react.production.min.js:26:308)
useSyncExternalStoreWithSelector (webpack:///node_modules/use-sync-external-store/cjs/use-sync-external-store-with-selector.production.min.js:11:490)
subscription (webpack:///node_modules/react-redux/dist/react-redux.legacy-esm.js:177:6)
LabelRenderer (webpack:///app/javascript/mastodon/features/notifications_v2/components/notification_mention.tsx:39:30)
Nh (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:160:136)
Vk (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:289:336)
tj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:279:391)
tj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:279:322)
tj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:279:179)
Nk (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:270:87)
Ck (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:272:299)
jg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:127:104)
Dk (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:266:272)
```

### Mastodon instance

https://mastodon.social

### Mastodon version

Mastodon v4.3.0-nightly.2024-08-12

### Browser name and version

Firefox 129.0 (64-bit). It also crashes on Edge, Chrome and Vivaldi. It's probably not a browser problem!

### Operating system

Windows 11

**Comment by znmeb** [comment]
I also tried clearing the browser data for Firefox. It didn't help.

**Comment by ClearlyClaire** [comment]
Thanks for your report! This seems to be a bug with the grouped notifications interface when the underlying activity for a notification is missing from the database (this is rare, but can happen for a few reasons). Having a look!

**Comment by ClearlyClaire** [comment]
We are working on a workaround for this issue, but I'm curious how it occurred in the first place.

Since you are on mastodon.social, are you ok with us looking at your recent mentions (we should not have to see their contents, but there is a possibility we might accidentally see them if we look into it)? If so, can you share your mastodon.social username? It is of course completely ok if you do not want us to look at them.

**Comment by znmeb** [comment]
I think I know what happened. I deleted a post with a chain of replies not too long ago. So it's probably looking for the post I deleted or one of the replies to it. Go ahead and check 'AlgoCompSynth'.

**Comment by ClearlyClaire** [comment]
Thanks! We had a quick look! Can you check whether you still have this issue?

**Comment by znmeb** [comment]
It's working now. Thanks! I'll leave this open in case you need to modify the code to cover this edge case.

**Comment by ClearlyClaire** [comment]
Alright, so what happened is a post you were mentioned in got deleted but for some reason the associated notification has not been deleted. Unfortunately, we could not learn when or why it was deleted from what remains in the database. The only other piece of information we can get is which account mentioned you, but I'm not sure that would help us.

Thanks for the report and for your collaboration!
