### ISSUE TITLE
Authorize Interaction padding bug on mobile

### ISSUE THREAD

**Issue by dansup** [mastodon/mastodon#31396]
### Steps to reproduce the problem

1. Open a browser on a iOS device
2. Navigate to a mastodon server
3. Click on the "Follow" button or favourite/boost button while not logged in
4. See the modal with no padding

### Expected behaviour

There should be padding

### Actual behaviour

There was no padding

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-08-12

### Browser name and version

Chrome 127.0.6533.100

### Operating system

macOS 14.4.1

### Technical details

![IMG_6349](https://github.com/user-attachments/assets/ae0107c2-8468-4d22-997f-cd899bbdffc7)

**Comment by ClearlyClaire** [comment]
It seems it can be fixed in two different ways:
- give `.modal-root__modal interaction-modal` `box-sizing: border-box`
- have the padding and borders be defined in the children of `.modal-root__modal interaction-modal` rather than on the container itself, like for the safety modals
