### ISSUE TITLE
While "/api/v1/instance" reports as "language" the one that is set in ".env.production" with "DEFAULT_LOCALE", "/api/v2/instance" does not and always reports "en" instead

### ISSUE THREAD

**Issue by pezcurrel** [mastodon/mastodon#31400]
### Steps to reproduce the problem

Fetching the JSON from "/api/v2/instance" on an instance that has "DEFAULT_LOCALE=it" in its ".env.production" configuration file

### Expected behaviour

I expected the returned JSON to report "languages" as ["it"]

### Actual behaviour

The returned JSON reported "languages" as ["en"]

### Detailed description

While "/api/v1/instance" reports as "languages" the one that is set in ".env.production" with "DEFAULT_LOCALE", "/api/v2/instance" does not and always reports "en" instead.

### Mastodon instance

puntarella.party

### Mastodon version

v4.2.10

**Comment by ClearlyClaire** [comment]
The code for the `languages` property in both endpoints is the same, so I suspect something else is going on. This endpoint can be cached, so perhaps this is a cached version being served?

**Comment by pezcurrel** [comment]
> The code for the `languages` property in both endpoints is the same, so I suspect something else is going on. This endpoint can be cached, so perhaps this is a cached version being served?

Maybe, but how can one know, and solve?

**Comment by ClearlyClaire** [comment]
If I try fetching `https://puntarella.party/api/v2/instance` and look at the HTTP headers, I can see:
`x-cached: STALE`

It suggests this is returning a cached version because the server is errorring out. Can you check for error in `mastodon-web` logs?

**Comment by pezcurrel** [comment]
Thank you :)

Unfortunately i can't, i'm just a user on that instance, but i'm reporting to the admins.

Also, i have to beg your pardon: it's not true i see the problem on my test instance too, i get "languages" -> "[it]" both on API v1 and v2 there; sorry, i got confused, i'm going to edit the bug report.

**Comment by pezcurrel** [comment]
Ok, it's solved, the problem on puntarella.party was due to a typo they made when they applied this hack to increase the max chars per post number, https://fouquet.me/2023/09/22/mastodon-char-limit

So it was not a Mastodon bug, i'm closing it.

Thanks a lot for your help! :)
