### ISSUE TITLE
Images not displaying

### ISSUE THREAD

**Issue by PlayBoxTech** [mastodon/mastodon#31428]
### Steps to reproduce the problem

1. Set locale to en_US.UTF-8
2. install instance following https://docs.joinmastodon.org/admin/install/
3. no images from local instance or remote shows up
...

### Expected behaviour

Images should be showing

### Actual behaviour

All custom images showing a 404 error

### Detailed description

Images such as https://galegale.online/system/accounts/avatars/112/958/259/072/853/781/original/00f9636cb240530d.jpg are showing up as a 404 error, checked the directory it should be in: /home/mastodon/live/public/system/accounts/avatars/112/958/259/072/853/781/original and found it has the permissions 644. 

### Mastodon instance

galegale.online

### Mastodon version

4.2.10

### Browser name and version

Firefox 129.0.1

### Operating system

Endeavour, Windows 11

### Technical details

Likely related nginx error log is getting a ton of Permission denied errors: 
2024/08/14 14:26:30 [crit] 35368#35368: *5292 stat() "/home/mastodon/live/public/system/cache/accounts/avatars/112/959/128/178/019/541/original/b41160344379cc6a.jpg" failed (13: Permission denied), client: 98.34.202.46, server: galegale.online, request: "GET /system/cache/accounts/avatars/112/959/128/178/019/541/original/b41160344379cc6a.jpg HTTP/2.0", host: "galegale.online"
2024/08/14 14:26:30 [crit] 35368#35368: *5292 stat() "/home/mastodon/live/public/500.html" failed (13: Permission denied), client: 98.34.202.46, server: galegale.online, request: "GET /system/cache/accounts/avatars/112/959/128/178/019/541/original/b41160344379cc6a.jpg HTTP/2.0", host: "galegale.online"
2024/08/14 14:26:30 [crit] 35368#35368: *5292 stat() "/home/mastodon/live/public/system/cache/media_attachments/files/112/960/734/903/844/273/small/b29af8a866817ab9.jpg" failed (13: Permission denied), client: 98.34.202.46, server: galegale.online, request: "GET /system/cache/media_attachments/files/112/960/734/903/844/273/small/b29af8a866817ab9.jpg HTTP/2.0", host: "galegale.online"
2024/08/14 14:26:30 [crit] 35368#35368: *5292 stat() "/home/mastodon/live/public/500.html" failed (13: Permission denied), client: 98.34.202.46, server: galegale.online, request: "GET /system/cache/media_attachments/files/112/960/734/903/844/273/small/b29af8a866817ab9.jpg HTTP/2.0", host: "galegale.online"
2024/08/14 14:26:31 [crit] 35368#35368: *5291 stat() "/home/mastodon/live/public/sw.js" failed (13: Permission denied), client: 98.34.202.46, server: galegale.online, request: "GET /sw.js HTTP/2.0", host: "galegale.online"
2024/08/14 14:26:31 [crit] 35368#35368: *5291 stat() "/home/mastodon/live/public/500.html" failed (13: Permission denied), client: 98.34.202.46, server: galegale.online, request: "GET /sw.js HTTP/2.0", host: "galegale.online"
2024/08/14 14:26:38 [crit] 35368#35368: *5301 stat() "/home/mastodon/live/public/inbox" failed (13: Permission denied), client: 65.21.187.247, server: galegale.online, request: "POST /inbox HTTP/1.1", host: "galegale.online"
2024/08/14 14:26:57 [crit] 35368#35368: *5303 stat() "/home/mastodon/live/public/inbox" failed (13: Permission denied), client: 94.130.174.59, server: galegale.online, request: "POST /inbox HTTP/1.1", host: "galegale.online"
2024/08/14 14:27:54 [crit] 35368#35368: *5305 stat() "/home/mastodon/live/public/inbox" failed (13: Permission denied), client: 65.21.187.247, server: galegale.online, request: "POST /inbox HTTP/1.1", host: "galegale.online"
2024/08/14 14:28:00 [crit] 35368#35368: *5307 stat() "/home/mastodon/live/public/inbox" failed (13: Permission denied), client: 128.140.121.34, server: galegale.online, request: "POST /inbox HTTP/1.1", host: "galegale.online"

**Comment by renchap** [comment]
The most probable reason is that the user `nginx` is running under does not have `r` or `x` permission to the `public` directory, or one of its parents.

**Comment by renchap** [comment]
The `public` directory permissions should probably be `755`.

Maybe look at the permissions for the `/home/mastodon`?

**Comment by PlayBoxTech** [comment]
OK that was it, somehow /home/mastodon only had 750, setting it to 755 fixed the issue.
