### ISSUE TITLE
All users can see locally displayed popular theme tags instead of alliance theme tags

### ISSUE THREAD

**Issue by qiancsff** [mastodon/mastodon#31438]
All users can see locally displayed popular theme tags instead of alliance theme tags
(Enable trends "and"... without approval "options:/deploy/tags/admin/settings/discovery enabled)
The current problem is: I have tags locally, but they are not displayed under the theme tag
### Pitch

![image](https://github.com/user-attachments/assets/4ef2b074-c1d3-418a-8cc7-a577f6855944)

### Motivation

How to display all Hashtags of a local instance

**Comment by qiancsff** [comment]
![image](https://github.com/user-attachments/assets/5706019d-acc3-4d4b-847d-d045751ffde5)

**Comment by ThisIsMissEm** [comment]
As a user or as an administrator/moderator? As an admin/mod, we've just added UI in #30880, which will be in Mastodon 4.3

The `/explore/tags` page only shows trending hashtags, which has some manual review potentially. Under `/admin/settings/discovery` see the "Enable trends" and "... without approval" options:
<img width="920" alt="Screenshot 2024-08-15 at 17 39 48" src="https://github.com/user-attachments/assets/2230d97b-3f0e-4a4a-9048-db339cb78000">

**Comment by qiancsff** [comment]
> 作为用户还是管理员/版主？作为管理员/mod，我们刚刚在 #30880 中添加了 UI，它将在 Mastodon 4.3 中出现

I am an administrator and I want all Hashtags locally, not federated and popular ones
(Enable trends "and"... without approval "options:/deploy/tags/admin/settings/discovery enabled)

**Comment by ThisIsMissEm** [comment]
So as an administrator, in the next version you'll be able to view all hashtags on your instance via the admin panel.

As a user, there is no list of all the hashtags, since the number of hashtags can be significant (e.g., on Hachyderm we have 3.5 million hashtags that our instance has seen)

**Comment by qiancsff** [comment]
All users can see locally displayed popular theme tags instead of co popular theme tags
(Enable trends "and"... without approval "options:/deploy/tags/admin/settings/discovery enabled)
The current problem is: I have tags locally, but they are not displayed under the theme tag

**Comment by ThisIsMissEm** [comment]
"Theme tag" and "alliance theme tag"? These aren't features I know of?

there isn't the capability to specify "theme tags" in Mastodon; are you sure you're not using a fork?

**Comment by qiancsff** [comment]
Hashtags

**Comment by ThisIsMissEm** [comment]
Yes, those are the hashtags that are currently trending on your instance. That will only show what is trending & approved to display there. You can manage these at: `/admin/trends/tags` on your instance.

**Comment by jmking-iftas** [comment]
> > 作为用户还是管理员/版主？作为管理员/mod，我们刚刚在 #30880 中添加了 UI，它将在 Mastodon 4.3 中出现
> > I am an administrator, and I want to display all Hashtags locally instead of federated and popular ones
> > (Enable trends "and"... without approval "options:/deploy/tags/admin/settings/discovery enabled)

I think the request might be some method to either 

1. display only local hashtags, and/or
2. prefer local hashtags in the recommendation algorithm

**Comment by ThisIsMissEm** [comment]
@jmking-iftas the problem there is that there's no such thing as "local hashtags", yes, there's local posts using hashtags, but hashtags are kind of global/universal
