### ISSUE TITLE
Question: is there plugins?

### ISSUE THREAD

**Issue by Mrs-Feathers** [mastodon/mastodon#31459]
i just want to know if there are plugins for this, as i really like mastodon, but want to add my own features with plugins. like XMPP chat, a game arcade (litterally just pages with iframes or html5 code added to the side menu) and other small fun stuff that doesnt effect the core or functionality of mastodon. just small QoL plugins.

**Comment by trwnh** [comment]
Nope! See #7717 for that feature request
