### ISSUE TITLE
Support OAuth login without JavaScript

### ISSUE THREAD

**Issue by rodarima** [mastodon/mastodon#31466]
### Pitch

Given that you don't [seem to be interested in allowing users to use the Mastodon web frontend without JavaScript](https://github.com/mastodon/mastodon/issues/6186) following the principles of [progressive enhancement](https://en.wikipedia.org/wiki/Progressive_enhancement), at least please consider allowing users to use the web OAuth login without JavaScript.

This allows using OAuth login in alternative web frontends like [Brutaldon](https://brutaldon.org/about) which don't require JavaScript to work, but currently can only login into a Mastodon server by giving your credentials to the Brutaldon instance, as the OAuth login requires JavaScript.

### Motivation

Remember that not everyone owns a computer with enough RAM or computing power to run the JavaScript web frontend, like me in this moment, but still, I can open this issue on the GitHub website without using JavaScript.

Disclaimer: I'm maintaintaning the Dillo browser, which doesn't support JavaScript.

**Comment by ThisIsMissEm** [comment]
On which URL are you encountering errors? As far as I know login & oAuth authorisation prompt screens do not require JavaScript.

**Comment by rodarima** [comment]
> On which URL are you encountering errors?

The page that manifest a problem is https://fosstodon.org/, but not sure if the
problem is there.

Using Dillo 3.1.1 to reproduce it, enable session cookies and remove old cookies
if any:

```
$ echo 'default ACCEPT_SESSION' > ~/.dillo/cookiesrc
$ rm  ~/.dillo/cookies.txt
$ dpidc stop # Restart cookie plugin
``` 

Then, the steps are:

```
$ dillo https://brutaldon.org/login
```

Enter fosstodon.org and press "Log in", which redirects to (`client_id` masked):

```
https://fosstodon.org/oauth/authorize?client_id=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&response_type=code&redirect_uri=https%3A%2F%2Fbrutaldon.org%2Foauth_callback&scope=read+write+follow&force_login=False
```

Which redirects to:

```
https://fosstodon.org/auth/sign_in
```

I put my user/pass and press "Login", which redirects to:

```
https://fosstodon.org/
```

With the following message:

> To use the Mastodon web application, please enable JavaScript. Alternatively,
> try one of the native apps for Mastodon for your platform.

Screenshot: https://0x0.st/X4hA.png

If I put my user/pass wrong it says "Invalid E-mail address or password.", so I
assume it went through.

I also tried Netsurf and Elinks, but they show this message instead:

> The redirect uri included is not valid.

The same happens in mastodon.social.

> which mastodon version?

Not sure how to read the version, as opening fosstodon.org only gives me a
message to enable JS. Inspecting the HTML I see:

```
"version":"4.2.11"
```

> which server?

Both fosstodon.org and mastodon.social.

I can also dump the whole HTTP traffic if you need it for debugging. I suspect
there may be a problem in the way Brutaldon is doing the authorization, as I
used the Tokodon desktop app and I was able to login with Dillo. Not sure why
I'm not able to see the same "The redirect uri included is not valid" message in
Dillo.

Here is the URL Tokodon is using:

```
https://fosstodon.org/oauth/authorize?client_id=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&redirect_uri=tokodon://oauth&response_type=code&scope=read%20write%20follow%20admin:read%20admin:write
```

**Comment by ThisIsMissEm** [comment]
@rodarima okay, so it sounds like something is going wrong during login; can you actually login to fosstodon in that browser?

I'm going to test in firefox with javascript disabled in a bit, just to try to figure out if it's really a JavaScript issue; because after login from an `/oauth/authorize` request you should be returned back to that URL

(there is a known bug that we've not been able to figure out yet where this breaks & you're redirected back to the web UI instead)

**Comment by ThisIsMissEm** [comment]
Having the client_id (a public value) would help, because then I could ask either the fosstodon admins or mastodon.social admins for details relating to those clients (the bad redirect_uri issue is that the redirect URIs nust be pre-registered with the mastodon server first and must be comparable using === (simple string comparison)

**Comment by rodarima** [comment]
> @rodarima okay, so it sounds like something is going wrong during login; can
> you actually login to fosstodon in that browser?

I tested it with the Tokodon app and it looks I can login with Dillo. Both
using the redirect url and code seem to work, but Dillo doesn't handle the
tokodon:// properly to launch the app, so I can only use the explicit code
method.

I would expect the https redirect to work properly for Brutaldon.

So I assume the login process works.

> I'm going to test in firefox with javascript disabled in a bit, just to try to
> figure out if it's really a JavaScript issue; because after login from an
> /oauth/authorize request you should be returned back to that URL

Thanks for looking into this!

> (there is a known bug that we've not been able to figure out yet where this
> breaks & you're redirected back to the web UI instead)

That may explain what I'm observing.

> Having the `client_id` (a public value) would help, because then I could ask
> either the fosstodon admins or mastodon.social admins for details relating to
> those clients (the bad `redirect_uri` issue is that the redirect URIs nust be
> pre-registered with the mastodon server first and must be comparable using ===
> (simple string comparison)

I didn't knew it was public, they are the following:

For `mastodon.social`: `1MinYCUnKaQ_g1BsqDeXKyYbt-1fA31v-uhTPFVEgHw`
For `fosstodon.org`: `UDYhp7drlT60h8TByadw4mRsg9HIPH9sgVCz_q567so`

**Comment by ThisIsMissEm** [comment]
I cannot reproduce on Firefox 128 with JavaScript disabled. However, if I see the OAuth Authorize page, and try to change accounts by clicking "logout", then I do get an error because that button requires JavaScript.

(because it's using the DELETE method of HTTP, but rails also supports this via method override using a hidden input named `_method`)

**Comment by ThisIsMissEm** [comment]
@rodarima yeah, OAuth Client IDs are considered "public" as they are transmitted over http(s) to a remote server, and therefore could be intercepted by browsers, proxies, or extensions.

But yeah, Mastodon requires applications to be pre-registered with the instance via `POST /api/v1/apps`, which provides a `client_id` and `client_secret` (which Brutaldon appears to do, otherwise I wouldn't be able to login at all).

There is a project to remove that pre-registration requirement via #31151, which involved an IETF Internet Draft that I've been co-authoring.

**Comment by ThisIsMissEm** [comment]
@rodarima could it be that Dillo isn't respecting Set-Cookie on 3xx redirects? This might explain why the `/oauth/authorize` redirect to `/auth/sign_in` doesn't return you to the OAuth flow, and instead treats it as if you're trying to access the Web UI which requires JavaScript.

**Comment by rodarima** [comment]
> @rodarima could it be that Dillo isn't respecting Set-Cookie on 3xx redirects?
> This might explain why the /oauth/authorize  redirect to  `/auth/sign_in`
> doesn't return you to the OAuth flow, and instead treats it as if you're
> trying to access the Web UI which requires JavaScript.

Yeah, good catch. This is one of the problems, but there are more.

I took a look at it and I identified (at least) three different issues that
prevent users from using Dillo to login via oauth to Brutaldon. All three issues
must be solved for it to work.

1. Third party cookies are rejected:

```c
if (!web->requester ||
    a_Url_same_organization(entry->Url, web->requester)) {
   /* If cookies are third party, don't even consider them. */
   char *server_date = Cache_parse_field(header, "Date");

   a_Cookies_set(Cookies, entry->Url, server_date);
   dFree(server_date);
   break;
}
```

This includes the case in which a server "brutaldon.org" redirects via 302 to
another server "fosstodon.org" which then tries to set a cookie. I'll have to
evaluate how to implement this safely or if it should be enabled on a case by
case basis in the cookie configuration. This could open the door to tracking,
which we prevent as much as we can in Dillo.

This could be avoided by making the user click on a link to open the fosstodon
link manually in brutaldon, so it directly loads from the same fosstodon.org
host as the origin request.

2. The `/auth/sign_in` endpoint will only redirect back to `/oauth/authorize` if
the Referer header is "properly" set. In Dillo is set by default to the host of
the current URL, not the previous URL. This is controlled by the `http_referer`
option. Changing it to none (not seding it) causes a failure in brutaldon.org.
Changing it to "path" causes it to hold the value of the current URL, which
works fine.

```
# Set the HTTP Referer (sic) header.
# Note that there is no option to reveal the page that you came from because it
# would endanger your privacy. 'host' and 'path' allow you to pretend that the
# link you followed was on the same site that you're going to.
# none  : Don't send any Referer header at all.
# host  : Send the requested URI's hostname.
# path  : Send the requested URI's host and path.
http_referer=path
```

By default it was being set to `Referer: fosstodon.org` which may be confusing
Mastodon of which URL should the login redirect to.

Using `Referer: https://fosstodon.org/auth/sign_in` works.

Would it make sense to ignore it or give more priority to the oauth redirect
URI? This way we can continue to send the hostname as the Referer without
leaking the privious URL.

3. The brutaldon redirection URI doesn't seem to match the one that the app
has registered. It seems to fail in all browsers with the message:

> The redirect uri included is not valid.

This is probably something that Brutaldon developers must fix. Not sure which
value has the app registered as the redirection URI. I see that is trying to
jump to:

```
https://brutaldon.org/oauth_callback
```

Changing the `http_referer` option and patching the code to allow third party
cookies makes Dillo behave like the other browsers and reach the error message
of the redirect URI.

Screenshot: https://0x0.st/XJeb.png

**Comment by ThisIsMissEm** [comment]
I can't really help you implement your browser; but I'd suggest following the specifications for how this stuff should work.

If OAuth with Mastodon is broken, then likely all OAuth / OIDC flows will be broken in your browser and a whole lot more.

I'd recommend creating an issue in your issue tracker, as this as far as I can tell isn't a Mastodon issue.

**Comment by rodarima** [comment]
On Mon, Aug 19, 2024 at 03:44:40PM -0700, Emelia Smith wrote:
> I can't really help you implement your browser; but I'd suggest 
> following the specifications for how this stuff should work.

Dillo is not "my" browser, it was developed by several people since 1999 
(not me) who are not involved anymore. I'm just trying to keep it alive.

As a general rule, I stick to standards unless they are in conflict with 
the core principles values of Dillo. Unfortunately, a lot of standards 
are backed by a handful of big companies which have their own priorities 
(specially regarding privacy) and a very different budget.

> If OAuth with Mastodon is broken, then likely all OAuth / OIDC flows 
> will be broken in your browser and a whole lot more.

What seems to be broken is the redirection towards brutaldon.org, but I 
wouldn't be surprised if there are other problems.

> I'd recommend creating an issue in your issue tracker, as this as far 
> as I can tell isn't a Mastodon issue.

Yeah, I'll do that. I think this can be closed now.

Thanks for your help!

**Comment by kirin333** [comment]
[](url)

**Comment by kirin333** [comment]
What's your good morning

**Comment by kirin333** [comment]
> What's your good morning

**Comment by kirin333** [comment]
[README.md](https://github.com/user-attachments/files/18255091/README.md)
[Publicité ciblée en ligne _ quels enjeux pour la protection des données personnelles _ _ CNIL.pdf](https://github.com/user-attachments/files/18255092/Publicite.ciblee.en.ligne._.quels.enjeux.pour.la.protection.des.donnees.personnelles._._.CNIL.pdf)
