### ISSUE TITLE
tootctl complains about not checked out gem omniauth-cas 

### ISSUE THREAD

**Issue by leahoswald** [mastodon/mastodon#31478]
### Steps to reproduce the problem

Running any tootctl command results in this error
```
/home/mastodon/.rbenv/versions/3.2.3/bin/ruby /home/mastodon/live/bin/tootctl accounts refresh mastodon@mastodon.social 
https://github.com/stanhu/omniauth-cas.git (at 4211e6d@4211e6d) is not yet checked out. Run `bundle install` first.
```

### Expected behaviour

tootctl command runs without this error

### Actual behaviour

There is an error I can't resolve

### Detailed description

I tried `bundle install` as stated, tried to reinstall all gems and also recreated the rbenv from scratch, but nothing resolves the error message about the not yet checked out gem. While reinstalling the gems, it reports the installation without any errors.

### Mastodon instance

chaos.social

### Mastodon version

v4.2.11

### Technical details

ruby: v3.2.3
Problem was also existent with mastodon v4.2.10
Debian Bullseye

**Comment by leahoswald** [comment]
Oh and additional note, using the 3.2.2 rbenv everything works.

**Comment by ThisIsMissEm** [comment]
Are you using CAS for user authentication? It should be an optional gem...

**Comment by leahoswald** [comment]
Nope, only the mastodon internal auth.

**Comment by ThisIsMissEm** [comment]
Does the machine you're getting this error on have git installed?

**Comment by ThisIsMissEm** [comment]
Found a similar error here with discussion on resolutions (a few are outdated, so definitely read the whole thread first): https://stackoverflow.com/questions/6648870/is-not-checked-out-bundle-install-does-not-fix-help

**Comment by leahoswald** [comment]
> Does the machine you're getting this error on have git installed?

Yes, of course.

> Found a similar error here with discussion on resolutions (a few are outdated, so definitely read the whole thread first):

Found it too, and the outdated and not working stuff is one of the reasons I asked here. I know what I do, but I'm not that experienced with all the ruby details. So this doesn't help.

**Comment by ThisIsMissEm** [comment]
@leahoswald hmm, okay. I'm wondering if you'd still see the same error upgrading to Ruby 3.3.4?

Also, I'd suggest adding the output of `uname -a` to the issue description.

**Comment by leahoswald** [comment]
> I'm wondering if you'd still see the same error upgrading to Ruby 3.3.4?
I don't want to try to upgrade because it's not the recommended version at the moment.

Added the OS to the technical details

**Comment by ThisIsMissEm** [comment]
Thanks; I don't think debian was an operating system we were having bundler errors relating to CXX version upgrades, so it's not that class of error, I guess.

The systems I knew were affected were MacOS 14.6 and the latest ArchLinux

**Comment by ThisIsMissEm** [comment]
Have you tried `bundle exec ./bin/tootctl` ?

**Comment by renchap** [comment]
This looks like an issue with your Ruby environment / rbenv, not directly related to Mastodon.

Can you try to delete the `vendor/bundle` directory, run `bundle install` again, and then try `bin/tootctl accounts refresh mastodon@mastodon.social`?

**Comment by leahoswald** [comment]
> Can you try to delete the `vendor/bundle` directory, run `bundle install` again, and then try `bin/tootctl accounts refresh mastodon@mastodon.social`?

removed it and run `bundle install`

> Fetching https://github.com/stanhu/omniauth-cas.git
>  [...]
> Using omniauth-cas 2.0.0 from https://github.com/stanhu/omniauth-cas.git (at 4211e6d@4211e6d)

But the error is still the same.

> Have you tried `bundle exec ./bin/tootctl` ?
This works and I have no idea why. Could you explain why?

**Comment by ThisIsMissEm** [comment]
>> Have you tried bundle exec ./bin/tootctl ?
> This works and I have no idea why. Could you explain why?

i can't off top of head. I know that sometimes things fail because bundler thinks it's not been run or something, but bundle exec somehow fixes that by I guess changing load paths

It's above my level of "off the top of my head" ruby knowledge; maybe someone else can explain it

**Comment by renchap** [comment]
> This works and I have no idea why. Could you explain why?

Most probably due to a conflict between your system & rbenv-managed ruby installations.

I am not sure how to troubleshoot this, but what does `which bundle` says? Basically I suspect that running `bundle` uses one Ruby version, while your original command above explicitely uses the rbenv managed one, which does not have the gems installed.

**Comment by leahoswald** [comment]
Then why did it work until the upgrade to v2.4.10?

> I am not sure how to troubleshoot this, but what does `which bundle` says? 

I never call bundle directly without the rbenv path so there should be no confusion

**Comment by renchap** [comment]
I dont know, I dont think we changed anything relevant in 4.2.10, so my most likely explanation is that it comes from your Ruby environment.

**Comment by leahoswald** [comment]
Ok I spent two more hours of debugging and found the following I can't explain:

I created a file test.rb  with the following content:
```
#!/usr/bin/env ruby
puts RUBY_VERSION
```
If I call it, I get the right ruby version from the rbenv.

> mastodon@cthulhu:~/live$ /home/mastodon/.rbenv/versions/3.2.3/bin/ruby test.rb 
> 3.2.3

Now I added the same line to the tootctl ruby file and the result is totaly different.

The tootctl file now looks like this:
```
#!/usr/bin/env ruby
puts RUBY_VERSION
APP_PATH = File.expand_path('../config/application', __dir__)

require_relative '../config/boot'
require_relative '../lib/mastodon/cli/main'

begin
  Chewy.strategy(:mastodon) do
    Mastodon::CLI::Main.start(ARGV)
  end
rescue Interrupt
  exit(130)
end
```
And the result calling it is now this:

> mastodon@cthulhu:~/live$ /home/mastodon/.rbenv/versions/3.2.3/bin/ruby /home/mastodon/live/bin/tootctl accounts refresh mastodon@mastodon.social 
> 3.2.3
> 3.1.2
> https://github.com/stanhu/omniauth-cas.git (at 4211e6d@4211e6d) is not yet checked out. Run `bundle install` first.

So I get the right version first but then something strange is switching the version to the distribution version 3.1.2 which fails. I have now idea what in the code runs the script from start again. Because the first line printing the version shouldn't be called multiple times. For me it looks like something from inside the tootctl scritpt is calling itself in another context.

Any idea?

**Comment by markrsmith83** [comment]
When you do su - mastodon do you also run “source ~/.bashrc” before doing anything?

**Comment by leahoswald** [comment]
No. But as already stated, this worked and nothing changed than the mastodon version.

**Comment by markrsmith83** [comment]
I think this is a PATH issue for your mastodon user, in the command line vs. inside of something else.
