### ISSUE TITLE
Notifications of Mentions Not Appearing

### ISSUE THREAD

**Issue by lrmikestone** [mastodon/mastodon#31476]
### Steps to reproduce the problem

1. One user mentions another user in a public post.
2. Second user gets no notification of mention despite having setting enabled to show in column.

### Expected behaviour

Notifications of mentions should show up in Notifications

### Actual behaviour

No notification appears

### Detailed description

Many users are reporting they're not receiving notifications when they receive replies or they're just mentioned. There's no visible errors and users are reporting the issue from the Standard UI, Advanced UI, and mobile applications. At present, the reports we have all have been centered around replies from local accounts with elevated permissions, such as a moderator of the local instance.

### Mastodon instance

fosstodon.org

### Mastodon version

4.2.11

### Technical details

Mastodon - 4.2.11
Ruby - 3.2.3p157
PostgreSQL - 15.0
Redis - 7.0.5
Elasticsearch - 7.10.2

**Comment by ssOleg** [comment]
I think it can be similar to what I created recently https://github.com/mastodon/mastodon/issues/31467 .

**Comment by hugogameiro** [comment]
I think @ssOleg is correct. I made a mistake when we spoke earlier @lrmikestone and was looking for the error in the Streaming log but the error shows up in the Sidekiq log and it's also present on Fosstodon.org. It's probably best to close this issue and mention on #31467 that the issue is also present for you. Sorry.

**Comment by lrmikestone** [comment]
Looks like this is a duplicate of #31467. Closing this ticket in favor of that one.
