### ISSUE TITLE
v4.2.11 does not compile with Ruby 3.2.4

### ISSUE THREAD

**Issue by markrsmith83** [mastodon/mastodon#31472]
### Steps to reproduce the problem

1. rbenv local 3.2.4
2. bundle install
3. yarn install --frozen-lockfile
4. RAILS_ENV=production bundle exec rails assets:precompile

At this point, there is a compile error shown below in Technical Details.

Doing rbenv local 3.2.3 and then repeating compiles correctly.

### Expected behaviour

The compile should have succeeded.

### Actual behaviour

Compile error

### Mastodon instance

smithtodon.org

### Mastodon version

v4.2.11

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: 3.2.4
- Node.js version: 20.13.0

mastodon@smithtodon:~/live$ RAILS_ENV=production bundle exec rails assets:precompile
<internal:/home/mastodon/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': /lib/x86_64-linux-gnu/libjemalloc.so.2: cannot allocate memory in static TLS block - /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/msgpack-1.7.1/lib/msgpack/msgpack.so (LoadError)
        from <internal:/home/mastodon/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/msgpack-1.7.1/lib/msgpack.rb:7:in `<top (required)>'
        from <internal:/home/mastodon/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/home/mastodon/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/store.rb:5:in `block in <top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/explicit_require.rb:45:in `rescue in with_gems'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/explicit_require.rb:41:in `with_gems'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/store.rb:5:in `<top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache.rb:68:in `require_relative'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache.rb:68:in `<top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap.rb:5:in `require_relative'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap.rb:5:in `<top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/setup.rb:3:in `require_relative'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/setup.rb:3:in `<top (required)>'
        from <internal:/home/mastodon/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/home/mastodon/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /home/mastodon/live/config/boot.rb:11:in `<top (required)>'
        from bin/rails:3:in `require_relative'
        from bin/rails:3:in `<main>'
<internal:/home/mastodon/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': /lib/x86_64-linux-gnu/libjemalloc.so.2: cannot allocate memory in static TLS block - /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/msgpack-1.7.1/lib/msgpack/msgpack.so (LoadError)
        from <internal:/home/mastodon/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/msgpack-1.7.1/lib/msgpack.rb:7:in `<top (required)>'
        from <internal:/home/mastodon/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/home/mastodon/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/store.rb:5:in `block in <top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/explicit_require.rb:42:in `with_gems'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/store.rb:5:in `<top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache.rb:68:in `require_relative'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache.rb:68:in `<top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap.rb:5:in `require_relative'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap.rb:5:in `<top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/setup.rb:3:in `require_relative'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/setup.rb:3:in `<top (required)>'
        from <internal:/home/mastodon/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/home/mastodon/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /home/mastodon/live/config/boot.rb:11:in `<top (required)>'
        from bin/rails:3:in `require_relative'
        from bin/rails:3:in `<main>'

**Comment by ThisIsMissEm** [comment]
See the note about Charlock Holmes in the upgrade instructions (I believe that's this error)

iirc, CXX compilers received updates in some distros like archlinux that caused this bug (it was previously reported and fixed to my knowledge)

may also be worth seeing if you can upgrade to ruby 3.3.4 which is the recommended version for 4.3 which is entering beta soon

**Comment by renchap** [comment]
According to this line in your log:

```
require': /lib/x86_64-linux-gnu/libjemalloc.so.2: cannot allocate memory in static TLS block - /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/msgpack-1.7.1/lib/msgpack/msgpack.so (LoadError) from <internal:/home/mastodon/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in require'
```

This seems to be a memory issue, and you are running out of memory on your system while compiling the assets.

**Comment by ThisIsMissEm** [comment]
@renchap I'm pretty sure that's not the case, since msgpack isn't involved in compiling assets afaik. But we did see an issue when investigating rubygem issues the itger month with the exact error: 

``` 
cannot allocate memory in static TLS block
```

because a ruby / gem that used native code had a mismatch with interfaces

At least, I'm pretty sure we did..?

**Comment by ThisIsMissEm** [comment]
Yeah, see: https://github.com/mastodon/mastodon/issues/29067

**Comment by renchap** [comment]
Ok, so maybe try removing the installed gems (`rm -r vendor/bundle`), then run `bundle install` again, then retry?

**Comment by markrsmith83** [comment]
Removed vendor/bundle as noted above, re-ran bundle install, yarn install --frozen-lockfile, and precompile:

mastodon@smithtodon:~/live$ RAILS_ENV=production bundle exec rails assets:precompile
Everything's up-to-date. Nothing to do
mastodon@smithtodon:~/live$

**Comment by renchap** [comment]
Ok, try removing `tmp/cache/webpacker/` and re-run precompile, so it does not try to reuse the cache

**Comment by markrsmith83** [comment]
Removed /tmp/cache/webpacker/, re-run precompile.

mastodon@smithtodon:~/live$ RAILS_ENV=production bundle exec rails assets:precompile
Compiling...
Compiled all packs in /home/mastodon/live/public/packs
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/home/mastodon/live/node_modules/babel-plugin-lodash/node_modules/@babel/types/lib/validators/generated/index.js:2740:35)
    at PluginPass.Program (/home/mastodon/live/node_modules/babel-plugin-lodash/lib/index.js:102:44)
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

It looks fixed. So probably was an old gem. Perhaps 4.3.0 should have removal of vendor/bundle before bundle install in the upgrade instructions.
