### ISSUE TITLE
Add context to "Are you sure?" prompt in Trending posts page

### ISSUE THREAD

**Issue by eliastorres** [mastodon/mastodon#31497]
### Steps to reproduce the problem

1. Go to https://mastodon.example/admin/trends/statuses
2. Click on a checkbox to select a post to allow 
3. Click on either "Allow post" or "Allow author", both links are very close, especially when using a mobile browser.
4. You get a prompt that says "Are you sure?" 
5. Ask yourself "Sure of what?" not being sure which link you clicked.

### Expected behaviour

Prompt should include the action, for example "Are you sure to allow this author?" or "Are you sure to allow only this specific post?"

### Actual behaviour

Prompt asks "Are you sure?" without context.

### Detailed description

Action links in post moderation like "Allow post", "Allow author", "Disallow post" and "Disallow author" are too close and sometimes is not clear which link was clicked, the prompt "Are you sure?" doesn't help to identify which option was chosen.

### Mastodon instance

mastodon.cr

### Mastodon version

v4.2.12

### Browser name and version

All browsers

### Operating system

All Operating systems

### Technical details

Screenshot of the issue, action links are too close and the prompt "Are you sure?" doesn't help to be sure which action was chosen

![image](https://github.com/user-attachments/assets/15a8b39f-33db-47fb-83ea-2eac0af4d7ac)

**Comment by renchap** [comment]
This has been solved in #19626 and will be available in 4.3.
