### ISSUE TITLE
Privacy and Reach settings appear to be ignored in 4.2.10

### ISSUE THREAD

**Issue by nztvar** [mastodon/mastodon#31500]
### Steps to reproduce the problem

1. /settings/privacy → Privacy and Reach → uncheck all, save changes.
2. In a separate, not-logged in browser, visit profile page. Check if followers, following are displayed. 
3. Toot something from account. In not-logged in browser, check if it appears in the local timeline.
...
![Screenshot from 2024-08-19 12-24-06](https://github.com/user-attachments/assets/b841230e-3094-4eb3-9f6e-1ced129e1ce1)
![Screenshot from 2024-08-19 12-37-08](https://github.com/user-attachments/assets/97c8065c-4296-43e3-9ce6-47625558349e)
![Screenshot from 2024-08-19 12-48-03](https://github.com/user-attachments/assets/bf88ac87-ff9f-4bbd-9375-25839f7d30ce)

### Expected behaviour

Followers and following should not be visible. If local feed uses search to identify posts, then my posts should not appear there.

### Actual behaviour

Both follower and following metadata are displayed. In local feed, posts appear.

### Detailed description

The behaviour observed is surprising, based on settings dashboard descriptions. It may be the intended actions, but the text seems to imply a different expectation.

It is possible this is a local issue on mamot.fr.

mstdn.ca, using v4.3.0-alpha.3+glitch, does not display followers, but does display following:

![Screenshot from 2024-08-19 12-56-05](https://github.com/user-attachments/assets/f2a7782c-8337-4088-8c4f-2b5a07cb284f)

### Mastodon instance

mamot.fr

### Mastodon version

v4.2.10

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by Gargron** [comment]
The number of followers cannot be hidden. Please check if the list itself is hidden. But mind that *you* as the owner of the account will see the list of followers if you are logged in. Search settings have no effect on the local timeline.

**Comment by nztvar** [comment]
Thanks! 

The list itself is hidden.

I find displaying followers, following metadata surprising, based on the text in the settings. I understand it is the expected behaviour.
