### ISSUE TITLE
`/api/v*/instance` should include favicon and touch icon

### ISSUE THREAD

**Issue by daprice** [mastodon/mastodon#31520]
### Pitch

The URLs of the instance’s favicon and apple-touch-icons should be available to clients as properties of `Instance`.

### Motivation

It’s weird that Mastodon added the ability to customize the favicon of an instance without giving clients a way to access them, other than scraping the HTML of the instance’s web interface.

**Comment by renchap** [comment]
I made an attempt at this here: https://github.com/mastodon/mastodon/pull/30205

**Comment by daprice** [comment]
Am I understanding the code in that PR correctly, that it includes sizes up to 512x512? Any chance of including 1024x1024 (or whatever the largest is)?

I don’t think I need more than 256x256 for my use case, but it seems like the highest res you can get from the API should equal what you can get from the HTML
