### ISSUE TITLE
Reverse Proxy with IPv4 & IPv6

### ISSUE THREAD

**Issue by RJGhugo** [mastodon/mastodon#31580]
### Steps to reproduce the problem

Running a NGINX Proxy (IPv4 to IPv6) in front of Mastodon (IPv6 only) does only work with IPv6 instances.

### Expected behaviour

Reverse Proxy should forward IPv4 to IPv6

### Actual behaviour

IPv4 instances does get error (503 Remote data could not be fetched)

### Detailed description

Searching a account on a IPv4 only instance does not work. (Fehler beim Suchen/Error while searching)
Searching a account on a IPv6  works.

### Mastodon instance

photog.social, social.heise.de

### Mastodon version

4.2.12

### Browser name and version

Tusky or Firefox latest

### Operating system

Android or Linux

### Technical details

It seems to be a problem related to IPv4 and IPv6. Other services with IPv4 to IPv6 are working.
NGINX Config more or less standard as published by mastodon.

**Comment by markrsmith83** [comment]
Can you post your .conf for Mastodon in NGINX?

**Comment by RJGhugo** [comment]
`map $http_upgrade $connection_upgrade {`
`  default upgrade;`
`  ''      close;`
`}`
``
`upstream backend {`
`    server [XXXX:XXXX:XXXX:XXXX:XXXX::aaaa]:3000 fail_timeout=0;`
`}`
``
`upstream streaming {`
`    server [XXXX:XXXX:XXXX:XXXX:XXXX::bbbb]:4000 fail_timeout=0;`
`}`
``
`proxy_cache_path /var/cache/nginx/mastodon levels=1:2 keys_zone=mastodon:10m inactive=7d max_size=1g;`
``
`server {`
`  listen 80;`
`  listen [::]:80;`
`  server_name mastodon.XXXX.XXXX;`
``
`  ssl_protocols TLSv1.2 TLSv1.3;`
`  ssl_session_tickets off;`
``
`  keepalive_timeout    70;`
`  sendfile             on;`
`  client_max_body_size 80m;`
``
`  root /home/mastodon/live/public;`
``
`  gzip on;`
`  gzip_disable "msie6";`
`  gzip_vary on;`
`  gzip_proxied any;`
`  gzip_comp_level 6;`
`  gzip_buffers 16 8k;`
`  gzip_http_version 1.1;`
`  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml image/x-icon;`
``
`add_header X-Content-Type-Options nosniff;`
``
`add_header Content-Security-Policy "default-src 'none'";`
``
`  location / {`
`    try_files $uri @proxy;`
`  }`
``
`  location = /sw.js {`
`    add_header Cache-Control "public, max-age=604800, must-revalidate";`
`    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";`
`    try_files $uri @proxy;`
`  }`
``
`  location ~ ^/assets/ {`
`    add_header Cache-Control "public, max-age=2419200, must-revalidate";`
`    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";`
`    try_files $uri @proxy;`
`  }`
``
`  location ~ ^/avatars/ {`
`    add_header Cache-Control "public, max-age=2419200, must-revalidate";`
`    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";`
`    try_files $uri @proxy;`
`  }`
``
`  location ~ ^/emoji/ {`
`    add_header Cache-Control "public, max-age=2419200, must-revalidate";`
`    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";`
`    try_files $uri @proxy;`
`  }`
``
`  location ~ ^/headers/ {`
`    add_header Cache-Control "public, max-age=2419200, must-revalidate";`
`    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";`
`    try_files $uri @proxy;`
`  }`
``
`  location ~ ^/packs/ {`
`    add_header Cache-Control "public, max-age=2419200, must-revalidate";`
`    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";`
`    try_files $uri @proxy;`
`  }`
``
`  location ~ ^/shortcuts/ {`
`    add_header Cache-Control "public, max-age=2419200, must-revalidate";`
`    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";`
`    try_files $uri @proxy;`
`  }`
``
`  location ~ ^/sounds/ {`
`    add_header Cache-Control "public, max-age=2419200, must-revalidate";`
`    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";`
`    try_files $uri @proxy;`
`  }`
``
`  location ~ ^/system/ {`
`    add_header Cache-Control "public, max-age=2419200, immutable";`
`    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";`
`    try_files $uri @proxy;`
`  }`
``
`  location ^~ /api/v1/streaming {`
`    proxy_set_header Host $host;`
`    proxy_set_header X-Real-IP $remote_addr;`
`    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`
`    proxy_set_header X-Forwarded-Proto $scheme;`
`    proxy_set_header Proxy "";`
``
`    proxy_pass http://streaming;`
`    proxy_buffering off;`
`    proxy_redirect off;`
`    proxy_http_version 1.1;`
`    proxy_set_header Upgrade $http_upgrade;`
`    proxy_set_header Connection $connection_upgrade;`
``
`    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";`
``
`    tcp_nodelay on;`
`  }`
``
`  location @proxy {`
`    proxy_set_header Host $host;`
`    proxy_set_header X-Real-IP $remote_addr;`
`    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`
`    proxy_set_header X-Forwarded-Proto $scheme;`
`    proxy_set_header Proxy "";`
`    proxy_pass_header Server;`
``
`    proxy_pass http://backend;`
`    proxy_buffering on;`
`    proxy_redirect off;`
`    proxy_http_version 1.1;`
`    proxy_set_header Upgrade $http_upgrade;`
`    proxy_set_header Connection $connection_upgrade;`
``
`    proxy_cache mastodon;`
`    proxy_cache_valid 200 7d;`
`    proxy_cache_valid 410 24h;`
`    proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;`
`    add_header X-Cached $upstream_cache_status;`
``
`    tcp_nodelay on;`
`  }`
``
`  error_page 500 501 502 503 504 /500.html;`
``
`}`

**Comment by markrsmith83** [comment]
Just trying to pick off the easy stuff.

**Comment by RJGhugo** [comment]
It seems, that with **IPv6** everything works fine!

I can add user, etc.

Only with **IPv4** I have problems.

**Comment by RJGhugo** [comment]
It seems, that NGINX is not able to forward **IPv4** to an **IPv6 only** Mastodon instance.

Running a test Web-Server with the following settings, the IPv4 forwarding is working:

`server {`
`   listen	80;`
`   listen	[::]:80;`
`   add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;`
`   add_header X-Frame-Options "SAMEORIGIN";`
`   add_header X-XSS-Protection "1; mode=block";`
`   add_header X-Content-Type-Options "nosniff";`
`   add_header Referrer-Policy "strict-origin";`
`   add_header Permissions-Policy "geolocation=();midi=();notifications=();push=();sync-xhr=();microphone=();camera=();magnetometer=();gyroscope=();speaker=(self);vibrate=();fullscreen=(self);payment=();";`
`   add_header Content-Security-Policy "default-src 'self'";`
`   server_name  test.XXXX.XXXX;`
`   location / {`
`      proxy_pass http://[XXXX:XXXX:XXXX:XXXX:XXXX::dddd]/;`
`   }`
`}`

**Comment by RJGhugo** [comment]
I can not add a **IPv4** account (e.g. mho@social.heise.de). Everything connected with **IPv6** works...

https://github.com/ClearlyClaire
https://github.com/ThisIsMissEm

**Comment by ThisIsMissEm** [comment]
Can you access Mastodon via that IPv6 address? If so, it's likely an nginx configuration issue, so you'd need to look into that (I'm not sure we can provide support for nginx configuration issues)

Perhaps these links will help:
- https://serverfault.com/questions/638367/do-you-need-separate-ipv4-and-ipv6-listen-directives-in-nginx
- https://stackoverflow.com/questions/51913072/setting-up-nginx-with-proxy-pass-and-ipv6
- https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass
- https://ipv6.net/blog/enabling-and-configuring-ipv6-on-an-nginx-web-server-on-ubuntu/

**Comment by RJGhugo** [comment]
Thank you for the hints.

I can access my Mastodon instance from **IPv4** and **IPv6** clients via the web-interface and the client app (Tuskey).

It seems that every thing (add user, replys, etc.) that is comming from an **IPv6** enabled instance works fine.

What is not working is reaching **IPv4 only** instances and add users (e.g. mho@social.heise.de): Fehler beim Suchen/Error while searching.

Assuming that my Mastodon instance can not transform queries to an **IPv4** instance.

P.S. Router has Tayga for accessing e.g. github, which is IPv4 only.

P.P.S. Firewall rules etc should not be a problem as incomming traffic to the proxy is http(s). The proxy (see config above https://github.com/mastodon/mastodon/issues/31580#issuecomment-2309390704) split the traffic to port 3000/4000.

**Comment by ThisIsMissEm** [comment]
Check the mastodon logs and sidekiq for errors, mastodon supports outbound requests via IPv6 and IPv4, if you only have IPv6 then you'd need to proxy through something with both IPv6 and IPv4: https://github.com/mastodon/mastodon/blob/main/app/lib/request.rb#L271

**Comment by RJGhugo** [comment]
sidekiq log: **failed to connect: Network is unreachable - connect(2) for 176.9.117.58:443**

ema:PropertyValue","value":"schema:value","ostatus":"<http://ostatus.org#","atomUri":"ostatus:atomUri","inRep>
lyToAtomUri":"ostatus:inReplyToAtomUri","conversation":"ostatus:conversation","focalPoint":{"@container":"@list
","@id":"toot:focalPoint"},"blurhash":"toot:blurhash","discoverable":"toot:discoverable","indexable":"toot:
indexable","memorial":"toot:memorial","votersCount":"toot:votersCount","Device":"toot:Device","Ed25519Signatu
re":"toot:Ed25519Signature","Ed25519Key":"toot:Ed25519Key","Curve25519Key":"toot:Curve25519Key","EncryptedMessa
ge":"toot:EncryptedMessage","publicKeyBase64":"toot:publicKeyBase64","deviceId":"toot:deviceId","claim":{"@ty
pe":"@id","@id":"toot:claim"},"fingerprintKey":{"@type":"@id","@id":"toot:fingerprintKey"},"identityKey"
:{"@type":"@id","@id":"toot:identityKey"},"devices":{"@type":"@id","@id":"toot:devices"},"messageFrankin
g":"toot:messageFranking","messageType":"toot:messageType","cipherText":"toot:cipherText","suspended":"toot:s
uspended"}],"id":"<https://nrw.social/users/moesch/statuses/113080393202446473/activity","type":"Create","actor>":
"[https://nrw.social/users/moesch","published":"2024-09-04T17:11:06Z","to":["https://nrw.social/users/moesch/follow](https://nrw.social/users/moesch\",\"published\":\"2024-09-04T17:11:06Z\",\"to\":[\"https://nrw.social/users/moesch/follow)
ers"],"cc":["[https://www.w3.org/ns/activitystreams#Public","https://mastodon.social/users/derpostillon"],"object](https://www.w3.org/ns/activitystreams#Public\",\"https://mastodon.social/users/derpostillon\"],\"object)":
{"id":"<https://nrw.social/users/moesch/statuses/113080393202446473","type":"Note","inReplyTo":"https://mastodon>.
social/users/derpostillon/statuses/113080349608876593","published":"2024-09-04T17:11:06Z","url":"<https://nrw.social>
/@moesch/113080393202446473","attributedTo":"[https://nrw.social/users/moesch","to":["https://nrw.social/users/moesc](https://nrw.social/users/moesch\",\"to\":[\"https://nrw.social/users/moesc)
h/followers"],"cc":["[https://www.w3.org/ns/activitystreams#Public","https://mastodon.social/users/derpostillon"],"s](https://www.w3.org/ns/activitystreams#Public\",\"https://mastodon.social/users/derpostillon\"],\"s)
ensitive":false,"atomUri":"<https://nrw.social/users/moesch/statuses/113080393202446473","inReplyToAtomUri":"https:/>
/[mastodon.social/users/derpostillon/statuses/113080349608876593","conversation":"tag:mastodon.social,2024-09-04:objectI](http://mastodon.social/users/derpostillon/statuses/113080349608876593\",\"conversation\":\"tag:mastodon.social,2024-09-04:objectI)
d=791620074:objectType=Conversation","content":"<p><span class=\\"h-card\\" translate=\\"no\\"><a href=\\"https://
[mastodon.social/@derpostillon\\](http://mastodon.social/@derpostillon\)" class=\\"u-url mention\\">@<span>derpostillon</span></a></span></p>","contentMap":{\
"de":"<p><span class=\\"h-card\\" translate=\\"no\\"><a href=\\"<https://mastodon.social/@derpostillon\>" class=\\"
u-url mention\\">@<span>derpostillon</span></a></span></p>"},"attachment":[{"type":"Document","mediaType":"image
/jpeg","url":"[https://nrw.social/system/media_attachments/files/113/080/392/955/393/032/original/8acee728d823cf53.jpeg\
","blurhash":"UeRV^Jj[*4j[M{fQxafQ?cfQIAfPxufQRkfQ","width":420,"height":420}],"tag":[{"type":"Mention","hre*](https://nrw.social/system/media_attachments/files/113/080/392/955/393/032/original/8acee728d823cf53.jpeg￼\",\"blurhash\":\"UeRV^Jj[4j[M{fQxafQ?cfQIAfPxufQRkfQ\",\"width\":420,\"height\":420}],\"tag\":[{\"type\":\"Mention\",\"hre)*
f":"[https://mastodon.social/users/derpostillon","name":"@derpostillon@mastodon.social"}],"replies":{"id":"https](https://mastodon.social/users/derpostillon\",\"name\":\"@derpostillon@mastodon.social\"}],\"replies\":{\"id\":\"https)
://[nrw.social/users/moesch/statuses/113080393202446473/replies","type":"Collection","first":{"type":"CollectionPa](http://nrw.social/users/moesch/statuses/113080393202446473/replies\",\"type\":\"Collection\",\"first\":{\"type\":\"CollectionPa)
ge","next":"[https://nrw.social/users/moesch/statuses/113080393202446473/replies?only_other_accounts=true&page=true](https://nrw.social/users/moesch/statuses/113080393202446473/replies?only_other_accounts=true&page=true)","
partOf":"[https://nrw.social/users/moesch/statuses/113080393202446473/replies","items":\[\]}}},"signature":{"type](https://nrw.social/users/moesch/statuses/113080393202446473/replies\",\"items\":[]}}},\"signature\":{\"type)":"
RsaSignature2017","creator":"[https://nrw.social/users/moesch#main-key","created":"2024-09-04T17:11:07Z","signatur](https://nrw.social/users/moesch#main-key\",\"created\":\"2024-09-04T17:11:07Z\",\"signatur)
eValue":"Urolx5N6l0SHu4rIpoySlfY7XB4Yr61z6EzTNOtKnNIyo/PdxIOd0/k2zRZ1JYJdSRc/YDYMV6RUjW/9t+UkBmm6xpkCE97KC1IuUP0RmEdIHqmj
1PEwzHoBS1jRQ1EZajWSPoJeZczKPYuiLGQtiK+E1ZdLYRLky1EDvTLUTyiwb5+wi5zhjTpbYbrI/wImJotSuFtY2dC0ob84Th0J/iGa6K1Dg1Hy+miuhCqKkzJ
46hmOfTAPVktL8HbCTk6Yww30d9ZYUxNQ3O0DIcVTMAd5AwLBUn7CBcOGspcMJaBz4Tp1LnQxUONXLuUGN0eRsSuetggWIav+3CwogGwQZQ=="}}",null,"Ac
count"],"class":"ActivityPub::ProcessingWorker","jid":"0215ce6f92cf696ed0da0e81","created_at":1725469868.6759377,"enqueued*
at":1725470368.4865763,"error_message":"failed to connect: Network is unreachable - connect(2) for 176.9.117.58:443 on http
s://[nrw.social/users/moesch#main-key","error_class":"HTTP::ConnectionError","failed_at":1725469868.7501945,"retry_count":4](http://nrw.social/users/moesch#main-key\",\"error_class\":\"HTTP::ConnectionError\",\"failed_at\":1725469868.7501945,\"retry_count\":4),
"error_backtrace":"eJyLVtLPLyjRLypNqtTPyUyCMIz1jPQM9Ivzk7NTS/SKkqwMjQzNrTLzFBLi\\n45Pz8/JSk0vi8/LzknKACtSVYgH4Mha7\\n","retri
ed_at":1725470082.136265}}
2024-09-04T17:19:28.510Z pid=7 tid=2plj WARN: HTTP::ConnectionError: failed to connect: Network is unreachable - connect(2)
for 176.9.117.58:443 on <https://nrw.social/users/moesch#main-key>
2024-09-04T17:19:28.510Z pid=7 tid=2plj WARN: /opt/ruby/lib/ruby/3.2.0/socket.rb:1217:in `\__connect_nonblock'
2024-09-04T17:19:37.641Z pid=7 tid=2jyj INFO: queueing Scheduler::AccountsStatusesCleanupScheduler (accounts_statuses_clean
up_scheduler)
2024-09-04T17:19:37.643Z pid=7 tid=2jzb INFO: queueing Scheduler::SuspendedUserCleanupScheduler (suspended_user_cleanup_sch
eduler)
2024-09-04T17:19:37.642Z pid=7 tid=2jzn INFO: queueing Scheduler::IndexingScheduler (indexing_scheduler)
2024-09-04T17:19:37.647Z pid=7 tid=2t1z class=Scheduler::AccountsStatusesCleanupScheduler jid=c3c15d9e838c75c56a314212 INFO
: start

**Comment by ThisIsMissEm** [comment]
@RJGhugo okay, so, I'm guessing sidekiq is running on a machine that only has IPv6, which means it can't reach IPv4 servers. You'll probably want to set up a IPv6 and IPv4 machine, with some sort of proxy and forward the requests through that. 

The `HTTP_PROXY` environment variable is what you'd want for that: https://docs.joinmastodon.org/admin/config/#http_proxy

I don't know what proxies exist out there already for this sort of setup.

**Comment by ThisIsMissEm** [comment]
Maybe something like these:
- https://github.com/lucasl0st/ipv4-for-ipv6_only-http-proxy
- https://github.com/stripe/smokescreen

Those I think can do IPv6 -> IPv4

**Comment by RJGhugo** [comment]
The NGNIX proxy (https://github.com/mastodon/mastodon/issues/31580#issuecomment-2309390704) has **IPv4 and IPv6** and is located in the DMZ segment. The communication between the proxy and Mastodon is IPv6 only.

The Mastodon instance is in a **IPv6** only segment.

The Mastodon instance is reachable (Firefox and Tuskey) from outside via **IPv4 only**, **dual stack** and **IPv6 only**.

Adding user (e.g. mho@social.heise.de) from an **IPv4 only** instance does not work.

I guess, in this case, Mastodon can not handle the IPv4-DNS-Request.

**Comment by ThisIsMissEm** [comment]
@RJGhugo by the looks of it, Mastodon is trying to make an outbound request to nrw.social which is ipv4 only, as this is happening from sidekiq, which only ipv6, the request fails. As such, you'd need to proxy those outbound requests through a server node that has both IPv6 and IPv4.

That is, it's not incoming traffic, but outgoing traffic that's failing. Mastodon needs to be able to make outbound requests to IPv4 addresses, if the instance it's attempting to contact does not support IPv6.

**Comment by RJGhugo** [comment]
For the outgoing traffic I have Tayga[1].

`ping nrw.social`
`PING nrw.social (64:ff9b::b009:753a) 56 Datenbytes`
`64 Bytes von 64:ff9b::b009:753a: icmp_seq=1 ttl=52 Zeit=11.7 ms`
`...`
`--- nrw.social ping-Statistik ---`
`4 Pakete übertragen, 4 empfangen, 0% packet loss, time 3004ms`
`rtt min/avg/max/mdev = 11.738/12.069/12.202/0.192 ms`

I can ping nrw.social...

[1]: https://docs.opnsense.org/manual/how-tos/tayga.html

**Comment by markrsmith83** [comment]
Is this more a routing issue? Do you need a route on the sidekiq server to send all ipv4 traffic to the proxy server?

**Comment by RJGhugo** [comment]
I am not sure about this!

It shoud work transparent...

**Comment by markrsmith83** [comment]
Take a look at this:
https://github.com/mastodon/mastodon/issues/19751

**Comment by RJGhugo** [comment]
Thank you @ThisIsMissEm and @markrsmith83 for the help.

The NGINX config is okay (https://github.com/mastodon/mastodon/issues/31580#issuecomment-2309390704).

The outgoing request via NAT64 were not activated in the Mastodon configuration.

Solved by adding: **ALLOWED_PRIVATE_ADDRESSES: 64:ff9b::/96**
