### ISSUE TITLE
OAuth Authorization Server Metadata not accessible by browser based apps

### ISSUE THREAD

**Issue by ThisIsMissEm** [mastodon/mastodon#31593]
### Steps to reproduce the problem

Try to do a `fetch` request to `https://mastodon.social/.well-known/oauth-authorization-server`, observe a CORS error

### Expected behaviour

Request should succeed

### Actual behaviour

Request fails with CORS error

### Detailed description

This was discovered by @chee

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-beta.1

### Technical details

n/a

**Comment by onyxblade** [comment]
I'm not able to reproduce this. Is there other background information like the error message?
![image](https://github.com/user-attachments/assets/c25f2ef7-c1d5-420b-ba77-90222b6b5848)
Chrome Version 127.0.6533.99 (Official Build) (64-bit)

I suspect this is related to the `content-security-policy` header in the browser app's response. Mastodon specifically allowed `'/.well-known/*'` in https://github.com/mastodon/mastodon/blob/main/config/initializers/cors.rb .

**Comment by ThisIsMissEm** [comment]
I'm not sure, was reported here, looks like the OP got it working. https://mastodon.social/@cheeaun/113027616819990261

I'm leaving this open to ensure we add test coverage to that endpoint to ensure it keeps having CORS set.

**Comment by ThisIsMissEm** [comment]
@cheeaun did you have any more information on this?

**Comment by ThisIsMissEm** [comment]
Sweet, I'm gonna go ahead and close this then. I'll open a new issue for test coverage of CORS headers as there isn't any right now.
