### ISSUE TITLE
Can't clear "Could not connect to Elasticsearch. Please check that it is running, or disable full-text search"

### ISSUE THREAD

**Issue by electricbrain-code** [mastodon/mastodon#31625]
### Steps to reproduce the problem

1. Install Mastodon
2. Enable "elasticsearch"
3. It did indeed have a connectivity issue - fixed
4. Fixed the connectivity issue - Opensearch is updating and seems OK. It appears to be working?
5. Can't clear "Could not connect to Elasticsearch. Please check that it is running, or disable full-text search"
...

### Expected behaviour

Error message in Admin screen should go away.

### Actual behaviour

 Could not connect to Elasticsearch. Please check that it is running, or disable full-text search 

### Detailed description

I have a detailed page explaining the deployment in some detail:
https://www.electricbrain.com.au/pages/desktop-datacenter-software/mastodon.php

The fact that the Admin page display the correct version information for Opensearch contradicts the "Could not connect to Elasticsearch" message. It is a https connection and the only way to get the correct version info is to "connect".

### Mastodon instance

mastodon.electricbrain.au

### Mastodon version

v4.2.10

### Browser name and version

Firefox 129.0.2 (64-bit)

### Operating system

Docker image: tootsuite/mastodon:v4.2.10

### Technical details

Software
Mastodon | 4.2.10
Ruby | 3.2.3p157
PostgreSQL | 14.13
Redis | 7.4.0
OpenSearch | 2.14.0

**Comment by markrsmith83** [comment]
What version of elasticsearch?

**Comment by electricbrain-code** [comment]
OpenSearch  2.14.0

**Comment by electricbrain-code** [comment]
This issue is resolved.
It turned out that /opt/mastodon/opt/mastodon/app/lib/admin/system_check/elasticsearch_check.rb at line that checks the index mapping:

  def mismatched_indexes
    @mismatched_indexes ||= INDEXES.filter_map do |klass|
      klass.base_name if Chewy.client.indices.get_mapping[klass.index_name]&.deep_symbolize_keys != klass.mappings_hash
    end
  end

asks the Opensearch cluster for a mapping using the deprecated deep_symbolize_keys function (which still works). However it appears that it asks for mappings for indices that are not prepended with the prepend setting (mastodon_ in this case). As such Opensearch denies access and so return a 403 access denied error.
So technically, I guess, the error message of can't access elasticsearch is actually correct.

The solution, for Opensearch, is to allow indices:admin/mappings/get on all indices, not just the prepended ones.
This worked and the issue is resolved. Obviously it is not ideal from a security perspective however.

**Comment by electricbrain-code** [comment]
Closed
