### ISSUE TITLE
Can't upload GIF and video files without ffmpeg, thumbnail generation fails

### ISSUE THREAD

**Issue by cadusilva** [mastodon/mastodon#31641]
### Steps to reproduce the problem

1. Enable `libvips` in `.env.production`
2. Uninstall `ffmpeg`
3. Try to upload a GIF or video file
4. Server returns error 503 about media thumbnail

### Expected behaviour

Upload successfull and thumbnail generated

### Actual behaviour

Error 503

### Detailed description

Similar to #30578, one can't upload GIF or video files without `ffmpeg` installed. I have `MASTODON_USE_LIBVIPS` set to `true` and tried to uninstall `ffmpeg`, but Paperclip still looks for it.

Mastodon shows this error:

```
500 Error processing thumbnail for uploaded media
``` 
Checking the server logs, I saw this line:

```
E, [2024-08-28T16:10:41.767007 #1184431] ERROR -- : [709e5a61-99e3-46a8-b4b2-baec3df82917] Paperclip::Errors::CommandNotFoundError: Could not run the `ffmpeg` command. Please install ffmpeg.
``` 

### Mastodon instance

bolha.one

### Mastodon version

v4.3.0-beta.1-f6fb9b7

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: `ruby 3.3.4`
- Node.js version: `v20.17.0`

**Comment by vmstan** [comment]
libvips only replaces ImageMagick for processing static images like JPEG, PNG and such.

ffmpeg is still required for video and animated images like GIF.

**Comment by cadusilva** [comment]
> libvips only replaces ImageMagick for processing static images like JPEG, PNG and such.
> 
> ffmpeg is still required for video and animated images like GIF.

Oh right, so I guess I'll close the issue. Thank you for the clarification.
