### ISSUE TITLE
Minor: I'd like it if a … was printed to indicate missing lines in batched notifications

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#31645]
This is minor.

In the new batched notification view, when showing favs or boosts the post text is truncated:

![image](https://github.com/user-attachments/assets/4eb7a8b4-3807-4e9c-8a93-a000e01d7951)

If a paragraph is cut off, it ends with a …

But if an entire line or paragraph is removed, there is no indication of missing content.

I think it would be better if there were a … also on the posts that had paragraphs removed. This would be more consistent (since it does appear on incomplete paragraphs) and also less mental overhead to parse. I keep looking at a post going "I don't remember making this" and then remembering "oh, right, truncation". This is especially bad if the first line is filler text like "Okay."

I think the … should go on its own line, and maybe have an entire blank line followed by a … line. But I understand you're trying to reduce vertical space taken up by posts.

**Comment by renchap** [comment]
This should have been fixed by https://github.com/mastodon/mastodon/pull/32348

Note that the ellipsis will not be shown in Safari, due to a webkit but (linked in the PR).
