### ISSUE TITLE
The mute user options only use color to indicate the selected option

### ISSUE THREAD

**Issue by stefan-scholl** [mastodon/mastodon#31661]
### Steps to reproduce the problem

Mute a user and click “Show Options”. You now see multiple circles that only indicate they are selected by changing the color.

### Expected behaviour

Filled circles, point in circle. Something like a real radio button.

### Actual behaviour

Empty circles, only other color.

### Detailed description

See image.

![image](https://github.com/user-attachments/assets/7bc3d1ca-89cb-4278-887b-c0cd8162608a)

The simulated radio buttons look differently from real radio buttons and make it hard for the user to see what they have selected.

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-08-28

### Browser name and version

Google Chrome 128.0.6613.114

### Operating system

Windows 10

**Comment by ClearlyClaire** [comment]
The radio button is meant to have a full circle inside it, but currently doesn't because of inconsistencies in our markup. I will have a go at fixing that.
