### ISSUE TITLE
4.3.0-beta.1: The message window is not displayed correctly

### ISSUE THREAD

**Issue by Izorkin** [mastodon/mastodon#31679]
### Steps to reproduce the problem

1. The message box is displayed incorrectly when the browser window width is small.
2. Set the window size to a width of 1200 to 1167 pixels.
![vivaldi_2024-09-01_17-48-27](https://github.com/user-attachments/assets/a5f98fab-ed7e-4a12-b6ec-35d381fd9e5c)

### Expected behaviour

The message box is cropped to the left

### Actual behaviour

The message window is displayed correctly

### Mastodon instance

example.com

### Mastodon version

4.3.0-beta.1

### Browser name and version

Vivaldi 6.2.3105.58

### Operating system

Windows 10 22H2

**Comment by ClearlyClaire** [comment]
I can reproduce the issue on Firefox, although I believe this to be older than 4.3.

**Comment by Izorkin** [comment]
Maybe, I just updated from version 4.2.12 the other day. I didn't see this error before.
Is there any way to fix it? I can pre-check with myself.

**Comment by ClearlyClaire** [comment]
You're right, it has been introduced by #28119. I think it has been introduced by switching in-column 10px padding to 16px `gap` property, so the necessary width changed from 2×285px+600px to 2×(285px + 16px) + 600px.

So the fix is to either reduce the size of the middle column by 32px, or change the UI breakpoint.

**Comment by Izorkin** [comment]
Thanks!

**Comment by Izorkin** [comment]
@ClearlyClaire щn version 4.3.0, the error is repeated again.

**Comment by Izorkin** [comment]
I think we should move the search and message fields a few pixels to the right.
![Image](https://github.com/user-attachments/assets/cfd848a9-c519-4dc0-92d0-f2b21583bcaa)

**Comment by ClearlyClaire** [comment]
> [@ClearlyClaire](https://github.com/ClearlyClaire) on version 4.3.0, the error is repeated again.

I'm unable to reproduce the issue.

**Comment by Izorkin** [comment]
> I'm unable to reproduce the issue.

Yes, right now the search box rests on the left edge. I would like to leave a gap of a few pixels.
