### ISSUE TITLE
Cannot login to mastodon using the app in my android phone

### ISSUE THREAD

**Issue by reshmiaravind** [mastodon/mastodon#31685]
### Steps to reproduce the problem

I tried to login to mastodon via app (android phone)and  everytime it tells invalid email address and password. But login via browser on my phone works

### Expected behaviour

Login via phone app must work

### Actual behaviour

Login via app gives invalid email address and password 

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by ClearlyClaire** [comment]
Hi! Are you using the official Mastodon Android app, or another application? Also, which server are you trying to log into?

**Comment by reshmiaravind** [comment]
Yes.mastodon.social.
But it works for web.

**Comment by reshmiaravind** [comment]
Closing this issue because now I'm able to login .
I think when I switched to mstdn.social instead of mastodon.social

**Comment by reshmiaravind** [comment]
Closing this as it works for me.
