### ISSUE TITLE
DomainValidator does not correctly block invalid domains

### ISSUE THREAD

**Issue by ThisIsMissEm** [mastodon/mastodon#31682]
### Steps to reproduce the problem

1. Try creating a DomainBlock for `*.example.com`
2. Observe that it succeeds

### Expected behaviour

This should fail because *.example.com isn't a valid domain, only example.com is

### Actual behaviour

Validation passes without errors

### Detailed description

Currently some people are creating domain blocks that would never actually match, where they're using `*.` as a prefix to try to mean "all subdomains of this domain", but the effect is a rule that never matches.

`Addressable::URI` used in DomainValidator appears to consider a host of `*.example.com` perfectly valid (I've no idea why), as such we probably need better validation of domains.

### Mastodon version

4.3.0 / main

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: 3.3.4
- Node.js version: n/a

**Comment by quintessence** [comment]
Suggestion: if the `*.example.com` fails in particular, add helper text that appears with the information: "Trying to block all subdomains of example.com? Just put in example.com."

**Comment by ThisIsMissEm** [comment]
Turns out this could be a bug in addressable, which treats `Addressable::URI.parse('*.example.com')` as being a URI consisting of just a path:

```
irb(main):070> Addressable::URI.parse('*.example.com').path
=> "*.example.com"
irb(main):070> Addressable::URI.parse('*.example.com').to_s
=> "*.example.com"
```

It seems when using `Addressable::URI.new.tap` the host isn't actually validated for some reason.

**Comment by mjankowski** [comment]
I believe this resolved as side effect of https://github.com/mastodon/mastodon/pull/31819/files#diff-fab37278bfec2e4b30f15a75e116cc7163d75892a806dab037fe12c4fe4e3765L19-R26 

If not, can you provide some console actions to show remaining error?
