### ISSUE TITLE
Colour theme for image description edit modal is mismatched

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon#31690]
### Steps to reproduce the problem

Click "edit" on uploaded image, And see this modal dialog
![image](https://github.com/user-attachments/assets/92a49b13-eb49-46f4-8fe1-b7d72c74bf5e)

### Expected behaviour

Matched color theme with other modals

### Actual behaviour

Modal's background is light while its textedit box and other modals are dark

### Detailed description

Other modals using dark theme
Boost:
![image](https://github.com/user-attachments/assets/4d60257d-f1f6-4455-bf93-95f4e24d41f5)
Mute user:
![image](https://github.com/user-attachments/assets/e6c7e6d0-a3d1-40b7-86a9-998f86c0dc82)

### Mastodon instance

development version

### Mastodon version

v4.3.0-beta.1

### Browser name and version

Firefox 129.0.2

### Operating system

Ubuntu 22.04.4 LTS

**Comment by ClearlyClaire** [comment]
This is known and being worked on!
