### ISSUE TITLE
Real-Time Block List Subscription

### ISSUE THREAD

**Issue by Masked-Witch** [mastodon/mastodon#31705]
### Pitch

Some XMPP servers use a real-time blocklist module that allows server administrators to subscribe to a centralized list. The module automatically blocks addresses on the list from being able to join chatrooms hosted on the server, or kicking those addresses if they are already joined (more information here: https://xmppbl.org/ ).

I think something similar could be used, where a Mastodon instance administrator could have their instance subscribe to a list maintained by people the administrator trusts that automatically blocks any addresses that make it onto the list for everyone on that instance. Having an option for the instance to only have other instances that use the same subscription in its global timeline I would also recommend.

### Motivation

I think this would help cut down on harassment of marginalized and targeted people on instances interested in creating safe spaces.

**Comment by ThisIsMissEm** [comment]
This is a duplicate. See #29022

**Comment by Masked-Witch** [comment]
Okay, closing this one in favor of https://github.com/mastodon/mastodon/issues/116
