### ISSUE TITLE
Error 422 when posting something with media attached

### ISSUE THREAD

**Issue by cadusilva** [mastodon/mastodon#31707]
### Steps to reproduce the problem

1. Attach a picture to a new post
2. Try to publish it (with or without text)
3. Error: `422 Media {id} not found or already attached to another post`

### Expected behaviour

Post published with the media attached

### Actual behaviour

Error 422

### Detailed description

After #31681, it's no longer possible to publish a new toot with media attached. It immediately throws an error `422 Media {id} not found or already attached to another post`. It doesn't matter if the post contains text or not. Broken via web and via apps.

### Mastodon instance

bolha.one, ursal.zone

### Mastodon version

v4.3.0-beta.1-491033c

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: `3.3.4`
- Node.js version: `20.17.0`

**Comment by c960657** [comment]
Fix coming up.
