### ISSUE TITLE
Notifications don't work any more in the web client with Firefox ESR 102

### ISSUE THREAD

**Issue by taljeth** [mastodon/mastodon#31712]
### Steps to reproduce the problem

1. Go to the notifications page and see it doesn't load
2. Check the notifications item in the menu and see that it doesn't show a number even though other devices do show that there are notifications

### Expected behaviour

The notification page should load successfully

### Actual behaviour

The notification page encounters a Javascript error and keeps showing a spinner

### Detailed description

On one system, I'm still using Firefox ESR 102, and I found that the notifications page on mastodon.online doesn't load any more. Also, I knew that I had notifications, but the number didn't show in the menu. The browser console shows a Javascript error.

### Mastodon instance

mastodon.online

### Mastodon version

v4.3.0-nightly.2024-08-30

### Browser name and version

Firefox ESR 102

### Operating system

openSUSE 15.3

### Technical details

The Javascript error I see on the browser console is the following:
```
Uncaught (in promise) TypeError: i.findLast is not a function
    Ne notification_groups.ts:267
    Pe notification_groups.ts:287
    Re notification_groups.ts:413
    s createReducer.ts:179
    produce immer.legacy-esm.js:589
    s createReducer.ts:178
    s createReducer.ts:151
    default inert.esm.js:76
    default inert.esm.js:73
    Lt Immutable
    default inert.esm.js:73
    b Redux
    dispatch autoBatchEnhancer.ts:114
    un sounds.ts:83
    rn errors.ts:50
    sn loading_bar.ts:84
    a index.js:2139
    dispatch Redux
    h createAsyncThunk.ts:369
```
This call seems to have been added recently in commit f587ff643f (#30440).

**Comment by ClearlyClaire** [comment]
Hi! Thank you for your report. We will consider it, but Firefox 102 ESR is unsupported.

**Comment by taljeth** [comment]
That's fair, I don't really have a good excuse to still be using Firefox ESR 102 on a desktop Linux. However, I'm also using the browser app on Sailfish OS (for which I also reported #31713), which is using an old Gecko engine even in it's latest shipped version, so I imagine that it would hit this one, too, once the first one is fixed. And already using the latest version for that one does feel like a better excuse at least. So if you could consider fixing that even though it's based on a rather old browser engine, that would be much appreciated.

By the way, I was looking for a list of supported browsers before I opened the two issues, but I couldn't find one. Is this in the documentation somewhere?

**Comment by taljeth** [comment]
I checked it, the current Gecko version used by the Sailfish OS browser is ESR 78.15.1, and they are currently working on a pull request (https://github.com/sailfishos/gecko-dev/pull/162) to update it to ESR 91.9.0. I guess the plan is to catch up step by step going from one ESR release to the next one.

**Comment by ClearlyClaire** [comment]
Oof, Firefox ESR 78.15.1 is fairly old (and long unmaintained)! I'm not sure it would make sense for us to support it. Even Firefox ESR 91 has been unmaintained for a while :/

**Comment by taljeth** [comment]
While I knew that it's old, it is indeed even a bit more ancient than I expected originally... On the other hand, Mastodon worked fine on it before the recent updates, so there's probably not much that is missing from it in practice.

Thanks for addressing it, I'll try to remember to report back once it's deployed.

**Comment by ClearlyClaire** [comment]
The update has been deployed, can you check if this solves your issue?

**Comment by taljeth** [comment]
Yes, now it works fine again. Thanks!
