### ISSUE TITLE
Web client doesn't load any more on sailfish-browser

### ISSUE THREAD

**Issue by taljeth** [mastodon/mastodon#31713]
### Steps to reproduce the problem

1. Open mastodon.online in sailfish-browser

### Expected behaviour

The mastodon web client should load and show my home feed

### Actual behaviour

Only the background is shown, no content or even UI elements load due to a Javascript error

### Detailed description

mastodon.online used to work fine on Sailfish OS until a few days ago. I don't know exactly when it upgraded and from which version, but this suggests to me that it is a recent regression.

### Mastodon instance

mastodon.online

### Mastodon version

v4.3.0-nightly.2024-08-30

### Browser name and version

sailfish-browser-2.2.61-1.12.1.jolla.armv7hl

### Operating system

Sailfish OS 4.5

### Technical details

When running sailfish-browser with the environment variable `EMBED_CONSOLE=1` set, I get the following output:
```
JavaScript error: https://mastodon.online/packs/js/common-55ba23609956620b878d.js, line 2: TypeError: Object.hasOwn is not a function
CONSOLE message:
[JavaScript Error: "TypeError: Object.hasOwn is not a function" {file: "https://mastodon.online/packs/js/common-55ba23609956620b878d.js" line: 2}]
_@https://mastodon.online/packs/js/common-55ba23609956620b878d.js:2:975717
v@https://mastodon.online/packs/js/common-55ba23609956620b878d.js:2:975589
@https://mastodon.online/packs/js/common-55ba23609956620b878d.js:2:976597
s@https://mastodon.online/packs/js/common-55ba23609956620b878d.js:2:35831
@https://mastodon.online/packs/js/common-55ba23609956620b878d.js:2:131275
s@https://mastodon.online/packs/js/common-55ba23609956620b878d.js:2:35831
@https://mastodon.online/packs/js/common-55ba23609956620b878d.js:2:465627
s@https://mastodon.online/packs/js/common-55ba23609956620b878d.js:2:35831
1345@https://mastodon.online/packs/js/application-109fb489d7dc47acd238.chunk.js:1:24937
s@https://mastodon.online/packs/js/common-55ba23609956620b878d.js:2:35831
n@https://mastodon.online/packs/js/common-55ba23609956620b878d.js:2:430
t@https://mastodon.online/packs/js/common-55ba23609956620b878d.js:2:293
@https://mastodon.online/packs/js/application-109fb489d7dc47acd238.chunk.js:1:47
```

**Comment by ClearlyClaire** [comment]
`hasOwn` is supported by the overwhelming majority of browsers; nevertheless, we did include polyfills for it through #29654

If those polyfills are not loaded, this may be because of an issue in our setup, or our browserlist not matching any of those browsers anymore

**Comment by taljeth** [comment]
Nice, this sounds like a fix won't be too complicated. If I can help you to find out why the polyfills are not loaded in the Sailfish OS browser, please let me know what to test.
