### ISSUE TITLE
Admin emails use user's localization rather than server's

### ISSUE THREAD

**Issue by micr0-dev** [mastodon/mastodon#31715]
### Steps to reproduce the problem

1. Be an admin of an instance
2. Require verification for new accounts
3. As another user: Make a new account with a non default localization
4. As an admin: Receive email with wrong localization 

### Expected behaviour

Email to admin should be standard/default localization

### Actual behaviour

Email to admin is sent in the user's localization

### Detailed description

If a user sets their language to some other language the email that comes to the admin of the instance to verify them is of that localization rather than the instances default.

User has this selected:
![image](https://github.com/user-attachments/assets/f2292a75-27ce-4ae8-abf5-0b54a3d00adf)

Email received **to the admin:**
![image](https://github.com/user-attachments/assets/b97f9dfa-33e1-4e9d-8d92-14f89cf803bd)

Translation:
```
New account up for review on fuzzies.wtf
The details of the new account are below. You can approve or reject this application.
```

### Mastodon instance

fuzzies.wtf

### Mastodon version

v4.3.0-alpha.5+no-portals

### Technical details

- Ruby version: ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux]
- Node.js version: v20.17.0

**Comment by ClearlyClaire** [comment]
The locale used should be the one of the admin. I'm not sure why you would want it otherwise.

**Comment by micr0-dev** [comment]
That's what I'm saying, it **should** be the admins, but it isn't. It uses the user's locale

**Comment by ClearlyClaire** [comment]
How did the user change interface language?

**Comment by micr0-dev** [comment]
I will ask them

**Comment by ClearlyClaire** [comment]
Interesting, I can reproduce the issue if and only if the two following conditions are met:
- the new user has a locale set
- the admin receiving the mail has no locale set

**Comment by darltrash** [comment]
> How did the user change interface language?

I... didn't! I actually didn't, I didn't even notice it was on spanish at first!

**Comment by ClearlyClaire** [comment]
> > How did the user change interface language?
> 
> I... didn't! I actually didn't, I didn't even notice it was on spanish at first!

Nevermind, this should be automatically set at registration time.
