### ISSUE TITLE
(More) Federation with Bluesky (and Threads)

### ISSUE THREAD

**Issue by h-2** [mastodon/mastodon#31771]
### Pitch

* I am a long-time Mastodon user, but I see more and more people I'd like to follow on bluesky or Threads
* It would be nice if interacting with people on those platforms were seamless (i.e. not requiring weird opt-in mechanisms like "following account FOO" or putting a codeword in your bio)
* Federation with Threads seems to be getting there slowly (and this mostly depends on Threads IIANM?)
* Federation with BlueSky works via [Bridgy](https://github.com/snarfed/bridgy-fed/)—proving that it's possible. But it is not seamless at all, and only a tiny fraction of users knows about it/uses it.

→ it would be nice if such functionality were available by default. This could happen by hosting and federating with a Bridgy instance by default. Or implementing other compatibility layers (likely more work).

### Motivation

Well... Federation is the whole point, right?

* Grow the network
* Reach more people that are not nerds
* Be able to follow some high-impact users like large news sources, famous people
* Not have to create an account on those other sites
* Make competition to X more viable

I assume a (vocal) minority to not want this, but everyone is free to block by domain or change the settings on their own instance. Of course, one could add dedicated options for "federating with foreign protocols / platforms", but since the current federation model is opt-out anyway, I don't see why that should be different here.

**Comment by trwnh** [comment]
I don't think there's anything Mastodon can do here. It's up to Threads and Bridgy-Fed to implement anything they might be missing at a federation level. Any further improvements to their policies should be reported to them. For example, if Bridgy-Fed "requires weird opt-in mechanisms" then that should be something you ask Bridgy-Fed about.

**Comment by h-2** [comment]
Thank you for the quick reply! 

> I don't think there's anything Mastodon can do here.

I politely disagree! 

**Low effort:** Mastodon (the software project) could announce that federation with BlueSky is desirable. This would increase visibility and support for projects like Bridgy. It would allow them to be less conservative and maybe remove the opt-in.

**Medium effort:** It could engage with BlueSky on a publicity or even policy / design level to make compatibility more well-known and better integrated, e.g. asking users on sign-up if they want to federate with the respective other; or adding a special icon for users from the other network; …

**Bigger effort:** Contribute to or even take over stewardship of projects like Bridgy. Host your own instance of it. Integrate more tightly with it by default...

*Who, other than you, would be able to do these things?*

I know that this is all work and that resources are limited, but I kindly ask you to consider these questions as part of the bigger picture. With the "twitter-alternatives-world" fragmenting more and more, proper cross-federation might be one of the most important features.

**Comment by h-2** [comment]
> For example, if Bridgy-Fed "requires weird opt-in mechanisms" then that should be something you ask Bridgy-Fed about.

Just to clarify: if bridgy or someone else were to provide a mechanism that connects to BlueSky **without opt-in** (i.e. opt-out), you would support/non-block such a mechanism on mastodon.social?

**Comment by praichor** [comment]
> I don't think there's anything Mastodon can do here. 

Implement ATProto in addition to ActivityPub.
