### ISSUE TITLE
Search remote account 404 error

### ISSUE THREAD

**Issue by Kitanit** [mastodon/mastodon#31776]
### Steps to reproduce the problem

1. search profile in mastodon(app or web)
2. get error 404

### Expected behaviour

Result profile found

### Actual behaviour

404 error

### Detailed description

![image](https://github.com/user-attachments/assets/0a359ebc-6d98-46a7-a8a0-c90635ec4273)

### Mastodon instance

soc.ua-fediland.de

### Mastodon version

v4.3.0-nightly.2024-08-24+glitch

### Technical details

docker

**Comment by ClearlyClaire** [comment]
Your server is blocked by the server you are trying to fetch an account form.
