### ISSUE TITLE
Windows Phone 10, Edge : Gif are not animated

### ISSUE THREAD

**Issue by xakan** [mastodon/mastodon#3181]
Hi,

When I am on Mastodon with my Windows Phone, I can't see gif. They are displayed, but not animated. Even when I click on it.

I don't experience the same issue with Chrome on Android for example.

Thank you for all your great job,

xakan

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by yookoala** [comment]
What is the version of your Windows Phone?

**Comment by xakan** [comment]
Hello, I don't remember which was the version. I sold it yesterday. But it was up to date.

**Comment by trwnh** [comment]
closing as stale. if windows phone comes back from the dead and you can reproduce this bug, please feel free to file a new issue
