### ISSUE TITLE
Web and app not sending push notifications 

### ISSUE THREAD

**Issue by jotaluissoy** [mastodon/mastodon#31847]
### Steps to reproduce the problem

1. Open the web
2. Enter on mastodon.social account 
3. No push notifications at all
...

### Expected behaviour

It is expected that I will be notified (push)

### Actual behaviour

It never sends push notifications. It's been happening since three or more days ago.

### Detailed description

The web and, of course, the official app are not sending push notifications. It seems it needs updating:
https://github.com/mastodon/webpush-fcm-relay/tree/master

### Mastodon instance

mastodon.social

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by renchap** [comment]
Google Deprecated the Android notification API our push relay is using. We are testing a new SDK which should fix the issue today.

Relevant PR in the relay repository: https://github.com/mastodon/webpush-fcm-relay/pull/5

This should only impact the Android app, not the web.

**Comment by renchap** [comment]
We updated the notification relay to the new Firebase API, and it should now be working again.

**Comment by jotaluissoy** [comment]
Working again! Feedback from somewhere in Latin America.
Thanks for your job!
