### ISSUE TITLE
cannot follow, post or interact with other instances

### ISSUE THREAD

**Issue by szethh** [mastodon/mastodon#31903]
### Steps to reproduce the problem

This is a fresh install, on NixOS. It's running on single user mode, and my `LOCAL_DOMAIN` and `WEB_DOMAIN` match.
I cannot find [myself](https://mastodon.social/@clara@social.bnuuy.net) via search on other instances (like mastodon.social). I also cannot see my posts through there.

I have tried following people on these instances, but it does not work. When I click the follow button, it changes to "following", but my following count does not change. If I refresh the page, it changes to "cancel follow" and it acts as if I sent a follow request (even for profiles that don't require follow approval).

My sidekiq queue has some jobs that keep retrying:
- If I try to post or comment: `Mastodon::UnexpectedResponseError: https://mastodon.social/inbox returned code 401`
- If I try to follow: `Mastodon::UnexpectedResponseError: https://mastodon.social/users/Gargron/inbox returned code 401`
- This happens sometimes after I attempt a follow: `Stoplight::Error::RedLight: https://mastodon.social/users/Gargron//inbox`

`journalctl -fu mastodon-web` shows no errors, just normal requests.

My webfinger seems to be fine:
https://social.bnuuy.net/.well-known/webfinger?resource=acct:clara@social.bnuuy.net

### Expected behaviour

being able to follow, post and be visible on other instances

### Actual behaviour

i seem to be unreachable from other instances

### Mastodon instance

social.bnuuy.net

### Mastodon version

v4.2.10

**Comment by renchap** [comment]
Here is what I get when trying to connect to your instance: 

<img width="1406" alt="image" src="https://github.com/user-attachments/assets/32af8f0c-f705-4ba7-9337-a7ec6832dbcd">


There must be a wrong Cloudflare configuration on your side preventing incoming requests

**Comment by szethh** [comment]
@renchap you are completely right, I set up (and forgot about) a cloudflare firewall rule to block all connections from outside the NL...

I'm sorry for the false flag, closing now
