### ISSUE TITLE
New scrollbar color in beta.2 is distracting

### ISSUE THREAD

**Issue by gunchleoc** [mastodon/mastodon#31951]
### Pitch

I find the scollbar in beta.2 next to the menu distracting. It is also much brighter than the main scroll bar

![image](https://github.com/user-attachments/assets/61409dd0-0267-4f59-9a8c-fa36d5233e4a)

### Motivation

It will be easier to read & concentrate on the posts not seeing this bright line in the corner of my eye

**Comment by ClearlyClaire** [comment]
> It is also much brighter than the main scroll bar

The main scrollbar?

**Comment by ClearlyClaire** [comment]
@gunchleoc would you be ok if your 4 lists stopped being displayed, only showing “Lists” instead?
