### ISSUE TITLE
No-gap layout is used at sizes that are too large for it to work well

### ISSUE THREAD

**Issue by daprice** [mastodon/mastodon#31973]
### Steps to reproduce the problem

1. Open the mastodon web interface on a large tablet in landscape mode

### Expected behaviour

Nicely proportioned three-column layout

### Actual behaviour

Stretched out version of a layout that’s more appropriate for phones held in portrait orientation

### Detailed description

With #31889, the breakpoint for the no-gap layout was increased to 1206px. This results in at least some iPads in landscape orientation (where we expect to see a full desktop-class layout on most websites) getting the no-gap layout, where it is strangely proportioned and less functional than the previous three-column layout. In particular, because the no-gap layout stretches everything to almost the full width of the display, portrait images end up being too tall to see the entire image, link preview cards are nearly full-screen (on a tablet, this is physically very large!), and text-only posts create large areas of whitespace.

Prior to this change:
![323378668-42f09faa-7f19-4b75-a3ef-1b9fcbd62033](https://github.com/user-attachments/assets/fee614a0-1b4a-49f9-ab6d-a4cf3e007fb4)

After this change (on an 11” iPad Pro), showing how you can’t even see the entirety of one post that has a link preview card in it:
![368347295-6f1fe061-a3ae-42df-905a-5b447349e4d3](https://github.com/user-attachments/assets/39b0e0f6-49df-4446-a7f5-cb544e39df55)

### Mastodon instance

mastodon.social, mastodon.online

### Mastodon version

v4.3.0-beta.2+pr-31960-9262aa2

### Browser name and version

Safari (iPadOS 18.0)

### Operating system

iPadOS 18.0

**Comment by Cryszon** [comment]
Besides tablets, this also affects desktops when using certain monitors in vertical orientation. For example, I normally browse Mastodon on a vertical 16:10 monitor with 1200 pixels wide resolution.
