### ISSUE TITLE
Text is overlapping in hashtag moderation view for status in French

### ISSUE THREAD

**Issue by Coukaratcha** [mastodon/mastodon#31976]
### Steps to reproduce the problem

1. Go to `admin/tags/`
2. Select any tag

![image](https://github.com/user-attachments/assets/685db191-2e96-4132-a667-a16abe47676e)

### Expected behaviour

Text is displayed on 1 line

### Actual behaviour

Text is displayed on 2 lines and overlapping next block

### Detailed description

Text for status of hashtag moderation is overlapping the next line because it is displayed on 2 lines.

### Mastodon instance

social.coukaratcha.fr

### Mastodon version

v4.3.0-beta.2

### Browser name and version

Firefox 130.0.1 (64 bits)

### Operating system

Windows 11

**Comment by judyfong** [comment]
Haha just switch to english and it'll be fine. Or use more acronyms
