### ISSUE TITLE
Can't federate with Threads/Pixelfed on my new instance

### ISSUE THREAD

**Issue by matlfb** [mastodon/mastodon#32013]
### Steps to reproduce the problem

1. I installed a mastodon instance on my own server (with [this tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-mastodon-on-ubuntu-20-04))
2. Installation is complete and it's all working. I imported all of my old account followings into the new one, but users from Threads I followed couldn't be imported & failed
3. I searched for Threads accounts (as such as @threads@threads.net) with the search on my new instance but found none of them. In the case of pixelfed I can follow pixelfed accounts, but they can't see my profile or my picture publications.
...

### Expected behaviour

I should be able to follow Threads federated accounts and Pixelfed accounts should be able to see my post and my profile picture

### Actual behaviour

I can't follow Threads federated accounts + Pixelfed users can't see my content

### Detailed description

Federation works with Flipboard, but doesn't seem entirely working with Pixelfed 

### Mastodon instance

zelk.space

### Mastodon version

v4.2.12

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.2.2)
- Node.js version: (from `node --version`, eg. v18.19.1)

**Comment by renchap** [comment]
This is not an issue with the Mastodon software, but probably with your installation / settings.

I see that you disabled the public local timeline, Threads.net requires this to be available to federate with them (see https://help.instagram.com/914046486923176/). It may be the reason.

**Comment by matlfb** [comment]
Are you talking about live feeds > this server or explore > posts ? Because I enabled live feeds > this server but I don't know how to enable Explore > Posts.

I enabled it like an hour ago, but I still can't find or follow threads accounts yet, it may need some time for them to see changes. I also checked the threads blocked instances list, but mine isn't displayed.

**Comment by renchap** [comment]
Are you getting an error when you access https://zelk.space/@threads@threads.net ?

There should be something in the puma/web logs that points to the problem.

**Comment by matlfb** [comment]
I have something in the logs : 

`sept. 22 19:43:21 zelk bundle[1319]: I, [2024-09-22T19:43:21.249362 #1319]  INFO -- : [bd97e26c-10f6-4b90-9faf-09828af242ef] method=POST path=/inbox format=*/* controller=ActivityPub::InboxesController action=create status=401 allocations=14830 duration=114.26 view=0.59 db=1.00 key=https://threads.net/ap/users/17841403891371853/#main-key`

**Comment by matlfb** [comment]
It took some time but I'm now federated with Threads. Thanks for you help :)
