### ISSUE TITLE
Some received statuses dont process and die with `Regexp::TimeoutError: regexp match timeout`

### ISSUE THREAD

**Issue by rrgeorge** [mastodon/mastodon#32051]
### Steps to reproduce the problem

1. Receive status
2. Check sidekiq morgue for failed jobs
3. See failed `activitypub::ProcessingWorker` jobs with the error `Regexp::TimeoutError: regexp match timeout`
4. Attempting to view the status manually results in an http 500

### Expected behaviour

For the status to be processed and delivered locally

### Actual behaviour

The status cannot be processed and is never delivered locally

### Detailed description

An example status received:
```
109498147060647699, "{\"@context\":[\"https://www.w3.org/ns/activitystreams\",{\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\",\"inReplyToAtomUri\":\"ostatus:inReplyToAtomUri\",\"conversation\":\"ostatus:conversation\",\"sensitive\":\"as:sensitive\",\"toot\":\"http://joinmastodon.org/ns#\",\"votersCount\":\"toot:votersCount\",\"blurhash\":\"toot:blurhash\",\"focalPoint\":{\"@container\":\"@list\",\"@id\":\"toot:focalPoint\"},\"Hashtag\":\"as:Hashtag\"},\"https://w3id.org/security/v1\"],\"id\":\"https://mastodon.social/users/gwaldby/statuses/113187318090872531/activity\",\"type\":\"Create\",\"actor\":\"https://mastodon.social/users/gwaldby\",\"published\":\"2024-09-23T14:23:31Z\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"cc\":[\"https://mastodon.social/users/gwaldby/followers\"],\"object\":{\"id\":\"https://mastodon.social/users/gwaldby/statuses/113187318090872531\",\"type\":\"Note\",\"summary\":null,\"inReplyTo\":null,\"published\":\"2024-09-23T14:23:31Z\",\"url\":\"https://mastodon.social/@gwaldby/113187318090872531\",\"attributedTo\":\"https://mastodon.social/users/gwaldby\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"cc\":[\"https://mastodon.social/users/gwaldby/followers\"],\"sensitive\":false,\"atomUri\":\"https://mastodon.social/users/gwaldby/statuses/113187318090872531\",\"inReplyToAtomUri\":null,\"conversation\":\"tag:mastodon.social,2024-09-23:objectId=805965626:objectType=Conversation\",\"content\":\"\\u003cp\\u003eJosh Riley is running for Congress with a promise: he will never take a penny from corporate PACs because he\\u0026#39;s fighting for neighborhoods like the one that raised –-not the special interests. \\u003ca href=\\\"https://mastodon.social/tags/BlueWaveRising\\\" class=\\\"mention hashtag\\\" rel=\\\"tag\\\"\\u003e#\\u003cspan\\u003eBlueWaveRising\\u003c/span\\u003e\\u003c/a\\u003e \\u003ca href=\\\"https://mastodon.social/tags/NY19\\\" class=\\\"mention hashtag\\\" rel=\\\"tag\\\"\\u003e#\\u003cspan\\u003eNY19\\u003c/span\\u003e\\u003c/a\\u003e\\u003c/p\\u003e\",\"contentMap\":{\"en\":\"\\u003cp\\u003eJosh Riley is running for Congress with a promise: he will never take a penny from corporate PACs because he\\u0026#39;s fighting for neighborhoods like the one that raised –-not the special interests. \\u003ca href=\\\"https://mastodon.social/tags/BlueWaveRising\\\" class=\\\"mention hashtag\\\" rel=\\\"tag\\\"\\u003e#\\u003cspan\\u003eBlueWaveRising\\u003c/span\\u003e\\u003c/a\\u003e \\u003ca href=\\\"https://mastodon.social/tags/NY19\\\" class=\\\"mention hashtag\\\" rel=\\\"tag\\\"\\u003e#\\u003cspan\\u003eNY19\\u003c/span\\u003e\\u003c/a\\u003e\\u003c/p\\u003e\"},\"attachment\":[{\"type\":\"Document\",\"mediaType\":\"video/mp4\",\"url\":\"https://files.mastodon.social/media_attachments/files/113/187/316/991/092/664/original/900a9dfa0b6a85d1.mp4\",\"name\":null,\"blurhash\":\"UKH{ZsMc4TMwJE8^t7j^MbV?IU%gt7Rjoex]\",\"width\":1920,\"height\":1080}],\"tag\":[{\"type\":\"Hashtag\",\"href\":\"https://mastodon.social/tags/bluewaverising\",\"name\":\"#bluewaverising\"},{\"type\":\"Hashtag\",\"href\":\"https://mastodon.social/tags/ny19\",\"name\":\"#ny19\"}],\"replies\":{\"id\":\"https://mastodon.social/users/gwaldby/statuses/113187318090872531/replies\",\"type\":\"Collection\",\"first\":{\"type\":\"CollectionPage\",\"next\":\"https://mastodon.social/users/gwaldby/statuses/113187318090872531/replies?only_other_accounts=true\\u0026page=true\",\"partOf\":\"https://mastodon.social/users/gwaldby/statuses/113187318090872531/replies\",\"items\":[]}}},\"signature\":{\"type\":\"RsaSignature2017\",\"creator\":\"https://mastodon.social/users/gwaldby#main-key\",\"created\":\"2024-09-23T14:23:31Z\",\"signatureValue\":\"niqGozMzferTAQSLIHwDAl/vIbPbIKFB/C7aXnxHxjS8wnFsMFyOoI+F2Jsy/ckn181fYVYCswYO2M2VYm6xAd0QS854CK96Loq6Mc1LnnXCDlLWGrLEe4Szx6PSRss1aISlGpEHH9yFXyGFpqphZL0Z+bwve9pSj+ahjKjRCRQ/fh0VPfnxZzmXjiFGMbO68TXZfq2WGOSZLKuT0tf5dCVaWechl8NkH8Nc6XF1vXt2jM7rrHqsSZFg7Kk9J9VujhfCOypHRD6O4+Lqvp7Bkl5OYbm31LTn3JkCCCFXyNtGFOizcFTAUhVl9T3Kzz07h734c8YRFr8qIGwk+K54/A==\"}}", nil, "Account"
```

The backtrace:
```
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/httplog-1.7.0/lib/httplog/http_log.rb:271:in `gsub'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/httplog-1.7.0/lib/httplog/http_log.rb:271:in `block in masked'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/httplog-1.7.0/lib/httplog/http_log.rb:269:in `each'
```

### Mastodon instance

raphus.social

### Mastodon version

v4.3.0-beta2

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
- Node.js version: v20.5.1

**Comment by ClearlyClaire** [comment]
Thank you for your report! Out of curiosity, can you share what `RAILS_LOG_LEVEL` you use, as well as the output of `Rails.application.config.filter_parameters` in a Rails console?

**Comment by ClearlyClaire** [comment]
Sorry, can you please also share `HttpLog.config.filter_parameters`?

**Comment by shleeable** [comment]
I'm experiencing the regex timeout... but I don't know if it's a concern or not
![image](https://github.com/user-attachments/assets/7212bc1d-b158-4870-a8d8-aa299ca26af5)

```
irb(main):001> HttpLog.config.filter_parameters
=> ["password"]

irb(main):002> Rails.application.config.filter_parameters
=> [:passw, :email, :secret, :token, :_key, :crypt, :salt, :certificate, :otp, :ssn, /^((?-mix:client_secret|authentication_token|access_token|refresh_token|code))$/, "user.otp_secret"]
```

**Comment by renchap** [comment]
How is the CPU on your Sidekiq servers when you experience this error?

**Comment by ClearlyClaire** [comment]
If my understanding is correct, the regexp for the original trace is exceedingly simple: `/(password)=[^&]+/i`. This being slow enough to trigger a timeout would be very surprising, unless it's not the regexp itself taking time.

I'm inclined to think something (e.g. memory thrashing) caused the server to be busy enough for the timeout being exceeded on a very simple regexp. If that's the case, it means the timeout caused more issues than it solved, though, and I wonder if we should increase it, or outright remove it.

**Comment by oneiros** [comment]
We increased the default timeout from 0.5 to 2s. Please let us know if it fixes the problem for you.

In case it does not, we now allow overriding this value via the `REGEXP_TIMEOUT` environment variable.

**Comment by renchap** [comment]
I am reopening this as the timeout can be consistently reproduced and is not related to the memory/cpu state of the process. There might be something else to look for here.

**Comment by rrgeorge** [comment]
I got another one to show up. this is the result of perform_inline:
```
I, [2024-09-28T00:50:52.519957 #3159364]  INFO -- : [paperclip] Trying to link /tmp/c5fe600a9d0230a24b0ca357b785123920240928-3159364-9anv8l.mp4 to /tmp/ad56799fdc5ff35176c925477d7a068620240928-3159364-u255d9.mp4
I, [2024-09-28T00:50:52.520196 #3159364]  INFO -- : Command :: file -b --mime '/tmp/ad56799fdc5ff35176c925477d7a068620240928-3159364-u255d9.mp4'
I, [2024-09-28T00:50:52.835375 #3159364]  INFO -- : Command :: ffmpeg -nostdin -i '/tmp/c5fe600a9d0230a24b0ca357b785123920240928-3159364-9anv8l.mp4' -loglevel 'fatal' -map_metadata '-1' -c:v 'copy' -c:a 'copy' -y '/tmp/c5fe600a9d0230a24b0ca357b785123920240928-3159364-9anv8l20240928-3159364-j57nsy.mp4'
I, [2024-09-28T00:50:53.275194 #3159364]  INFO -- : [paperclip] Trying to link /tmp/c5fe600a9d0230a24b0ca357b785123920240928-3159364-9anv8l20240928-3159364-j57nsy.mp4 to /tmp/28d871d2abb43c72c6aa0e4fe8e3fe6e20240928-3159364-en9kk2.mp4
I, [2024-09-28T00:50:53.470287 #3159364]  INFO -- : Command :: ffmpeg -nostdin -ss '0' -i '/tmp/28d871d2abb43c72c6aa0e4fe8e3fe6e20240928-3159364-en9kk2.mp4' -loglevel 'fatal' -vf 'scale='\''min(640\, iw):min(640\, ih)'\'':force_original_aspect_ratio=decrease' -f 'image2' -vframes '1' -y '/tmp/28d871d2abb43c72c6aa0e4fe8e3fe6e20240928-3159364-en9kk220240928-3159364-u824bk.png'
I, [2024-09-28T00:50:53.721314 #3159364]  INFO -- : [paperclip] Trying to link /tmp/28d871d2abb43c72c6aa0e4fe8e3fe6e20240928-3159364-en9kk220240928-3159364-u824bk.png to /tmp/6348ee5c8ad9e1408d99780d62d9853920240928-3159364-cy3rn0.png
I, [2024-09-28T00:50:53.722044 #3159364]  INFO -- : [paperclip] Trying to link /tmp/28d871d2abb43c72c6aa0e4fe8e3fe6e20240928-3159364-en9kk2.mp4 to /tmp/ad56799fdc5ff35176c925477d7a068620240928-3159364-46yjuh.mp4
I, [2024-09-28T00:50:53.722238 #3159364]  INFO -- : Command :: file -b --mime '/tmp/ad56799fdc5ff35176c925477d7a068620240928-3159364-46yjuh.mp4'
I, [2024-09-28T00:50:53.733042 #3159364]  INFO -- : [paperclip] saving cache/media_attachments/files/113/214/085/625/191/155/original/0b3ec74d27815803.mp4
lib/paperclip/attachment_extensions.rb:91:in `block in save': regexp match timeout (Regexp::TimeoutError)
        from lib/paperclip/attachment_extensions.rb:91:in `save'
        from app/lib/activitypub/activity/create.rb:281:in `block in process_attachments'
        from app/lib/activitypub/activity/create.rb:260:in `each'
        from app/lib/activitypub/activity/create.rb:260:in `process_attachments'
        from app/lib/activitypub/activity/create.rb:113:in `process_status_params'
        from app/lib/activitypub/activity/create.rb:81:in `process_status'
        from app/lib/activitypub/activity/create.rb:58:in `block in create_status'
        from app/models/concerns/lockable.rb:12:in `block (2 levels) in with_redis_lock'
        from app/models/concerns/lockable.rb:10:in `block in with_redis_lock'
        from app/lib/redis_connection.rb:10:in `with'
        from app/models/concerns/redisable.rb:9:in `with_redis'
        from app/models/concerns/lockable.rb:9:in `with_redis_lock'
        from app/lib/activitypub/activity/create.rb:52:in `create_status'
        from app/lib/activitypub/activity/create.rb:15:in `perform'
        from app/services/activitypub/process_collection_service.rb:68:in `process_item'
        from app/services/activitypub/process_collection_service.rb:59:in `block in process_items'
        ... 7 levels...
```
At first glance it looks like it's because it waits for the file to be written, which takes more than .5s...
The previous status i had with this issue also had a video attachment, so maybe the video's larger file size causes it?

**Comment by ClearlyClaire** [comment]
Can you retry with `BACKTRACE=1`?

**Comment by oneiros** [comment]
And can you share the status in question?

**Comment by rrgeorge** [comment]
> Can you retry with `BACKTRACE=1`?

I ran `BACKTRACE=1 rails c`, but i'm not sure it made much difference:
```
I, [2024-09-30T08:30:00.227372 #176144]  INFO -- : [paperclip] Trying to link /tmp/c5fe600a9d0230a24b0ca357b785123920240930-176144-gtwp4b.mp4 to /tmp/e5df9188141b061aa847a7ed7755be1e20240930-176144-l4s6xe.mp4
I, [2024-09-30T08:30:00.227720 #176144]  INFO -- : Command :: file -b --mime '/tmp/e5df9188141b061aa847a7ed7755be1e20240930-176144-l4s6xe.mp4'
I, [2024-09-30T08:30:00.547579 #176144]  INFO -- : Command :: ffmpeg -nostdin -i '/tmp/c5fe600a9d0230a24b0ca357b785123920240930-176144-gtwp4b.mp4' -loglevel 'fatal' -map_metadata '-1' -c:v 'copy' -c:a 'copy' -y '/tmp/c5fe600a9d0230a24b0ca357b785123920240930-176144-gtwp4b20240930-176144-1gf128.mp4'   
I, [2024-09-30T08:30:01.071341 #176144]  INFO -- : [paperclip] Trying to link /tmp/c5fe600a9d0230a24b0ca357b785123920240930-176144-gtwp4b20240930-176144-1gf128.mp4 to /tmp/c342eb3823335c6d942c3f40df3ab4c020240930-176144-2lykn0.mp4
I, [2024-09-30T08:30:01.287753 #176144]  INFO -- : Command :: ffmpeg -nostdin -ss '0' -i '/tmp/c342eb3823335c6d942c3f40df3ab4c020240930-176144-2lykn0.mp4' -loglevel 'fatal' -vf 'scale='\''min(640\, iw):min(640\, ih)'\'':force_original_aspect_ratio=decrease' -f 'image2' -vframes '1' -y '/tmp/c342eb3823335c6d942c3f40df3ab4c020240930-176144-2lykn020240930-176144-n1bb27.png'
I, [2024-09-30T08:30:01.533490 #176144]  INFO -- : [paperclip] Trying to link /tmp/c342eb3823335c6d942c3f40df3ab4c020240930-176144-2lykn020240930-176144-n1bb27.png to /tmp/bf0f54a70e98ba39c29ae1437605de3620240930-176144-lpdwwi.png
I, [2024-09-30T08:30:01.534281 #176144]  INFO -- : [paperclip] Trying to link /tmp/c342eb3823335c6d942c3f40df3ab4c020240930-176144-2lykn0.mp4 to /tmp/e5df9188141b061aa847a7ed7755be1e20240930-176144-nrc3i9.mp4
I, [2024-09-30T08:30:01.534482 #176144]  INFO -- : Command :: file -b --mime '/tmp/e5df9188141b061aa847a7ed7755be1e20240930-176144-nrc3i9.mp4'
I, [2024-09-30T08:30:01.545352 #176144]  INFO -- : [paperclip] saving cache/media_attachments/files/113/227/215/634/752/099/original/9f4dd4d8ce960b0d.mp4
httplog (1.7.0) lib/httplog/http_log.rb:271:in `gsub': regexp match timeout (Regexp::TimeoutError)
        from httplog (1.7.0) lib/httplog/http_log.rb:271:in `block in masked'
        from httplog (1.7.0) lib/httplog/http_log.rb:269:in `each'
        from httplog (1.7.0) lib/httplog/http_log.rb:269:in `reduce'
        from httplog (1.7.0) lib/httplog/http_log.rb:269:in `masked'
        from httplog (1.7.0) lib/httplog/http_log.rb:300:in `parse_request'
        from httplog (1.7.0) lib/httplog/http_log.rb:33:in `call'
        from httplog (1.7.0) lib/httplog/adapters/net_http.rb:26:in `request'
        from aws-sdk-core (3.205.0) lib/seahorse/client/net_http/connection_pool.rb:348:in `request'
        from aws-sdk-core (3.205.0) lib/seahorse/client/net_http/handler.rb:80:in `block in transmit'
        from aws-sdk-core (3.205.0) lib/seahorse/client/net_http/handler.rb:134:in `block in session'
        from aws-sdk-core (3.205.0) lib/seahorse/client/net_http/connection_pool.rb:106:in `session_for'
        from aws-sdk-core (3.205.0) lib/seahorse/client/net_http/handler.rb:129:in `session'
        from aws-sdk-core (3.205.0) lib/seahorse/client/net_http/handler.rb:77:in `transmit'
        from aws-sdk-core (3.205.0) lib/seahorse/client/net_http/handler.rb:46:in `block in call'
        from aws-sdk-core (3.205.0) lib/seahorse/client/net_http/handler.rb:206:in `block in span_wrapper'
        from aws-sdk-core (3.205.0) lib/aws-sdk-core/telemetry/no_op.rb:29:in `in_span'
        ... 148 levels...
irb(main):003>     
```

**Comment by rrgeorge** [comment]
> And can you share the status in question?

https://mastodon.social/@ChrisPirillo/113205387959559137

**Comment by ClearlyClaire** [comment]
> > Can you retry with `BACKTRACE=1`?
> 
> I ran `BACKTRACE=1 rails c`, but i'm not sure it made much difference:
> 
> ```
> I, [2024-09-30T08:30:00.227372 #176144]  INFO -- : [paperclip] Trying to link /tmp/c5fe600a9d0230a24b0ca357b785123920240930-176144-gtwp4b.mp4 to /tmp/e5df9188141b061aa847a7ed7755be1e20240930-176144-l4s6xe.mp4
> I, [2024-09-30T08:30:00.227720 #176144]  INFO -- : Command :: file -b --mime '/tmp/e5df9188141b061aa847a7ed7755be1e20240930-176144-l4s6xe.mp4'
> I, [2024-09-30T08:30:00.547579 #176144]  INFO -- : Command :: ffmpeg -nostdin -i '/tmp/c5fe600a9d0230a24b0ca357b785123920240930-176144-gtwp4b.mp4' -loglevel 'fatal' -map_metadata '-1' -c:v 'copy' -c:a 'copy' -y '/tmp/c5fe600a9d0230a24b0ca357b785123920240930-176144-gtwp4b20240930-176144-1gf128.mp4'   
> I, [2024-09-30T08:30:01.071341 #176144]  INFO -- : [paperclip] Trying to link /tmp/c5fe600a9d0230a24b0ca357b785123920240930-176144-gtwp4b20240930-176144-1gf128.mp4 to /tmp/c342eb3823335c6d942c3f40df3ab4c020240930-176144-2lykn0.mp4
> I, [2024-09-30T08:30:01.287753 #176144]  INFO -- : Command :: ffmpeg -nostdin -ss '0' -i '/tmp/c342eb3823335c6d942c3f40df3ab4c020240930-176144-2lykn0.mp4' -loglevel 'fatal' -vf 'scale='\''min(640\, iw):min(640\, ih)'\'':force_original_aspect_ratio=decrease' -f 'image2' -vframes '1' -y '/tmp/c342eb3823335c6d942c3f40df3ab4c020240930-176144-2lykn020240930-176144-n1bb27.png'
> I, [2024-09-30T08:30:01.533490 #176144]  INFO -- : [paperclip] Trying to link /tmp/c342eb3823335c6d942c3f40df3ab4c020240930-176144-2lykn020240930-176144-n1bb27.png to /tmp/bf0f54a70e98ba39c29ae1437605de3620240930-176144-lpdwwi.png
> I, [2024-09-30T08:30:01.534281 #176144]  INFO -- : [paperclip] Trying to link /tmp/c342eb3823335c6d942c3f40df3ab4c020240930-176144-2lykn0.mp4 to /tmp/e5df9188141b061aa847a7ed7755be1e20240930-176144-nrc3i9.mp4
> I, [2024-09-30T08:30:01.534482 #176144]  INFO -- : Command :: file -b --mime '/tmp/e5df9188141b061aa847a7ed7755be1e20240930-176144-nrc3i9.mp4'
> I, [2024-09-30T08:30:01.545352 #176144]  INFO -- : [paperclip] saving cache/media_attachments/files/113/227/215/634/752/099/original/9f4dd4d8ce960b0d.mp4
> httplog (1.7.0) lib/httplog/http_log.rb:271:in `gsub': regexp match timeout (Regexp::TimeoutError)
>         from httplog (1.7.0) lib/httplog/http_log.rb:271:in `block in masked'
>         from httplog (1.7.0) lib/httplog/http_log.rb:269:in `each'
>         from httplog (1.7.0) lib/httplog/http_log.rb:269:in `reduce'
>         from httplog (1.7.0) lib/httplog/http_log.rb:269:in `masked'
>         from httplog (1.7.0) lib/httplog/http_log.rb:300:in `parse_request'
>         from httplog (1.7.0) lib/httplog/http_log.rb:33:in `call'
>         from httplog (1.7.0) lib/httplog/adapters/net_http.rb:26:in `request'
>         from aws-sdk-core (3.205.0) lib/seahorse/client/net_http/connection_pool.rb:348:in `request'
>         from aws-sdk-core (3.205.0) lib/seahorse/client/net_http/handler.rb:80:in `block in transmit'
>         from aws-sdk-core (3.205.0) lib/seahorse/client/net_http/handler.rb:134:in `block in session'
>         from aws-sdk-core (3.205.0) lib/seahorse/client/net_http/connection_pool.rb:106:in `session_for'
>         from aws-sdk-core (3.205.0) lib/seahorse/client/net_http/handler.rb:129:in `session'
>         from aws-sdk-core (3.205.0) lib/seahorse/client/net_http/handler.rb:77:in `transmit'
>         from aws-sdk-core (3.205.0) lib/seahorse/client/net_http/handler.rb:46:in `block in call'
>         from aws-sdk-core (3.205.0) lib/seahorse/client/net_http/handler.rb:206:in `block in span_wrapper'
>         from aws-sdk-core (3.205.0) lib/aws-sdk-core/telemetry/no_op.rb:29:in `in_span'
>         ... 148 levels...
> irb(main):003>     
> ```

It does make a difference. This is still the same regexp failing, the one in HttpLog that, to my understanding, should be `/(password)=[^&]+/i`… so a very simple one… i don't get it

**Comment by ClearlyClaire** [comment]
Closing as we removed the Regexp timeouts.
