### ISSUE TITLE
Muted users interface not usable in advanced view

### ISSUE THREAD

**Issue by LonMcGregor** [mastodon/mastodon#32060]
### Steps to reproduce the problem

1. mute some users on your instance.com
2. Visit instance.com/deck/mutes

### Expected behaviour

Either open the mutes view as its own page, like muted words does, or display it neatly in an advanced view column

### Actual behaviour

It loads a column and only the unmute buttons are visible, no profile names, which makes it difficult to use

### Detailed description

Advanced view has a series of narrow columns and the muted users management page requires a wider column than is available.
This results in the buttons in the div with class .account__relationship overlaying the user info, so you have no idea what account the buttons will act on.

### Mastodon instance

https://social.vivaldi.net

### Mastodon version

v4.2.12

### Browser name and version

Vivaldi 6.10.3474.15 / Chrome 128.0.6613.164

### Operating system

Windows 10 22H2 x64

### Technical details

Bugged view:
![image](https://github.com/user-attachments/assets/9a98546b-dd11-4cfb-a630-9e7da00e1ee3)

With this additional style:
```
.layout-multiple-columns .account__wrapper {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
}
```
isn't perfect, but it does demonstrate the info that is missing:
![image](https://github.com/user-attachments/assets/a5accaf7-251d-4860-a3f7-ba05bfef2993)

**Comment by ClearlyClaire** [comment]
This is addressed in the upcoming 4.3.0 by the use of a `…` dropdown menu.
