### ISSUE TITLE
Duplicate indexes on my server. expected? mistake? missing migration?

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#32061]
### Steps to reproduce the problem

![image](https://github.com/user-attachments/assets/fdea7c0f-435d-45cb-a5a8-3d6912858902)

### Expected behaviour

No Duplicate indexes 

### Actual behaviour

Duplicate indexes 

### Mastodon instance

aus.social

### Mastodon version

4.3.0-beta.2

### Technical details

Ruby	3.3.5p100
PostgreSQL	16.4
Redis	7.4.0
Elasticsearch	8.14.1
libvips	8.15.3
FFmpeg	7.0.2

**Comment by ClearlyClaire** [comment]
These appear to be legitimately duplicated indexes. This could use some cleanup.

**Comment by Kerion-Nightfall** [comment]
Same here with docker on the latest image (v4.3)

**Comment by 101010pl** [comment]
Same on my server.

**Comment by ClearlyClaire** [comment]
“Same here” replies are not useful, the issue is already confirmed. This is a known but very minor performance issue with Mastodon's codebase. You can ignore it, and we will fix it eventually.

**Comment by shleeable** [comment]
Thanks team
