### ISSUE TITLE
Missing 'allow-popups' directive from sandbox attribute in embed.js causes browsers to prevent users directly opening links within the embed iframe

### ISSUE THREAD

**Issue by wolfgang101** [mastodon/mastodon#32133]
### Steps to reproduce the problem

1. Click "Get embed code" on any Mastodon post
2. Publish the generated embed code on any website
3. Go to the website and click on any link within the embed iframe
4. Links do not open and browser shows console message `Blocked opening '[...]' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.`

### Expected behaviour

User should be able to click on links within IFrame and they should open the corresponding Mastodon post, user profile, etc.

### Actual behaviour

Browser blocks opening of links

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0-nightly.2024-09-26

### Browser name and version

Google Chrome Version 129.0.6668.70 (Official Build) (64-bit)

### Operating system

Ubuntu 24.04.01

**Comment by Gargron** [comment]
I didn't realize target=_blank on links required this permission. Not sure how I didn't catch this sooner!
