### ISSUE TITLE
Duplicate Indexes / These indexes exist, but aren’t needed. Remove them for faster writes. 

### ISSUE THREAD

**Issue by bakunin1848** [mastodon/mastodon#32161]
### Steps to reproduce the problem

1. Upgrade from 4.2.12 to 4.3.0-beta.2 following all Steps.
2. Check pghero
3. Duplicate indexes appear
...

### Expected behaviour

Not duplicated Index

### Actual behaviour

4 Duplicates Indexes

### Detailed description

<html><body>
<h1>Duplicate Indexes</h1>

    <p>
      These indexes exist, but aren’t needed. Remove them
      for faster writes.
    </p>

    

    
Details
--
On account_aliases               index_account_aliases_on_account_id (account_id)               is covered by               index_account_aliases_on_account_id_and_uri (account_id, uri)
On account_relationship_severance_events               index_account_relationship_severance_events_on_account_id (account_id)               is covered by               idx_on_account_id_relationship_severance_event_id_7bd82bf20e (account_id, relationship_severance_event_id)
On custom_filter_statuses               index_custom_filter_statuses_on_status_id (status_id)               is covered by               index_custom_filter_statuses_on_status_id_and_custom_filter_id (status_id, custom_filter_id)
On webauthn_credentials               index_webauthn_credentials_on_user_id (user_id)               is covered by               index_webauthn_credentials_on_user_id_and_nickname (user_id, nickname)

</body>
</html>
![db](https://github.com/user-attachments/assets/44dbec0d-af37-4e27-b24b-a6d6d3a59b84)

### Mastodon instance

social.skynetcloud.site

### Mastodon version

v4.3.0-beta.2

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: 3.2.0
- Node.js version: 20.5.1

**Comment by bakunin1848** [comment]
![db](https://github.com/user-attachments/assets/d903fa6e-1d56-41af-a24d-e37393eea2a9)

**Comment by Gargron** [comment]
At different database sizes or with different usage patterns sometimes not all indexes are used by the query planner. If you remove them you will diverge from mastodon’s expected database schema which might create conflicts when upgrading. You might also run into issues once the index becomes necessary due to increased size or different usage pattern.

**Comment by bakunin1848** [comment]
I had not seen more issues like this but now I have seen one that I think is identical, if that is the case it can be closed as a duplicate.

Sorry!

https://github.com/mastodon/mastodon/issues/32061
