### ISSUE TITLE
Add a section to view followed hashtags

### ISSUE THREAD

**Issue by MilesONerd** [mastodon/mastodon#32162]
### Pitch

I would like to propose a feature that allows users to view the hashtags they are following. This section would provide a clear and accessible list of followed hashtags, helping users to better manage their interests on the platform.

### Motivation

This feature is needed because it enhances user experience by allowing easy access to followed hashtags. Users often forget which hashtags they follow, and having a visible list would help them organize their feeds better. Additionally, this functionality would facilitate hashtag management, enabling users to unfollow hashtags they are no longer interested in. Overall, this would benefit all users by creating a more personalized and enjoyable environment on Mastodon.

**Comment by ClearlyClaire** [comment]
Hi! This is already available at `/followed_tags`, accessible from the UI by clicking the “…” menu besides your name above the posting box, and selecting “Followed hashtags”
