### ISSUE TITLE
New Restrictive Form Action CSP breaks OMNIAUTH_ONLY

### ISSUE THREAD

**Issue by Sanguinaris** [mastodon/mastodon#32186]
### Steps to reproduce the problem

1. Setup a server with OMNIAUTH_ONLY configured
2. Try clicking the login button on the main webpage

### Expected behaviour

can get redirected to provider

### Actual behaviour

get csp error in console

### Detailed description

i suspect that https://github.com/mastodon/mastodon/pull/26897 broke omniauth_only.
the login button on the main page would redirect to https://INSTANCE/auth/auth/openid_connect which then takes you to the oidc provider. this is blocked by the new form-action policy. turning off omniauth_only makes it work as does logging in via /auth/sign_in.
I was able to fix this by hardcoding p.form_action in the web app controller concern to be https://INSTANCE/auth/auth/openid_connect . i've reverted the change for now to showcase current behaviour.

### Mastodon instance

m.fa.gl

### Mastodon version

v4.3.0-beta.2

### Browser name and version

Firefox 130, Edge 129

### Operating system

Windows 11

### Technical details

CSP error in console:
>  Refused to send form data to 'https://m.fa.gl/auth/auth/openid_connect' because it violates the following Content Security Policy directive: "form-action https://auth.home.fa.gl/api/oidc/authorization".

**Comment by ClearlyClaire** [comment]
Thanks for the report. I somehow missed that case.

Not a proper fix of course since it's hardcoded to your domain name, but does the following patch help?
```patch
diff --git a/app/controllers/concerns/web_app_controller_concern.rb b/app/controllers/concerns/web_app_controller_concern.rb
index ebbdba59af..269586a4d9 100644
--- a/app/controllers/concerns/web_app_controller_concern.rb
+++ b/app/controllers/concerns/web_app_controller_concern.rb
@@ -13,7 +13,7 @@ module WebAppControllerConcern
       policy = ContentSecurityPolicy.new
 
       if policy.sso_host.present?
-        p.form_action policy.sso_host
+        p.form_action "https://m.fa.gl/auth/auth/#{Devise.omniauth_providers[0]}", policy.sso_host
       else
         p.form_action :none
       end
```

**Comment by Sanguinaris** [comment]
yip that seems to work! applied it and login button on homepage now redirects to auth provider.

**Comment by ClearlyClaire** [comment]
Can you try with this?
```patch
diff --git a/app/controllers/concerns/web_app_controller_concern.rb b/app/controllers/concerns/web_app_controller_concern.rb
index ebbdba59af..e7a8c9d1f9 100644
--- a/app/controllers/concerns/web_app_controller_concern.rb
+++ b/app/controllers/concerns/web_app_controller_concern.rb
@@ -13,7 +13,7 @@ module WebAppControllerConcern
       policy = ContentSecurityPolicy.new
 
       if policy.sso_host.present?
-        p.form_action policy.sso_host
+        p.form_action policy.sso_host, ->() { "https://#{request.host}/auth/auth/#{Devise.omniauth_providers[0]}" }
       else
         p.form_action :none
       end
```

**Comment by Sanguinaris** [comment]
that seems to work as well but unsure if allowing a user set value would be good there?

**Comment by ClearlyClaire** [comment]
It is user-set but Rails should reject any value that is not in `LOCAL_DOMAIN`, `WEB_DOMAIN` or `ALTERNATE_DOMAINS`
