### ISSUE TITLE
Update the Notifications feed to see the body of posts that others have boosted or favorited

### ISSUE THREAD

**Issue by tinker123456** [mastodon/mastodon#32196]
### Pitch

The new formatting for notifications is very positive in that you don't see your post for every single boost or favorite you get.  It was too much.

However, now you don't see your posts in your Notifications feed at all.   You have to open the notification to see what someone liked or boosted ( I use Mastodon in a browser on a desktop PC ).   Like it or not, part of the draw of social media, even Mastodon, is getting feedback on what you wrote.

How about keeping the way things are condensed, but show a copy ( only 1 ) of the post that was favorited or boosted?

Example.  I post "It will rain tomorrow".  Five people favorite and boost it.  In my Notifications feed I see my full "It will rain tomorrow" post, with the 5 users names across the top of the people who favorited or boosted it.

Similar to now, but I don't have to open the notification to see the post, but I get to keep the compacted goodness of the new style.

### Motivation

Clearer, easy to see feedback on what you posted, making Mastodon more fun.

**Comment by renchap** [comment]
I am not sure I understand your report, the post is displayed in the notifications feed

<img width="593" alt="image" src="https://github.com/user-attachments/assets/dfdcd8ad-93fe-4ae9-b1f8-c9c16757adce">

**Comment by renchap** [comment]
Thanks, it helps understanding the issue. We probably should have a better way of selecting what to display in the notification.
