### ISSUE TITLE
[Advanced mode] Edited post UI with image, displays atop pre-existing search listing

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#32213]
### Steps to reproduce the problem

I saw this today on v4.3.0-nightly.2024-10-01 on firefox 130.0.1 snap version on Ubuntu 24.04. Reproduces across many refreshes. I think this is a regression, I feel like I've done this series of steps before but not seen the problem.

Below is a video (due to some sort of bug on my computer, the mouse cursor appears fixed in this video, although it is in fact moving).

Steps in video:
- Start from a new mastodon.social window.
- Do a search (in this search from:mcc, so I get my own posts)
- Select a post with an image. It will appear in the rightmost column.
- Click ⋯ on the post in the rightmost column and choose "Edit".
- The image from the edited post ONLY appears floating atop the search column. 

[Screencast from 2024-10-01 17-36-31.webm](https://github.com/user-attachments/assets/8f5eb1b4-ad24-46b7-b002-54939cbce228)

### Expected behaviour

Choosing "edit" should dismiss the search column. If choosing edit does not dismiss the search column, the edit pane appearing "behind" the search column and not reappearing until the search column is closed would also be entirely acceptable.

### Actual behaviour

Edit UI appears both behind and in front of the search column.

### Detailed description

In this video, uBlock Origin is ON and Stylus is OFF.

### Mastodon instance

-

### Mastodon version

-

### Browser name and version

-

### Operating system

-

### Technical details

-

**Comment by ClearlyClaire** [comment]
This is caused by the `z-index` changes in #31967, specifically the `z-index: 1` on `.media-gallery__item`.

Setting `z-index: 0` to `.drawer__inner` seems to fix this issue, though I'm not completely sure what is the best approach here.
