### ISSUE TITLE
Muted users not visible / hidden by buttons

### ISSUE THREAD

**Issue by bocops** [mastodon/mastodon#32226]
### Steps to reproduce the problem

1. Set interface language to German.
2. Click menu item "Stummgeschaltete Profile" to view list of muted users.
3. Find list of buttons without any identifiable portion of the individual profiles

### Expected behaviour

List should contain profile image and name

### Actual behaviour

Content is hidden by buttons with too long text

### Detailed description

See image:

![image](https://github.com/user-attachments/assets/b01f39eb-edf4-4a95-90a7-feb29bac7f0c)

### Mastodon instance

Checked on multiple instances

### Mastodon version

v4.2.12

### Browser name and version

Chrome 129

### Operating system

Windows 10

**Comment by renchap** [comment]
This has been fixed in Mastodon 4.3, which will be released next week.

It now looks like that (on the smallest screen size possible):

<img width="578" alt="image" src="https://github.com/user-attachments/assets/acba9206-69f0-4d60-9e5d-c89c4176c5cc">
