### ISSUE TITLE
RaceConditionError / Could not acquire lock for fetch

### ISSUE THREAD

**Issue by seano-vs** [mastodon/mastodon#32229]
### Steps to reproduce the problem

I realized that the link previews on masto.nyc were not loading (er, loading much much slower than normal), so I checked out the Sidekiq interface and saw more (~350) `LinkCrawlWorker` jobs than I was used to seeing. In the dead queue, I saw this race condition error:

`Could not acquire lock for fetch:https://www.cdt.org/insights/report-hated-more-online-violence-targeting-women-of-color-candidates-in-the-2024-us-election/, try again later`

![image](https://github.com/user-attachments/assets/2e10a237-cbf6-4d2e-b6f4-288e54a5bf76)

I'm not a ruby expert but I have read about fine tuning Sidekiq so the concurrency level doesn't have processes fighting over the GIL, is that what's happening here ([my pull queue is currently set to 25](https://github.com/Five-Borough-Fedi-Project/masto.nyc-docean/blob/main/kubernetes/mastodon/deployment-sidekiq-pull.yaml#L47))? I recently broke out each Sidekiq queue to its own process, and also wondering if that may have affected anything.

### Expected behaviour

Link previews load

### Actual behaviour

they ain't

### Mastodon instance

masto.nyc

### Mastodon version

v4.3.0-rc1

### Technical details

If this is happening on your own Mastodon server, please fill out those:
-  official Docker image

**Comment by ClearlyClaire** [comment]
This error occurs when multiple jobs try to build the same preview card at the same time and the job holding the lock is too slow to release it. This is generally safe to ignore as this is just a mechanism to avoid duplicate work.

By far the most likely explanation for such a job to be too slow to release the lock is the servers it fetches data from being too slow to respond. That might be what happened here.

**Comment by seano-vs** [comment]
Understood. Thanks for the context, Claire!
