### ISSUE TITLE
Add button "enable notification of everyone I follow", as there is currently no other way than manually clicking bell-icon on EVERYONE we follow

### ISSUE THREAD

**Issue by D4n2021** [mastodon/mastodon#32235]
### Pitch

See title.

### Motivation

For all us users using the Mastodon Smartphone app and want to receive "new post published"-notifications of EVERYONE that we follow, and it's a huuuuuuuge amount of work to open EVERY profile and click the bell individually.

**Comment by renchap** [comment]
Closing this as we will not add this feature. This is not what Mastodon is designed for, and will cause a lot of performance issues.

**Comment by trwnh** [comment]
> You _do_ realize that Twitter _does_ have such "enable notifications for everyone I follow" option, right?

Wait, what? Really? Where????
