### ISSUE TITLE
uses a disallowed e-mail provider error on mastodon.social instance

### ISSUE THREAD

**Issue by murolem** [mastodon/mastodon#32245]
### Steps to reproduce the problem

1. Try to sign up with @mail.ru email address
2. Get the error.

### Expected behaviour

no error

### Actual behaviour

error

### Mastodon instance

mastodon.social

### Mastodon version

no info on sign up page

### Browser name and version

jelly 13

### Operating system

android 13

**Comment by ClearlyClaire** [comment]
This is a moderation decision from this server.

**Comment by murolem** [comment]
Based on what? This is one of the biggest email providers here.

@ClearlyClaire
