### ISSUE TITLE
GNOME Web is reported as "Safari on Linux"

### ISSUE THREAD

**Issue by luciofstars** [mastodon/mastodon#32274]
### Steps to reproduce the problem

1. Use GNOME Web to log into tech.lgbt (and possibly other instances)
2. Check your active sessions
3. GNOME Web is reported as "Safari on Linux"

### Expected behaviour

GNOME Web should be reported properly as GNOME Web or Epiphany

### Actual behaviour

GNOME Web was reported as "Safari on Linux" in the session list.

### Detailed description

I recently (yesterday) applied for an account on tech.lgbt. While I clicked ADHD-ly around the interface waiting for my account to be approved, I noticed that my current session (GNOME Web on the Vanilla OS 2 Orchid Live ISO, long story: I tried to install Ubuntu to try out TPM-backed FDE and got a corrupted ISO, which then naturally had a Broken (TM) installer, which ended up wiping my SSD and then royally breaking -- Vanilla OS was the only USB I had lying around...) was reported as "Safari on Linux":

![image](https://github.com/user-attachments/assets/de01611c-78ce-484e-bbae-c8b0f8152a08)

### Mastodon instance

tech.lgbt

### Mastodon version

v4.3.0-alpha.5+glitch (reported downstream to glitch-soc and was told to report here!)

### Browser name and version

GNOME Web 46.3

### Operating system

Vanilla OS 2 Live ISO (also tested on Fedora Workstation 40)

**Comment by mjankowski** [comment]
There's probably nothing we can do about this at the mastodon app level, because the detection comes from an underlying browser user agent parsing library.

That said - what is the exact full UA string being sent that's detected as Safari? We might be able to open bug and/or patch in that lib if they are open to it.

**Comment by mjankowski** [comment]
https://github.com/fnando/browser/pull/552

**Comment by vmstan** [comment]
Resolved by #33182

**Comment by luciofstars** [comment]
Sorry for being unhelpful here @mjankowski! I don't check GitHub very often and I assumed this was dead in the water after @alice-mkh said something about it over on the glitch-soc tracker. Super happy to see this is fixed, though.
