### ISSUE TITLE
All Push Notifications in English 

### ISSUE THREAD

**Issue by jotaluissoy** [mastodon/mastodon#32294]
### Steps to reproduce the problem

1. Using Mastodon Social instance.
2. Device and Instance both set in Spanish 
3. The official app has been sending all push notifications in English and not Spanish as usual (since five days).
...

### Expected behaviour

All push notifications (phone notifications) should be in Spanish as usual 

### Actual behaviour

All push notifications (phone notifications) are being all received in English since five days.

### Detailed description

About five days ago push notifications (phone notifications) (using Mastodon official app) are all being received in English. If instance and device are both set in Spanish, and if it has never been any issue, that means that something weird should be happening on someone's side.

It's good to say that this is an issue with mastodon.social . It's not that way to other instances.

### Mastodon instance

mastodon.social

### Mastodon version

The latest version 

### Browser name and version

Chrome for Android last Playstore versión.

### Operating system

Android 11

### Technical details

It's been happening using Mastodon Official app for Android.
Have no log.

**Comment by jotaluissoy** [comment]
Yes. I have the most recent original Mastodon app for Android v. 2.7.2 (121) downloaded from GitHub.

Good to add that it is happening with mastodon.social , not with other instances.

**Comment by jotaluissoy** [comment]
Hi, ClearlyClaire. I read that this has been closed as completed, however this issue still remains to me.
Will that take its own time to me see it working as expected? Thanks.

**Comment by renchap** [comment]
We will need to deploy the new version of the change on mastodon.social. We plan to do this on monday.

**Comment by jotaluissoy** [comment]
That's ok.
Thanks for replying.
