### ISSUE TITLE
mastodon-web broken after upgrade to 4.3

### ISSUE THREAD

**Issue by coro1404** [mastodon/mastodon#32331]
### Steps to reproduce the problem

Upgrade docker config as per upgrade instructions and perform upgrade

### Expected behaviour

working mastodon-web

### Actual behaviour

mastodon-web gives error about inert.css

### Detailed description

System is working just mastodon-web is throwing an error: 

`mastodon-web        | E, [2024-10-08T20:20:11.731082 #20] ERROR -- : [628978dc-55f2-4ddc-9c56-ceaf88d06899]   
mastodon-web        | [628978dc-55f2-4ddc-9c56-ceaf88d06899] ActionView::Template::Error (Webpacker can't find inert.css in /opt/mastodon/public/packs/manifest.json. Possible causes:
mastodon-web        | 1. You want to set webpacker.yml value of compile to true for your environment
mastodon-web        |    unless you are using the `webpack -w` or the webpack-dev-server.
mastodon-web        | 2. webpack has not yet re-run to reflect updates.
mastodon-web        | 3. You have misconfigured Webpacker's config/webpacker.yml file.
mastodon-web        | 4. Your webpack configuration is not creating a manifest.
mastodon-web        | Your manifest contains:
mastodon-web        | {`

I am prettty sure I had the same error after the last major upgrade and it could be resolved by running 

`RAILS_ENV=production bundle exec rails assets:clobber
RAILS_ENV=production bundle exec rails assets:precompile`

but the docker images don't contain node / nodejs 

Any advice would be greatly appreciated - my guess is that because I'm using a custom theme the assets would need precompilation 

any Ideas? 

### Mastodon instance

social.kendoo.eu

### Mastodon version

v4.3

### Browser name and version

Chrome:latest

### Operating system

Chromebook

**Comment by renchap** [comment]
Did you made any changes to the files inside the container? This can not happen if you did not change anything.

If you want to make changes to the container, you will need to build your own, starting from the source code and using our provider Dockerfile, then use this image.

**Comment by coro1404** [comment]
changes were only made through the Admin interface (like adding a custom stylesheet) - just retried the 4.2.13  docker image and it can invoke clobber and precompile. But to my understanding nothing should have been changed within the image.

**Comment by renchap** [comment]
If you use our provider container images, then assets are already pre-built and you should not have to run `assets:precompile`. Can you please provide more details about your setup?

**Comment by coro1404** [comment]
Hi renchap - thank you for caring and your efforts! 

I have a docker-compose setup and I am not aware of changing things inside the images (but, as I said, the last major update had a similar problem which was fixed by running clobber & precomile inside the images). My compose file looks like this (shortened for readability): 

`cat /tmp/compose.yml 
version: "3.7"

services:

  mastodon-db:
  [...]

  mastodon-redis:
  [...]

  mastodon-elastic:
  [...]

  mastodon-web:
    restart: always
    image: "ghcr.io/mastodon/mastodon:${MASTODON_VERSION}"
    container_name: "mastodon-web"
    healthcheck:
      test: ['CMD-SHELL',"curl -s --noproxy localhost localhost:3000/health | grep -q 'OK' || exit 1"] 
    env_file: mastodon.env.production
    environment:
      LOCAL_DOMAIN: "${MASTODON_DOMAIN}"
      SMTP_FROM_ADDRESS: "notifications@${MASTODON_DOMAIN}"
      ES_HOST: mastodon-elastic
      ES_ENABLED: "true"
    command: bundle exec puma -C config/puma.rb 
    expose:
      - "3000"
    depends_on:
      - mastodon-db
      - mastodon-redis
      - mastodon-elastic
    volumes:
      - ./mastodon/public/system:/opt/mastodon/public/system
    networks:
      - caddy
      - frontend
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mastodon-streaming:
    restart: always
    image: "ghcr.io/mastodon/mastodon-streaming:${MASTODON_VERSION}"
    container_name: "mastodon-streaming"
    healthcheck:
      test: ['CMD-SHELL', "curl -s --noproxy localhost localhost:4000/api/v1/streaming/health | grep -q 'OK' || exit 1"]
    env_file: mastodon.env.production
    environment:
      LOCAL_DOMAIN: "${MASTODON_DOMAIN}"
      SMTP_FROM_ADDRESS: "notifications@${MASTODON_DOMAIN}"
      ES_HOST: mastodon-elastic
      ES_ENABLED: "true"
    command: node ./streaming/index.js
    expose:
      - "4000"
    depends_on:
      - mastodon-db
      - mastodon-redis
    networks:
      - frontend
      - backend

  mastodon-sidekiq:
    restart: always
    image: "ghcr.io/mastodon/mastodon:${MASTODON_VERSION}"
    container_name: "mastodon-sidekiq"
    healthcheck:
      test: ps aux | grep '[s]idekiq\ 6' || false
    env_file: mastodon.env.production
    environment:
      LOCAL_DOMAIN: "${MASTODON_DOMAIN}"
      SMTP_FROM_ADDRESS: "notifications@${MASTODON_DOMAIN}"
      ES_HOST: mastodon-elastic
      ES_ENABLED: "true"
    command: bundle exec sidekiq
    depends_on:
      - mastodon-db
      - mastodon-redis
    volumes:
      - ./mastodon/public/system:/mastodon/public/system
    networks:
      - frontend
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mastodon-public:

networks:
  frontend:
  [...]
  backend:
  [...]`

as node is no longer included in the images I cannot check wether that would fix the issue again. Is there a way to make sure the images are running unchanged? 

regards

**Comment by coro1404** [comment]
Hi renchap, 

found the error - and this bug can be closed. The fault was that from some previous deployment with caddy in the same docker-compose there was a docker volume for sharing data with caddy - as I removed caddy in favor of an external proxying solution the volume remained in the config. This is why it didn't contain the precompiled assets. 

Thanks for your feedback (which brought me in the right directiion) and regards,

**Comment by schnuffle** [comment]
Hi folks,
I've the exact same error as the one mentioned in this issue.
The difference is that I've a setup where I've Traefik doing TLS termination and then nginx as proxy.

Should I create a new issue or post more information into this issue?

I followed the update instructions for Docker at https://github.com/mastodon/mastodon/releases/tag/v4.3.0, did the image split changes to my docker-compose.yml. 
When I start my stack it seems to run fine, when I call the website in a browser I get the mentkioned error.

As already mentioned as node is missing I can'T check if rebuilding the assets would resolve the problem

Regards

Schnuffle

**Comment by coro1404** [comment]
Hi Schnuffle, 

is traefik in the same docker compose and are there any volume mounts to share data between nginx and mastodon? In my case one volume mount was mounted to the same mountpoint as the content of the mastodon docker image therefore there were the wrong assets in the image - maybe you can share your docker-compose so we can have a look. 

regards

**Comment by schnuffle** [comment]
Hi coro,

- nginx is part of the compose stack
- traefik is separate from the stack as it proxies other services as well

Regards

Schnuffle

**Comment by coro1404** [comment]
Hi Schnuffle 

glad this works out for you - but keep in mind, the assets in the image are correct and precompiled - meaning if they need compiling your container is seeing older or different assets (probably from a shared volume with nginx). 
Just make sure your volume for mastodon web is not mounted over by another volume (this was my problem see code excerpt):

>   mastodon-web:
>   [...] 
>   volumes:
>       # https://www.digitalocean.com/community/tutorials/how-to-share-data-between-docker-containers
>       #- mastodon-public:/opt/mastodon/public # map static files in volume for caddy <= WRONG!  because it superseeds the next line
>       - ./mastodon/public/system:/opt/mastodon/public/system

**Comment by rriemann** [comment]
I guess the now broken approach to share static content with caddy comes from my blog at https://blog.riemann.cc/digitalisation/2022/02/09/mastodon-setup-with-docker-and-caddy/ 

I do not understand how now caddy (or nginx) would access files in /opt/mastodon/public inside the web container. Can you explain please?

**Comment by renchap** [comment]
> I do not understand how now caddy (or nginx) would access files in /opt/mastodon/public inside the web container. Can you explain please?

It should not directly serve those, but request them from the web container using HTTP, and cache them

**Comment by rriemann** [comment]
Dear @renchap ,

After some exchange in the  #mastodon_admin:matrix.org , I understood this. My problem is that I cannot see the precompiled assets/500.html in the container that I loaded from ghcr.io/mastodon/mastodon:v4.3.1. If I would see this, I would just extract the files with `podman cp mastodon_web_1:/mastodon/public/assets public/assets` to serve them easily from the host. (I know I need to copy after every update.)

**Comment by renchap** [comment]
There is a `public/500.html` file in the container. It never was in `assets/`, and this has not changed.
