### ISSUE TITLE
"We're sorry, but something went wrong on our end." when accessing https://<myserver>/settings/verification

### ISSUE THREAD

**Issue by dmachaj** [mastodon/mastodon#32338]
### Steps to reproduce the problem

I just finished upgrading from 4.2.13 to 4.3.0 using the listed instructions.  My server is a single-user instance that I self-host and it uses Docker.  I generated the new DB secrets and added them to my .env.production.  I ran the before-upgrade db command.  I downloaded and used the newest version of docker-compose.yml.  I then launched the new docker compose file and ran the post-upgrade db command.  Nothing along the way reported any errors.

After the upgrade my home feed loads fine and mostly things seem to be working.  However, the preferences pages are throwing errors.  I cannot access the /settings/verification page at all.  It simply fails.  I can access /settings/privacy but when I change something and click save I get the same failure.

### Expected behaviour

I should be able to access the new verification page as well as save preference changes

### Actual behaviour

"We're sorry, but something went wrong on our end."

### Mastodon instance

https://fedi.machaj.info/

### Mastodon version

v4.3.0

### Browser name and version

Microsoft Edge 129.0.2792.79 (Official build) (64-bit)

### Operating system

Windows 11 23H2 22631.4317

### Technical details

F12 dev tools have one single error in the console:
`GET https://fedi.machaj.info/settings/verification 500 (Internal Server Error)`

**Comment by dmachaj** [comment]
I forgot a few details in the original filing. 

The server is running Ubuntu 22.04 LTS and is fully up to date according to apt. 

An nginx reverse proxy is in front and Lets Encrypt provides the certificates for HTTPS.

**Comment by renchap** [comment]
The error will be in your puma/`mastodon-web` logs. Can you check those to see what the exact error is?

**Comment by zoc** [comment]
I actually had the same issue. Fixed by pulling down ALL the containers and then up again. 

Updating docker compose and doing only pull then up seems to not restart everything properly.

**Comment by sebastian-meyer** [comment]
I had the same issue and can confirm that just restarting the docker containers fixes this. I didn't even pull them again, just restarted: `docker compose down && docker compose up -d`

**Comment by dmachaj** [comment]
Pulling and restarting seems to have fixed it for me.

Annoyingly it seems like there was some sort of nginx change that struck in the interim where my .conf file was no longer accepted and I had to edit it a few times to get it to load without that container immediately exiting.  Once I got nginx fixed back up it seems to be working and I can access these pages without Mastodon throwing any errors.
