### ISSUE TITLE
Hide completely checkbox in filters doesn't hide completely in notifications

### ISSUE THREAD

**Issue by phocks** [mastodon/mastodon#32340]
### Steps to reproduce the problem

1. Make a filter, check hide completely.
2. Check your Notifications

![Screenshot 2024-10-09 160133](https://github.com/user-attachments/assets/b349ceed-09cc-4946-adc8-666db41b98c3)

### Expected behaviour

They should be hidden completely

### Actual behaviour

A container with @ Mention shows up

### Mastodon instance

masto.byrd.ws

### Mastodon version

v4.3

### Browser name and version

Firefox 132

### Operating system

Windows 11

**Comment by ClearlyClaire** [comment]
For reference, posts coming from streaming are correctly filtered, like in the old notifications. Those coming from the REST API, however, are not filtered.

I am unsure at which level those posts were filtered in the non-grouped notifications code path.
