### ISSUE TITLE
Advanced webinterface only updates home and notifications, all other TL need manual refresh

### ISSUE THREAD

**Issue by glOOmyART** [mastodon/mastodon#32344]
### Steps to reproduce the problem

updated mastodon from 4.2.13 to 4.3 according to the upgrade steps described in the release notes

### Expected behaviour

new posts should show up in the TL

### Actual behaviour

i need to press F5 to view the newest posts

### Detailed description

When in the advanced webinterface, only the home TL and the notification is currently updating itself with new posts, neither the federated nor my pinned list TL is updating itself and in the firefox dev console it seems it's trying to connect to /api/v1/streaming/? which fails

### Mastodon version

v4.3.0

### Browser name and version

Firefox 128.2.0esr

### Operating system

OpenSuse Leap 15.6

**Comment by renchap** [comment]
If connecting to streaming fails, then you probably have an issue with the streaming server. Please ensure it is running, and add its logs to this issue so we can ensure it works correctly.

**Comment by glOOmyART** [comment]
it seemed to be a configuration error in my apache 2 reverse proxy

i used to have
```
<Location />
    ProxyPass https://127.0.0.1:8443/
    ProxyPassReverse https://127.0.0.1:8443/
</Location>

<Location /api/v1/streaming/>
    RewriteEngine on
    RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
    RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
    RewriteRule /api/v1/streaming/(.*) ws://127.0.0.1:4000/api/v1/streaming/$1 [P]
</Location>
```
which worked the past 4 years of running mastodon
i changed to
```
ProxyPass / https://127.0.0.1:8443/
ProxyPassReverse / https://127.0.0.1:8443/

RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
RewriteRule /api/v1/streaming/(.*) ws://127.0.0.1:4000/api/v1/streaming/$1 [P]
```

and now it seems to be working again

i'll leave it here for further reference
