### ISSUE TITLE
Filtered notification does not disappear if user is suspended

### ISSUE THREAD

**Issue by renatolond** [mastodon/mastodon#32349]
### Steps to reproduce the problem

1. Get notified by a filtered notification
2. Instance-wide suspend user in question (removing the post)

### Expected behaviour

Filter notification disappears when user is suspended

### Actual behaviour

Filtered notification is still there, even if clicking on it returns nothing

### Mastodon instance

masto.donte.com.br

### Mastodon version

v4.3.0+donte

### Browser name and version

Version 129.0.6668.58 (Official Build, ungoogled-chromium) Arch Linux (64-bit)

### Operating system

Linux

**Comment by ClearlyClaire** [comment]
> 2\. Instance-wide suspend user in question (removing the post)

This does not immediately remove the posts, but it makes them inaccessible. We should be consistent with other endpoints and exclude suspended users in API responses.
