### ISSUE TITLE
Since 4.3.0 a column with tags doesn't update anymore automatically

### ISSUE THREAD

**Issue by JosKlever** [mastodon/mastodon#32355]
### Steps to reproduce the problem

In the advanced webview I've added a column with a few hastags, that I want to monitor. Since 4.3.0 this column doesn't update automatically anymore.

### Expected behaviour

New items should appear as they are posted

### Actual behaviour

The column doesn't update until I manually refresh the page

### Mastodon instance

toot.re

### Mastodon version

v4.3.0

### Browser name and version

Firefox 131.0

### Operating system

Windows 11

**Comment by JosKlever** [comment]
Yes indeed, it gives 502 Bad Gateway errors:

> GET wss://toot.re/api/v1/streaming/?
> NS_ERROR_WEBSOCKET_CONNECTION_REFUSED
> 
> Firefox kan geen verbinding maken met de server op wss://toot.re/api/v1/streaming/?.

**Comment by renchap** [comment]
This is an issue with toot.re, there is something wrong with their deployment and the streaming server is not properly accessible.

Maybe similar to https://github.com/mastodon/mastodon/issues/32344 ?

**Comment by mbootsman** [comment]
Hello, toot.re admin here :wink: 

We do not use a reverse proxy that was mentioned in #32344, so this is another problem.
I see the same behavior as well. Where can the streaming server logs be found, /home/mastodon/live/log has 0 files (except .keep)?

**Comment by renchap** [comment]
How do you deploy Mastodon? If you are using systemd, then the logs should be in journald.

**Comment by mbootsman** [comment]
I see this in the nginx error.log:

```
[error] 742#742: *173093 connect() failed (111: Unknown error) while connecting to upstream, client: xxxx:xxxx:xxx:x:xxx:xxxx:xxxx:xxxx, server: toot.re, request: "GET /api/v1/streaming/? HTTP/1.1", upstream: "http://127.0.0.1:4000/api/v1/streaming/?", host: "toot.re"
```

**Comment by renchap** [comment]
Is the streaming server running without errors, on `127.0.0.1:4000` ?

**Comment by mbootsman** [comment]
I don't think so:

```
curl 127.0.0.1:4000/
curl: (7) Failed to connect to 127.0.0.1 port 4000 after 0 ms: Connection refused
```

**Comment by mbootsman** [comment]
I'm on to something I think.

When I look in `/etc/systemd/system/mastodon-streaming@.service`
I see the ExecStart as `/usr/bin/node ./streaming`

When I execute that on the command line, I get: `-bash: /usr/bin/node: No such file or directory`
Checking node install now...

**Comment by mbootsman** [comment]
Created a symlink with `sudo ln -s /home/mastodon/.nvm/versions/node/v18.20.4/bin/node /usr/bin/`
Started `mastodon-streaming` with `sudo systemctl restart mastodon-streaming`

`curl http://127.0.0.1:4000/` now gives: `{"error":"Unknown channel requested"}`

No more errors in the console in the browser.

**Comment by JosKlever** [comment]
I can confirm it has been solved now. But it would be great if the root cause of this issue could be found, so that the upgrade process might be improved to reduce the change of this happening again.

**Comment by ThisIsMissEm** [comment]
Most likely the streaming service didn't start because it didn't find the node executable. When managing ruby & node.js versions via tools like rbenv, nvm, asdf and fnm, you need to modify the service file to point to the right executable.

Usually this means changing the ExecStart line to execute through the version manager of choice

**Comment by ThisIsMissEm** [comment]
I would *not* recommend randomly symlinking the nvm node executable to a different location on your PATH.

Perhaps see here for ideas: https://gist.github.com/joepie91/73ce30dd258296bd24af23e9c5f761aa

(I've only setup where I'm using fnm)
