### ISSUE TITLE
Revert: #31365

### ISSUE THREAD

**Issue by ZoeBijl** [mastodon/mastodon#32352]
### Pitch

Revert the styling introduced by #31365. Alternatively, remove the chevron bars in the compose, timeline, and post views.

### Motivation

The content warning styling introduced in #31365 / v4.3.0 is off putting and anxiety inducing. Content warnings are used in a myriad of ways, not just as warnings but also as wrappers/email headlines/you name it. The visually blaring warning style that was added doesn’t fit these other purposes.

**Comment by jubalbarca** [comment]
Strongly agree with this. Even for those of us who don't find the new system anxiety inducing, it looks kind of unprofessional and tacky for the interface to be yelling "oou scary" any time someone wants to put a header line on their topic. As an academic who's been trying to press for more adoption of Mastodon in my academic work contexts, changes like this which make the interface look _less_ polished and more cluttered make that job more difficult.

**Comment by VirtualWolf** [comment]
Yepppp. The whole name "content warning" is completely misleading anyway (hence #20117 about changing it to "content note"), and a _lot_ of my use of content warnings isn't actually a literal content warning, it's just a way to hide posts for people who might not care about the subject I'm posting about and really should be treated as just a subject instead.

**Comment by antimundo** [comment]
Related to #20117

I agree, also Mastodon is using the _subject_ line from ActivityPub for Content Warnings, and it is indeed often used as a "subject" line on Mastodon instead of just a "content warning".

**Comment by pwoolcoc** [comment]
Agree, I usually try to just roll with UI changes because I know they always get a lot of criticism, but in this particular case I think it's more than just preference, the CWs are now styled in a way that actively works against many of their intended uses.

**Comment by ryliejamesthomas** [comment]
I also think 'Show anyway' instead of 'show post' or something carries the same limited connotation as the danger stripes.

**Comment by ruthtillman** [comment]
I support removal of danger stripes and a more neutral language like “Show post” 

Recent CWs on my timeline:
- a joke setup
- a hurricane post
- a USPOL post
- a subject line saying they need input from a specific group
- a selfie, eye contact, boosts welcome
- a post about ID protection services

For only a few of these is caution tape and “show anyway” warranted. 

I am an admin of a small server (300ish active users) and the admin group for my instance will be deploying local CSS changes today but that’s really not ideal.

**Comment by llhilton** [comment]
Very much agree. The current display brings more attention to the post than I think it deserves.

**Comment by KeraKaye** [comment]
Yeah, this was a really bad change for the interface. The big comedic barricade tape motif is very distracting on the timeline, and has the unintended effect of making actual important trigger/content warnings seem like jokes in the process

**Comment by Andre601** [comment]
If they want to emphasize the title part, maybe have it be highlighted with a yellow semi-transparent color. Could perhaps look better than this danger stripes thing.

**Comment by nehemiagurl** [comment]
I want to emphasise that this is not just a UI issue, but an accessibility issue. any design that discourages the use of content warnings means degraded accessibility of the product.
when it comes to the text, I think the change should be fully reverted. no need to use "show anyway" for reasons I won't repeat.
as for design, I agree the old design could use some touch-ups, but this is far from what we need. I recommend taking inspiration from nileane/TangerineUI-for-Mastodon as to what a modern content warning can look like. their design also solved another complaint people had, which is that the clicking area to open the warning was shrunk.

**Comment by forestine1** [comment]
i have CPTSD and i am afraid that the danger tape and "show anyway" text on the new content warning box is going to discourage people from using warnings at all. trying to get people to warn for triggering topics is difficult enough as it is. many potentially triggering topics are not necessarily always universally bad. a neutral label allowed them to have a warning but not have a value judgment attached.

in use, it also draws attention to the warning in a way that could still be triggering if a person is trying to avoid a specific topic. 

and of course, people have been using content warnings for a lot of reasons. this change ignores the will of the community.

**Comment by belaset** [comment]
The change to a caution tape border really doesn't fit with how people use CWs at all (see #20117 for further discussion). Most of the time it's being used as a content _wrapper_, as in a product label that lists a post's contents/ingredients, rather than as a "warning" anyway - so that blaring black and yellow changes the whole feel of the timeline into a sense of constant danger, instead of it being a friendly place. Additionally, I think "show anyway" should just be a "show/hide" toggle to continue with the sense of neutrality. CW'd content isn't necessarily dangerous; they headline is just a notice of what's behind the cut.

**Comment by nlurker** [comment]
I have seen several users confused and upset about the new "show anyway" feature.  I would like to know what sort of review process this change went through, and who thought it was a good idea.

**Comment by nehemiagurl** [comment]
fyi: I know of and can link to discussions of people who consider stopping using content warnings because of this new design, and I know of and can link to instance admins that implement server-wide custom CSS to cancel this change.
the redesign hurts accessibility - this is no longer a prediction but a fact.

**Comment by belaset** [comment]
> fyi: I know of and can link to discussions of people who consider stopping using content warnings because of this new design, and I know of and can link to instance admins that implement server-wide custom CSS to cancel this change. the redesign hurts accessibility - this is no longer a prediction but a fact.
> 

I have custom CSS to change the CW border to something less blaring, not to remove it altogether. My instance admin has done the same, but instead of changing it to gray he has changed it to plaid. Another instance admin has changed it to a rainbow gradient. I still don't think the default should be hazard stripes! 

```
/* Changes the 'hazard' stripe bordering CWs to subtle gray */
.content-warning:after, 
.content-warning:before,
.compose-form .spoiler-input__border {
	background-image: none !important;
	background-color: rgb(119, 110, 137) !important;
}
```

**Comment by shleeable** [comment]
I feel like the stripe is going to be removed entirely, but I'm also not against the additional visual feedback.

Stripe on one side with a different colour scheme might work as well....

The people on my instance deeply dislike this, so i'm glad it's getting redesigned.

**Comment by antimundo** [comment]
There is already a pull request to change this #32543
