### ISSUE TITLE
Upgrade to 4.3.0 breaks SAML login

### ISSUE THREAD

**Issue by pelzvieh** [mastodon/mastodon#32362]
### Steps to reproduce the problem

1. Upgrade mastodon instance to 4.3.0 with previously working SAML setup
2. Call up login page of that instance with a fresh browser session
3. Press the blue "SAML" button to initiate login with SAML

### Expected behaviour

Redirect to the IDP authentication endpoint

### Actual behaviour

Red error box immediately appearing: "Du konntest nicht mit deinem SAML-Konto angemeldet werden, weil „Neither pub key nor priv key“."

### Detailed description

No redirect happen at all. Journalctl is also just revealing that single message:
```
Okt 09 15:55:04 mastodon bundle[3962447]: D, [2024-10-09T15:55:04.470163 #3962447] DEBUG -- omniauth: (saml) Request phase initiated.
Okt 09 15:55:04 mastodon bundle[3962447]: E, [2024-10-09T15:55:04.474769 #3962447] ERROR -- omniauth: (saml) Authentication failure! Neither PUB key nor PRIV key: OpenSSL::PKey::RSAError, Neither PUB key nor PRIV key
Okt 09 15:55:04 mastodon bundle[3962447]: I, [2024-10-09T15:55:04.475929 #3962447]  INFO -- : [36322430-6325-4cd0-8f49-6fe63595e85b] method=POST path=/auth/auth/saml format=html controller=Auth::OmniauthCallbacksController action=failure status=302 allocations=436 duration=0.75 view=0.00 db=0.00 location=https://mastodon...../auth/sign_in
```

While it is not totally clear which pub or priv keys this message refers to, certificate an private key required for signing a SAML request _are_ configured in the .env.production config file using the SAML_CERT and SAML_PRIVATE_KEY items.

### Mastodon instance

mastodon.flying-snail.de

### Mastodon version

v4.3.0

### Browser name and version

Firefox 131.0; Safari 18.0.1

### Operating system

macOS 15.0.1

### Technical details

Network inspector reveleals that no redirect to IDP is happening at all.

**Comment by renchap** [comment]
This may be caused by a change in how `dotenv-ruby` handles multiline ENV variables.

It no longer transform `\n` text (2 characters) into new lines, your variable needs to contain real new lines. Can you check if this is the case for your certificates?

A quick way to check if this is the cause is by setting `DOTENV_LINEBREAK_MODE=legacy` and see if it works. If it does, then you should update your cert variables to contain real new line characters.
