### ISSUE TITLE
"More" (kebab) menu in filtered toot opens towards outside the screen (advanced web interface)

### ISSUE THREAD

**Issue by renatolond** [mastodon/mastodon#32377]
### Steps to reproduce the problem

1. Click on a notification by a filtered user
2. Click on the "more" menu in the toot that generated the notification

### Expected behaviour

Either the menu opens upward or it allows the screen to scroll

### Actual behaviour

Menu does not fit and no way to scroll

### Detailed description

The menu seems to open to the bottom, even though there's space, it does not show completely:

![image](https://github.com/user-attachments/assets/aa50d13c-7468-48a3-8130-da4178fdfafd)

The same seems to happen on the notification column, but not in other columns, which seem to make the menu open to the top of the button if there's no space

It happens if I open the notification on a new window too, outside of the advanced web interface:
![image](https://github.com/user-attachments/assets/7d82f7f5-f51d-47ee-a2be-f3d7b3e3f5a9)

### Mastodon instance

masto.donte.com.br

### Mastodon version

v4.3.0+donte

### Browser name and version

Version 129.0.6668.58 (Official Build, ungoogled-chromium) Arch Linux (64-bit)

### Operating system

Linux

### Technical details

Resolution is 1920x1080, though there's space, so I don't think that's the issue

**Comment by ClearlyClaire** [comment]
This looks like a duplicate of #31737. I think the reason this is happening is the position of the “…” on the screen, not because this is specifically in this view.

**Comment by renatolond** [comment]
@ClearlyClaire Yeah, you're right, I managed to reproduce it on other timelines, I'll close it since it is indeed a duplicate of that one :)
