### ISSUE TITLE
Follow recommendations page defaults to first alphabetical language (Afrikaans)

### ISSUE THREAD

**Issue by brookmiles** [mastodon/mastodon#32380]
### Steps to reproduce the problem

1. Navigate to the "Follow recommendations" moderation page

### Expected behaviour

List is not filtered by Afrikaans

### Actual behaviour

List is filtered by Afrikaans

### Detailed description

More sensible default would probably be: no filter selected (as in trending posts), my current user language, or the server default locale.

### Mastodon instance

sunny.garden

### Mastodon version

v4.3.0

### Browser name and version

Firefox 131.0.2

### Operating system

Microsoft Windows [Version 10.0.19045.4894]

**Comment by renchap** [comment]
I am not able to reproduce this.

According to https://github.com/mastodon/mastodon/blob/stable-4.3/app/controllers/admin/follow_recommendations_controller.rb#L28, the default value comes from a newly created `FollowRecommendationFilter`, with the HTTP `params`, which should not be set when you open the page. 

And this default language is `I18n.locale`, which should be the current user's default locale: https://github.com/mastodon/mastodon/blob/stable-4.3/app/models/follow_recommendation_filter.rb#L14

Can you confirm the URL shown in the browser when you click on the link? And confirm that your locale is not currently set to Afrikaans?

**Comment by brookmiles** [comment]
> Can you confirm the URL shown in the browser when you click on the link? And confirm that your locale is not currently set to Afrikaans?

The URL is `https://sunny.garden/admin/follow_recommendations`

My "Interface language" in preferences was set to "English (British)".  I changed it to "English" and after that, the following recommendations page defaulted to "English" when opened.  Changing it back to "English (British)" defaults to Afrikaans again.

**Comment by renchap** [comment]
Good catch, this is the issue! There is no "English (British)" post language, so it fallbacks to the first item in the menu.
