### ISSUE TITLE
"Suppress follow recommendation" keeps user in both Active and Suppressed lists. Error page when suppressing same user again.

### ISSUE THREAD

**Issue by brookmiles** [mastodon/mastodon#32382]
### Steps to reproduce the problem

1. Navigate to "Follow recommendations" moderation page.
2. Suppress a recommended user
3. Select the "Suppressed" filter to see the user is listed
4. Select the "Active" filter to see the user is also still listed there
5. Suppress the same user again

### Expected behaviour

When suppressing a user, the user is listed in both Active and Suppressed lists.  Supressing the user a second time displays an error page.

### Actual behaviour

Suppressed user is no longer listed on the Active page. Supressing a user a second time (eg. if two tabs are open) behaves the same as suppressing it once.

### Mastodon instance

sunny.garden

### Mastodon version

v4.3.0

### Browser name and version

Firefox 131.0.2

### Operating system

Microsoft Windows [Version 10.0.19045.4894]

**Comment by renchap** [comment]
I have been able to reproduce this from `main`.

**Comment by brookmiles** [comment]
Returning to the "Follow recommendations" page an hour later, the item I suppressed earlier is no longer visible in the Active list.  Suppressing a new user refreshes the page, with the newly suppressed user still listed in Active. Navigating away from the page and back, the user recently suppressed is still listed.

There may be a caching or time based component to this?

**Comment by ClearlyClaire** [comment]
> There may be a caching or time based component to this?

Yes, that's exactly that.

Follow recommendations are stored in a materialized view, which is periodically rebuilt. Suppressions are taken into account when rebuilding it, but they are not applied on top of the built follow recommendations when those are fetched from the materialized view.
