### ISSUE TITLE
Make tags/<tagname> and users/<user>/updates/<id> views interactive

### ISSUE THREAD

**Issue by andi1984** [mastodon/mastodon#3239]
Tag view <instance-domain>/tags/<tagname> and updates view (users/<user>/updates/<id>) should be interactive as it would be that we use the search to find the same messages for given tagname or when I visit the tweet in my timeline.

Tag views appears from me when hashtags are linked on profile pages. Update views appears when clicking on date timestamp near message.

Without that the instance management technical detail becomes clearly visible to the user which imho should not be the case. The interaction should be as seamless as possible to make the user not think about those technical things!

* * * *

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
Should be addressed by 4.0 update which makes the web-app handle all links and removes the static views.
