### ISSUE TITLE
Cannot show medias on SWIFT ojbect storage

### ISSUE THREAD

**Issue by kenkiku1021** [mastodon/mastodon#32438]
### Steps to reproduce the problem

I'm using SWIFT compatible object storage for serving media files and I cannot show them.
The browser reports CSP blocked error on the console and SWIFT_OBJECT_URL does not exist in CSP headers.

### Expected behaviour

Media files would display.

### Actual behaviour

The browser shows corrupted images.

### Mastodon instance

https://procydon.net/

### Mastodon version

v4.3.0

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by renchap** [comment]
Fixed in #32439
