### ISSUE TITLE
Condensing of hashtags 

### ISSUE THREAD

**Issue by tenebrios** [mastodon/mastodon#32451]
### Pitch

Pages would be visually easier to look at if the tags were condensed.
Some put many tags on a post. It can get quite lengthy. 
When scrolling a page and seeing all of these tags, it's a distraction.

Perhaps if there are more than say 3 tags, let's say there are 15 tags.
Just make the post show the 3 tags with the included "and 12 more". You would then click where it says "and 12 more" to view all of the tags.

Example
#red, #green, #blue (and 12 more)

### Motivation

Condensing the tags on posts would make pages easier to view and reduce scrolling as well

**Comment by Cassolotl** [comment]
That's been a thing for a while, like so:

![Image](https://github.com/user-attachments/assets/9d07a11f-c6a5-49e9-a7ae-942b063cfb5a)

It only works if the *last* paragraph is *only* hashtags. Sometimes people accidentally put in something other than a hashtag, like a / or a comma or an @ group tag, which prevents the hashtags from being condensed. If anything is after the paragraph of *only* hashtags, it prevents the hashtags from being condensed.

**Comment by tenebrios** [comment]
> That's been a thing for a while, like so:
> 
> ![Image](https://github.com/user-attachments/assets/9d07a11f-c6a5-49e9-a7ae-942b063cfb5a)
> 
> (Spotted on https://mastodon.social/explore)
> 
> It only works if the _last_ paragraph is _only_ hashtags. Sometimes people accidentally put in something other than a hashtag, like a / or a comma or an @ group tag, which prevents the hashtags from being condensed. If anything is after the paragraph of _only_ hashtags, it prevents the hashtags from being condensed.

The screenshot you show, is that of the web app or the app via the app store?
For me, yes the condensed tags are on the web app   but not on the app store version.
I use the app store version regularly.

**Comment by Cassolotl** [comment]
Ahh, then you're on the wrong issue list, I think!

You need this issue list for iOS: https://github.com/mastodon/mastodon-ios/issues

Or this issue list for Android: https://github.com/mastodon/mastodon-android/issues

**Comment by tenebrios** [comment]
> Ahh, then you're on the wrong issue list, I think!
> 
> You need this issue list for iOS: https://github.com/mastodon/mastodon-ios/issues
> 
> Or this issue list for Android: https://github.com/mastodon/mastodon-android/issues

Ok 
I had no idea there were separate lists

**Comment by Cassolotl** [comment]
No problem. :) Feel free to close this issue when you're done!
