### ISSUE TITLE
bug: streaming service: fails to connect to redis due to WRONGPASS

### ISSUE THREAD

**Issue by delgh1** [mastodon/mastodon#32467]
### Steps to reproduce the problem

1. setup a test rig for mastodony
2. configure `/etc/redis/users.acl` for redisy with the default user off, in `.env.production` set `REDIS_USER` and `REDIS_PASSWORD`
3. restart all mastodony processes then the streaming api fails to connect to redis while sidekiqy succeeds
4. switch to `REDIS_URL`, restart the processes, everything works ok

### Expected behaviour

no error

### Actual behaviour

the streaming service fails to connect to redis while sidekiqy succeeds

### Detailed description

the error spit by the streaming service:

```
Oct 14 19:07:49 mastt node[1400]: {"level":"error","time":1728900469085,"pid":1400,"hostname":"mastt","name":"streaming","err":{"type":"ReplyError","message":"WRONGPASS invalid username-password pair or user is disabled.","stack":"ReplyError: WRONGPASS invalid username-password pair or user is disabled.\n    at parseError (/home/mastodon/live/node_modules/redis-parser/lib/parser.js:179:12)\n    at parseType (/home/mastodon/live/node_modules/redis-parser/lib/parser.js:302:14)","command":{"name":"auth","args":["mastodon"]}},"msg":"Redis Client Error!"}
```

`/etc/redis/users.acl`

```
user default off
user mastodon on ~* &* +@all >mastodon
```

`.env.production`

```
# this doesn't work for streaming but works for sidekiq
#REDIS_HOST=localhost
#REDIS_PORT=6379
#REDIS_USER=mastodon
#REDIS_PASSWORD=mastodon
# this works for everyone
REDIS_URL=redis://mastodon:mastodon@localhost:6379/0
```

I suspect this is related to #32265 ... at least in part.

Also, if I turn on the redis default user, the streaming service will say `[WARN] This Redis server's `default` user does not require a password, but a password was supplied`, but it will work fine.

### Mastodon version

v4.3.0

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
- Node.js version: v20.17.0

**Comment by delgh1** [comment]
ah, I also see this acl log in redis (master node) but not redis sentinels:

```
127.0.0.1:6379> acl log
1)  1) "count"
    2) (integer) 810
    3) "reason"
    4) "auth"
    5) "context"
    6) "toplevel"
    7) "object"
    8) "auth"
    9) "username"
   10) "default"
   11) "age-seconds"
   12) "4641.2889999999998"
   13) "client-info"
   14) "id=1750 addr=[::1]:56240 laddr=[::1]:6379 fd=40 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=42 qbuf-free=20432 argv-mem=12 multi-mem=0 rbs=16384 rbp=16384 obl=0 oll=0 omem=0 tot-mem=37660 events=r cmd=auth user=default redir=-1 resp=2"
```

so, I think the streaming service is trying very hard to use the username `default`

**Comment by renchap** [comment]
Pinging @ThisIsMissEm here, as you worked on the Redis configuration in streaming lately

**Comment by ThisIsMissEm** [comment]
@renchap looks like streaming accidentally used `REDIS_USERNAME` instead of `REDIS_USER` and neither I nor @oneiros caught the difference. It's an easy enough change to fix, but is a now potentially breaking configuration change. The `REDIS_USERNAME` support was only added in 4.3.0, so we could make the breaking change reasonably safely, as people are likely to either be using `REDIS_URL` or already have figured out that the two are inconsistent and configured both.

Interestingly for sentinels, we used the same name: `REDIS_SENTINEL_USERNAME` – it's just for `REDIS_USER` that we have variance to `REDIS_USERNAME`

This PR introduced the `REDIS_USERNAME` environment variable: https://github.com/mastodon/mastodon/pull/31623

**Comment by oneiros** [comment]
Hey @delgh1, the fix was committed, so you might want to try again using the current `main` branch.

If you want to stay on the released version, you could try to set *both* the `REDIS_USER` and `REDIS_USERNAME` variables (to the same value) and see how far you come with that.

**Comment by oneiros** [comment]
Works as in "everything works now"? Can we close #32265 as well?

**Comment by delgh1** [comment]
> Works as in "everything works now"? Can we close [#32265](https://github.com/mastodon/mastodon/issues/32265) as well?

sorry, only non-sentinel works, #32265 is still an issue
