### ISSUE TITLE
Unable to create an alias (for moving)

### ISSUE THREAD

**Issue by nekromoff** [mastodon/mastodon#32523]
### Steps to reproduce the problem

Creating alias will always fail if the former website is down or errors out. This should not be so and no check should be done in order to move from a non-working website. Otherwise it is impossible to begin migration on a working server.

![Image](https://github.com/user-attachments/assets/c82ea149-97ca-4af3-bf8b-405dedf26d21)

### Expected behaviour

No check, migration begins

### Actual behaviour

Failed check due to server issues, migration not possible

### Mastodon instance

mastodon.bot

### Mastodon version

v4.1.11

**Comment by renchap** [comment]
The account move path requires collaboration from the "old" server, to confirm you are authorised to move your account. You can not move from a server that is not available, by design.

**Comment by nekromoff** [comment]
Then broken by design.

**Comment by renchap** [comment]
I am not sure how you want this to work if the origin server is not available. You need a way for the origin account to approve the move, otherwise anybody could move your account.

**Comment by nekromoff** [comment]
Not sure, but I am not a Mastodon system architect to know all the details.
I am reporting the edge case when account move is impossible. And that's
clearly a bug.

**Comment by nekromoff** [comment]
BTW, I am only reporting that alias creation is impossible, you are talking
about the whole moving process, I am not. I am explicitly reporting alias
creation failure due to server down. Alias creation does not constitute a
move (yet!).

**Comment by nekromoff** [comment]
Unfortunately, the developer instead of looking for solutions is just OK with the broken design. The solution would be e.g. to verify against signed assets - i.e. checking against known rel="me". This guarantees that once some instance goes down or is unreachable, users won't be stuck!
