### ISSUE TITLE
migration v4.2.13 > v4.2.12 > 4.3.0 // database migration does not work

### ISSUE THREAD

**Issue by plachetka** [mastodon/mastodon#32561]
### Steps to reproduce the problem

First I did a rollback from 4.2.13 to 4.2.12 without any database changes to be able to update without any problems.
Then the 4.3.0 update went through.
To finish I tried the database migration, which failed.

I think some parts of this db migration were done in 4.2.12 to 4.2.13 upgrade, so these could be obmitted. Are there any hints to solve this problem on a fast way?

### Expected behaviour

migration without failure

### Actual behaviour

failure

### Detailed description

RAILS_ENV=production bundle exec rails db:migrate

I, [2024-10-17T14:08:34.815280 #3283481]  INFO -- : [dotenv] Loaded .env.production
I, [2024-10-17T14:08:35.390644 #3283481]  INFO -- : Migrating to AddUniqueIndexOnPreviewCardsStatuses (20230803082451)
== 20230803082451 AddUniqueIndexOnPreviewCardsStatuses: migrating =============
[strong_migrations] DANGER: No lock timeout set
-- add_index(:preview_cards_statuses, [:status_id, :preview_card_id], {:name=>:preview_cards_statuses_pkey, :algorithm=>:concurrently, :unique=>true})
bin/rails aborted!
StandardError: An error has occurred, all later migrations canceled: (StandardError)

PG::DuplicateTable: FEHLER:  Relation »preview_cards_statuses_pkey« existiert bereits

...

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0

### Environment

debian 12.7
postgresql 15
mastodon 4.3.0
ruby 3.3.5
nodejs v18.19.0

Please at least include those informations:
- Operating system: (eg. Ubuntu 22.04)
- Ruby version: (from `ruby --version`, eg. v3.3.5)
- Node.js version: (from `node --version`, eg. v20.18.0)

**Comment by ClearlyClaire** [comment]
This migration exists since 4.2.0, and it should not re-run regardless of your upgrade path.

This is rather surprising, but it looks like the migration failed mid-run the first time you ran it, but that should have happened when moving to 4.2.0.

**Comment by ClearlyClaire** [comment]
Try:
```sql
DROP INDEX preview_cards_statuses_pkey;
```

then `RAILS_ENV=production bundle exec rails db:migrate`

**Comment by plachetka** [comment]
Looks good, that's also the suggestion by pghero.
db:migrate worked.

After that some small problems stay in datebase:

Duplicate Indexes
These indexes exist, but aren’t needed. Remove them for faster writes.

Details
On account_aliases
index_account_aliases_on_account_id (account_id)
is covered by
index_account_aliases_on_account_id_and_uri (account_id, uri)
On account_relationship_severance_events
index_account_relationship_severance_events_on_account_id (account_id)
is covered by
idx_on_account_id_relationship_severance_event_id_7bd82bf20e (account_id, relationship_severance_event_id)
On custom_filter_statuses
index_custom_filter_statuses_on_status_id (status_id)
is covered by
index_custom_filter_statuses_on_status_id_and_custom_filter_id (status_id, custom_filter_id)
On webauthn_credentials
index_webauthn_credentials_on_user_id (user_id)
is covered by
index_webauthn_credentials_on_user_id_and_nickname (user_id, nickname)

**Comment by ClearlyClaire** [comment]
You can ignore them.
