### ISSUE TITLE
`fediverse:creator` tag isn't detected

### ISSUE THREAD

**Issue by 2br-2b** [mastodon/mastodon#32574]
### Steps to reproduce the problem

1. Create an external webpage with the following meta tag (see https://codegito.xyz/2024/10/06/incredible-investments/):
```
<meta property="fediverse:creator" name="fediverse:creator" content="2br-2b@codegito.xyz" />
```
2. Post the link on my Mastodon account (see https://mastodon.social/@2br_2b/113326601668050022):
![Image](https://github.com/user-attachments/assets/33571ae8-b718-41a3-a297-b5b741fea92a)

### Expected behaviour

I should have the "More from XYZ author" tag at the bottom

### Actual behaviour

I don't have the tag

### Detailed description

Per [the announcement article](https://blog.joinmastodon.org/2024/07/highlighting-journalism-on-mastodon/) and https://github.com/swicg/activitypub-html-discovery/issues/16, this should be enough to have my username discovered. I'm currently using the [Wordpress ActivityPub Plugin](https://github.com/Automattic/wordpress-activitypub) (their implementation count be found [here](https://github.com/Automattic/wordpress-activitypub/blob/trunk/integration/class-opengraph.php)).

My site (example webpage [here](https://codegito.xyz/2024/10/06/incredible-investments/), example Mastodon post [here](https://mastodon.social/@2br_2b/113326601668050022)) has the tag accessible without needing javascript:
![Image](https://github.com/user-attachments/assets/2e767955-7256-4716-bab5-668db110b126)

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.0+pr-32558-4fbd174

### Browser name and version

Brave 1.70.126

### Operating system

Windows 11

**Comment by ClearlyClaire** [comment]
It looks like the HTML tag is incorrectly referencing `2br-2b@codegito.xyz` instead of `2br_2b@codegito.xyz`

**Comment by 2br-2b** [comment]
Hi, that's a good catch, but the user is `@2br-2b@codegito.xyz`. My mastodon social account has the underscore due to Mastodon's restrictions.

Come to think of it, maybe that's the problem - if dashes aren't allowed in mastodon usernames, even if they're supported by activitypub, maybe that's why it's not showing up?

**Comment by 2br-2b** [comment]
Thank you so much! I just opened an issue to get that fixed over there.

**Comment by pfefferle** [comment]
@ClearlyClaire even if it is the same domain?

**Comment by ClearlyClaire** [comment]
Yes

**Comment by pfefferle** [comment]
thanks @ClearlyClaire and @2br-2b !

**Comment by gelbphoenix** [comment]
Question: Is that also for embeds loaded from e.g. The Verge to an own instance? Or could that be for another issue?

**Comment by pfefferle** [comment]
@gelbphoenix this is not about WordPress' oEmbed feature, so yes it should be another issue!

**Comment by gelbphoenix** [comment]
> ...this is not about WordPress' oEmbed feature, so yes it should be another issue!

Opened issue #33556
