### ISSUE TITLE
Yarn fails with checksum errors installing 4.3

### ISSUE THREAD

**Issue by pviglucci** [mastodon/mastodon#32597]
### Steps to reproduce the problem

1. yarn install --immutable
2.
3.
...

### Expected behaviour

Yarn should complete without errors

### Actual behaviour

Yarn fails with dependency and checksum errors

### Detailed description

Yarn fails with the following errors;

➤ YN0000: · Yarn 4.5.0
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 333ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ react is listed by your project with version 18.3.1 (p68bdc), which doesn't satisfy what emoji-mart-lazyload and other dependencies request (but they have non-overlapping rang
es!).
➤ YN0060: │ react-dom is listed by your project with version 18.3.1 (p9d1ad), which doesn't satisfy what react-router-scroll-4 and other dependencies request (but they have non-overlappin
g ranges!).
➤ YN0060: │ react-router-dom is listed by your project with version 5.3.4 (p7a2e6), which doesn't satisfy what react-router-scroll-4 requests (^4.0.0).                                    
➤ YN0002: │ @mastodon/mastodon@workspace:. doesn't provide redux (p7bebf), requested by react-redux-loading-bar and other dependencies.                                                    
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.             
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.                                                                    
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0018: │ babel-plugin-lodash@patch:babel-plugin-lodash@npm%3A3.3.4#~/.yarn/patches/babel-plugin-lodash-npm-3.3.4-c7161075b6.patch::version=3.3.4&hash=201e99: The remote archive doesn't match the expected checksum
➤ YN0018: │ resolve@patch:resolve@npm%3A1.22.8#optional!builtin<compat/resolve>::version=1.22.8&hash=c3c19d: The remote archive doesn't match the expected checksum                        
➤ YN0018: │ resolve@patch:resolve@npm%3A2.0.0-next.5#optional!builtin<compat/resolve>::version=2.0.0-next.5&hash=c3c19d: The remote archive doesn't match the expected checksum            
➤ YN0018: │ typescript@patch:typescript@npm%3A5.5.4#optional!builtin<compat/typescript>::version=5.5.4&hash=379a07: The remote archive doesn't match the expected checksum                 
➤ YN0000: └ Completed in 1s 249ms
➤ YN0000: · Failed with errors in 1s 679ms

### Mastodon instance

wargamers.social

### Environment

Please at least include those informations:
- Operating system: Ubuntu 20.04 LTS
- Ruby version: v3.3.5
- Node.js version: v23.0.0

### Technical details

git status

HEAD detached at v4.3.0
nothing to commit, working tree clean

**Comment by pviglucci** [comment]
Current Mastodon version is 4.2.13

**Comment by pviglucci** [comment]
Curious, what version of node are you using? I had to upgrade node since I’m on an older Ubuntu distribution. I installed the latest stable with nvm and should have probably stuck with the latest LTS in hindsight. Not sure if that’s the issue but will troubleshoot more this week. 

If you’re dead in the water, adding 

checksumBehavior: "ignore"

to .yarnrc.yml worked for me. Not a proper solution so YMMV.

**Comment by frootmig** [comment]
I was able to go back to the last 4.2.x version, which seem to have worked so far. I updated from 4.1.x to 4.2.x before and wanted to make the next step, too.

I installed the LTS version of node via repository:

```
nodejs --version
v23.0.0
```
I'm not sure if it's a good idea to ignore the checksums. I might wait for the next 4.3.x release before continueing the update.

**Comment by pviglucci** [comment]
This issue is resolved. Yarn fails when using node stable (v23.0.0 at the time of this post). Switching to LTS (v.20.18.0), clearing the yarn cache, and rerunning solved the issue for me. 

Maybe it’s common knowledge, but suggest updating the docs to reflect that LTS versions are required/recommended, e.g., Node: 18 or newer -> Node: 18 LTS or newer. 

Nodes unfortunate use of the term “stable”, when they really mean dev/unstable makes it easy to misunderstand the requirement.

**Comment by frootmig** [comment]
For me, it would have been better to write in the docs
Node: 18 or 20
Then it would have been clear. 23 stable does not work… To be fair, it seems to be a new release.

**Comment by andycarle** [comment]
@pviglucci Thank you for providing the fix here. This got me back up and running also.
