### ISSUE TITLE
GET /api/v2/notifications should return Array of GroupedNotificationResults but doesn’t

### ISSUE THREAD

**Issue by PattaFeuFeu** [mastodon/mastodon#32594]
### Steps to reproduce the problem

1. Call `GET /api/v2/notifications` with necessary credentials and permissions and compare its output with that of `GET /api/v1/notifications`—JSON array of JSON objects VS JSON object

### Expected behaviour

GET /api/v2/notifications should return an Array of type GroupedNotificationResults like /api/v1/notifications returns an Array of type Notification

### Actual behaviour

GET /api/v2/notifications returns a single GroupedNotificationResults, breaking consistency with other endpoints supporting pagination

### Detailed description

I was just implementing the new 4.3.0 endpoints for our Kotlin library “[BigBone](https://github.com/andregasser/bigbone/pull/494)” when I noticed in writing tests that `GET /api/v2/notifications` returns `GroupedNotificationResults` and not, as I would have expected as it otherwise looks mostly the same as the non-grouped variant, Array of `GroupedNotificationResults`.

Other endpoints that return pageable data return arrays so I feel like this is inconsistent with the rest of the API.

### Mastodon instance

chaos.social

**Comment by renchap** [comment]
This is expected, and has been done for performance reasons, and we are considering using this kind of API shape for other endpoints in the future.

This endpoint can return a lot of data with hundred of accounts and many statuses, so we designed it in a way that allows not duplicating data for those objects when they appear multiple times in the response.

Closing as we do not plan to change this.

**Comment by PattaFeuFeu** [comment]
Alright, thanks for the explanation! Then we’ll need to adapt to the possibility of both variants being available around the API. 😊
