### ISSUE TITLE
Media from a server limited with "reject media files" no longer shows as "Preview not available"

### ISSUE THREAD

**Issue by renatolond** [mastodon/mastodon#32595]
### Steps to reproduce the problem

1. Limit a server with "reject media files"
2. Follow someone from that server, User A
3. User A posts with a single image and it shows up on your followed timeline

### Expected behaviour

The media is not downloaded, but it shows that there's media on the post, a "Preview not available" and a link to the original media

### Actual behaviour

The post shows as if there was no media attached

### Detailed description

I noticed recently that new posts from users of a server with rejected media does not show as "preview not available" anymore. There's no indication that the post had media in the first place and the only way to find out is if you go to the original post.

### Mastodon instance

masto.donte.com.br

### Mastodon version

v4.3.0+donte

### Browser name and version

Chromium Version 129.0.6668.58 (Official Build, ungoogled-chromium) Arch Linux (64-bit)

### Operating system

Linux

### Technical details

There's no errors on the rails logs or on the console logs.

**Comment by ThisIsMissEm** [comment]
Are you able to bring up the developer tools and provide the API response for that status? This should still work from what I can tell.

It'll be a request like `GET /api/v1/statuses/:id`

**Comment by ThisIsMissEm** [comment]
I've just tested between two servers, the sender running `v4.3.0-beta.2` and the receiver running `v4.3.0-beta.2` — to my knowledge there weren't any changes between `v4.3.0-beta.2` and `v4.3.0` related to the media attachment handling, though there were some UI changes, but none that I think should've caused this as a regression.

![Image](https://github.com/user-attachments/assets/4c28bf72-7b68-4dc1-bfab-a9fa8b407b28)

**Comment by ThisIsMissEm** [comment]
I can reproduce this on v4.3.1, the post above now displays as:
![Image](https://github.com/user-attachments/assets/c00efeac-70b8-4216-b3a9-59ba2d04fcf1)

@renchap I've no idea what caused this regression, I didn't see anything obvious in the commit history between v4.3.0-beta.2 and v4.3.1

**Comment by ThisIsMissEm** [comment]
The media attachment definitely still exists, and the media attachment type is unknown, which did previously trigger the correct UI.

**Comment by ThisIsMissEm** [comment]
Looks like there used to be an else branch here: https://github.com/mastodon/mastodon/blob/main/app/javascript/mastodon/components/status.jsx#L522 

At least, one exists on v4.3.0-beta.2: https://github.com/mastodon/mastodon/blob/v4.3.0-beta.2/app/javascript/mastodon/components/status.jsx#L504

**Comment by ThisIsMissEm** [comment]
I think a possible fix is to add `'unknown'` to the array here: https://github.com/mastodon/mastodon/blob/main/app/javascript/mastodon/components/status.jsx#L452

**Comment by ThisIsMissEm** [comment]
Have opened a fix in https://github.com/mastodon/mastodon/pull/32613
