### ISSUE TITLE
The number of followers in the account timeline is increased strangely

### ISSUE THREAD

**Issue by kedamaDQ** [mastodon/mastodon#32607]
### Steps to reproduce the problem

Hit the bell, then the number of followers is increased...

https://github.com/user-attachments/assets/2e07ec44-998d-468f-9e26-3b5f1e9b77be

### Expected behaviour

don't increase the display of number of followers

### Actual behaviour

the display of number of followers is increased strangely

### Mastodon instance

foresdon.jp and RAILS_ENV=development main

### Mastodon version

v4.3.1 and also main branch

### Browser name and version

any (Firefox 131.0.2 / Chromium 129.0.6668.100 / safari 17.6...)

### Operating system

any (macOS, Linux, Windows)

**Comment by oneiros** [comment]
Thank you so much for reporting this and escpecially for including the video. That made it really clear what was happening.

**Comment by kedamaDQ** [comment]
Thanks for a lot for your confirmation and quick fixing!
