### ISSUE TITLE
Hi- I don't know what's going on or what has been going on for months that has restricted my access to my personal accounts, cell phone, and caused issues with my job.... but I am NOT a programmer, so I am pleading with you to take me out of whatever this is. This has been going on for months. If you need my name its Christine Maley or if you could provide some advice on how to rectify this I would greatly appreciate it... The more I attempt to remove everything the more embedded into the system it gets, I cant get into my new cellphone account... I am pleading for some information. The lead IT security at two different institutions have looked into it and can't fix the issue; I truly don't know what to do at this point. Anything would be helpful.

### ISSUE THREAD

**Issue by binhle113** [mastodon/mastodon#32601]
Hi- I don't know what's going on or what has been going on for months that has restricted my access to my personal accounts, cell phone, and caused issues with my job.... but I am NOT a programmer, so I am pleading with you to take me out of whatever this is. This has been going on for months. If you need my name its Christine Maley or if you could provide some advice on how to rectify this I would greatly appreciate it... The more I attempt to remove everything the more embedded into the system it gets, I cant get into my new cellphone account... I am pleading for some information. The lead IT security at two different institutions have looked into it and can't fix the issue; I truly don't know what to do at this point. Anything would be helpful. 

_Originally posted by @maleycl in https://github.com/github/roadmap/pull/1005#issuecomment-2423416481_

**Comment by RobotoSkunk** [comment]
This is spam
