### ISSUE TITLE
Top Active Servers and Space usage queries never complete. Overall poor performance following 4.3.0 update.

### ISSUE THREAD

**Issue by stevek101** [mastodon/mastodon#32618]
### Steps to reproduce the problem

1. Install 4.3.1
2. Start Web, Sidekiq, Steaming
3. Admin dashboard--Top active servers never completes (a long running postgres query that never completes.
4. Admin dashboard---Space Usage never completes updating
...
Note: in addition to these, the overall functioning of the Web app feels sluggish as compared to the pre-4.30 and 4.3.1 updates.

### Expected behaviour

Top active servers and Space Usage take up to several seconds to update

### Actual behaviour

Top active servers and Space Usage never completes after several minutes

### Detailed description

I have updated postgres index stats (analyze) on accounts and statuses.

Note: I noticed after the 4.3.0 update, that I had 4 duplicate indexes, which I dropped.

### Mastodon instance

indieauthors.social

### Mastodon version

v4.3.1

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x86_64-linux-gnu]
- Node.js version: v20.18.0

**Comment by stevek101** [comment]
> > in addition to these, the overall functioning of the Web app feels sluggish as compared to the pre-4.30 and 4.3.1 updates.
> 
> You are seeing a performance regression between 4.2 and 4.3? 

**Yes, my users have reported (and I) see a performance regression between 4.2 and 4.3. I added more CPU cores and memory to see if it helped the DB and elastisearch. There wasn't a noticeable improvement.**

> 
> > I noticed after the 4.3.0 update, that I had 4 duplicate indexes, which I dropped.
> 
> You should never make database schema changes yourself, and this will cause issues in a future update where we will have a migration to fix those duplicate indexes.

**Until now, we have never touched the database, but it was either that or considering a rollback. But, going forward, we will keep this in mind (i.e. don't change DB)**

**Comment by ThisIsMissEm** [comment]
I believe this will be fixed by this https://github.com/mastodon/mastodon/pull/32827

**Comment by mjankowski** [comment]
The linked PR that had an attempt at solving this was closed w/out merge because of other issues.

- Do other operators see similar slowdown/issues?
- Do we think something changed in 4.2 -> 4.3, or is this just a growth side effect of adding more data?
- Do you have sql logs with the specific query/queries that are slow, or is it just that watching the dashboard page itself is?

**Comment by ThisIsMissEm** [comment]
I've now see this take entire servers offline, and cause major performance issues for others. I also have a bunch of opentelemetry data available regarding the performance impacts here.

**Comment by vmstan** [comment]
Consolidating discussion to #31014
