### ISSUE TITLE
Please don't group notifications

### ISSUE THREAD

**Issue by kujudi** [mastodon/mastodon#32610]
### Pitch

In v4.4.0, notifications are grouped. Please remove this feature.

### Motivation

This is not good for communication, as it makes some feel like they are being ignored. My friends and I, as users, feel very uncomfortable to this feature. Please don't group notifications.

**Comment by sneakers-the-rat** [comment]
Notification grouping can be turned off in the notification settings menu :)

go to your notifications, click the gear icon, and uncheck the "group" box

**Comment by oneiros** [comment]
I was going to say the same. I think this should fix your issue, so I am closing this. If the issue persists, or we somehow misunderstood, please let us and/or reopen.

**Comment by colinstu12** [comment]
> Notification grouping can be turned off in the notification settings menu :)
> 
> go to your notifications, click the gear icon, and uncheck the "group" box

Has this changed between 4.4.0 and 4.4.5? 
1) there's no more gear... it's this obtuse symbol that's two carets (^ v atop each other). (and they invert once expanded)
2) There's only a single "Group" checkbox and it's only for "New Followers" and no other notification types.
