### ISSUE TITLE
action=index status=503

### ISSUE THREAD

**Issue by RJGhugo** [mastodon/mastodon#32621]
### Steps to reproduce the problem

1. Search a user (e.g. photog.social, social.heise.de)
2. Error
3. Search a user (e.g. mastodon.de, mastodon.social)
4. Success

### Expected behaviour

Add user

### Actual behaviour

Error 503 (IPv4 only instance)

### Detailed description

a) IPv6 only instance
b) NGINX in DMZ (IPv4 & IPv6)
c) Forwarding DMZ to Mastodon via IPv6

Worked fine with 4.3.0.

### Mastodon version

4.3.1

### Technical details

I, [2024-10-22T09:22:58.253296 #18]  INFO -- : [20fb787a-835b-42e4-981a-48f7df2594f1] method=GET path=/api/v2/search format=html controller=Api::V2::SearchController action=index status=503 allocations=4756 duration=13.09 view=0.35 db=2.11

**Comment by renchap** [comment]
Is your instance able to connect to IPv4 only servers? I am not sure I understand your network setup correctly.

If this worked with 4.3.0 and not 4.3.1, please double check if anything changed in your deployment, I can not see any change we made that could explain this.

**Comment by RJGhugo** [comment]
I can `curl https://swiss.social/users/ji7ro#main-key` but not `https://208.53.33.98`.

I am using a IPv6 only interface for the mastodon pod and a IPv4 & IPv6 interface for the DMZ with NGINX.

`2024-10-23T18:21:52.459Z pid=7 tid=2r0n WARN: HTTP::ConnectionError: failed to connect: Network is unreachable - connect(2) for 178.33.220.142:443 on https://swiss.social/users/ji7ro#main-key`

**Comment by RJGhugo** [comment]
Have not found any solution yet.

- NAT64

[NAT64](https://docs.opnsense.org/manual/how-tos/tayga.html) is working for URLs but not for IPs.

I am assuming, that the DNS-request is handled inside the pods and is only delivering IPv4s not an URL to the outside DNS of the pod.

- web

Trying to follow `IPv4` User:

`I, [2024-10-28T09:17:37.929941 #28]  INFO -- : [890d67d4-92cd-490b-a2aa-e1b68faae54a] method=GET path=/api/v2/search format=html controller=Api::V2::SearchController action=index status=503 allocations=5163 duration=17.66 view=0.85 db=2.36`

config/puma.rb

`if ENV['SOCKET']`
`  bind "unix://#{ENV['SOCKET']}"`
`else`
`  bind "tcp://#{ENV.fetch('BIND', '127.0.0.1')}:#{ENV.fetch('PORT', 3000)}"`
`end`

- sidekiq

`2024-10-28T08:41:00.239Z pid=7 tid=2qab WARN: HTTP::ConnectionError: failed to connect: Network is unreachable - connect(2) for 151.101.3.52:443 on https://fosstodon.org/users/ramblingsteve#main-key`

sidekiq:

Inside the **sidekiq** pod `/opt/mastodon/config/webpacker.yml` uses `dev_server.host: 0.0.0.0`.

The IPv6 equivalent of IPv4's `0.0.0.0` is `::/0`.

**Comment by RJGhugo** [comment]
@renchap 

It seems to be a similar problem: https://github.com/mastodon/mastodon/issues/30621

from mastodon web log trying to add @mho@social.heise.de from a **IPv6** instance:

`I, [2024-11-01T19:02:36.020292 #23]  INFO -- : [4b480343-ff81-49d0-bb26-12e75a68d443] method=GET path=/api/v2/search format=html controller=Api::V2::SearchController action=index status=503 allocations=5095 duration=11.53 view=0.15 db=1.33`

Do not see any erros in NGINX error.log.

**Comment by RJGhugo** [comment]
Found the problem!

I have "lost" **ALLOWED_PRIVATE_ADDRESSES: 64:ff9b::/96** for NAT64...
