### ISSUE TITLE
Mastodon instance clear after activating Active_Record_Encryption-Keys

### ISSUE THREAD

**Issue by Monokel777** [mastodon/mastodon#32629]
### Steps to reproduce the problem

I (auto)-upgaded my Mastodon-Instance to the most recent Version.
After Setting all the _ACTIVE_RECORD_ENCRYPTION_-Keys (follwed post: https://github.com/mastodon/mastodon/issues/30100) my Mastodon-Instance started again.
But all my Postes are gone an everythings clear.
There is just an "Notification-Field" in the lower left saying: "500".

In my Docker-Logs I got:
DB-Log:
`2024-10-22 18:18:41.533 UTC [52] ERROR:  relation "notification_policies" does not exist at character 523
2024-10-22 18:18:41.533 UTC [52] STATEMENT:  SELECT a.attname, format_type(a.atttypid, a.atttypmod),
	       pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
	       c.collname, col_description(a.attrelid, a.attnum) AS comment,
	       attidentity AS identity,
	       attgenerated as attgenerated
	  FROM pg_attribute a
	  LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
	  LEFT JOIN pg_type t ON a.atttypid = t.oid
	  LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
	 WHERE a.attrelid = '"notification_policies"'::regclass
	   AND a.attnum > 0 AND NOT a.attisdropped
	 ORDER BY a.attnum`

Web-Log:
`[eea050e7-83fd-4610-b25a-e0379968da65]   
I, [2024-10-22T18:19:06.535960 #24]  INFO -- : [f0337194-7549-4bb8-b3b8-32f26c4dc497] method=GET path=/api/v1/announcements format=html controller=Api::V1::AnnouncementsController action=index status=200 allocations=1344 duration=4.18 view=0.71 db=0.92

I, [2024-10-22T18:19:06.554109 #20]  INFO -- : [fb8a84c1-21c7-4d52-9b63-5c3e5df93399] method=GET path=/api/v2/notifications/policy format=html controller=Api::V2::Notifications::PoliciesController action=show status=500 allocations=1296 duration=4.58 view=0.00 db=1.07
E, [2024-10-22T18:19:06.554870 #20] ERROR -- : [fb8a84c1-21c7-4d52-9b63-5c3e5df93399]   
[fb8a84c1-21c7-4d52-9b63-5c3e5df93399] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "notification_policies" does not exist
LINE 10:  WHERE a.attrelid = '"notification_policies"'::regclass`

![Image](https://github.com/user-attachments/assets/6a97d81f-005b-4d6d-9326-325c4a9e5e38)

### Expected behaviour

my instance should be working

### Actual behaviour

my instance is xlear and shows 500

### Mastodon instance

social.jp3d.de

### Mastodon version

v4.3.1

### Browser name and version

Version 129.0.6668.89 (Offizieller Build) (64-Bit)

### Operating system

Arch Linux (6.11.4-arch2-1)

**Comment by renchap** [comment]
You should follow the upgrade instructions that are in our release notes for 4.3.0: https://github.com/mastodon/mastodon/releases/tag/v4.3.0

You most probably forgot to run the migrations after migrating, the `notification_policies` table does not exists, and should have been created by those migrations.

**Comment by Monokel777** [comment]
> You should follow the upgrade instructions that are in our release notes for 4.3.0: https://github.com/mastodon/mastodon/releases/tag/v4.3.0
> 
> You most probably forgot to run the migrations after migrating, the `notification_policies` table does not exists, and should have been created by those migrations.

Thats it! thank you.

It caused by auto-update by watchtower.

**Comment by renchap** [comment]
You should not use a basic auto-updater for your Mastodon containers, it is important to follow the steps outlined in the release notes. The most important part of those being the migrations, and in when to run them.
