### ISSUE TITLE
Status containing mentions is returned with empty `mentions` property

### ISSUE THREAD

**Issue by nikclayton** [mastodon/mastodon#32636]
### Steps to reproduce the problem

1. Open https://mastodon.social/api/v1/statuses/113341431960167738

### Expected behaviour

Status mentions another user, and includes a link with the class `mention`. The `mentions` property should be non-empty, and reference the mentioned account

### Actual behaviour

The `mentions` property is empty

### Detailed description

Nothing special about this post as far as I'm aware, I just happened to be testing accessibility actions in Pachli, and wondered why this post didn't trigger the "Show a dialog with a list of mentions" code.

Here's an extract of the pretty-printed JSON in the response.

```json
{
  "id": "113341431960167738",
  // ...
  "content": "<p>A+++++++<br><br>ht: <a href=\"https://threads.net/@jayorsi/\" class=\"u-url mention\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">@<span>jayorsi</span></a></p>",
  // ...
  "mentions": [],
}
```

As you can see, the content definitely mentions @jayorsi@threads.net, and includes a link to their account with the `mention` class. From this I infer that the backend -- at some point -- knew this was a mention. However, the `mentions` property is the empty list.

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.1

**Comment by Gargron** [comment]
Most likely the mentioned account is not opted-in to fediverse sharing on Threads. In which case the link in the body is just a link.
