### ISSUE TITLE
Too-long media descriptions are silently truncated

### ISSUE THREAD

**Issue by nikclayton** [mastodon/mastodon#32639]
### Steps to reproduce the problem

POST to `/api/v2/media` https://docs.joinmastodon.org/methods/media/#v2 with a description that is longer than 1,500 chars (MAX_DESCRIPTION_LENGTH, https://github.com/mastodon/mastodon/blob/main/app/models/media_attachment.rb#L40C3-L40C33).

### Expected behaviour

POST should fail with a "400: Bad request" error

### Actual behaviour

POST succeeds, the description is silently truncated to MAX_DESCRIPTION_LENGTH

### Detailed description

Bug is here: https://github.com/mastodon/mastodon/blob/393f0a0159f8c12316e903979f6a506e44ea2b50/app/lib/activitypub/parser/media_attachment_parser.rb#L29, where a substring of the description is used, instead of returning an error.

### Mastodon instance

mastodon.social

### Mastodon version

4.3.1

**Comment by ThisIsMissEm** [comment]
@nikclayton the "bug is here" isn't correct, that's affecting *incoming* activities. It has nothing to do with `POST /api/v2/media`

**Comment by ThisIsMissEm** [comment]
As you can see by https://github.com/mastodon/mastodon/pull/32683 it does actually return an error (422 + a json containing errors)

**Comment by mjankowski** [comment]
I looked at that PR and spec, and agree w/ the assessment that the endpoint does successfully response with 422 and error json -- `{"error":"Validation failed: Description is too long (maximum is 1500 characters)"}` -- going to close as cant reproduce, but if there's some other scenario here which is NOT captured by that spec but does lead to that behavior, please reopen/update.
