### ISSUE TITLE
Sharing a URL that contains a hash sign gets truncated

### ISSUE THREAD

**Issue by SiegfriedSchweizer** [mastodon/mastodon#32645]
### Steps to reproduce the problem

1. Log into Mastodon
2. Go to https://digital-heritage-minds.com/dht-portal/
3. Type “Wien” into the search slot where it says “Find items”
4. Click the search button with the magnifier symbol to the right of the search slot
5. A search result containing a single item (a Secession placard) shows
6. Click the share button with the Mastodon symbol which is located rightmost one row above the search slot and button
7. Click “Post” and then “Open”

### Expected behaviour

URL should be posted as-is without truncation

### Actual behaviour

URL to share is being truncated after the hash sign

### Detailed description

On my portal page I got a Mastodon share button which consists of a hyperlink and a Mastodon symbol like so:

```
<a id="mastodonShareLink" href="https://mastodonshare.com/?url=https%3A%2F%2Fdigital-heritage-minds.com%2Fdht-portal%2F%23Wien" title="Share on Mastodon" target="_blank">
    <img src="https://digital-heritage-minds.com/wp-content/themes/wp-bootstrap-custom/img/mastodon.svg" class="header-mastodon-logo">
</a>
```

The value of the `url` GET parameter is the urlencoded https://digital-heritage-minds.com/dht-portal/#Wien where the part after the hash sign (the #) denotes a search parameter. That is, the user should be able to share a search result. The URL above yields, if called directly (clicked right here), a result of one item which is associated with the search term “Wien” (Vienna).

However, when shared via the above noted share button code, the hash sign and the “Wien” string is being cut off, so the URL https://digital-heritage-minds.com/dht-portal/ (where the resulting post links to) does not contain the search result anymore, but shows all items on my site.

This behavior already occurs in the sharing dialog that is to be seen after clicking the share button:

![Image](https://github.com/user-attachments/assets/f574c85c-bce3-431b-aa01-296cdc429784)

 When posting said URL directly in the Mastodon web interface, the post contains the correct URL containing the hash sign and the following string.

### Technical details

Nothing to mention here

**Comment by daprice** [comment]
The page’s html specifies an `og:url` (i.e. the URL for sharing) value of `https://digital-heritage-minds.com/dht-portal/` (without the hash and string), which is probably why it gets shared that way. I see the same result when sharing with other messaging apps using Safari’s built-in share button as well.

**Comment by SiegfriedSchweizer** [comment]
> The page’s html specifies an `og:url` (i.e. the URL for sharing) value of `https://digital-heritage-minds.com/dht-portal/` (without the hash and string), which might be why it gets shared that way. I see the same result when sharing with other messaging apps using Safari’s built-in share button as well.
> 
> It’s possible that the canonical URL meta tag is also involved here, as in [#32646](https://github.com/mastodon/mastodon/issues/32646)

I see, however as in [#32646] does this really override the GET parameter given in the share link and is it an intended behavior? At least Facebook, X and Pinterest do not behave that way.

**Comment by SiegfriedSchweizer** [comment]
Besides, when posting said URL directly in the Mastodon web interface, the post contains the correct URL containing the hash sign and the following string. So the `og:url` issue doesn't apply then. However I'm going to fix that in my pages and we'll see if it changes things.

**Comment by daprice** [comment]
Looking at this again, it looks like a bug in mastodonshare.com. It isn’t URL encoding the hash symbol, so Mastodon’s share page doesn’t interpret it as part of the query.

When mastodonshare.com opens the instance’s share page, it’s opening `https://[instance]/share?text=https://digital-heritage-minds.com/dht-portal/#Wien`

when it should use `https://[instance]/share?text=https://digital-heritage-minds.com/dht-portal/%23Wien` which includes the hash and the string following it.

**Comment by ThisIsMissEm** [comment]
This is likely because the hash fragment in the URL isn't sent to the server, so if you want that, then you need to URL Encode the text first.

**Comment by ThisIsMissEm** [comment]
This is a bug in mastodonshare.com, not in Mastodon: `https://hachyderm.io/share?text=https://digital-heritage-minds.com/dht-portal/%23wein` works correctly.

However, mastodonshare.com is incorrectly redirecting without URL encoding the text it received.

**Comment by ThisIsMissEm** [comment]
Another example of it failing when the share text included a hashtag, request URL was: `https://mastodonshare.com/?text=Test%20%23foo%20test`

![Image](https://github.com/user-attachments/assets/6b5a0e2a-15e2-4bfe-ae2e-981557bbb9bf)

**Comment by jarofgreen** [comment]
I know it's not related to this project but for anyone finding this this issue on https://mastodonshare.com has now been fixed. (Not by me, I'm just passing on)
