### ISSUE TITLE
Onboarding modal with about/more info before creating new account

### ISSUE THREAD

**Issue by chriswmartin** [mastodon/mastodon#3264]
It would be useful to create a popup that is designed based on the onboarding modal (#1883) that contains information from the instance's about/more page. 

This should appear after a user clicks on the "GET STARTED" button to create a new account and the user should have to click through the model before being presented with two options: "continue" - which will create their new account and "cancel" - which will not create a new account.

As it stands now a new user on an instance can create an account and join Mastodon all without realizing the about/more page exists - potentially missing important rules, code of conduct information.
* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
Closing on assumption that this is resolved in newer versions. Can you re-open with current screenshots if still problem in 4.3?
