### ISSUE TITLE
`fediverse:creator` implementation issues

### ISSUE THREAD

**Issue by j9t** [mastodon/mastodon#32654]
### Steps to reproduce the problem

1. Compare toots with links to URLs that have `fediverse:creator` implemented, like [1](https://mastodon.social/@heiseonline@social.heise.de/113363121147004025) (`<meta name="fediverse:creator" content="@mho@social.heise.de">`), [2](https://mastodon.social/@Edent/113356525041822038) (`<meta content="edent@mastodon.social" property="fediverse:creator">`), and [3](https://mastodon.social/@j9t@mas.to/113363947295928297) (`<meta name="fediverse:creator" content="@j9t@mas.to">`)

### Expected behaviour

Mastodon shows “More from…” creator info for 1 and 3 (and perhaps 2)

### Actual behaviour

Mastodon shows “More from…” creator info for 1 and 2 (but not 3)

### Detailed description

According to #30398, the markup to be used for `fediverse:creator` is `<meta name="fediverse:creator" content="username@domain">`.

However,

1. this metadata doesn’t seem to be supported reliably (cf. examples 1 and 3, which are of identical form)
2. there seem to be possibly undocumented alternative forms that are supported (cf. example 2, where not only the use of `property` but also the missing leading `@` seem relevant)

### Mastodon instance

mastodon.social, mas.to

### Mastodon version

v4.3.1

### Browser name and version

Vivaldi 6.9.3447.55

### Operating system

macOS 14.6.1

**Comment by renchap** [comment]
Can you provide some pages showing those examples?

Also note that the AP account needs to have approved the domain names for attribution before your instance learns for the link for the first time, otherwise nothing will show.

**Comment by j9t** [comment]
> Can you provide some pages showing those examples?

Three examples are linked above (I just named them “1”, “2,” and “3”). For more convenience:

1. https://mastodon.social/@heiseonline@social.heise.de/113363121147004025 → https://www.heise.de/news/Astronomie-Wohl-erstes-Schwarzes-Loch-in-Dreifachsystem-wirft-Fragen-auf-9993361.html
2. https://mastodon.social/@Edent/113356525041822038 → https://shkspr.mobi/blog/2024/10/theatre-review-coriolanus-at-the-national-theatre/
3. https://mastodon.social/@j9t@mas.to/113363947295928297 → https://meiert.com/en/blog/optimization-measures-27/

> Also note that the AP account needs to have approved the domain names for attribution before your instance learns for the link for the first time, otherwise nothing will show.

What does “AP” stand for, and how can a domain get approved? (Is there something to read up on?)

**Comment by renchap** [comment]
AP means ActivityPub, the protocol Mastodon is built upon.

To approve a domain for attribution with our account, you need to add it to the list in Preferences > Public Profile > Verification

![Image](https://github.com/user-attachments/assets/0f593314-a155-474c-b573-7c7ecc05f6d7)

**Comment by j9t** [comment]
That seems to be it!

There may be something to documentation and promotion of this feature, but for purposes of this to be working or not, this isn’t an issue then.

Thanks for clarifying, @renchap!

**Comment by miketheman** [comment]
> There may be something to documentation and promotion of this feature, but for purposes of this to be working or not, this isn’t an issue then.

Blog from July: https://blog.joinmastodon.org/2024/07/highlighting-journalism-on-mastodon/
