### ISSUE TITLE
Fail more gracefully when a user-selected theme isn't available

### ISSUE THREAD

**Issue by selectric401** [mastodon/mastodon#32702]
While upgrading an instance (non-docker) from 4.2.1 to 4.3.0, I temporarily removed a custom theme that I'd previously installed, because it also had updates for the new major release. While the theme was unavailable, users who had the custom theme enabled in their settings were unable to access the web interface at all. I was able to resolve this by manually editing the affected users' settings in the database.

Instead of instance admins having to edit this manually for all affected users, it would make far more sense for Mastodon to fall back to the default theme if a custom theme is no longer available.

**Comment by ClearlyClaire** [comment]
Mastodon already falls back to the server-specific default theme if the user-selected theme is not known: https://github.com/mastodon/mastodon/blob/75b2ac49fb75cc9a842baec207325ef2b3a1335d/app/controllers/application_controller.rb#L156

However, it would indeed fail if neither the user-selected theme nor the server-specific default theme are known. Was it perhaps your server's case?

**Comment by selectric401** [comment]
I don't think so -- my `themes.yml` file is otherwise untouched, and has contained the `default` theme entry this whole time. However, I may have found the actual issue I encountered while troubleshooting further: when I try to include the [Tangerine themes](https://github.com/nileane/TangerineUI-for-Mastodon) and precompile assets, the compile fails, seemingly due to the number of Dart Sass deprecation warnings. I'm assuming that some included style assets are affected by that failure, in addition to the Tangerine assets.

**Comment by ClearlyClaire** [comment]
The default theme is not set in `themes.yml` but at `/admin/settings/appearance`.

The Dart Sass deprecation warnings should be just that: deprecation warnings, and should not affect Tangerine afaik, and even less so built-in styles. But webpack has a bad habit of running out of memory when building assets, and webpacker of badly reporting the cause of assets build failure.

It would help if you had actual backtraces from the 500 errors your users initially faced.

**Comment by selectric401** [comment]
I'll attempt to reproduce the issue and generate some 500s -- if not, I'll close this issue out :)
