### ISSUE TITLE
RSS feeds not working for usernames containing an @ sign (ampersat)

### ISSUE THREAD

**Issue by notDavid** [mastodon/mastodon#32712]
### Steps to reproduce the problem

1. Try to get the rss feed of for example user `@FTM_nl@ftm.nl` at `https://mastodon.social/@FTM_nl@ftm.nl.rss`
2. The resulting rss feed should be at `https://mastodon.social/@FTM_nl@ftm.nl.rss`
3. However, this url does not work. See: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fmastodon.social%2F%40FTM_nl%40ftm.nl.rss

I assume the cause is the username containing an `@` sign.

### Expected behaviour

The rss feed should work

### Actual behaviour

The RSS feed url does not work, see: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fmastodon.social%2F%40FTM_nl%40ftm.nl.rss

### Mastodon instance

mastodon.social

### Mastodon version

v4.3.1

**Comment by ClearlyClaire** [comment]
Hi! Users with a `@` in the name are remote users and Mastodon not providing a RSS feed for them is by design!

In this case, please try <https://social.ftm.nl/@FTM_nl.rss>
