### ISSUE TITLE
Search with `max_id` or `min_id` always fails with `422 Invalid date`

### ISSUE THREAD

**Issue by daprice** [mastodon/mastodon#32731]
### Steps to reproduce the problem

1. make API call to search for statuses with a max_id, e.g. `https://mastodon.online/api/v2/search?q=search&type=statuses&max_id=113404702919566475`

Alternatively, using Ivory:
1. Perform any search (e.g. for the word “search”)
2. Scroll down far enough that it tries to load the next page of results, or refresh so it tries to load newer results

### Expected behaviour

Returns statuses with IDs below given max_id or above min_id

### Actual behaviour

422 Invalid date, with a date that was not in the request (example above returns `{"error":"Invalid date 2024-10-31T23:47:20Z”}`)

### Detailed description

This affects all searches in Ivory (probably other clients as well) which appears to use the min_id and/or max_id parameters for pagination

### Mastodon instance

mastodon.online, mastodon.gamedev.place

### Mastodon version

v4.3.1

### Technical details

The full error log entry from Ivory (with request and response headers) looks like:
```
GET 'https://mastodon.online/api/v2/search'
	Query Arguments:
		'min_id' = '113404702919566475'
		'q' = 'search'
		'type' = 'statuses'
		'limit' = '40'
	Request Headers:
		'Authorization' = '<REDACTED>'
	Response Headers:
		'x-runtime' = '0.019145'
		'content-security-policy' = 'default-src 'none'; frame-ancestors 'none'; form-action 'none''
		'Cache-Control' = 'private, no-store'
		'Strict-Transport-Security' = 'max-age=31557600'
		'x-ratelimit-reset' = '2024-11-01T00:00:00.638148Z'
		'Accept-Ranges' = 'bytes'
		'x-timer' = 'S1730419104.538322,VS0,VE169'
		'referrer-policy' = 'same-origin'
		'x-served-by' = 'cache-hel1410020-HEL, cache-iah1720101-IAH'
		'Alt-Svc' = 'h3=":443";ma=86400,h3-29=":443";ma=86400,h3-27=":443";ma=86400'
		'Content-Length' = '45'
		'Via' = '1.1 varnish, 1.1 varnish'
		'x-xss-protection' = '0'
		'Date' = 'Thu, 31 Oct 2024 23:58:23 GMT'
		'Vary' = 'Authorization, Origin'
		'x-cache-hits' = '0, 0'
		'x-ratelimit-limit' = '300'
		'x-request-id' = 'a0f61c8fd500a9ced9b872e837631ade'
		'x-frame-options' = 'DENY'
		'x-cache' = 'MISS, MISS'
		'Content-Type' = 'application/json; charset=utf-8'
		'x-ratelimit-remaining' = '267'
		'x-content-type-options' = 'nosniff'
	Error: PTHHTTPErrorDomain:422 'client error'
	Response:
		'error' = 'Invalid date 2024-10-31T23:47:20Z’
```

**Comment by nikclayton** [comment]
Data point: testing with Pachli shows that searches using the `offset` parameter instead of `m.._id` are not affected.

**Comment by ClearlyClaire** [comment]
This is almost surely due to #31526 rejecting datetimes that are not only dates.

**Comment by ClearlyClaire** [comment]
To add some more context: `offset` is the recommended way to paginate through search results, but `min_id`/`max_id` are also supported, and internally converted to ISO-8601 datetimes, which are rejected by the regexp introduced in https://github.com/mastodon/mastodon/pull/31526.

That regexp needs to be edited to support optional time in such datetimes.

**Comment by daprice** [comment]
Is there a particular reason `offset` is recommended? Since the results for a given `offset` value aren’t stable over time as more posts get made, it’s not really feasible to use in a user-focused app where we don’t know how long the user will wait before trying to load the next page.
