### ISSUE TITLE
For certain blog sites, Mastodon generates invalid links in the automatic preview

### ISSUE THREAD

**Issue by CarlFink** [mastodon/mastodon#32732]
### Steps to reproduce the problem

1.Paste a URL into a reply or new toot
2.Publish.
3.The toot has a preview card and text link automatically created. Both link to an invalid and incorrect URL.

### Expected behaviour

The URL pasted into the toot is also what the preview card links to.

### Actual behaviour

An extra slash is added to the URL, resulting in a 404 error

### Detailed description

Example URL: https://jamesdavisnicoll.com/review/up-in-the-sky/
Invalid preview card URL Mastodon generates: https://jamesdavisnicoll.com//review/up-in-the-sky

Tested on two instances: mstdn.party and wandering.shop.

What's the official way for a non-dev to report a bug,  anyway? Thanks.

### Mastodon instance

https://mstdn.party/

### Mastodon version

4.2.13

### Browser name and version

131.0.3 (64-bit)

### Operating system

Void Linux (rolling release as of 31 October 2024). Note that this cannot possibly be relevant.

**Comment by daprice** [comment]
That link with the two slashes is coming from the website itself: `<link rel="canonical" href="https://jamesdavisnicoll.com//review/up-in-the-sky”>` is in the `<head>`

**Comment by CarlFink** [comment]
> That link with the two slashes is coming from the website itself: `<link rel="canonical" href="https://jamesdavisnicoll.com//review/up-in-the-sky”>` is in the `<head>`

Wow. That never occurred to me. OK, I'll tell James, who can talk to the person that hosts his site.

Why is Mastodon taking a URL from <head> instead of using what is posted into the toot?

Thank you.

**Comment by daprice** [comment]
The canonical URL is a way for the site to tell search engines and social networks “here’s the main version of the URL you should use”. This [article](https://yoast.com/rel-canonical/) explains it pretty well I think.

As far as Mastodon changing the link, I think that should have been fixed in Mastodon 4.3 ( #27312 ), which is newer than what your server is running. I tried posting that link on a server running 4.3.1, and it kept it as the correct (single slash) version.

**Comment by CarlFink** [comment]
> The canonical URL is a way for the site to tell search engines and social networks “here’s the main version of the URL you should use”. This [article](https://yoast.com/rel-canonical/) explains it pretty well I think.
> 
> As far as Mastodon changing the link, I think that should have been fixed in Mastodon 4.3 ( [#27312](https://github.com/mastodon/mastodon/pull/27312) ), which is newer than what your server is running. I tried posting that link on a server running 4.3.1, and it kept it as the correct (single slash) version.

Thank you very much, @daprice. I'll tell James.

**Comment by ClearlyClaire** [comment]
Thanks for your report! Closing it, though, as it seems to be an issue with the particular blog and not with Mastodon itself.
