### ISSUE TITLE
Screen elements overlap each other when replying to a long toot

### ISSUE THREAD

**Issue by TimWardCam** [mastodon/mastodon#32780]
### Steps to reproduce the problem

1. Reply to a toot that was several lines long..

### Expected behaviour

The box in which I'm typing the reply and the bottom part of the toot to which I'm replying should not be splatted all over each other on the screen.

### Actual behaviour

They were.

### Detailed description

This is repeatable - it happens every time since c.im updated to v4.3.1, but never happened before.

![Image](https://github.com/user-attachments/assets/e3310dab-cc8b-4cec-86f9-192acf26897b)

Even weirder things happen when the toot being replied to contains emojis.

### Mastodon instance

c.im

### Mastodon version

v4.3.1

### Browser name and version

Chrome Version 130.0.6723.92 (Official Build) (64-bit)

### Operating system

Windows 11

### Technical details

As it's repeatable every time I can capture any additional information desired.

**Comment by ClearlyClaire** [comment]
Hi! This looks like an issue with some custom styling added by c.im.

**Comment by TimWardCam** [comment]
Now fixed by c.im. Thanks @ClearlyClaire for the diagnosis.
