### ISSUE TITLE
SMTP has stopped working (Net::OpenTimeout: execution expired)

### ISSUE THREAD

**Issue by collex100** [mastodon/mastodon#32808]
### Steps to reproduce the problem

A week ago, I installed version 4.3.1. on Ubuntu 24.04. I installed it from the source. Instructions from the official documentation. Everything is working well now. It was a test domain and instance.  I decided to launch production today using the same instructions on the working domain and encountered the error that Mastodon cannot send mail via SMTP.

Net::OpenTimeout: execution expired

![Image](https://github.com/user-attachments/assets/d857d860-3b5f-4ed7-95eb-47b07dbe4ecd)

### Expected behaviour

SMTP mail should be sent

### Actual behaviour

SMTP mail is not sent and constantly writes errors

### Detailed description

The same SMTP details work properly on a Mastodon instance in a week-old instance.
The instance that I launched today with these details and others also doesn't work at all.

I searched the whole Internet and the only thing I found were comments about Ruby.

I can't understand why a week ago, everything was installed well, and today I reinstalled it several times from scratch, on the same hosting, according to the same instructions, and I have an error that I can't figure out how to treat.

 Please help me figure out the issue, because SMTP does not work and I cannot launch an instance of Mastodon.

### Mastodon instance

planet596.socia

### Mastodon version

v4.3.1

### Environment

Please at least include those informations:
- Operating system: (eg. Ubuntu 24.04)
- Ruby version: (from `ruby --version`, eg. v3.3.6)
- Node.js version: (from `node --version`, eg. v20.18.0)

### Technical details

Net::OpenTimeout: execution expired

`.env.production`

SMTP_SERVER=smtp.xxxxx.com
SMTP_PORT=465
SMTP_LOGIN=notifications@xxxxx.xxx
SMTP_PASSWORD=xxxxxxxxxxxxxxx
SMTP_AUTH_METHOD=login
SMTP_OPENSSL_VERIFY_MODE=peer
SMTP_ENABLE_STARTTLS=auto
SMTP_SSL=true
SMTP_FROM_ADDRESS='<notifications@xxxxx.xxx>'

**Comment by collex100** [comment]
Started another server instance. The launch took place according to the official instructions again and everything worked. I don't know what it was. The new installation is working now.

**Comment by shiny** [comment]
Facing the same issue after upgrading from version 3 to version 4


----

In the end, I found that it was caused by a newly purchased server with a brand new firewall enabled by default. The provider had blocked the outbound email ports. After deleting it, email started working again.
