### ISSUE TITLE
Spelling error in EN settings

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#32820]
### Steps to reproduce the problem

Minor
Open Preferences
Click Public Profile
Click Privacy and Reach

![Image](https://github.com/user-attachments/assets/b7dc4243-774e-4161-a5ba-ce260d5da526)

### Expected behaviour

"choose"

### Actual behaviour

"chose"

### Mastodon instance

mastodon.social

### Mastodon version

v4.4.0-nightly.2024-11-06

### Browser name and version

firefox

### Operating system

lunix!!!

**Comment by ThisIsMissEm** [comment]
Opened a PR to fix: https://github.com/mastodon/mastodon/pull/32821
