### ISSUE TITLE
Drawer tries to scroll to top with every keypress, causing it to twitch

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [mastodon/mastodon#3283]
If you've typed a long enough post (on desktop mode) that your drawer starts to scroll down, it'll attempt to scroll back up when you press a key. However, the browser causes it to scroll back down because you're still typing, causing an odd twitching effect.

Steps to reproduce:
1. Be on multicolumn mode
2. Be replying to a long post (best way to cause it to scroll)
3. Type until it goes past your screen
4. Keep typing, and observe that the column will randomly twitch up.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
hmm. I'm having trouble reproducing this on Chrome 58, Mac OS, and Mastodon 1.4.0.3 (the version deployed on witches.town, with their custom CSS).

What browser and OS are you using?

**Comment by no-boot-device** [comment]
Firefox and Linux.

**Comment by nightpool** [comment]
I can reproduce this on Firefox.

**Comment by Gargron** [comment]
@nightpool Does this have anything to do with the textarea height hacks? Because afaik the compose column doesn't use Scrollable so it wouldn't be that

**Comment by nightpool** [comment]
@Gargron the root cause is definitely somewhere around there. There's something different about how the resizing works in chrome vs firefox that is causing this. 

The specific 1.4 regression though has to do with scrollbars though—as far as I can figure out, in 1.3 this was *also* a problem, but it wasn't noticeable because you couldn't scroll the left pane on your own, so the "jumping" was very hard to notice.

**Comment by Gargron** [comment]
Uhh is this still a problem?

**Comment by trwnh** [comment]
i can't reproduce this in the latest firefox, and the issue was filed for v1.x, so i'm closing it as stale. if it can be reproduced, please file a new issue for it
