### ISSUE TITLE
Due to a bug in our code or a browser compatibility issue, this page could not be displayed correctly.

### ISSUE THREAD

**Issue by kenji-m** [mastodon/mastodon#32867]
### Steps to reproduce the problem

I got an error message on web browser. This is the first time I got an error message like this. There was no issue a few hours ago. I paste it below:

> Due to a bug in our code or a browser compatibility issue, this page could not be displayed correctly.
> Try refreshing the page. If that does not help, you may still be able to use Mastodon through a different browser or native app.
> Mastodon v4.3.1-stable+ff1_

```
TypeError: Cannot read properties of undefined (reading 'pending_requests_count')


TypeError: Cannot read properties of undefined (reading 'pending_requests_count')
    at b (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1156505)
    at mi (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1457820)
    at Ss (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1471871)
    at jl (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1517656)
    at yc (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1506037)
    at bc (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1505965)
    at mc (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1505828)
    at oc (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1502663)
    at lc (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1503045)
    at Ba (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1444194)


b (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1156505)
mi (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1457820)
Ss (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1471871)
jl (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1517656)
yc (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1506037)
bc (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1505965)
mc (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1505828)
oc (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1502663)
lc (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1503045)
Ba (https://climatejustice.social/packs/js/common-0858d3cbedf1b49dde15.js:2:1444194)
```

### Expected behaviour

Page should be loaded without an error.

### Actual behaviour

Couldn't be loaded.

### Mastodon instance

climatejustice.social

### Mastodon version

Mastodon v4.3.1-stable+ff1

### Browser name and version

Google Chrome Ver. 130.0.6723.117 64bit

### Operating system

Windows 11 Home 23H2

**Comment by b2cc** [comment]
@kenji-m : cj.s had a database maintenance last night around 20:00-22:00 UTC. Does it work for you again now?

**Comment by kenji-m** [comment]
> [@kenji-m](https://github.com/kenji-m) : cj.s had a database maintenance last night around 20:00-22:00 UTC. Does it work for you again now?

It doesn't work. I still have a same issue. But it does work with incognito mode, so I assume there will be something conflict with mastodon web version.

**Comment by b2cc** [comment]
@kenji-m : we've been trying to debug this issue further, since we got a couple of user reports regarding this issue. By now we have identified two error cases.

Please try the following: log out, clear the browser site cache/storage for cj.s and reload the page with CTRL+SHIFT+R to ensure you cleanly reload all the frontend assets. Log in again, it should work now.

If you still have errors with certain timelines (e.g. in the advanced web interface), then:
 - unpin all columns
 - check your user profile and ensure: timezone is not empty, and deactivate "Group boosts" under Settings -> Other
 - Save and go back to the web interface
 - Set up your pinned columns as before
 - re-enable "Group boosts..." again

This should resolve the issue.

**Comment by ClearlyClaire** [comment]
Looking into it, I fail to see a scenario where Mastodon would crash with this traceback. For this to happen, `state.notificationPolicy` would have to be `undefined`, but its initial value is `null`, and the only times the value gets changed is on successful API requests to `/api/v2/notifications/policy`, which should always return a `NotificationPolicy` entity.

The climatejustice.social version string has a custom tag. Is there any local change we should know about?

**Comment by kenji-m** [comment]
@b2cc @ClearlyClaire
After several attempts to clear cache, finally it's back to normal. Thank you for the help!

**Comment by kenji-m** [comment]
@ClearlyClaire 
> That's good to hear! I'm going to close this on the suspicion that it was something specific to climatejustice.social, but I would really like to understand what was going on.

For different issue that probably would be specific to climatejustice.social, I can access to the website only via VPN. I reported this issue to admin of climatejustice.social, but they couldn't find what made it happen. I use VPN anyways, but it would be annoying someone has the same issue.

**Comment by ClearlyClaire** [comment]
>  While communicating with users, we singled out two types of errors:

Those two errors are basically the same, but reported differently by Firefox and Chromium. I *think* it might occur if `/api/v2/notifications/policy` returned an empty or malformed value while not actually returning an error code (which should never happen with Mastodon's codebase).

> Put up a maintenance page and block access to the instances

I am curious how you did that. Is it possible you were replying with a custom response and a 200 status to `/api/v2/notifications/policy` during that time?

**Comment by ClearlyClaire** [comment]
Sidekiq does not handle the API. The web app, API and ActivityPub endpoints are all served by the puma (`mastodon-web`) processes.

Did you redirect to the HTML page regardless of path?

**Comment by b2cc** [comment]
Yes, just checked, we redirected the API reqeests as well - in hindsight that was probably a bad idea :\

**Comment by ClearlyClaire** [comment]
That explains the issue then, thanks!
