### ISSUE TITLE
Top loading bar appears constantly

### ISSUE THREAD

**Issue by rfinnie** [mastodon/mastodon#32862]
### Steps to reproduce the problem

1. Wait on any page for more than a few seconds
2. Observe blue loading bar across top of page

### Expected behaviour

Loading bar only appears as a result of user interaction

### Actual behaviour

Loading bar happens by itself constantly

### Detailed description

This is only happening on Firefox on MacOS; I haven't been able to replicate it on Linux, or on Chrome. From inspecting the network requests, it appears to be coinciding with the `notifications` endpoint. None of the HTTP requests are being blocked or otherwise failing.

https://github.com/user-attachments/assets/f45f9c79-bda1-431c-b612-79fb039dc411

### Mastodon instance

fosstodon.org

### Mastodon version

v4.3.1

### Browser name and version

Firefox 132.0.1

### Operating system

MacOS 15.1

**Comment by renchap** [comment]
If you know how to do it, can you check that there is a working websocket connection to the streaming endpoint in the inspector's network tab?

I suspect it is not working, and this is a result of it as the browser polls for notifications, which (due to a bug) does show a loading bar

**Comment by rfinnie** [comment]
... and of course now I can't replicate it 😆 

Looks "normal" now, with a 101 from `/api/v1/streaming`, and no regular active polling like I was seeing before. (Is it possible in Firefox to trace active WS connections? I only see that it was upgraded from HTTP to WS in the network console.)

But this has been a regular occurrence, but I'm wondering if those are long-lived tabs and there was a previous networking event which broke the WS connection, and the UI didn't try again (or maybe did and gave up, permanently switching to active polling.)
