### ISSUE TITLE
CW appears open in Home timeline and can't be closed

### ISSUE THREAD

**Issue by cadusilva** [mastodon/mastodon#32870]
### Steps to reproduce the problem

1. CW posts aren't configured to automatically open
2. A CW'd post appears opened in the Home timeline either way
3. You can't close it

### Expected behaviour

CW'd post appears closed and can be opened and closed

### Actual behaviour

It appears opened and can't be closed

### Detailed description

It only happens in the **Home** column. When looking at the toot in a page or other column, the button works just fine, and the post isn't automatically open.

If the same toot is open in the Home timeline and in another column (like the user profile column in the example bellow), the CW opens and closes in the other column but not in the Home timeline.

Home timeline:

![Image](https://github.com/user-attachments/assets/c4c343e8-7e30-4e7a-8626-79be0b53b916)

Different columns' behaviour:

![Image](https://github.com/user-attachments/assets/fa1ad9ff-7e84-4726-94cf-16607c1fd311)

### Mastodon instance

bolha.one, ursal.zone

### Mastodon version

v4.4.0-alpha.1-f8e96e7 (bolha.one), v4.4.0-alpha.1-f8e96e7 (ursal.zone)

### Browser name and version

LibreWolf 132.0.1-1, Chromium 130.0.6723.123

### Operating system

Linux Debian 13

**Comment by ClearlyClaire** [comment]
That is fairly surprising, and I've not been able to reproduce it for now. I'll keep investigating, but does it happen with all CWs? Are there errors in the browser's console? Is there anything else that you think might help us reproduce the issue?

**Comment by cadusilva** [comment]
> That is fairly surprising, and I've not been able to reproduce it for now. I'll keep investigating, but does it happen with all CWs? Are there errors in the browser's console? Is there anything else that you think might help us reproduce the issue?

Not all but only a few CW behaves like that. I'll wait for the next occurrence and look at the browser console (forgot that one).

**Comment by ClearlyClaire** [comment]
It would help if we could see all the custom changes without any omission. Though given your description, it is indeed unlikely to be related.

I'm continuing to investigate, but I have not managed to identify or reproduce the issue yet.

**Comment by ClearlyClaire** [comment]
Nevermind, I can reproduce it, it is related to boosts. I know what to look for.

**Comment by ClearlyClaire** [comment]
https://github.com/mastodon/mastodon/pull/32887 should address this. Sorry, this bug was introduced by a recent change of mine.

**Comment by cadusilva** [comment]
No problem, thank you for the fix!
