### ISSUE TITLE
<title> on toots is double quoted

### ISSUE THREAD

**Issue by progval** [mastodon/mastodon#32877]
### Steps to reproduce the problem

1. Go to https://mastodon.social/@ircv3/113476882448853258

### Expected behaviour

The HTML should contain `<title>IRCv3: &quot;We missed doing one of these last year, but here&#39;…&quot; - Mastodon</title>`

### Actual behaviour

The HTML contains `<title>IRCv3: &amp;quot;We missed doing one of these last year, but here&amp;#39;…&amp;quot; - Mastodon</title>`

### Mastodon instance

mastodon.social

### Mastodon version

v4.4.0-nightly.2024-11-13

**Comment by trwnh** [comment]
is this actually an issue? firefox at least seems to render `&amp;quot;` as quotation marks...

**Comment by ClearlyClaire** [comment]
The rendered title in Firefox looks correct. However, there is a discrepancy between the `title` value when the page has fully loaded and the javascript executed, and the server-side-rendered tag. The server-side-rendered tag indeed appears to be incorrect for some reason.

**Comment by ClearlyClaire** [comment]
I think `chomp` could make a string unsafe if you're calling it with an argument, e.g. `.chomp('>')`. Without an argument, I don't think it can make a string unsafe, but maybe I am missing something.

I think doing `content_for(:page_title).to_s.chomp.html_safe` would be safe right now, and is pretty unlikely to be unsafe in the future, but I'm not very comfortable with doing that. Should we have a weird codepath or a weird Rails change making `content_for(:page_title)` return an unescaped unsafe string, we would effectively be bypassing the whole `SafeBuffer` security feature.

**Comment by Gargron** [comment]
Maybe the `chomp` could be avoided?

**Comment by ClearlyClaire** [comment]
Yeah, that sounds like a good solution: any newline there will always be followed by a space character due to the `safe_join` with ` - `, so whitespace should be collapsed according to HTML rules.

**Comment by oneiros** [comment]
> I think doing `content_for(:page_title).to_s.chomp.html_safe` would be safe right now

Interestingly enough, that is how it used to be: https://github.com/mastodon/mastodon/commit/4476a454445281b2468d03c9c6d4d99e52b1a597

The final `.html_safe` got lost when this was extracted to a helper method.

> Should we have a weird codepath or a weird Rails change making `content_for(:page_title)` return an unescaped unsafe string, we would effectively be bypassing the whole `SafeBuffer` security feature.

You are right. It is not `content_for` that is doing the escaping, so there is no guarantee it will always return safe strings. So the only way I can see to do this is check the safety of the returned string, chomp it and only mark the result as safe if the original was. Quite some effort for so tiny a feature 😕 

> Maybe the `chomp` could be avoided?

That would be good. I think it is haml that inserts linefeed characters when `#content_for` is used to capture content, so we would still have them in the HTML that is emitted, but as far as I can see that is valid and browsers deal with it just fine. I do not know if all HTML parsers / consumers of our HTML deal with this as gracefully though. I can easily imagine this breaking for example link previews on other platforms. But this is just hypothetical and would require a bunch of things to go wrong.

FWIW the only way to prevent linefeed characters from being inserted here that I could find is to change all haml templates that do

```haml
- content_for :page_title do
  = t(:key)
```

to this here:

```haml
- content_for(:page_title) { t(:key) }
```

**Comment by ClearlyClaire** [comment]
Note that `- content_for :page_title, t(:key)` should work as well
