### ISSUE TITLE
"Hide with warning" not applying to Boosted content

### ISSUE THREAD

**Issue by vmstan** [mastodon/mastodon#32894]
### Steps to reproduce the problem

After #32887 on `main` filters which only use the "Hide with warning" setting do not filter Boosted content. If the filter is set to hide completely, it is applied. Third party clients (tested Ivory) appear to still filter boosts when in warning only.

### Expected behaviour

Boosts are filtered

### Actual behaviour

Boosts not filtered

### Mastodon instance

vmst.io

### Mastodon version

v4.4.0-alpha.1+766358e

### Browser name and version

Any

### Operating system

Any

**Comment by vmstan** [comment]
@ClearlyClaire FYI

**Comment by vmstan** [comment]
Fixed by #32895

**Comment by ClearlyClaire** [comment]
Reopening because the fix has not been merged yet
