### ISSUE TITLE
“Websites allowed to credit you” field has autocorrect enabled

### ISSUE THREAD

**Issue by daprice** [mastodon/mastodon#32896]
### Steps to reproduce the problem

1. Navigate to Settings > Public Profile > Verification
2. Try to type one or more website addresses into the “Websites allowed to credit you” field

### Expected behaviour

it accepts that you’ve typed a website address

### Actual behaviour

autocorrect changes what you’ve typed to English words, inserts spaces between “words”, and spellcheck gives you a red underline if you type a domain that isn’t an English word (or whatever the browser language is set to)

### Detailed description

Website addresses don’t tend to be spelled correctly or grammatically correct in whatever language someone is browsing in, so autocorrect/autocomplete and spell check are not appropriate here.

I shouldn’t have to carefully decline all of my autocorrect suggestions to avoid having the website address be misspelled.

### Mastodon instance

mastodon.online, mastodon.gamedev.place

### Mastodon version

v4.3.1

### Browser name and version

Safari

### Operating system

iPadOS 18.2b3

### Technical details

This field should probably have `autocorrect=“off”`, `autocomplete=“off”`, `autocapitalize=“none”`, and `spellcheck=“false”`.

Or better yet, instead of one textarea for entering multiple URLs, use multiple `<input type=“url”>` elements so the browser can do the correct thing on its own and also show a more appropriate keyboard.

**Comment by ClearlyClaire** [comment]
https://github.com/mastodon/mastodon/pull/32903 should address this

> Or better yet, instead of one textarea for entering multiple URLs, use multiple `<input type=“url”>` elements so the browser can do the correct thing on its own and also show a more appropriate keyboard.

That sounds like a good idea, can you open a separate suggestion for that?

**Comment by daprice** [comment]
> That sounds like a good idea, can you open a separate suggestion for that?

#32918
