### ISSUE TITLE
Attempting to pull docker images for Mastodon v4.3.x hits dockerhub rate limit

### ISSUE THREAD

**Issue by wolfteeth** [mastodon/mastodon#32961]
### Steps to reproduce the problem

1. git checkout v4.3.1
2. Re-add version line to docker-compose.yml (I'm on an old version of docker-compose, and version is required)
3. docker-compose pull

### Expected behaviour

Docker images are pulled from dockerhub

### Actual behaviour

ERROR: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

### Detailed description

I don't recall ever hitting this before. Every time I've attempted to pull containers for v4.3.x I have hit the dockerhub rate limit. I have tried this days apart, after a server reboot.

I'm not sure if something has changed, behavior-wise, when it comes to Mastodon docker images, or if dockerhub has changed something. According to dockerhub, the rate limit is 100 requests every 6 hours. My VPS is deployed on its own IP address. I have no idea what could be causing dockerhub to think I'm hammering them. Mastodon is the only container-based service I'm running at this IP.

### Mastodon instance

mellified.men

### Mastodon version

v4.2.13

### Environment

Using docker containers to deploy the instance. Earlier upgrades worked.

**Comment by wolfteeth** [comment]
This also seems to have left my mastodon install in a broken state when I reverted back to the old version. Images are no longer loading in the web interface.

**Comment by wolfteeth** [comment]
@renchap Revisiting this today, with an attempt to update to Mastodon v4.3.1 from v4.2.13. At this point both redis and postgres are failing on the rate limits (maybe this is what was getting rate-limited earlier). Is there some workaround for updating these containers?

I'm not able to restart my mastodon containers using the old redis and postgres. It spits out a Python stack trace ending with `KeyError: 'ContainerConfig'`

**Comment by wolfteeth** [comment]
I ended up pulling the images from the AWS ECR repo and had to delete the containers and recreate them anyway (upgraded the version of docker to better handle this update).

**Comment by gurubert** [comment]
You need to update docker-compose. Version 1 is deprecated.

Replace calls to docker-compose with "docker compose".
