### ISSUE TITLE
1080x1920 video displayed as 1920x1080 on Mastodon Web

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#33006]
### Steps to reproduce the problem

Last night I made this post:

https://mastodon.social/@mcc/113514552341290968

It features a video made in portrait mode with my phone. The video is "1080p sideways", 1080x1920.

### Actual behaviour

mastodon.social is displaying the video with a 1080p aspect ratio, in other words, 1920x1080. To do this, it crops the video down vertically, so that only a slice at the bottom of the video can be seen.

### Expected behaviour

Because I am allowed to post 1080x1920 *images* without issue and they appear at their full height, I expect it would appear at its full height in the Mastodon feed. If for some policy reason it must be cropped, I expect I should be allowed to place a "focus point" (it seems you can't do this with videos).

### Detailed description

* The problem occurs in both Advanced and "regular" mode. 
* The problem here is the CSS and not the-video-as-stored-on-mastodon's-server. I know this for four reasons: Because [url=https://mastodon.social/@leona/113514663103374885]leon looked at the inspector[/url] and found a "aspect-ratio: 1920 / 1080" in the css; because if you click fullscreen, it appears correctly; because in the "edit"/add alt text pane it appears more or less correctly (oversized and with a aspect ratio something like 3:4, but I am able to scroll it); and because the video appears correctly in Tusky.

### Mastodon instance

mastodon.social

### Mastodon version

v4.4.0-nightly.2024-11-19

### Browser name and version

Firefox 130.0.1

### Operating system

Ubuntu 24.04.1 LTS

### Technical details

The video was taken on a Sony XPeria 5 III running Android 13, and not processed.

If I download the image locally and feed it into ffmpeg -i, I find something interesting for the video track:

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '522354ab61852ad8.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf61.7.100
  Duration: 00:00:15.92, start: 0.000000, bitrate: 17660 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080, 17497 kb/s, 29.96 fps, 29.97 tbr, 90k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
    Side data:
      displaymatrix: rotation of -90.00 degrees
```

Notice that the video internally advertises a size of 1920x1080, with a "rotation of -90 degrees". I understand this to be a common approach for videos and images taken with cell phones. It looks to me as if the "bug" is that although Mastodon's video converter understands the "1080p plus -90 rotation", and the browser understands it as well, whatever is storing the metadata that eventually leads to the CSS aspect-ratio is extracting only the "base" resolution and not the appropriate transformation which would have changed it from 1920x1080 to 1080x1920.

**Comment by mcclure** [comment]
I did not press send on that. I don't know why it posted. Hold on still writing

**Comment by Gargron** [comment]
Mastodon extracts the dimensions of the video through ffmpeg and saves it in the `meta` blob. This is then used to set the appropriate aspect ratio on the video player. This rotation data is not saved to the `meta` blob. Normally, if ffmpeg re-encodes the video, it applies the rotation so it's irrelevant. But if the original video codecs match our target codecs, we save work by not re-encoding the video entirely. This is probably what's happening with this specific video. Most likely, what we need is to extract the rotation from the video and manually apply it to the extracted dimensions to simulate re-encoding.
