### ISSUE TITLE
Increase cap on displayed and attached image/media to above 4

### ISSUE THREAD

**Issue by craigS89** [mastodon/mastodon#33034]
### Pitch

I feel it is worth considering raising the number of images Mastodon will display on posts to more than just four.

The does not mean mastodon itself would need to change the 4 image /attachment upload cap on its own service (though i would personally like to see that too) but it would mean other Activitypub services like Pixelfed, Wordpress blogs, GoToSocail etc. would be displayed closer to how they are intended.

### Motivation

With many wordpress blogs which host many images now becoming fediverse connected, and other Activitypub services like pixelfed and GoToSocial allowing for between 6 to 10 images attached to posts, it would allow for greater fediverse coheasion if mastodon would allow for these posts to be displayed as intended and show all images with the post and not just the first 4.

**Comment by mjankowski** [comment]
Related https://github.com/mastodon/mastodon/pull/29562
