### ISSUE TITLE
DeepL translates two opposite definitions with same expression

### ISSUE THREAD

**Issue by PimpOfSune** [mastodon/mastodon#33070]
### Steps to reproduce the problem

RU>EN: "самое свежее" is translated as "freshest" and "самое несвежее" is translated as "freshest" under specific circumstances. These are opposite of each other.

### Expected behaviour

"самое несвежее" is translated as "stale" or similarly clear definition of "unfresh"

### Actual behaviour

"самое несвежее" is translated as "freshest" - but only sometimes, under specific circumstances

### Detailed description

Account's preferred language & default translation's target language: English
Post language: Russian
Post content: https://mastodon.social/@DrinkFromTheCup/113544027855354076
(can't make a proper copypaste-friendly quote in modern GitHub UI, sorry)
Try Translate'ing it into English.
![Image](https://github.com/user-attachments/assets/7545020b-c988-44c5-928d-1ba39d63d55f)

SOMEHOW, translator gets its marbles together if I only use this specific quote to make a post:
`К одной биолабе от вагонов идут манипуляторы с приоритетом "самое свежее". К другой "самое несвежее".`
![Image](https://github.com/user-attachments/assets/8637a564-d9f2-4f79-b9f6-35c9344e1a77)

It... aint quite right.

### Mastodon instance

mastodon.social

### Mastodon version

v4.4.0-nightly.2024-11-23

**Comment by vmstan** [comment]
Unfortunately this isn't something within the control of Mastodon, but DeepL itself. Some languages it does better than others in different contexts. We have LibreTranslate as an alternative for partly this reason. I would encourage you to provide this feedback to DeepL and see if they can improve their models.
