### ISSUE TITLE
Character limit indicator in new user form

### ISSUE THREAD

**Issue by ronilaukkarinen** [mastodon/mastodon#33093]
### Pitch

Right now there is no indication of the character limit in this form:

![Image](https://github.com/user-attachments/assets/dda2003b-7364-4ce3-9717-54b2a11c036a)

### Motivation

A new user tried to register and wrote a 700 character essay about why they would join only to realize there is a limit and lost the message... This should have some indicator about how long the application can be.

**Comment by mjankowski** [comment]
Related https://github.com/mastodon/mastodon/issues/31863#issuecomment-2502199815
