### ISSUE TITLE
Aggressive new tab opening when scroll-clicking in Mastodon suddenly

### ISSUE THREAD

**Issue by mcclure** [mastodon/mastodon#33100]
### Steps to reproduce the problem

I have a laptop and a Windows PC with a mouse. When I use the mouse, because of my RSI I scroll by clicking down the middle mouse button to enter <img src="https://github.com/user-attachments/assets/eec01268-15dc-479a-9443-de25bde7dcdf" width=24> scroll mode. Unfortunately click with middle mouse also is the verb in a web browser for "open new link".

I just spent a month (oct 27 - nov 27) traveling during which time I used only my laptop. When I came back I noticed a slight difference in Mastodon's Advanced Interface. I think something changed. Now if I click almost anywhere to scroll, it opens a new mastodon tab. Since scroll is a frequent action, this means as I use Mastodon many clone tabs pile up unless I am very careful to click on the margins of posts.

I see this in both Firefox and Chrome so I think the change must have been in Mastodon.

### Expected behaviour

Scroll

### Actual behaviour

New Window

### Detailed description

It might be this is just a byproduct of improvements on the "click to focus on this post" hitboxes in Advanced Mode and there is nothing you can do about this, but I haven't seen this behavior before today.

### Mastodon instance

mastodon.social

### Mastodon version

v4.4.0-nightly.2024-11-27

### Browser name and version

Chrome 131.0.6778.86 64bit

### Operating system

Windows 10

**Comment by Gargron** [comment]
Someone requested that you should be able to middle click a post to open it in a new tab, because Twitter and Bluesky have that behavior. I’m a bit at a loss, is there a programmatic way to tell this click to scroll even from a middle mouse click on a link?

**Comment by mcclure** [comment]
Yes, I don't know if this is something you have control over or if it's all in the browser.

It turns out Firefox has an about:config to disable middle-click-for-new-tab completely browserwide. Maybe I will just use that…

**Comment by ClearlyClaire** [comment]
> It turns out Firefox has an about:config to disable middle-click-for-new-tab completely browserwide. Maybe I will just use that…

This is unlikely to help as we are doing it in Javascript, and not through a `link` element (because a post can itself include links).

I'm not sure what's the best way to proceed here.

**Comment by ClearlyClaire** [comment]
Note: I'm able to reproduce the issue on Firefox on Linux by enabling “Automatic Scrolling”. I don't know if it's completely equivalent to the feature being discussed, but it allows scrolling when middle-clicking as well as when holding the middle button.

On normal links, middle-clicking will still open the link in a new tab rather than initiate scroll.
When middle-clicking on a status, it will both open a new tab and initiate the “automatic scrolling” mode.

It looks like we can use `event.detail` (https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/detail) and it will be 0 in this case and 1 otherwise. Gonna try that.

**Comment by ClearlyClaire** [comment]
Note that I have confirmed the PR to fix the issue on Firefox/Linux, but I don't know whether this will fix the issue on your setup too. Let us know.

**Comment by mcclure** [comment]
That's great, I appreciate it. If I am going to test, on what version of m.s (for example currently I see a version of `v4.4.0-nightly.2024-11-27`) should I expect the PR to appear?

**Comment by ClearlyClaire** [comment]
`v4.4.0-nightly.2024-11-27` does not include it, and neither does `v4.4.0-nightly.2024-11-29`. Anything else that we might deploy should contain it. This will probably happen on Monday.
