### ISSUE TITLE
Character limit hidden when user asked why they want to join server

### ISSUE THREAD

**Issue by FediVideos** [mastodon/mastodon#33160]
### Steps to reproduce the problem

1. Attempt to sign up on a server which asks why you want to join
2. Write a very long reason
3. The reason is rejected for being too long
...

### Expected behaviour

It should either prevent writing more than the limit, or mention the limit prominently

### Actual behaviour

There's nothing to indicate a limit, and it doesn't stop people going over the limit until they submit it

### Detailed description

Several users got in touch via FediTips that they had written a long reason for joining why which was rejected for being too long. One of them then wrote a shorter reason but this was rejected by the instance admin for being too short (the admin may not have been aware of the limit).

It would be clearer for users and admins if people signing up were told about the limit and/or prevented from writing over the limit.

### Mastodon instance

Any instance requiring giving a reason when signing up

### Mastodon version

v4.3.2

### Browser name and version

Firefox

### Operating system

Linux Mint

**Comment by mjankowski** [comment]
Similar https://github.com/mastodon/mastodon/issues/33093
