### ISSUE TITLE
Feature Request: Moderation/Administration Feed

### ISSUE THREAD

**Issue by ErikLentz** [mastodon/mastodon#33165]
### Pitch

A separate feed view, directly available in the main Mastodon UI, that shows

* Reports
* Accounts pending sign-up approval
* Trending Posts, Links, and Hashtags awaiting approval

It could be launched via the hamburger menu, or show up on the top notification bar like instance announcements.

### Motivation

At present, Mastodon moderators and admins can only become aware of reports, sign-up approvals, or trending items via separate screens under Settings, or via email notifications. Mastodon moderators and admins cannot receive notifications about these events from the main Mastodon UI! As an admin, I can be reading Mastodon for hours without ever knowing about a pending sign-up needing approval or user report. A Mastodon admin shouldn't need to keep an email client open to be notified of their instance's needs.

**Comment by ThisIsMissEm** [comment]
We do have notifications for new reports and new users...

![Image](https://github.com/user-attachments/assets/4cbeec58-b4b8-4d2f-99f0-676ae1a5d8aa)
