### ISSUE TITLE
New embed sometimes needs a scrollbar even for short statuses

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#33167]
### Steps to reproduce the problem

1. Copy the embed code for a status with an image attachment (?)
2. Paste the embed code into an HTML file

### Expected behaviour

iframe is sized to not need a scrollbar? (421px tall)

### Actual behaviour

iframe is slightly too small (418px tall)

### Detailed description

![Image](https://github.com/user-attachments/assets/359838f7-e4bd-4020-b913-c392f1d16112)

### Technical details

mastodon.social v4.4.0-nightly.2024-12-02
Chromium v130.0.6723.58

**Comment by ClearlyClaire** [comment]
I am unable to reproduce the issue, but I wouldn't be too surprised if the resize event sometimes were triggered before everything was laid out correctly by the browser.

It seems we call `window.requestAnimationFrame` to handle that, but I'm not sure it would be 100% reliable, and importantly, there is one code path where it is not called.

**Comment by ClearlyClaire** [comment]
Is that something you can reproduce consistently? If so, what browser are you using? Anything else worth noting?

**Comment by ClearlyClaire** [comment]
Hm, Chromium 131 does show me a scrollbar on the iframe, but that scrollbar has no thumb. So I'm not sure why it is even showing. 

When trying an embed for the specific post above, the `iframe` has `height="415"` while the computed inner document's height is `414.766px`… so I don't get the values you do.

Playing with the `iframe`'s size, its current height (415) is the lowest one that does not result in the scrollbar having a thumb, while the scrollbar itself disappears at 422px of height. I do not understand why this happens.
