### ISSUE TITLE
Automatic visibility restriction of posts by age

### ISSUE THREAD

**Issue by pelzvieh** [mastodon/mastodon#33213]
### Pitch

There's an Automated Post Deletion feature in Mastodon 4.3 with an impressive set of criteria to configure, which posts will be handled or exempted from the automatism.
However, the only result available is deletion.
I'd like not to have my posts deleted, but to restrict their visibility. E. g. I'd like to have all my posts older than one year to be follower-only if they were posted as public or quiet public. Obviously in this example, posts with original visibility "specific people" should not be upgraded to "followers", but remain "specific people".
The exemption features of current "Automatic post deletion" seem appropriate here as well - e. g. I'd like to keep my sticky posts as public as they are.

### Motivation

I'd like to contribute to some current public discussions in public visibility. However, in the course of time, the context of such contributions might get lost, and I will forget about most contributions I did. That's why I do not want the anonymous public to read most of the public posts I posted earlier.
Nonetheless I still want the account directly mentioned then, to still see the communication we had, therefore not to delete posts altogether.

**Comment by renchap** [comment]
Closing as it is not supported (and iirc not possible in ActivityPub) to change the audience/visibility of a post without recreating it.
