### ISSUE TITLE
unknown type of jsonb container (PG::InternalError)

### ISSUE THREAD

**Issue by sthaydn** [mastodon/mastodon#33232]
### Steps to reproduce the problem

Hi there,

I am trying to do some maintenance stuff from the command line, but I get the message in the title soon after running a command.

1. tootctl media remove-orphans, for example
2. The output is:
.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:911:in `exec_prepared': PG::InternalError: ERROR:  unknown type of jsonb container (ActiveRecord::StatementInvalid)

### Expected behaviour

Running the maintenance tasks without error

### Actual behaviour

getting the error in the title

### Detailed description

Postgres Version (15)  is the latest on Debian 12.

### Mastodon instance

mainburg.hallertau.social

### Mastodon version

v4.3.2

### Environment

Please at least include those informations:
- Operating system: Debian 12
- Ruby version: v3.3.5
- Node.js version: 22.12.0

**Comment by mjankowski** [comment]
Was this previously working and then just suddenly stopped out of nowhere? Or was there an upgrade of something prior to the issue  showing up?

**Comment by sthaydn** [comment]
I have done it weeks ago until yesterday without errors. It even worked yesterday once, but since then I always get this error with every maintenance tootctl command I use.

**Comment by sthaydn** [comment]
This is the whole output after RAILS_ENV=production /home/mastodon/live/bin/tootctl media remove-orphans:

`
I, [2024-12-10T11:25:47.158342 #423537]  INFO -- : [dotenv] Loaded .env.production
/home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:911:in `exec_prepared': PG::InternalError: FEHLER:  unknown type of jsonb container (ActiveRecord::StatementInvalid)
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:911:in `block (2 levels) in exec_cache'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:1142:in `log'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:910:in `block in exec_cache'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:1027:in `block in with_raw_connection'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:999:in `with_raw_connection'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:906:in `exec_cache'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:874:in `execute_and_clear'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:64:in `internal_exec_query'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:630:in `select'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:71:in `select_all'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/query_cache.rb:115:in `select_all'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/querying.rb:62:in `_query_by_sql'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/querying.rb:51:in `find_by_sql'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/statement_cache.rb:150:in `execute'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/core.rb:431:in `cached_find_by'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/core.rb:300:in `find_by'
	from /home/mastodon/live/lib/mastodon/cli/media.rb:182:in `block in remove_orphans'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/find.rb:51:in `block (2 levels) in find'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/find.rb:50:in `catch'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/find.rb:50:in `block in find'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/find.rb:45:in `each'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/find.rb:45:in `find'
	from /home/mastodon/live/lib/mastodon/cli/media.rb:162:in `remove_orphans'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:116:in `invoke'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:338:in `block in subcommand'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
	from /home/mastodon/live/bin/tootctl:9:in `block in <main>'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/chewy-7.6.0/lib/chewy/strategy.rb:60:in `wrap'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/chewy-7.6.0/lib/chewy.rb:151:in `strategy'
	from /home/mastodon/live/bin/tootctl:8:in `<main>'
/home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:911:in `exec_prepared': FEHLER:  unknown type of jsonb container (PG::InternalError)
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:911:in `block (2 levels) in exec_cache'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:1142:in `log'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:910:in `block in exec_cache'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:1027:in `block in with_raw_connection'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:999:in `with_raw_connection'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:906:in `exec_cache'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:874:in `execute_and_clear'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:64:in `internal_exec_query'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:630:in `select'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:71:in `select_all'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/query_cache.rb:115:in `select_all'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/querying.rb:62:in `_query_by_sql'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/querying.rb:51:in `find_by_sql'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/statement_cache.rb:150:in `execute'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/core.rb:431:in `cached_find_by'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/core.rb:300:in `find_by'
	from /home/mastodon/live/lib/mastodon/cli/media.rb:182:in `block in remove_orphans'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/find.rb:51:in `block (2 levels) in find'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/find.rb:50:in `catch'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/find.rb:50:in `block in find'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/find.rb:45:in `each'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/find.rb:45:in `find'
	from /home/mastodon/live/lib/mastodon/cli/media.rb:162:in `remove_orphans'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:116:in `invoke'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:338:in `block in subcommand'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
	from /home/mastodon/live/bin/tootctl:9:in `block in <main>'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/chewy-7.6.0/lib/chewy/strategy.rb:60:in `wrap'
	from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/chewy-7.6.0/lib/chewy.rb:151:in `strategy'
	from /home/mastodon/live/bin/tootctl:8:in `<main>'
`

**Comment by ClearlyClaire** [comment]
Thanks!

Can you apply the following patch and try again?
```patch
diff --git a/lib/mastodon/cli/media.rb b/lib/mastodon/cli/media.rb
index 70c11ee1a1..b3721b060e 100644
--- a/lib/mastodon/cli/media.rb
+++ b/lib/mastodon/cli/media.rb
@@ -205,6 +205,9 @@ module Mastodon::CLI
           rescue => e
             progress.log(pastel.red("Error processing #{key}: #{e}"))
           end
+        rescue ActiveRecord::StatementInvalid
+          progress.log(pastel.red("Error processing #{path} (#{model_name} / #{record_id})"))
+          raise
         end
       end
 
```

**Comment by ClearlyClaire** [comment]
What happens if you do the following in a Rails console? (`RAILS_ENV=production bundle exec rails c`)

```ruby
Account.find(109303583135211577)
```

**Comment by sthaydn** [comment]
This is the whole output:

`(irb):1:in `<main>': PG::InternalError: FEHLER:  unexpected jsonb type as object key (ActiveRecord::StatementInvalid)
/home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:911:in `exec_prepared': FEHLER:  unexpected jsonb type as object key (PG::InternalError)
        from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:911:in `block (2 levels) in exec_cache'
        from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
        from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:1142:in `log'
        from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:910:in `block in exec_cache'
        from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:1027:in `block in with_raw_connection'
        from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.1.4.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
        from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:999:in `with_raw_connection'
        from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:906:in `exec_cache'
        from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:874:in `execute_and_clear'
        from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:64:in `internal_exec_query'
        from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:630:in `select'
        from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:71:in `select_all'
        from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract/query_cache.rb:115:in `select_all'
        from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/querying.rb:62:in `_query_by_sql'
        from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/querying.rb:51:in `find_by_sql'
        from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/statement_cache.rb:150:in `execute'
        ... 34 levels...
`

**Comment by ClearlyClaire** [comment]
Can you run the following in PostgreSQL?

```sql
SELECT fields FROM accounts WHERE id = 109303583135211577;
```

**Comment by sthaydn** [comment]
The output is:
ERROR: unknown type of jsonb container

**Comment by mjankowski** [comment]
Is there anything at all interesting/custom/etc about the postgres install here (how it was built/installed, where its hosted) ... or is it just a stock version 15 PG db server?

**Comment by sthaydn** [comment]
It is the standard installation from the Mastodon docs with upgrade to PS13 and PS15, but that was like a year ago.

**Comment by sthaydn** [comment]
Ok, I felt brave and just deleted the file in the cache mentioned above (Error processing /home/mastodon/live/public/system/cache/accounts/avatars/109/303/583/135/211/577/original/9cd6b2398ffdda06.png). 

Now tootctl media remove-orphans is at 42000 and counting...it stopped before at around 2300. 55000...70000... 90000...Found and removed orphan: cache/accounts/avatars... about 30 files so far...120000...150000... about 40 files... 240000 and about 60 files...310000... now in cache/custom_emojis...now in cache/media_attachments...exciting! Fingers crossed... 360000...cache/preview_cards....come on!

Ok, it took 25 minutes and removed 238 orphans (36.5 MB). Thanks for sticking with me. :-)

tootctl statuses remove --days=7...OK!
tootctl media remove: Removed 1913 media attachments (approx. 3.78 GB)

It seems it is working again!

9cd6b2398ffdda06.png owns us some beers (or whatever you guys like) I guess! :-)

Thanks @mjankowski and @ClearlyClaire for taking care.

**Comment by ClearlyClaire** [comment]
There is still something very weird going on with your database. There's an already-stored account which cannot be loaded. This is likely to cause you more issues.

Unfortunately, I have no idea what may be happening here.

**Comment by sthaydn** [comment]
I will have a look. Maybe there is some postgres maintenance I can do.

**Comment by cdhagmann** [comment]
This is an issue I am having upgrading my app to using PG 17 (which brought me here looking for a solution). I would confirm your PG version.

**Comment by ClearlyClaire** [comment]
> This is an issue I am having upgrading my app to using PG 17 (which brought me here looking for a solution). I would confirm your PG version.

Hi! Just to clarify, is that something you encountered with Mastodon, or with some other piece of software?

**Comment by cdhagmann** [comment]
Another piece of software. The `pg` gem (or maybe the adapter for AR) does not seem to know how to work with JSONB  on PostgeSQL17. If the OP accidentally has PG 17 as their DB they would get that error.

**Comment by ClearlyClaire** [comment]
This seems to be something within PostgreSQL itself, not necessarily related to ActiveRecord. Indeed, if you look at https://github.com/mastodon/mastodon/issues/33232#issuecomment-2536376914, pure SQL fails. I wonder if it's a somewhat widespread PG bug?
