### ISSUE TITLE
The Explore Tab is Empty

### ISSUE THREAD

**Issue by freqq68** [mastodon/mastodon#33309]
### Steps to reproduce the problem

1. we go to the /explore page
2.
3.
...

### Expected behaviour

showing some posts of the federated network

### Actual behaviour

nothing is showing

### Detailed description

Hello Dear,

We are a small server (https://fedidb.org/network/instance/social.roadfm.fr) but when we go to the /explore page, nothing is showing. And we don't understand why. 

![Image](https://github.com/user-attachments/assets/9da97989-0808-4c85-b5ab-556849afafcf)

If we can get help, it will be apreciated.
Many thanks

### Mastodon instance

social.roadfm.fr

### Mastodon version

v4.3.2

### Browser name and version

Edge latest

### Operating system

Windows 11 23h2

**Comment by ClearlyClaire** [comment]
Trends are computed locally and are based on locally-known activity, such as boosts or local favourites.

Furthermore, trending items can require moderation review before being allowed, depending on the settings in <https://social.roadfm.fr/admin/settings/discovery>. When trends are available for review, they show up in <https://social.roadfm.fr/admin/trends/statuses> and neighbouring pages.

Finally, not all posts can trend. Only public posts from people who have opted into “Feature profile and posts in discovery algorithms” (https://social.roadfm.fr/settings/privacy) can trend.

**Comment by freqq68** [comment]
Hello @ClearlyClaire 

Thanks for taking the time to reply. 

It's all checked ✔️🤣

Now I know how it's work. They need more activity of local user interact w outside of the federated network. 

But why they don't discover other toots from other network that have checked : yes I want to be discoverable etc...? 

Thanks

**Comment by ClearlyClaire** [comment]
The numbers being used to determine activity/popularity are those computed on your own server (so from interactions your server actually knows of), because it's otherwise easy to fake.

This does mean that you need some level of activity for the trends to fill up.

Also, thinking about it, one thing you could check is the status of `trends_refresh_scheduler` in https://social.roadfm.fr/sidekiq/recurring-jobs: is it running like it should?

**Comment by freqq68** [comment]
> The numbers being used to determine activity/popularity are those computed on your own server (so from interactions your server actually knows of), because it's otherwise easy to fake.
> 
> This does mean that you need some level of activity for the trends to fill up.
> 
> Also, thinking about it, one thing you could check is the status of `trends_refresh_scheduler` in https://social.roadfm.fr/sidekiq/recurring-jobs: is it running like it should?

In sidekiq there is no problem for now 

I attached you some screenshots ![Uploading 396507929...] ![image](https://github.com/user-attachments/assets/31f7e126-c5f8-4d65-b625-16e3eeb7c3bb)
