### ISSUE TITLE
M.S / M.O donation prompt

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#33333]
### Pitch

![Image](https://github.com/user-attachments/assets/420f8889-3212-4e2a-bd99-91e34fe790f7)

Have a fundraiser popup twice a year at least.. attach the event to a major fundraiser supported by the core team and included on the official webpages.

+ Write a press release for the tech media to promote the official fundraiser.

### Motivation

Get that bag.

**Comment by shleeable** [comment]
I'd have $2 a month subscription ($24/year).

**Comment by renchap** [comment]
We have something similar in the official mobile apps (for m.s and m.o), but nothing for the web at the moment. This requires some work as we need to have a web widget to accept those donations. 

It is planned to add this to the web, under a configuration flag so we can enable it only on m.o & m.s. We have lot of ideas around this topic, including some that would allow server admins (and maybe client developers) to also benefit from those donations, but this is a complex topic.

I am closing this issue as we have internal ones related to this, but be assured that this is on our radar.
