### ISSUE TITLE
Featured hashtag last used date is incorrect for remote users

### ISSUE THREAD

**Issue by daprice** [mastodon/mastodon#33357]
### Steps to reproduce the problem

1. Load `/api/v1/accounts/[id]/featured_hashtags` with the ID of a remote user

### Expected behaviour

`last_status_at` should show the date of the most recent post from this user using that hashtag that is either public or viewable to the person making the query

### Actual behaviour

`last_status_at` shows a long ago date for a hashtag with recent public posts. I think `statuses_count` is also incorrect. I also found at least one example (possibly specific to the web UI) where a future date is displayed as the last usage date of a featured hashtag, even though the user’s posts are all dated correctly.

### Detailed description

I’ve seen this frequently on multiple servers where it will either give a long ago date or even say “no posts” for a featured hashtag that someone uses very frequently. I can see the user’s posts just fine from the affected server so it’s not an issue of the posts not federating. When looking at my own featured hashtags on my own server, or looking at local users’ featured hashtags, the date appears to be correct, only remote accounts seem to be affected.

For example, https://mastodon.social/api/v1/accounts/109281825849025262/featured_tags should be the featured tags of my own mastodon.online account, viewed from mastodon.social. The `last_status_at` for the swiftui hashtag is `2024-02-19`, almost a year ago, but I’ve posted about it several times since then, including in the last few days.

Possibly related to #22665 where someone saw the `last_status_at` date getting updated correctly but not the `statuses_count`. In my case, the `last_status_at` is also incorrect.

### Mastodon instance

mastodon.social, mastodon.online, mastodon.gamedev.place

### Mastodon version

v4.4.0-nightly.2024-12-18, v4.3.2

**Comment by daprice** [comment]
A weirder example:
Here’s the profile of a mastodon.social user viewed on mastodon.social showing a post from Dec 18 with the pixelart hashtag. The featured pixelart hashtag in the sidebar shows 1k posts with a last used date of Dec 17 (so one day behind, but at least close).

<img width="952" alt="Image" src="https://github.com/user-attachments/assets/3040c970-1f9c-4313-828e-399e6e4f4920" />

But then here’s the same profile viewed on mastodon.gamedev.place (currently v4.3.2). This time the featured pixelart hashtag only says 233 posts, but with a last used date of Dec 31. It’s currently Dec 18. Dec 31 hasn’t happened yet.

<img width="915" alt="Image" src="https://github.com/user-attachments/assets/ad60686e-a9a2-43be-815d-627696dab250" />

**Comment by ClearlyClaire** [comment]
Thanks for the report!

What's happening is that featured tags for local accounts are updated at the time a post is posted, edited or deleted, through `ProcessHashtagsService` and `RemoveStatusService`.

However, the same thing is not happening for remote accounts, for which featured hashtags stats are computed on first discovery, and when a post is deleted, but not when a new post comes in.

> But then here’s the same profile viewed on mastodon.gamedev.place (currently v4.3.2). This time the featured pixelart hashtag only says 233 posts, but with a last used date of Dec 31. It’s currently Dec 18. Dec 31 hasn’t happened yet

Looking at the API results, those dates are not for 2024, but for 2023. So this is an issue with the way dates are displayed being misleading.
