### ISSUE TITLE
Proposal: Integrate assets into docker image

### ISSUE THREAD

**Issue by Naouak** [mastodon/mastodon#3436]
v1.4.1 introduces an issue with assets precompiling making it complicated to build webpack assets on certain instances. Unfortunately, currently the only way to workaround this issue is to build on another machine assets and copy the files to the packs directory.

Wouldn't it be easier to directly integrates packs into the docker image (instead of a volume) and build the webpack assets when building the docker image? 

It would permit building your assets on another machine and then publish your image through a custom repository (or directly through docker default image repo). It would also make installation a bit easier for new instance owners.

**Comment by Gargron** [comment]
This is true, but would require rebuilding the image if you change assets. If that's an acceptable tradeoff for most, I'll make it so

**Comment by tlemarchand** [comment]
I'd like to add something on this issue; while I think it's a really good tradeoff, it's also a Docker best practice to include everything needed.
You should not have to "git pull" the repository for assets or repackage them, Docker images are meant to simplify deployments in a KISS way.
While we are on the matter, we should have 3 mastodon docker images, not one ( one for each service ). It would help greatly building process, security management and keep size in check.
If I have some time and if you are interested, I'll work with @maur1th on this.

**Comment by Gargron** [comment]
>This is true, but would require rebuilding the image if you change assets. If that's an acceptable tradeoff for most, I'll make it so

Another point is that if you have a monolithic Docker image without a volume for the assets, you can't point nginx to the assets directly, meaning they have to go through the Rails/Puma stack which is inherently less performant.

**Comment by pierreozoux** [comment]
@rtucker could you PR your change to include assets in the docker image, it would indeed be a great addition!

https://github.com/vulpineclub/mastodon/blob/master/Dockerfile#L92

In https://github.com/tootsuite/mastodon/issues/6905#issuecomment-376199456 you mention your nginx setup, can you also detail, I'm interested.
I'm actually wondering if it wouldn't make sense to just bake an nginx docker image with the assets, and the right configuration.

It would also ease https://github.com/tootsuite/mastodon/issues/6511

**Comment by pierreozoux** [comment]
@rtucker could you PR your change to include assets in the docker image, it would indeed be a great addition!

https://github.com/vulpineclub/mastodon/blob/master/Dockerfile#L92

In https://github.com/tootsuite/mastodon/issues/6905#issuecomment-376199456 you mention your nginx setup, can you also detail, I'm interested.
I'm actually wondering if it wouldn't make sense to just bake an nginx docker image with the assets, and the right configuration.

It would also ease https://github.com/tootsuite/mastodon/issues/6511
