### ISSUE TITLE
Lost some statuses when I see someone's timeline again

### ISSUE THREAD

**Issue by unarist** [mastodon/mastodon#3473]
1. Bob opens Alice's timeline (e.g. /web/accounts/1), and back to other page (e.g. /web/getting-started)
2. Alice posts more than 20 toots. (e.g. 30 toots)
3. Bob opens Alice's timeline again.
4. Bob can see 20 toots from step 2, and other toots from step 1. He cannot see 10 toots from step 2 unless he reloads the whole page.

Our web client requests with `since_id` on step 3, and the server returns *newer* 20 toots since specified id. Also we don't have a way to load with `max_id=xxx&since_id=yyy`.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Is the solution here this?:

When since_id is set, instead of zrevrange, do zrange, and treat since_id like max_id. Then reverse the order of the returned items during output.

Does that make sense?

**Comment by Gargron** [comment]
I think that would return 20 items starting from where you left off, and you'd be able to paginate iteratively to the most recent content.

**Comment by unarist** [comment]
Hmm, but probably I want to see most recent toots when I open account timeline again rather than older ones. This is same as other services, like Twitter.

So I'm thinking now...

- Replace whole timeline (i.e. drop timeline cache), or
- Insert "Load more" button in between recent toots and previous fetched toots

**Comment by unarist** [comment]
I found same issue on Local/Federated timeline. We disconnect WebSocket for those timeline while it's unmounted (except home/notifications), so only statuses before unmount will be shown on next mounting.

This may confuses v1.3 users because we had never disconnected in that version (due to #2271).
