### ISSUE TITLE
Midori 0.5.11 (Fedora/Linux) : no user interface

### ISSUE THREAD

**Issue by Shnoulle** [mastodon/mastodon#3534]
With Midori : a javascript broke all interface usage after connection. Other page seems OK.

Javascript error : `Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'"`
With console, i see this error
```
Error
column: 12123
line: 1
message: "Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".↵"
sourceURL: "https://m.sl-network.fr/packs/base_polyfills-6efe23b62b83d8a7dc3b.js"
stack: "Function@[native code]↵https://m.sl-network.fr/packs/base_polyfills-6efe23b62b83d8a7dc3b.js:1:12123↵e@https://m.sl-network.fr/packs/common-8e139fced5f5d5323f03.js:1:105↵https://m.sl-network.fr/packs/base_polyfills-6efe23b62b83d8a7dc3b.js:1:13838↵e@https://m.sl-network.fr/packs/common-8e139fced5f5d5323f03.js:1:105↵https://m.sl-network.fr/packs/base_polyfills-6efe23b62b83d8a7dc3b.js:1:1118↵e@https://m.sl-network.fr/packs/common-8e139fced5f5d5323f03.js:1:105↵e@[native code]↵PromiseResolutionHandlerFunction@[native code]"
__proto__: Error
```

The server is on 1.4.1. Not related to issue https://github.com/tootsuite/mastodon/issues/1904 because it's OK with Opera.

![capture du 2017-06-03 15-58-46](https://cloud.githubusercontent.com/assets/1439428/26754201/28f1fa0c-4876-11e7-84a4-d128b1f4815c.png)
![capture du 2017-06-03 16-03-30](https://cloud.githubusercontent.com/assets/1439428/26754206/51368230-4876-11e7-8d89-b08febefb93b.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [1.4.1](https://github.com/tootsuite/mastodon/releases) and not on `master`

**Comment by Gargron** [comment]
Check correctness of CSP headers. They're finnicky and I do not officially recommend using them because they're most likely wrong in some way.

**Comment by Shnoulle** [comment]
Due to the way the admin setup is instance ? Or related to mastodon ?

**Comment by trwnh** [comment]
closing as stale. if it can be reproduced, please file a new issue.
