### ISSUE TITLE
Make sure Message has not been deleted when clicking on Reply button

### ISSUE THREAD

**Issue by fracolo** [mastodon/mastodon#3638]
Experimented on 1.4.1 version release 

Made a response to a message which was appearing on the "notifications" column. 
A 404 error occured when trying to submit the response message.
After having refreshed the main page, I've noticed that the message I was replying to has been deleted.
A way to prevent this experience to happen again could be to make sure when the reply button is clicked that the message still exists.

**Comment by mjankowski** [comment]
This has since been improved to better handle the error state.
