### ISSUE TITLE
add option to "Federated timeline" that excludes "Local timeline" content

### ISSUE THREAD

**Issue by cphuntington97** [mastodon/mastodon#3663]
Since it is now possible to view both the "Local timeline" and "Federated timeline" simultaneously, I would like the "Federated timeline" to have an option to exclude "Local timeline" content -- an "all content except for local content" option.

If there is a way to do this with regular expressions, please advise.

**Comment by trwnh** [comment]
There is now a "remote only" toggle/filter on the federated public timeline; this issue can probably be closed
