### ISSUE TITLE
Opening the timeline including videos may takes a while

### ISSUE THREAD

**Issue by unarist** [mastodon/mastodon#3742]
![gif](https://user-images.githubusercontent.com/705555/27140811-760cc9cc-5161-11e7-951b-9c7a95ece180.gif)

I understand about loading time of video, but timeline itself and other statuses should be shown quickly. This issue will happen regardless of autoplay setting.

This seems to be resolved by adding some delay (200 - 500 ms?) before loading the video, but it doesn't seem to be the best solution, because the required delay would vary according to environment.

EDIT: It's not surprising, but similar issue also happens on scrolling because we remove status content (incl. video tag) when the status is too far from viewport.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nolanlawson** [comment]
Which browser(s) do you see the delay in?

**Comment by unarist** [comment]
Edge 40, Chrome 59 and Firefox 55 on Windows 10.

I've tested with four mp4 files in the timeline, and each files are about 8 MB.
