### ISSUE TITLE
[enhancement] Web UI: Some toots are not shown

### ISSUE THREAD

**Issue by nailyk-fr** [mastodon/mastodon#3794]
It seems some toots are not well displayed into the webUI. I was not able to find the exact matching (maybe users from an instance not linked to mine? )

Steps to reproduce: 
- A post a toot
- B anwser on A publicly, 
- C anwser on A publicly. 
1. Clic on A toot into the webUI (or Tusky) display only A&C toots, 
![mastodon_webui](https://user-images.githubusercontent.com/16372405/27223238-e83a086e-528f-11e7-94f4-14c287f5e6ef.png)

2. Clic on the 'time" of the toot to open it into a new tab, A,B&C toots are displayed. 
![mastodon_web](https://user-images.githubusercontent.com/16372405/27223253-eee756bc-528f-11e7-9185-d98b75aa8ef1.png)

(in this [example](https://miaou.drycat.fr/users/Dryusdan/updates/5177) there is no C)
I can provide a lot more samples. Am still trying to find the 'pattern' of not shown toots. 
(This should not be a 'privacy setting' problem as opening the toot while not connected into the browser display A,B&C toots.)

Tested on Tusky on CM-12.1 & Firefox ESR 52 on debian 8
My instance is actually running [1.4.1](https://github.com/tootsuite/mastodon/tree/v1.4.1)

Many thanks

P.S. you can reach me on freenode, nickname: nailyk
* * * *
- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
I tried to search before posting but my keywords where not relevant, sorry. 
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Kimik0** [comment]
If B is not followed by someone on your instance, it won't know B's toots exist. It's just displaying all the replies it knows of.

**Comment by nailyk-fr** [comment]
@Kimik0 The use case is known now, thanks :)
But this is weird. Why does it works into the web page (out of the web UI) and not into the web UI ?

**Comment by unarist** [comment]
Mentioned instance will receive all mentions and replies directly, but other instances will only receive through subscription (i.e. following).

**Comment by nailyk-fr** [comment]
Can't understand. I received a mail about an added comment but I cannot see it here: 

> Mentioned instance will receive all mentions and replies directly, but other instances will only receive through subscription (i.e. following).

Think I understand now. With the web UI my instance is used so some message from not linked instances can be missing, with the tab into the browser the person first toot instance is used so know every message? 

I will change title for enhancement then, thanks.

**Comment by unarist** [comment]
Mentioned instance will receive all mentions and replies directly, but other instances will only receive through subscription (i.e. following). If your instance is later case, your instance won't know these toots.

Clicking timestamp will open *that toot's* instance, so it will display all mentions and replies. Web UI uses data from *your* instance, so it may not display all of them.

**Comment by nailyk-fr** [comment]
Thanks @unarist 
I just find something that looks related: 
![mastodon2_web](https://user-images.githubusercontent.com/16372405/27233607-550c1ca0-52ba-11e7-8e73-b5fd36a25031.png)
![mastodon2_webui](https://user-images.githubusercontent.com/16372405/27233608-551373f6-52ba-11e7-8e06-45d2edef0973.png)
Status shown into webUI are 3 only when on the browser there is more, publicly posted. 
Is it the same? Only those 3 status where boosted/liked by someone linked to my instance? Does that explain why I only saw 3 statues?

**Comment by Kimik0** [comment]
@nailyk-fr Correct. Your instance doesn't know a remote toot exists until someone from your instance interacts with that toot (boost, fav, reply, or simply look it up by its url). When you look up a remote user, the web UI shows only the toots that your instance knows of.
For example, if you look up a remote user that your instance has never seen before through the search bar, the web UI will show their profile with 0 toots, even though they may have been super active.

**Comment by nailyk-fr** [comment]
Thanks for the explanations. 
But AFAICT mastodon had been designed this way. Not linked to every instances to prevent data being stolen by a compromised (not linked) instance. 
This issue is https://github.com/tootsuite/mastodon/labels/bug tagged. Should I change the title? 
Thanks everyone.
