### ISSUE TITLE
Confirmation dialogue for unboosting toots

### ISSUE THREAD

**Issue by clarfonthey** [mastodon/mastodon#3815]
There is the shift + click confirmation dialogue for boosting toots, but not unboosting.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by harrybailey** [comment]
#10287 looks to be merged. Can this be closed?

**Comment by trwnh** [comment]
unboost confirmation is currently tied to boost confirmation, but it does exist. see #7860 for tracking issue on confirmation dialogs
