### ISSUE TITLE
Add option to always show "remote follow" button on profiles

### ISSUE THREAD

**Issue by clarfonthey** [mastodon/mastodon#3825]
For people who have multiple accounts on multiple instances, it would be nice to have the option to click the "remote follow" button every time, so that they can choose which instance they want to follow an account on.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by kerim** [comment]
I like this idea, but I also think having the ability to create an alias so that you can join multiple instances which link to a single account is a more robust solution. See here for an explanation: https://github.com/tootsuite/mastodon/issues/3796

**Comment by clarcharr** [comment]
I don't know if that's necessarily the right path; people will always have multiple accounts. That said, #2291 might be the more robust solution.

**Comment by trwnh** [comment]
both the remote follow popup and the static permalink profile view have since been removed
