### ISSUE TITLE
Answer to a boosted toot not appearing on this toot web page

### ISSUE THREAD

**Issue by Lertsenem** [mastodon/mastodon#3845]
I'm using mastodon v1.4.3, on a personal docker instance, through the Twidere android client.

Having a personal docker instance, I'm used to check a toot webpage when I want to see all the answers to a toot. But recently I noticed that when I'm answering a boosted toot, my answer does not appear on the original toot webpage, but rather on the boosted toot webpage.

For example :

@Alice@instanceA toots "Hello, world!"

Now there's a 'https://instanceA/users/Alice/updates/1234' webpage.

@Bob@instanceB boosts Alice toot.

Now there's also a 'https://instanceB/users/Bob/updates/5678' webpage, containing the exact same toot, only with a "Bob boosted" mention.

Following Bob, I get to read the boost and decide to answer Alice. But when I do, my answer will appear on the instanceB webpage only, not on instanceA.

This is not something major, since Alice will still be noticed of her mentions, but I was under the impression that I could always get all a toot answers by checking its original webpage and that is apparently not the case.

Would there be a way to have this behaviour? It would make following discussions a more consistent experience. :]

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Kimik0** [comment]
Sounds like a kind of bug to me. We don't have quoted toots on Mastodon, so there's nothing in a boost to reply to other than the boosted toot. The instance you're replying from should link it to the original toot and instance, not the boosting one. I'm not even sure the boosting user should be auto-mentioned when replying (this is something people often complain about on birdsite).

**Comment by nightpool** [comment]
Can you link to a toot that exhibits this behavior? I don't think I've ever seen this.

**Comment by Gargron** [comment]
It is actually possible to reply to a boost just like to a regular toot. Since it is a new toot that simply embeds the original, API-wise. It is up to the client whether to reply to the original or to the boost. The web UI chooses to always reply to the original. So this sounds like a Twidere bug or feature.

**Comment by Lertsenem** [comment]
> Can you link to a toot that exhibits this behavior? I don't think I've ever seen this.

Here I answered @Ymelia_@witches.town boost of @Hylde_@imaginair.es and my toot appears on her page: https://witches.town/users/Ymelia_/updates/349643
Here is @Hylde_@imaginair.es original toot webpage, where my answer does not appear: https://imaginair.es/users/Hylde_/updates/2245

@Gargron:
I understand the problem now, and I'll be opening an issue on the Twidere side, but shouldn't the boosting instance somehow notify the original toot instance? I have no idea of how the code actually works, so I'm not sure I'm making sense here.
Also I'm guessing boost and favs work the same way, so I could be boosting the boosted toot and the original poster would never be notified?

**Comment by Kimik0** [comment]
@Gargron - It is a client mistake, but it seems to me that the server end could help in this regard by automatically linking replies to the original toot if it was originally from that same instance, or refusing them if it was from another instance. Either way, no replies to boosts should appear in the database. That is, unless Mastodon introduces quote-toots of course; in that case a reply to the quote would be useful.

**Comment by trwnh** [comment]
no longer relevant -- boosts no longer get their own permalinks, and also there are no permalinks anymore since everything is rendered by the webapp since v4.0
