### ISSUE TITLE
Combine Getting Started and Compose columns

### ISSUE THREAD

**Issue by clarfonthey** [mastodon/mastodon#3872]
Considering how both are always open, it makes sense to merge them into one column somehow. It'd make it easier to fit more things on the screen too.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
Doing some issue triage ... 

This is super old, has not been responded to, and the team has a policy of not accepting outside UX ideas, so I'm going to close this.

If you want to push forward, please reopen and include some screenshots (From current version) with rough indication of what you'd want to change (no guarantee anyone will review).
