### ISSUE TITLE
rsync for maintenance / setup on a new VPS 

### ISSUE THREAD

**Issue by LoggenCocka** [mastodon/mastodon#3971]
rsync the database on an new VPS  for maintenance will be a idea and more than a workaround staying online and consistent .   could there already a cmd line workaround,  but just for expert .

**Comment by nightpool** [comment]
Is there a question here? I'm not sure how related this is to the actual software—you might be better served by the admin discussion on Discourse: https://discourse.joinmastodon.org/c/instance-admin
