### ISSUE TITLE
Imprint for instances hosted in germany

### ISSUE THREAD

**Issue by ThomasLeister** [mastodon/mastodon#4057]
Websites from Germany need to have a imprint linked from every page, which contains the name, address and contact details of the person, who is responsible. Of course you can add your imprint data to the "about" details, but that wouldn't match the requirement "linked from every page". 

**A tiny feature which allows easy integration of a imprint would be really nice :-)**

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nightpool** [comment]
Is there a specific page /about/more isn't linked from where we could easily add that link? that's probably the easiest solution from a compatibility standpoint

**Comment by ApoRes1337** [comment]
we will see the Imprint Feature for German Instances ?

**Comment by trwnh** [comment]
with the webapp rendering everything, it should be sufficient to put the imprint on the About page, which is indeed "linked from every page" -- mastodon.social and mastodon.online are doing this.

if you disagree, the issue can be reopened
