### ISSUE TITLE
User backgrounds always animate

### ISSUE THREAD

**Issue by saper** [mastodon/mastodon#4239]
(from https://icosahedron.website/users/shel/updates/72248 by @yiskah)

With "auto play GIFs" disabled user profile background is still animated (for example https://glitch.social/web/accounts/11788 running on 7f4375822a869bac55eb9dd9884e7803695aed82)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
This is still the case and it needs to be fixed!

**Comment by trwnh** [comment]
animation for logged-out users is now only on-hover, i think? although, they might not even animate anymore...
