### ISSUE TITLE
Live text search and search box inside Favourite column

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#4385]
First of all: English is not my native language. Apologies in advance for any grammar mistakes.

I was scrolling through my Favourite column looking for a specific toot when I had the idea of implementing a **live text search*** inside the column, above all starred toots. I believe this feature would be handy for a great amount of people since users tend to archive toots in there. I know Mastodon doesn't have text search because of its concern with privacy, but perhaps this could be implemented only in the Favourite column so users don't have to scroll forever trying to find a toot.

*I don't know if that's the right term.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
This is *sort of* coming! Specifically: https://github.com/tootsuite/mastodon/pull/6423

**Comment by Cassolotl** [comment]
*Full-text search for authorized statuses #6423* has now been merged. Do you want to keep this open and specifically request a text search in the favourites column only?

**Comment by trwnh** [comment]
you can do this now, if elasticsearch is installed
