### ISSUE TITLE
Add ability for emails to be encrypted with your GPG public key.

### ISSUE THREAD

**Issue by LogalDeveloper** [mastodon/mastodon#4501]
The idea here is that you can upload your public key to your Mastodon account somewhere in the users settings area, and all emails, including password reset emails, that are going to your email address are encrypted with this key before being sent.

One thing that should probably be considered is verifying the user actually has the private key, as they could get locked out of their account if they forget their password and don't possess the private key. An idea to handle this is to send an encrypted verification email when a key is submitted or changed and only start encrypting all other emails when the verification link inside is clicked, proving that the user has the private key.
***
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by N07070** [comment]
This would be a great ideal for people that need extra security in there emais with Mastodon being used for work, i.e switter.at for example.

Also, a lot of people using it in the infosec community would love to see this happen I think.

**Comment by nightpool** [comment]
>
> Also, a lot of people using it in the infosec community would love to see
> this happen I think.
>

not sure where you're getting your info from, but most people "in the
infosec community" think that gpg mail is a really bad idea for tons of
well established reasons, mostly because of it's famously god awful
usability, but also because of it's pisspoor threat modelling for most
situations

>

**Comment by Lukas2112** [comment]
I would very much welcome such a function.

**Comment by Lukas2112** [comment]
@Gargron and @ClearlyClaire could you take a closer look here to what extent this would be feasible?

**Comment by Gargron** [comment]
This is absolutely not worth it.

**Comment by Lukas2112** [comment]
When would it be, @Gargron ?
