### ISSUE TITLE
Enabling push notifications for an account logs out other sessions

### ISSUE THREAD

**Issue by nightpool** [mastodon/mastodon#4507]
1. Log in on chrome
2. Log in on the same machine, on a new browser (like safari)
3. See "push notifications registered!" from Safari
4. Go back to chrome, get "invalid access token", and see that you have to go back to the login page and log in before taking any action.

I *think* this is a push notifications thing, since after I logged back in on chrome where I already had push notifications registered, it didn't log me out of safari. May be unrelated though!

**Comment by sorin-davidoi** [comment]
> 3. See "push notifications registered!" from Safari

I don't follow. So this notification is generated by the Safari login but is displayed by Chrome?

**Comment by nightpool** [comment]
No, sorry, the notification is correct. The problem is that after seeing that notification, I can't do anything else on chrome. It logs me out.

**Comment by Gargron** [comment]
Is this still present?

**Comment by trwnh** [comment]
seems to no longer be happening
