### ISSUE TITLE
Replies to unfederated posts don't show up in Home column

### ISSUE THREAD

**Issue by impiaaa** [mastodon/mastodon#4573]
I have a main account on mastodon.social and several alt accounts following it from other servers. If I reply to a post of my own that is old enough to have not previously appeared on the remote server, both statuses will appear on the remote, however only the old one will appear in the remote Home timeline. Subsequent replies do appear.
Expected behavior (in this case, the old post has federated): 
![image](https://user-images.githubusercontent.com/1307275/29156139-2b08d572-7d55-11e7-9247-75646a91535a.png)
Errant behavior (the old post was not previously federated, but shows up new): 
![image](https://user-images.githubusercontent.com/1307275/29156177-68bef1c6-7d55-11e7-903c-fe81d7d5efad.png)
The posts show correctly (still incorrect order) once I go to the profile page: 
![image](https://user-images.githubusercontent.com/1307275/29156247-a5855bae-7d55-11e7-963e-f453b8d9cc56.png)
Link to the test: https://mastodon.social/@impiaaa/14965983

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
possibly related to #2614
