### ISSUE TITLE
Display followers-only toots from accounts you follow in hashtag search

### ISSUE THREAD

**Issue by nclm** [mastodon/mastodon#4701]
When you search for (or click on) a hashtag, a tag search timeline opens, with the latest toots containing the keyword. It does not however displays toots that are followers-only / from locked accounts, even if you’re part of the followers of that person.

For instance, I’m part on a small instance where everyone is locked and post to followers-only. We tried to start introducing hashtags, but the feature has no use since we can’t retrieve toots sharing the same tag, even though we all follow each other.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
I think this is a duplicate of *Hashtag timelines don't include private posts even if you are allowed to see them #2440* ?

**Comment by wxlfe** [comment]
Since this was declared intentional on #2440, should this issue now be closed?

**Comment by bryszard** [comment]
Bumping up the question above - I believe this is a `wontfix` and should be closed?
