### ISSUE TITLE
WebPush notification should be consistent between mention and favourite

### ISSUE THREAD

**Issue by unarist** [mastodon/mastodon#4809]
In the mention notification, both of text and image appears:

![image](https://user-images.githubusercontent.com/705555/30033622-3e490148-91d7-11e7-9316-ce73271f3bbf.png)

and NSFW image hidden by expand button.

![image](https://user-images.githubusercontent.com/705555/30033582-03003822-91d7-11e7-9446-dab87a499a47.png)

However, only image appears in the favourite notification if image attached:

![image](https://user-images.githubusercontent.com/705555/30034888-5eb0abd6-91df-11e7-89eb-3f16b7fedc98.png)

also same behavior occurs even if NSFW is set.

It should be act like mention notification, i.e. show both of text and image, and hide NSFW image.

Chrome 62 / Windows

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this). v1.6.0rc1

**Comment by mjankowski** [comment]
Still relevant on 4.3? If so, can you add updated screenshots?

**Comment by unarist** [comment]
I cannot reproduce this issue now, so I'm closing this.
