### ISSUE TITLE
Separate the strings for toot counts and toots display tab in profile page

### ISSUE THREAD

**Issue by mabkenar** [mastodon/mastodon#4823]
If I am not mistaken, the two words for **Toots** in the screenshot below come from the same string in `config/locales/en.yml:L44`.

![selection_426](https://user-images.githubusercontent.com/3006332/30123406-303ada66-9332-11e7-8c0e-9ee3592dd4a3.png)

But they should not. The word **Toots** in the two cases translate to different things in Persian. One is the noun used for counting toots and the other is literally "toots". The problem is in Persian nouns are counted with their singular forms, for example we say "20.4K toot" and not "20.4K toots".

Therefore the top "Toots" should be translate "نوشته" and the bottom "Toots" should be translated "نوشته‌ها". Having the same string for these two occurrences of "Toots" makes it impossible to translate it into Persian.

**Comment by mjankowski** [comment]
Closing on assumption that this is resolved in newer versions. Can you re-open with current screenshots if still problem in 4.3?
