### ISSUE TITLE
Reuse of deleted accounts/handles

### ISSUE THREAD

**Issue by ClearlyClaire** [mastodon/mastodon#4874]
I have encountered the following situation a few times: for some reason, an account and/or instance (let's call it A) is wiped and re-created after a while. In this situation, remote instances will not be notified of the account deletion and will keep following the “new” account, although the “new” account's instance may not know about it. This can lead to a few issues with the user experience:
1. Some remote followers may not be notified of new toots anymore and may wonder why (they still think they are following A)
2. If an instance has re-subscribed to new-A, follows are still not synchronized, which may result in “shadow follows” (some followers of former-A will be notified of A's new/private toots although A won't know about it)

A synchronization mechanism for follows could be useful for that situation (and also for the situation where a user force some followers to unfollow them, e.g. the “private account” thing in the settings), but there is something else that could be done: have some special handling when a remote account's private key changes. I can see two easy options, and one that would need some more work:
1. Whenever a remote account's private key changes, make every local follower unfollow them (downside is that it would also lead to bad user experience if this is done silently)
2. Whenever a remote account's private key changes, re-issue a follow request for each local follower (the downsides of this are potentially flooding the remote user, and the case of impersonation/cybersquatting)
3. A mixture of 1. and 2., unfollow the remote account, but notify each local follower of this, offering them to re-follow with a single click

**Comment by nightpool** [comment]
(@cassolotl and future readers—this doesn't have anything to do with #4614)

Is this something you can reproduce with only-ActivityPub instances? The way subscriptions work has changed fundamentally and I want to make sure we're working with the most up to date information.

**Comment by Lana-chan** [comment]
this is related to #4614

**Comment by Lana-chan** [comment]
ideally deleting an account on mastodon would delete all toots and media and metadata (including follows and followers, propagating to those users that the account has been deleted so remote instances reflect this as well) but leave the account suspended in a way that it could be unsuspended and the password changed so the handle could be reused. right now from personal experience none of this is currently true and needs to be implemented.

**Comment by ThibG** [comment]
This is only remotely related to #4614, which is about to reuse a local account.

This issue is about handling reuse of remote accounts: one such case might arise from someone using #4614, but I was thinking about a wider range of situations, in particular those where things went wrong at some point and can't be achieved by the deleted account's instance notifying remote ones (namely, a wiped instance being brought back up).
In such a situation, the user's keypair will change, and remote instances could handle it like I proposed.

As for ActivityPub, no synchronisation mechanism for followers exists, and it would not be reliable either as the followers collection is optional IIRC. Therefore, AP doesn't really bring any improvement over OStatus in this regard.

**Comment by nightpool** [comment]
Okay, so there are a couple things happening here.

 - Sometimes, a remote followers collection can change with respect to your local server, *without* notifying you. This can happen above and beyond anything that happens in the app—the most common way is dropping your instance database, but there are other ways this can happen.
    
    I'm not sure what the easiest way to fix this is, but the most correct way is to occasionally check or embed the followers collection during federation. This has real bad performance impacts though. 

 - We currently don't "clean up" suspended remote accounts in the right way, in a way that causes this state desync. I thought we did, using the SoftBlockWorker, but I was mistaken. This part should be easier to address.

**Comment by Cassolotl** [comment]
>(@Cassolotl and future readers—this doesn't have anything to do with #4614)

Oops, sorry, I will go and delete my comment in the other thread.

**Comment by ThibG** [comment]
ActivityPub's followers are not appropriate for syncing. Or rather, they may be, if the collection is actually accessible, but it is only a “should” in the specs!

I think my second proposition (re-issue a follow request on keypair change) is the closest to the current behavior, except it is more reliable and also fixes the “shadow followers” issue. I am not completely comfortable with it, though, for the reasons I explained above:
1. It means potentially re-issuing a lot of follow requests (but that's only the number of followers the user had before deleting their account)
2. If the handle doesn't actually correspond to the same user (cybersquatting, identity usurpation, or just random luck), users will re-follow someone they weren't following in the first place. This is more or less what Mastodon currently does, though, and a proper “fix” for this situation has to handle much more than just the follow part (all previous known toots of the previous user would currently still be attributed to the new user)

**Comment by ThibG** [comment]
https://github.com/tootsuite/mastodon/pull/4907 is an (currently untested) attempt at implementing my second proposition: that is, re-issuing follow requests whenever a remote users' keypair changes.

**Comment by Ry3yr** [comment]
So whats the consensus here, seeing as this issue is still "open" ?

**Comment by ClearlyClaire** [comment]
I'd say that's fixed (between Mastodon instances) thanks to #15026
