### ISSUE TITLE
Mastodon does not respect Accept-Language order for en-US

### ISSUE THREAD

**Issue by Artoria2e5** [mastodon/mastodon#4887]
On mstdn.io and mastodon.social's (both 1.6.0, I think) initial sign-in/about page, Mastodon tries to cater to the browser's request by looking at the Accept-Language for localization. However, this process seems to prefer non-English languages, as my order of `en-US,zh-CN;q=0.8,zh;q=0.6,en;q=0.4` ends up always giving me zh-CN. Or maybe it just doesn't know the implied `q=1`?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ykzts** [comment]
Please try `Accept-Language: en,zh-CN;q=0.8,zh;q=0.6`.

Mastodon supports `en` (not `en-US`).

**Comment by Artoria2e5** [comment]
Good call. Seems to work with `en`:
```
$ curl -H 'Accept-Language: en,zh-CN;q=0.8,zh;q=0.6' https://mstdn.io/about | head -n 2
<!DOCTYPE html>
<html lang='en'>
```
Might be a good idea to somehow fake an `en-US` from `en`, for it's a pretty popular default.

**Comment by mjankowski** [comment]
Closing on assumption that last few comments here explained/resolved this (and 7 years old!)...

That said, if this can be reliably reproduced on an updated version (or it wasnt resolved) please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
