### ISSUE TITLE
Share button does not work

### ISSUE THREAD

**Issue by steelman** [mastodon/mastodon#4892]
I've got account at mstdn.io, which quite recently has been upgraded to 1.6.0. I got the question about registering web+mastodon protocol handler. Now, when I enter `web+mastodon://share?text=Lorem+ipsum` Firefox asks me to choose which handler to use and I am redirected to https://mstdn.io/auth/sign_in (despite the fact that I am logged in in a different tab). Next, the authentication fails (I triplechecked the password) and I get the following message

Security verification failed. Are you blocking cookies?

Firebug indicates that I am properly redirected to /intent and /share actions. It is the latter that redirects to sign_in. When I enter https://mstdn.io/intent?uri=web%2Bmastodon%3A%2F%2Fshare%3Ftext%3DLorem%2Bipsum in the URL bar, I get the share screen as expected.
Firebug also indicates that when I enter /intent URL the requests that follow contain authentication cookies. Requests triggered by web+mastodon://share don't. I use Firefox 52.3.0

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases/v1.6.0) and not on `master` (If you're a user, don't worry about this).

**Comment by steelman** [comment]
The error message is true. The problem is the way Firefox handles/I have configured my cookies. For the `web+mastodon://` links to work, "Accept third-party cookies" needs to be set to either "Always" or "From visited".

I think it might be worth noting it somewhere (error message, documentation), because as of now I expect noticeable number of Mastodon might be privacy aware people who set the option to "Never".

**Comment by trwnh** [comment]
the protocol handler has since been removed, so i am closing this issue.
