### ISSUE TITLE
Columns based on filters

### ISSUE THREAD

**Issue by Phyks** [mastodon/mastodon#5010]
Hi,

First, thanks for all the work you are putting in Mastodon, it's really an amazing software!

For now, it is possible to create a new column with a given hashtag, to see toots with this hashtag. However, this is limited to a simple hashtag, and I think it might be useful to be able to have such columns with more advanced expressions (a bit like intelligent playlists in iTunes, or email filtering in Thunderbird).

My typical use case would be: I want to track `#meetup` to have some info about future meetups, but I live in Paris, so I want info about future meetups in Paris. If I track `#meetup`, I have toots from all over the world, if I track `#Paris` I have some irrelevant news. It would be awesome if I could just track `#meetup AND #paris` in a column.

Thanks!

**Comment by thiagomgd** [comment]
This could also helps with #1096, as someone who wants to follow a few hashtags could create:
`#Introductions OR #Mastodon OR #MastodonHelp` or `MusicMonday OR #wcw OR #fridayreads OR #letsplay`

**Comment by rory** [comment]
I would like this too, because I want to follow the `#OpenStreetMap` hashtag, but sometimes people use `#OSM` (or even the misspelling `#OpenStreetMaps`). It's all under the topic of "OpenStreetMap", so it would be nice to have one column.

**Comment by LC43** [comment]
another use case ( mine ) is to follow a few topics that don't have yet lots of content ( #vr + #ar + #webvr ). being able to have a column for a bunch of them would be great.

Please avoid OR. 

May I suggest that, by default, `#vr #ar` should a `AND`, while `#vr + #ar + #webvr` would be `OR`.

**Comment by VonKavalier** [comment]
I would love that too :)

**Comment by mkosler** [comment]
A common use case for something like this would be following big reoccurring events, such as AGDQ. There usually is a general hashtag, like #agdq, and a hashtag for the specific event, like #agdq2018. The conversation around the event can get fractured based on whether a toot uses only one of those hashtags.

Twitter handles this through the Boolean logic mentioned by @LC43: two bare hashtags are by defaulted ANDed together; if you want to specifically OR them, you need to add it to your query. I think this would be a great feature for Mastodon.

**Comment by Cassolotl** [comment]
See also *Join several hashtags in a search/column #6359*, which has some comments by Gargron and other devs!

**Comment by sjaveed** [comment]
Is this still needed given #6359 is already done?

**Comment by Cassolotl** [comment]
Yeah, *Allow joining several hashtags in a single column #8904* was merged in 2018.

**Comment by sjaveed** [comment]
Right. So can we close this then?

**Comment by Cassolotl** [comment]
Yes, we'll need @Phyks or a mod to close it though, I think?
