### ISSUE TITLE
Toot visibility icons

### ISSUE THREAD

**Issue by MightyPork** [mastodon/mastodon#5055]
This is a feature we've been using on glitch-soc for a couple months now and it's proven immensely useful.
I'm making an issue first before spending any time on re-implementing this for a PR, to gauge interest.

They look like this (in the corner):
![screenshot_20170923_140242](https://user-images.githubusercontent.com/2041118/30773008-e21248fe-a067-11e7-8be0-ecb228d5049d.png)

Since upstream toots have a different layout to ours, we'll need to find a different place for those icons. Maybe the bottom right corner would work?

![screenshot_20170923_140350](https://user-images.githubusercontent.com/2041118/30773018-0db73776-a068-11e7-9a1e-be7290add576.png)

**Comment by wxcafe** [comment]
I really like this idea yeah 👍

**Comment by renatolond** [comment]
I really like this too. I was checking how it was implemented in glitch-soc and it would be awesome to have it brought to upstream. 👍

**Comment by Cassolotl** [comment]
I think the date/time makes more sense in the bottom right corner anyway - there's usually more space down there.

**Comment by wbrawner** [comment]
+1 on this. Also it would be nice to be able to click the icon and change the visibility after the post. Might be difficult with federation but at least being able to change the _future_ visibility would be an improvement I think

**Comment by trwnh** [comment]
fixed by #14123, this issue can be closed
