### ISSUE TITLE
REST API returns null in url property for Announce activities

### ISSUE THREAD

**Issue by unarist** [mastodon/mastodon#5403]
![image](https://user-images.githubusercontent.com/705555/31584947-a2212812-b1f3-11e7-9899-8f7c64e12a23.png)

|             | local                            | via OStatus | via ActivityPub                  |
|-------------|----------------------------------|-------------|----------------------------------|
| API on <1.6 | /@.../...                        | /@.../...   | /users/.../statuses/.../activity |
| API on 1.6+ | /users/.../statuses/.../activity | /@.../...   |  *null*                            |

[We said it's non-nullable in API docs](https://github.com/tootsuite/documentation/blob/53f52cdddc9afc8457ac07e0ff7f09f928d015f2/Using-the-API/API.md#status), so I think it's a breaking change.

The cause is that we don't set URL on Announce activity handling, but actually, we don't have a URL for ActivityPub which provides HTML for reblog itself. Also `/users/.../statuses/...` will be redirected to the original status.

So options would be...

* Change REST API spec to return null in `url` property on reblogs
(for consistency, also we may want to return null even for local reblogs)
* Use URL of reblogged status
* Add HTML representation of reblog itself, and use it

Anyway, we may want to use url property of Announce activity if exists.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
> Use URL of reblogged status
seems to be what is done now

**Comment by mjankowski** [comment]
Closing on assumption that last comment is accurate and suggests this is handled - please reopen if not.
