### ISSUE TITLE
Do not include Unicode directional formatting characters in URL detection

### ISSUE THREAD

**Issue by unarist** [mastodon/mastodon#5468]
I don't know other case exists, but when I copied all text from compose dialog of iOS Twitter app, it was surrounded with directional formatting characters in Unicode.

![image](https://user-images.githubusercontent.com/705555/31767465-1f2f4770-b506-11e7-9e09-9f85cdce17fb.png)

What if the text was ended with an URL?

![image](https://user-images.githubusercontent.com/705555/31767588-a5b13b3c-b506-11e7-94bc-12b7a82fbfaa.png)

I have seen these *broken* links sometimes.

We have changed autolink condition in #4941 to capture those characters along with non-ASCII characters, but I think it shouldn't be captured unless manually encoded.

So the question is, what character set should we capture on URL autolinking? We need to specify it in regexp pattern, and current pattern is here:

https://github.com/tootsuite/mastodon/blob/09d81defcda96eae7ffba36ccf1fb091ce08f17b/config/initializers/twitter_regex.rb#L4-L5

or maybe...should we disallow those characters in the post, like twitter-text does?

https://github.com/twitter/twitter-text/blob/aa713d3203e5c8678cf9e3c6d45dc00c7da33de2/rb/lib/twitter-text/regex.rb#L56-L60

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by unarist** [comment]
> when I copied all text from compose dialog of iOS Twitter app, it was surrounded with directional formatting characters in Unicode.

As a workaround for this case, add some character (e.g. white space) around the URL before copy it. It will separate directional formatting characters from the URL.

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
