### ISSUE TITLE
Emojis inserted by shortcode should have the set skin color

### ISSUE THREAD

**Issue by gandaro** [mastodon/mastodon#5498]
In the emoji picker, I specified a light skin color.

When I type a shortcode, say `:ok_hand:`, the emoji gets inserted as Unicode character.

But without a skin color. It’s yellow.

It should be inserted with light skin color.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
Closing on assumption that this is resolved in newer versions. Can you re-open with current screenshots if still problem in 4.3?
