### ISSUE TITLE
React status components are re-rendered when Redux changes

### ISSUE THREAD

**Issue by nolanlawson** [mastodon/mastodon#5504]
This is causing performance problems which I observed when you tap the favorite star, and sometimes the whole UI seems to slow down. :confused:

Steps to repro:

1. In React dev tools, turn on "Highlight updates"
2. Click the "favorite" button on any status
3. Observe that unrelated statuses are re-rendered ([video demonstration](https://gfycat.com/CommonChillyGrassspider))

I did some profiling, and it appears we are spending lots of time in `mapStateToProps`. AFAICT the root cause is that in this code:

https://github.com/tootsuite/mastodon/blob/fdb0848e08f34ee967ae2d0ad24cd994e996169b/app/javascript/mastodon/selectors/index.js#L18-L44

... the `accountBase` is changing every time anything changes in Redux. The values don't _actually_ change, but the object doesn't pass a strict `===` equality check. Which is weird, because it's an `ImmutableMap`, so I thought that wasn't supposed to happen?

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
