### ISSUE TITLE
Treating URLs as fixed length allows users to post super long status

### ISSUE THREAD

**Issue by unarist** [mastodon/mastodon#5553]
We have 500 characters length validation for statuses, but users can avoid this by putting any number of characters in the URL. Then this may damage clients or remote instances.

I think we should have hard limit for status length, which won't be affected by URL handling.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
I mean, currently remote instances can specify arbitrarily long statuses? so this is already something we need to handle and I don't see why we should avoid it. Furthermore, URLs are truncated to their host portion during display, so I don't see this being a major problem for the front-end.

**Comment by unarist** [comment]
Ah yes, remote instance can do this already.

>  URLs are truncated to their host portion during display, so I don't see this being a major problem for the front-end.

Actually it's in redux store and DOM element, even if it's not displayed. URL with one million characters makes WebUI significantly slow, for example.

Also, the original issue reported by @imncls@knzk.me was a URL with lot of emojis. I opened this issue as it's common problem on URL handling, but I've realized that "lot of emojis" was the point. We replace emojis to Twemoji in the front-end, so performance impact is bigger than normal characters.

**Comment by Gargron** [comment]
What options do we have?

**Comment by trwnh** [comment]
Realistically?

1) Have URLs count against the character limit (since most instances default to 500, this can be seen as "enough" for all but the longest URLs)
2) Optional URL shortening module (autoshort of every single URL is bad -- any implementation should be up to the user to use)
3) Do nothing, continue suffering from performance drops / etc related to long URLs

**Comment by nightpool** [comment]
.... or just add a 25kb hard limit on local statuses the same way we do for
remote activities (I dont know what the actual number is)

**Comment by Gargron** [comment]
@nightpool We have a 25kb limit for statuses? :thinking: That's news to me

**Comment by nightpool** [comment]
Huh, nevermind, I swore the last time I was looking at the signature verification code it had somehting like that in there.....

**Comment by vmstan** [comment]
URL are limited via #17908
