### ISSUE TITLE
"Show more" link does not appear if the column is empty

### ISSUE THREAD

**Issue by wchristian** [mastodon/mastodon#558]
![image](https://cloud.githubusercontent.com/assets/175467/22381145/c30b8fe6-e4c0-11e6-993d-f7489c76819b.png)

**Comment by wchristian** [comment]
It looks like this is a general issue wherein a column that has overflow and scrolled all the way down with try to load more, but a column that isn't filled by the last load won't attempt to load more and has no UI for loading more.

I noticed this when my notifications column got stuck after a page refresh, and got unstuck when i opened the options menu, thus making the viewport smaller, then scrolling in that viewport.

**Comment by Gargron** [comment]
Could this be closed now that the bottom of columns always has a "load more" link?

**Comment by wchristian** [comment]
@Gargron Sorry, i don't see such a link. Not yet deployed?

**Comment by ashfurrow** [comment]
@wchristian can you confirm this is still a bug?

**Comment by wchristian** [comment]
Confirm it still happens. Reproduced by messing with the notification column settings.

To reproduce, disable "show in column" for all types of notifications, then reload the page. Notifications column will be empty with no load more link, even if you re-enable a type.

However if you reenable all, reload, and disable all but one, you can get into a view where only a few entries show, but the column is full, and there's a load more link.

I suspect there's some logic that prevents the link from showing up if a column is empty.

**Comment by ashfurrow** [comment]
Interesting. Thanks for the steps to reproduce 👍

**Comment by wchristian** [comment]
![image](https://cloud.githubusercontent.com/assets/175467/25313882/9a273556-2838-11e7-8d8b-0ec61bfbe974.png) ![image](https://cloud.githubusercontent.com/assets/175467/25313877/7b5629e8-2838-11e7-82ec-fb6b8130086f.png)

**Comment by luzpaz** [comment]
Is this still an issue?
