### ISSUE TITLE
standalone skin type modifiers not getting emojified

### ISSUE THREAD

**Issue by nightpool** [mastodon/mastodon#5583]
maybe an emojimart issue? standalone skin type combining blocks (e.g. 🏽, 1F3FD) aren't getting emoji-fied, they're just represented by system emoji.

![image](https://user-images.githubusercontent.com/233815/32288622-de5aab68-bf0a-11e7-82e5-fa0bf0f46465.png)

**Comment by nightpool** [comment]
root cause seems to be emoji-data? 

```
# Notes:
#   • This currently omits the 12 keycap bases, the 5 modifier characters, and 26 singleton Regional Indicator characters
#   • The file is in CLDR order, not codepoint order. This is recommended (but not required!) for keyboard palettes.
#   • The groups and subgroups are purely illustrative. See the Emoji Order chart for more information.
```

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
