### ISSUE TITLE
Support for longdesc on images

### ISSUE THREAD

**Issue by wimvanderbauwhede** [mastodon/mastodon#5612]
It's great that Mastodon supports alt text on images, but would it be possible to support the `longdesc` attribute  as well? This allows to put a hyperlink for more detailed description.
This is recommended by the W3C accessibility guidelines: 
[https://www.w3.org/TR/2000/NOTE-WCAG10-HTML-TECHS-20001106/](https://www.w3.org/TR/2000/NOTE-WCAG10-HTML-TECHS-20001106/).
Details about the attribute are here: [https://www.w3.org/TR/html-longdesc/](https://www.w3.org/TR/html-longdesc/).

**Comment by ZoeBijl** [comment]
The `longdesc` attribute is obsolete and has been removed from the [HTML spec](https://html.spec.whatwg.org/multipage/).

**Comment by charliepark** [comment]
As it's been several years and `longdesc` is still deprecated ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/longDesc)), perhaps this issue would be a good candidate for closing?

**Comment by brennanyoung** [comment]
`longdesc` is not coming back, but there are aria attributes that do similar things.

`aria-describedby` hooks up to the text nodes inside another element (flat text only)
`aria-details` (coming in ARIA 1.3) points at one or more other elements for more info (structured content is supported)

I suggest closing this issue and revisiting the idea when ARIA 1.3 is an official recommendation.
