### ISSUE TITLE
Adjust position of the user's name vs. their profile address in settings to be above, or bellow

### ISSUE THREAD

**Issue by mareklach** [mastodon/mastodon#5657]
[Issue text goes here].

_Unfortunately I cannot implement this myself as I am not a coder of any sort, but if anyone else is interested, I am just throwing this here as a feature suggestion_:

By default as it stands now, the full profile address of a Mastodon user is positioned UNDER their name. My proposal is that in the profile settings of a each user account there should be an option to place a user's profile address above their name instead.

I am thinking that it all could be just a simple checkbox option is user settings which would state something like 'Display profile address below name'.

Feel free to elaborate and discuss this, anyone. Thank you

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by averageunicorn** [comment]
I would love to see something like that.

For me, the main issue is:
@ names are often cut off, only the display names visible fully, so I never actually learn the handles of the people I am following (let alone which instances they are on).
And I'd love to have just about any option that makes handles more visible than display names. Changing their places seems good to me, alternatively I could imagine them each having their own line.

**Comment by trwnh** [comment]
this is what we do now
