### ISSUE TITLE
Some local/remote animated avatar is corrupted on Docker instances

### ISSUE THREAD

**Issue by unarist** [mastodon/mastodon#5658]
For example, https://mstdn.maud.io/system/accounts/avatars/000/005/574/original/89de63b40ca41c7e.gif is a fetched avatar of remote user https://mastodon.zunda.ninja/@zundan. However, the last frame of the image is corrupted, like this:

![image](https://user-images.githubusercontent.com/705555/32691087-02dbee0a-c746-11e7-996a-d81ad140bd51.png)

This seems a bug of GIF optimization feature on ImageMagick, and this bug doesn't exist on ImageMagic 6. Major distributions still use ImageMagic 6 as a stable package, but [Alpine Linux 3.6 uses 7.0.5-10](https://pkgs.alpinelinux.org/package/v3.6/main/x86_64/imagemagick).

I've opened an issue on upstream too (https://github.com/ImageMagick/ImageMagick/issues/859).

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by vmstan** [comment]
Closed as fixed in IM7 with https://github.com/ImageMagick/ImageMagick/issues/859
