### ISSUE TITLE
Relationship metadata

### ISSUE THREAD

**Issue by zerok** [mastodon/mastodon#5737]
Hi 😄 First of all a big thank you to everyone who is working on Mastodon!

I often browse through my follow-relationships and can no longer remember why I chose to follow that account. Here it would be great, if I could somehow include a description of such a relationship that is only visible to me as the creator of that relationship.

Other information that might turn out being helpful here and could be exposed primarily/exclusively to the creator:

- When was the relationship created
- When was the relationship stopped / re-created
- Hashtags about the relationship (e.g. adding #golang to everyone I follow because of their expertise with the Go programming language)

## Affected API methods:

- `POST /api/v1/accounts/:id/follow`
- `POST /api/v1/accounts/:id/unfollow`
- `POST /api/v1/accounts/:id/block`
- `POST /api/v1/accounts/:id/unblock`
- `POST /api/v1/accounts/:id/mute`
- `POST /api/v1/accounts/:id/unmute`
- `GET /api/v1/accounts/relationships`
- `GET /api/v1/blocks`
- `GET /api/v1/domain_blocks`
- `POST /api/v1/domain_blocks`
- `POST /api/v1/follows`
- `GET /api/v1/mutes`

Would something like that be useful to somebody else?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by wxcafe** [comment]
This sounds pretty interesting to me. I think if we add something like this we might wanna make it a simple text field, that frees us from having to handle every single use-case and allows users to do more things with it.

**Comment by tchoutri** [comment]
We might as well have the Reddit Enhancement Suite feature to write a memo about a user.

**Comment by fsnk** [comment]
The hashtag part sounds like de-facto lists.

**Comment by trwnh** [comment]
> We might as well have the Reddit Enhancement Suite feature to write a memo about a user.

we have this now in the form of profile notes, so maybe this addresses most of the issue and the issue can be closed?
