### ISSUE TITLE
Top toot inter-client tracking

### ISSUE THREAD

**Issue by apiarian** [mastodon/mastodon#5788]
It would be interesting to support cross-client "don't scroll to top" "remember my timeline position" functionality. See also https://github.com/ReticentJohn/Amaroq/issues/59 . This might be an API which would let a client keep the id of the top toot per timeline (maybe at least for the main Home, Local, Federated ones?) on the server. Then all clients could start there when showing new toots.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
This can be closed now that `/api/v1/markers` exists!
