### ISSUE TITLE
Followers-only toots that your instance knows about already should be searchable using the URL by people who follow the author

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#5818]
Scenario:

1. Sandy has been following Paul for like... 3 weeks.
2. Yesterday Paul tooted something on the followers-only privacy setting, and Sandy saved the URL for later boosting or whatever.
3. Sandy pastes the URL into their Mastodon web UI so that they can boost the toot.

**Expected behaviour:** Sandy's instance "knows" Paul's followers-only toot and knows that Sandy follows Paul. Sandy's search should bring up the toot.

**Current behaviour:** Sandy's search yields 0 results, because the toot they are searching for is set to followers-only.

This might be a duplicate but I honestly don't know what to search for. :S It is inspired by [this thread](https://mastodon.starrevolution.org/@Laurelai/99066325170584371).

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
it is maybe possible to do this in the case where the status has already been populated, *if* the searched for URI is the same as the url or uri that was sent with the post (i.e. there's no redirection happening).

it is probably not currently feasible for us to fetch remote media with this, even though I could imagine a HTTP Signatures way of doing it.

**Comment by puckipedia** [comment]
not parsing HTTP signatures on GETs for statuses is a thing that I've been missing due to my Kroeg instance not being as well populated and trying to retrieve entire post chains, but failing because there's posts that might be follower-only, but before I was a follower

**Comment by trwnh** [comment]
this is supported now

**Comment by Cassolotl** [comment]
Oh great, then I will close this. Thanks! :)
