### ISSUE TITLE
The order of media ids is ignored when creating a status

### ISSUE THREAD

**Issue by tks333** [mastodon/mastodon#5857]
The order of media ids is ignored when creating a status using /api/v1/statuses. Even though I arranged the order of media ids and requested to create a status, the created status has media attachments in ascendants order of their media id instead of the ones I arranged.

I would like to allow users to rearrange the order of media when creating a status, but this behavior doesn't allow them.

- A request to create a status with media ids in a rearranged order.
```
{
    "media_ids" = (
        3220172,
        3220173,
        3220171,
        3220174
    );
    status = "...";
}
```
- Mastodon 2.0 responses a status whose media ids are in a different order:
```
{
    ...
    "media_attachments" = (
        {
            id = 3220171;
            ...
        },
        {
            id = 3220172;
            ...
        },
        {
            id = 3220173;
            ...
        },
        {
            id = 3220174;
            ...
        }
    );
}
```

- Expected response that is in the order which same as I requested:
```
{
    ...
    "media_attachments" = (
        {
            id = 3220172;
            ...
        },
        {
            id = 3220173;
            ...
        },
        {
            id = 3220171;
            ...
        },
        {
            id = 3220174;
            ...
        }
    );
}
```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
Not sure whether to mark it as a bug or not, but there is definitely room for improvement here.
No order is enforced at any moment when creating or rendering a toot, and the `media_ids` passed to the API is just used to find the media attachments, not to order them.
That would be a welcome change, but I think it would require a bit of work.

**Comment by umonaca** [comment]
I think this issue is important to fix, because when network is unstable, users on our instance feel annoyed because they have to re-upload everything. What's even worse is that there is no guarantee the delete-and-redraft works in an unstable network, so in many cases the toot just disappeared altogether with its images.

**Comment by umonaca** [comment]
Relevant issue #9635
