### ISSUE TITLE
Admin/moderator feature: force hide all media from an account

### ISSUE THREAD

**Issue by chr-1x** [mastodon/mastodon#5896]
Sometimes, as a moderator, we encounter users who through ignorance, malice, or inability of host instance are not hiding sensitive images. Sometimes a silence is okay, but often even if their followers are okay with seeing the content, they still would prefer it be hidden until clicked on. 

The proposed feature would allow administrators to set a flag on local or remote users such that all of their media is hidden with the spoiler warning until clicked on, even if the user in question has not flagged their media as such. This is similar to Twitter's ability to flag accounts as NSFW if they are frequently posting this kind of media.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
the "reject media" option does some of this, although it's a little more heavy handed (it doesn't cache the image at all and requires you to click through to see the content)

**Comment by nullkal** [comment]
It would be helpful we can apply "force hide all media" not only per instance, but also per user. There are users who ignores "please ignore lewd images by using NSFW", and we can nothing but suspend them for now.

**Comment by dracos** [comment]
Overlaps with #7179.

**Comment by Gargron** [comment]
This requires a more advanced permissions system than a single boolean. The reason that is difficult is that there is no single solution but many possibly valid ways of implementing it, so it's hard to decide. How should it be designed? Currently I am veering towards a user_permissions table with one row per user and one column per permission...

**Comment by trwnh** [comment]
I think we have this now with "force mark as sensitive" and the `sensitized` flag?
