### ISSUE TITLE
List feature polishing

### ISSUE THREAD

**Issue by Aldarone** [mastodon/mastodon#5915]
I just made the upgrade to v2.1.0rc1 and the list feature is great. However here is some things that are, in my opinion, missing : 

- [ ] Add the ability to rename an existing list.
- [ ] Add the filter feature to the list columns.

**Comment by hellocam** [comment]
It would be great if toggles for showing/hiding boosts and replies are added, too, like in the Home column.

**Comment by trwnh** [comment]
Semi-related: #6058

**Comment by trwnh** [comment]
Both of these have been done now, I think? You can rename lists and there is now a separate "filter" feature that isn't per-column.
