### ISSUE TITLE
Past posts are not reflected in the TL of the list when added to the list

### ISSUE THREAD

**Issue by abcang** [mastodon/mastodon#5938]
In the case of Home TL, MergeWorker will be executed and follow past postings will be reflected. I think the list also needs the same function.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
Closing in favor of #13687
