### ISSUE TITLE
Autoreply

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#5944]
Okay, so I feel like maybe this is a bit of a weird one...

I know that migrating accounts is a big job, and I don't know whether it's possible to have followers stop following an old account and start following a new one automatically - if it is possible, this might be a bit redundant in time.

I recently moved to a new instance, and I'm still getting the odd mention in the old place. I was wondering whether it would be too clumsy to create an autoreply function, and I could set it to respond to all mentions with something I wrote myself, like: "Hi! This is an autoreply to let you know that I have moved to `@newusername@newinstance`." That way I get tagged at my new account and I can see what someone wants to say to me, and folks know who to tag and/or follow.

If you have something else in mind then it's probably better and that's all good, let me know and I'll close this!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by dolfinsbizou** [comment]
v2.1.0 will introduce a "moved profile" note on old profiles (see #5746). 
Maybe the "autoreply function" you describe here would be somewhat annoying, one message per mention can quickly lead to a big amount of automatic toots.

**Comment by Cassolotl** [comment]
If #5746 prevents *most* of the mentions that won't get seen, the autoreply function would probably not happen very much anyway. But if I sent someone a message and typed in their details from memory and I got an autoreply saying "please unfollow this account and follow me at..." I'd probably appreciate it!

**Comment by enterprisey** [comment]
Autoreply, for the specific use case of moving instances, is also being discussed at #8003. The current issue is still good for the case of "vacation notices", etc.

**Comment by Cassolotl** [comment]
Migration lets you take your followers with you now, and I think it also does sensible things in search/autocomplete, so I'll close this.
