### ISSUE TITLE
Status creation fails on id collision in transaction

### ISSUE THREAD

**Issue by akihikodaki** [mastodon/mastodon#5960]
#5260 introduces `id` override, and it is expected to try up to 100 times if `id` collides. However, it does not really work because it can be in transaction (e.g. [ActivityPub implementation](https://github.com/tootsuite/mastodon/blob/4c6b5dbe96b565d3db3cbf0912f3b9911bc3922a/app/lib/activitypub/activity/create.rb#L23)), and `id` collision immediately causes rollback.

I do not think it really matters, but it is a bug anyway so here is an issue.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
