### ISSUE TITLE
Posts remain on the list when muted

### ISSUE THREAD

**Issue by abcang** [mastodon/mastodon#5978]
Posts remain on the list when muted. Also, when you cancel mute, posts in the period you were muting will not be inserted. Perhaps it is because there is no manipulation of redis data managing the list when muted.

Related: #5938

**Comment by Gargron** [comment]
This is true, but muting someone you deliberately put on a list is probably an edge case, what the interaction *should* be like is not entirely clear-cut.

**Comment by nightpool** [comment]
@Gargron from @abcang's description, I think the behavior here is inconsistent either way—either it should remove the posts from *before* you were muting the user, and then not add any additional posts, or it should *leave* the posts and *continue* to add additional posts. currently it sounds like the behavior is *leave* old posts but *fail* to add new posts. I think the correct resolution here it to bypass the muting check for lists, but I could see arguments either way.

**Comment by delightfulagony** [comment]
Furthermore, if someone in the list boosts an account, and you then mute/block the account that was boosted the post will still be shown in the list.

I've tried muting, muting+silencing notifications and blocking and whenever I reload the webpage the toot is still there.

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.

**Comment by trwnh** [comment]
#32930
