### ISSUE TITLE
Blocklists shouldn't display a follow button when unblocking a user

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#601]

**Comment by joyeusenoelle** [comment]
This should be reopened. Here's a better description of the problem:

1. Adam opens their list of blocked users.
2. Adam clicks the "unblock" button on Eve.
3. Once Eve is unblocked, the UI does not remove Eve from the list of blocked users. Instead, it changes the "unblock" button at the right-hand side of Eve's listing in the list of blocked users to a "follow" button.
4. If Adam clicks twice, not only is Eve unblocked, but Adam follows Eve.

When Adam unblocks Eve, the icon should change state, from "blocked -> unblock" to "unblocked -> reblock". In other words, clicking twice should restore the state Eve was in before Adam clicked. Clicking twice should NOT both unblock and follow Eve.

If Adam clicks Eve's username after unblocking Eve, Mastodon should present Eve's user column, which will allow Adam to follow and/or mute Eve as usual.

If Adam clicks away from the Blocked Users column, Eve will no longer appear in the Blocked Users column and Eve's state in the column will change back to normal (i.e. not present).

**Comment by nightpool** [comment]
This is right on the edge of bug/not bug for me, but it definitely is confusing behavior that should get fixed.
