### ISSUE TITLE
Parallel display of "desktop notifications" and "push notifications" is confusing

### ISSUE THREAD

**Issue by akihikodaki** [mastodon/mastodon#6034]
![screenshot of column settings](https://user-images.githubusercontent.com/17036990/34035407-4b36c1d6-e1c5-11e7-909b-39af5b212b6b.png)

Here, "desktop notifications" toggle and "push notifications" toggle are shown in the same way. However, push notifications is a superset of desktop notifications in terms of their functions, and enabling both at the same time does not make sense.
The UI should be more helpful to understand those settings.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by sorin-davidoi** [comment]
There was an attempt at clarifying this (https://github.com/tootsuite/mastodon/pull/4218) but it was ignored.

**Comment by deutrino** [comment]
It might be easier for many to understand if instead of "Push notifications [this device]" it were worded to convey the meaning, e.g. "Allow when tab is closed."

I'm a developer and I couldn't figure out what was meant by "Push notifications [this device]," FWIW.

**Comment by wanderview** [comment]
FWIW, I had both of these enabled for a while and got duplicate/flickering notifications.

Also, the term "desktop" is a bit confusing on my mobile device.  Other sites seem to use "web notifications" for showing notifications whether from push or the main window.
