### ISSUE TITLE
The layout of notification settings is messy

### ISSUE THREAD

**Issue by akihikodaki** [mastodon/mastodon#6035]
In the past, we had only email notifications and notification columns, and settings for them are located at Preferences page and the column settings menu, respectively. The UI worked perfectly then.
Later, we added desktop notifications, and push notifications. Settings for them are pushed to the column settings menu, probably due to the convenience to implement, but that caused some problems:
* If (i) you found email notification settings in Preferences page and (ii) you know you can have desktop notifications and push notifications (that is possible because the browser tells you that), but (iii) you don't know where the settings are located, you'll wonder where those settings are.
* If (i) you found desktop and push notification settings in the column settings menu and (ii) you know you can have email notifications, but (iii) you don't know where the settings are located, you'll wonder where those settings are.
* The column settings menu has so many items that it needs to be scrolled.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by deutrino** [comment]
Can confirm, just went looking for desktop notifications settings in the settings page.
