### ISSUE TITLE
Remote follower remains on follower list even after that user has been deleted by home instance

### ISSUE THREAD

**Issue by BrodyB** [mastodon/mastodon#6064]
1. Get followed by a user from another instance
2. Remote user appears on your followers list
3. That remote user's instance suspends/removes their account, so now trying to go to their page URL shows a 404 error

Result: Remote user still appears on your followers list.

Expected Result: A user being deleted from another instance removes them from your follower and following lists if they appear on either of them.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Related: #6054

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
