### ISSUE TITLE
Feature request: account watch list [bridge.joinmastodon example]

### ISSUE THREAD

**Issue by bunnybooboo** [mastodon/mastodon#6069]
I recently deactivated my Twitter account with over 3,000 followers. A similar number that I followed. Before doing so I regular posted about how amazing Mastodon is and a few people signed up and reconnected. Others I used the bridge.joinmastodon feature, which is ace btw but this use case is bigger than that joinmastodon project itself.

Now I've deactivated Twitter I have no way of being notified when any of those people create an account in the Fediverse. This requires me going back through the CSV and manually checking.

What would be cool for users doing this in future might be a way when using the bridge feature and integrating Twitter/Mastodon API's -- a user might be able to take a snapshot of their current followers details and save alongside their associated Mastodon account. The intended use would be this snapshot becomes a watch list:

    - notification when a matching NAME is created (e.g. Brenda Smith)
    - notification when a matching @username is created (e.g. @BrendaIsaStar)

I'd imagine it presented like: 
> Brenda Smith just joined Mastadon! You saved a snapshot requesting to be notified if someone of this name matched. Click Here to do a welcome toot. Click Here to edit this watch list.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by bunnybooboo** [comment]
P.S. any similarity to any existing person of that username was unintentional, as it was just off the top of my head. :smile_cat:

**Comment by corbindavenport** [comment]
I like the idea about notifications for your contacts joining Mastodon. Twitter does this based on the email/phone number used for signup.

**Comment by nightpool** [comment]
Not sure how this would work in a federated context—there's no concept of a "username" joining a network, since you'll only see the people following/followed by your individual server. Furthermore we *definitely* don't expose emails or phone numbers to remote servers for privacy reasons, so that's a non-starter as well.

If this is integrated into the bridge though, maybe you could detect when someone connects a new mastodon account to an existing twitter account?

**Comment by Gargron** [comment]
@nightpool I'm assuming this is a feature request for mastodon-bridge

**Comment by nightpool** [comment]
Yeah, we should maybe move discussion over to that repo.

**Comment by trwnh** [comment]
wrong repo, also bridge.joinmastodon.org is long-dead since twitter revoked API access for mastodon/gargron
