### ISSUE TITLE
Searching URL of un-federated old posts makes the posts count mistakenly +1

### ISSUE THREAD

**Issue by SerCom-KC** [mastodon/mastodon#6070]
Suppose I'm `a@exampleA.com` and I just followed `b@exampleB.com`
Now posts counter of `b` on both sites shows the same value (say, `40`)
Current version of Mastodon won't fetch `b`'s posts prior to `a`'s following (I'll call it "old posts" here), which is expected;
But when `a` searches one of `b`'s un-federated old posts using post's URL on `exampleA.com`, **posts counter on `exampleA.com` immediately plus 1 (so now it's `41`), while `exampleB.com` remains the correct value `40`**.
Search the same post again won't plus 1; however, when searching another un-federated old post, exampleA.com plus 1 again.
I hope I made myself clear, as I've tried with several accounts; Of course, none of those `b`s posted anything new (or deleted anything) during this process.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
This will get fixed the next time post numbers are re-fetched. In the
meantime, I don't know if there's any way to fix this that doesn't incur
the cost of another http round trip

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
