### ISSUE TITLE
when "Reply to thread" is clicked, scroll automatically to composition column even if other users are mentioned in the thread

### ISSUE THREAD

**Issue by cphuntington97** [mastodon/mastodon#6079]
Click "Reply to thread." As long as the user clicking is the only user mentioned in the thread, the ui will scroll automatically to the composition column. This is very helpful.

However, if any other users are mentioned in the thread, the ui will not scroll automatically.

**Comment by Cassolotl** [comment]
I noticed this yesterday but thought it was my browser or a peculiarity of my instance. Thank you!

**Comment by cphuntington97** [comment]
Likewise; I don't have sophisticated testing ability so I appreciate the confirmation, @Cassolotl!

**Comment by trwnh** [comment]
seems to be fixed in the past 5 or so years
