### ISSUE TITLE
[Bug] Certain videos will play audio-only

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#6083]
On mastodon.social, I just had this interaction: https://mastodon.social/@vertigo/99215270208748225

It seems that Vertigo tried to manually transcode a video from 1280x720 to 720px wide in kdenlive, with some interesting results. The 720x404 video uploaded to mastodon.social does not seem to play the video; instead, a frozen thumbnail is shown while only the audio plays. HOWEVER, the original version on archive.org plays back without issues.

This is the first time I have seen a video NOT play properly on Mastodon, so I did some investigation by downloading the two video files and comparing their codec information side-by-side. I discovered that the following:

* archive.org version: 1280x720, .mp4, AVC, H.264/aac
* mastodon.social version: 720x404, .mp4, MPEG-4, H.263/mp3

The relevant bit seems to be that Vertigo output their video to H.263 somehow. While the obvious workaround would be to ensure that all videos are exported to H.264 instead, the alternative option is to make use of [libavcodec](https://en.wikipedia.org/wiki/Libavcodec) in ffmpeg to properly support playback of a wide variety of codecs.

Not sure what needs to be done to fix this, but posting this for someone smarter than me to figure out what needs to be done.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this). -- 2.1.0 as of this writing

**Comment by vmstan** [comment]
Is this a behavior you still see @trwnh

**Comment by trwnh** [comment]
Seems to no longer happen, i imagine the media processing has changed several times over in the past 7 years...
