### ISSUE TITLE
Toot stats are not always up-to-date

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#6113]
Despite being favourited, this toot shows a 0 next to the star:

![screen shot 2017-12-27 at 11 05 33](https://user-images.githubusercontent.com/6607512/34379936-ef3cd638-eaf5-11e7-813c-fed37db137ea.png)

Clicking the timestamp to open the toot in a new tab shows the correct info on the toot's own page.

If you wait long enough, somehow the numbers do eventually update. I think it might show the numbers that were visible when the toot was first loaded in the last column?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
Maybe related to *Boost and favourite count are out of sync #3166*?

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
