### ISSUE TITLE
Show the real reason for connection errors due to instances being on a block list 

### ISSUE THREAD

**Issue by ckeen** [mastodon/mastodon#6122]
This is a feature proposal for a better user experience. When admins put an instance on their block list, and I as a user still follow users there, they will just drop off my timeline without me noticing it. If I direktly want to contact them I get a cryptic 500 server error.

It would be helpful when I could see the real reason for connection failure.

I have been discussing this with people at the 34c3 mastodon meetup and I clearly would not want this for blocking of individuals as we do not want to single out individuals. But if whole instances are disconnected from the instance federation I as a user would like to know that via a more helpful error message.

**Comment by lostinlight** [comment]
In my boldest dreams Mastodon architecture ensures all admins make their instance blocklists public, in one common place (/About page?) That would make this whole process transparent. 
Not sure whether this is possible?

Right now some admins publish silenced / suspended instances on 'About' page, or in a GitHub repo, or via random link one should know, or don't make the info public at all.

**Comment by deutrino** [comment]
@lostinlight see #3874

**Comment by mjankowski** [comment]
Does the ability to publish moderated servers list on about page in some way mitigate this ... or still need for API-level or UI-level information about what happened?

**Comment by trwnh** [comment]
was the pr for "notify of relationship severance events" merged? i think that would address this

**Comment by trwnh** [comment]
i think this can be closed by that then
