### ISSUE TITLE
Resource not found when following (with no WEB_DOMAIN set)

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#6135]
I only have LOCAL_DOMAIN set in my production environment on snabeltann.no, and everything is on the same domain, yet I am still getting 404 Resource not found when I attempt to follow the account @thor@snabeltann.no from mastodon.social. The webfinger URL seems to work just fine when I access it from my browser.

My instance is running Mastodon v2.0.0.

Similar ticket here, but that guy had WEB_DOMAIN set: https://github.com/tootsuite/mastodon/issues/5765

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
hmm, works from my instance....

**Comment by ThibG** [comment]
Does that still occur?

**Comment by trwnh** [comment]
closing this issue as stale; if it can be reproduced in current versions, then it can be reopened (or a new issue filed)
