### ISSUE TITLE
Feature request: getting a large number of statuses in a single api request

### ISSUE THREAD

**Issue by codl** [mastodon/mastodon#6136]
I run a service that needs to keep track of a large number of statuses and I keep running into rate limits because checking the continued existence and the updated fav/reblog counts of N statuses requires N requests.

I'd like to request for a way to look up a large number of statuses by id in a single api call. Perhaps `/statuses/:id` could accept a list like `/statuses/123,456`, or perhaps there should be a separate endpoint. Twitter, for example, has [`/statuses/lookup`](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-statuses-lookup)

**Comment by Gargron** [comment]
Such an endpoint would still be limited to maybe 100 or 200 results max, because fetching a lot of statuses from the DB *is* costly.

**Comment by codl** [comment]
Of course. Twitter's equivalent is limited to 100 statuses per request

**Comment by codl** [comment]
i think #27871 does this?

**Comment by trwnh** [comment]
Indeed it does!
