### ISSUE TITLE
deleted accounts should be filtered from searches on the instance

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#6137]
@Gargron deleted my account on mastodon.social earlier in 2017.
Now I found that if you are logged in at mastodon.social and you search for '@ng0' a couple of accounts pop up, including the deleted one at mastodon.social.

If it's possible deleted accounts should get some kind of "tag" or "category" to allow filterin them out of search results by default. Listing them is useless as they are effectively useless (no longer used, bit rotting, no access possible).

Searches from other instances (for example: mastodon.sdf.org, toot.cat) do only list the local one + the ones they have access to in their world view. They do not display the deleted account at mastodon.social.

**Comment by Cassolotl** [comment]
Related to *Deleted accounts still show up as followable on search bar #6054*.

**Comment by jpdeplaix** [comment]
Any updates on this ?

**Comment by Gargron** [comment]
Deleted accounts don't show up in search. However, accounts that were deleted a long time ago did not federate the deletion so they do show up. They will keep doing so until the instance admin runs a special maintenance rake task to check & purge them. Not a code issue.

**Comment by kit-ty-kate** [comment]
@Cassolotl I don't understand your question. @Gargron said that should be handled automatically (via protocol ?), why would we need a rake task ?

**Comment by Cassolotl** [comment]
@kit-ty-kate Oh I see, sorry, I misread - I didn't realise the account that's coming up in searches was deleted very recently. My mistake!

**Comment by kit-ty-kate** [comment]
ping @Gargron ?

**Comment by ThisIsMissEm** [comment]
I think this could be related to #7246 — i.e., it isn't filtering out deleted accounts from the results.

**Comment by trwnh** [comment]
i can't replicate this anymore. if anyone can, please file a new issue
