### ISSUE TITLE
deleted accounts need more restriction (should not be allowed to reset password and login)

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#6139]
Out of curiosity I've tried to log into my deleted account at mastodon.social.

I was able to reset the password, set a new one and log back in.
The login lead to an error page, which is expected.

As a user you should not be allowed to login to an deleted account and reset its password.
There is no data you could access and no functionality you could make use of.

**Comment by Gargron** [comment]
Hmmm. Deleting your account removes the "user" record (email/password) so this shouldn't be possible at all. Are you sure your account was previously deleted by yourself, using native functionality rather than console/db access by your admin, and that it wasn't merely suspended?

**Comment by ng-0** [comment]
I think it was still manual back then (early 2017, late 2016) as described in #6137 

So my error description does not match what usually happens when you try to interact with an deleted account as it is deleted today (via user interface, not via console/db access by the admin)?

**Comment by mjankowski** [comment]
Going to close this on assumption that last few comments clarified things and the original issue does not exist as described, please reopen if Im missing something...
