### ISSUE TITLE
Combine CW and Hide Media

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#6141]
dev.glitch.social has it, and now awoo.space has it too, and it is really good! Reasons I like it:

- No big black rectangles filling up your timeline, but it's still obvious when there's an image to see.
- Clicking "show less" re-hides the media, when it doesn't in vanilla currently. (See also #4399)

Also I just find the whole thing quite intuitive.

![cwhidemedia](https://user-images.githubusercontent.com/6607512/34463975-bffd675c-ee65-11e7-87d7-3b67a682cad6.gif)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
Relevant: https://github.com/tootsuite/mastodon/pull/10563

**Comment by Cassolotl** [comment]
There's some discussion of this issue going on [here](https://mastodon.social/@Gargron/102009438065570259) on m.s, if anyone is into that. :)

**Comment by noiob** [comment]
bump, this has been in glitch-soc for ages and there's no good reason not to have it

**Comment by trwnh** [comment]
Other clients like Subway Tooter also have this behavior by default. Both media and polls are hidden behind the CW, along with the post content.

**Comment by ClearlyClaire** [comment]
The CW design changes in 4.3 address this.

**Comment by Cassolotl** [comment]
Finally! :D Thank you!
