### ISSUE TITLE
Timelines don't load more toots when all recent toots are filtered out

### ISSUE THREAD

**Issue by duxovni** [mastodon/mastodon#6208]
My local timeline has a lot of #nowplaying toots, so I sometimes filter them out. However, if a lot of the recent toots hit the filter, I just see an empty timeline with the "your timeline is empty, toot something to get the ball rolling" message, or a timeline with just one or two toots and a "load more" button. It'd be good if we automatically loaded more toots in this case, especially if all of the already-loaded toots are filtered out (in which case there isn't even a "load more" button)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Cassolotl** [comment]
>It'd be good if we automatically loaded more toots in this case, especially if all of the already-loaded toots are filtered out (in which case there isn't even a "load more" button)

Just thought I'd link this issue: * "Show more" link does not appear if the column is empty #558*

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
