### ISSUE TITLE
Emoji insertion: Spaces should be added

### ISSUE THREAD

**Issue by gandaro** [mastodon/mastodon#6220]
When I type `Hello` into the compose box, without trailing whitespace, any emoji that I picked from the emoji picker will be inserted right after `Hello`, without a space added in between. This creates a problem with custom emojis, because, for those, not a Unicode character but the shortcode is inserted, like this: `Hello:blobpats:`. Because short codes must have leading whitespace, the emoji will not be rendered after tooting this out.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by dariusk** [comment]
I know this is an old issue but I've resolved this locally by adding a zero-width space after emoji. This lets you type `Hello` and pick an emoji, custom or not, and have it render correctly. It also means that if you pick 10 custom emoji in a row on the picker, it will be encoded as `:ce_1:<0ws>:ce_2:<0ws>:ce_3:<0ws>`, where `<0ws>` is a zero-width space character. This means they render in a way that looks correct to a human.

The downside is you have to delete an "invisible" character if you choose to backspace through all those emoji inserted with the picker.

My users have enjoyed this feature for about year now and I haven't gotten any complaints about backspace. I'm happy to make a PR if that seems like a good idea.

**Comment by trwnh** [comment]
seems to be fixed now?
