### ISSUE TITLE
Adding captions to images makes the form recreate itself, causing keyboard nav issues

### ISSUE THREAD

**Issue by Xkeeper0** [mastodon/mastodon#6239]
When adding a caption to an image, the form recreates itself. The easiest way to see this is to do the following:

* Add an image
* Click the caption field
* Type something
* Try to interact with the form

Expected behaviors:
* Keyboard: Tab focuses the next element, shift-tab focuses the previous element
* Mouse: Clicked element receives focus/is activated

Observed behaviors:
* Keyboard: Focus *resets* to the textbox. (To resume captioning images, you now have to cycle through *all* of the images you've captioned, instead of being able to progress to the next one) ...  e.g. Write caption, tab, focus resets to text box, tab (emoji), tab (image remove), tab (caption), tab ...
* Mouse: Focus is removed from whatever and the element you clicked on is not activated. e.g. if you set a caption and then click "Toot", most of the time the toot will not post and you have to click it again.

(I searched for "keyboard" and "caption" and saw nothing.)

**Comment by Cassolotl** [comment]
I've seen another report of this bug, but yours has more detail about what happens, how to recreate it, etc. so this should stay open, I think. (I can't find the other one but when I do I will link to this one.)

**Comment by trwnh** [comment]
images are now captioned in a separate modal, so this issue is stale
