### ISSUE TITLE
[Feature Request] change frontend language JavaScript to TypeScript  

### ISSUE THREAD

**Issue by rinsuki** [mastodon/mastodon#6267]
> TypeScript is a language for application-scale JavaScript. TypeScript adds optional types, classes, and modules to JavaScript. TypeScript supports tools for large-scale JavaScript applications for any browser, for any host, on any OS. TypeScript compiles to readable, standards-based JavaScript. 

from [TypeScript README](https://github.com/Microsoft/TypeScript/blob/master/README.md).

TypeScript is a very good language(this is my subjectivity), and compatible with React and JSX.
Also, even if JavaScript and TypeScript are mixed, it works well, so you can change on little by little.

sorry for my not good english.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by deutrino** [comment]
What is the benefit to be gained when compared to the cost in developer labor?

This is probably more appropriate for a fork or a brand new client.

**Comment by voronoipotato** [comment]
Honestly you can do typescript checks for javascript. I don't know if I would say it's appropriate for a fork or a new client but probably less appropriate for active devs. Someone could likely come in with little understanding of the project and port it over. I also don't know if this is the right time to do this as mastodon seems to be going through some growing pains in terms of issues / pull requests
