### ISSUE TITLE
[Feature/Improvement] combined searches for tags (and users?)

### ISSUE THREAD

**Issue by raingloom** [mastodon/mastodon#6287]
Currently one can only search for a single hashtag or search for accounts.

At the very least it should be possible to combine tag searches. It doesn't even need special search syntax, something like this could work: `#tag1 #tag2`

Since tags can't have whitespace, it's easy to decide where tags start.

Extending on that, we could have `@user@instance.examle #topic` if you want to read posts by a single user.

Extending that even further, we could have `and` and `or` operators. If there is no full text search, only tag and user search, then that can be as easy as: `@user #tag1 or #tag2`

I think this should be read as: `(@user and (#tag1 or #tag2))`

And if we have operators, we should have parentheses, so the previous example should also be legal.

Implementation-wise, it's just:
 - write search parser: should be simple as long as there is a tool like LPEG available for Ruby (I'm pretty sure there is)
 - write the `and` and `or` functions: results are already ordered by time and implementing set operations for ordered lists is very easy and they run efficiently

**Comment by Cassolotl** [comment]
Related to *Join several hashtags in a search/column #6359*.

**Comment by spaceottercode** [comment]
I also would love to see this. Only thing I would add is, if and once `and` and `or` are added, add a `not` as well.

**Comment by tryloke** [comment]
Also, perhaps even better would be to use symbols instead of words: `&`, `|` and `!`. 
also it would be nice to be able to search plaintext. Though I understand if that's a long way off...

**Comment by Cassolotl** [comment]
>it would be nice to be able to search plaintext

This was considered and ruled out for anti-harassment reasons.

**Comment by tryloke** [comment]
anti-harassment!? I really don't understand the logic. isn't the purpose of mastodon about finding and spreading ideas? I just don't see how harassment concerns could outweigh a basic feature like this. I kind of had assumed this limitation was due to some reason like keeping low server overhead on the fediverse, and  i am very surprised to learn that this is the real reason! Not having this feature makes it harder for me to use Mastodon. Without his feature I don't know if someone else has tooted something already, it also makes it hard to find like minded people. Scrolling though individual #tag results is an incredibly inefficient way to find out if something has been said before...

**Comment by tryloke** [comment]
reading my own post just now, I feel like i should acknowledge twitter can be very toxic, and perhaps there is something to the idea of not searching plain text. 

Still, It would be very helpful to be able to search multiple #tags at once! I think this small enhancement would really go a long way to improving usability(at least for me*winky-face*).

**Comment by CarwilB** [comment]
For the love of all that is beautiful, yes!

Acknowledging that some might want to keep both their profile and their untagged content out of searches, I duly wrote an introduction Toot with many hashtags, but I still can't use the procedure to find people with common interests… That is, I can't search for "#Introduction #rstats" and find other like-minded users.

**Comment by KazuShuSora** [comment]
I'd love to see this feature, too!
The search feature being limited to one hashtag at once is really inefficient and doesn't really serve the purpose I'd want it to use for.

If this feature was added, I could throw e.g. combine a lot of gaming related columns to one "big" combined column which would save me the hassle of clicking through all the tags manually and a lot of space on my monitor.

**Comment by spaceottercode** [comment]
I would love to see this feature too 🙏

**Comment by biasto-bias** [comment]
I would love this!!

**Comment by igorlogius** [comment]
Would be very helpful to find toots of interest.

**Comment by rric** [comment]
+1

Use case: `#genuary #python` ... people are posting a lot of generative art samples using `#genuary`, and I'd like to filter those done in `#python`.

**Comment by brendanjones** [comment]
I'd like to see this expanded to include far more search operators. If necessary to keep development scope down then sure, start only with boolean operators, but eventually it'd be great to have other operators such as `from:` (show only posts from the mentioned account). I hate to link to Twitter but they have a useful list: https://developer.twitter.com/en/docs/twitter-api/v1/rules-and-filtering/search-operators. 

See the screenshots if you don't want to click the link. I've added a 'no' to any that we *definitely* wouldn't or couldn't do here on Mastodon:

![Screenshot 2023-07-10 at 15 30 57](https://github.com/mastodon/mastodon/assets/16049594/0721865c-b5fc-4c98-9297-3f14a0e4f3fe)
![Screenshot 2023-07-10 at 15 31 07](https://github.com/mastodon/mastodon/assets/16049594/98f36241-0531-4de8-8b2b-3c4fe05f9601)

**Comment by renchap** [comment]
The new search system implements most of this. Please open new issues for specific features / operators that you would like to have and do not exists.

**Comment by spaceottercode** [comment]
@renchap could we please keep this issue open or have it filed as will not implement.

Given the original request:

 (A) At the very least it should be possible to combine tag searches. It doesn't even need special search syntax, something like this could work: #tag1 #tag2

(B) Extending on that, we could have @user@instance.examle #topic if you want to read posts by a single user.

(C) Extending that even further, we could have and and or operators. If there is no full text search, only tag and user search, then that can be as easy as: @user #tag1 or #tag2

(D) And if we have operators, we should have parentheses, so the previous example should also be legal.

Feature (A) isn't implemented. I imagine (B) is but I would have to check. As for (C) and (D), do you know if they are implemented?

PS I'm not expecting C & D to be implemented but if they are that's awesome.





> At the very least it should be possible to combine tag searches. It doesn't even need special search syntax, something like this could work: #tag1 #tag2

I am unsure the new search system fulfils the original intent.

**Comment by spaceottercode** [comment]
@renchap ok I just checked feature (B) and it too does not meet OP's request. So unless there is additional unrelease code that has not made its way into the flagship instances, searches remain text centric and to some extent tag agnostic.

**Comment by Gargron** [comment]
The syntax is `from:user@domain #hashtag`

**Comment by spaceottercode** [comment]
@Gargron I tried that but it also matches posts containing the text "hashtag". For example,

`from:user@domain #test` will also match posts from user `user@domain` containing `testing` not just those tagged with `test`.

It seems the search is for the text "test" in posts from `user@domain` 

Take this silly/absurd example: create a post like,
```
silly absurd#test 

#tag1 
```

We know `silly#test` is not a tag, that it's pure text, yet the following search with match:

'#test #tag1`

I thought this was doing a tag search but it appears its a text search. Query matches the silly post and one post containing "testing".

I will run some further tests.

PS it's ok if this feature isn't implemented. I just want to make sure this ticket isn't inadvertently closed.

Thanks

**Comment by spaceottercode** [comment]
The search system isn't truly tag-aware. 

Other oddities: searching for something like `#tag20` matches post containing the text `tag` (not the hashtag `#tag20`) and (more surprisingly) posts containing the text `20`, `2020`, `#foo2020`, etc.

so, yeah, in my opinion, I don't think the current changes satisfy the goals of this request.

tested on mastodon.online running v4.2.0-nightly.2023-09-06

**Comment by Gargron** [comment]
It is tag-aware, when your term begins with `#` it will *only* match on the hashtags, not body. But looks like `#tag20` will match any hashtags that have a `20` as a component, the match isn't strict enough.

**Comment by natsume-shokogami** [comment]
My instance (mastodon.world) recently added full-text search, but the search don't aware of searching for multiple hashtags. For example, when I typed "#steamdeck #linux", I expect post results with both hashtags, the the search show no post at all. I think that would still be nice to be able to search multiple hashtags without using advanced interface since it's confusing for many people, and it is also good for instances which don't have ElasticSearch/OpenSearch installed and full-text search enabled too.

**Comment by Gargron** [comment]
Currently even if you search by hashtags it only brings up results from people opted into search indexing (contrary to e.g. going directly to a hashtag timeline). This will be addressed in 4.3.

**Comment by spaceottercode** [comment]
@natsume-shokogami I can do multi-tag search now, but there's some very weird things at play @Gargron 

Searching for 
```
#steamdeck #linux 
```

returns no matches....but....would you have guessed that

```
#SteamDeck #linux
```
does?!

![20230919_224619](https://github.com/mastodon/mastodon/assets/36016546/ba7f288b-8e6f-49a1-9df0-bc59920a1dde)
![20230919_224641](https://github.com/mastodon/mastodon/assets/36016546/c9fae5e9-14b9-44ab-9d0c-b29b04c195eb)

moreover when I search for:

```
#linux #python
```
there's this inexplicable hit:

![20230919_225016](https://github.com/mastodon/mastodon/assets/36016546/2da8a9d5-21c9-4d1e-a0e4-e77673e2163c)

I must be blind.

**Comment by Gargron** [comment]
The last one is because of `#atareaoConLinux`

**Comment by spaceottercode** [comment]
> The last one is because of #atareaoConLinux

Sorry. I guess I was expecting a stricter match: a tag only containing the characters `linux` (case insensitive).

But in the search below, I see a search for `#deck` in post also matches `#SteamDeck` and `#steamdeck`.

![20230919_232026](https://github.com/mastodon/mastodon/assets/36016546/80c83060-7ffc-4093-bada-072cb67010e4)

**Comment by brendanjones** [comment]
> The last one is because of `#atareaoConLinux`

Ohhh I would have expected hashtag searches to only return exact matches, not any hashtag containing the word. Hmmm. If I and Spaceottercode aren’t alone in this assumption, this could be confusing for people.

**Comment by travisfw** [comment]
Wishing for this. Please reopen.

**Comment by jadedgnome** [comment]
why can't post searches work for non-account users?
