### ISSUE TITLE
Cannot access Atom feeds from Javascript (CORS issue)

### ISSUE THREAD

**Issue by CaptainSpam** [mastodon/mastodon#6329]
I'm working on a simple StatusNet (GNU Social, Mastodon, etc) Javascript widget, so one could, for instance, embed a StatusNet feed into a website.  It's mostly for my own use on my own server, but I'm trying to make it as useful as possible for people with other setups than I use.

The way I have it set up, you give the widget an Atom feed, it downloads it, and it formats the posts.  This works fine on my GNU Social setup, but it fails on any Mastodon instance I try it on, owing to the Atom feeds not being sent with Access-Control-Allow-Origin headers.  Javascript refuses to do anything with that for (very good) security reasons.

I'll admit I haven't done much work involving Javascript reading data from remote APIs like this, so this may seem like a naive question, but is there a specific reason why Mastodon doesn't return that header when fetching a user's Atom feed?  And if not, would it be possible to update it to do so?

I'm not currently running a Mastodon instance; this is just from the perspective of a developer reading data from a feed.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by unarist** [comment]
Note that browsers won't send credentials (i.e. cookies) on cross-origin requests unless the server allowed explicitly via `exposes Access-Control-Allow-Credentials` header. Also we've already allowed basic CORS on some routes including REST APIs.

https://github.com/tootsuite/mastodon/blob/69f13e7bca90f4855e05a49dd69bba66f843134a/config/application.rb#L81-L88

**Comment by vitalyster** [comment]
Same issue for ActivityPub endpoints

**Comment by measlytwerp** [comment]
Same issue for the status embed endpoint.

For example: https://fosstodon.org/@measlytwerp/100568808235949213/embed

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
