### ISSUE TITLE
Scrolling instead of pages in public views

### ISSUE THREAD

**Issue by moshpirit** [mastodon/mastodon#6362]
When we read other people timelines on their servers the toots are loaded in pages and not in just one page that loads (btw there's only "Next" button but not "previous" button (checked with mastodon.social)) more messages when we come to the end, I think it would be better to do this just like it happens on the "Tootdeck" interface.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ThibG** [comment]
There is a “previous” button now.

**Comment by charlag** [comment]
I think Mastodon tries to keep these pages mostly JS-free. You cannot have infinity scroll without JS.
Also infinity scroll if bad for accessibility and I think these pages serve different need.

**Comment by trwnh** [comment]
If JS is enabled then pages should load more content on scroll; if JS is disabled then prev/next links should be presented instead.

**Comment by trwnh** [comment]
public views have been removed since v4.0 so this issue is now stale
