### ISSUE TITLE
Suggestion to be able to save searches

### ISSUE THREAD

**Issue by chrisddumont** [mastodon/mastodon#6379]
It would be nice to be able to save searches for future use.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by chrisddumont** [comment]
I realize that I can pin a search, but it would still be nice. :)

**Comment by mjankowski** [comment]
We are now at ~6 years without a reply here which makes me suspect it's not anyone's utmost priority ... do you want to keep this open, or is pinning sufficient?
