### ISSUE TITLE
[Feature] Diagnostics Page

### ISSUE THREAD

**Issue by jebuskrust** [mastodon/mastodon#6387]
Would be nice to have a section in the admin page that shows what version of ruby, etc, is powering the running instance. Similar to something like php's ` <? PhpInfo(); ?>` for outputting the version of php and present running/configured extensions.

Thanks

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
should be added https://github.com/mastodon/mastodon/blob/679aca46da56228a3219d1c6f0c942adcfb8fdb1/app/lib/admin/metrics/dimension.rb#LL9C15-L9C15
