### ISSUE TITLE
API requests from Web Client failing

### ISSUE THREAD

**Issue by thegcat** [mastodon/mastodon#6405]
I have a few 422s due to the requests not being authenticated. I have noticed this for `/api/web/push_subscriptions` and `/api/web/embed`, it fails on the instance I administer (on 2.2.0), though for example not on mastodon.social.

I have tried analysing the differences between the working requests to mastodon.social and the failing requests to our instance, and I have noticed that the `Bearer` Tokens for the authentication are missing. I'm at a loss here on how to debug this further, could someone point me in the right direction? Might this be due to our web domain being different from our local domain?

Thanks.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
closing this issue as stale. if anyone can reproduce it, please file a new issue.
