### ISSUE TITLE
sessionStorage is null

### ISSUE THREAD

**Issue by NoNamesLeft59633** [mastodon/mastodon#6452]
I was able to log on to Mastodon for a while, but eventually I got a type error: sessionStorage variable is null whenever  I logged in. I don't know what changed to cause that. 

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by ProgVal** [comment]
Hi,

I can provide more insights into this issue, thanks to a user who reported it on IRC and helped me troubleshoot it.

The error happens on one of those lines:

```
node_modules/scroll-behavior/lib/index.js:    this._stateStorage.save(this._getCurrentLocation(), key, [(0, _scrollLeft2.default)(element), (0, _scrollTop2.default)(element)]);
node_modules/scroll-behavior/lib/index.js:    return this._stateStorage.read(location, key);
```

`this._stateStorage` is defined as `new SessionStorage()` in `node_modules/react-router-scroll-4/lib/react-router-scroll-4.js`.

However, in some browsers, including Tor Browser, `new SessionStorage()` seems to return `null`.

Therefore, calling methods of `this._stateStorage` fails. It makes it impossible to use Mastodon's web UI.

I wanted to report the issue to [`react-router-scroll-4`](https://github.com/ytase/react-router-scroll), but they have no issue tracker...

Also, this bug happens on 2.3.3, and started happening after an instance upgrade (from an unknown version).

**Comment by nightpool** [comment]
https://github.com/taion/react-router-scroll/issues/52 may be the best
place to report this

**Comment by ProgVal** [comment]
According to npm's website, that repo is not the one used in the package

**Comment by trwnh** [comment]
closing this issue as stale; if it still occurs, please comment so the issue can be reopened.
