### ISSUE TITLE
Federation: WebFinger request does not have Accept header set

### ISSUE THREAD

**Issue by aral** [mastodon/mastodon#6492]
From Mastodon v2.1.0, I’m seeing WebFinger requests that do not have an Accept header set to `application/jrd+json`.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [2.1.0](https://github.com/tootsuite/mastodon/releases) – cannot test on latest release right now due to #6491

**Comment by JMendyk** [comment]
@aral Since #6491 has been solved, could you please verify that WebFinger requests don't have Accept header set to `application/jrd+json` in some cases? Additionally, could you share some requests that lack this header?

**Comment by trwnh** [comment]
appears to be fixed https://github.com/mastodon/mastodon/blob/679aca46da56228a3219d1c6f0c942adcfb8fdb1/app/lib/webfinger.rb#L99
