### ISSUE TITLE
API to get IDs of deleted toot

### ISSUE THREAD

**Issue by tateisu** [mastodon/mastodon#6549]
In case of Single Page Application, app always read stream for delete event for TL of loaded toots.
But in case of mobile Application, app may go background or sleep, and restore with TL of loaded before, then app can't get delete event while background or sleep and it shows TL with deleted toot.

It would be nice that server has table of (deleted time, status_id, account_id ), and provides API to get it with pagenation by deleted time.

- it may filtered for authorized user.
- it may filtered for non-login client.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by tateisu** [comment]
It's also helpful for some external services that uses stream of public TL and that is NOT read home/notification stream.

**Comment by SoniEx2** [comment]
Just re-request the toots?

**Comment by tateisu** [comment]
do you say about reload ALL toot those clients already have? nonsense.

**Comment by SoniEx2** [comment]
I'm saying re-fetch metadata for each loaded toot, yes.

**Comment by tateisu** [comment]
Application sometimes has many statuses. 
It can reach several tens of columns to several thousand totes.
also if Application is a kind of external toot search service. statuses may be permanently saved.
reloading it is not make sense.

**Comment by codl** [comment]
#6136 might help in checking the existence of a large number of statuses

**Comment by tateisu** [comment]
do you say about reload ALL toot those clients already have? nonsense.

**Comment by SoniEx2** [comment]
I'm surprised you don't give a shit about star/repeat counts.

**Comment by tateisu** [comment]
I am taking actions according to complaints from users of my application. Although claims regarding reflection of deletion are coming, there are no complaints about Fav / BT count. Perhaps because those counts are not inherently accurate (especially for remote status).

**Comment by tateisu** [comment]
For mobile applications, reloading all the toot every time it gets in the foreground has difficulties with battery, data usage, and API rate limit.
In case of an external toot search service, it has many toots, so reloading all of them periodically has difficulty loading the instance.

**Comment by SoniEx2** [comment]
If the service is external, why are you running it on the phone?

Run it on a server, run a cache on the server, then provide a lightweight API for phones.

Also, how do you handle users getting blocked? Don't you need to refresh the status then?

I like to believe everything involves refreshing statuses and caching and so that's how you should just do it.

**Comment by tateisu** [comment]
mobile applications and external service are independent cases.
These are not related each other.

I will not discuss about blocks, it's not focus on this issue.

**Comment by Gargron** [comment]
Hey @SoniEx2 please stop. "You don't give a shit about x" is not a good thing to say to someone you don't know in a professional setting. You are not a developer or contributor of Mastodon and you cannot represent the project.

I understand @tateisu's problem, but I am not sure if that's something we should solve. I am not aware of any precedents in other APIs. For example, Twitter also sends delete messages over their streaming API. But I don't think it "catches up" the deleted messages after you connect. While apps may cache content for a long time, it's not permanent. For the web UI, it's an eventual browser refresh. Mobile apps also have to evict cache at some point to not grow infinitely in size.

**Comment by tateisu** [comment]
If you think that functionality is unnecessary, why did you make it available only during streaming reception?

**Comment by mjankowski** [comment]
Closing as not planned due to no updates in ~6 years and implication of feedback that "refresh" or "cache evict" are the ways to handle.

Separately, basically all the APIs have evolved a bit since original creation here ... if there's still compelling need that's not otherwise solved, please describe!
