### ISSUE TITLE
Mastodon removes final dot at the end of my link

### ISSUE THREAD

**Issue by MyNameIsTroll** [mastodon/mastodon#6701]
When I paste a link with a (dot) at the end of the link, when I click on my link mastodon remove the (dot) and do not redirect me to the right page. 

Example, I put this link: https://fr.wikipedia.org/wiki/Ministère_A.M.E.R. 
mastodon shows me the full link in the toot but when I click on the link, mastodon sends me back to a fake page because it removes the final point of my link.

EDIT: It's the same on github >_<'.

![screenshot-2018-3-8 ministere a m e r wikipedia](https://user-images.githubusercontent.com/31790025/37173022-c6df9a7c-2312-11e8-8ce8-d1595663c241.png)

![screenshot-2018-3-8 ministere a m e r wikipedia 1](https://user-images.githubusercontent.com/31790025/37173032-cb13530e-2312-11e8-8885-8a78748c7aff.png)

**Comment by JohnD28** [comment]
You can use url tag on github "[text](your url with dot)" : 
[https://fr.wikipedia.org/wiki/Minist%C3%A8re_A.M.E.R.](https://fr.wikipedia.org/wiki/Minist%C3%A8re_A.M.E.R.)

**Comment by nightpool** [comment]
You'll have to url-encode your link to get the right output:

`https://fr.wikipedia.org/wiki/Minist%C3%A8re_A%2EM%2EE%2ER%2E`

see:

https://fr.wikipedia.org/wiki/Minist%C3%A8re_A%2EM%2EE%2ER%2E

**Comment by unarist** [comment]
This rule was imported from Twitter, and it's intended to avoid capturing final dot on the end of sentences, like "You can see an example page on http://example.com/test."

Another workaround is appending `#` to the end of the URL:

`https://fr.wikipedia.org/wiki/Ministère_A.M.E.R.#`
https://fr.wikipedia.org/wiki/Ministère_A.M.E.R.#

and looks like wrapping with `<` and `>` also works on Github, but this won't work on Mastodon:

`<https://fr.wikipedia.org/wiki/Ministère_A.M.E.R.>`
<https://fr.wikipedia.org/wiki/Ministère_A.M.E.R.>

**Comment by MyNameIsTroll** [comment]
@unarist  Thank you for these tips and explanations:)
