### ISSUE TITLE
Move compose column back to tab bar on tablets

### ISSUE THREAD

**Issue by zcdunn** [mastodon/mastodon#6727]
Please move the compose column back on tablets. I would prefer the removal of the FAB completely, but especially on tablets where there's less space constraints. The removal of swipe functionality between the compose/home columns reduces usability of the app for no gain.

**Comment by Gargron** [comment]
Don't tablets show the non-mobile layout?

**Comment by zcdunn** [comment]
No

![screenshot_20180311-122808](https://user-images.githubusercontent.com/7121969/37255799-9383d592-2549-11e8-8348-e91f069b5d17.png)
 This is a screenshot taken on an 8 inch Nvidia Shield tablet

**Comment by zcdunn** [comment]
![screenshot_20180312-185704](https://user-images.githubusercontent.com/7121969/37314021-34239d8c-2628-11e8-9ec5-e9062c93831e.png)


The FAB should also be removed when viewing a thread. In the above screenshot, the post at the bottom is covered and, since it's the last in the thread, it can't be scrolled into view.

**Comment by zcdunn** [comment]
The FAB also shows up on the profile page which implies pressing it would mention the user you're viewing. But this isn't the case, and it could be confusing

**Comment by kjhoerr** [comment]
@zcdunn I like the contextual idea. Maybe in a thread it defaults to replying to the highlighted toot.

Personally, I find it distracting when I'm scrolling down - I'd prefer it be hidden when scrolling down and appear when I'm scrolling up. Otherwise it's obstructing my view of what's appearing.

**Comment by zcdunn** [comment]
Bump. This is still an issue. And even on a phone it's still a constant annoyance when I perform searches and can't swipe to the home column.

**Comment by nynhex** [comment]
@zcdunn can you do a PR that addresses this?  Or are you requesting contributors/maintainer's help?

**Comment by nightpool** [comment]
this is fixed in #6859

**Comment by nightpool** [comment]
Oh, misunderstood the scope here. I think the fix is that we should use the two-column layout out tablets, which is what i thought the default behavior was? 

i agree that the swiping thing is kind of annoying, i've run into that recently.

**Comment by zcdunn** [comment]
@nightpool I've only used 7-8 inch tablets so I don't know about larger tablets. Small tablets use the single column layout in portrait and multi-column layout in landscape. 

I don't think a different layout is needed. Two columns would be too cluttered. But a floating action button doesn't make much sense on a tablet.

**Comment by trwnh** [comment]
i do believe the breakpoint now is 631px -- advanced UI will show the static sidebar with compose window at that point.
