### ISSUE TITLE
Ability to edit a post

### ISSUE THREAD

**Issue by celesteh** [mastodon/mastodon#6829]
Feature request: I often hit the post button and realised I should have CWed the post.  While I understand there are good reasons related to harassment not to allow people to edit posts, it seems like the ability to add content warnings (iff there are none already there) has mostly good applications. It allows greater sensitivity but doesn't allow people to completely change their meaning - especially as nobody can currently assume their readers are on platforms that support CWs.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by jennifermf** [comment]
There's a request to be able to do this at the moderation level too. I think both would be great.

https://github.com/tootsuite/mastodon/issues/1307

**Comment by Sciss** [comment]
I don't wish to hijack the ticket, but I would think that it would coincide with being able to edit a toot for a minute or two after posting, for any kind of correction, whether it be adding the CW or fixing a typo. I find myself deleting and re-tooting often when I make typos that somehow I don't spot immediately when typing.

**Comment by jennifermf** [comment]
i know that full-on editing is a hot button and a complex issue, but running with it anyway...

gmail has an option to unsend mail for a short time after sending. i believe this works by queuing the email and not sending it right away to wait for that unsend command. (please correct me if i’m wrong.)

is a similar option possible here? can we hold posts in queue for a period of time (60sec? 90sec?) to allow time for that “oh no!” moment and option to fix before it federates out?

and would this be acceptable to people who want the ability to edit toots and add cw’s?

**Comment by metasintactic** [comment]
same. I don't want to hijack the ticket either, but having edit would be good. I'm unsure of the technical hurdles involved, but I even think having a time limit on it should be entirely optional and/or a user configurable setting. delete/retoot is a pita.

**Comment by steckerhalter** [comment]
@celesteh could you rename the issue to just "Ability to edit a post" to make it more general?

ActivityPub includes an `update` [method](https://www.w3.org/TR/activitypub/#update-activity-outbox) which should allow editing a post if Mastodon implemented it.

**Comment by Cassolotl** [comment]
I don't think that's a good idea. #256 is the issue for "ability to edit toots", and it was closed a long time ago because Gargron said in June 2017:

>I understand that it's annoying to find out you made a typo in a toot. And yes, displaying a "last edited by" with all the differences like in git would solve the rogue edits problem wherein somebody converts an innocent toot that got many favs/boosts into something vulgar or offensive. However, given the nature of toots, deleting and re-doing it manually is still a much lesser effort than, in my assesment, it would be to implement such a change tracking system.

This issue is separate because it acknowledges that CWs are a slightly different use case from wanting to fix a typo. CWs may be needed for the comfort and mental health of followers.

**Comment by steckerhalter** [comment]
@Cassolotl I understand, but `update` is part of ActivityPub so I guess it should be supported by Mastodon as well? As for the distinction between CWs and other "edits" I don't think it's much of a difference technically, you'd have to implement `update` either way, but I see your rationale for making the distinction :smile:

**Comment by steckerhalter** [comment]
I have made a new "issue": https://github.com/tootsuite/mastodon/issues/7209

**Comment by steckerhalter** [comment]
@Cassolotl Hmm, I think it's not the same. Mastodon was not using ActivityPub at that time. Also the update method is not supposed to allow undoing toots like #256 requests.

**Comment by Cassolotl** [comment]
Oh okay! Then I take it back. :) It is probably good to say that on your new issue, to make sure it doesn't get closed!

**Comment by nemobis** [comment]
https://github.com/mastodon/mastodon/pull/19103
