### ISSUE TITLE
Deleted toots are not deleted across federation

### ISSUE THREAD

**Issue by kit-ty-kate** [mastodon/mastodon#6849]
*I couldn't find any but if there is an issue about this already, if somebody could point me to it, it would be perfect*

Steps to reproduce:
1) Have two accounts in two different instances
2) Have them two following each other
3) Have one posting something (in my case was a picture)
4) Delete the post
5) Look at the other account TL: the post in still there (reloading the page doesn't change a thing)

Version: 2.3.0 (for both instances)

**Comment by kit-ty-kate** [comment]
Is it to be noted that the toot in question was every time the same picture and text with just a slightly different crop.

**Comment by ThibG** [comment]
This should not happen. Can you still reproduce this?

**Comment by kit-ty-kate** [comment]
Well this happened "once" so far but consistently that one time: I was trying to post something with the same picture and text but with a slightly different "crop" each time and ended up deleting and redoing this post 5 or 6 times. Each time the post was still visible from another instance but not from the one where the post was originating from.

I'll try to do some experiment later this week or I'll try to see if anybody else experienced the same thing.

**Comment by kit-ty-kate** [comment]
It happened again :/

This time I can give you the links to the two posts and also a post where other people are telling me they see the deleted toot:
* Deleted toot: https://social.wxcafe.net/@kit_ty_kate/100164520614875750
* Toot recreated: https://social.wxcafe.net/@kit_ty_kate/100164523271877347
* Other instance point of view: https://social.wxcafe.net/@kit_ty_kate/100165339562691951

The two toots are exactly the same except the first one is a standalone toot and the second is a response to others. Otherwise they uses the same image and text, and the second one got recreated less than one minute after the first one (don't know if it's relevant)

cc @wxcafe just in case

**Comment by MaiaDereva** [comment]
Hello, 
I see the same problem. Toots deleted a long time ago (2019, 2020,...) still appear on other instances where I also have accounts. Curiously, they are not the same toots depending on the instances consulted. How can I exercise my right of deletion according to the GDPR? Shouldn't there be a mandatory purge coded into the software itself to be compliant? See also #14719

**Comment by lapineige** [comment]
Also there is no way to sent the "deletion event" another time if it fails (because of foreign instance not responding, …), right ?
Could that be an admin possibility ?

**Comment by ClearlyClaire** [comment]
> Also there is no way to sent the "deletion event" another time if it fails (because of foreign instance not responding, …), right ? Could that be an admin possibility ?

It's retried a bunch of times, but once every retry is elapsed and the post is deleted, Mastodon stores neither the post's previous existence nor who was supposed to see it, so such a feature would require the admin to provide:
- the post's author
- the post's exact ID
- who to send the deletion notice to

**Comment by lapineige** [comment]
So that's quite complex… author is simple, exact ID can be archived with tools like mastodon-backup, but the last one… on could approximate it for private account by the list of followings maybe ? 🤔

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
