### ISSUE TITLE
Search Function in Web UI has Poor Accessibility and Returns No Results

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#6850]
According to [a blind user using NVDA screenreader software](https://octodon.social/web/statuses/99718973629937162), the web UI's Search function has poor accessibility and returns no results.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by alexstine** [comment]
I noticed the same. Search usability is really bad for NVDA users. I am new to the whole idea of this project, I'll send a PR shortly that should start addressing some of these problems. I'll start with a really simple fix and see where it goes from here.

**Comment by alexstine** [comment]
Looks like other than this enhancement, the following needs to happen.
1. Need to figure out why screen reader users do not have access to the search results overlay.
2. Custom label text may be a nice prop addition for the PR or future PR.
