### ISSUE TITLE
Colour profiles being stripped from JPEGs?

### ISSUE THREAD

**Issue by HywelPhillips** [mastodon/mastodon#6882]
[
I'm very sorry if I'm doing this wrong, I am a newbie running a hosted instance.

It seems like coloursync profiles are stripped from JPEGs when posting, is this correct?

I posted the same pic to birdsite and via Mastodon, and the Mastodon one had its profile stripped away when I saved the file. This seems to be causing colour shifts for non-sRGB JPEGs (eg stuff in ProphotoRGB). 
]

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by rhaamo** [comment]
IIRC all exif tags are stripped after upload, the coloursync profiles may be too.

**Comment by cangyuyao** [comment]
There should be a better solution to the colour profiles. Every photo uploaded from iPhone 7 or above distorted in colour, which is really annoying.

**Comment by StudioPetrikas** [comment]
I would like to add my 2 cents about this issue. 
I have listed some points as to why stripping color profiles is bad practice in mareklipka's pull request here:

https://github.com/mastodon/mastodon/pull/11758#issuecomment-1310671267
