### ISSUE TITLE
[feature request[ Make tag #admin reserved for admin set flagged users only

### ISSUE THREAD

**Issue by jebuskrust** [mastodon/mastodon#6892]
That way we can communicate with each other easily without unneeded noise. This will be a dedicated admin announcement tag only should there be any service related / and or impacting issues due to external threats, denial of service, etc.

* * * *

- [ x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by trwnh** [comment]
this should be covered by the announcements feature
