### ISSUE TITLE
Boost button doesn't darken on hover on Firefox

### ISSUE THREAD

**Issue by Sylvhem** [mastodon/mastodon#6906]
According to [this conversation on Mastodon](https://witches.town/@Sylvhem/99745658839873526), if your web-browser uses a Gecko engine, then when you hover your cursor above the boost button, it doesn't darken like the others do.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by fwenzel** [comment]
I didn't know it was supposed to darken! And I can confirm that behavior.

**Comment by trwnh** [comment]
the style has been changed to highlight with a partially-transparent background on hover
