### ISSUE TITLE
Public timeline on /public page should be filterable by language for non-members

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#6907]
... so that they can see whether the posts that they can actually read might be of interest!

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by donkeybonks** [comment]
I came here to post this bug.

Basically, I am of the opinion that it should pull your browser language and not show you public posts that you can not understand. I browsed to mastodon.social at ~7pm from Australia and every single post for over 2 minutes was in Japanese, which gave me a negative experience.

**Comment by Cassolotl** [comment]
This is still an issue now that public timelines for non-members have moved to /public.
