### ISSUE TITLE
"Would it be hard to automatically downsize photos that exceed the limit?"

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#6912]
Someone [posted](https://mastodon.social/@dopealope/99739725498645685):

>Is there a size limit on photos being posted? I noticed when I tried to upload a couple, the upload seemed successful, but the photo did not appear? Would it be hard to automatically downsize photos that exceed the limit (if it exists)?

It might be cool if we could handle images better, like maybe Mastodon shouldn't automatically reject images over 8MB - maybe it could resize them, like this person suggests?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by luzi82** [comment]
Then the system need another limit of file size, maybe 20MB.
With out it, ppl can upload a 1TB image file to the server.

**Comment by Gargron** [comment]
Would this be closed by the in-browser downsizing?
