### ISSUE TITLE
Editor content is reset when clicking in.

### ISSUE THREAD

**Issue by njouanin** [mastodon/mastodon#6919]
When repyling to a toot, the editor is initialized with the user name. When I click in the editor to start typing the username disappear. I've also seen cases where old messages come back in the editor.

See video in attachment.
[simplescreenrecorder-2018-03-26_14.00.13.zip](https://github.com/tootsuite/mastodon/files/1847667/simplescreenrecorder-2018-03-26_14.00.13.zip)

* * * *

- [X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [2.322](https://github.com/tootsuite/mastodon/releases).

**Comment by trwnh** [comment]
cannot reproduce in current version. if anyone can, this issue can be reopened or refiled.
