### ISSUE TITLE
[Feature] Show privacy-status of toots for the admin view

### ISSUE THREAD

**Issue by sammy8806** [mastodon/mastodon#6923]
When an admin is auditing a users activity out of the moderation-area it doesn't show what type of toot a status is (for example a DM).

This could be misleading and only clarified by clicking on the timestamp and look at the conversation where the privacy-marker is shown.

Attached are two little mockups as ideas where the a privacy-indicator is shown.
Another possibility would be to explicitly hide DMs similar to media and only show them as opt-in.

![message_with_envelope](https://user-images.githubusercontent.com/1584070/37935042-8c929e04-3150-11e8-877c-afe13612cc4c.png)
![message_with_outer_envelope](https://user-images.githubusercontent.com/1584070/37935043-8ce199f0-3150-11e8-81f2-20bbfa5190a2.png)

Also there are some who request for auditing this kind of actions.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ThibG** [comment]
I second this, and I'm favor of something similar to the first mockup, except the privacy information would be close to the date and not to the handle.

In addition, I'm not even sure why moderators should be able to see toots that they cannot see as a user and that weren't actually reported.

**Comment by Gargron** [comment]
DMs should be hidden from that view so you have to explicitly opt into viewing them, I think.

**Comment by ThisIsMissEm** [comment]
This seems related to #6969 — I'm thinking it'd be wise to just put the visibility and NSFW/CW stuff in a table/list below the toots.
