### ISSUE TITLE
'Your full handle' in Welcome email is unreadable

### ISSUE THREAD

**Issue by da2x** [mastodon/mastodon#6938]
I just signed up at [Mastodon.social](https://mastodon.social/) and received the welcome email. I got the welcome email and noticed a style issue. There is almost no contrast against the text and the background where my username is supposed to be shown.

Thunderbird 52.7.0 on Windows 10.1803 (default theming and colors.)

[![mastodon_welcome_email_handle](https://user-images.githubusercontent.com/1102886/37999938-7ea84502-3225-11e8-836b-5feb5d5e92a1.png)](https://mastodon.social/@da2x)

**Comment by Gargron** [comment]
I think it might be Thunderbird coloring what it thinks is an e-mail address. Safari does something similar.

**Comment by nynhex** [comment]
@Gargron Can confirm browser in Safari.  Doesn't happen in Chrome or Firefox proper.

**Comment by rugk** [comment]
Can confirm this with the web mail client Roundcube (https://roundcube.net/):
![g](https://user-images.githubusercontent.com/11966684/76216125-513a5e80-6210-11ea-9222-872176726d4a.png)
![g](https://user-images.githubusercontent.com/11966684/76216130-53042200-6210-11ea-9cdc-494ef5c2eafe.png)

**Comment by Elgueromiranda** [comment]
Closes #27708

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
