### ISSUE TITLE
Net::LDAP simple method not supported

### ISSUE THREAD

**Issue by VVelox** [mastodon/mastodon#6991]
Looking at the docs and from trying it appears that it will always attempt to use encryption.

From looking at the docs for Net::LDAP it appears that it should support simple for a connect method, but it appears SSL is just being assumed as a constant.

[1d1e6547-221e-49e2-a719-a66829b0a1ff]
[1d1e6547-221e-49e2-a719-a66829b0a1ff] Net::LDAP::Error (unsupported encryption method simple):
[1d1e6547-221e-49e2-a719-a66829b0a1ff]
[1d1e6547-221e-49e2-a719-a66829b0a1ff] lib/devise/ldap_authenticatable.rb:27:in `authenticate!'
[1d1e6547-221e-49e2-a719-a66829b0a1ff] app/controllers/concerns/localized.rb:14:in `set_locale'

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Thatoo** [comment]
Is mastodon not supporting Plain method for LDAP connection?
There was a wonder about it on discourse : https://discourse.joinmastodon.org/t/ldap-configuration-help-needed/1352/2

**Comment by VVelox** [comment]
@Thatoo Last I knew this was the case. I've since have dropped it and moved to another server as node and ruby stuff Mastodon left a lot to be desired, so I am unable to provide you with any info on its current status. Sorry.

**Comment by PureTryOut** [comment]
I don't get the "not supported" error, but I can't get it to connect with Plain either. If I set `LDAP_METHOD=simple`, the log doesn't indicate it's even trying to check in LDAP, same with `LDAP_METHOD=plain`.

**Comment by cyberb** [comment]
Non ssl ldap_method is supported enter any value like simple or plain and it will work, I think this issue should be closed.
