### ISSUE TITLE
Feature: API Endpoint to list Admins & Moderators of an instance

### ISSUE THREAD

**Issue by ThisIsMissEm** [mastodon/mastodon#7108]
As instances can add and remove moderators, it'd be great to have a way to fetch this through the API so we can list moderators in terms of service documents or other features. Presently we have to statically add this information.

It'd just return a list of Users using the AccountSerializer grouped by role (Admin or Moderator)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by mal0ki** [comment]
While it's not an API endpoint, is it at least adjacent with https://github.com/tootsuite/mastodon/pull/6984 ?

**Comment by ThisIsMissEm** [comment]
Not really, as this would return all the admins / mods

**Comment by Tagadda** [comment]
Maybe add a `role` attribute to the `Account` entity ?

**Comment by trwnh** [comment]
admin/mod has been removed in favor of entirely custom roles, and you can filter by role in the *admin* accounts API, but there's no option for regular users or the public to do this kind of filtering iirc.

**Comment by ThisIsMissEm** [comment]
Yeah, upon further thought on this, this should not be allowed, as otherwise admins and moderators can be harassed about reports, which poses a risk for phishing and social engineering of moderation and administration teams.

Closing this as it shouldn't be implemented.
