### ISSUE TITLE
Proposal: Add notifications for users affected by Moderator actions

### ISSUE THREAD

**Issue by ThisIsMissEm** [mastodon/mastodon#7127]
Currently, whenever we make an action as a moderator, if we want to explain to the user that we did something / why we did it, we have to send them a direct mention via our own accounts (or through a shared "support" account), this is less than ideal, particularly in cases where the action was an account deletion (suspension).

I'd like to have each moderator action (delete toot, change visibility, remove avatar, deletion/suspension)  generate an email to the user that was affected, it should include text that links to the terms of service/code of conduct pages (perhaps a configurable message from `Setting`'s)

This feature would probably need some sort of "note" so that moderations can say more explicitly about what was actually against the code of conduct or terms of service.

This increases user transparency for moderator actions, increase accountability for moderators.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by nynhex** [comment]
This would actually be relatively simple to implement. If there’s enough demand I’ll open a PR to address it.

**Comment by ThisIsMissEm** [comment]
@nynhex I'm probably going to implement this when I get around to it, I just have a lot on my plate already, not to mention having to do client work as well to pay the bills :(

So, until further notice: Feel free to take this and implement it; I'll update here if I start working on it, such that we don't double up.

**Comment by nynhex** [comment]
@ThisIsMissEm Sounds great, Emelia.  I have a bunch of free time starting tomorrow so it should be fun to surface.  I'll reference my fork/branch here as I update just in case we collide :) 

Good luck with the client work!  I feel your pain, often lol

**Comment by ThisIsMissEm** [comment]
@nynhex just wondering if you made any progress on this?

**Comment by Gargron** [comment]
@nynhex Wondering the same thing :eyes:

**Comment by mal0ki** [comment]
@nynhex could you make a default text along something like this: 

https://dragon.style/@anthracite/99955341286580131

**Comment by nynhex** [comment]
@mal0ki I had to stop development on Mastodon for now.  Too busy with ssb and hydra right now.  Feel free to drop in and delegate.  I'll likely pick up something else later.  Sorry for not updating, but I had notifications off.

**Comment by renchap** [comment]
Closing this as implemented. Mails are sent for moderator actions now, and they can include a moderator note.
