### ISSUE TITLE
Prevent over-scroll when scrolling on columns

### ISSUE THREAD

**Issue by ThisIsMissEm** [mastodon/mastodon#7145]
Currently in chrome based browsers (haven't tested others), when you reach the top of the column by scrolling, the whole application jumps around due to that elastic scroll / over scroll — that is, you switch from scrolling the column to scrolling the application.

This could be fixed using something like this: https://github.com/willmcpo/body-scroll-lock (however, modified to only be working on the Y (vertical) alignment. 

This could have an impact on menus appearing. (I think these were recently changed to popup to the top as well as the bottom)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ThisIsMissEm** [comment]
This probably also only affects Mac OS X / iOS (I'm not sure if other platforms feature "elastic scrolling")

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
