### ISSUE TITLE
[suggestion ] migration error message

### ISSUE THREAD

**Issue by S-H-GAMELINKS** [mastodon/mastodon#7154]
I adapted the latest source code, but using postgresql version was  old (ver 9.2) .
 And, I could not migrate.

It seems that the type jsonb, used for bio that did not correspond to PostgreSQL 9.2 .

I think that it,  error message saying  like "Your using PostgreSQL version does not correspond for jsonb"

How about it?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
cc #6645

**Comment by S-H-GAMELINKS** [comment]
I update PostgreSQL so it's okay. (9.2 to 9.6)

But I guess the other admins who use the Mastodon Start up Script from Sakura Cloud are serious(These's Instance using Postgresql 9.2)?

Because they are not constantly keeping track of Mastodon's changes, it seems that it will be hard to update quite a few Japanese instances.

If that kind of change is difficult, I'll write about PostgreSQL update.

Thanks comment!

**Comment by trwnh** [comment]
closing as stale; if this issue is still relevant, please comment here and it can be reopened
