### ISSUE TITLE
Temporarily cache Follow (Followers) list

### ISSUE THREAD

**Issue by jumoru** [mastodon/mastodon#7155]
It would be useful if the Follow (Followers) list in the profile page could be temporarily cached after going through multiple "Load more" for the first time. 

Examplary use-case:

I sometimes go through some profiles on both lists to see whether they are still active or have moved to another instance. Right now I have go through multiple "Load more" every single time when returning from a profile to one of those lists.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nemobis** [comment]
> Right now I have go through multiple "Load more" every single time

I don't understand how caching would help with this. Are you requesting a bigger pagination?

**Comment by jumoru** [comment]
Thanks for checking back. I’ve just tested it again and it seems as if the problem got fixed in the meantime. 

What I meant is this: When I click on a profile and then on followers, for example, I see the first X people of that list, depending on the size of the screen. In the past, if you have scrolled to, for example, to the 100th person, then clicked on this person and used the back button to return to the follower list, the list jumped back to person 1 and if you wanted to explore the, for example, 101th profile of the list you had to scroll down the entire list again. Furthermore, at least according to my impression at the time it was so that the whole list had to be reloaded gradually while scrolling down, although you had already loaded it once before. As it seems, the whole thing in the background now remembers the position where you clicked on a profile and leads you back to this point after returning.

Sorry if my initial description was a bit confusing.
