### ISSUE TITLE
Vagrantfile: Clearer error when/if RVM fails to install

### ISSUE THREAD

**Issue by marrus-sh** [mastodon/mastodon#7226]
When attempting to use Mastodon via Vagrant for development, the following line failed:

```bash
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
```

(This happens sometimes because `keys.gnupg.net` occasionally times out, or so I gather; when I ran the command manually it worked fine.)

This prevented RVM from installing and naturally meant that any of the following steps which required ruby didn't work.

However, there was no clear indication that this was the problem, making it somewhat difficult to debug. If RVM fails to install, the provisioning script should terminate immediately and notify the user to probably just try again.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Aside: Nobody I know who contributes to Mastodon regularly uses Vagrant, so nobody keeps it up to date or notices in time when it breaks. If anyone wants to become the person who maintains Vagrant, be my guest.

**Comment by trwnh** [comment]
this didn't happen last time i tried the Vagrantfile, so i'm closing this as stale / can't reproduce. if there are any issues with the current Vagrantfile then please file those as new issues
