### ISSUE TITLE
Make tags at the end of posts invisible somehow

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#7250]
Today I was talking with some people on Mastodon about hashtags and discoverability.

Someone was asking why people don't put hashtags in their posts very much on here, since searching hashtags is the best way to find posts about your interests. Someone else replied and said #people don't like to #use #hashtags because it looks #spammy. We talked about how Twitter posts by spammers contain a lot of hashtags, and some Instagram posts by people who want to reach as many people as possible are often a small description and then dozens of hashtags, and maybe those things are causing people to feel uncomfortable with using hashtags even though our deliberately limited search sort of requires that. People are being considerate, which is a good sign! But it means that posts are less discoverable than they otherwise might be.

We agreed that everyone would be able to get more out of Mastodon if hashtags were used more often, because then people would be able to find people who share their interests, posts that they might want to reply to or boost, stuff like that. I shared this Github feature request with them, and it was met positively: *Replace hashtags with tags #2331*

I'm wondering if the solution might be simpler than adding an extra text box for hashtags. Perhaps hashtags at the end of a post could be hidden somehow. Maybe under a faint "show tags" link, or something? That way people can tag freely and make their posts very discoverable, without looking spammy, and without complicating the New Toot UI with a whole extra field.

Edit:

> What if your last word is a hashtag but it's used as a word? "Look at my #cluckers"

Requiring a double line break, and requiring that last paragraph to be *only* hashtags without punctuation, would resolve that and make it easy to not hide your tags.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
What if your last word is a hashtag but it's used as a word? "Look at my #cluckers" - if the last word got hidden automatically that wouldn't be good. Please mind there's another issue by hoodie asking for tags instead of hashtags, i.e. WordPress/Tumblr style not as part of the text, but I don't think that's a direction we are interested in.

**Comment by qwertystop** [comment]
I think requiring a double linebreak, with the final block being tags-only, would be enough to prevent the "my #cluckers" case. The worst-case would be if someone made their last paragraph entirely out of tags, but even then punctuation would usually stop that from counting. In the extremely unusual case of an unpunctuated tags-only last paragraph, the user could easily add  one punctuation mark at the end, same as how birdsite had people dotting leading usernames so they didn't count as replies.

**Comment by LeeteqXV** [comment]
On Tue, Apr 24, 2018, at 04:41, David Heyman wrote:
> I think requiring a double linebreak, with the final block being tags-
> only, would be enough to prevent the "my #cluckers" case. 

This sounds doable, and such a "Show tags" feature would certainly be a good and practical addition to Mastodon.

Regards,

**Comment by adamk678** [comment]
I wonder if it would be a good idea to display hashtags as an uncolored hyperlink without the # symbol. You'd still type the hashtag in the same as now when you're making the toot, but in the timeline it just shows up with the word underlined. I think it'd make posts containing hashtags a lot more visually appealing than they currently are, which could contribute to people using them more often. My only concern is that could potentially be confusing to new users coming from other social media. Ugly as they are right now, the nice thing about hashtags is that they look consistent and are used the same way on just about every platform. I'd say "make it a setting" but I know that makes for twice as much work and risks bloating the settings page even more.
_Note: Adapted from [my toots](https://mastodon.social/@adamk678/99910752099906769) in a conversation about this topic._

**Comment by LeeteqXV** [comment]
On Fri, Apr 27, 2018, at 21:45, Adam wrote:
> I wonder if it would be a good idea to display hashtags as an uncolored 
> hyperlink without the # symbol. You'd still type the hashtag in the same 
> as now when you're making the toot, but in the timeline it just shows up 
> with the word underlined.

Not a bad idea, but I think that we should list all the words that are used as hashtags in a bullet list (incl. # signs and shown as links to their cateory page) behind the CW/show more toggle as well.

-- 
Regards,
Teqleez

**Comment by pacohope** [comment]
Seems to me that the way this makes good people look less like spammers has the coincident effect of making spammers look less like spammers. Spammers and bots and bad people like to cram popular hashtags into their posts for greater reach. Any hashtag on Twitter, for example, that has a lively discussion will quickly get bots and stuff posting unrelated content using that hashtag. This would have the effect of making spammy posts aesthetically more pleasing, right? 

Could this have the effect of encouraging overuse of hashtags and spammy behaviour by reducing one of the negative effects of being spammy?

**Comment by Cassolotl** [comment]
I feel like having good tools to deal with spammers might be the best way to deal with that? Like, admins can already keep spammers out of the public timeline, and block instances that harbour spammers. Obviously reducing the load on admins is a good idea, so I'm not sure.

I'd like to see some admins who've dealt with particularly annoying spammers weigh in with their personal experiences.

**Comment by pacohope** [comment]
Getting actual experiences from actual admins is a good idea. However, I doubt any are dealing with industrial scale spam yet (unless perhaps they deal with it on a platform other than Mastodon). Let me posit an approach, and then let's contemplate the outcome. The goal of most spammers is to get clicks on links, not to engage with people on mastodon. Web clicks get them ad revenue.

So imagine I write a bot that creates an account on a random instance, and toots a few links to various web pages, including some @-mentions for various popular people and a whole bunch of popular hashtags. I get it that there are a number of defences against spam, including admins, and defending spam generally is not what this discussion is about.

One of the last lines of defence against spam is the user themselves. They eyeball a toot and think "huh: look at all those random hashtags. That's probably just a spammer, I'm not gonna click on that link because it's probably not actually relevant." This proposal would obscure those hashtags, weakening that last line of defence. If the response is "admins have tools to deal with spam that are so effective, we don't need to worry about weakening that last line of defence", cool. But we should contemplate whether those tools really are that effective in the face of industrialised spam.

**Comment by LeeteqXV** [comment]
On Sat, Apr 28, 2018, at 10:29, Paco Hope wrote:
> They eyeball a toot and think "huh: look at all those random hashtags. 
> That's probably just a spammer, I'm not gonna click on that link because 
> it's probably not actually relevant." This proposal would obscure those 
> hashtags, weakening that last line of defence. 

That is perhaps ONLY (?) the case IF the toot in question actually has one or more external links?
For toots that does not include other links than what the hashtags themselves are pointing to (their category list pages), 
then this logic falls short.

So I agree with "half of your argument"...
I think that we might automate around this to get Mastodon/clients to show hashtags whenever there is an external link present,
and then hide them and put them in a bullet list behind a CW every time there are no external links included?
Best of both?

-- 
Regards,
Teqleez

**Comment by adamk678** [comment]
> One of the last lines of defence against spam is the user themselves. They eyeball a toot and think "huh: look at all those random hashtags. That's probably just a spammer, I'm not gonna click on that link because it's probably not actually relevant." This proposal would obscure those hashtags, weakening that last line of defence.
Even if they don't have the # symbol in front of them, wouldn't a bunch of random underlined words at the end of a toot still look odd and spammy? I'm also not sure how I feel about tags being hidden behind a CW. At the end of the day, as users we want to see tags, so I don't think adding an extra step to being able to do that would be helpful, and I don't think having an extra button added to any toots containing hashtags would be either. What might be better is having a "highlight hashtags" option, which would display them normally as they are now. This could be turned on by default to be friendly to new users, but with the ability to disable it for those who would prefer to see hashtags the way I described earlier. But then we've added another setting, and I'd like to come up with a solution that doesn't require that if possible.

**Comment by Cassolotl** [comment]
Spammers gonna spam no matter what we do. If at the end of the day it's a choice between quality of life improvements for end users or making spam more obvious to end users, I guess ultimately that's a choice Gargron has to make.

If spammers are likely to use *many more* hashtags than genuine users, maybe the "show tags" button could say "show x tags" where x is the number of tags, to help make it more obvious when someone has used a lot of tags. There will be genuine users who do use a lot of hashtags in a post, but we can trust that members and admins can recognise spammers based on more things than just the number of hashtags.

**Comment by LeeteqXV** [comment]
On Sat, Apr 28, 2018, at 15:54, Cassolotl wrote:
> If spammers are likely to use *many more* hashtags than genuine users, 
> maybe the "show tags" button could say "show x tags" where x is the 
> number of tags, to help make it more obvious when someone has used a lot 
> of tags.

Yes, a "Show all # tags" sounds like a practical feature here.

PS. IMO this should be offered as a custom setting, though, so that people can choose to keep the current/normal way as we have now, or to turn on the function that we are discussing here now.

That way, we do not have to debate whether all users would like this or not.
The main question would then be which should be the default setting for this feature, on or off?

-- 
Regards,
Teqleez

**Comment by trwnh** [comment]
i don't think the `content` of a post should be modified like this, because it would/could change the meaning of the post. #10743 seems like a more reasonable option to take, if anything is to be done

**Comment by Cassolotl** [comment]
Just posting this here to connect it up to the PR: *PR: Change hashtags at the end of the post to not be rendered #26260*

Needless to say, I disagree with 5-years-ago-me, for the following reasons:

1. Currently there is no indication that a post is in your Home timeline because you follow a hashtag in the post. (*Show mention of the followed hashtag #19528*) So if posts appear in the Home timeline and even the followed hashtag isn't visible in the post, this is going to cause so much confusion. And Gargron has implied that it's not currently possible to have that "because you follow #hashtag" indicator above a post on Mastodon.
2. It might make reporting spam in hashtags a bit more complicated?
3. I can understand wanting to collapse hashtags when they're in a big block at the end of a post, but I think people should be able to see them if they want to. Hashtags shouldn't just be totally invisible with no option to show them.

**Comment by renchap** [comment]
Closing this as hashtags at the end of posts are now displayed in a special hashtag bar
