### ISSUE TITLE
In a toot page, unhiding a CW should unhide all of them

### ISSUE THREAD

**Issue by nicolasmaia** [mastodon/mastodon#7255]
Case in point: https://cybre.space/@shel/99915241796309889

It feels dumb having to click to unhide _every single_ toot.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by clarcharr** [comment]
This should only apply if the CWs match.

**Comment by picsi** [comment]
>This should only apply if its in the same thread to be honest. Content warnings exist for a reason and clicking on one once shouldn't mean you always see that content. One day you might be able to handle it and the next you might not.

Agreed, I meant to say this should only happen in a one-time basis inside a thread page.

**Comment by clarcharr** [comment]
Also FWIW, if you open a thread in a column there's an eye icon which lets you show or hide all of the CWs on the thread. I just noticed this today, and while it's not super discoverable, it is sort of a partial fix for this.

**Comment by mal0ki** [comment]
I agree with being able to open all CW for a thread to be a good feature. Will tag this for enhancement.

**Comment by Cassolotl** [comment]
There is now an eye icon on threads in the web UI that lets you hide and unhide all posts in a thread. Having this on toot pages makes a lot of sense consistency-wise, I think.

**Comment by mal0ki** [comment]
> There is now an eye icon on threads in the web UI 

I hadn't even noticed that!

**Comment by picsi** [comment]
@mal0ki it might be a good idea to make them a little more noticeable

**Comment by rugk** [comment]
BTW don't know what you mean with "toot page", but IMHO it should always just unhide the whole CS thread if I unhide the main CW. (no matter where I do so)

**Comment by trwnh** [comment]
Repeating what I said on #8552: I should point out this issue is specifically for public pages; sharing a thread with someone who doesn't use Mastodon is a very terrible experience. For people actually using Mastodon, #1123 is more appropriate.

**Comment by rugk** [comment]
Buz autoexpanding is another thing.

So why only for public toot pages?
I re-read this issue and found the eye thing. I never noticed it. And I think it would not hurt to drop it and integrate the functionality into the existing (and way more obvious) "unhide" buttons.

**Comment by trwnh** [comment]
public pages have been removed in v4.0 and the web-app has a button to expand CWs in a thread, so i'm closing this issue -- if there's anything you consider "undone" then please file a new issue for that
