### ISSUE TITLE
Bug: Empty space added to notifications

### ISSUE THREAD

**Issue by mal0ki** [mastodon/mastodon#7328]
Bug encountered on web interface, notifications column. 

I've seen this recently myself, and got reminded when I saw the example provided below.

See this post for example: 
https://ajin.la/@kai/99884105354138061

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate. I really did search, but who knows, words are hard!
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
cc @sorin-davidoi
