### ISSUE TITLE
Mastodon doesn't handle gifs from other software correctly

### ISSUE THREAD

**Issue by zcdunn** [mastodon/mastodon#7345]
Gifs from other federated software aren't shown inline. This is likely a result of the change to convert gifs from mastodon to mp4. 

Example: https://pleroma.soykaf.com/objects/92e72df2-6387-40cb-a10c-e1826a074751

**Comment by Gargron** [comment]
>they only convert gifs to mp4 when posted, so if another implementation posts a gif, they don't recognize it

This is plain wrong and inaccurate. Accepted formats and conversion rules apply equally to local and remote posts

**Comment by nightpool** [comment]
that status is indeed broken, but gifs in general are not. don't believe everything lain tells you lol

**Comment by zcdunn** [comment]
I didn't believe it because Lain said it. I believed it because the gif in the post doesn't show up and I've seen this happen before

**Comment by nightpool** [comment]
classic paperclip spoof error 

```
May  3 07:24:54 neo bundle[8852]: [paperclip] Content Type Spoof: Filename e9f871e47dcc0631.gif (video/mp4 from Headers, ["image/gif"] from Extension), content type discovered from file command: video/mp4. See documentation to allow t
```

let's see here..... maybe this is an Accept headers situation? can't reproduce it with wget + file alone.

**Comment by nightpool** [comment]
That code hasn't been changed in years though, unless we just never federated gifs and always federated mp4s?

![image](https://user-images.githubusercontent.com/233815/39609665-9f56a4b4-4f18-11e8-95f1-3b2a2a7dedb1.png)

**Comment by nightpool** [comment]
hnmm. I know I have seen gifs from gnu social, but maybe paperclip broke this recently and noone noticed.

**Comment by Gargron** [comment]
Which instance did this get discovered on? Latest stable release is on Paperclip 5.1, unreleased master is on Paperclip 6.0. It could be conceivable that something broke between 5.1 and 6.0

**Comment by nightpool** [comment]
i've been checking cybre logs, so stable-ish

**Comment by zcdunn** [comment]
I noticed the issue from my account on toot.cafe

**Comment by djoerd** [comment]
On our intance, GIFs from other instances are not shown, see: 
https://mastodon.utwente.nl/@hiemstra/100600152117840221

**Comment by trwnh** [comment]
this is still happening

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.

**Comment by ClearlyClaire** [comment]
Furthermore, it appears to be fixed, at least with the libvips codepath.
