### ISSUE TITLE
Searching profile URL doesn't always re-fetch avatar and bio

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#7397]
I'm searching from sunbeam.city:

![screen shot 2018-05-07 at 13 06 13](https://user-images.githubusercontent.com/6607512/39701018-75d3aa6a-51f7-11e8-9e1b-43241798c95f.png)
![screen shot 2018-05-07 at 13 06 19](https://user-images.githubusercontent.com/6607512/39701020-78e8d57c-51f7-11e8-9eed-3da345505e83.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ThibG** [comment]
This is intentional, as updating a remote account information is very costly to both instances, this is throttled to at most once a day.

**Comment by Cassolotl** [comment]
I think I have tried to fetch the new avatar of this account before. I'll try again tomorrow and see what happens.

**Comment by Cassolotl** [comment]
1 day and 4 hours later, I just tried again with the same account and I'm getting the same result. So, this isn't explained by a 24-hour cooldown.

**Comment by mal0ki** [comment]
Is it only not displaying in the search? 

I do remember there being old issues with this, but I don't recall why.

**Comment by Cassolotl** [comment]
Usually when you have an account with an out of date avatar and you search the URL of the profile, the account and the updated avatar show in the search results, and at the same time it updates the avatar in the search results and anywhere else it's visible in the web UI.

This bug report is because entering the profile URL has no effect at all. The account and old avatar appear in the search results, and the avatar isn't updated anywhere else in the web UI.

**Comment by ThibG** [comment]
This occurs because that person's header image is broken for some reason. Therefore, Mastodon discards both the profile picture and the header image.
