### ISSUE TITLE
Improve @user@domain search

### ISSUE THREAD

**Issue by clarfonthey** [mastodon/mastodon#7464]
For example, if you search @ user @ cybre, it should show the results for @ user and limit the domains to ones which contain "cybre." In this case, if the instance that's doing the search is federating with cybre.space, it should show the results for @ user @ cybre.space.

This would be a nice UX improvement, as the current options are to either write out @ user and sift through all of the instances, or to write @ user @ domain, with the domain spelled out in full without any typos.

Obviously, you need a full domain name to check users on instances which are not currently federated, but we should be able to immediately tell if something is just a partial domain search by checking either [IANA's TLD list] or [Mozilla's public suffix list]. It would be cool if we could also search for federated subdomains as well, e.g. if you search for @ user @ masto.host, it would only list subdomains of masto.host.

There are a lot of different options for this, but allowing some basic form of searching for the domain would be very helpful.

[IANA's TLD list]: http://data.iana.org/TLD/tlds-alpha-by-domain.txt
[Mozilla's public suffix list]: https://publicsuffix.org/list/public_suffix_list.dat

**Comment by mal0ki** [comment]
Oh, interesting find. (I was actually convinced that we could do this, but joke's on me, apparently I've always written the full instance url when I've done it)

**Comment by Gargron** [comment]
Actually if I search for "cwebber octo" I get a result for cwebber@octodon.social. The search index is a kgram for autocomplete purposes so what you're asking for should already be working. You can't include the @ tho because then it does expect you to write it out full :)
