### ISSUE TITLE
Pinned DM column sometimes doesn't automatically update

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#7537]
When my DM column is pinned on mastodon.social and there's nothing in it, new incoming DMs don't update in that column automatically even though they do in Notifications. If I want to see new DMs in the DM column I have to reload the page.

After a DM has arrived and is visible in the column, new DMs load in the DM column when they come in.

Steps to reproduce:

1. Have an account which has received no DMs ever. You should see the "You don't have any direct messages yet" message.
2. Click "Direct messages" in the Getting Started menu.
3. Pin the DMs column, and then press the star to get rid of the spare DMs column.
4. Have another account send it a DM.

Notifications updates with the new DM, but the new DM column doesn't.

If you unpin and reopen the DMs column the DM still doesn't appear even though it's still in the Notifications column. Reloading the page makes the DM appear.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Cassolotl** [comment]
UGH I cannot reproduce this now. Sorry. 🙄

**Comment by Cassolotl** [comment]
![screen_shot_2018-05-26_at_19_49_53](https://user-images.githubusercontent.com/6607512/40579390-28c65656-611e-11e8-8fbb-a313b3081710.png)

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
