### ISSUE TITLE
Embed dialog weirdness + poor use of space on desktop

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#7561]
![image](https://user-images.githubusercontent.com/10606431/40283779-85797754-5c49-11e8-8ea4-7b7c0887c78b.png)

Rather than using a scrollbar, the status should be shown in full if it's small enough to fit on the page. The modal itself has a max-height of 80vh, but the iframe height is merely a couple of hundred px high (hard-coded in the html).

---

![image](https://user-images.githubusercontent.com/10606431/40283807-11e6a69e-5c4a-11e8-8802-52dd141eab75.png)

Also, when the date is long, the edge of the status can become cut off.

---

![image](https://user-images.githubusercontent.com/10606431/40283820-33ed9c34-5c4a-11e8-88e5-e06d88754758.png)

And in a particularly tall status (perhaps one with media attached), the bottom will be chopped off entirely. The height is set to 766px when it should be more like 832px.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (v2.4.0rc4, but not unique to this version)

**Comment by Gargron** [comment]
Iframes cannot be dynamically resized to contents.

**Comment by trwnh** [comment]
I guess they need to be better calculated, then? The main issue seems to be that the size is never quite 100% appropriate -- at best, it seems to be barely too short; even a one-liner will be just a couple of pixels taller than the frame.

![image](https://user-images.githubusercontent.com/10606431/40283943-521e0020-5c4c-11e8-9a83-8317d2c2e247.png)

Anyway, it should be possible to set iframe height dynamically based on content in javascript, based on a quick Google search.

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
