### ISSUE TITLE
When copypasting toot from web UI, it copies some text twice

### ISSUE THREAD

**Issue by Gargron** [mastodon/mastodon#7567]
Ref: https://mastodon.observer/@stephen/100051796813616115

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by bonsaiheldin** [comment]
I can confirm that.

**Comment by vmstan** [comment]
Is this still an issue?
