### ISSUE TITLE
The new "Media only" filter on the public timelines allows posts where the media isn't visible

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#7579]
This thing:

![screen shot 2018-05-21 at 20 59 37](https://user-images.githubusercontent.com/6607512/40327196-f3b2a100-5d39-11e8-9463-a42448a7fe1e.png)

It allows toots where the media isn't visible, presumably due to instance-level media blocks. It doesn't look good on the timeline to see media only posts without media, I think?

(I also think it would also be cool if the media was at the top of the post instead of the bottom for media-only filters a la Instagram but I can understand if people would rather not have the inconsistency there!)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
