### ISSUE TITLE
Timestamps on DMs from other instances should not be clickable

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#7584]
Clicking on a timestamp on a DM from someone on another instance ALWAYS leads to a "not found", so perhaps making them not clickable will save some collective effort and confusion.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by trwnh** [comment]
There should still be a way to copy the URL for your own use later, in the web app. The public URL may always resolve to a "not found" page, but that doesn't mean it's completely useless.

**Comment by Cassolotl** [comment]
What *is* it useful for? The URL doesn't return any results in the web UI search, and I can't think of any other uses!

**Comment by ThibG** [comment]
“The URL doesn't return any results in the web UI search” that might change in the future, and it does work from the originating instance afaik
