### ISSUE TITLE
/api/push returns 503 when requested from unconnectable instance

### ISSUE THREAD

**Issue by takayamaki** [mastodon/mastodon#7616]
In friends.nico, we are monitoring our instance's status by access logs.

Sometimes, we get alerts that it says too many http status 5xx.
It caused by request to `/api/push` from unconnectable instances by some reason.
ex. expired SSL Cert, incorrect DNS record, connection refused at port 443, connection timeout by NAT, etc...

Anyway, these errors are not our fault.
In these cases, I think necessary to change status codes.

![image](https://user-images.githubusercontent.com/24884114/40530223-ddbb4ce8-6032-11e8-8cc2-ec9b9cc15ed6.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
Consider this: If the DNS or SSL is fixed later, the same request could be retried and be successful. However if you return a 4xx error, the sending server will believe that the request cannot be retried and won't attempt to re-deliver.

**Comment by tateisu** [comment]
I think 5xx is okay, but if you choose a response code other than 503 then building a monitoring system will be easier?

**Comment by takayamaki** [comment]
I think with each cases.

### expired SSL Cert
At least the other server is alive.
There is a possibility that the SSL cert is updated.
And the contact information of the administrator may be announced if ignoring SSL cert error.

In this case, I don't agree with returning 503 errors, but I have no more better choice.

### incorrect DNS record
In this case, I have never seen a fixed.

In the worst case of I encountered, the A record returned 127.0.0.1!
It seems that the other server was going to closing.

Configuring DNS records correctly is the most basic responsibility of server administrator.

I still think that I think necessary to change status codes.
I seem that 400 Bad Request is better.

### connection refused at port 443, connection timeout by NAT
In this case, I have never seen a fixed too.

Most of this cases, the other server is development or staging environment.
The user agent's domain was `dev.example.com`, `localhost:3000`, etc.

I cannot understand why perform request at unreachable server.
Even if they misconfigured, it is the besicaly responsibility of the server administrator to make the correct settings.

I still think that I think necessary to change status codes too.
I seem that 400 Bad Request is better.

**Comment by Gargron** [comment]
The `/api/push` endpoint has been removed.
