### ISSUE TITLE
PWA shows "Oops! An unexpected error occurred." multiple times when visited offline

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#7622]
iOS 11.3.1 / Safari Portable Web App (added to home screen)

This should preferably show a more accurate error and load a cached version of posts.

**Comment by johneakin** [comment]
This is a big problem, I get a ton of these popups when trying to read while travelling on the London underground. I don't think these errors should popup when trying to view posts offline.

**Comment by averageunicorn** [comment]
Replying to this old issue because it is what still happens in Mastodon 2.6.1, not only in the PWA, but also in desktop Firefox at least. Would be cool if only one error appeared :)

**Comment by rtucker** [comment]
https://cdn-assets.vulpine.owogroupllc.com/media_attachments/files/001/312/792/original/133475b076e2908f.png

**Comment by BenLubar** [comment]
just wanna poke my head into this thread to point out that `navigator.onLine === false` is most definitely a thing you can put in an if statement in JavaScript.

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
