### ISSUE TITLE
Misleading text on profile edit page - Account privacy doesn't alter post privacy.

### ISSUE THREAD

**Issue by vladanghene** [mastodon/mastodon#766]
So I got this today, trying to go unlisted/private, I checked the box under my profile which didn't make my future posts private (as it supposed to).
![screenshot from 2017-04-03 08-03-03](https://cloud.githubusercontent.com/assets/3773948/24596094/3acadc14-1845-11e7-9555-a4e5d01c91b4.png)

**Comment by vladooku** [comment]
Also, on a related note, every post that I boost is still public even though I've set post privacy to just my followers.

**Comment by spaceottercode** [comment]
This is no longer the case as of 2.6.5 possibly earlier @cycle337 and the two have been split as @Cassolotl   suggested. @Gargron @nightpool

**Comment by Cassolotl** [comment]
They were already split! They're currently on separate pages, and I suggested that the two settings be moved to the same page, and be side-by-side so that it's clear that they're related but separate.

**Comment by spaceottercode** [comment]
You are right @Cassolotl. Only the wording has changed (compared to the screenshot)

**Comment by despair1134** [comment]
docker总体来说还是一个很不错的数据存储，相对于新手来说比较具有亲和力

**Comment by ClearlyClaire** [comment]
Since it does not make any mention of post privacy in current versions, I think it is not misleading anymore, closing.

![image](https://user-images.githubusercontent.com/384364/153008928-c2c6aa3d-b567-4c0b-b0ff-2c6585f6c40f.png)

> Also, on a related note, every post that I boost is still public even though I've set post privacy to just my followers.

As for this, private boosts were implemented a while ago and boost privacy defaults to post privacy.
