### ISSUE TITLE
Public timeline gap followed by 31 duplicates in a row

### ISSUE THREAD

**Issue by trwnh** [mastodon/mastodon#7666]
Not entirely sure what happened exactly, but I stepped away from my computer for a few minutes and came back to this:

![image](https://user-images.githubusercontent.com/10606431/40639217-604d24ca-62d5-11e8-8b50-475d97ba746c.png)

This isn't the first time something similar has happened, and it usually happens after a period of inactivity, and it goes away when refreshing the page. Seems to occur only recently, so I'd guess it was introduced sometime after 2.4.0rc4 at minimum.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on v2.4.0 and not on `master`

**Comment by trwnh** [comment]
Here's a video of this happening again, with a *lot* more than 31 duplicate statuses... although in this case, they don't even have the correct timestamp.

https://mastodon.social/@trwnh/100153425427125244

**Comment by trwnh** [comment]
The timestamps are also out-of-order with the ghost toots. 
![image](https://user-images.githubusercontent.com/10606431/40996215-e2116e02-68c6-11e8-9c07-8b18db304769.png)

**Comment by vmstan** [comment]
Is this still an issue?

**Comment by trwnh** [comment]
I'm not sure; I haven't seen it happen because I don't browse the public timelines like I used to, but I'll close this issue and it can be reopened or refiled it it happens to anyone else in the future.
