### ISSUE TITLE
Mobile compose view can obscure "toot!" button on adding new CW to reply

### ISSUE THREAD

**Issue by catscode** [mastodon/mastodon#7695]
When composing a reply, the toot I am replying to is displayed above the compose box, pushing it further down the page (which is expected behavior). When the previous toot occupies just the right amount of space, the "toot!" button is right at the bottom of the screen, but not below it, so the compose view is not scrollable (also expected behavior). In this situation, if the previous toot did not have a cw and i add one, the "toot!" button is pushed below the bottom of the page, but the page remains non-scrollable, and so I can't actually scroll down to that button to send my reply. it is un-sendable.

the caveat here is that i'm on an older version of mobile safari, so this is only worth looking into if someone else can easily reproduce it. but it tracks with other bugs i've seen over time (and still see now) in mastodon's mobile web interface around ui dynamically updating a page in ways that change length (e.g. opening a cw) without enabling scrolling if that update changes the page length from less than one screen-length (unscrollable) to more than one screen length (should be scrollable).

this is on 2.4.1rc1

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by catscode** [comment]
also intermittently reproduced on an older version of mobile chrome (63.0.3239.73)

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
