### ISSUE TITLE
Live account mirroring

### ISSUE THREAD

**Issue by penguin42** [mastodon/mastodon#7715]
(Split out of my comment on https://github.com/tootsuite/mastodon/issues/177)

The need for account migration is driven by two things:
  a) People wanting to move
  b) Instances dieing/getting unreliable

(b) is impossible as a migration if an instance is actually dead already and gets hard when they're on their last legs.  I suggest a live mirroring would solve (b) better.

Here's a proposal (I don't know the protocol to know how hard it is, please educate):
a) I create an account on multiple instance
b) On each instance I add a list of my equivalent identities on the other instances to my profile.
c) Each instance follows the mirrored identities
d) Each message shall contain a unique ID including the server that originated the message
e) When an instance receives a federated message from a server with an ID corresponding to a mirror-ID of one of it's users, it checks that the unique ID doesn't indicate that it originally started at it's own server, and if it doesn't retransmits the message on their users profile, including the original unique ID. (Is this that different to a boost?)
f) Servers filter multiple messages with the same ID from the federated stream leaving one.
g) When following a user the client also follows mirror identities. This updates when the person being followed adds/removes mirrors
h) Admins can allow/disallow mirroring from certain bad/good servers

Now, there's essentially no 'primary' server for any one user; if one dies you just log into one of the other instances you've previously set up as mirrors and your message propagates to other servers by normal federation, your followers carry on seeing your messages with no change; if your original server wakes up it'll also pull those messages in by federation (probably).

Note: I'm not suggesting that all of instance 'a' mirrors instance 'b' - this is much more free form allowing users to select their mirrors.   However a bunch of friendly admins could set it up by prepopulating on account creation.

There's probably a billion more questions; like what happens to direct messaging and all the other things that might interact with any one user.

**Comment by trwnh** [comment]
closing in favor of #9206 which got more discussion
