### ISSUE TITLE
Flag emoji autocompletition issue

### ISSUE THREAD

**Issue by MasterGroosha** [mastodon/mastodon#7725]
Let's say I want to insert Russian flag emoji, which has code `:flag-ru:`
I type `:flag-ru` and see this:
![image 1](https://user-images.githubusercontent.com/2780044/40905679-5a3b8862-67e7-11e8-862e-5cd1342595e1.png)
wtf? Maybe shortcode has been changed? So I keep typing: `:flag-rus`
![image 2](https://user-images.githubusercontent.com/2780044/40905742-7d185202-67e7-11e8-8d22-e8c5e0cbc6f3.png)
Oh, there you are!

* * * *

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [*] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by renatolond** [comment]
We use emoji-mart for the autocomplete of the emojis, this seems like an upstream bug, if you type flag-ru here: https://missive.github.io/emoji-mart/ you'll see that the results are the same.

Do you mind if I create this issue on https://github.com/missive/emoji-mart/ and link it back here?

**Comment by MasterGroosha** [comment]
@renatolond it would be very kind of you

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.

**Comment by trwnh** [comment]
Reproducible on mastodon.social v4.4.0-nightly.2024-11-26
