### ISSUE TITLE
Reporting a toot equals NO confirmation - Redirect to getting started.

### ISSUE THREAD

**Issue by vladanghene** [mastodon/mastodon#774]
I see that the user disappears from the timeline altogether (not just his one toot that I report).
I get redirected to Getting Started.
If I refresh browser window I still see the user and the toot I reported.

**Comment by Gargron** [comment]
Perhaps we should display a "success" message but report by itself isn't intended to automatically remove something, it goes to the admin's reports overview where the admins decide what to do.

Or do you mean that report should automatically invoke a block as well?

**Comment by vladooku** [comment]
yes, that's what I mean. I think on other platforms that's what happens. It's debateable, maybe we as an open sourced platform should do things differently, but I for one see no reason not to block at least that single toot that caused distress.

**Comment by ashfurrow** [comment]
I think an option, enabled by default maybe, to block might be nice.

**Comment by Cassolotl** [comment]
I just tested this out on 2.2.0 and there's no confirmation that the report was sent or received, and the toot I reported doesn't disappear.

The way I've seen this done on other sites is like:

\*reported post disappears\* "Thanks for your report. Would you like to block this person? y/n"

**Comment by trwnh** [comment]
this can probably be closed?

**Comment by Cassolotl** [comment]
Why?

**Comment by trwnh** [comment]
there's a confirmation on reports now

![image](https://user-images.githubusercontent.com/10606431/215212127-b4bbc2f1-26ac-4367-9914-f73ab9aebbc4.png)

**Comment by Cassolotl** [comment]
Oh yes, fair enough!
