### ISSUE TITLE
Account gallery can't be loaded more when opened it again

### ISSUE THREAD

**Issue by unarist** [mastodon/mastodon#7784]
## Steps to reproduce

1. Open someone's account gallery
2. Open other page in right-most column, e.g. account timeline
3. Open the account gallery same as step 1
4. Scroll to bottom

It should load older entries, but it doesn't now.

## Details

Opening timeline causes *refresh* and update `hasMore` property in the store. Our timeline API won't set `rel="next"` header if `since_id` is set and no more entries from the specified id. Therefore, `hasMore` property will be changed to `false` on refreshing.

This issue won't happen on normal timelines because `<ScrollableList>` don't check `hasMore` prop in the scroll handler:

https://github.com/tootsuite/mastodon/blob/0979d4275a387556fa040247330a4ed0e7f89602/app/javascript/mastodon/components/scrollable_list.js#L48-L50

but `<AccountGallery>` does:

https://github.com/tootsuite/mastodon/blob/0979d4275a387556fa040247330a4ed0e7f89602/app/javascript/mastodon/features/account_gallery/index.js#L68-L72

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).
  -> v2.4.0 (dafd7af re-enables usage of `since_id`)

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
