### ISSUE TITLE
recommand set sidekiq id:nil, some cloud providers can't suppot redis client command

### ISSUE THREAD

**Issue by xrain0610** [mastodon/mastodon#7785]
config/initializers/sidekiq.rb:

this file should add id: nil 
> redis_params = { url: ENV['REDIS_URL'], id: nil}

this can let sidekiq don't require client command~

**Comment by mjankowski** [comment]
This feedback was for a pretty old version and the redis/sidekiq config has changed since then ... going to close this as stale on assumption its resolved or no longer relevant, but please reopen with current version details if still an issue.
