### ISSUE TITLE
/oauth/applications can cause an infinite redirect

### ISSUE THREAD

**Issue by trrk** [mastodon/mastodon#7786]
Opening `/oauth/applications` with non-admin account causes an infinite redirect.
(`/oauth/applications` -> `/auth/sign_in/` -> `/oauth/applications` -> …)

Returning 403 might be one of the solutions.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by felipecsl** [comment]
I can reproduce this on latest master as of commit c1de6730604f526a6c2d19adcf6f195352de0641

**Comment by trwnh** [comment]
cannot reproduce on latest version -- i was redirected to the /getting-started page.
