### ISSUE TITLE
Change "open source" to "free software" in footer

### ISSUE THREAD

**Issue by ghost** [mastodon/mastodon#7795]
The term 'open source' is used in https://github.com/tootsuite/mastodon/blob/10f51c9886123982bc9f2a95fba39dd1f24b9a05/app/javascript/mastodon/locales/en.json#L118. Would be nice if the term free software was used instead.

**Comment by carlosjs23** [comment]
@ghost what you want to transmit changing the term?.

**Comment by akuckartz** [comment]
Proposal: use both!

**Comment by BillyWM** [comment]
@akuckartz Yeah describing it with the language "free and open source" is, from what I've seen, generally understood to mean that it's FOSS according to the FSF definition.

**Comment by akuckartz** [comment]
Why was this issue labelled as "invalid" ?

**Comment by Gargron** [comment]
Because I was triaging issues en masse and the title "open source vs free software distinction" made be believe this was a discussion about terminology. (Tip: Concise and descriptive titles are key)

**Comment by trwnh** [comment]
the language in question is no longer used, as the footer has been redesigned
