### ISSUE TITLE
Make avatar shape consistent

### ISSUE THREAD

**Issue by mattcoxonline** [mastodon/mastodon#7796]
I see avatars are sometimes circles, sometimes squares with rounded corners, and sometimes squares with even rounder corners.

Not a big issue, but a real kicker to my OCD.

It would be nice if all the avatar shapes were consistent across the product; rather than different in different places.

<img width="1091" alt="screen shot 2018-06-13 at 13 26 53" src="https://user-images.githubusercontent.com/673542/41348775-0a096890-6f0e-11e8-949c-224294cc3f4a.png">

<img width="425" alt="screen shot 2018-06-13 at 13 27 04" src="https://user-images.githubusercontent.com/673542/41348776-0a4e546e-6f0e-11e8-852b-a5995b147dfb.png">

<img width="710" alt="screen shot 2018-06-13 at 13 27 21" src="https://user-images.githubusercontent.com/673542/41348777-0a7f6662-6f0e-11e8-8a98-85c6d424035e.png">

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by jhaye** [comment]
This remains an issue on the outward facing designs of a profile on the desktop. The top profile picture is a circle, whereas the profile pictures on the timeline are rounded squares.

**Comment by trwnh** [comment]
circle avatars don't seem to be user anywhere anymore, and the public permalinks/profiles have been removed in v4.0
