### ISSUE TITLE
Create a user without sending email?

### ISSUE THREAD

**Issue by tiaod** [mastodon/mastodon#7922]
I want to create a mastodon instance for my bots (maybe hundreds of them. Every bot follow a RSS feed) , but I can't find a way to register a bot automatically. 😢 Could anyone help me please?

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by MaciekBaron** [comment]
Wouldn't that just require from you to add them manually into the database using some sort of script you write?

**Comment by Elshara** [comment]
Two separate issues?

**Comment by limdingwen** [comment]
This would be great for friend-only instances. Would make it much easier to self-host too.
