### ISSUE TITLE
Feature request: keyword triggered auto-CWs

### ISSUE THREAD

**Issue by jamestomasino** [mastodon/mastodon#7947]
As an alternative option to completely filtering keywords, add an option to have keywords convert a toot to use a content warning even if it wasn't composed that way. 

For instance, if I added the word "Mastodon" to my auto-CW list, then any toots containing that term which were not already enclosed in a content warning would appear in a content warning anyway. Optionally the label of the content warning could use the name of the "filter" that was added.

**Comment by phoe** [comment]
I second this idea. I enjoy the idea of defining keywords and/or regexes describing toots that are going to be automatically CWed by the system for me.

**Comment by maiki** [comment]
Does this functionality live in the Mastodon UI? What is a CW, according to ActivityPub?

I hardly use the web UI, so depending on where this is implemented in the stack determines how much I am affected, so wanted to ask.

This sounds like something that a client could do, and would be more customizable moving forward.

**Comment by phoe** [comment]
I don't think this does ever need to leave the UI. You can define the filter on the UI frontend, it gets saved in the user's setting on the instance, and then every time a message comes to be displayed on the UI, the filters trigger and if any of them successfully match, the message is shown with a content warning.

This would mean that people implementing other Mastodon/Fediverse UIs would need to follow suit with their own implementations, but, given the already present issues with content warnings like https://github.com/w3c/activitypub/issues/232 this sounds like a sane option to me.

**Comment by jumoru** [comment]
I second this idea as well. It's something I already know from Twitterrific for Twitter and it's very handy, because it gives you the chance to think about whether you want to engage with it or not, similar to when people manually CW posts.

The first paragraph of this support article by Twitterrific explains in a bit more detail how and why they've added this functionality:

http://support.iconfactory.com/kb/twitterrific/muffling-and-muting-tweets-in-twitterrific-ios-and-macos

**Comment by Gargron** [comment]
What I want to understand is whether you want the filter to make a normal toot look like it has a CW as added by the author (pre-filter UX) or you want filters to have a different UX after all ("Filtered" message, everything obscured, fixed height, filter details in tooltip or something)

**Comment by phoe** [comment]
Perhaps a greyed-out CW? Normal CWs are white now; perhaps automated CWs could be different coloristically.

Dnia 5 lipca 2018 17:14:46 CEST, Eugen Rochko <notifications@github.com> napisał(a):
>What I want to understand is whether you want the filter to make a
>normal toot look like it has a CW as added by the author (pre-filter
>UX) or you want filters to have a different UX after all ("Filtered"
>message, everything obscured, fixed height, filter details in tooltip
>or something)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/tootsuite/mastodon/issues/7947#issuecomment-402756644

-- Wysłane za pomocą K-9 Mail.

**Comment by jumoru** [comment]
In principle, as long as both ways allow hiding the content of a toot, (optionally) show the rule why it’s hidden and allow to see the content of the toot when clicking on it, I’d be fine with both ways.

What I’m wondering about is whether there are other advantages / disadvantages to those two ways from a technical point of view that we should consider?

**Comment by jamestomasino** [comment]
I think we should also keep accessibilty in mind. If the only difference were a color change that wouldn't be recognizable to folks with vision impairment. That pushes me more in the direction that @Gargron mentioned with "filtered" instead of "CW".

As a possible experience, maybe filters get a `name` and matching `pattern`. When the `pattern` matches the toot is concealed like a CW but it says "Filtered: XXX" where XXX is the `name` of the filter.

**Comment by ThibG** [comment]
I think they need to look different, because otherwise you wouldn't know if something was “properly CWed” before boosting it.

**Comment by ShadowJonathan** [comment]
Any interest in this issue still? CWs are amazing, but this would allow users to curate their own experience better and better, as today mastodon still has the problem of users not properly cw-ing content if it's deemed cw-able, or if an instance doesn't have a community around cw-ing issue X, but another instance might have, and their community wants to interact with the former instance.

**Comment by ShadowJonathan** [comment]
> I think they need to look different, because otherwise you wouldn't know if something was “properly CWed” before boosting it.

maybe in italics?

> *contains "cheese" keyword* [show more]

**Comment by dregin** [comment]
Hi, is there any movement on this request? We have some users asking for it on mastodon.ie, cheers.

**Comment by ClearlyClaire** [comment]
The new filtering system is similar #18058

**Comment by jamestomasino** [comment]
I think the new filtering system achieves the goals that this issue originally requested. Unless anyone objects, I'd suggest marking this resolved.

**Comment by dregin** [comment]
I don't see it on my `v3.5.3` instance. @ClearlyClaire does it need to be enabled somewhere? Can't find anything for it in the admin ui. Thanks!

**Comment by ClearlyClaire** [comment]
> I don't see it on my `v3.5.3` instance. @ClearlyClaire does it need to be enabled somewhere? Can't find anything for it in the admin ui. Thanks!

This is not in v3.5.3, it's in the upcoming version!

**Comment by dregin** [comment]
A sweet, thank you for your work :)
