### ISSUE TITLE
Support for pinning user columns

### ISSUE THREAD

**Issue by allo-** [mastodon/mastodon#7970]
Columns like "user tweets" cannot be pinned currently, but this would be a nice feature.
I for example like to pin my own toot timeline (preferred without boosts), so I can see and find again what I wrote.
Other uses would include monitoring the activity of a bot you're hosting, or following an account of a news website to stay updates with a consistent timeline of this account instead of mixing it into the home timeline.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by trwnh** [comment]
Duplicate of #3858
