### ISSUE TITLE
editing a timed keyword mute makes a permanent keyword mute

### ISSUE THREAD

**Issue by codl** [mastodon/mastodon#7995]
if I set a timed keyword mute and then go back to edit it, the "expire after" is set to none and if I save it without noticing, the mute is now permanent

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Xkeeper0** [comment]
Just bumping this with some screenshots from mastodon.social showing it happening:

![image](https://user-images.githubusercontent.com/1077535/46684919-10689100-cba9-11e8-9bd6-f3df13305d7c.png)

![image](https://user-images.githubusercontent.com/1077535/46684924-12325480-cba9-11e8-9e96-848ad28010b7.png)

**Comment by trwnh** [comment]
filter expiry and filter keywords have been separated in v4.0 and the filter v2 revamp, so this no longer occurs
