### ISSUE TITLE
Text that is usually bold isn't when Roboto is a system font

### ISSUE THREAD

**Issue by iliana** [mastodon/mastodon#8097]
On my Chromebook, and today after installing Roboto on my Linux laptop, fonts that are normally supposed to be bold aren't.

In the image below, the user's display name should be bold.

![screenshot_2018-07-30 cybrespace](https://user-images.githubusercontent.com/52814/43378530-8ae79e9a-9395-11e8-8dc3-c37599de25ad.png)

I *think* this can be fixed by adding `local('Roboto Bold'), local('Roboto-Bold')` before `local('Roboto')` where font-weight is bold (and something similar for the 500 weight) in app/javascript/styles/fonts/roboto.scss.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
