### ISSUE TITLE
Thread display is not consistent between dynamic and static frontend

### ISSUE THREAD

**Issue by ariasuni** [mastodon/mastodon#8117]
Bug report splitted from #7899.

---

To reproduce:

- user1 send a private toot
- user2 answers user1’s toot
- user1 answers user2’s toot

When user3, who follows user1 but not user2, opens any toot that user1 made, they can see:
- on static front-end: the 2 toots of user1, without the toot of user2 [correct]
- on the logged-in UI:
  - if you click on the first toot of user1: the 2 toots of user1 [correct]
  - if you click on the last toot of user1: only the last toot of user1 [incorrect]

The JSON of `context` seems fine (contains ID of every ancestors that should be displayed) and it works in the static front-end, so retrieving the whole thread is probably an easy fix?

**Comment by ariasuni** [comment]
Here:

https://github.com/tootsuite/mastodon/blob/79a1f667c5388ea025b2c160c029191d14e4cfc5/app/javascript/mastodon/features/status/index.js#L71

`state.getIn()` returns `undefined` when the user can’t access the toot.

We could maybe make this function returns the id even when the user can’t access it, but I’m not sure how this change would affect the codebase.

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
