### ISSUE TITLE
Custom emoji are not displayed in Profile metadata label

### ISSUE THREAD

**Issue by Tagadda** [mastodon/mastodon#8140]
Example with the :nb: custom emoji : https://crazynoisybizarre.town/@Dhveszak
![image](https://user-images.githubusercontent.com/36127788/43804306-d811e1c8-9a9b-11e8-85d1-e3ace585b3e3.png)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on master, commit : https://github.com/tootsuite/mastodon/commit/4da03a298a20e5007718764483544593556a5ed4

**Comment by rugk** [comment]
Indeed, I also don't like that. (also there is no auto-completion for emojis there)

Could technically be the same report/issue as https://github.com/tootsuite/mastodon/issues/8116 (dupe).

**Comment by rugk** [comment]
It's a valid unfixed bug.

**Comment by trwnh** [comment]
![image](https://github.com/mastodon/mastodon/assets/10606431/2e11b13e-a501-40b1-bae0-4d8e1c039d9d)
