### ISSUE TITLE
Add resolved option to a toot

### ISSUE THREAD

**Issue by MyNameIsTroll** [mastodon/mastodon#8143]
An option to put a toot in "resolved" would be great and useful.

Sometimes we ask a question but people don't see the answers and keep answering us, it can take a long time to answer everyone.
Maybe it adds the mention (resolved) to the initial toot and has the answer eventually as on some forums. Or it could gray out the initial toot or disable the answers, I don't know what the best option would be.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by jusdepatate** [comment]
pouce bleu

**Comment by TheMrNomis** [comment]
I think this would be a great option.

Maybe a “reaction” system as in github, discord, facebook, etc. ?
Coupled with a privacy settings (e.g Who can react ? or Who can see the reactions) it would be great for “marking as resolved” (Only the tooter can react, everybody can see the reactions) as well as polls (where everybody reacts with a given emoji to express his opinion and either everyone or only the tooter can see the result).

**Comment by jusdepatate** [comment]
no, i think this will be too hard

**Comment by mcb2003** [comment]
I don’t know much about activity pub, so I don’t know how feasible all of this would be, but it would  also be handy if, when you mark something as resolved, you can also mark an accepted answer, like on  most forums.

**Comment by danhunsaker** [comment]
At the least, a "disable replies" option might be handy for certain scenarios. Mastodon is a social platform, not a Q&A service, so while there may be a lot of resistance to "mark resolved"/"mark accepted answer" features, user safety can be served by disabling replies in some cases. Much like disabling comments on GitHub issues, and for generally the same reasons.

**Comment by MyNameIsTroll** [comment]
I think the solution I'm suggesting in this ticket is more appropriate : 
https://github.com/tootsuite/mastodon/issues/12917

**Comment by PhieF** [comment]
Need

**Comment by starcrashr** [comment]
With the edit button coming in the new release on Monday, this can be accomplished by editing your post to add "RESOLVED" to the top. This is how I do it on Discord and Facebook.

**Comment by MyNameIsTroll** [comment]
@starcrashr Indeed, it is possible now:) I close the ticket.
