### ISSUE TITLE
Change the default preview to local on /about

### ISSUE THREAD

**Issue by naught101** [mastodon/mastodon#8176]
From https://github.com/tootsuite/mastodon/issues/1053#issuecomment-412247823

It would be good if the default behaviour of the preview on the About page was set to show only local toots. As it stands, if I visit any random instance, nearly all of them show the federated timeline, which is very similar on many instances, so I get basically the same thing on each, and don't get any feel for the local culture.

Another option might be to show two separate previews on the about page, one local and one federated.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by trwnh** [comment]
the old landing page has been removed, so i am closing this issue as stale
