### ISSUE TITLE
Embed dialog with CW is not correctly sized.

### ISSUE THREAD

**Issue by renatolond** [mastodon/mastodon#8195]
I don't think this is the same issue as #7561 as this is related to the toot size being posted somewhere else.

If I post a toot containing a CW, originally the embed size is correct, but when I click the "show more" button, as the iframe is not resized and is sized to fit the closed CW, the toot gets cut off.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on [v2.4.3](https://github.com/tootsuite/mastodon/releases/2.4.3) and not on `master` (If you're a user, don't worry about this).

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
