### ISSUE TITLE
Push notifications and HTML encoded entities

### ISSUE THREAD

**Issue by edent** [mastodon/mastodon#8248]
I received a push notification saying:

> That`&apos;`s so cool

The original text says

> That`'`s so cool

The push notification came to Firefox for Android 61.0.2 running on Oreo.

### Screenshot
![f2a80323ee78b29c](https://user-images.githubusercontent.com/837136/44270963-c7dbc980-a230-11e8-864d-8455b117e3c0.jpg)

### Toot which caused the notification
https://mastodon.social/@naomialderman/100565975103807068

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by DagAgren** [comment]
This one is an issue for Toot! also.

**Comment by edent** [comment]
Happy birthday little bug! You were fixed a few years ago. So now it is time to close you. Bye-bye!
