### ISSUE TITLE
Reply counts don't update in the WebUI

### ISSUE THREAD

**Issue by ClearlyClaire** [mastodon/mastodon#8324]
Reply counts are not updated in the WebUI. While I understand why (it is very hard to do that efficiently), this makes them mostly useless, as most of the toots will be received by the client with 0 replies.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Sylvhem** [comment]
This makes me really question the interest of displaying the reply count in the WebUI.

**Comment by Gargron** [comment]
>as most of the toots will be received by the client with 0 replies.

This is only true for the streaming API's live updates. Whenever toots are loaded from the backend, the reply counts are there & accurate.

> This makes me really question the interest of displaying the reply count in the WebUI.

That's a strange comment. Native mobile apps may sometimes not use the streaming API at all, so for them, this is as accurate as anything else.

The count is especially useful for older content that is boosted into the home timeline.

**Comment by vmstan** [comment]
Is this still an issue?

**Comment by trwnh** [comment]
Yes

**Comment by trwnh** [comment]
Looks like not:

1. Make a test post
2. Reply to that test post
3. Some seconds later, the counter will update with an animation
