### ISSUE TITLE
Feature to add text description to toots that have already been posted

### ISSUE THREAD

**Issue by haiitch** [mastodon/mastodon#8338]
#Mastodon feature needed:

- Allow users to add a text description to image attachments of toots that have already been posted.

This would help to make an increasing number of toots accessible retroactively without altering their chronological order. 

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by codl** [comment]
Is this more feasible now that mastodon supports edited posts?

**Comment by Akryum** [comment]
Currently trying to edit a toot by adding an image description results in an "Unexpected error" message after clicking on "Apply":

![image](https://user-images.githubusercontent.com/2798204/200795348-479983b5-c47e-46aa-99e7-2b7cf0af4e6f.png)

**Comment by murb** [comment]
This works now, I think this issue can be closed (Mastodon 4.2.x)
