### ISSUE TITLE
[UX?] Sort languages in filter list alphabetically

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#8350]
Thanks to #8322, the languages in the filter list are now sorted top-to-bottom left-to-right, making them much easier to scan through to get to your language! It's a big improvement. :)

![44362239-439b7780-a4b8-11e8-8b82-789219f3e932](https://user-images.githubusercontent.com/6607512/44426280-1ddca400-a586-11e8-90d0-c82d829c4330.png)

It's still pretty confusing though, because the list is sorted by the language's name *in English*, even though the languages are listed named in their own languages. So, for example, Suomi (Finnish) comes just before Français (French).

I feel that the list should be sorted alphabetically by what is visible, rather than by the hidden labels in English. I think having the languages sorted by the letter they start with in their own language is not a problem because if you speak those languages you know what they are called in their languages. So a Greek speaker would look under E anyway.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
What you are looking for is phonetic sorting and I don't think it's easy. Normal string sorting algorithms won't put 日本語 under "n". Right now languages are sorted not by their English name, but by their ISO code. It's close, but a little more neutral.

**Comment by Cassolotl** [comment]
I checked the list order on Twitter and it looks like this. The languages are in the order of their first letter in their own language, so Finnish is under S for Suomi. This makes a lot more sense to me.

![screen shot 2018-08-22 at 10 30 43](https://user-images.githubusercontent.com/6607512/44455668-8499a600-a5f6-11e8-972b-13d40d76db88.png)

**Comment by NecroTechno** [comment]
It seems the sorting is taking place [here](https://github.com/tootsuite/mastodon/blob/995f8b389a66ab76ec92d9a240de376f1fc13a38/app/views/settings/preferences/show.html.haml) (filterable_languages.sort). If we drop the sort function, and make sure the languages stay sorted phonetically in [this](https://github.com/tootsuite/mastodon/blob/8c96fd4967348449d93904fc59326447aeb1cd02/app/helpers/settings_helper.rb) file, the languages should be ordered nicely, right? The only issue with this is that the result isn't sorted programmatically, and will be required to be kept in order in that file.

**Comment by Cassolotl** [comment]
#27158 got merged so I think this is resolved now. :)
