### ISSUE TITLE
[Feature] Split COC, TOS, and privacy policy into different pages.

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#8362]
I figure this was planned? both of the links under resources goes to terms.

also.. I'd like to make these more visible for logged in users

**Comment by Gargron** [comment]
That's bordering on CMS territory and I don't know how to even approach that.

**Comment by ashleyhull-versent** [comment]
Yeah... I figure having the ability to manage multiple pages would be too hard.. but because right now
<img width="117" alt="image" src="https://user-images.githubusercontent.com/17537000/46845510-84b06800-ce27-11e8-9a56-bcb5422fe36a.png">
both of these link to the terms

**Comment by Gargron** [comment]
Well, visitors don't know they're the same page. The idea is that someone might ask "Where is privacy policy?" or "Where are the terms?", if you have one link that just says "About this instance" they won't know to look there, but this explicitly guides them there.

**Comment by twilde** [comment]
"Server description" and "privacy policy" are separate things now. Any chance of terms of service and/or code of conduct getting their own dedicated sections/pages, since they're things ~all instances are likely to want/need?
