### ISSUE TITLE
Many ActivityPub::ProcessingWorker jobs on HTTP::TimeoutError 

### ISSUE THREAD

**Issue by njouanin** [mastodon/mastodon#8364]
Hi,
On mastodon.beerfactory.org I have a constantly growing number of jobs failing with `HTTP::TimeoutError: Read timed out after 10 seconds` error.  See https://mastodon.beerfactory.org/sidekiq/retries for details.
For example I have the following error : `HTTP::TimeoutError: Read timed out after 10 seconds on https://framapiaf.org/users/goofy/statuses/100593097285605959` , but trying a `curl https://framapiaf.org/users/goofy/statuses/100593097285605959` from the server works fine in less than 10 seconds.

* * * *

- [ X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ X ] This bug happens on a [2.4.3](https://github.com/tootsuite/mastodon/releases).

**Comment by njouanin** [comment]
Seen issue #8309, i've disabled ipv6 on my server, but I still get the same timeout error when retrying jobs.

**Comment by njouanin** [comment]
For information, upgrading to v2.5.0rc1 didn't fix the problem. I now have more than 2900+ failing jobs.

**Comment by Gargron** [comment]
Removing the timeout is a bad idea. Yes they complete without failing but they slow down all other processing! It's very strange that those servers don't answer within 10 seconds because 10 seconds is *very* long. It may still be some IPv6 connectivity issue...

**Comment by rhaamo** [comment]
Same issue here.
I don't have any public IPv6 configured and even changed v4/v6 dns resolution precedence and no effect.
And same, not all jobs fails, only ~250/300 timeouts and stay in retry..
By using curl on the timeouting urls works fine in <1s in ipv4, and instant fail with ipv6 (-6 argument).

**Comment by ThibG** [comment]
It is possible that you don't have trouble accessing the remote instance, but the remote instance has trouble accessing yours: if the sidekiq job is about posting an activity, the remote instance might have to perform a request back to your instance before replying. If that request timeouts, your own request will timeout.
I'm not too sure how likely that situation is.

**Comment by nemobis** [comment]
I have (I think) this issue with one specific instance, which pollutes my sidekiq retry queue with up to 7 (?) retries of ActivityPub::ProcessingWorker jobs like

> 108129085150143235, "{\"@context\": \"https://www.w3.org/ns/activitystreams\", \"type\": \"Announce\", \"to\": [\"https://relay.101010.pl/followers\"], \"actor\": \"https://relay.101010.pl/actor\", \"object\": \"https://social.beachcom.org/users/travel/statuses/108158860520026127\", \"id\": \"https://relay.101010.pl/activities/1d509b35-401d-4395-8900-23c3a0f10a17\"}", nil

on errors like

> HTTP::TimeoutError: Connect timed out after 5 seconds on https://social.beachcom.org/users/travel/statuses/108158860520026127

At some point weeks ago this social.beachcom.org instance looked genuinely down but now I have no idea what is going on. Maybe just intermittent overload or maybe some genuine networking issue between those servers.

This is not a big deal but I'd just like to make sure the sidekiq runners aren't wasting most of their time retrying pointless jobs. I still didn't figure out whether it's a misconfiguration on my side, sorry for the noise if so.
