### ISSUE TITLE
When logged in, the remote interaction dialogs could be bypassed

### ISSUE THREAD

**Issue by ClearlyClaire** [mastodon/mastodon#8374]
When a user is logged in, public pages still call the remote interaction dialogs.
Since the user is logged in, this could be avoided, making the experience much easier for a local user.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Sylvhem** [comment]
But if you are logged in to multiple instances simultaneously, which one will be chosen? Or should we display a drop-down menu letting people choosing there instance?

**Comment by ThibG** [comment]
Oh, that is not what I meant: you may be logged in the instance where you are viewing a public page. In this case, rather than going for the whole round-trip, have clicks handled directly by the instance, like they used to be for follows.

**Comment by Sylvhem** [comment]
Oh sorry I misunderstood. Yeah that makes a lot more sense ^^.

**Comment by trwnh** [comment]
public pages have been removed in v4.0 in favor of the web-app rendering everything, so this issue is now stale
