### ISSUE TITLE
Option to reverse scroll the columns

### ISSUE THREAD

**Issue by 8xk40367** [mastodon/mastodon#8384]
I didn't see this in issues, so on behalf of myself and others who have mentioned it on mastodon.technology:

Could we have the option to have columns scroll 'naturally', like a terminal window with new items at the bottom, instead of backwards like Twitter?  It would be great to read a backlog of toots in chronological order from top to bottom.

**Comment by renatolond** [comment]
I think this is a duplicate of #7900
