### ISSUE TITLE
Backspace keyboard shortcut doesn't work in firefox

### ISSUE THREAD

**Issue by pitermach** [mastodon/mastodon#8432]
STR:

- Open a new column, IE to view a user profile or conversation.
- Try to close the new column with backspace.
Expected: The column closes. This works in Chrome (Windows) and Safari (Mac).
Actual result: In firefox, the browser just goes back a page, meaning if Mastodon wasn't the first thing loaded in the tab it gets closed.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by charlag** [comment]
It works for me with:
Mastodon 2.6.5
UA: "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0" (Wayland)

**Comment by fruchti** [comment]
Similar for me on mastodon.social both with Firefox Nightly 83.0a1 (2020-09-26) (64-bit) with `browser.backspace_action` set to `0` and Chromium 86.0.4240.75 with the ‘Go Back With Backspace’ add-on.

It looks as if the Browser would go back twice instead of once when pressing backspace. Probably the propagation of the backspace key press event isn’t stopped, so it is handled both by Mastodon and the browser itself.

**Comment by wviechtb** [comment]
Same happens under Vivaldi. Backspace is the default shortcut for 'History Back', so hitting Backspace actually goes back to whatever page was open before going to Mastodon.

**Comment by DanielGibson** [comment]
This still is an issue with Firefox (at least on Linux?): Pressing Backspace goes back **two** pages instead of one.

**Comment by trwnh** [comment]
seems to work now?

**Comment by fruchti** [comment]
I can still reproduce this issue with Firefox Nightly 115 on Linux on mastodon.social. I have `browser.backspace_action` set to `0` so that backspace navigates back one page everywhere (which is not the default setting in Firefox anymore).

**Comment by Zazcallabah** [comment]
@trwnh please reopen this. it is still reproducible on firefox 115.0.1
