### ISSUE TITLE
French exclamation mark without space before.

### ISSUE THREAD

**Issue by jobastre** [mastodon/mastodon#8433]
French exclamation mark needs a space before in a sentence. It is not the case in the welcome mail and welcome page on mastodon.

* * * *

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
@Sylvhem
