### ISSUE TITLE
Long follower/followed lists have duplicate names

### ISSUE THREAD

**Issue by debbiegoldsmith** [mastodon/mastodon#8436]
If you scroll through a long (200+) list of followers or following on a profile page, you will see accounts repeating multiple times. Somehow the incremental fetching of the list is refetching already-fetched names.

Only happens with the web interface, not in apps accessing via API (e.g. Tootdon). I'm on mastodon.social.

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
