### ISSUE TITLE
[Feature] confirmation on log out.

### ISSUE THREAD

**Issue by aus-social** [mastodon/mastodon#8478]
apparently it looks like the logout will do it's job.. I clicked it by mistake.

<img width="135" alt="image" src="https://user-images.githubusercontent.com/42644106/44642545-0848fd80-aa10-11e8-8ca5-94e823f90749.png">

**Comment by rhaamo** [comment]
It also logout if right-click on it.

**Comment by trwnh** [comment]
![image](https://github.com/mastodon/mastodon/assets/10606431/fa237f47-5889-49e7-a07a-9a8064537b05)
