### ISSUE TITLE
Hashtag links inside embeds don't work

### ISSUE THREAD

**Issue by Gargron** [mastodon/mastodon#8490]
Hashtag links try to open inside the iframe which just leaves it empty. They should open in a new window instead.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by vmstan** [comment]
Is this still an issue?

**Comment by Gargron** [comment]
Clicking anything in the embed now just opens the post, so it's resolved.
