### ISSUE TITLE
[Feature] Hide DMs from feed / Threaded DMs per person (twitter style)

### ISSUE THREAD

**Issue by aus-social** [mastodon/mastodon#8495]
I'd love to see DMs dedicated to it's feed lane.. and also have threaded DMs per username

**Comment by rhaamo** [comment]
There is already an option to see all DMs (from the "Getting Started" menu) and you can pin that column.

For hidding DMs from home timeline there is #7536.

And for the groupping by user, #3819 covers it.

**Comment by trwnh** [comment]
Duplicate of #3819
