### ISSUE TITLE
Missing RTL layout

### ISSUE THREAD

**Issue by BoFFire** [mastodon/mastodon#8496]
Hi, there's a missing RTL layout both for mails when a new user creates an account and for the Welcome Masto intro.

Link : https://mstdn.fr/@BoF/100624353682208710

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
