### ISSUE TITLE
Feature Request: Fixed Width Text Mode

### ISSUE THREAD

**Issue by selfagency** [mastodon/mastodon#8504]
As someone who dabbles in ASCII art, I believe it would be a great boon to creativity on Mastodon if there were to be a fixed width text mode for composing and viewing individual toots. There could be a square icon with a T in it or something next to the post privacy button that, when clicked, changes the font in the post entry form from the default to Courier or another fixed width font, and when posted, wraps the toot in a `<pre></pre>`. It would also be helpful for people with visual impairments using screen readers, or folks who just don't care for it, to have the option in their user settings to hide ASCII art from their TLs all together, which would become possible once ASCII art posts are tagged as such.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by trwnh** [comment]
Subset of #853

**Comment by selfagency** [comment]
closing this because it's 4 years old and i want to clean up my issues tab
