### ISSUE TITLE
Problems after fresh reinstall of my instance

### ISSUE THREAD

**Issue by MCMic** [mastodon/mastodon#8509]
_Note: I tried to send this on https://discourse.joinmastodon.org/ but all I get is "Internal Server Error" when I send the form for creating a topic._

Hello,

My mastodon instance was an old version with some UI changes hardcoded by myself, and it stopped working at some point.
So I decided to start with a fresh install, I had an exported list of the account I followed so I thought it would be ok, I shutdown the old instance and pointed the domain to the fresh install which went well.
But after importing the accounts I followed, it only works for some of them, most of them appear as «waiting for approval», not sur approval by whom, since these are not private accounts.
I also lost all followers, and a friend said that if he tried to unfollow/follow again, he would get an error. (on his instance)

My account is here: https://social.chilliet.eu/@come
The imported follow list contained 99 people and only 32 show up. I had like 20 followers who vanished as well.

What can I do to solve this situation?

**Comment by diplozoon** [comment]
Same error

**Comment by imbsky** [comment]
That was caused by reinstall without database backup and restore.
Well, it should be fine after a while.
If you want to solve this issue immediately, I recommend to change the domain.

**Comment by MCMic** [comment]
Is there anything I can do besides waiting?
Or something I can ask the other instances admin to do to speed up things? (A lot of accounts are from framapiaf which seems to refuse to talk to my instance)

A friend sent me a DM which I received but he never got the reply.

**Comment by imbsky** [comment]
I'm sorry, I have no idea.

**Comment by renatolond** [comment]
Do you have any errors in sidekiq?

**Comment by diplozoon** [comment]
In my case, after a while the follow from my instance was normal.
However, if I look at the account of my instance from another instance, the previous information are displayed.

**Comment by MCMic** [comment]
Yes I have errors in sidekiq.
One example from retries:

> HTTP::TimeoutError: Read timed out after 10 seconds on https://framapiaf.org/users/framasky/statuses/100634439175225359

> 106, "{\"@context\":[\"https://www.w3.org/ns/activitystreams\",\"https://w3id.org/security/v1\",{\"manuallyApprovesFollowers\":\"as:manuallyApprovesFollowers\",\"sensitive\":\"as:sensitive\",\"movedTo\":\"as:movedTo\",\"Hashtag\":\"as:Hashtag\",\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\",\"inReplyToAtomUri\":\"ostatus:inReplyToAtomUri\",\"conversation\":\"ostatus:conversation\",\"toot\":\"http://joinmastodon.org/ns#\",\"Emoji\":\"toot:Emoji\",\"focalPoint\":{\"@container\":\"@list\",\"@id\":\"toot:focalPoint\"},\"featured\":\"toot:featured\"}],\"id\":\"https://mastodon.gougere.fr/users/bortzmeyer/statuses/100634532878622061/activity\",\"type\":\"Announce\",\"actor\":\"https://mastodon.gougere.fr/users/bortzmeyer\",\"published\":\"2018-08-29T16:45:09Z\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"cc\":[\"https://framapiaf.org/users/framasky\",\"https://mastodon.gougere.fr/users/bortzmeyer/followers\"],\"object\":\"https://framapiaf.org/users/framasky/statuses/100634439175225359\",\"atomUri\":\"https://mastodon.gougere.fr/users/bortzmeyer/statuses/100634532878622061/activity\",\"signature\":{\"type\":\"RsaSignature2017\",\"creator\":\"https://mastodon.gougere.fr/users/bortzmeyer#main-key\",\"created\":\"2018-08-29T17:02:35Z\",\"signatureValue\":\"086dSmL+d6SQF74a6J9aXVjeclXmcyAtcvbLUObVDWVF8GUlZdattyW4TAmEnksQwLsfob8Y6IAsBEeoWbw4Cap39QF5vooJ8fnTAI3zpB6YiC2dR8AsxmDQ28U/GwyPRz6x01HSwZZnLm+0lHLbbKwad8C5P6rlib2pdg4xKGI1dCbDYIH1gaf78VupHLWc6KpSy13VNo7TtjMnf55JQJLCmvGuJQkCAr8dMCcG0KdRELzNKuQqsMqAQaPA+r9sVB2A3ndhU8Fetr/AZY2fXiVuJrhdJJIPbZwhSpIrpNcuLJ8+M5wzim4AmExPlgTRg6lAmcDVW6eH17zQOBTRAQ==\"}}"

**Comment by renatolond** [comment]
That one should not be causing any troubles, timeout errors are normal and sidekiq usually retries by itself. You said you installed fresh, did you use the same domain?

**Comment by MCMic** [comment]
Yes of course the same domain, that is the point, to keep the same account. As stated in my first post: «I shutdown the old instance and pointed the domain to the fresh install which went well.»

Today I managed to get my following back by canceling and following each account which was in the waiting state. And one of my previous followers managed to do the same to follow me again. But I have no way of contacting the others to tell them to do this so I have only 1 follower from now on ^^

**Comment by trwnh** [comment]
closing this issue as stale
