### ISSUE TITLE
MP4 not playing video in browsers

### ISSUE THREAD

**Issue by Heiwajima** [mastodon/mastodon#8562]
2.5.0rc1 and 2.5.0rc2

In web browsers, uploaded mp4 files are not showing video content.
Audio content is playing, but only first image of mp4 is showing.
Two different videos from different devices (not Apple) I uploaded

See thread https://vcity.network/@c1t7/100653820603304731

Thread above was from both before and after upgrading to 2.5.0rc2 from 2.5.0rc1.

Uploaded gif images played normally.

Both mp4 and gif video played normally on Subway Tooter for Android

Opening post in browser and downloading mp4 displayed video in VLC.

Opening video URL in new browser window had same issue in chrome

Pasting video URL in Firefox failed to display video.

Issue was detected on Ubuntu 17.10 on Chrome/Firefox/Opera
Verified on Win10 Chrome and Android 7.0 Chrome
KDE Neon with current Firefox

gemlog@mastodonten.de and djsundog@toot-lab.reclaim.technology verified videos were not loading in browsers.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by nightpool** [comment]
I'm assuming this is just an issue with the specific video file?

**Comment by Heiwajima** [comment]
Issue has been recreated with multiple video files from different sources.

**Comment by C1T7** [comment]
Replaced app/models/media_attachment.rb with version from glitch-soc.
All videos working as designed.

**Comment by MightyPork** [comment]
Got a similar issue

```none
Media resource https://cdn-assets.vulpine.owogroupllc.com/media_attachments/files/001/684/946/original/1ba4b26adcf00429.mp4 could not be decoded. 101492886595034350
Media resource https://cdn-assets.vulpine.owogroupllc.com/media_attachments/files/001/684/946/original/1ba4b26adcf00429.mp4 could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)
Details: auto mozilla::SupportChecker::AddMediaFormatChecker(const mozilla::TrackInfo &)::(anonymous class)::operator()() const: Decoder may not have the capability to handle the requested video format with YUV444 chroma subsampling.
```
works in chrome, not in firefox (on linux, if that matters), tusky, some mobile browsers. YUV444 seems to be a problem

see https://vulpine.club/users/Triplefox/statuses/101492886595034350
