### ISSUE TITLE
OAuth sign in web page should not remember the currently logged in user as the account for access authorization

### ISSUE THREAD

**Issue by benoitsan** [mastodon/mastodon#8572]
Actually, when using the OAuth endpoint `/oauth/authorize` that shows the login web view, it automatically logs in, if it exists, the current logged in account.

In my opinion, it should not remember the currently logged in user as the account for access authorization because it makes it hard to support multiple accounts:

1. The user registers his first Mastodon account: the OAuth web view is shown and the user signs in.

2. The user registers a second Mastodon account: 

2.a. If the Mastodon instance for this second account is the same as for the first account: I use the same application (same client_id). The OAuth web view is shown but it's already signed in with the first account and it uses an application which has already been approved by the first account. In this situation, the callback url is immediately called without any user action.

To avoid the immediate redirection, a solution is to generate a new Mastodon application for the second user but it also has some issues: see 2.b

2.b When using a new Mastodon application. The OAuth web view is shown but it's already signed in with the first account. If the user taps on the button to sign out and then signs in, it doesn't redirect to the oauth authorization web view but to the home page. So, the authorization flow is broken, the user needs to cancel and retries (which will work because it's now signed in using his second account). 

The solution 2.b is the only flow I found to support multiple accounts but it has annoying issues:
- Generating multiple applications for the same Mastodon instance is not recommended following the API guide.
- UX is bad (user will need to sign out, cancel and then retries).

Notes:
- This discussion is about the implementation of Mastodon API in a native iOS application. The OAuth webview is shown in `SFSafariViewController ` (or `SFAuthenticationSession`) (web browser shown in a separate process/sandbox).`SFSafariViewController ` doesn't allow to evict the cookies so I can't use this as a workaround for the issues explained before. I could show the OAuth webview in a in-app webview where I could clear the cookies but it's not a good solution for security (oAuth sign in doesn't happen in a separate process) and for UX (credential auto fill doesn't work).
- Twitter API handles this using a parameter `force_login` (https://developer.twitter.com/en/docs/basics/authentication/api-reference/authenticate.html)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by m8811163008** [comment]
Use logout link

**Comment by Gargron** [comment]
We have [`force_login`](https://docs.joinmastodon.org/methods/apps/oauth/) to handle this.
