### ISSUE TITLE
New instance configured for S3 storage with CloudFlare alias, other instances aren't seeing our images

### ISSUE THREAD

**Issue by kode54** [mastodon/mastodon#8587]
We've just configured a new instance of 2.5.0 on ruxnor.net, and it's configured to use an S3 bucket (with dotted name), and uses S3_ALIAS_HOST set to the hostname, which by use of S3 behind CloudFlare, must be the same as the bucket name, which is cdn.ruxnor.net.

We can see our instance's cached images when logged in through the instance, but nobody on other instances can see our avatars, so they all get the "missing" placeholder image.

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate. (well, at least I searched for S3 related issues, as I assume this is an S3 related issue)
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this). (This happens on ccc2f608c5c1caac2ea4796f4490f29d59d67068, which is apparently tagged `2.5.0`.)

**Comment by kode54** [comment]
Huh, I guess it took a few hours or so for the data to spread, as it's now hitting other instances, somehow. Would I have needed to add the bucket's hostname to ALTERNATIVE_HOSTS or whatever it is to get other servers to accept it?

**Comment by kddlb** [comment]
I installed the instance and I can confirm that it *is* a tagged release, [v2.5.0](https://github.com/tootsuite/mastodon/releases/tag/v2.5.0).

**Comment by ThibG** [comment]
No, `ALTERNATE_DOMAINS` is not needed, it's only to allow discovery of your accounts with multiple domain names.
I don't seem to have an issue with displaying your accounts' avatars.
