### ISSUE TITLE
inverse filtering 

### ISSUE THREAD

**Issue by 153** [mastodon/mastodon#8592]
Right now there's a way to filter out certain topics (eg, NSFW, food, politics, etc) which works well, it's a good system, everyone likes it and is very happy with it 

I propose an "inverse filtering" method that shows ONLY these things that are typically filtered out (eg, NSFW, food, politics, etc) that is different from simply doing a search for given hashtags, it could be called "porn mode" or "controversial content mode" 

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by trwnh** [comment]
> that is different from simply doing a search for given hashtags

i don't see how this is any different
