### ISSUE TITLE
Instructions for upgrade to 2.5 are ambiguous (and are unsuccessful when followed)

### ISSUE THREAD

**Issue by CMHarrington** [mastodon/mastodon#8598]
The instructions for updating to 2.5 are incorrect causing the update not to occur. 

> As always, make sure you have backups of the database before performing any upgrades. If you are using docker-compose, this is how a backup command might look: docker exec mastodon_db_1 pg_dump -Fc -U postgres postgres > name_of_the_backup.dump

I can't verify this is accurate for a Docker install, but there is nothing as to how a 'vanilla' Postgres should be backed up. Considering this method is mentioned during normal install, it would be helpful to add basic backup instructions for vanilla Postgres users. *For the remainder of the upgrade instructions, I will be referring to the non-Docker path*

> * Node.js 6.x is no longer supported, so you will need to upgrade to Node.js 8.x
> `curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -`
> `sudo apt update && sudo apt install nodejs`

Which user should be performing this? I'm assuming it should be the unix user who 'owns' the mastodon instance. In the initial install walkthrough, that user would be *mastodon*. 

> Install dependencies: `bundle install` and `yarn install`

'bundle install' fails for me, saying `Could not locate Gemfile or .bundle/ directory`. This is as the mastodon user, in the mastodon home directory. Should this command be run elsewhere? 
It would be helpful if the documentation was explicit as to where this command should be run, and by whom.

> Run the pre-deployment database migrations by specifying the SKIP_POST_DEPLOYMENT_MIGRATIONS=true environment variable:
> …

All these instructions fail because of the  `Could not locate Gemfile or .bundle/ directory` error. 

> 3. Restart all Mastodon processes

How? It would be helpful if the documentation explicitly stated which user, and which commands need to be run.

> Nginx:
> Make sure to update client_max_body_size to 40m or higher.

Where does one do this? It would be helpful if the documentation explicitly stated which file needed to be edited to make this change.

* * * *
- [X ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by manedfolf** [comment]
For the database backup, you should just be able to use anything after `docker exec mastodon_db_1` so try just running `pg_dump -Fc -U postgres postgres > name_of_the_backup.dump`

As for your other issues, all rails commands should be run in the Mastodon application folder, which if you followed the original install instructions exactly, might end up being `/home/mastodon/mastodon`. Rails commands will only run in the folder that contains the Gemfile, so make sure the folder you're working in contains a file called "Gemfile". 

Lastly, your assumption that it should be run as user "mastodon" is correct if you followed the installation instructions. You don't really want to run things as root.

**Comment by Gargron** [comment]
There is a whole manual on all of this under [tootsuite/documentation](https://github.com/tootsuite/documentation). For example, when installing Mastodon, you setup a nginx configuration, it also tells you how to restart processes, how to backup Mastodon.

There are too many different ways someone can deploy Mastodon, if I was writing out a copypasteable bash script it would be inapplicable to half the setups. By mentioning core points, it's up to you to know what's appropriate for your system based on the initial setup documentation.

Most of the commands or instructions mentioned in the release notes are the same you are introduced to during the setup.

**Comment by ashleyhull-versent** [comment]
Not going to lie - Docker makes all of this go away.
