### ISSUE TITLE
Request: Add option to filter people you follow from local timeline

### ISSUE THREAD

**Issue by bannisdale** [mastodon/mastodon#8635]
I constantly run into the inconvenience that I read a lot of duplicate statuses when I browse both my home timeline and my local timeline. Therefore, I would appreciate an option to filter people I follow from the local timeline. I would imagine it to be another option just like the "only show media" option we already have within the options of the local TL.

Thanks!

**Comment by trwnh** [comment]
Duplicate of #8207
