### ISSUE TITLE
media tab of profile in web view is wicked slow

### ISSUE THREAD

**Issue by beatrix-bitrot** [mastodon/mastodon#8662]
- seems like it's due to a slow SQL query (the one i caught in pghero was at over 50 seconds when I looked)
- media view in public profile does not seem to be so slow
- this is on current master ie 47ea31847908e4b6d0a381130ada5662278d52be

**Comment by nightpool** [comment]
I've confirmed this doesn't happen on 2.4.5

**Comment by Gargron** [comment]
Should be fixed by #17709
