### ISSUE TITLE
Overlapping domain text and More text in footer

### ISSUE THREAD

**Issue by Espionage724** [mastodon/mastodon#8729]
[Site](https://social.realmofespionage.xyz/@Espionage724)
[Image](https://i.imgur.com/e1bfeJo.png)

In the footer, the domain text and More text are overlapping.

I'm running master branch currently.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by KNTRO** [comment]
Hello,

I've found another kind of overlapping between a customised profile and toots. This is on Mastodon web v2.9.2.

![Mastodon_overlap](https://user-images.githubusercontent.com/2568821/63632584-5b4b9580-c60f-11e9-8929-0fe205a8ce90.png)

**Comment by trwnh** [comment]
footer has been redesigned since. closing issue as stale
