### ISSUE TITLE
Better UX for remote interactions with toots?

### ISSUE THREAD

**Issue by alxlg** [mastodon/mastodon#8809]
Recently #916 was closed  adding an awesome feature, interact with toots remotely like remote following.

Actually when you try to boost, reply or favourite a toot on instance X it will ask for your address and you are redirected to instance Y that what does is basically show the original toot so you can interact with it.

I think it would be nice to have this instead:

1. Click on reply button on instance X redirect you to instance Y that show you the original toot and below the input text box and the button to confirm the reply.
2. Click on favourite button on instance X redirect you to instance Y that ask for confirmation: "do you want to favourite this?"
3. Click on boost button on instance X redirect you to instance Y that ask for confirmation: "do you want to boost this?"

I think this is how an average user expect it to work. I admit that when I tried to interact with a toot remotely and the original toot was shown on my instance I was a bit surprised/confused and I wondered if I should manually boost it or it was already boosted.

I understand that opening the toot in instance Y is better if you want to perform multiple interactions because you don't need to enter instance address multiple times and this is why it would be good in my opinion to keep this as a separate option: "open in another instance" next to favourite, boost and reply buttons.

If we will be able to perform remote reply like I suggested it would be nice and trivial to write a simple button ("Comment with Mastodon") in our blogs that ask for Mastodon ID and then redirect to Mastodon's remote reply widget (of course to complete the Mastodon-for-comments experience the blog will care about publish the articles as ActivityPub's Articles and show replies as comments to the articles).

**Comment by trwnh** [comment]
added, removed, added again, and about to be implemented again https://github.com/mastodon/mastodon/pull/24842
