### ISSUE TITLE
Proposal for Webhooks

### ISSUE THREAD

**Issue by ContainsLiquid** [mastodon/mastodon#8890]
Note: Please excuse my language, i might have made a few mistakes since english isn't my first language.

**Proposal for Webhooks**
A big part of the mastodon ecosystem are bots to automatically interact with the mastodon userbase. Since the method of interacting with the mastodon servers relies on polling, having a lot of bots on an instance uses a lot of ressources.

I would like to propose webhooks as an alternative to the classic polling mechanism. If an account would be marked as bot it would be then possible to define events (toot, mention, new follower, etc.) and an url which will be called on a new event. While calling the url a standardized payload would be send to the url in question.

This would allow even small instances to use multiple bots, since bots would only activate if certain events would get triggered, instead of bots polling all the time.

The payload could consist of the following fields:

* timestamp of the event
* type of the event
* account who triggered the event
* message body which contains texts and images

Thank you for reading and have a nice day.
Feel free to toot at me at @containsliquid@mstdn.io
* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ineffyble** [comment]
+1 This matches how the new Twitter APIs work. It also opens up options for "Serverless" bots (e.g. with AWS Lambda or Google Cloud Functions) that only run in response to events.

**Comment by rinsuki** [comment]
If you need only notifications(e.g. follow, mention, favourite, boost event), you can use Push API.

https://docs.joinmastodon.org/api/rest/notifications/#post-api-v1-push-subscription

**Comment by ThatXliner** [comment]
Is there a way to have a webhook that gets fired when someone post a new mastodon microblog?

**Comment by massimo-conversocial** [comment]
Year 2023, and still opened

**Comment by trwnh** [comment]
hasn't this been added since? 4.0 includes some webhooks and 4.1 includes some general webhook templating iirc

**Comment by VyrCossont** [comment]
mastodon/mastodon#24133 adds administrative webhooks for posts.
