### ISSUE TITLE
Add multiple filters in one dialogue

### ISSUE THREAD

**Issue by CosineP** [mastodon/mastodon#8915]
Right now, if I want to add multiple filters with the same settings, I must go through the add filter dialogue, enter a word, set the settings, click submit, *then repeat ad-nauseam*. I suggest that I can

1. Add each word/phrase I'd like filtered on *separate lines* in the Add Filter dialogue
2. Set the settings for *all of these phrases* below exactly how it is
3. Click submit, all filters are added

Pleroma has the one-line-per-filter interface and it's much, much, more convenient.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by trwnh** [comment]
It would also be really helpful to be able to use multiple keywords in a single filter that can be enabled/disabled at once.

**Comment by trwnh** [comment]
this might no longer be relevant with the revamped filter functionality
