### ISSUE TITLE
"tootctl settings help" returns incorrect output

### ISSUE THREAD

**Issue by rtucker** [mastodon/mastodon#8920]
`tootctl settings help` omits the `settings` word from the commands list:

```
rtucker@smithwicks:~/vulpine.club/mastodon$ docker-compose run --rm web tootctl settings help registrations
Starting mastodon_redis_1 ... done
Starting mastodon_db_1    ... done
Starting mastodon_es_1    ... done
Commands:
  tootctl registrations close           # Close registrations
  tootctl registrations help [COMMAND]  # Describe subcommands or one specific subcommand
  tootctl registrations open            # Open registrations

rtucker@smithwicks:~/vulpine.club/mastodon$ docker-compose run --rm web tootctl settings registrations open
Starting mastodon_db_1 ... done
Starting mastodon_redis_1 ... done
Starting mastodon_es_1    ... done
OK
rtucker@smithwicks:~/vulpine.club/mastodon$ docker-compose run --rm web tootctl registrations open
Starting mastodon_db_1 ... 
Starting mastodon_es_1    ... done
Starting mastodon_redis_1 ... done
Could not find command "registrations".
```

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
I think that's a thor bug.

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
