### ISSUE TITLE
Assign HTML lang attribute to each TOOT for correct font selection

### ISSUE THREAD

**Issue by RadarNyan** [mastodon/mastodon#8933]
> For example, in a page encoded in Unicode, text in Simplified Chinese, Traditional Chinese, Japanese, and Korean languages may share the same code point for an ideographic character, but speakers of these languages expect the glyphs used to vary in small details from language to language. In the absence of explicit styling applied by the content author, some browsers automatically assign appropriate fonts according to the language of the content.
>   
> ![](https://www.w3.org/International/questions/qa-lang-why-data/ideographs.png)

https://www.w3.org/International/questions/qa-lang-why#fonts

To get the correct font selection (in order to show correct glyph), it is necessary to assign language attributes to each TOOT, or at least to those are not in the user-default language.

Also, it would be somewhat necessary to have the ability to manually select language for each toot (#3478) as it could be difficult for auto language detection to distinguish CJK languages.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
On the public pages, each toot does have a `lang`. Likewise, people can select their posting language to override automatic detection. Maybe `lang` is missing in web UI, is that where you need it?

**Comment by RadarNyan** [comment]
![image](https://user-images.githubusercontent.com/2091529/46813396-922b0b00-cdb1-11e8-98cd-d57047e959db.png)
This could be hard to non-CJK users to understand so I made a simple example to show the difference between the same character between Chinese/Japanese. It can be understood but would look wrong to native speaker.

I've tested the Mastodon.social web version, Android APP Tusky, non of them seem to care about this, it always shows in my default language.
  
> people can select their posting language to override automatic detection

Can you provide more detail on this? I wonder if the posting language is saved with the post and wouldn't change in the future, or it would always be override by latest user setting?

**Comment by gunchleoc** [comment]
Since we now have a language attribute, this should be fixed.

There is 1 additional bug wit the Chinese languages where the wrong locale code gets assigned, but https://github.com/mastodon/mastodon/pull/27099 will take care of that.

@RadarNyan can we consider this issue closed?
