### ISSUE TITLE
silenced users cannot reply to messages sent to them

### ISSUE THREAD

**Issue by kaniini** [mastodon/mastodon#9028]
### Actual behaviour

If a user on an instance replies to a status written by a silenced user they do not follow, they will not receive any replies to their reply by that silenced user.

### Expected behaviour

Users should be able to receive replies from silenced users, when the OP they are both replying to is created by the silenced user.

### Steps to reproduce the problem

Allow replies through if they wouldn't otherwise be allowed through, when they are a direct reply to the person who wrote them.

### Specifications

Affects all known versions.

**Comment by nightpool** [comment]
this is also potentially a problem with the "Allow DMs only from followers" feature

**Comment by deutrino** [comment]
This is a serious problem in light of instance-level silencing; see #5694.

**Comment by Laurelai** [comment]
If you dont follow them and they are silenced how would you even see their OP to reply to it?

**Comment by kaniini** [comment]
@laurelai because you see the boosts

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
