### ISSUE TITLE
Filters don't consider image descriptions

### ISSUE THREAD

**Issue by qguv** [mastodon/mastodon#9060]
### Expected behaviour

After setting a filter at the `/filters` page, images with descriptions matching the filter ought to be removed right along with text posts that match the filter. If I don't want to read about (e.g.) Nick Cage, I certainly wouldn't want to see his face either.

### Actual behaviour

Currently a filter for X won't affect a post with an image whose description includes X.

### Steps to reproduce the problem

1. Find a post with an image description
2. Create a filter that matches the image description but doesn't match the text
3. Go back to the context you found the original post and see that it's not filtered out

### Specifications

instance software: Mastodon 2.5.2
browser: Firefox 62.0.3 on Arch

**Comment by ariasuni** [comment]
Fixed by #17206
