### ISSUE TITLE
Solution to fast scrolling of timelines

### ISSUE THREAD

**Issue by Clay-Ferguson** [mastodon/mastodon#9122]
Timelines are scrolling too fast to read, until user figures out to scroll down some, to make the live scrolling stop. If scrollbar position is > 0, it doesn't live scroll, but if you don't know that you can never tame the firehose of that live feed. 

Feature request: Put a message saying "Scroll down to disable live scroll" in the settings panel as a tip to users. People will at least be looking in there to find a button to throttle it back.

**Comment by sparr** [comment]
This behavior is relatively universal to live scrolling environments. I don't think we need to add another UI element to teach this.
