### ISSUE TITLE
Timeline randomly starts displaying old posts instead of the latest feed

### ISSUE THREAD

**Issue by kode54** [mastodon/mastodon#9185]
### Expected behaviour

Timeline should display most recent posts that have been federated.

### Actual behaviour

Timeline displays only toots from hours or even days ago, even after forcing a browser refresh.

### Steps to reproduce the problem

1. Open Mastodon instance feed in browser.
2. Notice that posts aren’t appearing.
3. Leave page.
4. Post something in another tab.
5. Return to Mastodon tab.
6. Notice that timeline has shifted back several hours.

### Specifications

Mastodon 2.6.1

Safari on iPad 2018 model running iOS 12.1

**Comment by Gargron** [comment]
Sounds like it could be a Sidekiq backlog situation specifically on your server. Cannot reproduce.
