### ISSUE TITLE
Add a toggleable background to the image lightbox.

### ISSUE THREAD

**Issue by davmillar** [mastodon/mastodon#9196]
### Pitch
Add options to place a light or dark background behind the image when shown in a lightbox.
### Motivation
Currently, posting an image with a transparent background can make it unreadable/indecipherable in the Mastodon UI. For example, a chart with black text on a transparent background cannot be read without considerable effort due to the dark theme being used in my instance.
It would be nice to have a background behind the image, and even better if the user can toggle it from within the lightbox easily. Simply adding a light background to the lightbox would fix my one use case described above, but would then hinder readability of light images with transparent backgrounds.

**Comment by MyNameIsTroll** [comment]
I have encountered the same problem many times as well.

**Comment by mjankowski** [comment]
Closing on assumption that this is resolved in newer versions -- can you please add screenshot (from current version) and re-open if not?

**Comment by trwnh** [comment]
![Image](https://github.com/user-attachments/assets/47d5a9f6-a7cf-406a-b67e-5f641f836f11)
![Image](https://github.com/user-attachments/assets/3fcb2aec-03b2-425d-90cf-56f44e3d8b94)
