### ISSUE TITLE
Replying to a Toot and including a hashtag changes Status from Public to Unlisted

### ISSUE THREAD

**Issue by imacdonald** [mastodon/mastodon#9202]
Replying to a Toot and then including a hashtag changes the Status from Public to Unlisted. Explicitly setting the Status prevents this behaviour.

The following Toot includes a screencast video showing this behaviour happening:
https://mstdn.io/@fitheach/101012213149471383

I have only noticed this happening since the introduction of Mastodon 2.6.1.

I have tested this using Palemoon, Firefox & Chromium on Debian Stretch x64, the behaviour happens using all three browsers.

**Comment by nightpool** [comment]
(i edited your post to fix your formatting)

> Sure, but the Status should be set when you press the reply button, not when entering a hashtag

If you look closely at the screencast, you can see that this is already the case. Look at the "privacy" icon in the bottom row, see how it shows the unlisted icon the whole time?

>I often search & discover posts where a hashtag is used by the non-parent.

You're right, this was my mistake. I assumed we used the same logic for hashtags and timelines, when in reality they have different behavior with respect to replies.

>I cannot test this now (as I don't have access to a Mastodon instance pre 2.6.1), but I never came across this behaviour before. Pretty sure it must have been introduced with 2.6+.

the warning box was introduced in 2.6, nothing else about the behavior of unlisted posts changed to my knowledge.

**Comment by imacdonald** [comment]
Thanks for fixing the formatting.

So, if you can search for hashtags in non-parent posts, what exactly does the statement in the warning box mean?

Also, does changing the Status to Public have any effect?

**Comment by nightpool** [comment]
>So, if you can search for hashtags in non-parent posts, what exactly does the statement in the warning box mean?

i means exactly what it says it does. Unlisted posts don't appear in the hashtag list. Replies are unlisted by default, but you can make them public if you want.

>Also, does changing the Status to Public have any effect?

Yes, I was mistaken about this bit, if you change the setting to public it will post in the hashtag timeline.

**Comment by Gargron** [comment]
>Is there anything that can be done about the warning box appearing as soon as I enter a hashtag?

If you want your post to be found through the hashtag, set it to public. However, it is possible that you may want to talk *about* a hashtag and link to it, without appearing *on* the hashtag, which is where being "unlisted" is useful. The warning is there because this is not obvious, and it appears only after you type a hashtag because it only matters when you type a hashtag.

**Comment by trwnh** [comment]
cannot reproduce on latest version
