### ISSUE TITLE
Make design adaptive to vertical screen layouts.

### ISSUE THREAD

**Issue by jonhoo** [mastodon/mastodon#9221]
### Pitch

I have my main monitor rotated 90° so that it is taller than it is wide. This is _great_ for most websites, as it allows more of the main content of the page to be visible at a time, and for websites like Twitter, it enables me to see more tweets at a glance. However, this layout works very poorly with Mastodon with its horizontally stacked columns. It'd be awesome if there was a way to switch to a layout (whether manual or automatic) that did not require so much horizontal space. Perhaps something like the Android App or twitter.com layouts where you have different pages for notifications and lists?

### Motivation

Locking the design to one that requires horizontal screen width isn't ideal, as we are only seeing more diversity in device form factors, whether phones and tables or rotated monitors like mine. I also think there's value in recognizing that Twitter has likely spent *a lot* of time investigating what layout works best, and they have stuck with the "a page per view" layout instead of allowing multiple columns. Perhaps that's something we should at least support as well?

**Comment by Angular-Angel** [comment]
I wish there were more ways to view content on Mastodon in general. For example, the ability to open a list or two in a new tab and view them there, and reply to them there, or the ability to view a post and it's replies in a tree graph like I've been trying to implement in Agora: https://agora-2866.nodechef.com. :/

**Comment by nightpool** [comment]
@angular-angel The Mastodon front-end UI only one client app and only one design—ways to view content that are radically different are better implemented by separate clients that either speak Mastodon's client protocol or the ActivityPub server protocol.

**Comment by nightpool** [comment]
I'm sympathetic to the idea that we should adapt to different screen sizes, but it's also true that we already have two different layouts (a single-column view for mobile, and a multi-column view for desktop), and i'm not sure if the "large rotated screen" setup is common enough to warrant maintaining another whole layout.

@jonhoo that said, i would be interested in seeing a screenshot of your CSS snippet on your monitor!

**Comment by Tagadda** [comment]
@nightpool 
![image](https://user-images.githubusercontent.com/36127788/49413093-0c06c180-f76f-11e8-8c40-b80f9caeb813.png)
