### ISSUE TITLE
Favourites to deleted toots still appear

### ISSUE THREAD

**Issue by kit-ty-kate** [mastodon/mastodon#9234]
### Expected behaviour

Do nothing

### Actual behaviour

A fav notification is displayed in the notification column and won't go away. As the original toot has been deleted the notification points to nothing:
![fav-bug](https://user-images.githubusercontent.com/2611789/48203269-f4e6d680-e35e-11e8-9cec-cc6b4400f859.png)

### Steps to reproduce the problem

Same steps than for #9231. I got this problem as I was trying to reproduce the issue to get a better console output. This time though, I also used Tusky as a way of creating and deleting the toot half the time (if that matters, though I suspect it does not as it seems to be a backend concurrency problem)

### Specifications

Mastodon version: 2.6.1
Web browser: Firefox 63.0.1

**Comment by ThibG** [comment]
Do those notifications stay if you reload the WebUI?

**Comment by kit-ty-kate** [comment]
> Do those notifications stay if you reload the WebUI?

yes.

**Comment by ThibG** [comment]
This is most likely a race condition in the backend, see #2865 (or another bug I can't find right now).
Basically happens when a `Notification` is created for an activity that is deleted in the meantime.
I'm not too sure how that can be fixed :/

**Comment by Gargron** [comment]
It can't be fixed. Best bet is a periodic clean-up task that finds these and deletes them, but I'm not sure that's worth the effort at all
