### ISSUE TITLE
Replace hyphen-minus to underscore if include user id w/LDAP

### ISSUE THREAD

**Issue by owatan** [mastodon/mastodon#9256]
### Pitch
I using Mastodon w/LDAP, but if include hyphen-minus (`-`) in user id, cannnot register account.
(Maybe deny in validation when create account in Mastodon.)

- like: `b-alice`, `a-bob`, etc ...

related ? issue: #6830

-----

If include `-` in user id, replace underscore (`_`) .
and registered user id what replaced character strings.

- like: `b-alice` -> `b_alice`, `a-bob` -> `a_bob` .

### Motivation
Mastodon may be used more on the corporate intranet.

**Comment by SuperSandro2000** [comment]
see #12021

Looks like you just need to set the ``LDAP_UID_CONVERSION_ENABLED=true`` env.

So this can be closed.
