### ISSUE TITLE
Avatar on PM gets replaced with recipient's avatar

### ISSUE THREAD

**Issue by sdomi** [mastodon/mastodon#9284]
### Expected behaviour

Your avatar should appear next to his nick

### Actual behaviour

Recipient's avatar appears next to my nick.

### Steps to reproduce the problem

Send a PM message, look at the DMs column.

![pic1](http://sakamoto.pl/tmp/15-11-2018_02-55-48.png)
while my real avatar can be seen here
![pic2](http://sakamoto.pl/tmp/15-11-2018_02-56-22.png)

### Specifications
Happens on Mastodon 2.6.1 (niu.moe)

**Comment by trwnh** [comment]
should be more clear now, as the component says "with (other person)"
