### ISSUE TITLE
Update Twemoji to version 11

### ISSUE THREAD

**Issue by koyuawsmbrtn** [mastodon/mastodon#9317]
What about upgrading Twemoji to the latest version?

**Comment by Sylvhem** [comment]
[Twemoji 11](https://github.com/twitter/twemoji/releases/tag/v11.0.0) include support for the new Unicode 11 specification. This new version add 64 new emojis, including 🦞.
We are currently still using Twemoji 2, so I suggest we update to [Twemoji 11.2](https://github.com/twitter/twemoji/releases/tag/v11.2.0) as soon as possible.

By the way @koyuawsmbrtn, to you think it's possible to change this issue's title to something like "Update Twemoji to version 11"?

**Comment by Gargron** [comment]
Our Twemoji is v11. I recently updated codepoint maps to the 11 spec. The emoji database of emoji-mart still doesn't include them in the listing/search though.
