### ISSUE TITLE
"Load More" button within Notifications column appears even if all notifs are loaded

### ISSUE THREAD

**Issue by sinisbad123** [mastodon/mastodon#9333]
### Expected behaviour

Load More button should not be there if there are no more notifications to render

### Actual behaviour

"Load More" button is there and when clicked, suddenly disappears.

### Steps to reproduce the problem

1. Create a new profile/account
2. Have some few notifs (around three), the "Load More" button will be there
3. When clicked, the button would disappear.

### Specifications

tootsuite/mastodon (v2.6.1).
MacOS High Sierra v10.13.6
Firefox 63.0.3 (64-bit)

**Comment by sinisbad123** [comment]
Maybe put a refresh button or a more appropriate icon in case the user wants to refresh manually?

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
