### ISSUE TITLE
Make the DM column last posts different from normal posts

### ISSUE THREAD

**Issue by kit-ty-kate** [mastodon/mastodon#9341]
### Pitch

Last posts shown on the DM column shouldn't have the DM greyed out icon, favourite button and side menu (and also maybe reply button but that might be handy)

### Motivation

Following #9190, somebody pointed out that the threads in the DM column should be different from normal posts. This feature make them significantly different.

**Comment by lapineige** [comment]
That's doesn't completely solve the issue, as DM still have the same background color and general look, and you still have others' avatars next to any DM including your messages, but that would be a readability improvement.
