### ISSUE TITLE
HTML is not sanitized on profile edit preview

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon#9343]
### Expected behaviour

![image](https://user-images.githubusercontent.com/5047683/48976693-a52e3c00-f0ce-11e8-8afb-6ca077869ac1.png)

### Actual behaviour
![image](https://user-images.githubusercontent.com/5047683/48976680-71531680-f0ce-11e8-9751-5a1fee7b4de5.png)

### Steps to reproduce the problem

Set display name as `<script>alert(1)</script>a` and preview

After saving it, it shows normally, But only in preview

**Comment by pawelngei** [comment]
I can implement a fix tomorrow.

**Comment by nightpool** [comment]
I'm not seeing a difference between the two screenshots?

**Comment by nightpool** [comment]
oh, it's in the profile card. pretty minor issue, but we'd be happy to accept a fix (should be as simple as using textContent instead of innerHtml)

**Comment by pawelngei** [comment]
It's not just `textContent`, it seems to be caused by `emojify(escapeTextContentForBrowser(displayName), emojiMap)`, since it occurs only when typing. If the profile page loads with `<script>` in the variable, it's displayed as text.

**Comment by pawelngei** [comment]
It's in Ruby, `_card.html.haml`. Now I'll learn some more Ruby and I'll fix this :P

**Comment by pawelngei** [comment]
Okay, I can honestly say I know Ruby to little to fix it. More data:

`_card.html.haml` contains `%strong.emojify.p-name= display_name(account, custom_emojify: true)`

`stream_entries_helper.rb`:
```
  def display_name(account, **options)
    if options[:custom_emojify]
      Formatter.instance.format_display_name(account, options)
    else
      account.display_name.presence || account.username
    end
  end
```

and finally `formatter.rb`:
```
  def format_display_name(account, **options)
    html = encode(account.display_name.presence || account.username)
    html = encode_custom_emojis(html, account.emojis, options[:autoplay]) if options[:custom_emojify]
    html.html_safe # rubocop:disable Rails/OutputSafety
  end
```

I don't know which element causes HTML not to be sanitized when typed in dynamically and sanitized on initial page render.

**Comment by nightpool** [comment]
again, it's not in the ruby. ruby runs on the server, JavaScript runs on
the client. the live preview discrepancy is solely caused by not escaping
things on the client side

**Comment by pawelngei** [comment]
Okay, I communicated this badly, I'm sorry.

What I'm trying to say that this script is not a part of the frontend application, since this view is not rendered by React. According to event listeners, the script handling this input is `rails-ujs.js?e1aa`, something used and injected by Rails. My knowledge of the platform doesn't allow me to find how and where it is constructed and/or injected.

The script is generated using https://github.com/rails/rails/tree/master/actionview/app/assets/javascripts

**Comment by Gargron** [comment]
The code that does the preview is in app/javascript/packs/public.js I think

**Comment by pawelngei** [comment]
Found it! Submitting a PR with a fix shortly. Thanks @Gargron !

**Comment by pawelngei** [comment]
Can be closed now.
