### ISSUE TITLE
Regression 2.6.2: Web-view does no longer fit on screen

### ISSUE THREAD

**Issue by scroom** [mastodon/mastodon#9344]
### Expected behaviour

The web view should adjust to the monitor size.

### Actual behaviour

The web view does not adjust to the monitor size. Some pixels are missing, so that you have to scroll vertically. 

### Steps to reproduce the problem

1. Update to Mastodon 2.6.2
2. Login to the webview

### Specifications

2.6.2
tested with Chromium and Firefox under Ubuntu 18.10. Screen-Size 1280*1024
![bildschirmfoto vom 2018-11-25 10-45-23](https://user-images.githubusercontent.com/5347731/48977716-fb37bb00-f09f-11e8-91ca-b836f4575f55.png)

**Comment by mjankowski** [comment]
Closing on assumption that this is resolved in newer versions. Can you re-open with current screenshots if still problem in 4.3?
