### ISSUE TITLE
Show thread doesn't show up on the first toot of a thread

### ISSUE THREAD

**Issue by kit-ty-kate** [mastodon/mastodon#9355]
### Pitch

Since 2.6.2, "show thread" is displayed instead of the double reply arrows. A good thing would be this "show thread" to be shown on the first toot as well.

### Motivation

People who would encounter a first toot of a thread would know it's a thread. This is common practice for people to boost only the first toot of a thread but for now, nothing indicates that it's actually a thread. Only if you see a reply then you can see it's a thread (which doesn't help in the case of a boost on the first one)

**Comment by trwnh** [comment]
"Show thread" at the bottom has been replaced with "Replied to x" at the top
