### ISSUE TITLE
Make a clearer distinction between "show thread" and the content

### ISSUE THREAD

**Issue by kit-ty-kate** [mastodon/mastodon#9356]
### Pitch

It would be a good idea to move "show thread" below the reply/boost/fav icon like twitter does. Also maybe shift it a bit to the left so that it make a every clearer distinction.

### Motivation

This would make a clearer distinction between the content of the toot and this link.

**Comment by trwnh** [comment]
You mean like this? 
![image](https://user-images.githubusercontent.com/10606431/49046231-04588300-f199-11e8-8fe3-c391beadf551.png)

**Comment by kit-ty-kate** [comment]
@trwnh yes, that'll do

**Comment by Gargron** [comment]
I'm sorry, I do not like that proposal visually. I think the way it's now makes more sense?

**Comment by kit-ty-kate** [comment]
> I think the way it's now makes more sense?

how does it make more sense? It's the way Twitter does it (and people seem generally ok with it) and also having a link in the area where you expect to get the content of the toot is kinda bad for readability.

Also, there is no way to distinguish between a normal link coming from pleroma for example (or media names), and this.

**Comment by Tuxhedoh** [comment]
> 
> 
> > I think the way it's now makes more sense?
> 
> how does it make more sense? It's the way Twitter does it (and people seem generally ok with it) and also having a link in the area where you expect to get the content of the toot is kinda bad for readability.

Saying this is the way Twitter does it, doesn't really help to make a case.

**Comment by ebehar** [comment]
So why not respond to the rest of it aside from the part about Twitter?

> having a link in the area where you expect to get the content of the toot is kinda bad for readability.
>
> Also, there is no way to distinguish between a normal link coming from pleroma for example (or media names), and this.

The way it is right now in the UI, "Show Thread" looks like part of the body of a toot. ‾\_(ツ)_/‾

**Comment by Amgine0** [comment]
> I'm sorry, I do not like that proposal visually. I think the way it's now makes more sense?

The actions menu is graphic buttons, and provides a clear and natural break from the text of the toot. Additional text action links should be separated from the body of the toot, which placing them below would accomplish. That is, the way it is now does **not** make more sense to me.

**Comment by LoMakesComics** [comment]
Twitter seems to be also adding (for some threads) a smaller version of the avatar and a line connecting the two together. I think it's part of why it works better visually, with the link being outside the post instead of it just floating below the action buttons by itself.

![image](https://user-images.githubusercontent.com/33736546/49296292-982a9780-f496-11e8-8a1b-f0d8f2109c4c.png)

I personally think the current behavior is ok if only because as far as I'm aware you cannot have a link that looks like that in the toot. Though some improvements could be made for new users that are not aware of this? One could argue that if you don't read that it says "Show Thread" then at a glance it looks like a link in the toot, but two words do not look like a url at a glance.

**Comment by trwnh** [comment]
Alternate options:

above toot | explicit "in reply" | greyed out
--- | --- | ---
![image](https://user-images.githubusercontent.com/10606431/49314285-94573f00-f4af-11e8-9d63-76ef8ba35605.png) | ![image](https://user-images.githubusercontent.com/10606431/49314388-e7c98d00-f4af-11e8-919b-5e19f29dc921.png) | ![image](https://user-images.githubusercontent.com/10606431/49314445-1d6e7600-f4b0-11e8-9b58-79ca312af5f3.png)

**Comment by kit-ty-kate** [comment]
I like the greyed out one for replies very much!!

Though I'm not convinced about having "Show thread" above. Maybe there is a way to have the same kind of design than greyed out replies with a logo and something more telling like `continuing thread`. But it'd have to be different enough from the replies to avoid taking toots for replies I guess.

**Comment by trwnh** [comment]
might be worth revisiting this especially after #9228 and specifically https://github.com/tootsuite/mastodon/pull/9228#issuecomment-444140017

> I worry that new users will see the occasional "Show thread" for self-replies and think that is the sole indicator of a thread, not even realizing there are other types of threads [...] Plus, you can reply to a thread without mentioning a user [...]

The double-arrow thing is something I just had to explain to someone who's been using Mastodon for over two years. It might be worth rethinking the way Mastodon indicates that something is a reply. Cases that might lead to UX confusion:

- Mentions that are not in reply to anything
- Replies that do not contain mentions
- CW'd posts that contain mentions or are replies

**Comment by trwnh** [comment]
I believe this has been implemented as part of 4.0 so the issue can be closed
![image](https://user-images.githubusercontent.com/10606431/201582100-1cdfea95-c01c-489b-8f9a-ecaa2a7183b1.png)

**Comment by kit-ty-kate** [comment]
Awesome! Thanks!
