### ISSUE TITLE
Does the public post import feature follow redirections?

### ISSUE THREAD

**Issue by MrPetovan** [mastodon/mastodon#9390]
### Expected behaviour

Taken from https://github.com/friendica/friendica/issues/6212:

> When giving a link to Friendica post to a Mastodon search (like this: "https://friendica.mrpetovan.com/display/735a2029-105b-feae-774e-519940805389") it should fetch and "find" this post then let the user interact with it.

### Actual behaviour

The search ends up empty.

### Additional information

Friendica uses a redirection from `/display/735a2029-105b-feae-774e-519940805389` to `/objects/735a2029-105b-feae-774e-519940805389` when the `Accept: application/activity+json` is supplied.

So this doesn't work:
```
curl -sH "Accept: application/activity+json" https://friendica.mrpetovan.com/display/735a2029-105b-feae-774e-519940805389
```

But this works (notice the following Location `L` flag):
```
curl -sLH "Accept: application/activity+json" https://friendica.mrpetovan.com/display/735a2029-105b-feae-774e-519940805389
```

**Comment by Gargron** [comment]
I believe this happens because verification fails when requested URL does not match returned `id` in the JSON, i.e. this is the result of a security check.

**Comment by MrPetovan** [comment]
Ah, thanks.

**Comment by annando** [comment]
In Friendica we do two two different url for a post. One is the object id, the other one is the display url. When there is a JSON request for the display url, we are doing a redirect to the correct id path.

**Comment by MrPetovan** [comment]
@Gargron Is this behavior codified anywhere?
