### ISSUE TITLE
Start a bug bounty program

### ISSUE THREAD

**Issue by EdOverflow** [mastodon/mastodon#941]
Since you have gained a lot of attention from the infosec community, I would highly recommend starting a bug bounty program. This would allow researchers to contact you when they discover security vulnerabilities. HackerOne offer free programs to open source platforms: https://www.hackerone.com/product/community

I currently run one, so if you need any help getting started feel free to contact me.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ClearlyClaire** [comment]
There's a bug bounty program for Mastodon at https://app.intigriti.com/programs/mastodon/mastodonio/detail
