### ISSUE TITLE
"Block DMs from people you don't follow" doesn't work completely

### ISSUE THREAD

**Issue by Cassolotl** [mastodon/mastodon#9424]
### Expected behaviour

I am unable to see DMs from people I don't follow, anywhere.

Ideally, when someone I don't follow tries to send me a DM it would fail with an error message, such as "this person only sees DMs from people they follow."

### Actual behaviour

I saw a DM from someone I don't follow in conversation view. They replied to a public post of mine with a DM, and it's not in my DM column or my notifications, but I see it in the replies to the original public post.

### Steps to reproduce the problem

1) Make two accounts, A and B.
2) B follows A, and A doesn't follow B.
3) A has "block DMs from people you don't follow" checked.
4) A makes a public post.
5) B replies to A's public post with a DM.
6) A can see B's DM in conversation view by clicking on their public post to open it in the fourth column.

### Specifications

v2.6.2+glitch (vanilla flavour)

Mac, Chrome.

**Comment by Cassolotl** [comment]
There's also the thing where you can see someone's DMs to you on their profile even when you have "block DMs from people you don't follow" checked.

1. Sally doesn't follow John.
2. Sally has "block DMs from people you don't follow" checked.
3. John DMs Sally, and Sally doesn't get notified.
4. Sally visits John's profile and clicks "toots and replies".
5. The DM to Sally from John is clearly visible among all toots and replies, even though Sally has opted not to see any DMs from John because Sally isn't following John.

**Comment by trwnh** [comment]
this probably depends on #8565 to be enforceable. or it could be renamed so that it says "mute/hide/filter dms from people you don't follow", since that's really what's happening.

**Comment by ThibG** [comment]
One way would be to drop processing the *mention* (like with blocked people) on the receiving server. Other mentioned people would still be mentioned though.

There's also nothing to signal other people that the account is using that setting. If we added one, I guess we could reject DM creation on the client API with an error like “cannot be posted because `@foo` doesn't accept DMs from people who do not follow them”

**Comment by Cassolotl** [comment]
This recently happened to me again. I shouldn't be able to see DMs from people I don't follow _anywhere_, but I can see them in profiles and in conversation view.

**Comment by ClearlyClaire** [comment]
I'm not sure what should be done there, to be honest. We can't really prevent the DM itself from existing, since people should still be able to mention other users… maybe not create a mention at all, but is there any benefit to not having the message accessible when other people have access to it?

**Comment by trwnh** [comment]
maybe handle the cases where it's a 1:1 direct post and the recipient has the setting enabled? that would push the issue further down the road, sure, but at least it would handle "half" of the cases.

alternatively, re-define the setting so it applies to the upcoming message type and not the status type? not sure what to do either, since the expectations around direct-visibility posts is very confusing in their current form... if a messate/status distinction is made then it would effectively mean that direct statuses should be treated the same as any other status -- which is to say, if you are receiving an unwanted mention, then the solution is to mute or block the person rather than try to filter out the status.

**Comment by ClearlyClaire** [comment]
> alternatively, re-define the setting so it applies to the upcoming message type and not the status type?

Sorry, I don't understand what you mean here :sweat_smile:

**Comment by trwnh** [comment]
> > alternatively, re-define the setting so it applies to the upcoming message type and not the status type?
> 
> Sorry, I don't understand what you mean here sweat_smile

i meant that "block DMs" will mean something different once there are actual DMs and not just "mentions only" statuses

**Comment by Cassolotl** [comment]
>We can't really prevent the DM itself from existing, since people should still be able to mention other users… maybe not create a mention at all, but is there any benefit to not having the message accessible when other people have access to it?

If I don't follow someone, I can't see their followers-only posts on their profile. The same should be true of people's DMs when I don't follow them and my DMs are set to "people I follow only".

**Comment by rbairwell** [comment]
@ClearlyClaire said in relation to the "block DMs from people you don't follow" option:

> There's also nothing to signal other people that the account is using that setting. If we added one, I guess we could reject DM creation on the client API with an error like “cannot be posted because `@foo` doesn't accept DMs from people who do not follow them”

This is the solution I prefer, but I'm not sure how that would work in the defederated model as it'll require the origin to contact the destination straight away to produce the message (unless there is the concept of "bounceback/rejected system messages" as per email in ActivityPub that I'm not aware of).

Perhaps if the [Account ](https://docs.joinmastodon.org/entities/Account/ ) had a new field "acceptsDms" with a choice of:
* "all" (current default)
* "following" (as requested),
* "local" (limited to just the user's home instance)
* "none" (no dms at all)
which then can be taken into account when the client auto-suggests the full username with the /api/v1/accounts/search?q=....&resolve=false&limit=4 requests. If a DM is received by the server and it doesn't qualify under those restrictions then it is silently dropped on the basis "sending user should have been alerted by client".

**Comment by Cassolotl** [comment]
Just checking - is this closed because it's fixed, or because DMs to me that I've said in settings I don't want to see will continue to be visible when visiting someone's profile, in conversation view, etc?

**Comment by trwnh** [comment]
closed because the setting has been removed in favor of the new "notification filters" feature. i guess there's #29722 as the next-closest issue? that one requests that a similar checkbox be properly implemented with more complete support for hiding/dropping unauthorized interactions.
