### ISSUE TITLE
Show last activity date on authorized apps

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon#9428]
Currently, authorized apps showing Application's name and authorized date.
![image](https://user-images.githubusercontent.com/5047683/49490196-21c0d780-f892-11e8-9036-84b6987879ea.png)

On the other hand, Session list are showing IP address and last activity time.
![image](https://user-images.githubusercontent.com/5047683/49490244-6ea4ae00-f892-11e8-83f5-95c005f78b13.png)

When user decide to remove unused authorized app tokens, It would be better with last activity time instead of authorized date.

**Comment by danhunsaker** [comment]
It would be important to show both times, IMHO.

**Comment by fowl2** [comment]
I believe this is already implemented in https://github.com/mastodon/mastodon/pull/17656: 

![image](https://github.com/user-attachments/assets/a68a2d82-8c44-454c-bc83-319b16c57203)
