### ISSUE TITLE
Mastodon doesn't respect HTTP 405 responses from other ActivityPub end-points

### ISSUE THREAD

**Issue by mariusor** [mastodon/mastodon#9435]
### Expected behaviour

Once a certain threshold of HTTP 405 responses is reached (~5-10), Mastodon should remove the end-point from its list of federated end-points. 

HTTP response 405 means that the end-point is signaling that it's not federated - in accordance with the ActivityPub spec.

### Actual behaviour

Mastodon keeps pushing new Activities to end-points that are replying with HTTP 405 Method not Allowed responses.

### Specifications

The requests are coming from mastodon.social which at the moment of submitting this ticket is running v2.6.4.

Thank you.

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this can be reliably reproduced on an updated version please open a new issue with updated logs/troubleshooting and we will take a look. Thank you.
