### ISSUE TITLE
Ability to subscribe or follow tags

### ISSUE THREAD

**Issue by nebulade** [mastodon/mastodon#945]
Similarly to following users, it would be great to be able to follow tags, so toots using the followed tags show up in the timeline. Ideally also with an option to show notifications in a similar manner than mentions.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by fallerOfFalls** [comment]
+1

**Comment by nd-** [comment]
Yes, that would be nice and very usefull.
But what toots should show up in your home timeline ? local ? federated ? all instances ?

**Comment by nebulade** [comment]
Good point. I personally would like to see all toots with that tag (federated+local) showing up in my home timeline, so basically the same as toots from people I follow.

**Comment by nd-** [comment]
Yes, that seems the best way.

**Comment by Cassolotl** [comment]
Just spotted this on Instagram today:

![insta](https://user-images.githubusercontent.com/6607512/38805071-75f47754-416c-11e8-8bc5-1bdd5444dc2c.jpg)

**Comment by Cassolotl** [comment]
This topic is almost the same as *option to follow hashtags #1096* - they were opened at the same time but #1096 has a lot more detail and discussion. Could this one be closed as a duplicate?

**Comment by rzr** [comment]
Relate-to: https://discourse.joinmastodon.org/t/request-follow-hashtags/1293/14
