### ISSUE TITLE
localhost:3000 => unable to connect

### ISSUE THREAD

**Issue by ManicPumpkin** [mastodon/mastodon#9486]
Hello,

I set up the mastodon docker like mentioned in the tutorial, but as soon as I try to connect to the server I get the following error from my webbrowser: "Unable to connect". There is mentioned, that the site may be currently unavailable or busy or that the firewall or proxy might me misconfigured, but I neither have a firewall/proxy in between (same PC), nor the site is unavailable. 

If I check the logs of my docker container then there is written "[bd4087b9-4dca-45a5-d72a994462f4] method=GET path=/ format=html controller=HomeController action=index status=301 duration=19.33 view=0.00 localtion=https://localhost/". 
The strange thing here is, that there is written "https" when I write "localhost:3000" into my browser. Anyways, I couldn't figure out, why I can't connect on my local machine via the mentioned input.

Does someone have any idea or any hint?
Thanks!

**Comment by Gargron** [comment]
Docker is configured for production use, so behind a HTTPS proxy like nginx. For development, please either use Rails directly, or use Vagrant, or a custom configuration for Docker.

**Comment by danhunsaker** [comment]
Or Nanobox, which handles dev vs prod seamlessly.

**Comment by marians** [comment]
... to be more explicit: In https://github.com/tootsuite/mastodon/blob/master/nanobox/nginx-local.conf there is a config that works well as a proxy in a local setup. I copied it nearly 1:1 to have a docker-compose setup working.

**Comment by Gargron** [comment]
Mastodon doesn't care which proxy it sits behind. So you can use Apache or Caddy or anything you want, but I can't personally help you with how to config Apache or Caddy.
