### ISSUE TITLE
Display square (and up to 1:1 ratio) medias without being cropped

### ISSUE THREAD

**Issue by nclm** [mastodon/mastodon#9582]
### Pitch

Currently, media attachments (both images and videos) that are higher than a ratio of what seems to be 16:9 get either cropped (images) or scaled down and letterboxed (videos) when shown in the interface. I think that maybe media up to 1:1 should be allowed to be displayed at their native sizes.

It could work like this:
1. Medias lower than 16:9 behave however they work now (I haven’t tried it, are they kept at their ratio or cropped to 16:9?).
2. Medias that are 16:9 obviously stay at 16:9.
3. Medias inbetween 16:9 and 1:1 (included) would now keep their ratio.
4. Medias higher than 1:1 do get cropped/scaled down to 16:9 exactly like they would now. I fully agree that we need at one point to limit the vertical space a toot can take.

Alternatively for number 3, instead of allowing all the variations, a set of common ratios (4:3, 1:1…) could be set, and the media  would be cropped/scaled to the closest.

### Motivation

1:1 ratio is quite common on social media, being used for graphics, illustrations — and also photography (see Instagram). Other social networks allows it so it might be expected by users that Mastodon would too. Additionally, the upcoming federation of Pixelfed might show the arrival of regular square pictures on the Fediverse, so for followers from Mastodon, not having to click on each pictures would be a more ideal experience.

4:3 can also appear from time to time, especially for screenshots and extracts from pre-mid-2000s media (TV shows, computer screens). In the landscape of social networks, Dribbble is notable for having it as its only ratio.

**Comment by Gargron** [comment]
The reason its always 16:9 in timelines is I want visual consistency between different posts. It also prevents tall images from taking up too much space.

**Comment by nclm** [comment]
Yes that I understand! The idea here is that when someone post something that is 1:1 or 4:3, it is often I think quite on purpose and expected to displayed in full. And they are both relatively common ratios to be maybe treated first class.

Everything else can get cropped down do 16:9 — I do entirely agree on limiting the tallness of toots, plus 1:1 is not _that_ tall. I also agree that consistency is important, but it can be “broken” from time to time at the off-chance someone post something precisely this size. I think the user experience would be improved by seeing these images at their size.

An example of use is the “factourism” account (thanks a lot for the retweet by the way!), which would look quite a lot better if everything was square (and the videos and images posts were the same size). I know it’s not the use of the average Mastodon account, but I do follow a lot of accounts on other social networks (mostly art related) that use only square posts, so there might be some on Mastodon too and as a follower I would prefer not having to click to display it all.

And if anything, there could be a “Limit height of posts” setting in the preferences.

**Comment by deutrino** [comment]
The cropping and enforced consistency is, to me, one of the worst misfeatures of the Mastodon web UI. It makes the majority of cropped images look like crap and necessitates the kludge of 'focal points.'

**Comment by zakwilson** [comment]
For instance admins, there's a setting for this affecting non-logged-in users in settings.yml.

I didn't find it with a web search and I'm hoping a comment about it will help someone. Some sort of default crop seems reasonable, but as a photographer, I find 16:9 a bizarre choice as it's rarely used in photography.

**Comment by bradanlane** [comment]
> 

having a display of 16:9 is consistent and works as long as images and video which are of a different aspect ratio are letterboxed. Currently, video with a 1:1 ratio are both squeezed and cropped making they unusable.

If 16:9 rendering is the design, then the current behavior appears to be a bug.

**Comment by mfb** [comment]
I found that vertical videos are cropped to fit in the 16x9 ratio, and then the play button becomes invisible, because it's down at the bottom of the video.  I can only start playback by clicking on the video and then hitting the space bar (which seems like a lot to ask for users to figure out).

**Comment by Gargron** [comment]
Images and videos are not cropped at all starting with Mastodon 4.2. Is the server you're on up to date @mfb?

**Comment by mfb** [comment]
So this was remote media being embedded from a third-party site. It looks like the third-party site was generating a `<video width="100%">` tag, which caused vertical videos to expand to the full width allotted by mastodon, thus being taller than the allotted height.   Found a quick-hack solution: The third-party site can generate a `<video height="100%">` tag for vertical videos.
