### ISSUE TITLE
Add  a "contains untagged/tagged media" text/label/message to the boost popup window.

### ISSUE THREAD

**Issue by spaceottercode** [mastodon/mastodon#9612]
### Pitch
 It occurred to me that a possible solution to issue #9530 might be to include somewhere in the popup that already exists when you boost a toot, the text (or something equivalent) "toot contains untagged media" or in the alternate case "toot contains tagged media". This provides a solution to #9530.

### Motivation

If you have your display settings set to show all media marked as sensitive it is easy to accidentally boost a toot with untagged media. This feature makes it easy to be a more responsible booster.

**Comment by trwnh** [comment]
I think a more sensible solution to this problem is to instead allow for tagging boosts. Responsibility is one thing, but different people will always have different expectations and different audiences. Being able to add metadata to boosts just like with regular posts would solve a host of other issues.

Related:
#2719 requested this but was deemed to be a duplicate of #309 (though I disagree)
#7860 more generally requests expanded confirmation dialogs / warnings

**Comment by spaceottercode** [comment]
For now, I would just like a message, label or other indicator added to the existing (boost) popup  (see initial post) because at face value it seems like the quickest & easiest approach to implement: low cost.

**Comment by crockwave** [comment]
I have a special use case, which is to monitor the Atom feed of a user account that is used exclusively for curating Mastodon feed content to a remote content aggregation site.  That aggregated content would be available as an RSS/Atom feed.  To make the Mastodon portion of that content richer, we would need a way to parse a useful Title value out of the Atom feed.  If the curating account boosted only toots that should be aggregated, and had the ability to edit a comment during the boosting process, the comment value would be parsed out of the Atom feed and used as a Title value in the aggregated RSS feed.  Currently, a boosted toot has a common title value of **curating_username shared a status by originating_username**.  If we had the ability to add metadata during a boost, such as a comment, then the resulting aggregated RSS feed title could look like **Saul makes a good point about such-and-so**
![image](https://user-images.githubusercontent.com/11214905/52246904-42ff6d80-28ad-11e9-9b94-1d9c017be8d6.png)

**Comment by spaceottercode** [comment]
This is an old request (2018). It may no longer be relevant. As author of this request, I am closing this request.
