### ISSUE TITLE
Cannot remove authorized followers from list on Firefox for Linux

### ISSUE THREAD

**Issue by testingwithfire** [mastodon/mastodon#9614]
### Expected result

I should be able to remove authorized followers from my account under any circumstances, even if I accept follows without approval. 

### Actual result

I'm running Firefox for Arch Linux (an up-to-date version) and I cannot remove authorized followers from one of my accounts. I get a several-page list but I can't check any of the boxes.

On my other account, which had only one instance with an authorized follower, I was able to check off that instance. That account is locked, though, so I have to approve followers. 

**The account on which I can't remove followers is NOT locked.** 

### Steps to reproduce
1. Log in to my account which allows unauthorized follows.
2. Open profile page
3. Navigate to authorized followers page, which contains several pages of results. A warning appears that my account is not locked
4. Try to check off any of the instances. Can't do it.

### Specifications
I don't know how to find the version of Mastodon that my instance is running on. 

See above for browser and O/S information.

**Comment by trwnh** [comment]
>The account on which I can't remove followers is NOT locked.

Removing followers for unlocked accounts has been disabled at some point. As the banner message says, "Lock your account to be able to review and reject followers."

**Comment by ClearlyClaire** [comment]
The relationship manager has been entirely redone since this issue and I don't think it requires a locked account anymore. Does the issue still occur?

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this issue can be reliably reproduced on an updated version please request that this issue be reopened or open a new issue. For either option please provide  updated logs/troubleshooting on a recent release investigate. Thank you.
