### ISSUE TITLE
unliking a post does not update like count

### ISSUE THREAD

**Issue by connyduck** [mastodon/mastodon#9638]
### Expected behaviour

when I unlike a post, the like count is updated as it is when liking a post

### Actual behaviour

The like count stays the same. Refreshing the page resolves the problem.
Does not happen everytime, but almost every time.

![video](https://user-images.githubusercontent.com/10157047/50457380-54269780-095b-11e9-97ac-01af69ff1956.gif)

### Steps to reproduce the problem

open the detail view of a toot, like it if it isn't already, unlike it

### Specifications

Happens on all instances I have accounts on, e.g. mastodon.social which is on 2.6.5 
Happens with both Tusky & web interface

**Comment by chuckyz** [comment]
I got curious so I looked it up; it looks like this gets queued up for later deletion in a redis key.

https://github.com/tootsuite/mastodon/blob/9311430ed7022e2e02fbd0b453adfc43356fdf9d/app/lib/activitypub/activity.rb#L120

Can you check some ~6 hours after unliking to see if the count goes down, or perhaps look under redis, specifically the (**do not run this in a production instance**) `KEYS delete_upon_arrival:*` command via redis-cli?

**Comment by nightpool** [comment]
@chuckx that's a completely different part of the code, and totally unrelated to this bug report, which is only about the front end (since it fixes itself after refreshing)

**Comment by trwnh** [comment]
cannot reproduce in latest versions
