### ISSUE TITLE
Highlight overflowing text in bio instead of forbidding extra characters

### ISSUE THREAD

**Issue by kit-ty-kate** [mastodon/mastodon#9679]
### Pitch

The idea is to be able to edit your bio, be able to copy/past or add text that is larger than the characters limit and shorten it afterwards instead of the current default which is to forbid any characters above the limit

### Motivation

when you are thinking of a bio that doesn't fit but you still want to be able to write it and see how to fit it into the limit it would be handy to actually be able to see the limit and write above the limit

**Comment by Cassolotl** [comment]
This seems connected to *Exaggerate excess sentence input #9726* - their styles could match, maybe?

**Comment by trwnh** [comment]
closing in favor of #9726 which covers both posts and profiles
