### ISSUE TITLE
Builtin language translation

### ISSUE THREAD

**Issue by MirceaKitsune** [mastodon/mastodon#9690]
I assume this discussion may already exist given it's a highly desired feature. I did a quick search on the Github database and couldn't find any recent issues about it. In case I'm mistaken, please mention any other tickets here and close this one if appropriate.

It would greatly help Mastodon users if the team could consider offering a builtin translation system. Nearly all social media platforms, including Facebook and Twitter, give users the ability to translate posts in other languages to a language they speak. This makes it possible for me daily to read and reply to posts in languages I don't understand... for instance following news about the Yellow Vests protests from people at the scene, written in French which I do not speak. As Mastodon lacks this feature the linguistic barrier poses a great problem; I often see posts in languages I don't know in the timeline, and have no way of following pages I may have enjoyed if I could understand what's being spoken. This will likely limit the growth and adoption of Mastodon and ActivityPub overall.

I assume a core obstacle is choosing which translation service(s) to use. The obvious choice would seem external tools like Google Translate, but for a project like Mastodon that could be a big mistake. First we're adding dependencies to third-party services, who could always shut us out or demand payment. It would also pose privacy concerns, given every translated post would have to be sent to Google.

The ideal solution is integrating open-source translation software, self-contained including all translation rules. Of course language translation is a complicated matter, and even Google Translate is just now becoming coherent. To my knowledge there's no software (especially written in Ruby) that you can just download and have it do everything GT does. Even if there was one, given the number of different languages and vocabulary rules, its databases would likely be Gigabytes in size. The solution may be a FOSS implementation which can rely on databases offered by other servers.

**Comment by foxmask** [comment]
may be a survey of the most accurate translator website will give an idea 
for example my english teacher recommends us deepl.com instead of google translate

**Comment by FediVideos** [comment]
Have had feedback through FediTips requesting this feature.

Many MANY people have asked for a "translate" button, especially during the recent influx of new users. I think a lot are dependent on this feature to use social media, it could help people switch to the Fediverse if it is available.

Some have suggested using LibreTranslate as a platform? https://libretranslate.com

**Comment by FediVideos** [comment]
Just heard that the app Fedilab has a built-in translation system for giving client-side translations, there is a web version of it at https://translate.fedilab.app

Is it possible to have something similar integrated into Mastodon's web client and/or official apps? This would seem to be what the original post is asking for?

**Comment by mirrorwolf** [comment]
_Any_ third party service is not okay IMO. Even if it's not Google, even if it's better than Google, shipping our posts off to some random third party is a huge violation of our privacy.

Firefox actually has an _offline_ translation extension now: https://addons.mozilla.org/en-US/firefox/addon/firefox-translations/ Perhaps we should be pointing people to that instead.

If you're going to have an autotranslate feature in Masto, it should be either offline or running on your Masto server (which of course already has the posts), not shipping them off elsewhere, to _anyone_.

**Comment by Lukas2112** [comment]
> _Any_ third party service is not okay IMO. Even if it's not Google, even if it's better than Google, shipping our posts off to some random third party is a huge violation of our privacy.
> 
> Firefox actually has an _offline_ translation extension now: https://addons.mozilla.org/en-US/firefox/addon/firefox-translations/ Perhaps we should be pointing people to that instead.
> 
> If you're going to have an autotranslate feature in Masto, it should be either offline or running on your Masto server (which of course already has the posts), not shipping them off elsewhere, to _anyone_.

A modular system could be used after all. 

1. Built-in translation
2. translation via e.g. self-hosted LibreTranslate instance

**Comment by smatthie** [comment]
Can it be done as an option, where the user can explicitly opt-in to one of a choice of translation services in their settings, but they are deactivated by default?

I agree with the issues of external services and data protection issue, but also that it would be an extremely useful service for many users. So perhaps giving people an individual choice is a good approach here?

For example, the instance admin can set up several translation services which are then shown to the user in their settings, and they can activate one if they want; if they don't activate any, then no data is sent to any service. This way the admin and the user individually can decide which service they trust.

The data protection issues are really very diverse. For public instances, where the posts are public anyway and are seen by Google bots, I don't really see why sending some to be translated adds much risk. But then there are other instances, for example those run by vulnerable groups, where this can be extremely dangerous. So rather than having a one size fits all, I suggest giving users the freedom to use what is best for them.

**Comment by smatthie** [comment]
> Firefox actually has an _offline_ translation extension now: https://addons.mozilla.org/en-US/firefox/addon/firefox-translations/ Perhaps we should be pointing people to that instead.

This is not a good suggestion. Firstly, people use different browsers. Secondly, it doesn't work with Mastodon: the Mozilla translation feature currently only the whole website, it is not (yet?) possible to highlight an individual post and have it translate only that. Even opening a single post in a separate Firefox Window doesn't work, as the language of the website is still set to the language of the mastodon instance, not to the language of the individual post, so the translator doesn't recognise it.

**Comment by Tc-001** [comment]
> shipping our posts off to some random third party is a huge violation of our privacy.

Is it? Mastadon is built on allowing "some random third pary service"s (aka other instances) access to user's posts. And if the translation request is proxied through mastodon's servers then any service you use cannot access any more information than other instances following your account already can.

**Comment by codl** [comment]
Link dump ahead about some permissively-licensed offline translation libraries and models:
* [Firefox Translations](https://github.com/mozilla/firefox-translations)/[Bergamot](https://browser.mt/), mentioned upthread, based on [Marian NMT](https://marian-nmt.github.io/).  [Models here](https://github.com/mozilla/firefox-translations-models/tree/main/models/prod), very few language pairs and they are all from or to English, which means you are out of luck if you want to translate, say, from Spanish to Portuguese. Though the intended use case is a browser extension, it can also be made to **[run standalone and offline in a web-page](https://github.com/mozilla/translate)**, which would be ideal for Mastodon. No ruby bindings.
* The University of Helsinky's Language Technology Research Group has trained an impressive amount of models [\[1\]](https://github.com/Helsinki-NLP/Opus-MT-train/tree/master/models)[\[2\]](https://github.com/Helsinki-NLP/Tatoeba-Challenge/tree/master/models) including many **between languages that aren't English**! These are for their own OPUS-MT, which is based on Marian NMT, but I have no idea how much glue would be required for these models to run in the browser with Firefox Translations. I also don't know how good the translations are. OPUS-MT itself does not run in the browser and does not have ruby bindings.
* [Argos Translate](https://www.argosopentech.com/), which powers LibreTranslate, mentioned upthread. [Models here](https://www.argosopentech.com/argospm/index/), all from/to English. Does not run in-browser, no ruby bindings.
* [Apache Joshua](https://cwiki.apache.org/confluence/display/JOSHUA/), has been retired. [Models here](https://cwiki.apache.org/confluence/display/JOSHUA/Language+Packs), all from/to English. Does not run in-browser, no ruby bindings.
* [Stanford Phrasal](https://nlp.stanford.edu/phrasal/), no pre-trained models included. Doesn't run in-browser, no ruby bindings.
* I could not actually find *any* offline machine translation libraries/bindings for ruby.

**Comment by Openmedianetwork** [comment]
This is worth thinking about, though best not to go down the #dotcons root.

**Comment by Gargron** [comment]
Added in #19218

**Comment by aliprofi** [comment]
К сожалению почни ни один клиент Mastadont не поддерживает перевод постов, а тот единственный, что поддерживает, не может найти нужный мне сервер. Замкнутый круг!
