### ISSUE TITLE
Single-page apps using the API have to store the client secret in their code

### ISSUE THREAD

**Issue by maxf** [mastodon/mastodon#9707]
Mastodon's API only supports OAuth's Authorization code flow and the Password grant flow.

In both cases the API client needs to send the client_secret. In the case of a single-page app, this is a problem as it means that the client_secret has to be stored in the code that's sent to the user's browser.

Alternative flows could be offered, either the Implicit Flow or a Proof Key for Code Exchange ([RFC7636](https://tools.ietf.org/html/rfc7636))

**Comment by nightpool** [comment]
This isn't unique to single page apps, any native client would also have to
store a client_secret. Since implementing a mastodon app already requires
generating clients programmatically for each server you want to connect to,
most native and single page apps don't run into this problem—they generate
clients programmatically when connecting to a server, which means clients
are never shared between users.

**Comment by maxf** [comment]
@nightpool, so you're saying that the API client is in fact the user's browser, and not where my SPA is hosted?

That's fine, although it bothers me a bit: loading SPAs in your browser isn't the same as installing an app, somehow. Even though you can store the id/client pairs, you would still need to re-request them  more often, if you change browsers or you're in incognito mode, or if you clear your local storage or whatever.

But maybe mastodon servers are ok with that and they're happy to deliver id/secret pairs every time someone loads my SPA in their browser. Is that the intent?

**Comment by dellagustin** [comment]
I know this is and old issue, but it is related to a question I have regarding the best practice for client apps registering themselves to mastodon instances for API consumption through the [apps API](https://docs.joinmastodon.org/methods/apps/)

@maxf when you say Single Page App (SPA), are you referring to an app where the Mastodon API will be consumed directly by the Web App (i.e. the browser will fire the requests to a Mastodon instance directly) or to an app where the API consumption would be through a server that is a counterpart to the SPA?

In my case it is a client side only app, no server, so I imagine I'll need to create one application (using /api/v1/apps) for each "instalation" of my app, and store the client_id and client_secret on each installation as well. At least that is the only way I could imagine it.

I would have a procedural generation for `client_name` (e.g. `<my app name>-<random string>`) to avoid collision.

Is there any guide out there that corroborates with my understanding for this use case?

**Comment by Gargron** [comment]
Client name does not need to be unique, it needs to be human-readable. Do not add random strings to it.

Yes, you are correct. Register each installation, store secret in the client.

**Comment by maxf** [comment]
@dellagustin : the former, like you.
@Gargron : thanks for clarifying
