### ISSUE TITLE
As a user, when I remove a user from a list, I want their toots from the list to also be removed

### ISSUE THREAD

**Issue by ldexterldesign** [mastodon/mastodon#9777]
Hi all,

Thanks for software

Hope you're well

As a user[r], when I remove a user from a list, I want their toots from the list to also be removed #Bug #Question

When I unfollow a user my "Home" column/feed removes toots from that user. I think the "List" columns/feeds should exhibit the same behaviour.

NB I'm unsure if this is a bug or feature but for me it's a bug because I can't think of a reason why I'd want to see content from a user I don't want in my list(s)

If documentation exists then feel free to link me or else can something on this topic be added to the documentation?

If you're reading and:

a) agree, then please up-vote and/or reply +1, or;
b) disagree, then I'd love to know why?

If you have any issues (e.g. questions/queries) happy to help

Hope this helps and to hear back!

Keep up great work!

Cheers

[r]
hardware: Apple, MacBook Pro (Retina, 15-inch, Mid 2014)
software - operating system: Apple, macOS, 10.14.2 (18C54)
software - application: Vivaldi, 2.2.1388.37 (Stable channel) (64-bit)

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
BUMP

**Comment by trwnh** [comment]
Related to #16290 and #13687

**Comment by trwnh** [comment]
Closing in favor of #13687
