### ISSUE TITLE
Confidential hosting

### ISSUE THREAD

**Issue by storm1er** [mastodon/mastodon#9785]
### Pitch

Is there any option so any anonymous users can't access anything within the instance?

The simple solution here is to have an option that will redirect any non-connected users to the homepage or the login-page (with auto-redirect eventually?) when they try to access pages out of scope.
(every page that contains toots)

### Motivation

We are trying to use Mastodon as a workplace social network,
I thought I could be great, but then I realized that as soon as you know some URL, you can access every "public" data. And toots can contain sensitive data that not meant to be public.

**Comment by trwnh** [comment]
Yes, you could redirect all unauthenticated requests to a login page. Some private unfederated instances do this.

**Comment by storm1er** [comment]
The question is how ? ^^'

**Comment by MirceaKitsune** [comment]
I wonder how much sense having this ability makes, though I can see some use in it. My primary issue would be that this breaks federation and being able to see user's posts from other instances, which is the primary strong point of Mastodon and ActivityPub as a whole. If you want posts to be confidential for now, you can ask users to make them Followers Only rather than Public.

**Comment by trwnh** [comment]
@MirceaKitsune I don't think "breaks federation" in itself is a worthwhile critique when it comes to matters of privacy. This is similar/related to the discussion for "local only" posts (#861 / #8427), but targeted at the public post pages. It is a valid use case for an organization to want to host their own internal communications infrastructure.

**Comment by Gargron** [comment]
This is exactly how counter.social originally defederated by accident.

**Comment by blind-coder** [comment]
Federation may be desirable for the fediverse at large, but there will always be cases where you want an isolated instance, be it for a company-internal network, a family-internal network or communities that simply don't want to share their content with you.

And the argument "it's bad for federation" does not hold any water here. It's not the place of the software to tell me who I want to share my data with.

**Comment by MirceaKitsune** [comment]
Might it be better to instead support optional instance whitelisting for federation? If this feature is enabled but no whitelist is used, the server won't federate with any other server... but if you have other departments you wish to share with, you can instead choose to federate only with those. It achieves the desired functionality while also letting you add exceptions.

Separately the instance can have a flag that causes posts to only be locally visible to connected users.

**Comment by blind-coder** [comment]
As an example:
Right now, we use an instance for a closed user group. No registrations allowed, authentication against LDAP where only family members get created.
We post pictures of our children there for the rest of the family to see.
Right now, anyone knowing our instance domain name and a username can access our.mastodon.instance/@username and access our toots and pictures.

*We absolutely do not want that!*

By extension, we also do not want people from other instances following us. We do not want our instance to federate with other instances.

To clarify my point with a hyperbole: If I wanted ANYONE ELSE but my family to view ANYTHING on our instance, I could just use Twitter instead.

**Comment by blind-coder** [comment]
@MirceaKitsune
It's not just federation, but remote follow as well. RSS/Atom feeds. Profile views. Being private doesn't stop at not publishing directly to other instances.

**Comment by storm1er** [comment]
Hi guys,

Bumping as I'm starting to hesitate to close our mastodon if I'm not getting any help through his community :( 

I'm stuck with ruby and mastodon's API restriction. How did @trwnh found out how those private federations had done that?

**Comment by blind-coder** [comment]
@storm1er 
For me, I have shut down my Mastodon instance again. From the discussion here as well as there https://discourse.joinmastodon.org/t/completely-private-instance/1574/5 it has become obvious to me that the mastodon developers do NOT care about privacy in the least. Their priority is "everything must be federated, and everything must be visible to everyone else, no matter what".

That being said, I managed to at least somewhat hide my instance when it was still live, by doing the following:
Put Mastodon behind a reverse proxy.
Block access to some URLs:
```apache
        RewriteEngine on
        RewriteRule ^/@ [F]
        RewriteRule ^/users/ [F]

        RewriteCond expr "! %{REQUEST_URI} -strmatch '/.well-known/acme-challenge*'"
        RewriteRule ^/.well-known [F]

```

I also applied the following patch so that only authenticated users can access anything on the server:

```diff
diff --git a/app/controllers/api/base_controller.rb b/app/controllers/api/base_controller.rb
index ac8de5fc0..db9d5480a 100644
--- a/app/controllers/api/base_controller.rb
+++ b/app/controllers/api/base_controller.rb
@@ -6,6 +6,8 @@ class Api::BaseController < ApplicationController
 
   include RateLimitHeaders
 
+  before_action :require_user_maybe!
+
   skip_before_action :store_current_location
   skip_before_action :check_user_permissions
 
@@ -77,6 +79,18 @@ class Api::BaseController < ApplicationController
     end
   end
 
+  def require_user_maybe!
+    if "#{request.original_fullpath}" != "/api/v1/apps"
+      if current_user && !current_user.disabled?
+        set_user_activity
+      elsif current_user
+        render json: { error: 'Your login is currently disabled' }, status: 403
+      else
+        render json: { error: 'This method "'"#{request.original_fullpath}"'" requires an authenticated user' }, status: 422
+      end
+    end
+  end
+
   def render_empty
     render json: {}, status: 200
   end
diff --git a/app/controllers/well_known/webfinger_controller.rb b/app/controllers/well_known/webfinger_controller.rb
index 28654b61d..039801f5d 100644
--- a/app/controllers/well_known/webfinger_controller.rb
+++ b/app/controllers/well_known/webfinger_controller.rb
@@ -19,7 +19,7 @@ module WellKnown
         end
       end
 
-      expires_in(3.days, public: true)
+      #expires_in(3.days, public: true)
     rescue ActiveRecord::RecordNotFound
       head 404
     end

```

**Comment by Laurelai** [comment]
Since nobody wanted to help you who actually codes for this thing I will. I cant give you a mastodon software solution however.

Since this is only for your family this should be easy enough to do via the firewall.

iptables -A INPUT -p tcp --dport 80 -s 1.2.3.4 -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -j DROP


Make an accept rule for each IP address of your family members.

**Comment by blind-coder** [comment]
@Laurelai 
I appreciate the idea, but it's not quite helping. At least over here, people don't have static IP addresses. Not on the local WiFi, nor on the wider internet.

**Comment by Laurelai** [comment]
Since you have a server would you be able to set up a VPN on it? They could login to the VPN then use the VPN ip as the whitelisted access.

**Comment by blind-coder** [comment]
I could, but tech-savvyness of family is nowhere near that level. Readiness to learn stops at "has to install another app on phone" as well.

**Comment by Laurelai** [comment]
Perhaps you can protect your instance with a password via [nginx's htaccess ](https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-nginx-on-ubuntu-14-04)

**Comment by coreyreichle** [comment]
For an internal-only instance, for a corporate environment, firewalling off the instance is likely the easiest, and most maintainable solution.

**Comment by augray** [comment]
FWIW, I'm in the same boat as @blind-coder : set up an instance for my family with the intention of it being a "private twitter" for pictures of kids. Before I did this, I looked into whether Mastodon was fit for this use case. The existence of profile settings that allow restricting who can follow you and then setting post-privacy to "followers only" said to me that it should be possible to make posts that were completely shielded from the outside world. But much to my dismay I just discovered that even with these settings, the appropriate URLs will allow you to see pretty much anything. If nothing else, those configuration settings are VERY misleading.

**Comment by nightpool** [comment]
private posts are absolutely not visible "if you know the appropriate
URLs".

but we don't recommend using mastodon for a non-federated system. it's
contrary to the core guiding principles of the project and we won't offer
any support for it.

**Comment by blind-coder** [comment]
> but we don't recommend using mastodon for a non-federated system. it's contrary to the core guiding principles of the project and we can't really offer much any support for it.

So, basically, you don't care about privacy of your users, got it.

**Comment by augray** [comment]
> private posts are absolutely not visible "if you know the appropriate URLs".

In that case, I have found a bug, because I have an account set to post privacy of "followers only" whose posts are visible if you visit myinstance.com/@username.

> but we don't recommend using mastodon for a non-federated system. it's contrary to the core guiding principles of the project and we can't really offer much any support for it.

In that case, I'll sadly have to find another solution. It was working great for us otherwise.

**Comment by nightpool** [comment]
are you visiting it when you're logged in or when you're logged out?

**Comment by augray** [comment]
Logged out. I've since applied the changes suggested by @blind-coder, and thus can't reproduce at the moment. I'm in the process of getting what I need from the server before shutting down. I've also manually updated the DB for the time being and set all statuses to "follower only" visibility. That seems to have worked, so it's possible either (a) there is/was a bug where the config for post privacy wasn't propagating to the posts or (b) user error on my part, and the setting wasn't always set to "follower only" as I thought it was.

**Comment by nightpool** [comment]
my guess is that tootodon isn't respecting your default post privacy
settings and is instead defaulting to creating public posts. I'm guessing
that's a bug in the app

**Comment by augray** [comment]
Unless the defaults are meant to be used server-side (i.e. if the webpage/app doesn't specify post privacy to the server, use the default). I'm not familiar enough with the mastodon API to know what the intent is.

**Comment by nightpool** [comment]
the defaults are used server side, but I'm guessing most apps set their own
default instead of leaving it to the server to handle, which is a bug in
and of itself

**Comment by TheNomad11** [comment]
How can I apply this patch? I am no coder. I'd like to use Mastodon in my foreign language classes and it has to be private

> @storm1er
> For me, I have shut down my Mastodon instance again. From the discussion here as well as there https://discourse.joinmastodon.org/t/completely-private-instance/1574/5 it has become obvious to me that the mastodon developers do NOT care about privacy in the least. Their priority is "everything must be federated, and everything must be visible to everyone else, no matter what".
> 
> That being said, I managed to at least somewhat hide my instance when it was still live, by doing the following:
> Put Mastodon behind a reverse proxy.
> Block access to some URLs:
> 
> ```apache-config
>         RewriteEngine on
>         RewriteRule ^/@ [F]
>         RewriteRule ^/users/ [F]
> 
>         RewriteCond expr "! %{REQUEST_URI} -strmatch '/.well-known/acme-challenge*'"
>         RewriteRule ^/.well-known [F]
> ```
> 
> I also applied the following patch so that only authenticated users can access anything on the server:
> 
> ```diff
> diff --git a/app/controllers/api/base_controller.rb b/app/controllers/api/base_controller.rb
> index ac8de5fc0..db9d5480a 100644
> --- a/app/controllers/api/base_controller.rb
> +++ b/app/controllers/api/base_controller.rb
> @@ -6,6 +6,8 @@ class Api::BaseController < ApplicationController
>  
>    include RateLimitHeaders
>  
> +  before_action :require_user_maybe!
> +
>    skip_before_action :store_current_location
>    skip_before_action :check_user_permissions
>  
> @@ -77,6 +79,18 @@ class Api::BaseController < ApplicationController
>      end
>    end
>  
> +  def require_user_maybe!
> +    if "#{request.original_fullpath}" != "/api/v1/apps"
> +      if current_user && !current_user.disabled?
> +        set_user_activity
> +      elsif current_user
> +        render json: { error: 'Your login is currently disabled' }, status: 403
> +      else
> +        render json: { error: 'This method "'"#{request.original_fullpath}"'" requires an authenticated user' }, status: 422
> +      end
> +    end
> +  end
> +
>    def render_empty
>      render json: {}, status: 200
>    end
> diff --git a/app/controllers/well_known/webfinger_controller.rb b/app/controllers/well_known/webfinger_controller.rb
> index 28654b61d..039801f5d 100644
> --- a/app/controllers/well_known/webfinger_controller.rb
> +++ b/app/controllers/well_known/webfinger_controller.rb
> @@ -19,7 +19,7 @@ module WellKnown
>          end
>        end
>  
> -      expires_in(3.days, public: true)
> +      #expires_in(3.days, public: true)
>      rescue ActiveRecord::RecordNotFound
>        head 404
>      end
> ```

**Comment by Gargron** [comment]
In version 3.0 you still have "whitelist mode" available for this purpose @thenomad11. No code changes necessary.
