### ISSUE TITLE
Hide "new toot" button on search column

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon#9795]
"New toot" button on search column is useless and it covers "follow suggestion" UI
Hiding that button on search column would be better.

![screen shot 2019-01-13 at 14 09 01](https://user-images.githubusercontent.com/5047683/51081833-dcb77d00-173c-11e9-9204-2d3d966446cf.png)

**Comment by MirceaKitsune** [comment]
I don't know how to get that panel. Is this from the mastodon.social web interface, and not from mobile or other app? I'm looking at mine from Firefox on my desktop computer.

**Comment by MirceaKitsune** [comment]
I see. I tried shrinking my window but nothing changes for me. In any case, from what I see in the screenshot, I agree that button seems useless and especially does not belong in the search results.

**Comment by tmm576** [comment]
PR #9826 opened. I also removed it from `/getting-started`:
![image](https://user-images.githubusercontent.com/19373066/51289588-c6285480-19ce-11e9-8c77-3b19c6c04720.png)
as that seemed to be along the same lines to me. There may be other pages too that I'm not aware of yet, so let me know what you think.

**Comment by ilias-t** [comment]
I believe this issue is resolved and can now be closed
