### ISSUE TITLE
Processing for own moderation report

### ISSUE THREAD

**Issue by mayaeh** [mastodon/mastodon#9846]
### Actual behaviour

A moderation report for me also has an action button in WebUI report page, which can be pushed.
However, pressing it will generate an error.

At this time, it is output to the error log of the server as follows.
https://gist.github.com/mayaeh/d3743ab4adb342e73ee88faba93987c2

I think that it is necessary to prevent processing of own moderation report.
Or, like the account page, I think that it is necessary not to display the button to Staff.
However, I think that we may want to take action such as warning for Staff as well.

### Steps to reproduce the problem

1. Send reports from other accounts to Admin or Moderator.
2. Open that report with the reported account.
3. Press one of the WARN or SILENCE buttons and press PERFORM ACTION button.

<img width="600" alt="2019-01-18 10 53 53" src="https://user-images.githubusercontent.com/766076/51366375-8e352480-1b28-11e9-8f06-8595974b13bd.png">
<img width="600" alt="2019-01-18 10 54 04" src="https://user-images.githubusercontent.com/766076/51366378-91301500-1b28-11e9-823a-854470873755.png">
<img width="600" alt="2019-01-18 10 54 13" src="https://user-images.githubusercontent.com/766076/51366380-92f9d880-1b28-11e9-931e-22f618f733b6.png">

### Specifications

Equivalent to Mastodon master 69f782b54d035789a6386ed979940dd9719af1a1.

**Comment by vmstan** [comment]
This issue was filed against a now unsupported version of Mastodon. In an effort to clean up stale bugs, if this issue can be reliably reproduced on an updated version please request that this issue be reopened or open a new issue. For either option please provide updated logs/troubleshooting on a recent release. Thank you.
