### ISSUE TITLE
Enable to use emoji from smartphone

### ISSUE THREAD

**Issue by japaslu** [mastodon/mastodon#9881]
### Motivation

There were voices saying it was hard to use from users.

### Pitch

In the present situation, it is hidden with the keyboard from smartphone, it is hard to use.

This is the description video
https://twitchain.net/@QuQ/101443384640340620

**Comment by hadsn** [comment]
I think such problem is "おま環 (environmental depending)" issue. I couldn't reproduce it on my Galaxy Note8 with S Browser 8.2.01.2 and ATOK.
You should note which smartphone, browser and keyboard app occur the problem on.

And it is difficult for non-Japanese speaker to understand this issue only with the video.
You should note that "In composing Toot when you tap Emoji button, keyboard app hides Emoji pannel and browser zooms to text box in Emoji pannel. It makes hard to use Emoji on %THE_TERMINAL% with &BROWSER&."

**Comment by mayaeh** [comment]
It seems that there is no problem in my environment (iPhone X and Essential Phone).
However behavior on iPhone X seems to be a bit strange.

Click [here](https://taruntarun.net/media_files/Mastodon/media_attachments/files/000/313/098/original/a96d90cbedd78173.qt) for videos on iOS (iPhone X, iOS 12.1.2 Mobile Safari)

Click [here](https://taruntarun.net/media_files/Mastodon/media_attachments/files/000/313/096/original/1922d861676e447e.mp4) for videos on Android (Essential Phone, Android 9 Chrome)

**Comment by japaslu** [comment]
Thanks for the postscript,hadsn.
Should I remake issue?
And just now, I am asking questions [his](https://twitchain.net/@QuQ) environment.

**Comment by hadsn** [comment]
> Should I remake issue?
I think so too.
This issue should be titled as "Emoji pad runs strange on iPhoneX with Safari"

We can avoid this problem with some plan.
(Close keyboard and pinch out good place ;-)
But it is inconvenient for beginners.
