### ISSUE TITLE
status data (obtained by api ) hasn't `pinned` attribue

### ISSUE THREAD

**Issue by shuiRong** [mastodon/mastodon#9926]
Mastodon version: 2.7.0

![image](https://user-images.githubusercontent.com/16076993/51799808-25088c00-2261-11e9-9053-1551e5db0002.png)

sample: https://cmx.im/web/accounts/75326

**Comment by Gargron** [comment]
The API request was authenticated, and the toots belong to the authenticated user?

**Comment by shuiRong** [comment]
> The API request was authenticated, and the toots belong to the authenticated user?

Yes, the status data obtained by an reques means that the API request was authenticated correctly.

And I shouldn't take this link `https://cmx.im/web/accounts/75326` as a sample, just forget it.
