### ISSUE TITLE
Tootctl generate a one time password for a user

### ISSUE THREAD

**Issue by s5bug** [mastodon/mastodon#9931]
### Pitch

One time passwords for a user account generated by tootctl

### Motivation

My email setup doesn't work and I tried to change the credentials of a user who asked and a password reset wasn't sent. A system to generate OTPs would allow for a way to do this if your email system doesn't work (like mine).

**Comment by Gargron** [comment]
This is about existing accounts, right? Because accounts created with tootctl already receive a random password

**Comment by sorenbug** [comment]
Yes.

**Comment by kdmiller45** [comment]
how did you issue the one time password or how can you reset a password not working that was issued with tootctl

**Comment by mjankowski** [comment]
Closing on assumption that the `--reset-password` option to tootctl handles this -- please reopen and clarify if not?

**Comment by s5bug** [comment]
I haven't used Mastodon in years, but I'll keep watch on this issue, as if someone else confirms it doesn't work, I don't think they will have the permissions to reopen.
