### ISSUE TITLE
Translation accuracy

### ISSUE THREAD

**Issue by kasinjsh** [mastodon/mastodon#9955]
I'm planing to translate Mastodon to Latvian but I'm facing issues whit translation. In our language toot translates as "taurēt" and that word is understood in a way that someone is nuts, crazy, lost his mind. As My idea is to publish translation in Git to share whit others is it OK that some terminology is different? My idea is to call toot just publish, keep it simple.

**Comment by trwnh** [comment]
IMO I think you can feel free to localize "toot" however you see fit? For example, the French translation uses "pouet", which is kind of like "squeak" or "fart". The Arabic translation chose a word more similar to "fanfares", as in tooting a horn. The word "publish" is fine, but if there's a more playful interpretation into Latvian, then you can use that instead.
