### ISSUE TITLE
Direct Messages pane does not show second-to-last message 

### ISSUE THREAD

**Issue by Chaos99** [mastodon/mastodon#9961]
### Expected behavior

With the 'direct messages' pane open, I should see all my latest direct messages. Even if they are grouped by discussion, all of the messages (I sent) should be visible in the thread once I click on one of those discussions.

### Actual behavior

Clicking on one of the conversations (symbolized by the last message in that discussion in the direct messages pane) reveals the thread, but only shows the original message (to me, to which I replied) and the last message I wrote. Previous messages (from me, replying to the original toot) are not shown.

Opening the thread from the normal home pane by clicking on the original message will show all messages.

### Steps to reproduce the problem

1. Reply to a toot.
2. make sure privacy status is set to 'Direct'
3. write message and press 'Toot'
4. reply again to the same toot
5. write another direct message and press 'toot'
6. open direct messaging pane (e.g. from the 'getting started' pane)
7. see only the second message in the list
8. click that message to open the thread, still see only the original toot and the 2nd reply
9. (optional) Click on the original toot in the local timeline.
10. (optional) See both replies here

### Specifications

Not sure. Release tag v2.6.5 on Mastodon.technology 

Chrome 71.0.3578.98 (64bit) on Windows7

**Comment by trwnh** [comment]
i think separate conversations are now created for separate subthreads
