### ISSUE TITLE
The API ActivityPub for communicate with another site no mastodon

### ISSUE THREAD

**Issue by PierreGbx** [mastodon/mastodon#9987]
Hello i like to communicate with mastodon since another site no mastodon but i don't see the documentation for activity Pub mastodon ! 
Thanks  for your answer beforehand ! 
Have a good day !

**Comment by Gargron** [comment]
https://docs.joinmastodon.org/development/activitypub/

**Comment by PierreGbx** [comment]
is there a way to see all endpoints made avalable by mastodon to be compliant activity pub ?
because , I guess if we produce the same endpoints our plateforms will then be AP connectable , am i right ? but I found the mastodon api endpoints and played with a client 
but it's not using AP compliant api 
https://docs.joinmastodon.org/api/rest/follow-requests/
ex : POST /api/v1/follow_requests/:id/authorize 
how can I see it from this Accept | Follow as AP formatted response , what's the endpoints request ?
am I doing something wrong ?
https://mamot.fr/api/v1/streaming/user and i have this message:
error | "Error: Missing access token"

I'd like to do the same but with a AP api , am i on the right track ? 
are there any easy steps to follow  to get our api compliant ? 
FYI, I'm young dev intern trying to connect communecter.org a societal network with mastodon and the fediverse 
thanks for your help 
do you speak french ?
